# -*- coding: utf-8 -*-
# Dział 4 – Rynek finansowy, kapitałowy i ubezpieczenia (pytania ręczne)
M = [
 (4, "s", "Obligacja zerokuponowa o wartości nominalnej 1000 zł zostanie wykupiona za 2 lata. Wymagana stopa zwrotu wynosi 5%. Jej cena teoretyczna to około:",
  ["900,00 zł", "907,03 zł", "952,38 zł", "1102,50 zł"], "B",
  "P = 1000 / (1,05)² = 1000 / 1,1025 ≈ 907,03 zł. Różnica między ceną a nominałem to dyskonto – jedyne źródło dochodu z obligacji zerokuponowej."),
 (4, "s", "Gdy rynkowe stopy procentowe rosną, ceny obligacji o stałym oprocentowaniu:",
  ["rosną", "spadają", "nie zmieniają się", "rosną tylko dla obligacji długoterminowych"], "B",
  "Cena obligacji to zdyskontowane przepływy – wyższa stopa dyskontowa obniża cenę. Najsilniej reagują obligacje o długim czasie trwania (duration)."),
 (4, "s", "Lokata 10 000 zł na 2 lata z oprocentowaniem 6% rocznie i kapitalizacją kwartalną. Wartość przyszła (bez podatku) wynosi około:",
  ["11 200 zł", "11 236 zł", "11 265 zł", "11 272 zł"], "C",
  "FV = 10 000 · (1 + 0,06/4)^8 = 10 000 · 1,015^8 ≈ 11 264,93 zł. Przy kapitalizacji rocznej byłoby 11 236 zł, przy prostym oprocentowaniu – 11 200 zł; częstsza kapitalizacja zwiększa wartość."),
 (4, "s", "Efektywna roczna stopa procentowa przy nominalnej 12% i kapitalizacji miesięcznej wynosi około:",
  ["12,00%", "12,36%", "12,68%", "13,00%"], "C",
  "r_ef = (1 + 0,12/12)^12 − 1 = 1,01^12 − 1 ≈ 12,68%. Przy kapitalizacji półrocznej: 12,36%."),
 (4, "s", "Akcja spółki kosztuje 80 zł, a zysk na akcję wynosi 5 zł. Wskaźnik cena/zysk (P/E) wynosi:",
  ["0,0625", "16", "75", "400"], "B",
  "P/E = 80 / 5 = 16 – inwestorzy płacą 16 zł za każdą złotówkę rocznego zysku. Odwrotność (E/P = 6,25%) to stopa zysku."),
 (4, "s", "Współczynnik beta akcji wynosi 1,5, stopa wolna od ryzyka 4%, a oczekiwana stopa zwrotu z portfela rynkowego 10%. Według modelu CAPM wymagana stopa zwrotu z akcji to:",
  ["10%", "13%", "15%", "19%"], "B",
  "E(R) = Rf + β · (Rm − Rf) = 4% + 1,5 · 6% = 13%. Beta > 1 – akcja bardziej wrażliwa na wahania rynku niż przeciętnie."),
 (4, "m", "Które ryzyka można ograniczyć przez dywersyfikację portfela akcji?",
  ["Ryzyko specyficzne pojedynczej spółki", "Ryzyko systematyczne (rynkowe)", "Ryzyko upadłości jednej branży", "Ryzyko recesji w całej gospodarce"], "AC",
  "Dywersyfikacja eliminuje ryzyko niesystematyczne (specyficzne dla spółki lub branży). Ryzyko systematyczne (recesja, stopy procentowe) dotyczy całego rynku – mierzy je beta i nie da się go zdywersyfikować."),
 (4, "s", "Inwestor kupił opcję kupna (call) na akcję z ceną wykonania 100 zł, płacąc premię 5 zł. W dniu wygaśnięcia akcja kosztuje 112 zł. Zysk netto na jednej opcji wynosi:",
  ["7 zł", "12 zł", "17 zł", "−5 zł"], "A",
  "Wartość wewnętrzna = 112 − 100 = 12 zł; zysk netto = 12 − 5 = 7 zł. Gdyby akcja kosztowała ≤ 100 zł, opcja wygasłaby bez wartości, a strata ograniczyłaby się do premii 5 zł."),
 (4, "m", "Które cechy dotyczą kontraktów terminowych futures?",
  ["Są standaryzowane i notowane na giełdzie", "Obie strony mają obowiązek wykonania kontraktu", "Kupujący płaci premię, a sprzedający ma prawo, nie obowiązek", "Rozliczenie codzienne z depozytem zabezpieczającym (mark-to-market)"], "ABD",
  "Futures: standaryzowany instrument giełdowy, zobowiązanie obu stron, depozyt zabezpieczający i codzienne rozliczanie. Premię płaci nabywca opcji, a prawo bez obowiązku ma nabywca (nie wystawca) opcji."),
 (4, "s", "Hipoteza efektywności rynku w wersji półsilnej mówi, że:",
  ["ceny odzwierciedlają tylko informacje o przeszłych cenach", "ceny odzwierciedlają wszystkie publicznie dostępne informacje, więc analiza fundamentalna nie da trwałej przewagi", "ceny odzwierciedlają także informacje poufne", "rynek zawsze przecenia akcje"], "B",
  "E. Fama: forma słaba – ceny zawierają informacje historyczne (analiza techniczna nieskuteczna); półsilna – wszystkie informacje publiczne; silna – także poufne."),
 (4, "m", "Które papiery wartościowe są instrumentami rynku pieniężnego (do 1 roku)?",
  ["Bony skarbowe", "Bony pieniężne NBP", "Obligacje 10-letnie", "Certyfikaty depozytowe o terminie 6 miesięcy"], "ABD",
  "Rynek pieniężny obejmuje instrumenty krótkoterminowe: bony skarbowe i pieniężne, certyfikaty depozytowe, weksle, lokaty międzybankowe. Obligacje 10-letnie należą do rynku kapitałowego."),
 (4, "s", "Na GPW w Warszawie indeks WIG20 obejmuje:",
  ["20 najbardziej płynnych i największych spółek z rynku głównego", "wszystkie spółki rynku głównego", "20 spółek z rynku NewConnect", "20 największych banków"], "A",
  "WIG20 – indeks 20 największych i najpłynniejszych spółek (cenowy, od 1994 r.); WIG – indeks wszystkich spółek rynku głównego spełniających kryteria (dochodowy, od 1991 r.); NewConnect ma indeks NCIndex."),
 (4, "s", "Instytucja nadzorująca w Polsce rynek bankowy, kapitałowy, ubezpieczeniowy i emerytalny to:",
  ["NBP", "Komisja Nadzoru Finansowego", "UOKiK", "Ministerstwo Finansów"], "B",
  "KNF (od 2006 r., zintegrowany nadzór od 2008 r.) nadzoruje banki, rynek kapitałowy, ubezpieczenia, fundusze emerytalne, SKOK-i, instytucje płatnicze. UOKiK chroni konsumentów i konkurencję."),
 (4, "m", "Które cechy ma akcja zwykła?",
  ["Daje prawo głosu na walnym zgromadzeniu", "Daje prawo do dywidendy, jeśli walne zgromadzenie postanowi o jej wypłacie", "Gwarantuje stałe oprocentowanie", "Podlega zwrotowi nominału w terminie wykupu"], "AB",
  "Akcja to papier udziałowy: prawa korporacyjne (głos) i majątkowe (dywidenda, udział w majątku likwidacyjnym, prawo poboru). Stałe oprocentowanie i wykup w terminie to cechy obligacji (papieru dłużnego)."),
 (4, "s", "Ubezpieczenie OC posiadaczy pojazdów mechanicznych w Polsce jest ubezpieczeniem:",
  ["dobrowolnym majątkowym", "obowiązkowym majątkowym (odpowiedzialności cywilnej)", "osobowym na życie", "społecznym zarządzanym przez ZUS"], "B",
  "OC komunikacyjne, OC rolników i budynków rolniczych to ubezpieczenia obowiązkowe (dział II – majątkowe). AC, NNW to ubezpieczenia dobrowolne; ubezpieczenia społeczne to odrębny system publiczny."),
 (4, "s", "Udział własny i franszyza w umowie ubezpieczenia służą przede wszystkim ograniczeniu:",
  ["negatywnej selekcji", "pokusy nadużycia i drobnych szkód", "ryzyka systematycznego", "inflacji"], "B",
  "Gdy ubezpieczony pokrywa część szkody (udział własny) lub drobne szkody nie są wypłacane (franszyza), ma bodziec do ostrożności – ogranicza się pokusa nadużycia i koszty obsługi małych szkód."),
 (4, "s", "Fundusz inwestycyjny otwarty (FIO) różni się od zamkniętego (FIZ) tym, że:",
  ["FIO zbywa i odkupuje jednostki uczestnictwa na żądanie uczestnika", "FIO emituje certyfikaty notowane na giełdzie", "FIO nie podlega nadzorowi KNF", "FIO nie może inwestować w akcje"], "A",
  "FIO – jednostki uczestnictwa umarzane na żądanie (płynność). FIZ – certyfikaty inwestycyjne emitowane w zamkniętych emisjach, często notowane na giełdzie. Oba zarządzane przez TFI pod nadzorem KNF."),
 (4, "s", "Krótka sprzedaż akcji polega na:",
  ["sprzedaży akcji przed upływem roku od zakupu", "sprzedaży pożyczonych akcji z zamiarem odkupienia ich taniej w przyszłości", "sprzedaży akcji po cenie niższej od nominalnej", "sprzedaży akcji pracowniczych"], "B",
  "Inwestor pożycza akcje i je sprzedaje, licząc na spadek ceny; zysk = cena sprzedaży − cena odkupu − koszty pożyczki. Potencjalna strata jest teoretycznie nieograniczona."),
 (4, "s", "IPO to:",
  ["wycofanie spółki z giełdy", "pierwsza publiczna oferta akcji spółki, zwykle połączona z wejściem na giełdę", "emisja obligacji skarbowych", "wezwanie do sprzedaży akcji"], "B",
  "Initial Public Offering – pierwsza oferta publiczna (subskrypcja nowych akcji lub sprzedaż istniejących). Wymaga prospektu zatwierdzonego przez KNF (z wyjątkami). Wycofanie z obrotu to delisting."),
 (4, "m", "Które obligacje skarbowe detaliczne są indeksowane inflacją (od drugiego okresu odsetkowego)?",
  ["COI (4-letnie)", "EDO (10-letnie)", "OTS (3-miesięczne)", "ROD (12-letnie rodzinne)"], "ABD",
  "COI, EDO oraz rodzinne ROS i ROD mają oprocentowanie od 2. roku równe inflacji + marża. OTS i DOS (oraz TOS) mają oprocentowanie stałe, ROR i DOR – zmienne zależne od stopy referencyjnej NBP."),
]
