# -*- coding: utf-8 -*-
# Dział 6 – Gospodarka światowa, handel międzynarodowy i UE (pytania ręczne)
M = [
 (6, "s", "W Polsce 1 robotnik wytwarza w ciągu dnia 4 komputery albo 8 rowerów, a w Niemczech 6 komputerów albo 9 rowerów. Zgodnie z teorią Ricardo:",
  ["Niemcy powinny produkować oba dobra, bo mają przewagę absolutną", "Polska powinna specjalizować się w rowerach, a Niemcy w komputerach", "Polska powinna specjalizować się w komputerach", "handel nie przyniesie korzyści"], "B",
  "Koszt alternatywny komputera: Polska 2 rowery, Niemcy 1,5 roweru – Niemcy mają przewagę komparatywną w komputerach. Koszt roweru: Polska 0,5 komputera, Niemcy 0,67 – Polska ma przewagę komparatywną w rowerach. Przewaga absolutna Niemiec w obu dobrach nie wyklucza korzyści z handlu."),
 (6, "s", "Kurs EUR/PLN wzrósł z 4,20 do 4,40. Oznacza to:",
  ["aprecjację złotego", "deprecjację złotego", "rewaluację euro przez EBC", "dewaluację euro"], "B",
  "Za 1 euro trzeba zapłacić więcej złotych – złoty traci na wartości (deprecjacja przy kursie płynnym; przy kursie stałym urzędowe obniżenie to dewaluacja). Eksporterzy zyskują, importerzy tracą."),
 (6, "m", "Które skutki deprecjacji złotego są typowe (ceteris paribus)?",
  ["Polskie towary stają się tańsze dla zagranicy", "Import staje się droższy", "Rośnie inflacja importowana", "Zmniejsza się wartość w złotych długu zaciągniętego w euro"], "ABC",
  "Słabszy złoty poprawia konkurencyjność cenową eksportu, podraża import i podnosi ceny (pass-through). Dług w walucie obcej przeliczony na złote rośnie, a nie maleje."),
 (6, "s", "Parytet siły nabywczej (PPP) zakłada, że w długim okresie kurs walutowy dostosowuje się tak, aby:",
  ["wyrównać stopy procentowe", "ten sam koszyk dóbr kosztował tyle samo w obu krajach po przeliczeniu na wspólną walutę", "bilans handlowy był zrównoważony", "rezerwy walutowe były stałe"], "B",
  "PPP (prawo jednej ceny): E = P/P*. Przykładem testu jest indeks Big Maca (The Economist). Wyrównywanie stóp procentowych opisuje parytet stóp procentowych."),
 (6, "s", "Cena krajowa koszyka wynosi 1000 zł, a w strefie euro 250 euro. Kurs rynkowy EUR/PLN to 4,40. Zgodnie z PPP złoty jest:",
  ["przewartościowany", "niedowartościowany", "w równowadze", "nie da się stwierdzić"], "B",
  "Kurs PPP = 1000/250 = 4,00 zł/euro. Rynek płaci 4,40 zł za euro – więcej niż wynika z PPP, więc złoty jest niedowartościowany (słabszy niż wynikałoby z siły nabywczej)."),
 (6, "m", "Które pozycje są ujmowane w rachunku bieżącym bilansu płatniczego?",
  ["Eksport i import towarów", "Eksport i import usług (np. turystyka, transport)", "Przekazy emigrantów", "Zakup przez zagranicznego inwestora fabryki w Polsce (BIZ)"], "ABC",
  "Rachunek bieżący: towary, usługi, dochody pierwotne (wynagrodzenia, dochody z inwestycji) i wtórne (transfery, przekazy). Bezpośrednie inwestycje zagraniczne ujmuje się na rachunku finansowym."),
 (6, "s", "Nałożenie cła na import w małym kraju (który nie wpływa na ceny światowe) spowoduje:",
  ["spadek ceny krajowej", "wzrost produkcji krajowej i spadek importu", "wzrost importu", "korzyść dla konsumentów"], "B",
  "Cena krajowa rośnie o cło: producenci krajowi zwiększają produkcję, konsumenci kupują mniej, import spada. Nadwyżka konsumentów maleje bardziej, niż rosną nadwyżka producentów i wpływy z cła – powstaje strata (efekt produkcyjny i konsumpcyjny)."),
 (6, "s", "Zgodnie z warunkiem Marshalla–Lernera deprecjacja waluty poprawi saldo bilansu handlowego, jeśli:",
  ["suma elastyczności cenowych popytu na eksport i import jest większa od 1", "suma elastyczności jest równa 0", "elastyczność popytu na import jest równa 1", "kraj ma deficyt budżetowy"], "A",
  "Gdy |Ex| + |Em| > 1, ilościowa reakcja handlu przeważa nad efektem cenowym (droższy import). W krótkim okresie saldo może się najpierw pogorszyć – krzywa J."),
 (6, "m", "Które formy integracji gospodarczej obejmują wspólną zewnętrzną taryfę celną?",
  ["Strefa wolnego handlu", "Unia celna", "Wspólny rynek", "Unia gospodarcza i walutowa"], "BCD",
  "Etapy wg B. Balassy: strefa wolnego handlu (brak ceł wewnętrznych, każdy kraj ma własne cła zewnętrzne), unia celna (+ wspólna taryfa zewnętrzna), wspólny rynek (+ swobodny przepływ czynników), unia gospodarcza i walutowa, pełna integracja."),
 (6, "s", "Polska przystąpiła do Unii Europejskiej:",
  ["1 stycznia 1999 r.", "1 maja 2004 r.", "21 grudnia 2007 r.", "16 kwietnia 2003 r."], "B",
  "1 maja 2004 r. – członkostwo (z 9 innymi państwami); 16 kwietnia 2003 r. – podpisanie traktatu akcesyjnego w Atenach; 21 grudnia 2007 r. – wejście do strefy Schengen."),
 (6, "m", "Które państwa są członkami strefy euro (stan na 2026 r.)?",
  ["Chorwacja", "Bułgaria", "Szwecja", "Słowacja"], "ABD",
  "Chorwacja przyjęła euro 1 stycznia 2023 r., Bułgaria 1 stycznia 2026 r. (21. państwo), Słowacja w 2009 r. Szwecja nie przyjęła euro (nie weszła do ERM II, referendum 2003 r.)."),
 (6, "s", "Teoria Heckschera–Ohlina wyjaśnia handel międzynarodowy:",
  ["różnicami w technologii", "różnicami w zasobach czynników produkcji – kraje eksportują dobra intensywnie wykorzystujące ich obfite czynniki", "korzyściami skali i zróżnicowaniem produktów", "cyklem życia produktu"], "B",
  "H-O: kraj obfity w kapitał eksportuje dobra kapitałochłonne, obfity w pracę – pracochłonne. Paradoks Leontiefa (1953) pokazał, że eksport USA był bardziej pracochłonny niż import. Korzyści skali i zróżnicowanie – nowa teoria handlu (P. Krugman)."),
 (6, "s", "Który kraj jest największym partnerem handlowym Polski w eksporcie?",
  ["Chiny", "Niemcy", "Stany Zjednoczone", "Wielka Brytania"], "B",
  "Niemcy odpowiadają za ok. ¼ polskiego eksportu (i ok. 1/5 importu). W imporcie drugie miejsce zajmują Chiny."),
 (6, "m", "Które instytucje powstały w wyniku konferencji w Bretton Woods (1944)?",
  ["Międzynarodowy Fundusz Walutowy", "Bank Światowy (MBOiR)", "Światowa Organizacja Handlu", "Europejski Bank Centralny"], "AB",
  "Bretton Woods (lipiec 1944 r.) – MFW i Międzynarodowy Bank Odbudowy i Rozwoju (Bank Światowy) oraz system stałych kursów z dolarem wymienialnym na złoto (35 USD za uncję). WTO powstała w 1995 r. (wcześniej GATT 1947), EBC w 1998 r."),
 (6, "s", "Dumping w handlu międzynarodowym to:",
  ["sprzedaż towaru za granicą po cenie niższej niż na rynku krajowym lub poniżej kosztów", "ograniczenie ilościowe importu", "dopłata państwa do eksportu", "zakaz eksportu surowców"], "A",
  "Dumping może być karany cłami antydumpingowymi (procedury WTO, w UE – Komisja Europejska). Dopłaty do eksportu to subsydia eksportowe, ograniczenia ilościowe – kontyngenty."),
 (6, "s", "Wspólna polityka handlowa w Unii Europejskiej należy do:",
  ["wyłącznych kompetencji UE", "kompetencji dzielonych UE i państw członkowskich", "wyłącznych kompetencji państw członkowskich", "kompetencji EBC"], "A",
  "Art. 3 TFUE: wyłączne kompetencje UE to m.in. unia celna, reguły konkurencji dla rynku wewnętrznego, polityka pieniężna strefy euro i wspólna polityka handlowa. Dlatego umowy handlowe (np. z Mercosur) negocjuje Komisja Europejska."),
 (6, "m", "Które stwierdzenia o globalizacji są prawdziwe?",
  ["Sprzyjają jej spadek kosztów transportu i komunikacji", "Oznacza rosnące współzależności gospodarek przez handel, inwestycje i przepływy kapitału", "Prowadzi zawsze do zmniejszenia nierówności wewnątrz każdego kraju", "Przyspiesza przenoszenie kryzysów finansowych między krajami"], "ABD",
  "Globalizację napędza technologia i liberalizacja; zwiększa współzależność i ryzyko zarażania kryzysami. Jej wpływ na nierówności wewnątrz krajów jest zróżnicowany – w wielu krajach rozwiniętych nierówności wzrosły."),
 (6, "s", "Zarząd waluty (currency board) polega na tym, że:",
  ["bank centralny swobodnie ustala stopy procentowe", "emisja waluty krajowej jest w pełni pokryta rezerwami w walucie zakotwiczenia po stałym kursie", "kraj używa obcej waluty zamiast własnej", "kurs jest wyznaczany wyłącznie przez rynek"], "B",
  "Currency board (np. Bułgaria 1997–2025, Estonia przed euro, Hongkong) – sztywny kurs wobec waluty kotwicy i 100% pokrycie bazy monetarnej rezerwami; bank centralny traci samodzielną politykę pieniężną. Używanie obcej waluty to euroizacja/dolaryzacja."),
]
