# -*- coding: utf-8 -*-
# Pytania ręczne – druga partia (różne działy, więcej wielokrotnego wyboru)
M = [
 # --- osoby (10) ---
 (10, "m", "Które pary „autor – teoria motywacji” są poprawne?",
  ["A. Maslow – hierarchia potrzeb", "F. Herzberg – teoria dwuczynnikowa", "V. Vroom – teoria oczekiwań", "C. Alderfer – teoria X i Y"], "ABC",
  "Alderfer – teoria ERG (egzystencja, relacje, rozwój); teorię X i Y sformułował D. McGregor."),
 (10, "s", "„Droga do zniewolenia” (1944), krytyka planowania centralnego i koncepcja cen jako nośnika rozproszonej wiedzy to dorobek:",
  ["L. von Misesa", "F. von Hayeka", "M. Friedmana", "J.K. Galbraitha"], "B",
  "F. von Hayek (Nobel 1974) – szkoła austriacka; Mises (również austriacka) – „Socjalizm”, problem kalkulacji ekonomicznej."),
 (10, "s", "Twórcą krzywej pokazującej, że powyżej pewnej stawki podatkowej wpływy budżetowe maleją, jest:",
  ["A. Laffer", "A.W. Phillips", "M.O. Lorenz", "A. Okun"], "A",
  "Krzywa Laffera (lata 70.). Phillips – inflacja a bezrobocie, Lorenz – krzywa nierówności, Okun – bezrobocie a PKB."),
 (10, "m", "Którzy ekonomiści są związani ze szkołą chicagowską?",
  ["Milton Friedman", "George Stigler", "Gary Becker", "John Kenneth Galbraith"], "ABC",
  "Friedman, Stigler, Becker (także Coase, Lucas, Fama) – szkoła chicagowska: wolny rynek, monetaryzm, ekonomiczna analiza zachowań. Galbraith był instytucjonalistą krytycznym wobec wolnego rynku („Społeczeństwo dobrobytu”)."),
 (10, "s", "Pojęcie „twórczej destrukcji” i rolę przedsiębiorcy-innowatora w rozwoju gospodarczym opisał:",
  ["J.A. Schumpeter", "J.B. Say", "A. Marshall", "T. Veblen"], "A",
  "Schumpeter („Teoria rozwoju gospodarczego”, 1911; „Kapitalizm, socjalizm, demokracja”, 1942): innowacje niszczą stare struktury i tworzą nowe."),
 (10, "s", "Prawo Saya głosi, że:",
  ["podaż tworzy własny popyt", "popyt tworzy własną podaż", "pieniądz gorszy wypiera lepszy", "ludność rośnie geometrycznie"], "A",
  "J.B. Say: produkcja generuje dochody wystarczające do zakupu wytworzonych dóbr – ogólna nadprodukcja jest niemożliwa. Keynes krytykował to prawo, wskazując na niedobór popytu efektywnego."),
 (10, "s", "Model IS–LM sformułował (1937), interpretując teorię Keynesa:",
  ["J. Hicks", "P. Samuelson", "J. Tobin", "R. Mundell"], "A",
  "J. Hicks („Mr. Keynes and the Classics”, 1937), rozwinięty przez A. Hansena (model Hicksa–Hansena). Mundell i Fleming rozszerzyli go na gospodarkę otwartą."),
 # --- instytucje (11) ---
 (11, "m", "Które instytucje są organami Unii Europejskiej (instytucjami w rozumieniu traktatów)?",
  ["Komisja Europejska", "Europejski Bank Centralny", "Trybunał Sprawiedliwości UE", "Europejski Bank Odbudowy i Rozwoju"], "ABC",
  "Instytucje UE (art. 13 TUE): Parlament Europejski, Rada Europejska, Rada UE, Komisja, TSUE, EBC, Trybunał Obrachunkowy. EBOiR (Londyn, 1991) to odrębna międzynarodowa instytucja finansowa."),
 (11, "s", "Instytucją wypłacającą emerytury rolnikom w Polsce jest:",
  ["ZUS", "KRUS", "NFZ", "PFRON"], "B",
  "Kasa Rolniczego Ubezpieczenia Społecznego – finansowana głównie dotacją z budżetu. NFZ finansuje ochronę zdrowia, PFRON – rehabilitację osób niepełnosprawnych."),
 (11, "s", "Komitet Stabilności Finansowej w Polsce:",
  ["ustala stopy procentowe", "jest organem nadzoru makroostrożnościowego (przewodniczy prezes NBP)", "nadzoruje giełdę", "prowadzi rejestr dłużników"], "B",
  "KSF (od 2015 r.): prezes NBP, minister finansów, przewodniczący KNF, prezes BFG; identyfikuje ryzyko systemowe i rekomenduje bufory kapitałowe. Stopy ustala RPP."),
 (11, "s", "Która instytucja chroni konsumentów i konkurencję w Polsce, może nakładać kary na firmy za zmowy cenowe?",
  ["KNF", "UOKiK", "Rzecznik Finansowy", "NIK"], "B",
  "Prezes UOKiK – ochrona konkurencji (kartele, nadużywanie pozycji dominującej, kontrola koncentracji) i zbiorowych interesów konsumentów. NIK kontroluje wydatki publiczne."),
 # --- daty (12) ---
 (12, "s", "Przyporządkuj datę do wydarzenia: koniec wymienialności dolara na złoto („szok Nixona”), który zakończył system z Bretton Woods:",
  ["1944", "1971", "1979", "1992"], "B",
  "15 sierpnia 1971 r. R. Nixon zawiesił wymienialność dolara na złoto; od 1973 r. dominują kursy płynne. 1944 – konferencja w Bretton Woods; 1979 – Europejski System Walutowy; 1992 – Maastricht i „czarna środa”."),
 (12, "m", "Które wydarzenia miały miejsce w 2004 r.?",
  ["Wejście Polski do UE", "Przyjęcie przez NBP celu inflacyjnego 2,5% ± 1 pkt proc.", "Wprowadzenie podatku liniowego 19% dla przedsiębiorców w Polsce", "Wejście Polski do strefy Schengen"], "ABC",
  "2004: akcesja (1 maja), stały cel inflacyjny NBP od 2004 r., liniowy PIT 19% dla przedsiębiorców od 2004 r. Schengen – grudzień 2007 r."),
 (12, "s", "Giełda Papierów Wartościowych w Warszawie rozpoczęła działalność (pierwsza sesja) w:",
  ["1989 r.", "1991 r.", "1994 r.", "1998 r."], "B",
  "Pierwsza sesja GPW odbyła się 16 kwietnia 1991 r. (5 spółek, w budynku dawnego KC PZPR). W 1994 r. wprowadzono indeks WIG20."),
 (12, "s", "Rada Polityki Pieniężnej i Europejski Bank Centralny rozpoczęły działalność w:",
  ["1995 r.", "1997 r.", "1998 r.", "2002 r."], "C",
  "RPP – na mocy Konstytucji z 1997 r. i ustawy o NBP, pierwsza rada od 1998 r.; EBC powołano 1 czerwca 1998 r. (euro od 1999 r.)."),
 # --- przepisy (13) ---
 (13, "s", "Ustawa zasadnicza stanowiąca, że NBP odpowiada za wartość polskiego pieniądza i że państwo nie może finansować deficytu w banku centralnym, to:",
  ["ustawa o finansach publicznych", "Konstytucja RP z 1997 r.", "Prawo bankowe", "ustawa o NBP z 1989 r."], "B",
  "Art. 227 Konstytucji (NBP, wartość pieniądza, RPP) i art. 220 ust. 2 (zakaz finansowania deficytu przez bank centralny); szczegóły w ustawie o NBP z 29 sierpnia 1997 r."),
 (13, "m", "Które zasady są zapisane w Prawie przedsiębiorców (2018)?",
  ["Co nie jest prawem zabronione, jest dozwolone", "Domniemanie uczciwości przedsiębiorcy", "Rozstrzyganie wątpliwości faktycznych na korzyść przedsiębiorcy", "Obowiązek uzyskania zezwolenia na każdą działalność"], "ABC",
  "„Konstytucja biznesu” (od 30 kwietnia 2018 r.) wprowadziła m.in. zasadę wolności (co nie jest zabronione, jest dozwolone), domniemanie uczciwości, in dubio pro libertate, zasadę przyjaznej interpretacji przepisów. Zezwolenia i koncesje wymagane są tylko dla wybranych rodzajów działalności."),
 (13, "s", "Wiek emerytalny w Polsce (stan na 2026 r.) wynosi:",
  ["67 lat dla obu płci", "60 lat dla kobiet i 65 lat dla mężczyzn", "65 lat dla obu płci", "62 lata dla kobiet i 67 lat dla mężczyzn"], "B",
  "Od 1 października 2017 r. przywrócono 60/65 lat (wcześniej od 2013 r. stopniowo podnoszono do 67 lat)."),
 # --- paradoksy (14) ---
 (14, "m", "Które z poniższych są przykładami paradoksów lub błędów logicznych omawianych w ekonomii?",
  ["Błąd złożenia (to, co dobre dla jednostki, jest dobre dla całości)", "Paradoks wartości (woda i diament)", "Paradoks Leontiefa", "Prawo malejącej użyteczności krańcowej"], "ABC",
  "Błąd złożenia (np. paradoks oszczędności), paradoks wody i diamentu (rozwiązany przez marginalizm), paradoks Leontiefa (struktura handlu USA). Prawo malejącej użyteczności krańcowej to regularność, a nie paradoks."),
 (14, "s", "Paradoks Jevonsa polega na tym, że:",
  ["wzrost efektywności wykorzystania zasobu może zwiększyć jego łączne zużycie", "wzrost cen zwiększa popyt", "oszczędzanie obniża dochód", "bogactwo nie zwiększa szczęścia"], "A",
  "W.S. Jevons (1865) zauważył, że sprawniejsze maszyny parowe zwiększyły, a nie zmniejszyły zużycie węgla – tańsza usługa pobudza popyt (efekt odbicia)."),
 (14, "s", "Paradoks Easterlina dotyczy zależności między:",
  ["dochodem a deklarowanym poczuciem szczęścia", "inflacją a bezrobociem", "eksportem a kursem walutowym", "liczbą ludności a żywnością"], "A",
  "R. Easterlin (1974): w długim okresie wzrost dochodu na mieszkańca nie zwiększa średniego deklarowanego szczęścia, choć w danym momencie bogatsi są szczęśliwsi (liczy się dochód względny)."),
 # --- demografia (15) ---
 (15, "m", "Które cechy dotyczą drugiego przejścia demograficznego?",
  ["Trwały spadek dzietności poniżej poziomu zastępowalności", "Opóźnianie wieku zawierania małżeństw i rodzenia dzieci", "Wzrost liczby związków nieformalnych i urodzeń pozamałżeńskich", "Gwałtowny spadek umieralności niemowląt w krajach przedprzemysłowych"], "ABC",
  "Drugie przejście (van de Kaa, Lesthaeghe, 1986) wiąże się ze zmianą wartości (indywidualizm). Spadek umieralności w krajach przedprzemysłowych to element pierwszego przejścia demograficznego."),
 (15, "s", "Polska stała się krajem o dodatnim saldzie migracji i dużej imigracji zarobkowej głównie z:",
  ["Niemiec", "Ukrainy", "Wielkiej Brytanii", "Chin"], "B",
  "Wśród cudzoziemców ubezpieczonych w ZUS (ok. 1,29 mln w grudniu 2025 r.) dominują obywatele Ukrainy (ok. 857 tys.), następnie Białorusi i Gruzji."),
 (15, "s", "Państwami, które jako ostatnie (1 maja 2011 r.) otworzyły rynki pracy dla obywateli państw przyjętych do UE w 2004 r., były:",
  ["Wielka Brytania i Irlandia", "Niemcy i Austria", "Szwecja i Dania", "Francja i Hiszpania"], "B",
  "Wielka Brytania, Irlandia i Szwecja otworzyły rynki od 1 maja 2004 r.; Niemcy i Austria wykorzystały pełny okres przejściowy 2+3+2 lata."),
 (15, "s", "Współczynnik dzietności w Polsce w 2025 r. wyniósł około:",
  ["2,1", "1,5", "1,3", "1,1"], "D",
  "Według GUS ok. 1,07 (2024 – ok. 1,10; 1990 – 1,99). Średnia UE w 2024 r. – 1,34."),
 (15, "m", "Które instrumenty mogą łagodzić skutki starzenia się społeczeństwa dla finansów publicznych?",
  ["Podnoszenie efektywnego wieku przejścia na emeryturę", "Aktywizacja zawodowa kobiet i osób 50+", "Imigracja zarobkowa", "Obniżenie wieku emerytalnego"], "ABC",
  "Dłuższa aktywność, większe zatrudnienie i imigracja zwiększają liczbę płacących składki i podatki. Obniżenie wieku emerytalnego zwiększa liczbę świadczeniobiorców i obciążenie systemu."),
 (15, "s", "Ryzyko długowieczności w systemach emerytalnych oznacza ryzyko, że:",
  ["osoba przeżyje dłużej, niż wystarczą jej zgromadzone oszczędności", "fundusze emerytalne zbankrutują", "inflacja zmniejszy wartość świadczeń", "wiek emerytalny zostanie podniesiony"], "A",
  "Ubezpieczają od niego renty dożywotnie (annuitety) i publiczne systemy emerytalne – to jeden z celów systemu emerytalnego wg N. Barra i P. Diamonda."),
 # --- różne (1–9) ---
 (1, "m", "Które z poniższych sytuacji spowodują ruch wzdłuż krzywej podaży (a nie jej przesunięcie)?",
  ["Wzrost ceny dobra", "Spadek kosztów produkcji", "Spadek ceny dobra", "Nowa technologia"], "AC",
  "Zmiana ceny samego dobra zmienia wielkość podaży (ruch po krzywej). Koszty, technologia, podatki, liczba producentów przesuwają krzywą podaży."),
 (1, "m", "Które cechy dotyczą konkurencji doskonałej?",
  ["Duża liczba firm sprzedających jednorodny produkt", "Firma jest cenobiorcą (pozioma krzywa popytu)", "W długim okresie firmy osiągają zysk ekonomiczny równy zeru", "Wysokie bariery wejścia"], "ABC",
  "Konkurencja doskonała: wielu uczestników, jednorodny produkt, pełna informacja, swobodne wejście i wyjście – w długim okresie P = MC = min ATC, zysk ekonomiczny = 0."),
 (2, "m", "Które wielkości są strumieniami (a nie zasobami)?",
  ["PKB", "Deficyt budżetowy", "Dług publiczny", "Inwestycje"], "ABD",
  "Strumień mierzy się w okresie (rok): PKB, deficyt, inwestycje, konsumpcja. Zasób – w momencie: dług publiczny, majątek, kapitał, zasób pieniądza."),
 (2, "s", "Wzrost stopy procentowej przez bank centralny w gospodarce otwartej z płynnym kursem (model Mundella–Fleminga) w krótkim okresie zwykle:",
  ["osłabia walutę krajową", "umacnia walutę krajową, co ogranicza eksport netto", "nie wpływa na kurs", "zwiększa inflację"], "B",
  "Wyższe stopy przyciągają kapitał – waluta się umacnia (kanał kursowy transmisji), eksport netto spada, a import tanieje, co obniża inflację."),
 (3, "s", "Pieniądz fiducjarny (dekretowy) to pieniądz, którego wartość wynika:",
  ["z zawartości kruszcu", "z zaufania i nadania mu przez państwo statusu prawnego środka płatniczego", "z wymienialności na złoto", "z kosztu jego wytworzenia"], "B",
  "Współczesne banknoty i pieniądz bankowy są pieniądzem fiducjarnym – nie mają pokrycia w kruszcu; ich wartość opiera się na zaufaniu i polityce banku centralnego."),
 (4, "s", "Dywidenda na akcję wynosi 2 zł, a cena akcji 40 zł. Stopa dywidendy wynosi:",
  ["2%", "5%", "20%", "80%"], "B",
  "Stopa dywidendy = D/P = 2/40 = 5%."),
 (5, "s", "VAT jest podatkiem obciążającym ostatecznie:",
  ["producenta", "konsumenta końcowego", "hurtownika", "państwo"], "B",
  "VAT jest naliczany na każdym etapie obrotu, ale przedsiębiorcy odliczają VAT naliczony od należnego; ciężar ponosi konsument końcowy (podatek od wartości dodanej, neutralny dla firm)."),
 (6, "s", "Wzrost stóp procentowych w USA przy niezmienionych stopach w Polsce (ceteris paribus) prowadzi zwykle do:",
  ["umocnienia złotego wobec dolara", "osłabienia złotego wobec dolara", "spadku cen importu z USA", "spadku rentowności obligacji amerykańskich"], "B",
  "Kapitał przepływa do aktywów dolarowych (wyższy dochód), rośnie popyt na dolara – złoty słabnie (parytet stóp procentowych)."),
 (7, "s", "Kapitał zapasowy w spółce akcyjnej tworzy się obowiązkowo z odpisów z zysku do czasu, gdy osiągnie on co najmniej:",
  ["1/10 kapitału zakładowego", "1/3 kapitału zakładowego", "połowę kapitału zakładowego", "100% kapitału zakładowego"], "B",
  "Art. 396 KSH: co najmniej 8% zysku za dany rok obrotowy przelewa się na kapitał zapasowy, dopóki nie osiągnie on 1/3 kapitału zakładowego; trafia tam też nadwyżka emisyjna (agio)."),
 (8, "s", "Delegowanie uprawnień polega na:",
  ["przekazaniu podwładnemu zadań wraz z uprawnieniami, przy zachowaniu odpowiedzialności przełożonego za ich wykonanie", "zwolnieniu pracownika", "zatrudnieniu konsultanta", "zmianie struktury na płaską"], "A",
  "Kierownik deleguje zadania i uprawnienia, ale nie może zrzec się odpowiedzialności przed własnym przełożonym; delegowanie sprzyja decentralizacji i rozwojowi pracowników."),
 (9, "s", "Wskaźnik ogólnego zadłużenia: zobowiązania 300, aktywa 750. Wynosi on:",
  ["0,4", "2,5", "0,6", "1,5"], "A",
  "Zobowiązania / aktywa = 300/750 = 0,4 (40% majątku finansowane kapitałem obcym); kapitał własny = 450, więc wskaźnik zadłużenia kapitału własnego (przekładnia) = 300/450 ≈ 0,67."),
]
