# -*- coding: utf-8 -*-
# Dział 15 – Gospodarka wobec wyzwań demograficznych (pytania ręczne)
M = [
 (15, "s", "W kraju urodziło się w roku 300 tys. dzieci, zmarło 420 tys. osób, a liczba ludności wynosi 40 mln. Współczynnik przyrostu naturalnego wynosi:",
  ["−3‰", "−0,3‰", "−12‰", "+3‰"], "A",
  "PN = (U − Z)/L · 1000 = (300 − 420) tys. / 40 mln · 1000 = −120 000/40 000 000 · 1000 = −3‰."),
 (15, "s", "Ludność w wieku 0–14 lat liczy 6 mln, 15–64 lat – 24 mln, 65+ – 8 mln. Współczynnik obciążenia demograficznego (na 100 osób w wieku 15–64) wynosi:",
  ["25", "33,3", "58,3", "36,8"], "C",
  "WO = (6 + 8)/24 · 100 ≈ 58,3 osoby w wieku nieprodukcyjnym na 100 w wieku produkcyjnym; w tym obciążenie starszymi 8/24 · 100 ≈ 33,3."),
 (15, "s", "Współczynnik dzietności zapewniający prostą zastępowalność pokoleń w krajach rozwiniętych wynosi około:",
  ["1,3", "1,7", "2,1", "3,0"], "C",
  "Ok. 2,1 dziecka na kobietę (nadwyżka ponad 2 wynika z przewagi urodzeń chłopców i zgonów przed wiekiem rozrodczym). W Polsce TFR spadł do ok. 1,07 w 2025 r."),
 (15, "m", "Które czynniki prowadzą do starzenia się ludności?",
  ["Spadek dzietności", "Wydłużanie się oczekiwanej długości życia", "Emigracja młodych osób", "Wysoka dzietność przy wysokiej umieralności niemowląt"], "ABC",
  "Starzenie „od dołu” (mniej urodzeń), „od góry” (dłuższe życie) i odpływ młodych migrantów zwiększają udział osób starszych. Wysoka dzietność odmładza strukturę wieku."),
 (15, "s", "W fazie przejścia demograficznego, w której umieralność już spadła, a rozrodczość pozostaje wysoka, występuje:",
  ["depopulacja", "eksplozja demograficzna (szybki przyrost ludności)", "drugie przejście demograficzne", "stabilizacja liczby ludności"], "B",
  "Faza 2 (np. Europa w XIX w., Afryka obecnie): spadek umieralności dzięki postępowi medycyny i higieny przy wciąż wysokiej dzietności daje szybki wzrost ludności."),
 (15, "s", "System emerytalny, w którym bieżące składki pracujących finansują bieżące emerytury, to system:",
  ["kapitałowy", "repartycyjny (pay-as-you-go)", "zdefiniowanego świadczenia z funduszem kapitałowym", "dobrowolny III filar"], "B",
  "PAYG opiera się na umowie międzypokoleniowej i jest wrażliwy na relację liczby pracujących do emerytów. W systemie kapitałowym emerytura pochodzi z zainwestowanych składek."),
 (15, "s", "Zgodnie z warunkiem Aarona system repartycyjny daje wyższą stopę zwrotu niż kapitałowy, gdy:",
  ["tempo wzrostu ludności i płac realnych przewyższa realną stopę procentową", "realna stopa procentowa przewyższa wzrost płac", "ludność maleje", "inflacja jest wyższa od 2%"], "A",
  "H. Aaron (1966): PAYG korzystniejszy, gdy n + g > r. Starzenie się i spadek ludności (n < 0) osłabiają ten warunek."),
 (15, "s", "Emerytura w polskim systemie (część ZUS) obliczana jest jako:",
  ["% ostatniego wynagrodzenia zależny od stażu", "suma zwaloryzowanych składek i kapitału początkowego podzielona przez średnie dalsze trwanie życia w miesiącach", "stała kwota równa emeryturze minimalnej", "średnia płaca z 10 najlepszych lat"], "B",
  "System zdefiniowanej składki (NDC): E = (składki + kapitał początkowy) / średnie dalsze trwanie życia z tablic GUS. Formuła „% ostatniej płacy zależny od stażu” to system zdefiniowanego świadczenia."),
 (15, "s", "Kapitał 540 000 zł zgromadzony na koncie ZUS, średnie dalsze trwanie życia 270 miesięcy. Emerytura miesięczna (brutto) wyniesie:",
  ["1800 zł", "2000 zł", "2250 zł", "5400 zł"], "B",
  "E = 540 000 / 270 = 2000 zł brutto. Późniejsze przejście na emeryturę zwiększa kapitał i skraca dalsze trwanie życia – emerytura rośnie."),
 (15, "m", "Które twierdzenia wynikają z tezy Goodharta i Pradhana o „wielkim zwrocie demograficznym”?",
  ["Wejście Chin i Europy Wschodniej do gospodarki światowej obniżało płace realne i inflację w latach 1990–2020", "Starzenie się społeczeństw i kurczenie się zasobów pracy podniosą siłę przetargową pracowników", "Nierówności wewnątrz krajów będą maleć", "Inflacja i stopy procentowe pozostaną trwale bliskie zera"], "ABC",
  "Autorzy przewidują powrót inflacji i wzrost naturalnej stopy procentowej (rozszczędzanie seniorów, inwestycje zastępujące pracę), wyższe płace i niższe nierówności. Trwale zerowe stopy to scenariusz japoński, który traktują jako wyjątek."),
 (15, "s", "Teoria migracji, według której decyzję o wyjeździe podejmuje gospodarstwo domowe, aby zdywersyfikować ryzyko dochodowe, to:",
  ["teoria push–pull E. Lee", "nowa ekonomia migracji zarobkowych (O. Stark)", "teoria rynku dualnego (M. Piore)", "teoria systemów światowych (I. Wallerstein)"], "B",
  "NELM (Stark i Bloom, 1985): migracja jako strategia rodziny – dywersyfikacja ryzyka, przekazy pieniężne, deprywacja względna."),
 (15, "m", "Które skutki emigracji zarobkowej dotyczą kraju pochodzenia?",
  ["Napływ przekazów pieniężnych", "Drenaż mózgów", "Spadek bezrobocia w krótkim okresie", "Odmłodzenie struktury wieku ludności"], "ABC",
  "Emigracja młodych przynosi przekazy i zmniejsza bezrobocie, ale powoduje drenaż mózgów, ubytek siły roboczej i przyspiesza starzenie się (a nie odmłodzenie) ludności kraju pochodzenia."),
 (15, "s", "Druga dywidenda demograficzna może powstać, gdy:",
  ["rośnie dzietność", "starzejące się społeczeństwo gromadzi oszczędności na starość, które zwiększają zasób kapitału i produktywność", "rośnie emigracja", "obniża się wiek emerytalny"], "B",
  "Koncepcja R. Lee i A. Masona: po wygaśnięciu pierwszej dywidendy (wysoki udział osób w wieku produkcyjnym) korzyść może dać akumulacja kapitału przez osoby oszczędzające na starość."),
 (15, "s", "Program „Aktywny rodzic” (tzw. babciowe) w Polsce obowiązuje od:",
  ["1 kwietnia 2016 r.", "1 stycznia 2022 r.", "1 października 2024 r.", "1 stycznia 2024 r."], "C",
  "„Aktywny rodzic” – od 1 października 2024 r. (wsparcie opieki nad dzieckiem do 3 lat). 500+ – od 1 kwietnia 2016 r., 800+ – od 1 stycznia 2024 r., rodzinny kapitał opiekuńczy – od 1 stycznia 2022 r."),
 (15, "s", "Sekularna stagnacja to pojęcie, które spopularyzowali:",
  ["A. Hansen (1938) i L. Summers (2013)", "J.M. Keynes i M. Friedman", "A. Smith i D. Ricardo", "C. Goodhart i M. Pradhan"], "A",
  "Hansen powiązał stagnację ze spowolnieniem wzrostu ludności; Summers przywrócił pojęcie po kryzysie 2008 r. – nadwyżka oszczędności nad inwestycjami i bardzo niska naturalna stopa procentowa."),
]
