# -*- coding: utf-8 -*-
# Dział 1 – Mikroekonomia, partia 3
M = [
 (1, "s", "Krzywa możliwości produkcyjnych jest wklęsła (wygięta na zewnątrz), ponieważ:",
  ["koszt alternatywny produkcji jednego dobra rośnie wraz ze zwiększaniem jego produkcji", "zasoby są nieograniczone", "technologia jest stała", "ceny dóbr są stałe"], "A",
  "Zasoby nie są jednakowo przydatne do produkcji obu dóbr – przesuwając je, najpierw wykorzystuje się te najlepiej dopasowane, potem coraz mniej, więc koszt alternatywny rośnie."),
 (1, "s", "Punkt leżący wewnątrz krzywej możliwości produkcyjnych oznacza:",
  ["niepełne lub nieefektywne wykorzystanie zasobów (np. bezrobocie)", "kombinację nieosiągalną", "maksymalną efektywność", "wzrost gospodarczy"], "A",
  "Punkty na krzywej są efektywne, poza nią – nieosiągalne przy obecnych zasobach i technologii; wewnątrz – marnotrawstwo zasobów."),
 (1, "s", "Postęp techniczny w produkcji tylko jednego z dwóch dóbr spowoduje, że krzywa możliwości produkcyjnych:",
  ["przesunie się na zewnątrz wzdłuż osi tego dobra (obróci się)", "przesunie się równolegle do wewnątrz", "nie zmieni się", "przesunie się równolegle na zewnątrz wzdłuż obu osi w jednakowym stopniu"], "A",
  "Maksymalna produkcja drugiego dobra się nie zmienia, więc punkt na jego osi zostaje, a krzywa „rozciąga się” wzdłuż osi dobra objętego postępem."),
 (1, "s", "Pytanie „czy płaca minimalna powinna wzrosnąć?” należy do ekonomii:",
  ["normatywnej", "pozytywnej", "matematycznej", "opisowej (deskryptywnej)"], "A",
  "Ekonomia normatywna formułuje oceny i zalecenia („powinno”), pozytywna opisuje i wyjaśnia, jak jest (np. „wzrost płacy minimalnej o 10% zmniejszy zatrudnienie młodych o 2%”)."),
 (1, "s", "Założenie ceteris paribus w analizie popytu oznacza, że:",
  ["badając wpływ ceny na popyt, inne czynniki traktujemy jako niezmienione", "wszystkie ceny zmieniają się jednocześnie", "rynek jest w równowadze", "popyt jest doskonale elastyczny"], "A",
  "„Przy pozostałych warunkach niezmienionych” – pozwala wyodrębnić wpływ jednej zmiennej; zmiana innego czynnika (dochód, gusty) przesuwa całą krzywą."),
 (1, "s", "Spekulacyjny wzrost popytu na akcje po wzroście ich ceny (oczekiwanie dalszych wzrostów) to przykład:",
  ["odstępstwa od prawa popytu związanego z oczekiwaniami", "efektu substytucyjnego", "dobra niższego rzędu", "popytu doskonale nieelastycznego"], "A",
  "Gdy wzrost ceny rodzi oczekiwanie dalszych wzrostów, kupujący zwiększają zakupy (efekt spekulacyjny) – obok dóbr Giffena i Veblena to typowy wyjątek od prawa popytu."),
 (1, "s", "Przy liniowej krzywej popytu elastyczność cenowa:",
  ["zmienia się wzdłuż krzywej – na górnym odcinku popyt jest elastyczny, na dolnym nieelastyczny", "jest stała na całej krzywej", "jest zawsze równa nachyleniu krzywej", "jest równa zeru"], "A",
  "Nachylenie (ΔP/ΔQ) jest stałe, ale stosunek P/Q zmienia się – elastyczność jest wysoka przy wysokich cenach, jednostkowa w środku, niska przy niskich cenach."),
 (1, "s", "Popyt na papierosy jest nieelastyczny cenowo. Podwyżka akcyzy na papierosy spowoduje przede wszystkim:",
  ["wzrost wpływów budżetowych przy niewielkim spadku spożycia", "duży spadek spożycia i spadek wpływów", "wzrost spożycia", "brak zmiany ceny dla konsumentów"], "A",
  "Przy nieelastycznym popycie ilość spada słabo, więc wpływy z akcyzy rosną; ciężar podatku ponoszą głównie konsumenci. W długim okresie popyt staje się bardziej elastyczny."),
 (1, "s", "Rekordowe zbiory zbóż w całym kraju przy nieelastycznym popycie na zboże spowodują, że łączne przychody rolników:",
  ["spadną", "wzrosną proporcjonalnie do zbiorów", "nie zmienią się", "wzrosną ponad proporcjonalnie"], "A",
  "Wzrost podaży przy nieelastycznym popycie obniża cenę bardziej (procentowo), niż rośnie sprzedana ilość – „paradoks urodzaju”."),
 (1, "s", "Firma farmaceutyczna ma patent na lek bez substytutów. Popyt na ten lek jest najprawdopodobniej:",
  ["nieelastyczny cenowo", "doskonale elastyczny", "elastyczny, bo lek jest drogi", "jednostkowy"], "A",
  "Brak substytutów i konieczność leczenia czynią popyt nieelastycznym – stąd regulacja cen leków refundowanych i negocjacje cenowe państwa."),
 (1, "s", "Przedsiębiorstwo w konkurencji doskonałej sprzedaje 1000 szt. po 15 zł. Utarg krańcowy z ostatniej sprzedanej sztuki wynosi:",
  ["15 zł", "15 000 zł", "mniej niż 15 zł", "0 zł"], "A",
  "Cenobiorca może sprzedać dowolną ilość po cenie rynkowej, więc MR = AR = P = 15 zł."),
 (1, "s", "Monopolista sprzedaje 10 szt. po 50 zł. Aby sprzedać 11 szt., musi obniżyć cenę do 48 zł. Utarg krańcowy jedenastej sztuki wynosi:",
  ["28 zł", "48 zł", "−2 zł", "528 zł"], "A",
  "TR(10) = 500, TR(11) = 528 ⇒ MR = 28 zł. Zysk z nowej sztuki (48 zł) pomniejsza strata 2 zł na każdej z 10 wcześniejszych."),
 (1, "s", "Przy jakim warunku firma w krótkim okresie powinna zawiesić produkcję?",
  ["Gdy cena spadnie poniżej minimum przeciętnego kosztu zmiennego", "Gdy cena spadnie poniżej przeciętnego kosztu całkowitego", "Gdy zysk ekonomiczny jest równy zeru", "Gdy utarg krańcowy jest równy kosztowi krańcowemu"], "A",
  "Poniżej min AVC przychody nie pokrywają nawet kosztów zmiennych – zamknięcie ogranicza stratę do kosztów stałych."),
 (1, "s", "W branży doskonale konkurencyjnej o stałych kosztach (stała długookresowa krzywa podaży) trwały wzrost popytu w długim okresie spowoduje:",
  ["wzrost produkcji branży przy tej samej cenie", "trwały wzrost ceny", "spadek liczby firm", "trwałe zyski nadzwyczajne"], "A",
  "Najpierw cena i zyski rosną, potem wchodzą nowe firmy, aż cena wróci do min ATC. Długookresowa podaż branży o stałych kosztach jest pozioma."),
 (1, "s", "Firma rozważa, czy przyjąć dodatkowe zamówienie po 30 zł za sztukę. Koszt zmienny jednostkowy wynosi 22 zł, przeciętny koszt całkowity 35 zł, a firma ma wolne moce. Zamówienie:",
  ["warto przyjąć, bo pokrywa koszty zmienne i część stałych", "należy odrzucić, bo cena jest niższa od kosztu przeciętnego", "jest obojętne", "przyniesie stratę 5 zł na sztuce"], "A",
  "Koszty stałe i tak zostaną poniesione; liczy się koszt krańcowy (22 zł). Każda sztuka zwiększa wynik o 8 zł."),
 (1, "s", "Cena wody pitnej jest niska, a diamentów wysoka, mimo że woda jest niezbędna do życia. Marginaliści wyjaśniają to tym, że:",
  ["cena zależy od użyteczności krańcowej, a ta jest dla wody niska z powodu jej obfitości", "woda nie ma wartości użytkowej", "diamenty mają wyższą użyteczność całkowitą", "ceny ustala państwo"], "A",
  "Użyteczność całkowita wody jest ogromna, ale ostatnia jednostka (przy obfitości) daje niewiele; diamenty są rzadkie, więc ich krańcowa użyteczność jest wysoka."),
 (1, "s", "Konsument kupił za 200 zł bilet na mecz, ale w dniu meczu woli zostać w domu. Według teorii racjonalnych decyzji powinien:",
  ["pójść tylko wtedy, gdy korzyść z meczu przewyższa korzyść z alternatywnego wykorzystania czasu, niezależnie od ceny biletu", "pójść, bo zapłacił 200 zł", "sprzedać bilet za więcej niż 200 zł albo zostać w domu bez względu na cenę odsprzedaży", "zawsze iść, bo inaczej marnuje pieniądze"], "A",
  "200 zł to koszt utopiony; rozstrzyga porównanie przyszłych korzyści i kosztów (w tym możliwości odsprzedaży biletu). Kierowanie się wydanymi pieniędzmi to błąd kosztów utopionych."),
 (1, "s", "Zgodnie z prawem malejących przychodów (krańcowej produktywności):",
  ["po przekroczeniu pewnego poziomu nakładu czynnika zmiennego przyrost produkcji z jego kolejnych jednostek maleje", "produkcja zawsze spada, gdy rośnie zatrudnienie", "koszty stałe maleją wraz z produkcją", "podwojenie wszystkich czynników zawsze podwaja produkcję"], "A",
  "Prawo dotyczy krótkiego okresu (co najmniej jeden czynnik stały). Podwojenie wszystkich czynników to kwestia przychodów skali (długi okres)."),
 (1, "s", "Gdy produkt krańcowy pracy jest większy od produktu przeciętnego, to produkt przeciętny:",
  ["rośnie", "maleje", "jest stały", "jest ujemny"], "A",
  "Krańcowa większa od przeciętnej podnosi przeciętną (analogicznie do średniej ocen podnoszonej przez lepszą ocenę)."),
 (1, "s", "Izokwanta to krzywa przedstawiająca:",
  ["kombinacje nakładów pracy i kapitału dające tę samą wielkość produkcji", "kombinacje dóbr dające tę samą użyteczność", "kombinacje nakładów o tym samym koszcie", "zależność kosztu od produkcji"], "A",
  "Izokwanta – jednakowa produkcja; izokoszta – jednakowy koszt; krzywa obojętności – jednakowa użyteczność. Optimum producenta: styczność izokwanty i izokoszty."),
 (1, "s", "Wzrost płacy przy niezmienionej cenie kapitału spowoduje, że firma minimalizująca koszty (w długim okresie):",
  ["zastąpi część pracy kapitałem", "zatrudni więcej pracowników", "nie zmieni proporcji czynników", "zmniejszy ilość kapitału"], "A",
  "Zmienia się nachylenie izokoszty (w/r) – nowe optimum wykorzystuje względnie więcej taniejącego czynnika (kapitału): efekt substytucji czynników."),
 (1, "s", "Długookresowa krzywa kosztu przeciętnego opada, gdy w firmie występują:",
  ["rosnące przychody skali (korzyści skali)", "malejące przychody skali", "stałe przychody skali", "rosnące koszty stałe"], "A",
  "Rosnące przychody skali oznaczają, że produkcja rośnie szybciej niż nakłady, więc koszt jednostkowy spada; malejące – LAC rośnie; stałe – LAC poziomy."),
 (1, "s", "Minimalna efektywna skala produkcji (MES) to:",
  ["najmniejsza wielkość produkcji, przy której długookresowy koszt przeciętny osiąga minimum", "produkcja, przy której zysk jest maksymalny", "produkcja potrzebna do pokrycia kosztów stałych", "maksymalna zdolność produkcyjna"], "A",
  "Jeśli MES jest duża w stosunku do rynku, na rynku zmieści się niewiele firm (oligopol lub monopol naturalny)."),
 (1, "s", "W grze dwóch firm reklama jest strategią dominującą dla obu, choć bez reklam obie miałyby wyższe zyski. Taka sytuacja to:",
  ["dylemat więźnia", "równowaga kooperacyjna", "gra o sumie zerowej", "strategia mieszana"], "A",
  "Indywidualnie racjonalny wybór (reklamować) daje wynik gorszy dla obu niż współpraca – stąd np. zakazy reklam papierosów mogą zwiększać zyski branży."),
 (1, "s", "Przywództwo cenowe w oligopolu polega na tym, że:",
  ["jedna firma ustala cenę, a pozostałe ją naśladują", "państwo ustala cenę maksymalną", "firmy podpisują jawną umowę kartelową", "cenę ustala giełda"], "A",
  "Forma zmowy milczącej – firmy dostosowują się do lidera (często największej lub najtańszej firmy) bez formalnego porozumienia."),
 (1, "s", "Reklama i markowanie produktów są najbardziej typowe dla:",
  ["konkurencji monopolistycznej i oligopolu", "konkurencji doskonałej", "rynku z jednorodnym produktem rolniczym", "monopolu naturalnego wody"], "A",
  "Przy zróżnicowanych produktach firma reklamą zwiększa popyt i obniża jego elastyczność; w konkurencji doskonałej reklama pojedynczej firmy nie ma sensu."),
 (1, "s", "Firma jest „cenobiorcą”, jeśli:",
  ["nie ma wpływu na cenę rynkową i przyjmuje ją jako daną", "sama ustala cenę", "jest jedynym nabywcą", "działa w oligopolu"], "A",
  "Cenobiorcami są firmy w konkurencji doskonałej (pozioma krzywa popytu). Cenodawcami – monopol, oligopol, konkurencja monopolistyczna."),
 (1, "s", "Krańcowy przychód z pracy wynosi 60 zł/h, a płaca rynkowa 45 zł/h. Firma na konkurencyjnym rynku pracy powinna:",
  ["zwiększać zatrudnienie", "zmniejszać zatrudnienie", "pozostawić zatrudnienie bez zmian", "obniżyć płacę"], "A",
  "MRP > w – kolejna godzina pracy zwiększa zysk; zatrudnienie rośnie, aż (wskutek malejącej produktywności) MRP spadnie do 45 zł."),
 (1, "s", "Wynagrodzenie piłkarza wynosi 2 mln zł rocznie, a w najlepszym alternatywnym zajęciu zarobiłby 100 tys. zł. Renta ekonomiczna wynosi:",
  ["1,9 mln zł", "2 mln zł", "100 tys. zł", "2,1 mln zł"], "A",
  "Renta = dochód − dochód transferowy (minimum zatrzymujące czynnik w zastosowaniu) = 2 mln − 0,1 mln = 1,9 mln zł."),
 (1, "s", "Obligacja dająca 500 zł odsetek rocznie bezterminowo (wieczysta) przy stopie procentowej 5% jest warta:",
  ["10 000 zł", "500 zł", "25 000 zł", "5000 zł"], "A",
  "Wartość renty wieczystej = C/r = 500/0,05 = 10 000 zł. Tak samo wycenia się np. ziemię dającą stały czynsz (kapitalizacja renty)."),
 (1, "s", "Optimum Pareto oznacza stan, w którym:",
  ["nie można poprawić sytuacji nikogo bez pogorszenia sytuacji kogoś innego", "dochody wszystkich są równe", "państwo maksymalizuje dochody budżetu", "wszyscy mają maksymalną użyteczność"], "A",
  "Efektywność w sensie Pareto nie mówi nic o sprawiedliwości podziału – wiele podziałów może być efektywnych."),
 (1, "s", "Ekonomia behawioralna wskazuje, że ludzie wolą otrzymać 100 zł dziś niż 110 zł za tydzień, ale 110 zł za 53 tygodnie zamiast 100 zł za 52 tygodnie. Zjawisko to nazywa się:",
  ["dyskontowaniem hiperbolicznym (niespójnością czasową)", "awersją do strat", "efektem posiadania", "heurystyką dostępności"], "A",
  "Ludzie silnie przeceniają teraźniejszość w krótkim horyzoncie, ale nie w dalekim – co tłumaczy np. odkładanie oszczędzania. Remedium: automatyczne zapisy (nudge)."),
 (1, "s", "Osoba domaga się 50 zł za kubek, który dostała w prezencie, choć sama kupiłaby taki kubek najwyżej za 20 zł. To:",
  ["efekt posiadania (endowment effect)", "efekt Veblena", "pokusa nadużycia", "efekt substytucyjny"], "A",
  "Efekt posiadania (R. Thaler, D. Kahneman) – ludzie bardziej cenią rzeczy, które już posiadają; związany z awersją do strat."),
 (1, "s", "Domyślne zapisanie pracownika do PPK z możliwością rezygnacji jest przykładem zastosowania:",
  ["teorii szturchania (nudge)", "podatku Pigou", "kontroli cen", "dyskryminacji cenowej"], "A",
  "Architektura wyboru (opcja domyślna) zwiększa uczestnictwo bez przymusu – koncepcja R. Thalera i C. Sunsteina."),
 (1, "s", "Inwestor sprzedaje akcje, które zyskały, a trzyma te, które straciły, licząc na „odbicie”. To:",
  ["efekt dyspozycji", "efekt skali", "teoria portfela", "arbitraż"], "A",
  "Efekt dyspozycji wynika z awersji do realizowania strat (teoria perspektywy Kahnemana i Tversky’ego)."),
 (1, "s", "Gospodarka, w której o tym, co, jak i dla kogo produkować, decydują głównie decyzje centralnego planisty, to gospodarka:",
  ["centralnie planowana (nakazowo-rozdzielcza)", "rynkowa", "mieszana", "tradycyjna"], "A",
  "W gospodarce planowej ceny ustala państwo – typowe są niedobory i kolejki (J. Kornai – „gospodarka niedoboru”)."),
 (1, "s", "Krzywa podaży rynkowej powstaje przez:",
  ["poziome zsumowanie krzywych podaży poszczególnych producentów", "pionowe zsumowanie cen", "uśrednienie kosztów", "odjęcie popytu od podaży"], "A",
  "Przy każdej cenie sumuje się ilości oferowane przez wszystkie firmy (sumowanie poziome). Pionowe sumowanie stosuje się do popytu na dobra publiczne."),
 (1, "s", "Gotowość mieszkańców do zapłaty za park miejski wynosi odpowiednio 30, 20 i 10 zł miesięcznie. Krańcowa korzyść społeczna z parku (dobra publicznego) to:",
  ["60 zł", "30 zł", "20 zł", "10 zł"], "A",
  "Dla dobra publicznego wszyscy korzystają z tej samej ilości, więc korzyści sumuje się pionowo: 30 + 20 + 10 = 60 zł."),
 (1, "s", "Inflacja kosztów sprawiła, że ceny wszystkich dóbr i dochody wzrosły o 10%. Ceny względne:",
  ["nie zmieniły się", "wzrosły o 10%", "spadły o 10%", "wzrosły o 21%"], "A",
  "Ceny względne to relacje cen dóbr. Przy proporcjonalnym wzroście wszystkich cen relacje się nie zmieniają."),
 (1, "s", "W pewnej branży powstał kartel. Nowy członek, który potajemnie zwiększa produkcję ponad przydział, w krótkim okresie:",
  ["zwiększa swój zysk, ale obniża cenę i zyski pozostałych", "obniża swój zysk", "nie wpływa na rynek", "podnosi cenę rynkową"], "A",
  "Bodziec do oszukiwania wynika z tego, że cena kartelowa przewyższa koszt krańcowy – dodatkowa sprzedaż jest dla oszukującego opłacalna."),
 # --- wielokrotny wybór ---
 (1, "m", "Które z poniższych czynników zwiększą popyt na mieszkania w dużym mieście?",
  ["Spadek oprocentowania kredytów hipotecznych", "Napływ studentów i pracowników", "Wzrost czynszów najmu (substytutu kupna)", "Wzrost ceny samych mieszkań"], "ABC",
  "Kredyt i mieszkania są komplementarne, więc tańszy kredyt zwiększa popyt; tak samo napływ ludności i droższy najem. Wzrost ceny mieszkań to ruch wzdłuż krzywej popytu."),
 (1, "m", "Które stwierdzenia są poprawne dla dobra o popycie doskonale elastycznym?",
  ["Krzywa popytu jest pozioma", "Niewielki wzrost ceny powoduje spadek popytu do zera", "Ciężar podatku ponosi w całości sprzedawca", "Krzywa popytu jest pionowa"], "ABC",
  "Pozioma krzywa popytu (|Ed| → ∞) dotyczy np. pojedynczej firmy w konkurencji doskonałej. Nabywcy nie zaakceptują wyższej ceny, więc ciężar podatku przechodzi na sprzedawców."),
 (1, "m", "Które czynniki zmniejszą podaż jabłek (przesuną krzywą w lewo)?",
  ["Przymrozki niszczące część upraw", "Wzrost płac pracowników sezonowych", "Dopłaty do produkcji owoców", "Spadek ceny jabłek"], "AB",
  "Przymrozki i wyższe koszty pracy ograniczają podaż; dopłaty ją zwiększają, a spadek ceny powoduje ruch wzdłuż krzywej."),
 (1, "m", "Państwo ustala maksymalną cenę benzyny poniżej równowagi. Jakie są typowe skutki?",
  ["Niedobór paliwa i kolejki na stacjach", "Pojawienie się czarnego rynku", "Nadwyżka paliwa na stacjach", "Spadek motywacji dostawców do zwiększania podaży"], "ABD",
  "Cena maksymalna poniżej równowagi zwiększa wielkość popytu i zmniejsza wielkość podaży – powstają niedobory, kolejki, reglamentacja i czarny rynek."),
 (1, "m", "Które z poniższych wielkości są zawsze stałe w krótkim okresie?",
  ["Koszty stałe całkowite", "Koszt krańcowy", "Przeciętny koszt stały", "Liczba maszyn w zakładzie (czynnik stały)"], "AD",
  "Koszty stałe całkowite i nakład czynnika stałego nie zmieniają się w krótkim okresie. AFC = FC/Q maleje, a MC zmienia się z produkcją."),
 (1, "m", "Kiedy krzywa popytu na produkt monopolisty i jego krzywa utargu krańcowego są liniowe, prawdziwe jest, że:",
  ["krzywa MR ma dwukrotnie większe nachylenie niż krzywa popytu", "MR przecina oś ilości w połowie odległości od punktu przecięcia popytu z tą osią", "MR leży powyżej krzywej popytu", "MR = 0 tam, gdzie |Ed| = 1"], "ABD",
  "Dla P = a − bQ: MR = a − 2bQ. MR leży zawsze poniżej popytu (dla Q > 0)."),
 (1, "m", "Które cechy dotyczą konkurencji monopolistycznej?",
  ["Wiele firm", "Zróżnicowane produkty", "Brak barier wejścia w długim okresie", "Jedna firma kontroluje cały rynek"], "ABC",
  "To struktura łącząca cechy monopolu (opadający popyt firmy, marka) i konkurencji (wiele firm, swobodne wejście)."),
 (1, "m", "Które stwierdzenia o zysku normalnym są prawdziwe?",
  ["Jest kosztem alternatywnym kapitału i pracy właściciela", "Jest wliczany do kosztów ekonomicznych", "Gdy zysk ekonomiczny = 0, firma osiąga zysk normalny", "Oznacza, że zysk księgowy jest równy zeru"], "ABC",
  "Zysk ekonomiczny = 0 oznacza, że zysk księgowy wystarcza dokładnie na pokrycie kosztów ukrytych (zysk normalny), a więc zysk księgowy jest dodatni."),
 (1, "m", "Które sytuacje są przykładami pozytywnych efektów zewnętrznych?",
  ["Pszczelarz, którego pszczoły zapylają sad sąsiada", "Edukacja zwiększająca innowacyjność całego społeczeństwa", "Remont elewacji podnoszący wartość sąsiednich domów", "Hałas z lotniska"], "ABC",
  "Korzyści odnoszą osoby niebędące stronami transakcji. Hałas to negatywny efekt zewnętrzny."),
 (1, "m", "Które z poniższych są założeniami modelu konkurencji doskonałej?",
  ["Pełna informacja", "Jednorodny produkt", "Swoboda wejścia i wyjścia", "Opadająca krzywa popytu przed pojedynczą firmą"], "ABC",
  "Pojedyncza firma ma poziomą krzywą popytu (jest cenobiorcą)."),
 (1, "m", "Które odpowiedzi są przykładami asymetrii informacji?",
  ["Sprzedawca używanego auta zna jego wady lepiej niż kupujący", "Kredytobiorca zna swoje zamiary spłaty lepiej niż bank", "Pracownik zna własną pracowitość lepiej niż pracodawca", "Obaj uczestnicy giełdy widzą te same notowania w czasie rzeczywistym"], "ABC",
  "Asymetria informacji – jedna strona wie więcej; jednakowy dostęp do notowań to symetria informacji."),
 (1, "m", "Które z poniższych ilustrują błędy poznawcze opisywane przez ekonomię behawioralną?",
  ["Efekt zakotwiczenia – kierowanie się pierwszą usłyszaną liczbą", "Nadmierna pewność siebie inwestorów", "Awersja do strat", "Maksymalizacja oczekiwanej użyteczności przy pełnej informacji"], "ABC",
  "Ostatni opis to model racjonalnego homo oeconomicus, który ekonomia behawioralna krytykuje."),
 (1, "m", "Które stwierdzenia o krzywej możliwości produkcyjnych są prawdziwe?",
  ["Ilustruje rzadkość zasobów i koszt alternatywny", "Wzrost zasobów pracy przesuwa ją na zewnątrz", "Punkty poza krzywą są osiągalne przy obecnych zasobach", "Bezrobocie oznacza produkcję wewnątrz krzywej"], "ABD",
  "Punkty poza krzywą są nieosiągalne przy danych zasobach i technologii (mogą stać się osiągalne dzięki handlowi lub wzrostowi gospodarczemu)."),
 (1, "m", "Które twierdzenia o elastyczności cenowej popytu są prawdziwe?",
  ["Przy popycie elastycznym obniżka ceny zwiększa utarg", "Przy popycie nieelastycznym obniżka ceny zmniejsza utarg", "Przy elastyczności jednostkowej zmiana ceny nie zmienia utargu", "Elastyczność jest zawsze równa nachyleniu krzywej popytu"], "ABC",
  "Elastyczność zależy od nachylenia i punktu na krzywej (P/Q), więc nie jest równa nachyleniu."),
 (1, "m", "Które z poniższych mogą być źródłem monopolu?",
  ["Wyłączna kontrola nad kluczowym surowcem", "Patent lub prawo autorskie", "Koncesja lub licencja państwowa", "Duża liczba małych konkurentów"], "ABC",
  "Do źródeł monopolu należą też korzyści skali (monopol naturalny) i efekty sieciowe. Duża liczba konkurentów oznacza brak monopolu."),
 (1, "m", "Które zjawiska wynikają z efektów sieciowych (wartość dobra rośnie z liczbą użytkowników)?",
  ["Dominacja jednej platformy społecznościowej", "Trudność wejścia nowego komunikatora na rynek", "Tendencja do standaryzacji (np. jeden format płatności)", "Rosnący koszt krańcowy obsługi kolejnego użytkownika"], "ABC",
  "Efekty sieciowe sprzyjają koncentracji („zwycięzca bierze wszystko”) i stanowią barierę wejścia. Koszt krańcowy obsługi użytkownika w platformach cyfrowych jest zwykle niski."),
 (1, "m", "Które stwierdzenia o dobrach publicznych są prawdziwe?",
  ["Rynek prywatny dostarcza ich zwykle za mało", "Ich finansowanie z podatków ogranicza problem gapowicza", "Są zawsze wytwarzane przez państwo", "Korzyści z nich sumuje się pionowo"], "ABD",
  "Państwo zapewnia finansowanie, ale wytwarzać dobra publiczne mogą firmy prywatne (np. budowa dróg na zlecenie)."),
 (1, "m", "Które z poniższych są przykładami substytutów?",
  ["Masło i margaryna", "Pociąg i autokar na tej samej trasie", "Samochód i benzyna", "Kawa i herbata"], "ABD",
  "Samochód i benzyna to dobra komplementarne."),
 (1, "m", "Które czynniki zwiększają elastyczność podaży?",
  ["Dłuższy okres na dostosowanie produkcji", "Możliwość magazynowania produktu", "Wolne moce produkcyjne", "Unikalny, nieodtwarzalny charakter dobra (np. obraz mistrza)"], "ABC",
  "Unikalne dobra mają podaż doskonale nieelastyczną."),
 (1, "m", "Firma w konkurencji doskonałej w krótkim okresie osiąga P = MC = 12 zł, ATC = 14 zł, AVC = 10 zł. Które stwierdzenia są prawdziwe?",
  ["Firma ponosi stratę 2 zł na każdej sztuce", "Firma powinna kontynuować produkcję w krótkim okresie", "W długim okresie część firm opuści branżę", "Firma osiąga zysk ekonomiczny"], "ABC",
  "P < ATC – strata; P > AVC – produkcja ogranicza stratę; w długim okresie wyjście firm podniesie cenę do min ATC."),
]
