# -*- coding: utf-8 -*-
# Dział 2 – Makroekonomia, partia 2
M = [
 (2, "s", "W gospodarce wynagrodzenia wynoszą 500, nadwyżka operacyjna i dochody mieszane 350, podatki od produkcji i importu 150, dotacje 20. PKB metodą dochodową wynosi:",
  ["980", "1000", "1020", "850"], "A",
  "PKB = koszty pracy + nadwyżka operacyjna brutto i dochody mieszane + podatki od produkcji i importu − dotacje = 500 + 350 + 150 − 20 = 980."),
 (2, "s", "Wartość produkcji globalnej firm wynosi 2400, a zużycie pośrednie 1300; podatki od produktów minus dotacje do produktów to 150. PKB metodą produkcyjną wynosi:",
  ["1250", "1100", "3700", "2550"], "A",
  "Wartość dodana brutto = 2400 − 1300 = 1100; PKB = 1100 + 150 = 1250."),
 (2, "s", "PKB wynosi 2000, dochody rezydentów z zagranicy 60, dochody nierezydentów uzyskane w kraju 110, amortyzacja 250. Produkt narodowy brutto (DNB) wynosi:",
  ["1950", "2050", "1700", "2170"], "A",
  "PNB = PKB + dochody rezydentów z zagranicy − dochody nierezydentów w kraju = 2000 + 60 − 110 = 1950 (typowe dla krajów z dużym kapitałem zagranicznym, jak Polska: PNB < PKB). PNN = 1950 − 250 = 1700."),
 (2, "s", "Realny PKB na mieszkańca wzrósł z 50 000 do 52 000 zł, a liczba ludności spadła o 1%. Realny PKB całej gospodarki wzrósł o około:",
  ["3%", "4%", "5%", "1%"], "A",
  "PKB per capita +4%, ludność −1%: PKB = per capita · ludność ⇒ 1,04 · 0,99 ≈ 1,0296 – wzrost ok. 3%."),
 (2, "s", "Który z poniższych wydatków zostanie zaliczony do inwestycji (I) w rachunku PKB?",
  ["Zakup nowej koparki przez firmę budowlaną", "Zakup akcji spółki giełdowej przez gospodarstwo domowe", "Zakup używanego mieszkania od osoby prywatnej", "Wypłata zasiłku dla bezrobotnych"], "A",
  "Inwestycje w PKB to nakłady na nowe dobra kapitałowe, budownictwo mieszkaniowe i przyrost zapasów. Zakup akcji to inwestycja finansowa (zmiana właściciela), używane mieszkanie wytworzono wcześniej, zasiłek to transfer."),
 (2, "s", "Firma wyprodukowała w 2025 r. towary za 100 mln zł, z czego sprzedała 80 mln zł, a 20 mln zł trafiło do magazynu. Do PKB 2025 r. wliczy się:",
  ["100 mln zł (sprzedaż 80 mln zł + przyrost zapasów 20 mln zł)", "80 mln zł", "20 mln zł", "nic, dopóki towary nie zostaną sprzedane"], "A",
  "PKB mierzy produkcję danego roku; niesprzedana produkcja jest ujmowana jako przyrost zapasów (część inwestycji). Sprzedaż z magazynu w kolejnym roku nie zwiększy PKB tego roku."),
 (2, "s", "Wzrost PKB nie uwzględnia m.in.:",
  ["wartości czasu wolnego i pracy domowej nieodpłatnej", "produkcji dóbr inwestycyjnych", "usług publicznych (wycenianych kosztami)", "eksportu usług"], "A",
  "PKB pomija pracę nieodpłatną, czas wolny, szarą strefę (częściowo szacowaną), degradację środowiska i rozkład dochodów – dlatego stosuje się też HDI i inne miary dobrobytu."),
 (2, "s", "Wskaźnik HDI (Human Development Index) uwzględnia:",
  ["dochód na mieszkańca, oczekiwaną długość życia i poziom wykształcenia", "PKB, inflację i bezrobocie", "nierówności dochodowe i emisję CO₂", "dług publiczny i deficyt"], "A",
  "HDI publikuje UNDP od 1990 r. (koncepcja M. ul Haqa i A. Sena): zdrowie, edukacja (lata nauki), standard życia (DNB per capita wg PPP)."),
 (2, "s", "W modelu Keynesa wydatki autonomiczne wynoszą 200, a krańcowa skłonność do konsumpcji 0,6 (gospodarka zamknięta, bez podatków). Dochód równowagi wynosi:",
  ["500", "333", "120", "1200"], "A",
  "Y = A / (1 − c) = 200 / 0,4 = 500."),
 (2, "s", "Funkcja konsumpcji ma postać C = 100 + 0,75Yd. Przy dochodzie rozporządzalnym 1000 oszczędności wynoszą:",
  ["150", "250", "850", "100"], "A",
  "C = 100 + 750 = 850; S = Yd − C = 150. Funkcja oszczędności: S = −100 + 0,25Yd."),
 (2, "s", "Gospodarka otwarta: krańcowa skłonność do konsumpcji 0,9, stopa podatku dochodowego 20%, krańcowa skłonność do importu 0,22. O ile wzrośnie dochód narodowy, jeśli eksport wzrośnie o 30 mld zł?",
  ["60 mld zł", "300 mld zł", "107 mld zł", "75 mld zł"], "A",
  "k = 1 / [1 − c(1 − t) + m] = 1 / [1 − 0,9 · 0,8 + 0,22] = 1 / 0,5 = 2; ΔY = 2 · 30 = 60 mld zł. Import i podatki to „przecieki” zmniejszające mnożnik."),
 (2, "s", "Rząd obniża podatki kwotowe o 20 mld zł przy krańcowej skłonności do konsumpcji 0,8 (gospodarka zamknięta). Dochód wzrośnie o:",
  ["80 mld zł", "100 mld zł", "20 mld zł", "16 mld zł"], "A",
  "Mnożnik podatkowy = c/(1 − c) = 0,8/0,2 = 4 (co do wartości bezwzględnej); ΔY = 4 · 20 = 80 mld zł – mniej niż przy wzroście wydatków o tę samą kwotę (100 mld zł), bo część obniżki ludzie oszczędzają."),
 (2, "s", "Paradoks zapobiegliwości w modelu Keynesa oznacza, że wzrost skłonności do oszczędzania przy stałych inwestycjach:",
  ["obniża dochód, a łączne oszczędności pozostają takie same", "zwiększa dochód i oszczędności", "zwiększa inwestycje", "nie wpływa na dochód"], "A",
  "W równowadze S = I. Jeśli inwestycje są stałe, wyższa skłonność do oszczędzania zmniejsza popyt i dochód, aż oszczędności wrócą do poziomu inwestycji."),
 (2, "s", "Dochód równowagi wynosi 900, a dochód potencjalny 1000. Krańcowa skłonność do konsumpcji 0,8 (gospodarka zamknięta). Aby osiągnąć pełne zatrudnienie, rząd powinien zwiększyć wydatki o:",
  ["20", "100", "80", "500"], "A",
  "Luka recesyjna (deflacyjna) w wydatkach = luka PKB / mnożnik = 100 / 5 = 20."),
 (2, "s", "Akcelerator inwestycyjny oznacza, że:",
  ["inwestycje zależą od zmian (przyrostu) produkcji lub popytu", "konsumpcja zależy od dochodu", "pieniądz przyspiesza obieg", "stopy procentowe rosną z inflacją"], "A",
  "Zasada akceleracji: I = v · ΔY. Połączenie mnożnika i akceleratora (model Samuelsona–Hicksa) wyjaśnia wahania koniunktury."),
 (2, "s", "Według teorii q Tobina firmy zwiększają inwestycje, gdy:",
  ["rynkowa wartość firmy przewyższa koszt odtworzenia jej kapitału (q > 1)", "q < 1", "stopy procentowe rosną", "spada cena akcji"], "A",
  "q = wartość rynkowa / koszt odtworzenia aktywów. q > 1 – opłaca się tworzyć nowy kapitał (emitować akcje i inwestować)."),
 (2, "s", "Stopa bezrobocia wynosi 6%, a naturalna 4%. W kraju występuje przede wszystkim bezrobocie:",
  ["cykliczne (koniunkturalne)", "frykcyjne", "sezonowe", "dobrowolne"], "A",
  "Bezrobocie ponad naturalną stopę (frykcyjne + strukturalne) to bezrobocie cykliczne – wynik niedostatecznego popytu w recesji."),
 (2, "s", "Wprowadzenie hojnych i długotrwałych zasiłków dla bezrobotnych może według teorii ekonomii:",
  ["wydłużyć czas poszukiwania pracy i podnieść bezrobocie frykcyjne", "obniżyć naturalną stopę bezrobocia", "wyeliminować bezrobocie strukturalne", "nie mieć wpływu na rynek pracy"], "A",
  "Zasiłki obniżają koszt pozostawania bez pracy – podnoszą płacę progową i wydłużają poszukiwania (choć mogą też poprawiać dopasowanie pracownika do stanowiska)."),
 (2, "s", "Płace efektywnościowe to płace ustalane przez firmy:",
  ["powyżej poziomu równowagi, aby zwiększyć wydajność i lojalność pracowników", "na poziomie płacy minimalnej", "przez związki zawodowe", "według stażu pracy"], "A",
  "Wyższa płaca ogranicza rotację, przyciąga lepszych kandydatów i zwiększa koszt utraty pracy (mniejsza pokusa obijania się) – wyjaśnienie bezrobocia przymusowego w nowej ekonomii keynesowskiej."),
 (2, "s", "Histereza bezrobocia oznacza, że:",
  ["długotrwałe bezrobocie podnosi naturalną stopę bezrobocia (utrata kwalifikacji, wypadanie z rynku)", "bezrobocie zależy od pory roku", "bezrobocie spada wraz z inflacją", "płace są sztywne w dół"], "A",
  "Wysokie bezrobocie z recesji może się utrwalić – bezrobotni tracą umiejętności i kontakty, a zatrudnieni (insiderzy) negocjują płace bez uwzględnienia bezrobotnych (outsiderów)."),
 (2, "s", "Inflacja popytowa powstaje, gdy:",
  ["zagregowany popyt rośnie szybciej niż możliwości produkcyjne gospodarki", "drożeją surowce energetyczne", "rosną płace ponad wydajność pracy", "słabnie waluta krajowa"], "A",
  "Popytowa – przesunięcie AD w prawo (np. ekspansja fiskalna, szybki wzrost kredytu). Drożejąca energia, płace i słabsza waluta to źródła inflacji kosztowej (podażowej)."),
 (2, "s", "Spirala płacowo-cenowa polega na tym, że:",
  ["wzrost cen skłania pracowników do żądania podwyżek, a podwyżki płac podnoszą koszty i ceny", "spadek cen powoduje spadek płac i dalszy spadek cen", "bank centralny podnosi stopy w odpowiedzi na wzrost płac", "płace realne są stałe"], "A",
  "Mechanizm utrwalania inflacji poprzez oczekiwania i indeksację; przerwanie spirali wymaga wiarygodnej polityki pieniężnej (kotwiczenie oczekiwań)."),
 (2, "s", "Koszty „zdartych butów” (shoe-leather costs) inflacji to:",
  ["koszty częstszych wizyt w banku i ograniczania gotówki, gdy inflacja jest wysoka", "koszty drukowania nowych cenników", "spadek realnej wartości oszczędności", "redystrybucja od wierzycieli do dłużników"], "A",
  "Wysoka inflacja to podatek od trzymania gotówki – ludzie starają się trzymać jej mniej, co pochłania czas i zasoby. Zmiana cenników to koszty menu."),
 (2, "s", "Deflacja może być szkodliwa dla gospodarki, ponieważ:",
  ["konsumenci odkładają zakupy w oczekiwaniu na dalsze spadki cen, a realne obciążenie długów rośnie", "zawsze obniża bezrobocie", "zwiększa realną wartość długów na korzyść dłużników", "obniża realne stopy procentowe"], "A",
  "Spirala deflacyjna (I. Fisher – deflacja długów): spadek cen zwiększa realną wartość długu i realną stopę procentową, osłabia popyt i inwestycje (Japonia lat 90., Wielki Kryzys)."),
 (2, "s", "Inflacja bazowa różni się od inflacji CPI tym, że:",
  ["wyłącza ceny najbardziej zmienne (np. żywności i energii)", "obejmuje tylko usługi", "jest liczona dla dóbr inwestycyjnych", "jest zawsze wyższa od CPI"], "A",
  "Inflacja bazowa (NBP publikuje kilka miar, główną – bez cen żywności i energii) pokazuje trwałe tendencje cenowe, na które może wpływać polityka pieniężna."),
 (2, "s", "Krótkookresowa krzywa Phillipsa przesuwa się w górę, gdy:",
  ["rosną oczekiwania inflacyjne", "spada podaż pieniądza", "rośnie wydajność pracy", "spadają ceny ropy"], "A",
  "Wg Friedmana i Phelpsa: π = πᵉ − β(u − u*). Wyższe oczekiwania inflacyjne podnoszą inflację przy każdym poziomie bezrobocia; negatywne szoki podażowe działają podobnie."),
 (2, "s", "Wskaźnik poświęcenia (sacrifice ratio) mierzy:",
  ["ile procent rocznego PKB trzeba utracić, aby obniżyć inflację o 1 pkt proc.", "ile wynosi deficyt potrzebny do obniżenia bezrobocia", "relację długu do PKB", "koszty wymiany waluty"], "A",
  "Dezinflacja ma koszt w postaci przejściowego spadku produkcji; wiarygodna polityka pieniężna (racjonalne oczekiwania) może go zmniejszyć."),
 (2, "s", "Model AD–AS: rząd zwiększa wydatki, gdy gospodarka działa powyżej produktu potencjalnego. W długim okresie skutkiem będzie przede wszystkim:",
  ["wyższy poziom cen przy produkcji powracającej do potencjalnej", "trwale wyższa produkcja", "niższy poziom cen", "wyższe bezrobocie"], "A",
  "Długookresowa AS jest pionowa na poziomie produktu potencjalnego – ekspansja popytu poza nim przekłada się na inflację (płace i oczekiwania się dostosowują)."),
 (2, "s", "Która zmiana przesuwa długookresową krzywą AS w prawo?",
  ["Wzrost zasobu kapitału i postęp techniczny", "Wzrost podaży pieniądza", "Wzrost wydatków rządowych na transfery", "Wzrost oczekiwanej inflacji"], "A",
  "Długookresowa AS zależy od zasobów (praca, kapitał, ziemia), technologii i instytucji. Czynniki popytowe przesuwają AD."),
 (2, "s", "Recesja techniczna to:",
  ["spadek realnego PKB (kwartał do kwartału) przez co najmniej dwa kolejne kwartały", "wzrost bezrobocia o 2 pkt proc.", "spadek inflacji poniżej zera", "spadek eksportu przez rok"], "A",
  "To umowna definicja; w USA recesje datuje komitet NBER, biorąc pod uwagę szerszy zestaw wskaźników (zatrudnienie, produkcja, dochody)."),
 (2, "s", "Indeks PMI dla przemysłu wynoszący 47 pkt sygnalizuje:",
  ["pogorszenie koniunktury (kurczenie się aktywności) w przemyśle", "ożywienie", "inflację powyżej celu", "stabilizację"], "A",
  "Próg 50 pkt oddziela ekspansję od kurczenia się. PMI to wskaźnik wyprzedzający oparty na ankiecie menedżerów zakupów."),
 (2, "s", "Cykl Juglara (7–11 lat) wiąże się przede wszystkim z:",
  ["inwestycjami w środki trwałe (maszyny, urządzenia)", "zapasami", "budownictwem i demografią", "przełomowymi innowacjami technologicznymi"], "A",
  "Kitchin – zapasy (3–4 lata), Juglar – inwestycje w kapitał trwały, Kuznets – budownictwo (15–25 lat), Kondratiew – długie fale innowacji (40–60 lat)."),
 (2, "s", "Fazy cyklu koniunkturalnego w kolejności to:",
  ["ożywienie, rozkwit (boom), recesja (załamanie), depresja", "depresja, rozkwit, ożywienie, recesja", "recesja, rozkwit, depresja, ożywienie", "rozkwit, ożywienie, depresja, recesja"], "A",
  "Klasyczny podział: ożywienie (wzrost po dnie), rozkwit (szczyt), recesja (spadek), depresja (dno)."),
 (2, "s", "Według teorii politycznego cyklu koniunkturalnego rządy przed wyborami:",
  ["stymulują gospodarkę (np. podwyżki świadczeń), a po wyborach wprowadzają zacieśnienie", "podnoszą podatki", "ograniczają wydatki", "obniżają płacę minimalną"], "A",
  "M. Kalecki (1943), W. Nordhaus (1975): politycy wykorzystują krótkookresową krzywą Phillipsa dla celów wyborczych, co destabilizuje gospodarkę – argument za niezależnym bankiem centralnym i regułami fiskalnymi."),
 (2, "s", "Twierdzenie o ekwiwalencji ricardiańskiej (R. Barro) mówi, że:",
  ["obniżka podatków finansowana długiem nie zwiększa konsumpcji, bo racjonalni podatnicy oszczędzają na przyszłe wyższe podatki", "dług publiczny zawsze zwiększa inflację", "deficyt budżetowy zawsze zwiększa popyt", "podatki pośrednie i bezpośrednie są równoważne"], "A",
  "Jeśli ludzie uwzględniają przyszłe podatki potrzebne na spłatę długu, sposób finansowania wydatków (podatki czy dług) nie wpływa na popyt. Założenia (nieskończony horyzont, brak ograniczeń kredytowych) są w praktyce dyskusyjne."),
 (2, "s", "Niekeynesowskie efekty polityki fiskalnej to sytuacja, w której:",
  ["konsolidacja fiskalna (cięcia deficytu) pobudza wzrost dzięki poprawie zaufania i spadkowi stóp procentowych", "ekspansja fiskalna zawsze zwiększa PKB", "podatki nie wpływają na konsumpcję", "deficyt finansowany jest przez bank centralny"], "A",
  "Przykłady: Dania i Irlandia w latach 80. – wiarygodne ograniczenie deficytu obniżyło premię za ryzyko i stopy, co pobudziło inwestycje i konsumpcję."),
 (2, "s", "Wzrost gospodarczy w modelu Solowa przy stałej technologii zatrzymuje się w stanie ustalonym, ponieważ:",
  ["inwestycje zrównują się z amortyzacją i przyrostem ludności, a krańcowy produkt kapitału maleje", "oszczędności spadają do zera", "rząd ogranicza inwestycje", "ludność przestaje rosnąć"], "A",
  "W stanie ustalonym kapitał na pracownika jest stały (s·f(k) = (δ + n)·k). Wyższa stopa oszczędności podnosi poziom k i y, ale nie trwałe tempo wzrostu."),
 (2, "s", "Złota reguła akumulacji kapitału (E. Phelps) wyznacza stopę oszczędności, która:",
  ["maksymalizuje konsumpcję na pracownika w stanie ustalonym", "maksymalizuje produkcję", "minimalizuje inflację", "zapewnia zerowy deficyt"], "A",
  "Przy zbyt niskich oszczędnościach kapitału jest za mało, przy zbyt wysokich – konsumpcja jest za niska. Optimum: krańcowy produkt kapitału = δ + n."),
 (2, "s", "Teorie wzrostu endogenicznego (P. Romer, R. Lucas) podkreślają rolę:",
  ["kapitału ludzkiego, badań i rozwoju oraz efektów rozprzestrzeniania się wiedzy", "wyłącznie zasobów naturalnych", "przypadkowych szoków technologicznych spoza modelu", "kursu walutowego"], "A",
  "W odróżnieniu od modelu Solowa postęp techniczny wynika z decyzji gospodarczych – polityka (edukacja, B+R, ochrona własności intelektualnej) może wpływać na długookresowe tempo wzrostu."),
 (2, "s", "Pułapka średniego dochodu to sytuacja, w której kraj:",
  ["po osiągnięciu średniego poziomu dochodu traci dotychczasowe źródła wzrostu (tania praca) i nie przechodzi do wzrostu opartego na innowacjach", "ma hiperinflację", "ma zbyt wysoki dług zagraniczny", "traci ludność przez emigrację"], "A",
  "Kraj staje się za drogi, by konkurować tanią pracą, a jeszcze niewystarczająco innowacyjny, by konkurować technologią (przykłady: Ameryka Łacińska); wyzwanie wskazywane także dla Polski."),
 (2, "s", "Teoria cyklu życia Modiglianiego przewiduje, że osoby w wieku emerytalnym:",
  ["konsumują więcej, niż wynoszą ich bieżące dochody (rozszczędzają się)", "oszczędzają najwięcej w swoim życiu", "nie konsumują", "mają najwyższe dochody"], "A",
  "Profil oszczędności ma kształt odwróconego U: młodzi się zadłużają, osoby w wieku produkcyjnym oszczędzają, emeryci konsumują oszczędności – stąd wpływ demografii na oszczędności narodowe."),
 # --- wielokrotny wybór ---
 (2, "m", "Które składniki są uwzględniane w PKB metodą wydatkową jako wydatki rządowe (G)?",
  ["Wynagrodzenia nauczycieli w szkołach publicznych", "Zakup sprzętu wojskowego", "Wypłata emerytur", "Budowa drogi ekspresowej"], "ABD",
  "G obejmuje zakupy dóbr i usług przez sektor publiczny (w tym wynagrodzenia urzędników, nauczycieli, inwestycje publiczne). Emerytury to transfery."),
 (2, "m", "Które czynniki zwiększają naturalną stopę bezrobocia?",
  ["Niedopasowanie kwalifikacji do potrzeb pracodawców", "Wysokie i długotrwałe zasiłki", "Szybki postęp techniczny zmieniający strukturę zatrudnienia", "Ekspansywna polityka pieniężna"], "ABC",
  "Naturalna stopa zależy od czynników strukturalnych i instytucjonalnych; polityka pieniężna wpływa na bezrobocie cykliczne, nie naturalne (w długim okresie)."),
 (2, "m", "Które skutki są typowe dla nieoczekiwanie wysokiej inflacji?",
  ["Redystrybucja majątku od wierzycieli do dłużników", "Spadek realnej wartości oszczędności w gotówce", "Wzrost realnej wartości stałych emerytur", "Zakłócenie sygnałów cenowych"], "ABD",
  "Stałe w ujęciu nominalnym świadczenia tracą realną wartość, a nie zyskują."),
 (2, "m", "Które z poniższych mogą wywołać inflację kosztową?",
  ["Wzrost cen ropy naftowej", "Wzrost płac szybszy niż wzrost wydajności pracy", "Deprecjacja waluty krajowej", "Spadek podaży pieniądza"], "ABC",
  "Spadek podaży pieniądza działa dezinflacyjnie."),
 (2, "m", "Które twierdzenia o produkcie potencjalnym są prawdziwe?",
  ["To produkcja przy naturalnej stopie bezrobocia", "Może rosnąć dzięki inwestycjom i postępowi technicznemu", "Faktyczny PKB nigdy nie może go przekroczyć", "Ujemna luka PKB oznacza produkcję poniżej potencjalnej"], "ABD",
  "Faktyczny PKB może przejściowo przekroczyć potencjalny (dodatnia luka – przegrzanie, presja inflacyjna)."),
 (2, "m", "Które wskaźniki są uznawane za wyprzedzające koniunkturę?",
  ["Nowe zamówienia w przemyśle", "Indeks PMI", "Stopa bezrobocia", "Ceny akcji"], "ABD",
  "Bezrobocie jest zwykle wskaźnikiem opóźnionym (firmy zwalniają i zatrudniają z opóźnieniem)."),
 (2, "m", "Które działania zalicza się do polityki podażowej?",
  ["Obniżanie stawek podatków od pracy i kapitału", "Deregulacja i upraszczanie przepisów", "Inwestycje w edukację i szkolenia", "Zwiększenie transferów socjalnych w celu pobudzenia popytu"], "ABC",
  "Polityka podażowa zwiększa potencjał produkcyjny (długookresową AS); stymulowanie popytu transferami to polityka popytowa."),
 (2, "m", "Które czynniki mogą wywołać negatywny szok podażowy?",
  ["Gwałtowny wzrost cen energii", "Klęska żywiołowa niszcząca infrastrukturę", "Zakłócenia łańcuchów dostaw", "Spadek stóp procentowych"], "ABC",
  "Spadek stóp działa po stronie popytu (pobudza AD)."),
 (2, "m", "Które twierdzenia o nowej ekonomii klasycznej są prawdziwe?",
  ["Zakłada racjonalne oczekiwania", "Przewidywalna polityka pieniężna nie wpływa na produkcję realną", "Ceny i płace są elastyczne, rynki się oczyszczają", "Zaleca aktywne „dostrajanie” koniunktury przez państwo"], "ABC",
  "Aktywne dostrajanie popytu zalecają keynesiści."),
 (2, "m", "Które z poniższych są założeniami keynesizmu?",
  ["Gospodarka może długo pozostawać w równowadze przy niepełnym zatrudnieniu", "Płace nominalne są sztywne w dół", "Popyt efektywny wyznacza poziom produkcji w krótkim okresie", "Prawo Saya obowiązuje zawsze"], "ABC",
  "Keynes odrzucił prawo Saya – podaż nie gwarantuje wystarczającego popytu."),
 (2, "m", "Które z poniższych mierników opisują nierówności lub ubóstwo?",
  ["Stopa ubóstwa skrajnego (poniżej minimum egzystencji)", "Współczynnik Giniego", "Stopa zagrożenia ubóstwem relatywnym (60% mediany dochodu)", "Inflacja bazowa"], "ABC",
  "Inflacja bazowa to miara dynamiki cen."),
 (2, "m", "Które twierdzenia o PKB według parytetu siły nabywczej (PPP) są prawdziwe?",
  ["Uwzględnia różnice poziomu cen między krajami", "Lepiej porównuje poziom życia niż PKB po kursie rynkowym", "Dla krajów biedniejszych jest zwykle wyższy niż PKB po kursie rynkowym", "Zawsze równa się PKB nominalnemu w dolarach"], "ABC",
  "W krajach biedniejszych usługi są tańsze, więc po przeliczeniu według PPP PKB jest wyższy niż według kursu rynkowego."),
 (2, "m", "Które cechy dotyczą automatycznych stabilizatorów, a które polityki dyskrecjonalnej? Zaznacz zdania prawdziwe.",
  ["Progresywny PIT jest automatycznym stabilizatorem", "Pakiet antykryzysowy uchwalony przez parlament to polityka dyskrecjonalna", "Automatyczne stabilizatory wymagają nowej ustawy przy każdej recesji", "Polityka dyskrecjonalna działa z opóźnieniami decyzyjnymi"], "ABD",
  "Stabilizatory działają bez nowych decyzji – to ich główna zaleta (brak opóźnień decyzyjnych)."),
 (2, "m", "Które stwierdzenia o krzywej Phillipsa są zgodne z poglądami Friedmana i Phelpsa?",
  ["W długim okresie krzywa jest pionowa", "Trwałe obniżenie bezrobocia poniżej naturalnego wymaga przyspieszającej inflacji", "Oczekiwania inflacyjne przesuwają krzywą krótkookresową", "Można trwale wybrać niższe bezrobocie za cenę stałej, wyższej inflacji"], "ABC",
  "Ostatnie zdanie opisuje pierwotną (keynesowską) interpretację krzywej, którą Friedman i Phelps odrzucili."),
 (2, "m", "Które czynniki sprzyjały wysokiemu tempu wzrostu gospodarczego Polski po 1990 r.?",
  ["Napływ bezpośrednich inwestycji zagranicznych", "Członkostwo w UE i dostęp do jednolitego rynku", "Fundusze unijne", "Zamknięcie gospodarki na handel zagraniczny"], "ABC",
  "Otwarcie na handel, inwestycje i integracja z UE były kluczowe; zamknięcie gospodarki działałoby przeciwnie."),
 (2, "m", "Które zjawiska zwiększają krańcową skłonność do konsumpcji w gospodarce?",
  ["Przesunięcie dochodów do gospodarstw o niższych dochodach", "Łatwiejszy dostęp do kredytu konsumpcyjnego", "Wzrost niepewności co do przyszłych dochodów", "Rosnące zaufanie konsumentów"], "ABD",
  "Niepewność skłania do oszczędności ostrożnościowych – zmniejsza skłonność do konsumpcji."),
 (2, "m", "Które z poniższych mogą zmniejszyć wartość mnożnika wydatków?",
  ["Wyższa stopa podatkowa", "Wyższa krańcowa skłonność do importu", "Wyższa krańcowa skłonność do konsumpcji", "Efekt wypychania przez rosnące stopy procentowe"], "ABD",
  "Wyższa skłonność do konsumpcji zwiększa mnożnik."),
 (2, "m", "Które stwierdzenia o deficycie i długu publicznym są prawdziwe?",
  ["Deficyt jest strumieniem, a dług zasobem", "Deficyt zwiększa dług publiczny", "Dług w relacji do PKB może maleć mimo deficytu, gdy nominalny PKB rośnie szybko", "Nadwyżka budżetowa zwiększa dług"], "ABC",
  "Relacja dług/PKB spada, gdy nominalny wzrost PKB przewyższa tempo wzrostu długu – nadwyżka pozwala dług spłacać."),
 (2, "m", "Które cechy dotyczą stagflacji z lat 70. XX w.?",
  ["Wysoka inflacja", "Wysokie bezrobocie", "Szoki naftowe (1973, 1979)", "Gwałtowny wzrost produktywności"], "ABC",
  "W latach 70. wzrost produktywności wyraźnie zwolnił."),
]
