# -*- coding: utf-8 -*-
# Dział 5 – Finanse publiczne, podatki i zabezpieczenie społeczne, partia 2
M = [
 (5, "s", "Towar kosztuje netto 200 zł i jest objęty stawką VAT 23%. Cena brutto wynosi:",
  ["246 zł", "223 zł", "200 zł", "260 zł"], "A",
  "VAT = 23% · 200 = 46 zł; cena brutto 246 zł. Przy cenie brutto VAT liczy się metodą „w stu”: 46/246 ≈ 18,7% ceny brutto."),
 (5, "s", "Hurtownia kupiła towar za 1000 zł netto (VAT 23%) i sprzedała za 1500 zł netto. VAT do zapłaty do urzędu skarbowego wynosi:",
  ["115 zł", "345 zł", "230 zł", "500 zł"], "A",
  "VAT należny = 345 zł, naliczony = 230 zł; do zapłaty 345 − 230 = 115 zł, czyli 23% wartości dodanej (500 zł)."),
 (5, "s", "Przedsiębiorca na podatku liniowym ma dochód 200 000 zł. PIT (bez uwzględnienia składki zdrowotnej) wynosi:",
  ["38 000 zł", "24 000 zł", "54 400 zł", "40 000 zł"], "A",
  "Podatek liniowy 19% bez kwoty wolnej: 0,19 · 200 000 = 38 000 zł."),
 (5, "s", "Spółka osiągnęła dochód 1 mln zł i jest dużym podatnikiem CIT. Podatek wynosi:",
  ["190 000 zł", "90 000 zł", "230 000 zł", "120 000 zł"], "A",
  "Stawka podstawowa CIT 19%; preferencyjna 9% dotyczy małych podatników (przychody do 2 mln euro) i podatników rozpoczynających działalność."),
 (5, "s", "Inwestor zarobił na sprzedaży akcji 10 000 zł zysku. Podatek od zysków kapitałowych wynosi:",
  ["1900 zł", "1200 zł", "3200 zł", "0 zł"], "A",
  "Podatek Belki – 19% od dochodu z kapitałów pieniężnych (zbycie papierów, odsetki, dywidendy); wyjątki m.in. dla IKE/IKZE i PPK."),
 (5, "s", "Podatek, którego ciężar nie może zostać przerzucony na inny podmiot i który obciąża dochód lub majątek podatnika, to podatek:",
  ["bezpośredni", "pośredni", "obrotowy", "akcyzowy"], "A",
  "Bezpośrednie: PIT, CIT, podatki majątkowe; pośrednie (VAT, akcyza, cło) są wliczane w cenę i ostatecznie obciążają konsumenta."),
 (5, "s", "Akcyza w Polsce obciąża m.in.:",
  ["wyroby alkoholowe, tytoniowe, paliwa i energię elektryczną", "żywność podstawową", "usługi edukacyjne", "leki refundowane"], "A",
  "Akcyza ma charakter fiskalny i korekcyjny (ograniczanie spożycia szkodliwych dóbr – w tym napoje słodzone objęte osobną opłatą cukrową)."),
 (5, "s", "Podatek od nieruchomości w Polsce jest dochodem:",
  ["gminy", "budżetu państwa", "województwa", "powiatu"], "A",
  "Podatki lokalne (od nieruchomości, rolny, leśny, od środków transportowych) są dochodami gmin; rada gminy ustala stawki w granicach ustawowych maksimów."),
 (5, "s", "Subwencja ogólna dla samorządów różni się od dotacji celowej tym, że:",
  ["jest środkiem bezzwrotnym o ogólnym przeznaczeniu, a dotacja musi zostać wykorzystana na określony cel", "musi zostać zwrócona", "jest przekazywana tylko gminom", "pochodzi z funduszy UE"], "A",
  "Subwencja (m.in. oświatowa, wyrównawcza) – do swobodnego wykorzystania (oświatowa – na zadania oświatowe); dotacja celowa – na konkretne zadania (np. zlecone z zakresu administracji rządowej), z rozliczeniem."),
 (5, "s", "Janosikowe to:",
  ["wpłaty bogatszych samorządów do budżetu państwa, rozdzielane jako subwencja dla biedniejszych", "podatek od najbogatszych obywateli", "danina solidarnościowa", "podatek od banków"], "A",
  "Mechanizm wyrównawczy w systemie dochodów JST (np. Warszawa i Mazowsze jako największy płatnik); mechanizm zmieniono w reformie dochodów JST obowiązującej od 2025 r."),
 (5, "s", "Danina solidarnościowa w Polsce to:",
  ["4% od nadwyżki dochodów powyżej 1 mln zł rocznie", "19% od zysków kapitałowych", "9% składki zdrowotnej", "podatek od nieruchomości luksusowych"], "A",
  "Wprowadzona w 2019 r.; wpływy trafiają do Funduszu Solidarnościowego (wsparcie osób z niepełnosprawnościami)."),
 (5, "s", "Kwota wolna od podatku w skali PIT (2026) wynosi:",
  ["30 000 zł", "8000 zł", "120 000 zł", "3091 zł"], "A",
  "Od 2022 r. kwota wolna wynosi 30 000 zł (kwota zmniejszająca podatek 3600 zł przy stawce 12%); próg drugiej stawki 32% – 120 000 zł."),
 (5, "s", "Najwyższą pozycją dochodów budżetu państwa w Polsce są wpływy z:",
  ["VAT", "CIT", "akcyzy", "podatku od gier"], "A",
  "VAT przynosi ok. 40% dochodów budżetu państwa; kolejne: PIT (część trafia do JST), CIT, akcyza."),
 (5, "s", "Największą pozycją wydatków sektora finansów publicznych w Polsce są wydatki na:",
  ["zabezpieczenie społeczne (głównie emerytury i renty)", "obronę narodową", "obsługę długu", "administrację publiczną"], "A",
  "Wydatki socjalne (FUS, KRUS, świadczenia rodzinne) to największa grupa wydatków publicznych; wydatki na obronę wzrosły po 2022 r. do ok. 4–5% PKB."),
 (5, "s", "Państwowy dług publiczny w relacji do PKB (metodologia krajowa) w Polsce w połowie lat 2020. wynosił około:",
  ["45–50%", "10–15%", "90–100%", "150%"], "A",
  "Dług wg metodologii krajowej był niższy niż wg unijnej (sektor general government), która obejmuje m.in. fundusze w BGK; dług GG przekroczył 55% PKB w 2025 r."),
 (5, "s", "Procedura nadmiernego deficytu (EDP) wobec Polski została otwarta przez Radę UE w 2024 r., ponieważ:",
  ["deficyt sektora finansów publicznych przekroczył 3% PKB", "dług przekroczył 100% PKB", "inflacja przekroczyła 10%", "Polska nie przyjęła euro"], "A",
  "Deficyt GG w 2023 r. wyniósł ok. 5,1% PKB, a w 2024 r. ok. 6,5% PKB; procedura wymaga ścieżki korekty fiskalnej uzgodnionej z UE."),
 (5, "s", "Stabilizująca reguła wydatkowa w Polsce ogranicza:",
  ["tempo wzrostu wydatków większości sektora finansów publicznych", "wysokość deficytu NBP", "inflację", "emisję obligacji przez samorządy do zera"], "A",
  "Reguła (od 2014 r.) wiąże dopuszczalny wzrost wydatków z inflacją i średniookresowym tempem wzrostu PKB, z korektą przy wysokim długu lub deficycie."),
 (5, "s", "Wydatki z Funduszu Przeciwdziałania COVID-19 i Funduszu Wsparcia Sił Zbrojnych w BGK są ujmowane:",
  ["poza budżetem państwa, ale w długu i deficycie sektora general government (metodologia UE)", "w budżecie NBP", "w budżetach gmin", "w ogóle nie są wliczane do finansów publicznych"], "A",
  "Fundusze pozabudżetowe obniżają przejrzystość finansów publicznych (krytyka NIK, Rady Fiskalnej) – dlatego różnica między długiem wg metodologii krajowej i unijnej wzrosła."),
 (5, "s", "Rok budżetowy w Polsce trwa:",
  ["od 1 stycznia do 31 grudnia", "od 1 lipca do 30 czerwca", "od 1 kwietnia do 31 marca", "od 1 października do 30 września"], "A",
  "Rok budżetowy pokrywa się z kalendarzowym (w USA rok fiskalny rozpoczyna się 1 października, w Wielkiej Brytanii 6 kwietnia)."),
 (5, "s", "Sprawozdanie z wykonania budżetu państwa Rada Ministrów przedstawia Sejmowi w ciągu:",
  ["5 miesięcy od zakończenia roku budżetowego", "1 miesiąca", "roku", "2 lat"], "A",
  "Art. 226 Konstytucji: wraz z analizą NIK; Sejm podejmuje uchwałę o udzieleniu (lub nieudzieleniu) absolutorium rządowi."),
 (5, "s", "Kontrolę wykonania budżetu państwa sprawuje:",
  ["Najwyższa Izba Kontroli", "Regionalna Izba Obrachunkowa", "Komisja Nadzoru Finansowego", "Rzecznik Praw Obywatelskich"], "A",
  "NIK podlega Sejmowi; RIO kontrolują gospodarkę finansową samorządów."),
 (5, "s", "Deficyt pierwotny (primary deficit) to deficyt:",
  ["bez kosztów obsługi długu publicznego", "wyłącznie samorządów", "skorygowany o cykl koniunkturalny", "w handlu zagranicznym"], "A",
  "Saldo pierwotne pokazuje, czy bieżące dochody pokrywają wydatki bez odsetek; dla stabilizacji długu ważna jest relacja stopy procentowej do tempa wzrostu PKB."),
 (5, "s", "Dług publiczny wynosi 50% PKB, nominalny PKB rośnie o 6%, a nominalna stopa procentowa od długu wynosi 4%. Aby relacja długu do PKB się nie zmieniła, saldo pierwotne może wynosić około:",
  ["deficyt pierwotny ok. 1% PKB", "nadwyżka pierwotna 1% PKB", "deficyt pierwotny 5% PKB", "zero"], "A",
  "Δd ≈ (i − g)·d − saldo pierwotne = (4% − 6%) · 0,5 = −1 pkt proc.; deficyt pierwotny ok. 1% PKB utrzymuje stałą relację długu."),
 (5, "s", "Rolowanie długu publicznego oznacza:",
  ["spłatę zapadających obligacji z wpływów z emisji nowych", "umorzenie długu", "zamianę długu na akcje", "finansowanie przez NBP"], "A",
  "Ryzyko refinansowania rośnie, gdy znaczna część długu zapada w krótkim czasie, a koszty finansowania rosną."),
 (5, "s", "Ubezpieczenie zdrowotne w Polsce finansuje przede wszystkim:",
  ["Narodowy Fundusz Zdrowia ze składki zdrowotnej (9%)", "ZUS ze składki emerytalnej", "budżet gmin", "prywatne ubezpieczenia obowiązkowe"], "A",
  "NFZ (od 2003 r.) kontraktuje świadczenia; od 2022 r. składka zdrowotna nie jest odliczana od PIT, a dla przedsiębiorców zależy od formy opodatkowania."),
 (5, "s", "Fundusz Ubezpieczeń Społecznych (FUS) jest zarządzany przez:",
  ["ZUS", "NFZ", "KRUS", "Ministerstwo Finansów"], "A",
  "FUS gromadzi składki i wypłaca świadczenia (emerytury, renty, zasiłki); deficyt FUS pokrywa dotacja z budżetu państwa."),
 (5, "s", "Wydatki na świadczenie 800+ zaliczane są w PKB metodą wydatkową do:",
  ["żadnej kategorii – to transfer, a nie zakup dóbr i usług", "wydatków rządowych G", "inwestycji", "eksportu netto"], "A",
  "Transfery socjalne zwiększają dochód rozporządzalny gospodarstw; do PKB trafia dopiero wydana z nich konsumpcja (C)."),
 (5, "s", "Zasada niedopuszczalności finansowania deficytu przez bank centralny w Polsce wynika z:",
  ["art. 220 Konstytucji RP", "ustawy o VAT", "kodeksu cywilnego", "ustawy o PPK"], "A",
  "Art. 220 ust. 2: ustawa budżetowa nie może przewidywać pokrywania deficytu przez zaciąganie zobowiązań w centralnym banku państwa."),
 (5, "s", "Funkcja redystrybucyjna finansów publicznych polega na:",
  ["zmianie podziału dochodów, np. przez progresywne podatki i transfery", "dostarczaniu dóbr publicznych", "łagodzeniu wahań koniunktury", "emisji pieniądza"], "A",
  "Musgrave wyróżnił funkcje: alokacyjną (dobra publiczne, korekta zawodności rynku), redystrybucyjną i stabilizacyjną."),
 (5, "s", "Ulga podatkowa polegająca na odliczeniu kwoty od podatku (np. ulga na dzieci) różni się od odliczenia od dochodu tym, że:",
  ["daje tę samą korzyść niezależnie od stawki podatku", "zawsze daje większą korzyść bogatszym", "nie zmniejsza podatku", "dotyczy tylko CIT"], "A",
  "Odliczenie od dochodu (np. wpłaty na IKZE) daje korzyść równą kwocie × stawka krańcowa – więcej przy wyższej stawce; odliczenie od podatku – stałą kwotę."),
 (5, "s", "Podatnik uzyskał 50 000 zł dochodu i zapłacił 2400 zł PIT. Przeciętna stopa podatkowa wynosi:",
  ["4,8%", "12%", "2,4%", "19%"], "A",
  "Stopa przeciętna = podatek / dochód = 2400 / 50 000 = 4,8%; krańcowa (stawka od kolejnej złotówki) wynosi 12%."),
 (5, "s", "Optymalizacja podatkowa (unikanie opodatkowania) różni się od uchylania się od podatku tym, że:",
  ["polega na legalnym wykorzystaniu przepisów, podczas gdy uchylanie się jest przestępstwem", "jest zawsze karana", "dotyczy tylko VAT", "polega na niezłożeniu zeznania"], "A",
  "Agresywne schematy optymalizacji ogranicza klauzula przeciwko unikaniu opodatkowania (GAAR) i obowiązek raportowania schematów podatkowych (MDR)."),
 (5, "s", "Raje podatkowe to:",
  ["jurysdykcje o bardzo niskich podatkach i ograniczonej wymianie informacji podatkowych", "specjalne strefy ekonomiczne w Polsce", "gminy bez podatku od nieruchomości", "kraje z wysokim VAT"], "A",
  "Przykłady na listach UE/OECD zmieniają się; walce z przenoszeniem zysków służą m.in. projekt BEPS OECD i globalny podatek minimalny 15% (od 2024 r. w UE)."),
 (5, "s", "Globalny minimalny podatek dochodowy od dużych grup kapitałowych (filar 2 OECD) wynosi:",
  ["15%", "9%", "19%", "25%"], "A",
  "Dotyczy grup o przychodach ponad 750 mln euro; w UE wdrożony dyrektywą z 2022 r., w Polsce ustawą o podatku wyrównawczym (od 2025 r.)."),
 (5, "s", "Krajowy System e-Faktur (KSeF) służy do:",
  ["wystawiania i przechowywania faktur ustrukturyzowanych w systemie Ministerstwa Finansów", "rejestracji spółek", "obsługi PPK", "przelewów międzybankowych"], "A",
  "KSeF ograniczy wyłudzenia VAT i uprości rozliczenia; obowiązkowe korzystanie wprowadzono etapami w 2026 r."),
 (5, "s", "Split payment (mechanizm podzielonej płatności) polega na tym, że:",
  ["kwota VAT z faktury trafia na osobny rachunek VAT sprzedawcy", "podatek płaci się w ratach", "VAT jest dzielony między gminę i państwo", "faktura jest dzielona na dwie"], "A",
  "Wprowadzony w 2018 r. (obowiązkowy od 2019 r. dla towarów wrażliwych powyżej 15 000 zł); utrudnia wyłudzenia VAT (karuzele)."),
 (5, "s", "Luka VAT to:",
  ["różnica między teoretycznymi a faktycznymi wpływami z VAT", "różnica między VAT należnym i naliczonym", "deficyt budżetu", "różnica stawek VAT w UE"], "A",
  "Luka VAT w Polsce spadła z ok. 20–25% (2015) do kilku–kilkunastu procent dzięki uszczelnieniu systemu (JPK, split payment, STIR)."),
 (5, "s", "Podatek od niektórych instytucji finansowych (bankowy) w Polsce wynosi:",
  ["0,0366% miesięcznie od aktywów ponad ustawowy próg", "19% od zysku", "1% od depozytów", "0,5% od kredytów rocznie"], "A",
  "Wprowadzony w 2016 r.; podstawą są aktywa (po odliczeniach, m.in. obligacji skarbowych), co zachęca banki do kupowania obligacji SP."),
 (5, "s", "Opłata cukrowa (od napojów słodzonych) ma przede wszystkim charakter:",
  ["korekcyjny (prozdrowotny), ograniczający spożycie", "wyłącznie fiskalny", "redystrybucyjny", "stabilizacyjny"], "A",
  "Od 2021 r.; przykład podatku Pigou korygującego negatywne efekty zewnętrzne (koszty leczenia otyłości ponoszone przez system ochrony zdrowia)."),
 (5, "s", "Emerytura w KRUS różni się od emerytury z ZUS tym, że:",
  ["jest finansowana głównie z dotacji budżetowej, a składki rolników są niskie i ryczałtowe", "jest zawsze wyższa", "zależy od kapitału na koncie", "jest wypłacana z OFE"], "A",
  "Składka rolnika zależy od emerytury podstawowej (10%), więc system jest silnie dotowany (ok. 80–90% wydatków KRUS pokrywa budżet)."),
 (5, "s", "Trzynasta emerytura jest wypłacana:",
  ["co roku w kwietniu w wysokości minimalnej emerytury", "w grudniu w wysokości średniej płacy", "tylko osobom powyżej 80 lat", "co dwa lata"], "A",
  "Od 2019 r. (ustawowo stała od 2021 r.); czternasta (od 2021 r.) wypłacana jesienią, z progiem dochodowym."),
 (5, "s", "Pomoc de minimis dla przedsiębiorcy w UE (ogólna) od 2024 r. nie może przekroczyć w okresie 3 lat:",
  ["300 000 euro", "200 000 euro", "1 mln euro", "100 000 euro"], "A",
  "Rozporządzenie Komisji 2023/2831 podniosło limit z 200 tys. do 300 tys. euro w ciągu 3 lat (okres kroczący); pomoc de minimis nie wymaga notyfikacji."),
 # --- wielokrotny wybór (głównie 1, 2 i 4 poprawne) ---
 (5, "m", "Które podatki są dochodem budżetu państwa (w całości)?",
  ["VAT", "Akcyza", "Podatek od nieruchomości", "Podatek rolny"], "AB",
  "Podatek od nieruchomości i rolny to podatki lokalne – dochody gmin."),
 (5, "m", "Które z poniższych są składkami na ubezpieczenia społeczne w Polsce?",
  ["Emerytalna", "Rentowa", "Chorobowa", "Wypadkowa"], "ABCD",
  "Składka zdrowotna (9%) nie jest składką na ubezpieczenia społeczne – trafia do NFZ."),
 (5, "m", "Które cechy dotyczą podatku progresywnego?",
  ["Stopa przeciętna rośnie wraz z dochodem", "Stopa krańcowa jest wyższa od przeciętnej", "Każdy płaci tę samą kwotę", "Stopa przeciętna maleje wraz z dochodem"], "AB",
  "Stała kwota to podatek pogłówny, malejąca stopa przeciętna – podatek regresywny."),
 (5, "m", "Które dochody są dochodami powiatu?",
  ["Udział we wpływach z PIT", "Podatek od nieruchomości", "Podatek VAT", "Akcyza"], "A",
  "Powiat nie ma własnych podatków; jego dochody to głównie udziały w PIT i CIT, subwencje i dotacje oraz opłaty (np. komunikacyjne)."),
 (5, "m", "Które z poniższych zasad budżetowych są poprawnie opisane?",
  ["Zasada jawności – debata nad budżetem jest publiczna", "Zasada roczności – budżet uchwala się na rok", "Zasada równowagi – deficyt jest zawsze zakazany", "Zasada szczegółowości – wydatki dzieli się na części, działy i rozdziały"], "ABD",
  "Zasada równowagi postuluje zrównoważony budżet, ale prawo dopuszcza deficyt państwa (w granicach reguł)."),
 (5, "m", "Które wydatki są wydatkami majątkowymi (inwestycyjnymi) samorządu?",
  ["Budowa szkoły", "Zakup autobusów komunikacji miejskiej", "Wynagrodzenia nauczycieli", "Zasiłki pomocy społecznej"], "AB",
  "Wynagrodzenia i zasiłki to wydatki bieżące."),
 (5, "m", "Które twierdzenia o długu publicznym w Polsce są prawdziwe?",
  ["Konstytucja ogranicza go do 3/5 PKB", "Ustawa przewiduje progi ostrożnościowe 43% i 48%", "Brak jest jakichkolwiek ograniczeń długu", "Najwięcej długu Skarbu Państwa stanowią obligacje skarbowe"], "ABD",
  "Progi 43% i 48% (oraz 55%) określa ustawa o finansach publicznych, a dług SP to głównie skarbowe papiery wartościowe."),
 (5, "m", "Które z poniższych są przykładami podatków pośrednich?",
  ["Cło", "Podatek od gier", "PIT", "Podatek od spadków i darowizn"], "AB",
  "PIT i podatek od spadków to podatki bezpośrednie."),
 (5, "m", "Które informacje o NFZ są prawdziwe?",
  ["Finansuje świadczenia zdrowotne ze składek", "Kontraktuje usługi szpitali i przychodni", "Wypłaca emerytury", "Ustala stopy procentowe"], "AB",
  "Emerytury wypłaca ZUS/KRUS, a stopy ustala RPP."),
 (5, "m", "Które z poniższych są dochodami niepodatkowymi budżetu państwa?",
  ["Wpłata z zysku NBP", "Dywidendy ze spółek Skarbu Państwa", "Cła (dochód UE)", "VAT"], "AB",
  "Cła są tradycyjnym zasobem własnym UE (Polska zatrzymuje część na koszty poboru), a VAT to dochód podatkowy."),
 (5, "m", "Które twierdzenia o krzywej Laffera są prawdziwe?",
  ["Przy stawce 0% wpływy są równe zeru", "Przy stawce 100% wpływy są teoretycznie równe zeru", "Wpływy zawsze rosną liniowo ze stawką", "Istnieje stawka maksymalizująca wpływy"], "ABD",
  "Zależność jest nieliniowa – po przekroczeniu stawki optymalnej wpływy spadają."),
 (5, "m", "Które cechy dotyczą podatku liniowego PIT dla przedsiębiorców w Polsce?",
  ["Stawka 19%", "Brak kwoty wolnej od podatku", "Możliwość wspólnego rozliczenia z małżonkiem", "Stawka 12% do 120 000 zł"], "AB",
  "Wspólne rozliczenie z małżonkiem i stawki 12%/32% dotyczą skali podatkowej."),
 (5, "m", "Które z poniższych działań uszczelniły pobór VAT w Polsce?",
  ["Jednolity Plik Kontrolny (JPK)", "Mechanizm podzielonej płatności", "System STIR analizujący przepływy na rachunkach", "Obniżenie wszystkich stawek VAT do zera"], "ABC",
  "Obniżenie stawek nie jest narzędziem uszczelnienia."),
 (5, "m", "Które z poniższych należą do sektora finansów publicznych w Polsce?",
  ["Jednostki samorządu terytorialnego", "ZUS", "Narodowy Fundusz Zdrowia", "Spółki giełdowe z udziałem Skarbu Państwa"], "ABC",
  "Spółki prawa handlowego (nawet z udziałem SP) nie należą do sektora finansów publicznych."),
 (5, "m", "Które z poniższych świadczeń są obecnie (2026) wypłacane w Polsce?",
  ["800+", "13. emerytura", "500+ na każde dziecko", "Becikowe 50 000 zł"], "AB",
  "500+ zastąpiono w 2024 r. świadczeniem 800+, a becikowe wynosi 1000 zł (z kryterium dochodowym)."),
 (5, "m", "Które cechy dotyczą podatku Pigou?",
  ["Koryguje negatywny efekt zewnętrzny", "Jego stawka powinna równać się krańcowemu kosztowi zewnętrznemu", "Zwiększa produkcję zanieczyszczającą", "Jego celem jest przede wszystkim zrównanie dochodów"], "AB",
  "Podatek Pigou zmniejsza nadmierną produkcję i nie służy redystrybucji."),
 (5, "m", "Które informacje o procedurze budżetowej w Polsce są prawdziwe?",
  ["Projekt budżetu przygotowuje Rada Ministrów", "Prezydent nie może zawetować ustawy budżetowej", "Senat może wprowadzać poprawki", "Ustawę budżetową uchwala NBP"], "ABC",
  "Ustawę budżetową uchwala Sejm (z udziałem Senatu); NBP prowadzi politykę pieniężną."),
 (5, "m", "Które z poniższych należą do automatycznych stabilizatorów w Polsce?",
  ["Zasiłek dla bezrobotnych", "Progresywny PIT", "Coroczna waloryzacja emerytur o inflację", "Uchwalenie tarczy antykryzysowej"], "AB",
  "Waloryzacja nie reaguje na cykl, a tarcza to polityka dyskrecjonalna."),
 (5, "m", "Które twierdzenia o deficycie strukturalnym są prawdziwe?",
  ["Jest skorygowany o wpływ cyklu koniunkturalnego", "Służy ocenie polityki fiskalnej w regułach UE", "Zawsze jest równy deficytowi faktycznemu", "Rośnie automatycznie w recesji"], "AB",
  "W recesji rośnie deficyt cykliczny, a strukturalny zależy od decyzji polityki fiskalnej."),
 (5, "m", "Które zadania należą do gminy?",
  ["Utrzymanie szkół podstawowych", "Zaopatrzenie w wodę i gospodarka odpadami", "Utrzymanie dróg krajowych", "Obronność"], "AB",
  "Drogi krajowe – GDDKiA (administracja rządowa); obronność – państwo."),
 (5, "m", "Które z poniższych zjawisk zwiększają deficyt budżetowy w recesji?",
  ["Spadek wpływów z podatków", "Wzrost wydatków na zasiłki", "Wzrost wpływów z VAT", "Spadek bezrobocia"], "AB",
  "Wpływy z VAT w recesji zwykle spadają, a bezrobocie rośnie."),
 (5, "m", "Które z wymienionych instytucji kontrolują finanse publiczne?",
  ["Najwyższa Izba Kontroli", "Regionalne izby obrachunkowe", "Krajowa Administracja Skarbowa", "Giełda Papierów Wartościowych"], "ABC",
  "GPW nie jest organem kontroli finansów publicznych."),
 (5, "m", "Które z poniższych opisuje podatek obrotowy (od przychodu) w odróżnieniu od podatku od wartości dodanej?",
  ["Kumuluje się na kolejnych etapach obrotu (podatek od podatku)", "Sprzyja integracji pionowej firm", "Pozwala odliczyć podatek zapłacony przez dostawców", "Jest neutralny dla liczby etapów produkcji"], "AB",
  "Możliwość odliczenia i neutralność wobec liczby etapów to zalety VAT."),
 (5, "m", "Które z poniższych są przykładami ulg i zwolnień w PIT w Polsce?",
  ["Ulga na dzieci", "Ulga dla młodych (zwolnienie do 26 lat do limitu)", "Ulga termomodernizacyjna", "Ulga na zakup akcji spółek z WIG20"], "ABC",
  "Nie ma ulgi PIT na zakup akcji spółek WIG20."),
 (5, "m", "Które twierdzenia o reformie emerytalnej z 1999 r. są prawdziwe?",
  ["Wprowadziła system zdefiniowanej składki", "Utworzyła OFE", "Wprowadziła wiek emerytalny 67 lat", "Objęła wszystkie osoby urodzone po 1948 r."], "ABD",
  "Podwyższanie wieku do 67 lat wprowadzono od 2013 r. (cofnięto od 2017 r.)."),
]
