# -*- coding: utf-8 -*-
# Dział 6 – Gospodarka światowa, handel międzynarodowy i UE, partia 2
M = [
 (6, "s", "Kraj X eksportuje towary za 300 mld zł i importuje za 320 mld zł; eksport usług wynosi 80 mld zł, import usług 50 mld zł. Saldo obrotów towarami i usługami wynosi:",
  ["+10 mld zł", "−20 mld zł", "+30 mld zł", "−10 mld zł"], "A",
  "Towary: 300 − 320 = −20; usługi: 80 − 50 = +30; razem +10 mld zł (sytuacja typowa dla Polski: nadwyżka w usługach, np. transport, IT)."),
 (6, "s", "Kurs USD/PLN spadł z 4,00 do 3,60. Polski importer płacący 10 000 USD za towar zapłaci teraz:",
  ["o 4000 zł mniej", "o 4000 zł więcej", "tyle samo", "o 400 zł mniej"], "A",
  "Wcześniej 40 000 zł, teraz 36 000 zł – złoty umocnił się (aprecjacja), więc import tanieje."),
 (6, "s", "Big Mac kosztuje w USA 5,70 USD, a w Polsce 22,80 zł. Rynkowy kurs USD/PLN wynosi 4,00. Według indeksu Big Maca złoty jest:",
  ["w równowadze", "niedowartościowany o 25%", "przewartościowany o 20%", "niedowartościowany o 50%"], "A",
  "Kurs implikowany PPP = 22,80 / 5,70 = 4,00 zł/USD – równy rynkowemu, więc według tego miernika złoty jest wyceniony „sprawiedliwie”."),
 (6, "s", "Złoty osłabił się nominalnie wobec euro o 10%, a inflacja w Polsce była o 3 pkt proc. wyższa niż w strefie euro. Realny kurs złotego:",
  ["osłabił się o ok. 7%", "umocnił się o ok. 7%", "osłabił się o ok. 13%", "nie zmienił się"], "A",
  "Zmiana kursu realnego ≈ zmiana kursu nominalnego skorygowana o różnicę inflacji: 10% − 3% ≈ 7% realnej deprecjacji złotego – polskie towary stały się relatywnie tańsze."),
 (6, "s", "Parytet stóp procentowych: stopa w Polsce wynosi 6%, w strefie euro 2%, kurs spot EUR/PLN 4,30. Teoretyczny kurs terminowy za rok wynosi około:",
  ["4,47", "4,13", "4,30", "4,56"], "A",
  "F = S · (1 + iPL)/(1 + iEUR) = 4,30 · 1,06/1,02 ≈ 4,47 – waluta o wyższej stopie procentowej jest notowana z dyskontem terminowym."),
 (6, "s", "Cło ad valorem to cło:",
  ["wyrażone jako procent wartości importowanego towaru", "wyrażone kwotowo od sztuki lub kilograma", "nakładane na eksport", "zwrotne po reeksporcie"], "A",
  "Cło specyficzne (kwotowe) – stała kwota od jednostki; mieszane łączy obie formy."),
 (6, "s", "Kontyngent importowy w porównaniu z cłem o tym samym efekcie ilościowym:",
  ["nie przynosi budżetowi dochodów (renta przypada posiadaczom licencji importowych)", "zawsze zwiększa wpływy budżetu", "obniża cenę krajową", "zwiększa import"], "A",
  "Różnica cen krajowych i światowych trafia do importerów z licencjami (renta kontyngentowa), chyba że państwo licytuje licencje."),
 (6, "s", "Dobrowolne ograniczenie eksportu (VER) to:",
  ["porozumienie, w którym kraj eksportujący sam ogranicza eksport pod presją kraju importującego", "zakaz importu", "cło eksportowe", "subsydium eksportowe"], "A",
  "Przykład: japoński eksport samochodów do USA w latach 80.; dziś zasady WTO ograniczają takie praktyki."),
 (6, "s", "Argument „przemysłu raczkującego” (F. List) uzasadnia:",
  ["czasową ochronę celną młodych gałęzi przemysłu, dopóki nie osiągną konkurencyjności", "trwały zakaz importu", "subsydia dla eksporterów surowców", "całkowity wolny handel"], "A",
  "F. List (1841) – protekcjonizm wychowawczy; krytycy wskazują, że ochrona bywa nadużywana i trwa zbyt długo."),
 (6, "s", "Teoria cyklu życia produktu w handlu (R. Vernon) zakłada, że:",
  ["nowy produkt powstaje w kraju rozwiniętym, a w fazie dojrzałości jego produkcja przenosi się do krajów o niższych kosztach", "handel zależy tylko od zasobów naturalnych", "kraje eksportują dobra o najwyższych kosztach", "produkty nie mają cyklu życia"], "A",
  "Wyjaśnia zmiany kierunków handlu i lokalizacji produkcji w czasie (np. elektronika: USA → Japonia → Chiny)."),
 (6, "s", "Handel wewnątrzgałęziowy (np. Niemcy i Francja wymieniają między sobą samochody) wyjaśnia przede wszystkim:",
  ["nowa teoria handlu – korzyści skali i zróżnicowanie produktów (P. Krugman)", "teoria przewagi absolutnej", "teoria Heckschera–Ohlina", "merkantylizm"], "A",
  "Konsumenci cenią różnorodność, a producenci korzystają ze skali – kraje o podobnych zasobach handlują podobnymi dobrami."),
 (6, "s", "Merkantylizm zalecał:",
  ["dążenie do nadwyżki w handlu zagranicznym i gromadzenia kruszców", "całkowity wolny handel", "specjalizację według przewagi komparatywnej", "rezygnację z eksportu"], "A",
  "Doktryna XVI–XVIII w. (np. J.-B. Colbert); krytykowali ją A. Smith i D. Hume (mechanizm przepływu złota)."),
 (6, "s", "Terms of trade (relacja wymiany) kraju poprawiają się, gdy:",
  ["ceny eksportu rosną szybciej niż ceny importu", "rośnie wolumen importu", "waluta się osłabia przy stałych cenach w walutach obcych", "spadają ceny eksportowanych surowców"], "A",
  "ToT = indeks cen eksportu / indeks cen importu; poprawa oznacza, że za jednostkę eksportu można kupić więcej importu."),
 (6, "s", "Rachunek finansowy bilansu płatniczego obejmuje m.in.:",
  ["bezpośrednie inwestycje zagraniczne, inwestycje portfelowe i zmiany aktywów rezerwowych", "eksport usług", "przekazy emigrantów", "wynagrodzenia pracowników sezonowych"], "A",
  "Usługi, przekazy (dochody wtórne) i wynagrodzenia (dochody pierwotne) należą do rachunku bieżącego."),
 (6, "s", "Polska ma deficyt na rachunku dochodów pierwotnych głównie z powodu:",
  ["wypływu dochodów z inwestycji zagranicznych (dywidendy, reinwestowane zyski firm z kapitałem zagranicznym)", "importu ropy", "emigracji zarobkowej", "wydatków turystów"], "A",
  "Duże zasoby BIZ w Polsce generują dochody nierezydentów; dlatego PNB (DNB) Polski jest niższy od PKB."),
 (6, "s", "Inwestycja typu greenfield to:",
  ["budowa przez inwestora zagranicznego nowego zakładu od podstaw", "zakup istniejącej firmy", "zakup akcji na giełdzie", "inwestycja w obligacje"], "A",
  "Alternatywą jest brownfield (przejęcie istniejącego zakładu) lub fuzje i przejęcia; inwestycje portfelowe nie dają kontroli (poniżej 10% głosów)."),
 (6, "s", "Teoria eklektyczna (paradygmat OLI) J. Dunninga wyjaśnia bezpośrednie inwestycje zagraniczne występowaniem korzyści:",
  ["własnościowych, lokalizacyjnych i internalizacji", "skali, zakresu i sieci", "komparatywnych i absolutnych", "podatkowych, celnych i kursowych"], "A",
  "Ownership (np. technologia, marka), Location (koszty, rynek), Internalisation (lepiej produkować samodzielnie niż sprzedać licencję)."),
 (6, "s", "Korporacja transnarodowa to przedsiębiorstwo, które:",
  ["prowadzi działalność produkcyjną lub usługową w wielu krajach poprzez filie, kontrolowane z centrali", "eksportuje wyłącznie surowce", "jest własnością kilku państw", "działa tylko w jednym kraju"], "A",
  "Największe korporacje (np. Apple, Walmart) mają przychody porównywalne z PKB średnich państw; ich działalność rodzi m.in. problem cen transferowych."),
 (6, "s", "Offshoring to:",
  ["przeniesienie części działalności firmy za granicę", "zlecenie usług firmie zewnętrznej w kraju", "powrót produkcji do kraju", "przeniesienie siedziby do raju podatkowego"], "A",
  "Outsourcing – zlecenie na zewnątrz; nearshoring – przeniesienie do pobliskiego kraju; reshoring – powrót produkcji (np. po pandemii)."),
 (6, "s", "Polska jest jednym z największych w Europie centrów:",
  ["nowoczesnych usług biznesowych (BPO/SSC/IT)", "wydobycia ropy naftowej", "produkcji samolotów pasażerskich", "bankowości offshore"], "A",
  "Sektor usług biznesowych zatrudnia w Polsce ponad 400 tys. osób (Kraków, Warszawa, Wrocław)."),
 (6, "s", "Jednolity rynek UE (od 1993 r.) opiera się na czterech swobodach przepływu:",
  ["towarów, usług, kapitału i osób", "towarów, pieniądza, informacji i technologii", "kapitału, ziemi, pracy i przedsiębiorczości", "ropy, gazu, energii i węgla"], "A",
  "Program jednolitego rynku zapoczątkował Jednolity Akt Europejski (1986); rynek funkcjonuje od 1 stycznia 1993 r."),
 (6, "s", "Wspólna Polityka Rolna UE finansuje przede wszystkim:",
  ["płatności bezpośrednie dla rolników i rozwój obszarów wiejskich", "budowę autostrad", "badania kosmiczne", "obronność"], "A",
  "WPR (od 1962 r.) to jeden z największych wydatków budżetu UE (ok. 1/3). Filary: płatności bezpośrednie i rynkowe (EFRG) oraz rozwój wsi (EFRROW)."),
 (6, "s", "Wieloletnie ramy finansowe UE określają:",
  ["limity wydatków budżetu UE na okres zwykle 7 lat", "stopy procentowe EBC", "kursy walut", "podatki krajowe"], "A",
  "Obecne ramy obejmują lata 2021–2027; dodatkowo fundusz odbudowy NextGenerationEU (w Polsce KPO)."),
 (6, "s", "Krajowy Plan Odbudowy (KPO) jest finansowany z:",
  ["Instrumentu na rzecz Odbudowy i Zwiększania Odporności (RRF) w ramach NextGenerationEU", "budżetu NBP", "Europejskiego Mechanizmu Stabilności", "Banku Światowego"], "A",
  "RRF obejmuje dotacje i pożyczki finansowane wspólnym zadłużeniem UE; wypłaty zależą od realizacji kamieni milowych i reform."),
 (6, "s", "Polska jest w budżecie UE:",
  ["beneficjentem netto (otrzymuje więcej, niż wpłaca)", "płatnikiem netto", "nie wpłaca składki", "wyłącznie płatnikiem"], "A",
  "Od akcesji Polska jest największym beneficjentem netto funduszy UE w wartościach bezwzględnych."),
 (6, "s", "Kryterium kursowe z Maastricht wymaga:",
  ["co najmniej dwuletniego uczestnictwa w ERM II bez poważnych napięć i dewaluacji", "kursu stałego wobec dolara", "płynnego kursu bez interwencji", "przyjęcia currency board"], "A",
  "Standardowe pasmo wahań w ERM II wynosi ±15% od kursu centralnego wobec euro."),
 (6, "s", "Kryterium stóp procentowych z Maastricht dotyczy:",
  ["długoterminowych stóp procentowych – nie wyższych niż o 2 pkt proc. od średniej trzech krajów o najniższej inflacji", "stopy referencyjnej banku centralnego", "oprocentowania lokat", "stóp kredytów hipotecznych"], "A",
  "Kryterium mierzy rentowność 10-letnich obligacji skarbowych."),
 (6, "s", "Europejski Mechanizm Stabilności (EMS):",
  ["udziela pomocy finansowej państwom strefy euro w trudnościach, pod warunkiem reform", "ustala stopy procentowe EBC", "jest systemem kursów walut z 1979 r.", "zarządza funduszami spójności"], "A",
  "EMS (od 2012 r., Luksemburg) zastąpił tymczasowy EFSF; pomoc otrzymały m.in. Grecja, Cypr, Hiszpania (dla banków)."),
 (6, "s", "Brexit formalnie nastąpił:",
  ["31 stycznia 2020 r.", "23 czerwca 2016 r.", "1 stycznia 2019 r.", "29 marca 2019 r."], "A",
  "23 czerwca 2016 r. odbyło się referendum; wyjście nastąpiło 31 stycznia 2020 r., a okres przejściowy zakończył się 31 grudnia 2020 r."),
 (6, "s", "Traktat z Lizbony (2007, w mocy od 2009 r.) wprowadził m.in.:",
  ["stałego przewodniczącego Rady Europejskiej i osobowość prawną UE", "walutę euro", "wspólny rynek", "Europejski System Walutowy"], "A",
  "Lizbona wzmocniła też Parlament Europejski (zwykła procedura ustawodawcza), wprowadziła wysokiego przedstawiciela ds. zagranicznych i procedurę wystąpienia z UE (art. 50 TUE)."),
 (6, "s", "Unia bankowa w strefie euro obejmuje:",
  ["jednolity mechanizm nadzorczy (SSM) i jednolity mechanizm restrukturyzacji (SRM)", "wspólną walutę i wspólny budżet", "jednolitą stawkę CIT", "wspólną politykę rolną"], "A",
  "Od 2014 r. EBC nadzoruje największe banki strefy euro; trzecim filarem miał być wspólny system gwarantowania depozytów (EDIS), wciąż nieukończony."),
 (6, "s", "Kryzys azjatycki 1997–1998 rozpoczął się od:",
  ["załamania kursu tajlandzkiego bahta po wyczerpaniu rezerw", "upadku Lehman Brothers", "kryzysu naftowego", "wojny handlowej USA–Chiny"], "A",
  "Kryzys walutowy drugiej/trzeciej generacji: ucieczka krótkoterminowego kapitału, słabe banki i sztywne kursy – rozprzestrzenił się na Indonezję, Koreę, Malezję."),
 (6, "s", "Wojna handlowa USA–Chiny (od 2018 r.) polegała głównie na:",
  ["wzajemnym nakładaniu ceł na import towarów o wartości setek miliardów dolarów", "zakazie handlu ropą", "wprowadzeniu wspólnej waluty", "zniesieniu wszystkich ceł"], "A",
  "Cła nałożone przez administrację D. Trumpa i odwetowe cła Chin; kolejne fale ceł USA ogłoszono w 2025 r. – przykład protekcjonizmu i deglobalizacji."),
 (6, "s", "Klauzula największego uprzywilejowania (KNU) w WTO oznacza, że:",
  ["korzyść handlowa przyznana jednemu członkowi musi zostać przyznana wszystkim członkom", "krajowe i zagraniczne towary mają być traktowane jednakowo po przekroczeniu granicy", "kraje rozwijające się nie płacą ceł", "każdy kraj ustala dowolne cła"], "A",
  "Druga zasada niedyskryminacji to traktowanie narodowe. Wyjątki: unie celne i strefy wolnego handlu oraz preferencje dla krajów rozwijających się."),
 (6, "s", "Unia Europejska ma z Kanadą umowę o wolnym handlu nazywaną:",
  ["CETA", "TTIP", "NAFTA", "USMCA"], "A",
  "CETA tymczasowo stosowana od 2017 r.; TTIP (z USA) nie została zawarta; NAFTA zastąpiono umową USMCA (2020)."),
 (6, "s", "Kraje BRICS to pierwotnie:",
  ["Brazylia, Rosja, Indie, Chiny, RPA", "Belgia, Rumunia, Irlandia, Czechy, Słowacja", "Bangladesz, Rosja, Indonezja, Chile, Szwecja", "Brazylia, Rumunia, Indie, Kanada, Szwajcaria"], "A",
  "Akronim BRIC (J. O’Neill, Goldman Sachs, 2001); RPA dołączyła w 2010 r., a od 2024 r. grupa rozszerza się o kolejne państwa."),
 (6, "s", "Polska wstąpiła do OECD w:",
  ["1996 r.", "1989 r.", "2004 r.", "1995 r."], "A",
  "22 listopada 1996 r. Do WTO Polska należy od 1995 r. (wcześniej członek GATT od 1967 r.)."),
 (6, "s", "Dolaryzacja (euroizacja) jednostronna oznacza, że:",
  ["kraj używa obcej waluty jako prawnego środka płatniczego bez formalnego członkostwa w unii walutowej", "kraj ma płynny kurs wobec dolara", "bank centralny emituje własną walutę cyfrową", "kraj przystępuje do strefy euro"], "A",
  "Przykłady: Ekwador i Salwador (dolar), Czarnogóra i Kosowo (euro). Kraj traci politykę pieniężną i dochody z senioratu."),
 (6, "s", "Rezerwy walutowe kraju służą m.in. do:",
  ["interwencji walutowych i ochrony przed nagłym odpływem kapitału", "finansowania deficytu budżetowego", "wypłaty emerytur", "zakupu akcji krajowych spółek przez państwo"], "A",
  "Adekwatność rezerw ocenia się np. regułą Greenspana–Guidottiego (pokrycie długu krótkoterminowego) lub liczbą miesięcy importu."),
 (6, "s", "Elastyczna linia kredytowa (FCL) MFW, z której Polska korzystała w latach 2009–2017, to:",
  ["zapobiegawcza linia kredytowa dla krajów o silnych fundamentach, bez warunków reform", "kredyt na finansowanie deficytu budżetowego", "linia swapowa z EBC", "pożyczka z Banku Światowego"], "A",
  "FCL zwiększała wiarygodność Polski w okresie kryzysu (zabezpieczenie na wypadek odpływu kapitału); Polska nigdy z niej nie skorzystała."),
 # --- wielokrotny wybór (1, 2 lub 4 poprawne) ---
 (6, "m", "Które z poniższych są instrumentami pozataryfowymi (barierami pozacelnymi) w handlu?",
  ["Kontyngenty importowe", "Normy techniczne i sanitarne utrudniające import", "Cło ad valorem", "Cło specyficzne"], "AB",
  "Cła są barierami taryfowymi; kontyngenty, normy, licencje i subsydia – pozataryfowymi."),
 (6, "m", "Które skutki dla kraju importującego ma nałożenie cła (mały kraj)?",
  ["Wzrost ceny krajowej", "Spadek importu", "Spadek nadwyżki konsumentów", "Wzrost dobrobytu netto całego kraju"], "ABC",
  "Mały kraj ponosi stratę netto (deadweight loss) – nadwyżka konsumentów spada bardziej, niż rośnie nadwyżka producentów i wpływy z cła."),
 (6, "m", "Które państwa należą do strefy euro?",
  ["Polska", "Czechy", "Węgry", "Szwecja"], "",
  "Żadne z wymienionych – Polska, Czechy, Węgry i Szwecja zachowały własne waluty (złoty, korona czeska, forint, korona szwedzka). W strefie euro jest 21 państw (od 2026 r. z Bułgarią)."),
 (6, "m", "Które z poniższych instytucji mają siedzibę w Waszyngtonie?",
  ["Międzynarodowy Fundusz Walutowy", "Bank Światowy", "Światowa Organizacja Handlu", "OECD"], "AB",
  "WTO ma siedzibę w Genewie, OECD w Paryżu."),
 (6, "m", "Które wydarzenia dotyczą historii integracji europejskiej i są poprawnie datowane?",
  ["Traktaty rzymskie – 1957 r.", "Traktat z Maastricht – 1992 r.", "Wprowadzenie gotówki euro – 2002 r.", "Wejście Polski do UE – 2004 r."], "ABCD",
  "Wszystkie daty są poprawne."),
 (6, "m", "Które czynniki mogą spowodować deprecjację złotego?",
  ["Obniżka stóp procentowych przez NBP", "Wzrost awersji do ryzyka na rynkach wschodzących", "Duży napływ BIZ do Polski", "Nadwyżka w obrotach bieżących"], "AB",
  "Napływ inwestycji i nadwyżka bieżąca zwiększają popyt na złotego – działają w kierunku aprecjacji."),
 (6, "m", "Które cechy dotyczą unii celnej?",
  ["Brak ceł między członkami", "Wspólna zewnętrzna taryfa celna", "Wspólna waluta", "Swobodny przepływ pracowników"], "AB",
  "Wspólna waluta i swoboda przepływu osób to wyższe etapy integracji (unia walutowa, wspólny rynek)."),
 (6, "m", "Które z poniższych są skutkami utworzenia unii celnej opisanymi przez J. Vinera?",
  ["Kreacja handlu (zastąpienie droższej produkcji krajowej tańszym importem od partnera)", "Przesunięcie handlu (zastąpienie tańszego importu spoza unii droższym od partnera)", "Wprowadzenie wspólnej waluty", "Likwidacja wszystkich barier wobec krajów trzecich"], "AB",
  "Viner (1950): unia celna jest korzystna, gdy kreacja handlu przeważa nad jego przesunięciem."),
 (6, "m", "Które z poniższych są przykładami dóbr lub usług, w których Polska ma silną pozycję eksportową?",
  ["Meble", "Usługi transportowe", "Części i akcesoria samochodowe", "Samoloty pasażerskie szerokokadłubowe"], "ABC",
  "Polska jest jednym z czołowych eksporterów mebli i usług transportu drogowego w UE; samolotów szerokokadłubowych nie produkuje."),
 (6, "m", "Które kraje przyjęły euro w XXI w. jako ostatnie (po 2010 r.)?",
  ["Estonia", "Łotwa", "Litwa", "Chorwacja"], "ABCD",
  "Estonia 2011, Łotwa 2014, Litwa 2015, Chorwacja 2023 (a następnie Bułgaria 2026)."),
 (6, "m", "Które cechy dotyczą systemu z Bretton Woods?",
  ["Stałe, ale dostosowywalne kursy walut wobec dolara", "Wymienialność dolara na złoto dla banków centralnych", "Kursy płynne wszystkich walut", "Wspólna waluta europejska"], "AB",
  "Kursy płynne przyjęto po upadku systemu (od 1973 r.)."),
 (6, "m", "Które z poniższych mogą tłumaczyć napływ BIZ do Polski?",
  ["Wykwalifikowana i relatywnie tania siła robocza", "Członkostwo w UE i dostęp do jednolitego rynku", "Położenie geograficzne w centrum Europy", "Brak jakichkolwiek podatków"], "ABC",
  "W Polsce obowiązują podatki (CIT 19%); zachęty to raczej ulgi (np. Polska Strefa Inwestycji)."),
 (6, "m", "Które zdania o globalnych łańcuchach wartości są prawdziwe?",
  ["Produkcja jednego wyrobu jest rozłożona na wiele krajów", "Wartość eksportu brutto kraju może zawierać importowaną wartość dodaną", "Pandemia COVID-19 ujawniła ich wrażliwość na zakłócenia", "Wyeliminowały handel międzynarodowy"], "ABC",
  "Łańcuchy wartości zwiększyły handel (zwłaszcza półproduktami), a nie go wyeliminowały."),
 (6, "m", "Które z poniższych organizacji to ugrupowania integracyjne?",
  ["ASEAN", "Mercosur", "OPEC", "NATO"], "AB",
  "OPEC to kartel eksporterów ropy, NATO – sojusz wojskowy."),
 (6, "m", "Które twierdzenia o euro są prawdziwe?",
  ["Jest drugą walutą rezerwową świata po dolarze", "Politykę pieniężną dla strefy euro prowadzi EBC", "Każde państwo strefy ma własną stopę referencyjną", "Polska zobowiązała się w traktacie akcesyjnym do przyjęcia euro w przyszłości"], "ABD",
  "Stopy procentowe są wspólne dla całej strefy; Polska ma derogację, bez wyznaczonej daty przyjęcia euro."),
 (6, "m", "Które z wymienionych zjawisk składają się na deglobalizację (slowbalizację)?",
  ["Reshoring i nearshoring produkcji", "Wzrost ceł i barier handlowych", "Sankcje gospodarcze i fragmentacja geopolityczna", "Spadek kosztów transportu kontenerowego do zera"], "ABC",
  "Koszty transportu nie spadły do zera; czynniki deglobalizacji to raczej rosnące ryzyka i polityka handlowa."),
 (6, "m", "Które z poniższych należą do kryteriów konwergencji z Maastricht?",
  ["Stabilność cen", "Stabilność kursu (ERM II)", "Długoterminowe stopy procentowe", "Stan finansów publicznych (deficyt i dług)"], "ABCD",
  "Wszystkie cztery obszary kryteriów nominalnych; dodatkowo wymagana jest zgodność prawna (niezależność banku centralnego)."),
 (6, "m", "Które twierdzenia o bilansie płatniczym Polski są prawdziwe?",
  ["Polska ma nadwyżkę w handlu usługami", "Saldo dochodów pierwotnych jest ujemne", "Bilans płatniczy publikuje GUS", "Rachunek bieżący obejmuje eksport i import towarów"], "ABD",
  "Bilans płatniczy Polski publikuje NBP."),
]
