# -*- coding: utf-8 -*-
# Dział 7 – Rachunkowość, finanse przedsiębiorstwa i prawo gospodarcze, partia 2
M = [
 (7, "s", "Suma bilansowa spółki wynosi 900 tys. zł, kapitał własny 360 tys. zł, zobowiązania długoterminowe 240 tys. zł. Zobowiązania krótkoterminowe wynoszą:",
  ["300 tys. zł", "540 tys. zł", "600 tys. zł", "120 tys. zł"], "A",
  "Pasywa = kapitał własny + zobowiązania (i rezerwy): 900 − 360 − 240 = 300 tys. zł."),
 (7, "s", "Aktywa trwałe spółki to 500 tys. zł, kapitał własny 400 tys. zł, zobowiązania długoterminowe 200 tys. zł. Kapitał obrotowy netto wynosi:",
  ["100 tys. zł", "−100 tys. zł", "600 tys. zł", "200 tys. zł"], "A",
  "KON = kapitał stały (400 + 200) − aktywa trwałe (500) = 100 tys. zł. Złota reguła bilansowa (KW ≥ AT) nie jest spełniona, ale srebrna (kapitał stały ≥ AT) – tak."),
 (7, "s", "Przychody ze sprzedaży 2 mln zł, koszt własny sprzedaży 1,4 mln zł, koszty sprzedaży i ogólnego zarządu 300 tys. zł. Zysk ze sprzedaży wynosi:",
  ["300 tys. zł", "600 tys. zł", "1,7 mln zł", "100 tys. zł"], "A",
  "Wariant kalkulacyjny RZiS: zysk brutto ze sprzedaży = 2 − 1,4 = 0,6 mln zł; po kosztach sprzedaży i zarządu – 0,3 mln zł."),
 (7, "s", "Zysk brutto spółki wynosi 500 tys. zł, a CIT 19%. Zysk netto wynosi:",
  ["405 tys. zł", "95 tys. zł", "500 tys. zł", "481 tys. zł"], "A",
  "Zysk netto = 500 − 0,19 · 500 = 405 tys. zł (przy założeniu, że podstawa opodatkowania równa się zyskowi brutto)."),
 (7, "s", "Rentowność sprzedaży netto (ROS) wynosi 8%, a rotacja aktywów 1,5. ROA wynosi:",
  ["12%", "5,3%", "9,5%", "6,5%"], "A",
  "ROA = ROS · rotacja aktywów = 8% · 1,5 = 12% (pierwszy stopień piramidy Du Ponta)."),
 (7, "s", "ROA spółki wynosi 6%, a aktywa są finansowane w 40% kapitałem własnym. ROE wynosi:",
  ["15%", "2,4%", "10%", "6%"], "A",
  "Mnożnik kapitałowy = A/KW = 1/0,4 = 2,5; ROE = ROA · 2,5 = 15% – wyższe zadłużenie podnosi ROE (dźwignia), ale i ryzyko."),
 (7, "s", "Zapasy wynoszą 90 tys. zł, a roczny koszt własny sprzedaży 730 tys. zł. Cykl rotacji zapasów (w dniach, 365 dni) wynosi:",
  ["45 dni", "8 dni", "81 dni", "30 dni"], "A",
  "Rotacja zapasów w dniach = zapasy · 365 / koszt sprzedaży = 90 · 365 / 730 = 45 dni."),
 (7, "s", "Cykl zapasów 40 dni, cykl należności 35 dni, cykl zobowiązań 50 dni. Cykl konwersji gotówki wynosi:",
  ["25 dni", "125 dni", "75 dni", "55 dni"], "A",
  "CKG = 40 + 35 − 50 = 25 dni – tyle dni firma musi sfinansować działalność operacyjną z innych źródeł niż kredyt kupiecki."),
 (7, "s", "Wskaźnik płynności gotówkowej to relacja:",
  ["środków pieniężnych (i ich ekwiwalentów) do zobowiązań krótkoterminowych", "aktywów obrotowych do zobowiązań krótkoterminowych", "zapasów do zobowiązań", "zysku do przychodów"], "A",
  "Najostrzejsza miara płynności – pokazuje, jaką część bieżących zobowiązań można spłacić natychmiast."),
 (7, "s", "EBIT wynosi 600 tys. zł, a odsetki 150 tys. zł. Wskaźnik pokrycia odsetek wynosi:",
  ["4", "0,25", "450", "3"], "A",
  "EBIT / odsetki = 600 / 150 = 4 – zysk operacyjny czterokrotnie pokrywa koszty odsetek (banki często wymagają co najmniej 2–3)."),
 (7, "s", "EBITDA różni się od EBIT tym, że:",
  ["dodaje się do niej amortyzację", "odejmuje się od niej podatek", "nie uwzględnia przychodów", "zawiera odsetki"], "A",
  "EBITDA = zysk operacyjny + amortyzacja; przybliża operacyjne przepływy pieniężne i jest używana w relacji dług netto/EBITDA."),
 (7, "s", "Dług netto spółki wynosi 300 mln zł, a EBITDA 100 mln zł. Wskaźnik dług netto/EBITDA wynosi:",
  ["3", "0,33", "200", "400"], "A",
  "Wskaźnik pokazuje, ile lat zajęłaby spłata długu z EBITDA; wartości powyżej ok. 3–4 często uznaje się za wysokie (kowenanty kredytowe)."),
 (7, "s", "Projekt: nakład 10 000 zł, wpływy 4000 zł rocznie przez 3 lata, koszt kapitału 0%. Prosty okres zwrotu wynosi:",
  ["2,5 roku", "3 lata", "2 lata", "4 lata"], "A",
  "Po 2 latach odzyskano 8000 zł; brakujące 2000 zł to połowa wpływu trzeciego roku – okres zwrotu 2,5 roku."),
 (7, "s", "Nakład 1000 zł, wpływy 600 zł po roku i 600 zł po dwóch latach, koszt kapitału 10%. NPV wynosi około:",
  ["+41 zł", "+200 zł", "−41 zł", "+91 zł"], "A",
  "NPV = 600/1,1 + 600/1,21 − 1000 ≈ 545,45 + 495,87 − 1000 ≈ 41,3 zł > 0."),
 (7, "s", "Dwa projekty wykluczające się: A (NPV = 50 tys. zł, IRR = 25%) i B (NPV = 80 tys. zł, IRR = 18%), koszt kapitału 10%. Przy konflikcie wskazań należy wybrać:",
  ["projekt B – o wyższym NPV, bo maksymalizuje przyrost wartości firmy", "projekt A – o wyższym IRR", "żaden", "oba"], "A",
  "Przy projektach wzajemnie wykluczających się decyduje NPV (bezpośrednia miara przyrostu wartości); IRR może wprowadzać w błąd przy różnej skali i rozkładzie przepływów."),
 (7, "s", "Zmodyfikowana wewnętrzna stopa zwrotu (MIRR) różni się od IRR tym, że:",
  ["zakłada reinwestowanie przepływów po koszcie kapitału, a nie po IRR", "nie uwzględnia wartości pieniądza w czasie", "jest zawsze równa zeru", "dotyczy tylko projektów finansowanych długiem"], "A",
  "MIRR usuwa nierealistyczne założenie reinwestycji po IRR i problem wielu IRR przy nietypowych przepływach."),
 (7, "s", "Spółka chce sfinansować inwestycję. Która kolejność źródeł jest zgodna z teorią hierarchii źródeł finansowania (pecking order)?",
  ["zysk zatrzymany → dług → emisja akcji", "emisja akcji → dług → zysk zatrzymany", "dług → emisja akcji → zysk zatrzymany", "emisja akcji → zysk zatrzymany → dług"], "A",
  "S. Myers i N. Majluf (1984): asymetria informacji sprawia, że emisja akcji jest sygnałem przewartościowania – firmy wolą finansowanie wewnętrzne, potem dług."),
 (7, "s", "Zgodnie z twierdzeniem Modiglianiego–Millera bez podatków i kosztów bankructwa wartość firmy:",
  ["nie zależy od struktury kapitału", "rośnie wraz z zadłużeniem", "maleje wraz z zadłużeniem", "zależy od wypłacanej dywidendy"], "A",
  "Twierdzenie I M–M (1958); po uwzględnieniu CIT (1963) dług zwiększa wartość o wartość tarczy podatkowej."),
 (7, "s", "Odsetki od kredytu wynoszą 100 tys. zł rocznie, a stawka CIT 19%. Roczna tarcza podatkowa wynosi:",
  ["19 tys. zł", "100 tys. zł", "81 tys. zł", "0 zł"], "A",
  "Tarcza podatkowa = odsetki · T = 100 · 0,19 = 19 tys. zł – o tyle niższy jest podatek dzięki zaliczeniu odsetek do kosztów."),
 (7, "s", "Polityka dywidendy rezydualnej oznacza, że spółka wypłaca dywidendę:",
  ["z zysku pozostałego po sfinansowaniu wszystkich opłacalnych inwestycji", "w stałej kwocie co roku", "zawsze w wysokości 100% zysku", "tylko w akcjach"], "A",
  "Alternatywy: stała dywidenda na akcję, stały wskaźnik wypłaty, skup akcji własnych. Teoria „lepszy wróbel w garści” (Gordon, Lintner) kontra irrelewancja dywidendy (M–M)."),
 (7, "s", "Skup akcji własnych przez spółkę:",
  ["jest alternatywną formą przekazania gotówki akcjonariuszom i zmniejsza liczbę akcji w obrocie", "zwiększa kapitał zakładowy", "jest zakazany w Polsce", "zwiększa zadłużenie wobec akcjonariuszy"], "A",
  "KSH dopuszcza nabycie akcji własnych m.in. w celu umorzenia (upoważnienie walnego zgromadzenia); EPS po skupie zwykle rośnie."),
 (7, "s", "Kredyt kupiecki z warunkiem „2/10, netto 30” oznacza, że odbiorca:",
  ["może odliczyć 2% skonta, płacąc w ciągu 10 dni, albo zapłacić pełną kwotę w ciągu 30 dni", "płaci 2% odsetek po 10 dniach", "musi zapłacić 10% w ciągu 2 dni", "dostaje 30% rabatu"], "A",
  "Rezygnacja ze skonta to drogi kredyt: 2% za 20 dni ≈ 2/98 · 365/20 ≈ 37% rocznie – zwykle opłaca się skorzystać ze skonta."),
 (7, "s", "Weksel własny różni się od trasowanego tym, że:",
  ["wystawca sam zobowiązuje się do zapłaty", "wystawca poleca zapłatę innej osobie (trasatowi)", "nie wymaga podpisu", "jest zawsze gwarantowany przez bank"], "A",
  "Weksel trasowany (trata) zawiera polecenie zapłaty skierowane do trasata; poręczenie wekslowe to aval."),
 (7, "s", "Wartość firmy (goodwill) powstaje w bilansie, gdy:",
  ["cena nabycia innej jednostki przewyższa wartość godziwą jej aktywów netto", "spółka osiąga wysoki zysk", "rośnie kurs jej akcji", "spółka wydaje środki na reklamę"], "A",
  "Goodwill odzwierciedla m.in. markę, klientów, synergię; wytworzonej samodzielnie wartości firmy nie ujmuje się w bilansie."),
 (7, "s", "Zasada memoriału w rachunkowości oznacza, że:",
  ["przychody i koszty ujmuje się w okresie, którego dotyczą, niezależnie od terminu zapłaty", "ewidencjonuje się tylko wpływy i wydatki gotówki", "aktywa wycenia się po cenie rynkowej", "księgi prowadzi się w pamięci księgowego"], "A",
  "Obok niej: współmierności przychodów i kosztów, ostrożności, ciągłości, kontynuacji działalności, istotności."),
 (7, "s", "Zasada ostrożnej wyceny nakazuje m.in.:",
  ["uwzględniać zmniejszenia wartości aktywów i rezerwy na znane ryzyka, nawet jeśli strata nie została jeszcze zrealizowana", "wyceniać wszystkie aktywa po najwyższej cenie rynkowej", "nie tworzyć rezerw", "ujmować niezrealizowane zyski jako przychód"], "A",
  "Ostrożność chroni wierzycieli przed zawyżeniem wyniku i majątku."),
 (7, "s", "Kontynuacja działalności (going concern) jest podstawowym założeniem przy sporządzaniu sprawozdania. Jeśli jest zagrożona:",
  ["aktywa wycenia się w wartości netto możliwej do uzyskania (likwidacyjnej), a biegły rewident zwraca na to uwagę", "sprawozdania się nie sporządza", "spółka musi wypłacić dywidendę", "zysk zwiększa się automatycznie"], "A",
  "Ustawa o rachunkowości przewiduje inne zasady wyceny przy braku kontynuacji działalności."),
 (7, "s", "Badanie sprawozdania finansowego przez biegłego rewidenta jest obowiązkowe m.in. dla:",
  ["spółek akcyjnych i jednostek przekraczających ustawowe progi zatrudnienia, sumy bilansowej lub przychodów", "wszystkich osób fizycznych prowadzących działalność", "spółek cywilnych zawsze", "gmin"], "A",
  "Sprawozdania jednostek zainteresowania publicznego bada firma audytorska; nadzór publiczny sprawuje PANA."),
 (7, "s", "Rachunek kosztów zmiennych (marżowy) różni się od rachunku kosztów pełnych tym, że:",
  ["koszt wytworzenia produktu obejmuje tylko koszty zmienne, a stałe obciążają wynik okresu", "nie uwzględnia kosztów materiałów", "wlicza zysk do kosztów", "jest zakazany w Polsce"], "A",
  "Rachunek zmienny ułatwia decyzje krótkookresowe (marża pokrycia, próg rentowności); pełny jest wymagany do wyceny zapasów w sprawozdaniu."),
 (7, "s", "Marża pokrycia (marża brutto na produkcie) to:",
  ["cena minus jednostkowy koszt zmienny", "cena minus koszt całkowity", "zysk netto podzielony przez przychody", "koszty stałe podzielone przez produkcję"], "A",
  "Marża pokrycia pokrywa koszty stałe, a po ich pokryciu tworzy zysk; jej relacja do ceny to stopa marży."),
 (7, "s", "Firma sprzedaje 5000 szt. po 40 zł, koszt zmienny 25 zł/szt., koszty stałe 50 000 zł. Margines bezpieczeństwa (w %) wynosi około:",
  ["33%", "67%", "25%", "50%"], "A",
  "Próg rentowności = 50 000 / 15 = 3333 szt.; margines bezpieczeństwa = (5000 − 3333)/5000 ≈ 33% – o tyle może spaść sprzedaż, zanim firma przyniesie stratę."),
 (7, "s", "Firma ma koszty stałe 120 000 zł, cenę 60 zł i koszt zmienny 40 zł. Ile sztuk musi sprzedać, aby osiągnąć zysk 40 000 zł?",
  ["8000 szt.", "6000 szt.", "2000 szt.", "4000 szt."], "A",
  "Q = (FC + zysk docelowy) / marża jednostkowa = (120 000 + 40 000) / 20 = 8000 szt."),
 (7, "s", "Leasing zwrotny (sale and leaseback) polega na:",
  ["sprzedaży własnego środka trwałego firmie leasingowej i dalszym korzystaniu z niego w ramach leasingu", "wynajmie samochodu na weekend", "zwrocie przedmiotu leasingu po roku", "kredycie konsumenckim"], "A",
  "Pozwala uwolnić gotówkę zamrożoną w majątku (np. nieruchomości) przy zachowaniu możliwości jego użytkowania."),
 (7, "s", "Forfaiting to:",
  ["wykup przez instytucję finansową należności (zwykle eksportowych, średnioterminowych) bez prawa regresu do sprzedającego", "kredyt hipoteczny", "dzierżawa ziemi", "emisja akcji uprzywilejowanych"], "A",
  "Forfaiter przejmuje ryzyko niewypłacalności dłużnika; zwykle dotyczy należności zabezpieczonych wekslem lub akredytywą."),
 (7, "s", "Akredytywa dokumentowa w handlu zagranicznym to:",
  ["zobowiązanie banku importera do zapłaty eksporterowi po przedstawieniu określonych dokumentów", "ubezpieczenie od kradzieży towaru", "cło przywozowe", "kredyt dla importera na zakup waluty"], "A",
  "Zmniejsza ryzyko obu stron: eksporter ma pewność zapłaty, importer – że zapłata nastąpi po wysyłce towaru potwierdzonej dokumentami."),
 (7, "s", "Inkaso dokumentowe różni się od akredytywy tym, że:",
  ["bank nie gwarantuje zapłaty, tylko pośredniczy w wydaniu dokumentów za zapłatę lub akcept", "jest zawsze droższe", "dotyczy tylko handlu krajowego", "wymaga zaliczki 100%"], "A",
  "Inkaso jest tańsze, ale mniej bezpieczne dla eksportera niż akredytywa."),
 (7, "s", "Ubezpieczenie kredytów eksportowych w Polsce oferuje przede wszystkim:",
  ["KUKE (Korporacja Ubezpieczeń Kredytów Eksportowych)", "ZUS", "NFZ", "UFG"], "A",
  "KUKE ubezpiecza należności eksporterów od ryzyka handlowego i politycznego; finansowanie eksportu wspiera też BGK."),
 (7, "s", "Spółka komandytowo-akcyjna łączy cechy spółki osobowej i kapitałowej, ponieważ:",
  ["co najmniej jeden komplementariusz odpowiada całym majątkiem, a akcjonariusze nie odpowiadają za zobowiązania spółki", "wszyscy wspólnicy odpowiadają do sumy komandytowej", "nie ma kapitału zakładowego", "jest prowadzona tylko przez osoby fizyczne"], "A",
  "S.K.A. ma kapitał zakładowy (min. 50 000 zł) podzielony na akcje; komplementariusz prowadzi sprawy spółki."),
 (7, "s", "W prostej spółce akcyjnej (PSA) akcje:",
  ["nie mają wartości nominalnej i nie stanowią części kapitału zakładowego (jest kapitał akcyjny)", "mają nominał co najmniej 1 zł", "muszą być notowane na giełdzie", "mogą obejmować tylko osoby fizyczne"], "A",
  "PSA (od 1 lipca 2021 r.) przeznaczona m.in. dla startupów: akcje za wkład w postaci pracy lub usług, rejestr akcjonariuszy, elastyczne zasady."),
 (7, "s", "Spółka z o.o. jest reprezentowana na zewnątrz przez:",
  ["zarząd", "zgromadzenie wspólników", "radę nadzorczą", "komisję rewizyjną"], "A",
  "Zgromadzenie wspólników podejmuje kluczowe uchwały (np. zatwierdzenie sprawozdania, podział zysku), rada nadzorcza (obowiązkowa w większych spółkach) – nadzoruje."),
 (7, "s", "Osoba fizyczna rejestrująca jednoosobową działalność gospodarczą dokonuje wpisu do:",
  ["CEIDG", "KRS", "rejestru PESEL", "BIK"], "A",
  "Centralna Ewidencja i Informacja o Działalności Gospodarczej; spółki (poza cywilną) wpisuje się do Krajowego Rejestru Sądowego."),
 (7, "s", "Upadłość przedsiębiorcy ogłasza:",
  ["sąd upadłościowy na wniosek dłużnika lub wierzyciela", "urząd skarbowy", "KNF", "zgromadzenie wspólników"], "A",
  "Prawo upadłościowe (2003, zmienione 2016): dłużnik musi złożyć wniosek w ciągu 30 dni od dnia, gdy stał się niewypłacalny; alternatywą jest restrukturyzacja (układ)."),
 (7, "s", "Postępowanie restrukturyzacyjne (Prawo restrukturyzacyjne z 2015 r.) ma na celu:",
  ["uniknięcie upadłości przez zawarcie układu z wierzycielami", "likwidację majątku dłużnika", "nacjonalizację firmy", "wypłatę dywidendy"], "A",
  "Postępowania: o zatwierdzenie układu, przyspieszone układowe, układowe, sanacyjne."),
 (7, "s", "Ochrona prawna znaku towarowego w Polsce udzielana przez Urząd Patentowy RP trwa:",
  ["10 lat z możliwością przedłużania na kolejne okresy", "20 lat bez przedłużenia", "5 lat", "do śmierci twórcy + 70 lat"], "A",
  "Patent – 20 lat (nieprzedłużalny), prawa autorskie majątkowe – co do zasady 70 lat po śmierci twórcy, znak towarowy – 10 lat z możliwością przedłużania."),
 (7, "s", "Czyn nieuczciwej konkurencji to m.in.:",
  ["naruszenie tajemnicy przedsiębiorstwa lub wprowadzające w błąd oznaczenie towaru", "obniżka cen w wyniku spadku kosztów", "reklama prawdziwych zalet produktu", "zatrudnienie pracownika konkurencji za wyższą płacę bez naruszenia prawa"], "A",
  "Ustawa o zwalczaniu nieuczciwej konkurencji (1993) wymienia m.in. naśladownictwo produktów, pomówienie, nieuczciwą reklamę, sprzedaż poniżej kosztów w celu eliminacji konkurentów."),
 (7, "s", "Praktyką naruszającą zbiorowe interesy konsumentów może zająć się:",
  ["Prezes UOKiK, nakładając karę do 10% obrotu", "Prezes NBP", "GPW", "Rzecznik Praw Dziecka"], "A",
  "Np. stosowanie niedozwolonych klauzul, wprowadzająca w błąd reklama, agresywne praktyki rynkowe."),
 (7, "s", "Konsument, który zawarł umowę na odległość (np. przez internet), może od niej odstąpić bez podania przyczyny w terminie:",
  ["14 dni", "7 dni", "30 dni", "2 lat"], "A",
  "Ustawa o prawach konsumenta (2014); rękojmia sprzedawcy za wady (od 2023 r. odpowiedzialność za brak zgodności z umową) trwa co do zasady 2 lata."),
 (7, "s", "Gwarancja jakości różni się od rękojmi (odpowiedzialności za zgodność towaru z umową) tym, że:",
  ["jest dobrowolnym zobowiązaniem gwaranta (np. producenta) na warunkach przez niego określonych", "wynika z ustawy i nie można jej wyłączyć wobec konsumenta", "trwa zawsze 2 lata", "dotyczy tylko usług"], "A",
  "Odpowiedzialność sprzedawcy wynika z ustawy; gwarancja jest dodatkowa i nie wyłącza uprawnień konsumenta wobec sprzedawcy."),
 (7, "s", "Fuzja dwóch spółek z tej samej branży na tym samym etapie produkcji to fuzja:",
  ["pozioma (horyzontalna)", "pionowa (wertykalna)", "konglomeratowa", "odwrotna"], "A",
  "Pionowa łączy różne etapy łańcucha (np. producent i dystrybutor), konglomeratowa – niepowiązane branże. Fuzje poziome najsilniej zwiększają koncentrację (kontrola UOKiK/KE)."),
 # --- wielokrotny wybór (1, 2, 4 poprawne) ---
 (7, "m", "Które z poniższych pozycji należą do aktywów obrotowych?",
  ["Zapasy", "Należności krótkoterminowe", "Środki trwałe w budowie", "Wartości niematerialne i prawne"], "AB",
  "Środki trwałe w budowie i WNiP to aktywa trwałe."),
 (7, "m", "Które z poniższych są źródłami finansowania wewnętrznego?",
  ["Zysk zatrzymany", "Odpisy amortyzacyjne", "Kredyt bankowy", "Emisja obligacji"], "AB",
  "Kredyt i obligacje to zewnętrzne źródła obce."),
 (7, "m", "Które wskaźniki mierzą rentowność?",
  ["ROE", "Wskaźnik bieżącej płynności", "Wskaźnik ogólnego zadłużenia", "Cykl rotacji zapasów"], "A",
  "Płynność, zadłużenie i rotacja to inne grupy wskaźników (płynności, struktury finansowania, sprawności)."),
 (7, "m", "Które twierdzenia o amortyzacji są prawdziwe?",
  ["Jest kosztem, który nie powoduje wydatku pieniężnego w danym okresie", "Obniża podstawę opodatkowania", "Dotyczy gruntów", "Jest źródłem finansowania wewnętrznego"], "ABD",
  "Gruntów nie amortyzuje się (nie zużywają się)."),
 (7, "m", "Które wady ma prosty okres zwrotu jako metoda oceny inwestycji?",
  ["Pomija wartość pieniądza w czasie", "Pomija przepływy po okresie zwrotu", "Jest trudny do obliczenia", "Zawsze wskazuje projekt o najwyższym NPV"], "AB",
  "Okres zwrotu jest prosty w obliczeniu i nie gwarantuje wyboru projektu o najwyższym NPV."),
 (7, "m", "Które cechy dotyczą spółki jawnej?",
  ["Jest spółką osobową", "Wspólnicy odpowiadają całym majątkiem (subsydiarnie)", "Wymaga minimalnego kapitału 5000 zł", "Jest wpisywana do CEIDG"], "AB",
  "Spółka jawna nie ma minimalnego kapitału, a wpisuje się ją do KRS."),
 (7, "m", "Które dokumenty wchodzą w skład rocznego sprawozdania finansowego jednostki (pełnego)?",
  ["Bilans", "Rachunek zysków i strat", "Informacja dodatkowa", "Biznesplan na kolejny rok"], "ABC",
  "Pełne sprawozdanie obejmuje też (dla jednostek badanych) rachunek przepływów pieniężnych i zestawienie zmian w kapitale własnym; biznesplan nie jest jego częścią."),
 (7, "m", "Które czynniki zwiększają próg rentowności (ilościowy)?",
  ["Wzrost kosztów stałych", "Wzrost jednostkowego kosztu zmiennego", "Wzrost ceny sprzedaży", "Spadek kosztów stałych"], "AB",
  "Wzrost ceny i spadek kosztów stałych obniżają próg rentowności."),
 (7, "m", "Które z poniższych są formami zabezpieczenia kredytu bankowego?",
  ["Hipoteka", "Zastaw rejestrowy", "Weksel in blanco", "Poręczenie"], "ABCD",
  "Wszystkie są typowymi zabezpieczeniami (rzeczowymi lub osobistymi)."),
 (7, "m", "Które stwierdzenia o leasingu operacyjnym w polskim prawie podatkowym są prawdziwe?",
  ["Raty leasingowe w całości są kosztem korzystającego", "Odpisów amortyzacyjnych dokonuje finansujący", "Odpisów amortyzacyjnych dokonuje korzystający", "Przedmiot leasingu jest wykazywany w aktywach korzystającego dla celów podatkowych"], "AB",
  "W leasingu finansowym (podatkowo) przedmiot ujmuje i amortyzuje korzystający."),
 (7, "m", "Które z poniższych to organy spółki akcyjnej?",
  ["Zarząd", "Rada nadzorcza", "Walne zgromadzenie", "Zgromadzenie wspólników"], "ABC",
  "Zgromadzenie wspólników to organ spółki z o.o."),
 (7, "m", "Które z poniższych mogą zwiększyć ryzyko utraty płynności przez firmę?",
  ["Wydłużenie terminów płatności udzielanych odbiorcom", "Skrócenie terminów płatności u dostawców", "Uzyskanie linii kredytowej", "Sprzedaż należności faktorowi"], "AB",
  "Linia kredytowa i faktoring poprawiają płynność."),
 (7, "m", "Które informacje o KRS są prawdziwe?",
  ["Wpisuje się do niego spółki handlowe", "Prowadzą go sądy rejonowe (rejestrowe)", "Wpisuje się do niego jednoosobowych przedsiębiorców", "Zawiera rejestr dłużników niewypłacalnych"], "AB",
  "Osoby fizyczne – CEIDG; rejestr dłużników niewypłacalnych przeniesiono do Krajowego Rejestru Zadłużonych (KRZ)."),
 (7, "m", "Które przykłady to koszty stałe w zakładzie produkcyjnym?",
  ["Czynsz za halę", "Wynagrodzenie dyrektora", "Surowce zużyte do produkcji", "Energia zużyta przez maszyny proporcjonalnie do produkcji"], "AB",
  "Surowce i energia zależna od produkcji to koszty zmienne."),
 (7, "m", "Które z poniższych są przejawem nieuczciwej konkurencji lub praktyki ograniczającej konkurencję?",
  ["Zmowa przetargowa", "Ustalanie cen z konkurentem", "Obniżka cen dzięki nowej technologii", "Wprowadzenie innowacyjnego produktu"], "AB",
  "Konkurowanie ceną wynikającą z efektywności i innowacjami jest pożądane."),
 (7, "m", "Które informacje o fuzjach i przejęciach są prawdziwe?",
  ["Kontrolę koncentracji w Polsce prowadzi Prezes UOKiK", "Fuzja pionowa łączy różne etapy łańcucha produkcji", "Fuzja konglomeratowa łączy firmy z tej samej branży", "Duże koncentracje o wymiarze unijnym ocenia Komisja Europejska"], "ABD",
  "Konglomeratowa łączy firmy z niepowiązanych branż."),
 (7, "m", "Które czynniki skracają cykl konwersji gotówki?",
  ["Szybsza rotacja zapasów", "Szybsze ściąganie należności", "Szybsza spłata zobowiązań wobec dostawców", "Dłuższe terminy płatności dla odbiorców"], "AB",
  "Szybsza spłata zobowiązań i dłuższe kredytowanie odbiorców wydłużają cykl."),
 (7, "m", "Które cechy dotyczą obligacji jako źródła finansowania firmy?",
  ["Odsetki są kosztem uzyskania przychodu", "Obligatariusze nie uzyskują prawa głosu", "Emisja rozwadnia udziały dotychczasowych akcjonariuszy", "Trzeba je wykupić w terminie"], "ABD",
  "Rozwodnienie udziałów powoduje emisja akcji, nie obligacji (wyjątek: obligacje zamienne po konwersji)."),
 (7, "m", "Które z poniższych należą do prawa własności przemysłowej?",
  ["Patent na wynalazek", "Znak towarowy", "Wzór przemysłowy", "Prawo autorskie do powieści"], "ABC",
  "Prawo autorskie to odrębna dziedzina (własność intelektualna, ale nie przemysłowa)."),
 (7, "m", "Które z poniższych stwierdzeń o EVA są prawdziwe?",
  ["Uwzględnia koszt całego kapitału, także własnego", "EVA > 0 oznacza tworzenie wartości", "Jest równa zyskowi księgowemu", "Wykorzystuje NOPAT i WACC"], "ABD",
  "Zysk księgowy nie uwzględnia kosztu kapitału własnego."),
 (7, "m", "Które z poniższych są skutkami wysokiej dźwigni finansowej?",
  ["Wyższa zmienność zysku netto", "Wyższe ryzyko upadłości", "Niższe koszty odsetek", "Zawsze wyższe ROE niezależnie od koniunktury"], "AB",
  "Dźwignia zwiększa koszty odsetek; w złej koniunkturze może obniżyć ROE (efekt ujemny)."),
 (7, "m", "Które prawa konsumenta wynikają z polskich przepisów?",
  ["Odstąpienie od umowy zawartej na odległość w ciągu 14 dni", "Odpowiedzialność sprzedawcy za brak zgodności towaru z umową", "Prawo do zwrotu każdego towaru kupionego w sklepie stacjonarnym w ciągu 30 dni", "Zakaz stosowania klauzul niedozwolonych"], "ABD",
  "Zwrot towaru kupionego stacjonarnie zależy od dobrej woli sklepu – ustawa go nie gwarantuje."),
 (7, "m", "Które informacje o spółce cywilnej są prawdziwe?",
  ["Jest umową wspólników, a nie spółką handlową", "Wspólnicy są przedsiębiorcami", "Ma osobowość prawną", "Jest wpisywana do KRS"], "AB",
  "Spółka cywilna nie ma osobowości ani zdolności prawnej; wspólnicy wpisują się do CEIDG."),
 (7, "m", "Które z poniższych zwiększają kapitał własny spółki?",
  ["Zysk netto zatrzymany w spółce", "Emisja nowych akcji", "Wypłata dywidendy", "Zaciągnięcie kredytu"], "AB",
  "Dywidenda zmniejsza kapitał własny, a kredyt zwiększa zobowiązania."),
 (7, "m", "Które czynności są przykładami zarządzania ryzykiem walutowym przez eksportera?",
  ["Zawarcie kontraktu forward", "Zakup opcji walutowej", "Fakturowanie w walucie krajowej", "Zwiększenie kosztów w złotych przy przychodach w euro"], "ABC",
  "Zwiększanie kosztów w złotych przy przychodach w euro pogłębia niedopasowanie walutowe – naturalny hedging wymagałby kosztów w euro."),
 (7, "m", "Które twierdzenia o wycenie zapasów przy rosnących cenach są prawdziwe?",
  ["FIFO daje wyższy zysk niż LIFO", "LIFO daje wyższy koszt sprzedanych towarów niż FIFO", "Metoda wyceny nie wpływa na zysk", "FIFO daje wyższą wartość zapasów końcowych"], "ABD",
  "Przy rosnących cenach FIFO przypisuje sprzedaży starsze, tańsze partie – koszt jest niższy, a zysk i zapasy końcowe wyższe."),
]
