# -*- coding: utf-8 -*-
# Dział 8 – Zarządzanie, marketing i organizacja, partia 2
M = [
 (8, "s", "Według H. Mintzberga kierownik, który reprezentuje organizację podczas uroczystości i podpisuje oficjalne dokumenty, pełni rolę:",
  ["reprezentanta (figuranta) – rola interpersonalna", "przedsiębiorcy – rola decyzyjna", "monitora – rola informacyjna", "negocjatora – rola decyzyjna"], "A",
  "Mintzberg (1973) wyróżnił 10 ról: interpersonalne (reprezentant, przywódca, łącznik), informacyjne (monitor, propagator, rzecznik) i decyzyjne (przedsiębiorca, przeciwdziałający zakłóceniom, dysponent zasobów, negocjator)."),
 (8, "s", "Umiejętność dostrzegania organizacji jako całości i zależności między jej częściami a otoczeniem to według R. Katza umiejętność:",
  ["koncepcyjna", "techniczna", "interpersonalna", "manualna"], "A",
  "Katz: techniczne (najważniejsze dla kierowników niższego szczebla), interpersonalne (na każdym szczeblu), koncepcyjne (najważniejsze dla naczelnego kierownictwa)."),
 (8, "s", "Kierownicy średniego szczebla to np.:",
  ["dyrektorzy zakładów i kierownicy działów realizujący strategię naczelnego kierownictwa", "członkowie zarządu spółki", "brygadziści nadzorujący pracowników wykonawczych", "akcjonariusze"], "A",
  "Naczelne kierownictwo (zarząd) – strategia; średni szczebel – wdrażanie i koordynacja; pierwsza linia (mistrzowie, brygadziści) – bezpośredni nadzór nad wykonawcami."),
 (8, "s", "Sprawność organizacji (efficiency) oznacza:",
  ["wykorzystanie zasobów w racjonalny sposób, bez marnotrawstwa", "osiągnięcie zamierzonych celów niezależnie od kosztów", "wysoki udział w rynku", "duże zatrudnienie"], "A",
  "Griffin: sprawność – „robić rzeczy właściwie” (relacja efektów do nakładów); skuteczność – „robić właściwe rzeczy” (stopień osiągnięcia celów)."),
 (8, "s", "Cele SMART to cele:",
  ["konkretne, mierzalne, osiągalne, istotne i określone w czasie", "strategiczne, marketingowe, administracyjne, rynkowe i techniczne", "ustalane wyłącznie przez akcjonariuszy", "niemierzalne, ale ambitne"], "A",
  "Specific, Measurable, Achievable (Attainable), Relevant (Realistic), Time-bound – wzorzec formułowania celów (np. w MBO)."),
 (8, "s", "Misja organizacji to:",
  ["ogólne określenie celu istnienia organizacji i jej wartości", "szczegółowy plan finansowy na rok", "lista stanowisk pracy", "budżet marketingowy"], "A",
  "Wizja opisuje pożądany stan w przyszłości, misja – po co organizacja istnieje i komu służy; z nich wynikają cele strategiczne."),
 (8, "s", "Analiza PEST (PESTEL) służy do badania:",
  ["makrootoczenia: czynników politycznych, ekonomicznych, społecznych i technologicznych (oraz ekologicznych i prawnych)", "kosztów produkcji", "kompetencji pracowników", "struktury organizacyjnej"], "A",
  "Pięć sił Portera bada otoczenie konkurencyjne (sektor), a SWOT łączy analizę otoczenia z analizą wnętrza organizacji."),
 (8, "s", "Strategia przywództwa kosztowego według M. Portera polega na:",
  ["osiągnięciu najniższych kosztów w branży i konkurowaniu ceną", "oferowaniu wyjątkowego produktu po wysokiej cenie", "obsłudze jednej niszy", "dywersyfikacji w niepowiązane branże"], "A",
  "Strategie generyczne Portera: przywództwo kosztowe, zróżnicowanie (dyferencjacja), koncentracja (na niszy – kosztowa lub przez zróżnicowanie). Firma „utknięta pośrodku” nie ma przewagi."),
 (8, "s", "Firma, która agresywnie szuka nowych rynków i produktów, akceptując ryzyko, to w typologii Milesa i Snowa:",
  ["poszukiwacz (prospector)", "obrońca (defender)", "analizator (analyzer)", "reagujący (reactor)"], "A",
  "Obrońca utrzymuje pozycję na wąskim rynku, analizator łączy stabilność z ostrożnym rozwojem, reagujący nie ma spójnej strategii."),
 (8, "s", "Integracja pionowa wstecz to przykład sytuacji, w której:",
  ["producent przejmuje swojego dostawcę surowców", "producent przejmuje sieć sklepów", "firma łączy się z konkurentem", "firma wchodzi w niepowiązaną branżę"], "A",
  "Integracja wstecz – w stronę dostawców; w przód – w stronę odbiorców (dystrybucja); pozioma – z konkurentem."),
 (8, "s", "Joint venture to:",
  ["wspólne przedsięwzięcie kilku firm, często w formie nowej spółki o wspólnej własności", "fuzja dwóch spółek w jedną", "przejęcie wrogie", "outsourcing usług"], "A",
  "Forma aliansu strategicznego – dzielenie ryzyka i zasobów (np. wejście na rynek zagraniczny z lokalnym partnerem)."),
 (8, "s", "Franczyza polega na tym, że:",
  ["franczyzodawca udostępnia markę, know-how i system działania franczyzobiorcy w zamian za opłaty", "firma sprzedaje licencję na patent", "pracownik kupuje udziały pracodawcy", "państwo przekazuje majątek samorządowi"], "A",
  "Przykłady: sieci restauracji, sklepów (Żabka); franczyzobiorca jest niezależnym przedsiębiorcą."),
 (8, "s", "Struktura organizacyjna, w której jednostki tworzy się według produktów lub rynków, a każda ma własne działy funkcjonalne, to struktura:",
  ["dywizjonalna (typu M)", "funkcjonalna (typu U)", "macierzowa", "liniowa"], "A",
  "Dywizjonalna sprzyja odpowiedzialności za wyniki jednostek biznesowych, ale dubluje funkcje; funkcjonalna grupuje według funkcji (produkcja, sprzedaż, finanse)."),
 (8, "s", "Struktura organizacyjna płaska charakteryzuje się:",
  ["małą liczbą szczebli i szeroką rozpiętością kierowania", "dużą liczbą szczebli i wąską rozpiętością", "brakiem kierowników", "tylko jednym pracownikiem"], "A",
  "Spłaszczanie struktur (delayering) przyspiesza komunikację i decyzje, ale zwiększa obciążenie kierowników."),
 (8, "s", "Centralizacja w organizacji oznacza:",
  ["skupienie uprawnień decyzyjnych na wyższych szczeblach", "przekazywanie decyzji na niższe szczeble", "brak hierarchii", "zlecanie zadań firmom zewnętrznym"], "A",
  "Decentralizacja zwiększa elastyczność i motywację, centralizacja – kontrolę i spójność decyzji."),
 (8, "s", "Biurokracja w ujęciu M. Webera to model organizacji oparty na:",
  ["formalnych regułach, hierarchii, specjalizacji i bezosobowości", "nieformalnych relacjach", "charyzmie przywódcy", "braku dokumentacji"], "A",
  "Weber uważał biurokrację za najbardziej racjonalną formę organizacji; potoczne znaczenie (nadmiar formalności) to jej dysfunkcja."),
 (8, "s", "Eksperymenty w zakładach Hawthorne (E. Mayo) wykazały, że:",
  ["na wydajność silnie wpływają czynniki społeczne i poczucie uwagi ze strony kierownictwa", "wydajność zależy wyłącznie od oświetlenia", "pracownicy reagują tylko na płacę akordową", "grupy nieformalne nie mają znaczenia"], "A",
  "Tzw. efekt Hawthorne'a dał początek szkole stosunków międzyludzkich."),
 (8, "s", "Teoria oczekiwań V. Vrooma zakłada, że motywacja zależy od:",
  ["oczekiwania, że wysiłek da wynik, instrumentalności wyniku dla nagrody i wartości nagrody (walencji)", "hierarchii potrzeb", "czynników higieny", "kar i przymusu"], "A",
  "M = oczekiwanie × instrumentalność × walencja – jeśli którykolwiek element jest zerowy, motywacja znika."),
 (8, "s", "Pracownik obniża zaangażowanie, bo kolega na tym samym stanowisku zarabia więcej za tę samą pracę. Zjawisko to wyjaśnia teoria:",
  ["sprawiedliwości (J.S. Adams)", "ERG Alderfera", "X i Y McGregora", "dwuczynnikowa Herzberga"], "A",
  "Pracownicy porównują relację swoich wkładów do nagród z relacją innych; poczucie niesprawiedliwości prowadzi do zmiany zachowań."),
 (8, "s", "Wzmocnienie pozytywne w teorii wzmocnień (B.F. Skinner) to:",
  ["nagradzanie pożądanego zachowania, aby było powtarzane", "karanie niepożądanego zachowania", "ignorowanie zachowań", "usunięcie nagrody"], "A",
  "Wzmocnienie negatywne – usunięcie czegoś nieprzyjemnego po pożądanym zachowaniu; kara i wygaszanie osłabiają zachowania."),
 (8, "s", "Wzbogacanie pracy (job enrichment) polega na:",
  ["zwiększeniu odpowiedzialności, autonomii i kontroli pracownika nad pracą", "dodaniu kolejnych, podobnych zadań tego samego szczebla", "rotacji pracowników między stanowiskami", "zwiększeniu płacy akordowej"], "A",
  "Poszerzanie pracy (job enlargement) dodaje zadania poziomo, wzbogacanie – pionowo (zadania kierownicze), zgodnie z teorią Herzberga."),
 (8, "s", "Siatka kierownicza Blake’a i Mouton wyróżnia styl (9,9) jako:",
  ["styl zespołowy – wysoka troska o ludzi i o zadania", "styl klubowy", "styl zubożały", "styl autorytarny"], "A",
  "(1,1) – zubożały, (1,9) – klubowy, (9,1) – zadaniowy (autorytarny), (5,5) – kompromisowy, (9,9) – zespołowy, uznawany za najbardziej efektywny."),
 (8, "s", "Według modelu F. Fiedlera skuteczność przywódcy zależy od:",
  ["dopasowania stylu (zorientowanego na zadania lub ludzi) do sytuacji: relacji z podwładnymi, struktury zadania i władzy formalnej", "wyłącznie cech osobowości", "płacy", "liczby podwładnych"], "A",
  "Fiedler uważał styl za stały, więc należy dobierać przywódcę do sytuacji (miara LPC – najmniej preferowany współpracownik)."),
 (8, "s", "Przywódca transformacyjny:",
  ["inspiruje podwładnych wizją i zmienia ich wartości oraz aspiracje", "opiera się wyłącznie na wymianie nagród za wyniki", "unika podejmowania decyzji", "kieruje tylko za pomocą przepisów"], "A",
  "Przywództwo transakcyjne opiera się na wymianie (nagroda za wykonanie), transformacyjne – na inspiracji i zmianie."),
 (8, "s", "Władza wynikająca z wiedzy i doświadczenia kierownika to według J. Frencha i B. Ravena władza:",
  ["ekspercka", "nagradzania", "przymusu", "prawomocna (z mianowania)"], "A",
  "Pięć źródeł władzy: prawomocna, nagradzania, przymusu, ekspercka i odniesienia (charyzmatyczna)."),
 (8, "s", "Zjawisko „myślenia grupowego” (groupthink, I. Janis) polega na tym, że:",
  ["dążenie do zgody w spójnej grupie tłumi krytykę i prowadzi do złych decyzji", "grupa podejmuje decyzje szybciej niż jednostka", "członkowie grupy zawsze się kłócą", "decyzje podejmuje się w drodze losowania"], "A",
  "Przeciwdziałanie: adwokat diabła, zapraszanie ekspertów zewnętrznych, technika delficka, burza mózgów z oddzieleniem generowania i oceny pomysłów."),
 (8, "s", "Metoda delficka to:",
  ["anonimowe, wieloetapowe zbieranie i uzgadnianie opinii ekspertów", "burza mózgów na żywo", "analiza SWOT", "losowe podejmowanie decyzji"], "A",
  "Stosowana w prognozowaniu – eksperci poznają zbiorcze wyniki poprzednich rund i korygują oceny, bez presji grupy."),
 (8, "s", "Model ograniczonej racjonalności (H. Simon) zakłada, że decydenci:",
  ["wybierają rozwiązanie zadowalające, a nie optymalne, z powodu ograniczonej informacji i czasu", "zawsze wybierają rozwiązanie optymalne", "decydują losowo", "nie biorą pod uwagę kosztów"], "A",
  "Simon (Nobel 1978) – satysfakcjonowanie (satisficing) zamiast maksymalizacji."),
 (8, "s", "Kontrola wstępna (prewencyjna) to kontrola:",
  ["prowadzona przed rozpoczęciem działania, np. sprawdzanie jakości surowców", "prowadzona po zakończeniu działania", "wyłącznie finansowa", "dokonywana przez klientów"], "A",
  "Rodzaje kontroli według czasu: wstępna, bieżąca (sterująca), końcowa (po działaniu)."),
 (8, "s", "Zrównoważona karta wyników (Kaplan i Norton) obejmuje perspektywy:",
  ["finansową, klienta, procesów wewnętrznych oraz uczenia się i rozwoju", "produkcyjną, kadrową, podatkową i prawną", "rynku, konkurencji, państwa i UE", "tylko finansową"], "A",
  "Balanced Scorecard (1992) przekłada strategię na mierniki w czterech perspektywach, nie ograniczając oceny do wskaźników finansowych."),
 (8, "s", "Kaizen to koncepcja:",
  ["ciągłego doskonalenia małymi krokami z udziałem wszystkich pracowników", "radykalnej przebudowy procesów", "outsourcingu", "zarządzania przez cele"], "A",
  "Kaizen (Japonia) kontrastuje z reengineeringiem (M. Hammer, J. Champy) – radykalnym przeprojektowaniem procesów."),
 (8, "s", "Cykl Deminga (PDCA) składa się z etapów:",
  ["planuj – wykonaj – sprawdź – działaj", "analizuj – projektuj – wdrażaj – oceniaj", "zdefiniuj – zmierz – analizuj – kontroluj", "organizuj – motywuj – kontroluj – nagradzaj"], "A",
  "Plan-Do-Check-Act – podstawa zarządzania jakością (TQM, normy ISO 9001); DMAIC to cykl Six Sigma."),
 (8, "s", "Normy ISO 9001 dotyczą:",
  ["systemów zarządzania jakością", "zarządzania środowiskowego", "bezpieczeństwa informacji", "rachunkowości"], "A",
  "ISO 14001 – zarządzanie środowiskowe, ISO 27001 – bezpieczeństwo informacji, ISO 45001 – BHP."),
 (8, "s", "Ścieżka krytyczna w zarządzaniu projektem to:",
  ["najdłuższy ciąg zależnych czynności, który wyznacza najkrótszy możliwy czas realizacji projektu", "najtańsza ścieżka realizacji", "lista zadań bez terminów", "ścieżka awansu kierownika projektu"], "A",
  "Opóźnienie czynności na ścieżce krytycznej (CPM/PERT) opóźnia cały projekt; wykres Gantta przedstawia harmonogram."),
 (8, "s", "Segmentacja rynku według stylu życia, wartości i osobowości to segmentacja:",
  ["psychograficzna", "demograficzna", "geograficzna", "behawioralna"], "A",
  "Behawioralna – według zachowań (częstotliwość zakupu, lojalność, poszukiwane korzyści); demograficzna – wiek, płeć, dochód; geograficzna – region."),
 (8, "s", "Pozycjonowanie produktu to:",
  ["kształtowanie miejsca, jakie produkt zajmuje w świadomości klientów względem konkurencji", "ustawienie produktu na półce", "ustalanie ceny", "wybór kanału dystrybucji"], "A",
  "Po segmentacji i wyborze rynku docelowego (STP) firma określa, czym ma się wyróżniać (np. „najbezpieczniejszy samochód”)."),
 (8, "s", "Strategia „pull” w promocji polega na:",
  ["kierowaniu działań do konsumentów, aby sami domagali się produktu u pośredników", "zachęcaniu pośredników do sprzedaży produktu (rabaty, prowizje)", "obniżaniu ceny poniżej kosztu", "rezygnacji z reklamy"], "A",
  "Push – „wypychanie” produktu przez kanał dystrybucji; pull – „przyciąganie” popytu reklamą i promocją konsumencką."),
 (8, "s", "Dystrybucja intensywna jest typowa dla:",
  ["dóbr codziennego użytku (np. napoje, gazety)", "dóbr luksusowych", "maszyn przemysłowych", "nieruchomości"], "A",
  "Selektywna – wybrani pośrednicy (np. AGD), wyłączna – jeden pośrednik na obszarze (np. luksusowe samochody)."),
 (8, "s", "Cena psychologiczna to np.:",
  ["9,99 zł zamiast 10 zł", "cena ustalona przez państwo", "cena dumpingowa", "cena transferowa"], "A",
  "Wykorzystuje percepcję klientów (efekt lewej cyfry); inne techniki: ceny prestiżowe, pakietowe, kotwiczenie."),
 (8, "s", "Marketing szeptany to:",
  ["celowe wywoływanie rekomendacji i rozmów o produkcie między konsumentami", "reklama w radiu", "sprzedaż osobista", "akcja promocyjna w sklepie"], "A",
  "Word-of-mouth marketing wymaga etycznej przejrzystości – ukryta reklama jest nieuczciwą praktyką rynkową."),
 (8, "s", "Dyfuzja innowacji (E. Rogers) dzieli nabywców na grupy według szybkości przyjmowania nowości; pierwszą grupę stanowią:",
  ["innowatorzy (ok. 2,5%)", "wczesna większość", "maruderzy", "późna większość"], "A",
  "Kolejno: innowatorzy (2,5%), wcześni naśladowcy (13,5%), wczesna większość (34%), późna większość (34%), maruderzy (16%)."),
 (8, "s", "Innowacja przełomowa (disruptive, C. Christensen) to taka, która:",
  ["zaczyna od prostszych, tańszych rozwiązań dla niszy i stopniowo wypiera liderów rynku", "jest drobnym ulepszeniem istniejącego produktu", "jest zawsze droższa od dotychczasowych", "nie zmienia rynku"], "A",
  "Przykłady: aparaty cyfrowe wobec kliszowych, streaming wobec wypożyczalni. Innowacje przyrostowe ulepszają istniejące produkty."),
 (8, "s", "Kultura organizacyjna według E. Scheina ma trzy poziomy:",
  ["artefakty, deklarowane wartości i podstawowe założenia", "misję, wizję i cele", "zarząd, kierowników i pracowników", "planowanie, organizowanie i kontrolę"], "A",
  "Artefakty są widoczne (ubiór, rytuały), wartości – deklarowane, a podstawowe założenia – nieuświadomione przekonania wpływające na zachowania."),
 (8, "s", "Wymiar „dystans władzy” w badaniach G. Hofstede opisuje:",
  ["stopień akceptacji nierównego podziału władzy w społeczeństwie i organizacjach", "odległość siedziby od klientów", "liczbę szczebli zarządzania", "poziom płac kierowników"], "A",
  "Inne wymiary: indywidualizm–kolektywizm, męskość–kobiecość, unikanie niepewności, orientacja długoterminowa, pobłażliwość."),
 (8, "s", "Opór pracowników wobec zmian według K. Lewina można przezwyciężyć w procesie:",
  ["rozmrożenia, zmiany i ponownego zamrożenia", "planowania, organizowania i kontroli", "rekrutacji, selekcji i adaptacji", "analizy, syntezy i oceny"], "A",
  "Model trzech faz zmiany; analiza pola sił – zwiększanie sił napędowych i osłabianie hamujących."),
 (8, "s", "Organizacja ucząca się według P. Senge opiera się na pięciu dyscyplinach, w tym:",
  ["myśleniu systemowym", "ścisłej hierarchii", "wyłącznej kontroli finansowej", "zakazie pracy zespołowej"], "A",
  "Pięć dyscyplin („Piąta dyscyplina”, 1990): mistrzostwo osobiste, modele myślowe, wspólna wizja, zespołowe uczenie się, myślenie systemowe."),
 (8, "s", "Rekrutacja wewnętrzna w porównaniu z zewnętrzną:",
  ["jest tańsza i motywuje pracowników perspektywą awansu, ale ogranicza dopływ nowych pomysłów", "zawsze przyciąga więcej kandydatów", "nie wymaga oceny kandydatów", "jest zakazana w spółkach akcyjnych"], "A",
  "Rekrutacja zewnętrzna wnosi nowe kompetencje, ale jest droższa i dłuższa."),
 (8, "s", "Ocena pracownika metodą 360 stopni polega na:",
  ["zbieraniu ocen od przełożonych, współpracowników, podwładnych i klientów", "ocenie wyłącznie przez przełożonego", "samoocenie pracownika", "ocenie przez związek zawodowy"], "A",
  "Daje pełniejszy obraz kompetencji, ale wymaga zaufania i anonimowości ocen."),
 (8, "s", "Outsourcing w zarządzaniu to:",
  ["zlecanie wybranych funkcji (np. IT, księgowości) wyspecjalizowanym firmom zewnętrznym", "zatrudnianie pracowników na etat", "przenoszenie siedziby do raju podatkowego", "zakup udziałów konkurencji"], "A",
  "Pozwala skupić się na kluczowych kompetencjach i obniżyć koszty; ryzyka to utrata kontroli i zależność od dostawcy."),
 # --- wielokrotny wybór (1, 2, 4 poprawne) ---
 (8, "m", "Które z poniższych są funkcjami (procesami) zarządzania według klasycznego ujęcia?",
  ["Planowanie", "Organizowanie", "Przewodzenie (motywowanie)", "Kontrolowanie"], "ABCD",
  "Wszystkie cztery tworzą klasyczny cykl zarządzania (Griffin, Stoner)."),
 (8, "m", "Które elementy należą do analizy wnętrza organizacji (a nie otoczenia)?",
  ["Mocne strony", "Słabe strony", "Szanse", "Zagrożenia"], "AB",
  "Szanse i zagrożenia pochodzą z otoczenia."),
 (8, "m", "Które z poniższych należą do otoczenia bliższego (zadaniowego) firmy?",
  ["Klienci", "Dostawcy", "Sytuacja demograficzna kraju", "Postęp technologiczny na świecie"], "AB",
  "Demografia i technologia to otoczenie ogólne (makrootoczenie)."),
 (8, "m", "Które cechy dotyczą struktury funkcjonalnej (typu U)?",
  ["Grupowanie stanowisk według funkcji (produkcja, sprzedaż, finanse)", "Specjalizacja i efektywność w dużej skali", "Pełna samodzielność wydziałów produktowych z własnym rachunkiem zysków", "Podwójna podległość pracowników"], "AB",
  "Samodzielne wydziały to struktura dywizjonalna, podwójna podległość – macierzowa."),
 (8, "m", "Które teorie motywacji są teoriami treści (dotyczącymi potrzeb)?",
  ["Hierarchia potrzeb Maslowa", "Teoria ERG Alderfera", "Teoria oczekiwań Vrooma", "Teoria sprawiedliwości Adamsa"], "AB",
  "Teorie Vrooma i Adamsa są teoriami procesu (jak przebiega motywowanie)."),
 (8, "m", "Która ze strategii Portera polega na obsłudze wąskiego segmentu rynku?",
  ["Koncentracja", "Przywództwo kosztowe", "Zróżnicowanie w skali całego rynku", "Dywersyfikacja konglomeratowa"], "A",
  "Koncentracja (focus) – obsługa niszy kosztowo lub przez zróżnicowanie; dywersyfikacja nie jest strategią generyczną Portera."),
 (8, "m", "Które z poniższych należą do elementów 7P marketingu usług (poza klasycznym 4P)?",
  ["Ludzie (People)", "Proces (Process)", "Świadectwo materialne (Physical evidence)", "Cena (Price)"], "ABC",
  "Cena należy do klasycznego 4P."),
 (8, "m", "Które cechy mają usługi w odróżnieniu od dóbr materialnych?",
  ["Niematerialność", "Nierozdzielność produkcji i konsumpcji", "Nietrwałość (niemożność magazynowania)", "Zmienność (heterogeniczność) jakości"], "ABCD",
  "Wszystkie cztery cechy utrudniają standaryzację i wymagają m.in. dbałości o personel."),
 (8, "m", "Które z poniższych to narzędzia promocji (komunikacji marketingowej)?",
  ["Reklama", "Public relations", "Dystrybucja wyłączna", "Ustalanie cen pakietowych"], "AB",
  "Dystrybucja (place) i ceny to inne elementy marketingu mix."),
 (8, "m", "Które zachowania oznaczają styl kierowania autokratyczny?",
  ["Samodzielne podejmowanie decyzji przez kierownika", "Ścisła kontrola wykonania", "Konsultowanie decyzji z zespołem", "Pozostawienie pracownikom pełnej swobody"], "AB",
  "Konsultacje to styl demokratyczny, pełna swoboda – liberalny."),
 (8, "m", "Które czynniki są według Herzberga czynnikami motywacyjnymi?",
  ["Uznanie za osiągnięcia", "Odpowiedzialność", "Warunki pracy", "Polityka firmy"], "AB",
  "Warunki pracy i polityka firmy to czynniki higieny."),
 (8, "m", "Które z poniższych opisują fazy rozwoju zespołu według B. Tuckmana?",
  ["Formowanie", "Docieranie się (burza)", "Normowanie", "Działanie (wykonywanie)"], "ABCD",
  "Tuckman (1965) dodał później fazę rozwiązania (adjourning)."),
 (8, "m", "Które cechy dotyczą komunikacji nieformalnej w organizacji (poczty pantoflowej)?",
  ["Szybko rozprzestrzenia informacje", "Może przenosić plotki i zniekształcenia", "Przebiega wyłącznie zgodnie ze schematem organizacyjnym", "Kierownictwo może ją całkowicie wyeliminować"], "AB",
  "Komunikacja nieformalna omija oficjalne kanały i nie da się jej wyeliminować – można ją jedynie wykorzystywać i uzupełniać rzetelną informacją."),
 (8, "m", "Które z poniższych są metodami doskonalenia jakości lub koncepcjami zarządzania jakością?",
  ["TQM", "Six Sigma", "Kaizen", "Macierz BCG"], "ABC",
  "Macierz BCG służy do analizy portfela produktów."),
 (8, "m", "Które z poniższych to bariery w komunikacji?",
  ["Szum informacyjny", "Różnice kulturowe i językowe", "Selektywna percepcja odbiorcy", "Aktywne słuchanie"], "ABC",
  "Aktywne słuchanie to sposób pokonywania barier."),
 (8, "m", "Które cechy ma struktura macierzowa?",
  ["Podwójna podległość pracowników", "Jedność rozkazodawstwa", "Elastyczność w realizacji projektów", "Brak jakiejkolwiek koordynacji"], "AC",
  "Struktura macierzowa narusza jedność rozkazodawstwa i wymaga intensywnej koordynacji."),
 (8, "m", "Które z poniższych należą do pięciu dyscyplin organizacji uczącej się P. Senge’a?",
  ["Mistrzostwo osobiste", "Modele myślowe", "Wspólna wizja", "Zespołowe uczenie się"], "ABCD",
  "Piątą dyscypliną (integrującą) jest myślenie systemowe."),
 (8, "m", "Które z poniższych to przykłady integracji pionowej w przód?",
  ["Producent odzieży otwiera własne sklepy", "Browar kupuje sieć pubów", "Piekarnia kupuje młyn", "Bank łączy się z innym bankiem"], "AB",
  "Zakup młyna przez piekarnię to integracja wstecz, połączenie banków – pozioma."),
 (8, "m", "Które cechy przypisuje się przywództwu transformacyjnemu?",
  ["Inspirująca wizja", "Indywidualne podejście do rozwoju podwładnych", "Wyłącznie wymiana nagród za wykonanie zadań", "Stymulowanie intelektualne"], "ABD",
  "Wymiana nagród za wykonanie to przywództwo transakcyjne."),
 (8, "m", "Które z poniższych to wymiary kultury narodowej według G. Hofstede?",
  ["Dystans władzy", "Indywidualizm–kolektywizm", "Unikanie niepewności", "Rozpiętość kierowania"], "ABC",
  "Rozpiętość kierowania to pojęcie z teorii struktur organizacyjnych."),
 (8, "m", "Które z poniższych dotyczą macierzy BCG?",
  ["Względny udział w rynku", "Tempo wzrostu rynku", "Atrakcyjność sektora i pozycja konkurencyjna (9 pól)", "Faza cyklu życia sektora"], "AB",
  "9 pól to macierz GE/McKinsey, faza cyklu życia sektora – macierz ADL."),
 (8, "m", "Które z poniższych opisują fazę dojrzałości w cyklu życia produktu?",
  ["Sprzedaż osiąga maksimum", "Nasila się konkurencja cenowa", "Produkt jest dopiero wprowadzany na rynek", "Zyski są zwykle ujemne"], "AB",
  "Wprowadzenie i ujemne zyski to cechy pierwszej fazy."),
 (8, "m", "Które z poniższych należą do zadań działu zarządzania zasobami ludzkimi?",
  ["Rekrutacja i selekcja", "Szkolenia i rozwój", "Ocena pracownicza", "Wynagradzanie"], "ABCD",
  "Wszystkie cztery to podstawowe funkcje ZZL (HRM)."),
 (8, "m", "Która technika podejmowania decyzji grupowych polega na anonimowym, wielorundowym zbieraniu opinii ekspertów?",
  ["Metoda delficka", "Burza mózgów", "Metoda grupy nominalnej", "Adwokat diabła"], "A",
  "Burza mózgów odbywa się na żywo, grupa nominalna łączy indywidualne generowanie pomysłów z głosowaniem, adwokat diabła to celowa krytyka propozycji."),
 (8, "m", "Które z poniższych zjawisk dotyczy kontroli końcowej?",
  ["Analiza wyników finansowych po zakończeniu roku", "Sprawdzanie surowców przed produkcją", "Bieżące monitorowanie linii produkcyjnej", "Szkolenie przed rozpoczęciem pracy"], "A",
  "Kontrola surowców i szkolenia to kontrola wstępna, monitorowanie linii – bieżąca."),
]
