# -*- coding: utf-8 -*-
# Dział 9 – Wzory (zadania obliczeniowe), partia 2
M = [
 (9, "s", "Kredyt 100 000 zł na 10 lat w ratach równych (annuitetowych), oprocentowanie 12% rocznie (1% miesięcznie). Miesięczna rata wynosi około:",
  ["1435 zł", "1833 zł", "1000 zł", "1200 zł"], "A",
  "Rata = K · r / (1 − (1 + r)^(−n)) = 100 000 · 0,01 / (1 − 1,01^(−120)) ≈ 1434,71 zł. Łącznie spłata ok. 172 tys. zł."),
 (9, "s", "Renta 1000 zł płatna na koniec każdego roku przez 5 lat, stopa 8%. Jej wartość obecna wynosi około:",
  ["3993 zł", "5000 zł", "4630 zł", "5867 zł"], "A",
  "PV = 1000 · (1 − 1,08^(−5)) / 0,08 ≈ 3992,71 zł."),
 (9, "s", "Wpłacając 500 zł na koniec każdego roku przez 10 lat przy 5% rocznie, zgromadzimy około:",
  ["6289 zł", "5000 zł", "7500 zł", "8144 zł"], "A",
  "FV = 500 · ((1,05)^10 − 1) / 0,05 ≈ 6288,95 zł (przyszła wartość renty)."),
 (9, "s", "Obligacja 3-letnia, nominał 1000 zł, kupon 6% rocznie, wymagana rentowność 5%. Cena wynosi około:",
  ["1027 zł", "1000 zł", "973 zł", "1060 zł"], "A",
  "P = 60/1,05 + 60/1,05² + 1060/1,05³ ≈ 1027,23 zł – kupon wyższy od rentowności, więc cena powyżej nominału."),
 (9, "s", "Akcja kosztuje 50 zł, oczekiwana dywidenda za rok to 2 zł, a inwestorzy wymagają 9% stopy zwrotu. Jakie tempo wzrostu dywidend (stałe) zakłada rynek według modelu Gordona?",
  ["5%", "4%", "9%", "13%"], "A",
  "k = D₁/P₀ + g ⇒ g = 9% − 2/50 = 9% − 4% = 5% (stopa dywidendy 4% + wzrost 5%)."),
 (9, "s", "Roczne zużycie materiału 36 000 kg, koszt zamówienia 80 zł, roczny koszt utrzymania 1 kg zapasu 4,50 zł. EOQ wynosi około:",
  ["1131 kg", "800 kg", "1600 kg", "640 kg"], "A",
  "EOQ = √(2 · 36 000 · 80 / 4,5) = √1 280 000 ≈ 1131 kg; liczba zamówień rocznie ≈ 32."),
 (9, "s", "Lokata daje 7% nominalnie, inflacja wynosi 2,5%. Realna stopa zwrotu (dokładnie) wynosi około:",
  ["4,39%", "4,50%", "9,68%", "2,80%"], "A",
  "r = 1,07 / 1,025 − 1 ≈ 4,39%; przybliżenie 7% − 2,5% = 4,5%."),
 (9, "s", "Wartość bieżąca wpływów z projektu wynosi 13 200 zł, a nakład początkowy 12 000 zł. Wskaźnik rentowności (PI) wynosi:",
  ["1,10", "0,91", "1 200 zł", "0,10"], "A",
  "PI = PV wpływów / nakład = 13 200 / 12 000 = 1,10 > 1, więc NPV = 1200 zł > 0 – projekt opłacalny."),
 (9, "s", "Kredyt jest oprocentowany na 10%, a stawka CIT wynosi 19%. Efektywny koszt długu po uwzględnieniu tarczy podatkowej wynosi:",
  ["8,1%", "10,0%", "1,9%", "11,9%"], "A",
  "kd · (1 − T) = 10% · 0,81 = 8,1% – odsetki obniżają podatek dochodowy."),
 (9, "s", "Nominalna stopa 8% rocznie przy kapitalizacji kwartalnej odpowiada efektywnej stopie rocznej około:",
  ["8,24%", "8,00%", "8,33%", "8,16%"], "A",
  "r_ef = (1 + 0,08/4)^4 − 1 ≈ 8,24%."),
 (9, "s", "Kwota 10 000 zł do otrzymania za 5 lat przy stopie dyskontowej 4% jest dziś warta około:",
  ["8219 zł", "8000 zł", "9615 zł", "12 167 zł"], "A",
  "PV = 10 000 / 1,04^5 ≈ 8219,27 zł."),
 (9, "s", "Według reguły 72 kapitał oprocentowany na 9% rocznie podwoi się po około:",
  ["8 latach", "9 latach", "6 latach", "12 latach"], "A",
  "72 / 9 = 8 lat (reguła 72 jest dokładniejsza dla stóp ok. 6–10% niż reguła 70)."),
 (9, "s", "Portfel składa się w 60% z akcji o becie 1,5 i w 40% z akcji o becie 0,5. Beta portfela wynosi:",
  ["1,1", "1,0", "2,0", "0,9"], "A",
  "Beta portfela to średnia ważona: 0,6 · 1,5 + 0,4 · 0,5 = 0,9 + 0,2 = 1,1."),
 (9, "s", "Stopień dźwigni finansowej spółki wynosi 1,5. Zysk operacyjny (EBIT) wzrośnie o 8%. Zysk netto wzrośnie o:",
  ["12%", "8%", "5,3%", "9,5%"], "A",
  "%ΔZN = DFL · %ΔEBIT = 1,5 · 8% = 12% (dźwignia działa też przy spadkach – zysk netto spadłby o 12%)."),
 (9, "s", "Mnożnik pieniężny wynosi 6. Bank centralny zwiększa bazę monetarną o 5 mld zł. Podaż pieniądza wzrośnie (przy stałym mnożniku) o:",
  ["30 mld zł", "5 mld zł", "0,83 mld zł", "11 mld zł"], "A",
  "ΔM = m · ΔB = 6 · 5 = 30 mld zł."),
 (9, "s", "Ceny wzrosły w kolejnych latach o 5% i 4%. Łączny wzrost cen w ciągu dwóch lat wyniósł:",
  ["9,2%", "9,0%", "4,5%", "20%"], "A",
  "1,05 · 1,04 = 1,092 ⇒ 9,2% (indeksy łańcuchowe mnożymy, nie dodajemy)."),
 (9, "s", "Średnie wynagrodzenie nominalne wzrosło o 12%, a ceny o 8%. Wynagrodzenie realne wzrosło o około:",
  ["3,7%", "4,0%", "20,0%", "1,5%"], "A",
  "1,12 / 1,08 ≈ 1,037 ⇒ ok. 3,7% (przybliżenie 12% − 8% = 4%)."),
 (9, "s", "Deflator PKB wynosi 125, a nominalny PKB 3000 mld zł. Realny PKB (w cenach roku bazowego) wynosi:",
  ["2400 mld zł", "3750 mld zł", "2875 mld zł", "3125 mld zł"], "A",
  "Realny PKB = nominalny / deflator · 100 = 3000 / 1,25 = 2400 mld zł."),
 (9, "s", "W gospodarce 2 dobra: w roku bazowym jabłka 10 kg po 4 zł i chleb 5 szt. po 3 zł; w roku bieżącym jabłka po 5 zł, chleb po 3,60 zł. Indeks Laspeyresa (koszyk bazowy) wynosi:",
  ["123,6", "120,0", "125,0", "122,5"], "A",
  "Koszyk bazowy: 10·4 + 5·3 = 55 zł; w cenach bieżących: 10·5 + 5·3,60 = 68 zł; indeks = 68/55 · 100 ≈ 123,6 (ceny wzrosły średnio o 23,6%)."),
 (9, "s", "Popyt Qd = 80 − 4P, podaż Qs = 6P − 20. Nadwyżka konsumenta w równowadze wynosi:",
  ["200", "400", "100", "300"], "A",
  "Równowaga: 80 − 4P = 6P − 20 ⇒ P = 10, Q = 40. Cena maksymalna (Qd = 0) = 20; nadwyżka konsumenta = ½ · 40 · (20 − 10) = 200."),
 (9, "s", "Dla rynku Qd = 80 − 4P, Qs = 6P − 20 nadwyżka producenta w równowadze wynosi:",
  ["133,3", "200", "100", "266,7"], "A",
  "P = 10, Q = 40; podaż zaczyna się przy P = 20/6 ≈ 3,33. Nadwyżka producenta = ½ · 40 · (10 − 3,33) ≈ 133,3."),
 (9, "s", "Koszty stałe wynoszą 500 zł, a jednostkowy koszt zmienny jest stały i równy 20 zł. Przy jakiej produkcji przeciętny koszt całkowity spadnie do 25 zł?",
  ["100 szt.", "25 szt.", "50 szt.", "500 szt."], "A",
  "ATC = 500/Q + 20 = 25 ⇒ 500/Q = 5 ⇒ Q = 100 szt."),
 (9, "s", "Utarg całkowity monopolisty TR = 120Q − 3Q². Utarg krańcowy przy Q = 10 wynosi:",
  ["60", "90", "900", "30"], "A",
  "MR = dTR/dQ = 120 − 6Q = 120 − 60 = 60; cena przy Q = 10: P = TR/Q = 120 − 30 = 90."),
 (9, "s", "Monopolista: P = 120 − 3Q, MC = 30. Maksymalny zysk przy braku kosztów stałych wynosi:",
  ["675", "1350", "450", "900"], "A",
  "MR = 120 − 6Q = 30 ⇒ Q = 15, P = 75; zysk = (75 − 30) · 15 = 675."),
 (9, "s", "Gospodarka: C = 50 + 0,8Yd, I = 100, G = 150, T = 0,25Y (podatek proporcjonalny). Dochód równowagi wynosi:",
  ["750", "1500", "1000", "600"], "A",
  "Y = 50 + 0,8 · 0,75Y + 100 + 150 ⇒ Y − 0,6Y = 300 ⇒ Y = 750."),
 (9, "s", "W gospodarce z poprzedniego zadania (C = 50 + 0,8Yd, I = 100, G = 150, T = 0,25Y) saldo budżetu wynosi:",
  ["+37,5 (nadwyżka)", "−37,5 (deficyt)", "0", "−150"], "A",
  "T = 0,25 · 750 = 187,5; G = 150 ⇒ nadwyżka 37,5."),
 (9, "s", "Stopa bezrobocia wzrosła z 4% do 7%, a naturalna wynosi 5%. Według prawa Okuna (współczynnik 2) luka PKB wynosi:",
  ["−4%", "−6%", "−3%", "−2%"], "A",
  "Luka = −2 · (7% − 5%) = −4% produktu potencjalnego."),
 (9, "s", "Liczba ludności 38 mln, w wieku 15+ 32 mln, pracujący 17,5 mln, bezrobotni 0,7 mln. Współczynnik aktywności zawodowej wynosi około:",
  ["56,9%", "47,9%", "54,7%", "3,8%"], "A",
  "Aktywni = 18,2 mln; 18,2 / 32 ≈ 56,9%. Stopa bezrobocia = 0,7/18,2 ≈ 3,8%."),
 (9, "s", "Krańcowa skłonność do oszczędzania 0,25, krańcowa skłonność do importu 0,15 (bez podatków). Mnożnik w gospodarce otwartej wynosi:",
  ["2,5", "4", "6,67", "1,67"], "A",
  "k = 1 / (s + m) = 1 / (0,25 + 0,15) = 2,5."),
 (9, "s", "Nominalny PKB wynosi 3000 mld zł, a przeciętna ilość pieniądza w obiegu (M2) 1200 mld zł. Prędkość obiegu pieniądza wynosi:",
  ["2,5", "0,4", "3600", "1,25"], "A",
  "V = PY / M = 3000 / 1200 = 2,5 – każdy złoty obraca się średnio 2,5 razy w roku w transakcjach finalnych."),
 (9, "s", "Wskaźnik Lernera dla firmy wynosi 0,25, a koszt krańcowy 30 zł. Cena wynosi:",
  ["40 zł", "37,50 zł", "120 zł", "22,50 zł"], "A",
  "L = (P − MC)/P = 0,25 ⇒ P − 30 = 0,25P ⇒ 0,75P = 30 ⇒ P = 40 zł."),
 (9, "s", "Na rynku działa 5 firm o udziałach 30%, 25%, 20%, 15% i 10%. Wskaźnik koncentracji CR3 wynosi:",
  ["75%", "55%", "2250", "100%"], "A",
  "CR3 = 30 + 25 + 20 = 75%. HHI = 900 + 625 + 400 + 225 + 100 = 2250."),
 (9, "s", "Przy cenie 50 zł firma sprzedaje 2000 szt.; elastyczność cenowa popytu wynosi −2. Po obniżce ceny o 5% sprzedaż wzrośnie do około:",
  ["2200 szt.", "2100 szt.", "2010 szt.", "4000 szt."], "A",
  "%ΔQ = −2 · (−5%) = +10% ⇒ 2200 szt.; utarg wzrośnie z 100 000 do 104 500 zł."),
 (9, "s", "Kurs EUR/PLN = 4,30, a cena towaru w Niemczech 200 euro. Ten sam towar w Polsce kosztuje 946 zł. Realny kurs walutowy (q = E · P*/P) wynosi:",
  ["0,91", "1,10", "4,30", "1,00"], "A",
  "q = 4,30 · 200 / 946 = 860 / 946 ≈ 0,91 – towar w Niemczech jest po przeliczeniu tańszy niż w Polsce."),
 (9, "s", "Aktywa banku ważone ryzykiem 2 mld zł; minimalny łączny współczynnik kapitałowy 8% plus bufor 2,5%. Wymagane fundusze własne wynoszą:",
  ["210 mln zł", "160 mln zł", "50 mln zł", "2,1 mld zł"], "A",
  "(8% + 2,5%) · 2 mld = 10,5% · 2 mld = 210 mln zł."),
 (9, "s", "Zysk netto 1,2 mln zł, kapitał własny na początku roku 7 mln zł, na końcu 9 mln zł. ROE liczone od średniego kapitału wynosi:",
  ["15%", "13,3%", "17,1%", "12%"], "A",
  "Średni kapitał = 8 mln zł; ROE = 1,2/8 = 15%."),
 (9, "s", "Przychody 4 mln zł, należności średnio 500 tys. zł (rok = 360 dni). Wskaźnik rotacji należności w dniach wynosi:",
  ["45 dni", "8 dni", "40 dni", "80 dni"], "A",
  "500 000 · 360 / 4 000 000 = 45 dni (rotacja w razach = 8)."),
 (9, "s", "Udział kapitału własnego w pasywach wynosi 30%. Mnożnik kapitałowy (aktywa/kapitał własny) wynosi:",
  ["3,33", "0,30", "1,43", "2,33"], "A",
  "A/KW = 1 / 0,3 ≈ 3,33; wskaźnik zadłużenia ogólnego = 70%, przekładnia (KO/KW) ≈ 2,33."),
 (9, "s", "Firma osiąga ROS 5%, rotację aktywów 2 i mnożnik kapitałowy 2,5. ROE wynosi:",
  ["25%", "9,5%", "10%", "12,5%"], "A",
  "Model Du Ponta: ROE = 5% · 2 · 2,5 = 25%."),
 (9, "s", "Akcja kosztowała 80 zł, a po roku 72 zł; wypłacono dywidendę 4 zł. Stopa zwrotu wynosi:",
  ["−5%", "−10%", "+5%", "−15%"], "A",
  "(72 − 80 + 4) / 80 = −4/80 = −5%."),
 (9, "s", "Inwestor ulokował 50% w akcjach A (oczekiwany zwrot 12%) i 50% w obligacjach B (5%). Oczekiwana stopa zwrotu portfela wynosi:",
  ["8,5%", "17%", "6%", "12%"], "A",
  "Średnia ważona: 0,5 · 12% + 0,5 · 5% = 8,5% (ryzyko portfela nie jest średnią ważoną – zależy od korelacji)."),
 (9, "s", "Zysk 100 zł z prawdopodobieństwem 0,6 albo strata 50 zł z prawdopodobieństwem 0,4. Wartość oczekiwana inwestycji wynosi:",
  ["40 zł", "50 zł", "60 zł", "25 zł"], "A",
  "E = 0,6 · 100 + 0,4 · (−50) = 60 − 20 = 40 zł."),
 (9, "s", "Kraj: PKB 2500 mld zł, dług publiczny 1300 mld zł. Relacja długu do PKB wynosi:",
  ["52%", "48%", "192%", "1,92"], "A",
  "1300 / 2500 = 0,52 = 52% – poniżej konstytucyjnego limitu 60%, ale powyżej progu ostrożnościowego 43% i 48%."),
 (9, "s", "Deficyt budżetowy wynosi 150 mld zł przy PKB 3000 mld zł. Relacja deficytu do PKB wynosi:",
  ["5%", "2%", "15%", "20%"], "A",
  "150 / 3000 = 5% – powyżej kryterium z Maastricht (3%)."),
 (9, "s", "Dochód rozporządzalny 4000 zł, konsumpcja 3400 zł. Przeciętna skłonność do oszczędzania wynosi:",
  ["0,15", "0,85", "0,60", "1,18"], "A",
  "APS = S/Yd = 600/4000 = 0,15; APC = 0,85."),
 (9, "s", "Krajowe oszczędności wynoszą 22% PKB, a inwestycje 25% PKB. Z tożsamości makroekonomicznej wynika saldo rachunku bieżącego około:",
  ["deficyt 3% PKB", "nadwyżka 3% PKB", "nadwyżka 47% PKB", "zero"], "A",
  "S − I = saldo obrotów bieżących: 22% − 25% = −3% PKB – nadwyżkę inwestycji nad oszczędnościami finansuje kapitał zagraniczny."),
 (9, "s", "Przychód z kapitału na pracownika: y = k^0,5. Stopa oszczędności s = 0,2, amortyzacja δ = 0,05, brak wzrostu ludności i postępu. Kapitał na pracownika w stanie ustalonym wynosi:",
  ["16", "4", "8", "64"], "A",
  "s·y = δ·k ⇒ 0,2·√k = 0,05·k ⇒ √k = 4 ⇒ k = 16; produkcja na pracownika y = 4."),
 (9, "s", "Wartość dodana: firma kupiła półprodukty za 300 tys. zł i usługi za 50 tys. zł, sprzedała produkty za 800 tys. zł, wynagrodzenia wyniosły 250 tys. zł. Wartość dodana brutto wynosi:",
  ["450 tys. zł", "500 tys. zł", "200 tys. zł", "800 tys. zł"], "A",
  "WDB = produkcja − zużycie pośrednie = 800 − (300 + 50) = 450 tys. zł (wynagrodzenia są częścią wartości dodanej, nie zużycia pośredniego)."),
 (9, "s", "Wskaźnik pokrycia długu: zysk netto 300, amortyzacja 100, raty kredytu 250, odsetki 50. Wskaźnik pokrycia obsługi długu nadwyżką finansową wynosi:",
  ["1,33", "1,00", "1,60", "0,75"], "A",
  "(300 + 100) / (250 + 50) = 400/300 ≈ 1,33 – nadwyżka finansowa pokrywa obsługę długu z zapasem."),
 (9, "s", "Elastyczność dochodowa popytu na samochody wynosi 1,8. Dochody wzrosną o 5%. Popyt na samochody wzrośnie o:",
  ["9%", "5%", "1,8%", "3,6%"], "A",
  "%ΔQ = 1,8 · 5% = 9% – dobro luksusowe (Ey > 1)."),
 (9, "s", "Cena masła wzrosła o 10%, a popyt na margarynę wzrósł o 4%. Elastyczność mieszana popytu wynosi:",
  ["0,4", "−0,4", "2,5", "0,04"], "A",
  "Exy = 4%/10% = +0,4 – substytuty."),
 (9, "s", "Indeks Giniego obliczony z krzywej Lorenza: pole między krzywą Lorenza a linią równości wynosi 0,15, a całe pole pod linią równości 0,5. Współczynnik Giniego wynosi:",
  ["0,30", "0,15", "0,35", "0,70"], "A",
  "G = A / (A + B) = 0,15 / 0,5 = 0,30."),
 (9, "s", "Płaca minimalna wynosi 4806 zł, a przeciętne wynagrodzenie 8000 zł. Relacja płacy minimalnej do przeciętnej wynosi około:",
  ["60%", "40%", "50%", "166%"], "A",
  "4806 / 8000 ≈ 0,60. Relację płacy minimalnej do przeciętnej (lub mediany) wykorzystuje się w ocenie jej wpływu na rynek pracy."),
 (9, "s", "Kredyt 10 000 zł oprocentowany prosto 10% rocznie na pół roku. Odsetki wynoszą:",
  ["500 zł", "1000 zł", "250 zł", "488 zł"], "A",
  "Odsetki proste = K · r · t = 10 000 · 0,10 · 0,5 = 500 zł."),
 (9, "s", "Weksel o wartości nominalnej 20 000 zł płatny za 90 dni zdyskontowano w banku przy stopie dyskontowej 12% rocznie (rok = 360 dni). Bank wypłaci:",
  ["19 400 zł", "18 800 zł", "19 760 zł", "20 600 zł"], "A",
  "Dyskonto = 20 000 · 0,12 · 90/360 = 600 zł; wypłata = 19 400 zł."),
 (9, "s", "Amortyzacja środka trwałego wynosi 30 000 zł rocznie przy stawce liniowej 15%. Wartość początkowa wynosi:",
  ["200 000 zł", "45 000 zł", "450 000 zł", "20 000 zł"], "A",
  "30 000 / 0,15 = 200 000 zł; okres amortyzacji ok. 6,7 roku."),
 (9, "s", "Cena wzrosła z 20 do 25 zł, a ilość podaży z 100 do 140 szt. Elastyczność cenowa podaży (metoda prosta, względem stanu wyjściowego) wynosi:",
  ["1,6", "0,625", "4", "1,25"], "A",
  "Es = (40/100) / (5/20) = 0,40 / 0,25 = 1,6 – podaż elastyczna."),
 (9, "s", "Koszt zmienny produkcji 200 szt. wynosi 3000 zł, a 201 szt. – 3018 zł. Koszt krańcowy 201. sztuki wynosi:",
  ["18 zł", "15 zł", "15,01 zł", "3018 zł"], "A",
  "MC = ΔVC/ΔQ = 18 zł; AVC przy 200 szt. = 15 zł – MC > AVC, więc AVC zaczyna rosnąć."),
 (9, "s", "Stopa dyskontowa 5%, wieczysty strumień 2000 zł rocznie rosnący o 1% rocznie (pierwsza płatność za rok). Wartość obecna wynosi:",
  ["50 000 zł", "40 000 zł", "33 333 zł", "200 000 zł"], "A",
  "PV = C₁ / (r − g) = 2000 / (0,05 − 0,01) = 50 000 zł (renta wieczysta rosnąca)."),
 (9, "s", "Kurs akcji 60 zł, cena wykonania opcji put 70 zł, premia 6 zł. Zysk nabywcy opcji put w dniu wygaśnięcia wynosi:",
  ["4 zł", "10 zł", "−6 zł", "16 zł"], "A",
  "Wartość wewnętrzna put = 70 − 60 = 10 zł; zysk netto = 10 − 6 = 4 zł."),
 (9, "s", "Wskaźnik obciążenia demograficznego: 0–14 lat – 5,5 mln, 15–64 – 24,5 mln, 65+ – 7,5 mln. Na 100 osób w wieku produkcyjnym przypada osób w wieku nieprodukcyjnym około:",
  ["53", "31", "22", "65"], "A",
  "(5,5 + 7,5) / 24,5 · 100 ≈ 53,1; w tym obciążenie starszymi ≈ 30,6."),
 (9, "s", "Przedsiębiorca chce zarobić 50 000 zł zysku przy kosztach stałych 150 000 zł i stopie marży pokrycia 40%. Wymagane przychody wynoszą:",
  ["500 000 zł", "375 000 zł", "200 000 zł", "125 000 zł"], "A",
  "Przychody = (FC + zysk) / stopa marży = 200 000 / 0,4 = 500 000 zł."),
 (9, "s", "Wzrost realnego PKB wyniósł 3%, a liczba pracujących wzrosła o 1%. Wydajność pracy (PKB na pracującego) wzrosła o około:",
  ["2%", "3%", "4%", "1%"], "A",
  "1,03 / 1,01 ≈ 1,0198 – ok. 2%."),
 # --- wielokrotny wybór (głównie 1, 2 i 4 poprawne) ---
 (9, "m", "Które wzory są poprawne?",
  ["ROE = zysk netto / kapitał własny", "Wskaźnik bieżącej płynności = aktywa obrotowe / zobowiązania krótkoterminowe", "EPS = cena akcji / zysk netto", "P/E = zysk na akcję / cena akcji"], "AB",
  "EPS = zysk netto / liczba akcji; P/E = cena akcji / EPS."),
 (9, "m", "Które wyrażenia opisują mnożnik wydatków w gospodarce zamkniętej bez podatków?",
  ["1 / (1 − MPC)", "1 / MPS", "MPC / (1 − MPC)", "1 − MPC"], "AB",
  "1/(1 − MPC) = 1/MPS; MPC/(1 − MPC) to (co do wartości bezwzględnej) mnożnik podatkowy."),
 (9, "m", "Które równości wynikają wprost z tożsamości bilansowej?",
  ["Aktywa = kapitał własny + zobowiązania (i rezerwy)", "Aktywa trwałe + aktywa obrotowe = pasywa", "Zysk netto = przychody − aktywa", "Kapitał własny = zobowiązania krótkoterminowe"], "AB",
  "Suma aktywów zawsze równa się sumie pasywów; zysk to różnica przychodów i kosztów, nie aktywów."),
 (9, "m", "Który wzór opisuje realną stopę procentową według dokładnego równania Fishera?",
  ["r = (1 + i)/(1 + π) − 1", "r = i + π", "r = i · π", "r = (1 + π)/(1 + i) − 1"], "A",
  "Przybliżenie: r ≈ i − π."),
 (9, "m", "Które wzory dotyczą wartości pieniądza w czasie i są poprawne?",
  ["FV = PV · (1 + r)ⁿ", "PV = FV / (1 + r)ⁿ", "FV = PV · (1 + r · n) dla procentu prostego", "PV = FV · (1 + r)ⁿ"], "ABC",
  "PV oblicza się przez dyskontowanie (dzielenie przez (1 + r)ⁿ)."),
 (9, "m", "Który wzór opisuje elastyczność cenową popytu?",
  ["(ΔQ/Q) / (ΔP/P)", "(ΔP/P) / (ΔQ/Q)", "(ΔQ/Q) / (ΔY/Y)", "ΔQ − ΔP"], "A",
  "(ΔQ/Q)/(ΔY/Y) to elastyczność dochodowa."),
 (9, "m", "Które zależności dotyczące kosztów są prawdziwe?",
  ["TC = FC + VC", "ATC = AFC + AVC", "MC = ΔTC / ΔQ", "AFC = FC · Q"], "ABC",
  "AFC = FC / Q."),
 (9, "m", "Który wzór opisuje wskaźnik Lernera?",
  ["(P − MC) / P", "(P − ATC) / ATC", "MC / P", "P / MC − 1"], "A",
  "Wskaźnik Lernera mierzy siłę rynkową; w monopolu równa się 1/|Ed|."),
 (9, "m", "Które wzory na PKB i jego pochodne są poprawne?",
  ["PKB = C + I + G + (X − M)", "PNN = PNB − amortyzacja", "PNB = PKB + saldo dochodów pierwotnych z zagranicą", "Realny PKB = nominalny PKB · deflator"], "ABC",
  "Realny PKB = nominalny / deflator (×100)."),
 (9, "m", "Który wzór opisuje prawo Okuna (w wersji luki)?",
  ["(Y − Y*)/Y* = −β · (u − u*)", "Y = C + I + G", "MV = PY", "π = πᵉ − β(u − u*)"], "A",
  "MV = PY to równanie wymiany, ostatni wzór – krzywa Phillipsa z oczekiwaniami."),
 (9, "m", "Które wzory opisują dźwignię i są poprawne?",
  ["DOL = (S − VC) / EBIT", "DFL = EBIT / (EBIT − odsetki)", "DTL = DOL · DFL", "DTL = DOL + DFL"], "ABC",
  "Dźwignię całkowitą oblicza się jako iloczyn, nie sumę."),
 (9, "m", "Który wzór pozwala obliczyć ilościowy próg rentowności?",
  ["FC / (P − AVC)", "FC / P", "(FC + VC) / P", "P / (FC − AVC)"], "A",
  "Koszty stałe dzielone przez jednostkową marżę pokrycia."),
 (9, "m", "Które wskaźniki mierzą zadłużenie przedsiębiorstwa?",
  ["Zobowiązania ogółem / aktywa", "Kapitał obcy / kapitał własny", "Aktywa obrotowe / zobowiązania krótkoterminowe", "Zysk netto / przychody"], "AB",
  "Trzeci wzór to płynność bieżąca, czwarty – rentowność sprzedaży."),
 (9, "m", "Który wzór opisuje model Gordona?",
  ["P₀ = D₁ / (k − g)", "P₀ = D₀ · k", "P₀ = EPS · P/E · g", "P₀ = D₁ · (k − g)"], "A",
  "Wymaga k > g; D₁ to dywidenda oczekiwana za rok."),
 (9, "m", "Które wzory dotyczące rynku pracy są poprawne?",
  ["Stopa bezrobocia = bezrobotni / aktywni zawodowo", "Współczynnik aktywności = aktywni / ludność w wieku 15+", "Wskaźnik zatrudnienia = pracujący / ludność w danej grupie wieku", "Aktywni zawodowo = pracujący + bierni zawodowo"], "ABC",
  "Aktywni = pracujący + bezrobotni."),
 (9, "m", "Które wzory na stopy zwrotu i ryzyko są poprawne?",
  ["CAPM: E(R) = Rf + β(Rm − Rf)", "Stopa dywidendy = dywidenda / cena akcji", "Wskaźnik Sharpe’a = (Rp − Rf) / σp", "Beta = cena akcji / indeks WIG"], "ABC",
  "Beta to kowariancja stopy zwrotu akcji z rynkiem podzielona przez wariancję rynku."),
 (9, "m", "Które wzory demograficzne są poprawne?",
  ["Przyrost naturalny = urodzenia − zgony", "Saldo migracji = imigracja − emigracja", "Przyrost rzeczywisty = przyrost naturalny + saldo migracji", "Współczynnik dzietności = urodzenia / liczba ludności"], "ABC",
  "Urodzenia na 1000 ludności to współczynnik urodzeń; TFR sumuje cząstkowe współczynniki płodności."),
 (9, "m", "Który wzór opisuje wartość obecną renty wieczystej o stałej płatności?",
  ["PV = C / r", "PV = C · r", "PV = C / (1 + r)", "PV = C · n"], "A",
  "Np. 500 zł rocznie przy r = 5%: PV = 10 000 zł."),
 (9, "m", "Które z poniższych są poprawnymi wzorami wskaźników rotacji (w dniach, rok = 365)?",
  ["Zapasy · 365 / koszt sprzedaży (lub przychody)", "Należności · 365 / przychody", "Zobowiązania · 365 / koszt sprzedaży (lub zakupy)", "Przychody · 365 / zapasy"], "ABC",
  "Ostatni wzór daje wynik bez interpretacji – rotacja w razach to przychody / zapasy."),
 (9, "m", "Który wzór opisuje ekonomiczną wartość dodaną (EVA)?",
  ["NOPAT − WACC · zaangażowany kapitał", "Zysk netto − dywidenda", "Przychody − koszty zmienne", "EBITDA − odsetki"], "A",
  "NOPAT to zysk operacyjny po opodatkowaniu."),
 (9, "m", "Które wzory dotyczące budżetu państwa są poprawne?",
  ["Saldo budżetu = dochody − wydatki", "Saldo pierwotne = saldo budżetu + koszty obsługi długu", "Dług na koniec roku ≈ dług na początku roku + deficyt", "Deficyt = dług · inflacja"], "ABC",
  "Ostatnie wyrażenie nie ma sensu ekonomicznego."),
 (9, "m", "Który wzór opisuje efektywną roczną stopę procentową przy kapitalizacji m razy w roku?",
  ["(1 + r/m)^m − 1", "r · m", "(1 + r)^m − 1", "r / m"], "A",
  "Przy kapitalizacji ciągłej: e^r − 1."),
 (9, "m", "Które zależności dla konkurencji doskonałej są prawdziwe?",
  ["P = MR = AR", "Maksymalizacja zysku: P = MC", "Próg zamknięcia: P = min AVC", "P > MR"], "ABC",
  "P > MR dotyczy monopolu i innych firm o opadającym popycie."),
 (9, "m", "Które wyrażenie oznacza indeks Herfindahla–Hirschmana?",
  ["Suma kwadratów udziałów rynkowych firm (w %)", "Suma udziałów trzech największych firm", "Udział największej firmy", "Iloczyn udziałów wszystkich firm"], "A",
  "Suma udziałów trzech największych firm to CR3."),
 (9, "m", "Które wzory opisują produkt i są poprawne?",
  ["APL = Q / L", "MPL = ΔQ / ΔL", "Optymalna kombinacja czynników: MPL / w = MPK / r", "MPL = Q · L"], "ABC",
  "Ostatni wzór jest błędny."),
 (9, "m", "Który wzór pozwala obliczyć kurs terminowy według parytetu stóp procentowych?",
  ["F = S · (1 + i_kraj) / (1 + i_zagr)", "F = S · (i_kraj − i_zagr)", "F = S / (1 + i_kraj)", "F = S + i_kraj"], "A",
  "Waluta o wyższej stopie procentowej jest notowana z dyskontem terminowym."),
 (9, "m", "Które wzory dotyczące konsumpcji i oszczędności są poprawne?",
  ["MPC + MPS = 1", "APC = C / Yd", "S = Yd − C", "MPC = C / ΔYd"], "ABC",
  "MPC = ΔC / ΔYd."),
 (9, "m", "Które wyrażenie opisuje podatek należny w skali PIT (12%/32%) od dochodu D > 120 000 zł?",
  ["10 800 zł + 32% · (D − 120 000 zł)", "32% · D", "12% · D − 3600 zł", "19% · D"], "A",
  "10 800 zł = 12% · 120 000 − 3600 zł; nadwyżkę ponad próg opodatkowuje się stawką 32%."),
]
