# -*- coding: utf-8 -*-
# Działy 11–14 – instytucje, daty, przepisy, paradoksy (partia 2)
M = [
 # --- 11. Instytucje ---
 (11, "s", "Instytucją UE, która zatwierdza budżet Unii wspólnie z Radą UE i wybiera przewodniczącego Komisji Europejskiej, jest:",
  ["Parlament Europejski", "Trybunał Sprawiedliwości UE", "Europejski Bank Centralny", "Trybunał Obrachunkowy"], "A",
  "Parlament (wybierany co 5 lat w wyborach powszechnych) współdecyduje o prawie i budżecie oraz zatwierdza Komisję."),
 (11, "s", "Europejski Trybunał Obrachunkowy:",
  ["kontroluje finanse Unii Europejskiej", "rozstrzyga spory prawne", "ustala stopy procentowe", "wydaje zezwolenia na fuzje"], "A",
  "Siedziba w Luksemburgu; kontrolę legalności aktów prawnych sprawuje TSUE, a decyzje o koncentracjach podejmuje Komisja."),
 (11, "s", "Europejski Bank Inwestycyjny (EBI):",
  ["udziela długoterminowych kredytów na projekty wspierające cele UE", "emituje euro", "nadzoruje banki strefy euro", "zarządza rezerwami walutowymi państw"], "A",
  "EBI (Luksemburg, od 1958 r.) jest bankiem UE; finansuje m.in. infrastrukturę, energetykę, innowacje także w Polsce."),
 (11, "s", "Organizacja Współpracy Gospodarczej i Rozwoju (OECD) ma siedzibę w:",
  ["Paryżu", "Genewie", "Waszyngtonie", "Brukseli"], "A",
  "OECD (od 1961 r., wcześniej OEEC z planu Marshalla) zrzesza 38 państw; prowadzi m.in. badanie PISA i analizy polityki gospodarczej."),
 (11, "s", "Międzynarodowa Organizacja Pracy (MOP/ILO):",
  ["ustala międzynarodowe standardy pracy i definicję bezrobocia stosowaną w badaniach", "udziela kredytów państwom", "zarządza handlem", "nadzoruje banki"], "A",
  "MOP (od 1919 r., Genewa) – trójstronna agenda ONZ (rządy, pracodawcy, związki zawodowe)."),
 (11, "s", "Główny Urząd Statystyczny publikuje m.in.:",
  ["wskaźnik cen towarów i usług konsumpcyjnych (CPI) i dane o PKB", "decyzje o stopach procentowych", "bilans płatniczy Polski", "ratingi kredytowe państw"], "A",
  "Bilans płatniczy publikuje NBP, decyzje o stopach – RPP, a ratingi nadają agencje (S&P, Moody’s, Fitch)."),
 (11, "s", "Polski Fundusz Rozwoju (PFR) to:",
  ["grupa instytucji finansowych wspierających rozwój gospodarczy (m.in. tarcze finansowe w pandemii, PPK)", "bank centralny", "fundusz emerytalny ZUS", "organ nadzoru finansowego"], "A",
  "PFR m.in. zarządzał Tarczą Finansową dla firm (2020) i portalem PPK; Bank Gospodarstwa Krajowego jest państwowym bankiem rozwoju."),
 (11, "s", "Bank Gospodarstwa Krajowego (BGK) jest:",
  ["państwowym bankiem rozwoju obsługującym programy rządowe i fundusze pozabudżetowe", "bankiem centralnym", "bankiem spółdzielczym", "bankiem hipotecznym"], "A",
  "BGK (założony w 1924 r.) prowadzi m.in. Fundusz Przeciwdziałania COVID-19, Krajowy Fundusz Drogowy, programy mieszkaniowe."),
 (11, "s", "Krajowa Administracja Skarbowa (KAS) powstała w 2017 r. z połączenia:",
  ["administracji podatkowej, kontroli skarbowej i Służby Celnej", "NBP i KNF", "ZUS i KRUS", "NIK i RIO"], "A",
  "KAS odpowiada za pobór podatków i ceł oraz zwalczanie przestępczości skarbowej."),
 (11, "s", "Urząd Regulacji Energetyki (URE):",
  ["zatwierdza taryfy na energię elektryczną, gaz i ciepło oraz wydaje koncesje", "ustala ceny paliw na stacjach", "prowadzi politykę pieniężną", "nadzoruje giełdę"], "A",
  "URE to regulator rynku energii (monopole naturalne sieci przesyłowych i dystrybucyjnych)."),
 (11, "s", "Instytucją rozstrzygającą spory handlowe między członkami WTO jest:",
  ["Organ Rozstrzygania Sporów (DSB) WTO", "Międzynarodowy Trybunał Sprawiedliwości", "Rada Bezpieczeństwa ONZ", "MFW"], "A",
  "System rozstrzygania sporów WTO jest częściowo sparaliżowany od 2019 r. z powodu blokady wyboru członków Organu Apelacyjnego."),
 (11, "s", "Komisja Nadzoru Finansowego powstała w obecnym kształcie (z nadzorem bankowym) w:",
  ["2008 r.", "1989 r.", "1997 r.", "2015 r."], "A",
  "KNF powołano w 2006 r. (rynek kapitałowy, ubezpieczenia, emerytury), a od 1 stycznia 2008 r. przejęła nadzór bankowy od Komisji Nadzoru Bankowego przy NBP."),
 (11, "s", "Instytucją ustalającą stopy procentowe w strefie euro jest:",
  ["Rada Prezesów EBC", "Komisja Europejska", "Eurogrupa", "Parlament Europejski"], "A",
  "Rada Prezesów EBC (członkowie Zarządu EBC i prezesi banków centralnych strefy euro) podejmuje decyzje w polityce pieniężnej."),
 (11, "s", "Agencją UE nadzorującą rynki papierów wartościowych jest:",
  ["ESMA", "EBA", "EIOPA", "ESRB"], "A",
  "EBA – nadzór bankowy, EIOPA – ubezpieczenia i emerytury pracownicze, ESRB – ryzyko systemowe (nadzór makroostrożnościowy)."),
 (11, "s", "Klub Paryski to:",
  ["nieformalne zgromadzenie państw wierzycieli renegocjujących długi publiczne państw dłużników", "klub banków komercyjnych", "organizacja pracodawców", "grupa G7"], "A",
  "W 1991 r. Klub Paryski zredukował o 50% polski dług wobec wierzycieli publicznych; Klub Londyński skupia banki komercyjne (redukcja polskiego długu w 1994 r.)."),
 (11, "s", "G20 to forum:",
  ["największych gospodarek świata (19 państw, UE i Unia Afrykańska)", "20 najbogatszych osób", "20 banków centralnych strefy euro", "20 państw założycielskich ONZ"], "A",
  "Szczyty przywódców od 2008 r. (kryzys finansowy); wcześniej spotkania ministrów finansów i prezesów banków centralnych (od 1999 r.)."),
 # --- wielokrotny wybór (instytucje) ---
 (11, "m", "Które instytucje mają siedzibę w Genewie?",
  ["Światowa Organizacja Handlu", "Międzynarodowa Organizacja Pracy", "OECD", "Bank Światowy"], "AB",
  "OECD ma siedzibę w Paryżu, Bank Światowy w Waszyngtonie."),
 (11, "m", "Która instytucja w Polsce prowadzi rejestr podmiotów gospodarki narodowej REGON?",
  ["GUS", "Ministerstwo Rozwoju", "NBP", "KRS"], "A",
  "REGON prowadzi GUS; KRS – sądy rejestrowe, CEIDG – minister właściwy do spraw gospodarki."),
 (11, "m", "Które instytucje sprawują w Polsce nadzór nad rynkiem finansowym lub uczestniczą w jego stabilizacji?",
  ["KNF", "NBP", "BFG", "PFRON"], "ABC",
  "PFRON wspiera osoby z niepełnosprawnościami."),
 (11, "m", "Które z poniższych są organami doradczymi UE?",
  ["Europejski Komitet Ekonomiczno-Społeczny", "Europejski Komitet Regionów", "Komisja Europejska", "Rada Europejska"], "AB",
  "Komisja i Rada Europejska to instytucje UE, a nie organy doradcze."),
 (11, "m", "Która instytucja przyznaje Polsce linie kredytowe i ocenia jej gospodarkę w raportach z art. IV?",
  ["Międzynarodowy Fundusz Walutowy", "Bank Światowy", "EBOiR", "OPEC"], "A",
  "Konsultacje z art. IV Statutu MFW to coroczna ocena polityki gospodarczej członków."),
 (11, "m", "Które instytucje są zaangażowane w tworzenie i wdrażanie budżetu UE?",
  ["Komisja Europejska", "Parlament Europejski", "Rada UE", "Europejski Bank Centralny"], "ABC",
  "EBC nie uczestniczy w procedurze budżetowej UE."),
 (11, "m", "Które instytucje działają w polskim systemie ubezpieczeń społecznych?",
  ["ZUS", "KRUS", "UFG", "KNF"], "AB",
  "UFG dotyczy ubezpieczeń komunikacyjnych, KNF – nadzoru finansowego."),
 (11, "m", "Która instytucja nadzoruje przestrzeganie zasad konkurencji przez przedsiębiorstwa w całej UE?",
  ["Komisja Europejska", "Europejski Bank Centralny", "Parlament Europejski", "Europejski Trybunał Obrachunkowy"], "A",
  "Komisja (DG COMP) bada kartele, nadużycia pozycji dominującej, fuzje i pomoc publiczną."),
 (11, "m", "Które organizacje międzynarodowe powstały po II wojnie światowej w latach 1944–1947?",
  ["MFW", "Bank Światowy", "GATT", "WTO"], "ABC",
  "WTO powstała dopiero w 1995 r., zastępując GATT."),
 (11, "m", "Które instytucje są częścią Grupy Banku Światowego?",
  ["Międzynarodowy Bank Odbudowy i Rozwoju", "Międzynarodowe Stowarzyszenie Rozwoju (IDA)", "Międzynarodowa Korporacja Finansowa (IFC)", "Bank Rozrachunków Międzynarodowych"], "ABC",
  "BIS w Bazylei to „bank banków centralnych”, niezwiązany z Bankiem Światowym."),
 (11, "m", "Która instytucja zatwierdza prospekty emisyjne spółek wchodzących na GPW?",
  ["KNF", "GPW", "KDPW", "UOKiK"], "A",
  "GPW dopuszcza akcje do obrotu, KDPW rejestruje papiery, ale prospekt zatwierdza KNF."),
 # --- 12. Daty ---
 (12, "s", "Uporządkuj chronologicznie: (1) Wielki Kryzys, (2) konferencja w Bretton Woods, (3) pierwszy szok naftowy, (4) upadek Lehman Brothers.",
  ["1, 2, 3, 4", "2, 1, 3, 4", "1, 3, 2, 4", "1, 2, 4, 3"], "A",
  "1929–1933, 1944, 1973, 2008."),
 (12, "s", "W którym roku Polska przeszła na płynny kurs złotego?",
  ["2000", "1990", "1995", "2004"], "A",
  "12 kwietnia 2000 r. – po stopniowym poszerzaniu pasma pełzającej dewaluacji (1991–2000) zniesiono pasmo wahań."),
 (12, "s", "Wspólną Politykę Rolną EWG uruchomiono w:",
  ["1962 r.", "1957 r.", "1986 r.", "1993 r."], "A",
  "Traktaty rzymskie (1957) przewidziały WPR, uruchomioną w 1962 r."),
 (12, "s", "Jednolity Akt Europejski, zapowiadający utworzenie rynku wewnętrznego do końca 1992 r., podpisano w:",
  ["1986 r.", "1957 r.", "1992 r.", "2007 r."], "A",
  "Wszedł w życie w 1987 r.; rynek wewnętrzny funkcjonuje od 1 stycznia 1993 r."),
 (12, "s", "Czarna środa (wyjście funta z ERM pod presją spekulacji G. Sorosa) miała miejsce w:",
  ["1992 r.", "1987 r.", "1997 r.", "2008 r."], "A",
  "16 września 1992 r.; czarny poniedziałek na giełdzie nowojorskiej – 19 października 1987 r."),
 (12, "s", "Plan Marshalla (pomoc USA dla odbudowy Europy) ogłoszono w:",
  ["1947 r.", "1939 r.", "1952 r.", "1961 r."], "A",
  "Program obejmował lata 1948–1952; Polska pod presją ZSRR odmówiła udziału."),
 (12, "s", "Polska wprowadziła podatek VAT w:",
  ["1993 r.", "1989 r.", "1999 r.", "2004 r."], "A",
  "Ustawa z 1993 r. (stawki 22% i 7%), od 5 lipca 1993 r.; obecna ustawa o VAT obowiązuje od 1 maja 2004 r."),
 (12, "s", "Ustawę o działalności gospodarczej (tzw. ustawę Wilczka), liberalizującą prowadzenie firm, przyjęto w:",
  ["1988 r.", "1990 r.", "1980 r.", "2018 r."], "A",
  "Ustawa M. Wilczka z 23 grudnia 1988 r. (obowiązywała od 1989 r.): „co nie jest zabronione, jest dozwolone”."),
 (12, "s", "Pierwszy szok naftowy (embargo OPEC) miał miejsce w:",
  ["1973 r.", "1960 r.", "1979 r.", "1990 r."], "A",
  "Wojna Jom Kippur (1973) – czterokrotny wzrost cen ropy; drugi szok naftowy – 1979 r. (rewolucja w Iranie)."),
 (12, "s", "Denominacja złotego i wprowadzenie nowych banknotów nastąpiły w:",
  ["1995 r.", "1990 r.", "2000 r.", "1999 r."], "A",
  "1 stycznia 1995 r.: 10 000 starych złotych = 1 nowy złoty."),
 (12, "s", "Kryzys zadłużeniowy strefy euro rozpoczął się w:",
  ["2010 r. (Grecja)", "2002 r.", "2015 r.", "1999 r."], "A",
  "Pomoc dla Grecji (2010), Irlandii (2010), Portugalii (2011), Cypru (2013); kryzys osłabiła deklaracja M. Draghiego „whatever it takes” (2012)."),
 (12, "s", "Pandemia COVID-19 i największy od II wojny spadek światowego PKB przypadły na:",
  ["2020 r.", "2018 r.", "2009 r.", "2022 r."], "A",
  "PKB Polski spadł w 2020 r. o ok. 2% (jeden z najmniejszych spadków w UE); rząd wprowadził tarcze antykryzysowe."),
 (12, "s", "Do NATO Polska przystąpiła w:",
  ["1999 r.", "2004 r.", "1991 r.", "1996 r."], "A",
  "12 marca 1999 r. (razem z Czechami i Węgrami)."),
 (12, "s", "Reformę samorządową, która utworzyła powiaty i 16 województw, wprowadzono w:",
  ["1999 r.", "1990 r.", "1975 r.", "2004 r."], "A",
  "Gminy odtworzono w 1990 r.; od 1 stycznia 1999 r. działa trójstopniowy podział terytorialny."),
 (12, "s", "Twierdzenie Coase’a ogłoszono w artykule „The Problem of Social Cost” w:",
  ["1960 r.", "1937 r.", "1991 r.", "1920 r."], "A",
  "1937 – „The Nature of the Firm” (koszty transakcyjne); 1991 – Nagroda Nobla; 1920 – „Ekonomia dobrobytu” Pigou."),
 # --- wielokrotny wybór (daty) ---
 (12, "m", "Które wydarzenia miały miejsce w 1989 r.?",
  ["Obrady Okrągłego Stołu", "Upadek muru berlińskiego", "Wejście Polski do OECD", "Przyjęcie euro przez Słowację"], "AB",
  "OECD – 1996 r., euro na Słowacji – 2009 r."),
 (12, "m", "Które wydarzenie zapoczątkowało system płynnych kursów walutowych na świecie?",
  ["Upadek systemu z Bretton Woods (1971–1973)", "Konferencja w Bretton Woods (1944)", "Traktat z Maastricht (1992)", "Utworzenie EBC (1998)"], "A",
  "Bretton Woods ustanowił kursy stałe; Maastricht i EBC dotyczą unii walutowej w Europie."),
 (12, "m", "Które pary „rok – wydarzenie w Polsce” są poprawne?",
  ["1990 – plan Balcerowicza", "1991 – pierwsza sesja GPW", "1997 – Konstytucja RP", "2004 – wejście do UE"], "ABCD",
  "Wszystkie pary są poprawne."),
 (12, "m", "Które wydarzenia nastąpiły w XXI w.?",
  ["Wprowadzenie gotówki euro", "Upadek Lehman Brothers", "Czarny poniedziałek na Wall Street", "Konferencja w Bretton Woods"], "AB",
  "Czarny poniedziałek – 1987 r., Bretton Woods – 1944 r."),
 (12, "m", "Które kraje przystąpiły do UE 1 maja 2004 r. razem z Polską?",
  ["Czechy", "Litwa", "Rumunia", "Chorwacja"], "AB",
  "Rumunia (z Bułgarią) przystąpiła w 2007 r., Chorwacja w 2013 r."),
 (12, "m", "W którym roku podpisano traktat z Maastricht?",
  ["1992", "1986", "1999", "2007"], "A",
  "Traktat o Unii Europejskiej podpisano 7 lutego 1992 r. (w mocy od 1 listopada 1993 r.)."),
 (12, "m", "Które wydarzenia miały miejsce w 2022 r.?",
  ["Agresja Rosji na Ukrainę i kryzys energetyczny", "Podwyżki stóp procentowych przez NBP", "Wprowadzenie euro w Polsce", "Brexit (formalne wyjście z UE)"], "AB",
  "Polska nie wprowadziła euro; brexit nastąpił 31 stycznia 2020 r."),
 (12, "m", "Które z poniższych dat są związane z polskim systemem emerytalnym?",
  ["1999 – reforma emerytalna", "2014 – zmiany w OFE", "2017 – przywrócenie wieku 60/65 lat", "2019 – start PPK"], "ABCD",
  "Wszystkie daty są poprawne."),
 (12, "m", "Które z poniższych wydarzeń nastąpiły przed 1900 r.?",
  ["Wydanie „Bogactwa narodów”", "Rewolucja marginalistyczna", "Wielki Kryzys", "Utworzenie Fed"], "AB",
  "Wielki Kryzys – 1929 r., Fed – 1913 r."),
 (12, "m", "Który rok jest datą wprowadzenia euro w obrocie bezgotówkowym?",
  ["1999", "2002", "1992", "2004"], "A",
  "Gotówka euro weszła do obiegu 1 stycznia 2002 r."),
 (12, "m", "Które wydarzenia związane z NBP są poprawnie datowane?",
  ["1945 – utworzenie NBP", "1998 – pierwsze posiedzenia RPP", "2004 – stały cel inflacyjny 2,5%", "1960 – wprowadzenie euro"], "ABC",
  "Euro nigdy nie było walutą Polski."),
 # --- 13. Przepisy ---
 (13, "s", "Zgodnie z Konstytucją RP ustawę budżetową uchwala:",
  ["Sejm (z udziałem Senatu)", "Rada Ministrów", "Prezydent", "NBP"], "A",
  "Rada Ministrów przygotowuje projekt, Sejm uchwala ustawę, a Prezydent podpisuje ją w ciągu 7 dni (nie może jej zawetować)."),
 (13, "s", "Ustawa o finansach publicznych przewiduje, że przekroczenie relacji długu do PKB na poziomie 55%:",
  ["skutkuje m.in. obowiązkiem przedstawienia budżetu, w którym relacja długu Skarbu Państwa do PKB spada", "nie ma żadnych skutków", "oznacza automatyczne przyjęcie euro", "zakazuje wypłaty emerytur"], "A",
  "Progi ostrożnościowe 43%, 48% i 55% uruchamiają coraz ostrzejsze działania naprawcze."),
 (13, "s", "Minimalna wartość nominalna jednego udziału w spółce z o.o. wynosi według KSH:",
  ["50 zł", "1 zł", "100 zł", "5000 zł"], "A",
  "Kapitał zakładowy sp. z o.o. to co najmniej 5000 zł, a udział – co najmniej 50 zł; w spółce akcyjnej minimalna wartość nominalna akcji to 1 grosz."),
 (13, "s", "Ustawa o ochronie konkurencji i konsumentów zakazuje m.in.:",
  ["porozumień ograniczających konkurencję i nadużywania pozycji dominującej", "obniżania cen", "reklamy porównawczej zgodnej z prawem", "zakładania nowych firm"], "A",
  "Pozycja dominująca – co do zasady przy udziale w rynku powyżej 40%; sama dominacja nie jest zakazana, tylko jej nadużywanie."),
 (13, "s", "Prawo bankowe z 1997 r. definiuje bank jako:",
  ["osobę prawną działającą na podstawie zezwoleń, uprawnioną do wykonywania czynności bankowych obciążających ryzykiem środki powierzone pod jakimkolwiek tytułem zwrotnym", "każdą firmę udzielającą pożyczek", "instytucję wyłącznie państwową", "fundusz inwestycyjny"], "A",
  "Licencję bankową wydaje KNF; czynności bankowe to m.in. przyjmowanie depozytów i udzielanie kredytów."),
 (13, "s", "Zgodnie z Kodeksem pracy podstawowy wymiar urlopu wypoczynkowego pracownika ze stażem co najmniej 10 lat wynosi:",
  ["26 dni", "20 dni", "30 dni", "14 dni"], "A",
  "20 dni przy stażu poniżej 10 lat; do stażu wlicza się okres nauki (np. 8 lat za studia wyższe)."),
 (13, "s", "Norma czasu pracy w Polsce wynosi:",
  ["8 godzin na dobę i przeciętnie 40 godzin w przeciętnie pięciodniowym tygodniu pracy", "10 godzin na dobę", "48 godzin tygodniowo bez nadgodzin", "35 godzin tygodniowo"], "A",
  "Kodeks pracy, art. 129; dyrektywa UE ogranicza przeciętny tygodniowy czas pracy z nadgodzinami do 48 godzin."),
 (13, "s", "Umowa zlecenia różni się od umowy o pracę tym, że:",
  ["jest umową cywilnoprawną, bez podporządkowania i bez większości uprawnień pracowniczych (np. urlopu)", "zawsze daje prawo do urlopu", "jest regulowana Kodeksem pracy", "nie wymaga zapłaty"], "A",
  "Zleceniobiorcę obejmuje jednak minimalna stawka godzinowa i (co do zasady) obowiązkowe ubezpieczenia społeczne."),
 (13, "s", "Ustawa o PPK obowiązuje pracodawców, ale pracownik może zrezygnować z oszczędzania, składając:",
  ["deklarację rezygnacji, przy czym co 4 lata następuje ponowny autozapis", "wniosek do ZUS", "pozew do sądu", "oświadczenie w urzędzie skarbowym"], "A",
  "Konstrukcja opt-out (domyślne uczestnictwo) zwiększa udział w programie zgodnie z teorią szturchania."),
 (13, "s", "Dyrektywa UE wymaga przeniesienia do prawa krajowego w terminie, natomiast rozporządzenie UE:",
  ["obowiązuje bezpośrednio we wszystkich państwach członkowskich", "jest tylko zaleceniem", "dotyczy wyłącznie strefy euro", "wymaga referendum"], "A",
  "Przykład rozporządzenia: RODO; dyrektywy: np. o prawach konsumentów, o ochronie sygnalistów."),
 (13, "s", "RODO (ogólne rozporządzenie o ochronie danych osobowych) stosuje się od:",
  ["25 maja 2018 r.", "1 maja 2004 r.", "1 stycznia 2010 r.", "1 stycznia 2022 r."], "A",
  "Kary sięgają do 20 mln euro lub 4% światowego obrotu; w Polsce organem nadzorczym jest Prezes UODO."),
 # --- wielokrotny wybór (przepisy) ---
 (13, "m", "Które z poniższych zasad są zapisane w Konstytucji RP w odniesieniu do gospodarki?",
  ["Społeczna gospodarka rynkowa jako podstawa ustroju gospodarczego", "Ochrona własności i prawa dziedziczenia", "Obowiązek przyjęcia euro do 2030 r.", "Zakaz prowadzenia działalności gospodarczej przez osoby fizyczne"], "AB",
  "Konstytucja nie zawiera obowiązku przyjęcia euro (a art. 227 wskazuje NBP jako emitenta pieniądza), a wolność działalności gospodarczej gwarantuje art. 20 i 22."),
 (13, "m", "Który akt prawny reguluje spółki handlowe w Polsce?",
  ["Kodeks spółek handlowych", "Kodeks pracy", "Prawo bankowe", "Ordynacja podatkowa"], "A",
  "KSH z 15 września 2000 r. (w mocy od 2001 r.)."),
 (13, "m", "Które świadczenia przysługują pracownikowi na umowie o pracę z mocy Kodeksu pracy?",
  ["Płatny urlop wypoczynkowy", "Ochrona przed wypowiedzeniem w szczególnych sytuacjach (np. w ciąży)", "Wynagrodzenie co najmniej równe płacy minimalnej (pełny etat)", "Udział w zysku firmy"], "ABC",
  "Udział w zysku nie wynika z Kodeksu pracy (może wynikać z umowy lub regulaminu)."),
 (13, "m", "Które podatki są regulowane ustawą o podatkach i opłatach lokalnych?",
  ["Podatek od nieruchomości", "Podatek od środków transportowych", "Podatek VAT", "Podatek CIT"], "AB",
  "VAT i CIT mają własne ustawy (podatki państwowe)."),
 (13, "m", "Która ustawa wprowadziła tzw. Konstytucję biznesu?",
  ["Prawo przedsiębiorców z 2018 r.", "Ustawa Wilczka z 1988 r.", "Kodeks spółek handlowych z 2000 r.", "Ordynacja podatkowa z 1997 r."], "A",
  "Pakiet ustaw z 2018 r., w tym Prawo przedsiębiorców i ustawa o Rzeczniku MŚP."),
 (13, "m", "Które przepisy chronią konsumentów kupujących przez internet?",
  ["Prawo do odstąpienia od umowy w ciągu 14 dni", "Obowiązek informacyjny przedsiębiorcy przed zawarciem umowy", "Zakaz zwrotu towarów kupionych w promocji", "Odpowiedzialność sprzedawcy za brak zgodności towaru z umową"], "ABD",
  "Promocja nie wyłącza praw konsumenta."),
 (13, "m", "Które reguły fiskalne obowiązują w Polsce?",
  ["Konstytucyjny limit długu 60% PKB", "Stabilizująca reguła wydatkowa", "Reguła zakazująca jakiegokolwiek deficytu budżetu państwa", "Progi ostrożnościowe długu w ustawie o finansach publicznych"], "ABD",
  "Deficyt budżetu państwa jest dopuszczalny w granicach reguł."),
 (13, "m", "Kto w Polsce może zostać ukarany za stosowanie niedozwolonych klauzul w umowach z konsumentami?",
  ["Przedsiębiorca (decyzja Prezesa UOKiK)", "Konsument", "Rzecznik Finansowy", "Sąd"], "A",
  "Od 2016 r. o abuzywności klauzul orzeka w trybie administracyjnym Prezes UOKiK."),
 (13, "m", "Które podatki opłaca przedsiębiorca będący osobą fizyczną, w zależności od formy opodatkowania?",
  ["PIT według skali, liniowy, ryczałt od przychodów ewidencjonowanych lub karta podatkowa (dla kontynuujących)", "VAT, jeśli nie korzysta ze zwolnienia", "CIT 19%", "Podatek bankowy"], "AB",
  "CIT płacą osoby prawne (i niektóre spółki osobowe), a podatek bankowy – wybrane instytucje finansowe."),
 (13, "m", "Które informacje o karze za brak OC komunikacyjnego są prawdziwe?",
  ["Nakłada ją UFG", "Jej wysokość zależy od płacy minimalnej i czasu braku ubezpieczenia", "Nakłada ją NBP", "Brak OC jest dozwolony dla aut używanych rzadko"], "AB",
  "Obowiązek OC dotyczy każdego zarejestrowanego pojazdu mechanicznego."),
 # --- 14. Paradoksy ---
 (14, "s", "Paradoks Giffena polega na tym, że:",
  ["wzrost ceny dobra niższego rzędu może zwiększyć popyt na nie, gdy efekt dochodowy przeważa nad substytucyjnym", "wzrost dochodu zmniejsza oszczędności", "deprecjacja pogarsza bilans handlowy w krótkim okresie", "sprawniejsze silniki zwiększają zużycie paliwa"], "A",
  "Klasyczny przykład – ziemniaki w Irlandii w XIX w. (dyskusyjny empirycznie). Pozostałe opisy dotyczą innych zjawisk (krzywa J, paradoks Jevonsa)."),
 (14, "s", "Paradoks Leontiefa dotyczył tego, że:",
  ["eksport USA (kraju obfitego w kapitał) okazał się bardziej pracochłonny niż import", "kraje biedne eksportują kapitał", "płace realne spadały mimo wzrostu PKB", "Polska ma nadwyżkę w handlu z Niemcami"], "A",
  "Wynik (1953) podważał teorię Heckschera–Ohlina; wyjaśnienia: wysoki kapitał ludzki pracy w USA, bariery handlowe, różnice technologii."),
 (14, "s", "Paradoks urodzaju (paradoks rolniczy) oznacza, że:",
  ["dobre zbiory mogą obniżyć łączne dochody rolników przy nieelastycznym popycie", "susza zawsze zmniejsza dochody rolników", "dopłaty obniżają produkcję", "ceny żywności nie zależą od zbiorów"], "A",
  "Przy nieelastycznym popycie spadek ceny jest procentowo większy niż wzrost sprzedanej ilości."),
 (14, "s", "Paradoks Solowa (paradoks produktywności) z lat 80. dotyczył obserwacji, że:",
  ["komputery widać wszędzie, tylko nie w statystykach produktywności", "oszczędności obniżają dochód", "płace rosną szybciej niż produktywność", "inflacja spada przy niskim bezrobociu"], "A",
  "Efekty technologii informacyjnych pojawiły się w statystykach z opóźnieniem (przyspieszenie produktywności w USA w drugiej połowie lat 90.)."),
 (14, "s", "„Paradoks obfitości” (klątwa surowcowa) polega na tym, że:",
  ["kraje bogate w surowce często rozwijają się wolniej niż kraje ich pozbawione", "obfitość dóbr zawsze obniża ceny do zera", "kraje bogate eksportują pracę", "obfite zasoby wody podnoszą jej cenę"], "A",
  "Przyczyny: holenderska choroba, korupcja i pogoń za rentą, zmienność cen surowców, słabe instytucje."),
 (14, "s", "Błąd złożenia (fallacy of composition) to przekonanie, że:",
  ["to, co jest korzystne dla jednostki, musi być korzystne dla całej gospodarki", "korelacja oznacza przyczynowość", "przeszłość wyznacza przyszłość", "ceny zawsze rosną"], "A",
  "Przykłady: paradoks oszczędności, wstawanie na koncercie, by lepiej widzieć. Błąd post hoc to mylenie następstwa czasowego z przyczynowością."),
 (14, "s", "Paradoks Abilene w zarządzaniu oznacza, że:",
  ["grupa podejmuje decyzję, której w rzeczywistości nie chce żaden z jej członków, bo każdy zakłada, że chcą jej inni", "lider zawsze decyduje sam", "pracownicy wolą niższe płace", "decyzje grupowe są zawsze lepsze"], "A",
  "J. Harvey (1974) – pokrewne zjawisku myślenia grupowego; remedium to otwarte wyrażanie zastrzeżeń."),
 (14, "s", "Prawo Goodharta mówi, że:",
  ["wskaźnik, który staje się celem polityki, przestaje być dobrą miarą", "pieniądz gorszy wypiera lepszy", "podaż tworzy popyt", "praca zawsze rozszerza się na cały dostępny czas"], "A",
  "C. Goodhart (1975) – np. cele ilościowe agregatów pieniężnych tracą wartość informacyjną; ostatnia odpowiedź to prawo Parkinsona."),
 (14, "s", "Zasada Petera głosi, że:",
  ["w hierarchii każdy pracownik awansuje do poziomu swojej niekompetencji", "80% skutków wynika z 20% przyczyn", "praca rozszerza się, by wypełnić dostępny czas", "zawsze wybiera się rozwiązanie optymalne"], "A",
  "L. Peter (1969). 80/20 to zasada Pareto, rozszerzanie pracy – prawo Parkinsona."),
 (14, "s", "Tragedia wspólnego pastwiska jest paradoksem, ponieważ:",
  ["racjonalne zachowanie każdego użytkownika prowadzi do zniszczenia zasobu ze szkodą dla wszystkich", "dobra publiczne są zawsze nadmiernie produkowane", "rynek zawsze chroni zasoby", "państwo nie może regulować zasobów"], "A",
  "G. Hardin (1968); rozwiązania: prawa własności, regulacje, instytucje wspólnotowe (E. Ostrom)."),
 (14, "s", "Paradoks Simpsona w analizie danych ekonomicznych polega na tym, że:",
  ["zależność widoczna w każdej z grup może się odwrócić po połączeniu grup", "średnia zawsze równa się medianie", "korelacja dowodzi przyczynowości", "dane z próby są zawsze reprezentatywne"], "A",
  "Ważna przestroga przy porównaniach (np. średnie płace w grupach o różnej strukturze)."),
 (14, "s", "„Efekt kobry” to sytuacja, w której:",
  ["zachęta wprowadzona do rozwiązania problemu pogłębia go (np. nagroda za zabite kobry skłoniła do ich hodowli)", "pieniądz traci wartość", "drapieżny konkurent przejmuje rynek", "spada popyt na dobra luksusowe"], "A",
  "Przykład niezamierzonych skutków (perverse incentives) – argument za starannym projektowaniem bodźców w polityce."),
 (14, "s", "Paradoks Easterlina wskazuje, że w długim okresie:",
  ["wzrost dochodu na mieszkańca nie zwiększa trwale średniego poczucia szczęścia", "bogatsze kraje zawsze są szczęśliwsze", "szczęście zależy tylko od pogody", "inflacja zwiększa szczęście"], "A",
  "R. Easterlin (1974) – liczy się dochód względny i adaptacja do poprawy warunków; teza bywa kwestionowana (B. Stevenson, J. Wolfers)."),
 (14, "s", "Paradoks Bertranda w teorii oligopolu polega na tym, że:",
  ["już dwie firmy konkurujące ceną przy identycznych kosztach osiągają wynik jak w konkurencji doskonałej (P = MC)", "oligopol zawsze tworzy kartel", "monopol obniża ceny", "dwie firmy zawsze dzielą rynek po połowie przy cenie monopolowej"], "A",
  "W praktyce wynik łagodzą ograniczenia mocy, zróżnicowanie produktów i powtarzalność gry."),
 # --- wielokrotny wybór (paradoksy) ---
 (14, "m", "Które paradoksy dotyczą zachowania konsumentów lub popytu?",
  ["Paradoks Giffena", "Paradoks wody i diamentu", "Paradoks Leontiefa", "Paradoks Solowa"], "AB",
  "Paradoks Leontiefa dotyczy handlu, Solowa – produktywności."),
 (14, "m", "Który paradoks opisuje sytuację, w której wzrost oszczędności wszystkich gospodarstw prowadzi do spadku dochodu narodowego?",
  ["Paradoks zapobiegliwości (oszczędności)", "Paradoks Jevonsa", "Paradoks Easterlina", "Paradoks Simpsona"], "A",
  "Keynesowski paradoks oszczędności jest przykładem błędu złożenia."),
 (14, "m", "Które zjawiska są przykładami niezamierzonych skutków polityki lub bodźców?",
  ["Efekt kobry", "Prawo Goodharta", "Optimum Pareto", "Prawo popytu"], "AB",
  "Optimum Pareto i prawo popytu to pojęcia opisowe, nie paradoksy bodźców."),
 (14, "m", "Które paradoksy lub prawa dotyczą organizacji i zarządzania?",
  ["Zasada Petera", "Prawo Parkinsona", "Paradoks Abilene", "Paradoks Leontiefa"], "ABC",
  "Paradoks Leontiefa dotyczy handlu międzynarodowego."),
 (14, "m", "Który paradoks został podany jako argument przeciw teorii Heckschera–Ohlina?",
  ["Paradoks Leontiefa", "Paradoks Giffena", "Paradoks Bertranda", "Paradoks Abilene"], "A",
  "Leontief badał strukturę handlu USA (1953)."),
 (14, "m", "Które zjawiska związane z surowcami są poprawnie opisane?",
  ["Holenderska choroba – aprecjacja waluty szkodzi przemysłowi po boomie surowcowym", "Klątwa surowcowa – kraje bogate w surowce często mają słabsze instytucje i wolniejszy wzrost", "Paradoks Jevonsa – wyższa efektywność zawsze zmniejsza zużycie surowca", "Paradoks urodzaju – lepsze zbiory zawsze podnoszą dochody rolników"], "AB",
  "Paradoks Jevonsa mówi o możliwym wzroście zużycia, a paradoks urodzaju – o spadku dochodów rolników."),
 (14, "m", "Które z poniższych są przykładami błędu złożenia?",
  ["Jeśli jeden widz wstanie na koncercie, widzi lepiej – więc gdy wstaną wszyscy, wszyscy będą widzieć lepiej", "Jeśli jedna firma obniży płace, zwiększy zysk – więc gdy zrobią to wszystkie, zyski wszystkich wzrosną", "Wzrost ceny dobra zmniejsza wielkość popytu na nie", "Wyższa stopa procentowa zmniejsza inwestycje"], "AB",
  "Dwa ostatnie zdania to typowe zależności ekonomiczne, a nie błędy logiczne."),
]
