# -*- coding: utf-8 -*-
# Pytania uzupełniające (różne działy) – domknięcie partii 1000 pytań
M = [
 (1, "s", "Krzywa Engla przedstawia zależność między:",
  ["dochodem konsumenta a ilością nabywanego dobra", "ceną a wielkością popytu", "kosztem a produkcją", "stopą procentową a inwestycjami"], "A",
  "Dla dóbr normalnych krzywa Engla rośnie, dla dóbr niższego rzędu – od pewnego dochodu opada. Prawo Engla: udział wydatków na żywność maleje wraz ze wzrostem dochodu."),
 (1, "s", "Udział wydatków na żywność w budżetach gospodarstw domowych maleje wraz ze wzrostem dochodów. Ta prawidłowość to:",
  ["prawo Engla", "prawo Saya", "prawo Okuna", "prawo Greshama"], "A",
  "E. Engel (1857) – udział żywności jako miara zamożności; stosowane w badaniach budżetów gospodarstw domowych GUS."),
 (1, "s", "Przy cenie 0 zł wielkość popytu na usługę wynosi 100, a przy cenie 50 zł – 0 (liniowo). Przy jakiej cenie utarg jest maksymalny?",
  ["25 zł", "50 zł", "10 zł", "0 zł"], "A",
  "P = 50 − Q/2, TR = 50Q − Q²/2, MR = 50 − Q = 0 ⇒ Q = 50, P = 25 zł (tam |Ed| = 1)."),
 (1, "s", "Gdy firma w konkurencji doskonałej zwiększa produkcję w krótkim okresie, jej koszt krańcowy zwykle rośnie z powodu:",
  ["prawa malejących przychodów z czynnika zmiennego", "korzyści skali", "spadku cen czynników", "efektu sieciowego"], "A",
  "Przy stałym kapitale każdy kolejny pracownik dodaje coraz mniej produkcji – koszt wytworzenia dodatkowej jednostki rośnie."),
 (2, "s", "Inwestycje autonomiczne wzrosły o 10 mld zł, a dochód narodowy wzrósł o 25 mld zł. Mnożnik inwestycyjny wynosi:",
  ["2,5", "0,4", "15", "35"], "A",
  "k = ΔY / ΔI = 25/10 = 2,5, co odpowiada (w gospodarce zamkniętej bez podatków) krańcowej skłonności do konsumpcji 0,6."),
 (2, "s", "Wzrost cen ropy naftowej przy niezmienionej polityce pieniężnej w krótkim okresie (model AD–AS) powoduje:",
  ["wzrost cen i spadek produkcji (stagflację)", "spadek cen i wzrost produkcji", "wzrost cen i produkcji", "brak zmian"], "A",
  "Negatywny szok podażowy przesuwa krótkookresową AS w lewo – dylemat banku centralnego: walczyć z inflacją czy wspierać produkcję."),
 (2, "s", "Bezrobocie ukryte w rolnictwie oznacza, że:",
  ["część osób formalnie pracujących nie zwiększa produkcji (krańcowy produkt bliski zeru)", "rolnicy są zarejestrowani jako bezrobotni", "praca w rolnictwie jest nielegalna", "rolnicy pracują w szarej strefie w miastach"], "A",
  "Zjawisko typowe dla rozdrobnionego rolnictwa (np. w Polsce w latach 90.); w modelu Lewisa to rezerwa siły roboczej dla przemysłu."),
 (2, "s", "Która zmiana zmniejszy deficyt strukturalny?",
  ["trwała podwyżka podatków lub cięcie wydatków", "wzrost wpływów podatkowych w czasie boomu koniunktury", "spadek wydatków na zasiłki przy spadku bezrobocia", "jednorazowa sprzedaż majątku"], "A",
  "Zmiany wynikające z cyklu (boom, mniej zasiłków) zmniejszają deficyt cykliczny; operacje jednorazowe nie zmieniają salda strukturalnego."),
 (3, "s", "Bank ma depozyty 1000 mln zł i trzyma rezerwy 80 mln zł przy stopie rezerwy obowiązkowej 3,5%. Rezerwy nadobowiązkowe wynoszą:",
  ["45 mln zł", "35 mln zł", "80 mln zł", "920 mln zł"], "A",
  "Rezerwa wymagana = 3,5% · 1000 = 35 mln zł; nadwyżka = 80 − 35 = 45 mln zł – może posłużyć do udzielenia kredytów."),
 (3, "s", "Kredyt hipoteczny ze zmiennym oprocentowaniem WIBOR 3M + 2 pkt proc. Po wzroście WIBOR z 1% do 6% oprocentowanie kredytu wzrośnie:",
  ["z 3% do 8%", "z 2% do 6%", "z 1% do 6%", "nie zmieni się"], "A",
  "Marża banku jest stała, zmienia się stawka referencyjna – raty w latach 2021–2022 wzrosły w Polsce nawet o kilkadziesiąt procent, stąd wakacje kredytowe."),
 (3, "s", "Wakacje kredytowe wprowadzone w Polsce w 2022 r. polegały na:",
  ["możliwości zawieszenia spłaty rat kredytu hipotecznego w złotych na określoną liczbę miesięcy", "umorzeniu kredytów frankowych", "obniżeniu stopy referencyjnej", "zakazie udzielania kredytów"], "A",
  "Pomoc dla kredytobiorców po gwałtownych podwyżkach stóp; koszt ponosiły banki."),
 (4, "s", "Spółka wypłaciła 3 zł dywidendy przy zysku na akcję 5 zł. Wskaźnik wypłaty dywidendy wynosi:",
  ["60%", "40%", "167%", "15%"], "A",
  "Payout ratio = DPS / EPS = 3/5 = 60%; pozostałe 40% zysku zatrzymano w spółce."),
 (4, "s", "Fundusz inwestycyjny pobiera opłatę za zarządzanie 2% rocznie. Przy stopie zwrotu z aktywów 6% inwestor otrzyma (w przybliżeniu):",
  ["4%", "6%", "8%", "2%"], "A",
  "Koszty zarządzania obniżają wynik inwestora – w długim okresie różnica kilku punktów procentowych znacząco zmniejsza końcowy kapitał (efekt procentu składanego)."),
 (5, "s", "Przedsiębiorca rozlicza się ryczałtem od przychodów ewidencjonowanych. Podstawą opodatkowania jest:",
  ["przychód (bez odliczania kosztów)", "dochód (przychód minus koszty)", "majątek firmy", "wartość dodana"], "A",
  "Stawka zależy od rodzaju działalności (np. 3%, 8,5%, 12%, 15%); ryczałt opłaca się przy niskich kosztach."),
 (5, "s", "Ulga dla młodych w PIT zwalnia z podatku przychody osób do 26. roku życia do limitu:",
  ["85 528 zł rocznie", "30 000 zł", "120 000 zł", "1 mln zł"], "A",
  "Limit odpowiada progowi z dawnej skali podatkowej; dotyczy przychodów m.in. z umowy o pracę i umowy zlecenia."),
 (5, "s", "Podatek od towarów i usług w UE jest częściowo zharmonizowany: minimalna stawka podstawowa wynosi:",
  ["15%", "5%", "23%", "25%"], "A",
  "Dyrektywa VAT wymaga stawki podstawowej co najmniej 15%; najwyższą stawkę podstawową w UE ma Węgry (27%)."),
 (6, "s", "Eksport netto Polski do Niemiec przy osłabieniu złotego wobec euro (ceteris paribus) zwykle:",
  ["rośnie", "spada", "nie zmienia się", "spada do zera"], "A",
  "Słabszy złoty obniża ceny polskich towarów w euro i podraża import; działa to z opóźnieniem (krzywa J)."),
 (6, "s", "Głównym celem Wspólnej Polityki Handlowej UE w negocjacjach z państwami trzecimi jest:",
  ["obniżanie barier handlowych na zasadzie wzajemności przy ochronie standardów UE", "zakaz importu spoza UE", "ustalanie kursów walut", "harmonizacja podatków dochodowych"], "A",
  "Przykłady umów UE: CETA (Kanada), z Japonią (2019), z Wietnamem, z Mercosurem (negocjowana od 1999 r.)."),
 (7, "s", "Wartość bilansowa zapasów (FIFO): na początku 100 szt. po 10 zł, zakup 100 szt. po 12 zł, sprzedaż 150 szt. Koszt sprzedanych towarów wynosi:",
  ["1600 zł", "1700 zł", "1650 zł", "1800 zł"], "A",
  "FIFO: 100 · 10 + 50 · 12 = 1600 zł; zapas końcowy 50 · 12 = 600 zł (przy LIFO koszt wyniósłby 100 · 12 + 50 · 10 = 1700 zł)."),
 (7, "s", "Kredyt kupiecki z perspektywy odbiorcy to:",
  ["odroczony termin zapłaty za otrzymany towar", "kredyt bankowy na zakup towaru", "zaliczka wpłacona dostawcy", "leasing maszyn"], "A",
  "Dla dostawcy oznacza należności, a dla odbiorcy – zobowiązania z tytułu dostaw i usług."),
 (7, "s", "Zgodnie z KSH wspólnicy spółki z o.o. odpowiadają za jej zobowiązania:",
  ["co do zasady nie odpowiadają osobiście (ryzykują tylko wniesione wkłady), ale członkowie zarządu mogą odpowiadać przy bezskutecznej egzekucji", "całym majątkiem", "do wysokości sumy komandytowej", "zawsze solidarnie z zarządem"], "A",
  "Art. 299 KSH: członkowie zarządu odpowiadają solidarnie, jeśli egzekucja wobec spółki okaże się bezskuteczna (chyba że wykażą, że w porę zgłosili wniosek o upadłość)."),
 (8, "s", "Model AIDA w komunikacji marketingowej opisuje kolejne etapy:",
  ["uwaga – zainteresowanie – pożądanie – działanie", "analiza – implementacja – decyzja – akcja", "atak – izolacja – dominacja – akwizycja", "audyt – inwestycja – dystrybucja – audyt"], "A",
  "Attention, Interest, Desire, Action – model działania przekazu reklamowego."),
 (8, "s", "Stosowanie podobnych standardów marki na całym świecie przy dostosowaniu wybranych elementów do lokalnych rynków to strategia:",
  ["glokalizacji („myśl globalnie, działaj lokalnie”)", "dumpingu", "monopolizacji", "penetracji cenowej"], "A",
  "Przykład: sieci fast food oferujące lokalne pozycje menu przy globalnej marce."),
 (8, "s", "Delegowanie uprawnień jest utrudnione, gdy kierownik:",
  ["nie ufa podwładnym i obawia się utraty kontroli", "ma wielu kompetentnych podwładnych", "ma jasno określone cele", "pracuje w strukturze zdecentralizowanej"], "A",
  "Bariery delegowania: brak zaufania, perfekcjonizm, obawa przed konkurencją podwładnych, brak systemu kontroli."),
 (9, "s", "Kapitał 20 000 zł ulokowano na 2 lata na 5% z kapitalizacją roczną, a podatek Belki pobiera się od odsetek na koniec każdego roku. Kapitał po 2 latach wyniesie około:",
  ["21 653 zł", "22 050 zł", "21 620 zł", "22 000 zł"], "A",
  "Stopa netto po podatku 19%: 5% · 0,81 = 4,05%; 20 000 · 1,0405² = 20 000 · 1,08264 ≈ 21 652,80 zł (bez podatku byłoby 22 050 zł)."),
 (9, "s", "Podatek akcyzowy wynosi 10 zł na sztukę. Przed podatkiem cena wynosiła 50 zł, a po nałożeniu podatku – 56 zł. Jaką część podatku ponoszą konsumenci?",
  ["60%", "40%", "100%", "56%"], "A",
  "Cena dla nabywców wzrosła o 6 zł z 10 zł podatku – konsumenci ponoszą 60%, producenci (otrzymujący 46 zł) – 40%."),
 (10, "s", "Autorem teorii wartości opartej na pracy i krytyki kapitalizmu w dziele „Kapitał” był:",
  ["Karol Marks", "David Ricardo", "Adam Smith", "John Stuart Mill"], "A",
  "Marks rozwinął pojęcie wartości dodatkowej i wyzysku; teorię wartości opartej na pracy wcześniej formułowali Smith i Ricardo."),
 (12, "s", "Wielki Kryzys rozpoczął się krachem na giełdzie nowojorskiej w:",
  ["październiku 1929 r.", "marcu 1933 r.", "wrześniu 1939 r.", "sierpniu 1971 r."], "A",
  "„Czarny czwartek” (24 października) i „czarny wtorek” (29 października 1929 r.); reakcją w USA był New Deal F.D. Roosevelta (od 1933 r.)."),
 (13, "s", "Przedsiębiorca rozpoczynający działalność może przez pierwsze 6 miesięcy korzystać z:",
  ["„ulgi na start” – zwolnienia ze składek na ubezpieczenia społeczne (płaci składkę zdrowotną)", "zwolnienia z wszystkich podatków na 5 lat", "dotacji z NBP", "zwolnienia z VAT bez względu na obroty"], "A",
  "Po uldze na start może przez 24 miesiące płacić preferencyjne (niższe) składki ZUS."),
 (15, "s", "Jeśli liczba osób w wieku produkcyjnym spada o 1% rocznie, a wydajność pracy rośnie o 3% rocznie (przy stałym wskaźniku zatrudnienia), PKB rośnie o około:",
  ["2% rocznie", "4% rocznie", "3% rocznie", "−1% rocznie"], "A",
  "Wzrost PKB ≈ wzrost zatrudnienia + wzrost wydajności = −1% + 3% = 2% – demografia obniża potencjalne tempo wzrostu."),
 # --- wielokrotny wybór ---
 (1, "m", "Które z poniższych dóbr mają zwykle popyt nieelastyczny cenowo?",
  ["Sól kuchenna", "Insulina", "Konkretna marka napoju gazowanego", "Bilety lotnicze na wakacje"], "AB",
  "Konkretna marka ma wiele substytutów, a podróże wakacyjne są dobrem odkładalnym – popyt na nie jest elastyczny."),
 (2, "m", "Która miara najlepiej pokazuje wpływ polityki fiskalnej na koniunkturę niezależnie od cyklu?",
  ["Zmiana salda strukturalnego (impuls fiskalny)", "Saldo faktyczne budżetu", "Stopa inflacji", "Kurs walutowy"], "A",
  "Saldo faktyczne zmienia się też automatycznie z cyklem."),
 (3, "m", "Które działania mogą ograniczyć ryzyko kredytobiorcy związane ze wzrostem stóp procentowych?",
  ["Kredyt o okresowo stałej stopie procentowej", "Nadpłata kapitału kredytu", "Wydłużenie okresu kredytowania przy zmiennej stopie bez zmian w budżecie", "Zaciągnięcie dodatkowego kredytu na spłatę rat"], "AB",
  "Wydłużenie okresu obniża ratę, ale zwiększa łączny koszt i nie zmienia wrażliwości na stopy; kredyt na spłatę rat zwiększa zadłużenie."),
 (5, "m", "Które z poniższych są formami opodatkowania działalności gospodarczej osoby fizycznej w Polsce?",
  ["Skala podatkowa", "Podatek liniowy", "Ryczałt od przychodów ewidencjonowanych", "Podatek tonażowy"], "ABC",
  "Podatek tonażowy dotyczy armatorów (żegluga morska)."),
 (7, "m", "Który dokument przedstawia sytuację majątkową firmy na określony dzień?",
  ["Bilans", "Rachunek zysków i strat", "Rachunek przepływów pieniężnych", "Biznesplan"], "A",
  "RZiS i rachunek przepływów pokazują wielkości za okres (strumienie)."),
 (8, "m", "Które czynniki sprzyjają skutecznej pracy zespołowej?",
  ["Jasno określony cel", "Komplementarne umiejętności członków", "Brak zaufania między członkami", "Brak podziału ról"], "AB",
  "Brak zaufania i niejasne role obniżają skuteczność zespołu."),
 (15, "m", "Które dane o ludności świata są prawdziwe?",
  ["Ludność świata przekroczyła 8 mld w 2022 r.", "Najludniejszym krajem są Indie", "Ludność Europy rośnie najszybciej spośród kontynentów", "Ludność Japonii rośnie"], "AB",
  "Najszybciej rośnie ludność Afryki; ludność Japonii i Europy maleje lub stagnuje."),
]
