# -*- coding: utf-8 -*-
# Zrozumienie – Demografia / Polityka ludnościowa i rodzinna
D = "2026-10-08"
GOVAR = S("gov.pl – Aktywny Rodzic", "https://www.gov.pl/web/rodzina/aktywny-rodzic", D)
GOV800 = S("gov.pl – Świadczenie wychowawcze (800 plus)", "https://www.gov.pl/web/rodzina/swiadczenie-wychowawcze", D)
ZUS800 = S("ZUS – Świadczenie wychowawcze 800 plus", "https://www.zus.pl/swiadczenia/swiadczenia-dla-rodzin/swiadczenie-wychowawcze-800-plus", D)
INFDZ = S("infor.pl – Pieniądze na dziecko w 2026 r. (lista świadczeń)", "https://www.infor.pl/twoje-pieniadze/swiadczenia/7527629,pieniadze-na-dziecko-w-2026-roku-kompletna-lista-swiadczen-800-plus-aktywny-rodzic-i-dobry-start-zobacz-o-jakie-dodatki-mozesz-wnioskowac.html", D)
PITAX = S("pitax.pl – Ulga prorodzinna (kwoty i limity)", "https://www.pitax.pl/wiedza/mniejsze-podatki/ulga-prorodzinna/", D)
PPURL = S("poradnikprzedsiebiorcy.pl – Nieprzenoszalność urlopu rodzicielskiego", "https://poradnikprzedsiebiorcy.pl/-nieprzenoszalnosc-urlopu-rodzicielskiego-na-czym-polega", D)
OWIDF = S("Our World in Data – Fertility Rate", "https://ourworldindata.org/fertility-rate", D)
GUSPWL = S("GUS – Polska w liczbach 2026 (dane za 2025 r.)", "https://plwliczbach.stat.gov.pl/pl/assets/pdf/polska-w-liczbach-2026.pdf", D)
EUFERT = S("Eurostat Statistics Explained – Fertility statistics", "https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Fertility_statistics", D)

LESSONS = [
    L(1, "Polityka ludnościowa: cele i rodzaje",
      "Rozumieć, czym jest polityka ludnościowa, odróżniać politykę pronatalistyczną i antynatalistyczną, migracyjną i rodzinną oraz oceniać przykłady z różnych krajów.",
      ["Polityka ludnościowa (demograficzna)"],
      [OWIDF, EUFERT],
      explain=[
          K("Definicja i cele",
            "Polityka ludnościowa to świadome działania państwa wpływające na liczebność, strukturę i rozmieszczenie ludności – przez płodność, umieralność (zdrowie) i migracje. Polityka rodzinna jest jej częścią, ale ma też cele społeczne (dobrostan dzieci, godzenie pracy i rodziny, ograniczanie ubóstwa), niezależnie od liczby urodzeń."),
          K("Pronatalistyczna i antynatalistyczna",
            "Pronatalistyczna – zachęca do posiadania dzieci (transfery, ulgi, usługi opiekuńcze, mieszkania) – typowa dziś w Europie i Azji Wschodniej. Antynatalistyczna – ogranicza urodzenia: najbardziej znany przykład to polityka jednego dziecka w Chinach (od 1980 r.), złagodzona do dwójki dzieci (2016) i trojga (2021). Skutki chińskiej polityki: szybkie starzenie się i zaburzona proporcja płci urodzeń."),
          W("Rząd zmniejsza zachęty do posiadania wielu dzieci i promuje antykoncepcję w kraju o TFR 5. Jaka to polityka?",
            "Antynatalistyczna", "Pronatalistyczna", "Senioralna",
            why="Celem jest ograniczenie liczby urodzeń."),
          K("Instrumenty",
            "Bezpośrednie: transfery pieniężne (zasiłki, bony), ulgi podatkowe, urlopy rodzicielskie, usługi (żłobki, przedszkola), polityka mieszkaniowa. Pośrednie: rynek pracy (elastyczna praca, równość płac), system edukacji i zdrowia, polityka migracyjna. Instrumenty różnią się kosztem i skutecznością."),
          K("Granice skuteczności",
            "Doświadczenia krajów (Francja, kraje nordyckie, Węgry, Korea Południowa) pokazują, że polityka może podnieść dzietność, ale zwykle umiarkowanie – nie przywraca poziomu zastępowalności. Trwalsze efekty dają rozwiązania ułatwiające łączenie pracy i rodzicielstwa oraz stabilność warunków życia niż jednorazowe transfery. Część efektu to zmiana kalendarza urodzeń (wcześniej, a nie więcej)."),
          PF("Polityka jednego dziecka w Chinach obowiązowała od 1980 do 2015 r.", True,
             why="Od 2016 r. dopuszczono dwoje dzieci, a od 2021 r. troje."),
      ],
      mech=[
          KT("Pronatalistyczna czy antynatalistyczna?",
             {"Pronatalistyczna": ["Świadczenie pieniężne na każde dziecko", "Bezpłatne żłobki", "Ulgi mieszkaniowe dla rodzin z dziećmi"],
              "Antynatalistyczna": ["Kary finansowe za drugie dziecko", "Kampanie promujące małe rodziny w kraju o wysokiej dzietności"]},
             why="Cel: zwiększyć lub zmniejszyć liczbę urodzeń."),
          LN("Ułóż skutki długotrwałej polityki jednego dziecka.",
             ["Gwałtowny spadek urodzeń", "Mniej liczne kolejne roczniki", "Szybkie starzenie się społeczeństwa", "Kurczenie się siły roboczej", "Złagodzenie polityki (dwoje, potem troje dzieci)"],
             why="Polityka antynatalistyczna ma długie skutki uboczne."),
          W("Dlaczego część wzrostu urodzeń po wprowadzeniu zasiłku może być przejściowa?",
            "Rodziny przyspieszają planowane urodzenia (efekt kalendarza)", "Bo zasiłek zawsze się kończy po roku", "Bo spada umieralność",
            why="Wcześniej, ale niekoniecznie więcej dzieci."),
          W("Który instrument najbardziej bezpośrednio ułatwia łączenie pracy i rodzicielstwa?",
            "Dostępne żłobki i elastyczny czas pracy", "Wyższy podatek VAT", "Obniżka emerytur",
            why="Zmniejsza koszt alternatywny posiadania dzieci."),
          M("Jakie cele ma polityka rodzinna poza zwiększaniem dzietności?",
            ["Ograniczanie ubóstwa dzieci", "Godzenie pracy i rodziny", "Dobrostan dzieci", "Zwiększanie emigracji"], [0, 1, 2],
            why="Polityka rodzinna nie ma celu zwiększania emigracji."),
          PF("Polityka migracyjna może być elementem polityki ludnościowej.", True,
             why="Migracje zmieniają liczbę i strukturę ludności."),
      ],
      calc=[
          LB("Ile lat obowiązywała polityka jednego dziecka w Chinach (1980–2015)?",
             35, "2015-1980", ["2015 − 1980 = 35"], unit="lat"),
          LB("TFR rośnie z 1,07 do 1,25 dzięki polityce. O ile procent?",
             16.82, "(1.25/1.07-1)*100", ["1,25 / 1,07 ≈ 1,1682 → +16,82%"], unit="%", tol=0.05),
          LB("Przy TFR 1,25 jaki procent progu zastępowalności 2,1 osiągnięto?",
             59.52, "1.25/2.1*100", ["1,25 / 2,1 ≈ 59,52%"], unit="%", tol=0.05),
          LB("Program kosztuje 60 mld zł rocznie i daje (hipotetycznie) 15 tys. dodatkowych urodzeń. Ile kosztuje jedno dodatkowe urodzenie (mln zł)?",
             4, "60e9/15000/1e6", ["60 mld / 15 tys. = 4 mln zł"], unit="mln zł"),
          LB("Urodzenia: 238 tys., kobiety w wieku 15–49: 8,3 mln (dane umowne). Ile wynosi ogólny współczynnik płodności (na 1 000 kobiet)?",
             28.67, "238/8300*1000", ["238 / 8 300 · 1 000 ≈ 28,67"], unit="‰", tol=0.02),
          LB("Polityka przyspiesza urodzenia o 1 rok: w roku 1 rodzi się 20 tys. więcej, w roku 2 o 15 tys. mniej. Ile wynosi efekt netto (tys.)?",
             5, "20-15", ["20 − 15 = 5 tys."], unit="tys."),
      ],
      case=[
          PR("Kraj X wprowadził wysokie świadczenie na drugie i kolejne dzieci. W pierwszych dwóch latach urodzenia wzrosły o 8%, potem wróciły do poprzedniego poziomu, a TFR po 10 latach jest tylko nieco wyższy.",
             W("Jak wyjaśnić krótkotrwały wzrost?",
               "Efektem kalendarza – rodziny przyspieszyły planowane urodzenia", "Błędem statystyki", "Wzrostem umieralności",
               why="Część urodzeń przesunięto w czasie."),
             W("Co mogłoby dać trwalszy efekt według badań?",
               "Rozwiązania ułatwiające łączenie pracy i rodzicielstwa oraz dostęp do mieszkań", "Tylko jeszcze wyższe świadczenie", "Zakaz pracy kobiet",
               why="Obniżają koszty i niepewność związane z dziećmi."),
             PF("Świadczenie mogło jednak zmniejszyć ubóstwo dzieci, nawet jeśli słabo wpłynęło na dzietność.", True,
                why="Polityka rodzinna ma też cele społeczne."),
          ),
          PR("Chiny po 2015 r. zniosły ograniczenia, ale liczba urodzeń dalej spadała. Młodzi mieszkańcy miast wskazują na wysokie koszty mieszkań i edukacji oraz długie godziny pracy.",
             W("Dlaczego zniesienie ograniczeń nie zwiększyło urodzeń?",
               "Normy małej rodziny i wysokie koszty wychowania dzieci się utrwaliły", "Bo Chiny dalej karzą za dzieci", "Bo spadła umieralność",
               why="Decyzje zależą od kosztów i norm, nie tylko od przepisów."),
             W("Jaki problem pogłębia się w Chinach?",
               "Szybkie starzenie się i kurczenie się siły roboczej", "Nadmiar dzieci", "Wysoka dzietność",
               why="Skutek długiej polityki antynatalistycznej."),
             PF("Polityka antynatalistyczna może mieć skutki trudne do odwrócenia.", True,
                why="Zmienia normy i strukturę wieku na dziesięciolecia."),
          ),
      ]),

    L(2, "Transfery pieniężne i ulgi dla rodzin w Polsce",
      "Znać i porównywać pieniężne instrumenty polityki rodzinnej w Polsce – 800 plus, ulgę na dzieci w PIT, becikowe i Dobry Start (stan na 10.2026) – oraz oceniać ich cele i skutki.",
      ["Instrumenty polityki rodzinnej w Polsce"],
      [GOV800, ZUS800, PITAX, INFDZ],
      explain=[
          K("800 plus",
            "Świadczenie wychowawcze – 800 zł miesięcznie na każde dziecko do 18. roku życia, bez kryterium dochodowego (od 1.01.2024; wcześniej 500 zł od 2016 r.). Wypłaca ZUS, okres świadczeniowy trwa od 1 czerwca do 31 maja. To największy transfer rodzinny w budżecie państwa."),
          K("Ulga na dzieci w PIT",
            "Odliczenie od podatku (za 2026 r.): 1 112,04 zł rocznie na 1. i 2. dziecko, 2 000,04 zł na 3. i 2 700 zł na 4. i kolejne. Przy jednym dziecku obowiązuje limit dochodu (112 000 zł dla małżonków i samotnych rodziców). Jeśli podatek jest za niski, część ulgi można otrzymać jako zwrot (do wysokości zapłaconych składek)."),
          W("Rodzina ma troje dzieci. Ile łącznie wynosi roczna ulga na dzieci w PIT?",
            "4 224,12 zł", "3 336,12 zł", "2 224,08 zł",
            why="1 112,04 · 2 + 2 000,04 = 4 224,12 zł."),
          K("Becikowe i Dobry Start",
            "Becikowe – jednorazowo 1 000 zł po urodzeniu dziecka, z progiem dochodowym 1 922 zł netto na osobę. Dobry Start – 300 zł raz w roku na wyprawkę szkolną dla uczniów (do 20. roku życia; do 24. przy niepełnosprawności). Istnieją też zasiłek rodzinny z dodatkami (dla rodzin o niskich dochodach) i Karta Dużej Rodziny (zniżki dla rodzin 3+)."),
          K("Ocena transferów",
            "Zalety: szybkie ograniczenie ubóstwa dzieci, prostota (świadczenie powszechne), wsparcie dochodu rodzin. Wady: wysoki koszt, ograniczony wpływ na dzietność, możliwy niewielki spadek aktywności zawodowej części rodziców (zwłaszcza matek o niskich zarobkach), brak waloryzacji obniża realną wartość z czasem."),
          PF("Świadczenie 800 plus jest wypłacane bez kryterium dochodowego.", True,
             why="To świadczenie powszechne."),
      ],
      mech=[
          KT("Instrument – transfer czy ulga podatkowa?",
             {"Transfer pieniężny": ["800 zł miesięcznie na dziecko", "Becikowe 1 000 zł", "Dobry Start 300 zł"],
              "Ulga podatkowa": ["Odliczenie 1 112,04 zł rocznie na pierwsze dziecko", "2 700 zł odliczenia na czwarte dziecko"]},
             why="Różne mechanizmy wsparcia dochodu rodzin."),
          LN("Ułóż łańcuch wpływu inflacji na realną wartość 800 plus.",
             ["Świadczenie ma stałą kwotę nominalną", "Ceny rosną co roku", "Za 800 zł można kupić coraz mniej", "Realna wartość świadczenia spada", "Pojawiają się postulaty waloryzacji"],
             why="Brak indeksacji obniża realną wartość transferu."),
          W("Dlaczego ulga podatkowa może mniej pomagać rodzinom o najniższych dochodach niż świadczenie pieniężne?",
            "Bo płacą niski podatek, od którego mogą odliczyć niewiele", "Bo nie mają dzieci", "Bo ulga jest wyższa dla nich",
            why="Ulga zależy od zapłaconego podatku (choć część może być zwrócona)."),
          W("Jaki możliwy skutek uboczny powszechnego świadczenia wskazują niektóre badania?",
            "Niewielki spadek aktywności zawodowej części matek o niskich zarobkach", "Wzrost liczby urodzeń o 50%", "Spadek cen mieszkań",
            why="Efekt dochodowy może zmniejszać podaż pracy."),
          M("Które świadczenia mają kryterium dochodowe?",
            ["Becikowe", "Zasiłek rodzinny", "Ulga na jedno dziecko w PIT (limit dochodu rodziców)", "800 plus"], [0, 1, 2],
            why="800 plus jest powszechne."),
          PF("Ulga na trzecie dziecko jest wyższa niż na pierwsze.", True,
             why="2 000,04 zł wobec 1 112,04 zł."),
      ],
      calc=[
          LB("Ile wynosi suma świadczeń 800 plus na jedno dziecko od urodzenia do 18. roku życia (zł)?",
             172800, "800*12*18", ["800 · 12 · 18 = 172 800 zł"], unit="zł"),
          LB("Rodzina z trojgiem dzieci: ile otrzymuje rocznie z 800 plus (zł)?",
             28800, "800*12*3", ["800 · 12 · 3 = 28 800 zł"], unit="zł"),
          LB("Ile wynosi roczna ulga w PIT na czworo dzieci (zł)?",
             6924.12, "1112.04*2+2000.04+2700", ["2 224,08 + 2 000,04 + 2 700 = 6 924,12 zł"], unit="zł", tol=0.01),
          LB("Inflacja wynosi 4% rocznie przez 3 lata. Ile wynosi realna wartość 800 zł w cenach początkowych (zł)?",
             711.20, "800/1.04**3", ["800 / 1,04³ ≈ 711,20 zł"], unit="zł", tol=0.05),
          LB("Rodzina 4-osobowa ma dochód netto 7 500 zł miesięcznie. Ile wynosi dochód na osobę (porównaj z progiem becikowego 1 922 zł)?",
             1875, "7500/4", ["7 500 / 4 = 1 875 zł < 1 922 zł → przysługuje"], unit="zł"),
          LB("Ilu uczniów obsługuje Dobry Start, jeśli wydatki wynoszą 1,35 mld zł (dane umowne), a świadczenie 300 zł (mln)?",
             4.5, "1.35e9/300/1e6", ["1,35 mld / 300 = 4,5 mln"], unit="mln"),
      ],
      case=[
          PR("Rodzina Nowaków: dwoje rodziców pracujących na etatach (łączny dochód 140 000 zł rocznie) i jedno dziecko. Kowalscy: jedna pensja 60 000 zł rocznie i troje dzieci.",
             W("Czy Nowakowie mogą skorzystać z ulgi na jedno dziecko w PIT?",
               "Nie – przekraczają limit 112 000 zł", "Tak, zawsze", "Tylko w połowie",
               why="Limit dochodu przy jednym dziecku wynosi 112 000 zł."),
             W("Ile 800 plus otrzymują rocznie Kowalscy?",
               "28 800 zł", "9 600 zł", "19 200 zł",
               why="800 · 12 · 3 = 28 800 zł."),
             PF("Przy niskim podatku Kowalscy mogą nie wykorzystać całej ulgi z podatku, ale część mogą otrzymać jako zwrot.", True,
                why="Zwrot do wysokości zapłaconych składek."),
          ),
          PR("Ekonomistka zauważa, że od 2024 r. kwota 800 plus się nie zmienia, a ceny rosną. Proponuje coroczną waloryzację o inflację. Minister finansów wskazuje na koszt dla budżetu.",
             W("Co się dzieje z realną wartością świadczenia bez waloryzacji?",
               "Spada", "Rośnie", "Nie zmienia się",
               why="Inflacja zmniejsza siłę nabywczą stałej kwoty."),
             W("Jaki jest argument przeciw automatycznej waloryzacji?",
               "Rosnący koszt dla budżetu przy wysokim deficycie", "Brak inflacji", "Zbyt mała liczba dzieci",
               why="To jeden z największych wydatków socjalnych."),
             PF("Spór dotyczy wyboru między wsparciem rodzin a stanem finansów publicznych.", True,
                why="To typowy dylemat polityki gospodarczej."),
          ),
      ]),

    L(3, "Urlopy, opieka nad dziećmi i godzenie pracy z rodzicielstwem",
      "Rozumieć system urlopów związanych z rodzicielstwem i program Aktywny Rodzic, zasadę nieprzenoszalności urlopu oraz rolę opieki żłobkowej w aktywności zawodowej rodziców (stan na 10.2026).",
      ["Instrumenty polityki rodzinnej w Polsce"],
      [GOVAR, PPURL, INFDZ],
      explain=[
          K("Urlopy",
            "Urlop macierzyński: 20 tygodni przy jednym dziecku. Urlop rodzicielski: 41 tygodni (43 przy ciąży mnogiej), z czego każdemu z rodziców przysługuje wyłącznie 9 tygodni, których nie można przenieść na drugiego (art. 182¹a § 4 Kodeksu pracy, od 26.04.2023 – wdrożenie unijnej dyrektywy work-life balance). Urlop ojcowski: 2 tygodnie. Za urlopy wypłaca się zasiłek macierzyński."),
          K("Nieprzenoszalność",
            "Celem 9 tygodni dla każdego rodzica jest zachęcenie ojców do opieki nad dzieckiem i wyrównanie obciążeń. Jeśli ojciec nie skorzysta ze „swoich” tygodni, przepadają – matka może wykorzystać maksymalnie 32 tygodnie urlopu rodzicielskiego (przy jednym dziecku)."),
          W("Matka chce wykorzystać cały urlop rodzicielski 41 tygodni. Ile maksymalnie może wziąć?",
            "32 tygodnie – 9 tygodni przysługuje wyłącznie ojcu", "41 tygodni", "20 tygodni",
            why="41 − 9 = 32 tygodnie."),
          K("Aktywny Rodzic (od 10.2024)",
            "Dla dzieci w wieku 12–35 miesięcy rodzic wybiera jedną ścieżkę: „aktywnie w żłobku” – do 1 500 zł miesięcznie na opłatę za żłobek lub klub dziecięcy (1 900 zł przy niepełnosprawności); „aktywni rodzice w pracy” – 1 500 zł miesięcznie dla pracujących rodziców (np. na nianię lub babcię), przez maksymalnie 24 miesiące; „aktywnie w domu” – 500 zł miesięcznie, gdy dziecko nie chodzi do żłobka. Program zastąpił Rodzinny Kapitał Opiekuńczy."),
          K("Dlaczego żłobki są ważne",
            "Dostępna i tania opieka nad małymi dziećmi zwiększa aktywność zawodową matek, zmniejsza koszt alternatywny rodzicielstwa i – według badań porównawczych – wiąże się z wyższą dzietnością w krajach rozwiniętych. W Polsce dostępność żłobków znacznie wzrosła, ale nadal jest zróżnicowana między miastami a wsiami."),
          PF("Ścieżka „aktywni rodzice w pracy” jest przeznaczona dla rodziców pracujących, których dziecko nie chodzi do żłobka.", True,
             why="Środki można przeznaczyć np. na nianię."),
      ],
      mech=[
          KT("Która ścieżka Aktywnego Rodzica?",
             {"Aktywnie w żłobku": ["Dziecko chodzi do żłobka, ZUS przelewa do 1 500 zł na opłatę"],
              "Aktywni rodzice w pracy": ["Oboje rodzice pracują, dzieckiem opiekuje się babcia"],
              "Aktywnie w domu": ["Mama zostaje z dzieckiem w domu – 500 zł miesięcznie", "Tata opiekuje się dzieckiem w domu i nie korzysta ze żłobka"]},
             why="Trzy ścieżki, z których wybiera się jedną."),
          LN("Ułóż mechanizm wpływu żłobków na dzietność i zatrudnienie.",
             ["Rośnie dostępność taniej opieki żłobkowej", "Rodzice mogą wcześniej wrócić do pracy", "Spada koszt alternatywny posiadania dziecka", "Rosną dochody i stabilność finansowa rodziny", "Łatwiej podjąć decyzję o kolejnym dziecku"],
             why="Godzenie pracy i rodziny obniża koszty rodzicielstwa."),
          W("Jaki jest główny cel nieprzenoszalnej części urlopu rodzicielskiego?",
            "Zwiększenie udziału ojców w opiece nad dziećmi", "Skrócenie urlopów", "Obniżenie zasiłków",
            why="Wdraża unijną dyrektywę work-life balance."),
          W("Rodzina mieszka na wsi bez żłobka, oboje rodzice pracują, a dzieckiem zajmuje się dziadek. Którą ścieżkę wybierze?",
            "Aktywni rodzice w pracy", "Aktywnie w żłobku", "Żadną",
            why="Dziecko nie chodzi do żłobka, rodzice pracują."),
          M("Jakie urlopy związane z rodzicielstwem przewiduje Kodeks pracy?",
            ["Macierzyński", "Rodzicielski", "Ojcowski", "Urlop emerytalny"], [0, 1, 2],
            why="Urlopu emerytalnego nie ma."),
          PF("Aktywny Rodzic zastąpił Rodzinny Kapitał Opiekuńczy.", True,
             why="Program działa od października 2024 r."),
      ],
      calc=[
          LB("Ile tygodni urlopu rodzicielskiego może maksymalnie wykorzystać jeden rodzic (1 dziecko)?",
             32, "41-9", ["41 − 9 = 32 tygodnie"], unit="tyg."),
          LB("Ile tygodni urlopu macierzyńskiego i rodzicielskiego łącznie (1 dziecko)?",
             61, "20+41", ["20 + 41 = 61 tygodni"], unit="tyg."),
          LB("„Aktywni rodzice w pracy”: 1 500 zł przez 24 miesiące. Ile łącznie (zł)?",
             36000, "1500*24", ["1 500 · 24 = 36 000 zł"], unit="zł"),
          LB("„Aktywnie w domu”: 500 zł przez 24 miesiące. Ile łącznie (zł)?",
             12000, "500*24", ["500 · 24 = 12 000 zł"], unit="zł"),
          LB("Żłobek kosztuje 1 800 zł, dopłata 1 500 zł. Ile płaci rodzic (zł)?",
             300, "1800-1500", ["1 800 − 1 500 = 300 zł"], unit="zł"),
          LB("Żłobek kosztuje 1 200 zł miesięcznie. Ile wynosi dopłata z programu (nie więcej niż opłata) (zł)?",
             1200, "1200", ["Dopłata nie może przekroczyć opłaty: 1 200 zł"], unit="zł"),
      ],
      case=[
          PR("Ania i Tomek mają rocznego syna. Ania wraca do pracy, Tomek chce wziąć urlop rodzicielski. Szef Tomka uważa, że „urlop rodzicielski jest dla matek”.",
             W("Czy Tomek ma prawo do urlopu rodzicielskiego?",
               "Tak – każdemu z rodziców przysługuje m.in. 9 nieprzenoszalnych tygodni", "Nie – tylko matka", "Tylko za zgodą szefa",
               why="Prawo wynika z art. 182¹a Kodeksu pracy."),
             W("Co się stanie, jeśli Tomek nie wykorzysta swoich 9 tygodni?",
               "Przepadną – Ania nie może ich przejąć", "Przejdą na Anię", "Zamienią się na pieniądze",
               why="Część nieprzenoszalna."),
             PF("Udział ojców w opiece może ułatwić matkom powrót do pracy.", True,
                why="Obciążenia opiekuńcze rozkładają się równiej."),
          ),
          PR("W gminie wiejskiej nie ma żłobka. Gmina może zbudować żłobek na 40 miejsc lub dofinansować dzienne opiekunki. Wiele matek nie wraca do pracy przed trzecimi urodzinami dziecka.",
             W("Jaki skutek może mieć budowa żłobka?",
               "Wzrost aktywności zawodowej matek", "Spadek zatrudnienia", "Brak skutków",
               why="Opieka umożliwia powrót do pracy."),
             W("Która ścieżka Aktywnego Rodzica byłaby dostępna po otwarciu żłobka?",
               "Aktywnie w żłobku – do 1 500 zł na opłatę", "Tylko aktywnie w domu", "Żadna",
               why="Dopłata do opłaty za żłobek."),
             PF("Dostępność opieki nad dziećmi różni się między miastami i wsiami.", True,
                why="Na wsiach żłobków jest znacznie mniej."),
          ),
      ]),

    L(4, "Skuteczność polityki rodzinnej – doświadczenia krajów",
      "Porównywać modele polityki rodzinnej (Francja, kraje nordyckie, Węgry, Azja Wschodnia) i rozumieć, dlaczego trudno ocenić jej wpływ na dzietność oraz jakie wnioski płyną dla Polski.",
      ["Polityka ludnościowa (demograficzna)", "Instrumenty polityki rodzinnej w Polsce"],
      [OWIDF, EUFERT, GUSPWL],
      explain=[
          K("Modele polityki rodzinnej",
            "Francja – długa tradycja polityki pronatalistycznej: hojne ulgi podatkowe rosnące z liczbą dzieci (iloraz rodzinny), powszechne przedszkola i żłobki – TFR przez lata należał do najwyższych w UE. Kraje nordyckie – nacisk na równość płci: długie, dobrze płatne urlopy z częścią dla ojców i powszechna opieka nad dziećmi. Węgry – rozbudowane ulgi podatkowe i kredyty mieszkaniowe dla rodzin. Korea Płd. i Japonia – duże wydatki, ale bardzo niska dzietność przy kulturze długich godzin pracy i wysokich kosztach edukacji."),
          K("Problem pomiaru",
            "Ocena skuteczności jest trudna: dzietność zależy też od koniunktury, mieszkań, norm, edukacji kobiet. Część efektu to zmiana kalendarza urodzeń. Wzrost TFR w latach po wprowadzeniu programu może wynikać z innych przyczyn (np. poprawy na rynku pracy). Dlatego badacze stosują metody porównujące grupy objęte i nieobjęte programem."),
          W("W roku wprowadzenia zasiłku bezrobocie spadło o 3 pkt proc., a urodzenia wzrosły. Jaki problem ma ocena programu?",
            "Trudno oddzielić efekt zasiłku od poprawy na rynku pracy", "Nie ma żadnego problemu", "Zasiłek na pewno nie działał",
            why="Wiele czynników zmienia się jednocześnie."),
          K("Wnioski z badań",
            "Pakiety łączące usługi (żłobki, przedszkola), urlopy dla obojga rodziców, elastyczną pracę i stabilność (mieszkania, umowy) wiążą się z wyższą dzietnością niż same transfery pieniężne. Spadek dzietności w ostatniej dekadzie dotknął jednak także krajów nordyckich i Francji – czynniki kulturowe i niepewność (mieszkania, klimat, rynek pracy) odgrywają rosnącą rolę."),
          K("Polska",
            "TFR w Polsce wzrósł z ok. 1,29 w 2015 r. do ok. 1,45 w 2017 r., po czym zaczął spadać, aż do 1,068 w 2025 r. – mimo podwyższenia świadczenia do 800 zł. Wskazuje to, że transfery same nie odwracają trendu, a ważne są mieszkania, stabilność zatrudnienia, opieka nad dziećmi i postawy młodych."),
          PF("Spadek dzietności w ostatnich latach dotyczy także krajów o rozbudowanej polityce rodzinnej.", True,
             why="Np. kraje nordyckie i Francja."),
      ],
      mech=[
          KT("Model polityki rodzinnej",
             {"Francja": ["Iloraz rodzinny w podatku dochodowym", "Powszechne przedszkola od wczesnego wieku"],
              "Kraje nordyckie": ["Długie, dobrze płatne urlopy z częścią dla ojców"],
              "Węgry": ["Preferencyjne kredyty mieszkaniowe dla rodzin z dziećmi", "Zwolnienia podatkowe dla matek wielu dzieci"]},
             why="Różne kraje akcentują inne instrumenty."),
          LN("Ułóż poprawną metodę oceny programu.",
             ["Określ grupę objętą programem i podobną grupę nieobjętą", "Zbierz dane o urodzeniach przed i po wprowadzeniu", "Porównaj zmiany w obu grupach", "Uwzględnij inne czynniki (rynek pracy, mieszkania)", "Sprawdź, czy efekt jest trwały, czy to zmiana kalendarza"],
             why="Porównanie różnic w różnicach ogranicza błędne wnioski."),
          W("Dlaczego wysokie wydatki na rodziny w Korei Płd. nie podniosły dzietności?",
            "Bariery kulturowe i ekonomiczne – długie godziny pracy, koszty edukacji i mieszkań – pozostały", "Bo wydatki były zerowe", "Bo dzietność już była wysoka",
            why="Same pieniądze nie usuwają głównych barier."),
          W("Co sugeruje przebieg TFR w Polsce po 2017 r.?",
            "Transfery pieniężne same nie odwracają długookresowego trendu spadkowego", "Że 800 plus podwoiło dzietność", "Że TFR rośnie",
            why="TFR spadł do 1,068 w 2025 r."),
          M("Jakie elementy pakietów wiążą się z wyższą dzietnością?",
            ["Dostępne żłobki", "Urlopy dla obojga rodziców", "Stabilne warunki mieszkaniowe", "Długie godziny pracy"], [0, 1, 2],
            why="Długie godziny pracy utrudniają rodzicielstwo."),
          PF("Wzrost urodzeń po wprowadzeniu programu nie dowodzi sam w sobie jego skuteczności.", True,
             why="Mogą działać inne czynniki i efekt kalendarza."),
      ],
      calc=[
          LB("TFR wzrósł z 1,29 do 1,45. O ile procent?",
             12.4, "(1.45/1.29-1)*100", ["1,45 / 1,29 ≈ 1,124 → +12,4%"], unit="%", tol=0.05),
          LB("TFR spadł z 1,45 do 1,068. O ile procent?",
             26.34, "(1-1.068/1.45)*100", ["1,068 / 1,45 ≈ 0,7366 → −26,34%"], unit="%", tol=0.05),
          LB("Różnica w różnicach: w grupie objętej urodzenia +6%, w grupie kontrolnej +2%. Ile wynosi oszacowany efekt (pkt proc.)?",
             4, "6-2", ["6 − 2 = 4 pkt proc."], unit="pkt proc."),
          LB("Wydatki na rodziny 3,5% PKB przy PKB 3 800 mld zł (dane umowne). Ile wynoszą (mld zł)?",
             133, "3800*0.035", ["3 800 · 0,035 = 133 mld zł"], unit="mld zł"),
          LB("Iloraz rodzinny: dochód 120 000 zł, 3 „części” (rodzice + dzieci). Ile wynosi dochód na część (zł)?",
             40000, "120000/3", ["120 000 / 3 = 40 000 zł"], unit="zł"),
          LB("Ile lat dzieli wprowadzenie 500 plus (2016) od jego podwyższenia do 800 zł (2024)?",
             8, "2024-2016", ["2024 − 2016 = 8"], unit="lat"),
      ],
      case=[
          PR("Rząd chce przeznaczyć dodatkowe 20 mld zł na politykę rodzinną. Opcja A: podwyżka świadczenia na dziecko. Opcja B: budowa żłobków, tańsze mieszkania na wynajem dla młodych rodzin i dłuższe urlopy ojcowskie.",
             W("Która opcja według badań ma większy potencjał trwałego wpływu na dzietność?",
               "Opcja B – usługi, mieszkania i urlopy", "Opcja A – wyłącznie transfer", "Żadna",
               why="Obniża bariery i koszt alternatywny rodzicielstwa."),
             W("Jaka jest zaleta opcji A?",
               "Szybko i prosto zwiększa dochody rodzin, zmniejsza ubóstwo dzieci", "Natychmiast tworzy miejsca w żłobkach", "Obniża ceny mieszkań",
               why="Transfer działa od razu na dochody."),
             PF("Efekty opcji B pojawią się z opóźnieniem.", True,
                why="Budowa żłobków i mieszkań wymaga czasu."),
          ),
          PR("Analityk porównuje dwa województwa: w jednym gmina A sfinansowała darmowe żłobki, a w porównywalnej gminie B ich nie było. Po 5 latach dzietność w A wzrosła o 0,08, a w B spadła o 0,04.",
             W("Jaki jest oszacowany efekt programu metodą różnicy w różnicach?",
               "+0,12", "+0,08", "−0,04",
               why="0,08 − (−0,04) = 0,12."),
             W("Co może zafałszować wynik?",
               "Inne różnice między gminami, np. napływ młodych rodzin do A", "Nic", "Liczba radnych",
               why="Migracje mogą zmieniać skład ludności."),
             PF("Porównanie z grupą kontrolną daje lepszą ocenę niż samo porównanie przed i po.", True,
                why="Uwzględnia ogólne trendy."),
          ),
      ]),

    L(5, "Regionalna polityka demograficzna",
      "Rozumieć zróżnicowanie procesów demograficznych między regionami Polski, przyczyny wyludniania się obszarów peryferyjnych oraz instrumenty regionalnej i lokalnej polityki demograficznej.",
      ["Regionalna polityka demograficzna"],
      [GUSPWL, EUFERT],
      explain=[
          K("Zróżnicowanie regionalne",
            "Procesy demograficzne w Polsce przebiegają nierównomiernie: wokół dużych miast (Warszawa, Kraków, Wrocław, Gdańsk, Poznań) ludność rośnie dzięki migracjom młodych, a regiony peryferyjne (m.in. część województw wschodnich, Opolszczyzna, Świętokrzyskie) tracą mieszkańców przez ujemny przyrost i odpływ. Różnią się też trwanie życia (najdłuższe na Podkarpaciu, najkrótsze w Łódzkiem) i struktura wieku."),
          K("Spirala wyludniania",
            "Odpływ młodych → mniej urodzeń i starsza struktura wieku → zamykanie szkół, przychodni, połączeń komunikacyjnych → spadek atrakcyjności miejsca → dalszy odpływ. Kurczą się dochody samorządów (PIT), a rosną koszty usług dla seniorów."),
          W("Gmina zamyka szkołę i ostatnie połączenie autobusowe. Jak może to wpłynąć na migracje?",
            "Zwiększyć odpływ młodych rodzin", "Zatrzymać odpływ", "Nie mieć wpływu",
            why="Pogarsza warunki życia rodzin z dziećmi."),
          K("Instrumenty",
            "Lokalne: dodatkowe świadczenia i ulgi dla rodzin, mieszkania komunalne i na wynajem dla młodych, żłobki, transport publiczny, przyciąganie inwestorów i pracy zdalnej, programy powrotów. Regionalne i krajowe: fundusze UE na rozwój obszarów zagrożonych marginalizacją, Krajowa Strategia Rozwoju Regionalnego (obszary strategicznej interwencji), inwestycje w infrastrukturę i usługi."),
          K("Adaptacja do kurczenia się",
            "Nie wszędzie da się odwrócić depopulację. Strategią może być „inteligentne kurczenie się” (smart shrinking): łączenie usług, przekształcanie zbędnej infrastruktury, usługi mobilne i cyfrowe, dostosowanie miast do starszej populacji – zamiast budowania na wyrost."),
          PF("Strefy podmiejskie dużych miast w Polsce zwykle zyskują ludność dzięki migracjom.", True,
             why="Przyciągają młode rodziny z miast i regionów peryferyjnych."),
      ],
      mech=[
          KT("Instrument lokalny czy krajowy/unijny?",
             {"Lokalny (gmina, powiat)": ["Mieszkania komunalne na wynajem dla młodych rodzin", "Gminny bon żłobkowy", "Dowóz dzieci do szkół"],
              "Krajowy lub unijny": ["Fundusze UE dla obszarów zagrożonych marginalizacją", "Krajowa strategia rozwoju regionalnego"]},
             why="Polityka demograficzna działa na kilku poziomach."),
          LN("Ułóż spiralę wyludniania.",
             ["Młodzi wyjeżdżają do dużych miast", "Spada liczba urodzeń, rośnie udział seniorów", "Zamyka się szkoły i usługi", "Region staje się mniej atrakcyjny", "Odpływ młodych przyspiesza"],
             why="Mechanizm samonapędzającego się spadku."),
          W("Co oznacza strategia „inteligentnego kurczenia się”?",
            "Dostosowanie usług i infrastruktury do mniejszej i starszej populacji", "Zakaz wyprowadzki z miasta", "Budowę nowych osiedli bez mieszkańców",
            why="Adaptacja zamiast nierealnego odwracania trendów."),
          W("Dlaczego praca zdalna może pomóc gminom peryferyjnym?",
            "Pozwala mieszkać poza dużym miastem, zarabiając tam", "Zwiększa koszty dojazdów", "Obniża dochody",
            why="Oddziela miejsce pracy od miejsca zamieszkania."),
          M("Jakie są skutki wyludniania dla samorządu?",
            ["Niższe wpływy z PIT", "Wyższe koszty usług na mieszkańca", "Rosnące potrzeby opieki senioralnej", "Szybki wzrost liczby uczniów"], [0, 1, 2],
            why="Liczba uczniów maleje."),
          PF("W Polsce najdłużej żyją mieszkańcy województwa podkarpackiego.", True,
             why="Dotyczy to zarówno kobiet, jak i mężczyzn (dane za 2025 r.)."),
      ],
      calc=[
          LB("Gmina: 9 000 mieszkańców w 2015 r., 7 900 w 2025 r. O ile procent spadła liczba ludności?",
             12.22, "(1-7900/9000)*100", ["7 900 / 9 000 ≈ 0,8778 → −12,22%"], unit="%", tol=0.02),
          LB("Szkoła ma 120 uczniów, a liczba dzieci spada o 4% rocznie. Ilu uczniów będzie za 5 lat?",
             97.84, "120*0.96**5", ["120 · 0,96⁵ ≈ 97,84"], unit="uczn.", tol=0.05),
          LB("Koszt utrzymania szkoły 3 mln zł rocznie. Ile wynosi koszt na ucznia przy 120 uczniach (zł)?",
             25000, "3000000/120", ["3 mln / 120 = 25 000 zł"], unit="zł"),
          LB("Ten sam koszt przy 80 uczniach (zł)?",
             37500, "3000000/80", ["3 mln / 80 = 37 500 zł"], unit="zł"),
          LB("Gmina oferuje 50 mieszkań na wynajem; każde przyciąga rodzinę 3,4-osobową. Ilu mieszkańców przybędzie?",
             170, "50*3.4", ["50 · 3,4 = 170"], unit="osób"),
          LB("Różnica e₀ mężczyzn: podkarpackie 76,8, łódzkie 73,9. Ile lat?",
             2.9, "76.8-73.9", ["76,8 − 73,9 = 2,9"], unit="lat", tol=0.001),
      ],
      case=[
          PR("Gmina w województwie opolskim straciła w 10 lat 15% mieszkańców. Wójt proponuje: gminny dodatek 1 000 zł za urodzenie dziecka, budowę 30 mieszkań na wynajem dla młodych, dowożenie dzieci do szkoły w sąsiedniej gminie oraz przyciągnięcie firmy logistycznej.",
             W("Które działanie najbezpośredniej odpowiada na przyczynę odpływu młodych?",
               "Przyciągnięcie pracodawcy i mieszkania na wynajem", "Tylko dodatek 1 000 zł", "Zamknięcie urzędu",
               why="Młodzi wyjeżdżają głównie za pracą i mieszkaniem."),
             W("Co oznacza dowożenie dzieci do szkoły w sąsiedniej gminie?",
               "Element adaptacji – łączenie usług przy malejącej liczbie dzieci", "Wzrost liczby uczniów", "Budowę nowej szkoły",
               why="Strategia „inteligentnego kurczenia się”."),
             PF("Jednorazowy dodatek za urodzenie sam w sobie raczej nie odwróci wyludniania.", True,
                why="Nie usuwa głównych przyczyn odpływu."),
          ),
          PR("Gmina podmiejska pod Wrocławiem rośnie o 5% rocznie. Brakuje przedszkoli i dróg, a za 25 lat obecni 35-latkowie będą seniorami.",
             W("Jakie ryzyko demograficzne ma ta gmina w długim okresie?",
               "Gwałtowne starzenie się jednolitych wiekowo osiedli", "Wyludnienie w ciągu 5 lat", "Brak dzieci teraz",
               why="Napływ osób w podobnym wieku tworzy falę starzenia."),
             W("Jak dobrze zaplanować infrastrukturę?",
               "Budować elastycznie – obiekty, które można przekształcić (np. przedszkole w dom seniora)", "Budować tylko szkoły", "Nie budować niczego",
               why="Potrzeby zmienią się wraz z wiekiem mieszkańców."),
             PF("Regiony Polski różnią się kierunkiem zmian demograficznych.", True,
                why="Strefy podmiejskie rosną, peryferie się wyludniają."),
          ),
      ]),
    L(6, "Kara za macierzyństwo i przemiany gospodarstw domowych",
      "Rozumieć, jak urodzenie dziecka wpływa na zarobki kobiet i mężczyzn (child penalty) i jakie rozwiązania ją łagodzą, oraz jak nuklearyzacja rodzin i wzrost liczby gospodarstw jednoosobowych zmieniają popyt na mieszkania i usługi opiekuńcze.",
      ["Kara za macierzyństwo (child penalty)", "Gospodarstwo domowe i rodzina – nuklearyzacja"],
      [S("NBER WP 24219 – Kleven, Landais, Søgaard: Children and gender inequality", "https://www.nber.org/papers/w24219.pdf", "2026-10-10"),
       S("Wikipedia – Child penalties", "https://en.wikipedia.org/wiki/Child_penalties", "2026-10-10"),
       S("GUS Białystok – NSP 2021: households and dwellings", "https://bialystok.stat.gov.pl/download/gfx/bialystok/en/defaultstronaopisowa/728/1/1/10_households._dwellings.pdf", "2026-10-10")],
      explain=[
          K("Kara za macierzyństwo",
            "H. Kleven, C. Landais i J.E. Søgaard (2019) porównali zarobki kobiet i mężczyzn w Danii przed i po urodzeniu pierwszego dziecka. Do narodzin ścieżki są podobne; potem zarobki kobiet spadają i nie wracają do poziomu mężczyzn – w długim okresie luka wynosi ok. 20%. Zarobki ojców prawie się nie zmieniają."),
          K("Skąd bierze się kara?",
            "Na spadek zarobków matek w podobnym stopniu składają się trzy kanały: rzadsza aktywność zawodowa (część kobiet nie wraca do pracy), krótszy czas pracy (niepełny etat) i niższe stawki godzinowe (wybór mniej wymagających stanowisk, wolniejszy awans). C. Goldin (Nobel 2023) wskazała, że dziś to rodzicielstwo, a nie wykształcenie, wyjaśnia większość luki płacowej."),
          K("Kara a dzietność",
            "Kara za macierzyństwo to część kosztu alternatywnego dziecka. Im jest wyższa, tym silniejsza zachęta do odkładania lub rezygnacji z urodzeń. Łagodzą ją: dostęp do żłobków i przedszkoli, urlopy przeznaczone dla ojców (nieprzenaszalne), elastyczne formy pracy i równiejszy podział obowiązków domowych."),
          K("Gospodarstwo domowe a rodzina",
            "Gospodarstwo domowe to osoby wspólnie mieszkające i utrzymujące się (lub osoba samotna); rodzina – osoby połączone małżeństwem lub pokrewieństwem (para z dziećmi lub bez, samotny rodzic). Nuklearyzacja to przejście od rodzin wielopokoleniowych do dwupokoleniowych. Dziś przeciętne gospodarstwo jest coraz mniejsze, a przybywa gospodarstw jednoosobowych – zwłaszcza osób starszych."),
          K("Skutki gospodarcze",
            "Mniejsze gospodarstwa oznaczają więcej gospodarstw przy tej samej liczbie ludności, a więc większy popyt na mieszkania – nawet gdy ludność maleje. Samotnie mieszkający seniorzy potrzebują więcej usług opiekuńczych z zewnątrz, bo rodzina wielopokoleniowa nie zapewnia już opieki na miejscu.",
            w="liczba gospodarstw = ludność / przeciętna wielkość gospodarstwa"),
          W("Co pokazuje badanie Klevena, Landais i Søgaard?",
            "Po urodzeniu pierwszego dziecka zarobki kobiet trwale spadają w porównaniu z zarobkami mężczyzn", "Zarobki ojców spadają bardziej niż matek", "Urodzenie dziecka nie wpływa na zarobki",
            why="W Danii długookresowa luka wynosi ok. 20%, a zarobki ojców prawie się nie zmieniają."),
          W("Ludność kraju się nie zmienia, ale maleje przeciętna wielkość gospodarstwa domowego. Co dzieje się z liczbą gospodarstw?",
            "Rośnie", "Maleje", "Nie zmienia się",
            why="Liczba gospodarstw = ludność / przeciętna wielkość."),
          PF("Nuklearyzacja oznacza przejście od rodzin wielopokoleniowych do rodzin dwupokoleniowych.", True,
             why="Rodzina nuklearna to rodzice z dziećmi."),
      ],
      mech=[
          KT("Czy rozwiązanie zmniejsza karę za macierzyństwo?",
             {"Zmniejsza": ["Powszechny dostęp do żłobków", "Nieprzenaszalny urlop dla ojca", "Możliwość pracy zdalnej"],
              "Nie zmniejsza lub zwiększa": ["Bardzo długi urlop wyłącznie dla matki", "Brak opieki nad dziećmi do lat 3", "Sztywny czas pracy"]},
             why="Kara maleje, gdy matki mogą szybciej wrócić do pracy, a ojcowie przejmują część opieki."),
          LN("Ułóż łańcuch: od nuklearyzacji do popytu na mieszkania.",
             ["Rodziny wielopokoleniowe dzielą się na mniejsze", "Maleje przeciętna wielkość gospodarstwa domowego", "Rośnie liczba gospodarstw domowych", "Rośnie popyt na mieszkania mimo stałej lub malejącej ludności"],
             why="Każde gospodarstwo potrzebuje osobnego mieszkania."),
          W("Państwo wprowadza 9 tygodni urlopu, który przepada, jeśli nie wykorzysta go ojciec. Jak to wpływa na karę za macierzyństwo?",
            "Może ją zmniejszyć, bo opieka rozkłada się na oboje rodziców", "Zwiększa ją", "Nie ma żadnego wpływu",
            why="Matka może wcześniej wrócić do pracy, a pracodawcy rzadziej traktują ją jako jedyną opiekunkę."),
          W("Rośnie liczba samotnie mieszkających osób w wieku 80+. Na jakie usługi wzrośnie popyt?",
            "Usługi opiekuńcze i opieka długoterminowa", "Żłobki", "Szkoły średnie",
            why="Brak rodziny na miejscu oznacza potrzebę opieki zewnętrznej."),
          M("Które kanały składają się na karę za macierzyństwo?",
            ["Rzadsza aktywność zawodowa matek", "Krótszy czas pracy", "Niższe stawki godzinowe", "Wyższe podatki od rodziców"], [0, 1, 2],
            why="Te trzy kanały mają podobny udział w spadku zarobków."),
          PF("Spadek liczby ludności zawsze oznacza spadek popytu na mieszkania.", False,
             why="Jeśli gospodarstwa się zmniejszają, ich liczba może rosnąć."),
      ],
      calc=[
          LB("Przed urodzeniem dziecka kobieta i mężczyzna zarabiali po 6 000 zł. Po 10 latach mężczyzna zarabia 7 500 zł, a kobieta 6 000 zł. Ile wynosi kara za macierzyństwo (% zarobków mężczyzny)?",
             20, "(1-6000/7500)*100", ["6 000 / 7 500 = 0,8", "(1 − 0,8) · 100 = 20%"], unit="%", tol=0.01),
          LB("Przy karze 20% i potencjalnych zarobkach 72 000 zł rocznie ile kobieta traci rocznie (zł)?",
             14400, "72000*0.2", ["72 000 · 0,2 = 14 400 zł"], unit="zł", tol=0.5),
          LB("Ile wynosi strata przez 25 lat (bez dyskontowania, tys. zł)?",
             360, "14400*25/1000", ["14 400 · 25 = 360 000 zł"], unit="tys. zł", tol=0.01),
          LB("Ludność 37,3 mln, przeciętna wielkość gospodarstwa 2,5 osoby. Ile jest gospodarstw domowych (mln)?",
             14.92, "37.3/2.5", ["37,3 / 2,5 = 14,92 mln"], unit="mln", tol=0.01),
          LB("Ludność spada do 36 mln, a przeciętna wielkość gospodarstwa do 2,3 osoby. O ile mln zmienia się liczba gospodarstw w porównaniu z 14,92 mln?",
             0.73, "36/2.3-37.3/2.5", ["36 / 2,3 ≈ 15,65 mln", "15,65 − 14,92 ≈ 0,73 mln – gospodarstw przybywa"], unit="mln", tol=0.01),
          LB("Wśród 15 mln gospodarstw 3,6 mln to gospodarstwa jednoosobowe. Jaki to odsetek (%)?",
             24, "3.6/15*100", ["3,6 / 15 · 100 = 24%"], unit="%", tol=0.01),
      ],
      case=[
          PR("Marta i Piotr, oboje informatycy, zarabiali przed urodzeniem dziecka po 10 000 zł. Marta wzięła roczny urlop, potem przeszła na 3/4 etatu i zrezygnowała z awansu na kierowniczkę zespołu. Po 5 latach zarabia 6 500 zł, Piotr – 12 000 zł.",
             W("Jak nazywa się zjawisko z opisu?",
               "Kara za macierzyństwo", "Luka emerytalna", "Efekt tempa",
               why="Spadek zarobków matki w porównaniu z ojcem po urodzeniu dziecka."),
             W("Które kanały kary wystąpiły w przypadku Marty?",
               "Przerwa w pracy, krótszy czas pracy i rezygnacja z awansu", "Wyższe podatki", "Wyłącznie inflacja",
               why="To trzy kanały opisane przez Klevena i współautorów."),
             PF("Kara za macierzyństwo obniża też przyszłą emeryturę Marty.", True,
                why="Niższe zarobki to niższe składki emerytalne."),
          ),
          PR("W średnim mieście liczba mieszkańców spadła w ciągu 20 lat o 8%, ale liczba gospodarstw domowych wzrosła o 5%. Deweloperzy nadal budują małe mieszkania, a miejski ośrodek pomocy społecznej zgłasza rosnące kolejki do usług opiekuńczych.",
             W("Co wyjaśnia wzrost liczby gospodarstw przy spadku ludności?",
               "Zmniejszanie się przeciętnej wielkości gospodarstwa", "Wzrost dzietności", "Napływ rodzin wielopokoleniowych",
               why="Więcej osób mieszka samotnie lub w małych gospodarstwach."),
             W("Dlaczego rosną kolejki do usług opiekuńczych?",
               "Więcej seniorów mieszka samotnie, bez opieki rodziny na miejscu", "Spadła liczba seniorów", "Wzrosła liczba urodzeń",
               why="Nuklearyzacja i starzenie się zwiększają popyt na opiekę zewnętrzną."),
             PF("W takim mieście popyt na małe mieszkania może rosnąć mimo depopulacji.", True,
                why="Liczy się liczba gospodarstw, a nie tylko mieszkańców."),
          ),
      ]),
]
