# -*- coding: utf-8 -*-
# Zrozumienie – Demografia / Systemy emerytalne
D = "2026-10-08"
BARR = S("N. Barr, Reforming Pensions: Myths, Truths, and Policy Choices (IMF WP/00/139)", "https://www.imf.org/external/pubs/ft/wp/2000/wp00139.pdf", D)
UEFUS = S("Ustawa z 17.12.1998 o emeryturach i rentach z FUS (Dz.U. 1998 nr 162 poz. 1118) – tekst pierwotny, ELI", "https://api.sejm.gov.pl/eli/acts/DU/1998/1118/text.pdf", D)
USUS = S("Ustawa z 13.10.1998 o systemie ubezpieczeń społecznych (Dz.U. 1998 nr 137 poz. 887) – tekst pierwotny, ELI", "https://api.sejm.gov.pl/eli/acts/DU/1998/887/text.pdf", D)
ZUSEM = S("ZUS – Emerytury", "https://www.zus.pl/swiadczenia/emerytury", D)
INFW = S("infakt.pl – Waloryzacja emerytur 2026", "https://www.infakt.pl/blog/waloryzacja-emerytur-2026-tabela/", D)
INFT = S("infor.pl – Nowe tablice dalszego trwania życia (2026)", "https://www.infor.pl/prawo/prawa-seniora/emerytura/7553784,zus-emerytury-w-latach-20262027-beda-nizsze-bo-polacy-dluzej-zyja-taki-jest-efekt-nowych-tablic-sredniego-dalszego-trwania-zycia-ogloszonych-przez-prezesa-gus.html", D)
GUSPWL = S("GUS – Polska w liczbach 2026 (dane za 2025 r.)", "https://plwliczbach.stat.gov.pl/pl/assets/pdf/polska-w-liczbach-2026.pdf", D)
AGEREP = S("Komisja Europejska – 2024 Ageing Report", "https://economy-finance.ec.europa.eu/publications/2024-ageing-report-economic-and-budgetary-projections-eu-member-states-2022-2070_en", D)

LESSONS = [
    L(1, "Cele systemów emerytalnych i mity reform",
      "Rozumieć cele systemu emerytalnego według N. Barra i P. Diamonda oraz najczęstsze mity w debacie o reformach emerytalnych – zwłaszcza o wyższości systemów kapitałowych.",
      ["Cele systemu emerytalnego (Barr i Diamond)", "Mity reform emerytalnych"],
      [BARR],
      explain=[
          K("Cele według Barra i Diamonda",
            "Z punktu widzenia jednostki: wygładzanie konsumpcji w cyklu życia (przesunięcie dochodu z okresu pracy na starość) i ubezpieczenie – zwłaszcza od ryzyka długowieczności (nie wiemy, jak długo będziemy żyć). Z punktu widzenia państwa: łagodzenie ubóstwa w starości i redystrybucja. Dodatkowe cele mogą obejmować wzrost gospodarczy, ale system emerytalny jest przede wszystkim instrumentem zabezpieczenia."),
          K("Kluczowa prawda: liczy się produkcja",
            "Emeryci konsumują dobra wytwarzane przez pracujących w danym momencie. Dlatego zarówno system repartycyjny, jak i kapitałowy zależą od przyszłej produkcji: w pierwszym emeryci mają roszczenia wobec składek pracujących, w drugim – aktywa, które sprzedają pracującym. Starzenie się dotyka obu typów systemów (N. Barr: „output is central”)."),
          W("Dlaczego system kapitałowy nie chroni automatycznie przed skutkami starzenia się?",
            "Bo emeryci i tak muszą sprzedać aktywa mniejszej liczbie pracujących lub korzystać z ich produkcji", "Bo nie ma w nim pieniędzy", "Bo jest zakazany w UE",
            why="Mniej kupujących aktywa obniża ich ceny; liczy się przyszła produkcja."),
          K("Mity reform (Barr, 2000)",
            "Przykłady mitów: „system kapitałowy rozwiązuje problem starzenia” (nie, jeśli nie zwiększa produkcji); „przejście na system kapitałowy zawsze zwiększa oszczędności narodowe” (nie, gdy finansuje się je długiem); „systemy kapitałowe nie są narażone na ryzyko polityczne i rynkowe” (są); „systemy kapitałowe mają niższe koszty administracyjne” (często wyższe). Barr podkreśla, że wybór systemu zależy od zdolności instytucjonalnych kraju."),
          K("Co naprawdę pomaga",
            "Działania, które zwiększają przyszłą produkcję: wyższe zatrudnienie, dłuższa praca, wyższa wydajność (kapitał ludzki i rzeczowy), imigracja. Zmiana sposobu finansowania emerytur sama w sobie nie tworzy dodatkowych dóbr."),
          PF("Ubezpieczenie od ryzyka długowieczności jest jednym z celów systemu emerytalnego.", True,
             why="Chroni przed wyczerpaniem oszczędności przy długim życiu."),
      ],
      mech=[
          KT("Cel jednostki czy państwa?",
             {"Cel jednostki": ["Wygładzanie konsumpcji w cyklu życia", "Ubezpieczenie od ryzyka długowieczności"],
              "Cel państwa": ["Ograniczanie ubóstwa osób starszych", "Redystrybucja dochodów"]},
             why="Barr i Diamond rozróżniają te perspektywy."),
          LN("Ułóż argument „liczy się produkcja”.",
             ["Emeryci konsumują dobra i usługi", "Dobra te wytwarzają pracujący w tym samym czasie", "W systemie kapitałowym emeryci sprzedają aktywa pracującym", "Przy mniejszej liczbie pracujących spada popyt na aktywa i ich cena", "Jedynie wzrost produkcji trwale poprawia sytuację emerytów"],
             why="Oba typy systemów zależą od przyszłej produkcji."),
          W("Rząd przechodzi na system kapitałowy, finansując składki przekazywane do funduszy nowym długiem publicznym. Co z oszczędnościami narodowymi?",
            "Mogą się nie zmienić – dług publiczny równoważy oszczędności w funduszach", "Na pewno silnie wzrosną", "Na pewno spadną do zera",
            why="To jeden z mitów opisanych przez Barra."),
          W("Który cel realizuje najniższa emerytura gwarantowana?",
            "Ograniczanie ubóstwa", "Wygładzanie konsumpcji", "Zwiększanie inflacji",
            why="Zapewnia minimalny dochód osobom o niskich zarobkach."),
          M("Które twierdzenia Barr uznaje za mity?",
            ["System kapitałowy rozwiązuje problem starzenia", "Systemy kapitałowe nie są narażone na ryzyko", "Systemy kapitałowe zawsze mają niższe koszty", "Liczy się przyszła produkcja"], [0, 1, 2],
            why="Ostatnie zdanie to prawda, nie mit."),
          PF("Według Barra zwiększenie produkcji jest ważniejsze niż sposób finansowania emerytur.", True,
             why="Emeryci konsumują przyszłą produkcję."),
      ],
      calc=[
          LB("Produkcja 1 000, pracujący 100, emeryci 50. Emeryci dostają 30% produkcji. Ile przypada na emeryta?",
             6, "1000*0.3/50", ["300 / 50 = 6"], unit="jedn."),
          LB("Ile przypada na pracującego (70% produkcji)?",
             7, "1000*0.7/100", ["700 / 100 = 7"], unit="jedn."),
          LB("Liczba emerytów rośnie do 70, produkcja i udział bez zmian. Ile przypada na emeryta?",
             4.29, "300/70", ["300 / 70 ≈ 4,29"], unit="jedn.", tol=0.01),
          LB("Ile wynosi relacja świadczenia emeryta do dochodu pracującego w przypadku 50 emerytów (6 / 7, %)?",
             85.71, "6/7*100", ["6 / 7 ≈ 85,71%"], unit="%", tol=0.02),
          LB("Opłaty funduszu 1% aktywów rocznie przez 40 lat. Jaka część kapitału zostaje względem funduszu bez opłat (%)?",
             66.9, "0.99**40*100", ["0,99⁴⁰ ≈ 0,669 → ok. 66,9%"], unit="%", tol=0.05),
          LB("Produkcja rośnie o 20%, emerytów 70, udział 30%. Ile przypada na emeryta?",
             5.14, "1200*0.3/70", ["360 / 70 ≈ 5,14"], unit="jedn.", tol=0.01),
      ],
      case=[
          PR("Polityk twierdzi: „Wystarczy przenieść wszystkie składki do prywatnych funduszy, a starzenie się społeczeństwa przestanie być problemem”.",
             W("Jaki błąd popełnia polityk według N. Barra?",
               "Pomija, że emeryci w obu systemach konsumują produkcję przyszłych pracujących", "Nie ma błędu", "Myli emerytury z zasiłkami",
               why="Zmiana finansowania nie zwiększa produkcji."),
             W("Co jeszcze pomija polityk?",
               "Koszt przejścia – trzeba nadal wypłacać obecne emerytury", "Brak emerytów", "Niskie koszty zarządzania",
               why="Podwójne obciążenie pokolenia przejściowego."),
             PF("Zwiększenie zatrudnienia osób starszych łagodzi skutki starzenia niezależnie od typu systemu.", True,
                why="Zwiększa produkcję i liczbę płacących składki."),
          ),
          PR("Kraj o słabych instytucjach finansowych, wysokiej inflacji i słabym nadzorze rynku rozważa obowiązkowe prywatne konta emerytalne.",
             W("Jaką uwagę zgłosiłby Barr?",
               "System kapitałowy wymaga silnych instytucji i nadzoru – inaczej jest ryzykowny", "Że to zawsze najlepsze rozwiązanie", "Że inflacja nie ma znaczenia",
               why="Zdolności instytucjonalne decydują o wyborze systemu."),
             W("Jakie ryzyko może zniszczyć oszczędności emerytalne?",
               "Wysoka inflacja i niestabilność rynku", "Zbyt niskie koszty", "Wysoki nadzór",
               why="Ryzyko rynkowe i inflacyjne."),
             PF("Systemy kapitałowe są narażone na ryzyko polityczne.", True,
                why="Np. przejęcia aktywów przez państwo."),
          ),
      ]),

    L(2, "System repartycyjny a kapitałowy i warunek Aarona",
      "Rozumieć różnicę między finansowaniem repartycyjnym (PAYG) a kapitałowym, warunek Aarona porównujący ich stopy zwrotu oraz koszty przejścia między systemami.",
      ["System repartycyjny (PAYG) a kapitałowy", "Warunek Aarona (paradoks Aarona–Samuelsona)"],
      [BARR, USUS],
      explain=[
          K("PAYG i system kapitałowy",
            "Repartycyjny (pay-as-you-go): bieżące składki pracujących finansują bieżące emerytury – „umowa międzypokoleniowa”. Kapitałowy: składki są inwestowane w aktywa, a emerytura pochodzi z zgromadzonego kapitału i jego zysków. W Polsce składka emerytalna wynosi 19,52% podstawy (połowę płaci pracownik, połowę pracodawca) i trafia głównie do FUS (konto i subkonto w ZUS); część kapitałowa to dziś głównie dobrowolne PPK, IKE i IKZE."),
          K("Warunek Aarona (1966)",
            "H. Aaron, rozwijając model P. Samuelsona (1958), pokazał, że w stanie ustalonym stopa zwrotu w systemie PAYG równa się tempu wzrostu sumy płac (wzrost liczby pracujących n + wzrost płac realnych g). System PAYG daje wyższą stopę zwrotu niż kapitałowy, gdy n + g > r (realna stopa procentowa) – i odwrotnie.",
            w="PAYG lepszy ⇔ n + g > r"),
          W("Liczba pracujących maleje o 1% rocznie, płace realne rosną o 2%, a realna stopa zwrotu z kapitału to 3%. Który system daje wyższą stopę zwrotu według warunku Aarona?",
            "Kapitałowy (r = 3% > n + g = 1%)", "Repartycyjny", "Oba równe",
            why="−1% + 2% = 1% < 3%."),
          K("Koszt przejścia",
            "Przechodząc z PAYG na system kapitałowy, pokolenie przejściowe musi jednocześnie finansować emerytury obecnych emerytów i oszczędzać na własne – „podwójne obciążenie”. Jeśli przejście finansuje się długiem, przyszłe pokolenia spłacają koszt. Dlatego wyższa stopa zwrotu z kapitału nie oznacza automatycznie zysku z reformy dla całego społeczeństwa."),
          K("Polska",
            "Reforma 1999 r. połączyła NDC w ZUS z obowiązkowym filarem kapitałowym (OFE). Od 2014 r. większość aktywów OFE przeniesiono do ZUS (subkonto), a składka do OFE stała się dobrowolna. W 2019 r. uruchomiono Pracownicze Plany Kapitałowe (PPK) z dopłatami państwa i pracodawców."),
          PF("W systemie PAYG emerytury bieżących emerytów są finansowane ze składek bieżących pracujących.", True,
             why="To istota finansowania repartycyjnego."),
      ],
      mech=[
          KT("PAYG czy kapitałowy?",
             {"Repartycyjny (PAYG)": ["Składki pracujących od razu wypłacane emerytom", "Stopa zwrotu zależy od wzrostu sumy płac"],
              "Kapitałowy": ["Składki inwestowane w akcje i obligacje", "Stopa zwrotu zależy od rynków finansowych", "Indywidualne konto w PPK"]},
             why="Różnią się sposobem finansowania i źródłem zwrotu."),
          LN("Ułóż łańcuch wpływu starzenia na system PAYG.",
             ["Spada liczba pracujących", "Rośnie liczba emerytów", "Spada tempo wzrostu sumy płac (n + g)", "Spada implicytna stopa zwrotu w PAYG", "Trzeba podnieść składki, obniżyć świadczenia lub wydłużyć pracę"],
             why="Starzenie się obniża rentowność PAYG."),
          W("Co jest głównym problemem przejścia z PAYG na system kapitałowy?",
            "Podwójne obciążenie pokolenia przejściowego", "Brak kont bankowych", "Zbyt wysoka dzietność",
            why="Trzeba płacić obecnym emerytom i oszczędzać na własną emeryturę."),
          W("Dlaczego system PAYG był atrakcyjny w okresie wyżu demograficznego i szybkiego wzrostu płac?",
            "Bo n + g było wysokie – stopa zwrotu PAYG przewyższała r", "Bo nie było emerytów", "Bo stopy procentowe były ujemne",
            why="Wzrost liczby pracujących i płac podnosił zwrot."),
          M("Od czego zależy stopa zwrotu w systemie PAYG?",
            ["Wzrostu liczby pracujących", "Wzrostu płac realnych", "Relacji emerytów do pracujących", "Kursu akcji na giełdzie"], [0, 1, 2],
            why="Giełda wpływa na system kapitałowy."),
          PF("Składka emerytalna w Polsce wynosi 19,52% podstawy wymiaru.", True,
             why="Finansowana po połowie przez pracownika i pracodawcę."),
      ],
      calc=[
          LB("n = 0,5%, g = 2%. Ile wynosi stopa zwrotu PAYG w stanie ustalonym (%)?",
             2.5, "0.5+2", ["0,5 + 2 = 2,5%"], unit="%", tol=0.001),
          LB("n = −1%, g = 2,5%. Ile wynosi stopa zwrotu PAYG (%)?",
             1.5, "-1+2.5", ["−1 + 2,5 = 1,5%"], unit="%", tol=0.001),
          LB("Płaca 9 420 zł, składka 19,52%. Ile wynosi miesięczna składka emerytalna (zł)?",
             1838.78, "9420*0.1952", ["9 420 · 0,1952 ≈ 1 838,78 zł"], unit="zł", tol=0.01),
          LB("Ile z tej składki płaci pracownik (połowa) (zł)?",
             919.39, "9420*0.0976", ["9 420 · 0,0976 ≈ 919,39 zł"], unit="zł", tol=0.01),
          LB("Kapitał 100 tys. zł rośnie 40 lat: w PAYG 1,5% rocznie, w funduszu 3% (realnie). Ile razy większy jest kapitał w funduszu?",
             1.8, "(1.03/1.015)**40", ["1,03⁴⁰ ≈ 3,262; 1,015⁴⁰ ≈ 1,814; 3,262 / 1,814 ≈ 1,80"], unit="razy", tol=0.01),
          LB("Wydatki na emerytury 400 mld zł; pokolenie przejściowe ma też oszczędzić 100 mld zł. O ile procent rośnie jego obciążenie?",
             25, "100/400*100", ["100 / 400 = 25%"], unit="%"),
      ],
      case=[
          PR("Kraj o szybkim wzroście ludności i płac (n = 2%, g = 3%) i realnej stopie procentowej 3% rozważa przejście na system kapitałowy.",
             W("Co mówi warunek Aarona?",
               "PAYG daje wyższy zwrot (5% > 3%)", "System kapitałowy daje wyższy zwrot", "Oba są równe",
               why="n + g = 5% > r = 3%."),
             W("Co zmieni się, gdy dzietność spadnie, a n stanie się ujemne?",
               "Przewaga PAYG zmaleje lub zniknie", "PAYG stanie się jeszcze bardziej opłacalny", "Nic",
               why="Spada n + g, a więc zwrot z PAYG."),
             PF("Warunek Aarona porównuje stopy zwrotu, ale nie uwzględnia kosztów przejścia.", True,
                why="Koszt przejścia trzeba ocenić osobno."),
          ),
          PR("W Polsce w 2014 r. większość aktywów OFE przeniesiono do ZUS i zapisano na subkontach. Zwolennicy twierdzili, że zmniejsza to dług publiczny; krytycy – że zamienia jawny dług na ukryte zobowiązania emerytalne.",
             W("Dlaczego dług jawny spadł?",
               "Obligacje skarbowe z OFE zostały umorzone po przeniesieniu do ZUS", "Bo wzrosły podatki", "Bo spadły emerytury",
               why="Państwo przejęło własne obligacje."),
             W("Co oznacza „ukryte zobowiązanie”?",
               "Obietnicę wypłaty przyszłych emerytur z subkont, niewykazywaną jako dług", "Brak zobowiązań", "Zaległe podatki",
               why="Zobowiązania emerytalne nie są długiem w statystyce."),
             PF("Przeniesienie aktywów nie zmieniło liczby przyszłych emerytów.", True,
                why="Zmieniło sposób finansowania, nie demografię."),
          ),
      ]),

    L(3, "Formuły emerytalne: DB, DC i NDC",
      "Rozumieć różnicę między systemem zdefiniowanego świadczenia (DB), zdefiniowanej składki (DC) i nominalnie zdefiniowanej składki (NDC) – kto ponosi ryzyko i jak każda formuła reaguje na starzenie się.",
      ["DB, DC i NDC – formuły emerytalne"],
      [BARR, UEFUS],
      explain=[
          K("DB – zdefiniowane świadczenie",
            "Wysokość emerytury wynika z formuły: np. 1,3% płacy za każdy rok pracy × liczba lat × podstawa (np. średnia z najlepszych lat). Ryzyko demograficzne i finansowe ponosi płatnik (państwo, pracodawca) – przy starzeniu się trzeba podnosić składki lub zmieniać formułę. Taki był polski system przed 1999 r.",
            w="E = a · lata · podstawa"),
          K("DC – zdefiniowana składka",
            "Ustalona jest składka, a emerytura zależy od zgromadzonego kapitału i jego zysków (np. IKE, PPK, fundusze). Ryzyko inwestycyjne i długowieczności ponosi uczestnik (jeśli nie kupi renty dożywotniej). Kapitał jest rzeczywiście inwestowany."),
          W("Kto ponosi ryzyko złych wyników inwestycyjnych w systemie DC?",
            "Uczestnik (przyszły emeryt)", "Państwo", "Pracodawca po przejściu na emeryturę",
            why="Emerytura zależy od faktycznego kapitału."),
          K("NDC – nominalnie zdefiniowana składka",
            "Hybryda: składki są zapisywane na indywidualnych kontach i waloryzowane według wskaźnika (np. wzrostu sumy płac), ale pieniądze nie są inwestowane – finansują bieżące emerytury (PAYG). Emerytura = zwaloryzowany kapitał / dalsze trwanie życia w wieku przejścia na emeryturę. Polska wprowadziła NDC w 1999 r. (podobnie Szwecja, Włochy, Łotwa)."),
          K("Reakcja na starzenie",
            "W DB wydatki rosną automatycznie – dostosowanie wymaga decyzji politycznych. W DC i NDC dłuższe życie automatycznie obniża miesięczne świadczenie (większy dzielnik), a dłuższa praca je podnosi. Dzięki temu system NDC jest bardziej stabilny finansowo, ale stopy zastąpienia spadają."),
          PF("W systemie NDC składki są inwestowane na giełdzie.", False,
             why="Kapitał jest zapisywany na kontach i waloryzowany, ale finansuje bieżące emerytury."),
      ],
      mech=[
          KT("DB, DC czy NDC?",
             {"DB": ["Emerytura = 1,3% podstawy za każdy rok pracy", "Ryzyko demograficzne ponosi płatnik"],
              "DC": ["Emerytura z kapitału w funduszu inwestycyjnym", "Ryzyko inwestycyjne ponosi uczestnik"],
              "NDC": ["Konto w ZUS waloryzowane wzrostem sumy płac", "Kapitał podzielony przez dalsze trwanie życia"]},
             why="Trzy podstawowe formuły emerytalne."),
          LN("Ułóż powstawanie emerytury w systemie NDC.",
             ["Składka zapisywana na indywidualnym koncie", "Coroczna waloryzacja zapisanych składek", "Przejście na emeryturę w wybranym wieku", "Podział kapitału przez dalsze trwanie życia", "Wypłata miesięcznej emerytury"],
             why="Składki są „wirtualne” – finansują bieżących emerytów."),
          W("Ludzie żyją dłużej. Jak automatycznie reaguje system NDC?",
            "Obniża miesięczne emerytury nowych emerytów (większy dzielnik)", "Podnosi składki", "Nie reaguje",
            why="Kapitał dzieli się przez dłuższe trwanie życia."),
          W("Dlaczego w DB starzenie się wymaga decyzji politycznych?",
            "Formuła gwarantuje świadczenie niezależnie od liczby płacących", "Bo składki są zbyt niskie z definicji", "Bo nie ma emerytów",
            why="Rosnące wydatki trzeba sfinansować zmianą parametrów."),
          M("Które kraje stosują NDC?",
            ["Polska", "Szwecja", "Włochy", "Stany Zjednoczone (Social Security)"], [0, 1, 2],
            why="Social Security w USA to system DB."),
          PF("W systemie NDC dłuższa praca podnosi emeryturę na dwa sposoby: większy kapitał i krótszy okres wypłaty.", True,
             why="Rośnie licznik, maleje mianownik."),
      ],
      calc=[
          LB("DB: 1,3% podstawy za rok, 35 lat pracy, podstawa 8 000 zł. Ile wynosi emerytura (zł)?",
             3640, "0.013*35*8000", ["0,013 · 35 · 8 000 = 3 640 zł"], unit="zł"),
          LB("Jaka to stopa zastąpienia (% podstawy)?",
             45.5, "0.013*35*100", ["1,3% · 35 = 45,5%"], unit="%", tol=0.001),
          LB("NDC: kapitał 600 000 zł, dalsze trwanie życia 268,9 mies. Ile wynosi emerytura (zł)?",
             2231.31, "600000/268.9", ["600 000 / 268,9 ≈ 2 231,31 zł"], unit="zł", tol=0.02),
          LB("Ten sam kapitał przy 222,7 mies. (wiek 65). Ile wynosi emerytura (zł)?",
             2694.21, "600000/222.7", ["600 000 / 222,7 ≈ 2 694,21 zł"], unit="zł", tol=0.02),
          LB("DC: 500 zł miesięcznie przez 30 lat bez zysków. Ile wynosi kapitał (zł)?",
             180000, "500*12*30", ["500 · 360 = 180 000 zł"], unit="zł"),
          LB("Kapitał DC 400 tys. zł przy realnym zwrocie 6% rocznie przez 10 lat. Ile wyniesie (zł)?",
             716339.08, "400000*1.06**10", ["400 000 · 1,06¹⁰ ≈ 716 339 zł"], unit="zł", tol=1),
      ],
      case=[
          PR("Pan Jan pracował 40 lat. W starym systemie DB (1,3% za rok, podstawa 7 000 zł) dostałby 3 640 zł. W NDC zgromadził zwaloryzowany kapitał 650 000 zł i przechodzi na emeryturę w wieku 65 lat (222,7 mies.).",
             W("Ile wynosi jego emerytura w NDC?",
               "Ok. 2 919 zł", "Ok. 3 640 zł", "Ok. 1 500 zł",
               why="650 000 / 222,7 ≈ 2 918,72 zł."),
             W("Dlaczego NDC daje mniej niż stara formuła?",
               "Stara formuła DB była hojniejsza i nie uwzględniała automatycznie długości życia", "Bo Jan pracował krócej", "Bo NDC jest inwestowany",
               why="NDC dopasowuje świadczenie do kapitału i trwania życia."),
             PF("Gdyby pan Jan pracował dłużej, jego emerytura w NDC wzrosłaby.", True,
                why="Większy kapitał i mniejszy dzielnik."),
          ),
          PR("Pani Ewa oszczędza w PPK (DC). W 2022 r. jej fundusz stracił 15%, a rok później zyskał 20%.",
             W("Kto ponosi skutki tych wahań?",
               "Pani Ewa – uczestniczka systemu DC", "Państwo", "Pracodawca",
               why="Wynik inwestycyjny przekłada się na jej kapitał."),
             W("Ile wynosi łączna zmiana kapitału w obu latach?",
               "+2%", "+5%", "−15%",
               why="0,85 · 1,2 = 1,02."),
             PF("Fundusze zdefiniowanej daty (PPK) zmniejszają udział akcji wraz ze zbliżaniem się do emerytury.", True,
                why="Ogranicza to ryzyko tuż przed wypłatą."),
          ),
      ]),

    L(4, "Obliczanie emerytury w Polsce, waloryzacja i emerytura minimalna",
      "Umieć obliczyć emeryturę w polskim systemie (konto, subkonto, kapitał początkowy, tablice GUS), rozumieć waloryzację składek i świadczeń oraz zasady emerytury minimalnej (stan na 10.2026).",
      ["Obliczanie emerytury w polskim systemie", "Waloryzacja i emerytura minimalna"],
      [UEFUS, ZUSEM, INFW, INFT],
      explain=[
          K("Wzór",
            "Emerytura dla osób urodzonych po 1948 r. = (kapitał początkowy + zwaloryzowane składki na koncie + zwaloryzowane środki na subkoncie) / średnie dalsze trwanie życia w wieku przejścia na emeryturę (w miesiącach). Kapitał początkowy to przeliczenie okresów pracy sprzed 1999 r. Tablica GUS obowiązująca od 1.04.2026 do 31.03.2027: 60 lat – 268,9 mies., 65 lat – 222,7 mies.",
            w="E = (KP + K + S) / sdtż"),
          K("Konto i subkonto",
            "Ze składki 19,52% (u osób nieprzekazujących części do OFE) 12,22 pkt proc. trafia na konto, a 7,30 pkt proc. na subkonto w ZUS. Konto jest waloryzowane rocznie wskaźnikiem odpowiadającym wzrostowi sumy składek (płac i zatrudnienia), subkonto – według średniego wzrostu nominalnego PKB z 5 lat. Powszechny wiek emerytalny: 60 lat (kobiety) i 65 lat (mężczyźni)."),
          W("Co dzieje się z emeryturą, gdy ktoś przejdzie na emeryturę 5 lat później?",
            "Rośnie – wyższy kapitał i krótsze dalsze trwanie życia", "Maleje", "Nie zmienia się",
            why="Rośnie licznik, maleje mianownik."),
          K("Waloryzacja świadczeń",
            "Emerytury i renty są waloryzowane co roku od 1 marca wskaźnikiem równym co najmniej inflacji emeryckiej (lub ogólnej) plus co najmniej 20% realnego wzrostu przeciętnego wynagrodzenia. Od 1.03.2026 wskaźnik wyniósł 105,3% (wzrost o 5,3%)."),
          K("Emerytura minimalna",
            "Państwo gwarantuje najniższą emeryturę, jeśli ubezpieczony ma okres składkowy i nieskładkowy co najmniej 20 lat (kobiety) lub 25 lat (mężczyźni) i osiągnął wiek emerytalny. Od 1.03.2026 wynosi ok. 1 978,49 zł brutto (wcześniej 1 878,91 zł). Jeśli emerytura z kapitału jest niższa, ZUS dopłaca do minimum."),
          PF("Warunkiem emerytury minimalnej dla mężczyzny jest 25 lat okresów składkowych i nieskładkowych.", True,
             why="Dla kobiet 20 lat."),
      ],
      mech=[
          KT("Co podnosi, a co obniża emeryturę w ZUS?",
             {"Podnosi": ["Dłuższa praca przed przejściem na emeryturę", "Wyższe zarobki i składki", "Wysoka waloryzacja kapitału"],
              "Obniża": ["Wzrost dalszego trwania życia w tablicach GUS", "Długie okresy pracy bez składek (np. w szarej strefie)"]},
             why="Licznik i mianownik wzoru."),
          LN("Ułóż etapy obliczenia emerytury przez ZUS.",
             ["Ustalenie kapitału początkowego (praca przed 1999 r.)", "Zsumowanie zwaloryzowanych składek na koncie", "Dodanie zwaloryzowanych środków z subkonta", "Podział przez średnie dalsze trwanie życia z tablicy GUS", "Ewentualna dopłata do emerytury minimalnej"],
             why="Kolejność wynika z art. 26 ustawy o emeryturach i rentach z FUS."),
          W("Emerytura z kapitału wynosi 1 500 zł, kobieta ma 22 lata stażu i 60 lat. Co się stanie?",
            "ZUS podwyższy świadczenie do emerytury minimalnej", "Otrzyma 1 500 zł", "Nie dostanie emerytury",
            why="Spełnia warunek 20 lat stażu."),
          W("Co oznacza waloryzacja 5,3% od 1.03.2026?",
            "Emerytury wzrosły o 5,3% od marca 2026 r.", "Emerytury spadły o 5,3%", "Składki wzrosły o 5,3%",
            why="Wskaźnik waloryzacji 105,3%."),
          M("Z czego składa się podstawa obliczenia emerytury w ZUS?",
            ["Kapitał początkowy", "Składki na koncie", "Środki na subkoncie", "Oszczędności na lokatach bankowych"], [0, 1, 2],
            why="Lokaty są poza systemem ZUS."),
          PF("Tablice GUS stosowane przez ZUS są wspólne dla kobiet i mężczyzn.", True,
             why="Ustawa wymaga tablic uniseks."),
      ],
      calc=[
          LB("Kapitał początkowy 120 tys. zł, konto 380 tys. zł, subkonto 100 tys. zł, sdtż 268,9 mies. Ile wynosi emerytura (zł)?",
             2231.31, "(120000+380000+100000)/268.9", ["600 000 / 268,9 ≈ 2 231,31 zł"], unit="zł", tol=0.02),
          LB("Ta sama osoba pracuje do 65 lat i kapitał rośnie do 760 tys. zł (sdtż 222,7 mies.). Ile wynosi emerytura (zł)?",
             3412.66, "760000/222.7", ["760 000 / 222,7 ≈ 3 412,66 zł"], unit="zł", tol=0.02),
          LB("Pensja 8 000 zł, na konto trafia 12,22%. Ile zł miesięcznie (zł)?",
             977.6, "8000*0.1222", ["8 000 · 0,1222 = 977,60 zł"], unit="zł", tol=0.01),
          LB("Ile trafia na subkonto (7,30%) (zł)?",
             584, "8000*0.073", ["8 000 · 0,073 = 584 zł"], unit="zł", tol=0.01),
          LB("Emerytura minimalna 1 878,91 zł zwaloryzowana o 5,3%. Ile wynosi (zł)?",
             1978.49, "1878.91*1.053", ["1 878,91 · 1,053 ≈ 1 978,49 zł"], unit="zł", tol=0.01),
          LB("Emerytura 3 000 zł brutto po waloryzacji 5,3%. Ile wynosi (zł)?",
             3159, "3000*1.053", ["3 000 · 1,053 = 3 159 zł"], unit="zł"),
      ],
      case=[
          PR("Pani Maria (60 lat) ma kapitał 540 000 zł. Rozważa przejście na emeryturę teraz (sdtż 268,9 mies.) albo pracę jeszcze 3 lata, co zwiększy kapitał do 640 000 zł (przyjmijmy sdtż w wieku 63 lat 246,0 mies. – dane umowne).",
             W("Ile wyniesie emerytura teraz?",
               "Ok. 2 008 zł", "Ok. 2 602 zł", "Ok. 1 500 zł",
               why="540 000 / 268,9 ≈ 2 008,18 zł."),
             W("Ile wyniesie emerytura po 3 latach pracy?",
               "Ok. 2 602 zł", "Ok. 2 008 zł", "Ok. 3 500 zł",
               why="640 000 / 246,0 ≈ 2 601,63 zł."),
             PF("Trzy lata dłuższej pracy podnoszą emeryturę o blisko 30%.", True,
                why="2 601,63 / 2 008,18 ≈ 1,296."),
          ),
          PR("Pan Adam (65 lat) ma 23 lata stażu i kapitał, z którego wychodzi 1 300 zł emerytury. Kolega mówi mu, że i tak dostanie minimum.",
             W("Czy pan Adam ma prawo do dopłaty do emerytury minimalnej?",
               "Nie – mężczyzna potrzebuje 25 lat stażu", "Tak, zawsze", "Tak, bo ma 65 lat",
               why="Nie spełnia warunku stażu."),
             W("Co mógłby zrobić, by zyskać prawo do minimum?",
               "Pracować jeszcze 2 lata, by uzupełnić staż do 25 lat", "Przejść na emeryturę wcześniej", "Nic nie można zrobić",
               why="Dodatkowe lata pracy uzupełnią staż."),
             PF("Dalsza praca podniosłaby także jego kapitał emerytalny.", True,
                why="Wpływałyby nowe składki."),
          ),
      ]),

    L(5, "Ryzyko długowieczności, renta dożywotnia i wiek emerytalny",
      "Rozumieć ryzyko długowieczności i rolę renty dożywotniej, a także argumenty za powiązaniem wieku emerytalnego z długością życia – na przykładach z Polski i Europy.",
      ["Ryzyko długowieczności i renta dożywotnia", "Wiek emerytalny a długość życia"],
      [BARR, AGEREP, GUSPWL, INFT],
      explain=[
          K("Ryzyko długowieczności",
            "Nikt nie wie, jak długo będzie żył. Kto oszczędza sam, ryzykuje, że wyczerpie oszczędności przed śmiercią (albo zostawi niewykorzystane środki, ograniczając konsumpcję). Rozwiązaniem jest renta dożywotnia (annuitet): wymiana kapitału na świadczenie wypłacane do końca życia – ryzyko łączy się w dużej grupie (osoby żyjące krócej „finansują” żyjące dłużej)."),
          K("Renta dożywotnia",
            "Wysokość renty zależy od kapitału, oczekiwanego trwania życia i stopy procentowej: przy dłuższym życiu i niższych stopach renta jest niższa. Problemy rynku prywatnego: selekcja negatywna (renty kupują głównie osoby spodziewające się długiego życia), ryzyko inflacji, wysokie marże. Emerytura z ZUS jest rentą dożywotnią waloryzowaną co roku.",
            w="renta = K · r / (1 − (1 + r)⁻ⁿ)"),
          W("Dlaczego prywatne renty dożywotnie są często drogie?",
            "Selekcja negatywna – kupują je głównie osoby oczekujące długiego życia", "Bo nikt ich nie kupuje", "Bo są waloryzowane o 50% rocznie",
            why="Ubezpieczyciel zakłada dłuższe trwanie życia nabywców."),
          K("Wiek emerytalny a długość życia",
            "Gdy rośnie trwanie życia, a wiek emerytalny się nie zmienia, wydłuża się okres pobierania emerytury, a w NDC spadają świadczenia. Część krajów (np. Dania, Holandia, Finlandia, Portugalia) powiązała wiek emerytalny lub świadczenia z oczekiwaną długością życia. W Polsce wiek 67 lat wprowadzony w 2013 r. przywrócono w 2017 r. do 60/65 lat."),
          K("Skutki niskiego wieku emerytalnego w NDC",
            "W Polsce kobiety przechodzą na emeryturę w wieku 60 lat, a w tym wieku mają przed sobą średnio 24,7 roku (dane za 2025 r.) – długi okres wypłaty oznacza niski dzielnik i niską emeryturę. Krótszy okres składkowy i dłuższy okres wypłaty pogłębiają lukę emerytalną kobiet."),
          PF("Emerytura z ZUS chroni przed ryzykiem długowieczności, bo jest wypłacana dożywotnio.", True,
             why="To renta dożywotnia waloryzowana co roku."),
      ],
      mech=[
          KT("Co obniża, a co podnosi miesięczną rentę dożywotnią z danego kapitału?",
             {"Obniża rentę": ["Dłuższe oczekiwane trwanie życia", "Niższe stopy procentowe", "Wcześniejszy wiek zakupu renty"],
              "Podnosi rentę": ["Wyższe stopy procentowe", "Późniejszy wiek przejścia na emeryturę"]},
             why="Zależność od n i r we wzorze renty."),
          LN("Ułóż argumentację za powiązaniem wieku emerytalnego z długością życia.",
             ["Trwanie życia stale rośnie", "Przy stałym wieku emerytalnym wydłuża się okres wypłat", "W NDC spadają miesięczne emerytury, w DB rosną wydatki", "Powiązanie wieku z długością życia stabilizuje relację pracy do emerytury", "Decyzja zostaje „odpolityczniona” – działa automatycznie"],
             why="Automatyczne mechanizmy stabilizują system."),
          W("Pan Piotr ma 300 000 zł oszczędności i obawia się, że wyda je za wcześnie. Co go chroni przed tym ryzykiem?",
            "Zakup renty dożywotniej", "Trzymanie gotówki w domu", "Wydanie wszystkiego od razu",
            why="Renta wypłaca świadczenie do końca życia."),
          W("Dlaczego niższy wiek emerytalny kobiet obniża ich emerytury w NDC?",
            "Krótszy okres składek i dłuższy okres wypłaty", "Bo kobiety płacą niższą stawkę składki", "Bo tablice są inne dla kobiet",
            why="Mniejszy kapitał dzielony przez więcej miesięcy."),
          M("Jakie są problemy prywatnego rynku rent dożywotnich?",
            ["Selekcja negatywna", "Ryzyko inflacji", "Wysokie marże", "Brak ryzyka długowieczności"], [0, 1, 2],
            why="Renty właśnie ubezpieczają od długowieczności."),
          PF("W Polsce wiek emerytalny 67 lat obowiązywał przejściowo po reformie z 2013 r., a w 2017 r. przywrócono 60/65 lat.", True,
             why="Ustawa z 2016 r. obniżyła wiek od 1.10.2017 r."),
      ],
      calc=[
          LB("Kapitał 500 000 zł, stopa 3%, renta płatna przez 20 lat (roczna). Ile wynosi roczna renta (zł)?",
             33607.85, "500000*0.03/(1-1.03**-20)", ["500 000 · 0,03 / (1 − 1,03⁻²⁰) ≈ 33 607,85 zł"], unit="zł", tol=1),
          LB("Bez odsetek (r = 0) i przez 20 lat – ile wynosi roczna renta (zł)?",
             25000, "500000/20", ["500 000 / 20 = 25 000 zł"], unit="zł"),
          LB("Kobieta w wieku 60 lat ma przed sobą 24,7 roku. Ile to miesięcy?",
             296.4, "24.7*12", ["24,7 · 12 = 296,4"], unit="mies.", tol=0.01),
          LB("Kapitał 500 000 zł podzielony przez 268,9 mies. Ile wynosi emerytura (zł)?",
             1859.43, "500000/268.9", ["500 000 / 268,9 ≈ 1 859,43 zł"], unit="zł", tol=0.02),
          LB("Ten sam kapitał przez 222,7 mies. O ile procent wyższa jest emerytura?",
             20.75, "(268.9/222.7-1)*100", ["268,9 / 222,7 ≈ 1,2075 → +20,75%"], unit="%", tol=0.02),
          LB("Emerytura minimalna 1 978,49 zł miesięcznie. Ile rocznie (12 miesięcy, zł)?",
             23741.88, "1978.49*12", ["1 978,49 · 12 = 23 741,88 zł"], unit="zł", tol=0.01),
      ],
      case=[
          PR("Kraj X zapisał w ustawie, że wiek emerytalny będzie rósł o 2/3 każdego roku wzrostu oczekiwanego dalszego trwania życia 60-latków. Związki zawodowe protestują, wskazując na ciężką pracę fizyczną części zawodów.",
             W("Jaki jest cel takiego mechanizmu?",
               "Utrzymanie stałej relacji okresu pracy do okresu emerytury", "Obniżenie emerytur do zera", "Zwiększenie bezrobocia",
               why="Część zysku z dłuższego życia przeznacza się na pracę."),
             W("Jakie rozwiązanie odpowiada na zarzut związków?",
               "Świadczenia pomostowe lub wcześniejsza emerytura dla prac w szczególnych warunkach", "Zniesienie emerytur", "Podwyżka wieku dla wszystkich o 10 lat",
               why="Uwzględnia zróżnicowanie zdolności do pracy."),
             PF("Wzrost trwania życia o 3 lata podniósłby wiek emerytalny w kraju X o 2 lata.", True,
                why="3 · 2/3 = 2 lata."),
          ),
          PR("Pani Zofia (65 lat) wypłaciła 400 000 zł z IKE i wydaje 2 500 zł miesięcznie, licząc, że pieniądze „wystarczą”.",
             W("Na ile lat wystarczą oszczędności przy zerowych odsetkach?",
               "Ok. 13,3 roku", "Ok. 20 lat", "Ok. 8 lat",
               why="400 000 / 30 000 ≈ 13,3 roku."),
             W("Jakie ryzyko ponosi pani Zofia?",
               "Ryzyko długowieczności – może żyć dłużej niż wystarczą środki", "Ryzyko kursowe", "Ryzyko braku waloryzacji ZUS",
               why="Przeciętna 65-latka ma przed sobą ok. 20 lat życia."),
             PF("Renta dożywotnia mogłaby zabezpieczyć ją przed wyczerpaniem środków.", True,
                why="Wypłaca świadczenie do końca życia."),
          ),
      ]),
]
