# -*- coding: utf-8 -*-
# Zrozumienie – Demografia / Instytucje
D = "2026-10-08"
IOMW = S("IOM – Who we are", "https://www.iom.int/who-we-are", D)
ILOM = S("ILO – Labour migration", "https://www.ilo.org/topics/labour-migration", D)
UNFPA = S("UNFPA – Fundusz Ludnościowy ONZ", "https://www.unfpa.org/", D)
EUAAH = S("EUAA – Agencja Unii Europejskiej ds. Azylu", "https://euaa.europa.eu/", D)
FRTX = S("Frontex – Europejska Agencja Straży Granicznej i Przybrzeżnej", "https://www.frontex.europa.eu/", D)
ECHA = S("Komisja Europejska – Migration and asylum", "https://home-affairs.ec.europa.eu/policies/migration-and-asylum_en", D)
UDSC = S("gov.pl – Urząd do Spraw Cudzoziemców", "https://www.gov.pl/web/udsc", D)
INFPAKT = S("infor.pl – Co zakłada pakt o migracji i azylu (2026)", "https://www.infor.pl/prawo/nowosci-prawne/7603725,co-zaklada-pakt-o-migracji-i-azylu-z-czego-polska-zostala-czasowo-zwolniona.html", D)
EUAA = S("EUAA – Przedłużenie tymczasowej ochrony do marca 2027", "https://dip.euaa.europa.eu/node/802", D)

LESSONS = [
    L(1, "Organizacje międzynarodowe zajmujące się migracją i ludnością",
      "Rozróżniać zadania IOM, UNHCR, ILO i UNFPA oraz rozumieć, jaką rolę odgrywają w zarządzaniu migracjami, ochronie uchodźców i polityce ludnościowej.",
      ["Międzynarodowe instytucje ds. migracji"],
      [IOMW, ILOM, UNFPA],
      explain=[
          K("IOM",
            "Międzynarodowa Organizacja ds. Migracji (założona w 1951 r., od 2016 r. organizacja powiązana z ONZ) – wspiera państwa w zarządzaniu migracjami: pomoc migrantom w kryzysach, dobrowolne powroty i reintegracja, przeciwdziałanie handlowi ludźmi, badania i dane o migracjach (m.in. raport World Migration Report)."),
          K("UNHCR",
            "Wysoki Komisarz ONZ ds. Uchodźców (od 1950 r.) – chroni uchodźców i osoby przesiedlone, czuwa nad stosowaniem Konwencji genewskiej z 1951 r., udziela pomocy humanitarnej i szuka trwałych rozwiązań: dobrowolnego powrotu, integracji lokalnej lub przesiedlenia do państw trzecich."),
          W("Która organizacja czuwa nad przestrzeganiem Konwencji dotyczącej statusu uchodźców?",
            "UNHCR", "ILO", "UNFPA",
            why="To główny mandat Wysokiego Komisarza ONZ ds. Uchodźców."),
          K("ILO i UNFPA",
            "Międzynarodowa Organizacja Pracy (1919) – standardy pracy, w tym konwencje o pracownikach migrujących (nr 97 z 1949 r. i nr 143 z 1975 r.), ochrona przed wyzyskiem i godna praca. Fundusz Ludnościowy ONZ (UNFPA, 1969) – zdrowie reprodukcyjne, dane o ludności (wsparcie spisów), polityka ludnościowa."),
          K("Podział ról",
            "IOM – zarządzanie migracjami i pomoc migrantom; UNHCR – ochrona uchodźców; ILO – prawa pracownicze migrantów; UNFPA – ludność i zdrowie reprodukcyjne. Organizacje współpracują, np. przy kryzysach humanitarnych (wojna w Ukrainie, konflikty w Afryce)."),
          PF("IOM od 2016 r. jest organizacją powiązaną z ONZ.", True,
             why="Wcześniej działała poza systemem ONZ."),
      ],
      mech=[
          KT("Która organizacja?",
             {"IOM": ["Organizacja dobrowolnych powrotów migrantów do kraju pochodzenia", "Przeciwdziałanie handlowi ludźmi"],
              "UNHCR": ["Ochrona uchodźców i przesiedlenia do państw trzecich"],
              "ILO": ["Konwencje o prawach pracowników migrujących"],
              "UNFPA": ["Wsparcie spisów powszechnych i zdrowia reprodukcyjnego"]},
             why="Różne mandaty organizacji międzynarodowych."),
          LN("Ułóż organizacje według roku założenia.",
             ["ILO (1919)", "UNHCR (1950)", "IOM (1951)", "UNFPA (1969)"],
             why="Chronologia instytucji międzynarodowych."),
          W("Kraj chce zorganizować bezpieczny powrót migrantów, którym odmówiono ochrony. Z którą organizacją najczęściej współpracuje?",
            "IOM", "UNFPA", "ILO",
            why="IOM prowadzi programy dobrowolnych powrotów."),
          W("Jakie trwałe rozwiązania dla uchodźców wskazuje UNHCR?",
            "Dobrowolny powrót, integracja lokalna, przesiedlenie", "Wyłącznie obozy na zawsze", "Deportacja do kraju prześladowań",
            why="Trzy trwałe rozwiązania UNHCR."),
          M("Czym zajmuje się ILO w kontekście migracji?",
            ["Standardami pracy migrantów", "Ochroną przed wyzyskiem", "Godną pracą", "Emisją walut"], [0, 1, 2],
            why="ILO nie zajmuje się walutami."),
          PF("UNFPA zajmuje się m.in. wsparciem spisów ludności.", True,
             why="Dane o ludności to część jej mandatu."),
      ],
      calc=[
          LB("Ile lat dzieli założenie ILO (1919) od założenia UNHCR (1950)?",
             31, "1950-1919", ["1950 − 1919 = 31"], unit="lat"),
          LB("Ile lat działała IOM przed włączeniem do systemu ONZ (1951–2016)?",
             65, "2016-1951", ["2016 − 1951 = 65"], unit="lat"),
          LB("Ile lat dzieli konwencje ILO nr 97 (1949) i nr 143 (1975)?",
             26, "1975-1949", ["1975 − 1949 = 26"], unit="lat"),
          LB("Program powrotów: 2 400 wniosków, 1 800 zrealizowanych powrotów. Jaki odsetek (%)?",
             75, "1800/2400*100", ["1 800 / 2 400 = 75%"], unit="%"),
          LB("Budżet operacji humanitarnej 120 mln USD dla 400 tys. osób. Ile przypada na osobę (USD)?",
             300, "120e6/400000", ["120 mln / 400 tys. = 300 USD"], unit="USD"),
          LB("Ile lat dzieli założenie UNFPA (1969) od 2026 r.?",
             57, "2026-1969", ["2026 − 1969 = 57"], unit="lat"),
      ],
      case=[
          PR("W kraju sąsiadującym ze strefą wojny pojawiają się setki tysięcy uciekinierów. Rząd prosi o pomoc w rejestracji, zakwaterowaniu, ochronie przed handlem ludźmi i ocenie, kto potrzebuje ochrony międzynarodowej.",
             W("Która organizacja odpowiada głównie za ochronę uchodźców?",
               "UNHCR", "UNFPA", "ILO",
               why="Mandat ochrony uchodźców."),
             W("Która organizacja pomoże w przeciwdziałaniu handlowi ludźmi i logistyce migracji?",
               "IOM", "ILO", "UNFPA",
               why="IOM prowadzi takie programy."),
             PF("W kryzysach humanitarnych organizacje międzynarodowe często współpracują.", True,
                why="Mają uzupełniające się mandaty."),
          ),
          PR("Pracownicy migrujący na budowach w pewnym kraju skarżą się na zatrzymywanie paszportów przez pracodawców i brak wypłat.",
             W("Które standardy międzynarodowe dotyczą tej sytuacji?",
               "Konwencje ILO o pracownikach migrujących i pracy przymusowej", "Konwencja genewska o uchodźcach", "Statut UNFPA",
               why="To kwestia praw pracowniczych."),
             W("Jak nazwać zatrzymywanie paszportów, by wymusić pracę?",
               "Przejawem pracy przymusowej", "Normalną praktyką kadrową", "Polityką ludnościową",
               why="Ogranicza swobodę pracownika."),
             PF("Ochrona praw migrantów zarobkowych jest elementem polityki godnej pracy ILO.", True,
                why="Godna praca obejmuje wszystkich pracowników."),
          ),
      ]),

    L(2, "Instytucje Unii Europejskiej i Polski w polityce migracyjnej",
      "Rozumieć rolę instytucji UE (Komisja Europejska, EUAA, Frontex) i Polski (Urząd do Spraw Cudzoziemców, Straż Graniczna, wojewodowie) w polityce migracyjnej i azylowej oraz znaczenie Paktu o migracji i azylu (stan na 10.2026).",
      ["Międzynarodowe instytucje ds. migracji"],
      [EUAAH, FRTX, ECHA, UDSC, INFPAKT, EUAA],
      explain=[
          K("Instytucje UE",
            "Komisja Europejska proponuje prawo i koordynuje politykę migracyjną (np. dyrektywy o Niebieskiej Karcie, tymczasowej ochronie). EUAA – Agencja UE ds. Azylu (od 2022 r., następczyni EASO) – wspiera państwa w procedurach azylowych i zbiera dane. Frontex – Europejska Agencja Straży Granicznej i Przybrzeżnej (od 2004 r.) – wspiera ochronę granic zewnętrznych UE i operacje powrotowe."),
          K("Pakt o migracji i azylu",
            "Przyjęty przez Radę UE 14.05.2024 r. (Polska głosowała przeciw), stosowany od 12.06.2026 r. Obejmuje m.in. kontrolę przesiewową na granicach, procedury graniczne, bazę Eurodac i mechanizm solidarności: państwa mogą przyjąć relokowane osoby, wpłacić 20 tys. euro za każdą nieprzyjętą osobę lub udzielić wsparcia operacyjnego. Polska jest czasowo zwolniona z wkładu solidarnościowego jako państwo pod szczególną presją migracyjną."),
          W("Która agencja UE wspiera państwa w procedurach azylowych?",
            "EUAA", "Frontex", "Europol",
            why="To Agencja Unii Europejskiej ds. Azylu."),
          K("Instytucje w Polsce",
            "Urząd do Spraw Cudzoziemców – rozpatruje wnioski o ochronę międzynarodową i jest organem odwoławczym w sprawach pobytowych. Wojewodowie – wydają zezwolenia na pobyt i na pracę. Straż Graniczna – kontrola granic i legalności pobytu. Starostowie (powiatowe urzędy pracy) – rejestrują oświadczenia o powierzeniu pracy. ZUS i GUS – dane o cudzoziemcach na rynku pracy i ludności."),
          K("Wielopoziomowe zarządzanie",
            "Polityka migracyjna jest dzielona: UE ustala wspólne zasady azylu, granic i części migracji legalnej, a państwa decydują m.in. o liczbie przyjmowanych imigrantów zarobkowych i integracji. Samorządy i organizacje pozarządowe prowadzą działania integracyjne."),
          PF("Frontex wspiera ochronę zewnętrznych granic UE.", True,
             why="To Europejska Agencja Straży Granicznej i Przybrzeżnej."),
      ],
      mech=[
          KT("Która instytucja?",
             {"Urząd do Spraw Cudzoziemców": ["Rozpatruje wniosek o status uchodźcy w Polsce"],
              "Wojewoda": ["Wydaje zezwolenie na pobyt czasowy i pracę"],
              "Straż Graniczna": ["Kontroluje osoby na przejściu granicznym"],
              "Frontex": ["Koordynuje wspólną operację na granicy zewnętrznej UE"],
              "EUAA": ["Wspiera państwa UE w procedurach azylowych"]},
             why="Podział zadań w polityce migracyjnej."),
          LN("Ułóż drogę cudzoziemca spoza UE do legalnej pracy w Polsce (zezwolenie).",
             ["Pracodawca składa elektronicznie wniosek o zezwolenie na pracę", "Wojewoda wydaje zezwolenie", "Cudzoziemiec uzyskuje wizę lub tytuł pobytowy", "Straż Graniczna kontroluje wjazd", "Pracodawca zgłasza pracownika do ZUS"],
             why="W procesie uczestniczy kilka instytucji."),
          W("Jakie formy solidarności przewiduje Pakt o migracji i azylu?",
            "Relokację, wkład finansowy lub wsparcie operacyjne", "Wyłącznie przymusową relokację", "Brak solidarności",
            why="Państwo wybiera formę wkładu."),
          W("Kto rejestruje oświadczenie o powierzeniu pracy cudzoziemcowi?",
            "Starosta (powiatowy urząd pracy)", "Frontex", "UNHCR",
            why="Procedura oświadczeniowa prowadzona jest przez starostów."),
          M("Które instytucje UE zajmują się migracjami i azylem?",
            ["Komisja Europejska", "EUAA", "Frontex", "Europejski Bank Centralny"], [0, 1, 2],
            why="EBC zajmuje się polityką pieniężną."),
          PF("Pakt o migracji i azylu stosuje się od 12 czerwca 2026 r.", True,
             why="Dwa lata po przyjęciu w 2024 r."),
      ],
      calc=[
          LB("Wkład solidarnościowy 20 tys. euro za osobę; państwo nie przyjmuje 300 osób. Ile wynosi wkład (mln euro)?",
             6, "20000*300/1e6", ["20 000 · 300 = 6 mln euro"], unit="mln euro"),
          LB("Ile lat dzieli założenie Frontexu (2004) od powołania EUAA (2022)?",
             18, "2022-2004", ["2022 − 2004 = 18"], unit="lat"),
          LB("Ile miesięcy dzieli przyjęcie Paktu (05.2024) od jego stosowania (06.2026)?",
             25, "12*2+1", ["Od maja 2024 do czerwca 2026: 25 miesięcy"], unit="mies."),
          LB("Urząd rozpatrzył 8 000 wniosków, 2 400 zakończyło się udzieleniem ochrony (dane umowne). Jaki to odsetek (%)?",
             30, "2400/8000*100", ["2 400 / 8 000 = 30%"], unit="%"),
          LB("Średni czas rozpatrzenia sprawy spadł z 180 do 120 dni. O ile procent?",
             33.33, "(1-120/180)*100", ["120 / 180 ≈ 0,667 → −33,33%"], unit="%", tol=0.02),
          LB("Kurs 4,25 zł/euro. Ile w złotych wynosi wkład 20 tys. euro za osobę?",
             85000, "20000*4.25", ["20 000 · 4,25 = 85 000 zł"], unit="zł"),
      ],
      case=[
          PR("Rodzina z Afganistanu przybywa na polską granicę i prosi o ochronę międzynarodową. Po kontroli zostaje skierowana do procedury azylowej.",
             W("Która instytucja rozpatruje jej wniosek o ochronę?",
               "Urząd do Spraw Cudzoziemców", "Powiatowy urząd pracy", "GUS",
               why="UdSC prowadzi postępowania o ochronę międzynarodową."),
             W("Która formacja przeprowadziła kontrolę na granicy?",
               "Straż Graniczna", "Policja skarbowa", "UNFPA",
               why="Kontrola graniczna należy do Straży Granicznej."),
             PF("Agencja EUAA może wspierać państwa w procedurach azylowych.", True,
                why="Np. szkoleniami i analizami."),
          ),
          PR("Minister mówi, że Polska nie przyjmie relokowanych migrantów w ramach Paktu. Dziennikarz pyta, czy Polska będzie musiała płacić 20 tys. euro za osobę.",
             W("Jaki jest stan na 10.2026 według dostępnych informacji?",
               "Polska jest czasowo zwolniona z wkładu solidarnościowego", "Polska już zapłaciła wkład", "Pakt nie obowiązuje w żadnym kraju",
               why="Zwolnienie przyznano kilku państwom pod presją migracyjną."),
             W("Dlaczego część państw uzyskała zwolnienie?",
               "Ze względu na szczególną presję migracyjną (np. przyjęcie wielu uchodźców)", "Bo nie są w UE", "Bo nie mają granic",
               why="Pakt przewiduje zwolnienia dla państw pod presją."),
             PF("Zakres i długość zwolnień mogą być przedmiotem kolejnych decyzji UE.", True,
                why="Pula solidarnościowa ustalana jest okresowo."),
          ),
      ]),
]
