# -*- coding: utf-8 -*-
# Zrozumienie – Demografia / Teorie demograficzne
D = "2026-10-08"
OWIDT = S("Our World in Data – Demographic transition", "https://ourworldindata.org/demographic-transition", D)
OWIDA = S("Our World in Data – Age structure", "https://ourworldindata.org/age-structure", D)
IMFDD = S("IMF Finance & Development (2006) – What Is the Demographic Dividend? (R. Lee, A. Mason)", "https://www.imf.org/external/pubs/ft/fandd/2006/09/basics.htm", D)
ECMAL = S("Econlib – Thomas Robert Malthus (biografia)", "https://www.econlib.org/library/Enc/bios/Malthus.html", D)
ECMALT = S("Econlib – T.R. Malthus, An Essay on the Principle of Population", "https://www.econlib.org/library/Malthus/malPop.html", D)
ECBEC = S("Econlib – Gary S. Becker (biografia)", "https://www.econlib.org/library/Enc/bios/Becker.html", D)
NOBBEC = S("Nobelprize.org – Gary S. Becker, nagroda 1992", "https://www.nobelprize.org/prizes/economic-sciences/1992/becker/facts/", D)
GUSPWL = S("GUS – Polska w liczbach 2026 (dane za 2025 r.)", "https://plwliczbach.stat.gov.pl/pl/assets/pdf/polska-w-liczbach-2026.pdf", D)

LESSONS = [
    L(1, "Przejście demograficzne",
      "Rozumieć etapy przejścia demograficznego, jego przyczyny i skutki dla liczby ludności oraz umieć umieścić Polskę i inne kraje na poszczególnych etapach.",
      ["Przejście (transformacja) demograficzne"],
      [OWIDT, GUSPWL],
      explain=[
          K("Model przejścia",
            "Teoria przejścia demograficznego (W. Thompson 1929, F. Notestein 1945) opisuje przejście od wysokiej rozrodczości i umieralności do niskiej. Etap 1: wysokie urodzenia i zgony, ludność rośnie wolno. Etap 2: spadek umieralności (higiena, żywność, medycyna), urodzenia wciąż wysokie – eksplozja demograficzna. Etap 3: spadek urodzeń (urbanizacja, edukacja kobiet, antykoncepcja). Etap 4: niskie urodzenia i zgony, wzrost bliski zera. Często dodaje się etap 5: urodzenia poniżej zgonów – depopulacja."),
          K("Dlaczego zgony spadają wcześniej",
            "Spadek umieralności wymaga zmian technicznych i zdrowotnych (woda, szczepienia, żywność), które szerzą się szybko. Spadek rozrodczości wymaga zmian norm, kosztów i korzyści z posiadania dzieci – trwa dłużej. Luka czasowa między tymi spadkami powoduje szybki wzrost ludności w etapie 2 i 3."),
          W("W którym etapie przejścia ludność rośnie najszybciej?",
            "W etapie 2 (i na początku 3) – zgony już spadły, urodzenia jeszcze wysokie", "W etapie 1", "W etapie 4",
            why="Największa różnica między urodzeniami a zgonami."),
          K("Przyczyny spadku urodzeń",
            "Spadek umieralności dzieci (nie trzeba „zapasu” dzieci), urbanizacja i praca poza rolnictwem (dziecko przestaje być siłą roboczą), powszechna edukacja (dziecko kosztuje), edukacja i aktywność zawodowa kobiet (wyższy koszt alternatywny), systemy emerytalne (mniejsza rola dzieci jako zabezpieczenia na starość), dostęp do antykoncepcji."),
          K("Polska i świat",
            "Polska przeszła klasyczne przejście w XIX–XX w.; współczynnik przyrostu naturalnego spadł z +4,1‰ (1990) do −4,5‰ (2025), czyli znalazła się w „etapie 5”. Wiele krajów Afryki Subsaharyjskiej jest wciąż w etapie 2–3, z TFR powyżej 4. Model opisuje ogólny wzorzec, ale tempo i przyczyny różnią się między krajami."),
          PF("W etapie 1 przejścia demograficznego ludność rośnie bardzo szybko.", False,
             why="Wysokie urodzenia równoważą wysokie zgony – wzrost jest powolny."),
      ],
      mech=[
          KT("Etap przejścia demograficznego",
             {"Etap 1": ["Wysokie urodzenia i wysokie zgony, wolny wzrost ludności"],
              "Etap 2": ["Szybki spadek zgonów, urodzenia nadal wysokie"],
              "Etap 3": ["Spadek urodzeń, wzrost ludności zwalnia"],
              "Etap 4": ["Niskie urodzenia i zgony, wzrost bliski zera"],
              "Etap 5": ["Urodzenia poniżej zgonów, ludność maleje"]},
             why="Kolejne etapy modelu przejścia."),
          LN("Ułóż łańcuch przyczyn spadku dzietności.",
             ["Poprawa higieny i medycyny", "Spada umieralność niemowląt", "Rodziny nie potrzebują „zapasu” dzieci", "Rosną koszty edukacji i koszt alternatywny pracy kobiet", "Spada liczba urodzeń na kobietę"],
             why="Rodziny dostosowują liczbę dzieci do nowych warunków."),
          W("Kraj ma TFR 5,5 i szybko spadającą umieralność dzieci. W którym etapie się znajduje?",
            "W etapie 2", "W etapie 4", "W etapie 5",
            why="Wysokie urodzenia przy spadających zgonach."),
          W("Dlaczego systemy emerytalne obniżają dzietność według teorii przejścia?",
            "Dzieci przestają być głównym zabezpieczeniem na starość", "Emeryci nie mogą mieć dzieci", "Emerytury są finansowane przez dzieci",
            why="Zmniejsza się korzyść ekonomiczna z posiadania dzieci."),
          M("Co powoduje spadek umieralności w etapie 2?",
            ["Poprawa higieny i dostęp do czystej wody", "Lepsze odżywianie", "Szczepienia i medycyna", "Spadek liczby urodzeń"], [0, 1, 2],
            why="Spadek urodzeń to etap 3."),
          PF("Polska w 2025 r. miała ujemny przyrost naturalny, co odpowiada tzw. etapowi 5.", True,
             why="Zgonów było więcej niż urodzeń (−4,5‰)."),
      ],
      calc=[
          LB("Etap 2: urodzenia 40‰, zgony 15‰. Ile wynosi przyrost naturalny (‰)?",
             25, "40-15", ["40 − 15 = 25‰"], unit="‰"),
          LB("Przy przyroście 2,5% rocznie, po ilu latach ludność się podwoi (reguła 70)?",
             28, "70/2.5", ["70 / 2,5 = 28 lat"], unit="lat"),
          LB("Etap 4: urodzenia 10‰, zgony 9,5‰. Ile wynosi przyrost (%)?",
             0.05, "(10-9.5)/10", ["0,5‰ = 0,05%"], unit="%", tol=0.0001),
          LB("Ludność 10 mln rośnie o 2,5% rocznie. Ile wyniesie po 10 latach (mln)?",
             12.8, "10*1.025**10", ["10 · 1,025¹⁰ ≈ 12,80 mln"], unit="mln", tol=0.01),
          LB("Przyrost naturalny w Polsce: +4,1‰ (1990), −4,5‰ (2025). O ile punktów promilowych się zmienił?",
             -8.6, "-4.5-4.1", ["−4,5 − 4,1 = −8,6"], unit="‰", tol=0.001),
          LB("Kraj ma 50 mln mieszkańców i przyrost 25‰. O ile osób rocznie przybywa (mln)?",
             1.25, "50*25/1000", ["50 · 0,025 = 1,25 mln"], unit="mln", tol=0.001),
      ],
      case=[
          PR("Kraj w Afryce Wschodniej: urodzenia 35‰, zgony 7‰, TFR 4,5, ludność bardzo młoda. Rząd inwestuje w szkoły dla dziewcząt i opiekę zdrowotną matek.",
             W("W którym etapie przejścia jest kraj?",
               "W etapie 2/3 – zgony niskie, urodzenia wciąż wysokie", "W etapie 1", "W etapie 5",
               why="Duża luka między urodzeniami a zgonami."),
             W("Jak edukacja dziewcząt wpłynie na dzietność?",
               "Obniży ją – wyższy koszt alternatywny i późniejsze macierzyństwo", "Podniesie ją", "Nie wpłynie",
               why="To jeden z najsilniejszych czynników spadku płodności."),
             PF("Ludność tego kraju będzie rosła jeszcze długo, nawet gdy dzietność spadnie.", True,
                why="Duża liczba młodych osób wejdzie w wiek rodzicielski (pęd demograficzny)."),
          ),
          PR("Uczeń twierdzi: „Spadek dzietności w Europie jest dowodem na to, że ludzie przestali lubić dzieci”.",
             W("Jak teoria przejścia demograficznego wyjaśnia spadek dzietności?",
               "Zmianami kosztów i korzyści z posiadania dzieci w nowoczesnej gospodarce", "Wyłącznie zmianą upodobań", "Klimatem",
               why="Czynniki ekonomiczne i społeczne zmieniają decyzje rodzin."),
             W("Który czynnik był ważny w spadku dzietności?",
               "Spadek umieralności niemowląt", "Wzrost umieralności niemowląt", "Powrót do rolnictwa",
               why="Rodziny nie potrzebowały już „zapasu” dzieci."),
             PF("Spadek dzietności w krajach rozwiniętych jest zjawiskiem powszechnym, a nie tylko europejskim.", True,
                why="Dotyczy też m.in. Azji Wschodniej i Ameryki Północnej."),
          ),
      ]),

    L(2, "Drugie przejście demograficzne, przejście epidemiologiczne i migracyjne",
      "Rozumieć drugie przejście demograficzne (van de Kaa, Lesthaeghe), przejście epidemiologiczne (Omran) i przejście migracyjne (Zelinsky) oraz ich przejawy w Polsce.",
      ["Drugie przejście demograficzne", "Przejście epidemiologiczne i przejście migracyjne"],
      [OWIDT, GUSPWL],
      explain=[
          K("Drugie przejście demograficzne",
            "D. van de Kaa i R. Lesthaeghe (1986) opisali zmiany w Europie od lat 60.: spadek dzietności trwale poniżej zastępowalności, odkładanie małżeństw i rodzicielstwa, wzrost kohabitacji, rozwodów i urodzeń pozamałżeńskich, różnorodność form rodziny. Przyczyną są zmiany wartości: indywidualizm, samorealizacja, autonomia, równość płci (wartości postmaterialistyczne)."),
          K("Polska",
            "Przejawy drugiego przejścia w Polsce: średni wiek kobiet przy pierwszym dziecku wzrósł z 22,7 (1990) do 29,5 roku (2025), zawieranie małżeństw spadło z 6,7 do 3,6 na 1 000 ludności, rośnie udział urodzeń pozamałżeńskich i kohabitacji. TFR od 1989 r. jest poniżej progu zastępowalności."),
          W("Która zmiana jest typowa dla drugiego przejścia demograficznego?",
            "Odkładanie rodzicielstwa i wzrost kohabitacji", "Wzrost umieralności niemowląt", "Wzrost liczby małżeństw w młodym wieku",
            why="To zmiany wzorców rodzinnych wynikające z wartości."),
          K("Przejście epidemiologiczne (Omran, 1971)",
            "Zmiana głównych przyczyn zgonów: era zarazy i głodu → era ustępujących pandemii → era chorób zwyrodnieniowych i cywilizacyjnych (serce, nowotwory) → (dodatkowo) era opóźnionych chorób zwyrodnieniowych – choroby przewlekłe pojawiają się coraz później. Towarzyszy temu wzrost trwania życia i przesunięcie zgonów do późnego wieku."),
          K("Przejście migracyjne (Zelinsky, 1971)",
            "W. Zelinsky powiązał etapy rozwoju i przejścia demograficznego z formami mobilności: społeczeństwo przednowoczesne – mała mobilność; wczesne przejście – masowe migracje ze wsi do miast i emigracja; późniejsze etapy – migracje między miastami i dojazdy; społeczeństwa zaawansowane – imigracja z krajów mniej rozwiniętych. Polska przechodzi od emigracji do imigracji."),
          PF("Według Omrana w zaawansowanej fazie przejścia dominują zgony z powodu chorób zakaźnych.", False,
             why="Dominują choroby zwyrodnieniowe i cywilizacyjne."),
      ],
      mech=[
          KT("Które przejście?",
             {"Drugie przejście demograficzne": ["Wzrost kohabitacji i urodzeń pozamałżeńskich", "Odkładanie rodzicielstwa na koniec trzeciej dekady życia"],
              "Przejście epidemiologiczne": ["Choroby serca zamiast gruźlicy jako główna przyczyna zgonów"],
              "Przejście migracyjne": ["Kraj emigracji staje się krajem imigracji", "Masowe migracje ze wsi do miast w okresie industrializacji"]},
             why="Trzy powiązane procesy przemian społeczeństw."),
          LN("Ułóż etapy przejścia epidemiologicznego.",
             ["Era zarazy i głodu", "Era ustępujących pandemii", "Era chorób zwyrodnieniowych i cywilizacyjnych", "Era opóźnionych chorób zwyrodnieniowych"],
             why="Zmiana struktury przyczyn zgonów."),
          W("Co według van de Kaa i Lesthaeghe jest główną przyczyną drugiego przejścia?",
            "Zmiana wartości – indywidualizm i samorealizacja", "Wysoka umieralność", "Brak antykoncepcji",
            why="Teoria akcentuje zmiany kulturowe."),
          W("Polska po 2004 r. była krajem dużej emigracji, a po 2014 r. przyjęła wielu imigrantów z Ukrainy. Co ilustruje ta zmiana?",
            "Przejście migracyjne", "Przejście epidemiologiczne", "Pułapkę maltuzjańską",
            why="Zmiana z kraju emigracji w kraj imigracji."),
          M("Jakie zjawiska są przejawami drugiego przejścia w Polsce?",
            ["Wzrost wieku matek przy pierwszym dziecku", "Spadek liczby małżeństw", "Wzrost udziału urodzeń pozamałżeńskich", "Wzrost TFR powyżej 2,1"], [0, 1, 2],
            why="TFR spadł do 1,068."),
          PF("Przejście epidemiologiczne wiąże się ze wzrostem trwania życia.", True,
             why="Zgony przesuwają się do późnego wieku."),
      ],
      calc=[
          LB("Małżeństwa: 6,7‰ (1990), 3,6‰ (2025). O ile procent spadł współczynnik?",
             46.27, "(1-3.6/6.7)*100", ["3,6 / 6,7 ≈ 0,5373 → −46,27%"], unit="%", tol=0.02),
          LB("Ile małżeństw zawarto przy 3,6‰ i ludności 37 333 tys. (tys.)?",
             134.4, "37333*3.6/1000", ["37 333 · 0,0036 ≈ 134,4 tys."], unit="tys.", tol=0.1),
          LB("Średni wiek przy 1. dziecku rośnie o 0,2 roku rocznie, obecnie 29,5. Ile wyniesie za 10 lat?",
             31.5, "29.5+0.2*10", ["29,5 + 2 = 31,5"], unit="lat", tol=0.001),
          LB("Ile lat dzieli prace Omrana i Zelinsky’ego (1971) od pracy van de Kaa i Lesthaeghe (1986)?",
             15, "1986-1971", ["1986 − 1971 = 15"], unit="lat"),
          LB("Na 1 000 zgonów 450 to choroby krążenia, 250 nowotwory. Jaki udział mają łącznie (%)?",
             70, "(450+250)/1000*100", ["700 / 1 000 = 70%"], unit="%"),
          LB("Rozwody: 1,1‰ (1990), 1,6‰ (2025). O ile procent wzrosły?",
             45.45, "(1.6/1.1-1)*100", ["1,6 / 1,1 ≈ 1,4545 → +45,45%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Ankieta wśród 30-latków w Polsce: większość deklaruje chęć posiadania dwójki dzieci, ale najpierw chce zdobyć wykształcenie, stabilną pracę i mieszkanie. Wiele par mieszka razem bez ślubu.",
             W("Które przejście opisują te postawy?",
               "Drugie przejście demograficzne", "Pierwsze przejście – etap 1", "Przejście epidemiologiczne",
               why="Odkładanie rodzicielstwa i kohabitacja."),
             W("Dlaczego odkładanie rodzicielstwa obniża liczbę urodzonych dzieci?",
               "Krótszy okres na urodzenie planowanych dzieci i spadek płodności z wiekiem", "Nie ma wpływu", "Zwiększa liczbę dzieci",
               why="Część planów nie zostaje zrealizowana."),
             PF("Luka między deklarowaną a faktyczną liczbą dzieci może być celem polityki rodzinnej.", True,
                why="Np. przez mieszkania, opiekę nad dziećmi i stabilność pracy."),
          ),
          PR("W XIX-wiecznym mieście główną przyczyną zgonów były gruźlica, cholera i choroby niemowląt. Dziś w tym mieście dominują choroby serca i nowotwory, a zgony koncentrują się po 75. roku życia.",
             W("Jaki proces zaszedł?",
               "Przejście epidemiologiczne", "Drugie przejście demograficzne", "Suburbanizacja",
               why="Zmiana struktury przyczyn zgonów."),
             W("Jakie wyzwanie wynika z tej zmiany dla systemu zdrowia?",
               "Leczenie chorób przewlekłych i opieka nad osobami starszymi", "Walka wyłącznie z cholerą", "Brak wyzwań",
               why="Choroby przewlekłe wymagają długotrwałej opieki."),
             PF("Poprawa warunków sanitarnych była jedną z przyczyn spadku zgonów z chorób zakaźnych.", True,
                why="Czysta woda i kanalizacja ograniczyły epidemie."),
          ),
      ]),

    L(3, "Przejście struktury wieku i dywidendy demograficzne",
      "Rozumieć, jak przejście demograficzne zmienia strukturę wieku, czym jest pierwsza i druga dywidenda demograficzna i dlaczego „okno demograficzne” się zamyka.",
      ["Przejście struktury wieku", "Druga dywidenda demograficzna"],
      [IMFDD, OWIDA, GUSPWL],
      explain=[
          K("Przejście struktury wieku",
            "Spadek umieralności, a potem urodzeń zmienia strukturę wieku: najpierw rośnie udział dzieci, potem – gdy urodzenia spadają – rośnie udział osób w wieku produkcyjnym, a w końcu udział osób starszych. Okres wysokiego udziału osób w wieku produkcyjnym i niskiego obciążenia to „okno demograficzne”."),
          K("Pierwsza dywidenda",
            "R. Lee i A. Mason: gdy udział pracujących w ludności rośnie, PKB na mieszkańca rośnie nawet przy stałej wydajności pracy. Tożsamość: Y/N = (Y/L) · (L/N) – PKB na mieszkańca = wydajność × udział pracujących. Pierwsza dywidenda jest przejściowa – znika, gdy liczne roczniki przechodzą na emeryturę (staje się ujemna).",
            w="Y/N = (Y/L) · (L/N)"),
          W("Udział pracujących w ludności rośnie z 40% do 50%, wydajność bez zmian. O ile rośnie PKB na mieszkańca?",
            "O 25%", "O 10%", "O 50%",
            why="0,5 / 0,4 = 1,25."),
          K("Druga dywidenda",
            "Osoby w średnim wieku, spodziewając się długiego życia na emeryturze, oszczędzają i akumulują majątek. Jeśli oszczędności są inwestowane w kapitał (w kraju lub za granicą), rośnie wydajność i dochód – to druga dywidenda. Może być trwała, ale zależy od instytucji: jeśli emerytury finansuje się głównie z transferów (repartycja), bodziec do oszczędzania jest słabszy."),
          K("Warunki wykorzystania dywidendy",
            "Dywidenda nie jest automatyczna: wymaga miejsc pracy dla rosnącej liczby osób w wieku produkcyjnym, edukacji, aktywności zawodowej kobiet, sprawnych rynków finansowych. Azja Wschodnia (np. Korea Płd.) wykorzystała okno; w wielu krajach wysokie bezrobocie młodych zmarnowało jego część. Polska była w oknie demograficznym ok. 1990–2020 r.; dziś obciążenie osobami starszymi szybko rośnie."),
          PF("Pierwsza dywidenda demograficzna trwa bez końca.", False,
             why="Jest przejściowa – kończy się wraz ze starzeniem się liczebnych roczników."),
      ],
      mech=[
          KT("Pierwsza czy druga dywidenda?",
             {"Pierwsza dywidenda": ["Wzrost udziału osób w wieku produkcyjnym podnosi PKB per capita", "Mniej dzieci na pracującego"],
              "Druga dywidenda": ["Oszczędności osób w średnim wieku zwiększają kapitał", "Akumulacja majątku na długą emeryturę"]},
             why="Dwa różne mechanizmy wpływu demografii na wzrost."),
          LN("Ułóż przebieg przejścia struktury wieku.",
             ["Spada umieralność dzieci – rośnie udział dzieci", "Spada dzietność – mniej dzieci na dorosłego", "Liczne roczniki wchodzą w wiek produkcyjny – okno demograficzne", "Liczne roczniki przechodzą na emeryturę", "Rośnie obciążenie osobami starszymi"],
             why="Struktura wieku zmienia się falami."),
          W("Kraj ma rosnącą liczbę młodych dorosłych, ale bezrobocie młodzieży wynosi 30%. Co z dywidendą?",
            "Jest marnowana – potencjalni pracownicy nie pracują", "Jest w pełni wykorzystana", "Nie ma związku",
            why="Dywidenda wymaga zatrudnienia rosnącej siły roboczej."),
          W("Dlaczego druga dywidenda może być słabsza w krajach z hojnymi emeryturami repartycyjnymi?",
            "Ludzie mniej oszczędzają, licząc na transfery", "Bo nie ma osób w średnim wieku", "Bo podatki są niskie",
            why="Słabszy bodziec do akumulacji majątku."),
          M("Co sprzyja wykorzystaniu pierwszej dywidendy?",
            ["Tworzenie miejsc pracy", "Edukacja młodzieży", "Aktywność zawodowa kobiet", "Obniżanie wieku emerytalnego"], [0, 1, 2],
            why="Wcześniejsze emerytury zmniejszają liczbę pracujących."),
          PF("Spadek dzietności przez pewien czas może sprzyjać wzrostowi PKB na mieszkańca.", True,
             why="Spada obciążenie dziećmi, rośnie udział pracujących."),
      ],
      calc=[
          LB("Udział pracujących wzrasta z 0,5 do 0,6. O ile procent wzrośnie PKB per capita przy stałej wydajności?",
             20, "(0.6/0.5-1)*100", ["0,6 / 0,5 = 1,2 → +20%"], unit="%"),
          LB("Wydajność rośnie o 2% rocznie, a udział pracujących spada o 0,5% rocznie. Ile wynosi przybliżony wzrost PKB per capita (%)?",
             1.5, "2-0.5", ["2 − 0,5 = 1,5%"], unit="%", tol=0.001),
          LB("PKB 1 000 mld zł, 36 mln ludności, 17 mln pracujących. Ile wynosi wydajność (tys. zł na pracującego)?",
             58.82, "1000e9/17e6/1000", ["1 000 mld / 17 mln ≈ 58,82 tys. zł"], unit="tys. zł", tol=0.02),
          LB("Przy tych danych ile wynosi udział pracujących w ludności (%)?",
             47.22, "17/36*100", ["17 / 36 ≈ 47,22%"], unit="%", tol=0.02),
          LB("Obciążenie osobami poprodukcyjnymi rośnie z 41 do 60 na 100 w wieku produkcyjnym. O ile procent?",
             46.34, "(60/41-1)*100", ["60 / 41 ≈ 1,4634 → +46,34%"], unit="%", tol=0.02),
          LB("Oszczędności 10% dochodu przez 30 lat przy stopie 2% realnie: ile razy wzrośnie kapitał z jednej wpłaty?",
             1.81, "1.02**30", ["1,02³⁰ ≈ 1,81"], unit="razy", tol=0.01),
      ],
      case=[
          PR("Kraj A w latach 1970–2000 obniżył dzietność z 4 do 1,5, inwestował w edukację, przemysł eksportowy i miał wysoką stopę oszczędności. Kraj B miał podobne zmiany demograficzne, ale wysokie bezrobocie młodzieży i słabe szkoły.",
             W("Który kraj lepiej wykorzystał dywidendę demograficzną?",
               "Kraj A", "Kraj B", "Oba tak samo",
               why="Zatrudnienie i inwestycje przekształciły zmianę struktury wieku we wzrost."),
             W("Jaki problem pojawi się w kraju A w kolejnych dekadach?",
               "Szybkie starzenie się i spadek udziału pracujących", "Eksplozja demograficzna", "Brak osób starszych",
               why="Liczne roczniki przejdą na emeryturę."),
             PF("Oszczędności zgromadzone w okresie dywidendy mogą łagodzić skutki starzenia się (druga dywidenda).", True,
                why="Kapitał finansuje konsumpcję i inwestycje w przyszłości."),
          ),
          PR("Polska w 2025 r.: przedprodukcyjny 17,7%, produkcyjny 58,2%, poprodukcyjny 24,1%. W 1990 r.: 29,0% / 58,2% / 12,8%.",
             W("Jak zmieniło się obciążenie dziećmi?",
               "Spadło – z ok. 50 do ok. 30 dzieci na 100 osób w wieku produkcyjnym", "Wzrosło", "Nie zmieniło się",
               why="29,0 / 58,2 ≈ 0,50; 17,7 / 58,2 ≈ 0,30."),
             W("Co oznacza wzrost obciążenia osobami starszymi dla pierwszej dywidendy?",
               "Zamienia się ona w obciążenie – udział pracujących zacznie spadać", "Rośnie bez końca", "Nie ma wpływu",
               why="Pierwsza dywidenda staje się ujemna przy starzeniu się."),
             PF("Polska jest już na etapie zamykania się okna demograficznego.", True,
                why="Szybko rośnie udział osób w wieku poprodukcyjnym."),
          ),
      ]),

    L(4, "Malthus i pułapka maltuzjańska",
      "Rozumieć teorię ludności T.R. Malthusa (1798), mechanizm pułapki maltuzjańskiej, hamulce wzrostu ludności oraz to, dlaczego rewolucja przemysłowa pozwoliła z niej wyjść.",
      ["Pułapka maltuzjańska"],
      [ECMAL, ECMALT, OWIDT],
      explain=[
          K("Teoria Malthusa",
            "T.R. Malthus („Prawo ludności”, 1798): ludność, gdy nic jej nie hamuje, rośnie w postępie geometrycznym (1, 2, 4, 8…), a żywność – w najlepszym razie arytmetycznym (1, 2, 3, 4…). Dlatego wzrost ludności musi być hamowany. Hamulce pozytywne (zwiększające zgony): głód, choroby, wojny. Hamulce prewencyjne (zmniejszające urodzenia): późne małżeństwa, wstrzemięźliwość („moral restraint”)."),
          K("Pułapka maltuzjańska",
            "Gdy dochód na osobę rośnie (np. po dobrym urodzaju lub nowej technice rolnej), ludność zaczyna szybciej rosnąć. Przy stałej ilości ziemi i malejących przychodach z pracy dochód na osobę spada z powrotem do poziomu utrzymania. Postęp techniczny zwiększa więc liczbę ludzi, ale nie ich dobrobyt – tak przez tysiąclecia wyglądała gospodarka rolnicza."),
          W("Nowa odmiana zboża zwiększa plony o 30%. Co według modelu maltuzjańskiego stanie się w długim okresie?",
            "Ludność wzrośnie, a dochód na osobę wróci do poziomu utrzymania", "Dochód na osobę trwale wzrośnie o 30%", "Ludność spadnie",
            why="Wyższy dochód przekłada się na wzrost liczby ludności."),
          K("Wyjście z pułapki",
            "Od rewolucji przemysłowej postęp techniczny (maszyny, energia, chemia rolna) rósł szybciej niż ludność, a po przejściu demograficznym dzietność spadła mimo rosnących dochodów. Dzięki temu dochód na osobę zaczął trwale rosnąć. Malthus nie przewidział ani tempa innowacji, ani spadku płodności przy wzroście zamożności."),
          K("Neomaltuzjanizm",
            "Myśl Malthusa odżywa w debatach o granicach zasobów: raport Klubu Rzymskiego „Granice wzrostu” (1972), dyskusje o klimacie i wodzie. Krytycy wskazują, że rynki (ceny), technologia i instytucje pozwalają łagodzić niedobory; zwolennicy – że globalne dobra wspólne (klimat, bioróżnorodność) nie są dobrze wyceniane."),
          PF("Późne małżeństwa to według Malthusa hamulec prewencyjny.", True,
             why="Zmniejszają liczbę urodzeń."),
      ],
      mech=[
          KT("Hamulec pozytywny czy prewencyjny?",
             {"Pozytywny (więcej zgonów)": ["Klęska głodu", "Epidemia", "Wojna"],
              "Prewencyjny (mniej urodzeń)": ["Późne zawieranie małżeństw", "Wstrzemięźliwość"]},
             why="Dwa rodzaje hamulców wzrostu ludności według Malthusa."),
          LN("Ułóż mechanizm pułapki maltuzjańskiej.",
             ["Postęp w rolnictwie zwiększa plony", "Dochód na osobę rośnie", "Ludność rośnie szybciej (więcej urodzeń, mniej zgonów)", "Na osobę przypada mniej ziemi i żywności", "Dochód na osobę wraca do poziomu utrzymania"],
             why="Wzrost dochodów „zjada” wzrost ludności."),
          W("Dlaczego kraje rozwinięte wyszły z pułapki maltuzjańskiej?",
            "Postęp techniczny był szybszy od wzrostu ludności, a dzietność spadła", "Bo ziemia się powiększyła", "Bo nie było wojen",
            why="Trwały wzrost wydajności i przejście demograficzne."),
          W("Ludność rośnie geometrycznie: 1, 2, 4, 8. Jak rośnie żywność według Malthusa?",
            "Arytmetycznie: 1, 2, 3, 4", "Geometrycznie: 1, 2, 4, 8", "Nie rośnie wcale",
            why="Tak sformułował to Malthus."),
          M("Co według Malthusa hamuje wzrost ludności?",
            ["Głód", "Choroby", "Późne małżeństwa", "Rewolucja przemysłowa"], [0, 1, 2],
            why="Rewolucja przemysłowa nastąpiła później i nie była „hamulcem”."),
          PF("Malthus trafnie przewidział trwały wzrost dochodów na osobę w XIX i XX w.", False,
             why="Nie przewidział tempa postępu technicznego ani spadku płodności."),
      ],
      calc=[
          LB("Ludność podwaja się co 25 lat. Ile razy wzrośnie po 100 latach?",
             16, "2**(100/25)", ["2⁴ = 16"], unit="razy"),
          LB("Żywność rośnie co 25 lat o tę samą wielkość (1 → 2 → 3…). Ile razy wzrośnie po 100 latach?",
             5, "1+4", ["1 + 4 = 5"], unit="razy"),
          LB("Ile żywności na osobę zostanie po 100 latach względem stanu początkowego (5 / 16)?",
             0.3125, "5/16", ["5 / 16 = 0,3125"], unit="", tol=0.0001),
          LB("„Prawo ludności” – 1798, „Granice wzrostu” – 1972. Ile lat różnicy?",
             174, "1972-1798", ["1972 − 1798 = 174"], unit="lata"),
          LB("Plony rosną o 30%, ludność też o 30%. O ile zmieni się żywność na osobę (%)?",
             0, "(1.3/1.3-1)*100", ["1,3 / 1,3 = 1 → 0%"], unit="%"),
          LB("Ludność rośnie 1% rocznie, produkcja żywności 2,5% rocznie. O ile procent rocznie rośnie żywność na osobę (w przybliżeniu)?",
             1.5, "2.5-1", ["2,5 − 1 = 1,5%"], unit="%", tol=0.001),
      ],
      case=[
          PR("W średniowiecznej Europie po epidemii dżumy (XIV w.) zmarła duża część ludności. Płace realne robotników rolnych wyraźnie wzrosły, a w kolejnych stuleciach ludność się odbudowała, a płace spadły.",
             W("Jak model maltuzjański wyjaśnia wzrost płac po epidemii?",
               "Mniej ludzi na tę samą ilość ziemi – wyższa krańcowa wydajność pracy", "Wzrostem podatków", "Postępem technicznym",
               why="Praca stała się rzadsza względem ziemi."),
             W("Co stało się z płacami, gdy ludność się odbudowała?",
               "Spadły z powrotem", "Dalej rosły", "Nie zmieniły się",
               why="Mechanizm pułapki maltuzjańskiej."),
             PF("Epidemia działała jak hamulec pozytywny.", True,
                why="Zwiększyła liczbę zgonów."),
          ),
          PR("Ekolog twierdzi, że rosnąca ludność świata doprowadzi do braku żywności. Ekonomista odpowiada, że od 1960 r. ludność świata wzrosła ponad dwukrotnie, a produkcja żywności na osobę rośnie.",
             W("Jakie podejście reprezentuje ekolog?",
               "Neomaltuzjańskie", "Teorię Beckera", "Hipotezę Easterlina",
               why="Akcentuje ograniczenia zasobów."),
             W("Co wyjaśnia wzrost produkcji żywności na osobę?",
               "Postęp techniczny w rolnictwie (nawozy, odmiany, nawadnianie)", "Spadek liczby ludności", "Zmniejszenie powierzchni upraw",
               why="Zielona rewolucja zwiększyła plony."),
             PF("Globalne problemy środowiskowe sprawiają, że debata o granicach wzrostu jest wciąż aktualna.", True,
                why="Klimat i bioróżnorodność to zasoby słabo wyceniane przez rynek."),
          ),
      ]),

    L(5, "Ekonomiczne teorie płodności: Becker i Easterlin",
      "Rozumieć ekonomiczną teorię płodności G. Beckera (koszt alternatywny, wybór między liczbą a „jakością” dzieci) i hipotezę Easterlina o względnym dochodzie – oraz wnioski dla polityki rodzinnej.",
      ["Ekonomiczna teoria płodności (G. Becker)", "Hipoteza Easterlina (względnego dochodu)"],
      [ECBEC, NOBBEC],
      explain=[
          K("Becker: dzieci jako dobro",
            "G. Becker (od 1960 r., Nobel 1992) traktował decyzje o dzieciach jak wybory ekonomiczne: rodzina porównuje korzyści (satysfakcja, wsparcie) z kosztami – bezpośrednimi (utrzymanie, edukacja) i pośrednimi, zwłaszcza kosztem alternatywnym czasu matki (utracone zarobki). Gdy rosną płace kobiet, rośnie koszt alternatywny wychowania dziecka – efekt substytucji obniża płodność."),
          K("Liczba a „jakość” dzieci",
            "Becker i H.G. Lewis: rodzice wybierają nie tylko liczbę dzieci, ale też nakłady na każde dziecko (edukacja, zdrowie). Wraz ze wzrostem dochodów i zwrotów z edukacji rodziny wolą mniej dzieci, w które więcej inwestują. Wyjaśnia to, dlaczego zamożniejsze społeczeństwa mają mniej dzieci, choć „stać je” na więcej."),
          W("Płace kobiet rosną o 20%. Jaki efekt według Beckera obniża płodność?",
            "Efekt substytucji – rośnie koszt alternatywny czasu poświęconego dzieciom", "Efekt dochodowy", "Efekt Hawthorne",
            why="Każda godzina opieki oznacza większe utracone zarobki."),
          K("Hipoteza Easterlina",
            "R. Easterlin: o płodności decyduje dochód względny – zarobki młodych dorosłych w porównaniu z aspiracjami ukształtowanymi w domu rodzinnym. Małe roczniki mają dobrą sytuację na rynku pracy (mało konkurencji) → wyższy dochód względny → więcej dzieci; liczne roczniki – odwrotnie. Może to wywoływać cykle demograficzne (np. baby boom w USA po II wojnie światowej i późniejszy spadek)."),
          K("Wnioski dla polityki",
            "Z teorii Beckera wynika, że polityka może obniżać koszt alternatywny (żłobki, elastyczna praca, urlopy dla obojga rodziców), a nie tylko dawać transfery pieniężne. Z hipotezy Easterlina – że znaczenie ma sytuacja młodych na rynku pracy i mieszkaniowym względem ich oczekiwań. Badania wskazują, że same zasiłki zwykle mają umiarkowany wpływ na dzietność."),
          PF("Według Easterlina małe roczniki mogą mieć wyższą dzietność dzięki dobrej sytuacji na rynku pracy.", True,
             why="Wysoki dochód względny sprzyja zakładaniu rodzin."),
      ],
      mech=[
          KT("Becker czy Easterlin?",
             {"G. Becker": ["Koszt alternatywny czasu matki", "Wybór między liczbą a „jakością” dzieci"],
              "R. Easterlin": ["Dochód względny młodych wobec aspiracji z domu rodzinnego", "Cykle liczebności roczników i płodności"]},
             why="Dwie ekonomiczne teorie płodności."),
          LN("Ułóż mechanizm cyklu Easterlina.",
             ["Mały rocznik wchodzi na rynek pracy", "Mało konkurencji – wysokie płace i dobre perspektywy", "Wysoki dochód względny – więcej urodzeń", "Liczny rocznik dzieci dorasta", "Duża konkurencja na rynku pracy – mniej urodzeń"],
             why="Liczebność rocznika wpływa na jego płodność."),
          W("Rodzina o rosnących dochodach decyduje się na jedno dziecko i drogie zajęcia dodatkowe zamiast trojga dzieci. Którą ideę to ilustruje?",
            "Wybór między liczbą a „jakością” dzieci (Becker)", "Pułapkę maltuzjańską", "Hipotezę Easterlina",
            why="Rośnie nakład na jedno dziecko."),
          W("Które rozwiązanie najbardziej obniża koszt alternatywny posiadania dziecka według teorii Beckera?",
            "Dostępne żłobki i elastyczne formy pracy", "Wyższe podatki dla rodziców", "Likwidacja urlopów",
            why="Pozwalają łączyć pracę z rodzicielstwem."),
          M("Jakie koszty dziecka uwzględnia Becker?",
            ["Wydatki na utrzymanie", "Wydatki na edukację", "Utracone zarobki rodzica", "Koszt alternatywny dla sąsiadów"], [0, 1, 2],
            why="Liczą się koszty ponoszone przez rodzinę."),
          PF("Gary Becker otrzymał Nagrodę Nobla z ekonomii w 1992 r.", True,
             why="Za rozszerzenie analizy mikroekonomicznej na zachowania pozarynkowe."),
      ],
      calc=[
          LB("Matka zarabia 7 000 zł miesięcznie i rezygnuje z pracy na 24 miesiące. Ile wynosi koszt alternatywny (zł)?",
             168000, "7000*24", ["7 000 · 24 = 168 000 zł"], unit="zł"),
          LB("Przy świadczeniu 1 500 zł miesięcznie przez 24 miesiące jaka część tego kosztu jest pokryta (%)?",
             21.43, "1500*24/168000*100", ["36 000 / 168 000 ≈ 21,43%"], unit="%", tol=0.02),
          LB("Rodzina ma 600 000 zł na dzieci. Przy 3 dzieciach ile wynosi nakład na dziecko (zł)?",
             200000, "600000/3", ["600 000 / 3 = 200 000 zł"], unit="zł"),
          LB("Przy 2 dzieciach nakład na jedno wzrasta o ile procent w porównaniu z 3 dziećmi?",
             50, "(300000/200000-1)*100", ["300 000 / 200 000 = 1,5 → +50%"], unit="%"),
          LB("Dochód względny: zarobki młodych 6 000 zł, aspiracje 8 000 zł. Ile wynosi wskaźnik (dochód / aspiracje)?",
             0.75, "6000/8000", ["6 000 / 8 000 = 0,75"], unit="", tol=0.0001),
          LB("Ile lat dzieli pracę Beckera o płodności (1960) od jego Nagrody Nobla (1992)?",
             32, "1992-1960", ["1992 − 1960 = 32"], unit="lata"),
      ],
      case=[
          PR("W kraju X płace kobiet szybko rosną, ale żłobków brakuje, a powrót do pracy po urlopie jest trudny. Dzietność spada mimo wysokich zasiłków na dzieci.",
             W("Jak teoria Beckera wyjaśnia spadek dzietności?",
               "Rośnie koszt alternatywny wychowania dziecka, a zasiłki go nie rekompensują", "Zasiłki są za wysokie", "Kobiety zarabiają za mało",
               why="Utracone zarobki rosną szybciej niż transfery."),
             W("Jaka polityka byłaby bardziej skuteczna według tej teorii?",
               "Rozbudowa żłobków i elastycznej pracy, by łączyć pracę z rodzicielstwem", "Zakaz pracy kobiet", "Likwidacja zasiłków bez zastępstwa",
               why="Obniża koszt alternatywny zamiast go rekompensować."),
             PF("Według Beckera wzrost dochodów działa na płodność także efektem dochodowym (stać nas na więcej dzieci).", True,
                why="Efekt substytucji i dochodowy działają w przeciwnych kierunkach."),
          ),
          PR("Rocznik urodzony w czasie niżu wchodzi na rynek pracy: firmy konkurują o pracowników, płace szybko rosną, a ceny mieszkań względem płac spadają.",
             W("Czego spodziewałby się Easterlin w tym pokoleniu?",
               "Wyższej dzietności niż w pokoleniu rodziców z wyżu", "Niższej dzietności", "Braku związku",
               why="Wysoki dochód względny młodych."),
             W("Co mogłoby osłabić ten efekt?",
               "Bardzo wysokie aspiracje materialne lub wysokie koszty mieszkań", "Niskie ceny mieszkań", "Dobre zarobki",
               why="Dochód względny zależy też od aspiracji."),
             PF("Hipoteza Easterlina pomaga wyjaśnić baby boom w USA po II wojnie światowej.", True,
                why="Małe roczniki z lat 30. miały dobrą sytuację na rynku pracy."),
          ),
      ]),
    L(6, "Optimum zaludnienia, determinanty płodności, długowieczność i pułapka niskiej dzietności",
      "Rozumieć, kiedy kraj jest niedo- lub przeludniony według teorii optimum, przez jakie czynniki działają wpływy na dzietność (model Bongaartsa), co oznacza kompresja zachorowalności, dlaczego dochód i dzietność są odwrotnie powiązane oraz czym jest pułapka niskiej dzietności.",
      ["Teoria optimum zaludnienia", "Bliższe determinanty płodności (Davis–Blake, Bongaarts)", "Kompresja zachorowalności i teorie długowieczności", "Paradoks ekonomiczno-demograficzny", "Pułapka niskiej dzietności"],
      [S("Encyclopedia.com – Cannan, Edwin (optimum population)", "https://www.encyclopedia.com/social-sciences/encyclopedias-almanacs-transcripts-and-maps/cannan-edwin", "2026-10-10"),
       S("Demographic Research 33(19) – proximate determinants of fertility", "https://www.demographic-research.org/volumes/vol33/19/33-19.pdf", "2026-10-10"),
       S("Fries – Compression of morbidity (PMC 3163136)", "https://pmc.ncbi.nlm.nih.gov/articles/PMC3163136", "2026-10-10"),
       S("Lutz, Skirbekk, Testa – The low fertility trap hypothesis (IIASA)", "https://iiasa-9.eprints-hosting.org/id/eprint/8079/1/IR-06-017.pdf", "2026-10-10"),
       S("Wikipedia – Income and fertility", "https://en.wikipedia.org/wiki/Income_and_fertility", "2026-10-10")],
      explain=[
          K("Optimum zaludnienia",
            "K. Wicksell i E. Cannan pytali: ilu ludzi powinno żyć w kraju, by przy danych zasobach i technice dochód na mieszkańca był najwyższy? Dopóki kolejni mieszkańcy podnoszą dochód per capita (korzyści skali, podział pracy), kraj jest niedoludniony; gdy go obniżają (malejące przychody z ziemi i kapitału) – przeludniony. Optimum przesuwa się z postępem technicznym, a sama teoria pomija podział dochodu."),
          K("Bliższe determinanty płodności",
            "Dochód, religia czy polityka rodzinna wpływają na liczbę urodzeń tylko przez zmienne pośredniczące. K. Davis i J. Blake (1956) wymienili ich 11. J. Bongaarts (1978) wyróżnił cztery najważniejsze: odsetek kobiet w związkach, antykoncepcję, przerywanie ciąży i niepłodność poporodową (karmienie piersią). Każda obniża biologiczną płodność potencjalną (ok. 15 dzieci na kobietę).",
            w="TFR = Cm · Cc · Ca · Ci · TF"),
          K("Kompresja czy ekspansja zachorowalności",
            "J. Fries (1980): jeśli choroby przewlekłe pojawiają się coraz później, a wiek zgonu rośnie wolniej, okres życia w chorobie się skraca (kompresja), a krzywa przeżycia staje się „prostokątna”. E. Gruenberg (1977) twierdził odwrotnie – medycyna ratuje chorych, więc lat w chorobie przybywa (ekspansja). K. Manton (1982) – choroby trwają dłużej, ale są łagodniejsze (dynamiczna równowaga). Od tego zależą przyszłe koszty opieki."),
          K("Paradoks ekonomiczno-demograficzny",
            "Malthus sądził, że wyższy dochód to więcej dzieci. W praktyce bogatsze kraje mają niższą dzietność. Wyjaśnienia: rośnie koszt alternatywny czasu rodziców (zwłaszcza zarobki kobiet), rodzice inwestują w „jakość” dzieci zamiast ich liczby (G. Becker), wydłuża się edukacja, zmieniają się wartości. J.A. Majcherek podkreśla, że dzietność spada mimo poprawy warunków życia rodzin, więc doraźne zachęty finansowe mają ograniczoną skuteczność."),
          K("Pułapka niskiej dzietności",
            "W. Lutz, V. Skirbekk i M.R. Testa (2006): gdy dzietność długo jest bardzo niska (ok. 1,5 i mniej), działają trzy mechanizmy samopodtrzymujące – demograficzny (coraz mniej przyszłych matek), socjologiczny (mała rodzina staje się normą dla kolejnych pokoleń) i ekonomiczny (aspiracje rosną szybciej niż oczekiwane dochody młodych). Wniosek: łatwiej zapobiec wpadnięciu w pułapkę, niż z niej wyjść."),
          W("Według teorii optimum kraj jest przeludniony, gdy:",
            "Dalszy wzrost liczby ludności obniża dochód na mieszkańca", "Gęstość zaludnienia przekracza 100 osób/km²", "Brakuje mieszkań",
            why="Kryterium jest dochód per capita, a nie gęstość."),
          W("Który czynnik należy do czterech głównych bliższych determinant płodności Bongaartsa?",
            "Stosowanie antykoncepcji", "Poziom PKB", "Religia", "Wysokość zasiłku rodzinnego",
            why="PKB, religia i zasiłki działają tylko pośrednio – przez determinanty bliższe."),
          PF("Hipoteza kompresji zachorowalności zakłada, że liczba lat życia w chorobie maleje.", True,
             why="Początek chorób przesuwa się szybciej niż wiek zgonu."),
      ],
      mech=[
          KT("Determinanta bliższa czy dalsza?",
             {"Bliższa (pośrednicząca)": ["Odsetek kobiet w związkach", "Przerywanie ciąży", "Karmienie piersią"],
              "Dalsza (społeczno-ekonomiczna)": ["Wykształcenie kobiet", "Dochód rodziny", "Dostęp do żłobków"]},
             why="Czynniki dalsze działają zawsze przez bliższe."),
          LN("Ułóż mechanizm demograficzny pułapki niskiej dzietności.",
             ["Dzietność spada poniżej 1,5", "Kolejne roczniki urodzeń są coraz mniejsze", "Po 25–30 latach jest mniej kobiet w wieku rozrodczym", "Liczba urodzeń spada nawet przy stałym TFR"],
             why="Ujemne tempo wzrostu jest wbudowane w strukturę wieku."),
          W("Rośnie płaca kobiet przy stałych kosztach opieki nad dziećmi. Czego oczekuje ekonomiczna teoria płodności (Becker)?",
            "Spadku liczby dzieci, bo rośnie koszt alternatywny czasu", "Wzrostu liczby dzieci, bo rośnie dochód", "Braku zmiany",
            why="Efekt substytucji (droższy czas) może przeważyć nad efektem dochodowym."),
          W("Nowa technologia rolnicza znacznie zwiększa wydajność. Co dzieje się z optimum zaludnienia?",
            "Przesuwa się w górę – kraj może utrzymać więcej osób przy wysokim dochodzie per capita", "Przesuwa się w dół", "Nie zmienia się, bo jest stałe",
            why="Optimum zależy od zasobów i techniki."),
          W("Trwanie życia rośnie o 3 lata, a wiek pojawienia się niepełnosprawności – o 5 lat. Co się dzieje?",
            "Kompresja zachorowalności", "Ekspansja zachorowalności", "Przejście demograficzne",
            why="Okres życia z niepełnosprawnością skraca się o 2 lata."),
          M("Które argumenty wyjaśniają odwrotną zależność dochodu i dzietności?",
            ["Wyższy koszt alternatywny czasu rodziców", "Inwestowanie w wykształcenie mniejszej liczby dzieci", "Dłuższa edukacja i późniejsze założenie rodziny", "Niższe trwanie życia w krajach bogatych"], [0, 1, 2],
            why="Trwanie życia jest w bogatych krajach wyższe, a nie niższe."),
      ],
      calc=[
          LB("Ludność 12 mln wytwarza PKB 500 mld zł. Ile wynosi dochód na mieszkańca (tys. zł)?",
             41.67, "500/12", ["500 mld / 12 mln ≈ 41,67 tys. zł"], unit="tys. zł", tol=0.01),
          LB("Przy 14 mln mieszkańców PKB wynosi 560 mld zł (przy 12 mln – 500 mld). O ile procent zmienia się dochód na mieszkańca?",
             -4.0, "(560/14)/(500/12)*100-100", ["560 / 14 = 40 tys.; 500 / 12 ≈ 41,67 tys.", "40 / 41,67 − 1 ≈ −4,0% – kraj jest przeludniony"], unit="%", tol=0.01),
          LB("Model Bongaartsa: płodność potencjalna 15,3, Cm = 0,6, Cc = 0,3, Ca = 1, Ci = 0,9. Ile wynosi TFR?",
             2.48, "15.3*0.6*0.3*1*0.9", ["15,3 · 0,6 · 0,3 · 1 · 0,9 ≈ 2,48"], unit="", tol=0.01),
          LB("Trwanie życia wzrasta z 80 do 83 lat, a wiek początku niepełnosprawności – z 70 do 75 lat. O ile lat zmienia się okres życia z niepełnosprawnością?",
             -2, "(83-75)-(80-70)", ["Przedtem 80 − 70 = 10 lat, potem 83 − 75 = 8 lat", "8 − 10 = −2 lata"], unit="lata", tol=0),
          LB("Rocznik 200 tys. kobiet ma TFR 1,2. Udział dziewczynek wśród urodzeń wynosi 48,6%. Ile córek (tys.) urodzi ta kohorta (bez zgonów)?",
             116.64, "200*1.2*0.486", ["200 · 1,2 = 240 tys. dzieci", "240 · 0,486 = 116,64 tys. dziewczynek"], unit="tys.", tol=0.01),
          LB("O ile procent następne pokolenie matek (116,64 tys.) jest mniejsze od pokolenia 200 tys.?",
             41.68, "(1-116.64/200)*100", ["1 − 116,64 / 200 = 0,4168 → 41,68%"], unit="%", tol=0.01),
          LB("Matka zarabia 8 000 zł miesięcznie i przerywa pracę na 24 miesiące. Ile wynosi utracony dochód (koszt alternatywny) w tys. zł?",
             192, "8*24", ["8 000 · 24 = 192 000 zł"], unit="tys. zł", tol=0.01),
      ],
      case=[
          PR("Kraj Y od 15 lat ma dzietność ok. 1,2. Rząd wprowadził wysoki zasiłek na każde dziecko, ale liczba urodzeń prawie się nie zmieniła. Badania pokazują, że młodzi uważają jedno dziecko za „normalną” rodzinę, a mieszkania są bardzo drogie.",
             W("Jaką hipotezę ilustruje ta sytuacja?",
               "Pułapkę niskiej dzietności", "Optimum zaludnienia", "Kompresję zachorowalności",
               why="Działają mechanizmy socjologiczny (norma małej rodziny) i ekonomiczny (aspiracje a dochody)."),
             W("Który mechanizm pułapki opisuje przekonanie, że jedno dziecko to „normalna” rodzina?",
               "Socjologiczny", "Demograficzny", "Biologiczny",
               why="Kolejne pokolenia przejmują wzorzec małej rodziny."),
             PF("Według autorów hipotezy łatwiej zapobiec wpadnięciu w pułapkę niż z niej wyjść.", True,
                why="Mechanizmy samopodtrzymujące utrwalają niską dzietność."),
          ),
          PR("Ministerstwo zdrowia planuje wydatki na opiekę długoterminową do 2050 r. Jeden zespół zakłada, że kolejne pokolenia seniorów będą zdrowsze i krócej niesamodzielne; drugi – że dłuższe życie oznacza więcej lat z chorobami przewlekłymi i demencją.",
             W("Założenie pierwszego zespołu odpowiada hipotezie:",
               "Kompresji zachorowalności (Fries)", "Ekspansji zachorowalności (Gruenberg)", "Przejścia epidemiologicznego",
               why="Okres złego zdrowia skraca się mimo dłuższego życia."),
             W("Przy którym założeniu prognozowane wydatki będą wyższe?",
               "Przy ekspansji zachorowalności", "Przy kompresji zachorowalności", "Wydatki nie zależą od tego założenia",
               why="Więcej lat w chorobie to więcej opieki."),
             PF("Hipoteza dynamicznej równowagi (Manton) zakłada, że choroby trwają dłużej, ale są łagodniejsze.", True,
                why="To pośrednie stanowisko między kompresją a ekspansją."),
          ),
      ]),
]
