# -*- coding: utf-8 -*-
# Zrozumienie – Demografia / Osoby
D = "2026-10-08"
ECMAL = S("Econlib – Thomas Robert Malthus (biografia)", "https://www.econlib.org/library/Enc/bios/Malthus.html", D)
OWIDT = S("Our World in Data – Demographic transition", "https://ourworldindata.org/demographic-transition", D)
ECBEC = S("Econlib – Gary S. Becker (biografia)", "https://www.econlib.org/library/Enc/bios/Becker.html", D)
NOBBEC = S("Nobelprize.org – Gary S. Becker, nagroda 1992", "https://www.nobelprize.org/prizes/economic-sciences/1992/becker/facts/", D)
NOBLEW = S("Nobelprize.org – W. Arthur Lewis, nagroda 1979", "https://www.nobelprize.org/prizes/economic-sciences/1979/lewis/facts/", D)
NOBDIA = S("Nobelprize.org – Peter A. Diamond, nagroda 2010", "https://www.nobelprize.org/prizes/economic-sciences/2010/diamond/facts/", D)
IOM = S("IOM – Międzynarodowa Organizacja ds. Migracji", "https://www.iom.int/", D)
WBMIG = S("Bank Światowy – Migration (temat)", "https://www.worldbank.org/en/topic/migration", D)
BARR = S("N. Barr, Reforming Pensions: Myths, Truths, and Policy Choices (IMF WP/00/139)", "https://www.imf.org/external/pubs/ft/wp/2000/wp00139.pdf", D)
NBERGA = S("NBER – Auerbach, Gokhale, Kotlikoff: Generational Accounts (1991)", "https://www.nber.org/papers/w3589", D)
GPREV = S("Springer – C. Goodhart, M. Pradhan, The Great Demographic Reversal (2020)", "https://link.springer.com/book/10.1007/978-3-030-42657-6", D)
SUMM = S("L. Summers (2014), U.S. Economic Prospects: Secular Stagnation, Hysteresis, and the Zero Lower Bound", "https://larrysummers.com/publication/u-s-economic-prospects-secular-stagnation-hysteresis-and-the-zero-lower-bound/", D)
HANS = S("Conversable Economist – Secular Stagnation: Back to Alvin Hansen", "https://conversableeconomist.com/2013/12/12/secular-stagnation-back-to-alvin-hansen/", D)
OBMO = S("Ośrodek Badań nad Migracjami UW – prof. Marek Okólski", "https://www.migracje.uw.edu.pl/zespol/marek-okolski-2/", D)
OBMF = S("Ośrodek Badań nad Migracjami UW – Agnieszka Fihel", "https://www.migracje.uw.edu.pl/zespol/agnieszka-fihel-2/", D)
SDREC = S("Studia Demograficzne 2/2012 (recenzja: Okólski, Fihel, Demografia. Współczesne zjawiska i teorie)", "https://econjournals.sgh.waw.pl/SD/issue/view/283", D)

LESSONS = [
    L(1, "Twórcy teorii ludności i przejścia demograficznego",
      "Rozumieć wkład T.R. Malthusa, F. Notesteina oraz D. van de Kaa i R. Lesthaeghe’a w wyjaśnianie zmian liczby ludności i umieć zastosować ich idee do współczesnych zjawisk.",
      ["Malthus Thomas", "Notestein Frank", "van de Kaa Dirk, Lesthaeghe Ron"],
      [ECMAL, OWIDT],
      explain=[
          K("Thomas Malthus (1766–1834)",
            "Angielski duchowny i ekonomista, autor „Prawa ludności” (1798). Twierdził, że ludność rośnie geometrycznie, a żywność arytmetycznie, więc wzrost ludności hamują głód, choroby i wojny (hamulce pozytywne) lub późne małżeństwa i wstrzemięźliwość (hamulce prewencyjne). Jego model dobrze opisuje gospodarki przedprzemysłowe (pułapka maltuzjańska), ale nie przewidział rewolucji przemysłowej i spadku płodności."),
          K("Frank Notestein (1902–1983)",
            "Amerykański demograf z Princeton, w 1945 r. sformułował klasyczną wersję teorii przejścia demograficznego: spadek umieralności, a potem rozrodczości wraz z modernizacją (urbanizacja, edukacja, industrializacja). Był pierwszym dyrektorem Wydziału Ludności ONZ. Teoria stała się podstawą prognoz ludności świata."),
          W("Kto sformułował klasyczną teorię przejścia demograficznego w 1945 r.?",
            "F. Notestein", "T. Malthus", "G. Becker",
            why="Notestein opisał przejście od wysokiej do niskiej rozrodczości i umieralności."),
          K("Dirk van de Kaa i Ron Lesthaeghe",
            "Holenderski i belgijski demograf w 1986 r. zaproponowali koncepcję drugiego przejścia demograficznego: od lat 60. w Europie dzietność spada trwale poniżej zastępowalności z powodu zmian wartości – indywidualizmu, samorealizacji, sekularyzacji. Przejawy: odkładanie małżeństw i rodzicielstwa, kohabitacja, rozwody, urodzenia pozamałżeńskie."),
          K("Co łączy te koncepcje",
            "Wszystkie wiążą procesy ludnościowe z warunkami gospodarczymi i społecznymi: Malthus – z zasobami, Notestein – z modernizacją, van de Kaa i Lesthaeghe – ze zmianą wartości. Każda dobrze opisuje inny etap rozwoju społeczeństw."),
          PF("Koncepcja drugiego przejścia demograficznego akcentuje zmiany wartości i stylu życia.", True,
             why="Indywidualizm i samorealizacja są w niej kluczowe."),
      ],
      mech=[
          KT("Czyja idea?",
             {"T. Malthus": ["Hamulce pozytywne i prewencyjne wzrostu ludności", "Postęp geometryczny ludności i arytmetyczny żywności"],
              "F. Notestein": ["Spadek umieralności, a potem rozrodczości w procesie modernizacji"],
              "Van de Kaa i Lesthaeghe": ["Dzietność poniżej zastępowalności z powodu zmian wartości", "Wzrost kohabitacji i urodzeń pozamałżeńskich"]},
             why="Trzy etapy myśli o ludności."),
          LN("Ułóż koncepcje chronologicznie.",
             ["Malthus – „Prawo ludności” (1798)", "Notestein – przejście demograficzne (1945)", "Van de Kaa i Lesthaeghe – drugie przejście demograficzne (1986)"],
             why="Od teorii przedprzemysłowej do postmodernistycznej."),
          W("Dlaczego przewidywania Malthusa nie sprawdziły się w Europie XIX–XX w.?",
            "Postęp techniczny i spadek dzietności przerwały pułapkę maltuzjańską", "Bo ludność przestała rosnąć już w 1800 r.", "Bo żywność rosła geometrycznie od zawsze",
            why="Rewolucja przemysłowa i przejście demograficzne."),
          W("Które zjawisko w Polsce najlepiej opisuje koncepcja van de Kaa i Lesthaeghe’a?",
            "Wzrost wieku matek przy pierwszym dziecku do 29,5 roku", "Wysoka umieralność niemowląt", "Głód jako hamulec wzrostu",
            why="Odkładanie rodzicielstwa to przejaw drugiego przejścia."),
          M("Jakie hamulce wzrostu ludności opisał Malthus?",
            ["Głód", "Epidemie", "Późne małżeństwa", "Programy 800 plus"], [0, 1, 2],
            why="Malthus żył na przełomie XVIII i XIX w."),
          PF("Notestein był związany z Wydziałem Ludności ONZ.", True,
             why="Był jego pierwszym dyrektorem."),
      ],
      calc=[
          LB("Ile lat dzieli „Prawo ludności” (1798) od teorii Notesteina (1945)?",
             147, "1945-1798", ["1945 − 1798 = 147"], unit="lat"),
          LB("Ile lat dzieli teorię Notesteina (1945) od koncepcji drugiego przejścia (1986)?",
             41, "1986-1945", ["1986 − 1945 = 41"], unit="lat"),
          LB("Ludność według Malthusa podwaja się co 25 lat. Ile razy wzrośnie w ciągu 75 lat?",
             8, "2**3", ["2³ = 8"], unit="razy"),
          LB("Żywność rośnie co 25 lat o tę samą wielkość (1, 2, 3…). Ile razy wzrośnie w ciągu 75 lat?",
             4, "1+3", ["1 + 3 = 4"], unit="razy"),
          LB("Ile żywności na osobę zostanie po 75 latach (4 / 8)?",
             0.5, "4/8", ["4 / 8 = 0,5"], unit="", tol=0.0001),
          LB("Ile lat żył Malthus (1766–1834)?",
             68, "1834-1766", ["1834 − 1766 = 68"], unit="lat"),
      ],
      case=[
          PR("Uczeń porównuje kraj afrykański (TFR 5, szybki spadek umieralności) i Hiszpanię (TFR 1,1, rosnący wiek matek, wiele związków nieformalnych).",
             W("Której koncepcji użyć do opisu kraju afrykańskiego?",
               "Przejścia demograficznego Notesteina", "Drugiego przejścia demograficznego", "Teorii akordowej Taylora",
               why="Kraj jest w trakcie pierwszego przejścia."),
             W("Której koncepcji użyć do opisu Hiszpanii?",
               "Drugiego przejścia demograficznego", "Pułapki maltuzjańskiej", "Modelu Lewisa",
               why="Niska dzietność i zmiany wzorców rodzinnych."),
             PF("Różne kraje mogą być jednocześnie na różnych etapach przemian demograficznych.", True,
                why="Tempo modernizacji jest różne."),
          ),
          PR("W pewnym regionie świata plony rosną dzięki nowym odmianom, ale ludność rośnie tak szybko, że dochód na osobę stoi w miejscu od dekad.",
             W("Czyja teoria najlepiej opisuje sytuację?",
               "Malthusa", "Van de Kaa", "Diamonda",
               why="Wzrost produkcji „zjada” wzrost ludności."),
             W("Co mogłoby przerwać tę sytuację?",
               "Spadek dzietności wraz z edukacją i urbanizacją oraz szybki postęp techniczny", "Wyższa dzietność", "Wojna",
               why="Przejście demograficzne i wzrost wydajności."),
             PF("Pułapka maltuzjańska nie jest nieunikniona.", True,
                why="Kraje rozwinięte z niej wyszły."),
          ),
      ]),

    L(2, "Ekonomiści płodności i rozwoju: Becker, Easterlin, Lewis",
      "Rozumieć ekonomiczne podejście G. Beckera do decyzji o dzieciach, hipotezę względnego dochodu R. Easterlina oraz model rozwoju z nadwyżką siły roboczej W.A. Lewisa.",
      ["Becker Gary", "Easterlin Richard", "Lewis W. Arthur"],
      [ECBEC, NOBBEC, NOBLEW],
      explain=[
          K("Gary Becker (1930–2014)",
            "Amerykański ekonomista ze szkoły chicagowskiej, Nobel 1992 za rozszerzenie analizy mikroekonomicznej na zachowania pozarynkowe (rodzina, dyskryminacja, przestępczość, kapitał ludzki). W teorii płodności: dzieci jako „dobro”, koszt alternatywny czasu matki, wybór między liczbą a „jakością” dzieci – wyjaśnia niską dzietność bogatych społeczeństw."),
          K("Richard Easterlin (ur. 1926)",
            "Amerykański ekonomista i demograf. Hipoteza względnego dochodu: płodność zależy od dochodów młodych dorosłych w porównaniu z aspiracjami wyniesionymi z domu; małe roczniki mają lepszą sytuację i więcej dzieci – stąd cykle demograficzne (baby boom). Znany też z „paradoksu Easterlina” w badaniach szczęścia."),
          W("Który autor wyjaśniał baby boom w USA dobrą sytuacją małych roczników z lat 30.?",
            "R. Easterlin", "G. Becker", "W.A. Lewis",
            why="To hipoteza względnego dochodu."),
          K("W. Arthur Lewis (1915–1991)",
            "Ekonomista z Saint Lucia, Nobel 1979 (razem z T. Schultzem) za badania nad rozwojem gospodarczym. Model gospodarki dualnej (1954): przemysł zatrudnia nadwyżkę siły roboczej ze wsi przy stałych, niskich płacach, aż do punktu zwrotnego, w którym płace zaczynają rosnąć."),
          K("Wspólny mianownik",
            "Wszyscy trzej łączą decyzje demograficzne i rynek pracy: Becker – przez koszt czasu, Easterlin – przez sytuację roczników na rynku pracy, Lewis – przez podaż pracy z sektora tradycyjnego."),
          PF("Lewis otrzymał Nagrodę Nobla razem z Theodore’em Schultzem.", True,
             why="W 1979 r. za badania nad rozwojem gospodarczym."),
      ],
      mech=[
          KT("Czyja koncepcja?",
             {"G. Becker": ["Koszt alternatywny czasu matki", "Wybór między liczbą a „jakością” dzieci"],
              "R. Easterlin": ["Dochód względny młodych wobec aspiracji", "Cykle liczebności roczników"],
              "W.A. Lewis": ["Nadwyżka siły roboczej w rolnictwie i punkt zwrotny"]},
             why="Trzech ekonomistów, trzy mechanizmy."),
          LN("Ułóż wydarzenia chronologicznie.",
             ["Lewis – model gospodarki dualnej (1954)", "Becker – ekonomiczna analiza płodności (1960)", "Lewis – Nagroda Nobla (1979)", "Becker – Nagroda Nobla (1992)"],
             why="Chronologia dorobku i nagród."),
          W("Wzrost płac kobiet obniża dzietność. Czyja teoria to przewiduje?",
            "G. Beckera – przez wzrost kosztu alternatywnego", "W.A. Lewisa – przez punkt zwrotny", "T. Malthusa – przez głód",
            why="Efekt substytucji w teorii Beckera."),
          W("Dlaczego model Lewisa jest ważny dla zrozumienia Chin ok. 2010 r.?",
            "Opisuje koniec nadwyżki siły roboczej i szybki wzrost płac", "Opisuje spadek umieralności", "Dotyczy wyłącznie emerytur",
            why="Chiny osiągnęły punkt zwrotny Lewisa."),
          M("Za co Becker otrzymał Nagrodę Nobla?",
            ["Analizę ekonomiczną rodziny", "Teorię kapitału ludzkiego", "Analizę dyskryminacji", "Model ISLM"], [0, 1, 2],
            why="Model IS-LM to dorobek Hicksa i Hansena."),
          PF("Easterlin badał także związek dochodu ze szczęściem.", True,
             why="Stąd „paradoks Easterlina”."),
      ],
      calc=[
          LB("Ile lat dzieli model Lewisa (1954) od pracy Beckera o płodności (1960)?",
             6, "1960-1954", ["1960 − 1954 = 6"], unit="lat"),
          LB("Ile lat dzieli Nobla dla Lewisa (1979) i dla Beckera (1992)?",
             13, "1992-1979", ["1992 − 1979 = 13"], unit="lat"),
          LB("Koszt alternatywny: płaca matki 6 000 zł, przerwa 18 miesięcy. Ile wynosi (zł)?",
             108000, "6000*18", ["6 000 · 18 = 108 000 zł"], unit="zł"),
          LB("Płaca rośnie o 25%. O ile wzrośnie koszt alternatywny tej przerwy (zł)?",
             27000, "108000*0.25", ["108 000 · 0,25 = 27 000 zł"], unit="zł"),
          LB("Dochód względny: zarobki 7 200 zł, aspiracje 6 000 zł. Ile wynosi wskaźnik?",
             1.2, "7200/6000", ["7 200 / 6 000 = 1,2"], unit="", tol=0.0001),
          LB("Ile lat dzieli urodzenie Easterlina (1926) od wydania jego książki „Birth and Fortune” (1980)?",
             54, "1980-1926", ["1980 − 1926 = 54"], unit="lata"),
      ],
      case=[
          PR("W kraju X po wojnie mało liczne roczniki weszły na rynek pracy przy szybkim wzroście gospodarczym. Dzietność wzrosła. Ich dzieci, liczne roczniki, miały trudniejszą sytuację i dzietność spadła.",
             W("Czyja hipoteza wyjaśnia ten cykl?",
               "R. Easterlina", "G. Beckera", "T. Malthusa",
               why="Liczebność rocznika wpływa na jego dochód względny."),
             W("Jaki czynnik wpływa na decyzje według tej hipotezy?",
               "Dochód młodych w porównaniu z aspiracjami z domu rodzinnego", "Tylko cena żywności", "Wyłącznie religia",
               why="To istota hipotezy względnego dochodu."),
             PF("Hipoteza przewiduje cykle w liczbie urodzeń.", True,
                why="Na przemian liczne i mało liczne roczniki."),
          ),
          PR("Rząd kraju Y rozważa: podnieść zasiłki na dzieci czy zbudować sieć żłobków pozwalających matkom szybciej wracać do pracy.",
             W("Które rozwiązanie wynika z teorii Beckera o koszcie alternatywnym?",
               "Żłobki obniżające koszt alternatywny czasu matek", "Wyłącznie zakaz pracy kobiet", "Podwyżka podatków dla rodziców",
               why="Obniżają koszt alternatywny posiadania dzieci."),
             W("Jak Becker oceniłby efekt zasiłku?",
               "Efekt dochodowy może podnieść dzietność, ale nie usuwa kosztu alternatywnego", "Na pewno zwiększy dzietność dwukrotnie", "Zawsze obniży dzietność",
               why="Transfer działa przez dochód, nie przez koszt czasu."),
             PF("Teoria Beckera wyjaśnia, dlaczego wzrost wykształcenia kobiet wiąże się z niższą dzietnością.", True,
                why="Rośnie wartość ich czasu na rynku pracy."),
          ),
      ]),

    L(3, "Badacze migracji: Ravenstein, Lee, Todaro, Stark, Piore",
      "Rozumieć wkład najważniejszych badaczy migracji – od „praw migracji” Ravensteina, przez model push–pull Lee i model Todaro, po nową ekonomię migracji Starka i dualny rynek pracy Piore’a.",
      ["Ravenstein Ernst Georg", "Lee Everett", "Todaro Michael", "Stark Oded", "Piore Michael"],
      [IOM, WBMIG],
      explain=[
          K("Ravenstein i Lee",
            "E.G. Ravenstein, geograf niemieckiego pochodzenia działający w Anglii, na podstawie spisów ludności sformułował „prawa migracji” (1885, 1889): migracje na krótkie odległości, etapowość, strumienie i przeciwstrumienie, przewaga motywów ekonomicznych. E. Lee (1966) uporządkował je w model czynników wypychających i przyciągających, przeszkód pośrednich i czynników osobistych."),
          K("Todaro",
            "M. Todaro (1969) i model Harrisa–Todaro (1970): migracja ze wsi do miast zależy od oczekiwanej płacy – płacy w mieście pomnożonej przez prawdopodobieństwo znalezienia pracy. Wyjaśnia, dlaczego migracja do miast trwa mimo wysokiego bezrobocia miejskiego w krajach rozwijających się."),
          W("Kto wprowadził do analizy migracji oczekiwaną płacę uwzględniającą ryzyko bezrobocia?",
            "M. Todaro", "E.G. Ravenstein", "M. Piore",
            why="To model Todaro i Harrisa–Todaro."),
          K("Stark i Piore",
            "O. Stark – nowa ekonomia migracji zarobkowych (z D. Bloomem 1985; „The Migration of Labor”, 1991): decyzję podejmuje rodzina, by dywersyfikować ryzyko i poprawić pozycję względną (względna deprywacja). M. Piore („Birds of Passage”, 1979): migracje są napędzane popytem na pracę w wtórnym segmencie rynku pracy krajów rozwiniętych."),
          K("Porównanie perspektyw",
            "Ravenstein i Lee – opis prawidłowości i czynników; Todaro – decyzja jednostki według oczekiwanej płacy; Stark – decyzja gospodarstwa domowego i ryzyko; Piore – popyt w kraju przyjmującym. Razem wyjaśniają różne strony tego samego zjawiska."),
          PF("Piore wyjaśniał migracje głównie popytem na pracę w krajach przyjmujących.", True,
             why="Teoria dualnego rynku pracy."),
      ],
      mech=[
          KT("Czyja koncepcja?",
             {"E.G. Ravenstein": ["Migracje odbywają się etapami i na krótkie odległości"],
              "E. Lee": ["Czynniki wypychające, przyciągające i przeszkody pośrednie"],
              "M. Todaro": ["Oczekiwana płaca w mieście a bezrobocie"],
              "O. Stark": ["Rodzina dywersyfikuje ryzyko przez migrację członka"],
              "M. Piore": ["Wtórny segment rynku pracy przyciąga migrantów"]},
             why="Pięć klasycznych podejść do migracji."),
          LN("Ułóż prace chronologicznie.",
             ["Ravenstein – „The Laws of Migration” (1885)", "Lee – „A Theory of Migration” (1966)", "Todaro – model migracji do miast (1969)", "Piore – „Birds of Passage” (1979)", "Stark i Bloom – nowa ekonomia migracji (1985)"],
             why="Ewolucja teorii migracji."),
          W("Dlaczego Stark uważał, że migruje rodzina, a nie jednostka?",
            "Decyzja służy dywersyfikacji ryzyka całego gospodarstwa domowego", "Bo jednostki nie podejmują decyzji", "Bo migrują wyłącznie całe rodziny",
            why="Migrant jest „polisą” rodziny."),
          W("Która koncepcja najlepiej wyjaśnia, dlaczego polskie gospodarstwa rolne zatrudniają sezonowo cudzoziemców?",
            "Teoria dualnego rynku pracy Piore’a", "Prawa Ravensteina", "Teoria Malthusa",
            why="Miejscowi unikają prac sezonowych o niskim prestiżu."),
          M("Jakie elementy zawiera model Lee?",
            ["Czynniki w miejscu pochodzenia", "Czynniki w miejscu docelowym", "Przeszkody pośrednie", "Kurs akcji"], [0, 1, 2],
            why="Do tego czynniki osobiste."),
          PF("Ravenstein formułował swoje prawa na podstawie danych ze spisów ludności.", True,
             why="Analizował m.in. brytyjskie spisy."),
      ],
      calc=[
          LB("Ile lat dzieli prawa Ravensteina (1885) od modelu Todaro (1969)?",
             84, "1969-1885", ["1969 − 1885 = 84"], unit="lata"),
          LB("Płaca w mieście 5 000 zł, szansa na pracę 60%. Ile wynosi płaca oczekiwana według Todaro (zł)?",
             3000, "5000*0.6", ["5 000 · 0,6 = 3 000 zł"], unit="zł"),
          LB("Przy płacy wiejskiej 2 400 zł o ile płaca oczekiwana w mieście jest wyższa (zł)?",
             600, "3000-2400", ["3 000 − 2 400 = 600 zł"], unit="zł"),
          LB("Ile lat dzieli „Birds of Passage” (1979) od książki Starka „The Migration of Labor” (1991)?",
             12, "1991-1979", ["1991 − 1979 = 12"], unit="lat"),
          LB("Rodzina ma dochód 30 000 zł; migrant przesyła 12 000 zł rocznie. O ile procent rośnie dochód rodziny?",
             40, "12000/30000*100", ["12 000 / 30 000 = 40%"], unit="%"),
          LB("Ile lat dzieli teorię Lee (1966) od 2026 r.?",
             60, "2026-1966", ["2026 − 1966 = 60"], unit="lat"),
      ],
      case=[
          PR("Badaczka analizuje migrację z małej wsi w Gruzji do Polski: wyjeżdża zwykle jeden członek rodziny, rodzina wspólnie finansuje wyjazd, a przekazy pozwalają kupić maszyny rolnicze. Większość migrantów pracuje w polskich sadach.",
             W("Które dwie teorie najlepiej opisują ten przypadek?",
               "Nowa ekonomia migracji (Stark) i dualny rynek pracy (Piore)", "Malthus i Notestein", "Becker i Easterlin",
               why="Decyzja rodziny i popyt na prace sezonowe."),
             W("Jaką rolę pełnią przekazy w ujęciu Starka?",
               "Dywersyfikują ryzyko i finansują inwestycje rodziny", "Są wyłącznie konsumpcją luksusową", "Nie mają znaczenia",
               why="Zastępują brakujący kredyt i ubezpieczenie."),
             PF("Przypadek nie przeczy modelowi Lee – istnieją tu czynniki wypychające i przyciągające.", True,
                why="Np. niskie dochody na wsi i praca w Polsce."),
          ),
          PR("W stolicy kraju rozwijającego się bezrobocie wynosi 20%, a mimo to tysiące osób co roku przyjeżdżają ze wsi.",
             W("Czyj model wyjaśnia ten paradoks?",
               "Todaro (Harrisa–Todaro)", "Ravensteina", "Piore’a",
               why="Decyduje oczekiwana płaca w mieście."),
             W("Jaki skutek może mieć tworzenie miejsc pracy tylko w stolicy?",
               "Wzrost napływu migrantów i utrzymanie bezrobocia", "Spadek migracji do zera", "Brak skutków",
               why="Rośnie płaca oczekiwana w mieście."),
             PF("Rozwój obszarów wiejskich może ograniczyć napływ do stolicy.", True,
                why="Zmniejsza różnicę dochodów oczekiwanych."),
          ),
      ]),

    L(4, "Ekonomiści emerytur i finansów pokoleń: Barr, Diamond, Aaron, Kotlikoff",
      "Rozumieć wkład N. Barra, P. Diamonda, H. Aarona i L. Kotlikoffa w ekonomię emerytur i finansów publicznych w starzejących się społeczeństwach.",
      ["Barr Nicholas", "Diamond Peter", "Aaron Henry", "Kotlikoff Laurence"],
      [BARR, NOBDIA, NBERGA],
      explain=[
          K("Nicholas Barr i Peter Diamond",
            "N. Barr (London School of Economics) i P. Diamond (MIT, Nobel 2010 za analizę rynków z frykcjami poszukiwań) napisali m.in. „Reforming Pensions: Principles and Policy Choices” (2008). Cele systemu: wygładzanie konsumpcji, ubezpieczenie, łagodzenie ubóstwa, redystrybucja. Krytykują mity o automatycznej wyższości systemów kapitałowych – liczy się przyszła produkcja i jakość instytucji."),
          K("Henry Aaron",
            "Amerykański ekonomista (Brookings Institution). W 1966 r. opisał „paradoks ubezpieczeń społecznych”: system repartycyjny daje wyższą stopę zwrotu niż kapitałowy, gdy tempo wzrostu ludności i płac przewyższa stopę procentową (n + g > r) – warunek Aarona."),
          W("Kto sformułował warunek n + g > r dla systemów emerytalnych?",
            "H. Aaron", "N. Barr", "L. Kotlikoff",
            why="Warunek Aarona z 1966 r."),
          K("Laurence Kotlikoff",
            "Amerykański ekonomista (Boston University), współtwórca rachunkowości pokoleniowej (z A. Auerbachem i J. Gokhalem, 1991), autor (z S. Burnsem) „The Coming Generational Storm” (2004). Twierdzi, że roczny deficyt nie pokazuje obciążeń przenoszonych na przyszłe pokolenia – trzeba liczyć „lukę fiskalną”."),
          K("Wspólne przesłanie",
            "Starzenie się wymaga patrzenia w długim horyzoncie: na produkcję (Barr, Diamond), na demografię i płace (Aaron) oraz na międzypokoleniowy podział obciążeń (Kotlikoff)."),
          PF("Peter Diamond otrzymał Nagrodę Nobla w 2010 r.", True,
             why="Za analizę rynków z frykcjami poszukiwań."),
      ],
      mech=[
          KT("Czyja koncepcja?",
             {"N. Barr i P. Diamond": ["Cele systemu emerytalnego i mity reform", "Znaczenie przyszłej produkcji dla emerytów"],
              "H. Aaron": ["Porównanie stopy zwrotu PAYG i systemu kapitałowego"],
              "L. Kotlikoff": ["Rachunkowość pokoleniowa i luka fiskalna", "Obciążenia przenoszone na przyszłe pokolenia"]},
             why="Różne ujęcia problemu emerytur."),
          LN("Ułóż prace chronologicznie.",
             ["Aaron – paradoks ubezpieczeń społecznych (1966)", "Auerbach, Gokhale, Kotlikoff – rachunki pokoleniowe (1991)", "Barr – mity reform emerytalnych (2000)", "Kotlikoff i Burns – „The Coming Generational Storm” (2004)", "Barr i Diamond – „Reforming Pensions” (2008)"],
             why="Rozwój ekonomii emerytur."),
          W("Rząd zwiększa obietnice emerytalne bez zmian podatków. Który ekonomista najmocniej podkreśliłby obciążenie przyszłych pokoleń?",
            "L. Kotlikoff", "H. Aaron", "E. Lee",
            why="Rachunkowość pokoleniowa pokazuje przeniesienie kosztów."),
          W("Co według Barra i Diamonda decyduje o tym, czy emeryci będą mieli z czego żyć?",
            "Przyszła produkcja gospodarki", "Wyłącznie typ systemu emerytalnego", "Liczba funduszy inwestycyjnych",
            why="Emeryci konsumują przyszłe dobra i usługi."),
          M("Jakie cele systemu emerytalnego wymieniają Barr i Diamond?",
            ["Wygładzanie konsumpcji", "Ubezpieczenie od długowieczności", "Łagodzenie ubóstwa", "Maksymalizację zysków banków"], [0, 1, 2],
            why="Zysk banków nie jest celem systemu."),
          PF("Kotlikoff jest współtwórcą rachunkowości pokoleniowej.", True,
             why="Razem z Auerbachem i Gokhalem (1991)."),
      ],
      calc=[
          LB("Ile lat dzieli warunek Aarona (1966) od rachunków pokoleniowych (1991)?",
             25, "1991-1966", ["1991 − 1966 = 25"], unit="lat"),
          LB("n = 0,4%, g = 1,6%, r = 2,5%. O ile punktów procentowych r przewyższa n + g?",
             0.5, "2.5-(0.4+1.6)", ["2,5 − 2,0 = 0,5"], unit="pkt proc.", tol=0.001),
          LB("Rocznik zapłaci podatki o wartości bieżącej 350 tys. zł, otrzyma świadczenia 290 tys. zł. Ile wynosi jego rachunek pokoleniowy (tys. zł)?",
             60, "350-290", ["350 − 290 = 60 tys. zł"], unit="tys. zł"),
          LB("Ile lat dzieli książkę Barra i Diamonda (2008) od Nobla dla Diamonda (2010)?",
             2, "2010-2008", ["2010 − 2008 = 2"], unit="lata"),
          LB("Luka fiskalna 15% PKB do rozłożenia na 30 lat. Ile procent PKB rocznie (w uproszczeniu)?",
             0.5, "15/30", ["15 / 30 = 0,5% PKB"], unit="% PKB", tol=0.001),
          LB("Ile lat dzieli pracę Aarona (1966) od 2026 r.?",
             60, "2026-1966", ["2026 − 1966 = 60"], unit="lat"),
      ],
      case=[
          PR("Polityk mówi: „Wystarczy przenieść składki do funduszy prywatnych, a emerytury będą bezpieczne”. Inny polityk dodaje: „A deficyt w tym roku jest niski, więc nie ma problemu z obietnicami emerytalnymi”.",
             W("Jak odpowiedzieliby Barr i Diamond pierwszemu politykowi?",
               "Bezpieczeństwo emerytur zależy od przyszłej produkcji, nie tylko od formy finansowania", "Ma całkowitą rację", "Fundusze nie mają ryzyka",
               why="Ich kluczowy argument."),
             W("Jak odpowiedziałby Kotlikoff drugiemu politykowi?",
               "Roczny deficyt nie pokazuje obciążeń przyszłych pokoleń", "Niski deficyt oznacza brak problemów", "Deficyt nie ma znaczenia",
               why="Rachunkowość pokoleniowa patrzy w długim okresie."),
             PF("Obaj politycy pomijają długookresowe skutki demograficzne.", True,
                why="Starzenie się dotyka każdego systemu finansowania."),
          ),
          PR("W kraju o szybkim wzroście liczby pracujących i płac rząd w latach 60. wprowadził hojny system repartycyjny. Po 50 latach liczba pracujących maleje.",
             W("Czyj warunek uzasadniał system w latach 60.?",
               "Aarona – n + g było wysokie", "Malthusa", "Lee",
               why="PAYG dawał wysoki zwrot przy rosnącej populacji."),
             W("Co zmieniło się po 50 latach?",
               "Spadek n obniżył zwrot PAYG", "Wzrósł zwrot PAYG", "Nic",
               why="Mniej pracujących."),
             PF("Warunek Aarona może być spełniony w jednej epoce i niespełniony w innej.", True,
                why="Zależy od demografii i wzrostu płac."),
          ),
      ]),

    L(5, "Demografia i makroekonomia oraz polscy badacze",
      "Rozumieć koncepcje Hansena, Summersa, Goodharta i Pradhana o wpływie demografii na wzrost, stopy procentowe i inflację oraz dorobek polskich demografów M. Okólskiego i A. Fihel.",
      ["Hansen Alvin", "Summers Lawrence", "Goodhart Charles", "Pradhan Manoj", "Okólski Marek", "Fihel Agnieszka"],
      [HANS, SUMM, GPREV, OBMO, OBMF, SDREC],
      explain=[
          K("Alvin Hansen i Lawrence Summers",
            "A. Hansen (Harvard, „amerykański Keynes”) w 1938 r. sformułował hipotezę sekularnej stagnacji – m.in. spadek wzrostu ludności osłabia inwestycje. L. Summers (b. sekretarz skarbu USA) odnowił ją w 2013 r.: naturalna realna stopa procentowa spadła poniżej zera, więc gospodarki rozwinięte cierpią na chroniczny niedobór popytu. Zalecał inwestycje publiczne."),
          K("Charles Goodhart i Manoj Pradhan",
            "Ch. Goodhart (b. członek Komitetu Polityki Pieniężnej Banku Anglii, LSE) i M. Pradhan („The Great Demographic Reversal”, 2020): globalna podaż pracy, która w latach 1980–2010 obniżała płace, inflację i stopy, kurczy się; to ma przynieść wyższe płace, inflację i stopy procentowe oraz mniejsze nierówności."),
          W("Kto twierdzi, że demografia odwraca dezinflacyjne trendy ostatnich dekad?",
            "Goodhart i Pradhan", "Hansen", "Okólski",
            why="Teza o wielkim zwrocie demograficznym."),
          K("Marek Okólski i Agnieszka Fihel",
            "M. Okólski – profesor UW, współtwórca Ośrodka Badań nad Migracjami, badacz migracji z Europy Środkowo-Wschodniej (koncepcja migracji niepełnej – wahadłowej, gdy migrant utrzymuje gospodarstwo domowe w kraju) i transformacji migracyjnej Polski. A. Fihel – demografka z UW (OBM), badaczka migracji i umieralności. Razem napisali podręcznik „Demografia. Współczesne zjawiska i teorie” (Scholar, 2012)."),
          K("Spór o kierunek wpływu",
            "Hansen i Summers akcentują, że wolniejszy wzrost ludności obniża stopy i wzrost; Goodhart i Pradhan – że kurczenie się siły roboczej i konsumpcja emerytów podniosą stopy i inflację. Obie tezy mogą być prawdziwe w różnych fazach starzenia się."),
          PF("Okólski i Fihel są autorami podręcznika „Demografia. Współczesne zjawiska i teorie”.", True,
             why="Wydanego w 2012 r. przez Scholar."),
      ],
      mech=[
          KT("Czyja teza?",
             {"Hansen / Summers": ["Wolniejszy wzrost ludności obniża inwestycje i stopy procentowe", "Zalecenie inwestycji publicznych przy zerowych stopach"],
              "Goodhart / Pradhan": ["Kurcząca się siła robocza podniesie inflację i płace"],
              "Okólski / Fihel": ["Badania migracji z Europy Środkowo-Wschodniej i podręcznik demografii"]},
             why="Trzy perspektywy wpływu demografii."),
          LN("Ułóż chronologicznie.",
             ["Hansen – sekularna stagnacja (1938)", "Okólski i Fihel – podręcznik demografii (2012)", "Summers – powrót hipotezy stagnacji (2013)", "Goodhart i Pradhan – wielki zwrot demograficzny (2020)"],
             why="Od Hansena do współczesnych debat."),
          W("Dlaczego tezy Summersa i Goodharta–Pradhana mogą nie być sprzeczne?",
            "Mogą opisywać różne fazy starzenia się – najpierw nadmiar oszczędności, potem ich spadek", "Bo dotyczą różnych planet", "Bo obie są fałszywe",
            why="Kierunek wpływu demografii zmienia się w czasie."),
          W("Czym zajmuje się Ośrodek Badań nad Migracjami UW?",
            "Badaniem migracji, m.in. z i do Polski", "Polityką pieniężną", "Badaniami kosmicznymi",
            why="Współtworzył go M. Okólski."),
          M("Które zjawiska przewidują Goodhart i Pradhan?",
            ["Wzrost płac realnych", "Wyższą inflację", "Wyższe stopy procentowe", "Trwałą deflację"], [0, 1, 2],
            why="Deflacja to cecha poprzedniej epoki."),
          PF("Hansen sformułował hipotezę sekularnej stagnacji w czasie Wielkiego Kryzysu.", True,
             why="W przemówieniu z grudnia 1938 r."),
      ],
      calc=[
          LB("Ile lat dzieli hipotezę Hansena (1938) od tezy Goodharta i Pradhana (2020)?",
             82, "2020-1938", ["2020 − 1938 = 82"], unit="lata"),
          LB("Ile lat dzieli podręcznik Okólskiego i Fihel (2012) od wystąpienia Summersa (2013)?",
             1, "2013-2012", ["2013 − 2012 = 1"], unit="rok"),
          LB("Nominalna stopa 1%, inflacja 3%. Ile wynosi realna stopa (%)?",
             -2, "1-3", ["1 − 3 = −2%"], unit="%"),
          LB("Płace rosną o 7%, inflacja wynosi 4%. Ile wynosi przybliżony wzrost płac realnych (%)?",
             3, "7-4", ["7 − 4 = 3%"], unit="%"),
          LB("Migrant wahadłowy spędza 4 z 12 miesięcy za granicą. Jaki to procent roku?",
             33.33, "4/12*100", ["4 / 12 ≈ 33,33%"], unit="%", tol=0.02),
          LB("Ile lat dzieli Summersa (2013) od 2026 r.?",
             13, "2026-2013", ["2026 − 2013 = 13"], unit="lat"),
      ],
      case=[
          PR("Na seminarium jedna ekonomistka powołuje się na Summersa, twierdząc, że starzenie się utrzyma niskie stopy procentowe. Drugi powołuje się na Goodharta i Pradhana, przewidując wyższe stopy.",
             W("Jaki argument przemawia za tezą pierwszej ekonomistki?",
               "Wolniejszy wzrost siły roboczej obniża popyt inwestycyjny", "Emeryci wydają oszczędności", "Siła robocza rośnie",
               why="Mniej inwestycji przy nadwyżce oszczędności."),
             W("Jaki argument przemawia za tezą drugiego ekonomisty?",
               "Kurczenie się siły roboczej podnosi płace, a emeryci zmniejszają oszczędności", "Rośnie liczba młodych", "Inflacja spada do zera",
               why="Mechanizm wielkiego zwrotu demograficznego."),
             PF("Rozstrzygnięcie sporu zależy m.in. od tego, jak zmienią się oszczędności i inwestycje w starzejących się gospodarkach.", True,
                why="Stopa naturalna równoważy oszczędności i inwestycje."),
          ),
          PR("W latach 90. wielu Polaków wyjeżdżało na kilka miesięcy do Niemiec do prac sezonowych, wracając regularnie do domów, gdzie pozostawały rodziny i gospodarstwa.",
             W("Jak nazwał takie zjawisko M. Okólski?",
               "Migracją niepełną (wahadłową)", "Drugim przejściem demograficznym", "Pułapką maltuzjańską",
               why="Migrant utrzymuje gospodarstwo domowe w kraju."),
             W("Która ogólna teoria również je opisuje?",
               "Nowa ekonomia migracji – dywersyfikacja ryzyka rodziny", "Teoria Malthusa", "Sekularna stagnacja",
               why="Migracja jako strategia gospodarstwa domowego."),
             PF("Po 2004 r. część migracji z Polski przybrała formę dłuższych, osiedleńczych wyjazdów.", True,
                why="Swobodny przepływ pracowników ułatwił dłuższe wyjazdy."),
          ),
      ]),
]
