# -*- coding: utf-8 -*-
# Zrozumienie – Podstawy finansów / Zabezpieczenie społeczne i emerytury
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-08"
S153 = S("OpenStax, Principles of Economics 3e, 15.3 The Safety Net", OS3 + "15-3-the-safety-net", D)
S155 = S("OpenStax, Principles of Economics 3e, 15.5 Government Policies to Reduce Income Inequality", OS3 + "15-5-government-policies-to-reduce-income-inequality", D)
S174 = S("OpenStax, Principles of Economics 3e, 17.3 How to Accumulate Personal Wealth", OS3 + "17-3-how-to-accumulate-personal-wealth", D)
ZUSG = S("Zakład Ubezpieczeń Społecznych", "https://www.zus.pl/", D)
PPK = S("PFR Portal PPK – mojeppk.pl", "https://www.mojeppk.pl/", D)
SII = S("SII – Limity wpłat w 2026 r. na IKE, IKZE, OIPE i PPE", "https://www.sii.org.pl/18632/analizy/newsroom/limity-wplat-2026-r-ike-ikze-oipe-ppe.html", D)
WAL = S("inFakt – Waloryzacja emerytur 2026", "https://www.infakt.pl/blog/waloryzacja-emerytur-2026-tabela/", D)
MRPIPS = S("Ministerstwo Rodziny, Pracy i Polityki Społecznej", "https://www.gov.pl/web/rodzina", D)

LESSONS = [
    L(1, "System emerytalny w Polsce: filary i zdefiniowana składka",
      "Rozumieć budowę systemu emerytalnego od reformy 1999 r. (trzy filary), różnicę między systemem repartycyjnym a kapitałowym, zasadę zdefiniowanej składki, waloryzację i wiek emerytalny.",
      ["System emerytalny w Polsce (od 1999 r.)", "Wiek emerytalny w Polsce", "Otwarte fundusze emerytalne (OFE)"],
      [ZUSG, WAL],
      explain=[
          K("Repartycja a kapitał",
            "W systemie repartycyjnym (pay-as-you-go) składki dzisiejszych pracowników finansują dzisiejsze emerytury – działa jak umowa między pokoleniami i jest wrażliwy na demografię. W systemie kapitałowym składki inwestuje się na rynku, a emerytura zależy od zgromadzonych aktywów i ich wyników – jest wrażliwy na ryzyko rynkowe."),
          K("Trzy filary po reformie 1999 r.",
            "I filar – ZUS: repartycyjny, ale z indywidualnym kontem i zdefiniowaną składką (składki są zapisywane i waloryzowane, a nie inwestowane). II filar – OFE: kapitałowy, od 2014 r. dobrowolny, część składek trafia na subkonto w ZUS. III filar – dobrowolne oszczędzanie: PPE, IKE, IKZE i od 2019 r. PPK."),
          W("W którym filarze emerytura zależy od wyników inwestycji na giełdzie?",
            "W kapitałowym – OFE i III filar", "Tylko w I filarze ZUS", "W żadnym",
            why="Konto w ZUS jest waloryzowane wskaźnikiem ustawowym, nie wynikami rynku."),
          K("Zdefiniowana składka i waloryzacja",
            "Emerytura = (kapitał na koncie + subkonto) / średnie dalsze trwanie życia w miesiącach. Kapitał rośnie co roku o wskaźnik waloryzacji związany ze wzrostem funduszu płac. Wypłacane emerytury waloryzuje się co roku od 1 marca: inflacja emerycka + co najmniej 20% realnego wzrostu płac. W 2026 r. wskaźnik wyniósł 5,3%, a najniższa emerytura wzrosła do ok. 1 978,49 zł brutto.",
            w="emerytura = kapitał / dalsze trwanie życia (mies.)"),
          K("Wiek emerytalny",
            "Od 1.10.2017 r. powszechny wiek emerytalny wynosi 60 lat dla kobiet i 65 dla mężczyzn (wcześniej był stopniowo podnoszony do 67 lat). Przy zdefiniowanej składce niższy wiek oznacza mniejszy kapitał i dłuższe dalsze trwanie życia – a więc niższą emeryturę, zwłaszcza dla kobiet."),
          PF("W I filarze ZUS składki emerytalne są inwestowane na giełdzie.", False,
             why="Są zapisywane na koncie i waloryzowane, a bieżące wpływy finansują obecne emerytury."),
      ],
      mech=[
          KT("Repartycja czy kapitał?",
             {"Repartycyjny": ["Konto w ZUS (I filar)", "Subkonto w ZUS", "Emerytury finansowane bieżącymi składkami"],
              "Kapitałowy": ["OFE", "IKE", "PPK"]},
             why="Kapitałowy – środki inwestowane i należące do oszczędzającego."),
          LN("Ułóż, jak powstaje emerytura w I filarze.",
             ["Pracownik i pracodawca płacą składkę emerytalną 19,52%", "Składka jest zapisywana na indywidualnym koncie w ZUS", "Co roku zapisany kapitał jest waloryzowany", "Przy przejściu na emeryturę kapitał dzieli się przez dalsze trwanie życia", "Wypłacana emerytura jest co roku waloryzowana od 1 marca"],
             why="System zdefiniowanej składki łączy wpłaty z wysokością świadczenia."),
          W("Kobieta i mężczyzna mają ten sam kapitał, ale kobieta przechodzi na emeryturę w wieku 60 lat, a mężczyzna 65. Kto dostanie wyższą emeryturę?",
            "Mężczyzna", "Kobieta", "Oboje tyle samo",
            why="Kapitał dzieli się przez dłuższe dalsze trwanie życia dla wieku 60 lat."),
          W("Inflacja emerycka 4,2%, realny wzrost płac 5,5%. Ile co najmniej wyniesie waloryzacja emerytur?",
            "Ok. 5,3%", "4,2%", "9,7%",
            why="4,2% + 20% · 5,5% = 4,2% + 1,1% = 5,3%."),
          M("Co zmieniła reforma OFE z 2014 r.?",
            ["Przeniesiono 51,5% aktywów OFE do ZUS", "Udział w OFE stał się dobrowolny", "Wprowadzono stopniowe przenoszenie środków do ZUS przed emeryturą", "Zlikwidowano ZUS"], [0, 1, 2],
            why="ZUS pozostał podstawą systemu."),
          PF("Przy zdefiniowanej składce dłuższe trwanie życia obniża miesięczną emeryturę z tego samego kapitału.", True,
             why="Kapitał rozkłada się na więcej miesięcy."),
      ],
      calc=[
          LB("Kapitał 520 000 zł, dalsze trwanie życia 260 miesięcy. Ile wynosi emerytura (zł)?",
             2000, "520000/260", ["520 000 / 260 = 2000 zł"], unit="zł"),
          LB("Ten sam kapitał (520 000 zł), ale dalsze trwanie życia 215 miesięcy. Ile wynosi emerytura (zł)?",
             2418.6, "520000/215", ["520 000 / 215 ≈ 2418,60 zł"], unit="zł", tol=0.01),
          LB("Najniższa emerytura 1 878,91 zł, waloryzacja 5,3%. Ile wynosi po waloryzacji (zł)?",
             1978.49, "1878.91*1.053", ["1878,91 · 1,053 ≈ 1978,49 zł"], unit="zł", tol=0.01),
          LB("Pensja 7000 zł, składka emerytalna 19,52%. Ile rocznie trafia na konto emerytalne (zł)?",
             16396.8, "7000*0.1952*12", ["7000 · 19,52% = 1366,40", "· 12 = 16 396,80 zł"], unit="zł", tol=0.01),
          LB("Kapitał 300 000 zł waloryzowany przez 5 lat po 7% rocznie. Ile wyniesie (zł)?",
             420765.52, "300000*1.07**5", ["300 000 · 1,07⁵ ≈ 420 765,52 zł"], unit="zł", tol=0.01),
          LB("Emerytura 3000 zł, waloryzacja 5,3%. O ile złotych wzrośnie (zł)?",
             159, "3000*0.053", ["3000 · 5,3% = 159 zł"], unit="zł"),
      ],
      case=[
          PR("Pani Ewa (59 lat) ma na koncie i subkoncie ZUS 480 000 zł. Może przejść na emeryturę w wieku 60 lat (dalsze trwanie życia ok. 260 miesięcy) albo pracować do 65 lat – wtedy kapitał wzrośnie do ok. 650 000 zł, a dalsze trwanie życia wyniesie ok. 215 miesięcy (dane umowne).",
             W("Ile wyniesie emerytura w wieku 60 lat (w przybliżeniu)?",
               "Ok. 1846 zł", "Ok. 2500 zł", "Ok. 3023 zł",
               why="480 000 / 260 ≈ 1846 zł."),
             W("Ile wyniesie emerytura w wieku 65 lat (w przybliżeniu)?",
               "Ok. 3023 zł", "Ok. 1846 zł", "Ok. 2232 zł",
               why="650 000 / 215 ≈ 3023 zł."),
             PF("Dłuższa praca może podnieść emeryturę o kilkadziesiąt procent dzięki dwóm efektom naraz.", True,
                why="Rośnie kapitał i maleje liczba miesięcy wypłaty."),
          ),
          PR("W systemie repartycyjnym na jednego emeryta przypada dziś ok. 2,5 pracującego, a prognozy wskazują spadek do ok. 1,5 za kilkadziesiąt lat (dane umowne).",
             W("Jak zmiana wpłynie na relację emerytur do płac przy tej samej stopie składki?",
               "Emerytury będą niższe w relacji do płac", "Emerytury wzrosną", "Brak wpływu",
               why="Mniej płacących składki na jednego emeryta."),
             W("Które rozwiązanie łagodzi ten problem?",
               "Wyższa aktywność zawodowa i dłuższa praca", "Obniżenie wieku emerytalnego", "Zmniejszenie składki",
               why="Więcej pracujących, mniej lat pobierania świadczeń."),
             PF("Dobrowolne oszczędzanie w III filarze może uzupełnić niższą emeryturę z ZUS.", True,
                why="IKE, IKZE, PPK zwiększają dochód na emeryturze."),
          ),
      ]),

    L(2, "Stopa zastąpienia i demografia emerytur",
      "Liczyć stopę zastąpienia, rozumieć, dlaczego w systemie zdefiniowanej składki będzie ona spadać przy starzeniu się społeczeństwa, i oceniać sposoby jej podniesienia.",
      ["Stopa zastąpienia", "System emerytalny w Polsce (od 1999 r.)", "Wiek emerytalny w Polsce"],
      [ZUSG, S174],
      explain=[
          K("Stopa zastąpienia",
            "To relacja pierwszej emerytury do ostatniego wynagrodzenia (brutto lub netto). Mówi, jak bardzo spadnie dochód po przejściu na emeryturę. Stopa 60% oznacza, że emeryt dostaje 60% ostatniej pensji.",
            w="stopa zastąpienia = pierwsza emerytura / ostatnie wynagrodzenie"),
          W("Ostatnia pensja 8000 zł, pierwsza emerytura 3200 zł. Ile wynosi stopa zastąpienia?",
            "40%", "60%", "25%",
            why="3200 / 8000 = 40%."),
          K("Dlaczego będzie spadać",
            "W systemie zdefiniowanej składki emerytura zależy od składek i dalszego trwania życia. Gdy ludzie żyją dłużej, a wiek emerytalny się nie zmienia, ten sam kapitał dzieli się na więcej miesięcy. Waloryzacja kapitału związana z funduszem płac słabnie, gdy liczba pracujących spada. Prognozy Komisji Europejskiej (Ageing Report) wskazują na wyraźny spadek stopy zastąpienia w Polsce w najbliższych dekadach."),
          K("Przerwy w karierze",
            "Okresy bez składek (bezrobocie, praca bez umowy, długie przerwy na opiekę) lub niskie składki (preferencyjny ZUS, praca na umowie o dzieło) obniżają kapitał. Szczególnie dotyczy to kobiet – krótszy staż i niższy wiek emerytalny. Państwo gwarantuje najniższą emeryturę przy odpowiednim stażu (20 lat kobiety, 25 lat mężczyźni)."),
          K("Jak podnieść stopę zastąpienia",
            "Dłuższa praca (później przejście na emeryturę), legalne zatrudnienie i składki od pełnych dochodów, dodatkowe oszczędzanie w III filarze (PPK, IKE, IKZE), a na poziomie państwa – wyższa aktywność zawodowa i polityka rodzinna oraz migracyjna zwiększająca liczbę pracujących."),
          PF("Osoba, która przez lata płaciła składki od minimalnej podstawy, może mieć niską stopę zastąpienia, mimo wysokich realnych dochodów.", True,
             why="Emerytura zależy od podstawy składek, a nie od faktycznych dochodów."),
      ],
      mech=[
          LN("Ułóż, jak wydłużanie życia obniża stopę zastąpienia.",
             ["Średnie dalsze trwanie życia rośnie", "GUS publikuje nowe tablice trwania życia", "Kapitał dzieli się przez większą liczbę miesięcy", "Pierwsza emerytura jest niższa przy tym samym kapitale", "Spada relacja emerytury do ostatniej płacy"],
             why="Mechanizm zdefiniowanej składki przenosi ryzyko długowieczności na emeryta."),
          KT("Co podnosi, a co obniża przyszłą stopę zastąpienia?",
             {"Podnosi": ["Praca o 3 lata dłużej", "Oszczędzanie w PPK", "Składki od pełnego wynagrodzenia"],
              "Obniża": ["Wieloletnia praca bez umowy", "Składki od minimalnej podstawy przez całą karierę", "Długie przerwy w zatrudnieniu"]},
             why="Liczą się wpłacone składki i długość okresu wypłaty."),
          W("Dlaczego kobiety w Polsce mają zwykle niższe emerytury niż mężczyźni?",
            "Krótszy staż, niższy wiek emerytalny i często niższe płace", "Niższa stopa składki dla kobiet", "Brak prawa do waloryzacji",
            why="Wszystkie trzy czynniki zmniejszają kapitał lub zwiększają okres wypłaty."),
          W("Co się stanie ze stopą zastąpienia przedsiębiorcy płacącego ZUS od minimalnej podstawy, a zarabiającego 20 000 zł?",
            "Będzie bardzo niska", "Będzie wyższa niż u pracownika", "Wyniesie 100%",
            why="Emerytura zależy od podstawy wymiaru składek."),
          M("Które działania państwa łagodzą skutki starzenia się dla emerytur?",
            ["Zachęty do dłuższej aktywności zawodowej", "Wspieranie dodatkowego oszczędzania (PPK)", "Zwiększanie zatrudnienia, w tym imigrantów", "Obniżanie wieku emerytalnego"], [0, 1, 2],
            why="Niższy wiek emerytalny pogłębia problem."),
          PF("Stopa zastąpienia mierzy, jaki procent ostatniej pensji stanowi pierwsza emerytura.", True,
             why="To definicja tego wskaźnika."),
      ],
      calc=[
          LB("Ostatnie wynagrodzenie 9000 zł, pierwsza emerytura 4050 zł. Ile wynosi stopa zastąpienia (%)?",
             45, "4050/9000*100", ["4050 / 9000 = 45%"], unit="%"),
          LB("Przy stopie zastąpienia 35% i pensji 10 000 zł ile wyniesie emerytura (zł)?",
             3500, "10000*0.35", ["10 000 · 35% = 3500 zł"], unit="zł"),
          LB("Ile trzeba mieć kapitału, by przy 240 miesiącach dalszego trwania życia otrzymać 3500 zł (zł)?",
             840000, "3500*240", ["3500 · 240 = 840 000 zł"], unit="zł"),
          LB("Emerytura z ZUS 3500 zł, z PPK dodatkowo 600 zł miesięcznie, pensja 10 000 zł. Ile wynosi łączna stopa zastąpienia (%)?",
             41, "(3500+600)/10000*100", ["4100 / 10 000 = 41%"], unit="%"),
          LB("Pracujący 16 mln, emeryci 6,4 mln (dane umowne). Ilu pracujących przypada na jednego emeryta?",
             2.5, "16/6.4", ["16 / 6,4 = 2,5"], unit="", tol=0.01),
          LB("Prognoza: pracujący 13 mln, emeryci 8,7 mln. Ilu pracujących przypada na emeryta (2 miejsca po przecinku)?",
             1.49, "13/8.7", ["13 / 8,7 ≈ 1,49"], unit="", tol=0.01),
      ],
      case=[
          PR("Pan Krzysztof prowadzi firmę i przez 30 lat płacił składki od minimalnej podstawy (60% przeciętnego wynagrodzenia), choć zarabiał ok. 3 razy więcej niż przeciętnie. Jego kolega na etacie zarabiał przeciętną pensję.",
             W("Kto będzie miał wyższą emeryturę z ZUS (przy podobnym stażu)?",
               "Kolega na etacie", "Pan Krzysztof", "Obaj taką samą",
               why="Składki kolegi liczono od 100% przeciętnej płacy, Krzysztofa – od 60%."),
             W("Jaka będzie stopa zastąpienia Pana Krzysztofa względem jego faktycznych dochodów?",
               "Bardzo niska", "Wysoka", "Ponad 100%",
               why="Emerytura od małej podstawy w relacji do wysokich dochodów."),
             PF("Pan Krzysztof powinien rozważyć dodatkowe oszczędzanie, np. w IKZE z wyższym limitem dla przedsiębiorców.", True,
                why="W 2026 r. limit IKZE dla prowadzących działalność to 16 956 zł."),
          ),
          PR("Dwie siostry-bliźniaczki: Ania przeszła na emeryturę w wieku 60 lat, Basia pracowała do 65. Przez 5 lat Basia dopisała do konta ok. 120 000 zł składek i waloryzacji (dane umowne).",
             W("Która ma wyższą stopę zastąpienia?",
               "Basia", "Ania", "Obie taką samą",
               why="Większy kapitał i krótszy okres wypłaty."),
             W("Dlaczego różnica jest tak duża mimo tylko 5 lat?",
               "Działają dwa efekty: większy kapitał i mniej miesięcy wypłaty", "Basia ma wyższą stopę składki", "ZUS nagradza tylko osoby po 65. roku",
               why="Każdy rok pracy zwiększa licznik i zmniejsza mianownik wzoru."),
             PF("Ania może dorabiać, pobierając emeryturę, a dodatkowe składki można doliczyć do emerytury (przeliczenie).", True,
                why="Po osiągnięciu wieku emerytalnego emerytura nie jest zawieszana, a składki można doliczyć."),
          ),
      ]),

    L(3, "III filar: IKE, IKZE, PPE i PPK",
      "Odróżniać IKE, IKZE, PPE i PPK, rozumieć ich zachęty podatkowe i dopłaty, znać limity wpłat na 2026 r. i liczyć korzyści z oszczędzania w III filarze.",
      ["IKE, IKZE i PPE", "Pracownicze Plany Kapitałowe (PPK)", "Stopa zastąpienia"],
      [SII, PPK],
      explain=[
          K("IKE",
            "Indywidualne konto emerytalne: wpłacasz z dochodu już opodatkowanego, ale przy wypłacie po 60. roku życia (lub po 55., gdy nabyłeś prawo do emerytury) nie płacisz 19% podatku od zysków (Belki). Limit wpłat w 2026 r.: 28 260 zł (3 × prognozowane przeciętne wynagrodzenie)."),
          K("IKZE",
            "Indywidualne konto zabezpieczenia emerytalnego: wpłaty odliczasz od dochodu w PIT – oszczędzasz podatek od razu według swojej stawki (12% lub 32%, przy liniowym 19%). Wypłata po 65. roku życia jest opodatkowana ryczałtem 10%. Limit w 2026 r.: 11 304 zł, a dla prowadzących działalność 16 956 zł.",
            w="ulga IKZE = wpłata · stawka PIT"),
          W("Osoba w progu 32% wpłaca na IKZE 10 000 zł. Ile wynosi zwrot podatku?",
            "3200 zł", "1200 zł", "1000 zł",
            why="10 000 · 32% = 3200 zł."),
          K("PPE i PPK",
            "PPE tworzy pracodawca dobrowolnie i finansuje składkę podstawową. PPK (od 2019 r.) obejmuje pracowników z automatycznym zapisem – można zrezygnować deklaracją, ale co 4 lata następuje ponowny zapis. Wpłaty: pracownik 2% (może zwiększyć), pracodawca 1,5% (może zwiększyć), państwo – 250 zł powitalnej i 240 zł dopłaty rocznej. Od wpłaty pracodawcy pracownik płaci PIT."),
          K("Moc dopłat i ulg",
            "Siła III filara to dodatkowe pieniądze, których nie ma przy samodzielnym oszczędzaniu: w PPK – wpłaty pracodawcy i państwa, w IKZE – zwrot podatku, w IKE – brak podatku Belki od zysków. Dzięki procentowi składanemu kilkadziesiąt lat systematycznych wpłat może znacząco podnieść stopę zastąpienia."),
          PF("Wpłaty na IKE odlicza się od dochodu w zeznaniu PIT.", False,
             why="Odliczenie od dochodu dotyczy IKZE; IKE daje zwolnienie z podatku Belki przy wypłacie."),
      ],
      mech=[
          KT("Która cecha dotyczy którego produktu?",
             {"IKE": ["Brak podatku Belki przy wypłacie po 60. r.ż.", "Limit 3 × prognozowane przeciętne wynagrodzenie"],
              "IKZE": ["Odliczenie wpłat od dochodu w PIT", "Wypłata opodatkowana ryczałtem 10%"],
              "PPK": ["Automatyczny zapis pracownika", "Dopłata powitalna 250 zł od państwa"]},
             why="Każdy produkt ma inny mechanizm zachęty."),
          LN("Ułóż przepływ pieniędzy w PPK w miesiącu.",
             ["Pracodawca nalicza wynagrodzenie brutto", "Potrąca wpłatę pracownika 2%", "Dodaje wpłatę pracodawcy 1,5% (opodatkowaną u pracownika)", "Przekazuje obie wpłaty do instytucji finansowej", "Środki są inwestowane w fundusz zdefiniowanej daty"],
             why="Wpłaty są inwestowane według wieku uczestnika."),
          W("Dla kogo IKZE jest najbardziej opłacalne?",
            "Dla osoby z wysoką stawką PIT (32%)", "Dla osoby bez dochodów", "Dla osoby, która chce wypłacić środki za rok",
            why="Zwrot podatku zależy od stawki; wcześniejsza wypłata traci ulgę."),
          W("Pracownik rezygnuje z PPK, by mieć 2% więcej pensji. Co traci?",
            "Wpłaty pracodawcy i dopłaty państwa", "Tylko swoje 2%", "Prawo do emerytury z ZUS",
            why="Rezygnacja oznacza utratę dodatkowych pieniędzy."),
          M("Jak można wypłacić środki z PPK po 60. roku życia bez podatku Belki?",
            ["25% jednorazowo", "75% w co najmniej 120 ratach", "Całość w ratach", "Całość jednorazowo bez podatku"], [0, 1, 2],
            why="Jednorazowa wypłata całości (powyżej 25%) wiąże się z podatkiem od zysków."),
          PF("PPK jest dobrowolne – pracownik może złożyć deklarację rezygnacji.", True,
             why="Zapis jest automatyczny, ale udział dobrowolny."),
      ],
      calc=[
          LB("Pensja 8000 zł brutto. Ile miesięcznie wpłaca do PPK pracownik (2%) i pracodawca (1,5%) łącznie (zł)?",
             280, "8000*0.035", ["160 + 120 = 280 zł"], unit="zł"),
          LB("Ile to rocznie, wliczając dopłatę roczną państwa 240 zł (zł)?",
             3600, "280*12+240", ["280 · 12 = 3360", "+ 240 = 3600 zł"], unit="zł"),
          LB("Wpłata pracownika 160 zł miesięcznie, a łącznie na konto trafia 280 zł + 20 zł (1/12 dopłaty rocznej). Ile wynosi „zwrot” na starcie w % wpłaty pracownika?",
             87.5, "(280+20-160)/160*100", ["Dodatkowe 140 zł / 160 zł = 87,5%"], unit="%", tol=0.01),
          LB("Wpłata na IKZE 11 304 zł przy stawce 12%. Ile wynosi ulga podatkowa (zł)?",
             1356.48, "11304*0.12", ["11 304 · 12% = 1356,48 zł"], unit="zł", tol=0.01),
          LB("Zysk na IKE 40 000 zł przy wypłacie po 60. roku życia. Ile podatku Belki oszczędzono (zł)?",
             7600, "40000*0.19", ["40 000 · 19% = 7600 zł"], unit="zł"),
          LB("Wpłata 300 zł miesięcznie przez 30 lat, 5% rocznie (kapitalizacja roczna, wpłaty roczne 3600 zł na koniec roku). Ile wyniesie kapitał (zł)?",
             239179.85, "3600*((1.05**30-1)/0.05)", ["FV renty = 3600 · ((1,05³⁰ − 1) / 0,05) ≈ 239 179 zł"], unit="zł", tol=0.01),
      ],
      case=[
          PR("Pan Michał (35 lat, PIT 32%) ma co roku 15 000 zł do zaoszczędzenia. Rozważa IKZE (limit 11 304 zł w 2026 r.) i IKE na resztę.",
             W("Ile podatku odzyska co roku dzięki pełnej wpłacie na IKZE?",
               "Ok. 3617 zł", "Ok. 1356 zł", "Ok. 4800 zł",
               why="11 304 · 32% ≈ 3617 zł."),
             W("Jaką kwotę może wpłacić na IKE z pozostałych oszczędności?",
               "3696 zł", "15 000 zł", "11 304 zł",
               why="15 000 − 11 304 = 3696 zł – mieści się w limicie IKE."),
             PF("Zwrot podatku z IKZE może co roku reinwestować, zwiększając efekt procentu składanego.", True,
                why="Odzyskane pieniądze też mogą pracować."),
          ),
          PR("W PPK na 31.05.2025 uczestniczyło ok. 53% uprawnionych pracowników (dane PFR). Część młodych pracowników rezygnuje, bo „woli mieć pieniądze teraz”.",
             W("Jaką skłonność behawioralną opisuje to zachowanie?",
               "Skrzywienie ku teraźniejszości (present bias)", "Awersję do strat", "Efekt posiadania",
               why="Teraźniejsza korzyść jest ważona bardziej niż przyszła."),
             W("Dlaczego automatyczny zapis zwiększa udział w PPK?",
               "Ludzie często pozostają przy opcji domyślnej", "Bo rezygnacja jest zakazana", "Bo PPK daje gwarantowany zysk",
               why="Efekt status quo – jeden z wniosków ekonomii behawioralnej."),
             PF("Ponowny autozapis co 4 lata ma przypomnieć o korzyściach i zwiększyć uczestnictwo.", True,
                why="Osoby, które zrezygnowały, są zapisywane ponownie, chyba że znów złożą rezygnację."),
          ),
      ]),

    L(4, "Świadczenia społeczne i transfery",
      "Rozumieć rolę świadczeń społecznych w ograniczaniu ubóstwa, różnicę między transferami a zakupami rządowymi w PKB, problem pułapki ubóstwa oraz rozwiązania aktywizujące, takie jak dodatek aktywizacyjny.",
      ["Świadczenia społeczne w Polsce", "Transfery socjalne", "Dodatek aktywizacyjny"],
      [S153, S155, MRPIPS],
      explain=[
          K("Transfery socjalne",
            "Transfery to wypłaty bez świadczenia wzajemnego: emerytury, renty, zasiłki, świadczenie wychowawcze 800+, 13. i 14. emerytura. Nie są zakupem dóbr i usług przez państwo, więc nie wchodzą do G w PKB – zmieniają dochód rozporządzalny gospodarstw i dopiero przez ich konsumpcję wpływają na popyt."),
          K("Świadczenia w Polsce",
            "Najważniejsze: emerytury i renty (FUS), świadczenie wychowawcze 800 zł na dziecko (od 1.01.2024, wcześniej 500+ od 2016 r.), zasiłki rodzinne, zasiłek dla bezrobotnych, świadczenia z pomocy społecznej, 13. i 14. emerytura. Programy powszechne (800+) są proste i nie zniechęcają do pracy, ale trafiają też do zamożnych; programy kierowane (z progiem dochodowym) są tańsze, ale mogą tworzyć pułapkę ubóstwa."),
          W("Rząd zwiększa wypłaty 800+. Jak zmienia się składnik G w PKB?",
            "Nie zmienia się bezpośrednio – to transfer", "Rośnie o całą kwotę", "Spada",
            why="Transfery nie są zakupem dóbr i usług przez państwo."),
          K("Pułapka ubóstwa",
            "Gdy świadczenie znika po przekroczeniu progu dochodowego, dodatkowa praca może nie zwiększyć dochodu, a nawet go zmniejszyć – efektywna krańcowa stopa opodatkowania bywa bliska lub wyższa niż 100%. Rozwiązania: stopniowe zmniejszanie świadczenia (zasada „złotówka za złotówkę”), ulgi podatkowe dla pracujących, dodatki za podjęcie pracy."),
          K("Dodatek aktywizacyjny",
            "Bezrobotny z prawem do zasiłku, który sam znajdzie pracę, dostaje dodatek aktywizacyjny – część zasiłku wypłacaną mimo podjęcia zatrudnienia. Zmniejsza to koszt rezygnacji z zasiłku i skraca okres bezrobocia."),
          PF("Zasada „złotówka za złotówkę” przy progach dochodowych ogranicza pułapkę ubóstwa.", True,
             why="Świadczenie maleje stopniowo zamiast znikać nagle."),
      ],
      mech=[
          KT("Transfer czy zakup rządowy (G)?",
             {"Transfer": ["Wypłata emerytury", "Świadczenie 800+", "Zasiłek dla bezrobotnych", "13. emerytura"],
              "Zakup rządowy (G)": ["Pensje nauczycieli", "Zakup czołgów", "Budowa drogi ekspresowej"]},
             why="G to zakup dóbr i usług, transfer – przekazanie pieniędzy bez świadczenia."),
          LN("Ułóż mechanizm pułapki ubóstwa.",
             ["Rodzina pobiera świadczenie zależne od dochodu", "Rodzic dostaje ofertę lepiej płatnej pracy", "Dochód przekracza próg o kilka złotych", "Rodzina traci całe świadczenie", "Dochód netto po zmianie pracy jest niższy niż wcześniej – praca się nie opłaca"],
             why="Skokowy próg tworzy bardzo wysoką efektywną stawkę krańcową."),
          W("Które rozwiązanie najmniej zniechęca do podjęcia pracy?",
            "Świadczenie powszechne lub stopniowo wygaszane", "Świadczenie znikające całkowicie po przekroczeniu progu", "Wyższy zasiłek bez limitu czasu",
            why="Brak skokowej utraty świadczenia nie karze za dodatkowy dochód."),
          W("Państwo wypłaca dodatek aktywizacyjny. Na co liczy?",
            "Że bezrobotni szybciej podejmą pracę", "Że zwiększy się bezrobocie", "Że spadną płace",
            why="Dodatek zmniejsza koszt rezygnacji z zasiłku."),
          M("Jakie są zalety świadczeń powszechnych (bez progu dochodowego)?",
            ["Prosta administracja", "Brak pułapki ubóstwa", "Wysoka dostępność dla uprawnionych", "Najniższy koszt dla budżetu"], [0, 1, 2],
            why="Powszechność zwiększa koszt, bo świadczenie dostają też zamożni."),
          PF("Wzrost transferów socjalnych w czasie recesji działa jak automatyczny stabilizator.", True,
             why="Podtrzymuje dochody i konsumpcję gospodarstw."),
      ],
      calc=[
          LB("Rodzina ma troje dzieci. Ile miesięcznie wynosi świadczenie 800+ (zł)?",
             2400, "3*800", ["3 · 800 = 2400 zł"], unit="zł"),
          LB("Ile to rocznie (zł)?",
             28800, "2400*12", ["2400 · 12 = 28 800 zł"], unit="zł"),
          LB("Świadczenie 600 zł miesięcznie znika po przekroczeniu progu. Podwyżka pensji o 200 zł netto przekracza próg. O ile zmienia się dochód rodziny miesięcznie (zł; spadek ze znakiem minus)?",
             -400, "200-600", ["+200 − 600 = −400 zł"], unit="zł"),
          LB("Ta sama sytuacja z zasadą „złotówka za złotówkę”: przekroczenie progu o 200 zł zmniejsza świadczenie o 200 zł. Ile wynosi efektywna krańcowa stopa opodatkowania (%)?",
             100, "200/200*100", ["Utrata 200 zł z 200 zł podwyżki = 100%"], unit="%"),
          LB("Zasiłek 1700 zł, dodatek aktywizacyjny – przyjmij 50% zasiłku (dane umowne). Ile wynosi dodatek (zł)?",
             850, "1700*0.5", ["1700 · 50% = 850 zł"], unit="zł"),
          LB("Ubóstwo przed transferami 25%, po transferach 13,5% (dane umowne). O ile pkt proc. transfery zmniejszyły ubóstwo?",
             11.5, "25-13.5", ["25 − 13,5 = 11,5 pkt proc."], unit="pkt proc.", tol=0.01),
      ],
      case=[
          PR("Samotna matka zarabia 3500 zł netto i dostaje zasiłek rodzinny z dodatkami 500 zł, pod warunkiem że dochód na osobę nie przekracza progu. Ma ofertę pracy za 3700 zł netto, ale wtedy przekroczy próg o 50 zł (dane umowne).",
             W("Ile wyniesie jej dochód po zmianie pracy przy zasadzie „wszystko albo nic”?",
               "3700 zł", "4200 zł", "4000 zł",
               why="Traci 500 zł świadczenia – dochód z 4000 spada do 3700 zł."),
             W("Ile wyniesie przy zasadzie „złotówka za złotówkę” (dochód na rodzinę ponad próg o 50 zł)?",
               "4150 zł", "3700 zł", "4200 zł",
               why="Świadczenie maleje o 50 zł: 3700 + 450 = 4150 zł."),
             PF("Zasada „złotówka za złotówkę” sprawia, że wyższa pensja nie obniża łącznego dochodu.", True,
                why="Świadczenie spada co najwyżej o tyle, o ile wzrósł dochód."),
          ),
          PR("Badacze oceniający 500+ (później 800+) wskazywali, że program znacząco obniżył skrajne ubóstwo dzieci, ale w pierwszych latach mógł nieco zmniejszyć aktywność zawodową części kobiet o niskich dochodach.",
             W("Jaki efekt ekonomiczny może zmniejszać podaż pracy przy takim świadczeniu?",
               "Efekt dochodowy – przy wyższym dochodzie część osób wybiera więcej czasu wolnego", "Efekt substytucyjny podnoszący płace", "Efekt mnożnikowy",
               why="Świadczenie powszechne nie zmienia płacy za godzinę, ale zwiększa dochód."),
             W("Dlaczego 800+ nie tworzy pułapki ubóstwa?",
               "Nie ma progu dochodowego", "Wypłaca się je tylko pracującym", "Jest opodatkowane",
               why="Świadczenie nie znika po wzroście dochodu."),
             PF("Ocena programów socjalnych wymaga porównania korzyści (np. mniejsze ubóstwo) z kosztami (budżet, bodźce do pracy).", True,
                why="Polityka społeczna zawsze wiąże się z kompromisami."),
          ),
      ]),

    L(5, "Modele ochrony zdrowia i ich finansowanie",
      "Porównywać modele systemów ochrony zdrowia (Bismarcka, Beveridge’a, Siemaszki, rynkowy), rozumieć finansowanie ochrony zdrowia w Polsce oraz problemy asymetrii informacji i pokusy nadużycia w opiece zdrowotnej.",
      ["Modele systemów ochrony zdrowia", "Świadczenia społeczne w Polsce", "Transfery socjalne"],
      [S153, ZUSG],
      explain=[
          K("Cztery modele",
            "Model Bismarcka (Niemcy, Polska): obowiązkowe ubezpieczenie zdrowotne finansowane ze składek, płatnik (w Polsce NFZ) kupuje usługi od świadczeniodawców. Model Beveridge’a (Wielka Brytania – NHS): narodowa służba zdrowia finansowana z podatków, dostęp dla wszystkich obywateli. Model Siemaszki (ZSRR): państwo finansuje i prowadzi wszystkie placówki. Model rynkowy (USA): dominują prywatne ubezpieczenia, a państwo pokrywa wybrane grupy (Medicare, Medicaid)."),
          K("Polska",
            "Podstawą jest składka zdrowotna – 9% podstawy u pracowników (dla przedsiębiorców zasady zależą od formy opodatkowania). Środki gromadzi NFZ, który zawiera kontrakty ze szpitalami i przychodniami. Budżet państwa finansuje m.in. składki za niektóre grupy, ratownictwo i inwestycje. Wydatki publiczne na zdrowie w Polsce są niższe w relacji do PKB niż średnia UE, a znaczna część wydatków to płatności prywatne."),
          W("Kraj finansuje szpitale z podatków ogólnych, a leczenie jest bezpłatne dla obywateli. Jaki to model?",
            "Beveridge’a", "Bismarcka", "Rynkowy",
            why="Finansowanie z budżetu i powszechny dostęp to cechy modelu NHS."),
          K("Zawodności rynku zdrowia",
            "Pacjent wie mniej niż lekarz (asymetria informacji), więc trudno mu ocenić, czy leczenie jest potrzebne. Ubezpieczony może nadużywać usług, gdy są dla niego bezpłatne (pokusa nadużycia). Prywatne ubezpieczenia cierpią na negatywną selekcję. Dlatego w większości krajów państwo silnie reguluje i współfinansuje ochronę zdrowia."),
          K("Kolejki i współpłacenie",
            "Gdy usługa jest bezpłatna, popyt przewyższa podaż – pojawiają się kolejki (racjonowanie przez czas). Niektóre kraje wprowadzają współpłacenie (np. niewielka opłata za wizytę), by ograniczyć nadużycia, ale może ono zniechęcać najuboższych do leczenia. USA wydają na zdrowie najwięcej w relacji do PKB, choć nie mają najlepszych wskaźników zdrowotnych."),
          PF("W modelu Bismarcka głównym źródłem finansowania są składki ubezpieczeniowe.", True,
             why="Tak działa m.in. system niemiecki i polski."),
      ],
      mech=[
          KT("Który model ochrony zdrowia?",
             {"Bismarcka": ["Niemcy – kasy chorych finansowane ze składek", "Polska – składka zdrowotna i NFZ"],
              "Beveridge’a": ["Wielka Brytania – NHS finansowany z podatków", "Bezpłatne leczenie dla wszystkich obywateli z budżetu"],
              "Rynkowy": ["USA – prywatne ubezpieczenia przez pracodawcę", "Wysoki udział prywatnych wydatków"],
              "Siemaszki": ["ZSRR – państwowe placówki i lekarze na etatach państwowych"]},
             why="Kryteria: źródło finansowania i własność placówek."),
          LN("Ułóż, jak brak ceny prowadzi do kolejek.",
             ["Usługa medyczna jest bezpłatna w miejscu korzystania", "Pacjenci zgłaszają duży popyt, także na mniej pilne wizyty", "Liczba lekarzy i sprzętu jest ograniczona", "Popyt przewyższa podaż", "Dostęp racjonuje się czasem oczekiwania – powstają kolejki"],
             why="Przy cenie zero rynek nie równoważy się ceną, tylko kolejką."),
          W("Dlaczego pacjent nie może łatwo ocenić, czy zalecony zabieg jest potrzebny?",
            "Asymetria informacji – lekarz wie więcej", "Bo zabiegi są bezpłatne", "Bo NFZ zakazuje pytań",
            why="Wiedza medyczna jest specjalistyczna."),
          W("Wprowadzono opłatę 10 zł za wizytę. Jakiego skutku można się spodziewać?",
            "Mniej zbędnych wizyt, ale ryzyko rezygnacji najuboższych z potrzebnych", "Wzrost liczby wizyt", "Brak jakiegokolwiek wpływu",
            why="Współpłacenie ogranicza pokusę nadużycia, ale ma koszt społeczny."),
          M("Jakie zawodności rynku występują w ochronie zdrowia?",
            ["Asymetria informacji między lekarzem a pacjentem", "Pokusa nadużycia przy pełnym ubezpieczeniu", "Negatywna selekcja w prywatnych ubezpieczeniach", "Doskonała informacja wszystkich stron"], [0, 1, 2],
            why="Doskonała informacja to założenie rynku doskonałego, nie zawodność."),
          PF("W modelu Beveridge’a dostęp do leczenia zależy od opłacania składki przez pacjenta.", False,
             why="Dostęp ma każdy obywatel – system jest finansowany z podatków."),
      ],
      calc=[
          LB("Wynagrodzenie po odjęciu składek społecznych 6900 zł, składka zdrowotna 9%. Ile wynosi (zł)?",
             621, "6900*0.09", ["6900 · 9% = 621 zł"], unit="zł"),
          LB("Ile rocznie wynosi ta składka (zł)?",
             7452, "621*12", ["621 · 12 = 7452 zł"], unit="zł"),
          LB("Wydatki publiczne na zdrowie 6% PKB, PKB 3 912,7 mld zł. Ile to mld zł?",
             234.76, "3912.7*0.06", ["3912,7 · 6% ≈ 234,76 mld zł"], unit="mld zł", tol=0.01),
          LB("Wydatki na zdrowie 234,76 mld zł, ludność ok. 37,4 mln. Ile przypada na osobę (zł)?",
             6277.01, "234.76e9/37.4e6", ["234,76 mld / 37,4 mln ≈ 6277 zł"], unit="zł", tol=0.01),
          LB("Kraj A wydaje 17% PKB na zdrowie, kraj B 10%. Ile razy więcej (w relacji do PKB) wydaje A?",
             1.7, "17/10", ["17 / 10 = 1,7"], unit="razy", tol=0.01),
          LB("Opłata 10 zł za wizytę zmniejsza liczbę wizyt z 300 do 270 mln rocznie. O ile procent spadła liczba wizyt?",
             10, "(1-270/300)*100", ["270 / 300 = 0,9 → spadek o 10%"], unit="%"),
      ],
      case=[
          PR("Kraj X ma system Bismarcka, ale kolejki do specjalistów wynoszą wiele miesięcy. Rośnie rynek prywatnych abonamentów medycznych, opłacanych często przez pracodawców (dane umowne).",
             W("Dlaczego powstają kolejki w systemie publicznym?",
               "Popyt przy zerowej cenie przewyższa ograniczoną podaż usług", "Pacjenci nie chcą się leczyć", "Ceny usług są za wysokie",
               why="Brak ceny racjonuje dostęp czasem oczekiwania."),
             W("Jaki skutek ma rozwój prywatnych abonamentów dla równości dostępu?",
               "Osoby zamożniejsze i lepiej zatrudnione szybciej dostają leczenie", "Wszyscy mają równy dostęp", "Kolejki natychmiast znikają",
               why="Dostęp zaczyna zależeć od dochodu i pracodawcy."),
             PF("Zwiększenie liczby lekarzy i finansowania może skrócić kolejki bez wprowadzania opłat.", True,
                why="Rośnie podaż usług."),
          ),
          PR("USA wydają na zdrowie ok. 17% PKB – najwięcej wśród krajów OECD – a średnia długość życia jest tam niższa niż w wielu krajach europejskich wydających ok. 10–12% PKB.",
             W("Co może wyjaśniać wysokie koszty w modelu rynkowym?",
               "Wysokie ceny usług i leków, koszty administracyjne wielu ubezpieczycieli", "Zbyt mała liczba szpitali", "Brak lekarzy",
               why="Rozproszony system płatników i siła rynkowa dostawców podnoszą ceny."),
             W("Która grupa w USA jest objęta programem publicznym Medicare?",
               "Osoby starsze (65+)", "Wszyscy obywatele", "Tylko dzieci",
               why="Medicare obejmuje głównie osoby po 65. roku życia."),
             PF("Wyższe wydatki na zdrowie nie gwarantują lepszych wyników zdrowotnych.", True,
                why="Liczy się też efektywność wydatków i styl życia."),
          ),
      ]),
]
