# -*- coding: utf-8 -*-
# Zrozumienie – Podstawy finansów / Finanse publiczne i budżet
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-08"
S301 = S("OpenStax, Principles of Economics 3e, 30.1 Government Spending", OS3 + "30-1-government-spending", D)
S303 = S("OpenStax, Principles of Economics 3e, 30.3 Federal Deficits and the National Debt", OS3 + "30-3-federal-deficits-and-the-national-debt", D)
S305 = S("OpenStax, Principles of Economics 3e, 30.5 Automatic Stabilizers", OS3 + "30-5-automatic-stabilizers", D)
MFB = S("Ministerstwo Finansów – budżet państwa", "https://www.gov.pl/web/finanse/budzet-panstwa", D)
MFD = S("Ministerstwo Finansów – dług publiczny", "https://www.gov.pl/web/finanse/dlug-publiczny", D)
BUD26 = S("Bankier – Budżet na 2026 rok uchwalony", "https://www.bankier.pl/wiadomosc/Budzet-na-2026-rok-uchwalony-Sejm-przyjal-poprawki-Senatu-9066242.html", D)
KONST = S("Konstytucja RP (ELI, Dz.U. 1997 nr 78 poz. 483)", "https://api.sejm.gov.pl/eli/acts/DU/1997/483/text.pdf", D)

LESSONS = [
    L(1, "Funkcje i struktura finansów publicznych",
      "Rozumieć trzy funkcje finansów publicznych według Musgrave’a, strukturę sektora finansów publicznych i formy organizacyjne jednostek oraz klasyfikację wydatków COFOG.",
      ["Finanse publiczne", "Funkcje finansów publicznych (Musgrave)", "Sektor finansów publicznych", "Jednostka budżetowa i zakład budżetowy", "Klasyfikacja wydatków COFOG"],
      [S301, MFB],
      explain=[
          K("Czym są finanse publiczne",
            "To procesy gromadzenia środków publicznych (podatki, składki, opłaty, dochody z majątku) i ich rozdysponowania przez państwo, samorządy i inne podmioty publiczne. Sektor finansów publicznych obejmuje m.in. organy władzy i administracji, sądy, JST i ich związki, jednostki i zakłady budżetowe, agencje wykonawcze, państwowe fundusze celowe, ZUS i KRUS, NFZ, publiczne uczelnie i szpitale."),
          K("Trzy funkcje Musgrave’a",
            "Alokacyjna – państwo dostarcza dobra publiczne i koryguje zawodności rynku (obrona, drogi, ochrona środowiska). Redystrybucyjna – zmienia podział dochodów (progresja, świadczenia społeczne). Stabilizacyjna – łagodzi wahania koniunktury, utrzymując zatrudnienie i stabilność cen (automatyczne stabilizatory, polityka dyskrecjonalna)."),
          W("Państwo wypłaca zasiłki rodzinne finansowane z podatków progresywnych. Którą funkcję realizuje?",
            "Redystrybucyjną", "Alokacyjną", "Stabilizacyjną",
            why="Zmienia podział dochodów między gospodarstwami."),
          K("Jednostka i zakład budżetowy",
            "Jednostka budżetowa (np. szkoła publiczna, urząd) pokrywa wydatki bezpośrednio z budżetu, a pobrane dochody odprowadza do budżetu – metoda brutto. Samorządowy zakład budżetowy (np. zakład gospodarki komunalnej) odpłatnie wykonuje zadania i pokrywa koszty z własnych przychodów, może dostać dotację – metoda netto."),
          K("COFOG",
            "Klasyfikacja funkcji rządu (ONZ, OECD, Eurostat) dzieli wydatki według celów: ogólne usługi publiczne, obrona, porządek i bezpieczeństwo, sprawy gospodarcze, ochrona środowiska, mieszkalnictwo, zdrowie, rekreacja i kultura, edukacja, ochrona socjalna. Pozwala porównywać wydatki między krajami. W Polsce, jak w większości UE, największą kategorią jest ochrona socjalna (głównie emerytury)."),
          PF("ZUS i NFZ należą do sektora finansów publicznych.", True,
             why="Ustawa o finansach publicznych wymienia je wśród jednostek sektora."),
      ],
      mech=[
          KT("Która funkcja Musgrave’a?",
             {"Alokacyjna": ["Budowa autostrady", "Finansowanie obrony narodowej", "Ochrona parków narodowych"],
              "Redystrybucyjna": ["Progresywny PIT", "Świadczenie 800+", "Dodatek mieszkaniowy"],
              "Stabilizacyjna": ["Zasiłki dla bezrobotnych rosnące w recesji", "Program inwestycji publicznych w kryzysie"]},
             why="Każda funkcja odpowiada na inny problem rynku."),
          LN("Ułóż działanie automatycznego stabilizatora w recesji.",
             ["Gospodarka wchodzi w recesję", "Rośnie bezrobocie i spadają dochody", "Spadają wpływy z PIT i VAT, rosną wydatki na zasiłki", "Deficyt rośnie bez nowych decyzji rządu", "Popyt spada mniej, niż spadłby bez tych mechanizmów"],
             why="Stabilizatory działają automatycznie – realizują funkcję stabilizacyjną."),
          W("Gmina tworzy zakład budżetowy do utrzymania zieleni, który pobiera opłaty za usługi. Jak finansuje koszty?",
            "Z własnych przychodów, czasem z dotacją – metoda netto", "Wyłącznie bezpośrednio z budżetu – metoda brutto", "Z kredytów NBP",
            why="Zakład budżetowy działa w metodzie netto."),
          W("Która kategoria COFOG jest w Polsce największa?",
            "Ochrona socjalna", "Obrona", "Rekreacja i kultura",
            why="Emerytury i świadczenia społeczne to największa część wydatków publicznych."),
          M("Które podmioty należą do sektora finansów publicznych?",
            ["Gminy i powiaty", "Państwowe fundusze celowe", "Publiczne uczelnie", "Prywatne banki komercyjne"], [0, 1, 2],
            why="Banki komercyjne są w sektorze finansowym, ale nie publicznym."),
          PF("Jednostka budżetowa może swobodnie wydawać dochody, które sama pobrała, np. opłaty administracyjne.", False,
             why="W metodzie brutto dochody odprowadza się do budżetu."),
      ],
      calc=[
          LB("Wydatki publiczne 1600 mld zł, PKB 3 900 mld zł (dane umowne). Ile wynosi udział wydatków w PKB (%)?",
             41.03, "1600/3900*100", ["1600 / 3900 ≈ 41,03%"], unit="%", tol=0.01),
          LB("Ochrona socjalna to 40% wydatków 1600 mld zł. Ile to mld zł?",
             640, "1600*0.4", ["1600 · 40% = 640 mld zł"], unit="mld zł"),
          LB("Wydatki na obronę 4,7% PKB, PKB 3 900 mld zł. Ile to mld zł?",
             183.3, "3900*0.047", ["3900 · 4,7% = 183,3 mld zł"], unit="mld zł", tol=0.01),
          LB("Zakład budżetowy: przychody 6 mln zł, koszty 6,9 mln zł. Jaka dotacja pokryje różnicę (mln zł)?",
             0.9, "6.9-6", ["6,9 − 6 = 0,9 mln zł"], unit="mln zł", tol=0.01),
          LB("Gini przed transferami 0,45, po transferach 0,30. O ile procent transfery zmniejszyły nierówność?",
             33.33, "(1-0.30/0.45)*100", ["0,30 / 0,45 ≈ 0,667", "Spadek ≈ 33,33%"], unit="%", tol=0.02),
          LB("Wydatki na edukację 5% PKB, PKB 3 900 mld zł, 6 mln uczniów i studentów. Ile wynosi wydatek na osobę (zł)?",
             32500, "3900e9*0.05/6e6", ["195 mld zł / 6 mln = 32 500 zł"], unit="zł"),
      ],
      case=[
          PR("Rząd rozważa dwa programy za 20 mld zł: (A) budowę sieci szpitali regionalnych, (B) jednorazowy dodatek dla emerytów z najniższymi świadczeniami.",
             W("Którą funkcję realizuje głównie program A?",
               "Alokacyjną", "Redystrybucyjną", "Stabilizacyjną",
               why="Dostarcza usług publicznych – infrastruktury zdrowotnej."),
             W("Którą funkcję realizuje głównie program B?",
               "Redystrybucyjną", "Alokacyjną", "Żadną",
               why="Przenosi dochód do osób najuboższych."),
             PF("Oba programy w recesji mogą też pełnić funkcję stabilizacyjną, zwiększając popyt.", True,
                why="Wydatki publiczne zwiększają popyt globalny."),
          ),
          PR("Porównanie COFOG (dane umowne, % PKB): kraj A – ochrona socjalna 20%, zdrowie 8%, edukacja 5%; kraj B – ochrona socjalna 12%, zdrowie 5%, edukacja 6%.",
             W("Który kraj ma większe państwo opiekuńcze?",
               "A", "B", "Nie da się stwierdzić",
               why="Wyższe wydatki na ochronę socjalną i zdrowie."),
             W("Ile łącznie wynoszą te trzy kategorie w kraju A (% PKB)?",
               "33%", "23%", "20%",
               why="20 + 8 + 5 = 33%."),
             PF("Wyższe wydatki socjalne w kraju A mogą wynikać ze starszej struktury ludności.", True,
                why="Więcej emerytów oznacza wyższe wydatki emerytalne."),
          ),
      ]),

    L(2, "Budżet państwa: zasady, procedura i struktura",
      "Rozumieć zasady budżetowe, przebieg procedury budżetowej w Polsce (z terminami z Konstytucji), strukturę dochodów i wydatków budżetu na 2026 r., wydatki sztywne oraz wpłatę z zysku NBP.",
      ["Budżet państwa", "Zasady budżetowe", "Procedura budżetowa w Polsce", "Prowizorium budżetowe", "Dochody i wydatki budżetu państwa", "Wydatki sztywne i elastyczne", "Wpłata z zysku NBP", "Budżet zadaniowy i wieloletnia prognoza finansowa"],
      [MFB, BUD26, KONST],
      explain=[
          K("Zasady budżetowe",
            "Roczności – budżet na rok kalendarzowy. Zupełności – wszystkie dochody i wydatki w budżecie, w kwotach brutto. Jedności – jeden budżet. Uprzedniości – uchwalony przed rozpoczęciem roku. Jawności – dostępny dla obywateli. Szczegółowości – podział na części, działy, rozdziały. Równowagi – dążenie do zrównoważenia dochodów i wydatków."),
          K("Procedura budżetowa",
            "Rada Ministrów przedkłada Sejmowi projekt ustawy budżetowej najpóźniej do 30 września (art. 222 Konstytucji). Sejm uchwala ustawę, Senat ma na poprawki 20 dni (art. 223), prezydent podpisuje ją w ciągu 7 dni – nie może zawetować budżetu, może skierować go do TK (art. 224). Jeśli Sejm nie przedstawi ustawy prezydentowi do podpisu w ciągu 4 miesięcy od przedłożenia projektu, prezydent może skrócić kadencję Sejmu (art. 225). Gdy ustawy nie ma na początku roku, rząd działa według projektu lub uchwala się prowizorium."),
          W("Do kiedy rząd musi przedłożyć Sejmowi projekt budżetu na kolejny rok?",
            "Do 30 września", "Do 31 grudnia", "Do 31 marca",
            why="Termin wynika z art. 222 Konstytucji."),
          K("Budżet na 2026 r.",
            "Ustawa budżetowa na 2026 r. zakłada dochody 647,2 mld zł, wydatki 918,9 mld zł i deficyt nie wyższy niż 271,7 mld zł. Najważniejsze dochody: VAT 341,5 mld zł, akcyza 103,3 mld zł, CIT 80,4 mld zł, PIT 32 mld zł (niski, bo duża część PIT trafia do samorządów). Prezydent podpisał ustawę w styczniu 2026 r. i skierował ją do TK.",
            w="deficyt = wydatki − dochody"),
          K("Wydatki sztywne, NBP, budżet zadaniowy",
            "Wydatki sztywne wynikają z ustaw i umów (świadczenia, dotacje do FUS, obsługa długu, subwencje dla JST) – stanowią zdecydowaną większość wydatków, więc rząd ma niewielkie pole manewru. Zysk NBP w 95% trafia do budżetu, ale bank centralny nie może finansować deficytu (art. 220 ust. 2 Konstytucji). Budżet zadaniowy wiąże wydatki z celami i miernikami efektów; wieloletnia prognoza finansowa (WPF) obejmuje co najmniej 4 lata."),
          PF("Prezydent może zawetować ustawę budżetową tak jak inne ustawy.", False,
             why="Musi ją podpisać w 7 dni; może jedynie skierować ją do TK."),
      ],
      mech=[
          LN("Ułóż etapy procedury budżetowej.",
             ["Ministerstwo Finansów przygotowuje projekt na podstawie wniosków dysponentów", "Rada Ministrów przyjmuje projekt i przedkłada go Sejmowi do 30 września", "Sejm rozpatruje projekt w trzech czytaniach i uchwala ustawę", "Senat w ciągu 20 dni może wnieść poprawki", "Prezydent w ciągu 7 dni podpisuje ustawę (może skierować ją do TK)"],
             why="Kolejność i terminy wynikają z art. 222–224 Konstytucji."),
          KT("Którą zasadę budżetową narusza praktyka?",
             {"Zupełności": ["Część wydatków finansowana z funduszy poza budżetem", "Wykazywanie tylko salda dochodów i wydatków jednostki"],
              "Uprzedniości": ["Uchwalenie budżetu dopiero w marcu roku budżetowego"],
              "Jawności": ["Ukrywanie części wydatków przed opinią publiczną"],
              "Równowagi": ["Trwały deficyt kilka procent PKB"]},
             why="Fundusze pozabudżetowe osłabiają przejrzystość i zupełność budżetu."),
          W("Dlaczego rząd ma małe pole manewru przy cięciu wydatków budżetu?",
            "Większość wydatków jest sztywna – wynika z ustaw i umów", "Konstytucja zakazuje zmian wydatków", "Wydatki ustala NBP",
            why="Zmiana wydatków sztywnych wymaga zmiany ustaw."),
          W("Zysk NBP wzrasta dzięki dochodom z rezerw walutowych. Co dzieje się z budżetem w kolejnym roku?",
            "Rosną jego dochody z wpłaty z zysku NBP", "Rosną wydatki na obsługę długu", "Nic, bo zysk NBP zostaje w banku",
            why="95% zysku NBP trafia do budżetu państwa."),
          M("Które źródła należą do największych dochodów budżetu państwa w 2026 r.?",
            ["VAT", "Akcyza", "CIT", "Podatek od posiadania psów"], [0, 1, 2],
            why="Podatek od psów jest dochodem gmin i jest bardzo mały."),
          PF("NBP może kupić obligacje bezpośrednio od Ministerstwa Finansów, by sfinansować deficyt.", False,
             why="Konstytucja zakazuje pokrywania deficytu przez zaciąganie zobowiązań w banku centralnym."),
      ],
      calc=[
          LB("Budżet 2026: wydatki 918,9 mld zł, dochody 647,2 mld zł. Ile wynosi deficyt (mld zł)?",
             271.7, "918.9-647.2", ["918,9 − 647,2 = 271,7 mld zł"], unit="mld zł", tol=0.01),
          LB("Jaki procent dochodów budżetu 2026 stanowi VAT (341,5 z 647,2 mld zł)?",
             52.77, "341.5/647.2*100", ["341,5 / 647,2 ≈ 52,77%"], unit="%", tol=0.02),
          LB("Jaki procent wydatków (918,9 mld zł) pokrywają dochody (647,2 mld zł)?",
             70.43, "647.2/918.9*100", ["647,2 / 918,9 ≈ 70,43%"], unit="%", tol=0.02),
          LB("Zysk NBP 10 mld zł. Ile trafia do budżetu (95%, mld zł)?",
             9.5, "10*0.95", ["10 · 95% = 9,5 mld zł"], unit="mld zł", tol=0.01),
          LB("Wydatki sztywne to 75% z 918,9 mld zł (udział umowny). Ile wynoszą wydatki elastyczne (mld zł)?",
             229.73, "918.9*0.25", ["918,9 · 25% ≈ 229,73 mld zł"], unit="mld zł", tol=0.01),
          LB("Projekt przedłożono Sejmowi 30 września. Po ilu miesiącach od tej daty prezydent może skrócić kadencję Sejmu, jeśli nie dostanie ustawy do podpisu?",
             4, "4", ["Art. 225 Konstytucji: 4 miesiące"], unit="mies."),
      ],
      case=[
          PR("Jest 1 stycznia, a ustawa budżetowa na nowy rok nie została jeszcze uchwalona, bo trwają prace w Sejmie. Ministerstwa muszą wypłacać pensje i świadczenia.",
             W("Na jakiej podstawie rząd prowadzi gospodarkę finansową?",
               "Na podstawie projektu ustawy budżetowej (art. 219 ust. 4)", "Nie może wydawać żadnych pieniędzy", "Na podstawie decyzji NBP",
               why="Konstytucja pozwala działać według przedłożonego projektu."),
             W("Jakie inne rozwiązanie przewiduje Konstytucja na wypadek opóźnień?",
               "Ustawę o prowizorium budżetowym", "Budżet uchwalany przez prezydenta", "Dekret ministra finansów",
               why="Prowizorium to tymczasowa ustawa na część roku."),
             PF("Opóźnienie uchwalenia budżetu narusza zasadę uprzedniości.", True,
                why="Budżet powinien być uchwalony przed rozpoczęciem roku."),
          ),
          PR("W budżecie na 2026 r. VAT ma przynieść 341,5 mld zł, akcyza 103,3 mld zł, CIT 80,4 mld zł, a PIT tylko 32 mld zł, choć PIT płacą miliony osób.",
             W("Dlaczego PIT w budżecie państwa jest tak niski?",
               "Duża część wpływów z PIT trafia do samorządów", "Polacy nie płacą PIT", "PIT został zniesiony",
               why="JST mają udziały we wpływach z PIT mieszkańców."),
             W("Ile łącznie mają przynieść VAT i akcyza (mld zł)?",
               "444,8", "341,5", "421,9",
               why="341,5 + 103,3 = 444,8 mld zł."),
             PF("Duży udział podatków pośrednich czyni dochody budżetu wrażliwymi na wahania konsumpcji.", True,
                why="VAT i akcyza zależą od wydatków konsumentów."),
          ),
      ]),

    L(3, "Rodzaje deficytu i jego finansowanie",
      "Odróżniać deficyt budżetu państwa od deficytu sektora, deficyt strukturalny od cyklicznego i pierwotny od całkowitego, rozumieć deficyty bliźniacze i sposoby finansowania deficytu.",
      ["Deficyt budżetowy i deficyt sektora finansów publicznych", "Nadwyżka budżetowa", "Deficyt strukturalny i cykliczny", "Deficyt pierwotny", "Deficyty bliźniacze", "Finansowanie deficytu"],
      [S303, S305, MFD],
      explain=[
          K("Budżet państwa a sektor",
            "Deficyt budżetu państwa to tylko jeden element. Deficyt sektora instytucji rządowych i samorządowych (GG, metodologia UE – ESA 2010) obejmuje też fundusze pozabudżetowe (np. w BGK), ZUS, NFZ i samorządy. W 2025 r. deficyt GG Polski wyniósł 7,3% PKB – to ta miara liczy się w procedurze nadmiernego deficytu."),
          K("Strukturalny i cykliczny",
            "W recesji wpływy podatkowe spadają, a wydatki na zasiłki rosną – powstaje deficyt cykliczny, który zniknie, gdy gospodarka wróci do potencjału. Deficyt strukturalny to część, która pozostaje nawet przy produkcji potencjalnej – wynika z decyzji o stałych wydatkach i podatkach i wymaga reform.",
            w="deficyt całkowity = strukturalny + cykliczny"),
          W("Gospodarka działa przy PKB potencjalnym, a budżet ma deficyt 3% PKB. Jaki to deficyt?",
            "Strukturalny", "Cykliczny", "Pierwotny ujemny",
            why="Przy produkcji potencjalnej składnik cykliczny jest zerowy."),
          K("Deficyt pierwotny",
            "Deficyt pierwotny = deficyt całkowity − odsetki od długu. Pokazuje, czy bieżące dochody pokrywają wydatki inne niż obsługa długu. Kraj może mieć nadwyżkę pierwotną i jednocześnie deficyt całkowity, jeśli płaci wysokie odsetki.",
            w="deficyt pierwotny = deficyt − odsetki"),
          K("Bliźniacze deficyty i finansowanie",
            "Z tożsamości dochodu: (S − I) + (T − G) = NX. Jeśli oszczędności prywatne nie rosną, wyższy deficyt budżetowy (G > T) wiąże się z deficytem obrotów bieżących – to deficyty bliźniacze (np. USA w latach 80.). Deficyt finansuje się emisją obligacji i bonów skarbowych (krajowych i zagranicznych), kredytami (np. z EBI), prywatyzacją; nie wolno go finansować kredytem z NBP.",
            w="(S − I) + (T − G) = NX"),
          PF("Kraj może mieć nadwyżkę pierwotną i jednocześnie deficyt całkowity.", True,
             why="Gdy odsetki od długu są wyższe niż nadwyżka pierwotna."),
      ],
      mech=[
          KT("Deficyt cykliczny czy strukturalny – co go zwiększa?",
             {"Cykliczny": ["Spadek wpływów z VAT w recesji", "Wzrost liczby zasiłków dla bezrobotnych w kryzysie"],
              "Strukturalny": ["Trwałe obniżenie stawek PIT bez rekompensaty", "Nowe stałe świadczenie socjalne", "Trwały wzrost wydatków na obronę"]},
             why="Cykliczny zależy od koniunktury, strukturalny – od decyzji politycznych."),
          LN("Ułóż mechanizm deficytów bliźniaczych.",
             ["Rząd obniża podatki i zwiększa wydatki", "Rośnie deficyt budżetowy", "Państwo pożycza więcej, a popyt krajowy rośnie", "Rośnie import, a część obligacji kupują zagraniczni inwestorzy", "Pogarsza się saldo obrotów bieżących"],
             why="Oszczędności krajowe nie wystarczają – brakującą część dostarcza zagranica."),
          W("Gospodarka wychodzi z recesji, a deficyt spada z 6% do 4% PKB bez żadnych zmian w podatkach i wydatkach. Który składnik się zmniejszył?",
            "Cykliczny", "Strukturalny", "Pierwotny strukturalny",
            why="Poprawa koniunktury zwiększa dochody i zmniejsza zasiłki."),
          W("Rośnie oprocentowanie obligacji skarbowych. Co dzieje się z deficytem pierwotnym (przy tych samych dochodach i wydatkach poza odsetkami)?",
            "Nie zmienia się, rośnie deficyt całkowity", "Rośnie", "Zamienia się w nadwyżkę",
            why="Odsetki nie wchodzą do deficytu pierwotnego."),
          M("Jak może być finansowany deficyt budżetu państwa w Polsce?",
            ["Emisja obligacji skarbowych", "Kredyty z instytucji międzynarodowych", "Przychody z prywatyzacji", "Kredyt z NBP"], [0, 1, 2],
            why="Art. 220 ust. 2 Konstytucji zakazuje finansowania deficytu przez NBP."),
          PF("Deficyt budżetu państwa jest zawsze równy deficytowi sektora GG.", False,
             why="Sektor GG obejmuje też fundusze, ZUS, NFZ i samorządy."),
      ],
      calc=[
          LB("Deficyt całkowity 6% PKB, odsetki 2,5% PKB. Ile wynosi deficyt pierwotny (% PKB)?",
             3.5, "6-2.5", ["6 − 2,5 = 3,5% PKB"], unit="% PKB", tol=0.01),
          LB("Deficyt 7,3% PKB, z czego cykliczny 0,8% PKB. Ile wynosi strukturalny (% PKB)?",
             6.5, "7.3-0.8", ["7,3 − 0,8 = 6,5% PKB"], unit="% PKB", tol=0.01),
          LB("Luka PKB −3%, elastyczność salda budżetu względem luki 0,5. Ile wynosi deficyt cykliczny (% PKB)?",
             1.5, "3*0.5", ["0,5 · 3 = 1,5% PKB"], unit="% PKB", tol=0.01),
          LB("S − I = 2% PKB, T − G = −5% PKB. Ile wynosi saldo NX (% PKB; ujemne ze znakiem minus)?",
             -3, "2+(-5)", ["2 + (−5) = −3% PKB"], unit="% PKB"),
          LB("Deficyt GG 2025: ok. 284 mld zł, PKB nominalny 3 912,7 mld zł. Ile to % PKB?",
             7.26, "284/3912.7*100", ["284 / 3912,7 ≈ 7,26% (GUS podaje 7,3% z dokładnych danych)"], unit="%", tol=0.02),
          LB("Deficyt 271,7 mld zł finansowany w 75% emisjami krajowymi. Ile wynoszą te emisje (mld zł)?",
             203.78, "271.7*0.75", ["271,7 · 0,75 ≈ 203,78 mld zł"], unit="mld zł", tol=0.01),
      ],
      case=[
          PR("W 2025 r. deficyt sektora GG Polski wyniósł 7,3% PKB (GUS, notyfikacja fiskalna), przy realnym wzroście PKB o 3,6% (GUS), czyli w dobrej koniunkturze – luka produktowa była niewielka. Polska jest objęta procedurą nadmiernego deficytu od lipca 2024 r.",
             W("Jaki charakter ma większość tego deficytu?",
               "Strukturalny – gospodarka nie była w recesji", "Cykliczny – wynik recesji", "Pierwotny dodatni",
               why="W dobrej koniunkturze składnik cykliczny jest mały."),
             W("Co jest potrzebne, by trwale zmniejszyć taki deficyt?",
               "Zmiany ustaw: wyższe dochody lub niższe wydatki", "Wystarczy poczekać na ożywienie", "Kredyt z NBP",
               why="Deficyt strukturalny nie znika sam z koniunkturą."),
             PF("Wysokie wydatki na obronę zwiększają deficyt strukturalny, choć UE dopuszcza pewną elastyczność w ich ocenie.", True,
                why="Klauzula krajowa w nowych regułach UE pozwala częściowo wyłączać wzrost wydatków obronnych."),
          ),
          PR("W latach 80. w USA rząd Reagana obniżył podatki i zwiększył wydatki zbrojeniowe. Deficyt budżetowy wzrósł, a jednocześnie pojawił się duży deficyt handlowy.",
             W("Jak nazywamy to zjawisko?",
               "Deficyty bliźniacze", "Pułapka płynności", "Deficyt pierwotny ujemny",
               why="Deficyt budżetowy i deficyt obrotów bieżących rosły razem."),
             W("Kto sfinansował część deficytu?",
               "Zagraniczni inwestorzy kupujący obligacje USA", "Rezerwa Federalna bezpośrednim kredytem", "Nikt – deficyt sam zniknął",
               why="Napływ kapitału z zagranicy pokrył lukę oszczędności."),
             PF("Napływ kapitału zagranicznego mógł umacniać dolara, co dodatkowo pogarszało saldo handlowe.", True,
                why="Silniejsza waluta czyni import tańszym, a eksport droższym."),
          ),
      ]),

    L(4, "Dług publiczny: dynamika i zarządzanie",
      "Rozumieć, od czego zależy zmiana relacji długu do PKB (saldo pierwotne, stopa procentowa, wzrost PKB), odróżniać definicje długu oraz znać cele i narzędzia zarządzania długiem przez Ministerstwo Finansów.",
      ["Dług publiczny", "Obsługa i zarządzanie długiem publicznym", "Deficyt pierwotny", "Finansowanie deficytu"],
      [S303, MFD],
      explain=[
          K("Dwie miary długu",
            "Dług sektora GG (definicja UE, EDP) – w 2025 r. 59,7% PKB – służy do porównań w UE i ocenie w Pakcie Stabilności. Państwowy dług publiczny (definicja krajowa) nie obejmuje m.in. długu funduszy w BGK (np. Funduszu Wsparcia Sił Zbrojnych) – na 2026 r. prognozowano 53,8% PKB. Progi ustawowe (55%) i konstytucyjny (60%) dotyczą miary krajowej."),
          K("Matematyka długu",
            "Relacja długu do PKB rośnie, gdy państwo ma deficyt pierwotny i gdy stopa procentowa od długu (r) przewyższa tempo wzrostu nominalnego PKB (g). Przy r < g dług może maleć w relacji do PKB nawet przy niewielkim deficycie pierwotnym – PKB „przerasta” dług.",
            w="Δd ≈ (r − g)/(1 + g) · d − saldo pierwotne"),
          W("Dług 50% PKB, r = 5%, g = 5%, saldo pierwotne 0. Co dzieje się z relacją długu do PKB?",
            "Pozostaje stała", "Rośnie", "Spada",
            why="Przy r = g i zerowym saldzie pierwotnym relacja się nie zmienia."),
          K("Zarządzanie długiem",
            "MF w strategii zarządzania długiem dąży do minimalizacji kosztów obsługi w długim okresie przy akceptowalnym ryzyku. Ryzyka: refinansowania (dużo długu zapada naraz), stopy procentowej (dług o zmiennym kuponie), kursowe (dług w walutach obcych), płynności. Narzędzia: wydłużanie średniej zapadalności, ograniczanie udziału długu walutowego, rozkładanie wykupów, przedterminowe odkupy (buy-back) i zamiany obligacji."),
          K("Koszt obsługi długu",
            "Wydatki na odsetki rosną, gdy rośnie dług i stopy procentowe. Każda złotówka na odsetki to złotówka mniej na inne cele lub wyższe podatki. Wiarygodna polityka fiskalna obniża premię za ryzyko, a więc rentowność obligacji i koszty obsługi."),
          PF("Dług w walucie obcej rośnie w złotych, gdy złoty się osłabia.", True,
             why="Do spłaty trzeba kupić więcej walut za złote."),
      ],
      mech=[
          LN("Ułóż spiralę zadłużenia.",
             ["Kraj ma wysoki dług i deficyt pierwotny", "Inwestorzy żądają wyższej premii za ryzyko", "Rosną rentowności i koszty odsetek", "Deficyt całkowity i dług rosną jeszcze szybciej", "Relacja długu do PKB wymyka się spod kontroli"],
             why="Gdy r rośnie powyżej g, dług napędza sam siebie."),
          KT("Jakie ryzyko zarządzania długiem ogranicza działanie?",
             {"Ryzyko refinansowania": ["Rozłożenie wykupów obligacji równomiernie w czasie", "Wydłużenie średniej zapadalności długu"],
              "Ryzyko kursowe": ["Zmniejszenie udziału długu w euro i dolarach", "Zabezpieczenie emisji zagranicznej swapem walutowym"],
              "Ryzyko stopy procentowej": ["Emisja obligacji stałokuponowych zamiast zmiennokuponowych", "Ograniczenie krótkoterminowych bonów"]},
             why="Każde narzędzie dotyczy innego źródła niepewności."),
          W("Inflacja przyspiesza, a rentowność długu o stałym kuponie się nie zmienia. Co dzieje się z relacją długu do PKB?",
            "Spada, bo rośnie nominalny PKB", "Rośnie", "Nie zmienia się",
            why="Wyższe g przy stałym r obniża relację – inflacja „zjada” dług."),
          W("Dlaczego MF woli emitować obligacje długoterminowe, choć często są droższe niż krótkie?",
            "Zmniejszają ryzyko refinansowania i zmiany stóp", "Są zawsze tańsze", "Nie trzeba ich nigdy spłacać",
            why="Państwo „zamyka” koszt na dłużej i rzadziej musi refinansować dług."),
          M("Co obniża relację długu do PKB?",
            ["Nadwyżka pierwotna", "Szybki wzrost nominalnego PKB", "Spadek stóp procentowych od długu", "Deprecjacja złotego przy dużym długu walutowym"], [0, 1, 2],
            why="Deprecjacja zwiększa wartość długu walutowego w złotych."),
          PF("Dług sektora GG jest w Polsce wyższy niż państwowy dług publiczny, bo obejmuje m.in. fundusze w BGK.", True,
             why="Miara UE jest szersza od krajowej."),
      ],
      calc=[
          LB("Dług 60% PKB, r = 6%, g = 8%, saldo pierwotne 0. O ile pkt proc. zmieni się relacja? (ujemna – spadek; Δd = (r − g)/(1 + g) · d)",
             -1.11, "(0.06-0.08)/1.08*60", ["(−0,02 / 1,08) · 60 ≈ −1,11 pkt proc."], unit="pkt proc.", tol=0.02),
          LB("Dług 60% PKB, r = 6%, g = 4%, deficyt pierwotny 2% PKB. O ile pkt proc. wzrośnie relacja?",
             3.15, "(0.06-0.04)/1.04*60+2", ["(0,02 / 1,04) · 60 ≈ 1,15", "+ 2 = 3,15 pkt proc."], unit="pkt proc.", tol=0.02),
          LB("Jaka nadwyżka pierwotna (% PKB) ustabilizuje dług 60% PKB przy r = 6% i g = 4%?",
             1.15, "(0.06-0.04)/1.04*60", ["(0,02 / 1,04) · 60 ≈ 1,15% PKB"], unit="% PKB", tol=0.02),
          LB("Dług 2 335 mld zł, średnie oprocentowanie 4,5%. Ile wynoszą roczne odsetki (mld zł)?",
             105.08, "2335*0.045", ["2335 · 4,5% ≈ 105,08 mld zł"], unit="mld zł", tol=0.01),
          LB("Dług walutowy 300 mld zł przy kursie 4,30 zł/EUR. Złoty słabnie do 4,73 zł. O ile mld zł rośnie wartość tego długu?",
             30, "300*(4.73/4.30-1)", ["4,73 / 4,30 = 1,10", "300 · 10% = 30 mld zł"], unit="mld zł", tol=0.01),
          LB("Średnia rentowność rośnie o 1 pkt proc., a co roku refinansuje się 15% długu 2 335 mld zł. O ile wzrosną odsetki po pierwszym roku (mld zł)?",
             3.5, "2335*0.15*0.01", ["2335 · 15% = 350,25", "· 1% ≈ 3,5 mld zł"], unit="mld zł", tol=0.01),
      ],
      case=[
          PR("Kraj A: dług 90% PKB, r = 3%, g (nominalny wzrost) = 6%. Kraj B: dług 60% PKB, r = 7%, g = 3%. Oba mają zerowe saldo pierwotne (dane umowne).",
             W("W którym kraju relacja długu do PKB będzie rosła?",
               "B", "A", "W obu",
               why="W B r > g, w A r < g."),
             W("O ile pkt proc. w przybliżeniu zmieni się relacja w kraju A w ciągu roku?",
               "Spadnie o ok. 2,5 pkt proc.", "Wzrośnie o ok. 2,5 pkt proc.", "Nie zmieni się",
               why="(0,03 − 0,06)/1,06 · 90 ≈ −2,5."),
             PF("Wysoki dług nie musi oznaczać kryzysu, jeśli koszty obsługi są niskie, a gospodarka szybko rośnie.", True,
                why="Kluczowa jest relacja r do g i wiarygodność polityki."),
          ),
          PR("Ministerstwo Finansów planuje w kolejnym roku wykup obligacji za 180 mld zł oraz deficyt 270 mld zł. Rynki wymagają wysokiej rentowności, bo inwestorzy obawiają się o finanse publiczne.",
             W("Ile wynoszą potrzeby pożyczkowe brutto (bez innych pozycji)?",
               "450 mld zł", "270 mld zł", "90 mld zł",
               why="Deficyt plus wykup zapadającego długu: 270 + 180."),
             W("Co może zrobić MF, by zmniejszyć ryzyko refinansowania?",
               "Wydłużyć zapadalność nowych emisji i wcześniej odkupić część obligacji (buy-back)", "Emitować tylko bony 3-miesięczne", "Poprosić NBP o kredyt",
               why="Dłuższe terminy rozkładają wykupy w czasie; kredyt z NBP jest zakazany."),
             PF("Wiarygodny plan ograniczania deficytu może obniżyć rentowności obligacji.", True,
                why="Spada premia za ryzyko fiskalne."),
          ),
      ]),

    L(5, "Finanse samorządów, PPP i zamówienia publiczne",
      "Rozumieć źródła dochodów samorządów (dochody własne, udziały w PIT i CIT, subwencje, dotacje), mechanizmy wyrównawcze, reguły zadłużenia JST oraz zasady partnerstwa publiczno-prywatnego, zamówień publicznych i dyscypliny finansów publicznych.",
      ["Samorząd terytorialny w Polsce", "Subwencja i dotacja", "Janosikowe", "Reguły finansowe JST", "Partnerstwo publiczno-prywatne (PPP)", "Zamówienia publiczne", "Dyscyplina finansów publicznych"],
      [MFB, KONST],
      explain=[
          K("Trzy szczeble i ich dochody",
            "Samorząd w Polsce ma trzy szczeble: gminy (ok. 2,5 tys.), powiaty i województwa. Dochody: własne (podatki i opłaty lokalne, majątek), udziały w PIT i CIT, a także subwencje i dotacje z budżetu państwa. Od 2025 r. (ustawa z 1.10.2024) udziały w PIT i CIT liczy się jako procent dochodów podatników z terenu danej jednostki, a nie podatku należnego – samorządy nie tracą już automatycznie na obniżkach podatków przez państwo."),
          K("Subwencja a dotacja",
            "Subwencja to środki ogólne – samorząd sam decyduje, na co je wyda (np. część oświatowa na szkoły). Dotacja jest celowa – na konkretne zadanie (np. zadania zlecone z administracji rządowej, inwestycja), trzeba ją rozliczyć, a niewykorzystaną lub wydaną niezgodnie z przeznaczeniem – zwrócić."),
          W("Gmina dostaje 2 mln zł z budżetu państwa na wypłatę świadczeń w ramach zadania zleconego. To:",
            "Dotacja celowa", "Subwencja ogólna", "Dochód własny",
            why="Środki mają ściśle określone przeznaczenie i podlegają rozliczeniu."),
          K("Wyrównywanie i reguły zadłużenia",
            "Bogate i biedne samorządy mają bardzo różne dochody na mieszkańca. Janosikowe to wpłaty najbogatszych JST (np. województwa mazowieckiego i Warszawy) na rzecz wyrównania dochodów biedniejszych – w systemie obowiązującym do 2024 r. budziło duże spory. Reguły JST: wydatki bieżące nie mogą przekraczać dochodów bieżących (powiększonych o nadwyżkę i wolne środki, art. 242 ufp), a obsługa długu nie może przekroczyć indywidualnego wskaźnika zadłużenia (art. 243 ufp)."),
          K("PPP, zamówienia i dyscyplina",
            "W partnerstwie publiczno-prywatnym partner prywatny buduje i często finansuje oraz eksploatuje infrastrukturę (np. drogę, parking), a podmiot publiczny płaci mu wynagrodzenie lub przyznaje prawo do opłat – ryzyka są dzielone. Zamówienia publiczne (Prawo zamówień publicznych z 2019 r.) wymagają konkurencyjnego wyboru wykonawcy, gdy wartość zamówienia przekracza 130 000 zł netto. Naruszenie dyscypliny finansów publicznych (np. wydatek bez upoważnienia, przekroczenie planu) grozi odpowiedzialnością osób, które za nie odpowiadają."),
          PF("Subwencję samorząd może wydać na dowolne zadanie własne.", True,
             why="Subwencja jest środkiem ogólnym, w przeciwieństwie do dotacji celowej."),
      ],
      mech=[
          KT("Dochód własny, subwencja czy dotacja?",
             {"Dochód własny": ["Podatek od nieruchomości", "Opłata targowa", "Czynsz z najmu lokali gminnych"],
              "Subwencja": ["Część oświatowa na prowadzenie szkół", "Środki ogólne bez wskazanego celu"],
              "Dotacja": ["Środki na wykonanie zadania zleconego przez wojewodę", "Dofinansowanie budowy hali sportowej"]},
             why="Kryterium: źródło środków i swoboda ich wydatkowania."),
          LN("Ułóż, jak działa wyrównywanie dochodów samorządów.",
             ["Dochody na mieszkańca różnią się między regionami", "Ustala się wskaźnik dochodów względem średniej", "Najbogatsze jednostki wpłacają środki do wspólnej puli", "Biedniejsze jednostki otrzymują część wyrównawczą", "Różnice w możliwościach finansowania usług maleją"],
             why="Mechanizm ma zapewnić podobny standard usług publicznych w kraju."),
          W("Gmina chce wziąć duży kredyt na inwestycję. Co może ją ograniczać?",
            "Indywidualny wskaźnik zadłużenia z art. 243 ustawy o finansach publicznych", "Decyzja NBP", "Limit WIBOR",
            why="Reguła ogranicza obsługę długu w relacji do dochodów."),
          W("Dlaczego gmina wybiera PPP do budowy parkingu podziemnego?",
            "Partner prywatny wnosi kapitał i bierze część ryzyka, a gmina nie musi od razu finansować całej inwestycji", "PPP zwalnia z prawa zamówień publicznych w każdym przypadku", "Bo PPP jest zawsze tańsze",
            why="PPP dzieli finansowanie i ryzyko, ale wymaga rzetelnej analizy kosztów."),
          M("Co może stanowić naruszenie dyscypliny finansów publicznych?",
            ["Dokonanie wydatku bez upoważnienia w planie finansowym", "Udzielenie zamówienia z pominięciem przepisów Pzp", "Niezwrócenie dotacji wykorzystanej niezgodnie z przeznaczeniem", "Uchwalenie budżetu gminy z nadwyżką"], [0, 1, 2],
            why="Nadwyżka budżetowa nie narusza dyscypliny."),
          PF("Od 2025 r. obniżka stawek PIT przez państwo nie zmniejsza automatycznie dochodów gmin z udziału w PIT.", True,
             why="Udział liczony jest od dochodów podatników, a nie od należnego podatku."),
      ],
      calc=[
          LB("Gmina: dochody bieżące 80 mln zł, wydatki bieżące 76 mln zł. Ile wynosi nadwyżka operacyjna (mln zł)?",
             4, "80-76", ["80 − 76 = 4 mln zł"], unit="mln zł"),
          LB("Miasto na prawach powiatu dostaje 8,6% dochodów podatników PIT. Dochody mieszkańców wynoszą 12 mld zł. Ile wyniesie udział (mln zł)?",
             1032, "12000*0.086", ["12 000 mln · 8,6% = 1032 mln zł"], unit="mln zł"),
          LB("Dotacja 500 000 zł, wydano zgodnie z celem 460 000 zł. Ile trzeba zwrócić (zł)?",
             40000, "500000-460000", ["500 000 − 460 000 = 40 000 zł"], unit="zł"),
          LB("Zamówienie o wartości 155 000 zł brutto (VAT 23%). Ile wynosi wartość netto (zł)?",
             126016.26, "155000/1.23", ["155 000 / 1,23 ≈ 126 016,26 zł – poniżej progu 130 000 zł"], unit="zł", tol=0.01),
          LB("PPP: partner buduje parking za 40 mln zł, gmina płaci 3,6 mln zł rocznie przez 20 lat. Ile wynosi suma płatności (mln zł)?",
             72, "3.6*20", ["3,6 · 20 = 72 mln zł"], unit="mln zł"),
          LB("Wartość bieżąca tych płatności (3,6 mln zł przez 20 lat) przy stopie 6%. Ile wynosi (mln zł)?",
             41.29, "3.6*(1-1.06**-20)/0.06", ["3,6 · (1 − 1,06⁻²⁰) / 0,06 ≈ 41,29 mln zł"], unit="mln zł", tol=0.01),
      ],
      case=[
          PR("Średnie miasto planuje budowę nowej linii tramwajowej za 600 mln zł. Ma dochody bieżące 1,5 mld zł, a jego wskaźnik zadłużenia z art. 243 jest bliski limitu. Może dostać dotację unijną na 60% kosztów.",
             W("Ile musi sfinansować samo (mln zł)?",
               "240", "360", "600",
               why="600 · 40% = 240 mln zł."),
             W("Co może ograniczać możliwość kredytu na wkład własny?",
               "Reguła indywidualnego wskaźnika zadłużenia", "Brak prawa do zaciągania kredytów przez miasta", "Zasada jedności budżetu państwa",
               why="Wysoka obsługa długu w relacji do dochodów blokuje nowe kredyty."),
             PF("Dotacja unijna jest środkiem celowym, który trzeba rozliczyć zgodnie z umową.", True,
                why="Wydatki muszą odpowiadać celom projektu."),
          ),
          PR("Gmina zleca remont drogi o wartości 2 mln zł netto bez przetargu jednej firmie, której właściciel jest znajomym wójta. Regionalna Izba Obrachunkowa wykrywa nieprawidłowości.",
             W("Jakie przepisy prawdopodobnie naruszono?",
               "Prawo zamówień publicznych – zamówienie powyżej progu wymaga konkurencyjnego trybu", "Ustawę o NBP", "Przepisy o podatku Belki",
               why="2 mln zł znacznie przekracza próg 130 000 zł netto."),
             W("Jaki jest ekonomiczny skutek braku konkurencji?",
               "Wyższa cena lub gorsza jakość dla mieszkańców", "Niższa cena", "Brak skutków",
               why="Konkurencja ofert obniża koszt zamówienia."),
             PF("Za takie naruszenie może grozić odpowiedzialność za naruszenie dyscypliny finansów publicznych.", True,
                why="Udzielenie zamówienia z naruszeniem Pzp jest wymienione w ustawie o odpowiedzialności."),
          ),
      ]),
]
