# -*- coding: utf-8 -*-
# Zrozumienie – Podstawy finansów / Ubezpieczenia
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-08"
S162 = S("OpenStax, Principles of Economics 3e, 16.2 Insurance and Imperfect Information", OS3 + "16-2-insurance-and-imperfect-information", D)
KNF = S("Komisja Nadzoru Finansowego", "https://www.knf.gov.pl/", D)
UFG = S("Ubezpieczeniowy Fundusz Gwarancyjny", "https://www.ufg.pl/", D)
PIU = S("Polska Izba Ubezpieczeń", "https://piu.org.pl/", D)
ZUS = S("ZUS – wysokość składek na ubezpieczenia społeczne (2026)", "https://www.zus.pl/baza-wiedzy/skladki-wskazniki-odsetki/skladki/wysokosc-skladek-na-ubezpieczenia-spoleczne", D)
RF = S("Rzecznik Finansowy", "https://www.rf.gov.pl/", D)

LESSONS = [
    L(1, "Jak działa ubezpieczenie",
      "Rozumieć ubezpieczenie jako rozłożenie ryzyka na wielu uczestników, rolę prawa wielkich liczb i aktuariusza w ustalaniu składki oraz podział na działy i formy organizacyjne ubezpieczycieli.",
      ["Ubezpieczenie", "Aktuariusz", "Działy ubezpieczeń", "Towarzystwo ubezpieczeń wzajemnych (TUW)"],
      [S162, PIU],
      explain=[
          K("Wspólnota ryzyka",
            "Wiele osób narażonych na podobne, losowe zdarzenie (pożar, wypadek) wpłaca niewielkie składki do wspólnego funduszu. Z niego pokrywa się straty tych nielicznych, którym zdarzenie się przydarzy. Pewny, mały koszt (składka) zastępuje niepewną, dużą stratę – dlatego ubezpieczenie opłaca się osobom niechętnym ryzyku."),
          K("Prawo wielkich liczb i składka",
            "Dla jednej osoby szkoda jest nieprzewidywalna, ale dla tysięcy osób jej częstość jest bardzo stabilna. Aktuariusz szacuje składkę czystą (netto) = prawdopodobieństwo szkody × przeciętna wartość szkody, a następnie dodaje narzut na koszty, zysk i bezpieczeństwo.",
            w="składka netto = p · średnia szkoda;  składka brutto = netto + narzut"),
          W("Prawdopodobieństwo kradzieży roweru w roku to 2%, przeciętna szkoda 2500 zł. Ile wynosi składka netto?",
            "50 zł", "2500 zł", "500 zł",
            why="0,02 · 2500 = 50 zł."),
          K("Działy ubezpieczeń",
            "Dział I – ubezpieczenia na życie (śmierć, dożycie, posagowe, z UFK). Dział II – pozostałe osobowe i majątkowe (NNW, zdrowotne, komunikacyjne, OC, mienie). Jeden zakład nie może prowadzić działalności w obu działach naraz – stąd osobne spółki „życiowe” i „majątkowe” w jednej grupie."),
          K("Formy organizacyjne",
            "Zakład ubezpieczeń działa jako spółka akcyjna (dąży do zysku dla akcjonariuszy) albo towarzystwo ubezpieczeń wzajemnych – TUW, którego członkami są sami ubezpieczeni. W TUW nadwyżka może wrócić do członków, a przy stratach mogą być zobowiązani do dopłat. Nadzór sprawuje KNF."),
          PF("Ubezpieczyciel z 10 klientami może przewidzieć łączne szkody równie dokładnie jak ubezpieczyciel z 100 000 klientów.", False,
             why="Prawo wielkich liczb działa przy dużej liczbie podobnych ryzyk."),
      ],
      mech=[
          LN("Ułóż drogę od ryzyka do wypłaty odszkodowania.",
             ["Wiele osób jest narażonych na podobne ryzyko", "Aktuariusz szacuje częstość i wysokość szkód", "Klienci płacą składki do wspólnego funduszu", "U części klientów zachodzi zdarzenie losowe", "Ubezpieczyciel wypłaca odszkodowania z funduszu"],
             why="Ubezpieczenie przenosi ryzyko z jednostki na grupę."),
          KT("Dział I czy dział II?",
             {"Dział I (na życie)": ["Ubezpieczenie na wypadek śmierci", "Ubezpieczenie posagowe dla dziecka", "Polisa z ubezpieczeniowym funduszem kapitałowym"],
              "Dział II (pozostałe)": ["OC komunikacyjne", "Autocasco", "Ubezpieczenie mieszkania od pożaru", "NNW szkolne"]},
             why="Dział I obejmuje ryzyka związane z życiem człowieka."),
          W("Ubezpieczyciel zauważa, że liczba kradzieży aut w mieście wzrosła dwukrotnie. Co zrobi ze składką AC w tym mieście?",
            "Podniesie ją", "Obniży ją", "Pozostawi bez zmian, bo to sprawa policji",
            why="Składka netto rośnie razem z prawdopodobieństwem szkody."),
          M("Jakie ryzyka nadają się do ubezpieczenia?",
            ["Losowe i niezależne od woli ubezpieczonego", "Dotyczące wielu podobnych obiektów", "Pewne – np. zużycie opon", "Mierzalne w pieniądzu"], [0, 1, 3],
            why="Zdarzenie pewne nie jest ryzykiem i nie da się go ubezpieczyć."),
          W("Czym TUW różni się od spółki akcyjnej?",
            "Członkami są sami ubezpieczeni, a nadwyżka może do nich wrócić", "TUW nie podlega nadzorowi KNF", "TUW prowadzi tylko ubezpieczenia obowiązkowe",
            why="TUW działa na zasadzie wzajemności."),
          PF("Składka brutto jest wyższa od oczekiwanej wartości szkody.", True,
             why="Zawiera narzut na koszty działalności, zysk i rezerwę bezpieczeństwa."),
      ],
      calc=[
          LB("Prawdopodobieństwo pożaru domu 0,2% rocznie, średnia szkoda 400 000 zł. Ile wynosi składka netto (zł)?",
             800, "0.002*400000", ["0,002 · 400 000 = 800 zł"], unit="zł"),
          LB("Składka netto 800 zł, narzut 25% składki netto. Ile wynosi składka brutto (zł)?",
             1000, "800*1.25", ["800 · 1,25 = 1000 zł"], unit="zł"),
          LB("Ubezpieczyciel ma 50 000 klientów, a prawdopodobieństwo szkody wynosi 3%. Ilu szkód oczekuje w roku?",
             1500, "50000*0.03", ["50 000 · 3% = 1500"], unit="szkód"),
          LB("1500 szkód po średnio 6000 zł. Ile wynoszą oczekiwane wypłaty (mln zł)?",
             9, "1500*6000/1e6", ["1500 · 6000 = 9 000 000 zł"], unit="mln zł"),
          LB("Te wypłaty (9 mln zł) mają pokryć składki 50 000 klientów. Ile wynosi składka netto na osobę (zł)?",
             180, "9e6/50000", ["9 000 000 / 50 000 = 180 zł"], unit="zł"),
          LB("Szkodowość = odszkodowania / składki. Odszkodowania 720 mln zł, składki 1,2 mld zł. Ile wynosi szkodowość (%)?",
             60, "720/1200*100", ["720 / 1200 = 60%"], unit="%"),
      ],
      case=[
          PR("Pan Adam ma dom wart 600 000 zł. Ryzyko całkowitego zniszczenia w roku wynosi 0,1%. Ubezpieczyciel proponuje polisę za 900 zł rocznie.",
             W("Ile wynosi oczekiwana roczna strata?",
               "600 zł", "900 zł", "6000 zł",
               why="0,001 · 600 000 = 600 zł."),
             W("Dlaczego Pan Adam może kupić polisę, choć składka przekracza oczekiwaną stratę?",
               "Jest niechętny ryzyku – woli pewny koszt niż ryzyko utraty domu", "Bo ubezpieczenie domu jest obowiązkowe", "Bo składka jest niższa od oczekiwanej straty",
               why="Pewna strata 900 zł jest dla niego lepsza niż 0,1% szansy na stratę 600 000 zł."),
             PF("Nadwyżka 300 zł pokrywa koszty, zysk i rezerwy ubezpieczyciela.", True,
                why="To narzut ponad składkę netto."),
          ),
          PR("Małe TUW rolnicze ubezpiecza 300 gospodarstw w jednej gminie od gradobicia. W jednym roku burza gradowa zniszczyła uprawy w połowie gospodarstw.",
             W("Dlaczego to ryzyko jest trudne dla małego TUW?",
               "Szkody są skorelowane – jedno zdarzenie dotyka wielu klientów naraz", "Grad nie jest zdarzeniem losowym", "TUW nie może ubezpieczać rolników",
               why="Prawo wielkich liczb zawodzi, gdy ryzyka nie są niezależne."),
             W("Co może zrobić TUW, by ograniczyć to ryzyko?",
               "Przekazać część ryzyka reasekuratorowi", "Zrezygnować z badania szkód", "Obniżyć składki",
               why="Reasekuracja rozkłada ryzyko na większą, zróżnicowaną grupę."),
             PF("Członkowie TUW mogą być wezwani do dopłat, jeśli fundusz nie wystarczy na odszkodowania.", True,
                why="Statut TUW może przewidywać obowiązek dopłat."),
          ),
      ]),

    L(2, "Asymetria informacji i franszyzy",
      "Rozumieć, jak negatywna selekcja i pokusa nadużycia zagrażają ubezpieczycielom, oraz jak franszyza integralna, redukcyjna i udział własny ograniczają te problemy.",
      ["Franszyza integralna i redukcyjna", "Ubezpieczenie"],
      [S162, RF],
      explain=[
          K("Negatywna selekcja",
            "Klient zna swoje ryzyko lepiej niż ubezpieczyciel. Jeśli składka jest jednakowa dla wszystkich, najchętniej kupują ją osoby o wysokim ryzyku, a osoby ostrożne rezygnują. Średnie szkody rosną, składka rośnie, odchodzą kolejni „dobrzy” klienci – w skrajnym przypadku rynek zanika (spirala śmierci)."),
          K("Pokusa nadużycia",
            "Po zawarciu umowy ubezpieczony może mniej dbać o mienie, bo stratę pokryje ubezpieczyciel (np. nie zamyka auta, rzadziej serwisuje instalację). Rośnie prawdopodobieństwo szkody, którego ubezpieczyciel nie może łatwo obserwować."),
          W("Po wykupieniu ubezpieczenia od kradzieży kierowca przestaje włączać alarm. Jak nazywamy to zjawisko?",
            "Pokusa nadużycia", "Negatywna selekcja", "Niedoubezpieczenie",
            why="Zmiana zachowania następuje po zawarciu umowy."),
          K("Franszyzy i udział własny",
            "Franszyza integralna: szkody do określonej kwoty nie są wypłacane, a powyżej niej – w całości. Eliminuje drobne, kosztowne w obsłudze szkody. Franszyza redukcyjna (udział własny): z każdego odszkodowania potrąca się stałą kwotę lub procent – klient zawsze ponosi część straty, co ogranicza pokusę nadużycia.",
            w="integralna: S ≤ F → 0, S > F → S;  redukcyjna: max(0, S − F)"),
          K("Jak ubezpieczyciel się broni",
            "Przed negatywną selekcją: ankiety i badania (np. lekarskie), różnicowanie składki według ryzyka (wiek, historia szkód), ubezpieczenia grupowe i obowiązkowe. Przed pokusą nadużycia: udział własny, zniżki za bezszkodową jazdę (bonus-malus), wymogi zabezpieczeń (alarm, gaśnica)."),
          PF("Obowiązkowe OC komunikacyjne ogranicza negatywną selekcję, bo kupują je wszyscy kierowcy, nie tylko ryzykowni.", True,
             why="Pula ubezpieczonych obejmuje także osoby o niskim ryzyku."),
      ],
      mech=[
          LN("Ułóż spiralę negatywnej selekcji.",
             ["Ubezpieczyciel ustala jedną składkę dla wszystkich", "Osoby o niskim ryzyku uznają ją za za drogą i rezygnują", "W puli zostają głównie osoby o wysokim ryzyku", "Średnie szkody rosną, więc składka rośnie", "Rezygnują kolejni klienci – rynek się kurczy"],
             why="Asymetria informacji przed zawarciem umowy."),
          KT("Negatywna selekcja czy pokusa nadużycia?",
             {"Negatywna selekcja": ["Osoby chore chętniej kupują ubezpieczenie zdrowotne", "Ubezpieczenie od powodzi kupują głównie mieszkańcy terenów zalewowych"],
              "Pokusa nadużycia": ["Ubezpieczony przestaje zamykać mieszkanie", "Pacjent z pełną refundacją częściej chodzi na zbędne wizyty"]},
             why="Selekcja – przed umową; pokusa – po umowie."),
          W("Który mechanizm najlepiej ogranicza pokusę nadużycia?",
            "Udział własny w każdej szkodzie", "Jednakowa składka dla wszystkich", "Rezygnacja z wywiadu medycznego",
            why="Klient sam ponosi część straty, więc bardziej dba o mienie."),
          W("Ubezpieczyciel wprowadza zniżki za lata bez szkód (bonus-malus). Na co odpowiada?",
            "Na oba problemy: premiuje ostrożnych i zniechęca do niedbałości", "Tylko na problem niedoubezpieczenia", "Na żaden z nich",
            why="Historia szkód ujawnia ryzyko i nagradza ostrożność."),
          M("Które działania ograniczają negatywną selekcję?",
            ["Badania lekarskie przed polisą na życie", "Składka zależna od wieku i historii szkód", "Ubezpieczenia grupowe w zakładzie pracy", "Wypłata odszkodowania bez weryfikacji"], [0, 1, 2],
            why="Brak weryfikacji wręcz zachęca do nadużyć."),
          PF("Przy franszyzie integralnej 500 zł szkoda 600 zł zostanie wypłacona w kwocie 100 zł.", False,
             why="Integralna – powyżej progu wypłaca się całość, czyli 600 zł."),
      ],
      calc=[
          LB("Franszyza integralna 500 zł. Szkoda 450 zł. Ile wypłaci ubezpieczyciel (zł)?",
             0, "0", ["450 ≤ 500 → brak wypłaty"], unit="zł"),
          LB("Franszyza integralna 500 zł. Szkoda 2000 zł. Ile wypłaci ubezpieczyciel (zł)?",
             2000, "2000", ["2000 > 500 → wypłata w całości"], unit="zł"),
          LB("Franszyza redukcyjna 500 zł. Szkoda 2000 zł. Ile wypłaci ubezpieczyciel (zł)?",
             1500, "2000-500", ["2000 − 500 = 1500 zł"], unit="zł"),
          LB("Udział własny 10% szkody. Szkoda 12 000 zł. Ile wypłaci ubezpieczyciel (zł)?",
             10800, "12000*0.9", ["12 000 · 90% = 10 800 zł"], unit="zł"),
          LB("Pula: 50% klientów o szkodzie oczekiwanej 200 zł i 50% o 1000 zł. Ile wynosi składka netto przy jednej stawce (zł)?",
             600, "0.5*200+0.5*1000", ["0,5 · 200 + 0,5 · 1000 = 600 zł"], unit="zł"),
          LB("Klienci o niskim ryzyku odeszli – zostali tylko ci z oczekiwaną szkodą 1000 zł. O ile procent musi wzrosnąć składka netto z 600 zł?",
             66.67, "(1000/600-1)*100", ["1000 / 600 − 1 ≈ 66,67%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Nowy ubezpieczyciel oferuje tanie ubezpieczenie zdrowotne bez ankiety medycznej, z jedną składką 150 zł miesięcznie dla wszystkich i bez udziału własnego.",
             W("Jakich klientów przyciągnie najbardziej?",
               "Osoby, które spodziewają się wysokich kosztów leczenia", "Osoby zdrowe i młode", "Wszystkich po równo",
               why="Dla osób o wysokim ryzyku jednolita składka jest okazją."),
             W("Jak brak udziału własnego wpłynie na zachowanie ubezpieczonych?",
               "Będą częściej korzystać z usług, nawet niekoniecznych", "Będą rzadziej chodzić do lekarza", "Nie wpłynie",
               why="Koszt wizyty dla pacjenta wynosi zero – to pokusa nadużycia."),
             PF("Wprowadzenie ankiety medycznej i udziału własnego poprawiłoby wynik finansowy ubezpieczyciela.", True,
                why="Ogranicza obie formy asymetrii informacji."),
          ),
          PR("Ubezpieczenie AC: szkoda parkingowa 900 zł. Wariant A: franszyza integralna 1000 zł, składka 1800 zł. Wariant B: udział własny 500 zł w każdej szkodzie, składka 1600 zł.",
             W("Ile dostanie kierowca w wariancie A?",
               "0 zł", "900 zł", "400 zł",
               why="900 ≤ 1000 – franszyza integralna wyklucza wypłatę."),
             W("Ile dostanie w wariancie B?",
               "400 zł", "900 zł", "0 zł",
               why="900 − 500 = 400 zł."),
             W("Przy dużej szkodzie 20 000 zł który wariant daje wyższą wypłatę?",
               "A – 20 000 zł", "B – 20 000 zł", "Oba po 19 500 zł",
               why="A wypłaca całość powyżej progu, B potrąca 500 zł."),
          ),
      ]),

    L(3, "Suma ubezpieczenia, OC i AC w praktyce",
      "Liczyć odszkodowanie przy niedoubezpieczeniu (zasada proporcji), rozumieć zakaz wzbogacenia przy nadubezpieczeniu, odróżniać OC, AC i NNW oraz wiedzieć, jak działa BLS i UFG.",
      ["Suma ubezpieczenia, niedoubezpieczenie i nadubezpieczenie", "Autocasco (AC) i NNW", "Ubezpieczenia obowiązkowe w Polsce", "Bezpośrednia likwidacja szkód (BLS)"],
      [UFG, RF],
      explain=[
          K("Suma ubezpieczenia",
            "To górna granica odpowiedzialności ubezpieczyciela, zwykle równa wartości mienia. Gdy suma jest niższa od wartości (niedoubezpieczenie), przy zasadzie proporcji odszkodowanie zmniejsza się w tym samym stosunku. Gdy wyższa (nadubezpieczenie), i tak wypłaca się najwyżej rzeczywistą szkodę – ubezpieczenie majątkowe nie może wzbogacać.",
            w="odszkodowanie = szkoda · (suma ubezpieczenia / wartość mienia)"),
          W("Dom wart 500 000 zł ubezpieczono na 250 000 zł. Szkoda 100 000 zł. Ile wypłaci ubezpieczyciel przy zasadzie proporcji?",
            "50 000 zł", "100 000 zł", "250 000 zł",
            why="100 000 · 250/500 = 50 000 zł."),
          K("OC, AC, NNW",
            "OC posiadaczy pojazdów jest obowiązkowe i pokrywa szkody, które wyrządziliśmy innym. Autocasco (AC) jest dobrowolne i pokrywa szkody we własnym aucie (kolizja z naszej winy, kradzież, grad). NNW wypłaca świadczenie za uszczerbek na zdrowiu kierowcy i pasażerów, niezależnie od winy."),
          K("Ubezpieczenia obowiązkowe i UFG",
            "W Polsce obowiązkowe są m.in.: OC posiadaczy pojazdów mechanicznych, OC rolników i ubezpieczenie budynków rolniczych od ognia i innych zdarzeń, a także OC wielu zawodów (np. lekarzy, adwokatów). Ubezpieczeniowy Fundusz Gwarancyjny wypłaca odszkodowania ofiarom nieubezpieczonych lub nieznanych sprawców i pobiera opłaty karne za brak OC – w 2026 r. do 9 610 zł za samochód osobowy (dwukrotność płacy minimalnej)."),
          K("BLS",
            "Bezpośrednia likwidacja szkód: poszkodowany zgłasza szkodę z OC sprawcy do swojego ubezpieczyciela, który wypłaca odszkodowanie i rozlicza się z ubezpieczycielem sprawcy. W Polsce BLS jest dobrowolna – oferują ją wybrane zakłady."),
          PF("AC pokryje szkodę w moim aucie, nawet jeśli to ja spowodowałem kolizję.", True,
             why="AC chroni własny pojazd niezależnie od winy (z wyjątkami w OWU, np. jazda po alkoholu)."),
      ],
      mech=[
          KT("Które ubezpieczenie zadziała?",
             {"OC sprawcy": ["Ktoś wjechał w mój zaparkowany samochód", "Kierowca potrącił pieszego"],
              "Moje AC": ["Ukradziono mi samochód", "Grad zniszczył karoserię", "Sam uderzyłem w słupek"],
              "NNW": ["Pasażer złamał rękę w wypadku i dostaje świadczenie"]},
             why="OC – szkody wobec innych; AC – własny pojazd; NNW – zdrowie."),
          LN("Ułóż, co się dzieje, gdy sprawca wypadku nie miał OC.",
             ["Nieubezpieczony kierowca powoduje wypadek", "Poszkodowany zgłasza szkodę do UFG", "UFG wypłaca odszkodowanie", "UFG dochodzi zwrotu (regresu) od sprawcy", "Sprawca płaci też opłatę karną za brak OC"],
             why="UFG chroni poszkodowanych, a koszt przerzuca na sprawcę."),
          W("Właściciel ubezpieczył auto warte 40 000 zł na 60 000 zł. Auto zostało skradzione. Ile dostanie?",
            "40 000 zł", "60 000 zł", "50 000 zł",
            why="Nadubezpieczenie nie zwiększa odszkodowania ponad wartość szkody."),
          W("Co zwykle robi właściciel przy niedoubezpieczeniu, by uniknąć zaniżonego odszkodowania?",
            "Aktualizuje sumę ubezpieczenia do wartości mienia", "Zgłasza szkodę w dwóch firmach", "Wykupuje NNW",
            why="Suma równa wartości eliminuje działanie zasady proporcji."),
          M("Rolnik ma gospodarstwo z budynkami i samochód. Które polisy musi mieć z mocy ustawy?",
            ["OC posiadaczy pojazdów mechanicznych", "OC rolników", "Ubezpieczenie budynków rolniczych", "Autocasco"], [0, 1, 2],
            why="AC jest dobrowolne."),
          PF("Przy BLS poszkodowany może zgłosić szkodę u swojego ubezpieczyciela, choć płaci OC sprawcy.", True,
             why="Ubezpieczyciele rozliczają się potem między sobą."),
      ],
      calc=[
          LB("Mieszkanie warte 400 000 zł, suma ubezpieczenia 300 000 zł, szkoda 80 000 zł. Ile wynosi odszkodowanie przy zasadzie proporcji (zł)?",
             60000, "80000*300000/400000", ["80 000 · 0,75 = 60 000 zł"], unit="zł"),
          LB("Jaki procent wartości mienia ubezpieczono w poprzednim zadaniu (%)?",
             75, "300000/400000*100", ["300 / 400 = 75%"], unit="%"),
          LB("Płaca minimalna 2026: 4806 zł. Ile wynosi dwukrotność (zł, przed zaokrągleniem do 10 zł)?",
             9612, "2*4806", ["2 · 4806 = 9612 zł → po zaokrągleniu 9610 zł"], unit="zł"),
          LB("Roczne OC kosztuje 900 zł. Kierowca zwlekał z zakupem 20 dni i zapłacił karę 9610 zł. Ile razy kara przewyższa składkę?",
             10.68, "9610/900", ["9610 / 900 ≈ 10,68"], unit="razy", tol=0.01),
          LB("AC z udziałem własnym 5%: szkoda 18 000 zł, auto ubezpieczone na pełną wartość. Ile wypłaci ubezpieczyciel (zł)?",
             17100, "18000*0.95", ["18 000 · 95% = 17 100 zł"], unit="zł"),
          LB("Suma NNW 50 000 zł, uszczerbek na zdrowiu 8%. Ile wynosi świadczenie (zł)?",
             4000, "50000*0.08", ["50 000 · 8% = 4000 zł"], unit="zł"),
      ],
      case=[
          PR("Pani Kasia kupiła dom 10 lat temu za 400 000 zł i od tego czasu nie zmieniła sumy ubezpieczenia (400 000 zł). Dziś dom jest wart 800 000 zł. Pożar spowodował szkodę 200 000 zł.",
             W("Ile wypłaci ubezpieczyciel przy zasadzie proporcji?",
               "100 000 zł", "200 000 zł", "400 000 zł",
               why="200 000 · 400/800 = 100 000 zł."),
             W("Co powinna była zrobić?",
               "Regularnie aktualizować sumę ubezpieczenia", "Kupić drugi dom", "Zrezygnować z ubezpieczenia",
               why="Wzrost cen nieruchomości powoduje niedoubezpieczenie."),
             PF("Gdyby polisa przewidywała ubezpieczenie na pierwsze ryzyko (bez zasady proporcji), otrzymałaby pełne 200 000 zł.", True,
                why="Na pierwsze ryzyko odszkodowanie wypłaca się do sumy ubezpieczenia bez proporcji."),
          ),
          PR("Pan Robert, jadąc swoim autem, wjechał w tył samochodu pani Ewy. Oboje mają OC, a pan Robert ma też AC. Pani Ewa ma polisę z BLS.",
             W("Z czyjego OC zostanie naprawione auto pani Ewy?",
               "Z OC pana Roberta", "Z OC pani Ewy", "Z UFG",
               why="Szkodę wyrządzoną innym pokrywa OC sprawcy."),
             W("Z czego pan Robert może naprawić swoje auto?",
               "Ze swojego AC", "Ze swojego OC", "Z OC pani Ewy",
               why="Własne OC nie pokrywa szkód własnych; służy do tego AC."),
             PF("Dzięki BLS pani Ewa może zgłosić szkodę do własnego ubezpieczyciela.", True,
                why="BLS skraca drogę likwidacji szkody."),
          ),
      ]),

    L(4, "Reasekuracja, rezerwy i ubezpieczenia inwestycyjne",
      "Rozumieć, jak ubezpieczyciel przenosi ryzyko na reasekuratora, skąd bierze środki na wypłaty (rezerwy techniczno-ubezpieczeniowe, inwestycje) i jak działa polisa z ubezpieczeniowym funduszem kapitałowym.",
      ["Reasekuracja", "Ubezpieczeniowy fundusz kapitałowy (UFK)", "Aktuariusz"],
      [KNF, PIU],
      explain=[
          K("Reasekuracja – ubezpieczenie ubezpieczyciela",
            "Zakład ubezpieczeń (cedent) przekazuje część ryzyka i część składki reasekuratorowi (np. Munich Re, Swiss Re). Reasekuracja proporcjonalna (np. kwotowa): reasekurator bierze stały procent każdej składki i każdej szkody. Nieproporcjonalna (nadwyżki szkody): płaci tylko część szkody ponad ustalony próg (priorytet)."),
          W("Ubezpieczyciel ma umowę kwotową 40%. Szkoda 1 mln zł. Ile zapłaci reasekurator?",
            "400 000 zł", "600 000 zł", "1 000 000 zł",
            why="Przy reasekuracji kwotowej reasekurator pokrywa ustalony procent – 40%."),
          K("Po co reasekuracja",
            "Chroni przed katastrofami i kumulacją szkód (powódź, huragan), stabilizuje wynik, pozwala przyjmować duże ryzyka (elektrownie, samoloty) przy ograniczonym kapitale. Reasekuratorzy działają globalnie, więc rozpraszają ryzyka geograficznie."),
          K("Rezerwy i lokaty",
            "Składki wpływają z góry, a szkody wypłaca się później. Na przyszłe wypłaty zakład tworzy rezerwy techniczno-ubezpieczeniowe (wylicza je aktuariusz) i inwestuje środki, głównie w obligacje. Wymogi kapitałowe Wypłacalność II (Solvency II) w UE wymagają kapitału adekwatnego do ryzyka; nadzór w Polsce sprawuje KNF."),
          K("UFK – polisa z funduszem",
            "W ubezpieczeniu na życie z UFK część składki inwestuje się w fundusz kapitałowy wybrany przez klienta. Ryzyko inwestycyjne ponosi ubezpieczony, a wartość polisy zależy od wyników funduszu. Wysokie opłaty i kary za wcześniejsze wypowiedzenie („polisolokaty”) były przedmiotem skarg do Rzecznika Finansowego i decyzji UOKiK."),
          PF("W polisie z UFK ubezpieczyciel gwarantuje wartość inwestycji.", False,
             why="Ryzyko inwestycyjne ponosi klient."),
      ],
      mech=[
          LN("Ułóż, jak reasekuracja chroni ubezpieczyciela przed powodzią.",
             ["Ubezpieczyciel ma wiele polis domów w dorzeczu jednej rzeki", "Zawiera umowę nadwyżki szkody z reasekuratorem", "Powódź powoduje ogromne łączne szkody", "Ubezpieczyciel płaci szkody do priorytetu", "Reasekurator pokrywa nadwyżkę i chroni kapitał ubezpieczyciela"],
             why="Nieproporcjonalna reasekuracja ogranicza stratę z katastrofy."),
          KT("Reasekuracja proporcjonalna czy nieproporcjonalna?",
             {"Proporcjonalna": ["Reasekurator bierze 30% każdej składki i 30% każdej szkody", "Umowa kwotowa na portfel OC"],
              "Nieproporcjonalna": ["Reasekurator płaci część szkody ponad 10 mln zł", "Ochrona katastroficzna od huraganów"]},
             why="Proporcjonalna dzieli wszystko w stałym procencie, nieproporcjonalna – tylko nadwyżki."),
          W("Ubezpieczyciel chce ubezpieczyć elektrownię wartą 5 mld zł, mając kapitał 1 mld zł. Co zrobi?",
            "Przekaże większość ryzyka reasekuratorom", "Odmówi, bo to niemożliwe", "Podniesie kapitał do 5 mld zł",
            why="Reasekuracja umożliwia przyjmowanie ryzyk większych niż własny kapitał."),
          W("Kto ponosi ryzyko spadku wartości funduszy w polisie z UFK?",
            "Ubezpieczony", "Ubezpieczyciel", "Rzecznik Finansowy",
            why="Wartość polisy zależy od wyników funduszy wybranych przez klienta."),
          M("Do czego służą rezerwy techniczno-ubezpieczeniowe?",
            ["Pokrycie przyszłych wypłat z zawartych umów", "Zapewnienie wypłacalności zakładu", "Wypłata dywidendy akcjonariuszom", "Pokrycie szkód zaszłych, ale jeszcze niezgłoszonych"], [0, 1, 3],
            why="Rezerwy są zobowiązaniem wobec ubezpieczonych, nie zyskiem."),
          PF("Wzrost rentowności obligacji może zwiększyć dochody inwestycyjne ubezpieczyciela.", True,
             why="Nowe środki z rezerw inwestowane są w obligacje po wyższej rentowności."),
      ],
      calc=[
          LB("Umowa kwotowa 30%. Składki 200 mln zł, szkody 140 mln zł. Ile szkód zostaje u cedenta (mln zł)?",
             98, "140*0.7", ["140 · 70% = 98 mln zł"], unit="mln zł"),
          LB("Umowa nadwyżki szkody: priorytet 20 mln zł, limit 100 mln zł. Szkoda 75 mln zł. Ile zapłaci reasekurator (mln zł)?",
             55, "75-20", ["75 − 20 = 55 mln zł (mieści się w limicie)"], unit="mln zł"),
          LB("Ta sama umowa (priorytet 20, limit 100). Szkoda 150 mln zł. Ile zostanie u cedenta (mln zł)?",
             50, "150-100", ["Reasekurator płaci najwyżej 100", "Cedent: 150 − 100 = 50 mln zł"], unit="mln zł"),
          LB("Polisa z UFK: wpłata 10 000 zł, opłata wstępna 2%, fundusz wzrósł o 8%. Ile wynosi wartość polisy (zł)?",
             10584, "10000*0.98*1.08", ["9800 · 1,08 = 10 584 zł"], unit="zł"),
          LB("Wskaźnik mieszany = (szkody + koszty) / składki. Szkody 650, koszty 300, składki 1000 (mln zł). Ile wynosi wskaźnik (%)?",
             95, "(650+300)/1000*100", ["950 / 1000 = 95%"], unit="%"),
          LB("Rezerwy 4 mld zł zainwestowane w obligacje o rentowności 5,5%. Ile wynosi roczny dochód z lokat (mln zł)?",
             220, "4000*0.055", ["4000 · 5,5% = 220 mln zł"], unit="mln zł"),
      ],
      case=[
          PR("Ubezpieczyciel majątkowy ma kapitał 300 mln zł i dużo polis w regionie zagrożonym powodzią. Szacuje, że duża powódź może spowodować szkody 800 mln zł. Kupuje ochronę nadwyżki szkody: priorytet 150 mln zł, limit 600 mln zł.",
             W("Ile zapłaci reasekurator przy powodzi ze szkodami 800 mln zł?",
               "600 mln zł", "650 mln zł", "800 mln zł",
               why="Nadwyżka ponad priorytet to 650, ale limit wynosi 600 mln zł."),
             W("Ile szkód zostanie u ubezpieczyciela?",
               "200 mln zł", "150 mln zł", "50 mln zł",
               why="800 − 600 = 200 mln zł (priorytet 150 + 50 ponad limit)."),
             PF("Bez reasekuracji ta powódź oznaczałaby utratę całego kapitału.", True,
                why="Szkody 800 mln zł > kapitał 300 mln zł."),
          ),
          PR("Klient kupił w 2010 r. polisę z UFK, wpłacając 500 zł miesięcznie. Po 3 latach zrezygnował i dowiedział się, że opłata likwidacyjna pochłonęła większość wartości rachunku.",
             W("Jaki problem ilustruje przypadek?",
               "Wysokie opłaty i kary za wcześniejsze wycofanie z polisolokat", "Pokusę nadużycia klienta", "Działanie reasekuracji",
               why="Tzw. polisolokaty miały wysokie opłaty likwidacyjne."),
             W("Do kogo klient może się zwrócić o pomoc?",
               "Do Rzecznika Finansowego", "Do UFG", "Do ZUS",
               why="Rzecznik Finansowy pomaga klientom podmiotów rynku finansowego."),
             PF("Przed zakupem polisy z UFK warto sprawdzić tabelę opłat i ryzyko inwestycyjne.", True,
                why="Opłaty i wyniki funduszy decydują o wartości polisy."),
          ),
      ]),

    L(5, "Ubezpieczenia społeczne – składki ZUS",
      "Rozumieć różnicę między ubezpieczeniem społecznym a komercyjnym, rodzaje składek ZUS i ich podział między pracownika i pracodawcę oraz liczyć składki pracownika i przedsiębiorcy (stan na 2026 r.).",
      ["Ubezpieczenia społeczne (ZUS)", "Ubezpieczenie", "Ubezpieczenia obowiązkowe w Polsce"],
      [ZUS, S162],
      explain=[
          K("Społeczne a komercyjne",
            "Ubezpieczenia społeczne są obowiązkowe z mocy ustawy, składka zależy od dochodu, a nie od indywidualnego ryzyka, a państwo gwarantuje wypłaty. Łączą ubezpieczenie z solidarnością (np. minimalna emerytura). Komercyjne są dobrowolne (poza wyjątkami), a składka zależy od ryzyka."),
          K("Cztery ubezpieczenia ZUS",
            "Emerytalne 19,52% podstawy (po połowie: 9,76% pracownik i 9,76% pracodawca). Rentowe 8% (1,5% pracownik, 6,5% pracodawca). Chorobowe 2,45% – płaci pracownik. Wypadkowe – pracodawca, stopa zależna od branży i liczby pracowników (podstawowa 1,67%). Pracodawca płaci też Fundusz Pracy 2,45% i FGŚP 0,10% (stan na 2026 r., dane ZUS)."),
          W("Jaką łączną część wynagrodzenia brutto stanowią składki społeczne pracownika?",
            "13,71%", "19,52%", "22,14%",
            why="9,76% + 1,5% + 2,45% = 13,71%."),
          K("System repartycyjny i zdefiniowana składka",
            "Fundusz Ubezpieczeń Społecznych (FUS) działa repartycyjnie: dzisiejsze składki finansują dzisiejsze emerytury. Od 1999 r. obowiązuje zasada zdefiniowanej składki: składki są zapisywane na koncie, waloryzowane, a emerytura = zgromadzony kapitał / średnie dalsze trwanie życia w miesiącach (tablice GUS).",
            w="emerytura = kapitał / dalsze trwanie życia (mies.)"),
          K("Przedsiębiorca w 2026 r.",
            "Przedsiębiorca płaci składki od zadeklarowanej podstawy, nie niższej niż 60% prognozowanego przeciętnego wynagrodzenia: 5 652 zł w 2026 r. Składki społeczne z dobrowolną chorobową i FP wynoszą wtedy 1 926,76 zł miesięcznie. Nowe firmy mogą korzystać z ulgi na start i preferencyjnych składek (podstawa 30% płacy minimalnej – 1 441,80 zł)."),
          PF("Składka emerytalna jest jedynym ubezpieczeniem społecznym, które pracownik i pracodawca finansują po równo.", True,
             why="Rentowa: 1,5% / 6,5%; chorobowa – pracownik; wypadkowa – pracodawca."),
      ],
      mech=[
          KT("Kto finansuje składkę?",
             {"Tylko pracownik": ["Ubezpieczenie chorobowe"],
              "Tylko pracodawca": ["Ubezpieczenie wypadkowe", "Fundusz Pracy", "FGŚP"],
              "Obie strony": ["Ubezpieczenie emerytalne", "Ubezpieczenie rentowe"]},
             why="Podział wynika z ustawy o systemie ubezpieczeń społecznych."),
          LN("Ułóż, jak demografia wpływa na FUS w systemie repartycyjnym.",
             ["Rodzi się mniej dzieci, a ludzie żyją dłużej", "Liczba emerytów rośnie szybciej niż liczba pracujących", "Spada liczba płacących składki na jednego emeryta", "Wpływy ze składek nie pokrywają wypłat", "Deficyt FUS pokrywa dotacja z budżetu państwa"],
             why="W systemie repartycyjnym struktura wieku decyduje o równowadze funduszu."),
          W("Wydłuża się średnie dalsze trwanie życia. Co dzieje się z emeryturą przy tym samym kapitale?",
            "Maleje", "Rośnie", "Nie zmienia się",
            why="Kapitał dzieli się przez większą liczbę miesięcy."),
          W("Dlaczego składka wypadkowa jest różna w różnych firmach?",
            "Zależy od ryzyka wypadków w branży i firmie", "Zależy od wieku pracownika", "Ustala ją pracownik",
            why="To element ubezpieczeniowy: wyższe ryzyko – wyższa stopa."),
          M("Czym ubezpieczenie społeczne różni się od komercyjnego?",
            ["Jest obowiązkowe z mocy ustawy", "Składka zależy od dochodu, a nie od ryzyka", "Zawiera element solidarności, np. minimalną emeryturę", "Składka zależy od stanu zdrowia ubezpieczonego"], [0, 1, 2],
            why="ZUS nie bada zdrowia przed objęciem ubezpieczeniem."),
          PF("Odroczenie przejścia na emeryturę o rok zwykle podnosi jej wysokość.", True,
             why="Rośnie kapitał (składki, waloryzacja), a maleje dalsze trwanie życia."),
      ],
      calc=[
          LB("Wynagrodzenie brutto 8000 zł. Ile wynosi składka emerytalna pracownika (9,76%, zł)?",
             780.8, "8000*0.0976", ["8000 · 9,76% = 780,80 zł"], unit="zł", tol=0.01),
          LB("Wynagrodzenie brutto 8000 zł. Ile wynoszą łącznie składki społeczne pracownika (13,71%, zł)?",
             1096.8, "8000*0.1371", ["8000 · 13,71% = 1096,80 zł"], unit="zł", tol=0.01),
          LB("Składki pracodawcy od 8000 zł: emerytalna 9,76%, rentowa 6,5%, wypadkowa 1,67%, FP 2,45%, FGŚP 0,1%. Ile wynoszą łącznie (zł)?",
             1638.4, "8000*(0.0976+0.065+0.0167+0.0245+0.001)", ["Suma stóp 20,48%", "8000 · 20,48% = 1638,40 zł"], unit="zł", tol=0.01),
          LB("Podstawa przedsiębiorcy 5652 zł, składka emerytalna 19,52%. Ile wynosi (zł)?",
             1103.27, "5652*0.1952", ["5652 · 19,52% ≈ 1103,27 zł"], unit="zł", tol=0.01),
          LB("Kapitał emerytalny 600 000 zł, średnie dalsze trwanie życia 240 miesięcy. Ile wynosi emerytura (zł)?",
             2500, "600000/240", ["600 000 / 240 = 2500 zł"], unit="zł"),
          LB("Ten sam kapitał, ale przejście na emeryturę 2 lata później: kapitał 680 000 zł, trwanie życia 220 miesięcy. Ile wynosi emerytura (zł)?",
             3090.91, "680000/220", ["680 000 / 220 ≈ 3090,91 zł"], unit="zł", tol=0.01),
      ],
      case=[
          PR("Pani Marta zakłada działalność. W pierwszych 6 miesiącach korzysta z ulgi na start (bez składek społecznych), potem przez 24 miesiące płaci preferencyjne składki od podstawy 1 441,80 zł, a następnie pełne od 5 652 zł (stawki z 2026 r.).",
             W("Ile wynosi jej składka emerytalna w okresie preferencyjnym?",
               "Ok. 281 zł", "Ok. 1103 zł", "0 zł",
               why="1441,80 · 19,52% ≈ 281,44 zł."),
             W("Jaki jest skutek niskich składek dla przyszłej emerytury?",
               "Niższy kapitał emerytalny i niższa emerytura", "Brak wpływu", "Wyższa emerytura",
               why="W systemie zdefiniowanej składki emerytura zależy od wpłaconych składek."),
             PF("W okresie ulgi na start przedsiębiorca nadal płaci składkę zdrowotną.", True,
                why="Ulga na start zwalnia tylko ze składek na ubezpieczenia społeczne."),
          ),
          PR("Raport o FUS (dane umowne): wpływy ze składek 330 mld zł, wydatki na świadczenia 420 mld zł. Prognozy pokazują, że liczba osób w wieku 65+ będzie rosła przez kolejne dekady.",
             W("Ile wynosi deficyt FUS?",
               "90 mld zł", "750 mld zł", "330 mld zł",
               why="420 − 330 = 90 mld zł."),
             W("Jaki procent wydatków pokrywają składki?",
               "Ok. 79%", "Ok. 127%", "Ok. 21%",
               why="330 / 420 ≈ 78,6%."),
             W("Które rozwiązanie bezpośrednio poprawia saldo FUS?",
               "Wyższa aktywność zawodowa i dłuższa praca", "Obniżenie składki emerytalnej", "Wcześniejszy wiek emerytalny",
               why="Więcej płacących składki, mniej pobierających świadczenia."),
          ),
      ]),
]
