# -*- coding: utf-8 -*-
# Zrozumienie – Podstawy finansów / Banki i system bankowy
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-08"
S273 = S("OpenStax, Principles of Economics 3e, 27.3 The Role of Banks", OS3 + "27-3-the-role-of-banks", D)
S281 = S("OpenStax, Principles of Economics 3e, 28.1 The Federal Reserve Banking System and Central Banks", OS3 + "28-1-the-federal-reserve-banking-system-and-central-banks", D)
S282 = S("OpenStax, Principles of Economics 3e, 28.2 Bank Regulation", OS3 + "28-2-bank-regulation", D)
NBPE = S("NBP – edukacja ekonomiczna", "https://nbp.pl/edukacja/", D)
BFG = S("Bankowy Fundusz Gwarancyjny", "https://www.bfg.pl/", D)
KNF = S("Komisja Nadzoru Finansowego", "https://www.knf.gov.pl/", D)
GPWB = S("GPW Benchmark – administrator wskaźników WIBOR i POLSTR", "https://www.gpwbenchmark.pl/", D)
KIR = S("Krajowa Izba Rozliczeniowa", "https://www.kir.pl/", D)
BANKPL = S("Bank.pl – WIBOR zostaje do 2036 roku. Banki szykują się do przejścia na POLSTR", "https://bank.pl/wibor-zostaje-do-2036-roku-banki-szykuja-sie-do-przejscia-na-polstr/", D)

XWEK = S("Ustawa z 28.04.1936 – Prawo wekslowe (ISAP/ELI)", "https://isap.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU19360370282", D)
XKON = S("Rzeczpospolita (pro.rp.pl) – Co to jest konosament i rodzaje konosamentu", "https://pro.rp.pl/prawo-w-firmie/art4741661-co-to-jest-konosament-i-rodzaje-konosamentu", D)
XKM = S("M. Dragun-Gertner, Konosament – Prawo Morskie (PAN)", "https://www.czasopisma.pan.pl//Content/120543/PDF/6_Prawo_morskie_Dragun_Gertner_Konosament.pdf", D)

LESSONS = [
    L(1, "Bank komercyjny: bilans i operacje",
      "Czytać uproszczony bilans banku, odróżniać operacje bierne (pozyskiwanie środków) od czynnych (lokowanie), rozumieć, z czego bank zarabia, i poznać rodzaje instytucji: bank uniwersalny, spółdzielczy, hipoteczny i SKOK.",
      ["Bank komercyjny (uniwersalny)", "Operacje bankowe czynne i bierne", "Aktywa i pasywa banku", "Bank spółdzielczy", "Bank hipoteczny i list zastawny", "SKOK", "Bancassurance"],
      [S273, KNF],
      explain=[
          K("Pośrednik finansowy",
            "Bank zbiera oszczędności od tych, którzy mają nadwyżki (depozyty), i pożycza je tym, którzy potrzebują środków (kredyty). Przekształca krótkie depozyty w długie kredyty (transformacja terminów), łączy wiele małych wpłat w duże kredyty i ocenia ryzyko kredytobiorców lepiej niż pojedynczy oszczędzający."),
          K("Bilans banku",
            "Aktywa (na co bank przeznaczył środki): gotówka i rezerwy w NBP, kredyty, obligacje, nieruchomości. Pasywa (skąd ma środki): depozyty klientów, pożyczki z innych banków, emisje dłużne, kapitał własny. Aktywa = pasywa. Kapitał własny to „bufor”: pokrywa straty, zanim ucierpią deponenci.",
            w="aktywa = zobowiązania + kapitał własny"),
          W("Bank przyjmuje lokatę 10 000 zł. Jaka to operacja?",
            "Bierna – pozyskanie środków", "Czynna – lokowanie środków", "Pozabilansowa",
            why="Depozyt jest zobowiązaniem banku (pasywa)."),
          K("Z czego bank zarabia",
            "Wynik odsetkowy – różnica między odsetkami od kredytów i obligacji a odsetkami od depozytów (marża odsetkowa) – to główne źródło zysku. Do tego wynik prowizyjny (opłaty za konta, karty, przelewy) i sprzedaż produktów partnerów, np. ubezpieczeń (bancassurance). Koszty to m.in. odpisy na złe kredyty."),
          K("Rodzaje instytucji",
            "Bank uniwersalny prowadzi pełny zakres usług. Bank spółdzielczy działa lokalnie, jego właścicielami są członkowie-spółdzielcy, zwykle zrzeszony z bankiem zrzeszającym. Bank hipoteczny udziela kredytów na nieruchomości i finansuje je listami zastawnymi – obligacjami zabezpieczonymi hipotekami. SKOK to spółdzielcza kasa dla członków, nadzorowana przez KNF, z gwarancjami BFG."),
          PF("Kredyt udzielony przez bank jest dla niego aktywem, a depozyt klienta – pasywem.", True,
             why="Kredyt to należność banku, depozyt – jego zobowiązanie."),
      ],
      mech=[
          KT("Aktywa czy pasywa banku?",
             {"Aktywa": ["Kredyty hipoteczne udzielone klientom", "Obligacje skarbowe w portfelu banku", "Rezerwy na rachunku w NBP"],
              "Pasywa": ["Depozyty klientów", "Kapitał własny", "Wyemitowane listy zastawne"]},
             why="Aktywa – lokowanie środków, pasywa – źródła finansowania."),
          LN("Ułóż drogę oszczędności przez bank do inwestycji.",
             ["Gospodarstwo domowe wpłaca oszczędności na lokatę", "Bank płaci odsetki od depozytu", "Bank ocenia zdolność kredytową firmy", "Bank udziela firmie kredytu na maszynę", "Firma spłaca kredyt z odsetkami, z których bank pokrywa koszty depozytów i zarabia"],
             why="Bank jest pośrednikiem między oszczędzającymi a inwestującymi."),
          W("Kredyty są oprocentowane na 8%, depozyty na 4%. Bank obniża oprocentowanie depozytów do 3%. Co się stanie z marżą odsetkową?",
            "Wzrośnie", "Spadnie", "Nie zmieni się",
            why="Koszt pozyskania środków maleje przy niezmienionym dochodzie z kredytów."),
          W("Czym list zastawny różni się od zwykłej obligacji banku?",
            "Jest zabezpieczony wierzytelnościami hipotecznymi", "Nie przynosi odsetek", "Emituje go NBP",
            why="Za list zastawny odpowiada pula kredytów hipotecznych."),
          M("Które działania to operacje czynne banku?",
            ["Udzielenie kredytu", "Zakup obligacji skarbowych", "Przyjęcie lokaty", "Udzielenie gwarancji bankowej"], [0, 1, 3],
            why="Przyjęcie lokaty to operacja bierna."),
          PF("Kapitał własny banku chroni deponentów, bo to on jako pierwszy pokrywa straty z niespłaconych kredytów.", True,
             why="Straty zmniejszają najpierw kapitał, a dopiero potem mogłyby dotknąć zobowiązań."),
      ],
      calc=[
          LB("Kredyty 800 mln zł na 7%, depozyty 700 mln zł na 3%. Ile wynosi wynik odsetkowy (mln zł)?",
             35, "800*0.07-700*0.03", ["56 − 21 = 35 mln zł"], unit="mln zł"),
          LB("Bank: aktywa 1000 mln zł, depozyty 850 mln zł, inne zobowiązania 60 mln zł. Ile wynosi kapitał własny (mln zł)?",
             90, "1000-850-60", ["1000 − 910 = 90 mln zł"], unit="mln zł"),
          LB("Kapitał 90 mln zł, aktywa 1000 mln zł. Ile wynosi relacja kapitału do aktywów (%)?",
             9, "90/1000*100", ["90 / 1000 = 9%"], unit="%"),
          LB("Ten bank traci 5% kredytów (kredyty 800 mln zł). Ile zostanie kapitału (mln zł)?",
             50, "90-800*0.05", ["Strata 40", "90 − 40 = 50 mln zł"], unit="mln zł"),
          LB("ROE = zysk netto / kapitał. Zysk 13,5 mln zł, kapitał 90 mln zł. Ile wynosi ROE (%)?",
             15, "13.5/90*100", ["13,5 / 90 = 15%"], unit="%"),
          LB("Bank sprzedał 2000 polis w ramach bancassurance, prowizja 150 zł od polisy. Ile zarobił (zł)?",
             300000, "2000*150", ["2000 · 150 = 300 000 zł"], unit="zł"),
      ],
      case=[
          PR("Bank spółdzielczy w małym mieście ma depozyty mieszkańców 400 mln zł, ale lokalny popyt na kredyty to tylko 180 mln zł. Nadwyżkę lokuje w banku zrzeszającym i w obligacjach skarbowych.",
             W("Dlaczego bank spółdzielczy nie udziela więcej kredytów?",
               "Brakuje lokalnych wiarygodnych kredytobiorców", "Prawo zakazuje mu kredytów", "Nie ma depozytów",
               why="Działa lokalnie, a popyt na kredyty jest ograniczony."),
             W("Co jest głównym ryzykiem banku przy portfelu obligacji o stałym kuponie?",
               "Spadek ich cen przy wzroście stóp procentowych", "Bankructwo Skarbu Państwa w ciągu miesiąca", "Brak odsetek",
               why="Ryzyko stopy procentowej dotyczy też obligacji skarbowych."),
             PF("Zrzeszenie umożliwia bankom spółdzielczym przekazywanie nadwyżek płynności i wspólne systemy ochrony.", True,
                why="Banki zrzeszające i systemy ochrony instytucjonalnej wspierają banki spółdzielcze."),
          ),
          PR("Bank uniwersalny ma marżę odsetkową netto 3,5% od aktywów 200 mld zł. Gdy RPP obniża stopy, oprocentowanie kredytów spada szybciej niż depozytów (bo depozyty bieżące i tak są prawie nieoprocentowane), a marża spada do 3,0%.",
             W("Ile wynosi wynik odsetkowy przy marży 3,5%?",
               "7 mld zł", "3,5 mld zł", "70 mld zł",
               why="200 · 3,5% = 7 mld zł."),
             W("O ile zmniejszy się wynik po spadku marży do 3,0%?",
               "O 1 mld zł", "O 0,5 mld zł", "O 6 mld zł",
               why="200 · 0,5 pkt proc. = 1 mld zł."),
             PF("Banki zarabiają zwykle więcej przy wyższych stopach procentowych, bo marża odsetkowa rośnie.", True,
                why="Kredyty o zmiennej stopie szybko drożeją, a część depozytów nie jest oprocentowana."),
          ),
      ]),

    L(2, "Bank centralny, rynek międzybankowy i system płatniczy",
      "Rozumieć funkcje banku centralnego (bank emisyjny, bank banków, pożyczkodawca ostatniej instancji), działanie rynku międzybankowego i stawek POLONIA, WIBOR i POLSTR oraz drogę przelewu przez SORBNET, Elixir i BLIK.",
      ["Bank centralny", "Pożyczkodawca ostatniej instancji", "Bilans banku centralnego", "Rynek międzybankowy", "POLONIA", "WIBOR i WIBID", "Rozliczenia międzybankowe: SORBNET, Elixir, KIR", "BLIK", "System płatniczy", "Rachunek nostro i loro"],
      [S281, GPWB, BANKPL, KIR],
      explain=[
          K("Trzy funkcje banku centralnego",
            "Bank emisyjny – wyłączne prawo emisji pieniądza. Bank banków – prowadzi rachunki banków komercyjnych, przyjmuje ich rezerwy, udziela kredytu refinansowego, organizuje rozliczenia. Bank państwa – obsługuje budżet i zarządza rezerwami dewizowymi. Do tego prowadzi politykę pieniężną (w Polsce RPP ustala stopy) i dba o stabilność systemu finansowego."),
          K("Pożyczkodawca ostatniej instancji",
            "Gdy wypłacalny bank traci płynność (np. klienci nagle wypłacają depozyty), bank centralny może pożyczyć mu pieniądze pod zastaw dobrych aktywów, zwykle po karnej stopie (zasada Bagehota). Zapobiega to panice i upadkom zdrowych banków. Nie powinien jednak ratować banków niewypłacalnych – to zadanie restrukturyzacji."),
          W("Według zasady Bagehota bank centralny w kryzysie powinien pożyczać:",
            "Swobodnie, pod dobre zabezpieczenie i po karnej stopie", "Tylko bankom niewypłacalnym, bez zabezpieczeń", "Wyłącznie rządowi",
            why="Tak chroni się płynność zdrowych banków bez nagradzania hazardu."),
          K("Rynek międzybankowy i stawki referencyjne",
            "Banki z nadwyżką płynności pożyczają ją bankom z niedoborem, zwykle na krótko. POLONIA to średnia stopa niezabezpieczonych lokat overnight – NBP dąży do utrzymania jej blisko stopy referencyjnej. WIBOR (oferowana) i WIBID (bid) to stawki, od których liczy się oprocentowanie wielu kredytów. GPW Benchmark ogłosił 18.05.2026, że WIBOR będzie publikowany do 31.12.2036, a nowe umowy od 2027 r. mają opierać się na wskaźniku POLSTR – liczonym z rzeczywistych transakcji depozytowych."),
          K("Jak płyną pieniądze",
            "Przelewy wysokokwotowe i pilne rozlicza w czasie rzeczywistym SORBNET (system NBP). Zwykłe przelewy między bankami idą w sesjach przez Elixir (Krajowa Izba Rozliczeniowa), a natychmiastowe – przez Express Elixir. BLIK to polski system płatności mobilnych. Rachunek nostro to „nasz” rachunek w banku zagranicznym, loro – rachunek banku zagranicznego u nas."),
          PF("POLONIA jest stopą ustalaną przez RPP.", False,
             why="RPP ustala stopy NBP; POLONIA wynika z transakcji banków na rynku."),
      ],
      mech=[
          LN("Ułóż drogę zwykłego przelewu z banku A do banku B.",
             ["Klient zleca przelew w banku A", "Bank A obciąża jego rachunek", "Zlecenie trafia do sesji rozliczeniowej Elixir w KIR", "Saldo między bankami rozliczane jest przez rachunki w NBP", "Bank B uznaje rachunek odbiorcy"],
             why="KIR liczy salda, a NBP rozrachowuje je na rachunkach banków."),
          KT("Która funkcja banku centralnego?",
             {"Bank emisyjny": ["Emisja nowego banknotu 1000 zł", "Wprowadzenie monety okolicznościowej"],
              "Bank banków": ["Kredyt lombardowy dla banku komercyjnego", "Prowadzenie rachunków rezerw banków"],
              "Bank państwa": ["Obsługa rachunków budżetu państwa", "Zarządzanie rezerwami dewizowymi"]},
             why="Każda funkcja dotyczy innego klienta banku centralnego."),
          W("W systemie bankowym pojawia się nadwyżka płynności, a banki chętnie pożyczają sobie pieniądze. Co dzieje się z POLONIĄ?",
            "Spada w kierunku stopy depozytowej NBP", "Rośnie powyżej stopy lombardowej", "Nie zmienia się",
            why="Stopa depozytowa i lombardowa tworzą korytarz dla stóp rynkowych."),
          W("Rosną stawki WIBOR 3M. Co dzieje się z ratą kredytu hipotecznego o zmiennej stopie WIBOR 3M + marża?",
            "Rośnie przy najbliższej aktualizacji oprocentowania", "Spada", "Nie zmienia się do końca umowy",
            why="Oprocentowanie = WIBOR + marża, aktualizowane co 3 miesiące."),
          M("Które zdania o reformie wskaźników są prawdziwe (stan na 10.2026)?",
            ["Nowe umowy od 2027 r. mają opierać się na POLSTR", "WIBOR będzie publikowany do końca 2036 r. dla starych umów", "POLSTR liczony jest z rzeczywistych transakcji", "Kredyty na WIBOR wygasają automatycznie 1.01.2027"], [0, 1, 2],
            why="Istniejące umowy nie przechodzą automatycznie – mogą działać do końca 2036 r."),
          PF("Polski bank prowadzący rachunek w euro w banku niemieckim nazywa go rachunkiem nostro.", True,
             why="Nostro – „nasz” rachunek u was."),
      ],
      calc=[
          LB("Kredyt 400 000 zł, WIBOR 3M 4,2%, marża 2,0%. Ile wynosi roczne oprocentowanie (%)?",
             6.2, "4.2+2.0", ["4,2% + 2,0% = 6,2%"], unit="%", tol=0.01),
          LB("Ten sam kredyt (400 000 zł). Ile wynoszą odsetki za pierwszy miesiąc przy 6,2% rocznie (zł)?",
             2066.67, "400000*0.062/12", ["400 000 · 6,2% / 12 ≈ 2066,67 zł"], unit="zł", tol=0.01),
          LB("WIBOR wzrósł o 1,5 pkt proc. O ile wzrosną miesięczne odsetki od długu 400 000 zł (zł)?",
             500, "400000*0.015/12", ["400 000 · 1,5% / 12 = 500 zł"], unit="zł"),
          LB("Bank pożycza 200 mln zł na rynku międzybankowym na 1 dzień po 3,80% (rok 365 dni). Ile zapłaci odsetek (zł)?",
             20821.92, "200e6*0.038/365", ["200 000 000 · 3,8% / 365 ≈ 20 821,92 zł"], unit="zł", tol=0.01),
          LB("Stopy NBP: depozytowa 3,25%, lombardowa 4,25%. Ile punktów bazowych ma szerokość korytarza?",
             100, "(4.25-3.25)*100", ["1 pkt proc. = 100 pb"], unit="pb"),
          LB("Bank centralny pożycza bankowi 5 mld zł na 7 dni po stopie lombardowej 4,25% (rok 365 dni). Ile wynoszą odsetki (mln zł)?",
             4.08, "5000*0.0425*7/365", ["5000 · 4,25% · 7/365 ≈ 4,08 mln zł"], unit="mln zł", tol=0.01),
      ],
      case=[
          PR("Średniej wielkości bank zdrowy pod względem kapitału traci nagle płynność: po plotce w mediach społecznościowych klienci w ciągu dwóch dni wypłacili 15% depozytów.",
             W("Co może zrobić bank centralny jako pożyczkodawca ostatniej instancji?",
               "Udzielić kredytu pod zastaw obligacji i kredytów banku", "Przejąć bank bez odszkodowania", "Zakazać wypłat w całym kraju",
               why="Wsparcie płynnościowe pozwala bankowi przetrwać panikę."),
             W("Dlaczego wsparcie powinno być udzielane po karnej stopie?",
               "By banki nie traktowały go jako taniego źródła finansowania", "By bank centralny zarobił jak najwięcej", "By przyspieszyć upadek banku",
               why="Ogranicza to pokusę nadużycia."),
             PF("Gwarancje BFG dla depozytów zmniejszają skłonność klientów do paniki.", True,
                why="Depozyty do równowartości 100 000 euro są chronione."),
          ),
          PR("Pani Ola ma kredyt hipoteczny z oprocentowaniem WIBOR 6M + 1,9 pkt proc., zawarty w 2021 r. W 2026 r. słyszy, że WIBOR „znika” i obawia się o umowę.",
             W("Co według stanu na październik 2026 r. dzieje się z jej umową?",
               "Może nadal działać na WIBOR – publikacja potrwa do końca 2036 r.", "Wygasa 1.01.2027", "Bank musi ją rozwiązać",
               why="GPW Benchmark ogłosił publikację WIBOR do 31.12.2036 r."),
             W("Na jakim wskaźniku banki mają opierać nowe kredyty od 2027 r.?",
               "POLSTR", "POLONIA", "Stopa lombardowa NBP",
               why="POLSTR jest docelowym wskaźnikiem referencyjnym."),
             PF("Zmiana wskaźnika nie musi oznaczać niższej raty – zależy od wartości wskaźnika i ewentualnego spreadu korygującego.", True,
                why="Przy zamianie wskaźnika stosuje się korektę, by nie zmieniać wartości umowy."),
          ),
      ]),

    L(3, "Kredyt dla klienta: zdolność, RRSO i raty",
      "Rozumieć, jak bank ocenia zdolność kredytową, dlaczego RRSO jest lepszą miarą kosztu kredytu niż oprocentowanie nominalne, jak działają odsetki maksymalne, karencja, prolongata i konsolidacja oraz czego uczy historia kredytów frankowych.",
      ["Zdolność kredytowa", "Rzeczywista roczna stopa oprocentowania (RRSO)", "Kredyt konsumencki i odsetki maksymalne", "Raty równe (annuitetowe) i malejące", "Karencja i prolongata", "Konsolidacja kredytów", "Promesa kredytowa", "Kredyty frankowe (CHF)"],
      [KNF, NBPE],
      explain=[
          K("Zdolność kredytowa",
            "Bank sprawdza, czy klient będzie w stanie spłacać raty: dochody i ich stabilność, wydatki, inne zobowiązania (BIK), wiek, liczbę osób na utrzymaniu. Wskaźnik DSTI = raty / dochód netto nie powinien przekraczać limitów zalecanych przez KNF. Bank uwzględnia też bufor na wzrost stóp procentowych.",
            w="DSTI = suma rat / dochód netto"),
          K("RRSO – pełny koszt kredytu",
            "Oprocentowanie nominalne obejmuje tylko odsetki. RRSO uwzględnia wszystkie koszty: odsetki, prowizje, obowiązkowe ubezpieczenia, opłaty – i wyraża je jako roczną stopę. Kredyt „0%” z wysoką prowizją może mieć RRSO kilkadziesiąt procent. Odsetki maksymalne w Polsce to dwukrotność sumy stopy referencyjnej NBP i 3,5 pkt proc. – przy stopie 3,75% (stan na 10.2026) wynoszą 14,5% rocznie.",
            w="odsetki maks. = 2 · (stopa referencyjna + 3,5 pkt proc.)"),
          W("Kredyt A: 9% i prowizja 0%. Kredyt B: 0% i prowizja 15% za rok. Który jest tańszy na rok?",
            "A", "B", "Kosztują tyle samo",
            why="Koszt A ≈ 9%, koszt B ≈ 15% kwoty – porównuje się RRSO, nie samo oprocentowanie."),
          K("Karencja, prolongata, konsolidacja",
            "Karencja – okres na początku, gdy nie spłaca się kapitału (czasem także odsetek), np. na czas budowy. Prolongata – wydłużenie terminu spłaty. Konsolidacja – zastąpienie kilku kredytów jednym, zwykle z niższą ratą dzięki dłuższemu okresowi, ale często z wyższym łącznym kosztem odsetek. Promesa – zobowiązanie banku do udzielenia kredytu po spełnieniu warunków."),
          K("Lekcja kredytów frankowych",
            "W latach 2005–2008 wiele osób brało kredyty indeksowane do franka szwajcarskiego, bo ich oprocentowanie (LIBOR CHF) było niższe niż WIBOR. Gdy frank gwałtownie zdrożał (zwłaszcza w 2008 i w styczniu 2015 r.), raty i saldo w złotych wzrosły. Kredytobiorca zarabiający w złotych ponosił ryzyko walutowe. Sądy, po wyroku TSUE C-260/18 (Dziubak, 2019), często uznają klauzule indeksacyjne za abuzywne."),
          PF("Wydłużenie okresu kredytu przy konsolidacji zwykle obniża ratę, ale zwiększa łączną kwotę odsetek.", True,
             why="Kapitał spłaca się wolniej, więc odsetki nalicza się dłużej."),
      ],
      mech=[
          LN("Ułóż, jak wzrost kursu franka wpływał na kredytobiorcę.",
             ["Klient bierze kredyt indeksowany do CHF przy kursie 2,10 zł", "Zarabia w złotych, a rata liczona jest we frankach", "Kurs franka rośnie do ponad 4 zł", "Rata i saldo kredytu w złotych gwałtownie rosną", "Wartość długu może przekroczyć wartość mieszkania"],
             why="Niedopasowanie waluty dochodu i długu to ryzyko walutowe."),
          KT("Co zwiększa, a co zmniejsza zdolność kredytową?",
             {"Zwiększa": ["Stała umowa o pracę", "Wyższy dochód netto", "Dłuższy okres kredytowania"],
              "Zmniejsza": ["Limit na karcie kredytowej", "Inne raty kredytów", "Większa liczba osób na utrzymaniu"]},
             why="Bank porównuje dochód z obciążeniami i kosztami życia."),
          W("RPP podnosi stopy procentowe. Co dzieje się ze zdolnością kredytową klientów przy kredytach o zmiennej stopie?",
            "Spada, bo rośnie rata przy tej samej kwocie", "Rośnie", "Nie zmienia się",
            why="Wyższa rata zwiększa DSTI przy tym samym dochodzie."),
          W("Dlaczego RRSO kredytu ratalnego „0%” może być wysokie?",
            "Bo uwzględnia prowizje i obowiązkowe ubezpieczenie", "Bo RRSO zawsze przekracza 20%", "Bo RRSO liczy tylko odsetki",
            why="RRSO obejmuje wszystkie koszty kredytu."),
          M("Które rozwiązania ograniczają ryzyko dla kredytobiorcy?",
            ["Kredyt w walucie, w której się zarabia", "Okresowo stała stopa procentowa", "Bufor oszczędności na kilka rat", "Najdłuższy możliwy kredyt w obcej walucie"], [0, 1, 2],
            why="Kredyt w obcej walucie dodaje ryzyko kursowe."),
          PF("Karencja w spłacie kapitału zmniejsza łączny koszt odsetek kredytu.", False,
             why="Kapitał pozostaje dłużej niespłacony, więc odsetki rosną."),
      ],
      calc=[
          LB("Stopa referencyjna NBP 3,75%. Ile wynoszą odsetki maksymalne (%)?",
             14.5, "2*(3.75+3.5)", ["2 · (3,75 + 3,5) = 14,5%"], unit="%", tol=0.01),
          LB("Dochód netto 9000 zł, raty 3150 zł. Ile wynosi DSTI (%)?",
             35, "3150/9000*100", ["3150 / 9000 = 35%"], unit="%"),
          LB("Kredyt 20 000 zł na rok, oprocentowanie 0%, prowizja 2400 zł płatna z góry, spłata na koniec roku. Ile wynosi przybliżona roczna stopa kosztu (%)?",
             13.64, "2400/(20000-2400)*100", ["Klient realnie dostaje 17 600 zł", "2400 / 17 600 ≈ 13,64%"], unit="%", tol=0.02),
          LB("Kredyt CHF 100 000 CHF, kurs przy zaciągnięciu 2,10 zł, później 4,20 zł. O ile złotych wzrosło saldo (spłat nie uwzględniamy)?",
             210000, "100000*(4.2-2.1)", ["100 000 · 2,10 = 210 000 zł wzrostu"], unit="zł"),
          LB("Dwa kredyty: 600 zł i 900 zł raty miesięcznie. Po konsolidacji rata 1100 zł. O ile spada miesięczne obciążenie (zł)?",
             400, "600+900-1100", ["1500 − 1100 = 400 zł"], unit="zł"),
          LB("Kredyt 300 000 zł, 6% rocznie, karencja w spłacie kapitału 12 miesięcy (płacone tylko odsetki). Ile zapłaci odsetek w okresie karencji (zł)?",
             18000, "300000*0.06", ["300 000 · 6% = 18 000 zł"], unit="zł"),
      ],
      case=[
          PR("Młode małżeństwo zarabia razem 11 000 zł netto i chce kredytu hipotecznego 500 000 zł na 30 lat. Bank liczy ratę równą przy 7% rocznie i wymaga DSTI ≤ 40%. Mają też ratę za samochód 700 zł.",
             W("Ile wynosi miesięczna rata kredytu hipotecznego (w przybliżeniu)?",
               "Ok. 3330 zł", "Ok. 1390 zł", "Ok. 5800 zł",
               why="500 000 · (0,07/12) / (1 − (1 + 0,07/12)^(−360)) ≈ 3326 zł."),
             W("Czy spełnią wymóg DSTI ≤ 40%?",
               "Tak – łącznie ok. 4030 zł to ok. 37% dochodu", "Nie – przekraczają 60%", "Nie da się tego policzyć",
               why="(3326 + 700) / 11 000 ≈ 36,6%."),
             W("Jak zmieni się DSTI, gdy stopa wzrośnie o 2 pkt proc.?",
               "Wzrośnie i może przekroczyć limit", "Spadnie", "Nie zmieni się",
               why="Rata przy 9% to ok. 4023 zł – razem z 700 zł daje ponad 42%."),
          ),
          PR("Pan Marek ma trzy kredyty konsumpcyjne z ratami 450, 600 i 800 zł. Bank proponuje konsolidację: jedna rata 1200 zł, ale okres spłaty wydłużony z 3 do 8 lat.",
             W("O ile spadnie miesięczna rata?",
               "O 650 zł", "O 1200 zł", "O 450 zł",
               why="1850 − 1200 = 650 zł."),
             PF("Konsolidacja może zwiększyć łączny koszt kredytu mimo niższej raty.", True,
                why="Dłuższy okres spłaty oznacza więcej odsetek."),
             W("Co Pan Marek powinien porównać przed decyzją?",
               "Łączną kwotę do spłaty i RRSO obu wariantów", "Tylko wysokość raty", "Tylko liczbę kredytów",
               why="Rata to nie cały koszt – liczy się suma płatności."),
          ),
      ]),

    L(4, "Bezpieczeństwo banków: kapitał, Bazylea i gwarancje depozytów",
      "Rozumieć, dlaczego banki są narażone na runy, jak wymogi kapitałowe Bazylei i gwarancje BFG zwiększają bezpieczeństwo oraz jak powstaje credit crunch.",
      ["Współczynnik wypłacalności (adekwatności kapitałowej)", "Umowy bazylejskie (Bazylea I, II, III)", "Run na bank (panika bankowa)", "Credit crunch (zakleszczenie kredytowe)"],
      [S282, BFG, KNF],
      explain=[
          K("Dlaczego banki są kruche",
            "Bank trzyma w rezerwie tylko część depozytów, a resztę ma w długoterminowych kredytach, których nie da się szybko sprzedać bez straty. Jeśli wielu klientów naraz zażąda wypłaty, nawet wypłacalny bank może stracić płynność. Panika jest samospełniającą się przepowiednią: kto wypłaci pierwszy, ten nie straci – więc wszyscy biegną do banku."),
          K("Współczynnik wypłacalności",
            "Kapitał banku porównuje się z aktywami ważonymi ryzykiem (RWA): kredyt dla skarbu państwa ma niską wagę, kredyt dla firmy – wyższą. Łączny współczynnik kapitałowy = fundusze własne / RWA. Bazylea III wymaga co najmniej 8% (w tym kapitału najwyższej jakości CET1 – 4,5%) plus bufory, m.in. zabezpieczający 2,5% i antycykliczny.",
            w="współczynnik = fundusze własne / aktywa ważone ryzykiem"),
          W("Bank ma kapitał 12 mld zł i RWA 100 mld zł. Ile wynosi współczynnik kapitałowy?",
            "12%", "8%", "1,2%",
            why="12 / 100 = 12% – powyżej minimum 8%."),
          K("Od Bazylei I do III",
            "Bazylea I (1988) wprowadziła minimum 8% kapitału do aktywów ważonych ryzykiem. Bazylea II (2004) dodała trzy filary: wymogi kapitałowe, nadzór i dyscyplinę rynkową. Bazylea III (od 2010) po kryzysie podniosła jakość i ilość kapitału, wprowadziła bufory, wskaźnik dźwigni i wymogi płynności (LCR, NSFR). W UE wdraża je pakiet CRR/CRD."),
          K("Gwarancje i credit crunch",
            "BFG gwarantuje depozyty do równowartości 100 000 euro na osobę w jednym banku – dzięki temu drobni klienci nie muszą panikować. Credit crunch to gwałtowne ograniczenie kredytów: banki, które poniosły straty lub boją się ryzyka, zaostrzają warunki, nawet wobec wiarygodnych klientów. Firmy tracą finansowanie, inwestycje spadają, a spowolnienie zwiększa straty banków – powstaje spirala."),
          PF("Gwarancje BFG obejmują depozyty do 100 000 euro na deponenta w danym banku.", True,
             why="To limit zharmonizowany w UE."),
      ],
      mech=[
          LN("Ułóż spiralę credit crunch.",
             ["Banki ponoszą straty na złych kredytach", "Spada ich kapitał i współczynnik wypłacalności", "Ograniczają nowe kredyty i zaostrzają warunki", "Firmy tną inwestycje i zatrudnienie", "Rośnie liczba niespłacanych kredytów i straty banków"],
             why="Kredyt i koniunktura wzajemnie się napędzają."),
          KT("Co zwiększa, a co zmniejsza współczynnik wypłacalności banku?",
             {"Zwiększa": ["Zatrzymanie zysku zamiast dywidendy", "Emisja nowych akcji", "Zamiana kredytów firmowych na obligacje skarbowe"],
              "Zmniejsza": ["Duże straty na kredytach", "Szybki wzrost ryzykownych kredytów", "Wypłata wysokiej dywidendy"]},
             why="Licznik to kapitał, mianownik – aktywa ważone ryzykiem."),
          W("Dlaczego gwarancje depozytów zmniejszają ryzyko runu na bank?",
            "Klienci nie muszą się spieszyć z wypłatą, bo ich środki są chronione", "Zakazują wypłat gotówki", "Zwiększają oprocentowanie lokat",
            why="Znika motyw „kto pierwszy, ten lepszy”."),
          W("Bank udziela więcej kredytów konsumpcyjnych o wysokiej wadze ryzyka, a kapitał się nie zmienia. Co z jego współczynnikiem kapitałowym?",
            "Spada", "Rośnie", "Nie zmienia się",
            why="Rośnie mianownik – aktywa ważone ryzykiem."),
          M("Co wprowadziła Bazylea III?",
            ["Bufor zabezpieczający i antycykliczny", "Wymogi płynności LCR i NSFR", "Wskaźnik dźwigni", "Zniesienie minimum kapitałowego"], [0, 1, 2],
            why="Bazylea III zaostrzyła, a nie zniosła wymogi."),
          PF("Gwarancje depozytów mogą zwiększać pokusę nadużycia – klienci mniej sprawdzają bezpieczeństwo banku.", True,
             why="Dlatego potrzebny jest nadzór i wymogi kapitałowe."),
      ],
      calc=[
          LB("Kredyt dla firmy 100 mln zł, waga ryzyka 100%. Ile minimalnego kapitału wymaga przy 8% (mln zł)?",
             8, "100*1.0*0.08", ["RWA 100", "100 · 8% = 8 mln zł"], unit="mln zł"),
          LB("Kredyt hipoteczny 100 mln zł, waga ryzyka 35%. Ile minimalnego kapitału przy 8% (mln zł)?",
             2.8, "100*0.35*0.08", ["RWA 35", "35 · 8% = 2,8 mln zł"], unit="mln zł", tol=0.01),
          LB("Bank: kapitał 9 mld zł, RWA 75 mld zł. Ile wynosi współczynnik kapitałowy (%)?",
             12, "9/75*100", ["9 / 75 = 12%"], unit="%"),
          LB("Ten bank traci 3 mld zł kapitału na złych kredytach (RWA bez zmian). Ile wynosi nowy współczynnik (%)?",
             8, "6/75*100", ["6 / 75 = 8%"], unit="%"),
          LB("Ile maksymalnie RWA może mieć bank z kapitałem 6 mld zł przy wymogu 10,5% (8% + bufor 2,5%, mld zł)?",
             57.14, "6/0.105", ["6 / 0,105 ≈ 57,14 mld zł"], unit="mld zł", tol=0.01),
          LB("Gwarancja BFG 100 000 euro, kurs 4,25 zł. Ile to złotych?",
             425000, "100000*4.25", ["100 000 · 4,25 = 425 000 zł"], unit="zł"),
      ],
      case=[
          PR("W marcu 2023 r. amerykański Silicon Valley Bank upadł w ciągu dwóch dni. Większość jego depozytów należała do firm technologicznych i przekraczała limit gwarancji. Bank miał dużo długoterminowych obligacji, których wartość spadła po podwyżkach stóp Fed. Gdy informacja o stratach wyszła na jaw, klienci w jeden dzień próbowali wypłacić ok. 42 mld USD.",
             W("Dlaczego run był tak szybki?",
               "Duzi, niegwarantowani deponenci obawiali się strat i mogli wypłacić środki jednym kliknięciem", "Bank nie miał żadnych aktywów", "Fed zakazał bankowi działalności",
               why="Brak ochrony gwarancyjnej i bankowość internetowa przyspieszyły panikę."),
             W("Jakie ryzyko zrealizowało się w portfelu obligacji SVB?",
               "Ryzyko stopy procentowej", "Ryzyko walutowe", "Ryzyko kradzieży",
               why="Wzrost stóp obniżył wartość obligacji o stałym kuponie."),
             PF("Run na bank może doprowadzić do upadku nawet bank, który mógłby przetrwać, gdyby klienci nie panikowali.", True,
                why="Wymuszona sprzedaż aktywów zamienia problem płynności w niewypłacalność."),
          ),
          PR("Bank w kraju X ma współczynnik kapitałowy 9%. Recesja powoduje straty, a współczynnik spada do 7,5%. Nadzorca wymaga powrotu do minimum.",
             W("Jakie są dwie główne drogi poprawy współczynnika?",
               "Podnieść kapitał lub ograniczyć aktywa ważone ryzykiem", "Wypłacić dywidendę i zwiększyć kredyty", "Obniżyć oprocentowanie lokat",
               why="Licznik w górę lub mianownik w dół."),
             W("Co się stanie w gospodarce, jeśli wiele banków naraz wybierze ograniczenie kredytów?",
               "Credit crunch pogłębiający recesję", "Szybkie ożywienie", "Spadek bezrobocia",
               why="Mniej kredytów oznacza mniej inwestycji i konsumpcji."),
             PF("Bufor antycykliczny gromadzony w dobrych czasach można uwolnić w kryzysie, by banki nie musiały gwałtownie ciąć kredytów.", True,
                why="Taki jest cel bufora antycyklicznego."),
          ),
      ]),

    L(5, "Kryzysy bankowe: subprime, bailout, bail-in i restrukturyzacja",
      "Rozumieć mechanizm kryzysu subprime, problem „zbyt duży, by upaść”, różnicę między ratowaniem banku z pieniędzy podatników (bailout) a umorzeniem długu wierzycieli (bail-in) oraz działanie przymusowej restrukturyzacji w Polsce.",
      ["Kryzys subprime (2007–2009)", "Zbyt duży, by upaść (too big to fail)", "Bailout i bail-in", "Przymusowa restrukturyzacja (resolution)", "Pakiet zaufania (NBP, 2008)", "Run na bank (panika bankowa)"],
      [S282, BFG],
      explain=[
          K("Kryzys subprime",
            "W USA w latach 2000. udzielano kredytów hipotecznych osobom o słabej zdolności (subprime), licząc na stały wzrost cen domów. Banki łączyły kredyty w papiery wartościowe (sekurytyzacja – MBS, CDO), które agencje oceniały wysoko i sprzedawały na cały świat. Gdy ceny domów spadły, kredyty przestały być spłacane, papiery straciły wartość, a banki nie wiedziały, kto ma straty – zaufanie i rynek międzybankowy zamarły. 15.09.2008 upadł Lehman Brothers."),
          K("Zbyt duży, by upaść",
            "Upadek wielkiego, powiązanego banku mógłby wywołać lawinę bankructw. Rządy ratują więc takie banki. Rodzi to pokusę nadużycia: duże banki podejmują większe ryzyko i taniej pożyczają, bo rynek zakłada pomoc państwa. Odpowiedzią są wyższe wymogi kapitałowe dla banków systemowych i procedury restrukturyzacji."),
          W("Na czym polega pokusa nadużycia przy zasadzie „too big to fail”?",
            "Bank ryzykuje bardziej, licząc na ratunek państwa", "Bank ogranicza ryzyko z obawy przed upadkiem", "Klienci wypłacają depozyty",
            why="Zyski są prywatne, a potencjalne straty przerzucane na podatników."),
          K("Bailout a bail-in",
            "Bailout: państwo dokapitalizowuje bank z pieniędzy podatników (np. w USA program TARP w 2008 r.). Bail-in: straty pokrywają najpierw akcjonariusze, potem wierzyciele – posiadacze obligacji, w ostateczności niegwarantowane depozyty powyżej 100 000 euro – przez umorzenie lub zamianę długu na akcje. W UE bail-in wprowadziła dyrektywa BRRD (2014), w Polsce stosuje go BFG od 2016 r."),
          K("Przymusowa restrukturyzacja w Polsce",
            "Gdy bank jest na progu upadku, a jego upadłość zagrażałaby stabilności, BFG może przejąć kontrolę: sprzedać bank lub jego część innemu bankowi, utworzyć bank pomostowy, umorzyć instrumenty kapitałowe. Przykłady: Idea Bank (przejęty przez Pekao, 2020) i Getin Noble Bank (2022 – bank pomostowy VeloBank). Klienci zachowali dostęp do depozytów. W październiku 2008 r. NBP przyjął „pakiet zaufania”, zapewniając bankom płynność w złotych i walutach."),
          PF("W bail-in akcjonariusze banku tracą jako pierwsi.", True,
             why="Kolejność pokrywania strat zaczyna się od kapitału własnego."),
      ],
      mech=[
          LN("Ułóż przebieg kryzysu subprime.",
             ["Banki udzielają kredytów hipotecznych klientom o słabej zdolności", "Kredyty są sekurytyzowane i sprzedawane jako wysoko oceniane papiery", "Ceny domów zaczynają spadać", "Rośnie liczba niespłacanych kredytów, papiery tracą wartość", "Banki przestają sobie ufać i pożyczać, upada Lehman Brothers"],
             why="Kryzys przeniósł się z rynku nieruchomości na system finansowy."),
          KT("Bailout czy bail-in?",
             {"Bailout": ["Rząd kupuje akcje banku za pieniądze budżetu", "Program TARP w USA w 2008 r."],
              "Bail-in": ["Obligacje banku zamienia się na akcje", "Umorzenie obligacji podporządkowanych przez BFG", "Cypr 2013 – strata części depozytów powyżej 100 000 euro"]},
             why="Bailout – podatnicy płacą; bail-in – wierzyciele i właściciele."),
          W("Dlaczego po upadku Lehman Brothers stopy na rynku międzybankowym gwałtownie wzrosły?",
            "Banki nie ufały sobie nawzajem i bały się nie odzyskać pożyczek", "Bank centralny podniósł stopy", "Wzrosła podaż pieniądza",
            why="Rosła premia za ryzyko kontrahenta."),
          W("Klient ma 50 000 zł w banku objętym przymusową restrukturyzacją. Co dzieje się z jego depozytem?",
            "Jest chroniony – kwoty do 100 000 euro są gwarantowane i nie podlegają umorzeniu", "Zostaje zamieniony na akcje banku", "Jest umarzany w całości",
            why="Depozyty gwarantowane są wyłączone z bail-in."),
          M("Jakie były przyczyny kryzysu subprime?",
            ["Kredyty udzielane osobom o niskiej zdolności", "Złożone papiery sekurytyzacyjne z zawyżonymi ratingami", "Przekonanie o stałym wzroście cen domów", "Zbyt wysokie wymogi kapitałowe banków inwestycyjnych"], [0, 1, 2],
            why="Banki inwestycyjne miały wtedy bardzo wysoką dźwignię, a nie zbyt wysoki kapitał."),
          PF("Przymusowa restrukturyzacja ma zapewnić ciągłość kluczowych funkcji banku bez użycia pieniędzy podatników.", True,
             why="Straty ponoszą właściciele i wierzyciele, a klienci dalej korzystają z usług."),
      ],
      calc=[
          LB("Bank inwestycyjny: aktywa 600 mld USD, kapitał 20 mld USD. Ile wynosi dźwignia (aktywa / kapitał)?",
             30, "600/20", ["600 / 20 = 30"], unit="razy"),
          LB("Przy dźwigni 30 jaki procentowy spadek wartości aktywów wyzeruje kapitał (%)?",
             3.33, "1/30*100", ["1 / 30 ≈ 3,33%"], unit="%", tol=0.02),
          LB("Bank ma stratę 12 mld zł. Kapitał akcyjny 7 mld zł, obligacje podporządkowane 4 mld zł, obligacje uprzywilejowane 10 mld zł. Ile straty pokryją obligacje uprzywilejowane w bail-in (mld zł)?",
             1, "12-7-4", ["Akcjonariusze 7", "Podporządkowane 4", "Pozostaje 1 mld zł"], unit="mld zł"),
          LB("Klient ma 150 000 euro w upadającym banku, gwarancja 100 000 euro, bail-in obejmuje 20% nadwyżki. Ile straci (euro)?",
             10000, "(150000-100000)*0.2", ["Nadwyżka 50 000", "20% = 10 000 euro"], unit="euro"),
          LB("Kredyt subprime 200 000 USD, dom sprzedany po spadku cen za 140 000 USD, koszty sprzedaży 10 000 USD. Ile wynosi strata banku (USD)?",
             70000, "200000-(140000-10000)", ["Odzysk 130 000", "Strata 70 000 USD"], unit="USD"),
          LB("Bank ma 30 mld zł depozytów, z czego 70% gwarantowanych. Ile depozytów jest niegwarantowanych (mld zł)?",
             9, "30*0.3", ["30 · 30% = 9 mld zł"], unit="mld zł"),
      ],
      case=[
          PR("30.09.2022 r. BFG wszczął przymusową restrukturyzację Getin Noble Banku. Działalność przeniesiono do banku pomostowego VeloBank, a akcje i obligacje podporządkowane Getin Noble Banku umorzono. Klienci od następnego dnia korzystali z kont i kart normalnie.",
             W("Kto poniósł straty w tej restrukturyzacji?",
               "Akcjonariusze i posiadacze obligacji podporządkowanych", "Wszyscy deponenci", "Budżet państwa w całości",
               why="To zastosowanie zasady bail-in."),
             W("Po co tworzy się bank pomostowy?",
               "By zachować ciągłość usług dla klientów, a następnie go sprzedać", "By zlikwidować wszystkie depozyty", "By wypłacić dywidendę",
               why="Bank pomostowy przejmuje zdrowe części działalności."),
             PF("Restrukturyzację finansował m.in. system ochrony banków komercyjnych i BFG, a nie bezpośrednio budżet państwa.", True,
                why="Wsparcie zapewniły BFG i System Ochrony Banków Komercyjnych utworzony przez największe banki."),
          ),
          PR("Jesienią 2008 r. po upadku Lehman Brothers polskie banki, choć nie miały istotnych papierów subprime, przestały sobie wzajemnie pożyczać, a ich klienci walutowi potrzebowali franków. NBP przyjął „pakiet zaufania”.",
             W("Dlaczego zamarł polski rynek międzybankowy, choć banki nie miały subprime?",
               "Zaufanie spadło globalnie, a banki gromadziły płynność na wszelki wypadek", "NBP zakazał pożyczek", "Zabrakło banknotów",
               why="Kryzys zaufania rozlał się na rynki całego świata."),
             W("Co oferował pakiet zaufania?",
               "Dodatkowe operacje dostarczające płynności w złotych i walutach", "Dokapitalizowanie banków z budżetu", "Gwarancję 100% wszystkich długów",
               why="NBP działał jako dostawca płynności, nie właściciel banków."),
             PF("Pakiet zaufania był przykładem działania banku centralnego jako pożyczkodawcy ostatniej instancji.", True,
                why="Dostarczanie płynności w kryzysie to ta właśnie funkcja."),
          ),
      ]),
    L(6, "Instrumenty rozliczeniowe i rynku pieniężnego: czek, weksel, akredytywa, konosament",
      "Znać instrumenty rozliczeniowe i krótkoterminowe instrumenty dłużne – czek, weksel (własny i trasowany, indos, awal), akcept bankierski, certyfikat depozytowy, inkaso i akredytywę dokumentową z konosamentem – oraz podstawowe produkty bankowe dla klientów.",
      ["Czek", "Weksel", "Akcept bankierski i certyfikat depozytowy", "Konosament", "Inkaso dokumentowe", "Akredytywa dokumentowa", "Cash back", "Produkty bankowe dla klientów", "Pieniądz elektroniczny i karta płatnicza"],
      [XWEK, XKON, XKM, S273],
      explain=[
          K("Czek",
            "Wystawca (posiadacz rachunku) poleca bankowi (trasatowi) wypłacić określoną kwotę okazicielowi lub wskazanej osobie. Czek jest instrumentem płatniczym – zastępuje gotówkę – i dziś w Polsce prawie nie jest używany, bo zastąpiły go przelewy i karty."),
          K("Weksel",
            "Papier wartościowy (Prawo wekslowe z 1936 r.). Weksel własny – wystawca sam przyrzeka zapłacić. Weksel trasowany – wystawca (trasant) poleca trasatowi zapłacić remitentowi; trasat zobowiązuje się przez akcept. Indos przenosi prawa z weksla na inną osobę, awal to poręczenie wekslowe. Weksel zaakceptowany przez bank to akcept bankierski – instrument rynku pieniężnego."),
          W("Firma A wystawia weksel, w którym poleca firmie B zapłacić 50 000 zł firmie C. Jaki to weksel?",
            "Trasowany", "Własny", "Czek",
            why="Wystawca poleca zapłatę innej osobie (trasatowi)."),
          K("Akredytywa, inkaso i konosament",
            "W handlu zagranicznym eksporter nie zna importera. Akredytywa dokumentowa – bank importera zobowiązuje się zapłacić eksporterowi po przedstawieniu dokumentów (najważniejszy: konosament). Inkaso dokumentowe – bank tylko pośredniczy w wydaniu dokumentów za zapłatę, bez gwarancji. Konosament (kodeks morski) potwierdza przyjęcie ładunku na statek, a jego posiadacz może żądać wydania towaru."),
          K("Produkty bankowe dla klientów",
            "Rachunek oszczędnościowo-rozliczeniowy (ROR), lokata terminowa, karta debetowa i kredytowa, kredyt w rachunku (debet), kredyt gotówkowy i hipoteczny, przelewy natychmiastowe i BLIK, cash back (wypłata gotówki przy płatności kartą w sklepie). Certyfikat depozytowy to zbywalny dokument potwierdzający lokatę terminową."),
          PF("Przy inkasie dokumentowym bank gwarantuje eksporterowi zapłatę.", False,
             why="Gwarancję daje akredytywa; inkaso to tylko pośrednictwo."),
      ],
      mech=[
          KT("Instrument rozliczeniowy czy rynku pieniężnego?",
             {"Instrument rozliczeniowy": ["Akredytywa dokumentowa", "Inkaso dokumentowe", "Karta płatnicza"],
              "Instrument rynku pieniężnego": ["Bon skarbowy", "Akcept bankierski", "Certyfikat depozytowy"]},
             why="Pierwsze służą płatnościom, drugie – krótkoterminowemu finansowaniu."),
          LN("Ułóż przebieg rozliczenia akredytywą dokumentową.",
             ["Importer zleca swojemu bankowi otwarcie akredytywy", "Bank zawiadamia eksportera o akredytywie", "Eksporter wysyła towar i otrzymuje konosament", "Eksporter przedstawia dokumenty w banku", "Bank płaci, a importer otrzymuje dokumenty i odbiera towar"],
             why="Bank płaci za zgodne dokumenty."),
          W("Co oznacza indos na wekslu?",
            "Przeniesienie praw z weksla na inną osobę", "Poręczenie wekslowe", "Odmowę zapłaty",
            why="Poręczenie to awal."),
          W("Dlaczego konosament jest ważny w akredytywie?",
            "Potwierdza wysłanie towaru i daje prawo do jego odbioru", "Jest umową kredytu", "Zastępuje fakturę VAT",
            why="To towarowy papier wartościowy."),
          M("Które produkty są typowe dla bankowości detalicznej?",
            ["Rachunek oszczędnościowo-rozliczeniowy", "Kredyt hipoteczny", "Karta debetowa", "Akredytywa dokumentowa"], [0, 1, 2],
            why="Akredytywa to produkt dla firm w handlu zagranicznym."),
          PF("Awal to poręczenie zobowiązania wekslowego.", True,
             why="Awalista odpowiada jak ten, za kogo poręczył."),
      ],
      calc=[
          LB("Weksel na 10 000 zł płatny za 90 dni zdyskontowano przy stopie dyskontowej 8% rocznie (rok = 360 dni). Ile wynosi dyskonto (zł)?",
             200, "10000*0.08*90/360", ["10 000 · 0,08 · 90/360 = 200 zł"], unit="zł"),
          LB("Ile otrzymał posiadacz weksla (zł)?",
             9800, "10000-200", ["10 000 − 200 = 9 800 zł"], unit="zł"),
          LB("Prowizja za akredytywę 0,2% od 500 000 zł. Ile wynosi (zł)?",
             1000, "500000*0.002", ["500 000 · 0,002 = 1 000 zł"], unit="zł"),
          LB("Certyfikat depozytowy 100 000 zł na 6 miesięcy na 4% rocznie. Ile wynoszą odsetki (zł)?",
             2000, "100000*0.04*0.5", ["100 000 · 0,04 · 0,5 = 2 000 zł"], unit="zł"),
          LB("Odsetki po podatku Belki 19% (zł)?",
             1620, "2000*0.81", ["2 000 · 0,81 = 1 620 zł"], unit="zł"),
          LB("Klient płaci kartą 120 zł i wypłaca 200 zł cash back. Ile łącznie obciąża jego konto (zł)?",
             320, "120+200", ["120 + 200 = 320 zł"], unit="zł"),
      ],
      case=[
          PR("Polska firma meblarska po raz pierwszy sprzedaje meble klientowi z Kanady za 200 000 euro. Obawia się, że po wysłaniu kontenera nie dostanie zapłaty. Klient z kolei nie chce płacić z góry.",
             W("Jaka forma rozliczenia najlepiej chroni obie strony?",
               "Akredytywa dokumentowa", "Przedpłata gotówką", "Zwykły przelew po dostawie",
               why="Bank płaci po przedstawieniu dokumentów wysyłki."),
             W("Jaki dokument potwierdzi załadunek mebli na statek?",
               "Konosament", "Weksel własny", "Certyfikat depozytowy",
               why="Konosament wystawia przewoźnik morski."),
             PF("Inkaso dokumentowe byłoby tańsze, ale nie gwarantuje zapłaty przez bank.", True,
                why="Bank tylko pośredniczy w wymianie dokumentów na zapłatę."),
          ),
          PR("Hurtownia dostaje od kontrahenta weksel na 30 000 zł płatny za 3 miesiące. Potrzebuje gotówki teraz, więc przekazuje weksel (indos) dostawcy jako zapłatę, a ten dyskontuje go w banku.",
             W("Co hurtownia zrobiła, przekazując weksel dostawcy?",
               "Indosowała weksel", "Udzieliła awalu", "Wystawiła czek",
               why="Indos przenosi prawa z weksla."),
             W("Dlaczego bank wypłaci dostawcy mniej niż 30 000 zł?",
               "Pobiera dyskonto za oczekiwanie na zapłatę i ryzyko", "Bo weksel jest nieważny", "Bo musi zapłacić VAT",
               why="To koszt wcześniejszego otrzymania pieniędzy."),
             PF("Weksel może pełnić funkcję środka płatniczego między firmami.", True,
                why="Dzięki indosowi krąży jak pieniądz kredytowy."),
          ),
      ]),
]
