# -*- coding: utf-8 -*-
# Zrozumienie – Finanse / Kryzysy i globalny system finansowy (wg S. Owsiak, „Finanse”, PWE 2015 – literatura OWE)
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-08"
P282 = S("OpenStax, Principles of Economics 3e, 28.2 Bank Regulation", OS3 + "28-2-bank-regulation", D)
P294 = S("OpenStax, Principles of Economics 3e, 29.4 Exchange Rate Policies", OS3 + "29-4-exchange-rate-policies", D)
WTM = S("Wikipedia – Tulip mania", "https://en.wikipedia.org/wiki/Tulip_mania", D)
BRL = S("Britannica – John Law (Mississippi Bubble)", "https://www.britannica.com/money/John-Law", D)
WSS = S("Wikipedia – South Sea Company", "https://en.wikipedia.org/wiki/South_Sea_Company", D)
WMX = S("Wikipedia – Mexican peso crisis", "https://en.wikipedia.org/wiki/Mexican_peso_crisis", D)
WAS = S("Wikipedia – 1997 Asian financial crisis", "https://en.wikipedia.org/wiki/1997_Asian_financial_crisis", D)
FHGD = S("Federal Reserve History – The Great Depression", "https://www.federalreservehistory.org/essays/great-depression", D)
FHGR = S("Federal Reserve History – The Great Recession", "https://www.federalreservehistory.org/essays/great-recession-of-200709", D)
BISF = S("BIS – Financial Stability Forum re-established as the Financial Stability Board (3.04.2009)", "https://www.bis.org/press/p090403a.htm", D)
ESMH = S("ESM – History (EFSF 2010, ESM 2012)", "https://www.esm.europa.eu/about-us/history", D)
WEFSM = S("Wikipedia – European Financial Stabilisation Mechanism", "https://en.wikipedia.org/wiki/European_Financial_Stabilisation_Mechanism", D)
SOLV = S("Wikipedia – Solvency II", "https://en.wikipedia.org/wiki/Solvency_II", D)
ESRB = S("Regulation (EU) No 1092/2010 – European Systemic Risk Board (EUR-Lex)", "https://eur-lex.europa.eu/eli/reg/2010/1092/oj", D)

LESSONS = [
    L(1, "Czym jest kryzys finansowy i gdzie się zaczyna",
      "Rozumieć istotę kryzysu finansowego, jego przesłanki i rodzaje (bankowy, walutowy, finansów publicznych, giełdowy) oraz mechanizmy zarażania i przenoszenia na gospodarkę realną.",
      ["Kryzys finansowy – istota i rodzaje", "Run na bank (panika bankowa)", "Kryzysy walutowe – generacje", "Hipoteza niestabilności finansowej", "Zbyt duży, by upaść (too big to fail)"],
      [P282, FHGD],
      explain=[
          K("Istota kryzysu",
            "Kryzys finansowy to gwałtowne zaburzenie działania systemu finansowego: ceny aktywów spadają, instytucje tracą płynność lub wypłacalność, zaufanie znika, a kredyt się kurczy. Skutki przenoszą się na gospodarkę realną – inwestycje i konsumpcja spadają, rośnie bezrobocie."),
          K("Typowe przesłanki",
            "Szybki wzrost kredytu i dźwigni, bańka cen aktywów (akcje, nieruchomości), niedopasowanie terminów (krótkie depozyty, długie kredyty) i walut (długi w walucie obcej), słaby nadzór, pokusa nadużycia („too big to fail”). H. Minsky: długi okres stabilności skłania do coraz ryzykowniejszego finansowania."),
          W("Bank finansuje 30-letnie kredyty hipoteczne depozytami na żądanie. Jakie ryzyko to rodzi?",
            "Ryzyko płynności – niedopasowanie terminów", "Ryzyko walutowe", "Ryzyko inflacji zerowej",
            why="Masowe wypłaty depozytów mogą przekroczyć dostępne środki."),
          K("Rodzaje kryzysów",
            "Bankowy – run na banki, upadłości. Walutowy – gwałtowna deprecjacja, utrata rezerw. Finansów publicznych – państwo traci dostęp do rynku lub ogłasza niewypłacalność. Giełdowy – pęknięcie bańki. Często występują razem (np. kryzys bliźniaczy: bankowy i walutowy)."),
          K("Zarażanie",
            "Kryzys przenosi się przez powiązania między bankami, sprzedaż aktywów w panice, utratę zaufania do podobnych krajów (efekt tequili 1995, Azja 1997) i spadek handlu."),
          PF("Kryzys walutowy i bankowy często występują jednocześnie.", True,
             why="Deprecjacja zwiększa długi w walucie obcej i osłabia banki."),
      ],
      mech=[
          KT("Jaki rodzaj kryzysu?",
             {"Bankowy": ["Klienci masowo wypłacają depozyty", "Upadłości banków po stratach kredytowych"],
              "Walutowy": ["Waluta traci 40% wartości w miesiąc", "Bank centralny traci rezerwy, broniąc kursu"],
              "Finansów publicznych": ["Rząd nie może sprzedać obligacji", "Państwo ogłasza restrukturyzację długu"]},
             why="Rodzaje kryzysów finansowych."),
          LN("Ułóż przebieg typowego kryzysu kredytowego.",
             ["Długi okres stabilności i optymizmu", "Szybki wzrost kredytu i cen aktywów", "Rośnie zadłużenie i dźwignia", "Szok obniża ceny aktywów", "Straty banków, panika i spadek kredytu"],
             why="Mechanizm opisany m.in. przez H. Minsky’ego."),
          W("Dlaczego gwarancje depozytów ograniczają ryzyko runu na bank?",
            "Klienci nie muszą się spieszyć z wypłatą, bo depozyty do limitu są chronione", "Bo zakazują wypłat", "Bo podnoszą stopy",
            why="Usuwają motyw „kto pierwszy, ten lepszy”."),
          W("Co oznacza „too big to fail”?",
            "Bank jest tak duży, że państwo nie pozwoli mu upaść – co zachęca do ryzyka", "Bank ma zbyt mało klientów", "Bank nie podlega nadzorowi",
            why="Oczekiwanie ratunku tworzy pokusę nadużycia."),
          M("Które zjawiska należą do przesłanek kryzysu?",
            ["Bańka na rynku nieruchomości", "Wysoka dźwignia banków", "Kredyty w walucie obcej przy dochodach w krajowej", "Stabilny, umiarkowany wzrost kredytu"], [0, 1, 2],
            why="Umiarkowany wzrost kredytu nie jest przesłanką kryzysu."),
          PF("Kryzys finansowy zawsze pozostaje w sferze finansowej i nie wpływa na bezrobocie.", False,
             why="Spadek kredytu ogranicza inwestycje i zatrudnienie."),
      ],
      calc=[
          LB("Bank ma 100 mld zł aktywów i 8 mld zł kapitału. Ile wynosi dźwignia (aktywa/kapitał)?",
             12.5, "100/8", ["100 / 8 = 12,5"], unit=""),
          LB("Aktywa tracą 5% wartości. Ile kapitału zostaje (mld zł)?",
             3, "8-100*0.05", ["8 − 5 = 3 mld zł"], unit="mld zł"),
          LB("O ile procent spadł kapitał (%)?",
             62.5, "5/8*100", ["5 / 8 = 62,5%"], unit="%"),
          LB("Bank ma 10 mld zł płynnych aktywów, a klienci chcą wypłacić 15% z 80 mld zł depozytów. Ile brakuje (mld zł)?",
             2, "80*0.15-10", ["12 − 10 = 2 mld zł"], unit="mld zł"),
          LB("Firma ma dług 1 mln euro. Kurs rośnie z 4,30 do 5,00 zł/EUR. O ile wzrasta dług w złotych (tys. zł)?",
             700, "(5.00-4.30)*1000", ["0,70 · 1 000 = 700 tys. zł"], unit="tys. zł"),
          LB("Rezerwy walutowe 50 mld USD, bank centralny sprzedaje 4 mld USD miesięcznie. Na ile miesięcy wystarczą?",
             12.5, "50/4", ["50 / 4 = 12,5 miesiąca"], unit="mies."),
      ],
      case=[
          PR("We wrześniu 2007 r. klienci brytyjskiego banku Northern Rock ustawili się w kolejkach, by wypłacić depozyty, gdy bank – finansujący kredyty hipoteczne pożyczkami na rynku hurtowym – stracił dostęp do finansowania. Bank otrzymał pomoc Banku Anglii, a w 2008 r. został znacjonalizowany.",
             W("Jaki rodzaj kryzysu ilustruje ten przypadek?",
               "Bankowy – run na bank", "Walutowy", "Kryzys finansów publicznych",
               why="Masowe wypłaty depozytów."),
             W("Jaką przesłankę kryzysu miał Northern Rock?",
               "Finansowanie długich kredytów krótkoterminowymi pożyczkami rynkowymi", "Zbyt duży kapitał", "Brak kredytów hipotecznych",
               why="Niedopasowanie terminów i zależność od rynku hurtowego."),
             PF("Interwencja Banku Anglii to przykład roli pożyczkodawcy ostatniej instancji.", True,
                why="Bank centralny dostarczył płynności."),
          ),
          PR("W kraju przez lata szybko rosły ceny mieszkań i kredyty, w tym w walucie obcej. Po podwyżce stóp procentowych za granicą waluta krajowa straciła 30%, raty kredytów wzrosły, część kredytobiorców przestała spłacać, a banki ograniczyły kredyt.",
             W("Jakie kryzysy się tu łączą?",
               "Walutowy i bankowy", "Tylko giełdowy", "Żaden",
               why="Deprecjacja wywołała straty kredytowe banków."),
             W("Dlaczego kredyty w walucie obcej zwiększyły ryzyko?",
               "Dochody były w walucie krajowej, a dług w obcej – deprecjacja podniosła raty", "Bo były tańsze w spłacie", "Bo nie podlegały odsetkom",
               why="Niedopasowanie walutowe."),
             PF("Nadzór makroostrożnościowy może ograniczać takie ryzyka, np. limitami kredytów walutowych.", True,
                why="To jedno z narzędzi polityki makroostrożnościowej."),
          ),
      ]),

    L(2, "Historyczne bańki: tulipany, Missisipi, Mórz Południowych i Wielki Kryzys",
      "Znać przebieg pierwszych opisanych baniek spekulacyjnych (1637, 1720) i Wielkiego Kryzysu oraz wspólne cechy baniek: optymizm, kredyt, spekulacja i nagłe załamanie.",
      ["Mania tulipanowa", "Bańki Kompanii Missisipi i Kompanii Mórz Południowych (1720)", "Bańka spekulacyjna", "1929–1933 – Wielki Kryzys", "Law John", "1637 – krach na rynku tulipanów", "1720 – bańki Missisipi i Mórz Południowych"],
      [WTM, BRL, WSS, FHGD],
      explain=[
          K("Mania tulipanowa (1634–1637)",
            "W Republice Zjednoczonych Prowincji (Niderlandy) modne cebulki tulipanów stały się przedmiotem spekulacji – handlowano kontraktami na przyszłą dostawę. Ceny niektórych odmian sięgnęły niebotycznych poziomów, a w lutym 1637 r. rynek się załamał. Uznaje się ją za pierwszą opisaną bańkę spekulacyjną, choć jej skutki gospodarcze były ograniczone."),
          K("System Lawa i Kompania Missisipi",
            "Szkot J. Law założył we Francji bank emitujący banknoty (1716) i Kompanię Missisipi (Kompanię Zachodu), której akcje wymieniano na obligacje państwa. Emisja pieniądza napędzała popyt na akcje – kurs wzrósł z 500 do ok. 18 000 liwrów. W 1720 r. bańka pękła, a Law uciekł z Francji."),
          W("Co napędzało wzrost kursu akcji Kompanii Missisipi?",
            "Emisja banknotów przez bank Lawa i wymiana akcji na dług państwa", "Rzeczywiste zyski z handlu z Ameryką", "Spadek podaży pieniądza",
            why="Bańka była napędzana pieniądzem i kredytem."),
          K("Kompania Mórz Południowych (1720)",
            "Brytyjska kompania przejmowała dług państwa w zamian za akcje; mimo braku znaczących zysków z handlu kurs wzrósł ze 128 do niemal 1000 funtów, a jesienią 1720 r. się załamał. Kompania sprzedawała akcje na kredyt, co przyspieszało wzrost."),
          K("Wielki Kryzys (1929–1933)",
            "Po krachu na giełdzie nowojorskiej w październiku 1929 r. kolejne paniki bankowe i kurczenie się podaży pieniądza (o blisko 30% w latach 1930–1933) pogłębiły depresję. Lekcje: bank centralny powinien dostarczać płynności w panice, potrzebne są gwarancje depozytów i nadzór."),
          PF("Wspólną cechą wielu baniek jest finansowanie zakupów aktywów kredytem lub nowym pieniądzem.", True,
             why="Kredyt napędza wzrost cen ponad wartość fundamentalną."),
      ],
      mech=[
          KT("Która bańka lub kryzys?",
             {"Mania tulipanowa": ["Niderlandy, 1637", "Kontrakty na cebulki kwiatów"],
              "Kompania Missisipi": ["Francja, J. Law", "Bank emitujący banknoty i akcje wymieniane na dług"],
              "Kompania Mórz Południowych": ["Wielka Brytania, 1720", "Akcje sprzedawane na kredyt"],
              "Wielki Kryzys": ["Krach w Nowym Jorku w październiku 1929 r.", "Fale paniki bankowej w USA"]},
             why="Najsłynniejsze bańki i kryzysy w historii."),
          LN("Ułóż typowe etapy bańki spekulacyjnej.",
             ["Nowość lub innowacja budzi entuzjazm", "Ceny rosną, kredyt ułatwia zakupy", "Kupują nowi inwestorzy, licząc na dalszy wzrost", "Ceny tracą związek z wartością fundamentalną", "Zaufanie pęka i ceny gwałtownie spadają"],
             why="Schemat opisywany przez Minsky’ego i Kindlebergera."),
          W("W którym roku pękły bańki Missisipi i Mórz Południowych?",
            "W 1720 r.", "W 1637 r.", "W 1929 r.",
            why="Obie bańki pękły w tym samym roku."),
          W("Co pogłębiło Wielki Kryzys według Friedmana i Schwartz?",
            "Spadek podaży pieniądza przy bierności banku centralnego", "Zbyt szybki wzrost podaży pieniądza", "Brak giełdy",
            why="Paniki bankowe zmniejszyły mnożnik kreacji pieniądza."),
          M("Które rozwiązania wprowadzono po doświadczeniach Wielkiego Kryzysu?",
            ["Gwarancje depozytów", "Silniejszy nadzór bankowy", "Aktywną rolę banku centralnego w panice", "Powrót do sztywnego standardu złota"], [0, 1, 2],
            why="Standard złota utrudniał reakcję na kryzys."),
          PF("Mania tulipanowa doprowadziła do głębokiej wieloletniej depresji w Niderlandach.", False,
             why="Historycy oceniają jej skutki gospodarcze jako ograniczone."),
      ],
      calc=[
          LB("Akcja Kompanii Missisipi zdrożała z 500 do 18 000 liwrów. Ile razy?",
             36, "18000/500", ["18 000 / 500 = 36"], unit="razy"),
          LB("Akcja Kompanii Mórz Południowych zdrożała ze 128 do 1000 funtów. O ile procent (zaokrąglij do 1)?",
             681, "(1000/128-1)*100", ["1000 / 128 ≈ 7,81 → wzrost ok. 681%"], unit="%"),
          LB("Po krachu kurs spadł z 1000 do 150 funtów. O ile procent?",
             85, "(1-150/1000)*100", ["1 − 0,15 = 85%"], unit="%"),
          LB("Podaż pieniądza spadła o 30%. Przy stałym V i stałej produkcji realnej o ile procent spadłby poziom cen według teorii ilościowej?",
             30, "30", ["%ΔP = %ΔM = −30%"], unit="%"),
          LB("Inwestor kupił akcje za 10 000 zł, z czego 8 000 zł pożyczył. Kurs spadł o 20%. Ile procent własnego kapitału stracił?",
             100, "10000*0.2/2000*100", ["Strata 2 000 zł = cały wkład własny 2 000 zł"], unit="%"),
          LB("Ten sam spadek bez kredytu (wkład 10 000 zł). Ile procent kapitału traci (%)?",
             20, "20", ["2 000 / 10 000 = 20%"], unit="%"),
      ],
      case=[
          PR("W 1720 r. w Londynie powstawały dziesiątki nowych spółek akcyjnych, z których część nie miała realnych planów działalności. Akcje Kompanii Mórz Południowych sprzedawano na kredyt. Zanim bańka pękła, parlament uchwalił „Bubble Act” ograniczający zakładanie spółek.",
             W("Jaki mechanizm przyspieszał wzrost cen akcji?",
               "Sprzedaż akcji na kredyt", "Wysokie dywidendy z handlu", "Spadek liczby spółek",
               why="Kredyt zwiększał popyt na akcje."),
             W("Co łączy tę bańkę z Kompanią Missisipi?",
               "Obie wymieniały dług państwa na akcje i pękły w 1720 r.", "Obie dotyczyły tulipanów", "Obie zakończyły się sukcesem",
               why="Podobny schemat przejmowania długu publicznego."),
             PF("Według finansów behawioralnych owczy pęd sprzyja powstawaniu takich baniek.", True,
                why="Kupujący naśladują innych, licząc na dalszy wzrost."),
          ),
          PR("Między 1929 a 1933 r. w USA upadły tysiące banków, podaż pieniądza spadła o blisko 30%, produkcja i ceny gwałtownie spadły, a bezrobocie sięgnęło jednej czwartej siły roboczej. W 1933 r. utworzono federalny system gwarancji depozytów.",
             W("Dlaczego upadki banków zmniejszały podaż pieniądza?",
               "Ludzie trzymali więcej gotówki, a banki więcej rezerw – spadał mnożnik", "Bo rząd zakazał kredytów", "Bo rosła baza monetarna",
               why="Paniki bankowe ograniczają kreację pieniądza."),
             W("Czemu miały służyć gwarancje depozytów?",
               "Powstrzymaniu runów na banki", "Zwiększeniu inflacji", "Likwidacji banków",
               why="Klienci nie muszą się bać o depozyty."),
             PF("Wielki Kryzys przyczynił się do rozwoju teorii Keynesa i finansowania antycyklicznego.", True,
                why="„Ogólna teoria” ukazała się w 1936 r."),
          ),
      ]),

    L(3, "Kryzysy walutowe: Meksyk 1994, Azja 1997 i bańka internetowa",
      "Analizować kryzysy walutowe końca XX w. – meksykański (efekt tequili) i azjatycki – oraz bańkę internetową 2000 r., a także rozumieć rolę ucieczki kapitału, długu w walucie obcej i stałego kursu.",
      ["Kryzys meksykański (1994–1995)", "Kryzys azjatycki (1997–1998)", "Ucieczka kapitału", "Kryzysy walutowe – generacje", "2000 – płynny kurs złotego i bańka internetowa"],
      [WMX, WAS, P294],
      explain=[
          K("Kryzys meksykański (1994–1995)",
            "W grudniu 1994 r. Meksyk zdewaluował peso. Inwestorzy, obawiając się o spłatę krótkoterminowego długu powiązanego z dolarem, wycofywali kapitał – peso gwałtownie straciło na wartości, a gospodarka popadła w recesję. Zarażenie innych krajów Ameryki Łacińskiej nazwano „efektem tequili”; Meksyk otrzymał pomoc USA i MFW."),
          K("Kryzys azjatycki (1997–1998)",
            "W lipcu 1997 r. Tajlandia porzuciła powiązanie bahta z dolarem. Kryzys rozlał się na Indonezję, Koreę Płd., Malezję i inne kraje: banki i firmy zadłużone w dolarach traciły wypłacalność, kapitał uciekał, waluty gwałtownie traciły na wartości. MFW udzielił pomocy z warunkami dostosowawczymi. Po kryzysie utworzono Forum Stabilności Finansowej (1999)."),
          W("Co łączy kryzys meksykański i azjatycki?",
            "Ucieczka kapitału i krach kursu stałego lub powiązanego z dolarem", "Bańka na rynku tulipanów", "Brak długu zagranicznego",
            why="W obu przypadkach ucieczka kapitału doprowadziła do załamania kursu."),
          K("Bańka internetowa (2000)",
            "Pod koniec lat 90. akcje spółek internetowych drożały, choć wiele z nich nie miało zysków; indeks Nasdaq od szczytu w 2000 r. do 2002 r. stracił prawie 80%. Był to kryzys giełdowy bez wielkiego kryzysu bankowego, bo zakupy finansowano głównie kapitałem własnym."),
          K("Wnioski",
            "Ryzyko rośnie przy sztywnym kursie, dużym długu krótkoterminowym w walucie obcej i słabym nadzorze bankowym. Dlatego wiele krajów (w tym Polska od 2000 r.) wybrało płynny kurs, gromadzi rezerwy i stosuje politykę makroostrożnościową."),
          PF("Płynny kurs walutowy całkowicie wyklucza kryzysy finansowe.", False,
             why="Zmniejsza ryzyko ataku na kurs, ale kryzysy mogą mieć inne źródła."),
      ],
      mech=[
          KT("Który kryzys?",
             {"Meksyk 1994–1995": ["Dewaluacja peso w grudniu", "Efekt tequili"],
              "Azja 1997–1998": ["Tajlandia porzuca powiązanie bahta z dolarem", "Kłopoty Korei Płd. i Indonezji"],
              "Bańka internetowa 2000": ["Załamanie indeksu Nasdaq", "Spółki bez zysków wyceniane na miliardy"]},
             why="Trzy kryzysy przełomu wieków."),
          LN("Ułóż przebieg kryzysu walutowego przy stałym kursie.",
             ["Kraj utrzymuje stały kurs i ma duży dług w dolarach", "Inwestorzy tracą zaufanie i wycofują kapitał", "Bank centralny broni kursu, tracąc rezerwy", "Kurs zostaje uwolniony i waluta gwałtownie traci", "Rośnie ciężar długu, upadają banki i firmy"],
             why="Mechanizm kryzysów lat 90."),
          W("Dlaczego dług w dolarach był tak groźny w Azji?",
            "Deprecjacja waluty krajowej gwałtownie zwiększała jego wartość w walucie krajowej", "Bo dolar tracił na wartości", "Bo dług był w walucie krajowej",
            why="Niedopasowanie walutowe – grzech pierworodny."),
          W("Jak nazwano zarażenie Ameryki Łacińskiej kryzysem meksykańskim?",
            "Efektem tequili", "Efektem cappuccino", "Efektem Pigou",
            why="Nazwa od meksykańskiego trunku."),
          M("Co zmniejsza ryzyko kryzysu walutowego?",
            ["Płynny kurs walutowy", "Duże rezerwy walutowe", "Ograniczenie krótkoterminowego długu w walucie obcej", "Sztywne powiązanie z dolarem przy dużym deficycie"], [0, 1, 2],
            why="Sztywny kurs przy dużym deficycie zachęca do ataku spekulacyjnego."),
          PF("Po kryzysie azjatyckim kraje G7 utworzyły Forum Stabilności Finansowej.", True,
             why="FSF powstało w 1999 r."),
      ],
      calc=[
          LB("Kurs wzrósł z 3,5 do 6 peso za dolara. O ile procent zdrożał dolar (zaokrąglij do 0,1)?",
             71.4, "(6/3.5-1)*100", ["6 / 3,5 ≈ 1,714 → 71,4%"], unit="%"),
          LB("O ile procent stracił peso wobec dolara (wartość dolarowa peso; zaokrąglij do 0,1)?",
             41.7, "(1-3.5/6)*100", ["1 − 3,5 / 6 ≈ 41,7%"], unit="%"),
          LB("Firma ma dług 10 mln USD. Ile wynosi w peso przy kursie 6 (mln peso)?",
             60, "10*6", ["10 · 6 = 60 mln peso"], unit="mln peso"),
          LB("Przed kryzysem dług wynosił 35 mln peso. O ile mln peso wzrósł?",
             25, "60-35", ["60 − 35 = 25 mln peso"], unit="mln peso"),
          LB("Indeks spadł z 5 000 do 1 100 pkt. O ile procent?",
             78, "(1-1100/5000)*100", ["1 − 0,22 = 78%"], unit="%"),
          LB("Rezerwy 30 mld USD, dług krótkoterminowy 45 mld USD. Ile wynosi wskaźnik rezerwy/dług krótkoterminowy (%; zaokrąglij do 0,1)?",
             66.7, "30/45*100", ["30 / 45 ≈ 66,7% – poniżej bezpiecznego poziomu 100%"], unit="%"),
      ],
      case=[
          PR("Tajlandia przed 1997 r. utrzymywała baht powiązany z dolarem, a banki i firmy pożyczały tanio w dolarach, inwestując w nieruchomości. Gdy eksport osłabł, inwestorzy zaczęli wycofywać kapitał. W lipcu 1997 r. bank centralny, który stracił większość rezerw, uwolnił kurs.",
             W("Dlaczego bank centralny w końcu uwolnił kurs?",
               "Wyczerpały się rezerwy potrzebne do obrony powiązania", "Bo chciał wzmocnić bahta", "Bo zakazał handlu dolarem",
               why="Obrona kursu wymaga sprzedaży rezerw."),
             W("Jaki był skutek dla firm zadłużonych w dolarach?",
               "Ich długi w bahtach gwałtownie wzrosły", "Ich długi zmalały", "Nic się nie zmieniło",
               why="Deprecjacja zwiększa wartość długu walutowego."),
             PF("Kryzys rozlał się na inne kraje regionu.", True,
                why="M.in. Indonezję, Koreę Płd. i Malezję."),
          ),
          PR("Pod koniec lat 90. inwestorzy masowo kupowali akcje spółek internetowych. Wskaźniki C/Z przekraczały 100, a część spółek nie miała przychodów. Od 2000 r. indeks Nasdaq stracił prawie 80% wartości.",
             W("Jakiego rodzaju kryzys to był?",
               "Giełdowy – pęknięcie bańki spekulacyjnej", "Walutowy", "Finansów publicznych",
               why="Załamały się ceny akcji."),
             W("Dlaczego nie przerodził się w głęboki kryzys bankowy?",
               "Zakupy akcji finansowano głównie kapitałem własnym, a nie kredytem bankowym", "Bo banki nie istniały", "Bo stopy były ujemne",
               why="Straty poniosły głównie osoby inwestujące, a nie banki."),
             PF("Krytycy hipotezy rynku efektywnego uznali tę bańkę za przykład irracjonalnego entuzjazmu.", True,
                why="R. Shiller, „Irrational Exuberance” (2000)."),
          ),
      ]),

    L(4, "Kryzys 2007–2008 i działania ratunkowe",
      "Rozumieć przyczyny i przebieg globalnego kryzysu finansowego 2007–2008 (kredyty subprime, sekurytyzacja, upadek Lehman Brothers), działania ratunkowe (bailout, luzowanie ilościowe, pakiet zaufania NBP) i reformy po kryzysie.",
      ["Kryzys subprime (2007–2009)", "2008 – upadek Lehman Brothers", "Sekurytyzacja", "Luzowanie ilościowe (QE)", "Pakiet zaufania (NBP, 2008)", "Bailout i bail-in"],
      [FHGR, P282],
      explain=[
          K("Przyczyny",
            "W USA rosły ceny domów, a banki udzielały kredytów hipotecznych osobom o niskiej zdolności (subprime). Kredyty łączono w papiery wartościowe (sekurytyzacja) i sprzedawano na całym świecie, często z wysokimi ocenami ratingowymi. Instytucje finansowe miały dużą dźwignię. Gdy ceny domów zaczęły spadać, rosły niespłacane kredyty i straty."),
          K("Przebieg",
            "W 2007 r. zamarł rynek międzybankowy. We wrześniu 2008 r. upadł bank inwestycyjny Lehman Brothers, a ubezpieczyciel AIG wymagał ratunku – zaufanie między bankami znikło, kredyt się skurczył, a światowa gospodarka weszła w recesję w 2009 r."),
          W("Jak sekurytyzacja przyczyniła się do kryzysu?",
            "Rozproszyła ryzyko kredytów subprime po całym świecie i osłabiła staranność ich udzielania", "Zmniejszyła ilość kredytów", "Zakazała handlu obligacjami",
            why="Banki udzielające kredytów szybko je sprzedawały."),
          K("Działania ratunkowe",
            "Bailout – dokapitalizowanie banków przez państwo (np. program TARP w USA); gwarancje dla banków; obniżki stóp prawie do zera i luzowanie ilościowe – zakupy obligacji przez banki centralne; w Polsce pakiet zaufania NBP (2008) – operacje dostarczające bankom płynności."),
          K("Reformy po kryzysie",
            "Bazylea III (więcej i lepszego kapitału, wymogi płynności), nadzór makroostrożnościowy (ESRB, w Polsce KSF), unia bankowa w strefie euro i reguły bail-in (straty ponoszą najpierw właściciele i wierzyciele banku), przekształcenie FSF w Radę Stabilności Finansowej (2009)."),
          PF("Bail-in oznacza, że straty banku w pierwszej kolejności pokrywają podatnicy.", False,
             why="Bail-in obciąża akcjonariuszy i wierzycieli banku, a nie podatników."),
      ],
      mech=[
          LN("Ułóż przebieg kryzysu subprime.",
             ["Ceny domów w USA szybko rosną", "Banki udzielają ryzykownych kredytów i je sekurytyzują", "Ceny domów zaczynają spadać", "Rosną niespłacane kredyty i straty na papierach", "Upadek Lehman Brothers i zamrożenie rynku międzybankowego"],
             why="Główne etapy kryzysu 2007–2008."),
          KT("Działanie ratunkowe czy reforma po kryzysie?",
             {"Działanie ratunkowe": ["Dokapitalizowanie banków przez państwo", "Luzowanie ilościowe", "Pakiet zaufania NBP"],
              "Reforma po kryzysie": ["Bazylea III", "Utworzenie ESRB", "Unia bankowa w strefie euro"]},
             why="Najpierw gaszenie pożaru, potem nowe reguły."),
          W("Co oznacza luzowanie ilościowe (QE)?",
            "Zakupy obligacji przez bank centralny w celu obniżenia długoterminowych stóp", "Podwyżkę stóp procentowych", "Sprzedaż rezerw walutowych",
            why="Bank centralny powiększa bilans, kupując aktywa."),
          W("Czemu służył pakiet zaufania NBP?",
            "Zapewnieniu bankom płynności przy zamarłym rynku międzybankowym", "Podwyżce stóp", "Wymianie złotego na euro",
            why="Banki przestały sobie ufać i pożyczać."),
          M("Które elementy wprowadzono jako reformy po kryzysie?",
            ["Wyższe wymogi kapitałowe Bazylei III", "Nadzór makroostrożnościowy", "Reguły bail-in", "Zniesienie nadzoru bankowego"], [0, 1, 2],
            why="Nadzór wzmocniono, a nie zniesiono."),
          PF("Upadek Lehman Brothers nastąpił we wrześniu 2008 r.", True,
             why="15 września 2008 r. bank złożył wniosek o upadłość."),
      ],
      calc=[
          LB("Bank z dźwignią 30 (aktywa 30 razy kapitał) traci 4% aktywów. Ile procent kapitału traci?",
             120, "30*4", ["30 · 4% = 120% – bank jest niewypłacalny"], unit="%"),
          LB("Przy dźwigni 10 ta sama strata 4% aktywów to ile procent kapitału?",
             40, "10*4", ["10 · 4% = 40%"], unit="%"),
          LB("Pula kredytów 100 mln USD, 25% przestaje być spłacanych, odzysk z nich 40%. Ile wynosi strata (mln USD)?",
             15, "100*0.25*(1-0.4)", ["25 · 0,6 = 15 mln USD"], unit="mln USD"),
          LB("Bank ma kapitał 10 mld, aktywa ważone ryzykiem 100 mld. Ile wynosi współczynnik kapitałowy (%)?",
             10, "10/100*100", ["10 / 100 = 10%"], unit="%"),
          LB("Bail-in: strata 12 mld, kapitał akcjonariuszy 8 mld. Ile muszą pokryć wierzyciele (mld)?",
             4, "12-8", ["12 − 8 = 4 mld"], unit="mld"),
          LB("Bank centralny kupuje obligacje za 500 mld, bilans wynosił 1 000 mld. O ile procent rośnie bilans?",
             50, "500/1000*100", ["500 / 1 000 = 50%"], unit="%"),
      ],
      case=[
          PR("Jesienią 2008 r. po upadku Lehman Brothers polskie banki przestały pożyczać sobie nawzajem, a stawki rynku międzybankowego wzrosły. NBP ogłosił pakiet zaufania: dodatkowe operacje zasilające banki w płynność i swapy walutowe.",
             W("Dlaczego banki przestały sobie pożyczać?",
               "Obawiały się, że kontrahent może upaść", "Bo miały za dużo kapitału", "Bo stopy były zerowe",
               why="Kryzys zaufania na rynku międzybankowym."),
             W("Jaką rolę pełnił NBP?",
               "Dostarczyciela płynności – pożyczkodawcy ostatniej instancji", "Nadzorcy giełdy", "Emitenta obligacji skarbowych",
               why="Bank centralny zasilił banki w płynność."),
             PF("Polskie banki miały w 2008 r. niewielką ekspozycję na kredyty subprime, więc kryzys dotknął je głównie przez płynność i kurs.", True,
                why="Głównym kanałem był rynek międzybankowy i walutowy."),
          ),
          PR("W 2008 r. rząd USA przeznaczył setki miliardów dolarów na dokapitalizowanie banków, a Fed obniżył stopy prawie do zera i rozpoczął zakupy obligacji. Krytycy ostrzegali przed pokusą nadużycia, a zwolennicy – przed powtórką Wielkiego Kryzysu.",
             W("Jak nazywa się dokapitalizowanie banków przez państwo?",
               "Bailout", "Bail-in", "Seigniorage",
               why="Koszt ponoszą podatnicy."),
             W("Na czym polega zarzut pokusy nadużycia?",
               "Banki, licząc na ratunek, będą w przyszłości bardziej ryzykować", "Banki przestaną udzielać kredytów", "Inflacja spadnie do zera",
               why="Oczekiwanie pomocy zachęca do ryzyka."),
             PF("Reguły bail-in w UE miały ograniczyć koszty ratowania banków dla podatników.", True,
                why="Straty ponoszą najpierw właściciele i wierzyciele."),
          ),
      ]),

    L(5, "Architektura globalnego systemu finansowego",
      "Znać instytucje i reguły globalnego systemu finansowego: MFW, Bank Światowy, BIS i Komitet Bazylejski, Radę Stabilności Finansowej, Solvency II, europejski system nadzoru (EBA, ESMA, EIOPA, ESRB) i mechanizmy strefy euro (EFSF, EFSM, EMS).",
      ["Globalny system finansowy (architektura finansowa)", "Rada Stabilności Finansowej (FSB)", "Europejska Rada ds. Ryzyka Systemowego (ESRB)", "Solvency II", "EFSF i EFSM (tymczasowe mechanizmy strefy euro, 2010)", "Sieć bezpieczeństwa finansowego", "Umowy bazylejskie (Bazylea I, II, III)"],
      [BISF, ESMH, WEFSM, SOLV, ESRB],
      explain=[
          K("Od Bretton Woods do kursów płynnych",
            "System z Bretton Woods (1944) oparł waluty na dolarze wymienialnym na złoto i powołał MFW i Bank Światowy. Po 1971 r. przeważają kursy płynne, a MFW stał się głównie pożyczkodawcą dla krajów w kryzysie, a Bank Światowy – finansuje rozwój."),
          K("Standardy i koordynacja",
            "Bank Rozrachunków Międzynarodowych (BIS) w Bazylei skupia banki centralne; przy nim działa Komitet Bazylejski (normy kapitałowe Bazylea I–III). Rada Stabilności Finansowej (FSB) powstała w kwietniu 2009 r. (G20 w Londynie) z Forum Stabilności Finansowej z 1999 r.; koordynuje reformy regulacji. Dla ubezpieczycieli UE stosuje od 2016 r. Solvency II."),
          W("Z jakiego ciała powstała w 2009 r. Rada Stabilności Finansowej?",
            "Z Forum Stabilności Finansowej", "Z Banku Światowego", "Z Komisji Nadzoru Finansowego",
            why="FSF utworzono w 1999 r., a w 2009 r. przekształcono w FSB."),
          K("Nadzór w UE",
            "Europejski System Nadzoru Finansowego: EBA (banki), ESMA (rynki), EIOPA (ubezpieczenia i emerytury) oraz ESRB (od 16.12.2010) – nadzór makroostrożnościowy nad całym systemem. W strefie euro – unia bankowa: nadzór EBC nad największymi bankami i wspólny mechanizm restrukturyzacji."),
          K("Mechanizmy ratunkowe strefy euro",
            "W 2010 r. utworzono tymczasowe EFSM (do ok. 60 mld euro, gwarancja budżetu UE) i EFSF (do 440 mld euro, gwarancje państw strefy euro); od października 2012 r. nowe programy prowadzi stały Europejski Mechanizm Stabilności (EMS/ESM)."),
          PF("Solvency II reguluje wypłacalność banków komercyjnych.", False,
             why="Dotyczy zakładów ubezpieczeń i reasekuracji; banki regulują normy bazylejskie."),
      ],
      mech=[
          KT("Która instytucja lub regulacja?",
             {"MFW": ["Pożyczki dla krajów w kryzysie bilansu płatniczego", "Nadzór nad polityką gospodarczą członków"],
              "BIS i Komitet Bazylejski": ["Normy kapitałowe dla banków", "Bank banków centralnych"],
              "EIOPA i Solvency II": ["Wymóg kapitałowy SCR zakładów ubezpieczeń", "Nadzór nad ubezpieczycielami w UE"],
              "ESRB": ["Ostrzeżenia przed ryzykiem systemowym w UE", "Nadzór makroostrożnościowy"]},
             why="Elementy architektury finansowej."),
          LN("Ułóż chronologię mechanizmów ratunkowych strefy euro.",
             ["Kryzys zadłużenia Grecji (2010)", "EFSM i EFSF – mechanizmy tymczasowe (2010)", "Pomoc dla Irlandii i Portugalii", "Europejski Mechanizm Stabilności (2012)", "Unia bankowa – nadzór EBC (od 2014)"],
             why="Od rozwiązań doraźnych do stałych."),
          W("Co jest głównym zadaniem ESRB?",
            "Identyfikowanie ryzyka systemowego i wydawanie ostrzeżeń w UE", "Emisja euro", "Nadzór nad pojedynczym bankiem",
            why="To organ makroostrożnościowy."),
          W("Ile wynosi wymóg SCR w Solvency II?",
            "Kapitał pozwalający przetrwać rok z prawdopodobieństwem 99,5%", "10% przychodów", "Równowartość 100 000 euro",
            why="SCR odpowiada ryzyku zdarzenia raz na 200 lat."),
          M("Które instytucje tworzą Europejski System Nadzoru Finansowego?",
            ["EBA", "ESMA", "EIOPA", "MFW"], [0, 1, 2],
            why="MFW to instytucja globalna."),
          PF("EFSF i EFSM były mechanizmami tymczasowymi, zastąpionymi w nowych programach przez EMS.", True,
             why="EMS działa od października 2012 r."),
      ],
      calc=[
          LB("Zakład ubezpieczeń ma środki własne 1,5 mld zł i SCR 1,0 mld zł. Ile wynosi wskaźnik wypłacalności (%)?",
             150, "1.5/1.0*100", ["1,5 / 1,0 = 150%"], unit="%"),
          LB("MCR wynosi 35% SCR. Ile to (mld zł)?",
             0.35, "0.35*1.0", ["0,35 · 1,0 = 0,35 mld zł"], unit="mld zł"),
          LB("Prawdopodobieństwo 99,5% oznacza, że kapitał wystarczy z wyjątkiem zdarzeń występujących średnio raz na ile lat?",
             200, "1/0.005", ["1 / 0,005 = 200 lat"], unit="lat"),
          LB("Bank ma kapitał 12 mld zł i aktywa ważone ryzykiem 120 mld zł. Wymóg łączny 13%. O ile mld zł brakuje kapitału?",
             3.6, "0.13*120-12", ["15,6 − 12 = 3,6 mld zł"], unit="mld zł"),
          LB("EFSF miał zdolność pożyczkową 440 mld euro, EFSM 60 mld euro. Ile razem (mld euro)?",
             500, "440+60", ["440 + 60 = 500 mld euro"], unit="mld euro"),
          LB("FSF powstało w 1999 r., FSB w 2009 r. Ile lat działało FSF?",
             10, "2009-1999", ["2009 − 1999 = 10 lat"], unit="lat"),
      ],
      case=[
          PR("W maju 2010 r. Grecja straciła dostęp do rynku długu. Państwa strefy euro i MFW udzieliły jej pożyczek, a w ciągu kilku tygodni utworzono EFSF i EFSM. Później z ich pomocy korzystały Irlandia i Portugalia, a w 2012 r. powstał stały EMS.",
             W("Dlaczego utworzono nowe mechanizmy?",
               "Traktaty nie przewidywały pomocy dla państw strefy euro w kryzysie zadłużeniowym", "Bo EBC drukował za mało euro", "Bo MFW nie istniał",
               why="Trzeba było szybko stworzyć narzędzia pomocy."),
             W("Jaki problem związany z pomocą podnosili krytycy?",
               "Pokusę nadużycia – państwa mogą mniej dbać o finanse publiczne", "Zbyt niską inflację", "Brak wspólnej waluty",
               why="Pomoc może osłabiać dyscyplinę fiskalną."),
             PF("Pomoc z tych mechanizmów wiązała się z warunkami dostosowawczymi.", True,
                why="Kraje musiały m.in. ograniczać deficyty."),
          ),
          PR("Polski zakład ubezpieczeń wykazuje wskaźnik pokrycia SCR na poziomie 140%. KNF, obserwując ryzyko na rynku nieruchomości, zaleca też bankom dodatkowe bufory kapitałowe, a KSF analizuje ryzyko systemowe.",
             W("Czy wskaźnik 140% spełnia wymóg Solvency II?",
               "Tak – środki własne przekraczają SCR", "Nie – wymóg to 200%", "Nie da się ocenić",
               why="Wymagane jest co najmniej 100% SCR."),
             W("Który organ w Polsce odpowiada za nadzór makroostrożnościowy?",
               "Komitet Stabilności Finansowej", "Rzecznik Finansowy", "UOKiK",
               why="KSF działa na podstawie ustawy z 2015 r."),
             PF("Bufory kapitałowe banków to narzędzie polityki makroostrożnościowej.", True,
                why="Zwiększają odporność systemu na szoki."),
          ),
      ]),
]
