# -*- coding: utf-8 -*-
# Zrozumienie – Podstawy finansów / Pieniądz i jego funkcje
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-08"
S271 = S("OpenStax, Principles of Economics 3e, 27.1 Defining Money by Its Functions", OS3 + "27-1-defining-money-by-its-functions", D)
S272 = S("OpenStax, Principles of Economics 3e, 27.2 Measuring Money: Currency, M1, and M2", OS3 + "27-2-measuring-money-currency-m1-and-m2", D)
S274 = S("OpenStax, Principles of Economics 3e, 27.4 How Banks Create Money", OS3 + "27-4-how-banks-create-money", D)
NBPE = S("NBP – edukacja ekonomiczna", "https://nbp.pl/edukacja/", D)
NBPBM = S("NBP – banknoty i monety", "https://nbp.pl/banknoty-i-monety/", D)
NBPST = S("NBP – statystyka monetarna i finansowa", "https://nbp.pl/statystyka-i-sprawozdawczosc/statystyka-monetarna-i-finansowa/", D)
ECBDE = S("Europejski Bank Centralny – cyfrowe euro", "https://www.ecb.europa.eu/euro/digital_euro/html/index.pl.html", D)
BTC = S("S. Nakamoto, Bitcoin: A Peer-to-Peer Electronic Cash System (2008)", "https://bitcoin.org/bitcoin.pdf", D)

XECBE = S("EBC – Historia unii gospodarczej i walutowej (etapy UGW)", "https://www.ecb.europa.eu/ecb/history-arts-culture/history/emu/html/index.pl.html", D)
XDEL = S("Jacques Delors Centre – 25 years after the Delors Report", "https://www.delorscentre.eu/en/publications/detail/publication/25-years-after-the-delors-report", D)

LESSONS = [
    L(1, "Funkcje i formy pieniądza",
      "Rozumieć, dlaczego pieniądz ułatwia wymianę, rozpoznawać jego funkcje i formy (od towarowego do fiducjarnego) oraz wyjaśniać prawo Kopernika–Greshama i tezauryzację.",
      ["Pieniądz", "Pieniądz towarowy, kruszcowy i fiducjarny", "Prawo Kopernika–Greshama", "Tezauryzacja", "Siła nabywcza pieniądza"],
      [S271, NBPE],
      explain=[
          K("Problem barteru",
            "W wymianie barterowej potrzebna jest podwójna zgodność potrzeb: szewc, który chce chleba, musi znaleźć piekarza potrzebującego butów. Przy n towarach trzeba znać n(n−1)/2 cen względnych. Pieniądz – powszechnie akceptowany środek wymiany – usuwa oba problemy: wszystko wyceniamy w jednej jednostce.",
            w="liczba cen w barterze = n(n − 1) / 2"),
          K("Funkcje pieniądza",
            "Środek wymiany (płacimy nim za dobra), miernik wartości (jednostka rozrachunkowa – ceny w złotych), środek tezauryzacji (przechowywania wartości) i środek płatniczy (regulowanie zobowiązań odroczonych, np. podatków, rat). Pieniądz międzynarodowy pełni te funkcje w rozliczeniach między krajami."),
          W("Porównujesz ceny dwóch telefonów w złotych. Którą funkcję pełni pieniądz?",
            "Miernika wartości", "Środka wymiany", "Środka tezauryzacji",
            why="Wyrażenie wartości w jednej jednostce to funkcja miernika."),
          K("Od towaru do zaufania",
            "Pieniądz towarowy ma wartość jako towar (bydło, sól, muszle). Kruszcowy – złote i srebrne monety, wartość kruszcu ≈ wartość nominalna. Później banknoty wymienialne na złoto. Dziś pieniądz jest fiducjarny (dekretowy): nie ma pokrycia w kruszcu, a jego wartość wynika z zaufania i z tego, że państwo przyjmuje go w podatkach i nadaje mu status prawnego środka płatniczego."),
          K("Prawo Kopernika–Greshama i tezauryzacja",
            "„Pieniądz gorszy wypiera z obiegu pieniądz lepszy”: gdy w obiegu są monety o tej samej wartości nominalnej, lecz różnej zawartości kruszcu, ludzie płacą gorszymi, a lepsze chowają (tezauryzują) lub przetapiają. Kopernik opisał to w traktacie o monecie (1526), Gresham – w XVI w. w Anglii."),
          PF("Wartość współczesnego złotego wynika z zaufania do NBP i państwa, a nie z rezerw złota.", True,
             why="To pieniądz fiducjarny, niewymienialny na złoto."),
      ],
      mech=[
          KT("Jaką funkcję pełni pieniądz?",
             {"Środek wymiany": ["Płacisz za bilet do kina", "Kupujesz chleb w piekarni"],
              "Miernik wartości": ["Sklep podaje cenę w złotych", "Porównujesz pensje w dwóch ofertach pracy"],
              "Środek tezauryzacji": ["Odkładasz gotówkę na wakacje", "Trzymasz oszczędności na rachunku"],
              "Środek płatniczy": ["Płacisz zaległy podatek", "Spłacasz ratę kredytu"]},
             why="Każda czynność wykorzystuje inną cechę pieniądza."),
          LN("Ułóż ewolucję form pieniądza.",
             ["Wymiana barterowa", "Pieniądz towarowy (bydło, sól)", "Monety kruszcowe", "Banknoty wymienialne na złoto", "Pieniądz fiducjarny i bezgotówkowy"],
             why="Kolejne formy obniżały koszty wymiany i przechowywania."),
          W("Król obniża zawartość srebra w nowych monetach, ale stare i nowe mają tę samą wartość nominalną. Co się stanie?",
            "Stare monety znikną z obiegu – ludzie je zatrzymają", "Nowe monety znikną z obiegu", "Obie będą krążyć jednakowo",
            why="Prawo Kopernika–Greshama: gorszy pieniądz wypiera lepszy."),
          W("W kraju panuje inflacja 200% rocznie. Która funkcja pieniądza jest najbardziej zagrożona?",
            "Środek tezauryzacji", "Środek wymiany w najbliższej godzinie", "Jednostka rozrachunkowa w obcych krajach",
            why="Przechowywanie pieniądza przy wysokiej inflacji niszczy jego wartość."),
          M("Jakie cechy powinien mieć dobry pieniądz?",
            ["Powszechna akceptowalność", "Podzielność", "Trwałość", "Łatwa możliwość podrobienia"], [0, 1, 2],
            why="Łatwość podrabiania niszczy zaufanie do pieniądza."),
          PF("W czasie hiperinflacji ludzie często wracają do waluty obcej lub barteru.", True,
             why="Krajowy pieniądz przestaje pełnić swoje funkcje."),
      ],
      calc=[
          LB("Gospodarka barterowa ma 10 towarów. Ile cen względnych trzeba znać?",
             45, "10*9/2", ["10 · 9 / 2 = 45"], unit="cen"),
          LB("Ile cen względnych przy 100 towarach w barterze?",
             4950, "100*99/2", ["100 · 99 / 2 = 4950"], unit="cen"),
          LB("Ile cen trzeba znać przy 100 towarach, gdy jest pieniądz (cena każdego towaru w pieniądzu)?",
             100, "100", ["Jedna cena dla każdego towaru: 100"], unit="cen"),
          LB("Ceny wzrosły o 25%. O ile procent spadła siła nabywcza pieniądza?",
             20, "(1-1/1.25)*100", ["1 / 1,25 = 0,8", "Spadek o 20%"], unit="%"),
          LB("Inflacja 5% rocznie przez 3 lata. Ile wynosi siła nabywcza 1000 zł po 3 latach (w cenach początkowych, zł)?",
             863.84, "1000/1.05**3", ["1000 / 1,05³ ≈ 863,84 zł"], unit="zł", tol=0.01),
          LB("Moneta zawiera srebro warte 4 zł, a jej wartość nominalna to 5 zł. Ile wynosi różnica (zł) dla emitenta przy biciu monety (pomijając koszty)?",
             1, "5-4", ["5 − 4 = 1 zł"], unit="zł"),
      ],
      case=[
          PR("W XVI-wiecznych Prusach Królewskich krążyły monety o tej samej wartości nominalnej, ale różnej zawartości srebra – starsze były lepsze, nowsze psute. Mikołaj Kopernik zauważył, że w obiegu zostawały głównie nowe monety.",
             W("Co działo się ze starymi, lepszymi monetami?",
               "Były tezauryzowane lub przetapiane", "Wypierały nowe monety", "Traciły wartość",
               why="Opłacało się je zatrzymać lub przetopić, bo zawierały więcej srebra."),
             W("Co zalecał Kopernik w traktacie o monecie?",
               "Bić monetę o stałej, rzetelnej zawartości kruszcu", "Zwiększyć emisję monet psutych", "Wprowadzić pieniądz papierowy",
               why="Psucie monety prowadzi do drożyzny i utraty zaufania."),
             PF("Prawo Kopernika–Greshama działa, gdy obie monety mają ustaloną tę samą wartość nominalną.", True,
                why="Gdyby lepsza moneta mogła mieć wyższy kurs, nikt nie musiałby jej chować."),
          ),
          PR("W Zimbabwe w 2008 r. hiperinflacja sięgnęła miliardów procent rocznie. Bank centralny wyemitował banknot o nominale 100 bilionów dolarów zimbabweńskich. Ludzie zaczęli używać dolarów amerykańskich i randów.",
             W("Dlaczego ludzie przestali używać krajowej waluty?",
               "Przestała pełnić funkcję środka tezauryzacji i miernika wartości", "Banknoty były za duże", "Zakazał tego rząd",
               why="Ceny zmieniały się tak szybko, że pieniądz tracił wartość z dnia na dzień."),
             W("Co jest źródłem wartości pieniądza fiducjarnego, które tu zostało zniszczone?",
               "Zaufanie do emitenta", "Rezerwy złota", "Wielkość banknotów",
               why="Bez zaufania pieniądz fiducjarny nie ma wartości."),
             PF("Korzystanie z dolarów zamiast krajowej waluty nazywa się dolaryzacją.", True,
                why="Zastąpienie waluty krajowej dolarem w obiegu to dolaryzacja."),
          ),
      ]),

    L(2, "Emisja, denominacja, dewaluacja i renta emisyjna",
      "Rozumieć, kto i jak emituje pieniądz w Polsce, czym różnią się denominacja i dewaluacja, skąd bierze się renta emisyjna oraz liczyć kursy krzyżowe.",
      ["Emisja banknotów i monet w Polsce", "Denominacja", "Dewaluacja i rewaluacja", "Seigniorage (renta emisyjna)", "Kurs krzyżowy", "Monety kolekcjonerskie i obiegowe okolicznościowe", "Pieniądz gotówkowy i bezgotówkowy (bankowy)"],
      [NBPBM, NBPE],
      explain=[
          K("Kto emituje złotego",
            "Wyłączne prawo emisji znaków pieniężnych ma NBP (art. 227 Konstytucji). Banknoty drukuje Polska Wytwórnia Papierów Wartościowych, a monety bije Mennica Polska – na zlecenie NBP. NBP emituje też monety kolekcjonerskie (prawny środek płatniczy po wartości nominalnej, choć sprzedawane drożej) i obiegowe okolicznościowe."),
          K("Denominacja",
            "Denominacja to zmiana nominału pieniądza – skreślenie zer – bez zmiany jego realnej wartości. 1 stycznia 1995 r. w Polsce 10 000 starych złotych zastąpiono 1 nowym złotym. Ceny, płace i oszczędności podzielono przez 10 000, więc nikt nie stracił ani nie zyskał – zmieniła się tylko „miarka”.",
            w="nowa kwota = stara kwota / 10 000"),
          W("Przed denominacją bochenek chleba kosztował 12 000 zł. Ile kosztował po 1.01.1995 r.?",
            "1,20 zł", "12 zł", "0,12 zł",
            why="12 000 / 10 000 = 1,20 zł."),
          K("Dewaluacja i rewaluacja",
            "Przy kursie stałym dewaluacja to urzędowe obniżenie wartości waluty krajowej wobec obcych (więcej złotych za euro), a rewaluacja – podwyższenie. Dewaluacja zmienia realną wartość pieniądza wobec zagranicy: tanieje eksport, drożeje import. Przy kursie płynnym mówimy o deprecjacji i aprecjacji."),
          K("Renta emisyjna i kurs krzyżowy",
            "Seigniorage to dochód emitenta z tego, że wytworzenie pieniądza kosztuje mniej niż jego wartość nominalna; w szerszym ujęciu – dochód z aktywów kupionych za wyemitowany pieniądz. Zysk NBP w dużej części trafia do budżetu państwa. Kurs krzyżowy wylicza się z dwóch kursów wobec trzeciej waluty: EUR/USD = (PLN za EUR) / (PLN za USD).",
            w="kurs krzyżowy A/B = (PLN/A) / (PLN/B)"),
          PF("Denominacja zmniejsza realną wartość oszczędności.", False,
             why="Zmienia się tylko liczba zer – ceny i oszczędności dzieli się przez tę samą liczbę."),
      ],
      mech=[
          KT("Denominacja czy dewaluacja?",
             {"Denominacja": ["Skreślenie czterech zer w 1995 r.", "Zamiana 1000 starych jednostek na 1 nową bez zmiany cen realnych"],
              "Dewaluacja": ["Bank centralny ustala, że za 1 USD płaci się 5 zamiast 4 jednostek", "Urzędowe obniżenie parytetu waluty wobec koszyka"]},
             why="Denominacja jest neutralna, dewaluacja zmienia relację do walut obcych."),
          LN("Ułóż skutki dewaluacji waluty krajowej.",
             ["Bank centralny obniża urzędowy kurs waluty krajowej", "Za 1 euro trzeba płacić więcej złotych", "Towary krajowe są tańsze dla zagranicy", "Eksport rośnie, a import drożeje", "Poprawia się saldo handlowe, ale rośnie inflacja z importu"],
             why="Efekt cenowy działa przez kurs walutowy."),
          W("Kto bije polskie monety obiegowe?",
            "Mennica Polska na zlecenie NBP", "Ministerstwo Finansów", "Banki komercyjne",
            why="NBP jest emitentem, a Mennica Polska wykonawcą."),
          W("Moneta kolekcjonerska o nominale 20 zł kosztuje u NBP 200 zł. Za ile możesz nią zapłacić w sklepie?",
            "Za 20 zł – wartość nominalną", "Za 200 zł", "Nie można nią płacić",
            why="Jest prawnym środkiem płatniczym po wartości nominalnej."),
          M("Które zdania o rencie emisyjnej są prawdziwe?",
            ["Wynika z różnicy między wartością nominalną a kosztem wytworzenia pieniądza", "Zwiększa się przy większej emisji pieniądza bazowego", "Jest podatkiem płaconym przez NBP bankom komercyjnym", "Nadmierne korzystanie z niej grozi inflacją"], [0, 1, 3],
            why="Nadmierna emisja finansująca państwo to „podatek inflacyjny”."),
          PF("Przy kursie płynnym spadek wartości złotego nazywamy deprecjacją, a nie dewaluacją.", True,
             why="Dewaluacja to decyzja władz przy kursie stałym."),
      ],
      calc=[
          LB("Pensja 8 500 000 starych złotych w 1994 r. Ile to nowych złotych po denominacji?",
             850, "8500000/10000", ["8 500 000 / 10 000 = 850 zł"], unit="zł"),
          LB("Kurs: 1 EUR = 4,25 zł, 1 USD = 3,70 zł. Ile wynosi kurs krzyżowy EUR/USD?",
             1.1486, "4.25/3.70", ["4,25 / 3,70 ≈ 1,1486"], unit="USD", tol=0.001),
          LB("Kurs: 1 EUR = 4,25 zł, 1 CHF = 4,50 zł. Ile franków kosztuje 1 euro?",
             0.9444, "4.25/4.50", ["4,25 / 4,50 ≈ 0,9444"], unit="CHF", tol=0.001),
          LB("Dewaluacja z 4,00 do 4,60 zł za 1 USD. O ile procent wzrosła cena dolara w złotych?",
             15, "(4.6/4-1)*100", ["4,60 / 4,00 − 1 = 15%"], unit="%"),
          LB("Banknot 100 zł kosztuje w produkcji 0,40 zł. Ile wynosi seigniorage od 1 mln takich banknotów (mln zł)?",
             99.6, "(100-0.4)*1e6/1e6", ["(100 − 0,40) · 1 000 000 = 99,6 mln zł"], unit="mln zł", tol=0.01),
          LB("Towar eksportowy kosztuje 100 USD. Po dewaluacji z 4,00 do 4,60 zł/USD eksporter dostaje za niego ile złotych więcej?",
             60, "100*(4.6-4.0)", ["100 · 0,60 = 60 zł"], unit="zł"),
      ],
      case=[
          PR("Pod koniec 1994 r. w Polsce ceny liczone były w setkach tysięcy i milionach złotych. 1.01.1995 r. przeprowadzono denominację (10 000 : 1). Przez pewien czas w obiegu były stare i nowe banknoty, a ceny podawano w obu walutach.",
             W("Po co przeprowadzono denominację?",
               "Dla wygody rozliczeń i symbolicznego zakończenia wysokiej inflacji", "By obniżyć realne płace", "By zwiększyć rezerwy NBP",
               why="Długie kwoty utrudniały liczenie i księgowość."),
             W("Mieszkanie warte 1,5 mld starych zł – ile było warte w nowych złotych?",
               "150 000 zł", "1500 zł", "15 000 zł",
               why="1 500 000 000 / 10 000 = 150 000 zł."),
             PF("Sama denominacja nie obniża inflacji – potrzebna jest odpowiednia polityka pieniężna i fiskalna.", True,
                why="Denominacja zmienia tylko jednostkę."),
          ),
          PR("Kantor podaje kursy: 1 EUR = 4,26 zł, 1 GBP = 4,95 zł, 1 USD = 3,68 zł (dane umowne). Turysta wraca z Londynu z funtami i chce wymienić je na euro przez złotego.",
             W("Ile euro dostanie za 100 GBP (pomijając marżę)?",
               "Ok. 116,20 EUR", "Ok. 86,06 EUR", "Ok. 134,51 EUR",
               why="100 · 4,95 / 4,26 ≈ 116,20 EUR."),
             W("Ile wynosi kurs krzyżowy GBP/USD?",
               "Ok. 1,345", "Ok. 0,743", "Ok. 1,157",
               why="4,95 / 3,68 ≈ 1,345 USD za 1 GBP."),
             PF("Wymiana przez złotego oznacza w praktyce dwa spready kantoru.", True,
                why="Kantor zarabia na różnicy kursów kupna i sprzedaży przy każdej transakcji."),
          ),
      ]),

    L(3, "Agregaty pieniężne i kreacja pieniądza",
      "Odróżniać bazę monetarną od agregatów M1–M3, rozumieć, jak banki komercyjne tworzą pieniądz w systemie rezerwy cząstkowej, i liczyć mnożnik kreacji pieniądza.",
      ["Agregaty pieniężne (NBP)", "Baza monetarna (M0, pieniądz wielkiej mocy)", "Kreacja pieniądza (system rezerwy cząstkowej)", "Mnożnik kreacji pieniądza", "Pieniądz bankowy a gotówka w strukturze M3", "Gotówka w obiegu"],
      [S272, S274, NBPST],
      explain=[
          K("Baza monetarna i agregaty",
            "Baza monetarna (M0, pieniądz wielkiej mocy) to pieniądz banku centralnego: gotówka w obiegu i w kasach banków oraz rezerwy banków na rachunkach w NBP. Agregaty mierzą pieniądz w gospodarce: M1 – gotówka w obiegu i depozyty bieżące (a vista); M2 – M1 + depozyty terminowe do 2 lat; M3 – M2 + instrumenty rynkowe (np. operacje z przyrzeczeniem odkupu, dłużne papiery do 2 lat)."),
          K("Jak bank tworzy pieniądz",
            "Bank musi trzymać tylko część depozytów jako rezerwę (rezerwa obowiązkowa i nadwyżkowa), resztę może pożyczyć. Kredyt trafia na rachunek kredytobiorcy jako nowy depozyt – powstaje nowy pieniądz bankowy. Ten depozyt znów może być w części pożyczony. Dlatego większość pieniądza M3 to pieniądz bankowy, a nie gotówka."),
          W("Klient wpłaca 1000 zł gotówki, stopa rezerwy 10%. Ile bank może najwyżej pożyczyć od razu?",
            "900 zł", "1000 zł", "100 zł",
            why="Musi zatrzymać 10% = 100 zł jako rezerwę."),
          K("Mnożnik kreacji",
            "W uproszczonym modelu (cała kwota zostaje w bankach) maksymalny przyrost depozytów = początkowa rezerwa nadwyżkowa × 1/r. Gdy ludzie trzymają część pieniędzy w gotówce (wskaźnik c = gotówka/depozyty), mnożnik pieniężny wynosi m = (1 + c)/(r + c) i jest mniejszy. M = m · M0.",
            w="m = 1 / r;   m = (1 + c) / (r + c);   M = m · M0"),
          K("Gotówka a pieniądz bankowy w M3",
            "W rozwiniętych gospodarkach gotówka stanowi tylko kilkanaście procent M3 – reszta to depozyty, czyli pieniądz stworzony przez banki. Bank centralny kontroluje bazę monetarną bezpośrednio, ale M3 tylko pośrednio: przez stopy procentowe, rezerwę obowiązkową i wpływ na skłonność banków do kredytowania. Dane o agregatach NBP publikuje co miesiąc."),
          PF("Wzrost skłonności ludzi do trzymania gotówki zmniejsza mnożnik kreacji pieniądza.", True,
             why="Gotówka „wycieka” z systemu bankowego i nie może być pożyczona dalej."),
      ],
      mech=[
          LN("Ułóż proces kreacji pieniądza bankowego.",
             ["Klient wpłaca gotówkę do banku A", "Bank A zatrzymuje część jako rezerwę i udziela kredytu", "Kredytobiorca płaci firmie, która wpłaca pieniądze do banku B", "Bank B zatrzymuje rezerwę i znów pożycza resztę", "Suma depozytów w systemie wielokrotnie przewyższa pierwszą wpłatę"],
             why="Każda runda tworzy nowe depozyty, coraz mniejsze."),
          KT("Gdzie należy dany składnik?",
             {"Baza monetarna (M0)": ["Rezerwy banków na rachunkach w NBP", "Gotówka w kasach banków"],
              "M1 (poza M0)": ["Środki na rachunku bieżącym (ROR)", "Depozyty a vista firm"],
              "M2 (poza M1)": ["Lokata terminowa na 6 miesięcy", "Lokata roczna"],
              "M3 (poza M2)": ["Operacje z przyrzeczeniem odkupu (repo)", "Dłużne papiery wartościowe banków do 2 lat"]},
             why="Agregaty są coraz szersze i coraz mniej płynne."),
          W("NBP podnosi stopę rezerwy obowiązkowej. Co dzieje się z możliwością kreacji pieniądza?",
            "Maleje", "Rośnie", "Nie zmienia się",
            why="Większa część depozytów musi pozostać w rezerwie, mnożnik spada."),
          W("Ludzie w obawie przed kryzysem masowo wypłacają gotówkę z banków. Co z podażą pieniądza M3?",
            "Spada, bo banki muszą ograniczyć kredyty", "Rośnie, bo jest więcej gotówki", "Nie zmienia się",
            why="Rośnie c, maleje mnożnik, banki tracą rezerwy."),
          M("Które pozycje są pieniądzem wielkiej mocy, czyli zobowiązaniem NBP?",
            ["Gotówka w obiegu", "Rezerwy banków w banku centralnym", "Depozyty terminowe gospodarstw domowych", "Gotówka w kasach banków"], [0, 1, 3],
            why="Depozyty terminowe to pieniądz bankowy, nie pieniądz banku centralnego."),
          PF("Przelew z mojego rachunku na rachunek sklepu w innym banku nie zmienia ilości pieniądza M1 w gospodarce.", True,
             why="Pieniądz zmienia tylko właściciela i bank."),
      ],
      calc=[
          LB("Stopa rezerwy 5%, brak gotówki w obiegu poza bankami. Ile wynosi prosty mnożnik kreacji?",
             20, "1/0.05", ["1 / 0,05 = 20"], unit=""),
          LB("Nowa rezerwa nadwyżkowa 10 mln zł, stopa rezerwy 5%. Ile wynosi maksymalny przyrost depozytów (mln zł)?",
             200, "10/0.05", ["10 · 20 = 200 mln zł"], unit="mln zł"),
          LB("r = 4%, c = 0,16 (gotówka/depozyty). Ile wynosi mnożnik pieniężny m = (1 + c)/(r + c)?",
             5.8, "(1+0.16)/(0.04+0.16)", ["1,16 / 0,20 = 5,8"], unit="", tol=0.01),
          LB("Baza monetarna 500 mld zł, mnożnik 5,8. Ile wynosi podaż pieniądza (mld zł)?",
             2900, "500*5.8", ["500 · 5,8 = 2900 mld zł"], unit="mld zł"),
          LB("M3 = 2800 mld zł, gotówka w obiegu 420 mld zł (dane umowne). Jaki procent M3 to gotówka?",
             15, "420/2800*100", ["420 / 2800 = 15%"], unit="%"),
          LB("Pierwsza wpłata 1000 zł, stopa rezerwy 20%. Ile wyniesie depozyt w trzecim banku w łańcuchu (zł)?",
             640, "1000*0.8**2", ["Bank 1: 1000", "Bank 2: 800", "Bank 3: 640 zł"], unit="zł"),
      ],
      case=[
          PR("W marcu 2020 r., na początku pandemii, Polacy masowo wypłacali gotówkę z bankomatów. Wartość gotówki w obiegu w ciągu kilku tygodni wyraźnie wzrosła. NBP zapewnił bankom płynność i obniżył stopę rezerwy obowiązkowej.",
             W("Jak masowe wypłaty działały na mnożnik kreacji?",
               "Zmniejszały go – rósł udział gotówki", "Zwiększały go", "Nie miały wpływu",
               why="Wzrost c obniża m = (1 + c)/(r + c)."),
             W("Po co NBP obniżył stopę rezerwy obowiązkowej?",
               "By uwolnić płynność bankom i podtrzymać akcję kredytową", "By zmniejszyć podaż pieniądza", "By ograniczyć wypłaty gotówki",
               why="Niższa rezerwa zwiększa środki, którymi banki mogą dysponować."),
             PF("Gotówka wypłacona z banku nadal należy do agregatu M1.", True,
                why="Gotówka w obiegu jest częścią M1 – zmienia się struktura, nie przynależność."),
          ),
          PR("Bank ma depozyty 1000 mln zł, stopa rezerwy obowiązkowej wynosi 3,5% (dane umowne), a bank trzyma dodatkowo 1,5% jako rezerwę nadwyżkową na bieżące wypłaty.",
             W("Ile wynosi łączna rezerwa?",
               "50 mln zł", "35 mln zł", "15 mln zł",
               why="(3,5% + 1,5%) · 1000 = 50 mln zł."),
             W("Ile bank może przeznaczyć na kredyty i inne aktywa?",
               "950 mln zł", "965 mln zł", "1000 mln zł",
               why="1000 − 50 = 950 mln zł."),
             PF("Utrzymywanie rezerw nadwyżkowych obniża faktyczny mnożnik poniżej 1/r.", True,
                why="Część środków, która mogłaby być pożyczona, zostaje w rezerwie."),
          ),
      ]),

    L(4, "Popyt na pieniądz i stopy procentowe",
      "Rozumieć motywy trzymania pieniądza (preferencja płynności), zależność popytu na pieniądz od dochodu i stopy procentowej, odróżniać stopę nominalną od realnej i wyjaśniać pojęcie naturalnej stopy procentowej.",
      ["Popyt na pieniądz (preferencja płynności)", "Stopa procentowa nominalna i realna", "Naturalna (neutralna) stopa procentowa", "Siła nabywcza pieniądza"],
      [S272, NBPE],
      explain=[
          K("Trzy motywy Keynesa",
            "Ludzie trzymają pieniądz (zamiast obligacji) z motywu transakcyjnego – na bieżące zakupy, przezornościowego – na nieprzewidziane wydatki, i spekulacyjnego – czekając na lepsze okazje inwestycyjne. Dwa pierwsze rosną z dochodem, trzeci maleje, gdy stopa procentowa rośnie."),
          K("Koszt trzymania pieniądza",
            "Gotówka i rachunek bieżący nie dają (prawie) odsetek. Kosztem alternatywnym trzymania pieniądza jest więc nominalna stopa procentowa, którą można by zarobić na obligacjach. Gdy stopy rosną, ludzie ograniczają zasoby pieniądza – krzywa popytu na pieniądz MD opada względem stopy procentowej i przesuwa się w prawo, gdy rośnie dochód lub poziom cen.",
            g=G("pieniadz")),
          W("Stopa procentowa rośnie z 2% do 6%. Co dzieje się z ilością pieniądza, jaką ludzie chcą trzymać?",
            "Maleje – ruch wzdłuż krzywej MD", "Rośnie", "Krzywa MD przesuwa się w prawo",
            why="Wyższy koszt alternatywny zniechęca do trzymania pieniądza."),
          K("Stopa nominalna i realna",
            "Nominalna to stopa zapisana w umowie. Realna mierzy przyrost siły nabywczej: w przybliżeniu r ≈ i − π, dokładnie (1 + r) = (1 + i)/(1 + π) (równanie Fishera). Ujemna stopa realna oznacza, że oszczędności tracą wartość, choć rośnie ich nominalna kwota.",
            w="1 + r = (1 + i) / (1 + π);  r ≈ i − π"),
          K("Naturalna stopa procentowa",
            "Wicksell nazwał naturalną stopę taką, przy której oszczędności równają się inwestycjom, a gospodarka działa przy potencjalnym PKB i stabilnej inflacji. Współcześnie mówi się o stopie neutralnej (r*): polityka pieniężna jest restrykcyjna, gdy realna stopa banku centralnego przekracza r*, i łagodna, gdy jest niższa. r* nie da się bezpośrednio zaobserwować – szacuje się ją modelami."),
          PF("Gdy realna stopa procentowa jest ujemna, odkładanie gotówki w skarpecie zmniejsza jej siłę nabywczą.", True,
             why="Inflacja przewyższa oprocentowanie (a gotówka ma oprocentowanie zero)."),
      ],
      mech=[
          WY("Rośnie dochód narodowy. Jak przesuwa się krzywa popytu na pieniądz?",
             G("pieniadz", MD=1), "W prawo – potrzeba więcej pieniądza na transakcje", "W lewo", "Nie przesuwa się",
             why="Motyw transakcyjny rośnie z dochodem."),
          WY("Upowszechniają się płatności telefonem i karty – ludzie trzymają mniej gotówki przy tym samym dochodzie. Co z krzywą MD?",
             G("pieniadz", MD=-1), "Przesuwa się w lewo", "Przesuwa się w prawo", "Ruch wzdłuż krzywej",
             why="Innowacje płatnicze zmniejszają popyt na pieniądz przy każdej stopie."),
          WY("Bank centralny zwiększa podaż pieniądza przy niezmienionym popycie. Co ze stopą procentową?",
             G("pieniadz", MS=1), "Spada", "Rośnie", "Nie zmienia się",
             why="Przy większej podaży równowaga przesuwa się w dół krzywej MD."),
          LN("Ułóż mechanizm: wyższa inflacja → wyższe stopy nominalne (efekt Fishera).",
             ["Ludzie oczekują wyższej inflacji", "Pożyczkodawcy chcą zachować realny zwrot", "Żądają wyższej nominalnej stopy procentowej", "Kredytobiorcy akceptują ją, bo spłacą dług „tańszym” pieniądzem", "Nominalne stopy rosną mniej więcej o wzrost oczekiwanej inflacji"],
             why="Stopa realna pozostaje względnie stała, rośnie nominalna."),
          KT("Polityka pieniężna restrykcyjna czy łagodna? (r* = 1%)",
             {"Restrykcyjna": ["Stopa NBP 6%, oczekiwana inflacja 3%", "Stopa 4%, inflacja 1,5%"],
              "Łagodna": ["Stopa 2%, inflacja 4%", "Stopa 0,1%, inflacja 3%"]},
             why="Porównujemy realną stopę (i − π) z r* = 1%."),
          PF("Ruch wzdłuż krzywej MD następuje przy zmianie stopy procentowej, a przesunięcie – przy zmianie dochodu lub cen.", True,
             why="Stopa procentowa jest na osi wykresu, inne czynniki przesuwają krzywą."),
      ],
      calc=[
          LB("Lokata 6%, inflacja 4%. Ile wynosi dokładna realna stopa procentowa (%)?",
             1.92, "(1.06/1.04-1)*100", ["1,06 / 1,04 − 1 ≈ 1,92%"], unit="%", tol=0.02),
          LB("Lokata 3%, inflacja 8%. Ile wynosi przybliżona realna stopa procentowa (%)? (ujemna ze znakiem minus)",
             -5, "3-8", ["3% − 8% = −5%"], unit="%"),
          LB("Inwestor chce realnie 2%, oczekiwana inflacja 5%. Jakiej nominalnej stopy zażąda (dokładnie, %)?",
             7.1, "(1.02*1.05-1)*100", ["1,02 · 1,05 − 1 = 7,1%"], unit="%", tol=0.01),
          LB("Trzymasz 10 000 zł w gotówce, a obligacje dają 5,5%. Ile wynosi roczny koszt alternatywny (zł)?",
             550, "10000*0.055", ["10 000 · 5,5% = 550 zł"], unit="zł"),
          LB("Stopa referencyjna 3,75%, oczekiwana inflacja 2,5%. Ile wynosi realna stopa banku centralnego (przybliżenie, pkt proc.)?",
             1.25, "3.75-2.5", ["3,75 − 2,5 = 1,25 pkt proc."], unit="pkt proc.", tol=0.01),
          LB("Oszczędności 50 000 zł na koncie 0% przez 2 lata przy inflacji 6% rocznie. Ile wynosi ich realna wartość (zł)?",
             44499.82, "50000/1.06**2", ["50 000 / 1,06² ≈ 44 499,82 zł"], unit="zł", tol=0.01),
      ],
      case=[
          PR("W lutym 2023 r. inflacja CPI w Polsce wyniosła 18,4% r/r, a stopa referencyjna NBP – 6,75%. Najlepsze lokaty dawały ok. 6–7% rocznie (dane w przybliżeniu).",
             W("Ile w przybliżeniu wynosiła realna stopa stopy referencyjnej?",
               "Ujemna, ok. 11,7 pkt proc. poniżej zera", "Dodatnia, ok. 11,7 pkt proc.", "Bliska zera",
               why="6,75 − 18,4 ≈ −11,65."),
             W("Co działo się z siłą nabywczą oszczędności na lokatach?",
               "Spadała mimo dopisywanych odsetek", "Rosła", "Była stała",
               why="Oprocentowanie było znacznie niższe od inflacji."),
             PF("Silnie ujemna realna stopa procentowa sprzyja kredytobiorcom kosztem oszczędzających.", True,
                why="Dług realnie maleje szybciej, niż rosną odsetki."),
          ),
          PR("Ekonomiści banku centralnego szacują, że neutralna realna stopa procentowa (r*) wynosi ok. 1%. Bieżąca stopa banku to 5%, a oczekiwana inflacja 2,5% (dane umowne).",
             W("Ile wynosi realna stopa banku centralnego?",
               "2,5%", "5%", "7,5%",
               why="5% − 2,5% = 2,5%."),
             W("Jaki jest charakter polityki pieniężnej?",
               "Restrykcyjny – realna stopa przekracza r*", "Łagodny", "Neutralny",
               why="Realna stopa 2,5% jest wyższa niż r* = 1%."),
             PF("Oszacowania r* są obarczone dużą niepewnością, bo tej stopy nie da się bezpośrednio zaobserwować.", True,
                why="Wylicza się ją z modeli, które dają różne wyniki."),
          ),
      ]),

    L(5, "Pieniądz elektroniczny, kryptowaluty i CBDC",
      "Odróżniać pieniądz elektroniczny, kryptowaluty, stablecoiny i walutę cyfrową banku centralnego; rozumieć, jak działa blockchain i halving bitcoina oraz dlaczego kryptowaluty słabo pełnią funkcje pieniądza.",
      ["Pieniądz elektroniczny i karta płatnicza", "Kryptowaluta", "Bitcoin i halving", "Blockchain (łańcuch bloków)", "Stablecoin i altcoin", "Waluta cyfrowa banku centralnego (CBDC)"],
      [BTC, ECBDE],
      explain=[
          K("Pieniądz bezgotówkowy i elektroniczny",
            "Płacąc kartą lub BLIK-iem, przenosimy pieniądz bankowy – depozyt w banku komercyjnym. Pieniądz elektroniczny (np. środki na karcie przedpłaconej lub w portfelu instytucji pieniądza elektronicznego) to wartość pieniężna przechowywana elektronicznie, wydawana w zamian za wpłacone środki i wymienialna na nie po wartości nominalnej."),
          K("Blockchain i bitcoin",
            "Blockchain to rozproszony rejestr transakcji: bloki powiązane kryptograficznie (każdy zawiera skrót poprzedniego), przechowywane przez wiele węzłów, bez centralnego emitenta. Bitcoin (2008, S. Nakamoto) ma limit 21 mln jednostek. Nowe bitcoiny powstają jako nagroda dla górników, która co 210 000 bloków (ok. 4 lata) maleje o połowę – to halving. Ostatni: 20.04.2024, z 6,25 do 3,125 BTC na blok."),
          W("Nagroda za blok wynosi 3,125 BTC. Ile wyniesie po kolejnym halvingu?",
            "1,5625 BTC", "6,25 BTC", "3,125 BTC",
            why="Halving dzieli nagrodę przez 2."),
          K("Czy kryptowaluta jest pieniądzem?",
            "Bitcoin ma bardzo zmienną cenę, więc słabo pełni funkcję miernika wartości i środka tezauryzacji; jest mało powszechnie akceptowany i nie jest prawnym środkiem płatniczym w Polsce. Stablecoiny próbują ograniczyć zmienność, wiążąc wartość z walutą (np. 1 token = 1 USD) dzięki rezerwom. Altcoiny to pozostałe kryptowaluty poza bitcoinem. W UE emitentów i dostawców usług kryptoaktywów reguluje rozporządzenie MiCA."),
          K("CBDC – cyfrowy pieniądz banku centralnego",
            "CBDC to elektroniczna forma pieniądza banku centralnego dostępna dla obywateli – jak cyfrowa gotówka, będąca bezpośrednim zobowiązaniem banku centralnego, a nie banku komercyjnego. EBC prowadzi prace przygotowawcze nad cyfrowym euro. Ryzyko: odpływ depozytów z banków komercyjnych w kryzysie, dlatego rozważa się limity posiadania."),
          PF("Środki na rachunku w banku komercyjnym są zobowiązaniem tego banku, a CBDC byłaby zobowiązaniem banku centralnego.", True,
             why="To podstawowa różnica między pieniądzem bankowym a CBDC."),
      ],
      mech=[
          KT("Jaka to forma pieniądza lub aktywa?",
             {"Pieniądz bankowy": ["Saldo na rachunku osobistym", "Płatność kartą debetową"],
              "Kryptowaluta": ["Bitcoin", "Ether"],
              "Stablecoin": ["Token powiązany 1:1 z dolarem", "Token powiązany 1:1 z euro"],
              "CBDC": ["Projekt cyfrowego euro EBC", "Cyfrowy juan (e-CNY)"]},
             why="Różnią się emitentem i zabezpieczeniem wartości."),
          LN("Ułóż, jak transakcja bitcoinem trafia do łańcucha bloków.",
             ["Użytkownik podpisuje transakcję kluczem prywatnym", "Transakcja trafia do sieci węzłów", "Górnicy zbierają transakcje w blok i rozwiązują zadanie obliczeniowe", "Zwycięski górnik dołącza blok i dostaje nagrodę", "Kolejne bloki potwierdzają transakcję, utrudniając jej zmianę"],
             why="Konsensus proof of work zastępuje zaufanie do centralnej instytucji."),
          W("Popyt na bitcoina się nie zmienia, a halving zmniejsza tempo powstawania nowych jednostek. Co zakłada prosta analiza podaży i popytu?",
            "Presję na wzrost ceny", "Presję na spadek ceny", "Brak wpływu na cenę",
            why="Mniejszy przyrost podaży przy stałym popycie podnosi cenę; w praktyce cenę kształtują też oczekiwania."),
          W("Dlaczego bitcoin słabo pełni funkcję miernika wartości?",
            "Jego cena bardzo się waha", "Jest podzielny do 8 miejsc po przecinku", "Ma ograniczoną podaż",
            why="Ceny w bitcoinach musiałyby zmieniać się codziennie."),
          M("Jakie ryzyka wiążą się ze stablecoinami?",
            ["Rezerwy emitenta mogą być niewystarczające", "Masowe żądania wykupu mogą zachwiać powiązaniem", "Kurs może odbiegać od 1:1 w kryzysie", "Bank centralny gwarantuje ich wartość"], [0, 1, 2],
            why="Emitentem jest firma prywatna, nie bank centralny."),
          PF("W Polsce bitcoin jest prawnym środkiem płatniczym.", False,
             why="Prawnym środkiem płatniczym są znaki pieniężne emitowane przez NBP."),
      ],
      calc=[
          LB("Nagroda na początku istnienia bitcoina wynosiła 50 BTC. Ile wynosi po 4 halvingach?",
             3.125, "50/2**4", ["50 / 16 = 3,125 BTC"], unit="BTC", tol=0.001),
          LB("Ile bitcoinów powstaje w jednym okresie między halvingami (210 000 bloków) przy nagrodzie 3,125 BTC?",
             656250, "210000*3.125", ["210 000 · 3,125 = 656 250 BTC"], unit="BTC"),
          LB("Bloki powstają średnio co 10 minut. Ile bloków powstaje w ciągu doby?",
             144, "24*60/10", ["1440 / 10 = 144"], unit="bloków"),
          LB("Ile BTC dziennie trafia do górników jako nagroda (144 bloki, 3,125 BTC)?",
             450, "144*3.125", ["144 · 3,125 = 450 BTC"], unit="BTC"),
          LB("Cena bitcoina spadła z 60 000 do 42 000 USD. O ile procent?",
             30, "(1-42000/60000)*100", ["42 / 60 = 0,7 → spadek o 30%"], unit="%"),
          LB("Stablecoin w obiegu: 50 mld USD tokenów, rezerwy 47 mld USD. Jaki procent tokenów jest pokryty rezerwą?",
             94, "47/50*100", ["47 / 50 = 94%"], unit="%"),
      ],
      case=[
          PR("W maju 2022 r. algorytmiczny stablecoin TerraUSD (UST), który miał utrzymywać wartość 1 USD bez pełnych rezerw w dolarach, stracił powiązanie i w ciągu kilku dni jego cena spadła do kilku centów. Inwestorzy stracili dziesiątki miliardów dolarów.",
             W("Dlaczego UST stracił powiązanie z dolarem?",
               "Nie miał wystarczających rezerw, a mechanizm oparty na drugim tokenie zawiódł przy masowej sprzedaży", "Bank centralny USA go zakazał", "Wydobyto zbyt wiele bitcoinów",
               why="Bez twardych rezerw zaufanie załamało się jak w runie na bank."),
             W("Do jakiego zjawiska z bankowości jest to podobne?",
               "Paniki bankowej – runu na bank", "Denominacji", "Halvingu",
               why="Wszyscy chcieli wymienić tokeny naraz, a wartość zależała od zaufania."),
             PF("Rozporządzenie MiCA w UE wymaga od emitentów tokenów powiązanych z walutą utrzymywania rezerw.", True,
                why="MiCA wprowadza wymogi rezerw i nadzór nad emitentami."),
          ),
          PR("EBC rozważa wprowadzenie cyfrowego euro. Banki komercyjne obawiają się, że w czasie kryzysu klienci przeniosą depozyty do cyfrowego euro. EBC proponuje limit posiadania (np. kilka tysięcy euro na osobę).",
             W("Czym cyfrowe euro różniłoby się od euro na rachunku bankowym?",
               "Byłoby zobowiązaniem EBC, a nie banku komercyjnego", "Byłoby kryptowalutą bez emitenta", "Nie byłoby prawnym środkiem płatniczym",
               why="CBDC to pieniądz banku centralnego w formie cyfrowej."),
             W("Po co limit posiadania?",
               "By ograniczyć odpływ depozytów z banków", "By zwiększyć inflację", "By ułatwić spekulację",
               why="Masowy transfer depozytów osłabiłby zdolność banków do udzielania kredytów."),
             PF("CBDC, podobnie jak bitcoin, nie ma centralnego emitenta.", False,
                why="Emitentem CBDC jest bank centralny."),
          ),
      ]),
    L(6, "Droga do euro: od Europejskiego Systemu Walutowego do raportu Delorsa i Maastricht",
      "Znać etapy integracji walutowej w Europie – Europejski System Walutowy i ECU (1979), raport Delorsa (1989) z trzema etapami UGW, traktat z Maastricht i kryteria konwergencji – oraz wprowadzenie euro w 1999 i 2002 r.",
      ["Raport Delorsa (1989)", "Europejski System Walutowy (ESW) i ERM", "Kryteria konwergencji (z Maastricht)", "Unia Gospodarcza i Walutowa (UGW)", "Euro"],
      [XECBE, XDEL, ECBDE],
      explain=[
          K("Europejski System Walutowy (1979)",
            "Po upadku systemu z Bretton Woods państwa EWG utworzyły w 1979 r. Europejski System Walutowy: mechanizm kursowy ERM (kursy wahają się wokół parytetów) i ECU – koszykową jednostkę rozrachunkową, poprzedniczkę euro. W 1992 r. kryzys ERM („czarna środa”) zmusił Wielką Brytanię do wyjścia z mechanizmu."),
          K("Raport Delorsa (1989)",
            "Komitet pod przewodnictwem J. Delorsa przedstawił w kwietniu 1989 r. plan Unii Gospodarczej i Walutowej w trzech etapach: I (od 1.07.1990) – pełna swoboda przepływu kapitału i współpraca banków centralnych; II (od 1.01.1994) – Europejski Instytut Walutowy, niezależność banków centralnych, zakaz finansowania deficytów przez bank centralny; III (od 1.01.1999) – nieodwołalnie stałe kursy, euro i wspólna polityka pieniężna."),
          W("Od kiedy obowiązywał III etap UGW i euro w obrocie bezgotówkowym?",
            "Od 1.01.1999 r.", "Od 1.07.1990 r.", "Od 1.01.1994 r.",
            why="Banknoty i monety euro weszły 1.01.2002 r."),
          K("Maastricht i kryteria konwergencji",
            "Traktat z Maastricht (1992) wpisał UGW do prawa UE i określił kryteria przyjęcia euro: stabilność cen, finanse publiczne (deficyt ≤ 3% PKB, dług ≤ 60% PKB), stabilność kursu (2 lata w ERM II), zbieżność długoterminowych stóp procentowych oraz zgodność prawa z zasadami ESBC."),
          K("Euro",
            "1.01.1999 r. euro zastąpiło waluty 11 państw w obrocie bezgotówkowym, a 1.01.2002 r. weszły banknoty i monety. Politykę pieniężną prowadzi EBC. W 2026 r. strefa euro liczy 21 państw (Bułgaria od 1.01.2026 r.)."),
          PF("ECU było walutą z banknotami i monetami w obiegu powszechnym.", False,
             why="Była to koszykowa jednostka rozrachunkowa."),
      ],
      mech=[
          LN("Ułóż etapy drogi do euro.",
             ["Europejski System Walutowy i ECU (1979)", "Raport Delorsa (1989)", "Traktat z Maastricht (1992)", "Euro w obrocie bezgotówkowym (1999)", "Banknoty i monety euro (2002)"],
             why="Chronologia integracji walutowej."),
          KT("Który etap UGW według raportu Delorsa?",
             {"Etap I (1990)": ["Pełna swoboda przepływu kapitału", "Ściślejsza współpraca banków centralnych"],
              "Etap II (1994)": ["Europejski Instytut Walutowy", "Niezależność krajowych banków centralnych"],
              "Etap III (1999)": ["Nieodwołalnie stałe kursy", "Wspólna polityka pieniężna EBC"]},
             why="Trzy etapy Unii Gospodarczej i Walutowej."),
          W("Jaki instytut przygotowywał powstanie EBC w II etapie?",
            "Europejski Instytut Walutowy", "Bank Rozrachunków Międzynarodowych", "Europejski Bank Inwestycyjny",
            why="EIW działał w latach 1994–1998."),
          W("Ile wynosi limit deficytu w kryteriach z Maastricht?",
            "3% PKB", "60% PKB", "1,5% PKB",
            why="60% PKB to limit długu."),
          M("Które kryteria konwergencji obowiązują?",
            ["Stabilność cen", "Deficyt i dług w limitach", "Udział w ERM II przez 2 lata", "Bezrobocie poniżej 5%"], [0, 1, 2],
            why="Bezrobocie nie jest kryterium konwergencji."),
          PF("Raport Delorsa przewidywał zakaz finansowania deficytów przez banki centralne.", True,
             why="To element II etapu UGW."),
      ],
      calc=[
          LB("Ile lat minęło od raportu Delorsa (1989) do euro bezgotówkowego (1999)?",
             10, "1999-1989", ["1999 − 1989 = 10 lat"], unit="lat"),
          LB("Kraj ma deficyt 4,2% PKB. O ile pkt proc. przekracza limit z Maastricht?",
             1.2, "4.2-3", ["4,2 − 3 = 1,2 pkt proc."], unit="pkt proc."),
          LB("Dług 55% PKB. Ile wynosi zapas do limitu (pkt proc.)?",
             5, "60-55", ["60 − 55 = 5 pkt proc."], unit="pkt proc."),
          LB("Inflacja w trzech najlepszych krajach UE: 1,0%, 1,4%, 1,6%. Ile wynosi próg kryterium cen (średnia + 1,5 pkt proc.)?",
             2.83, "(1.0+1.4+1.6)/3+1.5", ["1,33 + 1,5 ≈ 2,83%"], unit="%"),
          LB("Kurs przeliczeniowy Bułgarii: 1 EUR = 1,95583 BGN. Ile euro to 1 000 lewów (zaokrąglij do 0,01)?",
             511.29, "1000/1.95583", ["1 000 / 1,95583 ≈ 511,29 euro"], unit="euro"),
          LB("Strefa euro: 11 państw w 1999 r., 21 w 2026 r. O ile państw się powiększyła?",
             10, "21-11", ["21 − 11 = 10"], unit=""),
      ],
      case=[
          PR("We wrześniu 1992 r. funt brytyjski znalazł się pod presją spekulacyjną w mechanizmie ERM. Mimo podwyżek stóp i interwencji Bank Anglii nie obronił kursu, a Wielka Brytania wyszła z ERM („czarna środa”).",
             W("Jaki element Europejskiego Systemu Walutowego zawiódł?",
               "Mechanizm kursowy ERM", "ECU jako jednostka rozrachunkowa", "Europejski Instytut Walutowy",
               why="Utrzymanie kursu w ramach ERM okazało się niemożliwe."),
             W("Jaki wniosek wyciągnięto dla UGW?",
               "Sztywne kursy bez wspólnej polityki pieniężnej są podatne na ataki spekulacyjne", "Należy zlikwidować banki centralne", "ERM należy rozszerzyć na cały świat",
               why="III etap UGW wprowadził wspólną walutę i politykę."),
             PF("Wielka Brytania nie przyjęła później euro.", True,
                why="Zachowała funta, a w 2020 r. wyszła z UE."),
          ),
          PR("Bułgaria przyjęła euro 1 stycznia 2026 r. jako 21. państwo strefy, po kilku latach w ERM II i wcześniej w systemie currency board. Polska, choć zobowiązała się do przyjęcia euro w traktacie akcesyjnym, nie wyznaczyła daty i nie uczestniczy w ERM II.",
             W("Którego kryterium konwergencji Polska formalnie nie spełnia?",
               "Udziału w ERM II przez co najmniej 2 lata", "Posiadania banku centralnego", "Członkostwa w UE",
               why="Polska nie przystąpiła do ERM II."),
             W("Dlaczego currency board ułatwił Bułgarii przyjęcie euro?",
               "Kurs lewa był już sztywno powiązany (z marką, potem z euro)", "Bo Bułgaria nie miała długu", "Bo nie miała inflacji",
               why="Stabilność kursu była zapewniona od lat."),
             PF("Przyjęcie euro oznacza przekazanie polityki pieniężnej do EBC.", True,
                why="Krajowy bank centralny staje się częścią Eurosystemu."),
          ),
      ]),
]
