# -*- coding: utf-8 -*-
# Zrozumienie – Podstawy finansów / Fundusze, derywaty i ryzyko
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-08"
S173 = S("OpenStax, Principles of Economics 3e, 17.2 How Households Supply Financial Capital", OS3 + "17-2-how-households-supply-financial-capital", D)
S174 = S("OpenStax, Principles of Economics 3e, 17.3 How to Accumulate Personal Wealth", OS3 + "17-3-how-to-accumulate-personal-wealth", D)
KNF = S("Komisja Nadzoru Finansowego", "https://www.knf.gov.pl/", D)
IZFA = S("Izba Zarządzających Funduszami i Aktywami (IZFiA)", "https://www.izfa.pl/", D)
GPW = S("Giełda Papierów Wartościowych w Warszawie", "https://www.gpw.pl/", D)
NBPE = S("NBP – edukacja ekonomiczna", "https://nbp.pl/edukacja/", D)

LESSONS = [
    L(1, "Ryzyko, dywersyfikacja i teoria portfela",
      "Mierzyć ryzyko inwestycji odchyleniem standardowym, odróżniać ryzyko systematyczne od specyficznego i rozumieć, dlaczego dywersyfikacja (Markowitz) zmniejsza ryzyko bez proporcjonalnej utraty zysku.",
      ["Ryzyko inwestycyjne", "Ryzyko systematyczne i specyficzne", "Dywersyfikacja portfela", "Nowoczesna teoria portfela (Markowitz)"],
      [S173, S174],
      explain=[
          K("Zysk i ryzyko",
            "Oczekiwana stopa zwrotu to średnia ważona możliwych wyników (wagi – prawdopodobieństwa). Ryzyko to niepewność wyniku, mierzona zwykle odchyleniem standardowym stóp zwrotu. Inwestorzy niechętni ryzyku żądają za nie premii – dlatego akcje w długim okresie przynoszą więcej niż obligacje, a obligacje więcej niż lokaty.",
            w="E(R) = Σ pᵢ · Rᵢ"),
          K("Dwa rodzaje ryzyka",
            "Ryzyko specyficzne (niesystematyczne) dotyczy jednej spółki lub branży: strajk, nieudany produkt, odejście prezesa. Ryzyko systematyczne (rynkowe) dotyka całego rynku: recesja, zmiana stóp procentowych, wojna. Dywersyfikacja usuwa ryzyko specyficzne, ale nie systematyczne – za to drugie rynek płaci premię."),
          W("Inwestor kupuje akcje 40 spółek z różnych branż. Które ryzyko istotnie ograniczył?",
            "Specyficzne", "Systematyczne", "Oba w równym stopniu",
            why="Problemy jednej spółki mają mały wpływ na cały portfel."),
          K("Markowitz i korelacja",
            "H. Markowitz (1952, Nobel 1990) pokazał, że ryzyko portfela zależy nie tylko od ryzyka składników, ale też od korelacji między nimi. Łącząc aktywa, które nie poruszają się idealnie razem (korelacja < 1), uzyskujemy portfel o ryzyku mniejszym niż średnia ważona ryzyk. Portfele efektywne dają najwyższy oczekiwany zwrot przy danym ryzyku – tworzą granicę efektywną.",
            w="σ²ₚ = w₁²σ₁² + w₂²σ₂² + 2w₁w₂ρσ₁σ₂"),
          K("Granice dywersyfikacji",
            "Ryzyko portfela szybko spada przy pierwszych kilkunastu spółkach, potem coraz wolniej, aż zostaje tylko ryzyko systematyczne. W kryzysach korelacje między aktywami rosną – dywersyfikacja chroni słabiej, niż wynika z danych z czasów spokoju."),
          PF("Portfel złożony z dwóch aktywów o korelacji −1 można zbudować tak, by jego ryzyko było zerowe.", True,
             why="Przy idealnie ujemnej korelacji wahania się znoszą."),
      ],
      mech=[
          KT("Ryzyko systematyczne czy specyficzne?",
             {"Systematyczne": ["Podwyżka stóp procentowych przez RPP", "Globalna recesja", "Wybuch wojny w regionie"],
              "Specyficzne": ["Pożar fabryki spółki", "Utrata kluczowego kontraktu", "Afera księgowa w zarządzie"]},
             why="Systematyczne dotyka wszystkich spółek, specyficzne – jednej."),
          LN("Ułóż, jak dywersyfikacja obniża ryzyko portfela.",
             ["Inwestor ma akcje jednej spółki – pełne ryzyko specyficzne", "Dodaje spółki z innych branż", "Złe wyniki jednej spółki częściowo kompensują dobre wyniki innych", "Wahania portfela maleją", "Zostaje głównie ryzyko systematyczne całego rynku"],
             why="Kompensacja działa, bo spółki nie są idealnie skorelowane."),
          W("Które połączenie najbardziej obniży ryzyko portfela?",
            "Aktywa o ujemnej korelacji", "Aktywa o korelacji +1", "Dwie spółki z tej samej branży",
            why="Im niższa korelacja, tym większy efekt dywersyfikacji."),
          W("W kryzysie 2008 r. prawie wszystkie akcje spadały jednocześnie. Co się stało z korelacjami?",
            "Wzrosły", "Spadły do zera", "Stały się ujemne",
            why="W panice inwestorzy sprzedają wszystko – korzyść z dywersyfikacji maleje."),
          M("Co wynika z teorii portfela Markowitza?",
            ["Ryzyko portfela zależy od korelacji składników", "Istnieje granica efektywna portfeli", "Racjonalny inwestor wybiera portfel z granicy efektywnej", "Najlepiej mieć jedną spółkę o najwyższym zwrocie"], [0, 1, 2],
            why="Koncentracja w jednej spółce zwiększa ryzyko bez rekompensaty."),
          PF("Za ryzyko specyficzne rynek płaci premię, bo inwestor nie może go uniknąć.", False,
             why="Ryzyko specyficzne można usunąć dywersyfikacją, więc rynek za nie nie płaci."),
      ],
      calc=[
          LB("Akcja: 30% szans na zwrot 20%, 50% na 8%, 20% na −10%. Ile wynosi oczekiwana stopa zwrotu (%)?",
             8, "0.3*20+0.5*8+0.2*(-10)", ["6 + 4 − 2 = 8%"], unit="%"),
          LB("Portfel: 60% akcji o oczekiwanym zwrocie 9% i 40% obligacji o 5%. Ile wynosi oczekiwany zwrot portfela (%)?",
             7.4, "0.6*9+0.4*5", ["5,4 + 2,0 = 7,4%"], unit="%", tol=0.01),
          LB("Dwa aktywa po 50%, σ = 20% każde, korelacja 0. Ile wynosi odchylenie standardowe portfela (%)?",
             14.14, "((0.25*400+0.25*400))**0.5", ["σ² = 0,25 · 400 + 0,25 · 400 = 200", "σ ≈ 14,14%"], unit="%", tol=0.02),
          LB("Te same aktywa (po 50%, σ = 20%), korelacja +1. Ile wynosi σ portfela (%)?",
             20, "((0.25*400+0.25*400+2*0.25*400))**0.5", ["σ² = 100 + 100 + 200 = 400", "σ = 20%"], unit="%"),
          LB("Zwroty z 4 lat: 10%, −5%, 15%, 0%. Ile wynosi średni zwrot (%)?",
             5, "(10-5+15+0)/4", ["20 / 4 = 5%"], unit="%"),
          LB("Wariancja zwrotu wynosi 225 (%²). Ile wynosi odchylenie standardowe (%)?",
             15, "225**0.5", ["√225 = 15%"], unit="%"),
      ],
      case=[
          PR("Pani Karolina ma 100 000 zł w akcjach jednej spółki, w której pracuje. W ciągu roku spółka straciła ważny kontrakt, kurs spadł o 45%, a firma ogłosiła zwolnienia.",
             W("Jakie ryzyko zrealizowało się w jej portfelu?",
               "Specyficzne – związane z jedną spółką", "Systematyczne", "Walutowe",
               why="Utrata kontraktu dotyczy tylko tej spółki."),
             W("Dlaczego jej sytuacja jest szczególnie niekorzystna?",
               "Ryzyko pracy i inwestycji jest skorelowane – traci naraz oszczędności i pewność zatrudnienia", "Bo akcje zawsze spadają", "Bo nie płaciła podatku Belki",
               why="Dochód z pracy i portfel zależą od tej samej firmy."),
             PF("Gdyby zainwestowała w szeroki fundusz indeksowy, spadek jednej spółki miałby niewielki wpływ na jej portfel.", True,
                why="Dywersyfikacja ogranicza ryzyko specyficzne."),
          ),
          PR("Inwestor porównuje dwa portfele: A – 100% akcji polskich (oczekiwany zwrot 9%, σ = 22%); B – 70% akcji i 30% obligacji skarbowych (oczekiwany zwrot 7,8%, σ = 15%). Dane umowne.",
             W("Który portfel ma lepszy stosunek zwrotu do ryzyka?",
               "B – ok. 0,52 vs 0,41", "A – ok. 0,41 vs 0,52", "Są takie same",
               why="7,8 / 15 ≈ 0,52; 9 / 22 ≈ 0,41."),
             W("Dlaczego ryzyko B spadło bardziej niż oczekiwany zwrot?",
               "Akcje i obligacje są słabo skorelowane", "Obligacje nie mają żadnego ryzyka", "Akcji jest więcej",
               why="Niska korelacja daje efekt dywersyfikacji."),
             PF("Wybór między A i B zależy także od skłonności inwestora do ryzyka i horyzontu inwestycji.", True,
                why="Młody inwestor z długim horyzontem może zaakceptować większe wahania."),
          ),
      ]),

    L(2, "CAPM, bańki spekulacyjne i uczciwość rynku",
      "Liczyć wymaganą stopę zwrotu z modelu CAPM i rozumieć współczynnik beta, wyjaśniać mechanizm baniek spekulacyjnych oraz rozumieć, dlaczego wykorzystanie informacji poufnej jest zakazane i jaką rolę pełni dom maklerski.",
      ["Model CAPM", "Ryzyko systematyczne i specyficzne", "Bańka spekulacyjna", "Insider trading (wykorzystanie informacji poufnej)", "Dom maklerski (firma inwestycyjna)"],
      [S174, KNF],
      explain=[
          K("CAPM",
            "Model wyceny aktywów kapitałowych (Sharpe, Lintner, Mossin; Nobel dla Sharpe’a 1990) mówi, że wymagana stopa zwrotu = stopa wolna od ryzyka + beta × premia za ryzyko rynkowe. Ponieważ ryzyko specyficzne można zdywersyfikować, wynagradzane jest tylko systematyczne, mierzone betą.",
            w="E(R) = r_f + β · (E(R_m) − r_f)"),
          K("Beta",
            "Beta mierzy wrażliwość akcji na ruchy rynku. β = 1 – porusza się jak rynek; β = 1,5 – gdy rynek rośnie o 10%, akcja średnio o 15% (i mocniej spada); β = 0,5 – spółki defensywne (energetyka, żywność). Beta ujemna – aktywo zachowuje się przeciwnie do rynku."),
          W("Stopa wolna od ryzyka 4%, premia rynkowa 6%, beta 1,5. Ile wynosi wymagana stopa zwrotu?",
            "13%", "10%", "9%",
            why="4% + 1,5 · 6% = 13%."),
          K("Bańka spekulacyjna",
            "Cena aktywa rośnie daleko ponad wartość wynikającą z fundamentów, bo kupujący liczą na dalszy wzrost i odsprzedaż drożej („teoria większego głupca”). Bańkę napędzają tani kredyt, euforia, opowieść o „nowej erze”. Gdy zabraknie nowych kupujących, ceny gwałtownie spadają. Przykłady: tulipanomania (Holandia, 1637), bańka internetowa (2000), bańka na rynku nieruchomości w USA (2006–2007)."),
          K("Informacja poufna i dom maklerski",
            "Informacja poufna to precyzyjna, niepubliczna informacja, która po ujawnieniu mogłaby istotnie wpłynąć na kurs (np. o przejęciu). Wykorzystanie jej do transakcji (insider trading) jest przestępstwem – narusza równość inwestorów i zaufanie do rynku. W UE reguluje to rozporządzenie MAR, a w Polsce ściga KNF. Dom maklerski (firma inwestycyjna) przyjmuje i wykonuje zlecenia, prowadzi rachunki maklerskie, doradza i oferuje emisje – działa za zezwoleniem KNF."),
          PF("Akcja z betą 0,6 przy spadku rynku o 10% powinna przeciętnie spaść o ok. 6%.", True,
             why="0,6 · 10% = 6%."),
      ],
      mech=[
          LN("Ułóż typowy przebieg bańki spekulacyjnej.",
             ["Pojawia się nowa technologia lub opowieść o wyjątkowym wzroście", "Pierwsze wzrosty cen przyciągają kolejnych inwestorów", "Tani kredyt i euforia napędzają zakupy na kredyt", "Ceny odrywają się od fundamentów", "Brakuje nowych kupujących – następuje gwałtowny krach"],
             why="Wzrost cen sam przyciąga popyt – do czasu."),
          KT("Spółka defensywna czy cykliczna (wysoka beta)?",
             {"Niska beta (defensywna)": ["Producent żywności podstawowej", "Dostawca energii elektrycznej", "Sieć aptek"],
              "Wysoka beta (cykliczna)": ["Producent samochodów", "Deweloper mieszkaniowy", "Spółka technologiczna w fazie wzrostu"]},
             why="Popyt na dobra podstawowe mało zależy od koniunktury."),
          W("Rośnie stopa wolna od ryzyka, a beta i premia rynkowa się nie zmieniają. Co dzieje się z wymaganą stopą zwrotu z akcji?",
            "Rośnie", "Spada", "Nie zmienia się",
            why="r_f jest składnikiem wymaganej stopy w CAPM."),
          W("Członek zarządu kupuje akcje dzień przed ogłoszeniem tajnego przejęcia. Co to jest?",
            "Wykorzystanie informacji poufnej – przestępstwo", "Legalny arbitraż", "Analiza fundamentalna",
            why="Informacja była niepubliczna i cenotwórcza."),
          M("Co sprzyja powstawaniu baniek?",
            ["Tani i łatwo dostępny kredyt", "Euforia i przekonanie o „nowej erze”", "Zakupy z myślą o szybkiej odsprzedaży", "Ostrożne wyceny oparte na zyskach"], [0, 1, 2],
            why="Ostrożna wycena fundamentalna działa przeciw bańkom."),
          PF("Według CAPM akcja o becie 0 powinna przynosić stopę wolną od ryzyka.", True,
             why="E(R) = r_f + 0 · premia = r_f."),
      ],
      calc=[
          LB("r_f = 5%, E(R_m) = 11%, β = 0,8. Ile wynosi wymagana stopa zwrotu (%)?",
             9.8, "5+0.8*(11-5)", ["5 + 0,8 · 6 = 9,8%"], unit="%", tol=0.01),
          LB("r_f = 5%, E(R_m) = 11%, β = 1,3. Ile wynosi wymagana stopa zwrotu (%)?",
             12.8, "5+1.3*6", ["5 + 1,3 · 6 = 12,8%"], unit="%", tol=0.01),
          LB("Portfel: 50% akcji o β = 1,4 i 50% o β = 0,6. Ile wynosi beta portfela?",
             1, "0.5*1.4+0.5*0.6", ["0,7 + 0,3 = 1,0"], unit="", tol=0.01),
          LB("Rynek spadł o 20%. O ile procent przeciętnie spadnie akcja o becie 1,5?",
             30, "1.5*20", ["1,5 · 20% = 30%"], unit="%"),
          LB("Indeks Nasdaq spadł z ok. 5000 pkt (2000) do ok. 1150 pkt (2002). O ile procent?",
             77, "(1-1150/5000)*100", ["1150 / 5000 = 0,23", "Spadek o 77%"], unit="%", tol=0.01),
          LB("Akcja przynosi oczekiwane 10%, a CAPM wymaga 12%. Ile wynosi alfa (różnica, pkt proc.; ujemna ze znakiem minus)?",
             -2, "10-12", ["10 − 12 = −2 pkt proc."], unit="pkt proc."),
      ],
      case=[
          PR("W latach 1995–2000 akcje spółek internetowych drożały po kilkaset procent, choć wiele z nich nie miało zysków. Indeks Nasdaq osiągnął szczyt w marcu 2000 r., a do października 2002 r. stracił ok. 78%.",
             W("Jaki mechanizm napędzał wzrosty?",
               "Oczekiwanie dalszego wzrostu cen i opowieść o „nowej ekonomii”", "Wysokie dywidendy spółek internetowych", "Rosnące zyski wszystkich spółek",
               why="Ceny oderwały się od zysków."),
             W("Jakie P/E miałaby spółka bez zysków?",
               "Nie da się go sensownie policzyć – zysk jest zerowy lub ujemny", "Zero", "Jeden",
               why="Dzielenie przez zero lub ujemny zysk nie ma sensu ekonomicznego."),
             PF("Internet okazał się przełomową technologią, ale to nie oznaczało, że ówczesne wyceny były uzasadnione.", True,
                why="Prawdziwa innowacja może współistnieć z bańką cenową."),
          ),
          PR("KNF nakłada karę na menedżera spółki giełdowej, który – znając wcześniej niepublikowane, bardzo złe wyniki – sprzedał swoje akcje przed publikacją raportu.",
             W("Co zrobił menedżer?",
               "Wykorzystał informację poufną", "Zastosował krótką sprzedaż", "Zrealizował arbitraż",
               why="Działał na podstawie niepublicznej informacji cenotwórczej."),
             W("Kto traci na takich praktykach?",
               "Inwestorzy, którzy kupili od niego akcje, i zaufanie do rynku", "Nikt", "Tylko KNF",
               why="Kupujący nie mieli tej samej informacji."),
             PF("Zakaz insider tradingu chroni równy dostęp inwestorów do informacji.", True,
                why="Rynek działa sprawnie, gdy inwestorzy mu ufają."),
          ),
      ]),

    L(3, "Fundusze inwestycyjne: od FIO do private equity",
      "Rozumieć, jak działa fundusz inwestycyjny i jednostka uczestnictwa, odróżniać FIO, FIZ, ETF i REIT, fundusze według polityki inwestycyjnej oraz private equity, venture capital i fundusze hedgingowe; poznać rolę OFE.",
      ["Fundusz inwestycyjny", "Fundusz inwestycyjny otwarty (FIO) i zamknięty (FIZ)", "Rodzaje funduszy wg polityki", "ETF", "REIT", "Fundusze private equity i venture capital", "Fundusz hedgingowy", "Otwarte fundusze emerytalne (OFE)"],
      [IZFA, KNF, S173],
      explain=[
          K("Jak działa fundusz",
            "Fundusz zbiera pieniądze wielu inwestorów i inwestuje je wspólnie według określonej polityki. Zarządza nim towarzystwo funduszy inwestycyjnych (TFI), a aktywa przechowuje depozytariusz – są oddzielone od majątku TFI. Inwestor ma jednostki uczestnictwa; ich wartość = wartość aktywów netto / liczba jednostek. Zalety: dywersyfikacja, profesjonalne zarządzanie; wady: opłaty.",
            w="WAN na jednostkę = (aktywa − zobowiązania) / liczba jednostek"),
          K("FIO, FIZ, ETF",
            "FIO zbywa i odkupuje jednostki na żądanie inwestora – można wejść i wyjść w dowolnym dniu wyceny. FIZ emituje certyfikaty inwestycyjne w zamkniętych emisjach, wykupuje je rzadko; może inwestować w mniej płynne aktywa (nieruchomości, wierzytelności). ETF to fundusz notowany na giełdzie, zwykle odwzorowujący indeks, o niskich opłatach – kupuje się go jak akcję."),
          W("Inwestor chce w każdej chwili odzyskać pieniądze po wycenie z danego dnia. Jaki fundusz wybrać?",
            "FIO", "FIZ", "Fundusz private equity",
            why="FIO odkupuje jednostki na żądanie uczestnika."),
          K("Polityka inwestycyjna",
            "Fundusze rynku pieniężnego – instrumenty krótkoterminowe, najniższe ryzyko. Dłużne – obligacje. Mieszane (zrównoważone, stabilnego wzrostu) – akcje i obligacje. Akcyjne – głównie akcje, najwyższe ryzyko i potencjalny zysk. REIT to spółka lub fundusz inwestujący w nieruchomości komercyjne i wypłacający większość dochodu z najmu."),
          K("PE, VC, hedge, OFE",
            "Private equity kupuje udziały w dojrzałych spółkach spoza giełdy (często z kredytem – wykup lewarowany), poprawia ich działanie i po kilku latach sprzedaje. Venture capital finansuje młode, ryzykowne firmy technologiczne. Fundusze hedgingowe stosują elastyczne strategie (krótka sprzedaż, dźwignia, derywaty) dla zamożnych inwestorów. OFE to prywatne fundusze emerytalne z reformy 1999 r.; w 2014 r. 51,5% ich aktywów (głównie obligacje skarbowe) przeniesiono do ZUS."),
          PF("Aktywa funduszu są oddzielone od majątku TFI i przechowywane przez depozytariusza.", True,
             why="Upadłość TFI nie oznacza utraty aktywów funduszu."),
      ],
      mech=[
          KT("Od najniższego do najwyższego ryzyka – przyporządkuj fundusz.",
             {"Niskie ryzyko": ["Fundusz rynku pieniężnego", "Fundusz obligacji krótkoterminowych"],
              "Średnie ryzyko": ["Fundusz stabilnego wzrostu", "Fundusz zrównoważony"],
              "Wysokie ryzyko": ["Fundusz akcji rynków wschodzących", "Fundusz venture capital"]},
             why="Im większy udział akcji i mniej płynnych aktywów, tym wyższe ryzyko."),
          LN("Ułóż, co dzieje się z pieniędzmi wpłaconymi do FIO.",
             ["Inwestor wpłaca 1000 zł", "TFI przydziela jednostki według najbliższej wyceny", "Zarządzający kupuje akcje i obligacje zgodnie z polityką", "Depozytariusz przechowuje aktywa i kontroluje TFI", "Wartość jednostek zmienia się codziennie razem z wartością portfela"],
             why="Inwestor ma udział w portfelu proporcjonalny do liczby jednostek."),
          W("Dlaczego ETF zwykle ma niższe opłaty niż aktywny fundusz akcji?",
            "Odwzorowuje indeks, więc nie wymaga kosztownej analizy i częstych transakcji", "Nie podlega nadzorowi", "Nie płaci podatków",
            why="Zarządzanie pasywne jest tańsze."),
          W("Fundusz private equity kupuje spółkę za 1 mld zł, finansując 70% kredytem. Jak nazywa się taka transakcja?",
            "Wykup lewarowany (LBO)", "IPO", "Sekurytyzacja",
            why="Dług zaciągnięty na zakup spółki to dźwignia."),
          M("Czym FIZ różni się od FIO?",
            ["Emituje certyfikaty zamiast jednostek uczestnictwa", "Odkupuje tytuły uczestnictwa rzadziej", "Może inwestować w mniej płynne aktywa", "Gwarantuje stały zysk"], [0, 1, 2],
            why="Żaden fundusz inwestycyjny nie gwarantuje zysku."),
          PF("Fundusz rynku pieniężnego nie może przynieść straty.", False,
             why="Ryzyko jest niskie, ale nie zerowe – np. przy niewypłacalności emitenta."),
      ],
      calc=[
          LB("Fundusz: aktywa 520 mln zł, zobowiązania 20 mln zł, 4 mln jednostek. Ile wynosi wartość jednostki (zł)?",
             125, "(520-20)/4", ["500 / 4 = 125 zł"], unit="zł"),
          LB("Inwestor wpłaca 10 000 zł, opłata dystrybucyjna 2%, wartość jednostki 125 zł. Ile jednostek otrzyma?",
             78.4, "10000*0.98/125", ["9800 / 125 = 78,4"], unit="jedn.", tol=0.01),
          LB("Wartość jednostki wzrosła ze 125 do 140 zł. Ile wynosi stopa zwrotu (%)?",
             12, "(140/125-1)*100", ["140 / 125 − 1 = 12%"], unit="%"),
          LB("Opłata za zarządzanie 1,8% rocznie od 50 000 zł. Ile kosztuje rocznie (zł)?",
             900, "50000*0.018", ["50 000 · 1,8% = 900 zł"], unit="zł"),
          LB("ETF z opłatą 0,2% i fundusz aktywny z opłatą 2%, oba zarabiają 7% rocznie przed opłatami. Ile wyniesie różnica wartości 10 000 zł po 20 latach (zł)?",
             10742.66, "10000*(1.068**20-1.05**20)", ["Netto: ETF 6,8%, aktywny 5% rocznie", "ETF: 10 000 · 1,068²⁰ ≈ 37 276", "Aktywny: 10 000 · 1,05²⁰ ≈ 26 533", "Różnica ≈ 10 743 zł"], unit="zł", tol=0.01),
          LB("Fundusz VC zainwestował w 10 startupów po 2 mln zł. 7 upadło, 2 zwróciły po 3 mln, 1 – 40 mln zł. Ile wynosi łączny zwrot (mln zł)?",
             46, "2*3+40", ["6 + 40 = 46 mln zł przy nakładzie 20 mln zł"], unit="mln zł"),
      ],
      case=[
          PR("Pani Zofia (60 lat) i jej wnuk Kuba (25 lat) mają po 50 000 zł. Zofia potrzebuje pieniędzy za 2 lata na remont, Kuba odkłada na emeryturę.",
             W("Jaki fundusz pasuje Zofii?",
               "Rynku pieniężnego lub obligacji krótkoterminowych", "Akcji rynków wschodzących", "Venture capital",
               why="Krótki horyzont wymaga niskiej zmienności."),
             W("Jaki fundusz pasuje Kubie?",
               "Akcyjny lub ETF na szeroki indeks", "Wyłącznie rynku pieniężnego", "Lokata jednodniowa",
               why="Długi horyzont pozwala przeczekać wahania i zarobić premię za ryzyko."),
             PF("Fundusz akcyjny może w ciągu 2 lat stracić kilkadziesiąt procent, dlatego nie pasuje do krótkiego celu.", True,
                why="Akcje są zmienne w krótkim okresie."),
          ),
          PR("W lutym 2014 r. z OFE do ZUS przeniesiono 51,5% aktywów (głównie obligacje skarbowe), które umorzono. Od tego czasu udział w OFE jest dobrowolny, a składki stopniowo przenoszone są do ZUS przed emeryturą („suwak”).",
             W("Jaki był skutek dla długu publicznego?",
               "Spadł – umorzono obligacje skarbowe z portfeli OFE", "Wzrósł", "Nie zmienił się",
               why="Państwo przestało być dłużne wobec OFE w części przejętych obligacji."),
             W("Co zamiast obligacji otrzymali członkowie OFE?",
               "Zapis na subkoncie w ZUS", "Gotówkę", "Akcje spółek Skarbu Państwa",
               why="Środki zapisano na subkontach w ZUS i są waloryzowane."),
             PF("Zmiana przesunęła ryzyko z rynku kapitałowego na system repartycyjny – emerytury zależą bardziej od przyszłych składek.", True,
                why="Subkonto w ZUS jest waloryzowane, a nie inwestowane na rynku."),
          ),
      ]),

    L(4, "Kontrakty terminowe i opcje",
      "Rozumieć, jak działają forward, futures i opcje, liczyć wypłaty z opcji kupna i sprzedaży, strategie straddle i strangle oraz prostą wycenę opcji w modelu dwumianowym; odróżniać zabezpieczanie (hedging) od spekulacji.",
      ["Instrument pochodny (derywat)", "Kontrakt terminowy (futures i forward)", "Opcja", "Opcja w pieniądzu, przy pieniądzu, poza pieniądzem", "Strategie opcyjne: straddle i strangle", "Wycena opcji: model Blacka–Scholesa i dwumianowy", "Hedging", "CFD", "Opcje binarne"],
      [GPW, KNF],
      explain=[
          K("Derywat i kontrakt terminowy",
            "Instrument pochodny ma wartość zależną od ceny instrumentu bazowego (akcji, indeksu, waluty, surowca). Kontrakt terminowy to umowa kupna lub sprzedaży w przyszłości po cenie ustalonej dziś. Forward jest zawierany indywidualnie poza giełdą; futures – standaryzowany, notowany na giełdzie, z codziennym rozliczaniem zysków i strat i depozytem zabezpieczającym (dźwignia)."),
          K("Opcja kupna i sprzedaży",
            "Opcja daje nabywcy prawo (nie obowiązek) kupna (call) lub sprzedaży (put) instrumentu po cenie wykonania K. Za to prawo płaci premię wystawcy. Wypłata calla w dniu wygaśnięcia = max(S − K, 0), puta = max(K − S, 0). Opcja jest „w pieniądzu”, gdy wykonanie daje dodatnią wypłatę, „przy pieniądzu”, gdy S ≈ K, i „poza pieniądzem”, gdy wykonanie się nie opłaca.",
            w="call: max(S − K, 0);  put: max(K − S, 0);  zysk = wypłata − premia"),
          W("Opcja call z K = 100 zł, premia 6 zł. W dniu wygaśnięcia kurs wynosi 115 zł. Ile wynosi zysk nabywcy?",
            "9 zł", "15 zł", "21 zł",
            why="Wypłata 15 zł minus premia 6 zł = 9 zł."),
          K("Strategie i wycena",
            "Straddle: kupno calla i puta z tą samą ceną wykonania – zarabia na dużym ruchu w dowolną stronę. Strangle: call i put z różnymi cenami wykonania (tańszy, wymaga większego ruchu). Wartość opcji rośnie ze zmiennością i czasem do wygaśnięcia. Model dwumianowy wycenia opcję, tworząc portfel replikujący; model Blacka–Scholesa (1973, Nobel 1997 dla Scholesa i Mertona) daje wzór dla opcji europejskich."),
          K("Hedging i produkty ryzykowne",
            "Hedging to zajęcie pozycji w derywacie przeciwnej do ryzyka, które się ma: eksporter sprzedaje walutę terminowo, rolnik – zboże przed żniwami, linia lotnicza kupuje paliwo terminowo. CFD (kontrakt na różnicę) i opcje binarne to produkty spekulacyjne z dużą dźwignią; KNF i ESMA ograniczyły ich sprzedaż klientom detalicznym, a oferowanie opcji binarnych tym klientom zakazano."),
          PF("Maksymalna strata nabywcy opcji jest ograniczona do zapłaconej premii.", True,
             why="Nabywca nie musi wykonać opcji, gdy jest to nieopłacalne."),
      ],
      mech=[
          KT("Hedging czy spekulacja?",
             {"Hedging": ["Eksporter sprzedaje euro terminowo, by zabezpieczyć kurs", "Linia lotnicza kupuje kontrakty na paliwo", "Posiadacz akcji kupuje opcję put"],
              "Spekulacja": ["Kupno CFD na złoto z dźwignią 1:20 bez ekspozycji na złoto", "Kupno calla, bo „akcje na pewno wzrosną”", "Straddle przed wynikami spółki"]},
             why="Hedging zmniejsza istniejące ryzyko, spekulacja tworzy nowe."),
          LN("Ułóż, jak eksporter zabezpiecza się kontraktem forward.",
             ["Eksporter wie, że za 3 miesiące otrzyma 1 mln euro", "Obawia się umocnienia złotego", "Zawiera z bankiem forward na sprzedaż euro po 4,25 zł", "Za 3 miesiące kurs rynkowy spada do 4,05 zł", "Eksporter i tak sprzedaje euro po 4,25 zł – zabezpieczył przychód"],
             why="Forward zamyka kurs z góry – chroni przed stratą, ale też odbiera ewentualny zysk."),
          W("Rośnie oczekiwana zmienność kursu akcji. Co dzieje się z ceną opcji call i put?",
            "Obie drożeją", "Obie tanieją", "Call drożeje, put tanieje",
            why="Większa zmienność zwiększa szansę na dużą wypłatę, a strata jest ograniczona."),
          W("Kurs akcji 80 zł, opcja put z K = 90 zł. Jaki to stan opcji?",
            "W pieniądzu", "Poza pieniądzem", "Przy pieniądzu",
            why="Put daje prawo sprzedaży po 90 zł, gdy rynek płaci 80 – wypłata 10 zł."),
          M("Czym futures różni się od forwardu?",
            ["Jest standaryzowany i notowany na giełdzie", "Ma codzienne rozliczanie zysków i strat", "Wymaga depozytu zabezpieczającego", "Daje prawo, ale nie obowiązek wykonania"], [0, 1, 2],
            why="Prawo bez obowiązku to cecha opcji, nie kontraktu terminowego."),
          PF("Wystawca opcji call bez posiadania akcji może ponieść teoretycznie nieograniczoną stratę.", True,
             why="Kurs może rosnąć bez górnej granicy."),
      ],
      calc=[
          LB("Put: K = 50 zł, premia 3 zł, kurs w dniu wygaśnięcia 41 zł. Ile wynosi zysk nabywcy (zł)?",
             6, "(50-41)-3", ["Wypłata 9 zł", "9 − 3 = 6 zł"], unit="zł"),
          LB("Straddle: call i put z K = 100 zł, premie 5 + 4 zł. Kurs w dniu wygaśnięcia 112 zł. Ile wynosi zysk (zł)?",
             3, "(112-100)-9", ["Wypłata calla 12, puta 0", "12 − 9 = 3 zł"], unit="zł"),
          LB("Ten straddle (premie razem 9 zł, K = 100). Przy jakim kursie powyżej 100 zł osiąga próg rentowności (zł)?",
             109, "100+9", ["100 + 9 = 109 zł"], unit="zł"),
          LB("Futures na WIG20: mnożnik 20 zł za punkt. Indeks wzrósł o 50 pkt. Ile zarobił posiadacz pozycji długiej na 1 kontrakcie (zł)?",
             1000, "20*50", ["20 · 50 = 1000 zł"], unit="zł"),
          LB("Model dwumianowy (1 okres): S = 100, za rok 120 albo 90, K = 100, stopa 0%. Prawdopodobieństwo neutralne q = (100 − 90)/(120 − 90). Ile wynosi wartość calla (zł)?",
             6.67, "((100-90)/(120-90))*20", ["q = 1/3", "Wypłata 20 w stanie wzrostu", "C = 20/3 ≈ 6,67 zł"], unit="zł", tol=0.01),
          LB("Eksporter sprzedał terminowo 1 mln euro po 4,25 zł; kurs rynkowy w dniu rozliczenia 4,05 zł. Ile zyskał dzięki zabezpieczeniu (zł)?",
             200000, "1000000*(4.25-4.05)", ["1 000 000 · 0,20 = 200 000 zł"], unit="zł"),
      ],
      case=[
          PR("Rolnik spodziewa się zebrać 200 ton pszenicy za 4 miesiące. Dziś cena terminowa wynosi 900 zł/t. Obawia się spadku cen, ale chciałby skorzystać, gdyby ceny wzrosły. Opcja put z K = 900 zł/t kosztuje 40 zł/t.",
             W("Co da mu sprzedaż kontraktu terminowego po 900 zł/t?",
               "Pewną cenę 900 zł/t, bez względu na rynek", "Prawo, ale nie obowiązek sprzedaży", "Cenę rynkową z dnia zbioru",
               why="Kontrakt terminowy wiąże obie strony."),
             W("Jaka będzie efektywna cena przy zakupie puta, jeśli cena rynkowa spadnie do 780 zł/t?",
               "860 zł/t", "780 zł/t", "900 zł/t",
               why="Sprzedaje po 900 dzięki opcji, minus premia 40 = 860 zł/t."),
             W("Jaka będzie efektywna cena z putem, jeśli cena wzrośnie do 1000 zł/t?",
               "960 zł/t", "900 zł/t", "1000 zł/t",
               why="Nie wykonuje opcji, sprzedaje po 1000, minus premia 40."),
          ),
          PR("Student otwiera konto u brokera CFD i widzi reklamę: „Zarabiaj na złocie z dźwignią 1:20”. Na stronie jest ostrzeżenie, że większość rachunków detalicznych traci pieniądze.",
             W("Co oznacza dźwignia 1:20 przy spadku ceny złota o 5%?",
               "Utrata ok. 100% depozytu", "Utrata 5% depozytu", "Zysk 100%",
               why="20 · 5% = 100%."),
             W("Czy jest to hedging?",
               "Nie – student nie ma ekspozycji na złoto, którą by zabezpieczał", "Tak, zawsze", "Tak, bo złoto jest bezpieczne",
               why="Bez istniejącego ryzyka nie ma czego zabezpieczać – to spekulacja."),
             PF("Regulatorzy w UE ograniczyli dźwignię CFD dla klientów detalicznych.", True,
                why="ESMA i krajowi nadzorcy wprowadzili limity dźwigni i ochronę przed ujemnym saldem."),
          ),
      ]),

    L(5, "Swapy, CDS, sekurytyzacja i finansowanie firm",
      "Rozumieć, jak swap procentowy i walutowy, FRA i CDS przenoszą ryzyko, jak działa sekurytyzacja oraz czym różnią się faktoring, forfaiting i leasing; poznać państwowe fundusze celowe.",
      ["Swap", "Swap walutowy (FX swap)", "FRA", "CDS (credit default swap)", "Sekurytyzacja", "Faktoring", "Forfaiting", "Leasing", "Państwowy fundusz celowy", "Krajowy Fundusz Drogowy i fundusze poza budżetem", "Fundusz Pracy i Fundusz Gwarantowanych Świadczeń Pracowniczych"],
      [KNF, NBPE],
      explain=[
          K("Swapy i FRA",
            "Swap procentowy (IRS): strony wymieniają płatności odsetkowe od tej samej kwoty – jedna płaci stałą stopę, druga zmienną (np. WIBOR). Firma z kredytem o zmiennej stopie może w ten sposób „zamienić” go na stałą. Swap walutowy (FX swap): wymiana walut dziś i wymiana odwrotna w przyszłości po ustalonym kursie – służy zarządzaniu płynnością walutową. FRA ustala dziś stopę procentową dla przyszłego okresu; rozliczana jest tylko różnica stóp."),
          K("CDS – ubezpieczenie od niewypłacalności",
            "Nabywca CDS płaci okresowe opłaty (spread CDS), a w razie niewypłacalności emitenta obligacji sprzedawca CDS pokrywa stratę. Cena CDS mierzy ryzyko kredytowe kraju lub firmy. W 2008 r. ubezpieczyciel AIG sprzedał ogromne ilości CDS na papiery hipoteczne i bez pomocy rządu USA nie byłby w stanie ich wypłacić."),
          W("Firma ma kredyt WIBOR + 2% i boi się wzrostu stóp. Jaki swap zawrze?",
            "Będzie płacić stałą stopę, a otrzymywać zmienną", "Będzie płacić zmienną, a otrzymywać stałą", "Swap walutowy na euro",
            why="Otrzymywana zmienna stopa pokrywa WIBOR w kredycie, a firma płaci stałą."),
          K("Sekurytyzacja",
            "Bank lub firma sprzedaje pulę należności (np. kredytów hipotecznych, leasingowych) spółce celowej, która emituje papiery wartościowe spłacane z tych należności. Bank odzyskuje gotówkę i może udzielać nowych kredytów. Ryzyko: pierwotny kredytodawca mniej dba o jakość kredytów, które i tak sprzeda – to jedna z przyczyn kryzysu subprime."),
          K("Faktoring, forfaiting, leasing i fundusze celowe",
            "Faktoring: firma sprzedaje faktorowi krótkoterminowe należności od odbiorców i szybciej dostaje pieniądze. Forfaiting: wykup średnio- i długoterminowych należności, często eksportowych, bez prawa regresu. Leasing: korzystanie z maszyny lub auta za raty bez kupowania. Państwowe fundusze celowe (np. Fundusz Pracy, FGŚP, Krajowy Fundusz Drogowy w BGK) gromadzą środki na określone cele poza budżetem państwa."),
          PF("W faktoringu z regresem ryzyko niewypłacalności odbiorcy wraca do firmy, która sprzedała należność.", True,
             why="Regres oznacza, że faktor może żądać zwrotu od zbywcy."),
      ],
      mech=[
          KT("Jaki instrument rozwiąże problem?",
             {"Swap procentowy": ["Firma chce zamienić zmienne oprocentowanie kredytu na stałe", "Bank chce zmniejszyć wrażliwość na zmiany WIBOR"],
              "CDS": ["Fundusz chce zabezpieczyć się przed bankructwem emitenta obligacji", "Inwestor chce zabezpieczyć obligacje kraju o niskim ratingu"],
              "Faktoring": ["Firma czeka 90 dni na zapłatę od klientów i brakuje jej gotówki", "Hurtownia chce szybciej odzyskać należności z faktur"]},
             why="Każdy instrument przenosi inny rodzaj ryzyka lub problemu."),
          LN("Ułóż etapy sekurytyzacji kredytów.",
             ["Bank udziela tysięcy kredytów hipotecznych", "Sprzedaje pulę kredytów spółce celowej", "Spółka emituje obligacje zabezpieczone tą pulą", "Inwestorzy kupują obligacje i otrzymują odsetki ze spłat kredytów", "Bank za uzyskane środki udziela nowych kredytów"],
             why="Kredyty zamieniają się w zbywalne papiery wartościowe."),
          W("Spread CDS na obligacje kraju X wzrósł z 80 do 350 pb. Co to oznacza?",
            "Rynek ocenia ryzyko niewypłacalności X jako znacznie wyższe", "Kraj X spłacił dług", "Ratingi X wzrosły",
            why="Droższa ochrona oznacza większe ryzyko."),
          W("Mała firma potrzebuje auta dostawczego, ale nie ma gotówki ani zdolności do dużego kredytu. Co najczęściej wybierze?",
            "Leasing", "Forfaiting", "CDS",
            why="Leasing pozwala korzystać z auta za raty, a przedmiot jest zabezpieczeniem."),
          M("Jakie ryzyka niesie sekurytyzacja?",
            ["Mniejsza staranność przy udzielaniu kredytów, które zostaną sprzedane", "Złożoność papierów utrudniająca ocenę ryzyka", "Rozproszenie strat po całym systemie finansowym", "Brak możliwości udzielenia nowych kredytów"], [0, 1, 2],
            why="Sekurytyzacja właśnie ułatwia nowe kredyty."),
          PF("Krajowy Fundusz Drogowy finansuje budowę dróg poza budżetem państwa, co zmniejsza widoczny deficyt budżetu.", True,
             why="Wydatki funduszy poza budżetem nie są w deficycie budżetu państwa, choć są w deficycie sektora GG."),
      ],
      calc=[
          LB("Swap: kwota 10 mln zł, firma płaci stałe 5%, otrzymuje WIBOR. WIBOR wynosi 6%. Ile netto otrzymuje firma rocznie (zł)?",
             100000, "10000000*(0.06-0.05)", ["(6% − 5%) · 10 mln = 100 000 zł"], unit="zł"),
          LB("Ten sam swap przy WIBOR 3,5%. Ile netto płaci firma rocznie (zł)?",
             150000, "10000000*(0.05-0.035)", ["(5% − 3,5%) · 10 mln = 150 000 zł"], unit="zł"),
          LB("CDS na 20 mln zł obligacji, spread 250 pb rocznie. Ile kosztuje ochrona rocznie (zł)?",
             500000, "20000000*0.025", ["20 mln · 2,5% = 500 000 zł"], unit="zł"),
          LB("Faktoring: faktura 100 000 zł, zaliczka 85%, prowizja 1,5% wartości faktury. Ile firma dostaje od razu po odjęciu prowizji (zł)?",
             83500, "100000*0.85-100000*0.015", ["85 000 − 1500 = 83 500 zł"], unit="zł"),
          LB("FRA: kontrakt na 50 mln zł na 3 miesiące, stopa FRA 4,0%, rynkowa w dniu rozliczenia 4,6%. Ile wynosi różnica odsetkowa (przed dyskontem, zł)?",
             75000, "50000000*(0.046-0.04)*3/12", ["50 mln · 0,6% · 3/12 = 75 000 zł"], unit="zł"),
          LB("Leasing auta wartego 120 000 zł: opłata wstępna 10%, 36 rat po 3 000 zł, wykup 1%. Ile wynosi suma opłat (zł)?",
             121200, "12000+36*3000+1200", ["12 000 + 108 000 + 1200 = 121 200 zł"], unit="zł"),
      ],
      case=[
          PR("Spółka produkcyjna ma kredyt 50 mln zł oprocentowany WIBOR 3M + 1,8 pkt proc. Zarząd boi się wzrostu stóp. Bank oferuje swap: spółka płaci stałe 4,6%, otrzymuje WIBOR 3M.",
             W("Ile wyniesie efektywne oprocentowanie kredytu po zawarciu swapu?",
               "6,4% – stałe", "WIBOR + 1,8%", "4,6%",
               why="WIBOR z kredytu znosi się z otrzymywanym WIBOR: 4,6% + 1,8% = 6,4%."),
             W("Co, jeśli WIBOR spadnie do 3%?",
               "Spółka nadal płaci 6,4%, więc traci na swapie w porównaniu z brakiem zabezpieczenia", "Płaci 4,8%", "Swap wygasa",
               why="Swap usuwa ryzyko w obie strony – także szansę na niższy koszt."),
             PF("Celem hedgingu nie jest zarabianie, lecz przewidywalność kosztów.", True,
                why="Zabezpieczenie usuwa niepewność."),
          ),
          PR("Eksporter maszyn sprzedał linię produkcyjną do Egiptu z płatnością rozłożoną na 4 lata (weksle na 8 mln euro). Potrzebuje pieniędzy teraz i nie chce ponosić ryzyka niewypłacalności odbiorcy.",
             W("Jaki instrument wybierze?",
               "Forfaiting – sprzedaż weksli bez regresu", "Faktoring z regresem", "Swap walutowy",
               why="Forfaiting dotyczy długoterminowych należności eksportowych bez regresu."),
             W("Kto ponosi ryzyko niewypłacalności odbiorcy po transakcji?",
               "Forfaiter", "Eksporter", "NBP",
               why="Bez regresu ryzyko przechodzi na nabywcę należności."),
             PF("Eksporter otrzyma mniej niż 8 mln euro, bo forfaiter dyskontuje należności i bierze opłatę za ryzyko.", True,
                why="Wartość bieżąca przyszłych płatności jest niższa od nominalnej."),
          ),
      ]),
]
