# -*- coding: utf-8 -*-
# Zrozumienie – Finanse / Podstawy finansów: kategorie, teorie i sektory (wg S. Owsiak, „Finanse”, PWE 2015 – literatura OWE)
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-08"
P171 = S("OpenStax, Principles of Economics 3e, 17.1 How Businesses Raise Financial Capital", OS3 + "17-1-how-businesses-raise-financial-capital", D)
P272 = S("OpenStax, Principles of Economics 3e, 27.2 Measuring Money: Currency, M1, and M2", OS3 + "27-2-measuring-money-currency-m1-and-m2", D)
P284 = S("OpenStax, Principles of Economics 3e, 28.4 Monetary Policy and Economic Outcomes", OS3 + "28-4-monetary-policy-and-economic-outcomes", D)
P304 = S("OpenStax, Principles of Economics 3e, 30.4 Using Fiscal Policy to Fight Recession, Unemployment, and Inflation", OS3 + "30-4-using-fiscal-policy-to-fight-recession-unemployment-and-inflation", D)
P307 = S("OpenStax, Principles of Economics 3e, 30.7 The Question of a Balanced Budget", OS3 + "30-7-the-question-of-a-balanced-budget", D)
KC720 = S("Kodeks cywilny, art. 720 (pożyczka) – Standardy Prawa", "https://standardyprawa.pl/akt/2/art/5238", D)
PBK = S("KNF – Kredyt bankowy i pożyczka (opracowanie)", "https://www.knf.gov.pl/knf/pl/komponenty/img/kredyt_bankowy_i_pozyczka_wojcicka.pdf", D)
KNFIP = S("KNF – Objęcie instytucji pożyczkowych nadzorem KNF", "https://nuk.knf.gov.pl/knf/pl/komponenty/img/Objecie_instytucji_pozyczkowych_nadzorem_KNF_83554.pdf", D)
WCS = S("Wikipedia – British Currency School (spór szkoły obiegowej i bankowej, Bank Charter Act 1844)", "https://en.wikipedia.org/wiki/British_Currency_School", D)
WBT = S("Wikipedia – Baumol–Tobin model", "https://en.wikipedia.org/wiki/Baumol%E2%80%93Tobin_model", D)
CRB = S("W.J. Baumol, The Transactions Demand for Cash: An Inventory Theoretic Approach, QJE 66(4), 1952", "https://doi.org/10.2307/1882104", D)
WFF = S("Wikipedia – Functional finance (A. Lerner)", "https://en.wikipedia.org/wiki/Functional_finance", D)
GTF = S("K. Górka, M. Łuszczyk, A. Thier, Teorie finansów publicznych w ujęciu historycznym, Studia i Prace WNEiZ US 47(1), 2017", "https://bazhum.muzhp.pl/media/texts/studia-i-prace-wydziau-nauk-ekonomicznych-i-zarzadzania/2017-tom-47-numer-1/studia_i_prace_wydzialu_nauk_ekonomicznych_i_zarzadzania-r2017-t47-n1-s21-33.pdf", D)
EUIS = S("Eurostat – Glossary: Institutional sector (ESA 2010)", "https://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Institutional_sector", D)
WFIN = S("Wikipedia – Financialization", "https://en.wikipedia.org/wiki/Financialization", D)
TON = S("Ustawa z 24.08.2006 o podatku tonażowym (Dz.U. 2006 nr 183 poz. 1353), ELI", "https://api.sejm.gov.pl/eli/acts/DU/2006/1353/text.html", D)
WBF = S("Wikipedia – Behavioral economics / behavioral finance", "https://en.wikipedia.org/wiki/Behavioral_economics", D)

LESSONS = [
    L(1, "Kategorie finansowe: przychód, dochód, wydatek, koszt",
      "Znać podział kategorii finansowych (przychodowe, dochodowe, wydatkowo-kosztowe, podatkowe, dłużne) i odróżniać przychód od dochodu oraz wydatek od kosztu; rozumieć, czym finanse behawioralne różnią się od klasycznego podejścia.",
      ["Kategorie finansowe", "Finanse behawioralne", "Amortyzacja", "Zysk księgowy", "Podatek od gier i podatek tonażowy"],
      [P171, WBF, TON],
      explain=[
          K("Finanse – nauka o przepływach pieniądza",
            "Finanse badają gromadzenie i wydatkowanie zasobów pieniężnych przez gospodarstwa domowe, przedsiębiorstwa, państwo i instytucje finansowe. Dzielą się m.in. na finanse publiczne, przedsiębiorstw, gospodarstw domowych i międzynarodowe. Łączą się z ekonomią, prawem, matematyką, socjologią, psychologią (finanse behawioralne) i etyką."),
          K("Pięć grup kategorii finansowych",
            "Przychodowe – cena, przychód pieniężny (np. ze sprzedaży). Dochodowe – dochód, zysk, procent, renta pieniężna. Wydatkowo-kosztowe – wydatek, koszt, amortyzacja. Podatkowe – podatki, opłaty, składki. Dłużne – pożyczka, kredyt, deficyt, dług."),
          W("Firma sprzedała towary za 500 tys. zł, a ich wytworzenie kosztowało 420 tys. zł. Jak nazwać 500 tys. i 80 tys. zł?",
            "500 tys. – przychód, 80 tys. – zysk (dochód)", "500 tys. – zysk, 80 tys. – przychód", "Obie kwoty to koszty",
            why="Przychód to wpływ ze sprzedaży, zysk – nadwyżka przychodu nad kosztami."),
          K("Wydatek a koszt",
            "Wydatek to rozchód pieniądza (np. zakup maszyny za 100 tys. zł dziś). Koszt to zużycie zasobów w danym okresie – maszynę rozlicza się w kosztach przez amortyzację, np. po 20 tys. zł rocznie przez 5 lat. Dlatego zysk księgowy w roku zakupu może być wysoki, mimo dużego wydatku."),
          K("Finanse behawioralne",
            "Klasyczne finanse zakładają racjonalnych inwestorów i efektywne rynki. Finanse behawioralne (R. Shiller, R. Thaler, D. Kahneman) pokazują błędy poznawcze: nadmierną pewność siebie, owczy pęd, awersję do strat, księgowość mentalną. Pomagają wyjaśnić bańki i anomalie cenowe."),
          K("Kategorie podatkowe – podatki sektorowe",
            "Obok PIT, CIT i VAT istnieją podatki dla wybranych branż. Podatek od gier (ustawa o grach hazardowych z 2009 r.) płacą organizatorzy loterii, zakładów i kasyn – od wpływów lub od różnicy między stawkami a wygranymi, ze stawkami zależnymi od rodzaju gry. Podatek tonażowy (ustawa z 2006 r.) armator może wybrać zamiast podatku dochodowego – liczy się go od zryczałtowanego przychodu zależnego od pojemności netto statków, a nie od faktycznego zysku."),
          PF("Każdy wydatek przedsiębiorstwa jest w tym samym roku jego kosztem.", False,
             why="Np. zakup maszyny trafia do kosztów stopniowo przez amortyzację."),
      ],
      mech=[
          KT("Do której grupy kategorii finansowych?",
             {"Przychodowe": ["Cena sprzedanego towaru", "Wpływy ze sprzedaży usług"],
              "Dochodowe": ["Zysk netto spółki", "Odsetki od lokaty"],
              "Wydatkowo-kosztowe": ["Odpis amortyzacyjny", "Zapłata za surowce"],
              "Dłużne": ["Kredyt hipoteczny", "Deficyt budżetu państwa"]},
             why="Podział kategorii finansowych według S. Owsiaka."),
          LN("Ułóż drogę od sprzedaży do zysku.",
             ["Sprzedaż towarów po ustalonej cenie", "Powstaje przychód", "Od przychodu odejmuje się koszty", "Powstaje zysk brutto", "Po zapłacie podatku – zysk netto"],
             why="Zysk to nadwyżka przychodów nad kosztami."),
          W("Inwestor trzyma akcje, które straciły 40%, bo „nie sprzeda ze stratą”. Jaki błąd opisują finanse behawioralne?",
            "Awersję do strat (efekt dyspozycji)", "Racjonalne oczekiwania", "Dywersyfikację",
            why="Ludzie zbyt długo trzymają przegrywające inwestycje."),
          W("Dlaczego amortyzacja to koszt, ale nie wydatek w danym roku?",
            "To rozłożenie wcześniejszego wydatku na lata użytkowania", "Bo jest podatkiem", "Bo zwiększa przychód",
            why="Pieniądz wydano w chwili zakupu."),
          M("Które pojęcia należą do kategorii dochodowych?",
            ["Zysk", "Procent", "Renta pieniężna", "Kredyt"], [0, 1, 2],
            why="Kredyt to kategoria dłużna."),
          PF("Finanse behawioralne kwestionują założenie pełnej racjonalności inwestorów.", True,
             why="Opierają się na badaniach psychologicznych."),
      ],
      calc=[
          LB("Przychód 800 tys. zł, koszty 650 tys. zł. Ile wynosi zysk brutto (tys. zł)?",
             150, "800-650", ["800 − 650 = 150 tys. zł"], unit="tys. zł"),
          LB("Podatek CIT 19%. Ile wynosi zysk netto (tys. zł)?",
             121.5, "150*0.81", ["150 · 0,81 = 121,5 tys. zł"], unit="tys. zł"),
          LB("Maszyna kosztuje 100 tys. zł, okres użytkowania 5 lat. Ile wynosi roczna amortyzacja liniowa (tys. zł)?",
             20, "100/5", ["100 / 5 = 20 tys. zł"], unit="tys. zł"),
          LB("Firma ma przychód 300 tys. zł i koszty bez amortyzacji 200 tys. zł. Ile wynosi zysk po amortyzacji 20 tys. zł (tys. zł)?",
             80, "300-200-20", ["300 − 200 − 20 = 80 tys. zł"], unit="tys. zł"),
          LB("W tym samym roku firma wydała 100 tys. zł na maszynę. Ile wynosi saldo przepływów pieniężnych (przychód − wydatki, tys. zł)?",
             0, "300-200-100", ["300 − 200 − 100 = 0 – zysk dodatni, ale gotówki nie przybyło"], unit="tys. zł"),
          LB("Rentowność sprzedaży = zysk netto / przychód. Zysk 121,5 tys., przychód 800 tys. Ile wynosi (%; zaokrąglij do 0,1)?",
             15.2, "121.5/800*100", ["121,5 / 800 ≈ 15,2%"], unit="%"),
      ],
      case=[
          PR("Piekarnia w 2026 r. sprzedała pieczywo za 1,2 mln zł, poniosła koszty bieżące 0,9 mln zł i kupiła nowy piec za 0,4 mln zł, amortyzowany przez 10 lat. Właściciel dziwi się, że „ma zysk, a na koncie brakuje pieniędzy”.",
             W("Ile wynosi zysk przed opodatkowaniem?",
               "260 tys. zł", "300 tys. zł", "Minus 100 tys. zł",
               why="1,2 mln − 0,9 mln − 0,04 mln amortyzacji = 0,26 mln zł."),
             W("Dlaczego brakuje gotówki?",
               "Wydatek na piec (400 tys.) jest dużo większy niż jego roczny koszt (40 tys.)", "Bo przychód był niższy od kosztów", "Bo amortyzacja jest wydatkiem",
               why="Wydatek i koszt rozkładają się różnie w czasie."),
             PF("Rachunek zysków i strat nie pokazuje w pełni przepływów pieniężnych.", True,
                why="Do tego służy rachunek przepływów pieniężnych."),
          ),
          PR("W 2021 r. wielu początkujących inwestorów kupowało akcje modnych spółek, bo „wszyscy na nich zarabiają”, nie sprawdzając wyników firm. Po spadkach część sprzedała akcje w panice, a część trzymała je mimo dużych strat.",
             W("Jakie zjawisko opisuje kupowanie, bo „wszyscy kupują”?",
               "Owczy pęd", "Dywersyfikację", "Arbitraż",
               why="To efekt naśladowania innych."),
             W("Która dziedzina finansów najlepiej opisuje takie zachowania?",
               "Finanse behawioralne", "Klasyczna teoria finansów publicznych", "Rachunkowość podatkowa",
               why="Bada psychologiczne błędy inwestorów."),
             PF("Trzymanie akcji ze stratą tylko po to, by „się odegrać”, jest zgodne z modelem racjonalnego inwestora.", False,
                why="Liczą się przyszłe perspektywy, a nie cena zakupu."),
          ),
      ]),

    L(2, "Kategorie dłużne: pożyczka, kredyt, deficyt i dług",
      "Odróżniać pożyczkę (kodeks cywilny) od kredytu bankowego (Prawo bankowe), znać zasady działania instytucji pożyczkowych oraz rozumieć związek deficytu ze wzrostem długu.",
      ["Pożyczka a kredyt", "Instytucja pożyczkowa (firma pożyczkowa)", "Kredyt konsumencki i odsetki maksymalne", "Deficyt budżetowy i deficyt sektora finansów publicznych", "Dług publiczny"],
      [KC720, PBK, KNFIP],
      explain=[
          K("Pożyczka",
            "Art. 720 k.c.: dający pożyczkę przenosi na biorącego własność pieniędzy (lub rzeczy oznaczonych co do gatunku), a biorący zwraca tę samą ilość. Pożyczki może udzielić każdy (także znajomy), może być nieodpłatna, a cel jest dowolny. Pożyczka powyżej 1000 zł wymaga formy dokumentowej (np. e-maila) – dla celów dowodowych."),
          K("Kredyt bankowy",
            "Art. 69 Prawa bankowego: bank oddaje do dyspozycji kwotę na określony cel, a kredytobiorca zwraca ją z odsetkami i prowizją. Kredytu udziela bank (lub SKOK), umowa musi być na piśmie i określać cel, a bank może kontrolować wykorzystanie środków. Kredyt jest zawsze odpłatny."),
          W("Kolega pożycza ci 2000 zł na wakacje bez odsetek. Co to za umowa?",
            "Pożyczka", "Kredyt bankowy", "Leasing",
            why="Pożyczki może udzielić każdy, także nieodpłatnie."),
          K("Instytucje pożyczkowe",
            "Firmy pozabankowe udzielające kredytu konsumenckiego (np. „chwilówek”) muszą być w rejestrze KNF, działać jako spółka akcyjna lub z o.o. z radą nadzorczą i mieć co najmniej 1 mln zł kapitału; od 2024 r. są pod nadzorem KNF. Ustawa ogranicza koszty pozaodsetkowe, a kodeks cywilny – odsetki maksymalne."),
          K("Deficyt i dług",
            "Deficyt to nadwyżka wydatków nad dochodami w danym roku (strumień). Dług to suma niespłaconych zobowiązań (zasób) – rośnie o deficyt. Ta sama zależność dotyczy państwa, firmy i gospodarstwa domowego."),
          PF("Pożyczki pieniężnej może udzielić osoba fizyczna, a kredytu – co do zasady tylko bank.", True,
             why="Kredyt to czynność bankowa."),
      ],
      mech=[
          KT("Pożyczka czy kredyt bankowy?",
             {"Pożyczka": ["Babcia pożycza wnukowi 500 zł", "Spółka pożycza pieniądze innej spółce z grupy"],
              "Kredyt bankowy": ["Bank finansuje zakup mieszkania", "Bank udziela firmie kredytu obrotowego na zakup towarów"]},
             why="Różnią się podstawą prawną, podmiotem i celem."),
          LN("Ułóż związek deficytu i długu.",
             ["Wydatki państwa przekraczają dochody", "Powstaje deficyt budżetowy", "Państwo emituje obligacje", "Rośnie dług publiczny", "Rosną przyszłe wydatki na odsetki"],
             why="Deficyt (strumień) zwiększa dług (zasób)."),
          W("Czym różni się deficyt od długu?",
            "Deficyt to strumień w danym roku, dług – zasób narosłych zobowiązań", "To synonimy", "Dług to strumień, deficyt – zasób",
            why="Dług rośnie o kolejne deficyty."),
          W("Która cecha jest obowiązkowa w umowie kredytu, a nie w umowie pożyczki?",
            "Określenie celu", "Odpłatność zerowa", "Forma ustna",
            why="Art. 69 Prawa bankowego wymaga celu kredytu."),
          M("Jakie wymogi musi spełnić instytucja pożyczkowa?",
            ["Wpis do rejestru KNF", "Kapitał zakładowy co najmniej 1 mln zł", "Forma spółki akcyjnej lub z o.o. z radą nadzorczą", "Licencja bankowa"], [0, 1, 2],
            why="Instytucja pożyczkowa nie jest bankiem."),
          PF("Umowa pożyczki na 3000 zł zawarta ustnie jest nieważna.", False,
             why="Forma dokumentowa jest zastrzeżona dla celów dowodowych."),
      ],
      calc=[
          LB("Kredyt 10 000 zł na rok, oprocentowanie 9%, prowizja 2%. Ile wynosi łączny koszt (zł)?",
             1100, "10000*0.09+10000*0.02", ["900 + 200 = 1 100 zł"], unit="zł"),
          LB("Dług państwa na początku roku 1 500 mld zł, deficyt 270 mld zł. Ile wynosi dług na koniec roku (mld zł)?",
             1770, "1500+270", ["1 500 + 270 = 1 770 mld zł"], unit="mld zł"),
          LB("Stopa referencyjna NBP 3,75%. Ile wynoszą odsetki maksymalne: 2 · (stopa ref. + 3,5) (%)?",
             14.5, "2*(3.75+3.5)", ["2 · 7,25 = 14,5%"], unit="%"),
          LB("Pożyczka 2 000 zł na rok przy odsetkach maksymalnych 14,5%. Ile maksymalnie wyniosą odsetki (zł)?",
             290, "2000*0.145", ["2 000 · 0,145 = 290 zł"], unit="zł"),
          LB("Dochody budżetu 647,2 mld zł, wydatki 918,9 mld zł. Ile wynosi deficyt (mld zł)?",
             271.7, "918.9-647.2", ["918,9 − 647,2 = 271,7 mld zł"], unit="mld zł"),
          LB("Kapitał instytucji pożyczkowej to 1 mln zł, a pożyczki – 8 mln zł. Ile razy pożyczki przekraczają kapitał?",
             8, "8/1", ["8 / 1 = 8"], unit="razy"),
      ],
      case=[
          PR("Pan Marek potrzebuje 3000 zł na naprawę samochodu. Bank proponuje kredyt gotówkowy z oprocentowaniem 10% i prowizją 3%, a firma pożyczkowa – pożyczkę „od ręki” na 30 dni z wysoką opłatą przygotowawczą. Kuzyn oferuje pożyczkę bez odsetek.",
             W("Która oferta to umowa pożyczki z kodeksu cywilnego bez odpłatności?",
               "Oferta kuzyna", "Oferta banku", "Żadna",
               why="Pożyczka może być nieodpłatna."),
             W("Co powinien sprawdzić, zanim weźmie pożyczkę w firmie pożyczkowej?",
               "Czy firma jest w rejestrze instytucji pożyczkowych KNF i ile wynosi RRSO", "Czy firma ma licencję bankową", "Czy oferuje ubezpieczenie OC",
               why="Legalna instytucja pożyczkowa musi być w rejestrze KNF."),
             PF("Przy pożyczce od kuzyna na 3000 zł warto mieć potwierdzenie w formie dokumentowej.", True,
                why="Ułatwia to dowód w razie sporu (powyżej 1000 zł)."),
          ),
          PR("Ustawa budżetowa na 2026 r. przewiduje dochody 647,2 mld zł i wydatki 918,9 mld zł. Krytycy ostrzegają, że kolejne duże deficyty zwiększą dług i koszty jego obsługi.",
             W("Ile wynosi planowany deficyt budżetu państwa?",
               "271,7 mld zł", "647,2 mld zł", "918,9 mld zł",
               why="918,9 − 647,2 = 271,7 mld zł."),
             W("Jak deficyt wpływa na dług?",
               "Zwiększa go o kwotę finansowaną nowymi pożyczkami", "Zmniejsza go", "Nie ma wpływu",
               why="Deficyt finansuje się emisją długu."),
             PF("Deficyt budżetu państwa i deficyt całego sektora finansów publicznych to zawsze ta sama kwota.", False,
                why="Sektor obejmuje też samorządy, fundusze i inne jednostki."),
          ),
      ]),

    L(3, "Teorie finansów: od taniego państwa do finansów funkcjonalnych",
      "Porównywać klasyczną i liberalną teorię finansów (tanie państwo, neutralność, zrównoważony budżet) z teorią finansowania antycyklicznego i finansami funkcjonalnymi A. Lernera oraz rozumieć pojęcie polityki finansowej.",
      ["Klasyczna i liberalna teoria finansów", "Teoria finansowania antycyklicznego (finanse funkcjonalne)", "Polityka finansowa", "Reguły podatkowe A. Smitha"],
      [GTF, WFF, P304, P307],
      explain=[
          K("Teoria klasyczna",
            "A. Smith i J.B. Say: państwo ma pełnić tylko funkcje klasyczne (obrona, sądy, bezpieczeństwo, część dóbr publicznych), wydawać mało i utrzymywać zrównoważony budżet. Podatki mają być neutralne – nie zmieniać decyzji rynkowych ani podziału dochodów – i zgodne z regułami Smitha: równość, pewność, dogodność, taniość poboru."),
          K("Teoria liberalna",
            "Nawiązuje do klasyków i zakłada maksymalne ograniczenie roli państwa, by finanse publiczne nie zakłócały mechanizmu rynkowego. Współcześnie bliskie są jej m.in. ekonomia podaży i szkoła wyboru publicznego (krytyka rozrostu państwa)."),
          W("Który postulat pasuje do teorii klasycznej?",
            "Zrównoważony budżet i neutralność podatków", "Deficyt w każdej recesji jako narzędzie stabilizacji", "Finansowanie wydatków emisją pieniądza",
            why="Klasycy zalecali tanie państwo i neutralne podatki."),
          K("Finansowanie antycykliczne",
            "Po Wielkim Kryzysie i „Ogólnej teorii” Keynesa (1936) budżet stał się narzędziem stabilizacji: w recesji – wyższe wydatki i niższe podatki (deficyt), w boomie – ograniczenie deficytu lub nadwyżka. A. Lerner (1943) – finanse funkcjonalne: o budżecie decydują jego skutki (pełne zatrudnienie, stabilne ceny), a nie zasada równowagi."),
          K("Polityka finansowa",
            "Obejmuje politykę pieniężną (bank centralny) i fiskalną (rząd i parlament). Cele: stabilność cen, wzrost, zatrudnienie, sprawiedliwy podział. Narzędzia muszą być skoordynowane – policy mix."),
          PF("Według finansów funkcjonalnych celem budżetu jest przede wszystkim jego zrównoważenie.", False,
             why="Lerner uważał, że liczą się skutki dla gospodarki."),
      ],
      mech=[
          KT("Która teoria?",
             {"Klasyczna i liberalna": ["Tanie państwo", "Neutralność podatków", "Zasada zrównoważonego budżetu"],
              "Finansowanie antycykliczne": ["Deficyt w recesji", "Nadwyżka w okresie boomu", "Budżet jako narzędzie pełnego zatrudnienia"]},
             why="Dwa przeciwstawne podejścia do roli budżetu."),
          LN("Ułóż przebieg polityki antycyklicznej w recesji.",
             ["Popyt i produkcja spadają", "Rząd zwiększa wydatki i obniża podatki", "Rośnie deficyt budżetowy", "Popyt odbudowuje się przez mnożnik", "W ożywieniu rząd ogranicza deficyt"],
             why="Budżet działa przeciwnie do cyklu."),
          W("Kto sformułował zasadę finansów funkcjonalnych?",
            "A. Lerner", "A. Smith", "J.B. Say",
            why="Abba Lerner, 1943."),
          W("Dlaczego klasycy postulowali neutralność podatków?",
            "By nie zakłócać decyzji rynkowych i podziału dochodów", "By zwiększyć deficyt", "By stabilizować koniunkturę",
            why="Rynek miał decydować o alokacji zasobów."),
          M("Które instrumenty należą do polityki fiskalnej?",
            ["Stawki podatków", "Wydatki budżetowe", "Zarządzanie długiem publicznym", "Stopa referencyjna NBP"], [0, 1, 2],
            why="Stopa referencyjna to narzędzie polityki pieniężnej."),
          PF("Automatyczne stabilizatory działają zgodnie z ideą finansowania antycyklicznego.", True,
             why="W recesji samoczynnie zwiększają deficyt."),
      ],
      calc=[
          LB("Luka popytowa wynosi 40 mld zł, mnożnik wydatków 2. O ile rząd powinien zwiększyć wydatki (mld zł)?",
             20, "40/2", ["40 / 2 = 20 mld zł"], unit="mld zł"),
          LB("Krańcowa skłonność do konsumpcji 0,75. Ile wynosi mnożnik wydatków 1/(1 − KSK)?",
             4, "1/(1-0.75)", ["1 / 0,25 = 4"], unit=""),
          LB("Przy tym mnożniku wzrost wydatków o 10 mld zł zwiększa popyt o ile (mld zł)?",
             40, "10*4", ["10 · 4 = 40 mld zł"], unit="mld zł"),
          LB("Mnożnik podatkowy = −KSK/(1 − KSK). Ile wynosi przy KSK 0,75 (podaj wartość bezwzględną)?",
             3, "0.75/0.25", ["0,75 / 0,25 = 3"], unit=""),
          LB("Obniżka podatków o 10 mld zł zwiększa popyt o ile (mld zł)?",
             30, "10*3", ["10 · 3 = 30 mld zł – mniej niż ten sam wzrost wydatków"], unit="mld zł"),
          LB("Wydatki państwa 900 mld zł, PKB 4 000 mld zł. Ile procent PKB stanowią (%)?",
             22.5, "900/4000*100", ["900 / 4 000 = 22,5%"], unit="%"),
      ],
      case=[
          PR("W 2020 r. większość państw UE zawiesiła reguły fiskalne i finansowała pomoc dla firm i pracowników ogromnymi deficytami. Część ekonomistów porównywała to do postulatów Keynesa i Lernera, inni ostrzegali przed długiem i inflacją.",
             W("Do której teorii nawiązywała ta polityka?",
               "Finansowania antycyklicznego (finanse funkcjonalne)", "Klasycznej teorii taniego państwa", "Teorii neutralności podatków",
               why="Deficyt świadomie użyto do stabilizacji."),
             W("Jaki argument podnieśliby zwolennicy podejścia klasycznego?",
               "Rosnący dług obciąży przyszłe pokolenia i wyprze inwestycje", "Deficyt powinien być jeszcze większy", "Podatki należy podnieść w recesji",
               why="Klasycy postulują zrównoważony budżet."),
             PF("Po kryzysie powrót do reguł fiskalnych jest zgodny z ideą finansowania antycyklicznego.", True,
                why="W ożywieniu deficyt powinien maleć."),
          ),
          PR("Kandydat na posła proponuje: „Państwo powinno wydawać tylko na wojsko, policję i sądy, a podatek powinien być jednakowy i prosty, bez ulg”.",
             W("Do której teorii nawiązuje ten postulat?",
               "Klasycznej i liberalnej teorii finansów", "Finansów funkcjonalnych", "Teorii optymalnego obszaru walutowego",
               why="Tanie państwo i neutralność podatków."),
             W("Którą z reguł podatkowych A. Smitha realizuje prosty podatek bez ulg?",
               "Pewność i taniość poboru", "Progresję", "Redystrybucję",
               why="Prosty podatek jest przewidywalny i tani w poborze."),
             PF("Taki program ogranicza funkcję redystrybucyjną finansów publicznych.", True,
                why="Brak transferów i ulg zmniejsza redystrybucję."),
          ),
      ]),

    L(4, "Teorie pieniądza: szkoła bankowa i obiegowa, Keynes i Baumol–Tobin",
      "Znać spór szkoły obiegowej i bankowej oraz ustawę Peela (1844), porównać teorię ilościową, keynesowską teorię preferencji płynności i model Baumola–Tobina oraz liczyć optymalny zasób gotówki.",
      ["Teoria bankowa i obiegowa (spór szkoły bankowej z obiegową)", "Model Baumola–Tobina (transakcyjny popyt na pieniądz)", "Model Baumola–Tobina – wzór", "Teoria ilościowa pieniądza (równanie wymiany Fishera)", "Popyt na pieniądz (preferencja płynności)", "Monetaryzm"],
      [WCS, WBT, CRB, P284],
      explain=[
          K("Szkoła obiegowa a bankowa",
            "W XIX-wiecznej Anglii szkoła obiegowa (lord Overstone, R. Torrens) twierdziła, że nadmierna emisja banknotów powoduje inflację, więc emisja powinna być w pełni pokryta złotem. Szkoła bankowa (T. Tooke, J. Fullarton) – że emisję ogranicza sama potrzeba obrotu i wymienialność na złoto, a depozyty działają jak banknoty."),
          K("Ustawa Peela (1844)",
            "Bank Charter Act przyjął pogląd szkoły obiegowej: Bank Anglii podzielono na departament emisyjny i bankowy, a emisję ponad limit trzeba było pokryć złotem. Depozytów nie objęto, więc kredyt i tak się rozszerzał; w kryzysach 1847, 1857 i 1866 ustawę zawieszano."),
          W("Co według szkoły obiegowej było główną przyczyną inflacji?",
            "Nadmierna emisja banknotów", "Wzrost płac", "Podatki",
            why="Postulowano pełne pokrycie emisji złotem."),
          K("Popyt na pieniądz: od Fishera do Keynesa",
            "Teoria ilościowa (M·V = P·Y): pieniądz służy transakcjom, a V jest stabilne. Keynes: ludzie trzymają pieniądz z motywu transakcyjnego, przezorności i spekulacyjnego, więc popyt na pieniądz zależy także od stopy procentowej. M. Friedman (monetaryzm): popyt na pieniądz jest stabilną funkcją dochodu permanentnego."),
          K("Model Baumola–Tobina",
            "Gospodarstwo domowe wybiera, jak często wypłacać pieniądze z rachunku: częste wypłaty kosztują (czas, opłata F), rzadkie oznaczają dużo gotówki bez odsetek. Optymalny przeciętny zasób gotówki M* = √(Y·F / (2i)) – rośnie z dochodem i kosztem wypłaty, maleje ze stopą procentową.",
            w="M* = √(Y·F / (2i))"),
          PF("W modelu Baumola–Tobina podwojenie dochodu podwaja przeciętny zasób gotówki.", False,
             why="Zasób rośnie z pierwiastkiem dochodu, czyli ok. 1,41 razy."),
      ],
      mech=[
          KT("Która teoria pieniądza?",
             {"Szkoła obiegowa": ["Pełne pokrycie banknotów złotem", "Ustawa Peela z 1844 r."],
              "Szkoła bankowa": ["Emisję ogranicza potrzeba obrotu", "Depozyty pełnią rolę pieniądza"],
              "Keynes": ["Motyw spekulacyjny", "Preferencja płynności"],
              "Baumol–Tobin": ["Koszt wypłaty a utracone odsetki", "Pierwiastek z dochodu"]},
             why="Kolejne teorie wyjaśniają popyt i podaż pieniądza."),
          LN("Ułóż rozumowanie z modelu Baumola–Tobina, gdy rośnie stopa procentowa.",
             ["Stopa procentowa rośnie", "Trzymanie gotówki staje się droższe", "Opłaca się częściej wypłacać mniejsze kwoty", "Przeciętny zasób gotówki spada", "Popyt na pieniądz maleje"],
             why="Popyt na pieniądz zależy od stopy procentowej."),
          W("Dlaczego ustawa Peela nie zapobiegła kryzysom?",
            "Nie objęła depozytów i kredytu bankowego", "Bo zakazała emisji banknotów", "Bo zniosła standard złota",
            why="Kredyt rozszerzał się poza kontrolą."),
          W("Który motyw trzymania pieniądza według Keynesa zależy od oczekiwań co do stóp procentowych?",
            "Spekulacyjny", "Transakcyjny", "Przezornościowy",
            why="Przy oczekiwanym spadku cen obligacji ludzie wolą gotówkę."),
          M("Od czego zależy optymalny zasób gotówki w modelu Baumola–Tobina?",
            ["Od dochodu (wydatków)", "Od kosztu jednej wypłaty", "Od stopy procentowej", "Od kursu walutowego"], [0, 1, 2],
            why="M* = √(Y·F / (2i))."),
          PF("Bankomaty i płatności kartą obniżają koszt F i zmniejszają przeciętny zasób gotówki.", True,
             why="Niższe F zmniejsza M*."),
      ],
      calc=[
          LB("Y = 48 000 zł, F = 6 zł, i = 4%. Ile wynosi M* (zł; zaokrąglij do 1)?",
             1897, "(48000*6/(2*0.04))**0.5", ["√(48 000 · 6 / 0,08) = √3 600 000 ≈ 1 897 zł"], unit="zł"),
          LB("Ile wynosi optymalna liczba wypłat w roku N* = Y / (2M*) (zaokrąglij do 0,1)?",
             12.6, "48000/(2*(48000*6/0.08)**0.5)", ["48 000 / 3 794 ≈ 12,6"], unit=""),
          LB("Stopa procentowa rośnie do 16%. Ile wynosi nowe M* (zł; zaokrąglij do 1)?",
             949, "(48000*6/(2*0.16))**0.5", ["√(288 000 / 0,32) = √900 000 ≈ 949 zł – o połowę mniej"], unit="zł"),
          LB("Dochód rośnie 4 razy (i = 4%). Ile razy rośnie M*?",
             2, "4**0.5", ["√4 = 2"], unit="razy"),
          LB("M = 500, V = 6, Y = 1 500 (realne). Ile wynosi poziom cen P?",
             2, "500*6/1500", ["P = M·V / Y = 3 000 / 1 500 = 2"], unit=""),
          LB("M rośnie o 8%, Y o 3%, V stałe. Ile w przybliżeniu wynosi inflacja (%)?",
             5, "8-3", ["%ΔP ≈ 8 − 3 = 5%"], unit="%"),
      ],
      case=[
          PR("W 1847 r. w Anglii wybuchła panika: Bank Anglii, ograniczony limitem emisji z ustawy Peela, nie mógł udzielać kredytu w banknotach. Rząd zawiesił ustawę, Bank zwiększył emisję i panika ustała.",
             W("Czyje argumenty wzmocnił ten przebieg wydarzeń?",
               "Szkoły bankowej – sztywny limit emisji szkodzi w kryzysie", "Szkoły obiegowej", "Monetarystów",
               why="Elastyczna emisja okazała się potrzebna."),
             W("Jaką funkcję banku centralnego ilustruje zwiększenie emisji w panice?",
               "Pożyczkodawcy ostatniej instancji", "Emitenta obligacji skarbowych", "Nadzoru nad giełdą",
               why="W panice bank centralny dostarcza płynności."),
             PF("Później W. Bagehot sformułował zasady udzielania pomocy w panice („Lombard Street”, 1873).", True,
                why="To klasyczne zasady pożyczkodawcy ostatniej instancji."),
          ),
          PR("Pani Ola wydaje 4 000 zł miesięcznie. Kiedyś wypłacała całą pensję gotówką na początku miesiąca. Teraz płaci kartą, a gotówkę wypłaca rzadko w bankomacie bez opłat. Na koncie oszczędnościowym dostaje 5%.",
             W("Co według modelu Baumola–Tobina dzieje się z jej przeciętnym zasobem gotówki?",
               "Maleje – koszt wypłaty spadł, a odsetki są wyższe", "Rośnie", "Nie zmienia się",
               why="Niższe F i wyższe i zmniejszają M*."),
             W("Jak zmiana zachowań wielu osób wpływa na popyt na pieniądz gotówkowy w gospodarce?",
               "Popyt na gotówkę maleje", "Popyt na gotówkę rośnie", "Brak wpływu",
               why="Mniej gotówki trzymanej przez gospodarstwa domowe."),
             PF("Według teorii ilościowej zmiana nawyków płatniczych może zmienić prędkość obiegu pieniądza.", True,
                why="V zależy m.in. od technologii płatności."),
          ),
      ]),

    L(5, "Sektory gospodarki, monetyzacja i finansjalizacja",
      "Znać sektory instytucjonalne ESA 2010 i obieg dochodu między nimi, rozumieć wskaźnik monetyzacji gospodarki jako miarę głębokości systemu finansowego oraz zjawisko finansjalizacji.",
      ["Sektory instytucjonalne gospodarki (ESA 2010)", "Monetyzacja gospodarki", "Finansjalizacja", "Model okrężnego obiegu w gospodarce otwartej z państwem", "Agregaty pieniężne (NBP)"],
      [EUIS, P272, WFIN],
      explain=[
          K("Sektory instytucjonalne",
            "Rachunki narodowe (ESA 2010) dzielą gospodarkę na: S.11 – przedsiębiorstwa niefinansowe, S.12 – instytucje finansowe, S.13 – instytucje rządowe i samorządowe, S.14 – gospodarstwa domowe, S.15 – instytucje niekomercyjne działające na rzecz gospodarstw domowych; S.2 – reszta świata. Sektory S.11 i S.14 tworzą głównie sferę realną, S.12 – sferę finansową."),
          W("Do którego sektora należy fundusz inwestycyjny?",
            "S.12 – instytucje finansowe", "S.11 – przedsiębiorstwa niefinansowe", "S.13 – instytucje rządowe i samorządowe",
            why="Fundusze to pośrednicy finansowi."),
          K("Obieg dochodu",
            "Gospodarstwa domowe oferują pracę i kapitał, otrzymują dochody, płacą podatki i oszczędzają. Oszczędności trafiają przez sektor finansowy do firm i państwa (kredyty, obligacje, akcje). Państwo pobiera podatki i wypłaca transfery. Z resztą świata łączą nas eksport, import i przepływy kapitału."),
          K("Monetyzacja gospodarki",
            "Wskaźnik monetyzacji = podaż pieniądza (zwykle M3) / PKB nominalny. Pokazuje, jak głęboko gospodarka korzysta z pieniądza bankowego: rośnie wraz z ubankowieniem i zaufaniem do banków. Kraje rozwinięte mają zwykle wyższy wskaźnik niż wschodzące.",
            w="M3 / PKB · 100%"),
          K("Finansjalizacja",
            "Od lat 80. XX w. rośnie znaczenie sektora finansowego: większy udział w dochodzie narodowym, wyższe zadłużenie gospodarstw domowych i firm, nacisk na wartość dla akcjonariuszy. Krytycy wiążą ją z niestabilnością i kryzysem 2008 r."),
          PF("Wysoki wskaźnik monetyzacji oznacza wysoką inflację.", False,
             why="Mierzy głębokość systemu finansowego, a nie tempo wzrostu cen."),
      ],
      mech=[
          KT("Do którego sektora ESA 2010?",
             {"S.11 – przedsiębiorstwa niefinansowe": ["Huta stali", "Sieć sklepów spożywczych"],
              "S.12 – instytucje finansowe": ["Bank komercyjny", "Zakład ubezpieczeń"],
              "S.13 – instytucje rządowe i samorządowe": ["Urząd gminy", "ZUS"],
              "S.14 – gospodarstwa domowe": ["Rodzina Kowalskich", "Rolnik indywidualny"]},
             why="Sektory grupują podmioty o podobnym zachowaniu gospodarczym."),
          LN("Ułóż drogę oszczędności gospodarstw domowych do inwestycji firm.",
             ["Gospodarstwo domowe oszczędza część dochodu", "Wpłaca środki do banku lub funduszu (S.12)", "Instytucja finansowa udziela kredytu lub kupuje obligacje", "Przedsiębiorstwo (S.11) otrzymuje finansowanie", "Firma kupuje maszyny"],
             why="Sektor finansowy pośredniczy między sferą realną a oszczędzającymi."),
          W("Co mierzy wskaźnik M3/PKB?",
            "Stopień monetyzacji gospodarki", "Stopę inflacji", "Deficyt budżetowy",
            why="To relacja podaży pieniądza do PKB."),
          W("Które zjawisko jest przejawem finansjalizacji?",
            "Rosnący udział sektora finansowego w dochodzie narodowym", "Spadek zadłużenia gospodarstw domowych", "Powrót do handlu wymiennego",
            why="Finansjalizacja to wzrost roli finansów."),
          M("Które jednostki należą do sektora instytucji rządowych i samorządowych (S.13)?",
            ["Ministerstwa", "Gminy i powiaty", "Fundusz Ubezpieczeń Społecznych", "Banki komercyjne"], [0, 1, 2],
            why="Banki należą do S.12."),
          PF("Reszta świata (S.2) obejmuje nierezydentów prowadzących transakcje z krajem.", True,
             why="Odpowiada przepływom ujętym w bilansie płatniczym."),
      ],
      calc=[
          LB("M3 = 2 400 mld zł, PKB nominalny = 4 000 mld zł. Ile wynosi wskaźnik monetyzacji (%)?",
             60, "2400/4000*100", ["2 400 / 4 000 = 60%"], unit="%"),
          LB("M3 rośnie o 10%, a PKB nominalny o 6%. Ile wyniesie nowy wskaźnik (%; zaokrąglij do 0,1)?",
             62.3, "2400*1.1/(4000*1.06)*100", ["2 640 / 4 240 ≈ 62,3%"], unit="%"),
          LB("Prędkość obiegu V = PKB / M3. Ile wynosi przy danych wyjściowych (zaokrąglij do 0,01)?",
             1.67, "4000/2400", ["4 000 / 2 400 ≈ 1,67"], unit=""),
          LB("Udział sektora finansowego w wartości dodanej wzrósł z 4% do 6%. O ile punktów procentowych?",
             2, "6-4", ["6 − 4 = 2 pkt proc."], unit="pkt proc."),
          LB("Gospodarstwa domowe mają dochód rozporządzalny 2 500 mld zł i konsumują 2 300 mld zł. Ile wynosi stopa oszczędności (%)?",
             8, "(2500-2300)/2500*100", ["200 / 2 500 = 8%"], unit="%"),
          LB("Dług gospodarstw domowych wynosi 900 mld zł, a PKB 4 000 mld zł. Ile procent PKB (%)?",
             22.5, "900/4000*100", ["900 / 4 000 = 22,5%"], unit="%"),
      ],
      case=[
          PR("Na początku lat 90. w Polsce wiele osób trzymało oszczędności w gotówce i w dolarach, a stosunek pieniądza do PKB był niski. W kolejnych dekadach rosła liczba rachunków bankowych, kart i kredytów, a wskaźnik monetyzacji wyraźnie wzrósł.",
             W("Co oznacza wzrost wskaźnika monetyzacji?",
               "Pogłębienie systemu finansowego i większe ubankowienie", "Wyższą inflację", "Spadek PKB",
               why="Więcej pieniądza bankowego względem PKB."),
             W("Który sektor ESA najbardziej się rozwinął w tym procesie?",
               "S.12 – instytucje finansowe", "S.15 – instytucje non-profit", "S.13 – instytucje rządowe",
               why="Banki i inne instytucje finansowe."),
             PF("Wysoka inflacja z początku lat 90. zniechęcała do trzymania oszczędności w złotych.", True,
                why="Realna wartość złotówki szybko spadała."),
          ),
          PR("Przed 2008 r. w USA i Wielkiej Brytanii szybko rósł udział usług finansowych w PKB, zadłużenie gospodarstw domowych i wartość instrumentów pochodnych. Po kryzysie wielu ekonomistów mówiło o „nadmiernej finansjalizacji”.",
             W("Jakie zjawisko opisano?",
               "Finansjalizację gospodarki", "Monetyzację długu publicznego", "Autarkię",
               why="Rosła rola sektora finansowego."),
             W("Jakie ryzyko niesie ono według krytyków?",
               "Większą podatność gospodarki na kryzysy finansowe", "Deflację w każdym roku", "Brak kredytu dla firm",
               why="Wysoka dźwignia i zależność od rynków finansowych."),
             PF("Finansjalizacja oznacza, że sektor finansowy przestaje pośredniczyć między oszczędzającymi a inwestorami.", False,
                why="Pośredniczy, ale jego rola i dochody stają się nieproporcjonalnie duże."),
          ),
      ]),
]
