# -*- coding: utf-8 -*-
# Zrozumienie – Podstawy finansów / Daty i chronologia
D = "2026-10-08"
NBP = S("Narodowy Bank Polski", "https://nbp.pl/", D)
NBPE = S("NBP – edukacja ekonomiczna", "https://nbp.pl/edukacja/", D)
FED = S("Board of Governors of the Federal Reserve System", "https://www.federalreserve.gov/", D)
ECB = S("Europejski Bank Centralny", "https://www.ecb.europa.eu/", D)
GPW = S("Giełda Papierów Wartościowych w Warszawie", "https://www.gpw.pl/", D)
KNF = S("Komisja Nadzoru Finansowego", "https://www.knf.gov.pl/", D)
BTC = S("S. Nakamoto, Bitcoin: A Peer-to-Peer Electronic Cash System (2008)", "https://bitcoin.org/bitcoin.pdf", D)

LESSONS = [
    L(1, "Od traktatu Kopernika do Fed (1526–1913)",
      "Umieszczać w czasie narodziny nowoczesnej myśli pieniężnej i bankowości centralnej i rozumieć, jak każde wydarzenie odpowiadało na problem swojej epoki.",
      ["1526 – „Monetae cudendae ratio” M. Kopernika", "1694 – założenie Banku Anglii", "1873 – „Lombard Street” W. Bagehota", "1913 – utworzenie Systemu Rezerwy Federalnej"],
      [NBPE, FED],
      explain=[
          K("1526 – Kopernik o monecie",
            "W „Monetae cudendae ratio” Kopernik opisał, jak psucie monety (zmniejszanie zawartości srebra) prowadzi do drożyzny i wypierania dobrej monety przez złą. Postulował jednolitą, rzetelną monetę dla Prus Królewskich i Korony. To jedno z pierwszych ujęć ilościowej teorii pieniądza."),
          K("1694 – Bank Anglii",
            "Powstał jako prywatna spółka, by pożyczyć królowi Wilhelmowi III pieniądze na wojnę z Francją. Z czasem zyskał monopol emisji banknotów w Anglii i stał się wzorem banku centralnego. Znacjonalizowany w 1946 r., niezależny w polityce pieniężnej od 1997 r."),
          W("Po co pierwotnie utworzono Bank Anglii?",
            "By finansować wydatki wojenne króla", "By walczyć z inflacją", "By nadzorować giełdę",
            why="Bank pożyczył koronie 1,2 mln funtów na wojnę."),
          K("1873 – „Lombard Street”",
            "Walter Bagehot, po panice z 1866 r. (upadek domu bankowego Overend, Gurney & Co.), opisał zasady działania Banku Anglii w kryzysie: pożyczać swobodnie, pod dobre zabezpieczenie, po karnej stopie. Tak powstała doktryna pożyczkodawcy ostatniej instancji."),
          K("1913 – Fed",
            "Po panice 1907 r., którą opanował prywatnie J.P. Morgan, Kongres USA uchwalił Federal Reserve Act (23.12.1913). Utworzono zdecentralizowany system 12 banków regionalnych i Radę w Waszyngtonie – jako pożyczkodawcę ostatniej instancji i emitenta elastycznej waluty."),
          PF("Wszystkie cztery wydarzenia były reakcją na kryzys lub problem z pieniądzem.", True,
             why="Psucie monety, potrzeby wojenne, panika 1866 i panika 1907."),
      ],
      mech=[
          LN("Ułóż wydarzenia chronologicznie.",
             ["Traktat Kopernika o monecie", "Założenie Banku Anglii", "Publikacja „Lombard Street”", "Federal Reserve Act", "Nacjonalizacja Banku Anglii"],
             why="1526 → 1694 → 1873 → 1913 → 1946."),
          KT("Jaki problem rozwiązywało wydarzenie?",
             {"Psucie pieniądza": ["Traktat Kopernika 1526"],
              "Finansowanie państwa": ["Założenie Banku Anglii 1694"],
              "Paniki bankowe": ["„Lombard Street” 1873", "Utworzenie Fed 1913"]},
             why="Każde wydarzenie było odpowiedzią na konkretny problem."),
          W("Która panika bezpośrednio doprowadziła do powstania Fed?",
            "Panika 1907 r.", "Panika 1866 r.", "Krach 1929 r.",
            why="Po 1907 r. uznano, że USA potrzebują banku centralnego."),
          W("Co łączy „Lombard Street” i powstanie Fed?",
            "Idea instytucji, która w panice dostarcza płynności bankom", "Wprowadzenie euro", "Podatek od transakcji",
            why="Fed miał pełnić funkcję opisaną przez Bagehota."),
          M("Które zdania są prawdziwe?",
            ["Bank Anglii był pierwotnie prywatną spółką", "Fed składa się z 12 banków regionalnych i Rady", "Kopernik pisał o skutkach psucia monety", "Fed powstał przed Bankiem Anglii"], [0, 1, 2],
            why="Bank Anglii (1694) jest o ponad 200 lat starszy od Fed (1913)."),
          PF("Doktryna pożyczkodawcy ostatniej instancji została sformułowana przed powstaniem Fed.", True,
             why="„Lombard Street” ukazała się 40 lat wcześniej."),
      ],
      calc=[
          LB("Ile lat dzieli traktat Kopernika (1526) od założenia Banku Anglii (1694)?",
             168, "1694-1526", ["1694 − 1526 = 168"], unit="lat"),
          LB("Ile lat dzieli „Lombard Street” (1873) od utworzenia Fed (1913)?",
             40, "1913-1873", ["1913 − 1873 = 40"], unit="lat"),
          LB("Ile lat minęło od założenia Banku Anglii (1694) do jego nacjonalizacji (1946)?",
             252, "1946-1694", ["1946 − 1694 = 252"], unit="lat"),
          LB("Ile lat dzieli panikę 1866 r. od publikacji „Lombard Street” (1873)?",
             7, "1873-1866", ["1873 − 1866 = 7"], unit="lat"),
          LB("Ile lat od utworzenia Fed (1913) do 2026 r.?",
             113, "2026-1913", ["2026 − 1913 = 113"], unit="lat"),
          LB("Bank Anglii pożyczył królowi 1,2 mln funtów na 8% rocznie. Ile wynosiły roczne odsetki (tys. funtów)?",
             96, "1200*0.08", ["1200 · 8% = 96 tys. funtów"], unit="tys. funtów"),
      ],
      case=[
          PR("Październik 1907 r.: upadek prób spekulacji akcjami miedziowymi wywołuje run na nowojorskie trust companies. Nie ma banku centralnego. J.P. Morgan organizuje grupę bankierów, którzy pożyczają pieniądze zagrożonym instytucjom.",
             W("Jaką funkcję pełnił w praktyce J.P. Morgan?",
               "Prywatnego pożyczkodawcy ostatniej instancji", "Agencji ratingowej", "Giełdy papierów wartościowych",
               why="Dostarczał płynności w panice."),
             W("Dlaczego Kongres uznał to rozwiązanie za niewystarczające?",
               "Stabilność systemu zależała od jednego prywatnego bankiera", "Bo Morgan był za biedny", "Bo nie było giełdy",
               why="Potrzebna była instytucja publiczna z mandatem ustawowym."),
             PF("W odpowiedzi w 1913 r. utworzono Fed.", True,
                why="Federal Reserve Act podpisano 23.12.1913."),
          ),
          PR("XVI w.: w Prusach Królewskich krążą monety pruskie, polskie i krzyżackie o różnej zawartości srebra, ale podobnych nominałach. Ceny rosną, a dobre monety znikają z obiegu.",
             W("Jakie zjawisko opisał Kopernik?",
               "Gorszy pieniądz wypiera z obiegu lepszy", "Halving", "Deflację dłużną",
               why="To prawo Kopernika–Greshama."),
             W("Co proponował jako rozwiązanie?",
               "Jedną, rzetelną monetę emitowaną według jednolitych zasad", "Wprowadzenie pieniądza papierowego", "Całkowity zakaz handlu",
               why="Jednolita moneta przywraca zaufanie."),
             PF("Kopernik zauważył związek między ilością i jakością pieniądza a poziomem cen.", True,
                why="Psucie monety prowadziło do drożyzny."),
          ),
      ]),

    L(2, "Złoty Grabskiego, NBP i pierwszy cel inflacyjny (1924–1990)",
      "Rozumieć reformę walutową Grabskiego i powstanie Banku Polskiego, utworzenie NBP w 1945 r. oraz narodziny strategii celu inflacyjnego w Nowej Zelandii w 1990 r.",
      ["1924 – reforma W. Grabskiego i Bank Polski", "1945 – Narodowy Bank Polski", "1990 – pierwszy cel inflacyjny"],
      [NBP, NBPE],
      explain=[
          K("1924 – reforma Grabskiego",
            "Po I wojnie Polska zmagała się z hiperinflacją marki polskiej. Premier i minister skarbu Władysław Grabski przeprowadził reformę: zrównoważył budżet (m.in. podatek majątkowy), utworzył Bank Polski SA – niezależny bank emisyjny – i wprowadził złotego wymienianego w relacji 1 zł = 1 800 000 marek polskich. Złoty był powiązany ze złotem."),
          K("1945 – Narodowy Bank Polski",
            "Dekretem z 15 stycznia 1945 r. utworzono NBP jako państwowy bank emisyjny, który zastąpił Bank Polski. W gospodarce centralnie planowanej NBP był jednocześnie bankiem centralnym i głównym bankiem komercyjnym (monobank). Dopiero w 1989 r. wydzielono z niego banki komercyjne i zbudowano system dwuszczeblowy."),
          W("Ile marek polskich wymieniano na 1 złotego w 1924 r.?",
            "1 800 000", "10 000", "100",
            why="Taki kurs wymiany ustalono w reformie Grabskiego."),
          K("1990 – cel inflacyjny",
            "Nowa Zelandia jako pierwsza (1990) wprowadziła bezpośredni cel inflacyjny: bank centralny publicznie zobowiązuje się do utrzymania inflacji w określonym przedziale, a prezes odpowiada za jego realizację. Strategię przejęły m.in. Kanada, Wielka Brytania, a Polska – od 1999 r. (cel ciągły 2,5% ± 1 pkt proc. od 2004 r.)."),
          K("Wspólny wątek",
            "Wszystkie trzy wydarzenia dotyczą wiarygodności pieniądza: Grabski musiał zakończyć hiperinflację, NBP w PRL był narzędziem planu, a cel inflacyjny to nowoczesny sposób zakotwiczenia oczekiwań. Przejście od monobanku do niezależnego banku centralnego było kluczowym elementem transformacji."),
          PF("W PRL NBP pełnił jednocześnie funkcje banku centralnego i komercyjnego.", True,
             why="System monobanku zlikwidowano dopiero w 1989 r."),
      ],
      mech=[
          LN("Ułóż kroki reformy Grabskiego.",
             ["Hiperinflacja marki polskiej niszczy oszczędności", "Rząd równoważy budżet, ograniczając wydatki i wprowadzając podatki", "Powstaje niezależny Bank Polski z prawem emisji", "Wprowadza się złotego w relacji 1 : 1 800 000 marek", "Ceny stabilizują się, a zaufanie do pieniądza wraca"],
             why="Bez zrównoważenia budżetu nowa waluta nie byłaby wiarygodna."),
          KT("Przyporządkuj zdarzenie do roku.",
             {"1924": ["Powstanie Banku Polskiego SA", "Wprowadzenie złotego"],
              "1945": ["Dekret o utworzeniu NBP"],
              "1989": ["Wydzielenie banków komercyjnych z NBP"],
              "1990": ["Cel inflacyjny w Nowej Zelandii"]},
             why="Chronologia bankowości centralnej w Polsce i na świecie."),
          W("Dlaczego reforma walutowa wymagała zrównoważenia budżetu?",
            "Deficyt finansowany drukiem pieniądza powodowałby nową inflację", "Bo tak wymagał Bank Anglii", "Bo złoty był papierowy",
            why="Źródłem hiperinflacji było finansowanie deficytu emisją."),
          W("Na czym polega strategia bezpośredniego celu inflacyjnego?",
            "Bank centralny ogłasza liczbowy cel inflacji i dostosowuje stopy, by go osiągnąć", "Bank centralny ustala stały kurs walutowy", "Rząd zamraża ceny",
            why="Cel zakotwicza oczekiwania inflacyjne."),
          M("Które elementy wzmacniały wiarygodność złotego w 1924 r.?",
            ["Niezależny bank emisyjny", "Zrównoważony budżet", "Powiązanie ze złotem", "Nielimitowany druk pieniądza"], [0, 1, 2],
            why="Nielimitowany druk wywołał wcześniejszą hiperinflację."),
          PF("Polska przyjęła strategię celu inflacyjnego w tym samym roku co Nowa Zelandia.", False,
             why="Nowa Zelandia – 1990, Polska – od 1999 r."),
      ],
      calc=[
          LB("Oszczędności 9 000 000 marek polskich. Ile to złotych po reformie?",
             5, "9000000/1800000", ["9 000 000 / 1 800 000 = 5 zł"], unit="zł"),
          LB("Ile lat dzieli reformę Grabskiego (1924) od utworzenia NBP (1945)?",
             21, "1945-1924", ["1945 − 1924 = 21"], unit="lat"),
          LB("Ile lat od utworzenia NBP (1945) do 2026 r.?",
             81, "2026-1945", ["2026 − 1945 = 81"], unit="lat"),
          LB("Cel NBP 2,5% ± 1 pkt proc. Ile wynosi dolna granica przedziału (%)?",
             1.5, "2.5-1", ["2,5 − 1 = 1,5%"], unit="%", tol=0.01),
          LB("Ceny rosły o 50% miesięcznie. Ile razy wzrosną w ciągu 6 miesięcy (2 miejsca po przecinku)?",
             11.39, "1.5**6", ["1,5⁶ ≈ 11,39"], unit="razy", tol=0.01),
          LB("Ile lat dzieli pierwszy cel inflacyjny (1990) od przyjęcia tej strategii przez Polskę (1999)?",
             9, "1999-1990", ["1999 − 1990 = 9"], unit="lat"),
      ],
      case=[
          PR("W 1923 r. ceny w Polsce rosły w niektórych miesiącach o kilkadziesiąt procent. Rząd finansował deficyt emisją marek. W 1924 r. Grabski przeprowadził reformę, a nowy złoty był stabilny przez kolejne lata.",
             W("Co było główną przyczyną hiperinflacji?",
               "Finansowanie deficytu budżetowego drukiem pieniądza", "Za mała ilość pieniądza", "Wysoki kurs złotego",
               why="Nadmiar emisji zwiększał ilość pieniądza szybciej niż produkcję."),
             W("Jaką rolę odegrał niezależny Bank Polski?",
               "Uniemożliwił finansowanie deficytu emisją i budował zaufanie do złotego", "Drukował pieniądze na potrzeby rządu", "Ustalał ceny towarów",
               why="Niezależność banku emisyjnego chroni wartość pieniądza."),
             PF("Reforma Grabskiego łączyła politykę fiskalną (budżet) i pieniężną (nowy bank emisyjny).", True,
                why="Oba elementy były konieczne."),
          ),
          PR("W 1989 r. Ustawą o NBP i Prawem bankowym wydzielono z NBP dziewięć banków komercyjnych (m.in. Bank Zachodni, BPH, Bank Śląski, PBK). NBP stał się wyłącznie bankiem centralnym.",
             W("Jak nazywamy system, w którym bank centralny jest jednocześnie bankiem komercyjnym?",
               "Monobank", "System dwuszczeblowy", "Eurosystem",
               why="Jeden bank pełnił obie funkcje."),
             W("Dlaczego rozdzielenie funkcji było ważne dla gospodarki rynkowej?",
               "Banki komercyjne mogły konkurować, a bank centralny – skupić się na pieniądzu i stabilności", "Bo NBP miał zbyt dużo pieniędzy", "Bo zakazał tego EBC",
               why="System dwuszczeblowy to standard gospodarki rynkowej."),
             PF("Wydzielenie banków komercyjnych było jednym z pierwszych kroków transformacji gospodarczej.", True,
                why="Nastąpiło w 1989 r., przed planem Balcerowicza."),
          ),
      ]),

    L(3, "Budowa rynku kapitałowego i euro (1991–2002)",
      "Umieszczać w czasie powstanie GPW, redukcję długu przez Klub Paryski, start WIG20, wprowadzenie euro i reformy 1999 r. w Polsce oraz rozumieć ich znaczenie dla transformacji.",
      ["1991 – GPW i redukcja długu przez Klub Paryski", "1994 – WIG20", "1999 – euro, reforma emerytalna i samorządowa w Polsce", "2002 – gotówka euro"],
      [GPW, ECB],
      explain=[
          K("1991 – GPW i Klub Paryski",
            "16 kwietnia 1991 r. odbyła się pierwsza sesja GPW: notowano 5 spółek, raz w tygodniu, w budynku dawnego KC PZPR. W tym samym roku Klub Paryski zgodził się zredukować o 50% dług Polski wobec rządów zachodnich – nagroda za odważne reformy rynkowe."),
          K("1994 – WIG20",
            "16 kwietnia 1994 r. wystartował WIG20 – indeks 20 największych i najpłynniejszych spółek (baza 1000 pkt). Stał się instrumentem bazowym dla kontraktów terminowych (od 1998 r.). W tym samym roku Klub Londyński zredukował dług Polski wobec banków komercyjnych."),
          W("Ile spółek notowano na pierwszej sesji GPW w 1991 r.?",
            "5", "20", "100",
            why="Na pierwszej sesji notowano 5 spółek, m.in. Tonsil i Próchnik."),
          K("1999 – euro i reformy",
            "1 stycznia 1999 r. 11 krajów UE wprowadziło euro w obrocie bezgotówkowym, a EBC przejął politykę pieniężną. W Polsce w tym samym dniu weszły w życie reformy: emerytalna (trzy filary, OFE), samorządowa (powiaty i 16 województw), zdrowotna (kasy chorych), a od września – oświatowa (gimnazja)."),
          K("2002 – gotówka euro",
            "1 stycznia 2002 r. do obiegu weszły banknoty i monety euro w 12 krajach; waluty narodowe wycofano w ciągu dwóch miesięcy. Była to największa wymiana gotówki w historii. W 2026 r. strefa euro liczy 21 państw (Bułgaria od 1.01.2026)."),
          PF("Euro w obrocie bezgotówkowym pojawiło się wcześniej niż banknoty euro.", True,
             why="Euro bezgotówkowe od 1999 r., gotówka dopiero od 2002 r."),
      ],
      mech=[
          LN("Ułóż wydarzenia chronologicznie.",
             ["Pierwsza sesja GPW", "Start indeksu WIG20", "Wprowadzenie euro w obrocie bezgotówkowym", "Reforma emerytalna w Polsce (w tym samym dniu co euro)", "Banknoty i monety euro w obiegu"],
             why="1991 → 1994 → 1999 → 1999 → 2002."),
          KT("Przyporządkuj do roku.",
             {"1991": ["Pierwsza sesja GPW", "Redukcja długu przez Klub Paryski"],
              "1994": ["Start WIG20", "Porozumienie z Klubem Londyńskim"],
              "1999": ["Euro bezgotówkowe", "Powstanie OFE", "16 województw i powiaty"],
              "2002": ["Banknoty i monety euro"]},
             why="Lata 90. to budowa instytucji rynkowych."),
          W("Dlaczego redukcja długu w 1991 r. sprzyjała rozwojowi GPW?",
            "Zwiększyła wiarygodność Polski i zaufanie inwestorów", "Zakazała handlu akcjami", "Zlikwidowała złotego",
            why="Mniejszy ciężar długu poprawił perspektywy gospodarki."),
          W("Dlaczego wprowadzenie euro odbyło się w dwóch etapach?",
            "Dla przygotowania systemów i druku ogromnej ilości gotówki", "Bo EBC nie był gotowy do 2010", "Bo tak wymagały USA",
            why="Najpierw rozliczenia, potem fizyczna wymiana gotówki."),
          M("Które reformy weszły w życie w Polsce 1.01.1999?",
            ["Emerytalna", "Samorządowa (powiaty, 16 województw)", "Zdrowotna (kasy chorych)", "Wprowadzenie euro w Polsce"], [0, 1, 2],
            why="Polska nie przyjęła euro."),
          PF("WIG20 jest starszy od GPW.", False,
             why="GPW – 1991, WIG20 – 1994."),
      ],
      calc=[
          LB("WIG20 wystartował z poziomu 1000 pkt. Przy poziomie 2500 pkt o ile procent wzrósł od startu?",
             150, "(2500/1000-1)*100", ["2500 / 1000 − 1 = 150%"], unit="%"),
          LB("Ile lat dzieli pierwszą sesję GPW (1991) od startu WIG20 (1994)?",
             3, "1994-1991", ["1994 − 1991 = 3"], unit="lata"),
          LB("Euro wprowadziło 11 krajów w 1999 r., a w 2026 r. strefa liczy 21. Ile krajów dołączyło?",
             10, "21-11", ["21 − 11 = 10"], unit="krajów"),
          LB("Dług wobec Klubu Paryskiego ok. 33 mld USD zredukowano o 50%. Ile pozostało do spłaty (mld USD)?",
             16.5, "33*0.5", ["33 · 50% = 16,5 mld USD"], unit="mld USD", tol=0.01),
          LB("Ile lat minęło od wprowadzenia gotówki euro (2002) do 2026 r.?",
             24, "2026-2002", ["2026 − 2002 = 24"], unit="lata"),
          LB("Kurs wymiany marki niemieckiej: 1,95583 DEM = 1 EUR. Ile euro za 1000 DEM (2 miejsca po przecinku)?",
             511.29, "1000/1.95583", ["1000 / 1,95583 ≈ 511,29 EUR"], unit="EUR", tol=0.01),
      ],
      case=[
          PR("16 kwietnia 1991 r. na pierwszej sesji GPW notowano 5 spółek, a obroty były niewielkie. Sesje odbywały się raz w tygodniu, a zlecenia składano na papierowych formularzach.",
             W("Dlaczego giełda była potrzebna w transformacji?",
               "Umożliwiała prywatyzację przez ofertę publiczną i pozyskiwanie kapitału przez firmy", "Bo zastępowała NBP", "By ustalać ceny chleba",
               why="Rynek kapitałowy to element gospodarki rynkowej."),
             W("Co oznaczała mała liczba spółek dla ryzyka inwestorów?",
               "Niską dywersyfikację i dużą zmienność", "Brak ryzyka", "Gwarantowane zyski",
               why="Przy kilku spółkach portfel nie może być zróżnicowany."),
             PF("Z czasem GPW stała się jedną z największych giełd w Europie Środkowo-Wschodniej.", True,
                why="Notuje kilkaset spółek i ma największą kapitalizację w regionie."),
          ),
          PR("Bułgaria przyjęła euro 1.01.2026 r. jako 21. kraj strefy, przy kursie konwersji 1,95583 lewa za euro (taki sam jak kurs marki niemieckiej, bo lew był do niej, a potem do euro, sztywno powiązany).",
             W("Ile euro dostanie Bułgar za 3911,66 lewa?",
               "2000 euro", "3911,66 euro", "1000 euro",
               why="3911,66 / 1,95583 = 2000 euro."),
             W("Co traci Bułgaria, przyjmując euro?",
               "Własną politykę pieniężną", "Członkostwo w UE", "Własny budżet",
               why="Stopy ustala EBC dla całej strefy."),
             PF("Sztywne powiązanie lewa z euro przed przyjęciem waluty ułatwiło przejście.", True,
                why="Kurs był stabilny od lat, więc konwersja nie zmieniła realnych wartości."),
          ),
      ]),

    L(4, "Kryzys i przebudowa nadzoru (2006–2015)",
      "Łączyć daty z okresu globalnego kryzysu finansowego z reformami nadzoru w Polsce i UE: KNF, NewConnect i Catalyst, bitcoin, nadzór nad SKOK, zmiany w OFE, unia bankowa, KSF i QE w strefie euro.",
      ["2006 – Komisja Nadzoru Finansowego", "2007 – NewConnect i początek kryzysu subprime", "2009 – Catalyst, traktat lizboński, bitcoin", "2012 – likwidacja lokat antybelkowych i nadzór KNF nad SKOK", "2014 – zmiany w OFE i unia bankowa", "2015 – Komitet Stabilności Finansowej i QE w strefie euro"],
      [KNF, ECB, BTC],
      explain=[
          K("2006–2007: KNF, NewConnect, subprime",
            "KNF powstała w 2006 r. (nadzór nad rynkiem kapitałowym, ubezpieczeniami i emerytalnym), a od 2008 r. przejęła też nadzór bankowy od NBP – powstał zintegrowany nadzór. W 2007 r. GPW uruchomiła NewConnect dla młodych spółek. W tym samym roku w USA zaczął się kryzys subprime, który w 2008 r. przerodził się w globalny kryzys finansowy."),
          K("2009: Catalyst, Lizbona, bitcoin",
            "GPW uruchomiła Catalyst – rynek obligacji korporacyjnych, komunalnych i skarbowych. 1 grudnia 2009 r. wszedł w życie traktat lizboński, który m.in. nadał EBC status instytucji UE. 3 stycznia 2009 r. wydobyto pierwszy blok bitcoina (genesis block) – z odniesieniem do ratowania banków przez rząd brytyjski."),
          W("Kiedy KNF przejęła nadzór nad bankami?",
            "Od 2008 r.", "Od 1991 r.", "Od 2015 r.",
            why="Nadzór bankowy przeszedł z NBP do KNF z początkiem 2008 r."),
          K("2012–2014: SKOK, lokaty, OFE, unia bankowa",
            "W 2012 r. SKOK-i objęto nadzorem KNF (po latach sporów) i ograniczono „lokaty antybelkowe”, które wykorzystywały zaokrąglanie podatku przy dziennej kapitalizacji. W 2014 r. przeniesiono część aktywów OFE do ZUS, a w strefie euro ruszyła unia bankowa – EBC przejął bezpośredni nadzór nad największymi bankami (jednolity mechanizm nadzorczy)."),
          K("2015: KSF i QE",
            "Ustawa o nadzorze makroostrożnościowym utworzyła Komitet Stabilności Finansowej z udziałem NBP, MF, KNF i BFG. W 2015 r. EBC rozpoczął skup obligacji skarbowych na dużą skalę (QE), by walczyć z ryzykiem deflacji w strefie euro."),
          PF("Unia bankowa oznacza, że EBC bezpośrednio nadzoruje największe banki strefy euro.", True,
             why="Jednolity mechanizm nadzorczy działa od listopada 2014 r."),
      ],
      mech=[
          LN("Ułóż wydarzenia chronologicznie.",
             ["Powstanie KNF", "Start NewConnect i początek kryzysu subprime", "Upadek Lehman Brothers", "Pierwszy blok bitcoina i start Catalyst", "Unia bankowa w strefie euro"],
             why="2006 → 2007 → 2008 → 2009 → 2014."),
          KT("Odpowiedź na kryzys czy rozwój rynku?",
             {"Odpowiedź na kryzys": ["Unia bankowa", "QE w strefie euro", "Komitet Stabilności Finansowej", "Nadzór KNF nad SKOK"],
              "Rozwój rynku": ["NewConnect", "Catalyst"]},
             why="Kryzys 2008–2012 wymusił wzmocnienie nadzoru."),
          W("Dlaczego EBC przejął nadzór nad największymi bankami strefy euro?",
            "Kryzys pokazał, że problemy banków i państw nawzajem się wzmacniają, a nadzór krajowy bywał zbyt łagodny", "Bo krajowe banki centralne zlikwidowano", "Bo tak zdecydowały USA",
            why="Unia bankowa miała przerwać „błędne koło” banków i państw."),
          W("Po co EBC prowadził QE od 2015 r.?",
            "By przeciwdziałać deflacji przy stopach bliskich zera", "By schłodzić inflację", "By umocnić euro",
            why="Gdy stopy są przy zerze, skup aktywów jest dodatkowym narzędziem."),
          M("Które wydarzenia miały miejsce w 2009 r.?",
            ["Start Catalyst", "Wejście w życie traktatu lizbońskiego", "Pierwszy blok bitcoina", "Powstanie KNF"], [0, 1, 2],
            why="KNF powstała w 2006 r."),
          PF("Pierwszy blok bitcoina zawierał odniesienie do ratowania banków przez rząd.", True,
             why="Zawierał nagłówek z „The Times” o drugim pakiecie pomocy dla banków."),
      ],
      calc=[
          LB("Ile lat dzieli powstanie KNF (2006) od powstania KSF (2015)?",
             9, "2015-2006", ["2015 − 2006 = 9"], unit="lat"),
          LB("Ile lat istnieje bitcoin w 2026 r. (pierwszy blok 2009)?",
             17, "2026-2009", ["2026 − 2009 = 17"], unit="lat"),
          LB("Ile lat dzieli start NewConnect (2007) od startu Catalyst (2009)?",
             2, "2009-2007", ["2009 − 2007 = 2"], unit="lata"),
          LB("QE EBC: skup 60 mld euro miesięcznie przez 18 miesięcy. Ile łącznie (mld euro)?",
             1080, "60*18", ["60 · 18 = 1080 mld euro"], unit="mld euro"),
          LB("Lokata antybelkowa: odsetki dzienne 2 grosze. Podatek 19% to 0,38 grosza, zaokrąglany do pełnych groszy. Ile wynosi podatek (gr)?",
             0, "0", ["0,38 gr zaokrągla się do 0"], unit="gr"),
          LB("W ramach zmian OFE w 2014 r. przeniesiono 51,5% aktywów. Przy aktywach ok. 300 mld zł ile to mld zł?",
             154.5, "300*0.515", ["300 · 51,5% = 154,5 mld zł"], unit="mld zł", tol=0.01),
      ],
      case=[
          PR("SKOK-i przez lata działały bez nadzoru państwowego. W 2012 r., po zmianie przepisów, objęła je nadzorem KNF. Badanie wykazało u wielu kas niedobory kapitału, a kilka trzeba było przejąć lub upadłościować; BFG wypłacał środki gwarantowane.",
             W("Dlaczego objęcie nadzorem było ważne dla klientów?",
               "Nadzór pozwala wcześniej wykryć problemy i chronić depozyty", "Zwiększył oprocentowanie lokat", "Zlikwidował gwarancje",
               why="Kontrola nadzorcza ogranicza ryzyko upadłości."),
             W("Kto wypłacał środki klientom upadłych kas?",
               "BFG", "KNF", "UFG",
               why="Od 2013 r. depozyty w SKOK są objęte gwarancjami BFG."),
             PF("Brak nadzoru zwiększa pokusę nadużycia w instytucjach przyjmujących depozyty.", True,
                why="Zarządzający mogą podejmować nadmierne ryzyko bez kontroli."),
          ),
          PR("W latach 2010–2012 kryzys zadłużenia w strefie euro (Grecja, Irlandia, Portugalia, Hiszpania) pokazał, że problemy banków obciążają budżety państw, a problemy państw – banki trzymające ich obligacje.",
             W("Jak nazywano to zjawisko?",
               "Błędne koło (pętla) banków i państw", "Halving", "Deficyty bliźniacze",
               why="Słabość jednej strony pogłębiała słabość drugiej."),
             W("Jaką odpowiedź instytucjonalną przyjęła strefa euro w 2014 r.?",
               "Unię bankową z nadzorem EBC", "Powrót do walut narodowych", "Zniesienie Paktu Stabilności",
               why="Wspólny nadzór i restrukturyzacja miały przerwać pętlę."),
             PF("Polska, nie będąc w strefie euro, nie jest automatycznie członkiem unii bankowej.", True,
                why="Kraje spoza strefy euro mogą przystąpić dobrowolnie."),
          ),
      ]),

    L(5, "Prawo dla przedsiębiorców i cyfrowe finanse (2018–2026)",
      "Umieszczać w czasie Konstytucję biznesu, RODO i prostą spółkę akcyjną oraz najnowsze zmiany w finansach (KSeF, reforma WIBOR, halving 2024, euro w Bułgarii) i rozumieć, czemu służą.",
      ["2018 – Konstytucja biznesu i RODO", "2021 – prosta spółka akcyjna", "Faktura VAT i KSeF", "WIBOR i WIBID"],
      [KNF, GPW],
      explain=[
          K("2018 – Konstytucja biznesu i RODO",
            "Pakiet ustaw zwany Konstytucją biznesu (w tym Prawo przedsiębiorców, od 30.04.2018) wprowadził zasady: co nie jest prawem zakazane, jest dozwolone; domniemanie uczciwości przedsiębiorcy; rozstrzyganie wątpliwości na jego korzyść; działalność nierejestrowana dla bardzo małych przychodów; Rzecznik MŚP. 25.05.2018 zaczęło obowiązywać RODO – unijne rozporządzenie o ochronie danych osobowych."),
          K("2021 – prosta spółka akcyjna",
            "Od 1 lipca 2021 r. można zakładać prostą spółkę akcyjną (PSA) – formę dla start-upów: minimalny kapitał akcyjny 1 zł, akcje bez wartości nominalnej, łatwe wnoszenie pracy i usług jako wkładu, elektroniczny rejestr akcjonariuszy, możliwość jednolitej rady dyrektorów."),
          W("Ile wynosi minimalny kapitał akcyjny prostej spółki akcyjnej?",
            "1 zł", "5 000 zł", "100 000 zł",
            why="PSA ma minimalny kapitał 1 zł – to bariera wejścia bliska zeru."),
          K("Najnowsze zmiany (2024–2026)",
            "20.04.2024 r. – czwarty halving bitcoina. 1.01.2026 r. – Bułgaria jako 21. kraj w strefie euro. 1.02.2026 r. – obowiązkowy KSeF dla największych firm, 1.04.2026 r. – dla pozostałych. 18.05.2026 r. – GPW Benchmark ogłosił koniec publikacji WIBOR z dniem 1.01.2037 r.; nowe umowy od 2027 r. mają opierać się na POLSTR."),
          K("Wspólny wątek",
            "Zmiany z lat 2018–2026 łączy cyfryzacja (KSeF, RODO, elektroniczny rejestr w PSA, kryptoaktywa) i dążenie do większej przejrzystości oraz zmniejszenia barier dla przedsiębiorców. Stawki referencyjne oparte na transakcjach (POLSTR) mają być trudniejsze do manipulacji niż kwotowania (WIBOR)."),
          PF("Prosta spółka akcyjna wymaga akcji o wartości nominalnej.", False,
             why="Akcje PSA nie mają wartości nominalnej."),
      ],
      mech=[
          LN("Ułóż wydarzenia chronologicznie.",
             ["Konstytucja biznesu", "RODO", "Prosta spółka akcyjna", "Czwarty halving bitcoina", "Obowiązkowy KSeF dla największych firm"],
             why="30.04.2018 → 25.05.2018 → 1.07.2021 → 20.04.2024 → 1.02.2026."),
          KT("Jakiemu celowi służy zmiana?",
             {"Mniejsze bariery dla firm": ["Działalność nierejestrowana", "PSA z kapitałem 1 zł", "Zasada „co nie jest zakazane, jest dozwolone”"],
              "Uszczelnienie podatków i przejrzystość": ["KSeF", "Wskaźnik POLSTR oparty na transakcjach"],
              "Ochrona prywatności": ["RODO"]},
             why="Reformy miały różne cele."),
          W("Dlaczego przejście z WIBOR na POLSTR zwiększa wiarygodność wskaźnika?",
            "POLSTR opiera się na rzeczywistych transakcjach, a nie deklaracjach banków", "Bo POLSTR ustala RPP", "Bo POLSTR jest zawsze niższy",
            why="Wskaźnik transakcyjny trudniej zmanipulować."),
          W("Który przepis Konstytucji biznesu chroni przedsiębiorcę w sporach z urzędem?",
            "Rozstrzyganie niedających się usunąć wątpliwości na korzyść przedsiębiorcy", "Obowiązek rejestracji każdej sprzedaży", "Zakaz działalności nierejestrowanej",
            why="To zasada in dubio pro libertate."),
          M("Co charakteryzuje prostą spółkę akcyjną?",
            ["Minimalny kapitał 1 zł", "Akcje bez wartości nominalnej", "Możliwość wniesienia pracy jako wkładu", "Obowiązek notowania na GPW"], [0, 1, 2],
            why="PSA nie musi być notowana na giełdzie."),
          PF("RODO jest rozporządzeniem UE stosowanym bezpośrednio we wszystkich państwach członkowskich.", True,
             why="Rozporządzenia UE nie wymagają transpozycji."),
      ],
      calc=[
          LB("Ile lat dzieli wejście w życie Konstytucji biznesu (2018) od prostej spółki akcyjnej (2021)?",
             3, "2021-2018", ["2021 − 2018 = 3"], unit="lata"),
          LB("WIBOR ma być publikowany do 31.12.2036. Ile lat od ogłoszenia (2026) do ostatniego roku publikacji?",
             10, "2036-2026", ["2036 − 2026 = 10"], unit="lat"),
          LB("Kara RODO do 4% rocznego obrotu. Firma ma obrót 500 mln euro. Ile maksymalnie (mln euro)?",
             20, "500*0.04", ["500 · 4% = 20 mln euro"], unit="mln euro"),
          LB("Strefa euro: 11 krajów w 1999 r., 21 w 2026 r. O ile procent wzrosła liczba członków?",
             90.91, "(21/11-1)*100", ["21 / 11 − 1 ≈ 90,91%"], unit="%", tol=0.02),
          LB("PSA z kapitałem 1 zł vs spółka z o.o. z minimalnym kapitałem 5 000 zł. Ile razy wyższy jest minimalny kapitał sp. z o.o.?",
             5000, "5000/1", ["5000 / 1 = 5000"], unit="razy"),
          LB("Czwarty halving był w 2024 r., kolejny oczekiwany ok. 2028 r. Co ile lat średnio następują halvingi?",
             4, "2028-2024", ["2028 − 2024 = 4"], unit="lata"),
      ],
      case=[
          PR("Trzech programistów zakłada start-up. Nie mają kapitału, ale wnoszą pracę i kod. Chcą w przyszłości przyjąć inwestora venture capital.",
             W("Jaka forma prawna jest dla nich zaprojektowana?",
               "Prosta spółka akcyjna", "Spółka akcyjna z kapitałem 100 000 zł", "Spółdzielnia",
               why="PSA pozwala wnieść pracę jako wkład i ma kapitał od 1 zł."),
             W("Jak ułatwi to wejście inwestora?",
               "Łatwo wyemitować nowe akcje i elastycznie ułożyć prawa akcjonariuszy", "Inwestor nie może wejść do PSA", "PSA musi wejść na GPW",
               why="PSA ma elastyczną strukturę kapitałową."),
             PF("Akcje PSA są rejestrowane w elektronicznym rejestrze akcjonariuszy.", True,
                why="Rejestr prowadzi uprawniony podmiot, np. dom maklerski lub notariusz."),
          ),
          PR("Od 1.02.2026 r. wielka firma wystawia faktury wyłącznie w KSeF, a od 1.04.2026 r. dotyczy to też jej mniejszych dostawców. Ministerstwo liczy na mniejsze wyłudzenia VAT.",
             W("Dlaczego KSeF może ograniczyć wyłudzenia?",
               "Faktury trafiają do systemu MF na bieżąco, więc łatwiej wykryć fikcyjne transakcje", "Bo zmniejsza stawki VAT", "Bo znosi VAT",
               why="Urząd widzi pełny obraz transakcji w czasie rzeczywistym."),
             W("Jaki koszt ponoszą firmy?",
               "Dostosowanie systemów księgowych i procedur", "Brak jakichkolwiek kosztów", "Opłatę 23% od faktury",
               why="Wdrożenie wymaga inwestycji w oprogramowanie i szkolenia."),
             PF("Do końca 2026 r. obowiązuje okres przejściowy bez kar za błędy w KSeF.", True,
                why="Kary za błędy związane z KSeF wprowadzono z odroczeniem."),
          ),
      ]),
]
