# -*- coding: utf-8 -*-
# Zrozumienie – Podstawy finansów / Przepisy i stawki
D = "2026-10-08"
NBP = S("Narodowy Bank Polski", "https://nbp.pl/", D)
KNF = S("Komisja Nadzoru Finansowego", "https://www.knf.gov.pl/", D)
BFG = S("Bankowy Fundusz Gwarancyjny", "https://www.bfg.pl/", D)
MFB = S("Ministerstwo Finansów – budżet państwa", "https://www.gov.pl/web/finanse/budzet-panstwa", D)
VAT = S("Ministerstwo Finansów – podatki.gov.pl: VAT", "https://www.podatki.gov.pl/vat/", D)
EPITY = S("e-pity.pl – skala podatkowa (stan na 2026 r.)", "https://www.e-pity.pl/skala-podatkowa/", D)
ZUS = S("ZUS – wysokość składek na ubezpieczenia społeczne (2026)", "https://www.zus.pl/baza-wiedzy/skladki-wskazniki-odsetki/skladki/wysokosc-skladek-na-ubezpieczenia-spoleczne", D)

LESSONS = [
    L(1, "Ustawy systemu finansowego",
      "Rozumieć, co regulują najważniejsze ustawy systemu finansowego – o finansach publicznych, o NBP, Prawo bankowe, o kredycie konsumenckim – oraz unijne MiCA, a także gwarancje BFG i cel inflacyjny NBP.",
      ["Ustawa o finansach publicznych (2009)", "Ustawa o Narodowym Banku Polskim (1997)", "Prawo bankowe (1997)", "Ustawa o kredycie konsumenckim (2011)", "Ustawa o kryptoaktywach i MiCA", "Gwarancja depozytów BFG", "Cel inflacyjny NBP"],
      [NBP, KNF, BFG, MFB],
      explain=[
          K("Ustawa o finansach publicznych (2009)",
            "Definiuje sektor finansów publicznych, zasady gospodarki budżetowej i jawności, procedury ostrożnościowe przy relacji państwowego długu do PKB (55%), reguły dla samorządów (art. 242–243) i stabilizującą regułę wydatkową, która ogranicza wzrost wydatków."),
          K("Ustawa o NBP i Prawo bankowe (1997)",
            "Ustawa o NBP: cel – stabilny poziom cen; organy (Prezes, RPP, Zarząd); instrumenty polityki pieniężnej; zakaz kredytowania budżetu. Cel inflacyjny NBP: 2,5% ± 1 pkt proc. CPI, w sposób ciągły od 2004 r. Prawo bankowe: definicja banku i czynności bankowych, tajemnica bankowa, ocena zdolności kredytowej, umowa kredytu w formie pisemnej, wymogi nadzorcze."),
          W("Która ustawa określa tajemnicę bankową?",
            "Prawo bankowe", "Ustawa o finansach publicznych", "Ustawa o kredycie konsumenckim",
            why="Tajemnicę bankową reguluje Prawo bankowe."),
          K("Kredyt konsumencki (2011)",
            "Dotyczy kredytów dla konsumentów do 255 550 zł. Kredytodawca musi podać RRSO i całkowity koszt kredytu, konsument może odstąpić od umowy w ciągu 14 dni bez podania przyczyny i spłacić kredyt wcześniej ze zwrotem części kosztów. Ustawa limituje pozaodsetkowe koszty kredytu, a Kodeks cywilny – odsetki maksymalne."),
          K("BFG i MiCA",
            "Gwarancje BFG obejmują depozyty do równowartości 100 000 euro na deponenta w banku lub SKOK-u; wypłata następuje w ciągu 7 dni roboczych. Unijne rozporządzenie MiCA (stosowane w pełni od 30.12.2024 r.) reguluje emitentów kryptoaktywów i dostawców usług – m.in. wymogi licencji i rezerw dla stablecoinów; w Polsce organem nadzoru ma być KNF."),
          PF("Konsument może odstąpić od umowy kredytu konsumenckiego w ciągu 14 dni bez podania przyczyny.", True,
             why="Tak stanowi ustawa o kredycie konsumenckim."),
      ],
      mech=[
          KT("Która regulacja?",
             {"Ustawa o finansach publicznych": ["Próg ostrożnościowy 55% PKB", "Stabilizująca reguła wydatkowa"],
              "Ustawa o NBP": ["Organy NBP i ich kompetencje", "Podstawowy cel – stabilność cen"],
              "Prawo bankowe": ["Tajemnica bankowa", "Obowiązek oceny zdolności kredytowej"],
              "Ustawa o kredycie konsumenckim": ["14 dni na odstąpienie od umowy", "Obowiązek podania RRSO"],
              "MiCA": ["Licencje dla dostawców usług kryptoaktywów", "Rezerwy emitentów stablecoinów"]},
             why="Każdy akt reguluje inny obszar."),
          LN("Ułóż procedurę ostrożnościową przy rosnącym długu.",
             ["Dług publiczny rośnie w relacji do PKB", "Przekracza próg ostrożnościowy 55% PKB", "Ustawa o finansach publicznych nakłada ograniczenia na budżet na kolejny rok", "Rząd musi przedstawić program sanacyjny", "Konstytucja zakazuje przekroczenia 60% PKB"],
             why="Progi ustawowe działają przed progiem konstytucyjnym."),
          W("Inflacja CPI wynosi 3,2%. Czy mieści się w paśmie celu NBP?",
            "Tak – pasmo to 1,5–3,5%", "Nie – cel to dokładnie 2,5%", "Nie – pasmo to 2–3%",
            why="2,5% ± 1 pkt proc. daje 1,5–3,5%."),
          W("Konsument podpisał umowę kredytu na 20 000 zł i po 10 dniach zmienił zdanie. Co może zrobić?",
            "Odstąpić od umowy, zwracając kapitał i odsetki za okres korzystania", "Nic, umowa jest wiążąca", "Odstąpić tylko za zgodą banku",
            why="Ma 14 dni na odstąpienie bez podania przyczyny."),
          M("Co gwarantuje BFG?",
            ["Depozyty w bankach do 100 000 euro na deponenta", "Depozyty w SKOK-ach do tego samego limitu", "Wypłatę w ciągu 7 dni roboczych", "Wartość akcji kupionych na giełdzie"], [0, 1, 2],
            why="Inwestycje giełdowe nie są objęte gwarancją depozytów."),
          PF("MiCA jest rozporządzeniem UE, więc stosuje się je bezpośrednio we wszystkich państwach członkowskich.", True,
             why="Rozporządzenia nie wymagają transpozycji, choć państwa wyznaczają organy nadzoru."),
      ],
      calc=[
          LB("Górna granica kwoty kredytu konsumenckiego to 255 550 zł. Klient chce 300 000 zł. O ile kwota przekracza limit (zł)?",
             44450, "300000-255550", ["300 000 − 255 550 = 44 450 zł"], unit="zł"),
          LB("Inflacja 5,1%. O ile pkt proc. przekracza górną granicę pasma celu NBP?",
             1.6, "5.1-3.5", ["5,1 − 3,5 = 1,6 pkt proc."], unit="pkt proc.", tol=0.01),
          LB("Dług publiczny 2 100 mld zł, PKB 3 900 mld zł. Ile wynosi relacja (%)?",
             53.85, "2100/3900*100", ["2100 / 3900 ≈ 53,85%"], unit="%", tol=0.02),
          LB("Ile brakuje do progu ostrożnościowego 55% przy relacji 53,85% (pkt proc.)?",
             1.15, "55-53.85", ["55 − 53,85 = 1,15 pkt proc."], unit="pkt proc.", tol=0.01),
          LB("Deponent ma 520 000 zł, gwarancja 100 000 euro po 4,30 zł. Ile wypłaci BFG (zł)?",
             430000, "100000*4.3", ["100 000 · 4,30 = 430 000 zł"], unit="zł"),
          LB("Stopa referencyjna 3,75%. Ile wynoszą odsetki maksymalne: 2 · (stopa + 3,5) (%)?",
             14.5, "2*(3.75+3.5)", ["2 · 7,25 = 14,5%"], unit="%", tol=0.01),
      ],
      case=[
          PR("Firma pożyczkowa oferuje „chwilówkę” 3000 zł na 30 dni z oprocentowaniem 18% rocznie (przy stopie referencyjnej 3,75%) i opłatą przygotowawczą 900 zł.",
             W("Czy oprocentowanie 18% jest dozwolone?",
               "Nie – przekracza odsetki maksymalne 14,5%", "Tak, nie ma limitu", "Tak, bo to krótki kredyt",
               why="Odsetki maksymalne to 2 · (3,75 + 3,5) = 14,5%."),
             W("Która ustawa ogranicza wysokość opłaty przygotowawczej?",
               "Ustawa o kredycie konsumenckim – limit pozaodsetkowych kosztów", "Prawo bankowe – tajemnica bankowa", "Ustawa o NBP",
               why="Pozaodsetkowe koszty kredytu są limitowane."),
             PF("Klient powinien porównać RRSO, a nie tylko oprocentowanie.", True,
                why="RRSO uwzględnia opłatę przygotowawczą."),
          ),
          PR("Giełda kryptowalut z siedzibą poza UE oferuje Polakom stablecoina bez licencji wymaganej przez MiCA. KNF publikuje ostrzeżenie.",
             W("Jakiej ochrony nie mają klienci tej platformy?",
               "Nadzoru i wymogów MiCA, np. dotyczących rezerw stablecoina", "Prawa do zakupu chleba", "Gwarancji BFG na akcje",
               why="Podmiot nielicencjonowany nie spełnia wymogów MiCA."),
             W("Czy środki na tej platformie są objęte gwarancją BFG?",
               "Nie", "Tak, do 100 000 euro", "Tak, w połowie",
               why="BFG gwarantuje depozyty w bankach i SKOK-ach, nie kryptoaktywa."),
             PF("Ostrzeżenie KNF ma pomóc klientom uniknąć ryzyka utraty środków.", True,
                why="Lista ostrzeżeń informuje o podmiotach działających bez zezwolenia."),
          ),
      ]),

    L(2, "Stawki VAT, PIT, składek i akcyzy w obliczeniach",
      "Sprawnie liczyć VAT według stawek 23/8/5/0%, PIT według skali na 2026 r., składki ZUS pracownika i akcyzę od samochodów, rozumiejąc, dlaczego stawki są zróżnicowane.",
      ["Stawki VAT w Polsce", "Skala podatkowa PIT", "Składki na ubezpieczenia społeczne", "Akcyza – przykładowe wyroby"],
      [VAT, EPITY, ZUS],
      explain=[
          K("Stawki VAT",
            "23% – stawka podstawowa. 8% – m.in. część usług budowlanych w budownictwie mieszkaniowym, usługi gastronomiczne, część żywności. 5% – podstawowa żywność, książki drukowane. 0% – eksport i wewnątrzwspólnotowa dostawa towarów (z prawem do odliczenia VAT naliczonego). Obniżone stawki mają łagodzić regresywność VAT.",
            w="brutto = netto · (1 + stawka);  VAT w brutto = brutto · stawka / (1 + stawka)"),
          K("PIT 2026",
            "Skala: 12% do 120 000 zł minus kwota zmniejszająca 3 600 zł (kwota wolna 30 000 zł); powyżej – 10 800 zł + 32% nadwyżki. Liniowy: 19% bez kwoty wolnej. Danina solidarnościowa: 4% od dochodu ponad 1 mln zł."),
          W("Dochód 100 000 zł, skala 2026. Ile wynosi podatek?",
            "8 400 zł", "12 000 zł", "19 000 zł",
            why="12% · 100 000 − 3 600 = 8 400 zł."),
          K("Składki ZUS 2026",
            "Pracownik: emerytalna 9,76%, rentowa 1,5%, chorobowa 2,45% (razem 13,71%). Pracodawca: emerytalna 9,76%, rentowa 6,5%, wypadkowa (np. 1,67%), FP 2,45%, FGŚP 0,1%. Składka zdrowotna pracownika: 9% podstawy po odjęciu składek społecznych."),
          K("Akcyza od samochodów",
            "Akcyza od samochodów osobowych: 3,1% wartości przy pojemności silnika do 2000 cm³ i 18,6% powyżej. Wyższa stawka dla dużych silników ma cel pozafiskalny – ograniczać emisje i zużycie paliwa. Akcyza obciąża też paliwa, alkohol, wyroby tytoniowe i energię elektryczną."),
          PF("Stawka VAT 0% przy eksporcie pozwala eksporterowi odzyskać VAT zapłacony przy zakupach.", True,
             why="W przeciwieństwie do zwolnienia, stawka 0% zachowuje prawo do odliczenia."),
      ],
      mech=[
          KT("Jaka stawka VAT (typowo)?",
             {"23%": ["Telefon komórkowy", "Usługa fryzjerska", "Paliwo na stacji"],
              "8%": ["Posiłek w restauracji", "Remont mieszkania w budownictwie mieszkaniowym"],
              "5%": ["Chleb i podstawowa żywność", "Książka drukowana"],
              "0%": ["Eksport maszyn poza UE", "Wewnątrzwspólnotowa dostawa towarów"]},
             why="Stawki obniżone dotyczą głównie dóbr podstawowych."),
          LN("Ułóż kroki liczenia pensji netto pracownika (uproszczenie).",
             ["Weź wynagrodzenie brutto", "Odejmij składki społeczne pracownika (13,71%)", "Policz składkę zdrowotną (9% od podstawy po składkach)", "Policz zaliczkę na PIT od podstawy po kosztach", "Odejmij składki, zdrowotną i zaliczkę – otrzymasz netto"],
             why="Kolejność wynika z ustaw o składkach i PIT."),
          W("Dlaczego żywność ma niższą stawkę VAT niż elektronika?",
            "By zmniejszyć obciążenie gospodarstw o niskich dochodach, które dużo wydają na żywność", "Bo żywność jest importowana", "Bo tak wymaga NBP",
            why="Obniżone stawki łagodzą regresywność VAT."),
          W("Dlaczego akcyza od samochodów z dużym silnikiem jest wyższa?",
            "By zniechęcać do zakupu aut o wysokim zużyciu paliwa i emisji", "Bo duże auta są tańsze", "Bo zakazuje ich UE",
            why="To pozafiskalna funkcja akcyzy."),
          M("Które składki płaci tylko pracodawca?",
            ["Wypadkowa", "Fundusz Pracy", "FGŚP", "Chorobowa"], [0, 1, 2],
            why="Chorobową płaci pracownik."),
          PF("Przy dochodzie 150 000 zł stawka 32% dotyczy tylko 30 000 zł nadwyżki.", True,
             why="Progresja dotyczy nadwyżki ponad próg 120 000 zł."),
      ],
      calc=[
          LB("Posiłek w restauracji kosztuje 54 zł brutto (VAT 8%). Ile wynosi VAT (zł)?",
             4, "54-54/1.08", ["Netto 54 / 1,08 = 50", "VAT 4 zł"], unit="zł"),
          LB("Książka 42 zł brutto (VAT 5%). Ile wynosi cena netto (zł)?",
             40, "42/1.05", ["42 / 1,05 = 40 zł"], unit="zł"),
          LB("Dochód 200 000 zł, skala 2026. Ile wynosi podatek (zł)?",
             36400, "10800+0.32*80000", ["Nadwyżka 80 000 · 32% = 25 600", "10 800 + 25 600 = 36 400 zł"], unit="zł"),
          LB("Wynagrodzenie brutto 10 000 zł. Ile wynoszą składki społeczne pracownika (13,71%, zł)?",
             1371, "10000*0.1371", ["10 000 · 13,71% = 1371 zł"], unit="zł"),
          LB("Samochód o wartości 120 000 zł z silnikiem 2500 cm³. Ile wynosi akcyza (18,6%, zł)?",
             22320, "120000*0.186", ["120 000 · 18,6% = 22 320 zł"], unit="zł"),
          LB("Ten sam samochód z silnikiem 1600 cm³ (3,1%). O ile niższa jest akcyza (zł)?",
             18600, "120000*(0.186-0.031)", ["120 000 · 15,5 pkt proc. = 18 600 zł"], unit="zł"),
      ],
      case=[
          PR("Pan Robert importuje z Niemiec używany samochód wart 80 000 zł z silnikiem 2200 cm³. Płaci akcyzę w Polsce. Pani Ewa kupuje auto o tej samej wartości z silnikiem 1500 cm³.",
             W("Ile akcyzy zapłaci Pan Robert?",
               "14 880 zł", "2 480 zł", "18 400 zł",
               why="80 000 · 18,6% = 14 880 zł."),
             W("Ile zapłaci Pani Ewa?",
               "2 480 zł", "14 880 zł", "0 zł",
               why="80 000 · 3,1% = 2 480 zł."),
             PF("Różnica stawek ma wpływać na wybory konsumentów w stronę mniejszych silników.", True,
                why="To pozafiskalny cel akcyzy."),
          ),
          PR("Sklep sprzedaje w jednym paragonie: chleb za 10,50 zł (5%), kawę w kawiarni sklepowej za 16,20 zł (8%) i ładowarkę za 61,50 zł (23%) – ceny brutto.",
             W("Ile VAT zawiera ładowarka?",
               "11,50 zł", "14,15 zł", "6,15 zł",
               why="61,50 / 1,23 = 50 netto; VAT = 11,50 zł."),
             W("Ile VAT zawiera chleb?",
               "0,50 zł", "0,53 zł", "2,10 zł",
               why="10,50 / 1,05 = 10 netto; VAT = 0,50 zł."),
             W("Ile łącznie VAT na paragonie (kawa: 16,20 / 1,08 = 15 netto)?",
               "13,20 zł", "12,00 zł", "18,50 zł",
               why="11,50 + 0,50 + 1,20 = 13,20 zł."),
          ),
      ]),
]
