# -*- coding: utf-8 -*-
# Zrozumienie – Finanse przedsiębiorstw / Źródła finansowania i kapitał obrotowy
OSF = "https://openstax.org/books/principles-financial-accounting/pages/"
OSM = "https://openstax.org/books/principles-managerial-accounting/pages/"
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-08"
S171 = S("OpenStax, Principles of Economics 3e, 17.1 How Businesses Raise Financial Capital", OS3 + "17-1-how-businesses-raise-financial-capital", D)
F121 = S("OpenStax, Principles of Accounting Vol. 1, 12.1 Current Liabilities", OSF + "12-1-identify-and-describe-current-liabilities", D)
F96 = S("OpenStax, Principles of Accounting Vol. 1, 9.6 Notes Receivable vs Accounts Receivable", OSF + "9-6-explain-how-notes-receivable-and-accounts-receivable-differ", D)
F141 = S("OpenStax, Principles of Accounting Vol. 1, 14.1 Equity Financing Through Issuance of Stock", OSF + "14-1-explain-the-process-of-securing-equity-financing-through-the-issuance-of-stock", D)
M73 = S("OpenStax, Principles of Accounting Vol. 2, 7.3 Financial Budgets (cash budget)", OSM + "7-3-prepare-financial-budgets", D)
PARP = S("Polska Agencja Rozwoju Przedsiębiorczości", "https://www.parp.gov.pl/", D)
ECSP = S("Rozporządzenie (UE) 2020/1503 w sprawie europejskich dostawców usług finansowania społecznościowego (EUR-Lex)", "https://eur-lex.europa.eu/legal-content/PL/TXT/?uri=CELEX:32020R1503", D)
PRESTR = S("Ustawa z 15 maja 2015 r. – Prawo restrukturyzacyjne (Dz.U. 2015 poz. 978, ELI)", "https://api.sejm.gov.pl/eli/acts/DU/2015/978/text.pdf", D)
PUPAD = S("Ustawa z 28 lutego 2003 r. – Prawo upadłościowe (Dz.U. 2003 nr 60 poz. 535, ELI)", "https://api.sejm.gov.pl/eli/acts/DU/2003/535/text.pdf", D)

LESSONS = [
    L(1, "Źródła finansowania i kredyt",
      "Klasyfikować źródła finansowania (własne i obce, wewnętrzne i zewnętrzne), liczyć koszt kredytu kupieckiego przy rezygnacji ze skonta i rozumieć rodzaje kredytów bankowych, ich zabezpieczenia oraz gwarancje de minimis.",
      ["Źródła finansowania przedsiębiorstwa", "Kredyt kupiecki (handlowy)", "Kredyt obrotowy i inwestycyjny", "Zabezpieczenia kredytu", "Gwarancje de minimis"],
      [S171, F121, PARP],
      explain=[
          K("Mapa źródeł",
            "Własne wewnętrzne: zysk zatrzymany, amortyzacja (jako źródło gotówki). Własne zewnętrzne: wkłady wspólników, emisja akcji, venture capital. Obce: kredyty bankowe, pożyczki, obligacje, leasing, faktoring, kredyt kupiecki. Wybór zależy od kosztu, ryzyka, kontroli (nowi akcjonariusze dostają głos) i dostępności."),
          K("Kredyt kupiecki i skonto",
            "Dostawca odracza płatność, np. „2/10, netto 30”: zapłać w 10 dni – rabat 2%, albo całość w 30 dni. Rezygnacja ze skonta to w praktyce kredyt na 20 dni kosztujący 2% – w skali roku bardzo drogo.",
            w="koszt = skonto/(100 − skonto) · 365/(dni kredytu − dni skonta)"),
          W("Warunki 2/10, netto 30. Ile w przybliżeniu wynosi roczny koszt rezygnacji ze skonta?",
            "Ok. 37%", "2%", "Ok. 10%",
            why="2/98 · 365/20 ≈ 37,2%."),
          K("Kredyty bankowe",
            "Kredyt obrotowy finansuje bieżącą działalność (zapasy, należności), zwykle do roku, często w formie limitu w rachunku. Kredyt inwestycyjny finansuje zakup środków trwałych, na kilka lat, spłacany z przepływów z inwestycji. Bank ocenia zdolność kredytową i żąda zabezpieczeń: hipoteka, zastaw rejestrowy, przewłaszczenie, cesja należności, weksel in blanco, poręczenie."),
          K("Gwarancje de minimis",
            "Bank Gospodarstwa Krajowego udziela małym i średnim firmom gwarancji spłaty części kredytu (pomoc de minimis), gdy brakuje im zabezpieczeń. Dzięki temu bank chętniej udziela kredytu. Pomoc de minimis to ograniczona kwotowo pomoc publiczna dopuszczalna w UE."),
          PF("Hipoteka jest typowym zabezpieczeniem kredytu na zakup nieruchomości.", True,
             why="Nieruchomość zabezpiecza wierzytelność banku."),
      ],
      mech=[
          KT("Jakie to źródło finansowania?",
             {"Własne wewnętrzne": ["Zysk zatrzymany", "Środki z amortyzacji"],
              "Własne zewnętrzne": ["Emisja nowych akcji", "Dopłaty wspólników", "Inwestycja funduszu VC"],
              "Obce": ["Kredyt bankowy", "Emisja obligacji", "Kredyt kupiecki od dostawcy"]},
             why="Kryteria: kto dostarcza kapitał i czy staje się współwłaścicielem."),
          LN("Ułóż przebieg uzyskania kredytu inwestycyjnego.",
             ["Firma przygotowuje biznesplan i prognozy", "Bank bada zdolność kredytową", "Strony ustalają zabezpieczenia, np. hipotekę", "Podpisanie umowy i wypłata transz", "Spłata rat z przepływów z inwestycji"],
             why="Kredyt inwestycyjny spłaca się z efektów inwestycji."),
          W("Firma ma tani kredyt w rachunku na 10% rocznie, a dostawca oferuje skonto 2/10, netto 30. Co robić?",
            "Skorzystać ze skonta, pożyczając w banku", "Płacić po 30 dniach", "Nic nie zmieniać",
            why="Kredyt 10% jest dużo tańszy od 37% kosztu rezygnacji ze skonta."),
          W("Dlaczego emisja akcji może być niechętnie wybierana przez założycieli?",
            "Rozwadnia ich udział i kontrolę", "Bo zawsze jest najtańsza", "Bo wymaga spłaty rat",
            why="Nowi akcjonariusze dostają prawa głosu."),
          M("Co może być zabezpieczeniem kredytu?",
            ["Hipoteka na nieruchomości", "Zastaw rejestrowy na maszynach", "Cesja należności od klientów", "Wysoki kurs WIG20"], [0, 1, 2],
            why="Kurs indeksu nie zabezpiecza wierzytelności banku."),
          PF("Kredyt obrotowy służy przede wszystkim finansowaniu zakupu budynków.", False,
             why="Finansuje bieżącą działalność; budynki – kredyt inwestycyjny."),
      ],
      calc=[
          LB("Warunki 2/10, netto 30. Ile wynosi roczny koszt rezygnacji ze skonta (%)?",
             37.24, "2/98*365/20*100", ["2/98 ≈ 2,04%", "· 365/20 ≈ 37,24%"], unit="%", tol=0.02),
          LB("Warunki 1/10, netto 40. Ile wynosi roczny koszt (%)?",
             12.29, "1/99*365/30*100", ["1/99 ≈ 1,01%", "· 365/30 ≈ 12,29%"], unit="%", tol=0.02),
          LB("Faktura 50 000 zł, skonto 2%. Ile firma zaoszczędzi, płacąc w terminie skonta (zł)?",
             1000, "50000*0.02", ["50 000 · 2% = 1 000 zł"], unit="zł"),
          LB("Kredyt inwestycyjny 600 000 zł, gwarancja de minimis pokrywa 60%. Ile kwoty kredytu jest gwarantowane (zł)?",
             360000, "600000*0.6", ["600 000 · 60% = 360 000 zł"], unit="zł"),
          LB("Bank wymaga zabezpieczenia hipotecznego 150% kwoty kredytu 400 000 zł. Jaka musi być wartość nieruchomości (zł)?",
             600000, "400000*1.5", ["400 000 · 1,5 = 600 000 zł"], unit="zł"),
          LB("Limit kredytu obrotowego 200 000 zł, średnie wykorzystanie 120 000 zł, oprocentowanie 9%. Ile wynoszą roczne odsetki (zł)?",
             10800, "120000*0.09", ["120 000 · 9% = 10 800 zł"], unit="zł"),
      ],
      case=[
          PR("Producent okien kupuje szkło za 300 000 zł miesięcznie na warunkach 2/10, netto 30. Zwykle płaci po 30 dniach. Ma dostępny kredyt w rachunku na 11% rocznie.",
             W("Ile zaoszczędziłby miesięcznie, korzystając ze skonta?",
               "6 000 zł", "3 000 zł", "30 000 zł",
               why="300 000 · 2% = 6 000 zł."),
             W("Ile kosztowałoby finansowanie płatności kredytem przez 20 dni (w przybliżeniu)?",
               "Ok. 1 770 zł", "Ok. 6 000 zł", "Ok. 33 000 zł",
               why="294 000 · 11% · 20/365 ≈ 1 772 zł."),
             PF("Opłaca się płacić w terminie skonta, finansując się kredytem.", True,
                why="Oszczędność 6 000 zł > koszt odsetek ok. 1 770 zł."),
          ),
          PR("Młoda firma meblarska chce kredytu 500 000 zł na maszyny, ale nie ma nieruchomości na zabezpieczenie. Bank proponuje zastaw rejestrowy na maszynach i gwarancję de minimis BGK.",
             W("Po co bankowi zastaw rejestrowy?",
               "W razie braku spłaty może zaspokoić się z maszyn", "By obniżyć oprocentowanie lokat", "By przejąć firmę od razu",
               why="Zastaw daje pierwszeństwo zaspokojenia z rzeczy."),
             W("Jak gwarancja de minimis pomaga firmie?",
               "Zmniejsza ryzyko banku, więc łatwiej uzyskać kredyt", "Umarza kredyt", "Zwalnia z podatku",
               why="BGK gwarantuje spłatę części kredytu."),
             PF("Gwarancja de minimis jest formą pomocy publicznej o ograniczonej wysokości.", True,
                why="Pomoc de minimis ma limity w prawie UE."),
          ),
      ]),

    L(2, "Kapitał obrotowy, cykl konwersji gotówki i budżet kasowy",
      "Liczyć cykl operacyjny i cykl konwersji gotówki, rozumieć strategie zarządzania kapitałem obrotowym (konserwatywną i agresywną), zarządzać należnościami i zobowiązaniami oraz sporządzać budżet kasowy.",
      ["Zarządzanie kapitałem obrotowym", "Cykl operacyjny i cykl konwersji gotówki", "Należności i zobowiązania", "Planowanie finansowe i budżet kasowy"],
      [F96, M73],
      explain=[
          K("Cykl operacyjny i konwersji gotówki",
            "Cykl operacyjny = rotacja zapasów + rotacja należności (dni od zakupu surowca do wpływu gotówki od klienta). Cykl konwersji gotówki = cykl operacyjny − rotacja zobowiązań – ile dni firma musi sama finansować działalność. Im krótszy, tym mniej kapitału obrotowego potrzeba.",
            w="CKG = rotacja zapasów + rotacja należności − rotacja zobowiązań"),
          K("Strategie kapitału obrotowego",
            "Konserwatywna: duże zapasy i gotówka, finansowanie długoterminowe – bezpieczna, ale kosztowna (zamrożony kapitał). Agresywna: małe zapasy, krótkoterminowe finansowanie – tańsza, ale ryzykowna (braki towaru, problemy z odnowieniem kredytu). Umiarkowana dopasowuje termin finansowania do charakteru aktywów."),
          W("Zapasy 40 dni, należności 45 dni, zobowiązania 30 dni. Ile wynosi cykl konwersji gotówki?",
            "55 dni", "85 dni", "115 dni",
            why="40 + 45 − 30 = 55 dni."),
          K("Należności i zobowiązania",
            "Zarządzanie należnościami: ocena wiarygodności klientów, limity kupieckie, terminy płatności, monitoring, windykacja, faktoring, ubezpieczenie należności. Zobowiązania: wykorzystanie terminów płatności bez utraty reputacji i skont. Ustawa o przeciwdziałaniu nadmiernym opóźnieniom w transakcjach handlowych ogranicza terminy (co do zasady do 60 dni między firmami)."),
          K("Budżet kasowy",
            "To plan wpływów i wydatków gotówki w poszczególnych miesiącach: saldo początkowe + wpływy − wydatki = saldo końcowe. Pokazuje, kiedy zabraknie gotówki (trzeba zaplanować kredyt) i kiedy pojawią się nadwyżki (można je ulokować). Uwzględnia sezonowość i terminy płatności klientów.",
            w="saldo końcowe = saldo początkowe + wpływy − wydatki"),
          PF("Skrócenie rotacji należności zmniejsza cykl konwersji gotówki.", True,
             why="Firma szybciej odzyskuje gotówkę od klientów."),
      ],
      mech=[
          KT("Wydłuża czy skraca cykl konwersji gotówki?",
             {"Skraca": ["Szybsze ściąganie należności", "Mniejsze zapasy dzięki dostawom just-in-time", "Dłuższe terminy płatności u dostawców"],
              "Wydłuża": ["Dłuższe terminy dla klientów", "Gromadzenie zapasów na zapas", "Płacenie dostawcom przed terminem bez skonta"]},
             why="CKG zależy od zapasów, należności i zobowiązań."),
          LN("Ułóż drogę gotówki w cyklu operacyjnym.",
             ["Firma kupuje surowce na kredyt kupiecki", "Produkuje i magazynuje wyroby", "Płaci dostawcy po terminie płatności", "Sprzedaje wyroby z odroczoną płatnością", "Otrzymuje gotówkę od klienta"],
             why="Luka między zapłatą dostawcy a wpływem od klienta wymaga finansowania."),
          W("Budżet kasowy pokazuje ujemne saldo w lipcu przez sezonowe zakupy. Co zrobić z wyprzedzeniem?",
            "Uzgodnić limit kredytu obrotowego na ten okres", "Nic – saldo samo się wyrówna", "Wypłacić dywidendę w czerwcu",
            why="Budżet kasowy służy planowaniu finansowania."),
          W("Która strategia kapitału obrotowego ma najwyższe ryzyko braku płynności?",
            "Agresywna", "Konserwatywna", "Umiarkowana",
            why="Małe zapasy gotówki i krótkie finansowanie."),
          M("Jak ograniczyć ryzyko niespłaconych należności?",
            ["Sprawdzać wiarygodność klientów", "Ustalać limity kupieckie", "Ubezpieczać należności lub korzystać z faktoringu bez regresu", "Wydłużać terminy wszystkim klientom"], [0, 1, 2],
            why="Dłuższe terminy zwiększają ryzyko i zamrażają gotówkę."),
          PF("Ujemny cykl konwersji gotówki oznacza, że dostawcy finansują działalność firmy.", True,
             why="Firma otrzymuje gotówkę od klientów, zanim zapłaci dostawcom."),
      ],
      calc=[
          LB("Zapasy 60 dni, należności 40 dni. Ile wynosi cykl operacyjny (dni)?",
             100, "60+40", ["60 + 40 = 100 dni"], unit="dni"),
          LB("Rotacja zobowiązań 35 dni. Ile wynosi cykl konwersji gotówki (dni)?",
             65, "100-35", ["100 − 35 = 65 dni"], unit="dni"),
          LB("Dzienne koszty operacyjne (gotówkowe) 20 000 zł. Ile kapitału obrotowego potrzeba na pokrycie CKG 65 dni (zł)?",
             1300000, "20000*65", ["20 000 · 65 = 1 300 000 zł"], unit="zł"),
          LB("Skrócenie CKG o 15 dni przy kosztach 20 000 zł dziennie uwalnia ile gotówki (zł)?",
             300000, "20000*15", ["20 000 · 15 = 300 000 zł"], unit="zł"),
          LB("Budżet kasowy: saldo początkowe 50 000 zł, wpływy 300 000 zł, wydatki 340 000 zł. Ile wynosi saldo końcowe (zł)?",
             10000, "50000+300000-340000", ["50 000 + 300 000 − 340 000 = 10 000 zł"], unit="zł"),
          LB("Minimalne saldo bezpieczeństwa to 30 000 zł. Ile kredytu trzeba zaplanować (zł)?",
             20000, "30000-10000", ["30 000 − 10 000 = 20 000 zł"], unit="zł"),
      ],
      case=[
          PR("Sieć dyskontów: rotacja zapasów 20 dni, klienci płacą natychmiast (0 dni), dostawcom płaci po 60 dniach. Producent maszyn: zapasy 120 dni, należności 75 dni, zobowiązania 45 dni.",
             W("Ile wynosi CKG sieci dyskontów?",
               "Ujemny, −40 dni", "Dodatni, 80 dni", "Zero",
               why="20 + 0 − 60 = −40 dni."),
             W("Ile wynosi CKG producenta maszyn?",
               "150 dni", "240 dni", "30 dni",
               why="120 + 75 − 45 = 150 dni."),
             PF("Producent maszyn potrzebuje dużo więcej kapitału obrotowego niż sieć dyskontów.", True,
                why="Musi finansować działalność przez 150 dni."),
          ),
          PR("Firma ogrodnicza ma sezonową sprzedaż: w marcu–maju wydaje dużo na sadzonki, a wpływy przychodzą w czerwcu–sierpniu. Saldo początkowe w marcu 40 000 zł. Plan: marzec wpływy 30 000, wydatki 90 000; kwiecień wpływy 50 000, wydatki 80 000.",
             W("Ile wynosi saldo na koniec marca?",
               "Ujemne, −20 000 zł", "Dodatnie, 20 000 zł", "Dodatnie, 60 000 zł",
               why="40 000 + 30 000 − 90 000 = −20 000 zł."),
             W("Ile wynosi saldo na koniec kwietnia (bez kredytu)?",
               "Ujemne, −50 000 zł", "Ujemne, −30 000 zł", "Dodatnie, 10 000 zł",
               why="−20 000 + 50 000 − 80 000 = −50 000 zł."),
             PF("Firma powinna z wyprzedzeniem uzgodnić kredyt obrotowy na sezon.", True,
                why="Budżet kasowy pokazuje przejściowy niedobór gotówki."),
          ),
      ]),

    L(3, "Finansowanie niestandardowe: emisje, mezzanine, project finance, crowdfunding",
      "Rozumieć przebieg emisji papierów wartościowych, finansowanie mezzanine i kredyt rewolwingowy, finansowanie projektów (project finance), crowdfunding udziałowy i dłużny oraz ideę inżynierii finansowej.",
      ["Emisja papierów wartościowych – przebieg", "Finansowanie mezzanine i kredyt rewolwingowy", "Project finance", "Crowdfunding", "Inżynieria finansowa"],
      [F141, ECSP],
      explain=[
          K("Emisja papierów wartościowych",
            "Etapy: decyzja organów spółki (uchwała walnego o podwyższeniu kapitału lub emisji obligacji), wybór doradców i domu maklerskiego, przygotowanie dokumentu ofertowego (prospekt zatwierdzany przez KNF lub dokument zwolniony z tego obowiązku), budowa księgi popytu, zapisy i przydział, rejestracja papierów w KDPW i wprowadzenie do obrotu. Emisja może być publiczna albo prywatna (do wąskiego grona inwestorów)."),
          K("Mezzanine i kredyt rewolwingowy",
            "Mezzanine to finansowanie „pośrodku” między długiem a kapitałem własnym: pożyczka podporządkowana (spłacana po kredycie bankowym), często z prawem zamiany na udziały (warranty). Droższa od kredytu, tańsza od kapitału własnego; używana przy wykupach i szybkim rozwoju. Kredyt rewolwingowy (odnawialny) – limit, który można wielokrotnie wykorzystywać i spłacać w okresie umowy."),
          W("Dlaczego mezzanine jest droższe od kredytu bankowego?",
            "Jest spłacane po kredycie – wierzyciel ponosi większe ryzyko", "Bo nie ma odsetek", "Bo jest gwarantowane przez państwo",
            why="Podporządkowanie zwiększa ryzyko, więc oprocentowanie jest wyższe."),
          K("Project finance",
            "Finansowanie konkretnego, dużego projektu (elektrownia, autostrada, farma wiatrowa) przez spółkę celową (SPV). Kredytodawcy spłacani są z przepływów samego projektu, a zabezpieczeniem są jego aktywa i umowy (np. długoterminowe umowy sprzedaży energii). Sponsorzy odpowiadają tylko do wysokości wkładu – ryzyko jest „odgrodzone” od ich pozostałej działalności."),
          K("Crowdfunding",
            "Finansowanie społecznościowe przez platformy internetowe: udziałowy (inwestorzy kupują udziały lub akcje), pożyczkowy (pożyczki dla firm), nagrodowy (wsparcie w zamian za produkt) i donacyjny. W UE dostawców usług crowdfundingu reguluje rozporządzenie 2020/1503 – oferta do 5 mln euro w ciągu 12 miesięcy, licencja i nadzór (w Polsce KNF). Inżynieria finansowa to projektowanie takich nowych instrumentów i struktur finansowania."),
          PF("W project finance kredytodawcy polegają głównie na przepływach z danego projektu.", True,
             why="Spółka celowa nie ma innej działalności."),
      ],
      mech=[
          LN("Ułóż przebieg publicznej emisji akcji.",
             ["Walne zgromadzenie uchwala podwyższenie kapitału", "Spółka z domem maklerskim przygotowuje prospekt", "KNF zatwierdza prospekt", "Budowa księgi popytu, zapisy i przydział akcji", "Rejestracja w KDPW i debiut na giełdzie"],
             why="Każdy etap ma określone obowiązki prawne."),
          KT("Jaka forma finansowania pasuje?",
             {"Project finance": ["Budowa farmy wiatrowej przez spółkę celową", "Autostrada w formule koncesji"],
              "Mezzanine": ["Wykup spółki przez fundusz z luką między kredytem a kapitałem", "Szybki rozwój firmy bez oddawania kontroli od razu"],
              "Crowdfunding": ["Startup sprzedający udziały tysiącom drobnych inwestorów online", "Przedsprzedaż gadżetu na platformie nagrodowej"],
              "Kredyt rewolwingowy": ["Sezonowe finansowanie zapasów z wielokrotnym wykorzystaniem limitu"]},
             why="Forma finansowania wynika z rodzaju potrzeby i ryzyka."),
          W("Spółka celowa budująca elektrownię zbankrutowała. Czy kredytodawcy mogą żądać spłaty od sponsora?",
            "Zasadniczo nie – odpowiedzialność sponsora jest ograniczona do wkładu", "Tak, bez ograniczeń", "Tylko od Skarbu Państwa",
            why="Project finance odgradza ryzyko projektu."),
          W("Jaki jest limit oferty crowdfundingowej według rozporządzenia UE 2020/1503?",
            "5 mln euro w ciągu 12 miesięcy", "500 tys. zł rocznie", "Bez limitu",
            why="Taki próg obowiązuje dla ofert na licencjonowanych platformach."),
          M("Czym jest kredyt rewolwingowy?",
            ["Limit odnawialny w okresie umowy", "Można wielokrotnie wykorzystywać i spłacać", "Odsetki płaci się od wykorzystanej kwoty", "Kredyt na zakup nieruchomości na 30 lat"], [0, 1, 2],
            why="Długi kredyt hipoteczny nie jest odnawialny."),
          PF("Emisja prywatna akcji nie wymaga prospektu zatwierdzanego przez KNF.", True,
             why="Prospekt dotyczy co do zasady ofert publicznych."),
      ],
      calc=[
          LB("Projekt farmy wiatrowej 400 mln zł: kredyt 75%, reszta wkład sponsorów. Ile wynosi wkład (mln zł)?",
             100, "400*0.25", ["400 · 25% = 100 mln zł"], unit="mln zł"),
          LB("Przepływy projektu na obsługę długu 36 mln zł, rata kredytu 30 mln zł. Ile wynosi wskaźnik pokrycia obsługi długu (DSCR)?",
             1.2, "36/30", ["36 / 30 = 1,2"], unit="", tol=0.01),
          LB("Crowdfunding: 1 200 inwestorów po średnio 2 500 zł. Ile zebrano (zł)?",
             3000000, "1200*2500", ["1 200 · 2 500 = 3 000 000 zł"], unit="zł"),
          LB("Limit 5 mln euro przy kursie 4,25 zł. Ile to złotych (mln zł)?",
             21.25, "5*4.25", ["5 · 4,25 = 21,25 mln zł"], unit="mln zł", tol=0.01),
          LB("Mezzanine 20 mln zł: odsetki 12% + premia 3% rocznie. Ile wynosi roczny koszt (mln zł)?",
             3, "20*0.15", ["20 · 15% = 3 mln zł"], unit="mln zł"),
          LB("Kredyt rewolwingowy: limit 5 mln zł, opłata za niewykorzystany limit 0,5%, wykorzystanie średnio 3 mln zł. Ile wynosi roczna opłata od niewykorzystanej części (zł)?",
             10000, "2000000*0.005", ["Niewykorzystane 2 mln zł · 0,5% = 10 000 zł"], unit="zł"),
      ],
      case=[
          PR("Konsorcjum buduje farmę fotowoltaiczną za 200 mln zł w spółce celowej. Bank finansuje 70% na 15 lat, zabezpieczając się umową sprzedaży energii z dużym odbiorcą na 15 lat po stałej cenie.",
             W("Ile wynosi kredyt?",
               "140 mln zł", "60 mln zł", "200 mln zł",
               why="200 · 70% = 140 mln zł."),
             W("Po co bankowi długoterminowa umowa sprzedaży energii?",
               "Daje przewidywalne przepływy na spłatę kredytu", "Obniża koszt paneli", "Zwalnia z podatku",
               why="Spłata zależy wyłącznie od przychodów projektu."),
             PF("Ryzyko spadku cen energii na rynku jest w tym projekcie ograniczone umową po stałej cenie.", True,
                why="Cena sprzedaży jest ustalona na cały okres kredytu."),
          ),
          PR("Browar rzemieślniczy chce zebrać 2 mln zł na rozbudowę. Rozważa crowdfunding udziałowy (inwestorzy-klienci) lub kredyt bankowy (wymaga zabezpieczeń, których browar nie ma).",
             W("Jaka jest korzyść marketingowa crowdfundingu udziałowego?",
               "Inwestorzy stają się ambasadorami marki", "Brak obowiązków informacyjnych", "Gwarantowany zysk",
               why="Klienci-współwłaściciele promują produkt."),
             W("Jaki jest koszt tej formy dla założycieli?",
               "Rozwodnienie udziałów i obowiązki wobec wielu inwestorów", "Wysokie raty kredytu", "Utrata licencji",
               why="Nowi udziałowcy mają prawa właścicielskie."),
             PF("Platforma crowdfundingowa działająca w Polsce potrzebuje zezwolenia KNF zgodnie z rozporządzeniem UE.", True,
                why="KNF jest właściwym organem nadzoru."),
          ),
      ]),

    L(4, "Ryzyko walutowe i stopy procentowej w firmie",
      "Rozpoznawać ekspozycję firmy na ryzyko kursowe i stopy procentowej, liczyć skutki zmian kursu i stóp oraz dobierać zabezpieczenia: naturalne, forward, opcje, swap; rozumieć finansowe aspekty działalności międzynarodowej.",
      ["Ryzyko walutowe i stopy procentowej w przedsiębiorstwie", "Międzynarodowe aspekty finansów firmy"],
      [S171, PARP],
      explain=[
          K("Rodzaje ekspozycji walutowej",
            "Transakcyjna – należności i zobowiązania w walucie obcej, których wartość w złotych zmieni się do dnia zapłaty. Przeliczeniowa (bilansowa) – wartość zagranicznych spółek zależnych w sprawozdaniu skonsolidowanym. Ekonomiczna – długoterminowy wpływ kursu na konkurencyjność firmy (np. silny złoty utrudnia eksport)."),
          K("Zabezpieczenia",
            "Naturalne: koszty w tej samej walucie co przychody (eksporter kupuje surowce w euro, zaciąga kredyt w euro). Forward: ustalenie kursu przyszłej transakcji dziś. Opcja walutowa: prawo sprzedaży waluty po ustalonym kursie – chroni przed spadkiem, zostawia zysk przy wzroście, ale kosztuje premię. Swap procentowy – zamiana zmiennej stopy kredytu na stałą."),
          W("Polski eksporter ma przychody w euro i koszty w złotych. Co mu szkodzi?",
            "Umocnienie złotego", "Osłabienie złotego", "Wzrost kursu euro",
            why="Za każde euro dostaje wtedy mniej złotych."),
          K("Ryzyko stopy procentowej",
            "Firma z kredytem o zmiennym oprocentowaniu (WIBOR, POLSTR + marża) ponosi ryzyko wzrostu rat, gdy rosną stopy. Firma z nadwyżkami gotówki – ryzyko spadku dochodów odsetkowych. Zabezpieczenia: kredyt o stałej stopie, swap procentowy (IRS), FRA, opcje na stopę (cap)."),
          K("Finanse międzynarodowe",
            "Działając za granicą, firma musi uwzględnić ryzyko kraju (polityczne, transferowe), różne systemy podatkowe (ceny transferowe, umowy o unikaniu podwójnego opodatkowania), koszt kapitału w różnych walutach i ubezpieczenie eksportu (np. KUKE). Parytet stóp procentowych wiąże kurs terminowy z różnicą stóp w dwóch krajach."),
          PF("Kredyt w euro dla firmy z przychodami w euro to forma zabezpieczenia naturalnego.", True,
             why="Raty i przychody są w tej samej walucie."),
      ],
      mech=[
          KT("Jaka to ekspozycja walutowa?",
             {"Transakcyjna": ["Należność 100 000 euro płatna za 60 dni", "Zobowiązanie wobec dostawcy z Chin w dolarach"],
              "Przeliczeniowa": ["Wycena czeskiej spółki zależnej w skonsolidowanym bilansie"],
              "Ekonomiczna": ["Silny złoty pogarsza konkurencyjność eksportu w kolejnych latach", "Konkurent z kraju o słabej walucie obniża ceny"]},
             why="Ekspozycje różnią się horyzontem i rodzajem skutku."),
          LN("Ułóż zabezpieczenie eksportera kontraktem forward.",
             ["Eksporter podpisuje kontrakt na dostawę za 500 000 euro płatne za 3 miesiące", "Obawia się umocnienia złotego", "Zawiera z bankiem forward na sprzedaż 500 000 euro po 4,28 zł", "Po 3 miesiącach kurs rynkowy wynosi 4,15 zł", "Eksporter sprzedaje euro po 4,28 zł i chroni marżę"],
             why="Forward ustala kurs z góry."),
          W("Importer płaci w dolarach za 90 dni i boi się wzrostu kursu USD. Co może zrobić?",
            "Kupić dolary terminowo (forward na kupno)", "Sprzedać dolary terminowo", "Nic – ryzyko go nie dotyczy",
            why="Ustala dziś kurs, po którym kupi walutę."),
          W("Dlaczego opcja walutowa kosztuje premię, a forward zwykle nie?",
            "Opcja daje prawo, ale nie obowiązek – zostawia możliwość zysku", "Bo forward jest nielegalny", "Bo opcja nie chroni przed ryzykiem",
            why="Asymetryczna ochrona ma swoją cenę."),
          M("Jakie są sposoby zabezpieczenia przed wzrostem stóp procentowych?",
            ["Kredyt o stałym oprocentowaniu", "Swap procentowy – płacenie stałej stopy", "Opcja cap na stopę procentową", "Zwiększenie kredytu o zmiennej stopie"], [0, 1, 2],
            why="Więcej długu o zmiennej stopie zwiększa ryzyko."),
          PF("Parytet stóp procentowych mówi, że waluta kraju o wyższych stopach jest w kontraktach terminowych tańsza niż w kursie bieżącym.", True,
             why="Różnica kursów kompensuje różnicę stóp."),
      ],
      calc=[
          LB("Należność 200 000 euro. Kurs spada z 4,30 do 4,18 zł. Ile eksporter traci (zł)?",
             24000, "200000*(4.30-4.18)", ["200 000 · 0,12 = 24 000 zł"], unit="zł"),
          LB("Forward na sprzedaż 500 000 euro po 4,28 zł; kurs rynkowy w dniu rozliczenia 4,15 zł. Ile zyskał dzięki zabezpieczeniu (zł)?",
             65000, "500000*(4.28-4.15)", ["500 000 · 0,13 = 65 000 zł"], unit="zł"),
          LB("Opcja put na euro: kurs wykonania 4,25 zł, premia 0,04 zł za euro, kurs rynkowy 4,10 zł. Ile wynosi efektywny kurs sprzedaży (zł)?",
             4.21, "4.25-0.04", ["Wykonuje opcję: 4,25 − premia 0,04 = 4,21 zł"], unit="zł", tol=0.001),
          LB("Ta sama opcja, ale kurs rynkowy 4,40 zł (opcji nie wykonuje). Ile wynosi efektywny kurs (zł)?",
             4.36, "4.40-0.04", ["Sprzedaje na rynku: 4,40 − 0,04 = 4,36 zł"], unit="zł", tol=0.001),
          LB("Kredyt 10 mln zł na WIBOR + 2%. WIBOR rośnie o 1,5 pkt proc. O ile wzrosną roczne odsetki (zł)?",
             150000, "10000000*0.015", ["10 mln · 1,5% = 150 000 zł"], unit="zł"),
          LB("Kurs bieżący 4,25 zł/EUR, roczna stopa w Polsce 4%, w strefie euro 2%. Ile wynosi roczny kurs terminowy wg parytetu stóp (zł)?",
             4.3333, "4.25*1.04/1.02", ["4,25 · 1,04 / 1,02 ≈ 4,3333"], unit="zł", tol=0.001),
      ],
      case=[
          PR("Producent mebli eksportuje 80% produkcji do Niemiec (przychody w euro), a 90% kosztów ponosi w złotych. Złoty umocnił się w ciągu roku z 4,50 do 4,20 zł za euro. Przychody wynoszą 10 mln euro rocznie.",
             W("Ile firma straciła w przeliczeniu na złote na rocznych przychodach (mln zł)?",
               "3 mln zł", "0,3 mln zł", "45 mln zł",
               why="10 mln · (4,50 − 4,20) = 3 mln zł."),
             W("Jakie zabezpieczenie naturalne może wprowadzić?",
               "Kupować surowce i zaciągać kredyty w euro", "Zwiększyć koszty w złotych", "Sprzedawać tylko w Polsce, zamykając eksport",
               why="Koszty w euro zrównoważą przychody w euro."),
             PF("Kontrakty forward na część przyszłych przychodów zmniejszyłyby niepewność kursową.", True,
                why="Ustalają kurs sprzedaży euro z góry."),
          ),
          PR("Firma ma kredyt 20 mln zł o zmiennej stopie WIBOR 3M + 1,8%. Zarząd obawia się wzrostu stóp. Bank proponuje swap: firma płaci stałe 4,6%, otrzymuje WIBOR 3M.",
             W("Ile będzie wynosić efektywne oprocentowanie po zawarciu swapu?",
               "6,4% stałe", "WIBOR + 1,8%", "4,6%",
               why="WIBOR z kredytu i swapu się znosi: 4,6% + 1,8% = 6,4%."),
             W("Co, jeśli WIBOR spadnie?",
               "Firma nie skorzysta na spadku – płaci nadal 6,4%", "Firma zapłaci mniej", "Swap automatycznie wygaśnie",
               why="Zabezpieczenie usuwa ryzyko w obie strony."),
             PF("Celem swapu jest przewidywalność kosztów finansowania.", True,
                why="Firma zamienia niepewność na stały koszt."),
          ),
      ]),

    L(5, "Przejęcia, wykupy oraz upadłość i restrukturyzacja",
      "Rozumieć motywy łączenia spółek i źródła synergii, mechanizm wykupu lewarowanego (LBO) i menedżerskiego (MBO) oraz polskie procedury restrukturyzacyjne i upadłościowe dla firm w kłopotach.",
      ["Łączenie spółek, wykupy LBO/MBO i synergia", "Upadłość i restrukturyzacja"],
      [PRESTR, PUPAD],
      explain=[
          K("Fuzje i przejęcia",
            "Połączenie (fuzja) tworzy jedną spółkę z dwóch; przejęcie – jedna spółka kupuje kontrolę nad drugą. Motywy: synergia (wartość połączonej firmy większa niż suma części – oszczędności kosztów, wyższe przychody, tańsze finansowanie), dostęp do rynków i technologii, eliminacja konkurenta. Wiele przejęć niszczy wartość – przejmujący przepłacają (premia > synergia)."),
          K("LBO i MBO",
            "Wykup lewarowany (LBO): fundusz kupuje spółkę, finansując zakup w dużej części długiem, który spłaca potem przejęta spółka ze swoich przepływów. Wykup menedżerski (MBO): kadra zarządzająca kupuje firmę, którą kieruje, zwykle z pomocą funduszu i banku. Wysoka dźwignia zwiększa zwrot przy sukcesie, ale i ryzyko upadłości.",
            w="synergia = V(A+B) − [V(A) + V(B)]"),
          W("Spółka A warta 300 mln zł przejmuje B wartą 100 mln zł. Połączona firma jest warta 450 mln zł. Ile wynosi synergia?",
            "50 mln zł", "150 mln zł", "450 mln zł",
            why="450 − (300 + 100) = 50 mln zł."),
          K("Restrukturyzacja",
            "Prawo restrukturyzacyjne (od 2016 r.) daje firmom zagrożonym niewypłacalnością lub niewypłacalnym szansę na układ z wierzycielami zamiast likwidacji. Postępowania: o zatwierdzenie układu, przyspieszone postępowanie układowe, postępowanie układowe i sanacyjne (najgłębsze – z ochroną przed egzekucją i możliwością odstąpienia od umów). Układ może obejmować rozłożenie długu na raty, umorzenie części, konwersję na udziały."),
          K("Upadłość",
            "Dłużnik jest niewypłacalny, gdy utracił zdolność do wykonywania wymagalnych zobowiązań (domniemanie: opóźnienie ponad 3 miesiące) lub gdy jego zobowiązania przekraczają wartość majątku przez ponad 24 miesiące. Zarząd musi złożyć wniosek o upadłość w ciągu 30 dni od wystąpienia niewypłacalności – inaczej członkowie zarządu ryzykują osobistą odpowiedzialność. Syndyk sprzedaje majątek i zaspokaja wierzycieli według kolejności kategorii."),
          PF("Postępowanie sanacyjne daje firmie ochronę przed egzekucją i czas na naprawę.", True,
             why="To najgłębsze postępowanie restrukturyzacyjne."),
      ],
      mech=[
          LN("Ułóż przebieg wykupu lewarowanego.",
             ["Fundusz wybiera spółkę o stabilnych przepływach", "Tworzy spółkę celową, która zaciąga kredyt na zakup", "Spółka celowa kupuje akcje spółki docelowej", "Przejęta spółka spłaca dług ze swoich przepływów", "Po kilku latach fundusz sprzedaje spółkę z zyskiem"],
             why="Dług finansuje zakup, a spłaca go przejęta firma."),
          KT("Restrukturyzacja czy upadłość?",
             {"Restrukturyzacja": ["Układ z wierzycielami na spłatę w ratach", "Postępowanie sanacyjne z ochroną przed egzekucją", "Konwersja długów na udziały"],
              "Upadłość": ["Syndyk sprzedaje majątek", "Zaspokojenie wierzycieli z masy upadłości", "Likwidacja działalności"]},
             why="Restrukturyzacja ma ratować firmę, upadłość – zaspokoić wierzycieli."),
          W("Spółka od 4 miesięcy nie płaci wymagalnych faktur. Co powinien zrobić zarząd?",
            "Złożyć wniosek o upadłość lub otworzyć restrukturyzację w ustawowym terminie", "Czekać na poprawę", "Wypłacić premie",
            why="Zachodzi domniemanie niewypłacalności; zwłoka grozi odpowiedzialnością osobistą."),
          W("Dlaczego wiele przejęć niszczy wartość dla akcjonariuszy przejmującego?",
            "Zapłacona premia przekracza faktyczną synergię", "Bo synergia zawsze jest ujemna", "Bo przejęcia są nielegalne",
            why="Nadmierny optymizm prowadzi do przepłacania."),
          M("Co może być źródłem synergii?",
            ["Wspólne zakupy i niższe koszty", "Sprzedaż produktów jednej firmy klientom drugiej", "Niższy koszt finansowania większej firmy", "Wyższa premia płacona akcjonariuszom przejmowanej spółki"], [0, 1, 2],
            why="Premia to koszt, nie źródło synergii."),
          PF("W MBO kupującymi są menedżerowie zarządzający firmą.", True,
             why="Management buy-out – wykup przez kadrę."),
      ],
      calc=[
          LB("Spółka B warta samodzielnie 200 mln zł. Synergia 40 mln zł. A płaci premię 25%. Ile zyskują akcjonariusze A (mln zł)?",
             -10, "40-200*0.25", ["Premia 50 mln zł", "40 − 50 = −10 mln zł – przepłacono"], unit="mln zł"),
          LB("LBO: cena 500 mln zł, dług 70%. Ile wynosi wkład własny funduszu (mln zł)?",
             150, "500*0.3", ["500 · 30% = 150 mln zł"], unit="mln zł"),
          LB("Po 5 latach fundusz sprzedaje spółkę za 650 mln zł; spłacono 150 mln zł długu (zostało 200 mln zł). Ile dostaje fundusz (mln zł)?",
             450, "650-200", ["650 − 200 = 450 mln zł"], unit="mln zł"),
          LB("Ile razy fundusz pomnożył wkład (450 / 150)?",
             3, "450/150", ["450 / 150 = 3"], unit="razy"),
          LB("Układ: dług 12 mln zł, umorzenie 40%, reszta w 24 równych ratach. Ile wynosi rata (tys. zł)?",
             300, "12000*0.6/24", ["Do spłaty 7,2 mln zł", "7 200 / 24 = 300 tys. zł"], unit="tys. zł"),
          LB("Masa upadłości 3 mln zł, wierzytelności kategorii z pierwszeństwem 1 mln zł, pozostałe 8 mln zł. Jaki procent dostaną pozostali wierzyciele?",
             25, "(3-1)/8*100", ["Po kategorii uprzywilejowanej zostaje 2 mln zł", "2 / 8 = 25%"], unit="%"),
      ],
      case=[
          PR("Producent opakowań ma 50 mln zł długu, przychody spadły o 40%, a od 2 miesięcy opóźnia płatności. Działalność jest rentowna operacyjnie po cięciu kosztów, ale dług jest za duży.",
             W("Jakie rozwiązanie daje szansę na przetrwanie firmy?",
               "Postępowanie restrukturyzacyjne i układ z wierzycielami", "Natychmiastowa likwidacja", "Nowy kredyt na wypłatę dywidendy",
               why="Restrukturyzacja pozwala zmniejszyć lub rozłożyć dług."),
             W("Dlaczego wierzyciele mogą zgodzić się na umorzenie części długu?",
               "Odzyskają więcej niż w upadłości z likwidacją majątku", "Bo prawo ich do tego zmusza w każdym przypadku", "Bo nic nie tracą",
               why="Wartość działającej firmy jest często wyższa niż likwidacyjna."),
             PF("Zarząd nie powinien zwlekać – po wystąpieniu niewypłacalności ma ustawowy termin na złożenie wniosku.", True,
                why="Opóźnienie grozi osobistą odpowiedzialnością członków zarządu."),
          ),
          PR("Fundusz private equity kupuje sieć sklepów za 1 mld zł, finansując 65% długiem, który obciąża przejętą spółkę. Plan: zwiększyć marże, sprzedać nieruchomości i po 5 latach wejść na giełdę.",
             W("Ile wynosi wkład własny funduszu?",
               "350 mln zł", "650 mln zł", "1 mld zł",
               why="1 000 · 35% = 350 mln zł."),
             W("Jakie ryzyko niesie wysoka dźwignia dla sieci?",
               "W recesji może zabraknąć gotówki na obsługę długu", "Brak ryzyka", "Spadek podatków",
               why="Stałe odsetki przy spadku sprzedaży grożą niewypłacalnością."),
             PF("Sprzedaż nieruchomości i ich odnajem (sale and leaseback) może pomóc spłacić dług, ale zwiększa przyszłe koszty najmu.", True,
                why="Gotówka teraz kosztem stałych opłat później."),
          ),
      ]),
]
