# -*- coding: utf-8 -*-
# Zrozumienie – Finanse przedsiębiorstw / Rachunek kosztów
OSM = "https://openstax.org/books/principles-managerial-accounting/pages/"
D = "2026-10-08"
M22 = S("OpenStax, Principles of Accounting Vol. 2, 2.2 Basic Cost Behavior Patterns", OSM + "2-2-identify-and-apply-basic-cost-behavior-patterns", D)
M31 = S("OpenStax, Principles of Accounting Vol. 2, 3.1 Contribution Margin", OSM + "3-1-explain-contribution-margin-and-calculate-contribution-margin-per-unit-contribution-margin-ratio-and-total-contribution-margin", D)
M32 = S("OpenStax, Principles of Accounting Vol. 2, 3.2 Break-Even Point", OSM + "3-2-calculate-a-break-even-point-in-units-and-dollars", D)
M61 = S("OpenStax, Principles of Accounting Vol. 2, 6.1 Traditional Overhead Allocation", OSM + "6-1-calculate-predetermined-overhead-and-total-cost-under-the-traditional-allocation-method", D)
M63 = S("OpenStax, Principles of Accounting Vol. 2, 6.3 Activity-Based Product Costs", OSM + "6-3-calculate-activity-based-product-costs", D)
M65 = S("OpenStax, Principles of Accounting Vol. 2, 6.5 Variable and Absorption Costing", OSM + "6-5-compare-and-contrast-variable-and-absorption-costing", D)
M114 = S("OpenStax, Principles of Accounting Vol. 2, 11.4 Discounted Cash Flow Models", OSM + "11-4-use-discounted-cash-flow-models-to-make-capital-investment-decisions", D)
UOR = S("Ustawa z 29 września 1994 r. o rachunkowości (ELI)", "https://api.sejm.gov.pl/eli/acts/DU/1994/591/text.pdf", D)

LESSONS = [
    L(1, "Klasyfikacje kosztów",
      "Grupować koszty według rodzajów, odróżniać koszty bezpośrednie od pośrednich i stałe od zmiennych oraz rozumieć, do jakich decyzji służy każda klasyfikacja.",
      ["Koszty według rodzajów", "Koszty bezpośrednie i pośrednie"],
      [M22, UOR],
      explain=[
          K("Koszty według rodzajów",
            "Układ rodzajowy pokazuje, na co firma wydała zasoby: amortyzacja, zużycie materiałów i energii, usługi obce, podatki i opłaty, wynagrodzenia, ubezpieczenia społeczne i inne świadczenia, pozostałe koszty rodzajowe. To podstawa porównawczego wariantu RZiS i analizy struktury kosztów."),
          K("Bezpośrednie i pośrednie",
            "Koszty bezpośrednie można przypisać konkretnemu produktowi na podstawie dokumentów (materiał zużyty na stół, płace stolarza przy tym stole). Pośrednie dotyczą wielu produktów naraz (czynsz hali, płace kierownika, energia całego zakładu) – rozlicza się je kluczem podziałowym, np. według godzin pracy maszyn."),
          W("Płaca kierownika hali, w której produkuje się 5 wyrobów, to koszt:",
            "Pośredni", "Bezpośredni", "Niezwiązany z produkcją",
            why="Dotyczy wszystkich wyrobów – trzeba go rozliczyć kluczem."),
          K("Stałe i zmienne",
            "Koszty zmienne rosną razem z wielkością produkcji (materiały, energia maszyn, prowizje od sprzedaży). Stałe nie zmieniają się w krótkim okresie (czynsz, amortyzacja, płace administracji). Na jednostkę produktu: koszt zmienny jednostkowy jest stały, a koszt stały jednostkowy maleje wraz z produkcją – to efekt skali.",
            w="KC = KS + kz · Q;  przeciętny KS = KS / Q"),
          K("Do czego służą klasyfikacje",
            "Układ rodzajowy – sprawozdawczość i kontrola struktury kosztów. Podział bezpośrednie/pośrednie – kalkulacja kosztu wyrobu i ustalanie cen. Podział stałe/zmienne – decyzje krótkookresowe: próg rentowności, przyjęcie dodatkowego zamówienia, wybór asortymentu."),
          PF("Przy wzroście produkcji koszt stały przypadający na jednostkę maleje.", True,
             why="Ta sama kwota rozkłada się na więcej sztuk."),
      ],
      mech=[
          KT("Koszt rodzajowy – która grupa?",
             {"Zużycie materiałów i energii": ["Drewno do produkcji mebli", "Prąd zużyty w hali"],
              "Usługi obce": ["Transport zlecony firmie kurierskiej", "Usługa sprzątania biura"],
              "Wynagrodzenia": ["Pensje pracowników produkcji", "Premie dla handlowców"],
              "Amortyzacja": ["Zużycie maszyny rozliczane w czasie", "Odpis od licencji na oprogramowanie"]},
             why="Grupowanie według natury wydatku."),
          KT("Bezpośredni czy pośredni (zakład produkujący kilka wyrobów)?",
             {"Bezpośredni": ["Tkanina zużyta na konkretną sofę", "Akordowa płaca tapicera za tę sofę"],
              "Pośredni": ["Ogrzewanie hali", "Ubezpieczenie budynku", "Płaca brygadzisty"]},
             why="Kryterium: czy da się przypisać konkretnemu wyrobowi."),
          LN("Ułóż kalkulację kosztu wytworzenia wyrobu.",
             ["Zbierz koszty bezpośrednie wyrobu (materiały, płace)", "Zbierz koszty pośrednie wydziału", "Wybierz klucz podziałowy, np. godziny pracy maszyn", "Rozlicz koszty pośrednie na wyroby według klucza", "Dodaj koszty bezpośrednie i przypisane pośrednie"],
             why="Koszty pośrednie wymagają rozliczenia kluczem."),
          W("Produkcja rośnie z 1000 do 2000 sztuk. Co dzieje się z jednostkowym kosztem zmiennym?",
            "Pozostaje taki sam", "Spada o połowę", "Podwaja się",
            why="Każda sztuka zużywa tyle samo materiału."),
          M("Które koszty są zwykle stałe w krótkim okresie?",
            ["Czynsz za halę", "Amortyzacja liniowa maszyn", "Płace zarządu", "Zużyte surowce"], [0, 1, 2],
            why="Zużycie surowców rośnie z produkcją."),
          PF("Ten sam koszt może być bezpośredni w jednej firmie, a pośredni w innej.", True,
             why="Zależy to od tego, czy firma potrafi go przypisać do konkretnego wyrobu."),
      ],
      calc=[
          LB("Koszty stałe 60 000 zł, koszt zmienny 25 zł/szt., produkcja 3 000 szt. Ile wynosi koszt całkowity (zł)?",
             135000, "60000+25*3000", ["60 000 + 75 000 = 135 000 zł"], unit="zł"),
          LB("Ile wynosi koszt jednostkowy przy 3 000 szt. (zł)?",
             45, "135000/3000", ["135 000 / 3 000 = 45 zł"], unit="zł"),
          LB("Ile wynosi koszt jednostkowy przy 6 000 szt. (zł)?",
             35, "(60000+25*6000)/6000", ["210 000 / 6 000 = 35 zł"], unit="zł"),
          LB("Koszty pośrednie 80 000 zł rozlicza się według godzin maszyn: wyrób A 1 500 h, B 2 500 h. Ile przypada na A (zł)?",
             30000, "80000*1500/4000", ["Stawka 80 000 / 4 000 = 20 zł/h", "1 500 · 20 = 30 000 zł"], unit="zł"),
          LB("Struktura: wynagrodzenia 420 tys. zł z kosztów rodzajowych 1 400 tys. zł. Jaki to udział (%)?",
             30, "420/1400*100", ["420 / 1400 = 30%"], unit="%"),
          LB("Wyrób: materiały 40 zł, płace bezpośrednie 15 zł, narzut kosztów pośrednich 120% płac bezpośrednich. Ile wynosi koszt wytworzenia (zł)?",
             73, "40+15+15*1.2", ["Narzut 15 · 120% = 18", "40 + 15 + 18 = 73 zł"], unit="zł"),
      ],
      case=[
          PR("Piekarnia produkuje chleb i bułki. Mąka i drożdże są przypisywane do produktów według receptur. Czynsz, energia pieca i pensja kierownika (razem 30 000 zł miesięcznie) dotyczą obu produktów. Chleb zajmuje piec 600 h, bułki 400 h.",
             W("Ile kosztów pośrednich przypisać bułkom według czasu pracy pieca?",
               "12 000 zł", "18 000 zł", "15 000 zł",
               why="30 000 · 400 / 1000 = 12 000 zł."),
             W("Co się stanie z kosztem jednego bochenka, jeśli produkcja chleba wzrośnie, a koszty pośrednie się nie zmienią?",
               "Spadnie – koszty stałe rozłożą się na więcej sztuk", "Wzrośnie", "Nie zmieni się",
               why="Efekt rozłożenia kosztów stałych."),
             PF("Wybór klucza podziałowego może zmienić obraz opłacalności produktów.", True,
                why="Inny klucz przypisze inną część kosztów pośrednich."),
          ),
          PR("Firma usługowa analizuje układ rodzajowy: wynagrodzenia i składki to 70% kosztów, usługi obce 15%, amortyzacja 5%, reszta 10%. Wszystkie płace rosną o 8%.",
             W("Jak wzrost płac wpłynie na koszty całkowite, jeśli rośnie tylko pozycja wynagrodzeń (z ubezpieczeniami)?",
               "Wzrosną o ok. 5,6%", "Wzrosną o 8%", "Wzrosną o 0,8%",
               why="70% · 8% = 5,6%."),
             W("Która firma jest najbardziej wrażliwa na wzrost płac?",
               "Pracochłonna firma usługowa", "Zautomatyzowana fabryka", "Spółka leasingowa",
               why="Udział płac w kosztach jest najwyższy."),
             PF("Analiza kosztów rodzajowych pozwala ocenić wrażliwość firmy na zmiany cen czynników produkcji.", True,
                why="Widać, jaki udział mają płace, materiały, energia."),
          ),
      ]),

    L(2, "Rachunek kosztów pełnych i zmiennych",
      "Rozumieć różnicę między rachunkiem kosztów pełnych i zmiennych, liczyć marżę pokrycia i wyjaśniać, dlaczego przy zmianie zapasów oba rachunki dają różny wynik.",
      ["Rachunek kosztów pełnych i zmiennych", "Koszty bezpośrednie i pośrednie"],
      [M65, M31],
      explain=[
          K("Dwa sposoby liczenia kosztu wyrobu",
            "W rachunku kosztów pełnych (absorpcyjnym) koszt wyrobu obejmuje koszty zmienne i część stałych kosztów produkcji – stałe „wędrują” razem z zapasem. W rachunku kosztów zmiennych koszt wyrobu to tylko koszty zmienne, a wszystkie koszty stałe obciążają wynik okresu, w którym powstały."),
          K("Marża pokrycia",
            "Marża pokrycia = przychody − koszty zmienne. Jednostkowo: cena − jednostkowy koszt zmienny. Pokazuje, ile każda sprzedana sztuka „dokłada” do pokrycia kosztów stałych i zysku. Wskaźnik marży = marża / przychody.",
            w="marża pokrycia = p − kz;  zysk = marża · Q − KS"),
          W("Cena 50 zł, koszt zmienny 30 zł. Ile wynosi jednostkowa marża pokrycia?",
            "20 zł", "80 zł", "30 zł",
            why="50 − 30 = 20 zł."),
          K("Dlaczego wyniki się różnią",
            "Gdy produkcja przewyższa sprzedaż, w rachunku pełnym część kosztów stałych trafia do zapasu (bilansu), więc wynik okresu jest wyższy niż w rachunku zmiennym. Gdy zapasy maleją, jest odwrotnie. Przy produkcji równej sprzedaży wyniki są identyczne."),
          K("Zastosowania",
            "Rachunek kosztów pełnych wymaga prawo bilansowe do wyceny zapasów. Rachunek zmienny lepiej służy decyzjom krótkookresowym: pokazuje, jak zysk zmienia się ze sprzedażą, nie pozwala „poprawić” wyniku nadprodukcją, ułatwia ocenę opłacalności produktów i zamówień."),
          PF("Przy produkcji równej sprzedaży rachunek pełny i zmienny dają ten sam zysk.", True,
             why="Nie ma zmiany zapasu, więc koszty stałe w całości obciążają okres."),
      ],
      mech=[
          KT("Rachunek pełny czy zmienny?",
             {"Rachunek kosztów pełnych": ["Wycena zapasów w bilansie zgodnie z ustawą", "Koszt stały produkcji wchodzi w koszt wyrobu"],
              "Rachunek kosztów zmiennych": ["Marża pokrycia jako kluczowa miara", "Wszystkie koszty stałe obciążają okres", "Decyzja o dodatkowym zamówieniu"]},
             why="Różnią się traktowaniem kosztów stałych produkcji."),
          LN("Ułóż, jak nadprodukcja może „poprawić” wynik w rachunku pełnym.",
             ["Menedżer zwiększa produkcję ponad sprzedaż", "Koszty stałe rozkładają się na więcej sztuk", "Część kosztów stałych trafia do niesprzedanego zapasu", "Koszt sprzedanych wyrobów spada", "Wynik okresu rośnie, choć sprzedaż się nie zmieniła"],
             why="Dlatego do oceny menedżerów lepszy jest rachunek zmienny."),
          W("Produkcja 10 000 szt., sprzedaż 8 000 szt. Który rachunek pokaże wyższy zysk?",
            "Rachunek kosztów pełnych", "Rachunek kosztów zmiennych", "Oba taki sam",
            why="Część kosztów stałych zostaje w zapasie 2 000 szt."),
          W("Produkt ma dodatnią marżę pokrycia, ale po przypisaniu kosztów stałych wykazuje stratę. Czy wycofać go natychmiast?",
            "Niekoniecznie – pokrywa część kosztów stałych, które i tak by zostały", "Tak, zawsze", "Nie ma to znaczenia",
            why="Po wycofaniu koszty stałe pozostaną, a zniknie marża."),
          M("Co wynika z dodatniej marży pokrycia produktu?",
            ["Każda sztuka pokrywa swój koszt zmienny", "Produkt dokłada się do pokrycia kosztów stałych", "Krótkookresowo sprzedaż zwiększa zysk całej firmy", "Produkt na pewno jest rentowny po kosztach pełnych"], [0, 1, 2],
            why="Rentowność po kosztach pełnych zależy też od przypisanych kosztów stałych."),
          PF("Rachunek kosztów zmiennych nie pozwala zawyżyć zysku przez nadprodukcję.", True,
             why="Koszty stałe obciążają okres niezależnie od zapasów."),
      ],
      calc=[
          LB("Cena 80 zł, koszt zmienny 50 zł, sprzedaż 4 000 szt. Ile wynosi marża pokrycia całkowita (zł)?",
             120000, "(80-50)*4000", ["30 · 4 000 = 120 000 zł"], unit="zł"),
          LB("Koszty stałe 90 000 zł. Ile wynosi zysk w rachunku zmiennym (zł)?",
             30000, "120000-90000", ["120 000 − 90 000 = 30 000 zł"], unit="zł"),
          LB("Ile wynosi wskaźnik marży pokrycia (cena 80, kz 50) w %?",
             37.5, "(80-50)/80*100", ["30 / 80 = 37,5%"], unit="%", tol=0.01),
          LB("Rachunek pełny: koszty stałe produkcji 90 000 zł, produkcja 5 000 szt. Ile kosztu stałego przypada na sztukę (zł)?",
             18, "90000/5000", ["90 000 / 5 000 = 18 zł"], unit="zł"),
          LB("Sprzedano 4 000 z 5 000 szt. Ile kosztów stałych zostaje w zapasie 1 000 szt. (zł)?",
             18000, "1000*18", ["1 000 · 18 = 18 000 zł"], unit="zł"),
          LB("Ile wynosi więc zysk w rachunku pełnym (zysk zmienny 30 000 + koszty stałe w zapasie, zł)?",
             48000, "30000+18000", ["30 000 + 18 000 = 48 000 zł"], unit="zł"),
      ],
      case=[
          PR("Kierownik zakładu ma premię zależną od zysku liczonego rachunkiem kosztów pełnych. Pod koniec roku zwiększa produkcję o 30% ponad popyt. Magazyn się zapełnia, a raport pokazuje wyższy zysk.",
             W("Skąd wziął się wyższy zysk?",
               "Część kosztów stałych przeniesiono do zapasu", "Wzrosła sprzedaż", "Spadły ceny surowców",
               why="Nadprodukcja odracza koszty stałe do kolejnego okresu."),
             W("Jak zarząd może zapobiec takim zachowaniom?",
               "Oceniać kierownika rachunkiem kosztów zmiennych lub z kontrolą zapasów", "Zwiększyć premię za produkcję", "Zakazać sprzedaży",
               why="Rachunek zmienny nie nagradza nadprodukcji."),
             PF("Nadmierny zapas generuje też koszty magazynowania i ryzyko przeterminowania.", True,
                why="Zamrożony kapitał i koszty utrzymania zapasu."),
          ),
          PR("Firma produkuje trzy produkty. Produkt C ma cenę 40 zł, koszt zmienny 32 zł i przypisane koszty stałe 12 zł na sztukę. Zarząd chce go wycofać, bo „przynosi stratę 4 zł na sztuce”. Koszty stałe po wycofaniu nie spadną.",
             W("Ile wynosi marża pokrycia produktu C?",
               "8 zł na sztukę", "Strata 4 zł", "40 zł",
               why="40 − 32 = 8 zł."),
             W("Co stanie się z zyskiem firmy po wycofaniu C przy sprzedaży 10 000 szt.?",
               "Spadnie o 80 000 zł", "Wzrośnie o 40 000 zł", "Nie zmieni się",
               why="Znika marża 8 · 10 000, a koszty stałe zostają."),
             PF("Decyzję o wycofaniu produktu należy opierać na marży pokrycia i kosztach, których da się uniknąć.", True,
                why="Koszty stałe, które pozostaną, nie są istotne dla tej decyzji."),
          ),
      ]),

    L(3, "Próg rentowności i decyzje krótkookresowe",
      "Liczyć próg rentowności ilościowy i wartościowy oraz margines bezpieczeństwa, a także podejmować decyzje o dodatkowym zamówieniu i „produkować czy kupić” na podstawie marży pokrycia i kosztów istotnych.",
      ["Próg rentowności (BEP)", "Rachunek kosztów pełnych i zmiennych"],
      [M32, M31],
      explain=[
          K("Próg rentowności",
            "To wielkość sprzedaży, przy której przychody pokrywają wszystkie koszty, a zysk wynosi zero. Ilościowo: BEP = KS / (p − kz). Wartościowo: BEP = KS / wskaźnik marży pokrycia. Powyżej progu każda sztuka zwiększa zysk o marżę jednostkową.",
            w="BEP(szt.) = KS / (p − kz);  BEP(zł) = KS / [(p − kz)/p]"),
          K("Margines bezpieczeństwa i sprzedaż docelowa",
            "Margines bezpieczeństwa = (sprzedaż planowana − BEP) / sprzedaż planowana – mówi, o ile może spaść sprzedaż, zanim firma zacznie ponosić stratę. Sprzedaż potrzebna do osiągnięcia zysku docelowego Z: Q = (KS + Z) / (p − kz).",
            w="MB = (Q − BEP) / Q;  Q_Z = (KS + Z) / (p − kz)"),
          W("Koszty stałe 120 000 zł, cena 50 zł, koszt zmienny 30 zł. Ile wynosi próg rentowności?",
            "6 000 szt.", "2 400 szt.", "4 000 szt.",
            why="120 000 / 20 = 6 000 szt."),
          K("Dodatkowe zamówienie",
            "Gdy firma ma wolne moce produkcyjne, dodatkowe zamówienie po cenie niższej od kosztu pełnego może być opłacalne, jeśli cena przekracza koszt zmienny (i dodatkowe koszty zamówienia) – koszty stałe i tak są ponoszone. Uwaga na ryzyko, że stali klienci zażądają takich samych cen."),
          K("Produkować czy kupić",
            "Porównuje się koszty istotne – te, które różnią się między wariantami: koszt zakupu z zewnątrz vs koszty zmienne własnej produkcji i koszty stałe, których da się uniknąć. Koszty stałe, które pozostaną bez względu na decyzję, są nieistotne (to także dotyczy kosztów utopionych)."),
          PF("Koszty utopione, poniesione w przeszłości, nie powinny wpływać na decyzję o przyszłości.", True,
             why="Nie zmienią się bez względu na wybór."),
      ],
      mech=[
          LN("Ułóż kroki decyzji o dodatkowym zamówieniu.",
             ["Sprawdź, czy firma ma wolne moce produkcyjne", "Ustal koszty zmienne i dodatkowe koszty zamówienia", "Porównaj oferowaną cenę z kosztem przyrostowym", "Oceń skutki dla stałych klientów i cen", "Przyjmij zamówienie, jeśli zwiększa łączny zysk"],
             why="Liczą się koszty przyrostowe, nie pełne."),
          KT("Koszt istotny czy nieistotny przy decyzji „produkować czy kupić”?",
             {"Istotny": ["Materiały do własnej produkcji", "Płace akordowe przy produkcji części", "Cena zakupu części od dostawcy", "Czynsz za halę, którą można wynająć, jeśli zrezygnujemy z produkcji"],
              "Nieistotny": ["Amortyzacja już kupionej maszyny bez alternatywnego zastosowania", "Płaca dyrektora, która się nie zmieni"]},
             why="Istotne są tylko koszty różniące się między wariantami."),
          W("Rosną koszty stałe przy stałej cenie i koszcie zmiennym. Co dzieje się z progiem rentowności?",
            "Rośnie", "Spada", "Nie zmienia się",
            why="BEP = KS / marża jednostkowa."),
          W("Cena rośnie przy niezmienionych kosztach. Co z progiem rentowności?",
            "Spada", "Rośnie", "Nie zmienia się",
            why="Rośnie marża jednostkowa, więc potrzeba mniej sztuk."),
          M("Kiedy przyjąć dodatkowe zamówienie poniżej zwykłej ceny?",
            ["Gdy są wolne moce produkcyjne", "Gdy cena pokrywa koszty zmienne i dodatkowe", "Gdy nie zaszkodzi to cenom dla stałych klientów", "Gdy cena jest niższa od kosztu zmiennego"], [0, 1, 2],
            why="Cena poniżej kosztu zmiennego zmniejsza zysk."),
          PF("Margines bezpieczeństwa 25% oznacza, że sprzedaż może spaść o jedną czwartą, zanim firma zacznie tracić.", True,
             why="Tyle wynosi odległość od progu rentowności."),
      ],
      calc=[
          LB("KS 200 000 zł, cena 100 zł, kz 60 zł. Ile wynosi BEP ilościowy (szt.)?",
             5000, "200000/(100-60)", ["200 000 / 40 = 5 000 szt."], unit="szt."),
          LB("Ile wynosi BEP wartościowy (zł)?",
             500000, "200000/(40/100)", ["Wskaźnik marży 40%", "200 000 / 0,4 = 500 000 zł"], unit="zł"),
          LB("Planowana sprzedaż 8 000 szt. Ile wynosi margines bezpieczeństwa (%)?",
             37.5, "(8000-5000)/8000*100", ["3 000 / 8 000 = 37,5%"], unit="%", tol=0.01),
          LB("Ile sztuk trzeba sprzedać, by osiągnąć zysk 100 000 zł?",
             7500, "(200000+100000)/40", ["300 000 / 40 = 7 500 szt."], unit="szt."),
          LB("Dodatkowe zamówienie: 1 000 szt. po 75 zł, kz 60 zł, dodatkowy transport 5 000 zł. Ile wynosi zmiana zysku (zł)?",
             10000, "1000*(75-60)-5000", ["15 000 − 5 000 = 10 000 zł"], unit="zł"),
          LB("Część kupiona kosztuje 42 zł; własna produkcja: kz 35 zł plus koszty stałe do uniknięcia 12 000 zł przy 2 000 szt. Ile kosztuje własna produkcja na sztukę (koszty istotne, zł)?",
             41, "35+12000/2000", ["35 + 6 = 41 zł < 42 zł – opłaca się produkować"], unit="zł"),
      ],
      case=[
          PR("Producent rowerów: cena 1 500 zł, koszt zmienny 900 zł, koszty stałe 1,8 mln zł rocznie. Planuje sprzedaż 4 000 szt. Sieć handlowa proponuje dodatkowe zamówienie 500 szt. po 1 100 zł; zakład ma wolne moce.",
             W("Ile wynosi próg rentowności?",
               "3 000 szt.", "2 000 szt.", "4 000 szt.",
               why="1 800 000 / 600 = 3 000 szt."),
             W("Ile wynosi zysk przy planowanej sprzedaży 4 000 szt.?",
               "600 000 zł", "2 400 000 zł", "1 800 000 zł",
               why="4 000 · 600 − 1 800 000 = 600 000 zł."),
             W("O ile wzrośnie zysk po przyjęciu zamówienia sieci?",
               "100 000 zł", "550 000 zł", "Spadnie o 200 000 zł",
               why="500 · (1 100 − 900) = 100 000 zł."),
             PF("Cena 1 100 zł jest niższa od kosztu pełnego jednego roweru (ok. 1 350 zł), a mimo to zamówienie się opłaca.", True,
                why="Koszty stałe są już pokryte przez podstawową sprzedaż."),
          ),
          PR("Firma kupiła rok temu maszynę za 300 000 zł, której nie da się sprzedać. Rozważa, czy dalej produkować na niej część (kz 30 zł/szt.), czy kupować ją po 26 zł/szt. Potrzebuje 20 000 szt. rocznie.",
             W("Czy koszt zakupu maszyny jest istotny dla decyzji?",
               "Nie – to koszt utopiony", "Tak – trzeba go odzyskać", "Tylko w połowie",
               why="Wydatku nie da się już cofnąć."),
             W("Która opcja jest tańsza?",
               "Zakup części – oszczędność 80 000 zł rocznie", "Własna produkcja", "Są równe",
               why="20 000 · (30 − 26) = 80 000 zł."),
             PF("Błąd utopionych kosztów polega na kontynuowaniu nieopłacalnego działania, bo „już dużo zainwestowano”.", True,
                why="Decyzje dotyczą przyszłych kosztów i korzyści."),
          ),
      ]),

    L(4, "Rachunek kosztów działań (ABC)",
      "Rozumieć, dlaczego tradycyjne rozliczanie kosztów pośrednich jednym kluczem zniekształca koszty produktów i jak rachunek ABC przypisuje koszty według rzeczywistego zużycia działań.",
      ["Rachunek kosztów działań (ABC)", "Koszty bezpośrednie i pośrednie"],
      [M61, M63],
      explain=[
          K("Problem jednego klucza",
            "Gdy koszty pośrednie rozlicza się jednym kluczem (np. godzinami pracy bezpośredniej), produkty masowe, robione dużymi partiami, „dopłacają” do produktów niszowych, które wymagają wielu ustawień maszyn, zamówień i kontroli jakości. Firma może wtedy błędnie uznać produkty niszowe za opłacalne, a masowe – za drogie."),
          K("Logika ABC",
            "Rachunek kosztów działań: 1) zidentyfikuj działania (przezbrajanie maszyn, zamawianie materiałów, kontrola jakości, obsługa klienta), 2) przypisz im koszty zasobów, 3) dla każdego działania wybierz nośnik kosztów (liczba przezbrojeń, liczba zamówień), 4) policz stawkę = koszt działania / liczba nośników, 5) przypisz koszty produktom według zużycia nośników.",
            w="stawka działania = koszt działania / liczba nośników"),
          W("Co jest najlepszym nośnikiem kosztów działania „przezbrajanie maszyn”?",
            "Liczba przezbrojeń", "Liczba pracowników biura", "Powierzchnia magazynu",
            why="Koszt zależy od liczby przezbrojeń, a nie od wielkości produkcji."),
          K("Hierarchia kosztów",
            "Koszty na poziomie jednostki (energia na sztukę), partii (przezbrojenie przed każdą partią), produktu (projekt, utrzymanie dokumentacji) i zakładu (zarząd, budynek). Tradycyjny rachunek traktuje wszystkie jak koszty jednostkowe; ABC rozróżnia poziomy."),
          K("Korzyści i koszty ABC",
            "ABC daje dokładniejsze koszty produktów i klientów, pokazuje, które działania są drogie i co można usprawnić (zarządzanie działaniami). Jest jednak kosztowny we wdrożeniu i utrzymaniu, dlatego opłaca się zwłaszcza przy dużym udziale kosztów pośrednich i zróżnicowanym asortymencie."),
          PF("ABC może wykazać, że produkt niszowy jest droższy, niż pokazywał tradycyjny rachunek.", True,
             why="Produkty niszowe zużywają wiele działań na poziomie partii i produktu."),
      ],
      mech=[
          LN("Ułóż kroki wdrożenia ABC.",
             ["Zidentyfikuj główne działania w firmie", "Przypisz do działań koszty zasobów", "Wybierz nośnik kosztów dla każdego działania", "Policz stawkę na jednostkę nośnika", "Przypisz koszty produktom według zużycia nośników"],
             why="Koszty płyną: zasoby → działania → produkty."),
          KT("Na jakim poziomie powstaje koszt?",
             {"Jednostki": ["Energia zużyta przez maszynę na każdą sztukę", "Opakowanie każdego wyrobu"],
              "Partii": ["Przezbrojenie linii przed partią", "Kontrola pierwszej sztuki z partii"],
              "Produktu": ["Projektowanie nowego wzoru", "Certyfikacja produktu"],
              "Zakładu": ["Wynagrodzenie dyrektora", "Ochrona budynku"]},
             why="Hierarchia pomaga dobrać nośniki kosztów."),
          W("Tradycyjny rachunek rozlicza koszty pośrednie według godzin pracy. Co dzieje się z kosztem produktu masowego w porównaniu z ABC?",
            "Jest zwykle zawyżony", "Jest zwykle zaniżony", "Jest identyczny",
            why="Produkt masowy zużywa wiele godzin, ale mało przezbrojeń i zamówień."),
          W("W jakiej firmie wdrożenie ABC przyniesie największe korzyści?",
            "W firmie z wysokimi kosztami pośrednimi i wieloma różnymi produktami", "W firmie z jednym produktem", "W firmie bez kosztów pośrednich",
            why="Tam zniekształcenia tradycyjnego rachunku są największe."),
          M("Jakie są zalety ABC?",
            ["Dokładniejszy koszt produktów", "Wskazanie kosztownych działań do usprawnienia", "Lepsza ocena rentowności klientów", "Niskie koszty wdrożenia"], [0, 1, 2],
            why="Wdrożenie ABC bywa kosztowne."),
          PF("W ABC koszty pośrednie rozlicza się wieloma nośnikami zamiast jednym kluczem.", True,
             why="Każde działanie ma własny nośnik."),
      ],
      calc=[
          LB("Koszt działania „przezbrajanie” 60 000 zł, liczba przezbrojeń 300. Ile wynosi stawka (zł/przezbrojenie)?",
             200, "60000/300", ["60 000 / 300 = 200 zł"], unit="zł"),
          LB("Produkt niszowy wymagał 120 przezbrojeń. Ile kosztów przezbrajania przypada na niego (zł)?",
             24000, "120*200", ["120 · 200 = 24 000 zł"], unit="zł"),
          LB("Produkt niszowy: 1 000 szt. Ile kosztów przezbrajania przypada na sztukę (zł)?",
             24, "24000/1000", ["24 000 / 1 000 = 24 zł"], unit="zł"),
          LB("Koszt działania „zamawianie materiałów” 45 000 zł, 900 zamówień. Produkt masowy wymaga 150 zamówień. Ile kosztów zamawiania mu przypada (zł)?",
             7500, "45000/900*150", ["Stawka 50 zł", "150 · 50 = 7 500 zł"], unit="zł"),
          LB("Tradycyjnie: koszty pośrednie 200 000 zł na 10 000 h pracy; produkt niszowy zużywa 1 000 h. Ile kosztów pośrednich mu przypada (zł)?",
             20000, "200000/10000*1000", ["Stawka 20 zł/h", "1 000 · 20 = 20 000 zł"], unit="zł"),
          LB("Według ABC na produkt niszowy przypada 52 000 zł kosztów pośrednich. O ile procent tradycyjny rachunek go zaniżał?",
             61.54, "(1-20000/52000)*100", ["20 000 / 52 000 ≈ 38,46%", "Zaniżenie ≈ 61,54%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Firma produkuje standardowe krzesła (50 000 szt., 20 partii) i krzesła na zamówienie (2 000 szt., 200 partii). Koszty pośrednie (500 000 zł) rozliczała według godzin pracy, przez co krzesła na zamówienie wydawały się bardzo rentowne. Koszt przezbrojeń to 220 000 zł.",
             W("Ile kosztów przezbrojeń przypada na jedną partię?",
               "1 000 zł", "11 000 zł", "100 zł",
               why="220 000 / 220 partii = 1 000 zł."),
             W("Ile kosztów przezbrojeń przypada na krzesła na zamówienie?",
               "200 000 zł", "20 000 zł", "110 000 zł",
               why="200 partii · 1 000 zł = 200 000 zł."),
             PF("Po wdrożeniu ABC krzesła na zamówienie mogą okazać się znacznie mniej rentowne, a standardowe – bardziej.", True,
                why="Wcześniej standardowe dopłacały do kosztów partii zamówień."),
          ),
          PR("Hurtownia analizuje klientów metodą ABC. Klient X kupuje za 1 mln zł rocznie w 10 dużych dostawach. Klient Y kupuje za 1 mln zł w 400 małych dostawach z pilnym transportem. Marża brutto na towarze u obu wynosi 15%.",
             W("Który klient jest prawdopodobnie bardziej rentowny?",
               "X – mniej dostaw i niższe koszty obsługi", "Y – więcej zamówień", "Obaj tak samo",
               why="Koszty obsługi zamówień i transportu rosną z liczbą dostaw."),
             W("Co hurtownia może zaproponować klientowi Y?",
               "Minimalną wartość zamówienia lub opłatę za pilne dostawy", "Wyższy rabat", "Darmowy transport każdej dostawy",
               why="Ceny powinny odzwierciedlać koszt obsługi."),
             PF("ABC można stosować także do oceny rentowności klientów, nie tylko produktów.", True,
                why="Klienci również zużywają działania firmy."),
          ),
      ]),

    L(5, "Koszt kapitału i WACC",
      "Liczyć koszt kapitału obcego po opodatkowaniu i koszt kapitału własnego z modelu CAPM, łączyć je w średni ważony koszt kapitału (WACC) i rozumieć jego rolę jako minimalnej stopy zwrotu z inwestycji.",
      ["Średni ważony koszt kapitału (WACC)", "Koszt kapitału własnego i obcego"],
      [M114],
      explain=[
          K("Koszt kapitału obcego",
            "To oprocentowanie kredytów i obligacji. Ponieważ odsetki są kosztem uzyskania przychodu, rzeczywisty koszt jest niższy o tarczę podatkową: k_d po podatku = k_d · (1 − T).",
            w="k_d(po podatku) = k_d · (1 − T)"),
          K("Koszt kapitału własnego",
            "To stopa zwrotu, jakiej oczekują właściciele – wyższa niż dla wierzycieli, bo ponoszą większe ryzyko (są zaspokajani na końcu). Szacuje się ją np. modelem CAPM: k_e = r_f + β · (E(R_m) − r_f), albo modelem Gordona: k_e = D₁/P + g.",
            w="k_e = r_f + β · (E(R_m) − r_f)"),
          W("r_f = 5%, premia rynkowa 6%, beta 1,0. Ile wynosi koszt kapitału własnego?",
            "11%", "6%", "5%",
            why="5% + 1,0 · 6% = 11%."),
          K("WACC",
            "Średni ważony koszt kapitału łączy koszty źródeł według ich udziałów w finansowaniu (najlepiej wartości rynkowych): WACC = E/V · k_e + D/V · k_d · (1 − T). To minimalna stopa zwrotu, jaką musi przynosić przeciętna inwestycja firmy, by nie niszczyć wartości – stosuje się ją jako stopę dyskontową w NPV.",
            w="WACC = E/V · k_e + D/V · k_d · (1 − T)"),
          K("Dług tańszy, ale…",
            "Kapitał obcy jest tańszy od własnego (niższe ryzyko dla wierzyciela i tarcza podatkowa), więc umiarkowane zadłużenie obniża WACC. Zbyt duży dług zwiększa jednak ryzyko bankructwa – rośnie i k_d, i k_e, a WACC zaczyna rosnąć. Szuka się optymalnej struktury kapitału."),
          PF("Projekt, którego stopa zwrotu jest niższa od WACC, niszczy wartość firmy (przy przeciętnym ryzyku).", True,
             why="Nie pokrywa kosztu kapitału, którym jest finansowany."),
      ],
      mech=[
          LN("Ułóż kroki liczenia WACC.",
             ["Ustal wartość rynkową kapitału własnego (E) i długu (D)", "Policz udziały E/V i D/V", "Oszacuj koszt kapitału własnego, np. z CAPM", "Policz koszt długu po opodatkowaniu", "Zważ koszty udziałami i zsumuj"],
             why="WACC to średnia ważona kosztów źródeł finansowania."),
          KT("Co podnosi, a co obniża WACC (ceteris paribus)?",
             {"Podnosi WACC": ["Wzrost stopy wolnej od ryzyka", "Wyższa beta akcji firmy", "Obniżenie ratingu i wzrost kosztu długu"],
              "Obniża WACC": ["Wyższa stawka podatku (większa tarcza)", "Spadek premii za ryzyko rynkowe", "Umiarkowane zastąpienie drogiego kapitału własnego tańszym długiem"]},
             why="Każdy składnik wzoru zmienia średnią."),
          W("Dlaczego kapitał własny jest droższy od obcego?",
            "Właściciele ponoszą większe ryzyko – są zaspokajani na końcu", "Bo od kapitału własnego płaci się odsetki", "Bo kapitał własny nie daje praw głosu",
            why="Wyższe ryzyko wymaga wyższej oczekiwanej stopy zwrotu."),
          W("Projekt ma oczekiwaną stopę zwrotu 9%, WACC firmy 10,5%, ryzyko projektu przeciętne. Co zrobić?",
            "Odrzucić projekt", "Przyjąć projekt", "Finansować wyłącznie długiem, bo jest tańszy",
            why="Zwrot poniżej kosztu kapitału obniża wartość."),
          M("Jakie stwierdzenia o koszcie długu są prawdziwe?",
            ["Odsetki dają tarczę podatkową", "Koszt długu po podatku = k_d · (1 − T)", "Bardzo wysoki dług podnosi koszt długu", "Dług nigdy nie zwiększa ryzyka firmy"], [0, 1, 2],
            why="Dług zwiększa ryzyko finansowe."),
          PF("Do liczenia WACC lepiej używać wartości rynkowych niż księgowych kapitału.", True,
             why="Odzwierciedlają aktualny koszt pozyskania kapitału."),
      ],
      calc=[
          LB("Kredyt oprocentowany na 8%, CIT 19%. Ile wynosi koszt długu po opodatkowaniu (%)?",
             6.48, "8*0.81", ["8% · 0,81 = 6,48%"], unit="%", tol=0.01),
          LB("r_f = 5,5%, β = 1,2, premia rynkowa 5%. Ile wynosi koszt kapitału własnego (%)?",
             11.5, "5.5+1.2*5", ["5,5 + 6 = 11,5%"], unit="%", tol=0.01),
          LB("E = 600, D = 400 (mln zł). k_e = 11,5%, k_d po podatku 6,48%. Ile wynosi WACC (%)?",
             9.49, "0.6*11.5+0.4*6.48", ["0,6 · 11,5 = 6,9", "0,4 · 6,48 = 2,592", "Razem ≈ 9,49%"], unit="%", tol=0.02),
          LB("Model Gordona: D₁ = 3 zł, cena 60 zł, g = 4%. Ile wynosi k_e (%)?",
             9, "3/60*100+4", ["5% + 4% = 9%"], unit="%"),
          LB("Firma finansowana wyłącznie kapitałem własnym o koszcie 12%. Ile wynosi WACC (%)?",
             12, "12", ["Brak długu: WACC = k_e = 12%"], unit="%"),
          LB("Projekt: nakład 1 mln zł, jednorazowy wpływ za rok 1,1 mln zł, WACC 9,49%. Ile wynosi NPV (zł)?",
             4657.96, "1100000/1.0949-1000000", ["1 100 000 / 1,0949 ≈ 1 004 657,96", "NPV ≈ 4 657,96 zł"], unit="zł", tol=0.01),
      ],
      case=[
          PR("Spółka energetyczna: wartość rynkowa akcji 3 mld zł, dług 2 mld zł oprocentowany na 7%. Beta 0,8, r_f 5%, premia rynkowa 6%. CIT 19%.",
             W("Ile wynosi koszt kapitału własnego?",
               "9,8%", "11%", "7%",
               why="5% + 0,8 · 6% = 9,8%."),
             W("Ile wynosi koszt długu po opodatkowaniu (w przybliżeniu)?",
               "5,67%", "7%", "1,33%",
               why="7% · 0,81 = 5,67%."),
             W("Ile wynosi WACC (w przybliżeniu)?",
               "8,15%", "9,8%", "6,4%",
               why="0,6 · 9,8 + 0,4 · 5,67 ≈ 5,88 + 2,27 = 8,15%."),
          ),
          PR("Po serii podwyżek stóp procentowych stopa wolna od ryzyka rośnie z 3% do 6%, a koszt kredytów firm o 3 pkt proc. Firma ma WACC 8% i portfel projektów o oczekiwanym zwrocie 9–10%.",
             W("Jak zmieni się WACC?",
               "Wzrośnie – drożeje i kapitał własny, i dług", "Spadnie", "Nie zmieni się",
               why="r_f wchodzi do k_e, a k_d rośnie razem ze stopami."),
             W("Co może się stać z planami inwestycyjnymi?",
               "Część projektów przestanie być opłacalna i zostanie odłożona", "Wszystkie projekty staną się bardziej opłacalne", "Brak wpływu",
               why="Wyższa stopa dyskontowa obniża NPV."),
             PF("Ten mechanizm jest jednym z kanałów, przez które polityka pieniężna wpływa na inwestycje.", True,
                why="Wyższe stopy – wyższy koszt kapitału – mniej inwestycji."),
          ),
      ]),
]
