# -*- coding: utf-8 -*-
# Zrozumienie – Finanse przedsiębiorstw / Instytucje
D = "2026-10-08"
CEIDG = S("gov.pl – CEIDG (Centralna Ewidencja i Informacja o Działalności Gospodarczej)", "https://www.gov.pl/web/ceidg", D)
KRS = S("Ministerstwo Sprawiedliwości – Krajowy Rejestr Sądowy", "https://www.gov.pl/web/sprawiedliwosc/krajowy-rejestr-sadowy", D)
EKRS = S("e-KRS – portal rejestrowy", "https://ekrs.ms.gov.pl/", D)
UPRP = S("Urząd Patentowy Rzeczypospolitej Polskiej (gov.pl)", "https://www.gov.pl/web/uprp", D)
PARP = S("Polska Agencja Rozwoju Przedsiębiorczości", "https://www.parp.gov.pl/", D)
RMSP = S("Rzecznik Małych i Średnich Przedsiębiorców", "https://www.rzecznikmsp.gov.pl/", D)
MRT = S("Ministerstwo Rozwoju i Technologii", "https://www.gov.pl/web/rozwoj-technologia", D)

LESSONS = [
    L(1, "Rejestry, sądy gospodarcze i Urząd Patentowy",
      "Rozumieć, gdzie i jak rejestruje się działalność (CEIDG, KRS), jakie informacje są jawne, jak sądy gospodarcze rozstrzygają spory przedsiębiorców i jaką rolę pełni Urząd Patentowy RP.",
      ["CEIDG i KRS", "Sądy gospodarcze", "Urząd Patentowy RP"],
      [CEIDG, KRS, UPRP],
      explain=[
          K("CEIDG",
            "Centralna Ewidencja i Informacja o Działalności Gospodarczej to bezpłatny, elektroniczny rejestr przedsiębiorców będących osobami fizycznymi (JDG, wspólnicy spółek cywilnych). Wniosek CEIDG-1 jest „jednym okienkiem”: jednocześnie zgłasza do urzędu skarbowego (NIP), GUS (REGON) i ZUS. Dane są jawne i dostępne online."),
          K("KRS",
            "Krajowy Rejestr Sądowy prowadzą sądy rejonowe (wydziały gospodarcze KRS). Składa się z rejestru przedsiębiorców (spółki handlowe, spółdzielnie, przedsiębiorstwa państwowe), rejestru stowarzyszeń i fundacji oraz rejestru dłużników niewypłacalnych. Od 1.07.2021 r. postępowanie rejestrowe toczy się wyłącznie elektronicznie. Wpis spółki kapitałowej jest konstytutywny – spółka nabywa osobowość prawną z chwilą wpisu."),
          W("Gdzie rejestruje się spółkę z o.o.?",
            "W KRS", "W CEIDG", "W Urzędzie Patentowym",
            why="Spółki handlowe wpisuje się do rejestru przedsiębiorców KRS."),
          K("Sądy gospodarcze",
            "Spory między przedsiębiorcami w sprawach z ich działalności rozpatrują sądy powszechne według przepisów o postępowaniu w sprawach gospodarczych – z szybszymi, bardziej sformalizowanymi zasadami (np. obowiązek przedstawienia dowodów w pozwie). Drobne roszczenia można dochodzić elektronicznie w e-sądzie (elektroniczne postępowanie upominawcze)."),
          K("Urząd Patentowy RP",
            "Udziela patentów na wynalazki, praw ochronnych na wzory użytkowe i znaki towarowe oraz praw z rejestracji wzorów przemysłowych. Prowadzi rejestry i bazy, w których można sprawdzić, czy rozwiązanie lub znak nie są już chronione. Ochronę w całej UE zapewniają też EUIPO (znaki unijne) i Europejski Urząd Patentowy."),
          PF("Spółka z o.o. uzyskuje osobowość prawną z chwilą wpisu do KRS.", True,
             why="Wpis spółki kapitałowej do KRS jest konstytutywny."),
      ],
      mech=[
          KT("Gdzie załatwisz sprawę?",
             {"CEIDG": ["Rejestracja jednoosobowej działalności", "Zawieszenie działalności przez osobę fizyczną"],
              "KRS": ["Zmiana składu zarządu spółki akcyjnej", "Rejestracja fundacji", "Wpis prokury spółki z o.o."],
              "Urząd Patentowy RP": ["Zgłoszenie znaku towarowego", "Wniosek o patent na wynalazek"]},
             why="Każda instytucja ma inny zakres."),
          LN("Ułóż rejestrację spółki z o.o. przez internet.",
             ["Wspólnicy zawierają umowę spółki (np. przez wzorzec w systemie S24 lub u notariusza)", "Wnoszą kapitał zakładowy", "Składają elektronicznie wniosek do KRS", "Sąd rejestrowy dokonuje wpisu", "Spółka uzyskuje osobowość prawną i NIP oraz REGON"],
             why="Od 2021 r. postępowanie rejestrowe w KRS jest elektroniczne."),
          W("Klient sprawdza wiarygodność kontrahenta – spółki akcyjnej. Gdzie znajdzie skład zarządu i sposób reprezentacji?",
            "W odpisie z KRS", "W CEIDG", "W księdze wieczystej",
            why="KRS ujawnia dane o organach i reprezentacji spółek."),
          W("Firma chce sprawdzić, czy nazwa jej nowego produktu nie narusza cudzego znaku towarowego. Gdzie szuka?",
            "W bazach Urzędu Patentowego RP i EUIPO", "W CEIDG", "W rejestrze dłużników",
            why="Urzędy własności przemysłowej prowadzą rejestry znaków."),
          M("Jakie korzyści daje elektroniczna rejestracja w CEIDG?",
            ["Jedno zgłoszenie do kilku urzędów (NIP, REGON, ZUS)", "Brak opłaty za wpis", "Szybkość i dostępność online", "Automatyczne zwolnienie z podatków"], [0, 1, 2],
            why="Rejestracja nie zwalnia z obowiązków podatkowych."),
          PF("Dane w CEIDG i KRS są jawne.", True,
             why="Jawność rejestrów chroni bezpieczeństwo obrotu."),
      ],
      calc=[
          LB("Opłata za wpis w CEIDG wynosi 0 zł, a koszt założenia spółki w S24 to 250 zł (opłata sądowa i ogłoszenie, dane umowne). Ile kosztują łącznie oba wpisy (zł)?",
             250, "0+250", ["0 + 250 = 250 zł"], unit="zł"),
          LB("Ochrona patentowa trwa do 20 lat. Patent zgłoszony w 2019 r. – do którego roku?",
             2039, "2019+20", ["2019 + 20 = 2039"], unit=""),
          LB("Znak towarowy zarejestrowany w 2016 r. na 10 lat. W którym roku trzeba go odnowić?",
             2026, "2016+10", ["2016 + 10 = 2026"], unit=""),
          LB("Postępowanie rejestrowe w KRS jest elektroniczne od 1.07.2021. Ile lat minęło do lipca 2026 r.?",
             5, "2026-2021", ["2026 − 2021 = 5"], unit="lat"),
          LB("Firma dochodzi w e-sądzie 120 faktur po średnio 1 500 zł. Ile wynosi łączna kwota roszczeń (zł)?",
             180000, "120*1500", ["120 · 1 500 = 180 000 zł"], unit="zł"),
          LB("Opłata od pozwu w e-sądzie to 1/4 zwykłej opłaty. Zwykła opłata przy roszczeniu 20 000 zł wynosi 1 000 zł. Ile wynosi w e-sądzie (zł)?",
             250, "1000/4", ["1 000 / 4 = 250 zł"], unit="zł"),
      ],
      case=[
          PR("Przedsiębiorca chce podpisać duży kontrakt ze spółką z o.o. „Alfa”. Z odpisu KRS wynika, że spółka ma dwuosobowy zarząd, a do składania oświadczeń wymagane jest współdziałanie dwóch członków zarządu. Umowę przysłał do podpisu tylko jeden z nich.",
             W("Czy podpis jednego członka zarządu wystarczy?",
               "Nie – zgodnie z KRS potrzebne jest współdziałanie dwóch członków", "Tak, zawsze wystarczy jeden", "Tak, jeśli jest prezesem",
               why="Sposób reprezentacji określa umowa spółki ujawniona w KRS."),
             W("Co jeszcze warto sprawdzić w KRS?",
               "Czy spółka nie jest w likwidacji lub upadłości", "Numer księgi wieczystej prezesa", "Prywatny adres wspólników",
               why="KRS ujawnia m.in. otwarcie likwidacji i upadłości."),
             PF("Jawność KRS chroni kontrahentów spółki.", True,
                why="Pozwala sprawdzić reprezentację i sytuację prawną."),
          ),
          PR("Mała firma z Gdańska wymyśliła nowy zawór do instalacji wodnych i markę „AquaStop”. Chce sprzedawać produkt w całej UE.",
             W("Gdzie zgłosi wynalazek, by uzyskać ochronę w Polsce?",
               "W Urzędzie Patentowym RP", "W CEIDG", "W KRS",
               why="UPRP udziela patentów w Polsce."),
             W("Jak chronić markę w całej UE jednym zgłoszeniem?",
               "Zgłosić znak towarowy UE w EUIPO", "Zarejestrować domenę internetową", "Złożyć wniosek do KRS",
               why="Znak unijny obowiązuje we wszystkich państwach UE."),
             PF("Przed zgłoszeniem warto sprawdzić bazy, czy podobne rozwiązanie lub znak nie są już chronione.", True,
                why="Zapobiega to sporom i odmowie rejestracji."),
          ),
      ]),

    L(2, "Wsparcie przedsiębiorców: PARP, PFR i Rzecznik MŚP",
      "Rozumieć, jak państwo wspiera małe i średnie firmy (PARP, PFR), jak działała Tarcza Finansowa w pandemii i w czym pomaga Rzecznik Małych i Średnich Przedsiębiorców.",
      ["Polska Agencja Rozwoju Przedsiębiorczości (PARP)", "Polski Fundusz Rozwoju (PFR)", "Rzecznik Małych i Średnich Przedsiębiorców", "Mała, średnia i mikrofirma (MŚP)"],
      [PARP, RMSP, MRT],
      explain=[
          K("PARP",
            "Polska Agencja Rozwoju Przedsiębiorczości (agencja rządowa) wdraża programy wsparcia MŚP, często współfinansowane z funduszy UE: dotacje na innowacje i wzornictwo, szkolenia (Baza Usług Rozwojowych), wsparcie startupów i eksportu. Zbiera też dane o kondycji sektora MŚP w raportach."),
          K("PFR",
            "Polski Fundusz Rozwoju to grupa instytucji finansowych państwa (m.in. fundusze inwestycyjne, KUKE, PFR TFI), która inwestuje w rozwój gospodarki, wspiera eksport i zarządza PPK przez Portal PPK. W pandemii 2020 r. prowadził Tarczę Finansową – subwencje dla setek tysięcy firm, częściowo umarzane przy utrzymaniu działalności i zatrudnienia."),
          W("Która instytucja prowadziła Tarczę Finansową dla firm w pandemii?",
            "Polski Fundusz Rozwoju", "Urząd Patentowy RP", "Krajowy Rejestr Sądowy",
            why="Tarcza Finansowa była programem PFR."),
          K("Rzecznik MŚP",
            "Rzecznik Małych i Średnich Przedsiębiorców (od 2018 r., z Konstytucji biznesu) stoi na straży praw MŚP: interweniuje w sporach z administracją, może wnosić o interpretacje, przystępować do postępowań, opiniować projekty przepisów. Pomaga bezpłatnie."),
          K("Dlaczego wspiera się MŚP",
            "Małe firmy mają trudniejszy dostęp do kapitału (brak zabezpieczeń, historii), wyższe jednostkowe koszty regulacji i mniejsze możliwości badań. Wsparcie publiczne ma korygować te zawodności rynku – ale musi być zgodne z zasadami pomocy publicznej UE (np. limity de minimis)."),
          PF("Rzecznik MŚP może pomóc przedsiębiorcy w sporze z urzędem skarbowym.", True,
             why="Interweniuje w sprawach przedsiębiorców wobec administracji."),
      ],
      mech=[
          KT("Do kogo się zwrócić?",
             {"PARP": ["Dotacja na wdrożenie wzornictwa", "Dofinansowanie szkoleń pracowników"],
              "PFR": ["Inwestycja funduszu państwowego w rozwój spółki", "Ubezpieczenie eksportu przez KUKE"],
              "Rzecznik MŚP": ["Spór z urzędem o interpretację przepisów", "Przewlekła kontrola w firmie"]},
             why="Każda instytucja ma inny zakres wsparcia."),
          LN("Ułóż drogę firmy po dotację na innowację.",
             ["Firma śledzi ogłoszenia konkursów PARP", "Przygotowuje projekt i wniosek o dofinansowanie", "Wniosek jest oceniany według kryteriów", "Firma podpisuje umowę i realizuje projekt", "Rozlicza wydatki i osiąga zaplanowane wskaźniki"],
             why="Dotacje rozlicza się według umowy."),
          W("Dlaczego subwencje Tarczy Finansowej były częściowo umarzane?",
            "By zachęcić firmy do utrzymania działalności i zatrudnienia", "Bo państwo nie chciało ich zwrotu w ogóle", "Bo były kredytami komercyjnymi",
            why="Warunki umorzenia premiowały utrzymanie miejsc pracy."),
          W("Dlaczego małe firmy trudniej uzyskują kredyt niż duże?",
            "Mają mniej zabezpieczeń i krótszą historię, a bank ponosi wysokie koszty oceny", "Bo prawo im zabrania", "Bo nie płacą podatków",
            why="Asymetria informacji i koszty transakcyjne są dla nich wyższe."),
          M("Jakie instytucje należą do Grupy PFR?",
            ["KUKE", "PFR TFI", "Fundusze inwestycyjne PFR", "Urząd Patentowy RP"], [0, 1, 2],
            why="UPRP to centralny organ administracji."),
          PF("Pomoc publiczna dla firm musi być zgodna z regułami UE, np. limitami de minimis.", True,
             why="Chroni to konkurencję na rynku wewnętrznym."),
      ],
      calc=[
          LB("Projekt PARP: koszty kwalifikowalne 800 000 zł, dofinansowanie 70%. Ile wynosi dotacja (zł)?",
             560000, "800000*0.7", ["800 000 · 70% = 560 000 zł"], unit="zł"),
          LB("Wkład własny firmy w tym projekcie (zł)?",
             240000, "800000-560000", ["800 000 − 560 000 = 240 000 zł"], unit="zł"),
          LB("Subwencja 300 000 zł, umorzono 75% przy utrzymaniu zatrudnienia. Ile firma musi zwrócić (zł)?",
             75000, "300000*0.25", ["300 000 · 25% = 75 000 zł"], unit="zł"),
          LB("Rzecznik MŚP działa od 2018 r. Ile lat działa w 2026 r.?",
             8, "2026-2018", ["2026 − 2018 = 8"], unit="lat"),
          LB("Limit pomocy de minimis od 2024 r.: 300 000 euro w ciągu 3 lat, kurs 4,25 zł. Ile to złotych?",
             1275000, "300000*4.25", ["300 000 · 4,25 = 1 275 000 zł"], unit="zł"),
          LB("Firma otrzymała już 900 000 zł pomocy de minimis. Ile może jeszcze dostać do limitu 1 275 000 zł (zł)?",
             375000, "1275000-900000", ["1 275 000 − 900 000 = 375 000 zł"], unit="zł"),
      ],
      case=[
          PR("Firma rodzinna (30 pracowników) chce wejść na rynek niemiecki z nowym produktem. Potrzebuje 1 mln zł na wzornictwo, certyfikaty i targi. Bank odmawia kredytu bez zabezpieczeń.",
             W("Gdzie może szukać dotacji na wzornictwo i promocję?",
               "W programach PARP", "W KRS", "W Urzędzie Patentowym",
               why="PARP wdraża programy wsparcia MŚP."),
             W("Jak zabezpieczyć należności od niemieckich klientów?",
               "Ubezpieczyć je w KUKE (Grupa PFR)", "Nie da się", "Przez wpis do CEIDG",
               why="KUKE ubezpiecza należności eksportowe."),
             PF("Gwarancja de minimis BGK może pomóc uzyskać kredyt mimo braku zabezpieczeń.", True,
                why="BGK gwarantuje część kredytu dla MŚP."),
          ),
          PR("Urząd od 8 miesięcy prowadzi kontrolę w małej firmie, wielokrotnie żądając tych samych dokumentów. Przedsiębiorca uważa, że narusza to jego prawa.",
             W("Kto może interweniować w obronie przedsiębiorcy?",
               "Rzecznik Małych i Średnich Przedsiębiorców", "Prezes NBP", "KNF",
               why="Rzecznik MŚP chroni prawa przedsiębiorców wobec administracji."),
             W("Na jaką zasadę Konstytucji biznesu może się powołać?",
               "Proporcjonalności i zaufania do przedsiębiorcy", "Zasadę ostrożności w rachunkowości", "Zasadę Bagehota",
               why="Prawo przedsiębiorców wymaga działań proporcjonalnych."),
             PF("Prawo przedsiębiorców ogranicza czas kontroli w zależności od wielkości firmy.", True,
                why="Limity czasu kontroli różnią się dla mikro, małych, średnich i dużych firm."),
          ),
      ]),
]
