# -*- coding: utf-8 -*-
# Zrozumienie – Finanse przedsiębiorstw / Przepisy i stawki
D = "2026-10-08"
ELI = "https://api.sejm.gov.pl/eli/acts/DU/"
KSH = S("Kodeks spółek handlowych (Dz.U. 2000 nr 94 poz. 1037 – ELI)", ELI + "2000/1037/text.pdf", D)
KC = S("Kodeks cywilny (Dz.U. 1964 nr 16 poz. 93 – ELI)", ELI + "1964/93/text.pdf", D)
KP = S("Kodeks pracy (Dz.U. 1974 nr 24 poz. 141 – ELI)", ELI + "1974/141/text.pdf", D)
PP = S("Prawo przedsiębiorców (Dz.U. 2018 poz. 646 – ELI)", ELI + "2018/646/text.pdf", D)
UOR = S("Ustawa o rachunkowości (Dz.U. 1994 nr 121 poz. 591 – ELI)", ELI + "1994/591/text.pdf", D)
OFE = S("Ustawa o ofercie publicznej (Dz.U. 2005 nr 184 poz. 1539 – ELI)", ELI + "2005/1539/text.pdf", D)
OBR = S("Ustawa o obrocie instrumentami finansowymi (Dz.U. 2005 nr 183 poz. 1538 – ELI)", ELI + "2005/1538/text.pdf", D)
PWP = S("Prawo własności przemysłowej (Dz.U. 2001 nr 49 poz. 508 – ELI)", ELI + "2001/508/text.pdf", D)
PA = S("Ustawa o prawie autorskim i prawach pokrewnych (Dz.U. 1994 nr 24 poz. 83 – ELI)", ELI + "1994/83/text.pdf", D)
PUPAD = S("Prawo upadłościowe (Dz.U. 2003 nr 60 poz. 535 – ELI)", ELI + "2003/535/text.pdf", D)
PRESTR = S("Prawo restrukturyzacyjne (Dz.U. 2015 poz. 978 – ELI)", ELI + "2015/978/text.pdf", D)
CIT = S("Ministerstwo Finansów – podatki.gov.pl: CIT", "https://www.podatki.gov.pl/cit/", D)
KSEF = S("Ministerstwo Finansów – podatki.gov.pl: KSeF", "https://www.podatki.gov.pl/ksef/", D)
PIT = S("Ministerstwo Finansów – podatki.gov.pl: PIT", "https://www.podatki.gov.pl/pit/", D)

LESSONS = [
    L(1, "Kodeksy prawa gospodarczego",
      "Wiedzieć, co regulują Kodeks cywilny, Kodeks spółek handlowych, Kodeks pracy i Prawo przedsiębiorców, i umieć wskazać właściwy akt dla typowych sytuacji w firmie.",
      ["Kodeks cywilny (1964)", "Kodeks spółek handlowych (2000)", "Kodeks pracy (1974)", "Prawo przedsiębiorców (2018)"],
      [KC, KSH, KP, PP],
      explain=[
          K("Kodeks cywilny (1964)",
            "Podstawa prawa prywatnego: osoby fizyczne i prawne, czynności prawne i pełnomocnictwo (w tym prokura), własność i prawa rzeczowe, zobowiązania i umowy (sprzedaż, najem, zlecenie, dzieło), odpowiedzialność odszkodowawcza, przedawnienie, spadki."),
          K("KSH (2000) i Kodeks pracy (1974)",
            "KSH reguluje tworzenie, ustrój, łączenie, podział i przekształcanie spółek handlowych – osobowych i kapitałowych. Kodeks pracy – stosunek pracy: umowy, wynagrodzenie, czas pracy, urlopy, BHP, ochronę pracowników, uprawnienia rodzicielskie."),
          W("W którym akcie znajdziesz zasady zwoływania walnego zgromadzenia S.A.?",
            "W Kodeksie spółek handlowych", "W Kodeksie pracy", "W Prawie autorskim",
            why="Ustrój spółek reguluje KSH."),
          K("Prawo przedsiębiorców (2018)",
            "Określa zasady podejmowania, wykonywania i zakończenia działalności gospodarczej, prawa i obowiązki przedsiębiorców oraz zadania organów: wolność działalności, domniemanie uczciwości, działalność nierejestrowana, „ulga na start”, zasady kontroli przedsiębiorców (limity czasu kontroli)."),
          K("Jak szukać przepisu",
            "Najpierw ustal, kogo dotyczy sprawa (umowa między stronami – KC; ustrój spółki – KSH; pracownik – KP; relacja przedsiębiorcy z urzędem – Prawo przedsiębiorców) i czy istnieje ustawa szczególna (np. o prawach konsumenta). Teksty jednolite publikuje się w Dzienniku Ustaw, dostępnym m.in. przez ELI Sejmu."),
          PF("Umowę o dzieło reguluje Kodeks cywilny, a umowę o pracę – Kodeks pracy.", True,
             why="Umowy cywilnoprawne są w KC, stosunek pracy – w KP."),
      ],
      mech=[
          KT("Który kodeks?",
             {"Kodeks cywilny": ["Umowa sprzedaży samochodu", "Przedawnienie roszczeń", "Zadatek i kara umowna"],
              "Kodeks spółek handlowych": ["Minimalny kapitał spółki z o.o.", "Obowiązki rady nadzorczej S.A."],
              "Kodeks pracy": ["Okres wypowiedzenia umowy o pracę", "Wymiar urlopu wypoczynkowego"],
              "Prawo przedsiębiorców": ["Działalność nierejestrowana", "Limity czasu kontroli przedsiębiorcy"]},
             why="Każdy akt reguluje inną dziedzinę."),
          LN("Ułóż chronologię aktów.",
             ["Kodeks cywilny", "Kodeks pracy", "Kodeks spółek handlowych", "Prawo przedsiębiorców"],
             why="1964 → 1974 → 2000 → 2018."),
          W("Spór dotyczy wadliwego towaru kupionego przez firmę od innej firmy. Jaki akt jest podstawowy?",
            "Kodeks cywilny", "Kodeks pracy", "Prawo przedsiębiorców",
            why="Umowa sprzedaży i rękojmia między przedsiębiorcami – KC."),
          W("Pracownik pyta o liczbę dni urlopu. Gdzie szukać?",
            "W Kodeksie pracy", "W Kodeksie spółek handlowych", "W Prawie restrukturyzacyjnym",
            why="Urlopy reguluje Kodeks pracy."),
          M("Co reguluje Kodeks spółek handlowych?",
            ["Rodzaje spółek handlowych", "Organy spółek kapitałowych", "Łączenie i przekształcanie spółek", "Wymiar czasu pracy"], [0, 1, 2],
            why="Czas pracy – Kodeks pracy."),
          PF("Kodeks spółek handlowych zastąpił w 2001 r. przedwojenny Kodeks handlowy z 1934 r.", True,
             why="KSH uchwalono w 2000 r., wszedł w życie 1.01.2001."),
      ],
      calc=[
          LB("Ile lat dzieli Kodeks cywilny (1964) od Kodeksu pracy (1974)?",
             10, "1974-1964", ["1974 − 1964 = 10"], unit="lat"),
          LB("Ile lat obowiązuje KSH (w życie 2001 r.) w 2026 r.?",
             25, "2026-2001", ["2026 − 2001 = 25"], unit="lat"),
          LB("Kontrola w mikroprzedsiębiorstwie może trwać do 12 dni roboczych w roku. Ile tygodni pracy po 5 dni to w przybliżeniu (tygodnie)?",
             2.4, "12/5", ["12 / 5 = 2,4"], unit="tyg.", tol=0.01),
          LB("Ile lat minęło od Prawa przedsiębiorców (2018) do 2026 r.?",
             8, "2026-2018", ["2026 − 2018 = 8"], unit="lat"),
          LB("Ile lat minęło od Kodeksu handlowego (1934) do wejścia w życie KSH (2001)?",
             67, "2001-1934", ["2001 − 1934 = 67"], unit="lat"),
          LB("Ile lat obowiązuje Kodeks cywilny w 2026 r. (w życie 1965 r.)?",
             61, "2026-1965", ["2026 − 1965 = 61"], unit="lat"),
      ],
      case=[
          PR("Spółka z o.o. „Delta” zatrudnia 15 pracowników, kupuje surowce od dostawców i właśnie zmienia skład zarządu. Pracownik zgłasza zaległe nadgodziny, a dostawca – opóźnienie płatności.",
             W("Który akt dotyczy zmiany składu zarządu?",
               "Kodeks spółek handlowych", "Kodeks pracy", "Prawo autorskie",
               why="Organy spółki reguluje KSH."),
             W("Który akt dotyczy nadgodzin?",
               "Kodeks pracy", "Kodeks cywilny", "KSH",
               why="Czas pracy i wynagrodzenie za nadgodziny – KP."),
             PF("Opóźnienie zapłaty dostawcy reguluje Kodeks cywilny oraz ustawa o przeciwdziałaniu nadmiernym opóźnieniom w transakcjach handlowych.", True,
                why="To zobowiązanie umowne między przedsiębiorcami."),
          ),
          PR("Urząd kontroluje małą firmę i chce przedłużyć kontrolę ponad limity. Przedsiębiorca powołuje się na „Konstytucję biznesu”.",
             W("Który akt określa limity czasu kontroli?",
               "Prawo przedsiębiorców", "Kodeks pracy", "Kodeks cywilny",
               why="Rozdział o kontroli działalności gospodarczej."),
             W("Do kogo może się zwrócić o pomoc?",
               "Do Rzecznika MŚP", "Do KNF", "Do UPRP",
               why="Rzecznik MŚP chroni przedsiębiorców wobec administracji."),
             PF("Limit czasu kontroli zależy od wielkości przedsiębiorcy.", True,
                why="Inne limity dotyczą mikro, małych, średnich i dużych firm."),
          ),
      ]),

    L(2, "Rynek kapitałowy i własność intelektualna w przepisach",
      "Rozumieć, co regulują ustawy o ofercie publicznej i o obrocie instrumentami finansowymi, znać progi znacznych pakietów akcji oraz zakres ustaw o prawie własności przemysłowej i o prawie autorskim.",
      ["Ustawa o ofercie publicznej (2005) i o obrocie instrumentami finansowymi (2005)", "Progi znacznych pakietów akcji (spółki publiczne)", "Prawo własności przemysłowej (2000)", "Ustawa o prawie autorskim (1994)"],
      [OFE, OBR, PWP, PA],
      explain=[
          K("Dwie ustawy rynku kapitałowego (2005)",
            "Ustawa o ofercie publicznej: warunki oferowania papierów, obowiązki informacyjne spółek publicznych, znaczne pakiety akcji i wezwania. Ustawa o obrocie instrumentami finansowymi: zasady obrotu, działalność firm inwestycyjnych (domów maklerskich), rynek regulowany i ASO, ochrona klientów. Obie stosuje się razem z unijnymi rozporządzeniami (prospektowym, MAR)."),
          K("Znaczne pakiety akcji",
            "Kto osiągnie lub przekroczy 5%, 10%, 15%, 20%, 25%, 33%, 33⅓%, 50%, 75%, 90% lub 95% głosów w spółce publicznej (albo zejdzie poniżej tych progów), musi w krótkim terminie zawiadomić KNF i spółkę – inwestorzy dowiadują się o zmianach kontroli. Przekroczenie 50% głosów wymaga od 2022 r. ogłoszenia wezwania na pozostałe akcje."),
          W("Inwestor zwiększa udział z 9% do 12% głosów w spółce publicznej. Co musi zrobić?",
            "Zawiadomić KNF i spółkę – przekroczył próg 10%", "Ogłosić wezwanie na 100% akcji", "Nic",
            why="Przekroczenie progu 10% wymaga zawiadomienia."),
          K("Prawo własności przemysłowej (2000)",
            "Reguluje wynalazki (patenty, do 20 lat), wzory użytkowe (do 10 lat), wzory przemysłowe (do 25 lat), znaki towarowe (10 lat z możliwością odnowienia), oznaczenia geograficzne i topografie układów scalonych. Prawa udziela Urząd Patentowy RP."),
          K("Prawo autorskie (1994)",
            "Chroni utwory – każdy przejaw działalności twórczej o indywidualnym charakterze (teksty, programy komputerowe, muzyka, zdjęcia, projekty). Prawa osobiste (np. autorstwo) są niezbywalne; majątkowe (do korzystania i zarabiania) można przenieść lub udzielić licencji; trwają 70 lat po śmierci twórcy."),
          PF("Ochrona patentowa wymaga zgłoszenia i decyzji urzędu, a prawa autorskie powstają automatycznie.", True,
             why="To podstawowa różnica między tymi reżimami."),
      ],
      mech=[
          KT("Która ustawa?",
             {"O ofercie publicznej": ["Zawiadomienie o przekroczeniu 25% głosów", "Obowiązek wezwania po przekroczeniu 50%"],
              "O obrocie instrumentami finansowymi": ["Licencja domu maklerskiego", "Zasady funkcjonowania rynku regulowanego"],
              "Prawo własności przemysłowej": ["Rejestracja znaku towarowego", "Patent na wynalazek"],
              "Prawo autorskie": ["Ochrona programu komputerowego", "Licencja na wykorzystanie zdjęcia"]},
             why="Każda ustawa reguluje inny obszar."),
          LN("Ułóż, co dzieje się, gdy inwestor buduje pakiet w spółce giełdowej.",
             ["Inwestor kupuje akcje na giełdzie", "Przekracza 5% głosów i zawiadamia KNF oraz spółkę", "Spółka publikuje raport bieżący", "Inwestor przekracza kolejne progi, każdorazowo zawiadamiając", "Po przekroczeniu 50% ogłasza wezwanie na pozostałe akcje"],
             why="Przejrzystość zmian w akcjonariacie chroni pozostałych inwestorów."),
          W("Dlaczego obowiązek zawiadamiania o znacznych pakietach jest ważny dla rynku?",
            "Informuje inwestorów o zmianach kontroli i możliwych przejęciach", "Bo zwiększa podatki", "Bo zakazuje handlu akcjami",
            why="Przejrzystość akcjonariatu ogranicza asymetrię informacji."),
          W("Programista stworzył aplikację w ramach umowy o pracę. Do kogo zwykle należą autorskie prawa majątkowe?",
            "Do pracodawcy (z mocy prawa, w granicach umowy)", "Wyłącznie do programisty", "Do Urzędu Patentowego",
            why="Prawo autorskie przyznaje je pracodawcy dla programów stworzonych w ramach obowiązków."),
          M("Które progi głosów wymagają zawiadomienia KNF?",
            ["5%", "33⅓%", "90%", "7%"], [0, 1, 2],
            why="7% nie jest progiem ustawowym."),
          PF("Znak towarowy można chronić bezterminowo, regularnie odnawiając rejestrację.", True,
             why="Ochronę przedłuża się na kolejne 10-letnie okresy."),
      ],
      calc=[
          LB("Spółka ma 20 mln głosów. Ile głosów to próg 33⅓%? (zaokrąglij do pełnej liczby)",
             6666667, "20000000/3", ["20 000 000 / 3 ≈ 6 666 667"], unit="głosów", tol=1),
          LB("Inwestor ma 950 000 akcji w spółce z 10 mln akcji. Jaki ma udział (%)?",
             9.5, "950000/10000000*100", ["950 000 / 10 000 000 = 9,5%"], unit="%", tol=0.01),
          LB("Ile akcji musi dokupić, by osiągnąć próg 10%?",
             50000, "1000000-950000", ["10% = 1 000 000", "1 000 000 − 950 000 = 50 000"], unit="akcji"),
          LB("Patent na wzór użytkowy (10 lat) zgłoszony w 2022 r. – do którego roku?",
             2032, "2022+10", ["2022 + 10 = 2032"], unit=""),
          LB("Wzór przemysłowy chroni się w okresach 5-letnich do 25 lat. Ile odnowień po pierwszym okresie jest możliwych?",
             4, "25/5-1", ["25 / 5 = 5 okresów", "5 − 1 = 4 odnowienia"], unit="odnowień"),
          LB("Twórca zmarł w 1980 r. Do końca którego roku trwają autorskie prawa majątkowe?",
             2050, "1980+70", ["1980 + 70 = 2050"], unit=""),
      ],
      case=[
          PR("Fundusz inwestycyjny skupuje na giełdzie akcje spółki „Beta” (10 mln głosów). W poniedziałek ma 480 000 akcji, we wtorek 520 000, w piątek 1 050 000.",
             W("Kiedy fundusz przekroczył pierwszy próg?",
               "We wtorek – 5,2% > 5%", "W poniedziałek", "W piątek",
               why="480 000 to 4,8%, 520 000 to 5,2%."),
             W("Który próg przekroczył w piątek?",
               "10% (10,5%)", "15%", "5%",
               why="1 050 000 / 10 000 000 = 10,5%."),
             PF("Za każdym razem musi zawiadomić KNF i spółkę.", True,
                why="Obowiązek dotyczy każdego przekroczenia progu."),
          ),
          PR("Agencja reklamowa zamówiła u freelancera logo na umowę o dzieło, ale umowa nie mówi nic o przeniesieniu praw autorskich. Klient agencji chce zarejestrować logo jako znak towarowy.",
             W("Kto ma autorskie prawa majątkowe do logo?",
               "Freelancer – brak umownego przeniesienia praw", "Agencja automatycznie", "Urząd Patentowy",
               why="Przy umowie o dzieło prawa trzeba przenieść na piśmie."),
             W("Co powinna zrobić agencja?",
               "Zawrzeć umowę przeniesienia praw na określonych polach eksploatacji", "Nic", "Zarejestrować logo bez zgody autora",
               why="Przeniesienie praw majątkowych wymaga formy pisemnej."),
             PF("Rejestracja znaku towarowego nie zastępuje nabycia praw autorskich do grafiki.", True,
                why="To odrębne reżimy prawne."),
          ),
      ]),

    L(3, "Kapitał spółek, rachunkowość, upadłość i restrukturyzacja",
      "Znać minimalny kapitał zakładowy spółek, zakres ustawy o rachunkowości oraz podstawowe zasady Prawa upadłościowego i restrukturyzacyjnego.",
      ["Limity kapitału zakładowego spółek", "Ustawa o rachunkowości (1994)", "Prawo upadłościowe (2003) i restrukturyzacyjne (2015)"],
      [KSH, UOR, PUPAD, PRESTR],
      explain=[
          K("Minimalny kapitał zakładowy",
            "Spółka z o.o. – 5 000 zł (udział co najmniej 50 zł). Spółka akcyjna – 100 000 zł. Spółka komandytowo-akcyjna – 50 000 zł. Prosta spółka akcyjna – kapitał akcyjny od 1 zł, akcje bez wartości nominalnej. Niski kapitał minimalny nie chroni wierzycieli, dlatego ważne są inne mechanizmy (odpowiedzialność zarządu, obowiązki informacyjne)."),
          K("Ustawa o rachunkowości (1994)",
            "Określa, kto prowadzi księgi rachunkowe (spółki kapitałowe, osobowe w określonych przypadkach, osoby fizyczne z przychodami ponad równowartość 2 mln euro), zasady rachunkowości, wycenę aktywów i pasywów, sporządzanie, badanie i ogłaszanie sprawozdań finansowych (do KRS)."),
          W("Jaki jest minimalny kapitał zakładowy spółki z o.o.?",
            "5 000 zł", "100 000 zł", "1 zł",
            why="Tak stanowi KSH."),
          K("Prawo upadłościowe (2003)",
            "Określa, kiedy dłużnik jest niewypłacalny (utrata zdolności do wykonywania wymagalnych zobowiązań – domniemanie po 3 miesiącach opóźnienia), obowiązek złożenia wniosku w ciągu 30 dni, rolę syndyka, kolejność zaspokajania wierzycieli. Przewiduje też upadłość konsumencką osób fizycznych nieprowadzących działalności."),
          K("Prawo restrukturyzacyjne (2015, w życie 2016)",
            "Wprowadziło cztery postępowania: o zatwierdzenie układu, przyspieszone postępowanie układowe, postępowanie układowe i sanacyjne. Cel: uniknięcie upadłości przez układ z wierzycielami. Restrukturyzacja ma pierwszeństwo, gdy daje wierzycielom więcej niż upadłość."),
          PF("Prosta spółka akcyjna może mieć kapitał akcyjny 1 zł.", True,
             why="PSA wprowadzono w 2021 r. z kapitałem od 1 zł."),
      ],
      mech=[
          KT("Minimalny kapitał",
             {"1 zł": ["Prosta spółka akcyjna"],
              "5 000 zł": ["Spółka z o.o."],
              "50 000 zł": ["Spółka komandytowo-akcyjna"],
              "100 000 zł": ["Spółka akcyjna"]},
             why="Progi wynikają z KSH."),
          LN("Ułóż kroki postępowania upadłościowego.",
             ["Dłużnik staje się niewypłacalny", "Zarząd składa wniosek o upadłość w ciągu 30 dni", "Sąd ogłasza upadłość i wyznacza syndyka", "Syndyk sporządza spis inwentarza i sprzedaje majątek", "Wierzyciele są zaspokajani według kategorii"],
             why="Upadłość służy zaspokojeniu wierzycieli."),
          W("Spółka ma 1 000 udziałów w spółce z o.o. o kapitale 5 000 zł. Czy to dopuszczalne?",
            "Nie – udział musi mieć co najmniej 50 zł (wyszłoby 5 zł)", "Tak", "Tak, jeśli są równe",
            why="5 000 / 1 000 = 5 zł < 50 zł."),
          W("Kiedy osoba fizyczna prowadząca firmę musi przejść na księgi rachunkowe?",
            "Gdy przychody przekroczą równowartość 2 mln euro", "Zawsze", "Nigdy",
            why="Taki próg określa ustawa o rachunkowości."),
          M("Jakie postępowania przewiduje Prawo restrukturyzacyjne?",
            ["Postępowanie o zatwierdzenie układu", "Przyspieszone postępowanie układowe", "Postępowanie sanacyjne", "Postępowanie egzekucyjne z nieruchomości"], [0, 1, 2],
            why="Egzekucję reguluje Kodeks postępowania cywilnego."),
          PF("Upadłość konsumencka dotyczy osób fizycznych nieprowadzących działalności gospodarczej.", True,
             why="Pozwala oddłużyć się osobom prywatnym."),
      ],
      calc=[
          LB("Spółka z o.o. ma kapitał 5 000 zł i udziały po 50 zł. Ile jest udziałów (maksymalnie)?",
             100, "5000/50", ["5 000 / 50 = 100"], unit="udziałów"),
          LB("S.A. ma kapitał 100 000 zł i 10 mln akcji. Ile wynosi wartość nominalna akcji (zł)?",
             0.01, "100000/10000000", ["100 000 / 10 000 000 = 0,01 zł – minimum 1 gr"], unit="zł", tol=0.001),
          LB("Ile razy wyższy jest minimalny kapitał S.K.A. od kapitału sp. z o.o.?",
             10, "50000/5000", ["50 000 / 5 000 = 10"], unit="razy"),
          LB("Opóźnienie w zapłacie zaczęło się 10 stycznia. Po ilu miesiącach powstaje domniemanie niewypłacalności?",
             3, "3", ["Domniemanie: opóźnienie ponad 3 miesiące"], unit="mies."),
          LB("Limit pełnej księgowości 2 mln euro, kurs 4,26 zł. Ile to złotych (mln zł)?",
             8.52, "2*4.26", ["2 · 4,26 = 8,52 mln zł"], unit="mln zł", tol=0.01),
          LB("Prawo restrukturyzacyjne uchwalono w 2015 r., a weszło w życie w 2016 r. Ile postępowań restrukturyzacyjnych przewiduje?",
             4, "4", ["Zatwierdzenie układu, przyspieszone układowe, układowe, sanacyjne"], unit=""),
      ],
      case=[
          PR("Dwóch wspólników zakłada spółkę z o.o. z kapitałem 5 000 zł. Po roku spółka ma 300 000 zł długów i 40 000 zł majątku; od 4 miesięcy nie płaci faktur.",
             W("Czy minimalny kapitał chroni wierzycieli w takiej sytuacji?",
               "Praktycznie nie – 5 000 zł to bardzo mało wobec długów", "Tak, w pełni", "Kapitał zakładowy gwarantuje spłatę całości",
               why="Niski kapitał minimalny nie stanowi realnego zabezpieczenia."),
             W("Co grozi członkom zarządu, jeśli nie złożą wniosku o upadłość w terminie?",
               "Osobista odpowiedzialność za długi spółki (art. 299 KSH)", "Nic", "Wyłącznie upomnienie",
               why="Zarząd odpowiada, gdy egzekucja z majątku spółki jest bezskuteczna."),
             PF("Spółka jest niewypłacalna w rozumieniu Prawa upadłościowego.", True,
                why="Opóźnienie przekracza 3 miesiące."),
          ),
          PR("Sprawozdanie finansowe spółki z o.o. za 2025 r. trzeba sporządzić, zatwierdzić i złożyć do KRS.",
             W("Do kiedy (licząc od dnia bilansowego 31.12) trzeba je sporządzić według ustawy o rachunkowości?",
               "Do 3 miesięcy – do 31 marca", "Do 30 dni", "Do 12 miesięcy",
               why="Ustawa przewiduje 3 miesiące na sporządzenie."),
             W("Do kiedy trzeba je zatwierdzić?",
               "Do 6 miesięcy – do 30 czerwca", "Do 31 stycznia", "Do 31 grudnia",
               why="Zatwierdza je zgromadzenie wspólników w ciągu 6 miesięcy."),
             PF("Zatwierdzone sprawozdanie składa się do Repozytorium Dokumentów Finansowych (KRS).", True,
                why="Służy to jawności informacji o spółkach."),
          ),
      ]),

    L(4, "Podatki firmy: CIT, terminy i KSeF",
      "Znać stawki CIT (19%, 9%, estoński CIT), podstawowe terminy rozliczeń podatkowych i składkowych oraz harmonogram obowiązkowego KSeF w 2026 r.",
      ["Stawki CIT", "Terminy podatkowe i zeznania", "Krajowy System e-Faktur (KSeF)"],
      [CIT, PIT, KSEF],
      explain=[
          K("Stawki CIT",
            "Podstawowa stawka CIT wynosi 19%. Mali podatnicy (przychody do równowartości 2 mln euro) i rozpoczynający działalność płacą 9% od dochodów innych niż z zysków kapitałowych. Od 2021 r. spółki mogą wybrać estoński CIT (ryczałt od dochodów spółek): podatek płaci się dopiero przy wypłacie zysku, a zysk reinwestowany nie jest opodatkowany."),
          K("Terminy",
            "Zaliczki na PIT i CIT – do 20. dnia następnego miesiąca. Składki ZUS – do 20. dnia następnego miesiąca (jednostki budżetowe do 5.). JPK_VAT z deklaracją – do 25. dnia następnego miesiąca. Zeznanie roczne PIT – do 30 kwietnia. Zeznanie CIT-8 – do końca 3. miesiąca następnego roku (zwykle 31 marca)."),
          W("Do kiedy składa się JPK_VAT z deklaracją za październik?",
            "Do 25 listopada", "Do 20 listopada", "Do 30 kwietnia",
            why="Termin to 25. dzień następnego miesiąca."),
          K("KSeF 2026",
            "Krajowy System e-Faktur: od 1.02.2026 r. obowiązkowy dla podatników ze sprzedażą powyżej 200 mln zł brutto w 2024 r., od 1.04.2026 r. dla pozostałych; najmniejsi (drobne transakcje) – od 1.01.2027 r. Do końca 2026 r. obowiązuje okres przejściowy bez kar za błędy. Faktura ma numer KSeF i jest dostępna dla nabywcy w systemie."),
          K("Estoński CIT – logika",
            "Firma, która reinwestuje zyski, odracza podatek – to zachęta do inwestycji. Przy wypłacie łączne obciążenie (CIT + PIT od dywidendy, z odliczeniem części CIT) jest zbliżone do zwykłego modelu, ale odroczenie ma wartość w czasie. Warunki: m.in. wspólnicy – wyłącznie osoby fizyczne, odpowiednie zatrudnienie."),
          PF("Spółka na estońskim CIT nie płaci podatku od zysku, dopóki go nie wypłaci.", True,
             why="Opodatkowanie następuje przy dystrybucji zysku."),
      ],
      mech=[
          KT("Jaki termin?",
             {"20. dnia następnego miesiąca": ["Zaliczka na CIT", "Składki ZUS przedsiębiorcy"],
              "25. dnia następnego miesiąca": ["JPK_VAT z deklaracją"],
              "30 kwietnia": ["Roczne zeznanie PIT-36"],
              "Koniec 3. miesiąca następnego roku": ["Zeznanie CIT-8 (rok kalendarzowy)"]},
             why="Terminy różnią się w zależności od podatku."),
          LN("Ułóż harmonogram wdrożenia KSeF.",
             ["Udostępnienie KSeF 2.0 i testy dla firm", "1.02.2026 – obowiązek dla największych podatników", "1.04.2026 – obowiązek dla pozostałych", "Do końca 2026 r. – okres przejściowy bez kar", "1.01.2027 – obowiązek dla najmniejszych"],
             why="Wdrożenie rozłożono w czasie według wielkości firm."),
          W("Spółka z przychodami 6 mln zł spełnia warunki małego podatnika. Jaka stawka CIT od dochodu operacyjnego?",
            "9%", "19%", "32%",
            why="Mały podatnik – przychody do równowartości 2 mln euro."),
          W("Dlaczego estoński CIT zachęca do inwestycji?",
            "Zysk reinwestowany nie jest opodatkowany do czasu wypłaty", "Bo stawka CIT wynosi 0% na zawsze", "Bo znosi VAT",
            why="Odroczenie podatku zwiększa środki na rozwój."),
          M("Kogo dotyczył obowiązek KSeF od 1.02.2026 r.?",
            ["Podatników ze sprzedażą powyżej 200 mln zł w 2024 r.", "Największych firm w Polsce", "Firm, które już wtedy musiały wystawiać e-faktury w KSeF", "Wszystkich konsumentów"], [0, 1, 2],
            why="Konsumenci nie wystawiają faktur w KSeF."),
          PF("Zeznanie roczne PIT za 2025 r. trzeba było złożyć do 30 kwietnia 2026 r.", True,
             why="Termin na PIT roczny to 30 kwietnia."),
      ],
      calc=[
          LB("Dochód spółki 800 000 zł, CIT 19%. Ile wynosi podatek (zł)?",
             152000, "800000*0.19", ["800 000 · 19% = 152 000 zł"], unit="zł"),
          LB("Ten sam dochód przy 9% CIT. Ile spółka oszczędza (zł)?",
             80000, "800000*(0.19-0.09)", ["800 000 · 10 pkt proc. = 80 000 zł"], unit="zł"),
          LB("Zaliczka za marzec – do którego dnia kwietnia trzeba ją wpłacić?",
             20, "20", ["Do 20. dnia następnego miesiąca"], unit="kwietnia"),
          LB("Spółka reinwestuje 500 000 zł zysku przez 3 lata, odraczając podatek 10% (dane umowne). Ile podatku odroczyła (zł)?",
             50000, "500000*0.1", ["500 000 · 10% = 50 000 zł"], unit="zł"),
          LB("Wartość odroczenia: 50 000 zł zapłacone za 3 lata zamiast dziś, stopa 8%. Ile wynosi PV tej płatności (zł)?",
             39691.61, "50000/1.08**3", ["50 000 / 1,08³ ≈ 39 691,61 zł"], unit="zł", tol=0.01),
          LB("Firma wystawia 1 200 faktur miesięcznie. Ile faktur rocznie trafi do KSeF?",
             14400, "1200*12", ["1 200 · 12 = 14 400"], unit="faktur"),
      ],
      case=[
          PR("Spółka z o.o. (przychody 7 mln zł, dochód 1 mln zł) rozważa przejście na estoński CIT, bo planuje przez 4 lata reinwestować cały zysk w nową linię produkcyjną.",
             W("Ile wyniósłby zwykły CIT przy stawce 9% od dochodu 1 mln zł?",
               "90 000 zł", "190 000 zł", "9 000 zł",
               why="1 000 000 · 9% = 90 000 zł."),
             W("Ile podatku zapłaci w estońskim CIT w latach reinwestowania?",
               "0 zł – podatek płaci się przy wypłacie zysku", "90 000 zł rocznie", "190 000 zł rocznie",
               why="Zysk zatrzymany nie jest opodatkowany."),
             PF("Korzyść z estońskiego CIT rośnie, gdy firma długo reinwestuje zyski.", True,
                why="Odroczenie podatku ma wartość w czasie."),
          ),
          PR("Księgowa planuje kalendarz na listopad 2026 r. dla spółki: zaliczka CIT za październik, składki ZUS za październik, JPK_VAT za październik.",
             W("Które płatności przypadają do 20 listopada?",
               "Zaliczka CIT i składki ZUS", "Tylko JPK_VAT", "Zeznanie roczne",
               why="Oba terminy to 20. dzień następnego miesiąca."),
             W("Do kiedy trzeba złożyć JPK_VAT?",
               "Do 25 listopada", "Do 20 listopada", "Do 31 grudnia",
               why="JPK_VAT – 25. dzień następnego miesiąca."),
             PF("Od kwietnia 2026 r. spółka (jeśli nie jest najmniejszym podatnikiem) wystawia faktury w KSeF.", True,
                why="Obowiązek dla pozostałych podatników od 1.04.2026."),
          ),
      ]),

    L(5, "Praca i dane w przepisach: wypowiedzenia, urlopy, czas pracy, RODO",
      "Liczyć okresy wypowiedzenia i wymiar urlopu, znać normy czasu pracy i limit nadgodzin oraz rozumieć podstawowe obowiązki firmy wynikające z RODO.",
      ["Okresy wypowiedzenia umowy o pracę", "Urlop wypoczynkowy i czas pracy", "Rozporządzenie RODO"],
      [KP, KSH],
      explain=[
          K("Okresy wypowiedzenia",
            "Umowa na czas nieokreślony i określony: 2 tygodnie przy zatrudnieniu u danego pracodawcy krótszym niż 6 miesięcy, 1 miesiąc od 6 miesięcy, 3 miesiące od 3 lat. Umowa na okres próbny: 3 dni roboczych (okres próbny do 2 tygodni), 1 tydzień (ponad 2 tygodnie), 2 tygodnie (3 miesiące). Okres miesięczny i dłuższy kończy się z ostatnim dniem miesiąca."),
          K("Urlop i czas pracy",
            "Urlop wypoczynkowy: 20 dni przy stażu pracy poniżej 10 lat, 26 dni od 10 lat (do stażu wlicza się m.in. okres nauki – np. ukończenie studiów to 8 lat). Czas pracy: do 8 godzin na dobę i przeciętnie 40 godzin w tygodniu w okresie rozliczeniowym. Limit nadgodzin – 150 godzin w roku kalendarzowym (chyba że regulamin stanowi inaczej); nadgodziny wynagradza się dodatkiem 50% lub 100%."),
          W("Absolwent studiów wyższych (8 lat wliczanych do stażu) pracuje od 2 lat. Ile dni urlopu mu przysługuje?",
            "26 dni", "20 dni", "30 dni",
            why="8 + 2 = 10 lat stażu urlopowego."),
          K("RODO w firmie",
            "Firma jako administrator danych musi mieć podstawę prawną przetwarzania (umowa, obowiązek prawny, zgoda, uzasadniony interes), informować osoby o przetwarzaniu, zbierać tylko niezbędne dane, zabezpieczać je, zgłaszać naruszenia organowi (w Polsce – Prezesowi UODO) w ciągu 72 godzin. Osobom przysługuje prawo dostępu, sprostowania, usunięcia, sprzeciwu."),
          K("Kary",
            "Naruszenia RODO mogą skutkować karami do 20 mln euro lub do 4% światowego rocznego obrotu (wyższa kwota). Naruszenie przepisów prawa pracy może prowadzić do grzywny nakładanej przez Państwową Inspekcję Pracy oraz roszczeń pracowników."),
          PF("Naruszenie ochrony danych trzeba zgłosić do UODO w ciągu 72 godzin od jego stwierdzenia (jeśli powoduje ryzyko).", True,
             why="Tak stanowi art. 33 RODO."),
      ],
      mech=[
          KT("Ile wynosi okres wypowiedzenia?",
             {"2 tygodnie": ["Staż 4 miesiące, umowa na czas określony", "Okres próbny 3 miesiące"],
              "1 miesiąc": ["Staż 2 lata, umowa na czas nieokreślony"],
              "3 miesiące": ["Staż 5 lat u tego pracodawcy", "Staż 3 lata i 1 miesiąc"]},
             why="Okres zależy od stażu u danego pracodawcy i rodzaju umowy."),
          LN("Ułóż reakcję firmy na wyciek danych klientów.",
             ["Firma wykrywa włamanie do bazy danych", "Ocenia ryzyko dla osób, których dane dotyczą", "Zgłasza naruszenie Prezesowi UODO w ciągu 72 godzin", "Przy wysokim ryzyku zawiadamia też klientów", "Usuwa przyczynę i dokumentuje zdarzenie"],
             why="RODO nakłada obowiązki zgłoszenia i dokumentacji."),
          W("Pracownik przepracował w tym roku 140 nadgodzin. Ile jeszcze może przepracować w ramach rocznego limitu?",
            "10 godzin", "150 godzin", "40 godzin",
            why="Limit 150 h – 140 h = 10 h."),
          W("Na jakiej podstawie firma przetwarza dane pracownika do wypłaty pensji?",
            "Wykonania umowy i obowiązku prawnego", "Wyłącznie zgody pracownika", "Bez podstawy prawnej",
            why="Zgoda nie jest tu potrzebna – podstawą jest umowa i prawo pracy."),
          M("Jakie prawa daje RODO osobom, których dane dotyczą?",
            ["Prawo dostępu do danych", "Prawo do sprostowania", "Prawo do usunięcia w określonych przypadkach", "Prawo do sprzedaży danych innych osób"], [0, 1, 2],
            why="RODO chroni dane, nie daje prawa do handlu cudzymi danymi."),
          PF("Okres wypowiedzenia liczony w miesiącach kończy się z ostatnim dniem miesiąca.", True,
             why="Tak stanowi Kodeks pracy."),
      ],
      calc=[
          LB("Pracownik pracuje od 4 lat; wypowiedzenie złożono 10 marca. Ile miesięcy wynosi okres wypowiedzenia?",
             3, "3", ["Staż ≥ 3 lata → 3 miesiące, liczone do końca czerwca"], unit="mies."),
          LB("Stawka godzinowa 40 zł, 10 nadgodzin z dodatkiem 50%. Ile wynosi wynagrodzenie za nadgodziny (zł)?",
             600, "10*40*1.5", ["10 · 40 · 1,5 = 600 zł"], unit="zł"),
          LB("Ten sam pracownik – 6 nadgodzin w nocy z dodatkiem 100%. Ile wynosi (zł)?",
             480, "6*40*2", ["6 · 40 · 2 = 480 zł"], unit="zł"),
          LB("Pracownik ze stażem 12 lat zaczyna pracę u nowego pracodawcy 1 lipca. Ile dni urlopu przysługuje mu za ten rok (proporcjonalnie, 26 dni rocznie)?",
             13, "26*6/12", ["26 · 6/12 = 13 dni"], unit="dni"),
          LB("Firma ma obrót 1 mld euro. Ile wynosi maksymalna kara RODO (4% obrotu, mln euro)?",
             40, "1000*0.04", ["1 000 · 4% = 40 mln euro"], unit="mln euro"),
          LB("Ile godzin wynosi norma czasu pracy w 4-tygodniowym okresie rozliczeniowym (przeciętnie 40 h tygodniowo)?",
             160, "40*4", ["40 · 4 = 160 h"], unit="h"),
      ],
      case=[
          PR("Pani Agata pracuje w firmie od 2 lat i 7 miesięcy na umowę na czas nieokreślony. Ukończyła studia magisterskie. Pracodawca wypowiada jej umowę 5 maja.",
             W("Ile wynosi okres wypowiedzenia?",
               "1 miesiąc – do 30 czerwca", "3 miesiące", "2 tygodnie",
               why="Staż u pracodawcy ≥ 6 miesięcy i < 3 lata; okres kończy się z końcem czerwca."),
             W("Ile dni urlopu przysługuje jej rocznie?",
               "26 – studia wliczają się jako 8 lat", "20", "30",
               why="8 lat (studia) + ponad 2 lata pracy ≥ 10 lat."),
             PF("Okres wypowiedzenia zależy od stażu u danego pracodawcy, a wymiar urlopu – od ogólnego stażu pracy z nauką.", True,
                why="Te dwa staże liczy się inaczej."),
          ),
          PR("Sklep internetowy zgubił pendrive z niezaszyfrowaną bazą 50 000 klientów (imiona, adresy, telefony). Kierownik chce „przemilczeć sprawę”.",
             W("Co powinien zrobić sklep?",
               "Zgłosić naruszenie Prezesowi UODO w ciągu 72 godzin i ocenić potrzebę zawiadomienia klientów", "Nic", "Tylko usunąć pliki z komputera",
               why="RODO nakłada obowiązek zgłoszenia naruszeń."),
             W("Jaki błąd organizacyjny ułatwił naruszenie?",
               "Brak szyfrowania nośnika z danymi", "Zbyt mała liczba klientów", "Brak KSeF",
               why="Szyfrowanie to podstawowe zabezpieczenie danych."),
             PF("Przemilczenie naruszenia może zwiększyć karę nałożoną przez UODO.", True,
                why="Organ ocenia też współpracę i reakcję administratora."),
          ),
      ]),
]
