# -*- coding: utf-8 -*-
# Zrozumienie – Finanse przedsiębiorstw / Analiza finansowa i wskaźniki
OSF = "https://openstax.org/books/principles-financial-accounting/pages/"
OSM = "https://openstax.org/books/principles-managerial-accounting/pages/"
D = "2026-10-08"
F53 = S("OpenStax, Principles of Accounting Vol. 1, 5.3 Current Ratio and Working Capital", OSF + "5-3-apply-the-results-from-the-adjusted-trial-balance-to-compute-current-ratio-and-working-capital-balance-and-explain-how-these-measures-represent-liquidity", D)
F93 = S("OpenStax, Principles of Accounting Vol. 1, 9.3 Efficiency of Receivables Management", OSF + "9-3-determine-the-efficiency-of-receivables-management-using-financial-ratios", D)
F105 = S("OpenStax, Principles of Accounting Vol. 1, 10.5 Efficiency of Inventory Management", OSF + "10-5-examine-the-efficiency-of-inventory-management-using-financial-ratios", D)
F165 = S("OpenStax, Principles of Accounting Vol. 1, 16.5 Ratios to Assess Liquidity and Solvency", OSF + "16-5-use-information-from-the-statement-of-cash-flows-to-prepare-ratios-to-assess-liquidity-and-solvency", D)
M35 = S("OpenStax, Principles of Accounting Vol. 2, 3.5 Margin of Safety and Operating Leverage", OSM + "3-5-calculate-and-interpret-a-companys-margin-of-safety-and-operating-leverage", D)
M123 = S("OpenStax, Principles of Accounting Vol. 2, 12.3 ROI, Residual Income and EVA", OSM + "12-3-evaluate-an-operating-segment-or-a-project-using-return-on-investment-residual-income-and-economic-value-added", D)

GDP = S("Wikipedia – DuPont analysis", "https://en.wikipedia.org/wiki/DuPont_analysis", D)
GHAG = S("Hagley Museum and Library – The Father of ROI: Donaldson Brown", "https://www.hagley.org/librarynews/father-roi-donaldson-brown", D)
GWYP = S("M. Wypych, Analiza czynnikowa rentowności (Dolnośląska Biblioteka Cyfrowa)", "https://www.dbc.wroc.pl//Content/120363/Wypych_Analiza_czynnikowa_rentownosci.pdf", D)
GNOW = S("J. Nowicki, Rentowność czy wydajność gotówkowa (Wydawnictwo UE w Poznaniu)", "https://wydawnictwo.ue.poznan.pl/books/978-83-8211-194-1/chapters/06.%20J.%20Nowicki%2C%20Rentowno%C5%9B%C4%87%20czy%20wydajno%C5%9B%C4%87%20got%C3%B3wkowa%2C%20s.%20102-117.pdf", D)
GTIE = S("Wikipedia – Times interest earned", "https://en.wikipedia.org/wiki/Times_interest_earned", D)
GGUS = S("GUS – Wyniki finansowe przedsiębiorstw niefinansowych (wskaźnik poziomu kosztów)", "https://stat.gov.pl/obszary-tematyczne/podmioty-gospodarcze-wyniki-finansowe/przedsiebiorstwa-niefinansowe/wyniki-finansowe-przedsiebiorstw-niefinansowych-w-2014-roku,12,18.html", D)
GKUJ = S("Kujawski, Koncepcja rachunku marż (Dolnośląska Biblioteka Cyfrowa)", "https://www.dbc.wroc.pl//Content/121292/Kujawski_Koncepcja_rachunku_marz.pdf", D)
GLIT = S("PTE – Literatura XXXIX OWE (W. Gabrusewicz, Metody analizy finansowej przedsiębiorstw, PWE 2019)", "https://pte.lodz.pl/wp-content/uploads/2025/09/Literatura-XXXIX.pdf", D)

LESSONS = [
    L(1, "Wstępna analiza sprawozdań: pozioma i pionowa",
      "Przeprowadzać analizę dynamiki (poziomą) i struktury (pionową) bilansu i RZiS, interpretować zmiany i wiedzieć, jakie pytania zadawać przed liczeniem wskaźników.",
      ["Analiza pozioma i pionowa (wstępna analiza sprawozdań)", "Analiza wskaźnikowa"],
      [F53, F165],
      explain=[
          K("Analiza pozioma",
            "Porównuje pozycje sprawozdań w czasie: zmiana bezwzględna (w złotych) i względna (dynamika w %). Np. przychody wzrosły z 10 do 12 mln zł, czyli o 20%. Pozwala wychwycić trendy: szybki wzrost należności, spadek marży, rosnące zadłużenie.",
            w="dynamika = (wartość bieżąca / wartość bazowa − 1) · 100%"),
          K("Analiza pionowa",
            "Pokazuje strukturę: udział każdej pozycji w sumie bilansowej lub w przychodach. Np. zapasy to 25% aktywów, koszty wynagrodzeń 30% przychodów. Ułatwia porównanie firm różnej wielkości i ocenę, czy struktura pasuje do branży."),
          W("Należności wzrosły z 2 do 3 mln zł. Ile wynosi dynamika?",
            "+50%", "+33%", "+150%",
            why="3 / 2 − 1 = 50%."),
          K("Analiza wskaźnikowa",
            "Wskaźniki łączą pozycje sprawozdań w relacje: płynności, rentowności, zadłużenia i sprawności. Same w sobie mówią niewiele – porównuje się je w czasie, z konkurencją, ze średnią branżową i z normami (np. wymaganymi przez bank w umowie kredytowej – kowenanty)."),
          K("Typowe sygnały ostrzegawcze",
            "Należności rosną szybciej niż przychody (klienci płacą coraz później), zapasy rosną szybciej niż sprzedaż (towar zalega), zysk rośnie, a przepływy operacyjne spadają (jakość zysku), rośnie udział krótkoterminowego długu."),
          PF("Wskaźnik finansowy najlepiej oceniać na tle branży i jego zmian w czasie.", True,
             why="Ta sama wartość może być dobra w handlu, a zła w przemyśle."),
      ],
      mech=[
          KT("Analiza pozioma czy pionowa?",
             {"Pozioma (dynamika)": ["Przychody wzrosły o 12% r/r", "Zapasy spadły o 300 tys. zł w ciągu roku"],
              "Pionowa (struktura)": ["Kapitał własny to 45% pasywów", "Koszty materiałów stanowią 60% przychodów"]},
             why="Pozioma – zmiany w czasie, pionowa – udziały w całości."),
          LN("Ułóż kolejność analizy finansowej firmy.",
             ["Zbierz sprawozdania za kilka lat", "Przeprowadź analizę poziomą i pionową", "Policz wskaźniki płynności, rentowności, zadłużenia i sprawności", "Porównaj z branżą i latami ubiegłymi", "Sformułuj wnioski i rekomendacje"],
             why="Od ogółu do szczegółu."),
          W("Przychody wzrosły o 5%, a należności o 40%. Co to może oznaczać?",
            "Klienci płacą coraz później – pogarsza się ściągalność", "Firma ma coraz więcej gotówki", "Firma spłaca długi szybciej",
            why="Należności rosną znacznie szybciej niż sprzedaż."),
          W("Zysk netto rośnie, ale przepływy operacyjne spadają trzeci rok. Co sygnalizuje?",
            "Niską jakość zysku – zysk nie zamienia się w gotówkę", "Bardzo dobrą sytuację", "Nic istotnego",
            why="Rozjazd zysku i gotówki to sygnał ostrzegawczy."),
          M("Z czym porównuje się wskaźniki finansowe?",
            ["Z wartościami z poprzednich lat", "Ze średnią branżową", "Z konkurentami", "Z kursem walut z dnia analizy"], [0, 1, 2],
            why="Kurs walut nie jest punktem odniesienia dla wskaźnika."),
          PF("Analiza pionowa ułatwia porównanie małej i dużej firmy z tej samej branży.", True,
             why="Struktura w procentach usuwa efekt skali."),
      ],
      calc=[
          LB("Przychody: 2025 r. 8,0 mln zł, 2026 r. 9,2 mln zł. Ile wynosi dynamika (%)?",
             15, "(9.2/8-1)*100", ["9,2 / 8 − 1 = 15%"], unit="%"),
          LB("Zapasy 1,5 mln zł, suma aktywów 6 mln zł. Ile wynosi ich udział (%)?",
             25, "1.5/6*100", ["1,5 / 6 = 25%"], unit="%"),
          LB("Koszt materiałów 5,4 mln zł przy przychodach 9 mln zł. Ile wynosi udział w przychodach (%)?",
             60, "5.4/9*100", ["5,4 / 9 = 60%"], unit="%"),
          LB("Zysk netto spadł z 1,2 mln zł do 0,9 mln zł. Ile wynosi dynamika (%)? (spadek ze znakiem minus)",
             -25, "(0.9/1.2-1)*100", ["0,9 / 1,2 − 1 = −25%"], unit="%"),
          LB("Należności: 1,0 → 1,4 mln zł, przychody: 10 → 10,5 mln zł. O ile pkt proc. dynamika należności przewyższa dynamikę przychodów?",
             35, "(1.4/1-1)*100-(10.5/10-1)*100", ["40% − 5% = 35 pkt proc."], unit="pkt proc."),
          LB("Kapitał własny 2,7 mln zł, pasywa 6 mln zł. Ile wynosi udział kapitału własnego (%)?",
             45, "2.7/6*100", ["2,7 / 6 = 45%"], unit="%"),
      ],
      case=[
          PR("Spółka handlowa (mln zł): przychody 2024 – 20, 2025 – 22, 2026 – 23; zapasy 2024 – 3, 2025 – 4,5, 2026 – 6,5; gotówka 2024 – 2, 2025 – 1,2, 2026 – 0,4.",
             W("Jaka jest dynamika zapasów 2024–2026?",
               "Ok. +117%", "Ok. +15%", "Ok. +50%",
               why="6,5 / 3 − 1 ≈ 116,7%."),
             W("Co sugeruje porównanie zapasów i przychodów?",
               "Towar zalega w magazynie – zapasy rosną znacznie szybciej niż sprzedaż", "Firma bardzo sprawnie zarządza zapasami", "Sprzedaż rośnie szybciej niż zapasy",
               why="Przychody +15%, zapasy +117%."),
             PF("Spadek gotówki może wynikać z zamrożenia jej w zapasach.", True,
                why="Gotówka wydana na zakup towarów, które się nie sprzedają."),
          ),
          PR("Dwie firmy z branży IT: A ma przychody 500 mln zł, B – 20 mln zł. W A koszty wynagrodzeń to 55% przychodów, w B – 70%.",
             W("Jaka analiza pozwala porównać te firmy mimo różnej wielkości?",
               "Pionowa (struktura)", "Wyłącznie pozioma", "Porównanie wartości bezwzględnych",
               why="Udziały w przychodach usuwają efekt skali."),
             W("Co może oznaczać wyższy udział płac w B?",
               "Niższą efektywność lub mniejszą skalę i brak efektu skali", "Wyższą rentowność", "Brak pracowników",
               why="Przy podobnych cenach większy udział płac obniża marżę."),
             PF("Interpretacja struktury kosztów wymaga znajomości modelu biznesowego firmy.", True,
                why="Np. software house ma naturalnie wysoki udział płac."),
          ),
      ]),

    L(2, "Płynność finansowa",
      "Liczyć i interpretować wskaźniki płynności bieżącej, szybkiej i gotówkowej, rozumieć, dlaczego zarówno za niska, jak i za wysoka płynność jest problemem.",
      ["Wskaźniki płynności", "Analiza wskaźnikowa"],
      [F53, F165],
      explain=[
          K("Trzy wskaźniki płynności",
            "Płynność bieżąca = aktywa obrotowe / zobowiązania krótkoterminowe (często zalecane ok. 1,2–2,0). Płynność szybka = (aktywa obrotowe − zapasy) / zobowiązania krótkoterminowe (ok. 1,0) – pomija zapasy, które trudniej szybko spieniężyć. Płynność gotówkowa = środki pieniężne / zobowiązania krótkoterminowe.",
            w="bieżąca = AO / ZK;  szybka = (AO − zapasy) / ZK;  gotówkowa = gotówka / ZK"),
          K("Za mało i za dużo",
            "Zbyt niska płynność grozi utratą zdolności do regulowania zobowiązań. Zbyt wysoka oznacza, że firma trzyma nadmiar gotówki, zapasów lub należności – zamrożony kapitał, który mógłby zarabiać. Optymalny poziom zależy od branży (np. handel detaliczny często ma niską płynność bieżącą i jest to normalne)."),
          W("Aktywa obrotowe 900, zapasy 400, zobowiązania krótkoterminowe 500 (tys. zł). Ile wynosi płynność szybka?",
            "1,0", "1,8", "0,8",
            why="(900 − 400) / 500 = 1,0."),
          K("Płynność a wypłacalność",
            "Płynność dotyczy krótkiego okresu – czy firma zapłaci bieżące rachunki. Wypłacalność (solidność) – czy majątek wystarcza na pokrycie wszystkich długów w długim okresie. Firma może być wypłacalna (dużo majątku), ale niepłynna (brak gotówki teraz)."),
          K("Jak poprawić płynność",
            "Przyspieszyć ściąganie należności (faktoring, krótsze terminy, rabaty za szybką zapłatę), zmniejszyć zapasy, wydłużyć terminy płatności dostawcom, zamienić krótki dług na długi, podwyższyć kapitał. Każda metoda ma koszt – trzeba porównać korzyść z płynności z utraconą rentownością."),
          PF("Płynność bieżąca równa 5 zawsze oznacza bardzo dobrą sytuację firmy.", False,
             why="Może wskazywać na nadmiar zamrożonego kapitału w zapasach i należnościach."),
      ],
      mech=[
          KT("Co poprawia, a co pogarsza płynność bieżącą (przy wskaźniku > 1)?",
             {"Poprawia": ["Zamiana kredytu krótkoterminowego na długoterminowy", "Emisja akcji za gotówkę", "Sprzedaż zbędnej maszyny za gotówkę"],
              "Pogarsza": ["Zakup maszyny za gotówkę", "Zaciągnięcie kredytu krótkoterminowego na inwestycję długoterminową", "Wypłata dywidendy"]},
             why="Licznik to aktywa obrotowe, mianownik – zobowiązania krótkoterminowe."),
          LN("Ułóż, jak problemy klientów przenoszą się na płynność firmy.",
             ["Główny klient opóźnia płatności", "Rosną należności, maleje gotówka", "Firma nie płaci dostawcom w terminie", "Dostawcy wstrzymują dostawy lub żądają przedpłat", "Produkcja spowalnia, a ryzyko upadłości rośnie"],
             why="Zatory płatnicze rozchodzą się po łańcuchu dostaw."),
          W("Firma ma płynność bieżącą 1,8, ale szybką 0,4. Co to oznacza?",
            "Większość aktywów obrotowych to zapasy – płynność zależy od ich sprzedaży", "Firma ma nadmiar gotówki", "Firma nie ma zapasów",
            why="Duża różnica oznacza wysoki udział zapasów."),
          W("Spółka spłaca gotówką część zobowiązań krótkoterminowych. Przy płynności bieżącej 2,0 wskaźnik:",
            "Wzrośnie", "Spadnie", "Nie zmieni się",
            why="Np. (200 − 50) / (100 − 50) = 3,0 > 2,0."),
          M("Jak firma może poprawić płynność?",
            ["Skrócić terminy płatności dla odbiorców", "Ograniczyć nadmierne zapasy", "Zastąpić krótki kredyt długim", "Wydłużyć terminy płatności dla odbiorców"], [0, 1, 2],
            why="Dłuższe terminy dla odbiorców zwiększają należności i pogarszają płynność gotówkową."),
          PF("Firma może być wypłacalna, a jednocześnie mieć problemy z płynnością.", True,
             why="Majątek może być trudny do szybkiego spieniężenia."),
      ],
      calc=[
          LB("AO 1 200, ZK 800 (tys. zł). Ile wynosi płynność bieżąca?",
             1.5, "1200/800", ["1200 / 800 = 1,5"], unit="", tol=0.01),
          LB("Zapasy 500 tys. zł. Ile wynosi płynność szybka?",
             0.88, "(1200-500)/800", ["700 / 800 = 0,875"], unit="", tol=0.02),
          LB("Gotówka 120 tys. zł. Ile wynosi płynność gotówkowa?",
             0.15, "120/800", ["120 / 800 = 0,15"], unit="", tol=0.01),
          LB("Firma spłaca 200 tys. zł ZK z gotówki (gotówki wystarcza dzięki wpływowi należności). Ile wynosi nowa płynność bieżąca?",
             1.67, "(1200-200)/(800-200)", ["1000 / 600 ≈ 1,67"], unit="", tol=0.02),
          LB("Przepływy operacyjne 600, ZK 800 (tys. zł). Ile wynosi wskaźnik pokrycia zobowiązań krótkoterminowych przepływami?",
             0.75, "600/800", ["600 / 800 = 0,75"], unit="", tol=0.01),
          LB("Ile gotówki musiałaby mieć firma (ZK 800 tys. zł), by płynność gotówkowa wyniosła 0,2 (tys. zł)?",
             160, "800*0.2", ["800 · 0,2 = 160 tys. zł"], unit="tys. zł"),
      ],
      case=[
          PR("Sieć supermarketów: aktywa obrotowe 3 mld zł (zapasy 2,2 mld), zobowiązania krótkoterminowe 4 mld zł (głównie wobec dostawców z terminem 60 dni). Towar rotuje co 20 dni, klienci płacą od razu.",
             W("Ile wynosi płynność bieżąca?",
               "0,75", "1,33", "0,2",
               why="3 / 4 = 0,75 – poniżej typowych norm."),
             W("Dlaczego niski wskaźnik nie musi oznaczać kłopotów?",
               "Towar sprzedaje się za gotówkę szybciej, niż trzeba zapłacić dostawcom", "Bo supermarkety nie płacą dostawcom", "Bo zapasy są nieistotne",
               why="Ujemny cykl konwersji gotówki – dostawcy finansują działalność."),
             PF("Normy wskaźników płynności trzeba dopasować do branży.", True,
                why="Handel detaliczny i przemysł ciężki mają różne modele finansowania."),
          ),
          PR("Firma budowlana ma płynność bieżącą 1,4 i szybką 1,1. Główny inwestor opóźnia płatność 5 mln zł. Firma ma zobowiązania krótkoterminowe 10 mln zł i gotówkę 1 mln zł.",
             W("Ile wynosi płynność gotówkowa?",
               "0,1", "1,1", "0,5",
               why="1 / 10 = 0,1 – gotówka pokrywa jedną dziesiątą długów."),
             W("Co może szybko zrobić, by zachować płynność?",
               "Sfaktoryzować należności lub uruchomić kredyt obrotowy", "Kupić nową koparkę za gotówkę", "Wypłacić dywidendę",
               why="Faktoring i kredyt obrotowy zamieniają należności lub zdolność kredytową na gotówkę."),
             PF("Dobre wskaźniki bieżącej i szybkiej płynności nie chronią, jeśli należności są nieściągalne.", True,
                why="Wskaźniki zakładają, że należności zamienią się w gotówkę."),
          ),
      ]),

    L(3, "Rentowność i analiza Du Ponta",
      "Liczyć rentowność sprzedaży, aktywów i kapitału własnego, rozkładać ROE metodą Du Ponta na marżę, rotację aktywów i dźwignię finansową i rozumieć, co naprawdę napędza zwrot dla właścicieli.",
      ["Wskaźniki rentowności (ROA, ROE, ROS)", "Analiza wskaźnikowa"],
      [M123, F165],
      explain=[
          K("Trzy rentowności",
            "ROS (rentowność sprzedaży) = zysk netto / przychody – ile zysku z każdej złotówki sprzedaży. ROA (rentowność aktywów) = zysk netto / aktywa – jak efektywnie firma wykorzystuje majątek. ROE (rentowność kapitału własnego) = zysk netto / kapitał własny – ile zarabiają właściciele.",
            w="ROS = ZN / P;  ROA = ZN / A;  ROE = ZN / KW"),
          K("Model Du Ponta",
            "ROE = ROS × rotacja aktywów × mnożnik kapitałowy = (ZN/P) × (P/A) × (A/KW). Pokazuje trzy drogi do wysokiego ROE: wysoka marża (np. marki luksusowe), szybka rotacja majątku (np. dyskonty) albo duża dźwignia finansowa (np. banki).",
            w="ROE = (ZN/P) · (P/A) · (A/KW)"),
          W("ROS 5%, rotacja aktywów 2, mnożnik kapitałowy 2,5. Ile wynosi ROE?",
            "25%", "10%", "12,5%",
            why="5% · 2 · 2,5 = 25%."),
          K("Dźwignia podnosi ROE – ale i ryzyko",
            "Przy tym samym ROA firma z większym długiem (wyższy mnożnik A/KW) ma wyższe ROE – o ile rentowność aktywów przekracza koszt długu. Gdy wyniki spadną, dług zwiększa straty właścicieli. Wysokie ROE uzyskane głównie dźwignią jest mniej trwałe niż z marży lub rotacji."),
          K("Porównania",
            "Rentowność porównuje się z kosztem kapitału: ROE poniżej kosztu kapitału własnego oznacza, że firma nie zarabia tyle, ile oczekują właściciele (por. EVA). Różne branże mają różne typowe ROS – dyskont ma niską marżę i szybką rotację, firma programistyczna – wysoką marżę."),
          PF("Dwie firmy o tym samym ROE mogą osiągać je zupełnie innymi drogami.", True,
             why="Model Du Ponta rozdziela marżę, rotację i dźwignię."),
      ],
      mech=[
          KT("Która składowa Du Ponta wyjaśnia wysokie ROE?",
             {"Wysoka marża (ROS)": ["Producent zegarków luksusowych", "Firma z unikalnym patentem"],
              "Szybka rotacja aktywów": ["Sieć dyskontów spożywczych", "Hurtownia o wysokim obrocie"],
              "Wysoka dźwignia (A/KW)": ["Bank komercyjny", "Spółka leasingowa"]},
             why="Różne modele biznesowe osiągają ROE różnymi drogami."),
          LN("Ułóż, jak dźwignia zwiększa ROE.",
             ["Firma ma ROA 10% i finansuje się tylko kapitałem własnym (ROE 10%)", "Zastępuje połowę kapitału własnego długiem o koszcie 6% po podatku", "Aktywa nadal zarabiają 10%", "Część zysku zostaje po zapłacie odsetek dla mniejszego kapitału", "ROE rośnie do 14%"],
             why="Gdy ROA > koszt długu, dźwignia podnosi ROE."),
          W("ROA spada poniżej kosztu długu po podatku. Co robi dźwignia?",
            "Obniża ROE – działa na niekorzyść właścicieli", "Podnosi ROE", "Nie ma wpływu",
            why="Odsetki pochłaniają więcej, niż zarabiają aktywa finansowane długiem."),
          W("Dyskont ma ROS 2%, ale ROE 20%. Jak to możliwe?",
            "Bardzo szybka rotacja aktywów i umiarkowana dźwignia", "Bardzo wysoka marża", "Brak aktywów",
            why="Np. 2% · 4 · 2,5 = 20%."),
          M("Co bezpośrednio podnosi ROE (ceteris paribus)?",
            ["Wzrost marży netto", "Szybsza rotacja aktywów", "Wyższy udział długu przy ROA > koszt długu", "Zatrzymanie gotówki bez inwestowania"], [0, 1, 2],
            why="Nieużywana gotówka zwiększa aktywa bez zysku – obniża ROA i ROE."),
          PF("ROE banku jest zwykle w dużej mierze wynikiem wysokiej dźwigni.", True,
             why="Banki finansują aktywa głównie depozytami."),
      ],
      calc=[
          LB("Zysk netto 1,5 mln zł, przychody 30 mln zł. Ile wynosi ROS (%)?",
             5, "1.5/30*100", ["1,5 / 30 = 5%"], unit="%"),
          LB("Aktywa 20 mln zł. Ile wynosi ROA (%)?",
             7.5, "1.5/20*100", ["1,5 / 20 = 7,5%"], unit="%", tol=0.01),
          LB("Kapitał własny 8 mln zł. Ile wynosi ROE (%)?",
             18.75, "1.5/8*100", ["1,5 / 8 = 18,75%"], unit="%", tol=0.01),
          LB("Ile wynosi rotacja aktywów (P/A)?",
             1.5, "30/20", ["30 / 20 = 1,5"], unit="", tol=0.01),
          LB("Ile wynosi mnożnik kapitałowy (A/KW)?",
             2.5, "20/8", ["20 / 8 = 2,5"], unit="", tol=0.01),
          LB("Sprawdzenie Du Ponta: ROS 5% · rotacja 1,5 · mnożnik 2,5 = ROE (%)?",
             18.75, "5*1.5*2.5", ["5 · 1,5 · 2,5 = 18,75%"], unit="%", tol=0.01),
      ],
      case=[
          PR("Firma A (marka premium): ROS 15%, rotacja aktywów 0,8, A/KW 1,5. Firma B (dyskont): ROS 2,5%, rotacja 3,2, A/KW 2,25.",
             W("Ile wynosi ROE firmy A?",
               "18%", "15%", "12%",
               why="15% · 0,8 · 1,5 = 18%."),
             W("Ile wynosi ROE firmy B?",
               "18%", "7,2%", "2,5%",
               why="2,5% · 3,2 · 2,25 = 18%."),
             PF("Obie firmy mają to samo ROE, ale osiągają je różnymi modelami biznesu.", True,
                why="A – marża, B – rotacja i dźwignia."),
             W("Która firma jest bardziej wrażliwa na spadek sprzedaży o 10% (przy stałych kosztach stałych)?",
               "Raczej B – niska marża i wyższa dźwignia", "Raczej A", "Żadna",
               why="Mała marża szybko znika przy spadku sprzedaży, a dług zwiększa ryzyko."),
          ),
          PR("Spółka ma aktywa 100 mln zł, zysk operacyjny po podatku 10 mln zł (ROA 10%). Rozważa finansowanie: (I) 100% kapitał własny, (II) 50% kapitał własny i 50% dług o koszcie po podatku 6%.",
             W("Ile wynosi ROE w wariancie I?",
               "10%", "14%", "6%",
               why="10 / 100 = 10%."),
             W("Ile wynosi ROE w wariancie II?",
               "14%", "10%", "20%",
               why="Zysk po odsetkach: 10 − 3 = 7; 7 / 50 = 14%."),
             PF("Gdyby ROA spadło do 4%, ROE w wariancie II byłoby niższe niż w wariancie I.", True,
                why="I: 4%; II: (4 − 3) / 50 = 2%."),
          ),
      ]),

    L(4, "Zadłużenie i sprawność działania",
      "Liczyć wskaźniki zadłużenia (ogólnego, kapitału własnego, pokrycia odsetek) i rotacji zapasów, należności i zobowiązań w dniach oraz łączyć je w ocenę bezpieczeństwa finansowego i sprawności firmy.",
      ["Wskaźniki zadłużenia", "Wskaźniki rotacji (sprawności)", "Analiza wskaźnikowa"],
      [F93, F105, F165],
      explain=[
          K("Wskaźniki zadłużenia",
            "Wskaźnik ogólnego zadłużenia = zobowiązania / aktywa (jaka część majątku jest finansowana długiem; często przyjmuje się do ok. 0,5–0,7). Zadłużenie kapitału własnego = zobowiązania / kapitał własny. Pokrycie odsetek = EBIT / odsetki – ile razy zysk operacyjny pokrywa koszty odsetek (bezpiecznie > 3).",
            w="zadłużenie ogólne = Z / A;  pokrycie odsetek = EBIT / odsetki"),
          K("Rotacja w dniach",
            "Rotacja zapasów (dni) = zapasy / koszt sprzedanych towarów × 365. Rotacja należności (dni) = należności / przychody × 365 – średni czas oczekiwania na zapłatę. Rotacja zobowiązań (dni) = zobowiązania handlowe / koszt zakupów (lub koszt sprzedaży) × 365 – po ilu dniach płacimy dostawcom.",
            w="dni = (pozycja bilansu / pozycja RZiS) · 365"),
          W("Należności 1,2 mln zł, przychody 14,6 mln zł. Ile wynosi rotacja należności w dniach?",
            "30 dni", "12 dni", "60 dni",
            why="1,2 / 14,6 · 365 = 30 dni."),
          K("Rotacja aktywów",
            "Rotacja aktywów = przychody / aktywa – ile złotych sprzedaży generuje złotówka majątku. Wysoka rotacja oznacza efektywne wykorzystanie majątku, ale zależy od branży (energetyka – niska, handel – wysoka)."),
          K("Spojrzenie banku",
            "Bank, udzielając kredytu, patrzy na zadłużenie (czy firma nie jest przelewarowana), pokrycie odsetek i dług netto / EBITDA (zdolność obsługi długu) oraz rotację (czy gotówka nie jest zamrożona). W umowach kredytowych wpisuje kowenanty – progi tych wskaźników, których przekroczenie pozwala bankowi np. wypowiedzieć kredyt."),
          PF("Wydłużenie rotacji należności z 30 do 60 dni zwiększa zapotrzebowanie na kapitał obrotowy.", True,
             why="Gotówka dłużej jest zamrożona u odbiorców."),
      ],
      mech=[
          KT("Co oznacza zmiana wskaźnika?",
             {"Sygnał poprawy": ["Rotacja zapasów spada z 90 do 60 dni", "Pokrycie odsetek rośnie z 2 do 5", "Zadłużenie ogólne spada z 0,8 do 0,6"],
              "Sygnał pogorszenia": ["Rotacja należności rośnie z 40 do 75 dni", "Dług netto / EBITDA rośnie z 2 do 5"]},
             why="Każdy wskaźnik ma pożądany kierunek."),
          LN("Ułóż, jak nadmierne zadłużenie prowadzi do kłopotów.",
             ["Firma finansuje ekspansję kredytami", "Rośnie zadłużenie i koszty odsetek", "W spowolnieniu EBIT spada", "Pokrycie odsetek spada poniżej progu w kowenantach", "Bank żąda spłaty lub zaostrza warunki – firma traci płynność"],
             why="Wysoka dźwignia zmniejsza margines bezpieczeństwa."),
          W("Firma płaci dostawcom po 20 dniach, a klienci płacą jej po 70 dniach. Co z tego wynika?",
            "Firma musi finansować 50 dni luki – rośnie zapotrzebowanie na kapitał obrotowy", "Firma ma nadmiar gotówki", "Nic nie wynika",
            why="Płaci szybciej, niż otrzymuje zapłatę."),
          W("Pokrycie odsetek wynosi 1,2. Co to oznacza?",
            "Zysk operacyjny ledwie wystarcza na odsetki – ryzyko jest wysokie", "Firma ma bardzo bezpieczne finansowanie", "Firma nie ma długu",
            why="Niewielki spadek EBIT uniemożliwi obsługę odsetek."),
          M("Jak skrócić rotację zapasów?",
            ["Lepsze prognozowanie popytu", "Dostawy just-in-time", "Wyprzedaż zalegającego towaru", "Zakup dużych partii na zapas"], [0, 1, 2],
            why="Duże zakupy na zapas wydłużają rotację."),
          PF("Kowenanty bankowe to warunki w umowie kredytowej, np. maksymalny poziom zadłużenia.", True,
             why="Ich naruszenie daje bankowi określone uprawnienia."),
      ],
      calc=[
          LB("Zobowiązania 6 mln zł, aktywa 10 mln zł. Ile wynosi wskaźnik ogólnego zadłużenia?",
             0.6, "6/10", ["6 / 10 = 0,6"], unit="", tol=0.01),
          LB("Ile wynosi zadłużenie kapitału własnego (KW = 4 mln zł)?",
             1.5, "6/4", ["6 / 4 = 1,5"], unit="", tol=0.01),
          LB("EBIT 2,4 mln zł, odsetki 0,6 mln zł. Ile wynosi pokrycie odsetek?",
             4, "2.4/0.6", ["2,4 / 0,6 = 4"], unit="razy"),
          LB("Zapasy 1,5 mln zł, koszt sprzedanych towarów 9,125 mln zł. Ile wynosi rotacja zapasów (dni)?",
             60, "1.5/9.125*365", ["1,5 / 9,125 · 365 = 60 dni"], unit="dni"),
          LB("Zobowiązania handlowe 0,75 mln zł, koszt sprzedanych towarów 9,125 mln zł. Ile wynosi rotacja zobowiązań (dni)?",
             30, "0.75/9.125*365", ["0,75 / 9,125 · 365 = 30 dni"], unit="dni"),
          LB("Przychody 15 mln zł, aktywa 10 mln zł. Ile wynosi rotacja aktywów?",
             1.5, "15/10", ["15 / 10 = 1,5"], unit="", tol=0.01),
      ],
      case=[
          PR("Producent mebli (mln zł): aktywa 50, zobowiązania 38, kapitał własny 12; EBIT 6, odsetki 3; dług netto 30, EBITDA 9. Kowenant: dług netto / EBITDA ≤ 3,5; pokrycie odsetek ≥ 2.",
             W("Ile wynosi wskaźnik ogólnego zadłużenia?",
               "0,76", "0,24", "3,17",
               why="38 / 50 = 0,76."),
             W("Czy firma spełnia kowenant dług netto / EBITDA?",
               "Tak – 3,33 ≤ 3,5", "Nie – 3,33 > 3,5", "Nie da się policzyć",
               why="30 / 9 ≈ 3,33 – tuż poniżej progu 3,5."),
             W("Ile wynosi pokrycie odsetek?",
               "2 – na granicy kowenantu", "0,5", "6",
               why="6 / 3 = 2 – dokładnie na progu kowenantu."),
             PF("Niewielki spadek EBIT spowoduje złamanie kowenantu pokrycia odsetek.", True,
                why="Wskaźnik jest dokładnie na progu."),
          ),
          PR("Hurtownia: rotacja zapasów 45 dni, należności 50 dni, zobowiązań 35 dni. Konkurent: 30, 35 i 45 dni.",
             W("Która firma potrzebuje więcej kapitału obrotowego (dłuższy cykl konwersji gotówki)?",
               "Hurtownia – cykl 60 dni vs 20 dni", "Konkurent", "Obie tyle samo",
               why="45 + 50 − 35 = 60; 30 + 35 − 45 = 20."),
             W("Co hurtownia może poprawić najszybciej?",
               "Ściąganie należności i zarządzanie zapasami", "Zwiększenie zapasów", "Skrócenie terminów płatności dostawcom",
               why="To skraca cykl i uwalnia gotówkę."),
             PF("Dłuższe terminy płatności wobec dostawców skracają cykl konwersji gotówki.", True,
                why="Dostawcy dłużej finansują działalność."),
          ),
      ]),

    L(5, "Dźwignia operacyjna i finansowa oraz modele ostrzegania przed upadłością",
      "Liczyć stopień dźwigni operacyjnej, finansowej i całkowitej, rozumieć, jak struktura kosztów i finansowania zwiększa wrażliwość zysku, oraz stosować modele wczesnego ostrzegania (np. Z-score Altmana).",
      ["Dźwignia operacyjna i finansowa (DOL, DFL)", "Modele wczesnego ostrzegania przed upadłością"],
      [M35, F165],
      explain=[
          K("Dźwignia operacyjna",
            "Wynika z kosztów stałych. Stopień dźwigni operacyjnej DOL = marża pokrycia / EBIT – pokazuje, o ile procent zmieni się EBIT, gdy sprzedaż zmieni się o 1%. Firma z wysokimi kosztami stałymi (np. huta) ma wysoki DOL: w dobrych latach zysk rośnie szybko, w złych – szybko spada.",
            w="DOL = marża pokrycia / EBIT = %ΔEBIT / %ΔQ"),
          K("Dźwignia finansowa i całkowita",
            "Wynika z kosztów odsetek. DFL = EBIT / (EBIT − odsetki) – o ile procent zmieni się zysk przed opodatkowaniem (i EPS), gdy EBIT zmieni się o 1%. Dźwignia całkowita DTL = DOL × DFL – wrażliwość zysku netto na zmianę sprzedaży.",
            w="DFL = EBIT / (EBIT − I);  DTL = DOL · DFL"),
          W("DOL = 3, sprzedaż rośnie o 10%. O ile procent wzrośnie EBIT?",
            "30%", "10%", "3%",
            why="3 · 10% = 30% – EBIT zmienia się trzy razy mocniej."),
          K("Modele wczesnego ostrzegania",
            "Łączą kilka wskaźników w jeden wynik przewidujący ryzyko upadłości. Najbardziej znany: Z-score E. Altmana (1968) dla spółek przemysłowych: Z = 1,2·X1 + 1,4·X2 + 3,3·X3 + 0,6·X4 + 1,0·X5 (kapitał obrotowy, zyski zatrzymane, EBIT, wartość rynkowa kapitału do zobowiązań, przychody – w relacji do aktywów). Z < 1,81 – wysokie ryzyko, Z > 2,99 – niskie. W Polsce opracowano własne modele (np. Mączyńskiej, Hołdy, Gajdki i Stosa).",
            w="Z = 1,2X1 + 1,4X2 + 3,3X3 + 0,6X4 + 1,0X5"),
          K("Ograniczenia",
            "Modele budowane na danych z jednego kraju i okresu mogą słabiej działać gdzie indziej. Są tylko sygnałem – nie zastępują analizy przepływów, rynku i zarządu. Wskaźniki można też „upiększać” (window dressing) przed dniem bilansowym."),
          PF("Wysoka dźwignia operacyjna i finansowa razem bardzo zwiększają ryzyko w recesji.", True,
             why="DTL = DOL · DFL – efekty się mnożą."),
      ],
      mech=[
          LN("Ułóż, jak spadek sprzedaży przenosi się na zysk netto.",
             ["Sprzedaż spada o 10%", "Koszty stałe pozostają – EBIT spada o DOL · 10%", "Odsetki pozostają – zysk brutto spada o DFL razy więcej niż EBIT", "Zysk netto spada o DTL · 10%", "Przy wysokich dźwigniach firma może przejść ze zysku w stratę"],
             why="Koszty stałe i odsetki działają jak mnożniki."),
          KT("Wysoka dźwignia operacyjna czy finansowa?",
             {"Operacyjna (koszty stałe)": ["Linia lotnicza z flotą samolotów", "Huta stali z drogimi piecami", "Firma programistyczna z wysokimi kosztami rozwoju"],
              "Finansowa (odsetki)": ["Spółka po wykupie lewarowanym", "Deweloper finansujący budowy kredytami"]},
             why="Źródło dźwigni: koszty stałe operacyjne lub koszty długu."),
          W("Firma zastępuje część kosztów zmiennych stałymi (automatyzacja). Co dzieje się z DOL?",
            "Rośnie", "Spada", "Nie zmienia się",
            why="Większy udział kosztów stałych zwiększa dźwignię operacyjną."),
          W("Z-score firmy spadł z 3,4 do 1,5. Jak to interpretować?",
            "Firma przeszła ze strefy bezpiecznej do strefy wysokiego ryzyka upadłości", "Sytuacja się poprawiła", "Nie ma to znaczenia",
            why="Poniżej 1,81 – wysokie ryzyko według Altmana."),
          M("Jakie wskaźniki wchodzą do Z-score Altmana (w relacji do aktywów)?",
            ["Kapitał obrotowy", "Zyski zatrzymane", "EBIT", "Liczba pracowników"], [0, 1, 2],
            why="Model nie uwzględnia zatrudnienia."),
          PF("DFL wynosi 1, gdy firma nie ma odsetek.", True,
             why="EBIT / (EBIT − 0) = 1."),
      ],
      calc=[
          LB("Marża pokrycia 3 mln zł, EBIT 1 mln zł. Ile wynosi DOL?",
             3, "3/1", ["3 / 1 = 3"], unit=""),
          LB("EBIT 1 mln zł, odsetki 0,5 mln zł. Ile wynosi DFL?",
             2, "1/(1-0.5)", ["1 / 0,5 = 2"], unit=""),
          LB("Ile wynosi DTL (DOL 3, DFL 2)?",
             6, "3*2", ["3 · 2 = 6"], unit=""),
          LB("Sprzedaż spada o 8%. O ile procent spadnie zysk netto przy DTL = 6?",
             48, "6*8", ["6 · 8% = 48%"], unit="%"),
          LB("Z-score: X1 = 0,1; X2 = 0,2; X3 = 0,1; X4 = 0,8; X5 = 1,2. Ile wynosi Z?",
             2.41, "1.2*0.1+1.4*0.2+3.3*0.1+0.6*0.8+1.0*1.2", ["0,12 + 0,28 + 0,33 + 0,48 + 1,2 = 2,41 – strefa szara"], unit="", tol=0.01),
          LB("EBIT 1,2 mln zł, odsetki 0,3 mln zł. O ile procent wzrośnie zysk przed opodatkowaniem, gdy EBIT wzrośnie o 10%?",
             13.33, "1.2/(1.2-0.3)*10", ["DFL = 1,2 / 0,9 ≈ 1,333", "1,333 · 10% ≈ 13,33%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Linia lotnicza: przychody 10 mld zł, koszty zmienne 6 mld zł, koszty stałe 3,2 mld zł, odsetki 0,4 mld zł. Pandemia obniża sprzedaż o 30%.",
             W("Ile wynosi EBIT przed pandemią?",
               "0,8 mld zł", "4 mld zł", "0,4 mld zł",
               why="10 − 6 − 3,2 = 0,8 mld zł."),
             W("Ile wynosi DOL?",
               "5", "2", "1,25",
               why="Marża 4 / EBIT 0,8 = 5."),
             W("Ile wyniesie EBIT po spadku sprzedaży o 30%?",
               "−0,4 mld zł (strata)", "0,56 mld zł", "0,8 mld zł",
               why="Marża 2,8 − koszty stałe 3,2 = −0,4 mld zł."),
             PF("Wysoka dźwignia operacyjna sprawiła, że 30% spadku sprzedaży zamieniło zysk w stratę.", True,
                why="DOL = 5: 30% · 5 = 150% spadku EBIT."),
          ),
          PR("Analityk banku liczy Z-score dla trzech klientów: A – 3,6; B – 2,2; C – 1,3. Bank ma ograniczony limit kredytowy.",
             W("Któremu klientowi bank najchętniej udzieli kredytu?",
               "A – strefa bezpieczna", "C – strefa zagrożenia", "B – strefa szara",
               why="Z > 2,99 oznacza niskie ryzyko."),
             W("Jak traktować klienta B?",
               "Pogłębić analizę – strefa niepewności", "Odrzucić automatycznie", "Przyjąć bez analizy",
               why="Wynik między 1,81 a 2,99 to strefa szara."),
             PF("Z-score nie powinien być jedynym kryterium decyzji kredytowej.", True,
                why="Model ma ograniczenia i nie uwzględnia wszystkich czynników."),
          ),
      ]),
    L(6, "Metody analizy finansowej: porównania, analiza czynnikowa i model Du Ponta",
      "Znać rodzaje analizy finansowej i jej materiały źródłowe, stosować metody porównań, rozkładać zmianę wielkości na czynniki metodą kolejnych podstawień i interpretować model Du Ponta; odróżniać metody deterministyczne od stochastycznych.",
      ["Analiza finansowa – istota, przedmiot i rodzaje", "Materiały źródłowe analizy finansowej", "Metody porównań w analizie finansowej", "Metody deterministyczne (kolejnych podstawień, różnic cząstkowych)", "Metoda kolejnych podstawień – wzór", "Metody stochastyczne w analizie finansowej", "Model Du Ponta (piramida wskaźników)"],
      [GLIT, GWYP, GDP, GHAG],
      explain=[
          K("Czym jest analiza finansowa",
            "To część analizy ekonomicznej przedsiębiorstwa, która na podstawie sprawozdań finansowych ocenia majątek, kapitały, wyniki, płynność, sprawność i zadłużenie. Bywa ex post (co się stało) lub ex ante (prognoza), wewnętrzna (dla zarządu) lub zewnętrzna (dla banku, inwestora), wstępna (czytanie sprawozdań) lub szczegółowa (wskaźniki)."),
          K("Materiały źródłowe",
            "Sprawozdanie finansowe: bilans, rachunek zysków i strat (porównawczy – koszty według rodzajów, lub kalkulacyjny – koszty według funkcji), rachunek przepływów pieniężnych, zestawienie zmian w kapitale własnym i informacja dodatkowa. Uzupełniają je sprawozdanie z działalności, opinia biegłego rewidenta oraz dane branżowe."),
          W("Bank ocenia wniosek kredytowy firmy na podstawie jej sprawozdań z ostatnich 3 lat. Jaki to rodzaj analizy?",
            "Zewnętrzna analiza ex post", "Wewnętrzna analiza ex ante", "Analiza techniczno-ekonomiczna",
            why="Analizę prowadzi podmiot zewnętrzny na danych historycznych."),
          K("Porównania i analiza czynnikowa",
            "Wskaźnik ma sens dopiero w porównaniu: w czasie, z konkurencją (benchmarking), z planem lub normą. Analiza czynnikowa wyjaśnia, skąd wzięła się zmiana. Metody deterministyczne działają przy zależności funkcyjnej (sprzedaż = ilość × cena) – np. metoda kolejnych podstawień. Metody stochastyczne (korelacja, regresja) badają zależności niepewne, np. reklama a sprzedaż.",
            w="Δy(a) = a₁b₀ − a₀b₀;  Δy(b) = a₁b₁ − a₁b₀"),
          K("Model Du Ponta",
            "Opracowany w koncernie DuPont (F. Donaldson Brown, ok. 1914 r.): ROE = rentowność sprzedaży × rotacja aktywów × mnożnik kapitałowy (aktywa / kapitał własny). Dwie firmy o tej samej ROE mogą zarabiać zupełnie inaczej – jedna wysoką marżą, druga szybkim obrotem, trzecia wysokim zadłużeniem.",
            w="ROE = (ZN/S) · (S/A) · (A/KW)"),
          PF("W metodzie kolejnych podstawień wynik nie zależy od kolejności podstawiania czynników.", False,
             why="Zmiana kolejności zmienia podział wpływów między czynniki."),
      ],
      mech=[
          KT("Metoda deterministyczna czy stochastyczna?",
             {"Deterministyczna": ["Wpływ ceny i ilości na wartość sprzedaży", "Rozkład zmiany ROE na czynniki Du Ponta"],
              "Stochastyczna": ["Związek wydatków na reklamę ze sprzedażą", "Prognoza sprzedaży na podstawie trendu i korelacji"]},
             why="Deterministyczne wymagają zależności funkcyjnej."),
          LN("Ułóż kroki analizy czynnikowej metodą kolejnych podstawień.",
             ["Zapisz zależność, np. S = ilość · cena", "Oblicz wartość bazową i badaną", "Podstaw badaną wartość pierwszego czynnika", "Podstaw badaną wartość drugiego czynnika", "Sprawdź, że suma wpływów równa się całkowitej zmianie"],
             why="Kolejne czynniki zastępuje się po kolei."),
          W("Firma ma ROE 20% przy niskiej marży i bardzo wysokim mnożniku kapitałowym. Co to oznacza?",
            "Wysoka ROE wynika głównie z zadłużenia, więc niesie większe ryzyko", "Firma ma najwyższą efektywność operacyjną", "Firma nie ma długów",
            why="Mnożnik kapitałowy mierzy dźwignię finansową."),
          W("Które sprawozdanie pokazuje koszty według funkcji (sprzedaży, ogólnego zarządu)?",
            "RZiS w wariancie kalkulacyjnym", "RZiS w wariancie porównawczym", "Bilans",
            why="Wariant porównawczy pokazuje koszty rodzajowe."),
          M("Jakie porównania stosuje się w analizie wskaźnikowej?",
            ["W czasie (dynamika)", "Z konkurencją lub średnią branży", "Z wartościami zalecanymi", "Z kursem walutowym z innego kraju bez związku z firmą"], [0, 1, 2],
            why="Punkt odniesienia musi być porównywalny."),
          PF("Model Du Ponta pozwala ocenić, czy ROE rośnie dzięki marży, obrotowi czy dźwigni.", True,
             why="To jego główna zaleta."),
      ],
      calc=[
          LB("Ilość 1000 → 1200 szt., cena 10 → 9 zł. Jaki jest wpływ zmiany ilości na sprzedaż (zł; kolejność: najpierw ilość)?",
             2000, "1200*10-1000*10", ["1200 · 10 − 1000 · 10 = 2000 zł"], unit="zł"),
          LB("Jaki jest wpływ zmiany ceny (zł)? Podaj wartość ze znakiem jako liczbę.",
             -1200, "1200*9-1200*10", ["1200 · 9 − 1200 · 10 = −1200 zł"], unit="zł"),
          LB("Ile wynosi całkowita zmiana sprzedaży (zł)?",
             800, "1200*9-1000*10", ["10 800 − 10 000 = 800 zł"], unit="zł"),
          LB("ROS 5%, rotacja aktywów 1,6, mnożnik kapitałowy 2,5. Ile wynosi ROE (%)?",
             20, "5*1.6*2.5", ["5% · 1,6 · 2,5 = 20%"], unit="%"),
          LB("Ile wynosi ROA w tej firmie (%)?",
             8, "5*1.6", ["5% · 1,6 = 8%"], unit="%"),
          LB("ROE: 10% (ROS 10%, rotacja 0,5, mnożnik 2) → ROS rośnie do 12%. Ile wynosi wpływ ROS na ROE (pkt proc.)?",
             2, "(12-10)*0.5*2", ["(12 − 10) · 0,5 · 2 = 2 pkt proc."], unit="pkt proc."),
      ],
      case=[
          PR("Dwie sieci handlowe mają ROE 15%. Sieć A: marża netto 1,5%, rotacja aktywów 5, mnożnik 2. Sieć B: marża 7,5%, rotacja 1, mnożnik 2. Analityk mówi, że ich modele biznesowe są zupełnie różne.",
             W("Skąd sieć A czerpie rentowność?",
               "Z bardzo szybkiego obrotu aktywami przy niskiej marży", "Z wysokiej marży", "Z wysokiego zadłużenia",
               why="ROE = 1,5% · 5 · 2 = 15%."),
             W("Skąd sieć B czerpie rentowność?",
               "Z wysokiej marży przy wolniejszym obrocie", "Z bardzo szybkiego obrotu", "Wyłącznie z zadłużenia",
               why="ROE = 7,5% · 1 · 2 = 15%."),
             PF("Obie sieci mają taki sam poziom dźwigni finansowej.", True,
                why="Mnożnik kapitałowy wynosi 2 w obu."),
          ),
          PR("Zarząd fabryki pyta, dlaczego sprzedaż wzrosła tylko o 800 zł, skoro sprzedano 20% więcej wyrobów. Analityk rozkłada zmianę na wpływ ilości (+2000 zł) i ceny (−1200 zł).",
             W("Jaką metodą posłużył się analityk?",
               "Metodą kolejnych podstawień", "Regresją liniową", "Analizą SWOT",
               why="To metoda deterministyczna analizy czynnikowej."),
             W("Jaki wniosek wynika z analizy?",
               "Obniżka ceny zjadła większość korzyści ze wzrostu ilości", "Cena nie miała wpływu", "Ilość spadła",
               why="Wpływ ceny −1200 zł wobec +2000 zł z ilości."),
             PF("Przy podstawianiu najpierw ceny podział wpływów byłby inny, choć suma pozostałaby 800 zł.", True,
                why="Wynik metody zależy od kolejności."),
          ),
      ]),

    L(7, "Analiza sprzedaży, kosztów i zysku",
      "Oceniać sprzedaż (wielkość, dynamika, struktura), koszty (wskaźnik poziomu kosztów, układ rodzajowy i kalkulacyjny) i zysk (poziomy wyniku, marża pokrycia), liczyć indeksy dynamiki i średnie tempo zmian.",
      ["Analiza sprzedaży (wielkość, dynamika, struktura, opłacalność)", "Indeksy dynamiki – wzory", "Wskaźnik poziomu kosztów", "Marża pokrycia (marża brutto)", "Wynik finansowy – poziomy", "Koszty według rodzajów"],
      [GLIT, GGUS, GKUJ, M35],
      explain=[
          K("Analiza sprzedaży",
            "Sprzedaż to źródło przychodów i podstawa zysku. Analizuje się jej wielkość (wartościowo i ilościowo), dynamikę (indeksy), strukturę (asortyment, rynki, klienci – np. analiza ABC: grupa A to kilka produktów dających większość przychodów) i opłacalność (marża pokrycia każdego wyrobu)."),
          K("Indeksy dynamiki",
            "Jednopodstawowy porównuje każdy okres z tym samym okresem bazowym, łańcuchowy – z okresem poprzednim. Średnie tempo zmian liczy się średnią geometryczną indeksów łańcuchowych.",
            w="iₜ = yₜ/y₀;  iₜ = yₜ/yₜ₋₁;  średnie tempo = (yₙ/y₀)^(1/n) − 1"),
          W("Sprzedaż: 200, 220, 242 mln zł. Ile wynosi indeks łańcuchowy w 3. roku?",
            "110", "121", "100",
            why="242 / 220 · 100 = 110."),
          K("Analiza kosztów",
            "Wskaźnik poziomu kosztów = koszty / przychody (ile groszy kosztów na złotówkę przychodu); dla przedsiębiorstw niefinansowych w Polsce wynosi zwykle ok. 95%. Koszty bada się w układzie rodzajowym (materiały, wynagrodzenia, amortyzacja…) i kalkulacyjnym (koszt wytworzenia, sprzedaży, ogólnego zarządu, koszt jednostkowy wyrobu)."),
          K("Zysk i marża pokrycia",
            "Wynik finansowy ma poziomy: ze sprzedaży, operacyjny (EBIT), brutto, netto. Marża pokrycia = przychody − koszty zmienne; pokrywa koszty stałe i daje zysk. Wyroby o ujemnej marży pokrycia obniżają zysk, a o dodatniej – pomagają pokryć koszty stałe, nawet gdy w rachunku pełnym wydają się nierentowne.",
            w="MP = S − KZ"),
          PF("Wzrost wskaźnika poziomu kosztów oznacza poprawę efektywności.", False,
             why="Więcej kosztów na złotówkę przychodu to pogorszenie."),
      ],
      mech=[
          KT("Indeks jednopodstawowy czy łańcuchowy?",
             {"Jednopodstawowy": ["Każdy rok porównany z 2020 r.", "Wzrost sprzedaży od początku działalności"],
              "Łańcuchowy": ["Każdy rok porównany z poprzednim", "Tempo zmian rok do roku"]},
             why="Różni je podstawa porównania."),
          LN("Ułóż od przychodów do zysku netto (wariant kalkulacyjny).",
             ["Przychody ze sprzedaży", "Minus koszt sprzedanych produktów – zysk brutto ze sprzedaży", "Minus koszty sprzedaży i ogólnego zarządu – zysk ze sprzedaży", "Plus/minus pozostała działalność operacyjna i finansowa – zysk brutto", "Minus podatek dochodowy – zysk netto"],
             why="Kolejne poziomy wyniku finansowego."),
          W("Wyrób ma cenę 50 zł i koszt zmienny 35 zł, ale po doliczeniu kosztów stałych „traci” 5 zł na sztuce. Czy wycofanie go zwiększy zysk w krótkim okresie?",
            "Nie – marża pokrycia 15 zł pomaga pokryć koszty stałe, które i tak pozostaną", "Tak – każdy wyrób ze stratą należy wycofać", "Nie ma to znaczenia",
            why="Koszty stałe nie znikną po wycofaniu wyrobu."),
          W("Co pokazuje analiza ABC asortymentu?",
            "Które produkty dają największą część przychodów", "Strukturę kapitału", "Rotację należności",
            why="Grupa A to nieliczne produkty o największym udziale."),
          M("Które pozycje należą do kosztów w układzie rodzajowym?",
            ["Zużycie materiałów i energii", "Wynagrodzenia", "Amortyzacja", "Koszty ogólnego zarządu"], [0, 1, 2],
            why="Koszty ogólnego zarządu to układ kalkulacyjny (funkcjonalny)."),
          PF("Średnie tempo zmian oblicza się średnią geometryczną indeksów łańcuchowych.", True,
             why="Uwzględnia procent składany zmian."),
      ],
      calc=[
          LB("Sprzedaż 200 → 242 mln zł w ciągu 2 lat. Ile wynosi średnie roczne tempo wzrostu (%)?",
             10, "((242/200)**0.5-1)*100", ["(242/200)^(1/2) − 1 = 1,1 − 1 = 10%"], unit="%"),
          LB("Jaki jest indeks jednopodstawowy dla 242 mln zł (baza 200)?",
             121, "242/200*100", ["242 / 200 · 100 = 121"], unit=""),
          LB("Koszty 9,5 mln zł, przychody 10 mln zł. Ile wynosi wskaźnik poziomu kosztów (%)?",
             95, "9.5/10*100", ["9,5 / 10 = 95%"], unit="%"),
          LB("Przychody 2 mln zł, koszty zmienne 1,2 mln zł. Ile wynosi marża pokrycia (mln zł)?",
             0.8, "2-1.2", ["2 − 1,2 = 0,8 mln zł"], unit="mln zł"),
          LB("Koszty stałe 0,5 mln zł. Ile wynosi zysk operacyjny (mln zł)?",
             0.3, "0.8-0.5", ["0,8 − 0,5 = 0,3 mln zł"], unit="mln zł"),
          LB("Ile wynosi wskaźnik marży pokrycia (%)?",
             40, "0.8/2*100", ["0,8 / 2 = 40%"], unit="%"),
      ],
      case=[
          PR("Producent mebli sprzedaje trzy wyroby. Szafy: przychody 6 mln zł, koszty zmienne 3,6 mln zł. Stoły: 3 mln zł i 2,4 mln zł. Krzesła: 1 mln zł i 1,1 mln zł. Koszty stałe firmy wynoszą 2,5 mln zł.",
             W("Który wyrób ma ujemną marżę pokrycia?",
               "Krzesła", "Szafy", "Stoły",
               why="1 − 1,1 = −0,1 mln zł."),
             W("Ile wynosi zysk operacyjny całej firmy?",
               "0,4 mln zł", "2,9 mln zł", "−0,1 mln zł",
               why="Marże: 2,4 + 0,6 − 0,1 = 2,9; minus 2,5 = 0,4 mln zł."),
             PF("Wycofanie krzeseł (przy stałych kosztach stałych) zwiększy zysk o 0,1 mln zł.", True,
                why="Zniknie ujemna marża pokrycia."),
          ),
          PR("Wskaźnik poziomu kosztów spółki wzrósł z 92% do 97%, choć przychody rosły o 10% rocznie. Analiza pokazała, że szybko rosły koszty wynagrodzeń i energii.",
             W("Co oznacza wzrost wskaźnika poziomu kosztów?",
               "Spadek rentowności – z każdej złotówki przychodu zostaje mniej zysku", "Poprawę efektywności", "Wzrost płynności",
               why="Rentowność ≈ 100% − wskaźnik poziomu kosztów."),
             W("Którą analizą najlepiej wykryć źródło wzrostu kosztów?",
               "Analizą kosztów w układzie rodzajowym", "Analizą rotacji należności", "Analizą Du Ponta kapitału własnego",
               why="Pokazuje, które rodzaje kosztów rosną."),
             PF("Przy wskaźniku 97% marża zysku przed opodatkowaniem wynosi ok. 3%.", True,
                why="100% − 97% = 3%."),
          ),
      ]),

    L(8, "Płynność w ujęciu dynamicznym i zdolność obsługi długu",
      "Odróżniać statyczną (bilansową) i dynamiczną (przepływową) analizę płynności, liczyć wskaźniki wydajności gotówkowej oraz oceniać zdolność obsługi zadłużenia wskaźnikiem pokrycia odsetek (TIE) i DSCR.",
      ["Wskaźniki wydajności gotówkowej (dynamiczna analiza płynności)", "Wskaźnik pokrycia odsetek (TIE)", "Wskaźniki obsługi zadłużenia – wzory", "Wskaźniki płynności", "Wskaźniki zadłużenia", "Rachunek przepływów pieniężnych (cash flow)"],
      [GNOW, GTIE, F165],
      explain=[
          K("Płynność statyczna i dynamiczna",
            "Wskaźniki bieżącej, szybkiej i gotówkowej płynności opisują stan z jednego dnia bilansowego. Analiza dynamiczna korzysta z rachunku przepływów pieniężnych – pokazuje, czy firma w ciągu roku generuje gotówkę z działalności operacyjnej wystarczającą na zobowiązania."),
          K("Wydajność gotówkowa",
            "Wydajność gotówkowa sprzedaży = przepływy operacyjne / przychody; aktywów = przepływy operacyjne / aktywa; jakość zysku = przepływy operacyjne / zysk netto. Zysk to kategoria memoriałowa – firma może wykazywać zysk, a nie mieć gotówki (np. gdy klienci płacą z opóźnieniem).",
            w="WGS = CFO / S"),
          W("Firma ma zysk netto 1 mln zł, a przepływy operacyjne −0,5 mln zł. Co to sygnalizuje?",
            "Zysk nie zamienia się w gotówkę – np. rosną należności lub zapasy", "Bardzo dobrą płynność", "Brak zadłużenia",
            why="Ujemne przepływy przy zysku to sygnał ostrzegawczy."),
          K("Pokrycie odsetek",
            "TIE = EBIT / odsetki – ile razy zysk operacyjny pokrywa odsetki. Wartość poniżej ok. 2–3 oznacza małą odporność na spadek zysku lub wzrost stóp. DSCR uwzględnia też raty kapitałowe: (zysk netto + amortyzacja + odsetki) / (raty + odsetki); banki wymagają zwykle DSCR powyżej 1.",
            w="TIE = EBIT / odsetki"),
          K("Zadłużenie a ryzyko",
            "Wskaźnik ogólnego zadłużenia (zobowiązania / aktywa) i zadłużenia kapitału własnego mówią, ile długu jest; TIE i DSCR – czy firma udźwignie jego obsługę. Analiza zadłużenia łączy obie perspektywy."),
          PF("Wysoki wskaźnik bieżącej płynności zawsze oznacza, że firma generuje dużo gotówki.", False,
             why="Może wynikać z zapasów i należności, które trudno zamienić na gotówkę."),
      ],
      mech=[
          KT("Statyczna czy dynamiczna analiza płynności?",
             {"Statyczna (bilans)": ["Wskaźnik bieżącej płynności", "Wskaźnik szybkiej płynności"],
              "Dynamiczna (przepływy)": ["Wydajność gotówkowa sprzedaży", "Pokrycie zobowiązań przepływami operacyjnymi"]},
             why="Różnią się źródłem danych."),
          LN("Ułóż przyczyny sytuacji „zysk jest, gotówki brak”.",
             ["Firma sprzedaje z długim terminem płatności", "Rosną należności", "Rośnie zysk w RZiS", "Przepływy operacyjne są niskie lub ujemne", "Firma ma problem z regulowaniem zobowiązań"],
             why="Zysk memoriałowy wyprzedza wpływy gotówki."),
          W("EBIT 2 mln zł, odsetki 1 mln zł. Jak ocenić TIE = 2?",
            "Niski zapas – niewielki spadek zysku zagrozi obsłudze odsetek", "Bardzo bezpieczny poziom", "Firma nie ma długu",
            why="Zysk pokrywa odsetki tylko dwukrotnie."),
          W("Czym DSCR różni się od TIE?",
            "Uwzględnia także raty kapitałowe", "Uwzględnia tylko zapasy", "Nie korzysta z zysku",
            why="Mierzy obsługę całego długu."),
          M("Które wskaźniki opierają się na przepływach pieniężnych?",
            ["Wydajność gotówkowa sprzedaży", "Wydajność gotówkowa aktywów", "Jakość zysku (CFO / zysk netto)", "Wskaźnik bieżącej płynności"], [0, 1, 2],
            why="Bieżąca płynność opiera się na bilansie."),
          PF("Wskaźnik jakości zysku powyżej 1 oznacza, że przepływy operacyjne przewyższają zysk netto.", True,
             why="Np. dzięki amortyzacji i spadkowi należności."),
      ],
      calc=[
          LB("Przepływy operacyjne 1,2 mln zł, przychody 15 mln zł. Ile wynosi wydajność gotówkowa sprzedaży (%)?",
             8, "1.2/15*100", ["1,2 / 15 = 8%"], unit="%"),
          LB("Aktywa 10 mln zł. Ile wynosi wydajność gotówkowa aktywów (%)?",
             12, "1.2/10*100", ["1,2 / 10 = 12%"], unit="%"),
          LB("Zysk netto 0,8 mln zł. Ile wynosi wskaźnik jakości zysku (CFO / zysk netto)?",
             1.5, "1.2/0.8", ["1,2 / 0,8 = 1,5"], unit=""),
          LB("EBIT 600 tys. zł, odsetki 150 tys. zł. Ile wynosi TIE?",
             4, "600/150", ["600 / 150 = 4"], unit=""),
          LB("Zysk netto 300, amortyzacja 200, odsetki 150, raty 350 (tys. zł). Ile wynosi DSCR?",
             1.3, "(300+200+150)/(350+150)", ["650 / 500 = 1,3"], unit=""),
          LB("Zobowiązania 6 mln zł, aktywa 10 mln zł. Ile wynosi wskaźnik ogólnego zadłużenia (%)?",
             60, "6/10*100", ["6 / 10 = 60%"], unit="%"),
      ],
      case=[
          PR("Spółka budowlana wykazuje zysk netto 5 mln zł i wskaźnik bieżącej płynności 2,1. Mimo to spóźnia się z płatnościami dla podwykonawców. Rachunek przepływów pokazuje przepływy operacyjne −3 mln zł, bo inwestor zalega z zapłatą za kontrakt.",
             W("Dlaczego wskaźnik bieżącej płynności nie ostrzegł przed problemem?",
               "Jest wysoki dzięki należnościom, które nie zostały spłacone", "Bo jest za niski", "Bo nie uwzględnia aktywów",
               why="Statyczny wskaźnik nie pokazuje, czy należności wpłyną."),
             W("Który wskaźnik lepiej oddaje sytuację?",
               "Wydajność gotówkowa i jakość zysku z rachunku przepływów", "Rentowność sprzedaży", "Mnożnik kapitałowy",
               why="Pokazują brak gotówki z działalności."),
             PF("To przykład, że zysk nie jest tym samym co gotówka.", True,
                why="Zysk memoriałowy wyprzedza wpływy."),
          ),
          PR("Firma ma kredyt inwestycyjny; bank w umowie zastrzegł, że DSCR nie może spaść poniżej 1,2. Po wzroście stóp procentowych odsetki wzrosły z 100 do 250 tys. zł, przy EBIT 600 tys. zł i ratach 300 tys. zł.",
             W("Ile wynosi TIE po wzroście odsetek?",
               "2,4", "6", "1,2",
               why="600 / 250 = 2,4."),
             W("Co grozi firmie, jeśli DSCR spadnie poniżej 1,2?",
               "Naruszenie kowenantu – bank może żądać dodatkowego zabezpieczenia lub wypowiedzieć kredyt", "Nic – to tylko informacja", "Automatyczne umorzenie kredytu",
               why="Kowenanty finansowe chronią bank."),
             PF("Wzrost stóp procentowych pogarsza wskaźniki obsługi długu przy zmiennym oprocentowaniu.", True,
                why="Rosną odsetki przy niezmienionym zysku."),
          ),
      ]),
]
