# -*- coding: utf-8 -*-
# Zrozumienie – Finanse przedsiębiorstw / Decyzje inwestycyjne i wycena
OSM = "https://openstax.org/books/principles-managerial-accounting/pages/"
OSF = "https://openstax.org/books/principles-financial-accounting/pages/"
D = "2026-10-08"
M111 = S("OpenStax, Principles of Accounting Vol. 2, 11.1 Capital Investment Decisions", OSM + "11-1-describe-capital-investment-decisions-and-how-they-are-applied", D)
M112 = S("OpenStax, Principles of Accounting Vol. 2, 11.2 Payback and Accounting Rate of Return", OSM + "11-2-evaluate-the-payback-and-accounting-rate-of-return-in-capital-investment-decisions", D)
M114 = S("OpenStax, Principles of Accounting Vol. 2, 11.4 Discounted Cash Flow Models", OSM + "11-4-use-discounted-cash-flow-models-to-make-capital-investment-decisions", D)
M115 = S("OpenStax, Principles of Accounting Vol. 2, 11.5 Non-Time-Value vs Time-Value Methods", OSM + "11-5-compare-and-contrast-non-time-value-based-methods-and-time-value-based-methods-in-capital-investment-decisions", D)
M123 = S("OpenStax, Principles of Accounting Vol. 2, 12.3 ROI, Residual Income and EVA", OSM + "12-3-evaluate-an-operating-segment-or-a-project-using-return-on-investment-residual-income-and-economic-value-added", D)
F145 = S("OpenStax, Principles of Accounting Vol. 1, 14.5 Earnings per Share", OSF + "14-5-discuss-the-applicability-of-earnings-per-share-as-a-method-to-measure-performance", D)
N1990 = S("Nobel Prize – The Prize in Economic Sciences 1990 (Markowitz, Miller, Sharpe)", "https://www.nobelprize.org/prizes/economic-sciences/1990/summary/", D)
N1985 = S("Nobel Prize – The Prize in Economic Sciences 1985 (Franco Modigliani)", "https://www.nobelprize.org/prizes/economic-sciences/1985/summary/", D)

LESSONS = [
    L(1, "Cel firmy: wartość dla właścicieli i EVA",
      "Rozumieć, dlaczego celem finansowym przedsiębiorstwa jest maksymalizacja jego wartości (a nie samego zysku), jak problem agencji wpływa na decyzje menedżerów i jak EVA mierzy tworzenie wartości.",
      ["Cel finansowy przedsiębiorstwa – maksymalizacja wartości", "EVA (ekonomiczna wartość dodana)"],
      [M123, M111],
      explain=[
          K("Wartość, a nie zysk",
            "Zysk księgowy jednego roku nie uwzględnia ryzyka, rozłożenia w czasie ani kosztu kapitału własnego. Wartość firmy to bieżąca wartość przyszłych przepływów pieniężnych zdyskontowanych kosztem kapitału – uwzględnia wszystkie te elementy. Dlatego w finansach przyjmuje się cel maksymalizacji wartości dla właścicieli, przy poszanowaniu prawa i interesów innych interesariuszy."),
          K("Problem agencji",
            "Menedżerowie (agenci) mogą działać we własnym interesie zamiast w interesie właścicieli (pryncypałów): budować „imperia”, unikać ryzyka, dbać o krótkoterminowe premie. Rozwiązania: wynagrodzenie zależne od wartości (opcje, akcje), rada nadzorcza, rynek przejęć, przejrzystość."),
          W("Menedżer odrzuca opłacalny, ale ryzykowny projekt, bo boi się utraty posady. Jak nazywamy to zjawisko?",
            "Problem agencji", "Efekt skali", "Dźwignia operacyjna",
            why="Interes menedżera różni się od interesu właścicieli."),
          K("EVA",
            "Ekonomiczna wartość dodana = NOPAT − WACC × zainwestowany kapitał, gdzie NOPAT to zysk operacyjny po podatku. EVA odejmuje koszt całego kapitału – także własnego, którego nie widać w RZiS. Dodatnia EVA oznacza, że firma zarabia więcej niż koszt kapitału, czyli tworzy wartość.",
            w="EVA = NOPAT − WACC · kapitał zainwestowany"),
          K("Zysk księgowy a ekonomiczny",
            "Firma może mieć zysk netto, a ujemną EVA – jeśli zwrot z kapitału jest niższy niż oczekiwania inwestorów. Odpowiada to rozróżnieniu z mikroekonomii: zysk księgowy vs zysk ekonomiczny (po uwzględnieniu kosztu alternatywnego kapitału)."),
          PF("Firma z dodatnim zyskiem netto zawsze tworzy wartość dla właścicieli.", False,
             why="Jeśli zwrot jest niższy od kosztu kapitału, EVA jest ujemna."),
      ],
      mech=[
          LN("Ułóż, jak EVA pokazuje tworzenie wartości.",
             ["Policz zysk operacyjny po podatku (NOPAT)", "Ustal zainwestowany kapitał", "Policz koszt kapitału: WACC × kapitał", "Odejmij koszt kapitału od NOPAT", "Dodatnia EVA – wartość tworzona, ujemna – niszczona"],
             why="EVA to „zysk ekonomiczny” firmy."),
          KT("Zgodne z maksymalizacją wartości czy nie?",
             {"Zgodne": ["Projekt z dodatnim NPV", "Sprzedaż zbędnego majątku obniżającego ROIC", "Wynagrodzenie zarządu w akcjach z długim okresem blokady"],
              "Niezgodne": ["Przejęcie drogiej spółki tylko dla wzrostu skali", "Cięcie badań, by poprawić zysk kwartalny", "Projekt o zwrocie niższym od WACC"]},
             why="Wartość rośnie, gdy zwrot przekracza koszt kapitału w długim okresie."),
          W("NOPAT 12 mln zł, kapitał 100 mln zł, WACC 10%. Ile wynosi EVA?",
            "Dodatnia, 2 mln zł", "12 mln zł", "Ujemna, 2 mln zł",
            why="12 − 10 = 2 mln zł."),
          W("Dlaczego cięcie wydatków na badania „poprawia” zysk w krótkim okresie, ale może obniżyć wartość?",
            "Zmniejsza przyszłe przepływy pieniężne", "Bo badania nie są kosztem", "Bo zwiększa WACC do zera",
            why="Wartość zależy od przyszłych przepływów, nie tylko bieżącego zysku."),
          M("Jakie mechanizmy ograniczają problem agencji?",
            ["Wynagrodzenie zależne od wartości akcji", "Nadzór rady nadzorczej", "Groźba przejęcia przez inną firmę", "Brak raportowania wyników"], [0, 1, 2],
            why="Brak informacji pogłębia problem agencji."),
          PF("EVA uwzględnia koszt kapitału własnego, którego nie pokazuje rachunek zysków i strat.", True,
             why="RZiS ujmuje tylko odsetki od długu."),
      ],
      calc=[
          LB("EBIT 20 mln zł, CIT 19%. Ile wynosi NOPAT (mln zł)?",
             16.2, "20*0.81", ["20 · 0,81 = 16,2 mln zł"], unit="mln zł", tol=0.01),
          LB("NOPAT 16,2 mln zł, kapitał 150 mln zł, WACC 9%. Ile wynosi EVA (mln zł)?",
             2.7, "16.2-0.09*150", ["Koszt kapitału 13,5", "16,2 − 13,5 = 2,7 mln zł"], unit="mln zł", tol=0.01),
          LB("ROIC = NOPAT / kapitał. Ile wynosi ROIC dla NOPAT 16,2 i kapitału 150 mln zł (%)?",
             10.8, "16.2/150*100", ["16,2 / 150 = 10,8%"], unit="%", tol=0.01),
          LB("EVA = (ROIC − WACC) · kapitał. ROIC 7%, WACC 9%, kapitał 200 mln zł. Ile wynosi EVA (mln zł)? (ujemna ze znakiem minus)",
             -4, "(0.07-0.09)*200", ["(−2%) · 200 = −4 mln zł"], unit="mln zł"),
          LB("Zysk netto 5 mln zł, kapitał własny 80 mln zł, koszt kapitału własnego 10%. Ile wynosi zysk rezydualny (mln zł)? (ujemny ze znakiem minus)",
             -3, "5-0.1*80", ["5 − 8 = −3 mln zł"], unit="mln zł"),
          LB("Firma oczekuje stałej EVA 2,7 mln zł rocznie w nieskończoność, WACC 9%. Ile wynosi wartość bieżąca przyszłych EVA (MVA, mln zł)?",
             30, "2.7/0.09", ["2,7 / 0,09 = 30 mln zł"], unit="mln zł"),
      ],
      case=[
          PR("Spółka X ma zysk netto 10 mln zł i kapitał własny 200 mln zł (bez długu). Akcjonariusze oczekują 9% rocznie. Zarząd chwali się „rekordowym zyskiem”.",
             W("Ile wynosi ROE?",
               "5%", "9%", "10%",
               why="10 / 200 = 5% – poniżej oczekiwań akcjonariuszy."),
             W("Czy spółka tworzy wartość dla akcjonariuszy?",
               "Nie – ROE 5% jest poniżej oczekiwanych 9%", "Tak, bo ma zysk", "Nie da się ocenić",
               why="Zysk rezydualny: 10 − 18 = −8 mln zł."),
             PF("Akcjonariusze mogliby osiągnąć więcej, inwestując w inne spółki o podobnym ryzyku.", True,
                why="To definicja kosztu alternatywnego kapitału."),
          ),
          PR("Zarząd ma premię zależną od wzrostu przychodów. Proponuje przejęcie konkurenta, które zwiększy przychody o 40%, ale za cenę, przy której zwrot z inwestycji wyniesie 5% przy WACC 9%.",
             W("Jak przejęcie wpłynie na wartość dla akcjonariuszy?",
               "Obniży ją – zwrot poniżej kosztu kapitału", "Zwiększy ją, bo rosną przychody", "Nie wpłynie",
               why="Wzrost skali bez nadwyżki nad WACC niszczy wartość."),
             W("Jaki problem ilustruje system premii zarządu?",
               "Problem agencji – zarząd jest nagradzany za wzrost, a nie za wartość", "Problem płynności", "Efekt Fishera",
               why="Cele menedżerów rozmijają się z celami właścicieli."),
             PF("Powiązanie premii z EVA lub długoterminowym kursem akcji ograniczyłoby ten problem.", True,
                why="Menedżer zyskuje wtedy na tworzeniu wartości."),
          ),
      ]),

    L(2, "Ocena projektów: okres zwrotu, ARR i NPV",
      "Liczyć prosty i zdyskontowany okres zwrotu, księgową stopę zwrotu i wartość bieżącą netto (NPV) oraz rozumieć, dlaczego metody dyskontowe są lepsze od prostych.",
      ["Okres zwrotu", "Wartość bieżąca netto (NPV)", "Ocena projektów inwestycyjnych – metody"],
      [M112, M114, M115],
      explain=[
          K("Metody proste",
            "Okres zwrotu: po ilu latach suma wpływów pokryje nakład. Prosta, intuicyjna, mierzy płynność projektu, ale pomija wartość pieniądza w czasie i przepływy po okresie zwrotu. Księgowa stopa zwrotu (ARR) = średni zysk księgowy / średni (lub początkowy) nakład – opiera się na zysku, a nie gotówce."),
          K("NPV",
            "Wartość bieżąca netto = suma zdyskontowanych przepływów − nakład początkowy. Stopa dyskontowa to koszt kapitału (np. WACC) skorygowany o ryzyko projektu. NPV > 0 – projekt zwiększa wartość firmy o tę kwotę; NPV < 0 – ją obniża. Przy projektach wykluczających się wybiera się wyższe NPV.",
            w="NPV = Σ CFₜ / (1 + r)ᵗ − I₀"),
          W("Nakład 100 000 zł, za rok wpływ 115 000 zł, stopa 10%. Ile wynosi NPV?",
            "Dodatnia, ok. 4 545 zł", "15 000 zł", "Ujemna, ok. 4 545 zł",
            why="115 000 / 1,1 − 100 000 ≈ 4 545 zł."),
          K("Zdyskontowany okres zwrotu",
            "Liczony jak prosty, ale na przepływach zdyskontowanych – uwzględnia wartość pieniądza w czasie, ale nadal pomija przepływy po okresie zwrotu. Jest zawsze dłuższy niż prosty okres zwrotu (przy dodatniej stopie)."),
          K("Przepływy, nie zysk",
            "Do oceny projektu bierze się przyrostowe przepływy pieniężne: nakład inwestycyjny, wpływy operacyjne po podatku (zysk + amortyzacja), zmiany kapitału obrotowego, wartość rezydualną. Pomija się koszty utopione, uwzględnia koszty alternatywne (np. wartość posiadanej działki, którą projekt zajmie)."),
          PF("NPV uwzględnia wszystkie przepływy projektu i wartość pieniądza w czasie.", True,
             why="Dyskontuje każdy przepływ przez cały okres życia projektu."),
      ],
      mech=[
          LN("Ułóż kroki oceny projektu metodą NPV.",
             ["Oszacuj nakład początkowy", "Prognozuj przyrostowe przepływy pieniężne w kolejnych latach", "Ustal stopę dyskontową (koszt kapitału z premią za ryzyko)", "Zdyskontuj przepływy i odejmij nakład", "Przyjmij projekt, jeśli NPV > 0"],
             why="NPV mierzy przyrost wartości firmy."),
          KT("Zaleta czy wada okresu zwrotu?",
             {"Zaleta": ["Prostota i intuicyjność", "Informacja o ryzyku płynności"],
              "Wada": ["Pomija wartość pieniądza w czasie", "Ignoruje przepływy po okresie zwrotu", "Nie mówi, czy projekt tworzy wartość"]},
             why="Okres zwrotu to miara pomocnicza, nie główne kryterium."),
          W("Wzrasta stopa dyskontowa. Co dzieje się z NPV projektu z dodatnimi przepływami w przyszłości?",
            "Spada", "Rośnie", "Nie zmienia się",
            why="Przyszłe przepływy są warte mniej dzisiaj."),
          W("Projekt A ma okres zwrotu 2 lata i NPV 10 000 zł; B – 4 lata i NPV 80 000 zł. Wykluczają się. Który wybrać (przy dostępnym finansowaniu)?",
            "B – wyższe NPV", "A – krótszy okres zwrotu", "Żaden",
            why="Kryterium nadrzędnym jest przyrost wartości."),
          M("Co należy uwzględnić w przepływach projektu?",
            ["Nakład na maszyny", "Wzrost kapitału obrotowego (zapasy)", "Koszt alternatywny wykorzystanej działki", "Koszty badań rynku poniesione w zeszłym roku"], [0, 1, 2],
            why="Koszty już poniesione są utopione."),
          PF("Projekt o NPV = 0 zwraca dokładnie koszt kapitału.", True,
             why="Ani nie tworzy, ani nie niszczy wartości."),
      ],
      calc=[
          LB("Nakład 120 000 zł, wpływy 40 000 zł rocznie. Ile wynosi prosty okres zwrotu (lata)?",
             3, "120000/40000", ["120 000 / 40 000 = 3 lata"], unit="lata"),
          LB("Nakład 100 000 zł, wpływy: 30 000, 40 000, 50 000 zł. Ile wynosi okres zwrotu (lata, z ułamkiem)?",
             2.6, "2+30000/50000", ["Po 2 latach odzyskano 70 000", "Brakuje 30 000 z 50 000 → 0,6 roku", "2,6 roku"], unit="lata", tol=0.01),
          LB("Nakład 100 000 zł, wpływy 40 000 zł przez 3 lata, stopa 8%. Ile wynosi NPV (zł)?",
             3083.88, "40000*(1-1.08**-3)/0.08-100000", ["PV wpływów ≈ 103 083,88", "NPV ≈ 3 083,88 zł"], unit="zł", tol=0.01),
          LB("Ten sam projekt przy stopie 12%. Ile wynosi NPV (zł)? (ujemne ze znakiem minus)",
             -3926.75, "40000*(1-1.12**-3)/0.12-100000", ["PV wpływów ≈ 96 073,25", "NPV ≈ −3 926,75 zł"], unit="zł", tol=0.01),
          LB("Średni zysk księgowy 18 000 zł, nakład 120 000 zł. Ile wynosi ARR liczony od nakładu początkowego (%)?",
             15, "18000/120000*100", ["18 000 / 120 000 = 15%"], unit="%"),
          LB("Zdyskontowany wpływ za 1. rok: 50 000 zł przy 10%. Ile wynosi (zł)?",
             45454.55, "50000/1.1", ["50 000 / 1,1 ≈ 45 454,55 zł"], unit="zł", tol=0.01),
      ],
      case=[
          PR("Piekarnia rozważa zakup pieca za 200 000 zł. Wpływy netto: 60 000 zł rocznie przez 5 lat, wartość końcowa pieca 0. Koszt kapitału 10%. W zeszłym roku wydała 8 000 zł na analizę rynku.",
             W("Czy 8 000 zł za analizę uwzględnić w NPV?",
               "Nie – to koszt utopiony", "Tak – jako nakład", "Tak – jako wpływ",
               why="Wydatek już poniesiony nie zależy od decyzji."),
             W("Ile wynosi NPV (w przybliżeniu)?",
               "Dodatnia, ok. 27 450 zł", "100 000 zł", "Ujemna, ok. 27 450 zł",
               why="60 000 · 3,7908 − 200 000 ≈ 27 447 zł."),
             W("Ile wynosi prosty okres zwrotu?",
               "3,33 roku", "5 lat", "2 lata",
               why="200 000 / 60 000 ≈ 3,33."),
             PF("Projekt należy przyjąć, bo zwiększa wartość firmy.", True,
                why="NPV > 0 – projekt zwiększa wartość firmy."),
          ),
          PR("Gmina planuje farmę fotowoltaiczną: nakład 4 mln zł, wpływy 500 000 zł rocznie przez 20 lat. Stopa dyskontowa 6%.",
             W("Po ilu latach zwróci się nakład na farmę (bez dyskontowania)?",
               "8 lat", "20 lat", "4 lata",
               why="4 000 000 / 500 000 = 8 lat."),
             W("Ile wynosi NPV farmy przy stopie 6%?",
               "Dodatnia, ok. 1,73 mln zł", "6 mln zł", "Ujemna, ok. 1,73 mln zł",
               why="500 000 · 11,4699 − 4 000 000 ≈ 1,73 mln zł."),
             PF("Długi okres zwrotu nie przesądza o nieopłacalności, jeśli projekt działa długo i ma dodatnie NPV.", True,
                why="Okres zwrotu pomija przepływy po zwrocie nakładu."),
          ),
      ]),

    L(3, "Wewnętrzna stopa zwrotu (IRR) i MIRR",
      "Rozumieć IRR jako stopę, przy której NPV = 0, porównywać ją z kosztem kapitału, znać pułapki IRR (projekty wykluczające się, nietypowe przepływy) i liczyć zmodyfikowaną stopę MIRR.",
      ["Wewnętrzna stopa zwrotu (IRR) i MIRR", "Wartość bieżąca netto (NPV)", "Ocena projektów inwestycyjnych – metody"],
      [M114, M115],
      explain=[
          K("Czym jest IRR",
            "Wewnętrzna stopa zwrotu to stopa dyskontowa, przy której NPV projektu wynosi zero. Projekt przyjmuje się, gdy IRR > koszt kapitału. Np. nakład 1 000 zł i wpływ 1 100 zł za rok: IRR = 10%. Dla wielu okresów IRR wyznacza się iteracyjnie (arkusz kalkulacyjny).",
            w="0 = Σ CFₜ / (1 + IRR)ᵗ − I₀"),
          K("NPV a IRR",
            "Dla pojedynczego, typowego projektu (najpierw nakład, potem wpływy) obie metody dają tę samą decyzję. Przy projektach wykluczających się mogą wskazać różne: mały projekt o wysokim IRR może mieć niższe NPV niż duży o niższym IRR. Wtedy decyduje NPV, bo mierzy przyrost wartości w złotych."),
          W("Projekt ma IRR 14%, koszt kapitału firmy 10%. Co to oznacza?",
            "NPV jest dodatnie – projekt warto przyjąć", "NPV jest ujemne", "Projekt na pewno ma okres zwrotu 1 rok",
            why="Przy stopie 10% < IRR projekt daje dodatnie NPV."),
          K("Pułapki IRR",
            "IRR zakłada reinwestowanie przepływów po stopie IRR (często nierealistyczne przy wysokim IRR). Przy przepływach zmieniających znak kilka razy (np. duży koszt likwidacji na końcu) może być kilka IRR albo żadnej. IRR nie uwzględnia skali projektu."),
          K("MIRR",
            "Zmodyfikowana wewnętrzna stopa zwrotu zakłada reinwestowanie wpływów po koszcie kapitału: MIRR = (FV wpływów / PV nakładów)^(1/n) − 1. Usuwa problem wielu IRR i daje bardziej realistyczną miarę.",
            w="MIRR = (FV wpływów przy k / PV nakładów)^(1/n) − 1"),
          PF("Wyższe IRR zawsze oznacza lepszy wybór spośród projektów wykluczających się.", False,
             why="Przy różnej skali lepszy jest projekt o wyższym NPV."),
      ],
      mech=[
          LN("Ułóż logikę szukania IRR metodą prób.",
             ["Policz NPV przy pewnej stopie, np. 10%", "Jeśli NPV > 0, zwiększ stopę", "Jeśli NPV < 0, zmniejsz stopę", "Zawężaj przedział, aż NPV będzie bliskie zera", "Stopa, przy której NPV ≈ 0, to IRR"],
             why="NPV maleje wraz ze wzrostem stopy dyskontowej."),
          KT("Która metoda lepiej odpowiada na pytanie?",
             {"NPV": ["Ile wartości w złotych doda projekt?", "Który z dwóch wykluczających się projektów wybrać?"],
              "IRR": ["Jaka jest „rentowność” projektu w procentach?", "Jaki maksymalny koszt kapitału zniesie projekt?"],
              "MIRR": ["Jaka jest stopa zwrotu przy realistycznym reinwestowaniu przepływów?"]},
             why="Metody się uzupełniają, ale przy konflikcie decyduje NPV."),
          W("Dlaczego IRR projektu o bardzo wysokiej stopie może przeceniać jego atrakcyjność?",
            "Zakłada reinwestowanie wpływów po tej wysokiej stopie", "Bo pomija nakład", "Bo zakłada stopę zero",
            why="Realnie wpływy reinwestuje się raczej po koszcie kapitału."),
          W("Projekt: nakład, wpływy, a na końcu duży koszt rekultywacji terenu. Jaki problem może wystąpić z IRR?",
            "Kilka różnych wartości IRR", "IRR zawsze równa zero", "Brak problemu",
            why="Przepływy zmieniają znak więcej niż raz."),
          M("Kiedy NPV i IRR mogą dać różne rankingi projektów?",
            ["Gdy projekty mają różną skalę nakładów", "Gdy przepływy rozkładają się różnie w czasie", "Gdy projekty się wykluczają", "Gdy oceniamy jeden niezależny, typowy projekt"], [0, 1, 2],
            why="Dla jednego typowego projektu decyzja jest zgodna."),
          PF("MIRR zakłada reinwestowanie przepływów po koszcie kapitału.", True,
             why="To główna różnica względem IRR."),
      ],
      calc=[
          LB("Nakład 1 000 zł, wpływ za rok 1 120 zł. Ile wynosi IRR (%)?",
             12, "(1120/1000-1)*100", ["1 120 / 1 000 − 1 = 12%"], unit="%"),
          LB("Nakład 1 000 zł, wpływ po 2 latach 1 210 zł (brak przepływów w 1. roku). Ile wynosi IRR (%)?",
             10, "((1210/1000)**0.5-1)*100", ["(1,21)^(1/2) − 1 = 10%"], unit="%", tol=0.01),
          LB("Nakład 10 000 zł, wpływy po 6 000 zł w 1. i 2. roku. Ile wynosi NPV przy 13% (zł)?",
             8.61, "6000/1.13+6000/1.13**2-10000", ["5 309,73 + 4 698,88 − 10 000 ≈ 8,61 zł"], unit="zł", tol=0.01),
          LB("Ten sam projekt przy 14%. Ile wynosi NPV (zł)? (ujemne ze znakiem minus)",
             -120.04, "6000/1.14+6000/1.14**2-10000", ["5 263,16 + 4 616,81 − 10 000 ≈ −120,04 zł", "IRR leży więc między 13% a 14%"], unit="zł", tol=0.01),
          LB("Projekt: nakład 10 000 zł, wpływy 3 000, 4 000, 5 000 zł; koszt kapitału 10%. Ile wynosi wartość przyszła wpływów na koniec 3. roku (zł)?",
             13030, "3000*1.1**2+4000*1.1+5000", ["3 000 · 1,21 + 4 000 · 1,1 + 5 000 = 3 630 + 4 400 + 5 000"], unit="zł", tol=0.01),
          LB("Ile wynosi MIRR tego projektu (%)?",
             9.22, "((13030/10000)**(1/3)-1)*100", ["(13 030 / 10 000)^(1/3) − 1 ≈ 9,22%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Firma ma 5 000 zł i może wybrać jeden z projektów (koszt kapitału 10%): A – nakład 1 000 zł, wpływ za rok 1 300 zł (IRR 30%); B – nakład 5 000 zł, wpływ za rok 6 000 zł (IRR 20%). Niewykorzystane środki zarobią tylko koszt kapitału.",
             W("Ile wynosi NPV projektu A (w przybliżeniu)?",
               "182 zł", "300 zł", "455 zł",
               why="1 300 / 1,1 − 1 000 ≈ 181,82 zł."),
             W("Ile wynosi NPV projektu B (w przybliżeniu)?",
               "455 zł", "182 zł", "1 000 zł",
               why="6 000 / 1,1 − 5 000 ≈ 454,55 zł."),
             W("Który projekt wybrać?",
               "B – wyższe NPV, mimo niższego IRR", "A – wyższe IRR", "Żaden",
               why="Przy projektach wykluczających się decyduje NPV."),
          ),
          PR("Projekt o nakładzie 10 000 zł daje wpływy 3 000, 4 000 i 5 000 zł. Jego IRR wynosi ok. 8,9%, a MIRR przy koszcie kapitału 10% – ok. 9,2%. Koszt kapitału firmy to 10%.",
             W("Czy projekt należy przyjąć?",
               "Nie – IRR i MIRR są poniżej kosztu kapitału, więc NPV < 0", "Tak – IRR jest dodatnie", "Tak – MIRR jest wyższe od IRR",
               why="Zwrot nie pokrywa kosztu kapitału."),
             W("Dlaczego MIRR jest tu wyższa od IRR?",
               "Zakłada reinwestowanie po 10%, czyli wyżej niż IRR 8,9%", "Bo pomija nakład", "Bo nie dyskontuje przepływów",
               why="MIRR przyjmuje stopę reinwestycji równą kosztowi kapitału."),
             PF("Dla tego projektu NPV przy 10% jest ujemne.", True,
                why="IRR < 10% oznacza NPV < 0 przy tej stopie."),
          ),
      ]),

    L(4, "Struktura kapitału: dług czy kapitał własny",
      "Rozumieć twierdzenia Modiglianiego–Millera, teorię kompromisową (tarcza podatkowa vs koszty trudności finansowych) i teorię hierarchii źródeł finansowania oraz oceniać, ile długu powinna mieć firma.",
      ["Struktura kapitału i teorie jej wyboru"],
      [N1985, N1990],
      explain=[
          K("Modigliani–Miller (1958)",
            "W świecie bez podatków, kosztów bankructwa i asymetrii informacji wartość firmy nie zależy od struktury kapitału: dodanie taniego długu podnosi ryzyko i koszt kapitału własnego dokładnie tak, że WACC się nie zmienia. To punkt odniesienia – pokazuje, że struktura kapitału ma znaczenie tylko przez „niedoskonałości” rynku. Modigliani dostał Nobla w 1985 r., Miller w 1990 r."),
          K("Podatki i koszty trudności finansowych",
            "Z podatkiem (MM 1963) dług zwiększa wartość o wartość tarczy podatkowej (≈ T × D przy stałym długu). Ale wysokie zadłużenie rodzi koszty trudności finansowych: ryzyko bankructwa, utratę klientów i dostawców, ograniczenie inwestycji. Teoria kompromisowa: optymalny dług wyrównuje korzyść z tarczy i krańcowe koszty trudności.",
            w="V_L = V_U + T · D − PV(kosztów trudności finansowych)"),
          W("Według MM z podatkami, firma z długiem 100 mln zł przy CIT 19% jest warta więcej od identycznej bez długu o:",
            "19 mln zł", "100 mln zł", "81 mln zł",
            why="Wartość tarczy podatkowej ≈ T · D = 19 mln zł."),
          K("Teoria hierarchii (Myers, Majluf 1984)",
            "Menedżerowie wiedzą więcej niż inwestorzy. Emisja akcji bywa odbierana jako sygnał, że akcje są przewartościowane, więc kurs spada. Dlatego firmy finansują się najpierw zyskiem zatrzymanym, potem długiem, a emisję akcji traktują jako ostateczność."),
          K("W praktyce",
            "Firmy o stabilnych przepływach i majątku nadającym się na zabezpieczenie (energetyka, nieruchomości) mają więcej długu. Firmy technologiczne o niepewnych przepływach i majątku niematerialnym – mniej. Banki patrzą na dług netto / EBITDA i pokrycie odsetek."),
          PF("Według teorii hierarchii firmy najchętniej finansują się zyskiem zatrzymanym.", True,
             why="Nie wymaga to zewnętrznych inwestorów ani sygnałów rynkowych."),
      ],
      mech=[
          LN("Ułóż logikę teorii kompromisowej.",
             ["Firma zwiększa udział długu", "Rośnie tarcza podatkowa i wartość firmy", "Rośnie też ryzyko trudności finansowych", "Krańcowe koszty trudności zaczynają przewyższać krańcową korzyść z tarczy", "Optimum leży tam, gdzie te efekty się równoważą"],
             why="Za mało długu – tracimy tarczę; za dużo – ryzyko bankructwa."),
          KT("Która firma będzie raczej miała więcej, a która mniej długu?",
             {"Więcej długu": ["Operator sieci energetycznej o stabilnych przychodach", "Spółka wynajmująca biurowce"],
              "Mniej długu": ["Start-up biotechnologiczny", "Producent gier o niepewnych przychodach", "Firma programistyczna bez majątku trwałego"]},
             why="Stabilność przepływów i zabezpieczenia sprzyjają zadłużeniu."),
          W("Spółka ogłasza dużą emisję nowych akcji. Kurs spada. Jak tłumaczy to teoria hierarchii?",
            "Rynek odczytuje emisję jako sygnał, że akcje są przewartościowane", "Bo emisja zawsze zwiększa wartość", "Bo dług jest droższy od akcji",
            why="Asymetria informacji – menedżerowie emitują, gdy akcje są drogie."),
          W("W świecie MM bez podatków firma zastępuje część kapitału własnego długiem. Co dzieje się z kosztem kapitału własnego?",
            "Rośnie, bo rośnie ryzyko akcjonariuszy", "Spada", "Nie zmienia się",
            why="Wzrost kosztu kapitału własnego równoważy tańszy dług."),
          M("Co należy do kosztów trudności finansowych?",
            ["Koszty prawne upadłości", "Utrata klientów obawiających się o gwarancje", "Rezygnacja z opłacalnych inwestycji", "Tarcza podatkowa"], [0, 1, 2],
            why="Tarcza podatkowa to korzyść z długu."),
          PF("Według MM bez podatków wartość firmy nie zależy od struktury kapitału.", True,
             why="To pierwsze twierdzenie Modiglianiego–Millera."),
      ],
      calc=[
          LB("Wartość firmy bez długu 500 mln zł. Dług 200 mln zł, CIT 19%. Ile wynosi wartość firmy według MM z podatkami (mln zł)?",
             538, "500+0.19*200", ["Tarcza 0,19 · 200 = 38", "500 + 38 = 538 mln zł"], unit="mln zł"),
          LB("Roczne odsetki 8% od 200 mln zł, CIT 19%. Ile wynosi roczna tarcza podatkowa (mln zł)?",
             3.04, "200*0.08*0.19", ["16 · 0,19 = 3,04 mln zł"], unit="mln zł", tol=0.01),
          LB("MM II (bez podatków): r_A = 10%, r_D = 6%, D/E = 1. Ile wynosi koszt kapitału własnego (%)? Wzór: r_E = r_A + (r_A − r_D) · D/E",
             14, "10+(10-6)*1", ["10 + 4 · 1 = 14%"], unit="%"),
          LB("Ten sam przykład, D/E = 0,5. Ile wynosi r_E (%)?",
             12, "10+(10-6)*0.5", ["10 + 4 · 0,5 = 12%"], unit="%"),
          LB("Sprawdź WACC (bez podatków) dla D/E = 1: połowa długu 6%, połowa kapitału 14%. Ile wynosi (%)?",
             10, "0.5*6+0.5*14", ["3 + 7 = 10% – niezmieniony, jak przewiduje MM"], unit="%"),
          LB("Wartość bieżąca oczekiwanych kosztów trudności finansowych 25 mln zł, tarcza 38 mln zł. O ile dług zwiększa wartość netto (mln zł)?",
             13, "38-25", ["38 − 25 = 13 mln zł"], unit="mln zł"),
      ],
      case=[
          PR("Spółka technologiczna z dużą gotówką i bez długu rozważa wyemitowanie obligacji za 300 mln zł i wypłatę tej kwoty akcjonariuszom (skup akcji). CIT 19%. Przepływy spółki są bardzo zmienne.",
             W("Jaka jest główna korzyść z długu według teorii kompromisowej?",
               "Tarcza podatkowa", "Niższe ryzyko", "Wyższe przychody",
               why="Odsetki obniżają podatek."),
             W("Jakie ryzyko należy rozważyć przy zmiennych przepływach?",
               "Koszty trudności finansowych przy spadku przychodów", "Spadek inflacji", "Brak rachunku bankowego",
               why="Zmienne przepływy utrudniają obsługę stałych odsetek."),
             PF("Dla firmy o zmiennych przepływach optymalny poziom długu jest zwykle niższy niż dla firmy stabilnej.", True,
                why="Ryzyko trudności finansowych jest większe."),
          ),
          PR("Spółka dystrybucyjna potrzebuje 50 mln zł na nowe magazyny. Ma 20 mln zł zysku zatrzymanego, bank oferuje kredyt, a doradca proponuje emisję akcji.",
             W("Od czego według teorii hierarchii zacznie finansowanie?",
               "Od zysku zatrzymanego", "Od emisji akcji", "Od sprzedaży magazynów",
               why="Źródło wewnętrzne nie wymaga sygnałów dla rynku."),
             W("Czym uzupełni brakujące 30 mln zł?",
               "Kredytem bankowym", "Emisją akcji jako pierwszym wyborem", "Niczym",
               why="Dług jest kolejny w hierarchii przed akcjami."),
             PF("Emisja akcji byłaby według tej teorii ostatecznością.", True,
                why="Emisja może zostać odebrana jako sygnał przewartościowania."),
          ),
      ]),

    L(5, "Wycena przedsiębiorstwa",
      "Porównywać metody wyceny – majątkowe, dochodowe (DCF, model Gordona) i porównawcze (mnożniki) – oraz liczyć wartość firmy i kapitału własnego w prostych przykładach.",
      ["Wycena przedsiębiorstwa – metody", "Model Gordona (wycena akcji)", "Cel finansowy przedsiębiorstwa – maksymalizacja wartości"],
      [M114, F145],
      explain=[
          K("Metody majątkowe",
            "Wartość = aktywa − zobowiązania, w różnych ujęciach: księgowa (z bilansu), skorygowana (po przeszacowaniu do wartości rynkowych), odtworzeniowa (ile kosztowałoby odtworzenie majątku), likwidacyjna (ile uzyska się ze sprzedaży majątku po spłacie długów). Dobre dla firm majątkowych lub w likwidacji; pomijają zdolność do generowania zysków."),
          K("Metody dochodowe – DCF",
            "Wartość przedsiębiorstwa (EV) = suma zdyskontowanych wolnych przepływów pieniężnych (FCF) w okresie prognozy + zdyskontowana wartość rezydualna. Stopa dyskontowa – WACC. Wartość rezydualną często liczy się modelem stałego wzrostu: TV = FCF_{n+1} / (WACC − g). Wartość kapitału własnego = EV − dług netto.",
            w="EV = Σ FCFₜ/(1+WACC)ᵗ + TV/(1+WACC)ⁿ;  TV = FCF_{n+1}/(WACC − g)"),
          W("Wartość przedsiębiorstwa 500 mln zł, dług netto 120 mln zł. Ile jest wart kapitał własny?",
            "380 mln zł", "620 mln zł", "500 mln zł",
            why="500 − 120 = 380 mln zł."),
          K("Model Gordona i mnożniki",
            "Dla spółek wypłacających stabilnie rosnącą dywidendę: P = D₁ / (k_e − g). Metody porównawcze wyceniają spółkę przez mnożniki podobnych firm lub transakcji: P/E, EV/EBITDA, P/BV. Szybkie i rynkowe, ale zależą od doboru porównywalnych spółek i nastrojów rynku.",
            w="EV = mnożnik EV/EBITDA · EBITDA"),
          K("Która metoda kiedy",
            "Startup bez zysków – DCF lub wycena porównawcza z transakcji. Spółka dywidendowa – Gordon. Holding nieruchomości – majątkowa skorygowana. W praktyce stosuje się kilka metod i porównuje wyniki; różnice zmuszają do sprawdzenia założeń."),
          PF("Wartość rezydualna często stanowi największą część wyceny DCF.", True,
             why="Obejmuje wszystkie przepływy po okresie szczegółowej prognozy."),
      ],
      mech=[
          KT("Która metoda wyceny?",
             {"Majątkowa": ["Wartość aktywów netto po przeszacowaniu nieruchomości", "Wartość likwidacyjna upadającej fabryki"],
              "Dochodowa": ["Zdyskontowane wolne przepływy pieniężne", "Model Gordona dla spółki dywidendowej"],
              "Porównawcza": ["Mnożnik EV/EBITDA podobnych spółek giełdowych", "P/E z niedawnych transakcji w branży"]},
             why="Metody różnią się podstawą wyceny: majątek, dochód lub rynek."),
          LN("Ułóż kroki wyceny DCF.",
             ["Prognozuj wolne przepływy pieniężne na kilka lat", "Ustal WACC jako stopę dyskontową", "Policz wartość rezydualną po okresie prognozy", "Zdyskontuj przepływy i wartość rezydualną, by otrzymać EV", "Odejmij dług netto, by otrzymać wartość kapitału własnego"],
             why="DCF wycenia całe przedsiębiorstwo, a potem kapitał właścicieli."),
          W("W modelu DCF zakładane długoterminowe tempo wzrostu g rośnie z 2% do 3% przy WACC 8%. Co z wartością rezydualną?",
            "Rośnie wyraźnie", "Spada", "Nie zmienia się",
            why="Mianownik WACC − g maleje z 6% do 5%."),
          W("Dlaczego wycena majątkowa może zaniżać wartość firmy programistycznej?",
            "Główną wartością są ludzie, klienci i oprogramowanie, których nie ma w bilansie", "Bo firma ma za dużo maszyn", "Bo wycena majątkowa zawsze zawyża wartość",
            why="Wartości niematerialne tworzone wewnętrznie często nie są ujmowane w bilansie."),
          M("Jakie są słabości wyceny porównawczej?",
            ["Trudność w znalezieniu naprawdę podobnych spółek", "Wpływ nastrojów rynkowych na mnożniki", "Różnice w księgowości między spółkami", "Konieczność prognozowania przepływów na 10 lat"], [0, 1, 2],
            why="Prognoza przepływów to cecha metod dochodowych."),
          PF("Wartość kapitału własnego = wartość przedsiębiorstwa (EV) − dług netto.", True,
             why="Dług netto należy się wierzycielom."),
      ],
      calc=[
          LB("FCF w 3. roku 12 mln zł, g = 2%, WACC 9%. Ile wynosi wartość rezydualna na koniec 3. roku (mln zł)?",
             174.86, "12*1.02/(0.09-0.02)", ["FCF₄ = 12,24", "12,24 / 0,07 ≈ 174,86 mln zł"], unit="mln zł", tol=0.01),
          LB("FCF: 10, 11, 12 mln zł; TV 174,86 mln zł na koniec 3. roku; WACC 9%. Ile wynosi EV (mln zł)?",
             162.72, "10/1.09+11/1.09**2+(12+12*1.02/0.07)/1.09**3", ["9,17 + 9,26 + 144,29 ≈ 162,72 mln zł"], unit="mln zł", tol=0.01),
          LB("Dług netto 40 mln zł. Ile jest wart kapitał własny (mln zł)?",
             122.72, "162.72-40", ["162,72 − 40 = 122,72 mln zł"], unit="mln zł", tol=0.01),
          LB("D₀ = 2,50 zł, g = 4%, k_e = 10%. Ile wynosi wartość akcji (zł)?",
             43.33, "2.5*1.04/(0.1-0.04)", ["D₁ = 2,60", "2,60 / 0,06 ≈ 43,33 zł"], unit="zł", tol=0.01),
          LB("EBITDA 25 mln zł, mnożnik EV/EBITDA dla branży 8. Ile wynosi EV (mln zł)?",
             200, "8*25", ["8 · 25 = 200 mln zł"], unit="mln zł"),
          LB("Aktywa po przeszacowaniu 90 mln zł, zobowiązania 35 mln zł. Ile wynosi wartość skorygowanych aktywów netto (mln zł)?",
             55, "90-35", ["90 − 35 = 55 mln zł"], unit="mln zł"),
      ],
      case=[
          PR("Fundusz chce kupić rodzinną spółkę produkcyjną. Dane: EBITDA 20 mln zł, dług netto 30 mln zł, aktywa netto po przeszacowaniu 70 mln zł. Podobne spółki notowane są przy EV/EBITDA 7, a wycena DCF daje EV 150 mln zł.",
             W("Ile wynosi wartość kapitału własnego metodą porównawczą?",
               "110 mln zł", "140 mln zł", "70 mln zł",
               why="EV = 7 · 20 = 140; 140 − 30 = 110 mln zł."),
             W("Ile wynosi według DCF?",
               "120 mln zł", "150 mln zł", "180 mln zł",
               why="150 − 30 = 120 mln zł."),
             W("Dlaczego wycena majątkowa (70 mln zł) jest niższa od dochodowych?",
               "Spółka generuje zyski przewyższające zwrot z samego majątku – ma wartość niematerialną (klienci, know-how)", "Bo majątek jest przeszacowany", "Bo DCF zawsze daje błędny wynik",
               why="Różnica to w przybliżeniu wartość firmy (goodwill)."),
          ),
          PR("Analityk wycenia spółkę modelem Gordona: D₁ = 4 zł, k_e = 9%. Dla g = 3% wychodzi 66,67 zł, a dla g = 5% – 100 zł.",
             W("Co pokazuje ten przykład?",
               "Wycena jest bardzo wrażliwa na założenie o tempie wzrostu", "Model nie zależy od g", "Model zawsze daje 100 zł",
               why="Zmiana g o 2 pkt proc. zmieniła wycenę o 50%."),
             W("Jak analityk powinien przedstawić wynik?",
               "Jako przedział wartości z analizą wrażliwości", "Jako jedną liczbę bez komentarza", "Jako średnią z obu bez uzasadnienia",
               why="Analiza wrażliwości pokazuje niepewność założeń."),
             PF("Długoterminowe g nie powinno przekraczać długoterminowego wzrostu gospodarki.", True,
                why="Żadna firma nie może rosnąć szybciej od gospodarki w nieskończoność."),
          ),
      ]),
]
