# -*- coding: utf-8 -*-
# Zrozumienie – Makroekonomia / Cykl koniunkturalny
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S213 = S("OpenStax, Principles of Economics 3e, 21.3 What Causes Changes in Unemployment over the Short Run", OS3 + "21-3-what-causes-changes-in-unemployment-over-the-short-run", D)
S191 = S("OpenStax, Principles of Economics 3e, 19.1 Measuring the Size of the Economy: GDP", OS3 + "19-1-measuring-the-size-of-the-economy-gross-domestic-product", D)
S194 = S("OpenStax, Principles of Economics 3e, 19.4 Tracking Real GDP over Time", OS3 + "19-4-tracking-real-gdp-over-time", D)
S245 = S("OpenStax, Principles of Economics 3e, 24.5 Growth, Unemployment and Inflation in the AD-AS Model", OS3 + "24-5-how-the-ad-as-model-incorporates-growth-unemployment-and-inflation", D)
S251 = S("OpenStax, Principles of Economics 3e, 25.1 Aggregate Demand in Keynesian Analysis", OS3 + "25-1-aggregate-demand-in-keynesian-analysis", D)
S261 = S("OpenStax, Principles of Economics 3e, 26.1 The Building Blocks of Neoclassical Analysis", OS3 + "26-1-the-building-blocks-of-neoclassical-analysis", D)
S285 = S("OpenStax, Principles of Economics 3e, 28.5 Pitfalls for Monetary Policy", OS3 + "28-5-pitfalls-for-monetary-policy", D)
S333 = S("OpenStax, Principles of Economics 3e, 33.3 Intra-industry Trade between Similar Economies", OS3 + "33-3-intra-industry-trade-between-similar-economies", D)
NOB04 = S("Nobel Prize – The Prize in Economic Sciences 2004 (Kydland, Prescott)", "https://www.nobelprize.org/prizes/economic-sciences/2004/summary/", D)
GUSK = S("GUS – Koniunktura w przetwórstwie przemysłowym, budownictwie, handlu i usługach (opis badania)", "https://stat.gov.pl/obszary-tematyczne/koniunktura/", D)

LESSONS = [
    L(1, "Fazy i rodzaje cykli",
      "Rozumieć fazy cyklu koniunkturalnego, różnicę między recesją a depresją oraz klasyczne typy cykli o różnej długości.",
      ["Cykl koniunkturalny", "Recesja i depresja", "Cykle koniunkturalne – typy"],
      [S194, S213, S245],
      explain=[
          K("Cykl wokół trendu",
            "PKB nie rośnie równomiernie – waha się wokół długookresowego trendu (potencjału). Cykl ma fazy: ożywienie, rozkwit (boom) z punktem szczytowym, recesja (kryzys) i dno (depresja jako najniższy punkt). Okres od szczytu do szczytu to długość cyklu."),
          K("Recesja i depresja",
            "Recesja to wyraźny, szeroki spadek aktywności gospodarczej trwający dłużej niż kilka miesięcy. Często stosuje się uproszczenie: „recesja techniczna” = dwa kolejne kwartały spadku realnego PKB (kw/kw). Depresja to bardzo głęboka i długa recesja – jak Wielki Kryzys 1929–1933."),
          W("Realny PKB spada przez dwa kolejne kwartały. Według popularnej reguły to:",
            "Recesja techniczna", "Depresja", "Ożywienie",
            why="Dwa kolejne kwartały spadku PKB kw/kw to umowna definicja recesji technicznej."),
          K("Typy cykli",
            "Kitchina – krótkie, ok. 3–5 lat (zapasy). Juglara – średnie, ok. 7–11 lat (inwestycje w maszyny). Kuznetsa – ok. 15–25 lat (budownictwo, demografia). Kondratiewa – długie fale, ok. 45–60 lat (przełomy technologiczne, np. kolej, elektryczność, informatyka)."),
          K("Wskaźniki w fazach cyklu",
            "W boomie: niskie bezrobocie, rosnąca inflacja, wysokie wykorzystanie mocy, rosnące zyski i kredyt. W recesji: rosnące bezrobocie, spadające inwestycje i zapasy, niższa inflacja, spadek importu. Inwestycje i zapasy wahają się znacznie silniej niż konsumpcja."),
          PF("Cykl koniunkturalny ma zawsze jednakową, regularną długość.", False,
             why="Cykle różnią się długością i głębokością – „cykl” nie oznacza regularności jak w zegarze."),
      ],
      mech=[
          LN("Ułóż fazy cyklu, zaczynając od dna.",
             ["Dno (depresja)", "Ożywienie", "Rozkwit (boom)", "Szczyt", "Recesja"],
             why="Po recesji gospodarka znowu osiąga dno i cykl się powtarza."),
          KT("Do której fazy pasuje opis?",
             {"Boom": ["Niedobór pracowników i szybki wzrost płac", "Pełne wykorzystanie mocy produkcyjnych", "Rosnąca inflacja"],
              "Recesja": ["Firmy ograniczają zapasy i inwestycje", "Rośnie liczba upadłości", "Spada import"]},
             why="Boom – napięcia popytowe; recesja – spadek aktywności."),
          KT("Który typ cyklu?",
             {"Kitchina": ["Wahania zapasów w ciągu kilku lat"],
              "Juglara": ["Fale inwestycji w maszyny co 7–11 lat"],
              "Kuznetsa": ["Cykle w budownictwie trwające kilkanaście–dwadzieścia lat"],
              "Kondratiewa": ["Długa fala związana z upowszechnieniem elektryczności"]},
             why="Typy różnią się długością i źródłem wahań."),
          W("Który składnik PKB zwykle waha się najsilniej w cyklu?",
            "Inwestycje (zwłaszcza w zapasy)", "Konsumpcja żywności", "Wydatki na emerytury",
            why="Decyzje inwestycyjne silnie reagują na oczekiwania i stopy procentowe."),
          PF("Import zwykle spada w recesji.", True,
             why="Spada popyt krajowy, w tym na dobra z zagranicy."),
          M("Co typowo rośnie w recesji?",
            ["Bezrobocie", "Liczba upadłości firm", "Inflacja popytowa", "Deficyt budżetowy (automatyczne stabilizatory)"],
            [0, 1, 3],
            why="Inflacja popytowa zwykle słabnie w recesji."),
      ],
      calc=[
          LB("PKB w kolejnych kwartałach (mld zł, ceny stałe): 1000, 990, 985. O ile procent spadł PKB w drugim kwartale spadku (kw/kw)?",
             -0.51, "(985/990-1)*100", ["985 / 990 − 1 ≈ −0,51%"], unit="%", tol=0.02),
          LB("Ile wynosi łączny spadek PKB od szczytu (1000) do 985 (%)?",
             -1.5, "(985/1000-1)*100", ["985 / 1000 − 1 = −1,5%"], unit="%"),
          LB("Potencjał rośnie 3% rocznie i wynosi 1030, a faktyczny PKB 985. Ile wynosi luka PKB (%)?",
             -4.37, "(985-1030)/1030*100", ["(985 − 1030) / 1030 ≈ −4,37%"], unit="%", tol=0.02),
          LB("Cykl Juglara trwa ok. 9 lat. Ile pełnych cykli zmieści się w jednej fali Kondratiewa trwającej 54 lata?",
             6, "54/9", ["54 / 9 = 6"], unit=""),
          LB("W boomie inwestycje wynoszą 800, w recesji 640, a konsumpcja 2500 i 2450. O ile procent spadły inwestycje?",
             -20, "(640/800-1)*100", ["640 / 800 − 1 = −20%"], unit="%"),
          LB("O ile procent spadła w tym czasie konsumpcja?",
             -2, "(2450/2500-1)*100", ["2450 / 2500 − 1 = −2% – dziesięć razy mniej niż inwestycje"], unit="%"),
      ],
      case=[
          PR("W 2020 r. pandemia COVID-19 i lockdowny spowodowały gwałtowny spadek PKB w wielu krajach już w II kwartale. W Polsce był to pierwszy roczny spadek PKB od początku lat 90. Odbicie w kolejnych kwartałach było jednak szybkie.",
             W("Jak nazwać tę recesję pod względem przyczyny?",
               "Wywołaną szokiem zewnętrznym (pandemia i ograniczenia)", "Wywołaną przegrzaniem kredytowym", "Wywołaną hiperinflacją",
               why="Źródłem był nagły szok, a nie wewnętrzna nierównowaga gospodarki."),
             W("Czy była to depresja?",
               "Nie – była głęboka, ale krótka, z szybkim odbiciem", "Tak, bo trwała dekadę", "Tak, bo PKB spadł do zera",
               why="Depresja to bardzo głęboka i długotrwała recesja."),
             PF("Kształt takiego przebiegu (gwałtowny spadek i szybkie odbicie) często nazywa się recesją w kształcie litery V.", True,
                why="Litera V obrazuje szybki spadek i szybki powrót."),
          ),
          PR("W latach 1929–1933 PKB USA spadł o ok. jedną czwartą, bezrobocie przekroczyło 20%, a ceny spadały. Upadły tysiące banków, a gospodarka wróciła do poziomu sprzed kryzysu dopiero pod koniec dekady.",
             W("Jak nazywa się takie zjawisko?",
               "Depresja (Wielki Kryzys)", "Recesja techniczna", "Przegrzanie",
               why="Bardzo głęboki i długi spadek aktywności."),
             M("Które zjawiska pogłębiały kryzys?",
               ["Upadłości banków i spadek kredytu", "Deflacja zwiększająca realny ciężar długów", "Ekspansywna polityka fiskalna", "Spadek handlu międzynarodowego"],
               [0, 1, 3],
               why="Polityka fiskalna była wtedy raczej restrykcyjna."),
             PF("Doświadczenie Wielkiego Kryzysu było ważnym impulsem dla teorii Keynesa.", True,
                why="„Ogólna teoria” (1936) powstała w reakcji na masowe bezrobocie."),
          ),
      ]),

    L(2, "Teorie cyklu koniunkturalnego",
      "Porównywać popytowe (keynesowskie), monetarne, austriackie i realne wyjaśnienia cyklu oraz rozumieć model mnożnika–akceleratora.",
      ["Teorie cyklu koniunkturalnego", "Teoria realnego cyklu koniunkturalnego", "Cykl koniunkturalny"],
      [S251, S261, NOB04],
      explain=[
          K("Teorie popytowe (keynesowskie)",
            "Źródłem wahań są zmiany zagregowanego popytu – przede wszystkim niestabilne inwestycje zależne od „zwierzęcych instynktów”. Model mnożnika–akceleratora (Samuelson): wzrost dochodu zwiększa inwestycje (akcelerator), a inwestycje przez mnożnik zwiększają dochód – powstają samopodtrzymujące się wahania."),
          K("Teorie monetarne i austriacka",
            "Monetaryści (Friedman): wahania wynikają głównie z błędów polityki pieniężnej, np. nadmiernego lub zbyt małego wzrostu podaży pieniądza. Szkoła austriacka (Mises, Hayek): sztucznie niskie stopy procentowe wywołują boom kredytowy i błędne inwestycje (malinwestycje), które recesja musi „oczyścić”."),
          W("Według szkoły austriackiej źródłem cyklu jest głównie:",
            "Sztucznie niska stopa procentowa wywołująca boom kredytowy i błędne inwestycje", "Spadek „zwierzęcych instynktów”", "Szoki technologiczne przy elastycznych cenach",
            why="Zbyt tani kredyt zniekształca decyzje inwestycyjne."),
          K("Teoria realnego cyklu (RBC)",
            "Kydland i Prescott (Nagroda Nobla 2004): wahania to optymalna reakcja gospodarki na realne szoki – głównie zmiany produktywności (technologia, ceny surowców). Ceny i płace są elastyczne, a recesja nie jest „błędem rynku”. Wniosek: polityka stabilizacyjna nie jest potrzebna, a może szkodzić."),
          K("Teorie polityczne i finansowe",
            "Polityczny cykl koniunkturalny (Nordhaus): rządy pobudzają gospodarkę przed wyborami. Teorie finansowe (Minsky, Fisher) podkreślają narastanie zadłużenia w boomie i deflację dłużną w kryzysie."),
          PF("W teorii realnego cyklu recesja wynika przede wszystkim ze spadku zagregowanego popytu.", False,
             why="RBC przypisuje wahania realnym szokom podażowym, głównie produktywności."),
      ],
      mech=[
          LN("Ułóż mechanizm mnożnika–akceleratora w fazie wzrostu.",
             ["Rosną wydatki autonomiczne", "Przez mnożnik rośnie dochód", "Akcelerator: wyższy przyrost dochodu zwiększa inwestycje", "Wyższe inwestycje znowu zwiększają dochód", "Gdy tempo wzrostu dochodu słabnie, inwestycje spadają i zaczyna się zwrot"],
             why="Inwestycje zależą od zmiany, a nie od poziomu dochodu – stąd wahania."),
          KT("Która teoria?",
             {"Keynesowska": ["Wahania nastrojów inwestorów", "Niedobór popytu w recesji"],
              "Monetarystyczna": ["Błędy w kontroli podaży pieniądza"],
              "Austriacka": ["Malinwestycje po okresie taniego kredytu"],
              "RBC": ["Szoki produktywności przy elastycznych cenach", "Recesja jako optymalna reakcja"]},
             why="Teorie różnią się źródłem wahań."),
          W("Która teoria najsilniej popiera aktywną politykę stabilizacyjną?",
            "Keynesowska", "Realnego cyklu (RBC)", "Austriacka",
            why="Keyneści widzą w recesji niedobór popytu, który państwo może uzupełnić."),
          PF("Polityczny cykl koniunkturalny zakłada, że rządy przed wyborami pobudzają gospodarkę.", True,
             why="Krótkookresowa poprawa ma zwiększyć szanse wyborcze."),
          M("Które twierdzenia pasują do teorii RBC?",
            ["Ceny i płace są elastyczne", "Szoki technologiczne są głównym źródłem wahań", "Bank centralny powinien zwalczać każdą recesję", "Wahania zatrudnienia to dobrowolne decyzje pracowników"],
            [0, 1, 3],
            why="RBC uważa aktywną politykę za zbędną."),
          W("Za co Kydland i Prescott otrzymali Nagrodę Nobla w 2004 r.?",
            "Za badania nad spójnością polityki w czasie i źródłami wahań cyklicznych", "Za teorię przewagi komparatywnej", "Za model IS-LM",
            why="Ich prace dotyczyły dynamicznej makroekonomii: wiarygodności polityki i siły napędowej cyklu."),
      ],
      calc=[
          LB("Akcelerator: I = 2 · (Yₜ − Yₜ₋₁). Dochód rośnie ze 1000 do 1050. Ile wynoszą inwestycje?",
             100, "2*(1050-1000)", ["I = 2 · 50 = 100"], unit=""),
          LB("W kolejnym roku dochód rośnie z 1050 do 1080. Ile wynoszą inwestycje?",
             60, "2*(1080-1050)", ["I = 2 · 30 = 60 – inwestycje spadają, choć dochód nadal rośnie"], unit=""),
          LB("Trzeci rok: dochód rośnie z 1080 do 1090. Ile wynoszą inwestycje?",
             20, "2*(1090-1080)", ["I = 2 · 10 = 20"], unit=""),
          LB("O ile procent spadły inwestycje między pierwszym (100) a trzecim rokiem (20)?",
             -80, "(20/100-1)*100", ["20 / 100 − 1 = −80%"], unit="%"),
          LB("Szok produktywności w modelu RBC: Y = A · 1000, A spada z 1,00 do 0,97. O ile procent spada produkcja?",
             -3, "(0.97-1)*100", ["Y spada proporcjonalnie do A: −3%"], unit="%"),
          LB("Mnożnik wynosi 2,5, a inwestycje spadają o 40 mld zł. O ile spada dochód (mld zł)?",
             100, "2.5*40", ["ΔY = 2,5 · 40 = 100 mld zł"], unit="mld zł"),
      ],
      case=[
          PR("W latach 2003–2007 w USA stopy procentowe były niskie, kredyt hipoteczny rósł bardzo szybko, a ceny domów biły rekordy. Budowano wiele nowych domów. Po wzroście stóp i spadku cen nieruchomości nastąpiła głęboka recesja 2008–2009.",
             W("Jak tę sekwencję interpretowałaby szkoła austriacka?",
               "Tani kredyt wywołał malinwestycje w nieruchomości, które kryzys „oczyścił”", "Szok produktywności przy elastycznych cenach", "Przypadkowy spadek nastrojów",
               why="To klasyczny schemat boomu kredytowego austriaków."),
             W("Co podkreślaliby keynesiści?",
               "Załamanie popytu, które wymagało pobudzenia fiskalnego i monetarnego", "Że recesja była optymalna", "Że należało podnieść podatki",
               why="Keynesiści widzą w recesji niedobór popytu."),
             PF("Teoria RBC miała trudności z wyjaśnieniem kryzysu 2008 r. wyłącznie szokami produktywności.", True,
                why="Kryzys miał wyraźnie finansowe i popytowe źródła."),
          ),
          PR("W pewnym kraju rząd przed wyborami obniża podatki i podnosi świadczenia, choć gospodarka rośnie szybko. Po wyborach inflacja przyspiesza, a nowy rząd tnie wydatki, co spowalnia gospodarkę.",
             W("Jaką teorię ilustruje ten przykład?",
               "Polityczny cykl koniunkturalny", "Realny cykl koniunkturalny", "Cykl Kondratiewa",
               why="Decyzje polityczne przed wyborami nasilają wahania."),
             W("Co mogłoby ograniczyć takie zachowanie?",
               "Reguły fiskalne i niezależne instytucje budżetowe", "Zniesienie wyborów", "Druk pieniądza",
               why="Reguły ograniczają swobodę prowadzenia procyklicznej polityki."),
             PF("Pobudzanie gospodarki rosnącej już szybko jest polityką procykliczną.", True,
                why="Wzmacnia boom zamiast go łagodzić."),
          ),
      ]),

    L(3, "Minsky: stabilność rodzi niestabilność",
      "Rozumieć hipotezę niestabilności finansowej Minsky’ego: finansowanie zabezpieczone, spekulacyjne i Ponziego oraz „moment Minsky’ego”.",
      ["Finansowanie zabezpieczone, spekulacyjne i Ponziego (Minsky)", "Teorie cyklu koniunkturalnego", "Recesja i depresja"],
      [S285, S("OpenStax, Principles of Economics 3e, 27.4 How Banks Create Money", OS3 + "27-4-how-banks-create-money", D)],
      explain=[
          K("Trzy rodzaje finansowania",
            "Hyman Minsky wyróżnił: (1) zabezpieczone (hedge) – dochody pokrywają odsetki i spłatę kapitału; (2) spekulacyjne – dochody pokrywają tylko odsetki, kapitał trzeba rolować nowym długiem; (3) Ponziego – dochody nie pokrywają nawet odsetek; dłużnik liczy na wzrost cen aktywów, by spłacić dług ze sprzedaży."),
          K("Stabilność rodzi niestabilność",
            "Gdy gospodarka długo jest stabilna, banki i inwestorzy stają się coraz śmielsi. Udział finansowania spekulacyjnego i Ponziego rośnie, a ceny aktywów idą w górę. Gospodarka staje się wrażliwa na każdy wzrost stóp procentowych lub spadek cen aktywów."),
          W("Firma z dochodów spłaca odsetki, ale kapitał musi refinansować nowym kredytem. To finansowanie:",
            "Spekulacyjne", "Zabezpieczone", "Ponziego",
            why="Dochody pokrywają tylko odsetki."),
          K("Moment Minsky’ego",
            "Punkt, w którym wierzyciele przestają rolować długi, a dłużnicy Ponziego muszą sprzedawać aktywa. Ceny spadają, co zmusza do sprzedaży kolejnych – spirala wymuszonej sprzedaży. Termin spopularyzowano podczas kryzysu 2007–2008."),
          K("Wnioski dla polityki",
            "Minsky podkreślał rolę państwa i banku centralnego jako pożyczkodawcy ostatniej instancji oraz potrzebę regulacji ograniczających lewarowanie. Dziś podobną rolę pełni polityka makroostrożnościowa (np. limity LTV i DSTI w kredytach hipotecznych)."),
          PF("Według Minsky’ego długi okres stabilności zmniejsza ryzyko kryzysu finansowego.", False,
             why="Stabilność zachęca do coraz ryzykowniejszego finansowania – ryzyko rośnie."),
      ],
      mech=[
          LN("Ułóż przebieg cyklu Minsky’ego.",
             ["Długi okres stabilnego wzrostu", "Rośnie optymizm i chęć do zadłużania się", "Przybywa finansowania spekulacyjnego i Ponziego", "Wzrost stóp lub spadek cen aktywów", "Wymuszona sprzedaż aktywów i kryzys"],
             why="Kryzys wyrasta z wcześniejszego okresu stabilności."),
          KT("Jaki rodzaj finansowania?",
             {"Zabezpieczone": ["Najem mieszkania pokrywa ratę kapitałowo-odsetkową", "Firma spłaca kredyt z bieżących zysków"],
              "Spekulacyjne": ["Spółka płaci odsetki, a obligacje refinansuje nowymi"],
              "Ponziego": ["Deweloper liczy, że spłaci kredyt tylko dzięki wzrostowi cen gruntu", "Inwestor dopłaca do odsetek, licząc na zysk ze sprzedaży mieszkania"]},
             why="Kryterium: czy dochody pokrywają odsetki i kapitał."),
          W("Dlaczego wzrost stóp procentowych jest groźny dla dłużników spekulacyjnych?",
            "Rośnie koszt rolowania długu – mogą przejść do kategorii Ponziego", "Bo spadają ich dochody z eksportu", "Nie jest groźny",
            why="Odsetki mogą przekroczyć dochody."),
          PF("Polityka makroostrożnościowa (np. limity LTV) ogranicza narastanie ryzykownego finansowania.", True,
             why="Ogranicza lewarowanie i udział kredytów bez zabezpieczenia w dochodach."),
          M("Co sygnalizuje narastanie nierównowag w duchu Minsky’ego?",
            ["Szybki wzrost kredytu względem PKB", "Rosnące ceny aktywów finansowane długiem", "Spadek zadłużenia gospodarstw domowych", "Kredyty, których spłata zależy od wzrostu cen nieruchomości"],
            [0, 1, 3],
            why="Spadek zadłużenia oznacza deleveraging, nie budowę nierównowag."),
          W("Kto według Minsky’ego powinien przerywać spiralę paniki?",
            "Bank centralny jako pożyczkodawca ostatniej instancji", "Agencje ratingowe", "Same banki komercyjne bez wsparcia",
            why="Dostarczenie płynności zatrzymuje wymuszoną sprzedaż aktywów."),
      ],
      calc=[
          LB("Inwestor kupuje mieszkanie za 600 000 zł z kredytem 540 000 zł. Ile wynosi wskaźnik LTV (%)?",
             90, "540000/600000*100", ["540 000 / 600 000 = 90%"], unit="%"),
          LB("Najem daje 30 000 zł rocznie, odsetki przy 5% wynoszą 27 000 zł, a rata kapitałowa 18 000 zł. Jaki to rodzaj finansowania? Podaj niedobór (zł), jakiego dochód nie pokrywa.",
             15000, "27000+18000-30000", ["Odsetki + kapitał = 45 000", "45 000 − 30 000 = 15 000 zł – finansowanie spekulacyjne (odsetki pokryte)"], unit="zł"),
          LB("Stopa rośnie z 5% do 7% (kredyt 540 000 zł). O ile zł rosną roczne odsetki?",
             10800, "540000*0.02", ["540 000 · 0,02 = 10 800 zł"], unit="zł"),
          LB("Nowe odsetki to 37 800 zł, a najem daje 30 000 zł. O ile zł odsetki przekraczają dochód (finansowanie Ponziego)?",
             7800, "540000*0.07-30000", ["37 800 − 30 000 = 7 800 zł"], unit="zł"),
          LB("Ceny mieszkań spadają o 15%. Ile wynosi nowe LTV (%), jeśli dług nadal wynosi 540 000 zł?",
             105.88, "540000/(600000*0.85)*100", ["600 000 · 0,85 = 510 000", "540 000 / 510 000 ≈ 105,88%"], unit="%", tol=0.02),
          LB("Ile zł wynosi ujemny kapitał własny inwestora po spadku cen?",
             30000, "540000-510000", ["540 000 − 510 000 = 30 000 zł"], unit="zł"),
      ],
      case=[
          PR("Przed 2007 r. w USA rosła liczba kredytów hipotecznych dla osób o niskiej zdolności kredytowej (subprime), często z niskimi ratami na początku. Kredytobiorcy i banki zakładali, że ceny domów będą rosły i kredyt da się zrefinansować. Gdy ceny zaczęły spadać, a raty wzrosły, fala niewypłacalności doprowadziła do kryzysu finansowego.",
             W("Jakim rodzajem finansowania w ujęciu Minsky’ego były takie kredyty?",
               "Ponziego – spłata zależała od wzrostu cen domów", "Zabezpieczonym", "Bezdłużnym",
               why="Dochody nie pokrywały pełnych rat; liczono na refinansowanie dzięki rosnącym cenom."),
             W("Co było „momentem Minsky’ego”?",
               "Spadek cen domów, który uniemożliwił refinansowanie i wymusił sprzedaże", "Obniżka podatków", "Wzrost eksportu",
               why="Spadek cen aktywów przerwał łańcuch rolowania długów."),
             PF("Wysoki udział finansowania Ponziego sprawia, że niewielki spadek cen aktywów może wywołać kryzys.", True,
                why="Dłużnicy nie mają dochodów pozwalających przetrwać spadek cen."),
          ),
          PR("Bank centralny pewnego kraju obserwuje, że kredyty hipoteczne rosną o 20% rocznie, coraz więcej z nich ma LTV powyżej 90%, a część kupujących nabywa mieszkania wyłącznie w celu szybkiej odsprzedaży.",
             W("Jakie ryzyko w duchu Minsky’ego narasta?",
               "Przejście od finansowania zabezpieczonego do spekulacyjnego i Ponziego", "Ryzyko deflacji", "Ryzyko zbyt niskiego zadłużenia",
               why="Kupno w celu odsprzedaży z wysokim LTV to typowe finansowanie Ponziego."),
             M("Jakie narzędzia makroostrożnościowe można zastosować?",
               ["Obniżenie maksymalnego LTV", "Limit wskaźnika DSTI (rata do dochodu)", "Obniżka stóp procentowych", "Bufor antycykliczny dla banków"],
               [0, 1, 3],
               why="Obniżka stóp jeszcze pobudziłaby kredyt."),
             PF("Narzędzia makroostrożnościowe działają celowo na kredyt, a nie na całą gospodarkę jak stopy procentowe.", True,
                why="Pozwala to ograniczać nierównowagi bez hamowania całego popytu."),
          ),
      ]),

    L(4, "Jak śledzić koniunkturę",
      "Rozumieć wskaźniki wyprzedzające, równoległe i opóźnione, badania koniunktury GUS (saldo odpowiedzi) i indeks PMI.",
      ["Wskaźniki wyprzedzające (barometry koniunktury)", "Badania koniunktury GUS i indeks PMI", "Cykl koniunkturalny"],
      [GUSK, S191, S194],
      explain=[
          K("Wyprzedzające, równoległe, opóźnione",
            "Wskaźniki wyprzedzające zmieniają się przed zmianą koniunktury: nowe zamówienia, pozwolenia na budowę, nastroje przedsiębiorców i konsumentów, indeksy giełdowe, różnica między stopami długo- i krótkoterminowymi. Równoległe: produkcja, sprzedaż, PKB. Opóźnione: bezrobocie, inflacja bazowa, długość okresu bezrobocia."),
          K("Badania koniunktury GUS",
            "GUS co miesiąc pyta przedsiębiorców (przetwórstwo, budownictwo, handel, usługi) i konsumentów o ocenę sytuacji obecnej i oczekiwania. Wynik podaje się jako saldo: odsetek odpowiedzi „poprawa” minus odsetek „pogorszenie”. Wskaźnik ogólnego klimatu koniunktury powyżej zera oznacza przewagę ocen pozytywnych."),
          W("40% firm ocenia, że sytuacja się poprawi, 25% – że się pogorszy, reszta – bez zmian. Ile wynosi saldo?",
            "15", "40", "65",
            why="Saldo = 40 − 25 = 15."),
          K("Indeks PMI",
            "Indeks menedżerów zakupów: ankieta wśród firm o zamówienia, produkcję, zatrudnienie, czasy dostaw i zapasy. Wartość powyżej 50 pkt oznacza poprawę (ekspansję) w porównaniu z poprzednim miesiącem, poniżej 50 – pogorszenie. PMI publikowany jest na początku miesiąca, więc szybko sygnalizuje zmiany."),
          K("Ograniczenia",
            "Wskaźniki wyprzedzające dają też fałszywe sygnały; nastroje mogą reagować na wydarzenia polityczne bez wpływu na gospodarkę. Dlatego prognostycy łączą wiele wskaźników w indeksy złożone."),
          PF("PMI równy 48 pkt oznacza, że produkcja przemysłowa spada o 48%.", False,
             why="Wartość poniżej 50 oznacza tylko przewagę firm zgłaszających pogorszenie."),
      ],
      mech=[
          KT("Wskaźnik wyprzedzający, równoległy czy opóźniony?",
             {"Wyprzedzający": ["Nowe zamówienia w przemyśle", "Liczba pozwoleń na budowę", "Nastroje konsumentów"],
              "Równoległy": ["Produkcja przemysłowa", "Sprzedaż detaliczna"],
              "Opóźniony": ["Stopa bezrobocia", "Inflacja bazowa"]},
             why="Firmy najpierw zbierają zamówienia, potem produkują, a na końcu zmieniają zatrudnienie."),
          LN("Ułóż typową kolejność sygnałów przy wejściu w ożywienie.",
             ["Poprawiają się nastroje i rośnie liczba zamówień", "PMI przekracza 50 pkt", "Rośnie produkcja i sprzedaż", "Firmy zwiększają zatrudnienie", "Bezrobocie zaczyna spadać"],
             why="Bezrobocie reaguje z opóźnieniem."),
          W("Dlaczego bezrobocie jest wskaźnikiem opóźnionym?",
            "Firmy najpierw zwiększają godziny pracy, a zatrudniają dopiero, gdy są pewne poprawy", "Bo GUS publikuje je raz na dekadę", "Bo nie zależy od koniunktury",
            why="Zatrudnianie i zwalnianie są kosztowne, więc firmy czekają."),
          PF("Odwrócenie krzywej rentowności (stopy krótkie wyższe od długich) bywa traktowane jako sygnał zbliżającej się recesji.", True,
             why="Rynek oczekuje spadku stóp w przyszłości, co zwykle towarzyszy spowolnieniu."),
          M("Co wskazuje na pogarszanie się koniunktury?",
            ["PMI spada poniżej 50 pkt", "Saldo ocen GUS staje się ujemne", "Rośnie liczba nowych zamówień", "Spada liczba pozwoleń na budowę"],
            [0, 1, 3],
            why="Rosnące zamówienia to sygnał poprawy."),
          W("Co oznacza wzrost PMI z 45 do 48 pkt?",
            "Pogorszenie trwa, ale jest wolniejsze", "Ekspansję", "Gwałtowne przyspieszenie spadku",
            why="Poniżej 50 wciąż przeważa pogorszenie, ale mniej firm je zgłasza."),
      ],
      calc=[
          LB("Konsumenci: 22% oczekuje poprawy, 41% pogorszenia. Ile wynosi saldo?",
             -19, "22-41", ["22 − 41 = −19"], unit=""),
          LB("PMI z 5 składowych: zamówienia 52 (waga 30%), produkcja 50 (25%), zatrudnienie 48 (20%), czasy dostaw 55 (15%), zapasy 46 (10%). Ile wynosi PMI?",
             50.55, "0.3*52+0.25*50+0.2*48+0.15*55+0.1*46", ["15,6 + 12,5 + 9,6 + 8,25 + 4,6 = 50,55 – lekka ekspansja"], unit="pkt", tol=0.02),
          LB("Indeks dyfuzji: 30% firm zgłasza poprawę, 50% bez zmian, 20% pogorszenie. Wzór: %poprawa + 0,5 · %bez zmian. Ile wynosi indeks?",
             55, "30+0.5*50", ["30 + 25 = 55 pkt"], unit="pkt"),
          LB("Stopa 10-letnia 4,8%, 2-letnia 5,3%. Ile wynosi spread (p.p.)?",
             -0.5, "4.8-5.3", ["4,8 − 5,3 = −0,5 p.p. – krzywa odwrócona"], unit="p.p."),
          LB("Pozwolenia na budowę spadły z 25 tys. do 20 tys. miesięcznie. O ile procent?",
             -20, "(20/25-1)*100", ["20 / 25 − 1 = −20%"], unit="%"),
          LB("Wskaźnik złożony = średnia z 4 sald: −5, +3, −12, −2. Ile wynosi?",
             -4, "(-5+3-12-2)/4", ["−16 / 4 = −4"], unit=""),
      ],
      case=[
          PR("W ciągu trzech miesięcy PMI w przemyśle spadł z 51 do 47 pkt, saldo ocen konsumentów GUS pogorszyło się, a liczba nowych zamówień spadła. Produkcja przemysłowa i stopa bezrobocia na razie się nie zmieniły.",
             W("Co sugerują te dane?",
               "Wskaźniki wyprzedzające sygnalizują spowolnienie, które nie dotarło jeszcze do danych o produkcji i zatrudnieniu", "Gospodarka przyspiesza", "Nic – bezrobocie się nie zmieniło",
               why="Wskaźniki wyprzedzające reagują przed produkcją i zatrudnieniem."),
             W("Który wskaźnik zareaguje najpóźniej?",
               "Stopa bezrobocia", "PMI", "Nowe zamówienia",
               why="Bezrobocie jest wskaźnikiem opóźnionym."),
             PF("Pojedynczy spadek PMI nie przesądza o recesji – mogą zdarzać się fałszywe sygnały.", True,
                why="Dlatego analizuje się trwałość zmian i wiele wskaźników."),
          ),
          PR("Analityczka prognozuje koniunkturę. Ma dane: wskaźnik ogólnego klimatu koniunktury GUS wzrósł z −8 do −2, PMI z 47 do 50,5, a liczba pozwoleń na budowę wzrosła o 12% r/r. Bezrobocie wciąż rośnie.",
             W("Jak ocenić sytuację?",
               "Koniunktura się poprawia; bezrobocie zareaguje później", "Recesja się pogłębia", "Brak sygnałów",
               why="Wskaźniki wyprzedzające się poprawiają."),
             W("Co oznacza PMI 50,5?",
               "Niewielka przewaga firm zgłaszających poprawę", "Wzrost produkcji o 50,5%", "Spadek zamówień",
               why="Powyżej 50 – ekspansja względem poprzedniego miesiąca."),
             PF("Ujemne saldo klimatu koniunktury (−2) oznacza nadal lekką przewagę ocen negatywnych.", True,
                why="Saldo poniżej zera – więcej odpowiedzi „pogorszenie”."),
          ),
      ]),

    L(5, "Cykl życia produktu Vernona i przenoszenie cykli",
      "Rozumieć teorię cyklu życia produktu w handlu międzynarodowym (Vernon) i kanały, którymi koniunktura przenosi się między krajami.",
      ["Teoria cyklu życia produktu w handlu (Vernon)", "Cykl koniunkturalny", "Wskaźniki wyprzedzające (barometry koniunktury)"],
      [S333, S("OpenStax, Principles of Economics 3e, 23.2 Trade Balances in Historical and International Context", OS3 + "23-2-trade-balances-in-historical-and-international-context", D)],
      explain=[
          K("Cykl życia produktu (Vernon, 1966)",
            "Nowy produkt powstaje w kraju bogatym i innowacyjnym (blisko klientów i inżynierów) i jest stamtąd eksportowany. W fazie dojrzałości technologia się standaryzuje, produkcja przenosi się do innych krajów rozwiniętych. W fazie standaryzacji decyduje koszt pracy – produkcja trafia do krajów o niskich płacach, a kraj-wynalazca zaczyna importować produkt."),
          K("Przykład",
            "Telewizory, komputery osobiste czy telefony komórkowe: początkowo produkowane w USA, Japonii lub Europie, później masowo w Azji. Kraj-innowator przechodzi do kolejnych nowych produktów."),
          W("W której fazie cyklu Vernona produkcja przenosi się do krajów o niskich płacach?",
            "Standaryzacji", "Wprowadzenia (nowego produktu)", "Żadnej",
            why="Gdy technologia jest powszechna, decyduje koszt pracy."),
          K("Przenoszenie cykli między krajami",
            "Koniunktura przenosi się przez: handel (recesja u partnera zmniejsza eksport), łańcuchy dostaw (komponenty), kanał finansowy (kapitał, kursy, ceny aktywów), ceny surowców i nastroje. Polska jest silnie powiązana z Niemcami – największym partnerem handlowym – więc spowolnienie w niemieckim przemyśle szybko widać w polskich zamówieniach eksportowych."),
          K("Synchronizacja",
            "Im silniejsze powiązania handlowe i finansowe, tym bardziej cykle krajów są zsynchronizowane. Integracja w UE zwiększyła synchronizację cykli państw członkowskich, co ułatwia wspólną politykę pieniężną w strefie euro."),
          PF("W fazie nowego produktu kraj-innowator zwykle importuje ten produkt.", False,
             why="Kraj-innowator produkuje i eksportuje; import pojawia się w fazie standaryzacji."),
      ],
      mech=[
          LN("Ułóż fazy cyklu życia produktu wg Vernona.",
             ["Wynalezienie i produkcja w kraju innowatora", "Eksport do innych krajów bogatych", "Produkcja startuje w innych krajach rozwiniętych", "Standaryzacja i przeniesienie produkcji do krajów o niskich płacach", "Kraj-innowator importuje produkt"],
             why="Przewaga przesuwa się z wiedzy na niski koszt pracy."),
          KT("Kanał przenoszenia koniunktury?",
             {"Handlowy": ["Spadek zamówień z Niemiec dla polskich eksporterów", "Recesja u partnera zmniejsza popyt na nasze usługi"],
              "Finansowy": ["Odpływ kapitału z rynków wschodzących", "Spadek kursów akcji na giełdach światowych"],
              "Surowcowy": ["Wzrost cen ropy po konflikcie na Bliskim Wschodzie"]},
             why="Kanały różnią się mechanizmem."),
          W("Dlaczego spowolnienie w Niemczech szybko odczuwa polska gospodarka?",
            "Niemcy są największym partnerem handlowym Polski, a firmy są powiązane łańcuchami dostaw", "Bo Polska używa euro", "Bo Polska nie handluje z innymi krajami",
            why="Silne powiązania handlowe przenoszą spadek popytu."),
          PF("Silniejsze powiązania handlowe zwiększają synchronizację cykli koniunkturalnych.", True,
             why="Wspólne szoki i wzajemny popyt sprawiają, że cykle się zbiegają."),
          M("Co sprzyja przeniesieniu produkcji w fazie standaryzacji?",
            ["Niski koszt pracy", "Dostęp do prostych, ustandaryzowanych technologii", "Konieczność bliskiego kontaktu z wynalazcami", "Duża skala produkcji masowej"],
            [0, 1, 3],
            why="Bliskość wynalazców jest kluczowa w fazie nowego produktu."),
          W("Kraj-innowator po przeniesieniu produkcji telewizorów za granicę zwykle:",
            "Przechodzi do produkcji nowszych, bardziej zaawansowanych dóbr", "Przestaje się rozwijać", "Zakazuje importu",
            why="Utrzymuje przewagę dzięki kolejnym innowacjom."),
      ],
      calc=[
          LB("Przyjmijmy (dane umowne): eksport do Niemiec to 27% eksportu kraju, a eksport – 55% PKB. Popyt z Niemiec spada o 4%. O ile procent PKB spada eksport (bezpośrednio)?",
             0.59, "0.27*0.55*4", ["0,27 · 0,55 = 0,1485", "0,1485 · 4% ≈ 0,59% PKB"], unit="%", tol=0.02),
          LB("Część tego eksportu to importowane komponenty (40%). Ile wynosi utracona wartość dodana (% PKB)?",
             0.36, "0.27*0.55*4*0.6", ["0,594 · 0,6 ≈ 0,36% PKB"], unit="%", tol=0.02),
          LB("Koszt montażu telewizora w kraju A: 120 USD, w kraju B: 45 USD, transport z B: 15 USD. Ile USD oszczędza firma, przenosząc montaż do B?",
             60, "120-(45+15)", ["120 − 60 = 60 USD"], unit="USD"),
          LB("Firma produkuje 2 mln sztuk rocznie. Ile mln USD rocznie oszczędza?",
             120, "60*2", ["60 · 2 = 120 mln USD"], unit="mln USD"),
          LB("Korelacja cykli: przed integracją 0,4, po – 0,7. O ile procent wzrosła?",
             75, "(0.7/0.4-1)*100", ["0,7 / 0,4 − 1 = 75%"], unit="%"),
          LB("PKB partnera spada o 2%, elastyczność importu partnera względem PKB wynosi 2,5. O ile procent spada import partnera (czyli nasz eksport do niego)?",
             5, "2*2.5", ["2 · 2,5 = 5%"], unit="%"),
      ],
      case=[
          PR("W 2023 r. niemiecki przemysł był w słabej kondycji: wysokie ceny energii i spadek popytu na dobra przemysłowe obniżały produkcję. Polskie firmy dostarczające komponenty dla niemieckiego przemysłu motoryzacyjnego notowały spadek zamówień.",
             W("Jakim kanałem spowolnienie przeniosło się do Polski?",
               "Handlowym i przez łańcuchy dostaw", "Wyłącznie walutowym", "Przez wspólną walutę",
               why="Polska nie ma euro; kluczowy był popyt na eksport i komponenty."),
             W("Który wskaźnik w Polsce mógł wcześnie zasygnalizować problem?",
               "Nowe zamówienia eksportowe w PMI", "Stopa bezrobocia", "Inflacja bazowa",
               why="Zamówienia to wskaźnik wyprzedzający."),
             PF("Dywersyfikacja rynków eksportowych zmniejsza wrażliwość na spowolnienie u jednego partnera.", True,
                why="Spadek popytu w jednym kraju ma mniejszy wpływ."),
          ),
          PR("Firma elektroniczna z Kalifornii wymyśliła nowy rodzaj słuchawek. Pierwsze lata produkuje je w USA i sprzedaje na świecie. Po kilku latach konkurenci kopiują technologię, a firma przenosi produkcję do Wietnamu.",
             W("Jaką teorię ilustruje ten przypadek?",
               "Cykl życia produktu Vernona", "Teorię Heckschera–Ohlina", "Model Solowa",
               why="Produkcja przenosi się wraz ze standaryzacją."),
             W("Dlaczego na początku produkcja była w USA?",
               "Potrzebna była bliskość projektantów i pierwszych klientów", "Bo praca w USA była najtańsza", "Bo eksport był zakazany",
               why="W fazie nowego produktu ważne są wiedza i szybkie poprawki."),
             PF("W fazie standaryzacji kluczową przewagą staje się niski koszt produkcji.", True,
                why="Technologia jest już znana i łatwa do przeniesienia."),
          ),
      ]),
]
