# -*- coding: utf-8 -*-
# Zrozumienie – Makroekonomia / Daty i chronologia
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S201 = S("OpenStax, Principles of Economics 3e, 20.1 The Relatively Recent Arrival of Economic Growth", OS3 + "20-1-the-relatively-recent-arrival-of-economic-growth", D)
S246 = S("OpenStax, Principles of Economics 3e, 24.6 Keynes’ Law and Say’s Law in the AD-AS Model", OS3 + "24-6-keynes-law-and-says-law-in-the-ad-as-model", D)
S253 = S("OpenStax, Principles of Economics 3e, 25.3 The Phillips Curve", OS3 + "25-3-the-phillips-curve", D)
S285 = S("OpenStax, Principles of Economics 3e, 28.5 Pitfalls for Monetary Policy", OS3 + "28-5-pitfalls-for-monetary-policy", D)
S294 = S("OpenStax, Principles of Economics 3e, 29.4 Exchange Rate Policies", OS3 + "29-4-exchange-rate-policies", D)
S331 = S("OpenStax, Principles of Economics 3e, 33.1 Absolute and Comparative Advantage", OS3 + "33-1-absolute-and-comparative-advantage", D)
S61 = S("OpenStax, Principles of Economics 3e, 6.1 Consumption Choices", OS3 + "6-1-consumption-choices", D)
NOB97 = S("Nobel Prize – The Prize in Economic Sciences 1997 (Merton, Scholes)", "https://www.nobelprize.org/prizes/economic-sciences/1997/summary/", D)
NBPH = S("NBP – Sprawozdanie z wykonania założeń polityki pieniężnej na 2000 r. (upłynnienie złotego)", "https://nbp.pl/wp-content/uploads/2022/07/wykonanie2000.pdf", D)

LESSONS = [
    L(1, "1758–1817: narodziny ekonomii",
      "Umieszczać w czasie i rozumieć znaczenie czterech dzieł założycielskich: Tablicy ekonomicznej, Bogactwa narodów, Traktatu Saya i Zasad Ricarda.",
      ["1758 – „Tablica ekonomiczna” F. Quesnaya", "1776 – „Bogactwo narodów” A. Smitha", "1803 – „Traktat o ekonomii politycznej” J.B. Saya", "1817 – „Zasady ekonomii politycznej i opodatkowania” D. Ricardo"],
      [S331, S246, S201],
      explain=[
          K("1758 – Tablica ekonomiczna",
            "François Quesnay, lekarz na dworze Ludwika XV, przedstawił obieg produktu między klasami społecznymi (rolnicy, właściciele ziemi, klasa „jałowa”) – pierwowzór modelu obiegu okrężnego i tablic przepływów międzygałęziowych."),
          K("1776 – Bogactwo narodów",
            "Adam Smith – podział pracy, niewidzialna ręka, krytyka merkantylizmu. Ten sam rok to Deklaracja Niepodległości USA, a w Wielkiej Brytanii trwała rewolucja przemysłowa (maszyna parowa Watta weszła do użytku w połowie lat 70.)."),
          W("Które dzieło ukazało się w roku uchwalenia Deklaracji Niepodległości USA?",
            "„Bogactwo narodów” A. Smitha", "„Tablica ekonomiczna” F. Quesnaya", "„Zasady” D. Ricarda", "„Kapitał” K. Marksa",
            why="Oba wydarzenia – 1776 r."),
          K("1803 i 1817 – Say i Ricardo",
            "Jean-Baptiste Say w „Traktacie o ekonomii politycznej” (1803) uporządkował i spopularyzował idee Smitha na kontynencie; sformułował prawo rynków (prawo Saya). David Ricardo w „Zasadach ekonomii politycznej i opodatkowania” (1817) przedstawił przewagę komparatywną, teorię renty i podziału dochodu – czasy wojen napoleońskich i sporu o ustawy zbożowe."),
          K("Wspólny kontekst",
            "Te dzieła powstawały w czasie przemian: upadku feudalizmu, wzrostu handlu i początków rewolucji przemysłowej. Odpowiadały na pytanie, skąd się bierze bogactwo i jaką rolę ma państwo."),
          PF("„Zasady” Ricarda ukazały się przed „Bogactwem narodów” Smitha.", False,
             why="Smith – 1776, Ricardo – 1817."),
      ],
      mech=[
          LN("Ułóż dzieła chronologicznie.",
             ["Tablica ekonomiczna (1758)", "Bogactwo narodów (1776)", "Traktat o ekonomii politycznej (1803)", "Zasady ekonomii politycznej i opodatkowania (1817)"],
             why="Od fizjokratów do dojrzałej szkoły klasycznej."),
          KT("Które dzieło zawiera ideę?",
             {"Tablica ekonomiczna": ["Obieg produktu między klasami społecznymi"],
              "Bogactwo narodów": ["Niewidzialna ręka", "Fabryka szpilek i podział pracy"],
              "Traktat Saya": ["Podaż tworzy własny popyt"],
              "Zasady Ricarda": ["Przewaga komparatywna", "Renta gruntowa"]},
             why="Łączenie idei z dziełami."),
          W("Ile lat dzieli „Tablicę ekonomiczną” od „Bogactwa narodów”?",
            "18", "28", "8",
            why="1776 − 1758 = 18."),
          PF("Prawo Saya zostało sformułowane w XIX wieku.", True,
             why="„Traktat” ukazał się w 1803 r."),
          M("Które dzieła należą do szkoły klasycznej?",
            ["„Bogactwo narodów”", "„Traktat o ekonomii politycznej” Saya", "„Tablica ekonomiczna”", "„Zasady” Ricarda"],
            [0, 1, 3],
            why="Quesnay to fizjokrata."),
          W("Na jaki spór polityczny w Anglii odpowiadał m.in. Ricardo?",
            "O ustawy zbożowe ograniczające import zboża", "O przyjęcie euro", "O kurs złotego",
            why="Ricardo krytykował cła zbożowe."),
      ],
      calc=[
          LB("Ile lat minęło od „Bogactwa narodów” (1776) do 2026 r.?",
             250, "2026-1776", ["2026 − 1776 = 250 lat"], unit="lat"),
          LB("Ile lat dzieli „Traktat” Saya (1803) od „Zasad” Ricarda (1817)?",
             14, "1817-1803", ["1817 − 1803 = 14"], unit="lat"),
          LB("Ile lat dzieli „Tablicę” Quesnaya (1758) od „Zasad” Ricarda (1817)?",
             59, "1817-1758", ["1817 − 1758 = 59"], unit="lat"),
          LB("Smith: 10 robotników bez podziału pracy robi po 20 szpilek, z podziałem – łącznie 48 000. Ile razy rośnie produkcja?",
             240, "48000/(10*20)", ["Bez podziału: 200", "48 000 / 200 = 240"], unit="razy"),
          LB("Ricardo: Anglia sukno 100 godz., wino 120 godz. Ile wynosi koszt alternatywny sukna (w winie)?",
             0.83, "100/120", ["100 / 120 ≈ 0,83 jednostki wina"], unit="", tol=0.02),
          LB("Quesnay: produkt czysty rolnictwa 2 mld, klasa właścicieli otrzymuje go jako rentę i wydaje połowę na produkty rolne. Ile wraca do rolników (mld)?",
             1, "2*0.5", ["2 · 0,5 = 1 mld"], unit="mld"),
      ],
      case=[
          PR("W 2026 r. przypada 250. rocznica wydania „Bogactwa narodów”. Komentatorzy przypominają, że Smith pisał w epoce, gdy dominował merkantylizm, a gospodarka opierała się na rolnictwie i manufakturach.",
             W("Przeciw jakiej doktrynie Smith kierował swoją krytykę?",
               "Merkantylizmowi", "Keynesizmowi", "Monetaryzmowi",
               why="Krytykował gromadzenie kruszców i ograniczenia handlu."),
             W("Która idea Smitha jest najczęściej cytowana?",
               "Niewidzialna ręka rynku", "Mnożnik inwestycyjny", "Krzywa Phillipsa",
               why="Opisuje koordynację rynkową działań jednostek."),
             PF("Smith dostrzegał też potrzebę działań państwa, np. w obronie, sądownictwie i niektórych pracach publicznych.", True,
                why="Nie był zwolennikiem całkowitego braku państwa."),
          ),
          PR("Uczeń ma ułożyć oś czasu: Quesnay, Smith, Say, Ricardo. Myli kolejność Saya i Ricarda, bo obaj pisali „na początku XIX wieku”.",
             W("Który z nich opublikował główne dzieło wcześniej?",
               "Say (1803)", "Ricardo (1817)", "Obaj w tym samym roku",
               why="Traktat Saya – 1803, Zasady Ricarda – 1817."),
             W("Kto był fizjokratą?",
               "Quesnay", "Say", "Ricardo",
               why="Quesnay – twórca Tablicy ekonomicznej."),
             PF("Wszystkie cztery dzieła powstały przed połową XIX wieku.", True,
                why="Najpóźniejsze – Zasady Ricarda z 1817 r."),
          ),
      ]),

    L(2, "1867–1899: Marks, marginaliści, Marshall i Veblen",
      "Umieszczać w czasie przełomowe dzieła drugiej połowy XIX w. i rozumieć, jak zmieniały ekonomię: krytyka kapitalizmu, rewolucja marginalistyczna, synteza Marshalla i instytucjonalizm.",
      ["1867 – „Kapitał” K. Marksa (t. 1)", "1871–1874 – rewolucja marginalistyczna", "1890 – „Zasady ekonomii” A. Marshalla", "1899 – „Teoria klasy próżniaczej” T. Veblena"],
      [S61, S201],
      explain=[
          K("1867 – Kapitał",
            "Pierwszy tom „Kapitału” Marksa analizował wyzysk, wartość dodatkową i akumulację kapitału w warunkach rozwiniętej rewolucji przemysłowej (fabryki, długi dzień pracy, praca dzieci)."),
          K("1871–1874 – marginaliści",
            "Niezależnie od siebie: William Stanley Jevons („Teoria ekonomii politycznej”, 1871), Carl Menger („Zasady ekonomii”, 1871) i Léon Walras („Elementy czystej ekonomii”, 1874) wyjaśnili wartość użytecznością krańcową. Walras stworzył model równowagi ogólnej."),
          W("Kto z marginalistów jest twórcą modelu równowagi ogólnej?",
            "Léon Walras", "Carl Menger", "William Stanley Jevons",
            why="„Elementy czystej ekonomii” (1874)."),
          K("1890 – Marshall",
            "Alfred Marshall w „Zasadach ekonomii” połączył marginalizm z klasyczną analizą kosztów: krzywe popytu i podaży jak „dwa ostrza nożyc”, elastyczność, nadwyżka konsumenta, krótki i długi okres. To podstawa współczesnej mikroekonomii."),
          K("1899 – Veblen",
            "Thorstein Veblen w „Teorii klasy próżniaczej” opisał konsumpcję na pokaz i zapoczątkował instytucjonalizm – badanie roli zwyczajów i instytucji."),
          PF("Rewolucja marginalistyczna nastąpiła przed wydaniem pierwszego tomu „Kapitału”.", False,
             why="„Kapitał” t. 1 – 1867; marginaliści – 1871–1874."),
      ],
      mech=[
          LN("Ułóż wydarzenia chronologicznie.",
             ["„Kapitał” t. 1 (1867)", "Jevons i Menger (1871)", "Walras (1874)", "„Zasady ekonomii” Marshalla (1890)", "„Teoria klasy próżniaczej” (1899)"],
             why="Druga połowa XIX w. to okres wielu przełomów."),
          KT("Kto jest autorem?",
             {"Marks": ["Wartość dodatkowa"],
              "Marshall": ["Nożyce popytu i podaży", "Elastyczność cenowa popytu"],
              "Walras": ["Równowaga ogólna"],
              "Veblen": ["Konsumpcja na pokaz"],
              "Menger": ["Subiektywna wartość – początki szkoły austriackiej"]},
             why="Łączenie idei z autorami."),
          W("Co odróżniało marginalistów od klasyków?",
            "Wartość wyjaśniali użytecznością krańcową, a nie ilością pracy", "Uważali, że wartość tworzy tylko ziemia", "Odrzucali rynek",
            why="To przesunięcie od kosztu do użyteczności."),
          PF("Marshall spopularyzował wykres popytu i podaży w podręcznikowej formie.", True,
             why="Jego „Zasady” były głównym podręcznikiem przez dekady."),
          M("Którzy ekonomiści należą do rewolucji marginalistycznej?",
            ["Jevons", "Menger", "Marks", "Walras"],
            [0, 1, 3],
            why="Marks rozwijał teorię wartości opartej na pracy."),
          W("Ile lat dzieli „Kapitał” (t. 1) od „Zasad ekonomii” Marshalla?",
            "23", "13", "33",
            why="1890 − 1867 = 23."),
      ],
      calc=[
          LB("Marshall: popyt Q = 120 − 2P, podaż Q = 3P − 30. Ile wynosi cena równowagi?",
             30, "150/5", ["120 − 2P = 3P − 30", "5P = 150 ⇒ P = 30"], unit=""),
          LB("Ile wynosi ilość w równowadze?",
             60, "120-2*30", ["Q = 120 − 60 = 60"], unit=""),
          LB("Marshall: elastyczność popytu w punkcie (P = 30, Q = 60), gdy dQ/dP = −2. Ile wynosi |ε|?",
             1, "2*30/60", ["|ε| = 2 · 30 / 60 = 1"], unit=""),
          LB("Jevons: użyteczność całkowita 3 jabłek: 10, 18, 24. Ile wynosi użyteczność krańcowa trzeciego?",
             6, "24-18", ["24 − 18 = 6"], unit=""),
          LB("Marks: kapitał stały 500, zmienny (płace) 200, wartość dodatkowa 200. Ile wynosi stopa zysku (m / (c + v), %)?",
             28.57, "200/(500+200)*100", ["200 / 700 ≈ 28,6%"], unit="%", tol=0.02),
          LB("Ile lat minęło od „Teorii klasy próżniaczej” (1899) do 2026 r.?",
             127, "2026-1899", ["2026 − 1899 = 127"], unit="lat"),
      ],
      case=[
          PR("W latach 70. XIX w. trzech ekonomistów w trzech krajach – Anglii, Austrii i Szwajcarii – niezależnie doszło do podobnej idei: wartość dobra zależy od użyteczności ostatniej jego jednostki.",
             W("Jak nazywa się ten przełom?",
               "Rewolucja marginalistyczna", "Rewolucja keynesowska", "Rewolucja przemysłowa",
               why="Analiza „na marginesie” stała się podstawą ekonomii neoklasycznej."),
             W("Która szkoła wyrosła z prac Mengera w Wiedniu?",
               "Szkoła austriacka", "Szkoła chicagowska", "Szkoła fryburska",
               why="Menger jest uznawany za jej założyciela."),
             PF("Walras pracował w Lozannie w Szwajcarii.", True,
                why="Stąd „szkoła lozańska” (Walras, Pareto)."),
          ),
          PR("Pod koniec XIX w. w USA rosły ogromne fortuny przemysłowców, a bogaci rywalizowali w budowie rezydencji i urządzaniu przyjęć. Veblen opisał to zjawisko w 1899 r.",
             W("Jak nazwał takie zachowanie?",
               "Konsumpcja na pokaz (ostentacyjna)", "Konsumpcja autonomiczna", "Konsumpcja permanentna",
               why="Dobra kupowane po to, by pokazać status."),
             W("Jakie dobra nazywa się dziś dobrami Veblena?",
               "Takie, których popyt rośnie wraz z ceną ze względu na prestiż", "Dobra podrzędne", "Dobra publiczne",
               why="Wyższa cena zwiększa ich atrakcyjność jako symbolu statusu."),
             PF("Veblen jest uważany za jednego z twórców instytucjonalizmu.", True,
                why="Badał rolę zwyczajów i instytucji w gospodarce."),
          ),
      ]),

    L(3, "1929–1958: kryzys, Keynes i nowy ład",
      "Rozumieć związek między Wielkim Kryzysem, „Ogólną teorią” Keynesa, systemem z Bretton Woods i krzywą Phillipsa.",
      ["1929–1933 – Wielki Kryzys", "1936 – „Ogólna teoria” J.M. Keynesa", "1944 – konferencja w Bretton Woods", "1958 – krzywa Phillipsa"],
      [S246, S294, S253],
      explain=[
          K("1929–1933 – Wielki Kryzys",
            "Krach na giełdzie w Nowym Jorku (październik 1929) zapoczątkował najgłębszą depresję w historii gospodarek rynkowych: spadek produkcji, masowe bezrobocie, deflacja, upadki banków i załamanie handlu (protekcjonizm, np. cła Smoota–Hawleya z 1930 r.)."),
          K("1936 – Ogólna teoria",
            "Keynes wyjaśnił, że gospodarka może długo tkwić w równowadze z bezrobociem z powodu niedoboru efektywnego popytu – i że państwo może go uzupełnić. Narodziny makroekonomii jako odrębnej dziedziny."),
          W("Która książka jest uznawana za początek nowoczesnej makroekonomii?",
            "„Ogólna teoria” Keynesa (1936)", "„Bogactwo narodów” (1776)", "„Kapitał” (1867)",
            why="Wprowadziła analizę zagregowanego popytu."),
          K("1944 – Bretton Woods",
            "W lipcu 1944 r. 44 państwa ustaliły powojenny ład walutowy: stałe, ale dostosowywalne kursy wobec dolara, dolar wymienialny na złoto (35 USD za uncję), utworzenie MFW i Banku Światowego. Celem było uniknięcie dewaluacji konkurencyjnych i protekcjonizmu z lat 30."),
          K("1958 – krzywa Phillipsa",
            "A. W. Phillips pokazał na danych brytyjskich (1861–1957) ujemną zależność między bezrobociem a tempem wzrostu płac. W latach 60. stała się podstawą polityki „wymiany” inflacji na bezrobocie."),
          PF("System z Bretton Woods powstał, aby uniknąć powtórki chaosu walutowego i protekcjonizmu z lat 30.", True,
             why="Lata 30. przyniosły wojny walutowe i handlowe."),
      ],
      mech=[
          LN("Ułóż wydarzenia chronologicznie.",
             ["Krach giełdowy w Nowym Jorku (1929)", "Cła Smoota–Hawleya (1930)", "„Ogólna teoria” Keynesa (1936)", "Konferencja w Bretton Woods (1944)", "Krzywa Phillipsa (1958)"],
             why="Kryzys → nowa teoria → nowy ład → nowe narzędzia polityki."),
          KT("Przyczyna czy reakcja na Wielki Kryzys?",
             {"Pogłębiało kryzys": ["Upadki banków i spadek podaży pieniądza", "Cła odwetowe i załamanie handlu", "Deflacja zwiększająca ciężar długów"],
              "Reakcja na kryzys": ["Programy robót publicznych (New Deal)", "Teoria Keynesa", "Utworzenie MFW w 1944 r."]},
             why="Kryzys zmienił myślenie o roli państwa."),
          W("Ile wynosiła cena uncji złota w systemie z Bretton Woods?",
            "35 USD", "20,67 USD", "100 USD",
            why="Stała parytetowa cena dolara względem złota."),
          PF("Krzywa Phillipsa pierwotnie dotyczyła związku bezrobocia z tempem wzrostu płac nominalnych.", True,
             why="Przeniesienie na inflację cen nastąpiło później (Samuelson i Solow, 1960)."),
          M("Które decyzje z lipca 1944 r. ukształtowały powojenny ład walutowy?",
            ["Stałe, ale dostosowywalne kursy wobec dolara", "Wymienialność dolara na złoto dla banków centralnych", "Płynne kursy wszystkich walut", "Utworzenie MFW"],
            [0, 1, 3],
            why="Kursy płynne upowszechniły się po 1973 r."),
          W("Ile lat minęło od wybuchu Wielkiego Kryzysu do wydania „Ogólnej teorii”?",
            "7", "17", "3",
            why="1936 − 1929 = 7."),
      ],
      calc=[
          LB("PKB spada ze 100 do 73 w ciągu 4 lat. O ile procent łącznie?",
             27, "(100-73)/100*100", ["(100 − 73) / 100 = 27%"], unit="%"),
          LB("Ceny spadają o 8% rocznie przez 3 lata. O ile procent łącznie spadły?",
             22.13, "(1-0.92**3)*100", ["0,92³ ≈ 0,7787", "Spadek ≈ 22,1%"], unit="%", tol=0.02),
          LB("Kredyt 1000 dolarów zaciągnięty przed deflacją. Po spadku cen o 22,13% jaki jest realny ciężar długu (dolary z początku okresu)?",
             1284.21, "1000/(0.92**3)", ["1000 / 0,77869 ≈ 1284,21"], unit="USD", tol=0.01),
          LB("Bretton Woods: kurs 4 marki za dolara, 35 USD za uncję. Ile marek za uncję złota?",
             140, "4*35", ["4 · 35 = 140 marek"], unit="marek"),
          LB("Phillips: Δw = 10 − 2u. Przy jakim bezrobociu płace się nie zmieniają?",
             5, "10/2", ["0 = 10 − 2u ⇒ u = 5%"], unit="%"),
          LB("Keynes: inwestycje publiczne 2 mld funtów, MPC = 0,6. O ile wzrośnie dochód?",
             5, "2/(1-0.6)", ["2 · 2,5 = 5 mld funtów"], unit="mld"),
      ],
      case=[
          PR("W 1930 r. USA uchwaliły cła Smoota–Hawleya na tysiące towarów. Inne kraje odpowiedziały cłami odwetowymi. Handel światowy na początku lat 30. gwałtownie się skurczył.",
             W("Jak protekcjonizm wpłynął na kryzys?",
               "Pogłębił go, ograniczając handel i eksport", "Zakończył go", "Nie miał wpływu",
               why="Spadek handlu zmniejszał popyt na eksport."),
             W("Jaką lekcję wyciągnięto po wojnie?",
               "Stworzenie GATT i ładu z Bretton Woods ograniczającego wojny handlowe i walutowe", "Zakaz handlu", "Powrót do standardu złota bez zmian",
               why="Współpraca miała zapobiec powtórce lat 30."),
             PF("Wojny handlowe z lat 30. są często przywoływane w dyskusjach o współczesnych cłach.", True,
                why="To przestroga przed spiralą odwetu."),
          ),
          PR("W latach 60. XX w. wielu polityków w USA i Wielkiej Brytanii wierzyło, że mogą trwale obniżyć bezrobocie, akceptując nieco wyższą inflację – zgodnie z krzywą Phillipsa z 1958 r. W latach 70. pojawiła się jednak stagflacja.",
             W("Kto w 1968 r. ostrzegał, że wymiana jest tylko krótkookresowa?",
               "Milton Friedman (i Edmund Phelps)", "John Maynard Keynes", "A. W. Phillips",
               why="Friedman i Phelps wskazali na rolę oczekiwań."),
             W("Co pokazała stagflacja lat 70.?",
               "Że prosta wymiana inflacja–bezrobocie nie jest stabilna", "Że krzywa Phillipsa jest pionowa w krótkim okresie", "Że inflacja zawsze spada",
               why="Wysoka inflacja szła w parze z wysokim bezrobociem."),
             PF("Krzywa Phillipsa z 1958 r. opierała się na danych brytyjskich obejmujących prawie sto lat.", True,
                why="Okres 1861–1957."),
          ),
      ]),

    L(4, "1971–2000: koniec złota, ropa, opcje i płynny złoty",
      "Rozumieć znaczenie zawieszenia wymienialności dolara na złoto (1971), roku 1973 (szok naftowy i model Blacka–Scholesa) oraz roku 2000 (upłynnienie złotego i pęknięcie bańki internetowej).",
      ["1971 – koniec wymienialności dolara na złoto", "1973 – model Blacka–Scholesa i pierwszy szok naftowy", "2000 – płynny kurs złotego i bańka internetowa"],
      [S294, NOB97, NBPH],
      explain=[
          K("1971 – szok Nixona",
            "15 sierpnia 1971 r. prezydent Nixon zawiesił wymienialność dolara na złoto dla zagranicznych banków centralnych. USA miały rosnące deficyty, a rezerwy złota nie pokrywały dolarów za granicą. Do 1973 r. główne waluty przeszły na kursy płynne – koniec systemu z Bretton Woods."),
          K("1973 – ropa i opcje",
            "W październiku 1973 r. arabscy producenci ropy ogłosili embargo – ceny ropy wzrosły kilkukrotnie, a gospodarki Zachodu wpadły w stagflację. W tym samym roku Fischer Black i Myron Scholes (z udziałem Roberta Mertona) opublikowali model wyceny opcji, a w Chicago ruszyła giełda opcji (CBOE). Merton i Scholes otrzymali Nobla w 1997 r. (Black zmarł w 1995 r.)."),
          W("Dlaczego USA zawiesiły wymienialność dolara na złoto w 1971 r.?",
            "Dolarów za granicą było znacznie więcej, niż USA miały złota", "Bo złoto staniało do zera", "Bo MFW tego zażądał",
            why="Groził „run” na amerykańskie rezerwy złota."),
          K("2000 – płynny złoty i bańka internetowa",
            "12 kwietnia 2000 r. Polska zrezygnowała z pasma wahań (wcześniej ±15%) – złoty stał się walutą o kursie płynnym, a NBP skupił się na celu inflacyjnym. W marcu 2000 r. indeks Nasdaq osiągnął szczyt i zaczęło się pękanie bańki spółek internetowych (dot-com), które doprowadziło do spadku kursów technologicznych spółek o kilkadziesiąt procent."),
          K("Wspólny wątek",
            "Wszystkie te wydarzenia zwiększyły rolę rynków: kursy walut zaczęły się kształtować rynkowo, wyceniano i handlowano ryzykiem (opcje), a ceny aktywów okazały się podatne na bańki spekulacyjne."),
          PF("Model Blacka–Scholesa służy do wyceny opcji.", True,
             why="Wycena zależy m.in. od zmienności ceny instrumentu bazowego, czasu i stopy procentowej."),
      ],
      mech=[
          LN("Ułóż wydarzenia chronologicznie.",
             ["Szok Nixona (sierpień 1971)", "Embargo naftowe (październik 1973)", "Nobel dla Mertona i Scholesa (1997)", "Szczyt Nasdaq (marzec 2000)", "Upłynnienie złotego (kwiecień 2000)"],
             why="Od upadku Bretton Woods do płynnego złotego."),
          KT("Do którego roku pasuje?",
             {"1971": ["Zawieszenie wymienialności dolara na złoto"],
              "1973": ["Embargo naftowe", "Publikacja modelu wyceny opcji"],
              "2000": ["Rezygnacja z pasma wahań złotego", "Szczyt bańki internetowej"]},
             why="Łączenie wydarzeń z datami."),
          W("Jaki system kursowy przyjęła Polska w kwietniu 2000 r.?",
            "Kurs płynny", "Currency board", "Kurs sztywny wobec euro",
            why="Zrezygnowano z pasma wahań."),
          PF("Pierwszy szok naftowy przyczynił się do stagflacji w krajach rozwiniętych.", True,
             why="Wzrost kosztów energii podniósł inflację i obniżył produkcję."),
          M("Co łączy wydarzenia z lat 1971–2000?",
            ["Rosnącą rolę rynków w wyznaczaniu kursów", "Rozwój instrumentów do zarządzania ryzykiem", "Powrót do standardu złota", "Podatność cen aktywów na bańki"],
            [0, 1, 3],
            why="Do standardu złota nie powrócono."),
          W("Dlaczego Black nie otrzymał Nagrody Nobla w 1997 r.?",
            "Zmarł w 1995 r., a nagrody nie przyznaje się pośmiertnie", "Bo odmówił", "Bo nie był ekonomistą",
            why="Komitet podkreślił jego wkład w uzasadnieniu."),
      ],
      calc=[
          LB("Przed 1971 r.: 35 USD za uncję. W 1980 r. cena złota przekroczyła 800 USD. Ile razy wzrosła (przy 840 USD)?",
             24, "840/35", ["840 / 35 = 24 razy"], unit="razy"),
          LB("Cena ropy rośnie z 3 do 12 USD za baryłkę. O ile procent?",
             300, "(12/3-1)*100", ["12 / 3 − 1 = 300%"], unit="%"),
          LB("Opcja: prawo kupna akcji po 100 zł. W dniu wygaśnięcia akcja kosztuje 118 zł, opcja kosztowała 7 zł. Ile wynosi zysk netto (zł)?",
             11, "118-100-7", ["Wartość opcji: 18", "18 − 7 = 11 zł"], unit="zł"),
          LB("Gdyby akcja kosztowała 95 zł, ile wyniosłaby strata posiadacza opcji (zł)?",
             7, "7", ["Opcja wygasa bezwartościowo – strata = cena opcji 7 zł"], unit="zł"),
          LB("Indeks Nasdaq spadł z ok. 5000 pkt (2000) do ok. 1100 pkt (2002). O ile procent?",
             78, "(5000-1100)/5000*100", ["3900 / 5000 = 78%"], unit="%"),
          LB("Pasmo wahań złotego ±15% wokół parytetu 4,00. Jaka była górna granica kursu?",
             4.6, "4*1.15", ["4,00 · 1,15 = 4,60"], unit="zł"),
      ],
      case=[
          PR("W 2000 r. inwestorzy masowo kupowali akcje spółek internetowych, które często nie miały zysków. Wyceny opierały się na wizji przyszłego wzrostu. Po szczycie w marcu 2000 r. kursy gwałtownie spadły, a wiele spółek zbankrutowało.",
             W("Jak nazywa się takie zjawisko?",
               "Bańka spekulacyjna", "Deflacja", "Pułapka płynności",
               why="Ceny oderwały się od fundamentów."),
             W("Co zwykle napędza bańkę?",
               "Oczekiwanie dalszego wzrostu cen i naśladowanie innych", "Spadek popytu", "Regulacje ograniczające handel",
               why="Inwestorzy kupują, bo ceny rosną."),
             PF("Po pęknięciu bańki internetowej część firm przetrwała i stała się globalnymi liderami.", True,
                why="Np. Amazon przetrwał mimo spadku kursu."),
          ),
          PR("Od 12 kwietnia 2000 r. kurs złotego kształtuje rynek. W kolejnych latach złoty silnie się wahał – np. umacniał w okresie napływu kapitału przed 2008 r. i gwałtownie osłabił jesienią 2008 r.",
             W("Jaką zaletę kursu płynnego pokazał kryzys 2008 r.?",
               "Osłabienie złotego poprawiło konkurencyjność eksportu i złagodziło szok", "Kurs w ogóle się nie zmienił", "NBP musiał wydać wszystkie rezerwy",
               why="Kurs zadziałał jak amortyzator."),
             W("Jaką wadę kursu płynnego pokazały te lata?",
               "Dużą zmienność, groźną dla kredytobiorców walutowych", "Brak możliwości prowadzenia polityki pieniężnej", "Stały kurs wobec euro",
               why="Kredyty w CHF podrożały wraz z osłabieniem złotego."),
             PF("Upłynnienie złotego umożliwiło NBP skupienie się na celu inflacyjnym.", True,
                why="Bez obowiązku obrony kursu stopy służą inflacji."),
          ),
      ]),

    L(5, "2008 i 2020: kryzysy XXI wieku",
      "Porównywać kryzys finansowy 2008 r. i kryzys pandemiczny 2020 r.: przyczyny, przebieg i reakcje polityki pieniężnej i fiskalnej, także w Polsce.",
      ["2008 – upadek Lehman Brothers", "2020 – pandemia COVID-19"],
      [S285, S("OpenStax, Principles of Economics 3e, 30.4 Using Fiscal Policy to Fight Recession, Unemployment, and Inflation", OS3 + "30-4-using-fiscal-policy-to-fight-recession-unemployment-and-inflation", D)],
      explain=[
          K("2008 – Lehman Brothers",
            "15 września 2008 r. upadł bank inwestycyjny Lehman Brothers. Źródłem kryzysu były kredyty subprime, sekurytyzacja i wysokie lewarowanie. Zaufanie między bankami się załamało, rynek międzybankowy zamarł, a recesja objęła większość krajów rozwiniętych."),
          K("Reakcja na 2008",
            "Banki centralne obniżyły stopy niemal do zera (Fed w grudniu 2008 r. do 0–0,25%), zapewniały płynność i rozpoczęły luzowanie ilościowe (zakupy aktywów). Rządy ratowały banki i uruchomiły pakiety fiskalne. Wprowadzono nowe regulacje (Bazylea III, testy warunków skrajnych)."),
          W("Co było głównym źródłem kryzysu 2008 r.?",
            "Ryzykowne kredyty hipoteczne, sekurytyzacja i nadmierne lewarowanie", "Pandemia", "Embargo naftowe",
            why="Kryzys miał źródło w systemie finansowym."),
          K("2020 – pandemia",
            "Kryzys 2020 r. wywołał szok zewnętrzny: lockdowny jednocześnie ograniczyły podaż (zamknięte zakłady, przerwane łańcuchy dostaw) i popyt (zamknięte usługi, niepewność). Spadek PKB był gwałtowny, ale odbicie szybkie. W Polsce NBP obniżył stopę referencyjną do 0,1%, a rząd uruchomił tarcze antykryzysowe i finansową (PFR)."),
          K("Konsekwencje",
            "Po 2008 r. – długie lata niskich stóp, wolnego wzrostu i reform regulacji. Po 2020 r. – szybkie ożywienie, a następnie wysoka inflacja 2021–2023 (bodźce, zakłócenia podaży, ceny energii po 2022 r.) i podwyżki stóp."),
          PF("Kryzys 2020 r. był przede wszystkim kryzysem bankowym, jak w 2008 r.", False,
             why="Miał źródło zewnętrzne (pandemia), a nie w systemie bankowym."),
      ],
      mech=[
          LN("Ułóż przebieg kryzysu 2008 r.",
             ["Boom kredytów hipotecznych subprime", "Spadek cen domów i niewypłacalność kredytobiorców", "Straty banków na papierach opartych na kredytach", "Upadek Lehman Brothers i panika", "Recesja i masowe interwencje państw"],
             why="Kryzys przeniósł się z rynku nieruchomości do banków i całej gospodarki."),
          KT("2008 czy 2020?",
             {"2008": ["Upadek dużego banku inwestycyjnego", "Kredyty subprime", "Bazylea III jako odpowiedź regulacyjna"],
              "2020": ["Lockdowny i zamknięcie usług", "Tarcze antykryzysowe i finansowa PFR", "Szok jednocześnie podażowy i popytowy"]},
             why="Różne źródła i mechanizmy kryzysów."),
          W("Jakie narzędzie banków centralnych upowszechniło się po 2008 r.?",
            "Luzowanie ilościowe (zakupy aktywów)", "Standard złota", "Kontrola cen",
            why="Przy stopach bliskich zera banki kupowały obligacje."),
          PF("W 2020 r. polityka fiskalna i pieniężna działały jednocześnie ekspansywnie.", True,
             why="Obniżki stóp i duże programy wsparcia."),
          M("Jakie były skutki pandemii dla gospodarki?",
            ["Przerwane łańcuchy dostaw", "Spadek popytu na usługi", "Gwałtowny wzrost turystyki międzynarodowej", "Wzrost deficytów budżetowych"],
            [0, 1, 3],
            why="Turystyka w 2020 r. się załamała."),
          W("Dlaczego odbicie po 2020 r. było szybsze niż po 2008 r.?",
            "Szok był zewnętrzny, a system bankowy pozostał sprawny; pomoc szybko podtrzymała dochody", "Bo stopy były wysokie", "Bo nie było żadnej pomocy",
            why="Brak kryzysu bankowego ułatwił powrót do wzrostu."),
      ],
      calc=[
          LB("RPP w 2020 r. obniżyła stopę referencyjną z 1,5% do 0,1%. O ile punktów bazowych łącznie?",
             140, "(1.5-0.1)*100", ["1,4 p.p. = 140 pb"], unit="pb"),
          LB("Rata odsetkowa kredytu 400 000 zł przy stopie 1,5% + marża 2% (rocznie). Ile wynoszą roczne odsetki (zł)?",
             14000, "400000*0.035", ["400 000 · 3,5% = 14 000 zł"], unit="zł"),
          LB("Po obniżce stopy do 0,1% (marża 2%). Ile wynoszą roczne odsetki (zł)?",
             8400, "400000*0.021", ["400 000 · 2,1% = 8 400 zł"], unit="zł"),
          LB("O ile procent spadły roczne odsetki?",
             40, "(14000-8400)/14000*100", ["5600 / 14 000 = 40%"], unit="%"),
          LB("Bank z kapitałem 30 mld i aktywami 900 mld (lewar 30×) traci 3,5% wartości aktywów. Ile wynosi strata (mld)?",
             31.5, "0.035*900", ["0,035 · 900 = 31,5 mld – więcej niż kapitał"], unit="mld"),
          LB("PKB spada w II kwartale o 9% kw/kw, a w III rośnie o 8% kw/kw. Ile procent poziomu sprzed spadku wynosi PKB po III kwartale?",
             98.28, "0.91*1.08*100", ["0,91 · 1,08 = 0,9828", "≈ 98,3% – jeszcze poniżej poziomu wyjściowego"], unit="%", tol=0.02),
      ],
      case=[
          PR("We wrześniu 2008 r., po upadku Lehman Brothers, banki przestały sobie pożyczać, a koszt kredytu międzybankowego gwałtownie wzrósł. Rządy USA i Europy ratowały banki kapitałem i gwarancjami, a banki centralne zalewały rynki płynnością.",
             W("Dlaczego rynek międzybankowy zamarł?",
               "Banki nie wiedziały, które z nich mają duże straty – utraciły zaufanie", "Bo stopy były zerowe", "Bo zakazano pożyczek",
               why="Asymetria informacji o stratach paraliżowała rynek."),
             W("Jaką rolę pełniły banki centralne?",
               "Pożyczkodawcy ostatniej instancji", "Organizatorów handlu ropą", "Agencji ratingowych",
               why="Dostarczały płynności, by zatrzymać panikę."),
             PF("Kryzys 2008 r. doprowadził do zaostrzenia regulacji bankowych (m.in. Bazylea III).", True,
                why="Podniesiono wymogi kapitałowe i płynnościowe."),
          ),
          PR("W marcu 2020 r. w Polsce zamknięto szkoły, galerie handlowe i wiele usług. W ciągu kilku tygodni RPP obniżyła stopę referencyjną z 1,5% do 0,1%, NBP rozpoczął skup obligacji, a rząd uruchomił tarcze antykryzysowe i tarczę finansową PFR (subwencje dla firm).",
             W("Jaki był charakter szoku?",
               "Jednocześnie podażowy i popytowy, wywołany czynnikiem zewnętrznym", "Wyłącznie bankowy", "Wyłącznie inflacyjny",
               why="Lockdown ograniczał zarówno produkcję, jak i zakupy."),
             W("Jaki był cel tarczy finansowej PFR?",
               "Utrzymanie płynności firm i miejsc pracy", "Zwiększenie podatków", "Zmniejszenie podaży pieniądza",
               why="Subwencje miały zapobiec masowym bankructwom i zwolnieniom."),
             PF("Skup obligacji przez NBP w 2020 r. był formą luzowania ilościowego.", True,
                why="Bank centralny kupował aktywa, zwiększając płynność."),
          ),
      ]),
]
