# -*- coding: utf-8 -*-
# Zrozumienie – Makroekonomia / Szkoły i historia myśli ekonomicznej
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S246 = S("OpenStax, Principles of Economics 3e, 24.6 Keynes’ Law and Say’s Law in the AD-AS Model", OS3 + "24-6-keynes-law-and-says-law-in-the-ad-as-model", D)
S254 = S("OpenStax, Principles of Economics 3e, 25.4 The Keynesian Perspective on Market Forces", OS3 + "25-4-the-keynesian-perspective-on-market-forces", D)
S261 = S("OpenStax, Principles of Economics 3e, 26.1 The Building Blocks of Neoclassical Analysis", OS3 + "26-1-the-building-blocks-of-neoclassical-analysis", D)
S262 = S("OpenStax, Principles of Economics 3e, 26.2 The Policy Implications of the Neoclassical Perspective", OS3 + "26-2-the-policy-implications-of-the-neoclassical-perspective", D)
S263 = S("OpenStax, Principles of Economics 3e, 26.3 Balancing Keynesian and Neoclassical Models", OS3 + "26-3-balancing-keynesian-and-neoclassical-models", D)
S331 = S("OpenStax, Principles of Economics 3e, 33.1 Absolute and Comparative Advantage", OS3 + "33-1-absolute-and-comparative-advantage", D)
S61 = S("OpenStax, Principles of Economics 3e, 6.1 Consumption Choices", OS3 + "6-1-consumption-choices", D)
NOB76 = S("Nobel Prize – The Prize in Economic Sciences 1976 (Milton Friedman)", "https://www.nobelprize.org/prizes/economic-sciences/1976/summary/", D)
NOB95 = S("Nobel Prize – The Prize in Economic Sciences 1995 (Robert E. Lucas Jr.)", "https://www.nobelprize.org/prizes/economic-sciences/1995/summary/", D)
NOB09 = S("Nobel Prize – The Prize in Economic Sciences 2009 (Ostrom, Williamson)", "https://www.nobelprize.org/prizes/economic-sciences/2009/summary/", D)
NOB74 = S("Nobel Prize – The Prize in Economic Sciences 1974 (Myrdal, Hayek)", "https://www.nobelprize.org/prizes/economic-sciences/1974/summary/", D)
KONST = S("Konstytucja RP, art. 20 (społeczna gospodarka rynkowa) – tekst, Dz.U. 1997 nr 78 poz. 483 (Sejm, ELI)", "https://api.sejm.gov.pl/eli/acts/DU/1997/483/text.pdf", D)

LESSONS = [
    L(1, "Od merkantylizmu do klasyków",
      "Rozumieć, jak merkantyliści, fizjokraci i klasycy (Smith, Ricardo, Say, Malthus) odpowiadali na pytanie o źródła bogactwa narodów i rolę państwa.",
      ["Merkantylizm", "Fizjokratyzm", "Szkoła klasyczna"],
      [S331, S246],
      explain=[
          K("Merkantylizm (XVI–XVIII w.)",
            "Bogactwo kraju to kruszec (złoto i srebro). Należy dążyć do nadwyżki w handlu: wspierać eksport, ograniczać import cłami, rozwijać manufaktury i kolonie. Państwo aktywnie kieruje gospodarką (np. Colbert we Francji). Handel traktowano jako grę o sumie zerowej."),
          K("Fizjokratyzm (Francja, XVIII w.)",
            "François Quesnay i jego „Tablica ekonomiczna”: tylko rolnictwo (ziemia) tworzy produkt czysty – nadwyżkę ponad koszty. Przemysł i handel są „jałowe” (przetwarzają, ale nie tworzą nadwyżki). Hasło „laissez faire, laissez passer” – wolność gospodarcza i jeden podatek od ziemi."),
          W("Która szkoła uważała, że nadwyżkę tworzy wyłącznie rolnictwo?",
            "Fizjokratyzm", "Merkantylizm", "Szkoła klasyczna",
            why="Fizjokraci uważali ziemię za jedyne źródło produktu czystego."),
          K("Szkoła klasyczna",
            "Adam Smith („Bogactwo narodów”, 1776): źródłem bogactwa jest praca i jej podział; „niewidzialna ręka” rynku koordynuje działania jednostek kierujących się interesem własnym. David Ricardo: przewaga komparatywna, teoria renty gruntowej. Jean-Baptiste Say: podaż tworzy własny popyt. Thomas Malthus: ludność rośnie szybciej niż żywność. Rola państwa: obrona, sądownictwo, niektóre dobra publiczne."),
          K("Wspólne cechy klasyków",
            "Wartość wynika z pracy (teoria wartości opartej na pracy), rynki same dążą do równowagi, pieniądz jest neutralny (dychotomia), wolny handel jest korzystny dla wszystkich stron. Spór z merkantylistami: handel nie jest grą o sumie zerowej."),
          PF("Merkantyliści uważali handel za grę, w której obie strony mogą zyskać.", False,
             why="Traktowali go jako grę o sumie zerowej – zysk jednego to strata drugiego; korzyści obu stron podkreślali klasycy."),
      ],
      mech=[
          KT("Która szkoła?",
             {"Merkantylizm": ["Nadwyżka handlowa i gromadzenie złota", "Cła na import gotowych wyrobów"],
              "Fizjokratyzm": ["Tablica ekonomiczna Quesnaya", "Jedyny podatek od ziemi"],
              "Szkoła klasyczna": ["Niewidzialna ręka rynku", "Przewaga komparatywna Ricardo", "Prawo Saya"]},
             why="Każda szkoła inaczej widziała źródło bogactwa."),
          LN("Ułóż szkoły chronologicznie.",
             ["Merkantylizm", "Fizjokratyzm", "Szkoła klasyczna (Smith)", "Rewolucja marginalistyczna", "Keynesizm"],
             why="Od XVI do XX wieku."),
          W("Co według Smitha jest głównym źródłem wzrostu wydajności?",
            "Podział pracy (specjalizacja)", "Gromadzenie złota", "Wyłącznie rolnictwo",
            why="Przykład fabryki szpilek w „Bogactwie narodów”."),
          PF("Prawo Saya głosi, że podaż tworzy własny popyt.", True,
             why="Dochody z produkcji są wydawane, więc ogólna nadprodukcja jest niemożliwa."),
          M("Które idee są zgodne ze szkołą klasyczną?",
            ["Wolny handel jest korzystny", "Rynek dąży do równowagi", "Państwo powinno gromadzić złoto", "Pieniądz w długim okresie jest neutralny"],
            [0, 1, 3],
            why="Gromadzenie złota to idea merkantylistów."),
          W("Jaki pesymistyczny wniosek sformułował Malthus?",
            "Ludność rośnie szybciej niż produkcja żywności, co utrzymuje płace na poziomie minimum", "Handel zawsze szkodzi", "Pieniądz jest zawsze nieneutralny",
            why="Postęp techniczny w rolnictwie później podważył tę prognozę."),
      ],
      calc=[
          LB("Merkantylistyczny kraj eksportuje za 120 tys. uncji srebra, importuje za 90 tys. Ile uncji przybywa w skarbcu?",
             30000, "120000-90000", ["120 000 − 90 000 = 30 000 uncji"], unit="uncji"),
          LB("Fabryka szpilek Smitha: 10 robotników z podziałem pracy robi 48 000 szpilek dziennie. Ile szpilek przypada na robotnika?",
             4800, "48000/10", ["48 000 / 10 = 4800"], unit="szt."),
          LB("Bez podziału pracy robotnik robi 20 szpilek dziennie. Ile razy wzrosła wydajność?",
             240, "4800/20", ["4800 / 20 = 240 razy"], unit="razy"),
          LB("Renta Ricarda: ziemia A daje 30 t, ziemia B (najgorsza uprawiana) 18 t przy tych samych nakładach. Ile wynosi renta z ziemi A (t)?",
             12, "30-18", ["Renta = 30 − 18 = 12 t"], unit="t"),
          LB("Malthus: ludność podwaja się co 25 lat (1, 2, 4, 8…), żywność rośnie o 1 jednostkę co 25 lat (1, 2, 3, 4…). Ile jednostek ludności przypada na jednostkę żywności po 75 latach?",
             2, "8/4", ["Ludność: 8, żywność: 4", "8 / 4 = 2"], unit=""),
          LB("Podatek jedyny fizjokratów: produkt czysty ziemi 500, stawka 20%. Ile wynosi podatek?",
             100, "0.2*500", ["0,2 · 500 = 100"], unit=""),
      ],
      case=[
          PR("W XVII-wiecznej Francji minister Colbert wspierał królewskie manufaktury, nakładał wysokie cła na import gotowych wyrobów i zabiegał o rozwój floty handlowej i kolonii.",
             W("Jaką politykę prowadził Colbert?",
               "Merkantylistyczną", "Fizjokratyczną", "Liberalną (klasyczną)",
               why="Wspieranie eksportu i ograniczanie importu to istota merkantylizmu."),
             W("Jak oceniłby tę politykę Adam Smith?",
               "Krytycznie – ograniczanie handlu zmniejsza korzyści z podziału pracy", "Pozytywnie – złoto to bogactwo", "Obojętnie",
               why="Smith krytykował merkantylizm w „Bogactwie narodów”."),
             PF("Cła merkantylistyczne podnosiły ceny dla krajowych konsumentów.", True,
                why="Ograniczony import oznacza wyższe ceny."),
          ),
          PR("W Wielkiej Brytanii w 1846 r. zniesiono „ustawy zbożowe” (Corn Laws), które ograniczały import zboża i podtrzymywały wysokie ceny chleba korzystne dla właścicieli ziemskich. Za zniesieniem opowiadali się przemysłowcy i zwolennicy idei Ricarda.",
             W("Kto zyskiwał na ustawach zbożowych?",
               "Właściciele ziemscy (wyższe renty)", "Robotnicy kupujący chleb", "Przemysłowcy",
               why="Wysokie ceny zboża podnosiły renty gruntowe."),
             W("Jaki argument Ricarda przemawiał za ich zniesieniem?",
               "Wolny handel i przewaga komparatywna – tańsza żywność, niższe płace nominalne i wyższe zyski przemysłu", "Gromadzenie złota", "Ochrona rolnictwa jako jedynego źródła bogactwa",
               why="Ricardo uważał, że wysokie ceny zboża hamują akumulację kapitału."),
             PF("Zniesienie ustaw zbożowych było symbolem zwycięstwa idei wolnego handlu w XIX-wiecznej Anglii.", True,
                why="Otworzyło okres liberalizacji handlu."),
          ),
      ]),

    L(2, "Marginaliści, austriacy i instytucjonaliści",
      "Rozumieć rewolucję marginalistyczną (wartość z użyteczności krańcowej), dorobek szkoły austriackiej oraz instytucjonalizmu i nowej ekonomii instytucjonalnej.",
      ["Rewolucja marginalistyczna", "Szkoła austriacka", "Instytucjonalizm i nowa ekonomia instytucjonalna"],
      [S61, NOB74, NOB09],
      explain=[
          K("Rewolucja marginalistyczna (lata 70. XIX w.)",
            "Jevons, Menger i Walras niezależnie od siebie wyjaśnili wartość nie kosztem pracy, lecz użytecznością krańcową – zadowoleniem z ostatniej jednostki dobra. Rozwiązało to „paradoks wody i diamentów”: woda jest niezbędna, ale obfita (niska użyteczność krańcowa), diamenty – rzadkie. Narodziła się ekonomia neoklasyczna z analizą „na marginesie”."),
          K("Szkoła austriacka",
            "Menger, Böhm-Bawerk, Mises, Hayek: subiektywna wartość, rola czasu i kapitału, przedsiębiorczość, rozproszona wiedza (ceny jako sygnały informacji), krytyka planowania centralnego (spór o kalkulację ekonomiczną w socjalizmie). Teoria cyklu: sztucznie tani kredyt prowadzi do malinwestycji. Hayek – Nobel 1974."),
          W("Jak marginaliści wyjaśnili paradoks wody i diamentów?",
            "Cena zależy od użyteczności krańcowej, a ta jest niska dla obfitej wody", "Diamenty wymagają więcej pracy", "Woda jest bezużyteczna",
            why="Liczy się użyteczność ostatniej jednostki, a nie całkowita."),
          K("Instytucjonalizm",
            "„Stary” instytucjonalizm (Veblen, Commons): gospodarkę kształtują zwyczaje, prawo i instytucje; krytyka modelu racjonalnego homo oeconomicus (Veblen – konsumpcja na pokaz). Nowa ekonomia instytucjonalna (Coase, North, Williamson, Ostrom): koszty transakcyjne, prawa własności, kontrakty – wyjaśnia, dlaczego istnieją firmy i jak instytucje wpływają na wzrost."),
          K("Znaczenie dla dzisiejszej ekonomii",
            "Marginalizm stał się fundamentem mikroekonomii. Idee austriaków o informacji i przedsiębiorczości wpłynęły na teorię rynku. Nowa ekonomia instytucjonalna tłumaczy różnice w rozwoju krajów jakością instytucji (prawa własności, rządy prawa)."),
          PF("Szkoła austriacka popierała centralne planowanie jako najlepszy sposób alokacji zasobów.", False,
             why="Krytykowała je – planista nie ma dostępu do rozproszonej wiedzy, którą przekazują ceny."),
      ],
      mech=[
          KT("Która szkoła?",
             {"Marginalizm": ["Wartość z użyteczności krańcowej", "Jevons, Menger, Walras"],
              "Szkoła austriacka": ["Spór o kalkulację ekonomiczną w socjalizmie", "Ceny jako nośnik rozproszonej wiedzy"],
              "Instytucjonalizm": ["Konsumpcja na pokaz (Veblen)", "Koszty transakcyjne i prawa własności (Coase)"]},
             why="Każda szkoła wniosła inny kluczowy pomysł."),
          LN("Ułóż argument Hayeka przeciw planowaniu centralnemu.",
             ["Wiedza o potrzebach i możliwościach jest rozproszona wśród milionów ludzi", "Żaden planista nie może jej zebrać", "Ceny rynkowe przekazują tę wiedzę w skondensowanej formie", "Bez wolnych cen alokacja jest błędna", "Planowanie prowadzi do niedoborów i marnotrawstwa"],
             why="Ceny jako system informacyjny."),
          W("Dlaczego według Coase’a istnieją firmy?",
            "Bo koordynacja wewnątrz firmy bywa tańsza niż zawieranie umów na rynku (koszty transakcyjne)", "Bo rynek nie istnieje", "Bo państwo je tworzy",
            why="Firma ogranicza koszty negocjacji i kontraktów."),
          PF("Elinor Ostrom wykazała, że wspólne zasoby mogą być skutecznie zarządzane przez społeczności lokalne.", True,
             why="Za te badania otrzymała Nagrodę Nobla w 2009 r."),
          M("Które idee pochodzą od nowej ekonomii instytucjonalnej?",
            ["Koszty transakcyjne", "Znaczenie praw własności", "Wartość wyłącznie z pracy", "Rola instytucji we wzroście (North)"],
            [0, 1, 3],
            why="Teoria wartości opartej na pracy to dorobek klasyków."),
          W("Co oznacza „analiza marginalna”?",
            "Porównywanie dodatkowych korzyści i kosztów kolejnej jednostki", "Analiza tylko dużych firm", "Badanie historii gospodarczej",
            why="Decyzje podejmuje się „na marginesie”."),
      ],
      calc=[
          LB("Użyteczność całkowita z 1, 2, 3 szklanek wody: 20, 35, 45. Ile wynosi użyteczność krańcowa trzeciej szklanki?",
             10, "45-35", ["45 − 35 = 10"], unit=""),
          LB("Ile wynosi użyteczność krańcowa drugiej szklanki?",
             15, "35-20", ["35 − 20 = 15"], unit=""),
          LB("Konsument w równowadze: MU kawy 30 przy cenie 10 zł, MU herbaty 12. Jaka cena herbaty zapewnia równość MU/P?",
             4, "12/(30/10)", ["MU/P kawy = 3", "12 / P = 3 ⇒ P = 4 zł"], unit="zł"),
          LB("Koszt zawarcia umowy na rynku: 2000 zł, liczba umów rocznie: 50. Zatrudnienie pracownika kosztuje dodatkowo 60 000 zł rocznie. Ile wynoszą koszty transakcyjne rynku?",
             100000, "2000*50", ["2000 · 50 = 100 000 zł"], unit="zł"),
          LB("O ile zł taniej jest zatrudnić pracownika niż zawierać umowy?",
             40000, "2000*50-60000", ["100 000 − 60 000 = 40 000 zł"], unit="zł"),
          LB("Pastwisko wspólne utrzyma 100 owiec. 5 rodzin ustala równy limit. Ile owiec może mieć każda rodzina?",
             20, "100/5", ["100 / 5 = 20"], unit=""),
      ],
      case=[
          PR("W latach 20. i 30. XX w. toczył się „spór o kalkulację ekonomiczną”. Mises i Hayek twierdzili, że bez rynkowych cen środków produkcji planista nie może racjonalnie liczyć kosztów. Oskar Lange odpowiadał, że planista może symulować rynek metodą prób i błędów.",
             W("Jaki był główny argument austriaków?",
               "Bez cen rynkowych brakuje informacji potrzebnej do racjonalnej alokacji", "Planowanie jest zbyt tanie", "Rynki zawsze zawodzą",
               why="Ceny agregują rozproszoną wiedzę."),
             W("Kim był Oskar Lange?",
               "Polskim ekonomistą, zwolennikiem „socjalizmu rynkowego”", "Austriackim przedsiębiorcą", "Twórcą monetaryzmu",
               why="Lange był jednym z głównych uczestników sporu."),
             PF("Doświadczenia gospodarek centralnie planowanych często wiązały się z niedoborami towarów.", True,
                why="Ceny nie odzwierciedlały rzadkości dóbr."),
          ),
          PR("Thorstein Veblen pisał w 1899 r. o „klasie próżniaczej”, która kupuje drogie dobra, by pokazać swój status. Uważał, że ekonomia powinna badać zwyczaje i instytucje, a nie tylko racjonalne decyzje.",
             W("Do jakiej szkoły należał Veblen?",
               "Instytucjonalizmu", "Szkoły austriackiej", "Monetaryzmu",
               why="Badał wpływ zwyczajów i instytucji na gospodarkę."),
             W("Jak nazywa się dobro, którego popyt rośnie wraz z ceną z powodu prestiżu?",
               "Dobro Veblena", "Dobro Giffena", "Dobro podrzędne",
               why="Wyższa cena zwiększa jego wartość jako symbolu statusu."),
             PF("Veblen krytykował założenie, że ludzie zawsze podejmują decyzje wyłącznie racjonalnie.", True,
                why="Podkreślał rolę naśladownictwa i statusu."),
          ),
      ]),

    L(3, "Keynesizm kontra monetaryzm",
      "Porównywać keynesizm i monetaryzm: poglądy na stabilność rynku, skuteczność polityki fiskalnej i pieniężnej oraz regułę stałego wzrostu pieniądza.",
      ["Keynesizm", "Monetaryzm", "Oczekiwania adaptacyjne i racjonalne"],
      [S254, S262, NOB76],
      explain=[
          K("Keynesizm",
            "John Maynard Keynes („Ogólna teoria zatrudnienia, procentu i pieniądza”, 1936): gospodarka może długo tkwić w równowadze z bezrobociem, bo płace i ceny są sztywne, a popyt niestabilny (zwierzęce instynkty inwestorów). Państwo powinno stabilizować popyt – zwłaszcza polityką fiskalną w recesji. „W długim okresie wszyscy będziemy martwi.”"),
          K("Monetaryzm",
            "Milton Friedman (Nobel 1976): gospodarka prywatna jest w zasadzie stabilna; główne zaburzenia wynikają z błędów polityki pieniężnej (Wielki Kryzys jako skutek skurczenia podaży pieniądza). Inflacja jest „zawsze i wszędzie zjawiskiem pieniężnym”. Zamiast aktywnego sterowania – reguła stałego wzrostu podaży pieniądza (np. 3–5% rocznie)."),
          W("Według Friedmana główną przyczyną Wielkiego Kryzysu było:",
            "Gwałtowne skurczenie się podaży pieniądza", "Zbyt wysokie wydatki rządowe", "Postęp techniczny",
            why="Friedman i Schwartz w „Historii monetarnej USA” obwiniali politykę Fed."),
          K("Główne różnice",
            "Keyneści: rynek niestabilny, polityka fiskalna skuteczna, opóźnienia małe, aktywna polityka. Monetaryści: rynek stabilny, polityka fiskalna wypycha inwestycje, opóźnienia polityki długie i zmienne – lepiej stosować reguły. Krzywa Phillipsa: keyneści – wymiana, monetaryści – tylko krótkookresowa (oczekiwania adaptacyjne)."),
          K("Oczekiwania adaptacyjne",
            "Ludzie przewidują przyszłą inflację na podstawie przeszłej i stopniowo korygują błędy. Dlatego według monetarystów ekspansja może obniżyć bezrobocie tylko przejściowo – do czasu, aż oczekiwania się dostosują."),
          PF("Monetaryści uważali, że aktywne „dostrajanie” gospodarki polityką pieniężną jest skuteczne, bo opóźnienia są krótkie.", False,
             why="Uważali opóźnienia za długie i zmienne – dlatego postulowali regułę."),
      ],
      mech=[
          KT("Keynesizm czy monetaryzm?",
             {"Keynesizm": ["Gospodarka może długo tkwić w bezrobociu", "Ekspansja fiskalna w recesji", "Sztywne płace i ceny"],
              "Monetaryzm": ["Reguła stałego wzrostu podaży pieniądza", "Inflacja to zjawisko pieniężne", "Długie i zmienne opóźnienia polityki"]},
             why="Spór dotyczy stabilności rynku i roli państwa."),
          LN("Ułóż argument monetarystów przeciw dostrajaniu gospodarki.",
             ["Rząd rozpoznaje recesję z opóźnieniem", "Decyzja wymaga czasu", "Polityka działa z długim i zmiennym opóźnieniem", "Bodziec może zadziałać, gdy gospodarka już się ożywia", "Polityka wzmacnia wahania zamiast je łagodzić"],
             why="Dlatego proponowali reguły zamiast uznaniowości."),
          W("Jakie narzędzie keyneści uważali za najskuteczniejsze w głębokiej recesji?",
            "Politykę fiskalną (wydatki publiczne)", "Złoty standard", "Ograniczenie podaży pieniądza",
            why="W pułapce płynności polityka pieniężna słabnie."),
          PF("Wysoka inflacja lat 70. XX w. zwiększyła popularność monetaryzmu.", True,
             why="Keynesowska polityka nie radziła sobie ze stagflacją."),
          M("Które poglądy łączą się z monetaryzmem?",
            ["Inflacja jest zawsze i wszędzie zjawiskiem pieniężnym", "Prywatna gospodarka jest w zasadzie stabilna", "Mnożnik fiskalny jest bardzo duży", "Polityka powinna opierać się na regułach"],
            [0, 1, 3],
            why="Duży mnożnik fiskalny to pogląd keynesowski."),
          W("Jak „W długim okresie wszyscy będziemy martwi” rozumieć w kontekście sporu?",
            "Keynes krytykował czekanie, aż rynek sam się dostosuje", "Keynes opowiadał się za regułą pieniężną", "Keynes chwalił prawo Saya",
            why="Uważał, że nie można bezczynnie czekać na długookresową równowagę."),
      ],
      calc=[
          LB("Teoria ilościowa: wzrost realnego PKB 3%, V stałe, reguła Friedmana: M rośnie o 5%. Ile wyniesie inflacja?",
             2, "5-3", ["%ΔP ≈ 5 − 3 = 2%"], unit="%"),
          LB("Keynesowski mnożnik: krańcowa skłonność do konsumpcji 0,75. Ile wynosi mnożnik wydatków?",
             4, "1/(1-0.75)", ["1 / (1 − 0,75) = 4"], unit=""),
          LB("Rząd zwiększa wydatki o 20 mld zł. O ile wzrośnie PKB według prostego mnożnika?",
             80, "4*20", ["4 · 20 = 80 mld zł"], unit="mld zł"),
          LB("Monetarysta szacuje, że wypychanie zmniejszy efekt o 75%. Ile wyniesie przyrost PKB?",
             20, "80*0.25", ["80 · 0,25 = 20 mld zł"], unit="mld zł"),
          LB("Oczekiwania adaptacyjne: πᵉ(t) = πᵉ(t−1) + 0,5·(π(t−1) − πᵉ(t−1)). πᵉ(t−1) = 2%, π(t−1) = 6%. Ile wynosi πᵉ(t)?",
             4, "2+0.5*(6-2)", ["2 + 0,5 · 4 = 4%"], unit="%"),
          LB("Podaż pieniądza w USA spadła w latach 1929–1933 o ok. jedną trzecią. Jeśli V i Y byłyby stałe, o ile procent spadłyby ceny?",
             33.33, "100/3", ["%ΔP ≈ %ΔM ≈ −33,3%"], unit="%", tol=0.03),
      ],
      case=[
          PR("W latach 1979–1982 bank centralny Wielkiej Brytanii i Fed w USA – pod wpływem idei monetarystycznych – skupiły się na ograniczaniu wzrostu podaży pieniądza, by zwalczyć wysoką inflację. Inflacja spadła, ale bezrobocie znacząco wzrosło, a ścisłe cele dla agregatów pieniężnych okazały się trudne do realizacji, bo szybkość obiegu pieniądza była niestabilna.",
             W("Jaką ideę monetarystyczną stosowano?",
               "Kontrolę tempa wzrostu podaży pieniądza", "Ekspansję fiskalną", "Kurs stały wobec złota",
               why="Celem było ograniczenie inflacji przez pieniądz."),
             W("Dlaczego cele dla agregatów pieniężnych porzucono?",
               "Szybkość obiegu (V) okazała się niestabilna", "Bo inflacja wzrosła do 100%", "Bo pieniądz przestał istnieć",
               why="Przy zmiennym V związek M z cenami jest luźny."),
             PF("Dziś większość banków centralnych steruje stopą procentową i ma cel inflacyjny, a nie cel ilościowy dla podaży pieniądza.", True,
                why="Tak działa m.in. NBP, EBC i Fed."),
          ),
          PR("W czasie pandemii w 2020 r. rządy wielu krajów uruchomiły ogromne pakiety pomocowe, a banki centralne obniżyły stopy i kupowały obligacje. W latach 2021–2022 inflacja gwałtownie wzrosła.",
             W("Który element reakcji był typowo keynesowski?",
               "Duże pakiety fiskalne wspierające popyt", "Reguła stałego wzrostu pieniądza", "Powrót do standardu złota",
               why="Keynesiści zalecają ekspansję fiskalną w recesji."),
             W("Jak monetarysta tłumaczyłby późniejszą inflację?",
               "Szybkim wzrostem podaży pieniądza", "Spadkiem podaży pieniądza", "Brakiem jakichkolwiek bodźców",
               why="Inflacja to zjawisko pieniężne."),
             PF("Na inflację 2021–2022 wpłynęły także szoki podażowe (łańcuchy dostaw, energia).", True,
                why="Większość ekonomistów wskazuje zarówno czynniki popytowe, jak i podażowe."),
          ),
      ]),

    L(4, "Racjonalne oczekiwania i nowa synteza",
      "Rozumieć nową ekonomię klasyczną, krytykę Lucasa, różnicę między oczekiwaniami adaptacyjnymi a racjonalnymi oraz odpowiedź nowej ekonomii keynesowskiej.",
      ["Nowa ekonomia klasyczna (szkoła racjonalnych oczekiwań)", "Krytyka Lucasa", "Oczekiwania adaptacyjne i racjonalne", "Nowa ekonomia keynesowska"],
      [S261, S263, NOB95],
      explain=[
          K("Racjonalne oczekiwania",
            "Ludzie wykorzystują wszystkie dostępne informacje, w tym wiedzę o polityce rządu, i nie popełniają systematycznych błędów. Mogą się mylić, ale błędy są przypadkowe. To przeciwieństwo oczekiwań adaptacyjnych, w których błędy są systematyczne i korygowane powoli."),
          K("Nowa ekonomia klasyczna",
            "Lucas, Sargent, Barro: przy elastycznych cenach i racjonalnych oczekiwaniach przewidywalna polityka pieniężna nie wpływa na produkcję (twierdzenie o nieskuteczności polityki). Wpływ ma tylko polityka zaskakująca. Ekwiwalencja ricardiańska (Barro): obniżka podatków finansowana długiem nie zwiększa konsumpcji, bo ludzie oszczędzają na przyszłe podatki."),
          W("Według nowej ekonomii klasycznej zapowiedziana z wyprzedzeniem ekspansja monetarna:",
            "Podniesie ceny, ale nie produkcję", "Trwale zwiększy produkcję", "Obniży ceny",
            why="Oczekiwania dostosowują się od razu."),
          K("Krytyka Lucasa",
            "Lucas (Nobel 1995) zauważył, że parametry modeli opartych na przeszłych danych zmieniają się, gdy zmienia się polityka – bo ludzie zmieniają zachowanie. Np. krzywa Phillipsa „znikła”, gdy próbowano ją wykorzystywać. Wniosek: modele muszą opierać się na zachowaniach jednostek (mikropodstawach)."),
          K("Nowa ekonomia keynesowska",
            "Mankiw, Akerlof, Stiglitz, Blanchard: przyjmują racjonalne oczekiwania i mikropodstawy, ale wskazują na realne źródła sztywności: koszty menu, kontrakty rozłożone w czasie, płace efektywnościowe, niedoskonałą konkurencję. Dlatego polityka popytowa jest skuteczna w krótkim okresie. Dzisiejsza „nowa synteza neoklasyczna” łączy obie tradycje (modele DSGE)."),
          PF("Nowa ekonomia keynesowska odrzuca racjonalne oczekiwania.", False,
             why="Przyjmuje je, ale dodaje sztywności cen i płac."),
      ],
      mech=[
          KT("Oczekiwania adaptacyjne czy racjonalne?",
             {"Adaptacyjne": ["Prognoza inflacji = ubiegłoroczna inflacja", "Błędy są systematyczne i korygowane powoli"],
              "Racjonalne": ["Ludzie uwzględniają zapowiedzi banku centralnego", "Błędy są przypadkowe, bez systematycznego wzorca"]},
             why="Różnią się zakresem wykorzystywanych informacji."),
          LN("Ułóż logikę krytyki Lucasa.",
             ["Ekonomiści szacują zależności na danych z przeszłości", "Rząd zmienia politykę, by wykorzystać te zależności", "Ludzie zmieniają oczekiwania i zachowanie", "Szacowane zależności przestają obowiązywać", "Polityka nie przynosi przewidywanego efektu"],
             why="Parametry modeli zależą od polityki."),
          W("Co według ekwiwalencji ricardiańskiej zrobią ludzie po obniżce podatków finansowanej długiem?",
            "Zaoszczędzą większość, przewidując przyszłe podatki na spłatę długu", "Wydadzą całość", "Zaciągną kredyty",
            why="Dług dziś to podatki jutro."),
          PF("Koszty menu są jednym z wyjaśnień sztywności cen w nowej ekonomii keynesowskiej.", True,
             why="Nawet niewielkie koszty zmiany cen mogą mieć duże skutki makroekonomiczne."),
          M("Które idee łączą się z nową ekonomią klasyczną?",
            ["Racjonalne oczekiwania", "Elastyczne ceny i płace", "Sztywne płace przez kontrakty", "Nieskuteczność przewidywalnej polityki"],
            [0, 1, 3],
            why="Sztywne płace to argument nowych keynesistów."),
          W("Czym są modele DSGE?",
            "Dynamicznymi modelami równowagi ogólnej z mikropodstawami, używanymi m.in. przez banki centralne", "Prostymi modelami mnożnika", "Modelami handlu zagranicznego",
            why="Łączą elementy nowej ekonomii klasycznej i keynesowskiej."),
      ],
      calc=[
          LB("Obniżka podatków 50 mld zł finansowana długiem. Pełna ekwiwalencja ricardiańska: o ile rosną oszczędności prywatne (mld zł)?",
             50, "50", ["Ludzie oszczędzają całą obniżkę na przyszłe podatki"], unit="mld zł"),
          LB("Bez ekwiwalencji, przy krańcowej skłonności do konsumpcji 0,8, o ile wzrośnie konsumpcja (pierwsza runda, mld zł)?",
             40, "0.8*50", ["0,8 · 50 = 40 mld zł"], unit="mld zł"),
          LB("Oczekiwania racjonalne: bank zapowiada wzrost M o 6% przy wzroście PKB potencjalnego 2%. Jaką inflację przewidują ludzie (teoria ilościowa)?",
             4, "6-2", ["≈ 6 − 2 = 4%"], unit="%"),
          LB("Krzywa Lucasa: Y = 1000 + 40(P − Pᵉ). Bank niespodziewanie podnosi P do 105, Pᵉ = 103. Ile wynosi Y?",
             1080, "1000+40*(105-103)", ["1000 + 40 · 2 = 1080"], unit=""),
          LB("Koszt zmiany cennika: 500 zł. Zysk z dostosowania ceny: 300 zł. Ile wynosi strata, gdyby firma zmieniła cenę (zł)?",
             200, "500-300", ["500 − 300 = 200 zł – firma nie zmieni ceny (sztywność)"], unit="zł"),
          LB("Połowa firm zmienia ceny co kwartał, połowa raz w roku. Inflacja przyspiesza o 4 p.p. Jaki odsetek firm dostosuje ceny w pierwszym kwartale?",
             62.5, "50+50*0.25", ["Kwartalne: 50%", "Roczne (¼ z nich w kwartale): 12,5%", "Razem 62,5%"], unit="%"),
      ],
      case=[
          PR("Na początku lat 70. XX w. politycy wierzyli, że mogą trwale utrzymać niskie bezrobocie kosztem nieco wyższej inflacji (krzywa Phillipsa). Po kilku latach inflacja była wysoka, a bezrobocie nie spadło.",
             W("Który pomysł wyjaśnia, dlaczego zależność „znikła”?",
               "Krytyka Lucasa – ludzie dostosowali oczekiwania do nowej polityki", "Prawo Saya", "Paradoks Leontiefa",
               why="Zmiana polityki zmieniła zachowanie i parametry modelu."),
             W("Jakie oczekiwania sprawiają, że polityka nie może systematycznie oszukiwać ludzi?",
               "Racjonalne", "Statyczne", "Żadne",
               why="Ludzie uczą się reguł polityki."),
             PF("Doświadczenie lat 70. przyczyniło się do rozwoju nowej ekonomii klasycznej.", True,
                why="Stagflacja podważyła ówczesny keynesizm."),
          ),
          PR("Bank centralny pewnego kraju publikuje prognozy, regularnie tłumaczy decyzje i konsekwentnie dąży do celu inflacyjnego 2%. Gdy następuje szok cenowy, oczekiwania inflacyjne prawie się nie zmieniają.",
             W("Dlaczego komunikacja banku centralnego jest tak ważna?",
               "Kształtuje racjonalne oczekiwania – wiarygodny bank łatwiej utrzymuje niską inflację", "Bo zastępuje stopy procentowe", "Nie ma znaczenia",
               why="Przy racjonalnych oczekiwaniach wiarygodność obniża koszt walki z inflacją."),
             W("Która szkoła podkreśla, że mimo to polityka pieniężna wpływa na produkcję w krótkim okresie?",
               "Nowa ekonomia keynesowska", "Nowa ekonomia klasyczna", "Fizjokratyzm",
               why="Sztywności cen dają polityce realne skutki krótkookresowe."),
             PF("Współczesne cele inflacyjne łączą idee obu nurtów – rolę oczekiwań i krótkookresowe skutki polityki.", True,
                why="To przejaw nowej syntezy neoklasycznej."),
          ),
      ]),

    L(5, "Spory współczesne i metoda ekonomii",
      "Rozumieć ordoliberalizm i społeczną gospodarkę rynkową, neoliberalizm i konsensus waszyngtoński, nurty heterodoksyjne oraz spory metodologiczne (instrumentalizm, paradygmat, matematyzacja, eklektyzm), także w polskiej ekonomii.",
      ["Ordoliberalizm i społeczna gospodarka rynkowa", "Neoliberalizm", "Konsensus waszyngtoński a kraje rozwijające się", "Ekonomia heterodoksyjna (marksistowska, feministyczna, ekologiczna)", "Instrumentalizm (M. Friedman)", "Paradygmat (w nauce)", "Matematyzacja ekonomii – spór", "Eklektyzm (racjonalny, refleksyjny)", "Szkoły myśli ekonomicznej w polskiej ekonomii akademickiej"],
      [KONST, S263, S("Nobel Prize – The Prize in Economic Sciences 2001 (Akerlof, Spence, Stiglitz)", "https://www.nobelprize.org/prizes/economic-sciences/2001/summary/", D)],
      explain=[
          K("Ordoliberalizm i społeczna gospodarka rynkowa",
            "Szkoła fryburska (Eucken, Böhm) i Müller-Armack, Erhard: państwo tworzy ramy („ład”) dla konkurencji – zwalcza monopole, dba o stabilny pieniądz i własność – ale nie steruje bieżąco gospodarką. Społeczna gospodarka rynkowa łączy rynek z solidarnością i dialogiem społecznym. Art. 20 Konstytucji RP wskazuje ją jako podstawę ustroju gospodarczego Polski."),
          K("Neoliberalizm i konsensus waszyngtoński",
            "Neoliberalizm (od lat 70.–80., Thatcher, Reagan): deregulacja, prywatyzacja, niższe podatki, ograniczona rola państwa. Konsensus waszyngtoński (Williamson, 1989) – zestaw zaleceń MFW i Banku Światowego dla krajów rozwijających się: dyscyplina fiskalna, liberalizacja handlu i finansów, prywatyzacja. Krytycy (Stiglitz, Rodrik) wskazywali na zbyt szybką liberalizację bez dobrych instytucji."),
          W("Która koncepcja jest wpisana w art. 20 Konstytucji RP?",
            "Społeczna gospodarka rynkowa", "Gospodarka centralnie planowana", "Merkantylizm",
            why="Opiera się na wolności działalności gospodarczej, własności prywatnej oraz solidarności, dialogu i współpracy partnerów społecznych."),
          K("Ekonomia heterodoksyjna",
            "Nurty krytyczne wobec głównego nurtu: marksistowski (wyzysk, walka klas, kryzysy kapitalizmu), postkeynesowski (niepewność, pieniądz endogeniczny – Kalecki, Minsky), feministyczny (praca nieodpłatna, rola płci), ekologiczny (granice planety, wzrost a środowisko), ewolucyjny (innowacje, rutyny firm)."),
          K("Metoda ekonomii",
            "Instrumentalizm Friedmana (1953): teorii nie ocenia się po realizmie założeń, lecz po trafności przewidywań. Paradygmat (Kuhn): wzorzec uprawiania nauki, który zmienia się przez rewolucje naukowe (np. „rewolucja keynesowska”). Spór o matematyzację: formalne modele dają precyzję, ale grozi oderwanie od rzeczywistości. Eklektyzm: świadome łączenie elementów różnych szkół – postawę tę deklaruje wielu polskich ekonomistów."),
          PF("Według instrumentalizmu Friedmana teoria jest dobra tylko wtedy, gdy jej założenia są w pełni realistyczne.", False,
             why="Liczy się trafność przewidywań, a nie realizm założeń."),
      ],
      mech=[
          KT("Który nurt?",
             {"Ordoliberalizm": ["Państwo strzeże ładu konkurencji, nie steruje cenami", "Szkoła fryburska"],
              "Neoliberalizm": ["Prywatyzacja i deregulacja w latach 80.", "Ograniczanie roli państwa"],
              "Heterodoksja": ["Praca nieodpłatna w ekonomii feministycznej", "Granice wzrostu w ekonomii ekologicznej", "Pieniądz endogeniczny w postkeynesizmie"]},
             why="Nurty różnią się podejściem do roli państwa i metody."),
          LN("Ułóż przebieg zmiany paradygmatu według Kuhna.",
             ["Nauka normalna w ramach paradygmatu", "Pojawiają się anomalie (fakty niezgodne z teorią)", "Kryzys paradygmatu", "Rewolucja naukowa – nowy paradygmat", "Nowa nauka normalna"],
             why="Przykład: Wielki Kryzys i rewolucja keynesowska."),
          W("Kto z polskich ekonomistów niezależnie od Keynesa sformułował zasadę efektywnego popytu?",
            "Michał Kalecki", "Leszek Balcerowicz", "Oskar Lange",
            why="Kalecki opublikował swoje prace na początku lat 30. XX w."),
          PF("Krytycy konsensusu waszyngtońskiego wskazywali, że liberalizacja bez silnych instytucji może zaszkodzić krajom rozwijającym się.", True,
             why="Np. szybkie otwarcie rynków kapitałowych zwiększało ryzyko kryzysów."),
          M("Które elementy należały do konsensusu waszyngtońskiego?",
            ["Dyscyplina fiskalna", "Liberalizacja handlu", "Nacjonalizacja przemysłu", "Prywatyzacja przedsiębiorstw państwowych"],
            [0, 1, 3],
            why="Zalecano prywatyzację, a nie nacjonalizację."),
          W("Co oznacza postawa eklektyczna w ekonomii?",
            "Świadome łączenie elementów różnych szkół, dobranych do badanego problemu", "Odrzucenie wszystkich teorii", "Wierność jednej szkole",
            why="Wielu polskich ekonomistów deklaruje taką postawę."),
      ],
      calc=[
          LB("Instrumentalizm w praktyce: model A pomylił się w prognozach inflacji o 1, 3 i 2 p.p. Ile wynosi średni błąd bezwzględny (p.p.)?",
             2, "(1+3+2)/3", ["(1 + 3 + 2) / 3 = 2 p.p."], unit="p.p."),
          LB("Model B (prostsze założenia) pomylił się o 1, 1 i 2,5 p.p. Ile wynosi jego średni błąd?",
             1.5, "(1+1+2.5)/3", ["4,5 / 3 = 1,5 p.p. – według Friedmana model B jest lepszy"], unit="p.p."),
          LB("Konsensus waszyngtoński: deficyt 8% PKB ma spaść do 3% w 5 lat równymi krokami. O ile p.p. rocznie?",
             1, "(8-3)/5", ["5 p.p. / 5 lat = 1 p.p."], unit="p.p."),
          LB("Prywatyzacja: państwo sprzedaje 40% akcji spółki wycenianej na 2,5 mld zł. Ile uzyska (mld zł)?",
             1, "0.4*2.5", ["0,4 · 2,5 = 1 mld zł"], unit="mld zł"),
          LB("Kalecki: zyski = inwestycje + konsumpcja kapitalistów (gospodarka zamknięta, bez państwa, robotnicy nie oszczędzają). I = 300, konsumpcja kapitalistów 100. Ile wynoszą zyski?",
             400, "300+100", ["Zyski = 300 + 100 = 400 – „kapitaliści zarabiają tyle, ile wydają”"], unit=""),
          LB("Ankieta wśród 60 ekonomistów: 27 deklaruje eklektyzm. Jaki to odsetek?",
             45, "27/60*100", ["27 / 60 = 45%"], unit="%"),
      ],
      case=[
          PR("Po II wojnie światowej Ludwig Erhard w Niemczech Zachodnich zniósł kontrolę cen, przeprowadził reformę walutową i oparł gospodarkę na konkurencji, a jednocześnie rozwijano zabezpieczenia społeczne i współpracę związków z pracodawcami. Nastąpił szybki wzrost nazywany „cudem gospodarczym”.",
             W("Jaki model ilustruje ten przykład?",
               "Społeczną gospodarkę rynkową (ordoliberalizm)", "Merkantylizm", "Gospodarkę centralnie planowaną",
               why="Rynek i konkurencja w ramach ładu instytucjonalnego plus solidarność społeczna."),
             W("Jaką rolę przypisują państwu ordoliberałowie?",
               "Twórcy i strażnika reguł konkurencji oraz stabilnego pieniądza", "Planisty ustalającego ceny", "Żadnej",
               why="Państwo silne w tworzeniu ładu, ale nieingerujące w bieżące decyzje."),
             PF("Polska konstytucja odwołuje się do tego modelu.", True,
                why="Art. 20 Konstytucji RP wskazuje społeczną gospodarkę rynkową."),
          ),
          PR("W latach 90. XX w. niektóre kraje Ameryki Łacińskiej i Azji szybko otworzyły rachunki kapitałowe zgodnie z zaleceniami międzynarodowych instytucji. Napływ krótkoterminowego kapitału, a potem jego nagły odpływ, przyczynił się do kryzysów.",
             W("Który nurt krytyki ilustruje ten przypadek?",
               "Krytykę konsensusu waszyngtońskiego (Stiglitz, Rodrik)", "Krytykę merkantylizmu (Smith)", "Krytykę fizjokratów",
               why="Krytycy wskazywali na zbyt szybką liberalizację finansową."),
             W("Co według krytyków powinno poprzedzać liberalizację finansową?",
               "Budowa silnych instytucji i nadzoru bankowego", "Nacjonalizacja banków", "Zamknięcie handlu",
               why="Sekwencja reform ma znaczenie."),
             PF("Zwolennicy reform wskazywali z kolei, że dyscyplina fiskalna i niska inflacja sprzyjały stabilności.", True,
                why="Ocena konsensusu jest przedmiotem sporu."),
          ),
      ]),
]
