# -*- coding: utf-8 -*-
# Zrozumienie – Makroekonomia / Rynek pracy i bezrobocie
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S211 = S("OpenStax, Principles of Economics 3e, 21.1 How Economists Define and Compute Unemployment Rate", OS3 + "21-1-how-economists-define-and-compute-unemployment-rate", D)
S212 = S("OpenStax, Principles of Economics 3e, 21.2 Patterns of Unemployment", OS3 + "21-2-patterns-of-unemployment", D)
S213 = S("OpenStax, Principles of Economics 3e, 21.3 What Causes Changes in Unemployment over the Short Run", OS3 + "21-3-what-causes-changes-in-unemployment-over-the-short-run", D)
S214 = S("OpenStax, Principles of Economics 3e, 21.4 What Causes Changes in Unemployment over the Long Run", OS3 + "21-4-what-causes-changes-in-unemployment-over-the-long-run", D)
S253 = S("OpenStax, Principles of Economics 3e, 25.3 The Phillips Curve", OS3 + "25-3-the-phillips-curve", D)
S323 = S("OpenStax, Principles of Economics 3e, 32.3 Causes of Unemployment around the World", OS3 + "32-3-causes-of-unemployment-around-the-world", D)
GUSRP = S("GUS – Sytuacja społeczno-gospodarcza kraju: rynek pracy (sierpień 2026)", "https://ssgk.stat.gov.pl/Rynek_pracy.html", D)
ALIOR = S("Alior Bank – raport rynkowy 26.08.2026 (BAEL II kw. 2026)", "https://www.aliorbank.pl/dam/jcr:2abea340-ba91-4ad1-8d5b-83d895d5cd99/20260826-raport-rynkowy.pdf", D)

LESSONS = [
    L(1, "Jak mierzy się bezrobocie",
      "Rozumieć podział ludności na pracujących, bezrobotnych i biernych, liczyć stopę bezrobocia, współczynnik aktywności i wskaźnik zatrudnienia oraz odróżniać bezrobocie rejestrowane od BAEL.",
      ["Rynek pracy", "Ludność aktywna zawodowo (zasób siły roboczej)", "Stopa bezrobocia",
       "Współczynnik aktywności zawodowej i wskaźnik zatrudnienia", "Bezrobocie rejestrowane i BAEL"],
      [S211, GUSRP, ALIOR],
      explain=[
          K("Trzy grupy ludności",
            "Ludność w wieku 15–89 lat (w BAEL) dzielimy na: pracujących, bezrobotnych (nie pracują, aktywnie szukają pracy i są gotowi ją podjąć) oraz biernych zawodowo (nie pracują i nie szukają – np. studenci, emeryci, osoby zniechęcone). Pracujący + bezrobotni = ludność aktywna zawodowo (siła robocza)."),
          K("Trzy wskaźniki",
            "Stopa bezrobocia = bezrobotni / aktywni zawodowo. Współczynnik aktywności = aktywni / cała ludność w wieku 15+. Wskaźnik zatrudnienia = pracujący / cała ludność w wieku 15+.",
            w="u = B / (P + B) · 100%"),
          W("Studentka nie pracuje i nie szuka pracy. Do jakiej grupy należy?",
            "Biernych zawodowo", "Bezrobotnych", "Pracujących",
            why="Bezrobotny musi aktywnie szukać pracy i być gotowy ją podjąć."),
          K("Bezrobocie rejestrowane a BAEL",
            "Bezrobocie rejestrowane liczą urzędy pracy – to osoby zarejestrowane jako bezrobotne (część rejestruje się m.in. dla ubezpieczenia zdrowotnego, a część pracuje nieformalnie). BAEL to badanie ankietowe GUS według definicji Międzynarodowej Organizacji Pracy, porównywalne między krajami. W Polsce stopa wg BAEL jest wyraźnie niższa: w II kw. 2026 r. wyniosła 3,2%, a rejestrowana pod koniec sierpnia 2026 r. – 5,8% (909,5 tys. osób)."),
          K("Pułapki interpretacji",
            "Stopa bezrobocia może spaść, choć nikt nie znalazł pracy – gdy zniechęceni przestają szukać i przechodzą do biernych. Dlatego warto patrzeć też na wskaźnik zatrudnienia."),
          PF("Osoba zniechęcona, która przestała szukać pracy, zwiększa stopę bezrobocia.", False,
             why="Przechodzi do biernych zawodowo – stopa bezrobocia formalnie spada."),
      ],
      mech=[
          KT("Pracujący, bezrobotny czy bierny?",
             {"Pracujący": ["Osoba pracująca 1 godzinę w tygodniu za wynagrodzeniem", "Pomagający w rodzinnym gospodarstwie rolnym"],
              "Bezrobotny": ["Absolwent wysyłający CV i gotowy zacząć od zaraz", "Zwolniony inżynier szukający pracy od 2 miesięcy"],
              "Bierny": ["Emeryt nieszukający pracy", "Osoba zniechęcona, która przestała szukać", "Student dzienny nieszukający pracy"]},
             why="Kluczowe kryteria: praca w badanym tygodniu, aktywne poszukiwanie i gotowość."),
          LN("Ułóż efekt „zniechęconych pracowników” w recesji.",
             ["Recesja przedłuża się", "Część bezrobotnych traci nadzieję na pracę", "Przestają aktywnie szukać", "Przechodzą do biernych zawodowo", "Stopa bezrobocia spada, choć zatrudnienie nie rośnie"],
             why="Stopa bezrobocia może zaniżać skalę problemu."),
          W("Dlaczego w Polsce bezrobocie rejestrowane jest wyższe niż BAEL?",
            "Część zarejestrowanych nie szuka aktywnie pracy lub pracuje nieformalnie", "Bo BAEL obejmuje tylko miasta", "Bo urzędy liczą tylko osoby młode",
            why="Rejestracja daje m.in. ubezpieczenie zdrowotne, a BAEL stosuje ścisłe kryteria MOP."),
          PF("Wskaźnik zatrudnienia jest odporny na przechodzenie bezrobotnych do biernych.", True,
             why="Liczy pracujących względem całej ludności, a nie tylko aktywnych."),
          M("Co zwiększa współczynnik aktywności zawodowej?",
            ["Podniesienie wieku emerytalnego", "Powrót matek na rynek pracy po urlopach", "Wydłużenie studiów dziennych", "Aktywizacja osób biernych przez urzędy pracy"],
            [0, 1, 3],
            why="Dłuższe studia zwiększają liczbę biernych."),
          W("Jaką definicję bezrobocia stosuje BAEL?",
            "Międzynarodowej Organizacji Pracy (MOP)", "Ustawy o rynku pracy (rejestracja w urzędzie)", "Definicję ZUS",
            why="Dzięki temu dane BAEL są porównywalne z Eurostatem."),
      ],
      calc=[
          LB("Ludność 15+: 30 mln. Pracujący: 17 mln, bezrobotni: 0,6 mln. Ile wynosi stopa bezrobocia?",
             3.41, "0.6/17.6*100", ["Aktywni: 17 + 0,6 = 17,6 mln", "0,6 / 17,6 ≈ 3,41%"], unit="%", tol=0.02),
          LB("Ile wynosi współczynnik aktywności zawodowej?",
             58.67, "17.6/30*100", ["17,6 / 30 ≈ 58,67%"], unit="%", tol=0.02),
          LB("Ile wynosi wskaźnik zatrudnienia?",
             56.67, "17/30*100", ["17 / 30 ≈ 56,67%"], unit="%", tol=0.02),
          LB("0,1 mln bezrobotnych przestaje szukać pracy (pozostałe dane bez zmian). Ile wynosi nowa stopa bezrobocia?",
             2.86, "0.5/17.5*100", ["Bezrobotni 0,5, aktywni 17,5", "0,5 / 17,5 ≈ 2,86%"], unit="%", tol=0.02),
          LB("Bezrobocie rejestrowane: 909,5 tys. przy stopie 5,8%. Ile (w przybliżeniu, mln) wynosi cywilna ludność aktywna przyjęta do obliczenia?",
             15.68, "0.9095/0.058", ["909,5 tys. / 0,058 ≈ 15,68 mln"], unit="mln", tol=0.02),
          LB("Stopa BAEL wzrosła z 2,8% (II kw. 2025) do 3,2% (II kw. 2026). O ile punktów procentowych?",
             0.4, "3.2-2.8", ["3,2 − 2,8 = 0,4 p.p."], unit="p.p."),
      ],
      case=[
          PR("Pod koniec sierpnia 2026 r. stopa bezrobocia rejestrowanego w Polsce wynosiła 5,8% (909,5 tys. osób), o 0,3 p.p. więcej niż rok wcześniej, a przeciętne zatrudnienie w sektorze przedsiębiorstw było o 0,8% niższe r/r. Stopa bezrobocia wg BAEL w II kw. 2026 r. wyniosła 3,2%.",
             W("Dlaczego obie stopy tak się różnią?",
               "Mierzą bezrobocie według różnych definicji i metod", "Jedna z nich jest błędna", "BAEL dotyczy tylko jednego województwa",
               why="Rejestracja w urzędzie vs ankieta według definicji MOP."),
             W("Którą stopę wykorzystasz do porównania Polski z Niemcami?",
               "BAEL (zharmonizowaną z Eurostatem)", "Rejestrowaną", "Dowolną",
               why="Definicja MOP jest wspólna dla krajów UE."),
             PF("Spadek zatrudnienia w sektorze przedsiębiorstw przy rosnącym bezrobociu wskazuje na ochłodzenie rynku pracy.", True,
                why="Oba wskaźniki poruszają się w tym samym, niekorzystnym kierunku."),
          ),
          PR("W pewnym powiecie stopa bezrobocia spadła w ciągu roku z 12% do 10%. Jednocześnie liczba pracujących się nie zmieniła, a wiele osób wyjechało za granicę lub przestało szukać pracy.",
             W("Czy rynek pracy w powiecie się poprawił?",
               "Niekoniecznie – spadek wynika ze zmniejszenia liczby aktywnych", "Tak, bo stopa spadła", "Tak, bo wzrosło zatrudnienie",
               why="Liczba pracujących się nie zmieniła."),
             W("Który wskaźnik lepiej pokazuje sytuację?",
               "Wskaźnik zatrudnienia", "Stopa bezrobocia", "Liczba ofert pracy w urzędzie",
               why="Nie zależy od tego, czy ktoś przestał szukać."),
             PF("Emigracja zarobkowa może obniżać stopę bezrobocia bez tworzenia miejsc pracy w kraju.", True,
                why="Zmniejsza liczbę bezrobotnych i aktywnych w kraju."),
          ),
      ]),

    L(2, "Rodzaje bezrobocia",
      "Rozróżniać bezrobocie frykcyjne, strukturalne, cykliczne i sezonowe, dobrowolne i przymusowe oraz ukryte – i dobierać do nich właściwe działania.",
      ["Bezrobocie frykcyjne", "Bezrobocie strukturalne", "Bezrobocie cykliczne (koniunkturalne, keynesowskie)",
       "Bezrobocie sezonowe", "Bezrobocie dobrowolne i przymusowe", "Bezrobocie ukryte"],
      [S212, S213, S214],
      explain=[
          K("Frykcyjne",
            "Bezrobocie „przejściowe”: ludzie zmieniają pracę, wchodzą na rynek po studiach, przeprowadzają się. Szukanie dobrej oferty trwa – dlatego jest ono nieuniknione, a nawet korzystne (lepsze dopasowanie pracownika do pracy)."),
          K("Strukturalne",
            "Niedopasowanie kwalifikacji lub miejsca zamieszkania do wolnych miejsc pracy – np. po upadku górnictwa czy automatyzacji. Wolne miejsca są, ale bezrobotni nie mają odpowiednich umiejętności. Trwa długo; pomagają szkolenia i mobilność."),
          K("Cykliczne",
            "Wynika ze spadku zagregowanego popytu w recesji – firmy produkują mniej i zwalniają. Znika, gdy gospodarka wraca do potencjału. Keynes nazywał je przymusowym: ludzie chcą pracować przy obecnej płacy, ale nie ma dla nich miejsc."),
          W("Górnik traci pracę po zamknięciu kopalni, a w regionie brakuje programistów. To bezrobocie:",
            "Strukturalne", "Frykcyjne", "Cykliczne",
            why="Problemem jest niedopasowanie kwalifikacji, a nie brak popytu w całej gospodarce."),
          K("Sezonowe, dobrowolne, ukryte",
            "Sezonowe – zależne od pory roku (rolnictwo, budownictwo, turystyka). Dobrowolne – osoby nie chcą pracować przy obecnej płacy (np. wolą zasiłek). Ukryte – formalnie pracujący, ale ich praca nic nie wnosi (np. nadmiar osób w małych gospodarstwach rolnych; krańcowa produktywność ≈ 0)."),
          PF("Bezrobocie frykcyjne można całkowicie wyeliminować pobudzaniem popytu.", False,
             why="Szukanie pracy zawsze trwa – dotyczy to nawet gospodarki przy pełnym zatrudnieniu."),
      ],
      mech=[
          KT("Jaki to rodzaj bezrobocia?",
             {"Frykcyjne": ["Absolwentka szuka pierwszej pracy przez 2 miesiące", "Pracownik zrezygnował, by poszukać lepszej oferty"],
              "Strukturalne": ["Kasjerzy zastąpieni kasami samoobsługowymi", "Zamknięcie kopalni w regionie bez innego przemysłu"],
              "Cykliczne": ["Zwolnienia w fabrykach podczas recesji", "Spadek zatrudnienia w budownictwie po załamaniu popytu w całej gospodarce"],
              "Sezonowe": ["Ratownik nad morzem zimą bez pracy"]},
             why="Kryterium to przyczyna braku pracy."),
          W("Które bezrobocie najlepiej zwalcza ekspansywna polityka makroekonomiczna?",
            "Cykliczne", "Strukturalne", "Frykcyjne",
            why="Wynika z niedoboru popytu – pobudzenie popytu je zmniejsza."),
          M("Co zmniejsza bezrobocie strukturalne?",
            ["Programy przekwalifikowania", "Dopłaty do przeprowadzki za pracą", "Obniżka stóp procentowych", "Dostosowanie kształcenia zawodowego do potrzeb firm"],
            [0, 1, 3],
            why="Obniżka stóp działa na popyt, a nie na niedopasowanie kwalifikacji."),
          LN("Ułóż, jak automatyzacja może tworzyć bezrobocie strukturalne.",
             ["Nowa technologia zastępuje prostą pracę", "Pracownicy o starych kwalifikacjach tracą pracę", "Nowe miejsca pracy wymagają innych umiejętności", "Bezrobotni nie pasują do ofert", "Bezrobocie trwa, dopóki się nie przekwalifikują"],
             why="To niedopasowanie, a nie brak popytu."),
          PF("Ukryte bezrobocie nie pojawia się w oficjalnych statystykach bezrobocia.", True,
             why="Osoby te formalnie pracują – ich krańcowa produktywność jest jednak bliska zera."),
          W("Internetowe portale z ofertami pracy najbardziej zmniejszają bezrobocie:",
            "Frykcyjne", "Cykliczne", "Ukryte",
            why="Skracają czas szukania i dopasowania."),
      ],
      calc=[
          LB("Bezrobotnych jest 1 mln: 250 tys. frykcyjnych, 350 tys. strukturalnych, reszta cyklicznych. Ile wynosi bezrobocie cykliczne (tys.)?",
             400, "1000-250-350", ["1000 − 250 − 350 = 400 tys."], unit="tys."),
          LB("Aktywnych zawodowo jest 17,5 mln. Ile wynosi stopa bezrobocia naturalnego (frykcyjne + strukturalne)?",
             3.43, "0.6/17.5*100", ["(250 + 350) tys. = 0,6 mln", "0,6 / 17,5 ≈ 3,43%"], unit="%", tol=0.02),
          LB("Ile wynosi faktyczna stopa bezrobocia?",
             5.71, "1/17.5*100", ["1 / 17,5 ≈ 5,71%"], unit="%", tol=0.02),
          LB("Gospodarstwo produkuje 30 t zboża przy 5 osobach i 30 t przy 3 osobach. Ile osób jest ukrytymi bezrobotnymi?",
             2, "5-3", ["Dwie dodatkowe osoby nie zwiększają produkcji – ich krańcowy produkt = 0"], unit="os."),
          LB("Przeciętne poszukiwanie pracy trwa 3 miesiące, a co roku 2 mln osób zmienia pracę lub wchodzi na rynek. Ilu (średnio, mln) jest jednocześnie bezrobotnych frykcyjnie?",
             0.5, "2*3/12", ["Zasób = przepływ × czas trwania", "2 mln · 3/12 roku = 0,5 mln"], unit="mln"),
          LB("Portal ofert skraca szukanie z 3 do 2 miesięcy (przepływ 2 mln/rok). O ile tys. spada bezrobocie frykcyjne?",
             166.67, "(2*3/12-2*2/12)*1000", ["0,5 mln − 2 · 2/12 ≈ 0,333 mln", "Spadek ≈ 166,67 tys."], unit="tys.", tol=0.02),
      ],
      case=[
          PR("W latach 90. XX w. w Polsce likwidowano państwowe gospodarstwa rolne (PGR). W wielu wsiach na północy kraju ich pracownicy przez lata nie mogli znaleźć pracy – nowe firmy powstawały głównie w dużych miastach, a pracownicy PGR mieli kwalifikacje rolnicze i niewielką mobilność.",
             W("Jaki rodzaj bezrobocia dominował w tych regionach?",
               "Strukturalne (kwalifikacje i miejsce zamieszkania)", "Frykcyjne", "Sezonowe",
               why="Niedopasowanie umiejętności i lokalizacji do nowych miejsc pracy."),
             M("Jakie działania mogłyby pomóc?",
               ["Szkolenia zawodowe", "Wsparcie dojazdów i przeprowadzek", "Rozwój lokalnej przedsiębiorczości", "Podwyżka stóp procentowych"],
               [0, 1, 2],
               why="Podwyżka stóp osłabia popyt i nie rozwiązuje niedopasowania."),
             PF("Przed likwidacją część zatrudnienia w PGR mogła mieć charakter bezrobocia ukrytego.", True,
                why="Przerost zatrudnienia przy niskiej krańcowej produktywności."),
          ),
          PR("W czasie recesji w 2009 r. w wielu krajach UE gwałtownie wzrosło bezrobocie, szczególnie w budownictwie i przemyśle. Po powrocie wzrostu w części krajów spadło szybko, w innych długo pozostało wysokie.",
             W("Jaki rodzaj bezrobocia wzrósł najpierw?",
               "Cykliczne", "Frykcyjne", "Ukryte",
               why="Przyczyną był spadek zagregowanego popytu."),
             W("Co mogło sprawić, że w niektórych krajach bezrobocie nie wróciło do wcześniejszego poziomu?",
               "Przekształcenie się bezrobocia cyklicznego w strukturalne (np. upadek boomu budowlanego)", "Wzrost popytu", "Spadek liczby studentów",
               why="Część pracowników budownictwa nie znalazła zatrudnienia w innych branżach."),
             PF("Polityka popytowa skutecznie zwalcza bezrobocie, które zamieniło się w strukturalne.", False,
                why="Strukturalnemu pomaga przekwalifikowanie i mobilność, nie sam popyt."),
          ),
      ]),

    L(3, "Naturalna stopa bezrobocia, NAIRU i histereza",
      "Rozumieć, czym jest naturalna stopa bezrobocia i NAIRU, od czego zależą, dlaczego długotrwałe bezrobocie może podnosić stopę naturalną (histereza) i jakie są koszty bezrobocia.",
      ["Naturalna stopa bezrobocia", "NAIRU", "Histereza bezrobocia", "Model insiderów–outsiderów", "Bezrobocie długotrwałe i koszty bezrobocia"],
      [S214, S323, S253],
      explain=[
          K("Naturalna stopa bezrobocia",
            "To bezrobocie, które pozostaje, gdy gospodarka działa na poziomie potencjału: frykcyjne + strukturalne (bez cyklicznego). Nie jest stałą natury – zależy od instytucji rynku pracy: zasiłków, płacy minimalnej, siły związków, mobilności, kwalifikacji, sprawności pośrednictwa."),
          K("NAIRU",
            "Non-Accelerating Inflation Rate of Unemployment – stopa bezrobocia, przy której inflacja się nie przyspiesza. Gdy bezrobocie spada poniżej NAIRU, rośnie presja płacowa i inflacja przyspiesza; gdy jest powyżej – inflacja zwalnia. W praktyce NAIRU szacuje się z modeli i ma duży błąd oszacowania."),
          W("Bezrobocie jest poniżej NAIRU. Czego się spodziewać?",
            "Przyspieszenia inflacji", "Deflacji", "Stabilnej inflacji",
            why="Napięty rynek pracy podnosi płace i ceny."),
          K("Histereza",
            "Długie bezrobocie zmienia samych bezrobotnych: tracą umiejętności, kontakty i motywację, a pracodawcy traktują przerwę w zatrudnieniu jako sygnał niskiej jakości. Bezrobocie cykliczne może więc „zamienić się” w strukturalne i trwale podnieść stopę naturalną."),
          K("Insiderzy i outsiderzy",
            "Zatrudnieni (insiderzy) i ich związki negocjują wysokie płace, bo zastąpienie ich jest kosztowne (rekrutacja, szkolenie, ochrona przed zwolnieniem). Bezrobotni (outsiderzy) nie mogą zaoferować pracy za mniej. Płace nie spadają mimo bezrobocia – a to wzmacnia histerezę."),
          PF("Naturalna stopa bezrobocia jest taka sama we wszystkich krajach i okresach.", False,
             why="Zależy od instytucji, demografii i struktury gospodarki."),
      ],
      mech=[
          LN("Ułóż mechanizm histerezy.",
             ["Recesja zwiększa bezrobocie cykliczne", "Część osób pozostaje bez pracy ponad rok", "Tracą umiejętności i kontakty", "Pracodawcy niechętnie ich zatrudniają", "Po powrocie wzrostu bezrobocie pozostaje wyższe"],
             why="Bezrobocie cykliczne przechodzi w strukturalne."),
          KT("Co podnosi, a co obniża naturalną stopę bezrobocia?",
             {"Podnosi": ["Bardzo wysokie i długie zasiłki", "Silna ochrona insiderów przed zwolnieniem", "Niska mobilność mieszkaniowa"],
              "Obniża": ["Sprawne pośrednictwo pracy", "Szkolenia dopasowane do potrzeb firm", "Rozwinięty rynek najmu mieszkań"]},
             why="Naturalna stopa zależy od instytucji rynku pracy."),
          W("Dlaczego bezrobotni outsiderzy nie mogą „przebić” płac insiderów?",
            "Firma ponosi koszty wymiany pracowników, a insiderzy są chronieni", "Bo prawo zakazuje zatrudniania bezrobotnych", "Bo outsiderzy żądają wyższych płac",
            why="Koszty rotacji i siła negocjacyjna insiderów utrzymują płace."),
          PF("Długotrwałe bezrobocie to zwykle bezrobocie trwające ponad 12 miesięcy.", True,
             why="Tak definiuje je m.in. Eurostat."),
          M("Jakie są koszty bezrobocia?",
            ["Utracona produkcja (luka PKB)", "Zanik kwalifikacji bezrobotnych", "Wzrost dochodów budżetu z PIT", "Problemy zdrowotne i społeczne"],
            [0, 1, 3],
            why="Bezrobocie zmniejsza dochody budżetu i zwiększa wydatki na zasiłki."),
          W("Według zwolenników histerezy, czy w recesji warto szybko pobudzać popyt?",
            "Tak – by nie dopuścić do trwałego wzrostu bezrobocia", "Nie – bezrobocie zawsze samo wróci do starego poziomu", "To bez znaczenia",
            why="Szybka reakcja zapobiega przechodzeniu bezrobocia w długotrwałe."),
      ],
      calc=[
          LB("Aktywnych jest 17 mln, a NAIRU szacuje się na 4%. Ilu bezrobotnych (tys.) odpowiada NAIRU?",
             680, "0.04*17000", ["0,04 · 17 000 tys. = 680 tys."], unit="tys."),
          LB("Faktycznie bezrobotnych jest 850 tys. Ile wynosi faktyczna stopa bezrobocia?",
             5, "850/17000*100", ["850 / 17 000 = 5%"], unit="%"),
          LB("Ile tys. osób to bezrobocie cykliczne (ponad NAIRU)?",
             170, "850-680", ["850 − 680 = 170 tys."], unit="tys."),
          LB("Bezrobotnych jest 850 tys., z czego 255 tys. szuka pracy ponad rok. Jaki procent stanowią długotrwale bezrobotni?",
             30, "255/850*100", ["255 / 850 = 30%"], unit="%"),
          LB("Bezrobotny dostawał 4000 zł brutto, a zasiłek wynosi 1700 zł. Jaką część poprzedniego dochodu traci (%)?",
             57.5, "(4000-1700)/4000*100", ["(4000 − 1700) / 4000 = 57,5%"], unit="%"),
          LB("Przez histerezę NAIRU wzrosło z 4% do 4,5%. Ilu dodatkowych bezrobotnych (tys.) oznacza to przy 17 mln aktywnych?",
             85, "0.005*17000", ["0,5 p.p. · 17 000 tys. = 85 tys."], unit="tys."),
      ],
      case=[
             PR("W latach 80. XX w. w wielu krajach Europy Zachodniej bezrobocie wzrosło po szokach naftowych i recesji, ale – w odróżnieniu od USA – nie wróciło do wcześniejszego poziomu przez kolejną dekadę. Kraje te miały silne związki zawodowe, wysoką ochronę zatrudnienia i długie zasiłki.",
             W("Jakie zjawisko opisuje ta sytuacja?",
               "Histerezę bezrobocia", "Paradoks zapobiegliwości", "Pułapkę płynności",
               why="Tymczasowy wzrost bezrobocia stał się trwały."),
             W("Jaki model wyjaśnia, dlaczego płace nie spadały mimo bezrobocia?",
               "Model insiderów–outsiderów", "Model wysp Lucasa", "Model Harroda-Domara",
               why="Zatrudnieni i związki chronili swoje płace."),
             PF("Wysoki udział długotrwale bezrobotnych osłabia presję bezrobocia na płace.", True,
                why="Długotrwale bezrobotni słabo konkurują o pracę, więc słabiej hamują płace."),
          ),
          PR("Bank centralny szacuje NAIRU na 4%. Faktyczna stopa bezrobocia spadła do 3% i utrzymuje się od roku; płace rosną o 12% rocznie, a inflacja bazowa przyspiesza.",
             W("Co sugeruje model NAIRU?",
               "Gospodarka jest przegrzana – presja inflacyjna będzie rosła", "Bezrobocie jest za wysokie", "Inflacja powinna spadać",
               why="Bezrobocie poniżej NAIRU przyspiesza inflację."),
             W("Jakiej decyzji banku centralnego można się spodziewać?",
               "Zacieśnienia polityki (podwyżki stóp)", "Obniżki stóp", "Zakupu obligacji na dużą skalę",
               why="Hamowanie popytu ogranicza presję płacową."),
             PF("NAIRU jest wielkością nieobserwowalną, szacowaną z dużą niepewnością.", True,
                why="Dlatego decyzje opierają się też na innych wskaźnikach."),
          ),
      ]),

    L(4, "Dlaczego płace są sztywne",
      "Rozumieć teorie wyjaśniające, dlaczego płace nie spadają mimo bezrobocia: płace efektywnościowe, model bumelowania, kontrakty implicytne – oraz krzywą Beveridge’a.",
      ["Płace efektywnościowe (motywujące)", "Model bumelowania (Shapiro–Stiglitz)", "Teoria kontraktów implicytnych",
       "Krzywa Beveridge’a", "Bezrobocie dobrowolne i przymusowe"],
      [S213, S214],
      explain=[
          K("Rynek pracy w modelu klasycznym",
            "W prostym modelu płaca realna dostosowuje się tak, by popyt na pracę (firmy) zrównał się z podażą (pracownicy) – trwałe przymusowe bezrobocie nie istnieje. W praktyce płace w recesji spadają rzadko i powoli. Ekonomiści szukają wyjaśnień tej sztywności.",
            g=G("praca")),
          K("Płace efektywnościowe",
            "Firmie opłaca się płacić powyżej poziomu rynkowego, bo lepiej opłacani pracownicy: pracują wydajniej, rzadziej odchodzą (niższe koszty rekrutacji i szkolenia), a firma przyciąga lepszych kandydatów. Przykład: Henry Ford w 1914 r. podniósł płacę do 5 dolarów dziennie, a rotacja spadła."),
          K("Model bumelowania (Shapiro–Stiglitz)",
            "Firma nie może stale kontrolować pracownika. Płaci więcej niż rynek, by utrata pracy była dla bumelanta kosztowna. Gdyby wszyscy mieli pełne zatrudnienie, zwolnienie nie byłoby karą – dlatego w równowadze utrzymuje się pewne bezrobocie, które „dyscyplinuje” pracowników."),
          W("Dlaczego w modelu Shapiro–Stiglitza istnieje przymusowe bezrobocie?",
            "Wysokie płace i bezrobocie sprawiają, że utrata pracy jest kosztowna, co zniechęca do bumelowania", "Bo pracownicy nie chcą pracować", "Bo płace są za niskie",
            why="Bezrobocie pełni funkcję „dyscyplinującą”."),
          K("Kontrakty implicytne i krzywa Beveridge’a",
            "Kontrakty implicytne: niepisana umowa – firma (mniej awersyjna do ryzyka) gwarantuje stabilną płacę w zamian za niższą średnią płacę; w złych czasach zamiast obniżać płace – zwalnia. Krzywa Beveridge’a: zależność ujemna między stopą wolnych miejsc pracy a stopą bezrobocia. Ruch wzdłuż krzywej – cykl koniunkturalny; przesunięcie na zewnątrz – gorsze dopasowanie (bezrobocie strukturalne)."),
          PF("Płace efektywnościowe oznaczają płacę niższą od rynkowej.", False,
             why="Oznaczają płacę WYŻSZĄ od rynkowej, która podnosi wydajność."),
      ],
      mech=[
          WY("Płaca jest ustalona powyżej równowagi (np. płaca efektywnościowa). Co pokazuje model rynku pracy?",
             G("praca", SL=1), "Podaż pracy przewyższa popyt – przymusowe bezrobocie", "Niedobór pracowników", "Równowaga bez bezrobocia",
             why="Przy płacy powyżej równowagi więcej osób chce pracować, niż firmy zatrudniają."),
          LN("Ułóż logikę płacy efektywnościowej.",
             ["Firma płaci powyżej stawki rynkowej", "Pracownikom bardziej zależy na tej pracy", "Pracują wydajniej i rzadziej odchodzą", "Spadają koszty rekrutacji i szkoleń", "Wyższa płaca się opłaca firmie"],
             why="Wydajność zależy od płacy."),
          W("Rośnie liczba wolnych miejsc pracy, a jednocześnie bezrobocie nie spada. Co dzieje się z krzywą Beveridge’a?",
            "Przesuwa się na zewnątrz – pogarsza się dopasowanie", "Ruch wzdłuż krzywej w górę", "Przesuwa się do środka",
            why="Więcej wakatów przy tym samym bezrobociu = gorsze dopasowanie (strukturalne)."),
          KT("Ruch wzdłuż krzywej Beveridge’a czy jej przesunięcie?",
             {"Ruch wzdłuż": ["Recesja: mniej wakatów, więcej bezrobotnych", "Ożywienie: więcej wakatów, mniej bezrobotnych"],
              "Przesunięcie": ["Automatyzacja zmienia potrzebne kwalifikacje", "Nowy portal ofert znacząco poprawia dopasowanie", "Spada mobilność pracowników"]},
             why="Cykl porusza wzdłuż, dopasowanie przesuwa krzywą."),
          PF("Teoria kontraktów implicytnych wyjaśnia, dlaczego w recesji firmy częściej zwalniają niż obniżają płace.", True,
             why="Stabilność płac jest elementem niepisanej umowy."),
          M("Które teorie wyjaśniają sztywność płac w dół?",
            ["Płace efektywnościowe", "Model insiderów–outsiderów", "Prawo Saya", "Kontrakty implicytne"],
            [0, 1, 3],
            why="Prawo Saya zakłada pełną elastyczność cen."),
      ],
      calc=[
          LB("Popyt na pracę: L = 200 − 4w, podaż: L = 40 + 4w (w – płaca w zł/godz.). Ile wynosi płaca równowagi?",
             20, "160/8", ["200 − 4w = 40 + 4w", "8w = 160 ⇒ w = 20"], unit="zł/godz."),
          LB("Firmy płacą płacę efektywnościową 25 zł/godz. Ile osób jest bezrobotnych (podaż − popyt)?",
             40, "(40+4*25)-(200-4*25)", ["Podaż: 140, popyt: 100", "Bezrobocie: 40"], unit=""),
          LB("Płaca 25 zł zamiast 20 zł zmniejsza rotację z 30% do 10% rocznie. Firma zatrudnia 100 osób, a zastąpienie jednej kosztuje 15 000 zł. Ile rocznie oszczędza na rotacji (zł)?",
             300000, "(0.30-0.10)*100*15000", ["Mniej odejść: 20 osób", "20 · 15 000 = 300 000 zł"], unit="zł"),
          LB("Dodatkowy koszt płac: 5 zł · 2000 godz. · 100 osób. Ile wynosi (zł)?",
             1000000, "5*2000*100", ["5 · 2000 · 100 = 1 000 000 zł"], unit="zł"),
          LB("Wydajność rośnie o 10% przy przychodzie na pracownika 120 000 zł rocznie. Ile wynosi dodatkowy przychód firmy (zł) dla 100 pracowników?",
             1200000, "0.10*120000*100", ["0,1 · 120 000 · 100 = 1 200 000 zł"], unit="zł"),
          LB("Czy płaca efektywnościowa się opłaca? Podaj zysk netto (zł) = oszczędność na rotacji + dodatkowy przychód − koszt płac.",
             500000, "300000+1200000-1000000", ["300 000 + 1 200 000 − 1 000 000 = 500 000 zł"], unit="zł"),
      ],
      case=[
          PR("W 1914 r. Henry Ford podniósł dzienną płacę robotników do 5 dolarów – mniej więcej dwukrotność stawki rynkowej. Wcześniej rotacja w fabryce była ogromna. Po podwyżce przed bramą ustawiały się kolejki chętnych, rotacja i absencja spadły, a wydajność wzrosła.",
             W("Jaką teorię ilustruje ten przypadek?",
               "Płac efektywnościowych", "Kontraktów implicytnych", "Prawa Okuna",
               why="Wyższa płaca zwiększyła wydajność i zmniejszyła rotację."),
             W("Co oznaczały kolejki przed bramą?",
               "Przy tej płacy podaż pracy przewyższała popyt – przymusowe bezrobocie", "Niedobór pracowników", "Równowagę rynku",
               why="Płaca była powyżej poziomu równowagi."),
             PF("Podwyżka mogła być opłacalna dla Forda, mimo że zwiększyła koszt godziny pracy.", True,
                why="Niższa rotacja i wyższa wydajność rekompensowały koszt."),
          ),
          PR("Po pandemii w wielu krajach liczba wolnych miejsc pracy osiągnęła rekordy, a bezrobocie spadało wolniej, niż sugerowały wcześniejsze zależności. Część pracowników zmieniła branżę lub zrezygnowała z pracy w usługach.",
             W("Jak opisać to na krzywej Beveridge’a?",
               "Przesunięcie krzywej na zewnątrz – gorsze dopasowanie", "Ruch wzdłuż krzywej w dół", "Przesunięcie do środka",
               why="Więcej wakatów przy podobnym bezrobociu."),
             M("Co mogło pogorszyć dopasowanie?",
               ["Zmiana preferencji pracowników co do branż", "Zmiany w strukturze popytu na usługi", "Obniżka podatków", "Problemy z mobilnością"],
               [0, 1, 3],
               why="Obniżka podatków nie wpływa bezpośrednio na dopasowanie."),
             PF("Szybkie wypełnianie wakatów w kolejnych latach przesuwa krzywą z powrotem.", True,
                why="Poprawa dopasowania przesuwa ją do środka."),
          ),
      ]),

    L(5, "Krzywa Phillipsa i prawo Okuna",
      "Rozumieć krótkookresową i długookresową krzywą Phillipsa, rolę oczekiwań oraz posługiwać się prawem Okuna do łączenia bezrobocia z luką PKB.",
      ["Krzywa Phillipsa", "Prawo Okuna", "NAIRU", "Naturalna stopa bezrobocia"],
      [S253, S("OpenStax, Principles of Economics 3e, 25.4 The Keynesian Perspective on Market Forces", OS3 + "25-4-the-keynesian-perspective-on-market-forces", D), S("OpenStax, Principles of Economics 3e, 26.1 The Building Blocks of Neoclassical Analysis", OS3 + "26-1-the-building-blocks-of-neoclassical-analysis", D)],
      explain=[
          K("Pierwotna krzywa Phillipsa",
            "A. W. Phillips (1958) pokazał na danych brytyjskich ujemną zależność między bezrobociem a tempem wzrostu płac. Samuelson i Solow przenieśli ją na inflację: niższe bezrobocie można „kupić” wyższą inflacją."),
          K("Krytyka Friedmana i Phelpsa",
            "Pod koniec lat 60. Friedman i Phelps twierdzili, że wymiana działa tylko krótko. Gdy ludzie zaczną oczekiwać wyższej inflacji, wliczą ją w płace – bezrobocie wróci do stopy naturalnej, a inflacja zostanie wyższa. Długookresowa krzywa Phillipsa jest pionowa na poziomie stopy naturalnej. Stagflacja lat 70. potwierdziła tę krytykę.",
            w="π = πᵉ − β(u − u*)"),
          W("Jak wygląda długookresowa krzywa Phillipsa według Friedmana?",
            "Pionowa na poziomie naturalnej stopy bezrobocia", "Opadająca", "Pozioma",
            why="W długim okresie nie ma wymiany między inflacją a bezrobociem."),
          K("Prawo Okuna",
            "Arthur Okun (1962) zauważył, że bezrobocie i produkcja poruszają się razem w przeciwnych kierunkach. Popularna reguła: każdy 1 p.p. bezrobocia ponad stopę naturalną odpowiada ok. 2% luki PKB (współczynnik zależy od kraju i okresu; Okun szacował ok. 3).",
            w="(Y − Y*)/Y* = −c(u − u*)"),
          K("Zastosowanie",
            "Prawo Okuna pozwala ocenić koszt recesji w utraconej produkcji, a krzywa Phillipsa – presję inflacyjną przy danym bezrobociu. Razem tworzą podstawę oceny luki popytowej przez banki centralne."),
          PF("Według prawa Okuna wzrost bezrobocia zwykle towarzyszy spadkowi produkcji względem potencjału.", True,
             why="Luka PKB i bezrobocie cykliczne poruszają się w przeciwnych kierunkach."),
      ],
      mech=[
          LN("Ułóż przejście z krótkiego do długiego okresu wg Friedmana.",
             ["Bank centralny pobudza popyt", "Inflacja rośnie ponad oczekiwania", "Płace realne spadają, firmy zatrudniają więcej – bezrobocie spada", "Pracownicy podnoszą oczekiwania inflacyjne i żądają wyższych płac", "Bezrobocie wraca do stopy naturalnej przy wyższej inflacji"],
             why="Wymiana jest możliwa tylko przy niespodziewanej inflacji."),
          W("Oczekiwania inflacyjne rosną. Co dzieje się z krótkookresową krzywą Phillipsa?",
            "Przesuwa się w górę", "Przesuwa się w dół", "Staje się pozioma",
            why="Przy każdym bezrobociu inflacja jest wyższa o wzrost oczekiwań."),
          KT("Krótki czy długi okres (wg Friedmana)?",
             {"Krótki okres": ["Niższe bezrobocie kosztem wyższej inflacji", "Opadająca krzywa Phillipsa"],
              "Długi okres": ["Pionowa krzywa Phillipsa", "Bezrobocie równe stopie naturalnej", "Polityka zmienia tylko inflację"]},
             why="Oczekiwania dostosowują się z czasem."),
          PF("Stagflacja lat 70. była sprzeczna z prostą, stabilną krzywą Phillipsa.", True,
             why="Wysoka inflacja współwystępowała z wysokim bezrobociem."),
          W("Aby trwale obniżyć bezrobocie, według Friedmana należy przede wszystkim:",
            "Obniżyć naturalną stopę bezrobocia reformami rynku pracy", "Stale podnosić inflację", "Ograniczyć podaż pieniądza do zera",
            why="Polityka popytowa nie zmienia stopy naturalnej."),
          M("Co obniża koszt dezinflacji (mniejszy wzrost bezrobocia)?",
            ["Wiarygodny bank centralny", "Zakotwiczone oczekiwania inflacyjne", "Silna indeksacja płac do przeszłej inflacji", "Jasna komunikacja celu inflacyjnego"],
            [0, 1, 3],
            why="Indeksacja do przeszłej inflacji zwiększa bezwładność i koszt dezinflacji."),
      ],
      calc=[
          LB("π = πᵉ − 0,5(u − u*). πᵉ = 3%, u* = 5%, u = 4%. Ile wynosi inflacja?",
             3.5, "3-0.5*(4-5)", ["π = 3 − 0,5 · (−1) = 3,5%"], unit="%"),
          LB("Przy tych samych parametrach bank chce inflacji 2%. Jakie bezrobocie jest potrzebne?",
             7, "5+(3-2)/0.5", ["2 = 3 − 0,5(u − 5)", "u − 5 = 2 ⇒ u = 7%"], unit="%"),
          LB("Prawo Okuna: c = 2, u* = 5%, u = 7%. Ile wynosi luka PKB (%)?",
             -4, "-2*(7-5)", ["−2 · 2 = −4%"], unit="%"),
          LB("Potencjał wynosi 4000 mld zł. Ile produkcji (mld zł) traci się przy luce −4%?",
             160, "0.04*4000", ["0,04 · 4000 = 160 mld zł"], unit="mld zł"),
          LB("Wskaźnik poświęcenia: obniżenie inflacji o 1 p.p. kosztuje 2% rocznego PKB. Ile kosztuje obniżenie inflacji z 6% do 2% (w % PKB)?",
             8, "2*(6-2)", ["4 p.p. · 2 = 8% PKB"], unit="%"),
          LB("PKB rośnie 1%, a potencjał 3% rocznie (c = 2). O ile p.p. zmieni się bezrobocie (wersja Okuna dla zmian)?",
             1, "(3-1)/2", ["Δu = (g* − g)/c = (3 − 1)/2 = 1 p.p. (wzrost)"], unit="p.p."),
      ],
      case=[
          PR("Na przełomie lat 70. i 80. XX w. inflacja w USA przekraczała 10%. Prezes Fed Paul Volcker drastycznie podniósł stopy procentowe. Inflacja spadła do ok. 4% w ciągu kilku lat, ale bezrobocie przejściowo przekroczyło 10%.",
             W("Jak opisać to w modelu krzywej Phillipsa?",
               "Ruch w dół wzdłuż krótkookresowej krzywej, potem jej przesunięcie w dół wraz ze spadkiem oczekiwań", "Ruch w górę krzywej", "Przesunięcie długookresowej krzywej w prawo",
               why="Najpierw wzrost bezrobocia, potem spadek oczekiwań inflacyjnych."),
             W("Dlaczego dezinflacja była kosztowna?",
               "Oczekiwania inflacyjne i kontrakty płacowe dostosowywały się powoli", "Bo inflacja była ujemna", "Bo Fed obniżał stopy",
               why="Bezwładność inflacji zwiększa wskaźnik poświęcenia."),
             PF("Wzrost wiarygodności banku centralnego obniżył koszty utrzymania niskiej inflacji w kolejnych latach.", True,
                why="Zakotwiczone oczekiwania ułatwiają stabilizację."),
          ),
          PR("W kraju potencjał rośnie o 3% rocznie, a stopa naturalna wynosi 5%. W tym roku PKB wzrósł o 0,5%, a bezrobocie było na poziomie 5%.",
             W("Czego, według prawa Okuna (c = 2), spodziewasz się w przyszłym roku?",
               "Wzrostu bezrobocia o ok. 1,25 p.p.", "Spadku bezrobocia", "Braku zmian",
               why="Δu = (3 − 0,5)/2 = 1,25 p.p."),
             W("Jaka luka PKB powstanie (c = 2), jeśli bezrobocie wzrośnie do 6,25%?",
               "Ok. 2,5% poniżej potencjału", "Ok. 2,5% powyżej potencjału", "Brak luki",
               why="−2 · (6,25 − 5) = −2,5%."),
             PF("Wzrost PKB poniżej tempa potencjału zwykle prowadzi do wzrostu bezrobocia.", True,
                why="Gospodarka nie tworzy wystarczająco wielu miejsc pracy."),
          ),
      ]),
]
