# -*- coding: utf-8 -*-
# Zrozumienie – Makroekonomia / Wzory (nacisk na obliczenia)
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S191 = S("OpenStax, Principles of Economics 3e, 19.1 Measuring the Size of the Economy: GDP", OS3 + "19-1-measuring-the-size-of-the-economy-gross-domestic-product", D)
S192 = S("OpenStax, Principles of Economics 3e, 19.2 Adjusting Nominal Values to Real Values", OS3 + "19-2-adjusting-nominal-values-to-real-values", D)
S221 = S("OpenStax, Principles of Economics 3e, 22.1 Tracking Inflation", OS3 + "22-1-tracking-inflation", D)
S211 = S("OpenStax, Principles of Economics 3e, 21.1 How Economists Define and Compute Unemployment Rate", OS3 + "21-1-how-economists-define-and-compute-unemployment-rate", D)
S234 = S("OpenStax, Principles of Economics 3e, 23.4 The National Saving and Investment Identity", OS3 + "23-4-the-national-saving-and-investment-identity", D)
S252 = S("OpenStax, Principles of Economics 3e, 25.2 The Building Blocks of Keynesian Analysis", OS3 + "25-2-the-building-blocks-of-keynesian-analysis", D)
S253 = S("OpenStax, Principles of Economics 3e, 25.3 The Phillips Curve", OS3 + "25-3-the-phillips-curve", D)
S285 = S("OpenStax, Principles of Economics 3e, 28.5 Pitfalls for Monetary Policy", OS3 + "28-5-pitfalls-for-monetary-policy", D)
S293 = S("OpenStax, Principles of Economics 3e, 29.3 Macroeconomic Effects of Exchange Rates", OS3 + "29-3-macroeconomic-effects-of-exchange-rates", D)
S331 = S("OpenStax, Principles of Economics 3e, 33.1 Absolute and Comparative Advantage", OS3 + "33-1-absolute-and-comparative-advantage", D)
S341 = S("OpenStax, Principles of Economics 3e, 34.1 Protectionism", OS3 + "34-1-protectionism-an-indirect-subsidy-from-consumers-to-producers", D)
S154 = S("OpenStax, Principles of Economics 3e, 15.4 Income Inequality: Measurement and Causes", OS3 + "15-4-income-inequality-measurement-and-causes", D)
S204 = S("OpenStax, Principles of Economics 3e, 20.4 Economic Convergence", OS3 + "20-4-economic-convergence", D)

LESSONS = [
    L(1, "Rachunki narodowe w liczbach",
      "Sprawnie liczyć PKB trzema metodami, przechodzić od PKB do PNB, PNN, dochodu osobistego i rozporządzalnego oraz przeliczać wielkości nominalne na realne deflatorem.",
      ["Metody liczenia PKB", "PKB – metoda wydatkowa", "Wartość dodana – sumowanie", "Produkt narodowy brutto (PNB, DNB)", "Produkt narodowy netto (PNN)",
       "Dochód osobisty i dochód rozporządzalny", "PKB nominalny i realny", "Deflator PKB"],
      [S191, S192, S("Fora.ie – „Leprechaun economics” (PKB Irlandii 2015)", "https://fora.ie/gdp-growth-leprechaun-economics-2-2876246-Jul2016/", D)],
      explain=[
          K("Trzy metody, jeden wynik",
            "Wydatkowa: PKB = C + I + G + (X − M). Produkcyjna: suma wartości dodanej (produkcja − zużycie pośrednie) wszystkich firm. Dochodowa: suma dochodów (płace, zyski, odsetki, renty) plus podatki pośrednie netto i amortyzacja. W teorii wszystkie dają ten sam wynik.",
            w="PKB = C + I + G + X − M"),
          K("Od PKB do dochodu rozporządzalnego",
            "PNB (DNB) = PKB + dochody czynników krajowych z zagranicy − dochody czynników zagranicznych w kraju. PNN = PNB − amortyzacja. Dochód narodowy (w cenach czynników) = PNN − podatki pośrednie netto. Dochód osobisty = dochód narodowy − zyski niewypłacone − składki + transfery. Dochód rozporządzalny = dochód osobisty − podatki bezpośrednie."),
          W("Polscy pracownicy za granicą zarobili 30 mld zł, a zagraniczni właściciele firm w Polsce wypłacili 80 mld zł zysków. PKB = 3900 mld zł. Ile wynosi PNB?",
            "3850 mld zł", "3950 mld zł", "3900 mld zł",
            why="PNB = 3900 + 30 − 80 = 3850."),
          K("Nominalne i realne",
            "PKB nominalny mierzy produkcję w cenach bieżących, realny – w cenach stałych roku bazowego. Deflator PKB = PKB nominalny / PKB realny · 100. Realny wzrost ≈ nominalny wzrost − wzrost deflatora.",
            w="Deflator = PKBnom / PKBreal · 100"),
          K("Wartość dodana",
            "Aby uniknąć podwójnego liczenia, sumujemy tylko wartość dodaną na każdym etapie: rolnik sprzedaje zboże za 2 zł, młyn mąkę za 5 zł, piekarnia chleb za 9 zł – wkład do PKB to 2 + 3 + 4 = 9 zł, czyli wartość dobra finalnego."),
          PF("Sumowanie wartości wszystkich transakcji (także półproduktów) daje PKB.", False,
             why="Zawyża PKB przez podwójne liczenie – liczy się tylko wartość dodana lub dobra finalne."),
      ],
      mech=[
          LN("Ułóż przejście od PKB do dochodu rozporządzalnego.",
             ["PKB", "PNB (+ dochody z zagranicy netto)", "PNN (− amortyzacja)", "Dochód narodowy (− podatki pośrednie netto)", "Dochód osobisty i rozporządzalny (± transfery, − podatki bezpośrednie)"],
             why="Kolejne korekty prowadzą do dochodu, którym dysponują gospodarstwa."),
          KT("Do którego składnika PKB (metoda wydatkowa)?",
             {"C": ["Zakup nowego telewizora przez gospodarstwo", "Opłata za fryzjera"],
              "I": ["Budowa nowego domu", "Wzrost zapasów w magazynach", "Zakup maszyn przez fabrykę"],
              "G": ["Pensje nauczycieli w szkołach publicznych"],
              "Nie wchodzi": ["Zasiłek dla bezrobotnych", "Zakup używanego samochodu od sąsiada"]},
             why="Transfery i dobra używane nie są nową produkcją."),
          W("PKB nominalny rośnie o 7%, deflator o 4%. Ile wynosi realny wzrost (w przybliżeniu)?",
            "3%", "11%", "7%",
            why="Realny ≈ nominalny − deflator = 7 − 4."),
          PF("Zakup akcji na giełdzie zwiększa inwestycje w rachunku PKB.", False,
             why="To transakcja finansowa – inwestycje to zakup nowych dóbr kapitałowych."),
          M("Które wielkości wymagają odjęcia amortyzacji?",
            ["Przejście od PNB do PNN", "Przejście od PKB do PKN (produktu krajowego netto)", "Przejście od PKB do PNB", "Inwestycje netto z inwestycji brutto"],
            [0, 1, 3],
            why="Przejście PKB → PNB dotyczy dochodów z zagranicy, nie amortyzacji."),
          W("Rok bazowy: deflator = 100. W roku bieżącym deflator = 120, PKB realny = 1000. Ile wynosi PKB nominalny?",
            "1200", "1000", "833",
            why="Nominalny = realny · deflator / 100."),
      ],
      calc=[
          LB("C = 2200, I = 700, G = 750, X = 2000, M = 1900 (mld zł). Ile wynosi PKB?",
             3750, "2200+700+750+2000-1900", ["2200 + 700 + 750 + (2000 − 1900) = 3750"], unit="mld zł"),
          LB("Amortyzacja 450, dochody czynników z zagranicy netto −120. Ile wynosi PNN?",
             3180, "3750-120-450", ["PNB = 3750 − 120 = 3630", "PNN = 3630 − 450 = 3180"], unit="mld zł"),
          LB("Rolnik sprzedaje zboże młynowi za 300, młyn mąkę piekarni za 700, piekarnia chleb konsumentom za 1200. Ile wynosi wkład do PKB?",
             1200, "300+(700-300)+(1200-700)", ["300 + 400 + 500 = 1200"], unit=""),
          LB("PKB nominalny 4200, PKB realny 3500. Ile wynosi deflator?",
             120, "4200/3500*100", ["4200 / 3500 · 100 = 120"], unit=""),
          LB("Deflator rośnie ze 120 do 126, a PKB nominalny z 4200 do 4515. O ile procent rośnie PKB realny?",
             2.38, "((4515/126)/(4200/120)-1)*100", ["Realny: 3500 → 3583,3", "3583,3 / 3500 − 1 ≈ 2,38%"], unit="%", tol=0.02),
          LB("Dochód osobisty 2800, podatki bezpośrednie 420. Ile wynosi dochód rozporządzalny?",
             2380, "2800-420", ["2800 − 420 = 2380"], unit=""),
      ],
      case=[
          PR("Irlandia według szacunku z 2016 r. odnotowała w 2015 r. wzrost PKB o 26,3%, głównie przez przeniesienie do kraju majątku i praw własności intelektualnej przez międzynarodowe koncerny. Dochody gospodarstw domowych nie wzrosły w podobnym tempie. Irlandzki urząd statystyczny wprowadził dodatkowy wskaźnik – zmodyfikowany DNB (GNI*).",
             W("Dlaczego PNB/DNB lepiej niż PKB pokazuje dochody Irlandczyków?",
               "Odejmuje dochody wypłacane zagranicznym właścicielom firm", "Bo dodaje dochody zagranicznych koncernów", "Bo nie uwzględnia eksportu",
               why="Duża część dochodów z produkcji w Irlandii trafia do zagranicznych właścicieli."),
             W("Jaka relacja PNB do PKB jest typowa dla kraju z dużym udziałem zagranicznych inwestorów?",
               "PNB mniejszy od PKB", "PNB większy od PKB", "PNB równy PKB",
               why="Wypłacane za granicę zyski i odsetki przewyższają dochody z zagranicy."),
             PF("Przykład Irlandii pokazuje, że PKB może być mylącą miarą dobrobytu mieszkańców.", True,
                why="Wzrost PKB nie przełożył się proporcjonalnie na dochody."),
          ),
          PR("Student porównuje PKB Polski w dwóch latach: nominalny wzrósł o 9%, a GUS podał wzrost realny o 3%. Zastanawia się, skąd ta różnica.",
             W("Ile w przybliżeniu wynosi wzrost deflatora PKB?",
               "Ok. 6%", "Ok. 12%", "Ok. 3%",
               why="Deflator ≈ 9 − 3 = 6% (dokładnie 1,09/1,03 − 1 ≈ 5,8%)."),
             W("Który wzrost lepiej pokazuje zmianę ilości wytworzonych dóbr i usług?",
               "Realny", "Nominalny", "Oba tak samo",
               why="Realny usuwa wpływ zmian cen."),
             PF("Deflator PKB obejmuje ceny wszystkich dóbr finalnych wytworzonych w kraju, także inwestycyjnych i eksportowych.", True,
                why="W odróżnieniu od CPI, które obejmuje koszyk konsumpcyjny."),
          ),
      ]),

    L(2, "Konsumpcja, oszczędności i obieg okrężny",
      "Liczyć funkcję konsumpcji, MPC i MPS, oszczędności narodowe (prywatne i publiczne), odpływy kapitałowe netto oraz warunek równowagi w modelu obiegu okrężnego.",
      ["Funkcja konsumpcji (keynesowska)", "Krańcowa skłonność do konsumpcji (MPC) i oszczędzania (MPS)", "Dochód rozporządzalny i oszczędności",
       "Oszczędności narodowe (prywatne i publiczne)", "Odpływy kapitałowe netto (NCO)", "Model okrężnego obiegu w gospodarce otwartej z państwem"],
      [S252, S234],
      explain=[
          K("Funkcja konsumpcji",
            "C = C₀ + c · Yd, gdzie C₀ – konsumpcja autonomiczna, c – krańcowa skłonność do konsumpcji (MPC), Yd – dochód rozporządzalny. Oszczędności S = Yd − C = −C₀ + (1 − c) · Yd. MPC + MPS = 1.",
            w="C = C₀ + c·Yd;  MPC + MPS = 1"),
          K("Przeciętna a krańcowa skłonność",
            "Przeciętna skłonność do konsumpcji APC = C / Yd, krańcowa MPC = ΔC / ΔYd. Przy dodatniej konsumpcji autonomicznej APC maleje wraz z dochodem i jest większa od MPC."),
          W("Dochód rośnie z 2000 do 2500, konsumpcja z 1800 do 2200. Ile wynosi MPC?",
            "0,8", "0,9", "0,2",
            why="ΔC / ΔY = 400 / 500 = 0,8."),
          K("Oszczędności narodowe i NCO",
            "Oszczędności narodowe = prywatne (Yd − C) + publiczne (T − G). W gospodarce otwartej: S = I + NCO, gdzie NCO (odpływy kapitałowe netto) = zakup aktywów zagranicznych przez rezydentów minus zakup aktywów krajowych przez nierezydentów; NCO = NX.",
            w="S = I + NCO,  NCO = NX"),
          K("Obieg okrężny",
            "Przecieki z obiegu: oszczędności (S), podatki (T), import (M). Zastrzyki: inwestycje (I), wydatki rządowe (G), eksport (X). Równowaga: S + T + M = I + G + X. Gdy zastrzyki przewyższają przecieki, dochód rośnie.",
            w="S + T + M = I + G + X"),
          PF("Jeśli MPC wynosi 0,7, to MPS wynosi 0,3.", True,
             why="MPC + MPS = 1, więc MPS = 1 − 0,7 = 0,3."),
      ],
      mech=[
          KT("Przeciek czy zastrzyk?",
             {"Przeciek": ["Oszczędności gospodarstw", "Podatki", "Import"],
              "Zastrzyk": ["Inwestycje firm", "Wydatki rządowe", "Eksport"]},
             why="Przecieki wyprowadzają dochód z obiegu, zastrzyki go wprowadzają."),
          LN("Ułóż skutki wzrostu zastrzyków ponad przecieki.",
             ["Eksport rośnie", "Zastrzyki przewyższają przecieki", "Dochód i produkcja rosną", "Rosną oszczędności, podatki i import", "Nowa równowaga: S + T + M = I + G + X"],
             why="Przecieki rosną wraz z dochodem aż do zrównania."),
          W("Rząd ma deficyt (T < G). Co to oznacza dla oszczędności narodowych?",
            "Oszczędności publiczne są ujemne i obniżają oszczędności narodowe", "Oszczędności narodowe rosną", "Nic",
            why="Oszczędności publiczne = T − G < 0."),
          PF("Przy dodatniej konsumpcji autonomicznej przeciętna skłonność do konsumpcji spada wraz ze wzrostem dochodu.", True,
             why="APC = C₀/Yd + c, a C₀/Yd maleje."),
          M("Co jest prawdą o NCO?",
            ["NCO = NX (eksport netto)", "Dodatnie NCO oznacza, że kraj kupuje per saldo aktywa zagraniczne", "NCO zawsze równa się zero", "S = I + NCO"],
            [0, 1, 3],
            why="NCO jest zwykle różne od zera."),
          W("Gospodarka zamknięta bez państwa: kiedy dochód jest w równowadze?",
            "Gdy oszczędności równają się inwestycjom", "Gdy eksport równa się importowi", "Gdy podatki równają się wydatkom",
            why="Jedyny przeciek to S, jedyny zastrzyk – I."),
      ],
      calc=[
          LB("C = 200 + 0,75·Yd. Yd = 2400. Ile wynosi konsumpcja?",
             2000, "200+0.75*2400", ["C = 200 + 1800 = 2000"], unit=""),
          LB("Ile wynoszą oszczędności przy tym dochodzie?",
             400, "2400-(200+0.75*2400)", ["S = 2400 − 2000 = 400"], unit=""),
          LB("Ile wynosi przeciętna skłonność do konsumpcji (APC)?",
             0.83, "(200+0.75*2400)/2400", ["2000 / 2400 ≈ 0,833"], unit="", tol=0.02),
          LB("Przy jakim dochodzie oszczędności wynoszą zero (próg)?",
             800, "200/(1-0.75)", ["S = −200 + 0,25·Yd = 0", "Yd = 800"], unit=""),
          LB("Oszczędności prywatne 600, T = 900, G = 1000, I = 450. Ile wynosi NCO?",
             50, "600+(900-1000)-450", ["S narodowe = 600 − 100 = 500", "NCO = 500 − 450 = 50"], unit=""),
          LB("S = 400, T = 800, M = 900, I = 500, G = 850. Jaki eksport zapewnia równowagę obiegu?",
             750, "400+800+900-500-850", ["X = S + T + M − I − G", "2100 − 1350 = 750"], unit=""),
      ],
      case=[
          PR("Gospodarstwa domowe w kraju mają funkcję konsumpcji C = 300 + 0,8·Yd. Rząd rozważa obniżkę podatków o 100 mld zł, co zwiększy dochód rozporządzalny o tyle samo.",
             W("O ile wzrośnie konsumpcja w pierwszej rundzie?",
               "O 80 mld zł", "O 100 mld zł", "O 20 mld zł",
               why="ΔC = 0,8 · 100."),
             W("O ile wzrosną oszczędności prywatne?",
               "O 20 mld zł", "O 80 mld zł", "O 0",
               why="ΔS = MPS · ΔYd = 0,2 · 100."),
             PF("Oszczędności publiczne spadną o 100 mld zł (przy niezmienionych wydatkach).", True,
                why="T − G maleje o wartość obniżki."),
          ),
          PR("Kraj ma oszczędności narodowe 22% PKB i inwestycje 25% PKB. Rząd planuje zredukować deficyt budżetowy o 2% PKB, a oszczędności prywatne i inwestycje się nie zmienią.",
             W("Ile wynosi dziś saldo NCO (= NX) w % PKB?",
               "Deficyt 3% PKB", "Nadwyżka 3% PKB", "Równowaga (0%)",
               why="NCO = S − I = 22 − 25."),
             W("Ile wyniesie NCO po redukcji deficytu?",
               "−1% PKB", "−5% PKB", "+2% PKB",
               why="Oszczędności narodowe rosną do 24%: 24 − 25 = −1."),
             PF("Redukcja deficytu budżetowego może zmniejszyć deficyt handlowy.", True,
                why="Wyższe oszczędności narodowe zmniejszają potrzebę finansowania zagranicznego."),
          ),
      ]),

    L(3, "Mnożniki i równowaga dochodu",
      "Wyznaczać równowagę w modelu mnożnikowym i liczyć mnożnik wydatkowy, podatkowy, zrównoważonego budżetu i w gospodarce otwartej, a także q Tobina.",
      ["Mnożnik (inwestycyjny, wydatkowy)", "Mnożnik podatkowy", "Mnożniki – zestawienie", "Równowaga w modelu mnożnikowym", "Krańcowa skłonność do importu (MPI)", "Inwestycje", "Q Tobina", "Zagregowany popyt (AD)"],
      [S252, S("OpenStax, Principles of Economics 3e, Appendix: The Expenditure-Output Model", OS3 + "d-the-expenditure-output-model", D)],
      explain=[
          K("Równowaga w modelu mnożnikowym",
            "Zagregowane wydatki: AE = C₀ + c(Y − T) + I + G + X − mY. Równowaga, gdy Y = AE. Rozwiązanie: Y = [C₀ − cT + I + G + X] / (1 − c + m).",
            w="Y* = A / (1 − c + m)"),
          K("Zestawienie mnożników",
            "Wydatkowy (gospodarka zamknięta): 1/(1 − c) = 1/MPS. Podatkowy (podatek kwotowy): −c/(1 − c). Zrównoważonego budżetu (ΔG = ΔT): 1. W gospodarce otwartej: 1/(1 − c + m). Z podatkiem proporcjonalnym t: 1/(1 − c(1 − t) + m).",
            w="kG = 1/(1−c);  kT = −c/(1−c)"),
          W("MPC = 0,8, gospodarka zamknięta. Ile wynosi mnożnik podatkowy?",
            "Minus 4", "Minus 5", "Plus 5",
            why="−0,8 / 0,2 = −4."),
          K("Q Tobina",
            "q = rynkowa wartość firmy / koszt odtworzenia jej majątku. Gdy q > 1, opłaca się inwestować (nowy kapitał jest wyceniany przez rynek wyżej, niż kosztuje). Gdy q < 1, taniej jest kupić istniejące firmy niż budować nowe zakłady.",
            w="q = wartość rynkowa / koszt odtworzenia"),
          K("Krańcowa skłonność do importu",
            "MPI = ΔM / ΔY – jaka część dodatkowego dochodu jest wydawana na import. Im wyższa, tym mniejszy mnożnik (więcej „wycieka” za granicę)."),
          PF("Mnożnik zrównoważonego budżetu w prostym modelu wynosi 1.", True,
             why="Efekt wydatków (1/(1−c)) minus efekt podatków (c/(1−c)) daje 1."),
      ],
      mech=[
          LN("Ułóż działanie mnożnika po wzroście inwestycji o 100 (MPC = 0,8).",
             ["Inwestycje rosną o 100 – dochód budowlańców rośnie o 100", "Wydają 80 na konsumpcję", "Sprzedawcy zarabiają 80 i wydają 64", "Kolejne rundy są coraz mniejsze", "Łączny przyrost dochodu: 500"],
             why="100 · 1/(1 − 0,8) = 500."),
          KT("Mnożnik większy czy mniejszy?",
             {"Większy": ["Wyższa MPC", "Niższa krańcowa skłonność do importu"],
              "Mniejszy": ["Wyższa stawka podatku proporcjonalnego", "Wyższa skłonność do importu", "Wyższa skłonność do oszczędzania"]},
             why="Przecieki zmniejszają mnożnik."),
          W("Q Tobina dla branży wynosi 1,4. Co robią firmy?",
            "Zwiększają inwestycje – nowy kapitał jest wart więcej, niż kosztuje", "Ograniczają inwestycje", "Sprzedają majątek",
            why="q > 1 zachęca do inwestowania."),
          PF("Mnożnik podatkowy jest co do wartości bezwzględnej mniejszy niż wydatkowy.", True,
             why="Część obniżki podatku jest oszczędzana – c/(1−c) < 1/(1−c)."),
          M("Co zwiększa dochód równowagi?",
            ["Wzrost wydatków rządowych", "Wzrost eksportu", "Wzrost podatków kwotowych", "Wzrost konsumpcji autonomicznej"],
            [0, 1, 3],
            why="Podatki zmniejszają dochód rozporządzalny i konsumpcję."),
          W("Dlaczego mały, otwarty kraj ma zwykle mniejszy mnożnik niż duży, zamknięty?",
            "Duża część wydatków trafia na import", "Bo nie ma podatków", "Bo MPC wynosi zero",
            why="Wysoka MPI zmniejsza mnożnik."),
      ],
      calc=[
          LB("C = 100 + 0,8(Y − T), T = 250, I = 300, G = 400, gospodarka zamknięta. Ile wynosi dochód równowagi?",
             3000, "(100-0.8*250+300+400)/(1-0.8)", ["A = 100 − 200 + 300 + 400 = 600", "Y = 600 / 0,2 = 3000"], unit=""),
          LB("G rośnie o 50. O ile rośnie Y?",
             250, "50/(1-0.8)", ["ΔY = 50 · 5 = 250"], unit=""),
          LB("Zamiast tego T spada o 50. O ile rośnie Y?",
             200, "0.8/(1-0.8)*50", ["ΔY = 4 · 50 = 200"], unit=""),
          LB("G i T rosną jednocześnie o 50. O ile rośnie Y?",
             50, "50/(1-0.8)-0.8/(1-0.8)*50", ["250 − 200 = 50 – mnożnik zrównoważonego budżetu = 1"], unit=""),
          LB("Gospodarka otwarta: c = 0,8, m = 0,3. Ile wynosi mnożnik wydatkowy?",
             2, "1/(1-0.8+0.3)", ["1 / (0,2 + 0,3) = 2"], unit=""),
          LB("Firma ma wartość giełdową 900 mln zł, a odtworzenie jej majątku kosztowałoby 600 mln zł. Ile wynosi q Tobina?",
             1.5, "900/600", ["900 / 600 = 1,5"], unit=""),
      ],
      case=[
          PR("Rząd małego, otwartego kraju (c = 0,8, krańcowa skłonność do importu 0,4) chce zwiększyć PKB o 30 mld zł, podnosząc wydatki na inwestycje publiczne. Doradca, posługując się mnożnikiem dla gospodarki zamkniętej, proponuje wydać 6 mld zł.",
             W("Ile wynosi faktyczny mnożnik?",
               "1/(1 − 0,8 + 0,4) ≈ 1,67", "5", "2,5",
               why="Import zmniejsza mnożnik."),
             W("Ile trzeba wydać, by PKB wzrósł o 30 mld zł?",
               "Ok. 18 mld zł", "6 mld zł", "30 mld zł",
               why="30 / 1,67 ≈ 18 mld zł."),
             PF("Błąd doradcy wynikał z pominięcia przecieku przez import.", True,
                why="Mnożnik zamknięty (5) zawyża efekt w gospodarce otwartej."),
          ),
          PR("Podczas hossy na giełdzie wartość rynkowa spółek budowlanych wzrosła do 1,6 kosztu odtworzenia ich majątku. W kolejnych miesiącach firmy ogłaszały liczne nowe inwestycje.",
             W("Jak wyjaśnia to teoria Tobina?",
               "q > 1 – inwestycje w nowy kapitał są opłacalne", "q < 1 – firmy sprzedają majątek", "q nie ma związku z inwestycjami",
               why="Rynek wycenia nowy kapitał wyżej niż jego koszt."),
             W("Co stanie się z inwestycjami, jeśli kursy akcji spadną i q spadnie do 0,8?",
               "Zmaleją – taniej kupić istniejące firmy", "Wzrosną", "Nie zmienią się",
               why="q < 1 zniechęca do budowy nowych zakładów."),
             PF("Q Tobina łączy decyzje inwestycyjne z sytuacją na rynku akcji.", True,
                why="Wartość rynkowa zależy od cen akcji."),
          ),
      ]),

    L(4, "Pieniądz, ceny i kursy w liczbach",
      "Liczyć inflację z indeksów, stosować równanie wymiany i efekt Fishera, kurs realny i parytet siły nabywczej oraz krzywą podaży Lucasa.",
      ["Inflacja i indeksy cen", "Równanie wymiany", "Teoria ilościowa pieniądza (równanie wymiany Fishera)", "Efekt Fishera", "Kurs nominalny i realny", "Kurs realny i parytet siły nabywczej – wzory", "Krzywa podaży Lucasa (model wysp)"],
      [S221, S285, S293],
      explain=[
          K("Inflacja z indeksu",
            "π = (Iₜ − Iₜ₋₁) / Iₜ₋₁ · 100%. Indeks łańcuchowy (rok do roku) a jednopodstawowy (względem stałej bazy). Kilka lat inflacji składamy przez mnożenie: (1 + π₁)(1 + π₂) − 1.",
            w="π = (Iₜ / Iₜ₋₁ − 1) · 100%"),
          K("Równanie wymiany i Fisher",
            "M·V = P·Y, w tempach: %ΔM + %ΔV ≈ %ΔP + %ΔY. Efekt Fishera: i ≈ r + πᵉ; dokładnie (1 + i) = (1 + r)(1 + πᵉ).",
            w="(1 + i) = (1 + r)(1 + π)"),
          W("Indeks cen wzrósł z 125 do 130. Ile wynosi inflacja?",
            "4%", "5%", "30%",
            why="130 / 125 − 1 = 4%."),
          K("Kurs realny i PPP",
            "Kurs realny e_r = e · P* / P (e – kurs nominalny w notowaniu bezpośrednim). PPP bezwzględny: e = P / P*. Względny: %Δe ≈ π − π*.",
            w="e_r = e · P* / P"),
          K("Krzywa Lucasa",
            "Y = Y* + α(P − Pᵉ): produkcja przekracza potencjał tylko przy niespodziewanym wzroście cen.",
            w="Y = Y* + α(P − Pᵉ)"),
          PF("Inflacja 10% przez dwa lata oznacza wzrost cen o dokładnie 20%.", False,
             why="1,1 · 1,1 = 1,21 – wzrost o 21%."),
      ],
      mech=[
          KT("Którego wzoru użyjesz?",
             {"Równanie wymiany": ["Szacowanie inflacji z tempa wzrostu pieniądza", "Związek V z P i Y"],
              "Efekt Fishera": ["Realna stopa lokaty przy znanej inflacji", "Nominalna stopa przy oczekiwanej inflacji"],
              "PPP": ["Kurs wynikający z relacji cen koszyków", "Prognoza kursu z różnicy inflacji"]},
             why="Dobór wzoru zależy od pytania."),
          LN("Ułóż obliczanie realnej stopy procentowej dokładnym wzorem.",
             ["Zapisz 1 + i (np. 1,07)", "Zapisz 1 + π (np. 1,04)", "Podziel: 1,07 / 1,04", "Odejmij 1", "Wynik ≈ 2,88%"],
             why="(1 + r) = (1 + i)/(1 + π)."),
          W("M rośnie o 8%, V spada o 2%, Y rośnie o 3%. Ile wynosi inflacja (przybliżenie)?",
            "3%", "13%", "7%",
            why="8 − 2 − 3 = 3%."),
          PF("Przy stałym kursie nominalnym i wyższej inflacji w kraju kurs realny (e·P*/P) spada.", True,
             why="Rośnie P w mianowniku – realna aprecjacja waluty krajowej."),
          M("Które wielkości są potrzebne do policzenia kursu realnego?",
            ["Kurs nominalny", "Poziom cen w kraju", "Stopa bezrobocia", "Poziom cen za granicą"],
            [0, 1, 3],
            why="e_r = e · P* / P."),
          W("W modelu Lucasa: P = Pᵉ. Ile wynosi produkcja?",
            "Produkt potencjalny Y*", "Zero", "Więcej niż Y*",
            why="Brak niespodzianki cenowej."),
      ],
      calc=[
          LB("Indeks cen: 2024 – 100, 2025 – 103,6, 2026 – 107,8. Ile wyniosła inflacja w 2026 r. (%)?",
             4.05, "(107.8/103.6-1)*100", ["107,8 / 103,6 − 1 ≈ 4,05%"], unit="%", tol=0.02),
          LB("Inflacja 3,6%, a potem 4,0%. Ile wyniósł łączny wzrost cen (%)?",
             7.74, "(1.036*1.04-1)*100", ["1,036 · 1,04 = 1,07744", "≈ 7,74%"], unit="%", tol=0.02),
          LB("Lokata 6%, inflacja 3,5%. Ile wynosi dokładna realna stopa (%)?",
             2.42, "(1.06/1.035-1)*100", ["1,06 / 1,035 − 1 ≈ 2,42%"], unit="%", tol=0.02),
          LB("M = 800, V = 5, Y = 2000. Ile wynosi P?",
             2, "800*5/2000", ["P = 4000 / 2000 = 2"], unit=""),
          LB("Kurs 4,30 zł/euro, P (Polska) = 110, P* (strefa euro) = 104. Ile wynosi kurs realny?",
             4.07, "4.30*104/110", ["4,30 · 104 / 110 ≈ 4,065"], unit="", tol=0.02),
          LB("Y = 2000 + 30(P − Pᵉ). P = 108, Pᵉ = 105. Ile wynosi Y?",
             2090, "2000+30*(108-105)", ["2000 + 90 = 2090"], unit=""),
      ],
      case=[
          PR("Oszczędzająca porównuje dwie oferty na rok: lokatę 5,5% oraz obligacje skarbowe oprocentowane według wskaźnika inflacji + 1,25 p.p. Oczekiwana inflacja to 4,0%.",
             W("Ile wynosi oczekiwane oprocentowanie obligacji (w przybliżeniu)?",
               "5,25%", "4,0%", "1,25%",
               why="4,0 + 1,25 = 5,25%."),
             W("Która oferta jest lepsza, jeśli inflacja okaże się 6%?",
               "Obligacje (7,25%)", "Lokata (5,5%)", "Obie tak samo",
               why="Obligacje rosną z inflacją: 6 + 1,25 = 7,25%."),
             PF("Lokata o stałym oprocentowaniu przy inflacji 6% daje ujemną realną stopę zwrotu.", True,
                why="5,5% < 6% – realnie traci się wartość."),
          ),
          PR("Bank centralny zwiększa podaż pieniądza o 10% rocznie. Realny PKB rośnie 3%, a szybkość obiegu spada o 1% rocznie.",
             W("Jakiej inflacji można się spodziewać według równania wymiany?",
               "Ok. 6%", "Ok. 10%", "Ok. 14%",
               why="10 − 1 − 3 = 6%."),
             W("Jaką nominalną stopę procentową przewiduje efekt Fishera przy realnej stopie 1%?",
               "Ok. 7%", "Ok. 1%", "Ok. 11%",
               why="i ≈ 1 + 6 = 7%."),
             PF("Gdyby szybkość obiegu nagle wzrosła, inflacja byłaby wyższa przy tym samym wzroście pieniądza.", True,
                why="%ΔP ≈ %ΔM + %ΔV − %ΔY."),
          ),
      ]),

    L(5, "Rynek pracy, wzrost i handel w liczbach",
      "Liczyć wskaźniki rynku pracy, stosować prawo Okuna i regułę 70, koszty alternatywne w handlu, skutki cła w małym kraju i współczynnik Giniego.",
      ["Stopa bezrobocia", "Stopa bezrobocia i wskaźniki rynku pracy", "Prawo Okuna", "Prawo Okuna – obliczanie", "Reguła 70", "Reguła 70 – wzór",
       "Koszt alternatywny w handlu (przewaga komparatywna)", "Skutki cła w małym kraju – obliczanie", "Współczynnik Giniego – wzór"],
      [S211, S253, S204, S331, S341, S154],
      explain=[
          K("Rynek pracy",
            "u = B / (P + B); współczynnik aktywności = (P + B) / ludność 15+; wskaźnik zatrudnienia = P / ludność 15+.",
            w="u = B / L · 100%"),
          K("Okun i reguła 70",
            "Okun: (Y − Y*)/Y* = −c(u − u*), zwykle c ≈ 2; w wersji zmian: Δu ≈ −(g − g*)/c. Reguła 70: czas podwojenia ≈ 70 / g.",
            w="(Y − Y*)/Y* = −c(u − u*)"),
          W("Bezrobocie jest o 1,5 p.p. wyższe od naturalnego, c = 2. Ile wynosi luka PKB?",
            "3% poniżej potencjału", "3% powyżej potencjału", "1,5% poniżej potencjału",
            why="−2 · 1,5 = −3%."),
          K("Handel i cła",
            "Koszt alternatywny dobra X = rezygnacja z dobra Y / wytworzone X. Cło w małym kraju (cena światowa stała): import spada, cena krajowa rośnie o cło, wpływy = cło · import; strata dobrobytu = dwa trójkąty ½ · cło · (wzrost podaży krajowej) + ½ · cło · (spadek popytu).",
            w="DWL = ½·t·ΔQs + ½·t·ΔQd"),
          K("Gini",
            "G = A / (A + B), gdzie A – pole między linią równości a krzywą Lorenza, B – pole pod krzywą. Ponieważ A + B = 0,5: G = 2A = 1 − 2B.",
            w="G = 1 − 2B"),
          PF("Jeśli pole pod krzywą Lorenza (B) wynosi 0,3, współczynnik Giniego wynosi 0,4.", True,
             why="G = 1 − 2 · 0,3 = 0,4."),
      ],
      mech=[
          LN("Ułóż obliczanie straty dobrobytu z cła.",
             ["Ustal cenę światową i cenę z cłem", "Policz wzrost produkcji krajowej i spadek popytu", "Policz trójkąt produkcyjny: ½ · cło · ΔQs", "Policz trójkąt konsumpcyjny: ½ · cło · ΔQd", "Dodaj oba trójkąty"],
             why="Strata to nieefektywna produkcja i utracona konsumpcja."),
          KT("Którego wzoru użyjesz?",
             {"Okun": ["Szacowanie luki PKB z bezrobocia", "Zmiana bezrobocia przy wolnym wzroście"],
              "Reguła 70": ["Po ilu latach podwoi się PKB", "Porównanie tempa doganiania"],
              "Gini": ["Pomiar nierówności z krzywej Lorenza"]},
             why="Dobór narzędzia do pytania."),
          W("PKB rośnie 1%, potencjał 3%, c = 2. Jak zmieni się bezrobocie?",
            "Wzrośnie o ok. 1 p.p.", "Spadnie o 1 p.p.", "Nie zmieni się",
            why="Δu ≈ (3 − 1)/2 = 1 p.p."),
          PF("Kraj z niższym kosztem alternatywnym wytworzenia dobra powinien je eksportować.", True,
             why="Ma w nim przewagę komparatywną."),
          M("Co rośnie po wprowadzeniu cła w małym kraju?",
            ["Cena krajowa", "Produkcja krajowa", "Import", "Wpływy budżetu"],
            [0, 1, 3],
            why="Import spada, bo cena krajowa rośnie."),
          W("Kraj rośnie 5% rocznie. Ile razy wzrośnie PKB w ciągu 28 lat (reguła 70)?",
            "Ok. 4 razy", "Ok. 2 razy", "Ok. 8 razy",
            why="Podwojenie co 14 lat – dwa podwojenia."),
      ],
      calc=[
          LB("Pracujący 16,8 mln, bezrobotni 0,7 mln, ludność 15+ 31 mln. Ile wynosi stopa bezrobocia (%)?",
             4, "0.7/17.5*100", ["0,7 / 17,5 = 4%"], unit="%"),
          LB("u = 6%, u* = 4%, c = 2, potencjał 4000 mld zł. Ile wynosi utracony PKB (mld zł)?",
             160, "2*(6-4)/100*4000", ["Luka: −2 · 2 = −4%", "0,04 · 4000 = 160 mld zł"], unit="mld zł"),
          LB("Ile lat potrzeba do podwojenia PKB przy wzroście 2,8%?",
             25, "70/2.8", ["70 / 2,8 = 25 lat"], unit="lat"),
          LB("Kraj A: 1 godz. = 6 t stali lub 3 komputery. Ile wynosi koszt alternatywny komputera (t stali)?",
             2, "6/3", ["6 / 3 = 2 t"], unit="t"),
          LB("Mały kraj: cło 5 zł/szt., produkcja krajowa rośnie o 40 tys. szt., popyt spada o 60 tys. szt. Ile wynosi strata dobrobytu (tys. zł)?",
             250, "0.5*5*40+0.5*5*60", ["½ · 5 · 40 = 100", "½ · 5 · 60 = 150", "Razem 250 tys. zł"], unit="tys. zł"),
          LB("Pole pod krzywą Lorenza B = 0,35. Ile wynosi Gini?",
             0.3, "1-2*0.35", ["G = 1 − 0,7 = 0,3"], unit=""),
      ],
      case=[
          PR("Analityk ma dane: realny PKB rośnie 1,5% rocznie, potencjał 3,5%, bezrobocie wynosi dziś 5% i jest równe stopie naturalnej; c = 2.",
             W("Jakie będzie bezrobocie za rok?",
               "Ok. 6%", "Ok. 4%", "5%",
               why="Δu = (3,5 − 1,5)/2 = 1 p.p."),
             W("Jaka luka PKB odpowiada temu bezrobociu?",
               "Ok. 2% poniżej potencjału", "Ok. 2% powyżej potencjału", "Brak luki",
               why="−2 · (6 − 5) = −2%."),
             PF("Wzrost poniżej tempa potencjału otwiera ujemną lukę PKB.", True,
                why="Produkcja oddala się od potencjału."),
          ),
          PR("Mały kraj importuje cukier po cenie światowej 3 zł/kg. Popyt krajowy: Q = 900 − 100P, podaż krajowa: Q = 100P − 100 (tys. t). Rząd wprowadza cło 1 zł/kg.",
             W("Ile wynosi import przed cłem (tys. t)?",
               "400", "200", "600",
               why="Popyt: 600, podaż: 200; import 400."),
             W("Ile wynosi import po cle (cena 4 zł)?",
               "200", "400", "0",
               why="Popyt: 500, podaż: 300; import 200."),
             PF("Wpływy z cła wynoszą 200 mln zł (1 zł · 200 tys. t).", True,
                why="1 zł · 200 000 t = 200 mln zł."),
          ),
      ]),
]
