# -*- coding: utf-8 -*-
# Zrozumienie – Makroekonomia / Konsumpcja, inwestycje i mnożnik
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S251 = S("OpenStax, Principles of Economics 3e, 25.1 Aggregate Demand in Keynesian Analysis", OS3 + "25-1-aggregate-demand-in-keynesian-analysis", D)
S252 = S("OpenStax, Principles of Economics 3e, 25.2 The Building Blocks of Keynesian Analysis", OS3 + "25-2-the-building-blocks-of-keynesian-analysis", D)
SD = S("OpenStax, Principles of Economics 3e, Appendix D – The Expenditure-Output Model", OS3 + "d-the-expenditure-output-model", D)
S234 = S("OpenStax, Principles of Economics 3e, 23.4 The National Saving and Investment Identity", OS3 + "23-4-the-national-saving-and-investment-identity", D)
S172 = S("OpenStax, Principles of Economics 3e, 17.1 How Businesses Raise Financial Capital", OS3 + "17-1-how-businesses-raise-financial-capital", D)

LESSONS = [
    L(1, "Konsumpcja: od czego zależy, ile wydajemy",
      "Rozumieć keynesowską funkcję konsumpcji, krańcową i przeciętną skłonność do konsumpcji oraz hipotezy cyklu życia i dochodu względnego.",
      ["Konsumpcja", "Funkcja konsumpcji (keynesowska)", "Krańcowa skłonność do konsumpcji (MPC) i oszczędzania (MPS)", "Przeciętna skłonność do konsumpcji (APC)",
       "Konsumpcja autonomiczna", "Hipoteza cyklu życia", "Hipoteza dochodu względnego i efekt rygla (zapadki)", "Efekt demonstracji"],
      [S252, SD],
      explain=[
          K("Funkcja konsumpcji Keynesa",
            "Keynes zauważył, że konsumpcja rośnie z dochodem rozporządzalnym, ale wolniej niż on. Najprostsza postać: C = Ca + c·Yd, gdzie Ca – konsumpcja autonomiczna (niezależna od dochodu, np. finansowana z oszczędności), c – krańcowa skłonność do konsumpcji.",
            w="C = Ca + c · Yd;  0 < c < 1"),
          K("MPC i MPS",
            "Krańcowa skłonność do konsumpcji (MPC) mówi, jaką część DODATKOWEJ złotówki dochodu przeznaczamy na konsumpcję; MPS – jaką oszczędzamy. Ponieważ dodatkową złotówkę można tylko wydać albo odłożyć, MPC + MPS = 1.",
            w="MPC = ΔC / ΔYd;  MPS = ΔS / ΔYd;  MPC + MPS = 1"),
          W("Dochód rozporządzalny rośnie o 1000 zł, a konsumpcja o 800 zł. Ile wynosi MPS?",
            "0,2", "0,8", "200", "1,25",
            why="MPC = 0,8, więc MPS = 1 − 0,8 = 0,2."),
          K("Przeciętna skłonność do konsumpcji",
            "APC = C / Yd – jaka część całego dochodu idzie na konsumpcję. Przy dodatniej konsumpcji autonomicznej APC maleje wraz ze wzrostem dochodu: osoby zamożniejsze wydają na konsumpcję mniejszą część dochodu.",
            w="APC = C / Yd"),
          K("Hipotezy o konsumpcji",
            "Cykl życia (Modigliani): ludzie wygładzają konsumpcję w całym życiu – zadłużają się, gdy są młodzi, oszczędzają w wieku produkcyjnym, a na emeryturze konsumują oszczędności. Dochód permanentny (Friedman): konsumpcja zależy od trwałego, oczekiwanego dochodu, a nie od jednorazowych wpływów. Dochód względny (Duesenberry): liczy się porównanie z innymi i dotychczasowym poziomem (efekt demonstracji, efekt rygla)."),
          PF("Według hipotezy dochodu permanentnego jednorazowa premia silniej zwiększy konsumpcję niż trwała podwyżka tej samej kwoty rocznie.", False,
             why="Trwała podwyżka zmienia dochód permanentny, więc zwiększa konsumpcję silniej niż jednorazowa wpłata."),
      ],
      mech=[
          KT("Która hipoteza tłumaczy zachowanie?",
             {"Cykl życia": ["Student bierze kredyt, licząc na przyszłe zarobki", "Emeryt wydaje oszczędności z okresu pracy"],
              "Dochód permanentny": ["Jednorazowa nagroda trafia głównie na lokatę", "Trwała podwyżka szybko zwiększa wydatki rodziny"],
              "Dochód względny": ["Rodzina kupuje nowy samochód, bo sąsiedzi kupili", "Po spadku dochodu rodzina utrzymuje wydatki kosztem oszczędności"]},
             why="Każda hipoteza inaczej wyjaśnia związek dochodu i konsumpcji."),
          LN("Ułóż, jak wzrost dochodu przenosi się na konsumpcję (funkcja Keynesa).",
             ["Dochód rozporządzalny rośnie o 1000 zł", "Gospodarstwo wydaje część przyrostu (MPC · 1000)", "Resztę oszczędza (MPS · 1000)", "Konsumpcja rośnie, ale mniej niż dochód"],
             why="Ponieważ 0 < MPC < 1, konsumpcja rośnie mniej niż dochód."),
          W("Obniżka podatków zapowiedziana jako tymczasowa (na 1 rok). Jak zareagują konsumenci według hipotezy dochodu permanentnego?",
            "Zwiększą konsumpcję niewiele – dochód trwały prawie się nie zmienia", "Silnie zwiększą konsumpcję", "Zmniejszą konsumpcję",
            why="Tymczasowe zmiany dochodu mają słaby wpływ na konsumpcję."),
          W("Dlaczego APC biednych gospodarstw jest zwykle wyższa niż zamożnych?",
            "Muszą przeznaczyć większość dochodu na bieżące potrzeby", "Bo mają wyższe MPS", "Bo nie płacą podatków",
            why="Przy niskim dochodzie konsumpcja pochłania prawie cały dochód (lub więcej)."),
          PF("Jeśli MPC = 0,75, to z każdych dodatkowych 100 zł dochodu 25 zł trafia do oszczędności.", True,
             why="MPS = 1 − 0,75 = 0,25."),
          M("Które zdania są prawdziwe dla funkcji C = 200 + 0,8Yd?",
            ["Konsumpcja autonomiczna wynosi 200", "MPC = 0,8", "APC jest stała przy każdym dochodzie", "Przy Yd = 1000 konsumpcja wynosi 1000"],
            [0, 1, 3],
            why="APC = 200/Yd + 0,8 maleje z dochodem."),
      ],
      calc=[
          LB("C = 300 + 0,75Yd. Ile wynosi konsumpcja przy dochodzie rozporządzalnym 2000?",
             1800, "300+0.75*2000", ["C = 300 + 1500 = 1800"], unit=""),
          LB("Dla tej funkcji ile wynosi APC przy Yd = 2000?",
             0.9, "1800/2000", ["APC = 1800 / 2000 = 0,9"], unit=""),
          LB("Przy jakim dochodzie oszczędności są zerowe (C = Yd) dla C = 300 + 0,75Yd?",
             1200, "300/0.25", ["Yd = 300 + 0,75Yd ⇒ 0,25Yd = 300", "Yd = 1200"], unit=""),
          LB("Dochód wzrósł z 5000 do 5600 zł, konsumpcja z 4600 do 5050 zł. Ile wynosi MPC?",
             0.75, "(5050-4600)/(5600-5000)", ["ΔC = 450, ΔYd = 600", "MPC = 0,75"], unit=""),
          LB("Cykl życia: osoba pracuje 40 lat, zarabiając 60 tys. zł rocznie, i żyje jeszcze 20 lat na emeryturze bez dochodu. Ile może konsumować rocznie przy równej konsumpcji przez 60 lat (bez odsetek)?",
             40, "40*60/60", ["Łączny dochód: 40 · 60 = 2400 tys. zł", "Na 60 lat: 2400 / 60 = 40 tys. zł rocznie"], unit="tys. zł"),
          LB("Ile ta osoba oszczędza rocznie w okresie pracy?",
             20, "60-40", ["60 − 40 = 20 tys. zł rocznie – na emeryturę"], unit="tys. zł"),
      ],
      case=[
          PR("Rząd rozważa dwie formy wsparcia rodzin o tej samej wartości budżetowej: jednorazowy bon 2000 zł albo trwałe zwiększenie zasiłku o 170 zł miesięcznie (2040 zł rocznie). Cel: pobudzić konsumpcję.",
             W("Która forma według hipotezy dochodu permanentnego silniej zwiększy konsumpcję?",
               "Trwałe zwiększenie zasiłku", "Jednorazowy bon", "Obie identycznie",
               why="Trwała zmiana dochodu zmienia dochód permanentny."),
             W("Która grupa najsilniej wyda jednorazowy bon?",
               "Gospodarstwa o niskich dochodach i bez oszczędności (wysoka MPC)", "Najzamożniejsze gospodarstwa", "Emeryci z dużymi oszczędnościami",
               why="Gospodarstwa z ograniczeniami płynności wydają dodatkowy dochód prawie w całości."),
             PF("Kierowanie wsparcia do gospodarstw o wysokiej MPC zwiększa efekt dla konsumpcji przy tym samym koszcie.", True,
                why="Większa część środków trafia do obiegu jako wydatki."),
          ),
          PR("Badanie budżetów domowych: rodziny z najniższego kwintyla wydają na konsumpcję 102% dochodu (zadłużają się lub korzystają z oszczędności), a z najwyższego – 70%.",
             LB("Ile wynosi APC najbiedniejszej grupy?",
                1.02, "102/100", ["APC = 102 / 100 = 1,02"], unit=""),
             W("Co oznacza APC > 1?",
               "Konsumpcja przewyższa dochód – ujemne oszczędności", "Błąd w danych", "Bardzo wysokie oszczędności",
               why="Brakującą część finansuje się kredytem lub wcześniejszymi oszczędnościami."),
             PF("Przesunięcie dochodu od rodzin zamożnych do biednych może krótkookresowo zwiększyć łączną konsumpcję.", True,
                why="Biedniejsze gospodarstwa mają wyższą skłonność do konsumpcji."),
          ),
      ]),

    L(2, "Inwestycje: stopy procentowe, oczekiwania i akcelerator",
      "Rozumieć, od czego zależą inwestycje (stopa procentowa, oczekiwania, wykorzystanie mocy, q Tobina), zasadę akceleracji i tożsamość oszczędności–inwestycje.",
      ["Inwestycje", "Akcelerator (zasada akceleracji)", "Q Tobina", "Oszczędności narodowe (prywatne i publiczne)", "Odpływy kapitałowe netto (NCO)",
       "Inwestycje bezpośrednie (BIZ) i portfelowe"],
      [S234, S172, S252],
      explain=[
          K("Inwestycje w makroekonomii",
            "Inwestycje (I) to zakupy dóbr kapitałowych: maszyn, budynków, oprogramowania, a także budowa mieszkań i przyrost zapasów. Zakup akcji czy obligacji to inwestycja finansowa, a nie inwestycja w rozumieniu PKB."),
          K("Stopa procentowa i oczekiwania",
            "Firma inwestuje, gdy oczekiwana stopa zwrotu przewyższa koszt kapitału. Wyższa realna stopa procentowa podnosi koszt finansowania i obniża inwestycje. Keynes podkreślał rolę „zwierzęcych instynktów” – nastrojów przedsiębiorców, które sprawiają, że inwestycje są najbardziej zmiennym składnikiem PKB."),
          W("Bank centralny podnosi stopy procentowe. Co dzieje się z inwestycjami (przy innych warunkach bez zmian)?",
            "Spadają – rośnie koszt kapitału", "Rosną", "Nie zmieniają się",
            why="Część projektów przestaje przewyższać koszt finansowania."),
          K("Akcelerator",
            "Zasada akceleracji: inwestycje zależą od ZMIANY produkcji. Jeśli do wytworzenia 1 zł produkcji rocznie potrzeba 3 zł kapitału, wzrost sprzedaży o 100 wymaga inwestycji 300. Gdy wzrost sprzedaży tylko zwalnia (a nie spada), inwestycje mogą spaść – to wzmacnia wahania cyklu.",
            w="I = v · ΔY  (v – współczynnik kapitałochłonności)"),
          K("q Tobina i tożsamość S = I + NCO",
            "q Tobina = rynkowa wartość firm / koszt odtworzenia ich kapitału. Gdy q > 1, opłaca się budować nowy kapitał. W gospodarce otwartej oszczędności narodowe (prywatne + publiczne) finansują inwestycje krajowe i odpływ kapitału netto za granicę.",
            w="q = wartość rynkowa / koszt odtworzenia;  S = I + NCO"),
          PF("Spowolnienie wzrostu sprzedaży (z 10% do 5% rocznie) może według akceleratora obniżyć poziom inwestycji.", True,
             why="Inwestycje zależą od przyrostu produkcji – mniejszy przyrost oznacza mniejsze inwestycje."),
      ],
      mech=[
          LN("Ułóż działanie akceleratora w czasie ożywienia.",
             ["Popyt na produkty rośnie", "Firmy wykorzystują moce w pełni", "Potrzebują dodatkowych maszyn i hal", "Inwestycje rosną szybciej niż produkcja", "Wzrost dochodów dodatkowo zwiększa popyt"],
             why="Akcelerator wzmacnia ożywienie (i spadek w recesji)."),
          KT("Co zwiększa, a co zmniejsza inwestycje?",
             {"Zwiększa": ["Optymistyczne prognozy sprzedaży", "Spadek realnych stóp procentowych", "Wysokie wykorzystanie mocy produkcyjnych", "q Tobina powyżej 1"],
              "Zmniejsza": ["Niepewność co do przepisów podatkowych", "Wzrost kosztu kredytu", "Wolne moce produkcyjne w fabrykach"]},
             why="Inwestycje zależą od kosztu kapitału i oczekiwanych zysków."),
          W("Kurs akcji spółek budowlanych mocno przewyższa koszt budowy nowych zakładów (q > 1). Co powinno się stać?",
            "Firmy zwiększą inwestycje w nowe zakłady", "Firmy zmniejszą inwestycje", "Nic",
            why="Rynek wycenia kapitał wyżej niż koszt jego wytworzenia – opłaca się go budować."),
          W("Zagraniczny koncern buduje fabrykę w Polsce. To jest:",
            "Bezpośrednia inwestycja zagraniczna (BIZ)", "Inwestycja portfelowa", "Import dóbr konsumpcyjnych",
            why="BIZ oznacza trwałe zaangażowanie i kontrolę nad przedsiębiorstwem; inwestycja portfelowa – zakup papierów bez kontroli."),
          PF("Wzrost deficytu budżetowego zmniejsza oszczędności narodowe przy niezmienionych oszczędnościach prywatnych.", True,
             why="Oszczędności publiczne = T − G; deficyt to ujemne oszczędności publiczne."),
          M("Które pozycje są inwestycjami w rachunkach narodowych?",
            ["Budowa nowego domu", "Zakup maszyny przez fabrykę", "Kupno akcji na giełdzie", "Przyrost zapasów w magazynie"],
            [0, 1, 3],
            why="Akcje to aktywo finansowe."),
      ],
      calc=[
          LB("Współczynnik kapitałochłonności v = 3. Produkcja rośnie z 1000 do 1050. Ile wynoszą inwestycje netto według akceleratora?",
             150, "3*(1050-1000)", ["ΔY = 50", "I = 3 · 50 = 150"], unit=""),
          LB("W kolejnym roku produkcja rośnie z 1050 do 1080. Ile wynoszą inwestycje (v = 3)?",
             90, "3*(1080-1050)", ["ΔY = 30", "I = 90 – spadek inwestycji mimo dalszego wzrostu produkcji"], unit=""),
          LB("Oszczędności prywatne 500 mld zł, deficyt budżetu 150 mld zł. Ile wynoszą oszczędności narodowe?",
             350, "500-150", ["S = 500 + (−150) = 350 mld zł"], unit="mld zł"),
          LB("Oszczędności narodowe 350 mld zł, inwestycje krajowe 420 mld zł. Ile wynoszą odpływy kapitałowe netto (NCO, ze znakiem)?",
             -70, "350-420", ["NCO = S − I = −70 mld zł – napływ kapitału z zagranicy"], unit="mld zł"),
          LB("Wartość rynkowa spółki 900 mln zł, koszt odtworzenia jej majątku 600 mln zł. Ile wynosi q Tobina?",
             1.5, "900/600", ["q = 900 / 600 = 1,5"], unit=""),
          LB("Projekt: nakład 1 mln zł, oczekiwany zysk 70 tys. zł rocznie. Stopa procentowa rośnie z 5% do 8%. O ile punktów procentowych stopa zwrotu projektu przewyższa nowy koszt kapitału (ze znakiem)?",
             -1, "7-8", ["Stopa zwrotu: 70 / 1000 = 7%", "7% − 8% = −1 p.p. – projekt przestaje być opłacalny"], unit="p.p."),
      ],
      case=[
          PR("Producent mebli wykorzystuje 95% mocy. Zamówienia rosną o 10% rocznie, a bank obniżył oprocentowanie kredytów inwestycyjnych. Zarząd rozważa nową halę za 40 mln zł.",
             W("Które czynniki przemawiają za inwestycją?",
               "Wysokie wykorzystanie mocy, rosnący popyt i tańszy kredyt", "Wolne moce produkcyjne", "Spadające zamówienia",
               why="Wszystkie trzy czynniki zwiększają opłacalność inwestycji."),
             LB("Hala ma dać 5 mln zł zysku rocznie. Ile wynosi prosta stopa zwrotu (w %)?",
                12.5, "5/40*100", ["5 / 40 = 12,5%"], unit="%"),
             PF("Gdyby zamówienia przestały rosnąć, inwestycja mogłaby zostać wstrzymana mimo niskich stóp.", True,
                why="Akcelerator: inwestycje zależą od przyrostu popytu."),
          ),
          PR("W kraju oszczędności prywatne wynoszą 18% PKB, deficyt budżetu 5% PKB, a inwestycje 17% PKB.",
             LB("Ile wynoszą oszczędności narodowe (% PKB)?",
                13, "18-5", ["18 − 5 = 13% PKB"], unit="% PKB"),
             LB("Ile wynosi napływ kapitału z zagranicy (−NCO, % PKB)?",
                4, "17-13", ["I − S = 17 − 13 = 4% PKB"], unit="% PKB"),
             W("Co oznacza ten napływ dla rachunku obrotów bieżących?",
               "Kraj ma deficyt obrotów bieżących ok. 4% PKB", "Nadwyżkę obrotów bieżących", "Nie ma związku",
               why="Saldo obrotów bieżących ≈ S − I."),
          ),
      ]),

    L(3, "Model Keynesa: równowaga i luki",
      "Wyznaczać równowagę w krzyżu keynesowskim (Y = C + I + G + NX), rozumieć dostosowanie przez zapasy oraz luki inflacyjną i recesyjną.",
      ["Model Keynesa (krzyż keynesowski)", "Wydatki autonomiczne", "Luka inflacyjna i deflacyjna (recesyjna)", "Odpływy (przecieki) z obiegu"],
      [SD, S251],
      explain=[
          K("Planowane wydatki i produkcja",
            "W modelu Keynesa w krótkim okresie ceny są sztywne, a produkcja dostosowuje się do popytu. Planowane wydatki: AE = C + I + G + NX. Równowaga zachodzi, gdy produkcja Y równa się planowanym wydatkom.",
            w="Y = AE = C + I + G + (X − M)"),
          K("Dostosowanie przez zapasy",
            "Jeśli firmy produkują więcej, niż wynoszą planowane wydatki, rosną niechciane zapasy – firmy ograniczają produkcję. Jeśli produkują mniej – zapasy się kurczą i produkcja rośnie. Gospodarka zmierza do punktu, w którym AE = Y (przecięcie z linią 45°)."),
          W("Produkcja wynosi 1000, a planowane wydatki 950. Co się stanie?",
            "Rosną niechciane zapasy, produkcja spadnie", "Produkcja wzrośnie", "Nic się nie zmieni",
            why="Firmy produkują więcej, niż kupują nabywcy."),
          K("Równowaga przy C = Ca + cY",
            "Dla gospodarki zamkniętej bez podatków: Y = Ca + cY + I + G, więc Y = (Ca + I + G) / (1 − c). Wydatki autonomiczne pomnożone przez mnożnik dają produkcję równowagi.",
            w="Y* = A / (1 − c),  A = wydatki autonomiczne"),
          K("Luki",
            "Jeśli równowaga keynesowska leży poniżej produktu potencjalnego, mamy lukę recesyjną (bezrobocie). Jeśli powyżej – lukę inflacyjną (przegrzanie). Keynes zalecał zwiększanie wydatków w recesji, by zamknąć lukę."),
          PF("W modelu Keynesa równowaga musi zawsze oznaczać pełne zatrudnienie.", False,
             why="Kluczowa teza Keynesa: równowaga może utrzymywać się przy bezrobociu."),
      ],
      mech=[
          LN("Ułóż, jak gospodarka wraca do równowagi, gdy planowane wydatki przewyższają produkcję.",
             ["Planowane wydatki > produkcja", "Zapasy w magazynach maleją", "Firmy zwiększają produkcję i zatrudnienie", "Rosną dochody i konsumpcja", "Produkcja dochodzi do poziomu AE = Y"],
             why="W modelu Keynesa dostosowuje się ilość, a nie cena."),
          KT("Luka recesyjna czy inflacyjna?",
             {"Recesyjna": ["Równowaga 900, potencjał 1000", "Rosnące bezrobocie i wolne moce", "Wydatki autonomiczne spadły po kryzysie"],
              "Inflacyjna": ["Równowaga 1050, potencjał 1000", "Brak rąk do pracy, rosnące płace", "Boom kredytowy ponad możliwości gospodarki"]},
             why="Porównujemy równowagę z produktem potencjalnym."),
          W("Inwestycje spadają o 50 przy MPC = 0,8 (gospodarka zamknięta, bez podatków). O ile spadnie produkcja równowagi?",
            "O 250", "O 50", "O 40", "O 62,5",
            why="Mnożnik 1/(1 − 0,8) = 5, więc 5 · 50 = 250."),
          W("Co oznacza przecięcie linii AE z linią 45°?",
            "Punkt, w którym planowane wydatki równają się produkcji", "Pełne zatrudnienie", "Maksymalne zyski firm",
            why="Linia 45° to wszystkie punkty AE = Y."),
          PF("Wzrost oszczędności autonomicznych (spadek Ca) obniża produkcję równowagi w modelu Keynesa.", True,
             why="Spadają wydatki autonomiczne, a z nimi – przez mnożnik – produkcja."),
          M("Które zdarzenia przesuwają linię AE w górę?",
            ["Wzrost wydatków rządowych", "Wzrost eksportu", "Wzrost podatków", "Wzrost optymizmu przedsiębiorców (inwestycje)"],
            [0, 1, 3],
            why="Wzrost podatków obniża dochód rozporządzalny i konsumpcję."),
      ],
      calc=[
          LB("C = 100 + 0,75Y, I = 150, G = 250 (gospodarka zamknięta, bez podatków). Ile wynosi Y równowagi?",
             2000, "(100+150+250)/(1-0.75)", ["A = 500", "Y = 500 / 0,25 = 2000"], unit=""),
          LB("Ile wynosi konsumpcja w tej równowadze?",
             1600, "100+0.75*2000", ["C = 100 + 1500 = 1600"], unit=""),
          LB("Potencjał wynosi 2200. Ile wynosi luka recesyjna (w jednostkach produkcji)?",
             200, "2200-2000", ["2200 − 2000 = 200"], unit=""),
          LB("O ile muszą wzrosnąć wydatki rządowe, by zamknąć tę lukę (mnożnik 4)?",
             50, "200/4", ["ΔG = 200 / 4 = 50"], unit=""),
          LB("Produkcja 2100, a planowane wydatki przy tej produkcji wynoszą 100 + 0,75·2100 + 150 + 250. O ile rosną niechciane zapasy?",
             25, "2100-(100+0.75*2100+150+250)", ["AE = 100 + 1575 + 400 = 2075", "Zapasy: 2100 − 2075 = 25"], unit=""),
          LB("C = 50 + 0,8Y, I = 100, G = 150, X = 120, M = 120 (NX = 0). Ile wynosi Y równowagi?",
             1500, "(50+100+150+0)/(1-0.8)", ["A = 300", "Y = 300 / 0,2 = 1500"], unit=""),
      ],
      case=[
          PR("Po kryzysie finansowym przedsiębiorstwa ograniczyły inwestycje o 80 mld zł, a gospodarstwa domowe zwiększyły ostrożnościowe oszczędności (konsumpcja autonomiczna spadła o 20 mld zł). MPC w gospodarce wynosi 0,6 (uwzględniając podatki i import).",
             LB("O ile spadną łącznie wydatki autonomiczne (mld zł)?",
                100, "80+20", ["80 + 20 = 100 mld zł"], unit="mld zł"),
             LB("O ile spadnie produkcja równowagi (mnożnik 1/(1 − 0,6))?",
                250, "100/(1-0.6)", ["Mnożnik = 2,5", "ΔY = 2,5 · 100 = 250 mld zł"], unit="mld zł"),
             W("Co według Keynesa powinien zrobić rząd?",
               "Zwiększyć wydatki lub obniżyć podatki, by zamknąć lukę recesyjną", "Zwiększyć podatki, by zrównoważyć budżet", "Nic – gospodarka szybko sama wróci do potencjału",
               why="Przy sztywnych cenach i płacach luka może utrzymywać się długo."),
          ),
          PR("Gospodarka ma silny boom: planowane wydatki rosną szybciej niż produkt potencjalny, zapasy w sklepach się kurczą, a firmy zgłaszają brak pracowników.",
             W("Jaka luka się otwiera?",
               "Inflacyjna", "Recesyjna", "Żadna",
               why="Popyt przekracza możliwości produkcyjne gospodarki."),
             W("Co może ograniczyć lukę według logiki modelu?",
               "Ograniczenie wydatków rządowych lub podwyżka podatków", "Zwiększenie wydatków rządowych", "Obniżka podatków",
               why="Trzeba zmniejszyć planowane wydatki."),
             PF("W tej sytuacji należy spodziewać się presji na wzrost cen i płac.", True,
                why="Model Keynesa przy luce inflacyjnej sygnalizuje przegrzanie."),
          ),
      ]),

    L(4, "Mnożniki: wydatkowy, podatkowy i Haavelmo",
      "Liczyć mnożnik wydatkowy, podatkowy, zrównoważonego budżetu i mnożnik w gospodarce otwartej z podatkami; rozumieć, od czego zależy jego wielkość.",
      ["Mnożnik (inwestycyjny, wydatkowy)", "Mnożnik podatkowy", "Mnożnik zrównoważonego budżetu (Haavelmo)", "Krańcowa skłonność do importu (MPI)"],
      [SD, S252],
      explain=[
          K("Skąd bierze się mnożnik",
            "Rząd wydaje 100 zł na remont szkoły. Robotnicy dostają 100 zł dochodu i wydają z niego część (MPC · 100), która staje się dochodem sklepikarzy, którzy znów wydają część… Suma wszystkich rund jest większa niż pierwotne 100 zł.",
            w="mnożnik wydatkowy k = 1 / (1 − MPC) = 1 / MPS"),
          K("Mnożnik podatkowy",
            "Obniżka podatków o 100 zł zwiększa dochód rozporządzalny o 100 zł, ale w pierwszej rundzie wydawane jest tylko MPC · 100 – dlatego mnożnik podatkowy jest mniejszy (co do wartości) niż wydatkowy i ma znak ujemny.",
            w="kT = −MPC / (1 − MPC)"),
          W("MPC = 0,8. Ile wynosi mnożnik wydatkowy?",
            "5", "4", "0,8", "1,25",
            why="1 / (1 − 0,8) = 5."),
          K("Twierdzenie Haavelmo",
            "Jeśli rząd zwiększy wydatki i podatki o tę samą kwotę (budżet zrównoważony), produkcja wzrośnie o tę kwotę – mnożnik zrównoważonego budżetu wynosi 1 (w prostym modelu z podatkami ryczałtowymi).",
            w="k + kT = 1/(1 − c) − c/(1 − c) = 1"),
          K("Przecieki zmniejszają mnożnik",
            "Gdy część dochodu trafia do podatków (stawka t) i na import (MPI), w każdej rundzie mniej pieniędzy zostaje w krajowym obiegu. Dla małych, otwartych gospodarek mnożnik jest więc wyraźnie niższy niż 1/(1 − MPC).",
            w="k = 1 / [1 − MPC·(1 − t) + MPI]"),
          PF("Im wyższa krańcowa skłonność do importu, tym większy mnożnik wydatków krajowych.", False,
             why="Import to przeciek – zmniejsza mnożnik."),
      ],
      mech=[
          LN("Ułóż kolejne rundy mnożnika (MPC = 0,5, początkowy wydatek 100).",
             ["Rząd wydaje 100 – dochód rośnie o 100", "Odbiorcy wydają 50", "Kolejni wydają 25", "Następni wydają 12,5", "Suma dąży do 200"],
             why="100 · (1 + 0,5 + 0,25 + …) = 100 / (1 − 0,5) = 200."),
          KT("Co zwiększa, a co zmniejsza mnożnik?",
             {"Zwiększa": ["Wyższa MPC", "Niższa stopa podatkowa"],
              "Zmniejsza": ["Wyższa krańcowa skłonność do importu", "Wyższa skłonność do oszczędzania", "Wyższa stopa podatku dochodowego"]},
             why="Mnożnik zależy od tego, ile z każdej złotówki zostaje w krajowym obiegu."),
          W("Dlaczego mnożnik podatkowy jest (co do wartości) mniejszy od wydatkowego?",
            "Bo część obniżki podatków zostaje zaoszczędzona już w pierwszej rundzie", "Bo podatki nie wpływają na dochód", "Bo rząd marnuje pieniądze",
            why="Wydatek rządowy w całości staje się dochodem, obniżka podatku – tylko w części wydatkiem."),
          W("Rząd zwiększa wydatki i podatki o 10 mld zł. O ile wzrośnie PKB według twierdzenia Haavelmo?",
            "O 10 mld zł", "O 0", "O 50 mld zł", "O 40 mld zł",
            why="Mnożnik zrównoważonego budżetu wynosi 1."),
          PF("W małej gospodarce otwartej z wysokim importem mnożnik fiskalny jest zwykle mniejszy niż w dużej, zamkniętej gospodarce.", True,
             why="Duża część wydatków „wycieka” za granicę."),
          M("Dla MPC = 0,75 (bez podatków proporcjonalnych i importu) które wartości są poprawne?",
            ["Mnożnik wydatkowy = 4", "Mnożnik podatkowy = −3", "Mnożnik zrównoważonego budżetu = 4", "MPS = 0,25"],
            [0, 1, 3],
            why="Mnożnik zrównoważonego budżetu = 4 − 3 = 1."),
      ],
      calc=[
          LB("MPC = 0,9. Ile wynosi mnożnik wydatkowy?",
             10, "1/(1-0.9)", ["1 / 0,1 = 10"], unit=""),
          LB("MPC = 0,8. Ile wynosi mnożnik podatkowy (ze znakiem)?",
             -4, "-0.8/(1-0.8)", ["−0,8 / 0,2 = −4"], unit=""),
          LB("MPC = 0,8, stopa podatku t = 0,25, MPI = 0,2. Ile wynosi mnożnik (1/[1 − c(1 − t) + MPI])?",
             1.67, "1/(1-0.8*(1-0.25)+0.2)", ["c(1 − t) = 0,8 · 0,75 = 0,6", "Mianownik: 1 − 0,6 + 0,2 = 0,6", "k = 1 / 0,6 ≈ 1,67 (bez przecieków byłoby 5)"], unit="", tol=0.01),
          LB("Wydatki rządowe rosną o 30 mld zł, mnożnik 2,5. O ile wzrośnie PKB?",
             75, "30*2.5", ["30 · 2,5 = 75 mld zł"], unit="mld zł"),
          LB("Obniżka podatków o 20 mld zł przy MPC = 0,75 (bez innych przecieków). O ile wzrośnie PKB?",
             60, "20*0.75/(1-0.75)", ["Mnożnik podatkowy: 0,75 / 0,25 = 3", "ΔY = 60 mld zł"], unit="mld zł"),
          LB("Rząd zwiększa G i T o 15 mld zł (Haavelmo). O ile zmieni się PKB?",
             15, "15*1", ["Mnożnik zrównoważonego budżetu = 1", "ΔY = 15 mld zł"], unit="mld zł"),
      ],
      case=[
          PR("Rząd planuje pakiet 40 mld zł na inwestycje infrastrukturalne. Ekonomiści szacują, że w Polsce, przy wysokim udziale importu i podatków, mnożnik wynosi ok. 1,2, a nie 1/(1 − 0,8) = 5 z prostego modelu.",
             LB("O ile wzrośnie PKB przy mnożniku 1,2 (mld zł)?",
                48, "40*1.2", ["40 · 1,2 = 48 mld zł"], unit="mld zł"),
             W("Dlaczego realny mnożnik jest dużo niższy niż w prostym modelu?",
               "Przecieki: podatki, import, oszczędności i wypychanie inwestycji prywatnych", "Bo rząd źle liczy", "Bo MPC wynosi 1",
               why="W każdej rundzie część dochodu wypływa z krajowego obiegu."),
             PF("Jeśli część materiałów budowlanych jest importowana, mnożnik dla polskiej gospodarki jest niższy.", True,
                why="Wydatek na import zwiększa produkcję za granicą."),
          ),
          PR("Kraj w recesji. Opcja A: wydatki rządowe +20 mld zł. Opcja B: obniżka podatków o 20 mld zł. MPC = 0,75 (prosty model bez innych przecieków).",
             LB("Ile wzrośnie PKB w opcji A?",
                80, "20/(1-0.75)", ["Mnożnik 4: 20 · 4 = 80 mld zł"], unit="mld zł"),
             LB("Ile wzrośnie PKB w opcji B?",
                60, "20*0.75/(1-0.75)", ["Mnożnik podatkowy 3: 20 · 3 = 60 mld zł"], unit="mld zł"),
             W("Kiedy opcja B mogłaby działać silniej niż wynika z modelu?",
               "Gdy obniżka trafia do osób o wysokiej MPC (np. o niskich dochodach)", "Gdy obniżka trafia do najzamożniejszych", "Nigdy",
               why="Wtedy większa część obniżki jest wydawana."),
          ),
      ]),

    L(5, "Paradoks zapobiegliwości i niestabilność finansowa",
      "Rozumieć paradoks zapobiegliwości (oszczędności), przecieki z obiegu, hipotezę niestabilności finansowej Minsky’ego i akcelerator finansowy.",
      ["Paradoks zapobiegliwości (oszczędności)", "Odpływy (przecieki) z obiegu", "Hipoteza niestabilności finansowej", "Akcelerator finansowy"],
      [S251, S("OpenStax, Principles of Economics 3e, 28.5 Pitfalls for Monetary Policy", OS3 + "28-5-pitfalls-for-monetary-policy", D)],
      explain=[
          K("Paradoks zapobiegliwości",
            "Dla jednej rodziny oszczędzanie więcej to rozsądek. Ale jeśli w recesji wszyscy jednocześnie zaczną więcej oszczędzać, spadnie konsumpcja, a z nią produkcja i dochody – łączne oszczędności mogą wcale nie wzrosnąć. To błąd złożenia: co dobre dla jednostki, nie zawsze jest dobre dla całości."),
          K("Przecieki i dopływy",
            "Oszczędności, podatki i import to przecieki z obiegu dochodu; inwestycje, wydatki rządowe i eksport – dopływy. Jeśli przecieki rosną, a dopływy nie, produkcja spada, aż przecieki zrównają się z dopływami na niższym poziomie dochodu."),
          W("Co dzieje się z dochodem, gdy wszyscy zwiększają oszczędności, a inwestycje się nie zmieniają (model Keynesa)?",
            "Dochód spada", "Dochód rośnie", "Dochód się nie zmienia",
            why="Spada konsumpcja, a więc i popyt oraz produkcja."),
          K("Minsky: stabilność rodzi niestabilność",
            "Hyman Minsky opisał trzy rodzaje finansowania: zabezpieczone (dochody pokrywają odsetki i kapitał), spekulacyjne (pokrywają tylko odsetki) i Ponziego (nie pokrywają nawet odsetek – potrzebny wzrost cen aktywów). Długi okres spokoju zachęca do coraz bardziej ryzykownego zadłużania, aż przychodzi „moment Minsky’ego” – nagły krach."),
          K("Akcelerator finansowy",
            "Gdy spadają ceny aktywów (np. nieruchomości), firmy i gospodarstwa mają mniejsze zabezpieczenia, banki ograniczają kredyt, inwestycje i konsumpcja spadają, ceny aktywów spadają dalej. Rynek finansowy wzmacnia wahania koniunktury."),
          PF("Paradoks zapobiegliwości oznacza, że oszczędzanie jest zawsze szkodliwe.", False,
             why="W długim okresie oszczędności finansują inwestycje i wzrost; paradoks dotyczy recesji przy niewykorzystanych zasobach."),
      ],
      mech=[
          LN("Ułóż przebieg paradoksu zapobiegliwości.",
             ["W recesji ludzie obawiają się utraty pracy", "Wszyscy jednocześnie ograniczają wydatki", "Firmy sprzedają mniej i zwalniają", "Dochody spadają", "Łączne oszczędności nie rosną mimo większej skłonności do oszczędzania"],
             why="Decyzja racjonalna dla jednostki prowadzi do gorszego wyniku dla całości."),
          LN("Ułóż cykl Minsky’ego.",
             ["Długi okres stabilnego wzrostu", "Rośnie optymizm i dźwignia finansowa", "Przybywa finansowania spekulacyjnego i Ponziego", "Wzrost cen aktywów zatrzymuje się", "Przymusowa sprzedaż aktywów i krach"],
             why="Stabilność zachęca do ryzyka, które ją niszczy."),
          KT("Finansowanie według Minsky’ego",
             {"Zabezpieczone": ["Dochody pokrywają raty kapitałowe i odsetki"],
              "Spekulacyjne": ["Dochody pokrywają tylko odsetki, kapitał trzeba rolować"],
              "Ponziego": ["Dochody nie pokrywają nawet odsetek – liczy się wzrost wartości aktywa", "Kredyt na mieszkanie pod wynajem, którego czynsz nie pokrywa odsetek"]},
             why="Im wyżej w tej hierarchii, tym większa wrażliwość na spadek cen aktywów."),
          W("Spadek cen mieszkań o 20% zmniejsza wartość zabezpieczeń kredytów. Jak działa akcelerator finansowy?",
            "Banki zaostrzają kredyt, inwestycje i konsumpcja spadają, co obniża ceny dalej", "Banki zwiększają kredyt", "Nie ma wpływu na gospodarkę",
            why="Sprzężenie zwrotne między cenami aktywów a kredytem wzmacnia spadek."),
          PF("Paradoks zapobiegliwości jest przykładem błędu złożenia.", True,
             why="To, co prawdziwe dla części, nie musi być prawdziwe dla całości."),
          M("Co może osłabić paradoks zapobiegliwości w recesji?",
            ["Wzrost wydatków rządowych", "Wzrost eksportu", "Jednoczesne cięcia płac i wydatków przez wszystkich", "Obniżki stóp procentowych zwiększające inwestycje"],
            [0, 1, 3],
            why="Cięcia wydatków pogłębiłyby spadek popytu."),
      ],
      calc=[
          LB("C = 200 + 0,8Y, I = 100. Ile wynosi Y równowagi?",
             1500, "(200+100)/(1-0.8)", ["Y = 300 / 0,2 = 1500"], unit=""),
          LB("Ile wynoszą oszczędności w tej równowadze (S = Y − C)?",
             100, "1500-(200+0.8*1500)", ["C = 200 + 1200 = 1400", "S = 100 = I"], unit=""),
          LB("Ludzie zaczynają więcej oszczędzać: C = 150 + 0,8Y (I = 100). Ile wynosi nowe Y?",
             1250, "(150+100)/(1-0.8)", ["Y = 250 / 0,2 = 1250"], unit=""),
          LB("Ile wynoszą oszczędności po zmianie (S = Y − C przy Y = 1250)?",
             100, "1250-(150+0.8*1250)", ["C = 150 + 1000 = 1150", "S = 100 – bez zmian, a dochód spadł o 250"], unit=""),
          LB("Kredyt 600 tys. zł na 6%, czynsz z wynajmu 30 tys. zł rocznie. O ile tys. zł roczne odsetki przewyższają czynsz?",
             6, "600*0.06-30", ["Odsetki: 36 tys. zł", "36 − 30 = 6 tys. zł – finansowanie typu Ponziego"], unit="tys. zł"),
          LB("Mieszkanie warte 500 tys. zł, kredyt 450 tys. zł. Ceny spadają o 15%. Ile wynosi kapitał własny właściciela po spadku (tys. zł, ze znakiem)?",
             -25, "500*0.85-450", ["Wartość: 425 tys. zł", "425 − 450 = −25 tys. zł – kredyt „pod wodą”"], unit="tys. zł"),
      ],
      case=[
          PR("W czasie pandemii gospodarstwa domowe w wielu krajach gwałtownie zwiększyły oszczędności: część z obawy przed utratą pracy, część dlatego, że nie mogły wydawać (zamknięte usługi). Rządy jednocześnie zwiększyły wydatki i transfery.",
             W("Które działanie rządów przeciwdziałało paradoksowi zapobiegliwości?",
               "Wzrost wydatków i transferów rządowych", "Podwyżki podatków", "Cięcia wydatków publicznych",
               why="Wydatki rządowe zastąpiły część brakującego popytu prywatnego."),
             PF("Część wzrostu oszczędności była wymuszona brakiem możliwości wydawania, a nie tylko ostrożnością.", True,
                why="Zamknięcie usług ograniczyło możliwość konsumpcji."),
             W("Co mogło się stać po otwarciu gospodarki?",
               "Wzrost konsumpcji z nagromadzonych oszczędności i presja na ceny", "Dalszy spadek konsumpcji", "Brak zmian",
               why="Odroczony popyt wrócił, gdy usługi się otworzyły."),
          ),
          PR("Przed kryzysem 2008 r. w USA wielu kredytobiorców zaciągało kredyty hipoteczne, których raty mogli spłacać tylko przy stałym wzroście cen domów (refinansowanie). Gdy ceny zaczęły spadać, spłaty stały się niemożliwe, a banki gwałtownie ograniczyły kredyt.",
             W("Jaki typ finansowania według Minsky’ego dominował?",
               "Ponziego – spłata zależała od wzrostu cen aktywów", "Zabezpieczony", "Bezgotówkowy",
               why="Dochody nie wystarczały na obsługę długu bez wzrostu cen domów."),
             W("Jak nazywa się mechanizm, w którym spadek cen domów ograniczył kredyt i pogłębił recesję?",
               "Akcelerator finansowy", "Mnożnik Haavelmo", "Efekt Veblena",
               why="Spadek wartości zabezpieczeń zmniejszył dostęp do kredytu."),
             PF("Długi okres stabilności przed kryzysem sprzyjał podejmowaniu coraz większego ryzyka.", True,
                why="To sedno hipotezy niestabilności finansowej."),
          ),
      ]),
]
