# -*- coding: utf-8 -*-
# Zrozumienie – Mikroekonomia / Popyt, podaż i równowaga
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"

LESSONS = [
    L(1, "Popyt: ruch po krzywej czy przesunięcie?",
      "Odróżniać zmianę wielkości popytu (skutek zmiany ceny) od zmiany popytu (skutek innych czynników) i przewidywać kierunek przesunięcia krzywej.",
      ["Popyt", "Prawo popytu", "Wielkość popytu a popyt", "Popyt indywidualny i rynkowy"],
      [S("OpenStax, Principles of Economics 3e, 3.1 Demand, Supply, and Equilibrium", OS3 + "3-1-demand-supply-and-equilibrium-in-markets-for-goods-and-services", D),
       S("OpenStax, Principles of Economics 3e, 3.2 Shifts in Demand and Supply", OS3 + "3-2-shifts-in-demand-and-supply-for-goods-and-services", D)],
      explain=[
          K("Krzywa popytu to cały „plan zakupów”",
            "Krzywa popytu pokazuje, ile dobra kupujący chcą i mogą kupić przy KAŻDEJ możliwej cenie, gdy wszystko inne (dochody, ceny innych dóbr, gusty) się nie zmienia. Zwykle opada: im wyższa cena, tym mniejsza kupowana ilość – to prawo popytu.",
            g=G("sd")),
          K("Zmiana ceny = ruch po krzywej",
            "Gdy zmienia się cena samego dobra, nie rysujemy nowej krzywej – przesuwamy się po istniejącej do innego punktu. Mówimy wtedy o zmianie WIELKOŚCI popytu (ilości nabywanej), a nie o zmianie popytu.",
            p="Cena biletu do kina spada z 30 do 25 zł, więc tego samego dnia kupujemy więcej biletów – to ruch w dół po tej samej krzywej."),
          K("Inne czynniki = przesunięcie krzywej",
            "Popyt zmienia się (cała krzywa przesuwa się), gdy zmienia się czynnik pozacenowy: dochód, ceny substytutów i dóbr komplementarnych, gusty i moda, oczekiwania co do przyszłych cen, liczba nabywców. W prawo = większy popyt przy każdej cenie, w lewo = mniejszy.",
            g=G("sd", D=1)),
          W("Rośnie cena masła. Co dzieje się na wykresie popytu na masło?",
            "Ruch w górę po tej samej krzywej popytu – spada wielkość popytu",
            "Krzywa popytu na masło przesuwa się w lewo",
            "Krzywa popytu na masło przesuwa się w prawo",
            why="Cena samego dobra nie przesuwa jego krzywej popytu – zmienia tylko punkt na krzywej (wielkość popytu)."),
          K("Substytuty, komplementy i dochód",
            "Wzrost ceny substytutu (np. margaryny) zwiększa popyt na masło – krzywa w prawo. Wzrost ceny dobra komplementarnego (np. pieczywa) zmniejsza popyt – krzywa w lewo. Wzrost dochodu zwiększa popyt na dobra normalne, a zmniejsza na dobra niższego rzędu."),
          PF("Spadek dochodów konsumentów przesuwa w lewo popyt na każde dobro.", False,
             why="Tylko na dobra normalne. Popyt na dobra niższego rzędu (np. najtańsze zamienniki) przy spadku dochodu rośnie."),
          K("Popyt rynkowy = suma popytów indywidualnych",
            "Popyt rynkowy powstaje przez zsumowanie w poziomie ilości, jakie przy danej cenie kupują wszyscy nabywcy. Dlatego wzrost liczby nabywców (np. więcej studentów w mieście) przesuwa w prawo rynkowy popyt na wynajem mieszkań."),
          W("Która zmiana jest zmianą WIELKOŚCI popytu, a nie popytu?",
            "Mniej osób jeździ taksówkami, bo podrożały przejazdy taksówką",
            "Mniej osób jeździ taksówkami, bo potaniała komunikacja miejska",
            "Mniej osób jeździ taksówkami, bo spadły ich dochody",
            "Mniej osób jeździ taksówkami, bo pojawiły się nowe aplikacje przewozowe",
            why="Tylko zmiana ceny samej usługi powoduje ruch po krzywej; pozostałe odpowiedzi to czynniki pozacenowe, które przesuwają krzywą."),
      ],
      mech=[
          WY("Bilety lotnicze tanieją. Co dzieje się z popytem na noclegi w hotelach w miejscowościach turystycznych?",
             G("sd", names={"D": "Popyt na noclegi", "S": "Podaż noclegów"}, D=1),
             "Popyt rośnie – krzywa D przesuwa się w prawo, rośnie cena i liczba noclegów",
             "Popyt maleje – krzywa D przesuwa się w lewo",
             "Rośnie podaż noclegów – krzywa S przesuwa się w prawo",
             "Nic się nie zmienia, bo cena noclegów jest stała",
             why="Lot i nocleg są dobrami komplementarnymi: tańszy dojazd zwiększa popyt na noclegi przy każdej cenie."),
          W("Konsumenci spodziewają się, że za miesiąc ceny telewizorów wyraźnie spadną (wyprzedaże). Co dzieje się dziś z popytem na telewizory?",
            "Maleje – część osób odkłada zakup",
            "Rośnie – wszyscy kupują zanim zmieni się cena",
            "Nie zmienia się, bo liczą się tylko obecne ceny",
            why="Oczekiwanie niższej ceny w przyszłości zmniejsza dzisiejszy popyt (krzywa w lewo); oczekiwanie podwyżki – zwiększa."),
          KT("Co przesuwa krzywą popytu na rowery W PRAWO, a co W LEWO?",
             {"W prawo (wzrost popytu)": ["Budowa nowych ścieżek rowerowych", "Wzrost cen paliw i biletów komunikacji", "Moda na zdrowy tryb życia", "Wzrost dochodów (rower – dobro normalne)"],
              "W lewo (spadek popytu)": ["Spadek cen hulajnóg elektrycznych na minuty", "Wysoki podatek od kasków i oświetlenia", "Ludzie wyjeżdżają z miasta – mniej mieszkańców"]},
             why="Substytut tańszy → popyt maleje; komplement droższy → popyt maleje; dochód, gusty, liczba nabywców i droższe substytuty działają w prawo."),
          LN("Ułóż łańcuch zdarzeń: rośnie cena kawy, a co z popytem na mleko do kawy?",
             ["Cena kawy rośnie", "Spada ilość kupowanej kawy (ruch po krzywej popytu na kawę)",
              "Ludzie potrzebują mniej mleka do kawy", "Krzywa popytu na mleko przesuwa się w lewo"],
             why="Kawa i mleko to dobra komplementarne: wzrost ceny jednego zmniejsza popyt na drugie."),
          PF("Jeśli cena dobra wzrosła, a kupowana ilość też wzrosła, to na pewno złamano prawo popytu.", False,
             why="Najczęściej oznacza to, że jednocześnie wzrósł popyt (krzywa przesunęła się w prawo), co podniosło i cenę, i ilość. Prawo popytu dotyczy sytuacji „ceteris paribus”."),
          W("Rośnie dochód studentów. Popyt na najtańszy makaron w hipermarkecie spada. Co to mówi o tym makaronie?",
            "Dla tej grupy jest dobrem niższego rzędu",
            "Jest dobrem luksusowym",
            "Jest dobrem komplementarnym do dochodu",
            "Jest dobrem Giffena",
            why="Dobro niższego rzędu to takie, na które popyt maleje, gdy dochód rośnie (ujemna elastyczność dochodowa)."),
          M("Które zdarzenia przesuną w prawo popyt na samochody elektryczne?",
            ["Dopłaty państwa do zakupu auta elektrycznego dla nabywców", "Spadek cen energii elektrycznej",
             "Spadek ceny samochodów elektrycznych", "Wzrost cen benzyny i oleju napędowego"],
            [0, 1, 3],
            why="Dopłata dla kupujących, tańszy komplement (prąd) i droższy substytut (paliwo) zwiększają popyt. Spadek ceny samego auta to ruch po krzywej."),
      ],
      calc=[
          LB("Popyt na bilety opisuje Qd = 1200 − 20P (P w zł). Ile biletów zostanie kupionych przy cenie 35 zł?",
             500, "1200-20*35", ["Podstawiamy P = 35: Qd = 1200 − 20·35", "= 1200 − 700 = 500 biletów"], unit="szt."),
          LB("Przy jakiej cenie popyt z równania Qd = 1200 − 20P spadnie do zera (cena „dławiąca”)?",
             60, "1200/20", ["Qd = 0 ⇒ 1200 − 20P = 0", "P = 1200 / 20 = 60 zł"], unit="zł"),
          LB("Na rynku jest 3 nabywców: Q₁ = 10 − P, Q₂ = 12 − 2P, Q₃ = 8 − P. Ile wynosi popyt rynkowy przy P = 3?",
             18, "(10-3)+(12-2*3)+(8-3)", ["Sumujemy ilości przy tej samej cenie (sumowanie poziome)", "Q₁ = 10 − 3 = 7, Q₂ = 12 − 6 = 6, Q₃ = 8 − 3 = 5", "Q = 7 + 6 + 5 = 18"], unit="szt."),
          LB("Po podwyżce płac popyt na obiady w barze zmienił się z Qd = 400 − 10P na Qd = 460 − 10P. O ile wzrosła kupowana ilość przy niezmienionej cenie 20 zł?",
             60, "(460-10*20)-(400-10*20)", ["Przed: 400 − 200 = 200", "Po: 460 − 200 = 260", "Różnica: 60 obiadów – to przesunięcie krzywej w prawo o 60"], unit="szt."),
          LB("Cena biletu wzrosła z 20 zł do 25 zł, a liczba sprzedanych biletów spadła z 900 do 800. O ile procent spadła wielkość popytu (licząc od wartości początkowej)?",
             11.11, "(900-800)/900*100", ["Zmiana: 900 − 800 = 100", "100 / 900 · 100% ≈ 11,11%"], unit="%", tol=0.05),
          W("Popyt opisuje Qd = 50 − 2P. Jak zmieni się równanie, jeśli przy każdej cenie konsumenci chcą kupić o 10 sztuk więcej?",
            "Qd = 60 − 2P", "Qd = 50 − 12P", "Qd = 40 − 2P", "Qd = 50 − 2P + 10P",
            why="Przesunięcie w prawo o stałą ilość zwiększa wyraz wolny o 10, nachylenie się nie zmienia."),
      ],
      case=[
          PR("Mieszkańcy dużego miasta: od września na uczelnie przyjeżdża 20 tys. nowych studentów. Jednocześnie miasto obniża ceny biletów miesięcznych o 30%, a wielu studentów rezygnuje z własnego samochodu.",
             W("Co dzieje się z popytem na wynajem pokoi w pobliżu uczelni?",
               "Rośnie – przybywa nabywców (krzywa w prawo)", "Maleje – tańsza komunikacja zmniejsza popyt na każdy pokój", "Nie zmienia się, bo zmienia się tylko cena",
               why="Wzrost liczby nabywców to klasyczny czynnik przesuwający popyt rynkowy w prawo."),
             W("Co dzieje się z popytem na miejsca parkingowe abonamentowe przy uczelni?",
               "Maleje – tańsza komunikacja miejska jest substytutem jazdy autem",
               "Rośnie – więcej studentów to więcej aut",
               "Rośnie, bo tanieją bilety",
               why="Bilet i jazda samochodem to substytuty; tańszy substytut zmniejsza popyt na parking."),
             PF("Większa liczba sprzedanych biletów miesięcznych po obniżce ceny to przesunięcie krzywej popytu na bilety w prawo.", False,
                why="Obniżka ceny samego biletu to ruch po krzywej (wzrost wielkości popytu). Przesunięcie dałby np. napływ nowych studentów."),
          ),
          PR("Sklep ze sprzętem sportowym: zima była bezśnieżna, a prognozy mówią o kolejnym ciepłym sezonie. Producent nart nie zmienił cen, ale sprzedaż spadła o 40%. Jednocześnie wzrosła sprzedaż rowerów i hulajnóg.",
             W("Jak opisać spadek sprzedaży nart?",
               "Przesunięcie popytu na narty w lewo (zmiana gustów i oczekiwań)",
               "Ruch po krzywej popytu na narty",
               "Spadek podaży nart",
               why="Cena się nie zmieniła, więc zmienił się czynnik pozacenowy – popyt przesunął się w lewo."),
             W("Jak najlepiej wyjaśnić wzrost sprzedaży rowerów?",
               "Konsumenci przenieśli wydatki na inne formy aktywności – popyt na rowery wzrósł",
               "Rowery stały się dobrem niższego rzędu",
               "Wzrosła cena rowerów",
               why="Przy braku śniegu rower i hulajnoga stają się atrakcyjniejsze – zmiana preferencji zwiększa popyt."),
             M("Które działania sklepu są sensowną reakcją na mniejszy POPYT na narty?",
               ["Obniżka cen wyprzedażowa, żeby sprzedać zapasy", "Mniejsze zamówienia nart na kolejny sezon",
                "Podniesienie cen nart, bo spadła sprzedaż", "Przesunięcie miejsca na półkach dla rowerów"],
               [0, 1, 3],
               why="Podniesienie ceny przy spadku popytu jeszcze zmniejszy sprzedaż; pozostałe działania dostosowują się do nowej krzywej."),
          ),
      ]),

    L(2, "Podaż: co ją przesuwa i dlaczego",
      "Rozumieć, dlaczego krzywa podaży rośnie, odróżniać zmianę wielkości podaży od zmiany podaży i przewidywać skutki zmian kosztów, technologii, podatków i dotacji.",
      ["Podaż", "Prawo podaży", "Subsydium do produkcji – skutki rynkowe"],
      [S("OpenStax, Principles of Economics 3e, 3.1 Demand, Supply, and Equilibrium", OS3 + "3-1-demand-supply-and-equilibrium-in-markets-for-goods-and-services", D),
       S("OpenStax, Principles of Economics 3e, 3.2 Shifts in Demand and Supply", OS3 + "3-2-shifts-in-demand-and-supply-for-goods-and-services", D)],
      explain=[
          K("Dlaczego krzywa podaży rośnie?",
            "Wyższa cena sprawia, że opłaca się produkować więcej: pokrywa rosnące koszty dodatkowych jednostek (np. nadgodziny, droższe surowce, mniej wydajne maszyny) i zachęca nowe firmy do wejścia na rynek. Dlatego przy wyższej cenie wielkość podaży jest większa – to prawo podaży.",
            g=G("sd")),
          K("Ruch po krzywej a przesunięcie",
            "Zmiana ceny dobra = ruch po krzywej podaży (zmiana wielkości podaży). Zmiana czynnika pozacenowego = przesunięcie całej krzywej: w prawo – przy każdej cenie oferowana jest większa ilość, w lewo – mniejsza."),
          K("Co przesuwa podaż?",
            "Koszty czynników produkcji (płace, surowce, energia), technologia, ceny innych dóbr, które firma mogłaby produkować z tych samych zasobów, warunki naturalne (pogoda, choroby zwierząt), oczekiwania producentów, liczba firm na rynku oraz podatki i dotacje. Droższe czynniki, susza czy nowy podatek przesuwają podaż w lewo; tańsza energia, lepsza technologia czy dotacja – w prawo.",
            g=G("sd", S=-1)),
          W("Rolnik może siać pszenicę albo rzepak. Rośnie cena rzepaku. Co dzieje się z podażą pszenicy?",
            "Maleje – część pól przechodzi pod rzepak (krzywa podaży pszenicy w lewo)",
            "Rośnie – rolnicy mają więcej pieniędzy",
            "Nie zmienia się – zmieniła się cena innego dobra",
            why="Pszenica i rzepak konkurują o tę samą ziemię: droższy rzepak zwiększa koszt alternatywny siania pszenicy."),
          K("Podatek i dotacja w modelu",
            "Podatek nałożony na producenta działa jak dodatkowy koszt: aby oferować tę samą ilość, firma potrzebuje ceny wyższej o kwotę podatku – krzywa podaży przesuwa się w górę (w lewo). Dotacja do każdej jednostki obniża koszt – podaż przesuwa się w dół (w prawo)."),
          PF("Wzrost ceny jabłek przesuwa krzywą podaży jabłek w prawo.", False,
             why="Zmiana ceny samego dobra powoduje ruch po krzywej (większą wielkość podaży), a nie przesunięcie krzywej."),
      ],
      mech=[
          WY("Wiosenne przymrozki niszczą dużą część kwiatów w sadach. Co stanie się na rynku owoców jesienią?",
             G("sd", names={"D": "popyt na owoce", "S": "podaż owoców"}, S=-1),
             "Podaż maleje – cena rośnie, kupowana ilość maleje",
             "Popyt maleje – cena i ilość spadają",
             "Podaż rośnie – cena spada",
             "Nic się nie zmienia, bo popyt jest stały",
             why="Warunki naturalne zmniejszają ilość oferowaną przy każdej cenie: krzywa S w lewo, nowa równowaga przy wyższej cenie i mniejszej ilości."),
          WY("Nowa technologia skraca czas produkcji paneli fotowoltaicznych o połowę. Jak zmienia się rynek paneli?",
             G("sd", names={"D": "popyt na panele", "S": "podaż paneli"}, S=1),
             "Podaż rośnie – cena spada, sprzedaż rośnie",
             "Popyt rośnie – cena rośnie",
             "Podaż maleje – cena rośnie",
             why="Lepsza technologia obniża koszty, więc przy każdej cenie opłaca się oferować więcej: S w prawo."),
          KT("Co przesuwa podaż pieczywa W PRAWO, a co W LEWO?",
             {"W prawo (wzrost podaży)": ["Spadek cen mąki", "Nowe, energooszczędne piece", "Otwarcie kilku nowych piekarni", "Dotacja do każdego bochenka"],
              "W lewo (spadek podaży)": ["Wzrost cen gazu i prądu", "Podwyżka płac piekarzy", "Nowy podatek od każdego bochenka"]},
             why="Niższe koszty, lepsza technologia, więcej firm i dotacje zwiększają podaż; wyższe koszty i podatki ją zmniejszają."),
          LN("Ułóż łańcuch: rosną płace w budownictwie.",
             ["Rosną płace pracowników budowlanych", "Rośnie koszt budowy każdego mieszkania",
              "Przy danej cenie deweloperom opłaca się budować mniej", "Podaż nowych mieszkań przesuwa się w lewo",
              "Cena mieszkań rośnie, liczba sprzedanych spada"],
             why="Koszt czynnika produkcji wpływa na opłacalność i przesuwa podaż; wynik rynkowy to wyższa cena i mniejsza ilość."),
          W("Producenci spodziewają się, że za kwartał cena ich wyrobu wyraźnie wzrośnie. Co mogą zrobić dziś?",
            "Ograniczyć dzisiejszą sprzedaż i magazynować – podaż dziś maleje",
            "Zwiększyć dzisiejszą sprzedaż – podaż dziś rośnie",
            "Nic – oczekiwania wpływają tylko na popyt",
            why="Oczekiwanie wyższej ceny w przyszłości skłania do przesunięcia sprzedaży w czasie, więc bieżąca podaż maleje."),
          PF("Dotacja do każdej wyprodukowanej sztuki przesuwa krzywą podaży w prawo (w dół).", True,
             why="Dotacja obniża koszt jednostki, więc przy każdej cenie opłaca się produkować więcej – jak spadek kosztów."),
          M("Które zdarzenia zmniejszą podaż mleka (krzywa w lewo)?",
            ["Choroba zwierząt w dużej części stad", "Wzrost cen pasz", "Spadek ceny mleka w skupie", "Wprowadzenie nowej opłaty od każdego litra mleka"],
            [0, 1, 3],
            why="Choroby, droższe pasze i nowa opłata od jednostki przesuwają podaż w lewo. Spadek ceny skupu to ruch po krzywej (mniejsza wielkość podaży)."),
      ],
      calc=[
          LB("Podaż opisuje Qs = −40 + 8P. Ile sztuk zostanie zaoferowanych przy cenie 15 zł?",
             80, "-40+8*15", ["Qs = −40 + 8·15 = −40 + 120 = 80"], unit="szt."),
          LB("Poniżej jakiej ceny podaż z równania Qs = −40 + 8P spada do zera?",
             5, "40/8", ["Qs = 0 ⇒ 8P = 40", "P = 5 zł – poniżej tej ceny nikt nie oferuje dobra"], unit="zł"),
          LB("Na rynku są 3 identyczne firmy, każda z podażą q = 2P − 4. Ile wynosi podaż rynkowa przy cenie 10 zł?",
             48, "3*(2*10-4)", ["Jedna firma: q = 2·10 − 4 = 16", "Rynek: 3 · 16 = 48"], unit="szt."),
          LB("Na producenta nałożono podatek 2 zł od sztuki. Jego podaż przed podatkiem: Qs = −40 + 8P. Ile zaoferuje przy cenie rynkowej 15 zł po wprowadzeniu podatku?",
             64, "-40+8*(15-2)", ["Producent zatrzymuje cenę pomniejszoną o podatek: 15 − 2 = 13 zł", "Qs = −40 + 8·13 = 64"], unit="szt."),
          LB("Po zmianie technologii podaż zmieniła się z Qs = −40 + 8P na Qs = −20 + 8P. O ile wzrosła oferowana ilość przy cenie 10 zł?",
             20, "(-20+8*10)-(-40+8*10)", ["Przed: −40 + 80 = 40", "Po: −20 + 80 = 60", "Wzrost o 20 sztuk – przesunięcie krzywej w prawo"], unit="szt."),
          LB("Cena wzrosła z 10 zł do 12 zł, a wielkość podaży z 40 do 56 sztuk. O ile procent wzrosła wielkość podaży (od wartości początkowej)?",
             40, "(56-40)/40*100", ["Zmiana: 56 − 40 = 16", "16 / 40 · 100% = 40%"], unit="%"),
      ],
      case=[
          PR("Rynek wieprzowiny: w regionie wykryto chorobę zwierząt i część stad trzeba było zlikwidować. Jednocześnie potaniały pasze, a import z innych krajów został czasowo ograniczony.",
             W("Który czynnik ma najsilniejszy krótkookresowy wpływ na podaż wieprzowiny w regionie?",
               "Likwidacja stad – podaż wyraźnie maleje",
               "Tańsze pasze – podaż rośnie",
               "Ograniczenie importu – rośnie popyt",
               why="Utrata części stad natychmiast zmniejsza możliwą produkcję; tańsze pasze działają wolniej i nie odbudują stad od razu."),
             PF("Ograniczenie importu wpływa na podaż na rynku krajowym (krzywa w lewo), a nie na popyt.", True,
                why="Import jest częścią oferty na rynku krajowym; jego ograniczenie zmniejsza łączną podaż."),
             W("Jakiego wyniku rynkowego najpewniej należy się spodziewać?",
               "Wzrost ceny wieprzowiny i spadek sprzedaży",
               "Spadek ceny i wzrost sprzedaży",
               "Brak zmian, bo efekty się znoszą",
               why="Dwa silne czynniki przesuwają podaż w lewo, a tańsze pasze tylko częściowo to łagodzą – cena rośnie, ilość spada."),
          ),
          PR("Wytwórnia rowerów: rząd wprowadza dotację 200 zł do każdego roweru elektrycznego wyprodukowanego w kraju. Jednocześnie rosną ceny baterii litowo-jonowych.",
             W("W którą stronę działa dotacja na krzywą podaży rowerów elektrycznych?",
               "W prawo (w dół) – obniża koszt jednostkowy", "W lewo – zwiększa koszty", "Nie działa na podaż, tylko na popyt",
               why="Dotacja do każdej sztuki działa jak spadek kosztu jednostkowego."),
             W("Co można powiedzieć o łącznym skutku dla podaży?",
               "Jest niejednoznaczny – zależy, który efekt jest silniejszy",
               "Podaż na pewno rośnie",
               "Podaż na pewno maleje",
               why="Dotacja przesuwa podaż w prawo, droższe baterie – w lewo; bez danych nie wiadomo, który efekt przeważa."),
             LB("Koszt wyprodukowania roweru wzrósł przez baterie o 150 zł, a dotacja wynosi 200 zł. O ile netto zmienił się koszt jednostkowy dla producenta (podaj ze znakiem)?",
                -50, "150-200", ["+150 zł (baterie) − 200 zł (dotacja) = −50 zł", "Koszt netto spadł o 50 zł – w tym przykładzie podaż przesunie się w prawo"], unit="zł"),
          ),
      ]),

    L(3, "Równowaga rynkowa i jej zmiany",
      "Wyznaczać równowagę, rozumieć mechanizm likwidacji nadwyżki i niedoboru oraz analizować jednoczesne zmiany popytu i podaży metodą czterech kroków.",
      ["Równowaga rynkowa", "Nadwyżka (rynkowa)", "Niedobór (rynkowy)", "Ceny jako sygnały (mechanizm cenowy)"],
      [S("OpenStax, Principles of Economics 3e, 3.1 Demand, Supply, and Equilibrium", OS3 + "3-1-demand-supply-and-equilibrium-in-markets-for-goods-and-services", D),
       S("OpenStax, Principles of Economics 3e, 3.3 Changes in Equilibrium Price and Quantity: The Four-Step Process", OS3 + "3-3-changes-in-equilibrium-price-and-quantity-the-four-step-process", D)],
      explain=[
          K("Równowaga = plany kupujących i sprzedających się zgadzają",
            "W punkcie przecięcia krzywych popytu i podaży ilość, jaką chcą kupić nabywcy, jest równa ilości, jaką chcą sprzedać producenci. Nikt nie ma powodu zmieniać ceny – to cena i ilość równowagi (E).",
            g=G("sd")),
          K("Nadwyżka spycha cenę w dół",
            "Gdy cena jest wyższa od równowagi, producenci oferują więcej, niż klienci chcą kupić – powstaje nadwyżka (zapasy w magazynach). Sprzedawcy obniżają ceny, wielkość popytu rośnie, a podaży maleje – aż do równowagi."),
          K("Niedobór pcha cenę w górę",
            "Gdy cena jest niższa od równowagi, chętnych jest więcej niż towaru – niedobór (kolejki, listy oczekujących). Kupujący przebijają oferty, sprzedawcy podnoszą ceny, aż niedobór zniknie. Ceny działają jak sygnał i bodziec dla obu stron."),
          W("Cena biletów na koncert jest ustalona poniżej poziomu równowagi. Czego się spodziewać?",
            "Niedoboru – biletów zabraknie, pojawi się wtórny rynek z wyższymi cenami",
            "Nadwyżki – część biletów się nie sprzeda",
            "Równowagi – cena nie ma znaczenia",
            why="Przy zbyt niskiej cenie wielkość popytu przewyższa wielkość podaży."),
          K("Cztery kroki analizy zmiany",
            "1) Narysuj stan wyjściowy. 2) Ustal, czy zdarzenie przesuwa popyt, czy podaż (czy obie). 3) Ustal kierunek przesunięcia. 4) Porównaj nową równowagę ze starą: co stało się z ceną i ilością.",
            g=G("sd", D=1)),
          K("Gdy przesuwają się obie krzywe",
            "Jeśli jednocześnie rośnie popyt i podaż, ilość na pewno rośnie, ale zmiana ceny zależy od tego, które przesunięcie jest większe. Jeśli popyt rośnie, a podaż maleje – cena na pewno rośnie, a ilość jest nieokreślona. Zawsze jedna zmienna jest jednoznaczna, druga zależy od skali przesunięć."),
          PF("Jeśli popyt i podaż jednocześnie maleją, to cena na pewno spada.", False,
             why="Na pewno spada ilość; cena może wzrosnąć, spaść lub się nie zmienić – zależy od siły obu przesunięć."),
      ],
      mech=[
          WY("Lekarze ogłaszają, że jedzenie orzechów bardzo poprawia zdrowie. Co dzieje się na rynku orzechów?",
             G("sd", D=1), "Cena i ilość równowagi rosną", "Cena rośnie, ilość spada", "Cena spada, ilość rośnie", "Cena i ilość spadają",
             why="Zmiana preferencji przesuwa popyt w prawo; nowa równowaga leży wyżej i bardziej na prawo."),
          WY("Do produkcji cukru potrzeba dużo energii, a jej ceny gwałtownie rosną. Co dzieje się na rynku cukru?",
             G("sd", S=-1), "Cena rośnie, ilość spada", "Cena i ilość rosną", "Cena spada, ilość rośnie", "Cena i ilość spadają",
             why="Wyższy koszt przesuwa podaż w lewo: cena równowagi rośnie, ilość maleje."),
          LN("Ułóż, jak rynek likwiduje niedobór mieszkań na wynajem (cena poniżej równowagi).",
             ["Chętnych na mieszkania jest więcej niż ofert", "Najemcy konkurują i akceptują wyższe stawki",
              "Właściciele podnoszą czynsze", "Wielkość popytu maleje, a podaży rośnie", "Niedobór znika w nowej równowadze"],
             why="Wzrost ceny jednocześnie zniechęca część kupujących i zachęca sprzedających – stąd likwidacja niedoboru."),
          KT("Popyt i podaż zmieniają się jednocześnie. Co jest JEDNOZNACZNE?",
             {"Cena jednoznaczna": ["Popyt rośnie, podaż maleje", "Popyt maleje, podaż rośnie"],
              "Ilość jednoznaczna": ["Popyt rośnie, podaż rośnie", "Popyt maleje, podaż maleje"]},
             why="Przesunięcia w przeciwne strony jednoznacznie ustalają kierunek ceny; w tę samą stronę – kierunek ilości."),
          W("Zimą rośnie popyt na narty, a jednocześnie producenci wprowadzają tańszą technologię. Co wiemy na pewno?",
            "Ilość sprzedanych nart rośnie", "Cena nart rośnie", "Cena nart spada", "Ilość sprzedanych nart spada",
            why="Popyt i podaż rosną: ilość na pewno rośnie, cena zależy od tego, które przesunięcie jest większe."),
          PF("Na rynku z nadwyżką sprzedawcy mają bodziec, by obniżać ceny.", True,
             why="Niesprzedane zapasy to koszt; obniżka ceny zwiększa sprzedaż i zmniejsza produkcję, aż do równowagi."),
          M("Ceny truskawek w czerwcu są dużo niższe niż w marcu. Które wyjaśnienia są zgodne z modelem?",
            ["W czerwcu podaż krajowa jest dużo większa (sezon zbiorów)", "W marcu truskawki trzeba sprowadzać lub uprawiać w szklarniach, co jest drogie",
             "W czerwcu popyt na truskawki zawsze spada do zera", "W marcu podaż jest mniejsza przy każdej cenie"],
            [0, 1, 3],
            why="Sezonowa zmiana podaży (koszty i warunki uprawy) tłumaczy różnicę cen; popyt w czerwcu nie znika."),
      ],
      calc=[
          LB("Popyt: Qd = 120 − 4P, podaż: Qs = −30 + 6P. Oblicz cenę równowagi.",
             15, "150/10", ["Qd = Qs ⇒ 120 − 4P = −30 + 6P", "150 = 10P ⇒ P* = 15 zł"], unit="zł"),
          LB("Dla tych samych funkcji (Qd = 120 − 4P, Qs = −30 + 6P) oblicz ilość równowagi.",
             60, "120-4*15", ["P* = 15", "Q* = 120 − 4·15 = 60 (sprawdzenie: −30 + 90 = 60)"], unit="szt."),
          LB("Przy cenie 10 zł (Qd = 120 − 4P, Qs = −30 + 6P) jaki jest niedobór?",
             50, "(120-4*10)-(-30+6*10)", ["Qd = 120 − 40 = 80", "Qs = −30 + 60 = 30", "Niedobór = 80 − 30 = 50"], unit="szt."),
          LB("Przy cenie 20 zł (Qd = 120 − 4P, Qs = −30 + 6P) jaka jest nadwyżka?",
             50, "(-30+6*20)-(120-4*20)", ["Qs = −30 + 120 = 90", "Qd = 120 − 80 = 40", "Nadwyżka = 90 − 40 = 50"], unit="szt."),
          LB("Popyt wzrósł do Qd = 150 − 4P (podaż bez zmian: Qs = −30 + 6P). Jaka jest nowa cena równowagi?",
             18, "180/10", ["150 − 4P = −30 + 6P", "180 = 10P ⇒ P = 18 zł"], unit="zł"),
          LB("Ile wynosi nowa ilość równowagi po wzroście popytu do Qd = 150 − 4P?",
             78, "150-4*18", ["Q = 150 − 4·18 = 78 (sprawdzenie: −30 + 108 = 78)", "Wzrost z 60 do 78 – zgodnie z przesunięciem popytu w prawo"], unit="szt."),
      ],
      case=[
          PR("Rynek mieszkań w dużym mieście: rosną dochody, banki obniżają marże kredytów (kredyt jest dobrem komplementarnym do zakupu mieszkania), a jednocześnie gminy szybciej wydają pozwolenia na budowę.",
             W("Jak działają rosnące dochody i tańszy kredyt?",
               "Przesuwają popyt na mieszkania w prawo", "Przesuwają podaż mieszkań w prawo", "Powodują ruch po krzywej popytu",
               why="Dochód i cena dobra komplementarnego (kredytu) to czynniki pozacenowe popytu."),
             W("Jak działa szybsze wydawanie pozwoleń?",
               "Przesuwa podaż mieszkań w prawo", "Przesuwa popyt w lewo", "Nie ma wpływu na rynek",
               why="Niższe koszty i krótszy czas inwestycji zwiększają ilość mieszkań oferowanych przy każdej cenie."),
             W("Co na pewno stanie się w nowej równowadze?",
               "Wzrośnie liczba sprzedanych mieszkań", "Wzrośnie cena mieszkań", "Spadnie cena mieszkań", "Spadnie liczba sprzedanych mieszkań",
               why="Popyt i podaż rosną: ilość rośnie na pewno, a kierunek ceny zależy od skali obu przesunięć."),
          ),
          PR("Kawiarnia przy uczelni ustala cenę kawy na 6 zł. Codziennie przed 9:00 ustawia się długa kolejka, a kawa kończy się przed południem. Właściciel rozważa podwyżkę do 8 zł.",
             W("Co oznacza kolejka i kończąca się kawa?",
               "Cena jest poniżej równowagi – występuje niedobór", "Cena jest powyżej równowagi – nadwyżka", "Rynek jest w równowadze",
               why="Przy zbyt niskiej cenie wielkość popytu przewyższa wielkość podaży."),
             PF("Podwyżka ceny zmniejszy kolejkę, bo część klientów zrezygnuje lub kupi mniej, a właścicielowi bardziej opłaci się przygotować więcej kawy.", True,
                why="To mechanizm likwidacji niedoboru: wyższa cena zmniejsza wielkość popytu i zwiększa wielkość podaży."),
             LB("Przy cenie 6 zł chętnych jest 300 osób, a kawy starcza dla 180. Ile osób odchodzi z niczym?",
                120, "300-180", ["Niedobór = wielkość popytu − wielkość podaży = 300 − 180 = 120"], unit="os."),
          ),
      ]),

    L(4, "Ceny maksymalne i minimalne w praktyce",
      "Rozumieć, kiedy cena urzędowa wiąże, jakie wywołuje skutki (niedobór, nadwyżka, kolejki, szara strefa, koszty dla budżetu) i analizować polskie przykłady: mrożenie cen prądu i płacę minimalną.",
      ["Cena maksymalna", "Cena minimalna", "Niedobór (rynkowy)", "Nadwyżka (rynkowa)"],
      [S("OpenStax, Principles of Economics 3e, 3.4 Price Ceilings and Price Floors", OS3 + "3-4-price-ceilings-and-price-floors", D),
       S("URE – taryfy na sprzedaż energii elektrycznej na 2026 r.", "https://www.ure.gov.pl/pl/urzad/informacje-ogolne/aktualnosci/13002,Prezes-Urzedu-Regulacji-Energetyki-zatwierdzil-taryfy-na-sprzedaz-i-dystrybucje-.html", D),
       S("Sejm RP, druk nr 841 – uzasadnienie projektu (mechanizm ceny maksymalnej i Fundusz Wypłaty Różnicy Ceny)", "https://api.sejm.gov.pl/sejm/term10/prints/841/841-uzasadnienie.docx", D),
       S("Rozporządzenie RM w sprawie minimalnego wynagrodzenia w 2026 r., Dz.U. 2025 poz. 1242", "https://dziennikustaw.gov.pl/D2025000124201.pdf", D)],
      explain=[
          K("Cena maksymalna działa tylko poniżej równowagi",
            "Cena maksymalna to najwyższa dopuszczalna cena. Jeśli ustalono ją POWYŻEJ ceny równowagi – nic się nie zmienia (nie wiąże). Jeśli PONIŻEJ – sprzedawcy oferują mniej, kupujący chcą więcej: powstaje trwały niedobór, bo cena nie może wzrosnąć i go zlikwidować."),
          K("Skutki uboczne ceny maksymalnej",
            "Przy niedoborze dobro trzeba jakoś rozdzielić: kolejki, reglamentacja, „znajomości”, czarny rynek z wyższą ceną. Sprzedawcy mogą obniżać jakość lub ograniczać inwestycje (np. przy kontroli czynszów – gorszy stan mieszkań). Część transakcji korzystnych dla obu stron w ogóle nie dochodzi do skutku."),
          K("Cena minimalna działa tylko powyżej równowagi",
            "Cena minimalna to najniższa dopuszczalna cena (np. skup interwencyjny w rolnictwie). Jeśli jest wyższa od ceny równowagi, sprzedający oferują więcej, niż kupujący chcą kupić – nadwyżka. Państwo często ją wykupuje i magazynuje, co kosztuje budżet."),
          W("Państwo ustala cenę maksymalną chleba na 3 zł, a cena równowagi wynosi 5 zł. Co się stanie?",
            "Pojawi się niedobór chleba", "Pojawi się nadwyżka chleba", "Nic – cena maksymalna nie wiąże",
            why="Cena maksymalna poniżej równowagi zwiększa wielkość popytu i zmniejsza wielkość podaży."),
          K("Mrożenie cen prądu – cena maksymalna z rekompensatą",
            "W latach kryzysu energetycznego Polska wprowadziła dla gospodarstw domowych cenę maksymalną energii (w 2025 r. 500 zł/MWh netto). Nie doszło do niedoboru prądu, bo sprzedawcy dostawali rekompensaty różnicy między kosztem a ceną maksymalną – z Funduszu Wypłaty Różnicy Ceny. Koszt nie znika: ponoszą go fundusz i budżet, a nie odbiorca w rachunku. Od 2026 r. obowiązują taryfy URE (średnio 495,16 zł/MWh netto za energię, bez dystrybucji)."),
          K("Płaca minimalna jako cena minimalna na rynku pracy",
            "Płaca minimalna (w 2026 r. 4806 zł brutto miesięcznie, 31,40 zł za godzinę) to cena minimalna pracy. W prostym modelu konkurencyjnym ustalona powyżej płacy równowagi zmniejsza zatrudnienie najmniej wydajnych pracowników. Badania pokazują jednak, że przy umiarkowanej wysokości efekt bywa mały, a na rynkach z siłą pracodawcy (monopson) zatrudnienie może nawet wzrosnąć.",
            g=G("praca")),
          PF("Cena maksymalna ustalona powyżej ceny równowagi powoduje niedobór.", False,
             why="Taka cena nie wiąże – rynek i tak ustali się w równowadze poniżej limitu."),
      ],
      mech=[
          LN("Ułóż skutki kontroli czynszów ustalonej poniżej równowagi.",
             ["Państwo ustala maksymalny czynsz poniżej równowagi", "Więcej osób chce wynająć mieszkanie",
              "Właściciele wycofują część mieszkań z najmu", "Pojawia się trwały niedobór mieszkań",
              "Rozwija się nieformalny rynek i spada jakość mieszkań"],
             why="Wiążąca cena maksymalna działa na obie strony rynku; niedobór wywołuje zjawiska zastępujące mechanizm cenowy."),
          KT("Która cena urzędowa WIĄŻE (zmienia wynik rynku)? Cena równowagi wynosi 50 zł.",
             {"Wiąże": ["Cena maksymalna 40 zł", "Cena minimalna 60 zł", "Cena maksymalna 49 zł"],
              "Nie wiąże": ["Cena maksymalna 70 zł", "Cena minimalna 30 zł", "Cena minimalna 45 zł"]},
             why="Maksymalna wiąże, gdy jest poniżej równowagi; minimalna – gdy jest powyżej."),
          W("Rząd ustala cenę minimalną skupu zboża powyżej ceny równowagi i zobowiązuje się kupić nadwyżkę. Kto ponosi koszt?",
            "Podatnicy – budżet płaci za skup i magazynowanie nadwyżki",
            "Wyłącznie rolnicy",
            "Nikt – nadwyżka znika sama",
            why="Wiążąca cena minimalna tworzy nadwyżkę; jej wykup finansuje budżet."),
          W("Dlaczego mrożenie cen prądu w Polsce nie wywołało niedoboru energii, choć było ceną maksymalną poniżej kosztów?",
            "Sprzedawcy dostawali rekompensaty różnicy cen z funduszu",
            "Popyt na prąd jest doskonale elastyczny",
            "Cena maksymalna była wyższa od rynkowej",
            "Elektrownie miały obowiązek produkować za darmo",
            why="Rekompensata sprawiała, że sprzedaż nadal się opłacała; koszt przeniesiono na fundusz i budżet."),
          PF("Wzrost płacy minimalnej w modelu konkurencyjnym (powyżej płacy równowagi) zwiększa wielkość podaży pracy i zmniejsza wielkość popytu na pracę.", True,
             why="Wyższa płaca zachęca więcej osób do szukania pracy, a firmy zatrudniają mniej – różnica to bezrobocie w modelu."),
          W("Która sytuacja jest typowa dla wiążącej ceny maksymalnej na leki w aptekach?",
            "Okresowe braki leku i dłuższe poszukiwania pacjentów",
            "Nadmiar leku w hurtowniach",
            "Spadek popytu na lek",
            why="Przy cenie poniżej równowagi część dostawców ogranicza dostawy, a popyt jest wyższy – stąd braki."),
          M("Które skutki mogą towarzyszyć wiążącej cenie maksymalnej?",
            ["Kolejki i listy oczekujących", "Czarny rynek", "Nadwyżka towaru w sklepach", "Spadek jakości dobra"],
            [0, 1, 3],
            why="Nadwyżka jest typowa dla ceny minimalnej, nie maksymalnej."),
      ],
      calc=[
          LB("Popyt: Qd = 120 − 4P, podaż: Qs = −30 + 6P (równowaga P* = 15). Ile wynosi niedobór przy cenie maksymalnej 10 zł?",
             50, "(120-4*10)-(-30+6*10)", ["Qd = 80, Qs = 30", "Niedobór = 80 − 30 = 50"], unit="szt."),
          LB("Ile sztuk faktycznie zostanie sprzedanych przy cenie maksymalnej 10 zł (Qd = 120 − 4P, Qs = −30 + 6P)?",
             30, "min(120-4*10, -30+6*10)", ["Sprzedaż ogranicza krótsza strona rynku", "min(Qd = 80, Qs = 30) = 30 – mniej niż w równowadze (60)"], unit="szt."),
          LB("Państwo ustala cenę minimalną 20 zł (Qd = 120 − 4P, Qs = −30 + 6P) i wykupuje całą nadwyżkę. Ile wyda na skup?",
             1000, "((-30+6*20)-(120-4*20))*20", ["Qs = 90, Qd = 40 ⇒ nadwyżka 50", "Koszt skupu = 50 · 20 zł = 1000 zł"], unit="zł"),
          LB("Gospodarstwo zużywa rocznie 1,8 MWh. Ile zapłaci za samą energię (netto, bez dystrybucji) przy średniej taryfie 2026 r. 495,16 zł/MWh?",
             891.29, "1.8*495.16", ["1,8 · 495,16 = 891,288 ≈ 891,29 zł"], unit="zł", tol=0.02),
          LB("O ile procent średnia taryfa 2026 (495,16 zł/MWh) jest niższa od taryfy z IV kwartału 2025 r. (572,64 zł/MWh)? Podaj liczbę dodatnią.",
             13.53, "(572.64-495.16)/572.64*100", ["Różnica: 572,64 − 495,16 = 77,48 zł", "77,48 / 572,64 · 100% ≈ 13,53%"], unit="%", tol=0.05),
          LB("Płaca minimalna wzrosła z 4666 zł (2025) do 4806 zł (2026). O ile procent?",
             3.0, "(4806-4666)/4666*100", ["Wzrost: 140 zł", "140 / 4666 · 100% ≈ 3,0%"], unit="%", tol=0.05),
      ],
      case=[
          PR("Kryzys energetyczny: hurtowe ceny prądu gwałtownie rosną. Rząd ustala dla gospodarstw domowych cenę maksymalną 500 zł/MWh netto, niższą od kosztu zakupu energii przez sprzedawców, i obiecuje sprzedawcom rekompensaty z Funduszu Wypłaty Różnicy Ceny.",
             W("Jaki jest główny cel ustalenia ceny maksymalnej w tym przypadku?",
               "Ochrona gospodarstw domowych przed gwałtownym wzrostem rachunków", "Zwiększenie zużycia energii", "Obniżenie kosztów produkcji energii",
               why="Cena maksymalna chroni odbiorców przed szokiem cenowym; nie obniża kosztów wytwarzania."),
             W("Kto w tym rozwiązaniu ponosi koszt różnicy między ceną zakupu a ceną maksymalną?",
               "Fundusz rekompensat, czyli ostatecznie finanse publiczne i spółki energetyczne objęte odpisami",
               "Wyłącznie gospodarstwa domowe w rachunkach",
               "Nikt – koszt znika",
               why="Rekompensaty wypłaca Fundusz Wypłaty Różnicy Ceny zasilany m.in. odpisami od nadmiarowych przychodów spółek energetycznych."),
             PF("Przy niskiej, sztucznie utrzymanej cenie gospodarstwa domowe mają słabszy bodziec do oszczędzania energii.", True,
                why="Cena przestaje w pełni przekazywać sygnał o niedoborze energii; dlatego takie rozwiązania często mają limity zużycia."),
          ),
          PR("Rząd rozważa podniesienie płacy minimalnej o 15% w jednym roku, przy przeciętnym wzroście wydajności pracy o 3%. Najwięcej pracowników z płacą minimalną zatrudniają małe firmy usługowe w mniejszych miejscowościach.",
             W("Które ryzyko jest największe według modelu ceny minimalnej?",
               "Ograniczenie zatrudnienia lub przejście części pracy do szarej strefy w małych firmach",
               "Nadwyżka towarów w sklepach",
               "Spadek podaży pracy",
               why="Wysoka i szybka podwyżka powyżej wzrostu wydajności zwiększa ryzyko, że płaca przekroczy wartość pracy dla części pracodawców."),
             M("Które argumenty przemawiają ZA umiarkowanym wzrostem płacy minimalnej?",
               ["Ochrona dochodów najsłabiej opłacanych pracowników", "Przeciwdziałanie sile pracodawcy na lokalnych rynkach (monopson)",
                "Pewność, że zatrudnienie nigdy nie spadnie", "Zachęta do szukania pracy (wyższa wielkość podaży pracy)"],
               [0, 1, 3],
               why="Żaden model nie daje pewności braku wpływu na zatrudnienie; pozostałe argumenty są uznawane w literaturze."),
             LB("Pracownik na płacy minimalnej 2026 (31,40 zł/h) pracuje 168 godzin w miesiącu na umowie zlecenia. Ile wynosi jego wynagrodzenie brutto?",
                5275.2, "31.40*168", ["31,40 zł · 168 h = 5275,20 zł brutto"], unit="zł", tol=0.05),
          ),
      ]),

    L(5, "Nadwyżki, podatek i dotacja – kto zyskuje, kto traci",
      "Liczyć nadwyżkę konsumenta i producenta, rozumieć stratę martwą podatku i dotacji oraz to, od czego zależy rozkład ciężaru podatku.",
      ["Nadwyżka konsumenta", "Nadwyżka producenta", "Zbędna strata społeczna (strata martwa, deadweight loss)",
       "Rozkład ciężaru podatku (incydencja podatkowa)", "Subsydium do produkcji – skutki rynkowe"],
      [S("OpenStax, Principles of Economics 3e, 3.5 Demand, Supply, and Efficiency", OS3 + "3-5-demand-supply-and-efficiency", D),
       S("OpenStax, Principles of Economics 3e, 5.3 Elasticity and Pricing (tax incidence)", OS3 + "5-3-elasticity-and-pricing", D)],
      explain=[
          K("Nadwyżka konsumenta",
            "To różnica między tym, ile kupujący byłby gotów zapłacić, a ceną, którą faktycznie płaci, zsumowana po wszystkich kupionych jednostkach. Na wykresie: trójkąt pod krzywą popytu i nad ceną."),
          K("Nadwyżka producenta",
            "To różnica między ceną a najniższą ceną, za którą producent byłby gotów sprzedać (kosztem krańcowym), zsumowana po jednostkach. Na wykresie: trójkąt nad krzywą podaży i pod ceną. Suma obu nadwyżek jest największa w równowadze rynku konkurencyjnego."),
          K("Podatek tworzy klin i stratę martwą",
            "Podatek od jednostki sprawia, że kupujący płacą więcej, a sprzedający dostają mniej (klin podatkowy). Ilość spada, więc część transakcji korzystnych dla obu stron znika. Wpływy budżetu nie rekompensują całej utraconej nadwyżki – różnica to strata martwa (trójkąt Harbergera).",
            w="Wpływy = t · Q₁;  Strata martwa ≈ ½ · t · (Q₀ − Q₁)"),
          W("Od czego zależy, kto faktycznie ponosi większą część podatku akcyzowego?",
            "Od elastyczności popytu i podaży – więcej płaci strona mniej elastyczna",
            "Od tego, kto formalnie odprowadza podatek do urzędu",
            "Zawsze płacą go po połowie kupujący i sprzedający",
            why="Ekonomiczny rozkład ciężaru nie zależy od formalnego podatnika, tylko od elastyczności obu stron rynku."),
          K("Dotacja – odwrotny klin",
            "Dotacja do jednostki obniża cenę płaconą przez kupujących i podnosi cenę otrzymywaną przez sprzedających. Ilość rośnie ponad poziom równowagi, a koszt dotacji dla budżetu jest większy niż łączny zysk kupujących i sprzedających – to także strata martwa."),
          PF("Podatek akcyzowy na papierosy płacą w dużej mierze palacze, bo ich popyt jest mało elastyczny.", True,
             why="Przy nieelastycznym popycie cena dla kupujących rośnie prawie o cały podatek."),
      ],
      mech=[
          WY("Na sprzedawców biletów nałożono podatek od każdego biletu. Jak zmienia się wykres?",
             G("sd", S=-1), "Podaż przesuwa się w górę/lewo: cena płacona rośnie, ilość spada",
             "Popyt przesuwa się w prawo", "Podaż przesuwa się w prawo: cena spada", "Nic się nie zmienia",
             why="Podatek od jednostki działa jak wzrost kosztu dla sprzedawców."),
          WY("Państwo dopłaca producentom do każdej pompy ciepła. Jak zmienia się rynek pomp?",
             G("sd", S=1), "Podaż rośnie: cena dla kupujących spada, sprzedaż rośnie",
             "Popyt maleje", "Podaż maleje: cena rośnie", "Cena i ilość się nie zmieniają",
             why="Dotacja do jednostki obniża koszt produkcji, przesuwając podaż w prawo."),
          LN("Ułóż, skąd bierze się strata martwa podatku.",
             ["Podatek podnosi cenę płaconą i obniża cenę otrzymywaną", "Ilość transakcji spada poniżej równowagi",
              "Znikają transakcje, w których gotowość do zapłaty przewyższała koszt", "Utracona nadwyżka tych transakcji nie trafia do nikogo"],
             why="Strata martwa to wartość transakcji, które przestały się odbywać – nie trafia ani do stron, ani do budżetu."),
          KT("Kto poniesie większą część podatku?",
             {"Głównie kupujący": ["Benzyna w krótkim okresie (popyt mało elastyczny)", "Leki ratujące życie", "Papierosy dla uzależnionych palaczy"],
              "Głównie sprzedający": ["Dobro z bardzo elastycznym popytem i sztywną podażą", "Działki budowlane o stałej podaży", "Owoce, których nie da się przechować (podaż sztywna krótkookresowo)"]},
             why="Ciężar przechodzi na stronę, która trudniej może się „wycofać” z rynku (mniej elastyczną)."),
          PF("Im bardziej elastyczny popyt i podaż, tym większa strata martwa przy tym samym podatku.", True,
             why="Przy wyższej elastyczności ilość spada mocniej, więc znika więcej korzystnych transakcji."),
          W("Rząd wprowadza dotację i podatek tej samej wysokości na dwóch różnych rynkach o identycznych krzywych. Co prawda?",
            "Oba narzędzia tworzą stratę martwą – oddalają ilość od równowagi",
            "Tylko podatek tworzy stratę martwą",
            "Tylko dotacja tworzy stratę martwą",
            why="Zarówno zbyt mała (podatek), jak i zbyt duża (dotacja) ilość względem równowagi obniża nadwyżkę całkowitą."),
          M("Które stwierdzenia o nadwyżkach są prawdziwe?",
            ["Spadek ceny przy niezmienionej podaży zwiększa nadwyżkę konsumenta", "Nadwyżka całkowita jest największa w równowadze konkurencyjnej",
             "Podatek zwiększa nadwyżkę producenta", "Wiążąca cena maksymalna może obniżyć nadwyżkę producenta"],
            [0, 1, 3],
            why="Podatek zmniejsza nadwyżki obu stron; cena maksymalna obniża cenę i ilość sprzedającego."),
      ],
      calc=[
          LB("Popyt: Qd = 120 − 4P (dla Qd = 0 cena wynosi 30 zł), podaż: Qs = −30 + 6P (dla Qs = 0 cena 5 zł). Równowaga: P = 15, Q = 60. Oblicz nadwyżkę konsumenta.",
             450, "0.5*(30-15)*60", ["NK = ½ · (cena maks. − P*) · Q*", "= ½ · (30 − 15) · 60 = 450 zł"], unit="zł"),
          LB("Dla tego samego rynku oblicz nadwyżkę producenta.",
             300, "0.5*(15-5)*60", ["NP = ½ · (P* − cena min.) · Q*", "= ½ · (15 − 5) · 60 = 300 zł"], unit="zł"),
          LB("Na sprzedawców nałożono podatek 5 zł od sztuki (Qd = 120 − 4P, Qs = −30 + 6(P − 5)). Jaką cenę zapłacą kupujący?",
             18, "180/10", ["Podaż po podatku: Qs = −30 + 6P − 30 = −60 + 6P", "120 − 4P = −60 + 6P ⇒ 180 = 10P ⇒ P = 18 zł", "Sprzedawcy dostają 18 − 5 = 13 zł"], unit="zł"),
          LB("Ile wyniosą wpływy z tego podatku (t = 5 zł, nowa ilość Q = 120 − 4·18)?",
             240, "5*(120-4*18)", ["Q₁ = 120 − 72 = 48", "Wpływy = 5 · 48 = 240 zł"], unit="zł"),
          LB("Ile wynosi strata martwa podatku (t = 5, Q₀ = 60, Q₁ = 48)?",
             30, "0.5*5*(60-48)", ["SM = ½ · t · (Q₀ − Q₁)", "= ½ · 5 · 12 = 30 zł", "Sprawdzenie: nadwyżki przed 750 zł; po: NK 288 + NP 192 + wpływy 240 = 720 zł; różnica 30 zł"], unit="zł"),
          LB("Jaki procent podatku ponoszą kupujący (cena wzrosła z 15 do 18 zł przy podatku 5 zł)?",
             60, "(18-15)/5*100", ["Kupujący: 18 − 15 = 3 zł z 5 zł", "3 / 5 · 100% = 60% (sprzedający: 40%)"], unit="%"),
          LB("Zamiast podatku państwo daje dotację 5 zł do sztuki: Qs = −30 + 6(P + 5). Ile wyniesie koszt dotacji dla budżetu?",
             360, "5*(120-4*12)", ["Qs = 6P; 120 − 4P = 6P ⇒ P = 12 zł (kupujący), sprzedawcy dostają 17 zł", "Q = 120 − 48 = 72", "Koszt = 5 · 72 = 360 zł"], unit="zł"),
      ],
      case=[
          PR("Rząd chce zebrać więcej pieniędzy i rozważa podwyżkę akcyzy na jeden z dwóch produktów: paliwo (popyt w krótkim okresie mało elastyczny) albo bilety do kina (popyt elastyczny – łatwo zastąpić je streamingiem).",
             W("Który podatek przyniesie większe wpływy przy tej samej stawce?",
               "Na paliwo – ilość spadnie niewiele, więc baza podatku pozostanie duża",
               "Na bilety – ludzie kupią więcej biletów",
               "Oba przyniosą identyczne wpływy",
               why="Wpływy = stawka · ilość po podatku; przy nieelastycznym popycie ilość spada mniej."),
             W("Który podatek wywoła mniejszą stratę martwą?",
               "Na paliwo – mniejsza zmiana ilości", "Na bilety", "Strata martwa nie zależy od elastyczności",
               why="Strata martwa rośnie wraz z elastycznością, bo zależy od spadku ilości."),
             PF("Podatek na paliwo w krótkim okresie zapłacą głównie kierowcy, nawet jeśli formalnie odprowadzają go stacje.", True,
                why="O rozkładzie ciężaru decyduje elastyczność, a nie to, kto przelewa podatek do urzędu."),
          ),
          PR("Gmina dopłaca 300 zł do każdego biletu na kolonie dla dzieci. Po wprowadzeniu dopłaty organizatorzy podnieśli ceny o 120 zł, a liczba uczestników wzrosła.",
             LB("Ile realnie zyskuje rodzic na każdym bilecie (spadek ceny płaconej netto)?",
                180, "300-120", ["Cena przed: P; po: P + 120 − 300 (dopłata)", "Spadek kosztu dla rodzica: 300 − 120 = 180 zł"], unit="zł"),
             W("Kto przejął część dotacji?",
               "Organizatorzy – dostają o 120 zł więcej za bilet", "Wyłącznie rodzice", "Nikt – dotacja w całości trafia do budżetu",
               why="Dotacja dzieli się między strony rynku podobnie jak ciężar podatku – zależnie od elastyczności."),
             PF("Wzrost liczby uczestników ponad poziom bez dopłaty może oznaczać stratę martwą – część kolonii kosztuje więcej, niż są warte dla rodzin.", True,
                why="Gdy dotacja wypycha ilość ponad równowagę, koszt dodatkowych jednostek przewyższa korzyść kupujących."),
          ),
      ]),
]
