# -*- coding: utf-8 -*-
# Zrozumienie – Mikroekonomia / Instytucje: UOKiK
D = "2026-10-07"
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
SKAR = S("UOKiK – Ograniczanie konkurencji: kary", "https://uokik.gov.pl/ograniczanie-konkurencji-kary", D)
SKON = S("UOKiK – Kontrola koncentracji (wyjaśnienia Prezesa UOKiK)", "https://uokik.gov.pl/kontrola-koncentracji-aktualizacja-wyjasnien-prezesa-uokik", D)
S112 = S("OpenStax, Principles of Economics 3e, 11.2 Regulating Anticompetitive Behavior", OS3 + "11-2-regulating-anticompetitive-behavior", D)
S111 = S("OpenStax, Principles of Economics 3e, 11.1 Corporate Mergers", OS3 + "11-1-corporate-mergers", D)

LESSONS = [
    L(1, "UOKiK: jak państwo chroni konkurencję",
      "Rozumieć zadania Prezesa UOKiK w ochronie konkurencji: zakaz porozumień i nadużywania pozycji dominującej, kontrolę koncentracji, kary i program łagodzenia kar.",
      ["Urząd Ochrony Konkurencji i Konsumentów (UOKiK)", "Kartel", "Formy monopolizacji (porozumienia i koncentracje)", "Dylemat więźnia"],
      [SKAR, SKON, S112, S111],
      explain=[
          K("Czym zajmuje się UOKiK",
            "Prezes Urzędu Ochrony Konkurencji i Konsumentów jest centralnym organem administracji, który stosuje ustawę o ochronie konkurencji i konsumentów: zwalcza porozumienia ograniczające konkurencję (zmowy, kartele), nadużywanie pozycji dominującej, kontroluje koncentracje (fuzje i przejęcia) oraz chroni zbiorowe interesy konsumentów."),
          K("Zakazane praktyki",
            "Zakazane są porozumienia, których celem lub skutkiem jest ograniczenie konkurencji – np. ustalanie cen, podział rynku, zmowy przetargowe. Zakazane jest też nadużywanie pozycji dominującej, np. narzucanie nieuczciwych cen, ceny drapieżne czy uzależnianie umowy od zakupu innych produktów."),
          W("Trzy hurtownie ustalają wspólnie minimalne ceny dla sklepów. Co to jest?",
            "Porozumienie ograniczające konkurencję (kartel)", "Koncentracja", "Pozycja dominująca", "Legalna współpraca",
            why="Ustalanie cen przez konkurentów to klasyczny przykład zakazanego porozumienia."),
          K("Kary i program łagodzenia kar",
            "Za praktyki ograniczające konkurencję przedsiębiorcy grozi kara do 10% obrotu, a menedżerowi odpowiedzialnemu za naruszenie – do 2 mln zł. Uczestnik zmowy, który pierwszy ją ujawni i współpracuje z urzędem (leniency), może uniknąć kary lub dostać jej obniżenie – to wykorzystanie logiki dylematu więźnia."),
          K("Kontrola koncentracji",
            "Zamiar koncentracji trzeba zgłosić Prezesowi UOKiK, gdy łączny obrót uczestników w roku poprzedzającym przekracza 1 mld euro na świecie lub 50 mln euro w Polsce (z wyjątkami w ustawie). Urząd może zgodzić się na fuzję, zgodzić się pod warunkami (np. sprzedaż części sklepów) albo jej zakazać, jeśli istotnie ograniczy konkurencję."),
          PF("UOKiK może nałożyć karę finansową także na menedżera, który świadomie dopuścił do zmowy.", True,
             why="Kara dla osoby zarządzającej może wynieść do 2 mln zł."),
      ],
      mech=[
          KT("Jaki rodzaj sprawy rozpatruje UOKiK?",
             {"Porozumienie ograniczające konkurencję": ["Zmowa przetargowa firm budowlanych", "Podział rynku regionami przez producentów", "Wspólne ustalanie cen przez konkurentów"],
              "Nadużycie pozycji dominującej": ["Jedyny dostawca uzależnia sprzedaż od zakupu drugiego produktu", "Firma dominująca stosuje ceny poniżej kosztów, by wyeliminować rywala"],
              "Kontrola koncentracji": ["Przejęcie sieci sklepów przez konkurenta", "Fuzja dwóch dużych producentów"]},
             why="UOKiK ma odrębne procedury dla każdej z tych spraw."),
          LN("Ułóż, jak program łagodzenia kar rozbija kartele.",
             ["Firmy uczestniczą w zmowie", "Każda obawia się, że inna zgłosi się pierwsza", "Pierwszy zgłaszający może uniknąć kary", "Wyścig do urzędu – zaufanie w kartelu słabnie", "Kartel zostaje ujawniony"],
             why="Program zmienia wypłaty w „grze” kartelowej na korzyść zdrady."),
          W("Dlaczego kontrola koncentracji działa „z wyprzedzeniem”, przed fuzją?",
            "Łatwiej zapobiec powstaniu siły rynkowej niż ją potem rozbić", "Bo fuzje są zawsze zakazane", "Bo UOKiK nie może kontrolować firm po fuzji",
            why="Po połączeniu przywrócenie konkurencji byłoby bardzo trudne i kosztowne."),
          W("UOKiK zgodził się na przejęcie sieci sklepów pod warunkiem sprzedaży części placówek. Po co?",
            "By na lokalnych rynkach zachować konkurencję", "By zwiększyć zysk przejmującego", "By ukarać sprzedającego",
            why="Warunki (środki zaradcze) usuwają ograniczenie konkurencji w miejscach, gdzie fuzja by je wywołała."),
          PF("Każda duża firma ma pozycję dominującą i dlatego łamie prawo.", False,
             why="Zakazane jest NADUŻYWANIE pozycji dominującej, a nie samo jej posiadanie."),
          M("Jakie decyzje może wydać Prezes UOKiK w sprawie koncentracji?",
            ["Zgoda", "Zgoda warunkowa", "Ustalenie cen wszystkich produktów firmy", "Zakaz"],
            [0, 1, 3],
            why="UOKiK nie ustala cen produktów firm."),
      ],
      calc=[
          LB("Obrót firmy w roku poprzedzającym decyzję: 800 mln zł. Ile wynosi maksymalna kara za udział w zmowie (10%)?",
             80, "800*0.1", ["10% · 800 mln zł = 80 mln zł"], unit="mln zł"),
          LB("Kartel podniósł ceny o 15% na rynku wartym 200 mln zł rocznie, działając 4 lata. Ile szacunkowo przepłacili klienci?",
             120, "200*0.15*4", ["200 · 0,15 = 30 mln zł rocznie", "· 4 = 120 mln zł"], unit="mln zł"),
          LB("Firma A ma 60 mln euro obrotu w Polsce, B – 2 mln euro (obie małe globalnie). Czy przekroczono próg 50 mln euro w Polsce? Podaj łączny obrót w Polsce (mln euro).",
             62, "60+2", ["60 + 2 = 62 mln euro > 50 mln euro – co do zasady trzeba zgłosić (o ile nie zachodzą wyjątki ustawowe)"], unit="mln euro"),
          LB("Program leniency: firma uniknęła kary 50 mln zł, a dwie inne dostały po 30 mln zł. Ile łącznie wyniosły kary?",
             60, "2*30", ["2 · 30 = 60 mln zł"], unit="mln zł"),
          LB("Menedżer odpowiedzialny za zmowę: maksymalna kara 2 mln zł. Jeśli jego roczna pensja to 500 tys. zł, ilu rocznym pensjom odpowiada kara?",
             4, "2000/500", ["2000 / 500 = 4"], unit=""),
          LB("Przed fuzją HHI = 1800, udziały łączących się firm 15% i 10%. Ile wyniesie HHI po fuzji?",
             2100, "1800+2*15*10", ["Δ = 2 · 15 · 10 = 300", "HHI = 2100"], unit=""),
      ],
      case=[
          PR("Trzech producentów materiałów budowlanych przez kilka lat uzgadniało podwyżki cennikowe i podział klientów. Jeden z nich złożył wniosek leniency i przekazał dokumenty. UOKiK nałożył kary na dwóch pozostałych i na menedżerów.",
             W("Dlaczego firma zgłosiła zmowę?",
               "Program leniency daje szansę uniknięcia kary pierwszemu, który ujawni kartel", "By zwiększyć zyski kartelu", "Bo musiała zrobić to co roku",
               why="Zgłoszenie się pierwszym jest strategią dominującą, gdy rośnie ryzyko wykrycia."),
             PF("Podział klientów między konkurentów jest zakazany tak samo jak ustalanie cen.", True,
                why="Podział rynku eliminuje konkurencję o klientów."),
             W("Kto ponosił koszt działania kartelu?",
               "Klienci – płacili wyższe ceny", "Tylko UOKiK", "Uczestnicy kartelu",
               why="Kartel podnosi ceny powyżej poziomu konkurencyjnego."),
          ),
          PR("Duża sieć drogerii chce przejąć mniejszą. W większości miast mają one niewielkie udziały, ale w trzech miastach po fuzji kontrolowałyby ponad 60% lokalnej sprzedaży.",
             W("Jaką decyzję najprawdopodobniej rozważy UOKiK?",
               "Zgodę warunkową – np. sprzedaż sklepów w trzech miastach", "Bezwarunkowy zakaz w całym kraju", "Brak zainteresowania sprawą",
               why="Problem dotyczy rynków lokalnych, więc środek zaradczy może być punktowy."),
             W("Dlaczego analizuje się rynki lokalne, a nie tylko krajowy?",
               "Klienci drogerii kupują blisko domu – konkurencja jest lokalna", "Bo tak jest łatwiej", "Bo prawo zakazuje analizy krajowej",
               why="Właściwy rynek geograficzny wyznacza miejsce, gdzie klienci mogą wybierać sprzedawców."),
             PF("Sama duża skala przedsiębiorstwa po fuzji jest wystarczającym powodem zakazu.", False,
                why="Liczy się istotne ograniczenie konkurencji na właściwym rynku, a nie wielkość firmy."),
          ),
      ]),

    L(2, "UOKiK i konsumenci: zbiorowe interesy i informacja",
      "Rozumieć ekonomiczne uzasadnienie ochrony konsumentów (asymetria informacji, koszty transakcyjne, błędy poznawcze) i rolę UOKiK w zwalczaniu praktyk naruszających zbiorowe interesy konsumentów.",
      ["Urząd Ochrony Konkurencji i Konsumentów (UOKiK)", "Asymetria informacji", "Teoria szturchania (nudge)"],
      [SKAR, S("OpenStax, Principles of Economics 3e, 16.1 Imperfect and Asymmetric Information", OS3 + "16-1-the-problem-of-imperfect-information-and-asymmetric-information", D)],
      explain=[
          K("Po co chronić konsumentów, skoro jest konkurencja?",
            "Konkurencja działa najlepiej, gdy klienci mają dobrą informację i mogą łatwo porównać oferty. Gdy sprzedawca wie znacznie więcej (warunki umowy drobnym drukiem, ukryte opłaty), rynek może premiować wprowadzanie w błąd zamiast lepszej oferty."),
          K("Zbiorowe interesy konsumentów",
            "UOKiK nie rozstrzyga indywidualnych sporów (tym zajmują się sądy i rzecznicy konsumentów), ale zwalcza praktyki dotyczące wielu klientów: wprowadzające w błąd reklamy, niedozwolone klauzule w umowach, agresywne techniki sprzedaży. Może nakazać zmianę praktyki i nałożyć karę."),
          W("Klient pokłócił się ze sklepem o reklamację jednej kurtki. Kto przede wszystkim mu pomoże?",
            "Miejski lub powiatowy rzecznik konsumentów albo sąd", "Prezes UOKiK w postępowaniu antymonopolowym", "Komisja Europejska",
            why="UOKiK działa w sprawach naruszających zbiorowe interesy konsumentów, a nie w pojedynczych sporach."),
          K("Ekonomia behawioralna w ochronie konsumentów",
            "Wiele praktyk wykorzystuje błędy poznawcze: fałszywe „ostatnie sztuki”, liczniki czasu promocji, ukrywanie rezygnacji z subskrypcji. Ochrona konsumentów coraz częściej dotyczy takich „ciemnych wzorców” i rzetelności informacji (np. najniższa cena z 30 dni przed obniżką)."),
          K("Granice regulacji",
            "Nadmierna regulacja podnosi koszty firm i może ograniczać wybór. Dlatego preferuje się narzędzia informacyjne (obowiązki ujawnienia, porównywalne wskaźniki kosztów kredytu – RRSO) zamiast kontroli cen."),
          PF("Obowiązek podawania RRSO przy kredycie konsumenckim to przykład regulacji poprawiającej informację, a nie kontroli ceny.", True,
             why="RRSO ułatwia porównanie łącznego kosztu kredytu bez ustalania jego ceny."),
      ],
      mech=[
          KT("Czy to typowa sprawa dla UOKiK?",
             {"Tak – zbiorowe interesy konsumentów": ["Bank stosuje w tysiącach umów niedozwoloną klauzulę", "Sieć sklepów reklamuje „promocje”, zawyżając cenę wyjściową", "Serwis utrudnia rezygnację z subskrypcji wszystkim klientom"],
              "Nie – sprawa indywidualna": ["Spór sąsiadów o płot", "Jednorazowa reklamacja butów w jednym sklepie", "Spór o wysokość alimentów"]},
             why="UOKiK działa, gdy praktyka dotyczy szerokiego kręgu konsumentów."),
          LN("Ułóż, jak wprowadzająca w błąd reklama psuje konkurencję.",
             ["Firma A ukrywa część kosztów w drobnym druku", "Jej oferta wygląda na tańszą", "Klienci wybierają A zamiast uczciwego B", "B traci klientów mimo lepszej oferty", "Firmy mają bodziec, by konkurować sztuczkami zamiast jakością"],
             why="Asymetria informacji odwraca bodźce konkurencji."),
          W("Licznik „oferta kończy się za 5:00”, który resetuje się po odświeżeniu strony, wykorzystuje:",
            "Presję czasu i błąd poznawczy – to może być nieuczciwa praktyka", "Efekt skali", "Teorię Coase’a",
            why="Fałszywa presja czasu zniekształca decyzje konsumentów."),
          W("Dlaczego RRSO pomaga konkurencji na rynku kredytów?",
            "Pozwala porównać pełny koszt kredytów różnych banków", "Ustala maksymalne oprocentowanie", "Zakazuje prowizji",
            why="Porównywalna informacja wzmacnia presję konkurencyjną."),
          PF("Ochrona konsumentów i ochrona konkurencji są ze sobą sprzeczne.", False,
             why="Uzupełniają się – dobrze poinformowani konsumenci wzmacniają konkurencję."),
          M("Jakie narzędzia stosuje się w ochronie konsumentów?",
            ["Obowiązki informacyjne", "Zakaz klauzul niedozwolonych", "Ustalanie zysków firm", "Kary za praktyki wprowadzające w błąd"],
            [0, 1, 3],
            why="Ochrona konsumentów nie polega na ustalaniu zysków firm."),
      ],
      calc=[
          LB("Kredyt 10 000 zł: oprocentowanie 8% rocznie, prowizja 1000 zł, okres 1 rok, spłata jednorazowa. Ile wynosi łączny koszt kredytu?",
             1800, "10000*0.08+1000", ["Odsetki: 800 zł", "Prowizja: 1000 zł", "Razem: 1800 zł"], unit="zł"),
          LB("Jaki procent kwoty kredytu stanowi łączny koszt (1800 zł z 10 000 zł)?",
             18, "1800/10000*100", ["18% – znacznie więcej niż „8%” z reklamy"], unit="%"),
          LB("Cena przed obniżką podana w reklamie: 1000 zł; najniższa cena z 30 dni: 750 zł; cena w promocji: 700 zł. Jaki jest rzeczywisty rabat względem najniższej ceny z 30 dni (w %)?",
             6.67, "(750-700)/750*100", ["50 / 750 ≈ 6,67% (zamiast reklamowanych 30%)"], unit="%", tol=0.02),
          LB("Ukryta opłata 9,99 zł miesięcznie dotyczy 200 000 klientów. Ile firma zarabia na niej rocznie (mln zł)?",
             23.976, "9.99*200000*12/1000000", ["9,99 · 200 000 · 12 = 23 976 000 zł"], unit="mln zł", tol=0.01),
          LB("Kara 3% obrotu dla firmy z obrotem 400 mln zł. Ile wynosi?",
             12, "400*0.03", ["0,03 · 400 = 12 mln zł"], unit="mln zł"),
          LB("Subskrypcja 39 zł/mies. Z powodu utrudnionej rezygnacji klient płacił 5 miesięcy dłużej. Ile przepłacił?",
             195, "39*5", ["39 · 5 = 195 zł"], unit="zł"),
      ],
      case=[
          PR("Operator telekomunikacyjny reklamuje „Internet za 29 zł”, ale w umowie po 6 miesiącach cena rośnie do 79 zł, a informacja o tym jest drobnym drukiem. Tysiące klientów zgłaszają skargi.",
             W("Jakie zjawisko ekonomiczne wykorzystuje operator?",
               "Asymetrię informacji i przecenianie teraźniejszości klientów", "Efekt skali", "Paradoks Jevonsa",
               why="Klienci skupiają się na cenie początkowej i nie czytają warunków."),
             LB("Ile klient zapłaci za 24 miesiące (6 · 29 zł + 18 · 79 zł)?",
                1596, "6*29+18*79", ["6 · 29 = 174 zł", "18 · 79 = 1422 zł", "Razem: 1596 zł (średnio 66,50 zł/mies.)"], unit="zł"),
             PF("Sprawa może być przedmiotem postępowania UOKiK w sprawie praktyk naruszających zbiorowe interesy konsumentów.", True,
                why="Dotyczy wielu konsumentów i może wprowadzać w błąd."),
          ),
          PR("Sklep internetowy przy każdym produkcie wyświetla „Tylko 2 sztuki w magazynie!” i „15 osób ogląda teraz ten produkt”, choć komunikaty są losowe.",
             W("Jakie błędy poznawcze wykorzystują komunikaty?",
               "Presję niedoboru i społeczny dowód słuszności (owczy pęd)", "Efekt Giffena", "Prawo Engla",
               why="Rzadkość i zachowanie innych skłaniają do szybkich zakupów."),
             PF("Fałszywe informacje o dostępności mogą być uznane za praktykę wprowadzającą w błąd.", True,
                why="Wpływają na decyzje konsumentów na podstawie nieprawdziwych danych."),
             W("Jak takie praktyki szkodzą konkurencji?",
               "Uczciwe sklepy tracą klientów na rzecz stosujących sztuczki", "Zwiększają konkurencję jakościową", "Nie wpływają na rynek",
               why="Nagradzanie manipulacji odwraca bodźce rynkowe."),
          ),
      ]),
]
