# -*- coding: utf-8 -*-
# Zrozumienie – Mikroekonomia / Elastyczność i rodzaje dóbr
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S51 = S("OpenStax, Principles of Economics 3e, 5.1 Price Elasticity of Demand and Supply", OS3 + "5-1-price-elasticity-of-demand-and-price-elasticity-of-supply", D)
S52 = S("OpenStax, Principles of Economics 3e, 5.2 Polar Cases of Elasticity", OS3 + "5-2-polar-cases-of-elasticity-and-constant-elasticity", D)
S53 = S("OpenStax, Principles of Economics 3e, 5.3 Elasticity and Pricing", OS3 + "5-3-elasticity-and-pricing", D)
S54 = S("OpenStax, Principles of Economics 3e, 5.4 Elasticity in Areas Other Than Price", OS3 + "5-4-elasticity-in-areas-other-than-price", D)
S62 = S("OpenStax, Principles of Economics 3e, 6.2 Changes in Income and Prices", OS3 + "6-2-how-changes-in-income-and-prices-affect-consumption-choices", D)

EL51 = S("OpenStax, Principles of Economics 3e, 5.1 Price Elasticity of Demand and Price Elasticity of Supply", OS3 + "5-1-price-elasticity-of-demand-and-price-elasticity-of-supply", D)
EL52 = S("OpenStax, Principles of Economics 3e, 5.2 Polar Cases of Elasticity and Constant Elasticity", OS3 + "5-2-polar-cases-of-elasticity-and-constant-elasticity", D)
EL53 = S("OpenStax, Principles of Economics 3e, 5.3 Elasticity and Pricing", OS3 + "5-3-elasticity-and-pricing", D)

LESSONS = [
    L(1, "Elastyczność cenowa popytu: jak mocno reagują kupujący",
      "Liczyć elastyczność cenową popytu (także metodą punktu środkowego), interpretować jej wartość i wyjaśniać, od czego zależy.",
      ["Elastyczność cenowa popytu", "Czynniki elastyczności popytu", "Popyt doskonale elastyczny / doskonale nieelastyczny"],
      [S51, S52],
      explain=[
          K("Elastyczność to wrażliwość",
            "Elastyczność cenowa popytu mówi, o ile procent zmieni się kupowana ilość, gdy cena zmieni się o 1%. Używamy procentów, a nie sztuk czy złotych, żeby porównywać różne dobra – litry mleka i samochody.",
            w="Ep = (% zmiany ilości) / (% zmiany ceny)"),
          K("Jak czytać wynik",
            "Elastyczność popytu jest zwykle ujemna (cena w górę, ilość w dół), dlatego często porównuje się wartość bezwzględną. |E| > 1 – popyt elastyczny (ilość reaguje silniej niż cena), |E| < 1 – nieelastyczny, |E| = 1 – jednostkowy. Skrajności: |E| = 0 (doskonale nieelastyczny), |E| → ∞ (doskonale elastyczny)."),
          W("Cena wzrosła o 10%, a kupowana ilość spadła o 25%. Jaki jest popyt?",
            "Elastyczny (|E| = 2,5)", "Nieelastyczny (|E| = 0,4)", "Jednostkowy", "Doskonale nieelastyczny",
            why="|E| = 25% / 10% = 2,5 > 1."),
          K("Metoda punktu środkowego",
            "Procent zmiany zależy od tego, czy liczymy od wartości początkowej, czy końcowej. Metoda punktu środkowego (łukowa) dzieli zmianę przez średnią obu wartości – wynik jest taki sam niezależnie od kierunku zmiany.",
            w="E = [(Q₂ − Q₁) / ((Q₁ + Q₂)/2)] / [(P₂ − P₁) / ((P₁ + P₂)/2)]"),
          K("Od czego zależy elastyczność",
            "Popyt jest bardziej elastyczny, gdy: istnieje wiele bliskich substytutów, dobro jest luksusem, a nie koniecznością, stanowi dużą część budżetu, rynek jest wąsko zdefiniowany (konkretna marka, a nie „napoje”) i gdy mamy więcej czasu na dostosowanie."),
          PF("Popyt na benzynę jest zwykle bardziej elastyczny w długim okresie niż w krótkim.", True,
             why="Z czasem można zmienić samochód, miejsce pracy czy środek transportu – więcej możliwości dostosowania."),
      ],
      mech=[
          KT("Popyt raczej elastyczny czy nieelastyczny?",
             {"Raczej elastyczny": ["Konkretna marka płatków śniadaniowych", "Wycieczki zagraniczne", "Bilety do kina przy wielu serwisach streamingowych"],
              "Raczej nieelastyczny": ["Insulina dla diabetyka", "Sól kuchenna", "Prąd w krótkim okresie"]},
             why="Substytuty, luksusowość i udział w budżecie zwiększają elastyczność; konieczność i brak substytutów ją zmniejszają."),
          W("Dlaczego popyt na „żywność” jest mniej elastyczny niż popyt na „jabłka odmiany Ligol”?",
            "Wąsko zdefiniowane dobro ma więcej substytutów", "Jabłka są luksusem", "Żywność jest tańsza",
            why="Ligol łatwo zastąpić inną odmianą; żywności jako całości – nie."),
          LN("Ułóż, dlaczego pojawienie się tanich linii lotniczych zwiększyło elastyczność popytu na bilety kolejowe na długich trasach.",
             ["Pojawia się bliski substytut – tani samolot", "Pasażerowie mają realną alternatywę", "Wzrost ceny biletu kolejowego skłania więcej osób do zmiany", "Popyt na kolej reaguje silniej na cenę"],
             why="Dostępność substytutów to główny czynnik elastyczności."),
          W("Popyt na dobro opisuje pionowa krzywa. Co to oznacza?",
            "Popyt doskonale nieelastyczny – ilość nie zależy od ceny", "Popyt doskonale elastyczny", "Popyt jednostkowy",
            why="Pionowa linia: przy każdej cenie kupowana jest ta sama ilość, |E| = 0."),
          PF("Wzdłuż liniowej (prostej) krzywej popytu elastyczność jest wszędzie taka sama.", False,
             why="Na prostej nachylenie jest stałe, ale elastyczność zmienia się: wysoka przy wysokich cenach, niska przy niskich."),
          M("Które czynniki zwiększają elastyczność cenową popytu?",
            ["Wiele bliskich substytutów", "Duży udział wydatku w budżecie", "Dobro pierwszej potrzeby", "Długi czas na dostosowanie"],
            [0, 1, 3],
            why="Dobra pierwszej potrzeby mają popyt mniej elastyczny."),
      ],
      calc=[
          LB("Cena biletu wzrosła o 8%, a sprzedaż spadła o 12%. Ile wynosi |Ep|?",
             1.5, "12/8", ["|E| = 12% / 8% = 1,5 – popyt elastyczny"], unit=""),
          LB("Cena wzrosła z 10 zł do 12 zł, a ilość spadła ze 100 do 80. Oblicz |Ep| metodą punktu środkowego.",
             1.22, "abs(((80-100)/90)/((12-10)/11))", ["%ΔQ = −20 / 90 ≈ −22,2%", "%ΔP = 2 / 11 ≈ 18,2%", "|E| ≈ 22,2 / 18,2 ≈ 1,22"], unit="", tol=0.01),
          LB("Ten sam przykład (10→12 zł, 100→80 szt.) policzony od wartości początkowych. Ile wynosi |E|?",
             1.0, "abs((-20/100)/(2/10))", ["%ΔQ = −20%", "%ΔP = +20%", "|E| = 1,0 – inny wynik niż metodą punktu środkowego"], unit=""),
          LB("|Ep| dla papierosów wynosi 0,4. O ile procent spadnie sprzedaż po podwyżce ceny o 15%?",
             6, "0.4*15", ["%ΔQ = E · %ΔP = 0,4 · 15% = 6%"], unit="%"),
          LB("Popyt: Q = 200 − 4P. Oblicz |E| w punkcie P = 30 (wzór punktowy E = −b·P/Q).",
             1.5, "4*30/(200-4*30)", ["Q = 200 − 120 = 80", "|E| = 4 · 30 / 80 = 1,5"], unit=""),
          LB("Dla tego samego popytu (Q = 200 − 4P) przy jakiej cenie |E| = 1?",
             25, "200/(2*4)", ["|E| = 1 ⇔ 4P = 200 − 4P", "8P = 200 ⇒ P = 25 zł (środek liniowej krzywej)"], unit="zł"),
      ],
      case=[
          PR("Kino w małym mieście jest jedynym w promieniu 40 km. Właściciel zauważył, że po podwyżce cen biletów z 20 zł do 22 zł liczba widzów w tygodniu spadła z 1000 do 950. Kino w dużym mieście, otoczone konkurencją, po takiej samej podwyżce straciło 30% widzów.",
             LB("Ile wynosi |E| dla kina w małym mieście (od wartości początkowych)?",
                0.5, "(50/1000)/(2/20)", ["%ΔQ = 5%", "%ΔP = 10%", "|E| = 0,5 – popyt nieelastyczny"], unit=""),
             LB("Ile wynosi |E| dla kina w dużym mieście (−30% widzów przy +10% ceny)?",
                3, "30/10", ["|E| = 30 / 10 = 3 – popyt bardzo elastyczny"], unit=""),
             W("Co najlepiej wyjaśnia różnicę?",
               "Liczba substytutów – w dużym mieście są inne kina i rozrywki", "Różnica w jakości filmów", "Inna cena biletu",
               why="Brak konkurencji czyni popyt mniej wrażliwym na cenę."),
          ),
          PR("Szacunki dla akcyzy na alkohol: krótkookresowa elastyczność popytu |E| ≈ 0,5, ale wśród młodzieży (mniejsze dochody, mniej przyzwyczajeń) |E| ≈ 1,2.",
             W("W której grupie podwyżka cen silniej ograniczy spożycie?",
               "Wśród młodzieży", "Wśród dorosłych", "Tak samo w obu",
               why="Wyższa elastyczność oznacza silniejszą reakcję ilości na cenę."),
             LB("O ile procent spadnie spożycie młodzieży po wzroście cen o 10%?",
                12, "1.2*10", ["1,2 · 10% = 12%"], unit="%"),
             PF("Niska elastyczność popytu wśród dorosłych oznacza, że akcyza przyniesie stosunkowo duże wpływy do budżetu.", True,
                why="Ilość spada niewiele, więc baza podatkowa pozostaje duża."),
          ),
      ]),

    L(2, "Elastyczność a przychód – kiedy obniżka ceny się opłaca",
      "Przewidywać, jak zmiana ceny wpłynie na utarg sprzedawcy w zależności od elastyczności popytu, i stosować to do decyzji cenowych.",
      ["Elastyczność a utarg", "Elastyczność cenowa popytu", "Utarg (przychód) całkowity, przeciętny i krańcowy"],
      [S53, S51],
      explain=[
          K("Dwa efekty zmiany ceny",
            "Podwyżka ceny ma dwa skutki dla przychodu (P · Q): każda sprzedana sztuka przynosi więcej (efekt ceny), ale sprzedaje się mniej sztuk (efekt ilości). Który efekt przeważy, zależy od elastyczności popytu."),
          K("Reguła elastyczności",
            "Popyt elastyczny (|E| > 1): podwyżka obniża przychód, obniżka go zwiększa. Popyt nieelastyczny (|E| < 1): podwyżka zwiększa przychód, obniżka go zmniejsza. Popyt jednostkowy (|E| = 1): przychód się nie zmienia – jest maksymalny."),
          W("Popyt na produkt jest nieelastyczny. Firma chce zwiększyć przychód. Co zrobić?",
            "Podnieść cenę", "Obniżyć cenę", "Cena nie ma wpływu na przychód",
            why="Przy |E| < 1 ilość spada procentowo mniej, niż rośnie cena."),
          K("Paradoks urodzaju",
            "Gdy rolnicy mają rekordowe zbiory, podaż rośnie, a ceny spadają. Ponieważ popyt na żywność jest nieelastyczny, ceny spadają procentowo bardziej, niż rośnie sprzedaż – przychody rolników jako grupy maleją, mimo że wyprodukowali więcej."),
          K("Przychód na liniowej krzywej popytu",
            "Przy wysokich cenach popyt jest elastyczny – obniżka zwiększa przychód. W środku krzywej |E| = 1 – przychód jest największy. Przy niskich cenach popyt jest nieelastyczny – dalsze obniżki zmniejszają przychód."),
          PF("Przychód jest największy w punkcie, w którym elastyczność popytu jest jednostkowa.", True,
             why="Wtedy niewielka zmiana ceny nie zmienia przychodu – to szczyt funkcji P · Q."),
      ],
      mech=[
          LN("Ułóż paradoks urodzaju.",
             ["Rekordowe zbiory zboża", "Podaż przesuwa się w prawo", "Cena spada silnie, bo popyt jest nieelastyczny",
              "Ilość sprzedana rośnie procentowo mniej, niż spada cena", "Łączny przychód rolników spada"],
             why="Przy nieelastycznym popycie spadek ceny przeważa nad wzrostem ilości."),
          KT("Jak zmieni się przychód sprzedawcy?",
             {"Wzrośnie": ["Podwyżka ceny przy |E| = 0,3", "Obniżka ceny przy |E| = 2", "Podwyżka ceny leku bez zamienników"],
              "Spadnie": ["Podwyżka ceny przy |E| = 1,8", "Obniżka ceny przy |E| = 0,4", "Podwyżka ceny jednej z wielu marek wody"]},
             why="Przy |E| > 1 przychód zmienia się przeciwnie do ceny, przy |E| < 1 – zgodnie z ceną."),
          W("Muzeum podniosło ceny biletów, a przychody spadły. Co to mówi o popycie?",
            "Był elastyczny", "Był nieelastyczny", "Był jednostkowy",
            why="Spadek przychodu po podwyżce oznacza, że ilość spadła procentowo bardziej niż wzrosła cena."),
          W("Zarząd metra rozważa obniżkę cen biletów, żeby zwiększyć przychody. Kiedy ma to sens?",
            "Gdy popyt na przejazdy jest elastyczny", "Gdy popyt jest nieelastyczny", "Zawsze",
            why="Obniżka zwiększa przychód tylko przy |E| > 1."),
          PF("Jeśli obniżka ceny zwiększa liczbę sprzedanych sztuk, to zawsze zwiększa przychód.", False,
             why="Przy nieelastycznym popycie ilość rośnie za mało, by zrekompensować niższą cenę."),
          M("Które sytuacje są przykładami wykorzystania wiedzy o elastyczności?",
            ["Tańsze bilety dla studentów (bardziej wrażliwych na cenę)", "Wysoka akcyza na paliwa", "Losowe ustalanie cen", "Promocje „happy hours” poza szczytem"],
            [0, 1, 3],
            why="Różnicowanie cen i podatki często celują w grupy o różnej elastyczności."),
      ],
      calc=[
          LB("Cena 20 zł, sprzedaż 500 szt. Po podwyżce do 22 zł sprzedaż spadła do 480. O ile zł zmienił się przychód (ze znakiem)?",
             560, "22*480-20*500", ["Przed: 20 · 500 = 10 000 zł", "Po: 22 · 480 = 10 560 zł", "Zmiana: +560 zł – popyt nieelastyczny"], unit="zł"),
          LB("Cena 50 zł, sprzedaż 200 szt. Po obniżce do 40 zł sprzedaż wzrosła do 300. O ile zł zmienił się przychód?",
             2000, "40*300-50*200", ["Przed: 10 000 zł", "Po: 12 000 zł", "+2000 zł – popyt elastyczny"], unit="zł"),
          LB("Popyt: Q = 100 − 2P. Przy jakiej cenie przychód jest największy?",
             25, "100/(2*2)", ["TR = P(100 − 2P) = 100P − 2P²", "Maksimum: 100 − 4P = 0 ⇒ P = 25 zł"], unit="zł"),
          LB("Ile wynosi ten maksymalny przychód (Q = 100 − 2P, P = 25)?",
             1250, "25*(100-2*25)", ["Q = 50", "TR = 25 · 50 = 1250 zł"], unit="zł"),
          LB("|E| = 0,2. Rolnicy zebrali o 10% więcej zboża, które w całości sprzedają. O ile procent (w przybliżeniu) spadnie cena?",
             50, "10/0.2", ["%ΔP = %ΔQ / |E| = 10% / 0,2 = 50%", "Przychód: 1,1 · 0,5 ≈ 0,55 – spadek o ok. 45%"], unit="%"),
          LB("Bilet kosztuje 40 zł, sprzedaje się 1000 sztuk, |E| = 1,5. O ile procent spadnie sprzedaż po podwyżce o 10%?",
             15, "1.5*10", ["%ΔQ = 1,5 · 10% = 15%", "Przychód: 1,1 · 0,85 = 0,935 – spadek o 6,5%"], unit="%"),
      ],
      case=[
          PR("Teatr miejski sprzedaje 300 biletów po 60 zł na każdy spektakl, a sala ma 500 miejsc. Badanie pokazało, że po obniżce ceny do 45 zł sprzedawałby 450 biletów.",
             LB("Jaki byłby przychód z jednego spektaklu po obniżce?",
                20250, "45*450", ["45 · 450 = 20 250 zł (wcześniej 18 000 zł)"], unit="zł"),
             W("Jaki jest popyt na bilety w tym przedziale cen?",
               "Elastyczny – obniżka zwiększa przychód", "Nieelastyczny", "Jednostkowy",
               why="Przychód wzrósł po obniżce ceny, więc |E| > 1."),
             PF("Ponieważ koszt dodatkowego widza przy wolnych miejscach jest prawie zerowy, obniżka zwiększa także zysk teatru.", True,
                why="Wzrost przychodu przy niemal stałych kosztach przekłada się na wyższy zysk."),
          ),
          PR("Rząd chce zwiększyć wpływy z akcyzy. Rozważa podwyżkę na papierosy (|E| ≈ 0,4) albo na napoje słodzone (|E| ≈ 1,2). Celem jest też ograniczenie spożycia szkodliwych produktów.",
             W("Która podwyżka da większy przyrost wpływów przy tej samej stawce?",
               "Na papierosy – ilość spadnie mniej", "Na napoje słodzone", "Obie dadzą tyle samo",
               why="Przy nieelastycznym popycie baza podatkowa maleje niewiele."),
             W("Która podwyżka silniej ograniczy spożycie?",
               "Na napoje słodzone – popyt jest bardziej elastyczny", "Na papierosy", "Żadna",
               why="Wyższa elastyczność oznacza silniejszą reakcję ilości."),
             PF("Cele „duże wpływy” i „duży spadek spożycia” mogą być ze sobą sprzeczne.", True,
                why="Duży spadek spożycia oznacza mniejszą bazę podatkową, a więc niższe wpływy."),
          ),
      ]),

    L(3, "Dochód i ceny innych dóbr: elastyczność dochodowa i krzyżowa",
      "Klasyfikować dobra na podstawie elastyczności dochodowej (normalne, luksusowe, niższego rzędu) i krzyżowej (substytuty, komplementy) oraz przewidywać zmiany popytu.",
      ["Elastyczność dochodowa popytu", "Elastyczność mieszana (krzyżowa) popytu", "Substytuty", "Dobra komplementarne",
       "Dobro normalne", "Dobro luksusowe (wyższego rzędu)", "Dobro niższego rzędu (podrzędne)"],
      [S54, S62],
      explain=[
          K("Elastyczność dochodowa",
            "Mówi, o ile procent zmienia się popyt, gdy dochód rośnie o 1%. Dodatnia – dobro normalne; powyżej 1 – dobro luksusowe (wydatki na nie rosną szybciej niż dochód); między 0 a 1 – dobro podstawowe; ujemna – dobro niższego rzędu.",
            w="Ed = % zmiany popytu / % zmiany dochodu"),
          K("Elastyczność krzyżowa",
            "Mówi, o ile procent zmienia się popyt na dobro X, gdy cena dobra Y rośnie o 1%. Dodatnia – substytuty (droższa kawa → więcej herbaty). Ujemna – komplementy (droższe drukarki → mniej tuszu). Bliska zeru – dobra niezależne.",
            w="Exy = % zmiany popytu na X / % zmiany ceny Y"),
          W("Dochody wzrosły o 10%, a popyt na rejsy wycieczkowe o 25%. Czym są rejsy?",
            "Dobrem luksusowym (Ed = 2,5)", "Dobrem niższego rzędu", "Dobrem podstawowym", "Komplementem",
            why="Ed > 1 oznacza dobro luksusowe."),
          K("Prawo Engla",
            "Wraz ze wzrostem dochodu udział wydatków na żywność w budżecie gospodarstwa maleje, choć kwotowo wydaje się na nią więcej. To dlatego żywność ma elastyczność dochodową między 0 a 1."),
          K("To zależy od dochodu i grupy",
            "To samo dobro może być luksusowe dla osób o niskich dochodach i podstawowe dla zamożnych. Komunikacja miejska bywa dobrem niższego rzędu: gdy rośnie dochód, część ludzi przesiada się do samochodów."),
          PF("Jeśli elastyczność krzyżowa masła względem ceny margaryny jest dodatnia, to są to substytuty.", True,
             why="Droższa margaryna zwiększa popyt na masło – dobra zastępują się nawzajem."),
      ],
      mech=[
          KT("Jakim dobrem jest X?",
             {"Luksusowe (Ed > 1)": ["Dochód +5%, popyt +12%", "Dochód +10%, popyt +18%"],
              "Podstawowe (0 < Ed < 1)": ["Dochód +10%, popyt +3%", "Dochód +5%, popyt +2%"],
              "Niższego rzędu (Ed < 0)": ["Dochód +10%, popyt −4%", "Dochód −5%, popyt +3%"]},
             why="Znak i wielkość elastyczności dochodowej wyznaczają rodzaj dobra."),
          KT("Substytuty czy komplementy?",
             {"Substytuty (Exy > 0)": ["Masło i margaryna", "Pociąg i autobus na tej samej trasie", "Netflix i kino"],
              "Komplementy (Exy < 0)": ["Konsola i gry", "Samochód i paliwo", "Drukarka i tusz"]},
             why="Substytuty się zastępują, komplementy używa się razem."),
          W("Rośnie cena konsoli do gier. Co dzieje się z popytem na gry do tej konsoli?",
            "Maleje – to komplementy", "Rośnie – to substytuty", "Nie zmienia się",
            why="Mniej osób kupuje konsolę, więc potrzebuje mniej gier."),
          LN("Ułóż skutki recesji dla taniego dyskontu spożywczego.",
             ["Dochody gospodarstw domowych spadają", "Ludzie rezygnują z droższych sklepów i marek",
              "Rośnie popyt na produkty dyskontowe (dobra niższego rzędu)", "Sprzedaż dyskontu rośnie mimo kryzysu"],
             why="Dla dóbr niższego rzędu spadek dochodu zwiększa popyt."),
          PF("Dobro luksusowe to po prostu dobro drogie.", False,
             why="Kryterium jest reakcja popytu na dochód (Ed > 1), a nie cena – tanie dobro też może być luksusowe dla danej grupy."),
          M("Które zdania są prawdziwe?",
            ["Udział żywności w budżecie maleje, gdy rośnie dochód", "Dobro niższego rzędu ma ujemną elastyczność dochodową",
             "Komplementy mają dodatnią elastyczność krzyżową", "To samo dobro może być luksusowe dla jednej grupy i podstawowe dla innej"],
            [0, 1, 3],
            why="Komplementy mają UJEMNĄ elastyczność krzyżową."),
      ],
      calc=[
          LB("Dochód wzrósł o 4%, a popyt na usługi fryzjerskie o 6%. Ile wynosi Ed?",
             1.5, "6/4", ["Ed = 6% / 4% = 1,5 – dobro luksusowe"], unit=""),
          LB("Cena kawy wzrosła o 20%, a popyt na herbatę o 5%. Ile wynosi elastyczność krzyżowa?",
             0.25, "5/20", ["Exy = 5% / 20% = 0,25 > 0 – substytuty"], unit=""),
          LB("Cena biletów lotniczych wzrosła o 10%, a liczba wynajętych samochodów na lotniskach spadła o 4%. Ile wynosi Exy (ze znakiem)?",
             -0.4, "-4/10", ["Exy = −4% / 10% = −0,4 < 0 – komplementy"], unit=""),
          LB("Ed dla mięsa wynosi 0,6. O ile procent wzrośnie popyt, gdy dochody wzrosną o 5%?",
             3, "0.6*5", ["0,6 · 5% = 3%"], unit="%"),
          LB("Rodzina zarabia 6000 zł i wydaje 1800 zł na żywność. Dochód wzrasta o 20%, a Ed żywności = 0,5. Jaki będzie udział żywności w budżecie (w %)?",
             27.5, "1800*1.1/(6000*1.2)*100", ["Nowy dochód: 7200 zł", "Wydatki: 1800 · (1 + 0,5 · 20%) = 1980 zł", "Udział: 1980 / 7200 = 27,5% (wcześniej 30%)"], unit="%", tol=0.05),
          LB("Ed komunikacji miejskiej = −0,3. O ile procent zmieni się popyt, gdy dochody wzrosną o 10% (ze znakiem)?",
             -3, "-0.3*10", ["−0,3 · 10% = −3% – dobro niższego rzędu"], unit="%"),
      ],
      case=[
          PR("Sieć restauracji ma dwie marki: tani bar mleczny i elegancką restaurację. Prognoza mówi o wzroście realnych dochodów o 6% w przyszłym roku. Szacunki: Ed baru = −0,5, Ed restauracji = 2.",
             LB("O ile procent zmieni się popyt w restauracji?",
                12, "2*6", ["2 · 6% = 12%"], unit="%"),
             LB("O ile procent zmieni się popyt w barze (ze znakiem)?",
                -3, "-0.5*6", ["−0,5 · 6% = −3%"], unit="%"),
             W("Co sieć powinna zrobić, przygotowując się na recesję zamiast wzrostu?",
               "Rozwijać bar mleczny – popyt na dobra niższego rzędu rośnie przy spadku dochodów", "Rozwijać restaurację", "Zamknąć obie marki",
               why="Przy spadku dochodu popyt na dobra niższego rzędu rośnie, na luksusowe – spada mocno."),
          ),
          PR("Producent drukarek sprzedaje je poniżej kosztów, a zarabia na tuszach. Konkurent zaczął sprzedawać tanie zamienniki tuszu pasujące do tych drukarek.",
             W("Jaka jest relacja drukarek i oryginalnych tuszy?",
               "Komplementy", "Substytuty", "Dobra niezależne",
               why="Drukarki i tusze używa się razem."),
             W("Jaka jest relacja oryginalnych tuszy i zamienników?",
               "Substytuty – tańszy zamiennik zmniejsza popyt na oryginał", "Komplementy", "Dobra niższego rzędu",
               why="Zamiennik zaspokaja tę samą potrzebę."),
             PF("Pojawienie się tanich zamienników zwiększa elastyczność cenową popytu na oryginalne tusze.", True,
                why="Więcej bliskich substytutów oznacza silniejszą reakcję na cenę."),
          ),
      ]),

    L(4, "Elastyczność podaży i rola czasu",
      "Liczyć i interpretować elastyczność cenową podaży, rozumieć, dlaczego rośnie z czasem, i stosować to do analizy szoków cenowych.",
      ["Elastyczność cenowa podaży", "Popyt doskonale elastyczny / doskonale nieelastyczny", "Funkcja o stałej elastyczności"],
      [S51, S52],
      explain=[
          K("Elastyczność podaży",
            "Mówi, o ile procent zmienia się oferowana ilość, gdy cena rośnie o 1%. Zwykle jest dodatnia. Es > 1 – podaż elastyczna, Es < 1 – nieelastyczna.",
            w="Es = % zmiany wielkości podaży / % zmiany ceny"),
          K("Czas to klucz",
            "W bardzo krótkim okresie (dzień, tydzień) firmy mogą tylko sprzedać to, co mają – podaż jest prawie pionowa. W krótkim okresie mogą zwiększyć zmiany i nadgodziny. W długim – budują nowe zakłady, a nowe firmy wchodzą na rynek: podaż staje się bardzo elastyczna."),
          W("Która podaż jest najmniej elastyczna?",
            "Podaż mieszkań w centrum miasta w ciągu miesiąca", "Podaż długopisów w ciągu roku", "Podaż aplikacji mobilnych",
            why="Budowa mieszkań trwa latami, a ziemi w centrum nie przybywa."),
          K("Inne czynniki elastyczności podaży",
            "Podaż jest bardziej elastyczna, gdy są wolne moce produkcyjne, łatwo przechowywać zapasy, czynniki produkcji można łatwo przenieść z innych zastosowań i gdy łatwo wejść na rynek."),
          K("Przypadki skrajne",
            "Podaż doskonale nieelastyczna (pionowa): obraz Rembrandta, ziemia w danym miejscu – całość zmiany popytu idzie w cenę. Podaż doskonale elastyczna (pozioma): dobra produkowane przy stałym koszcie w dowolnej ilości – zmiana popytu zmienia tylko ilość."),
          PF("Przy pionowej krzywej podaży wzrost popytu podnosi tylko cenę, nie zmieniając ilości.", True,
             why="Ilości nie da się zwiększyć, więc cała zmiana przechodzi w cenę."),
      ],
      mech=[
          WY("Na koncert jest stała liczba miejsc, a zespół nagle staje się bardzo popularny. Co dzieje się z ceną i liczbą biletów?",
             G("sd", names={"D": "popyt na bilety", "S": "podaż biletów"}, D=1),
             "Rośnie głównie cena – liczba miejsc jest prawie stała", "Rośnie głównie liczba biletów", "Cena spada", "Nic się nie zmienia",
             why="Przy bardzo nieelastycznej podaży wzrost popytu przekłada się na cenę (na wykresie podaż jest pochylona, ale w praktyce prawie pionowa)."),
          KT("Podaż w danym okresie raczej elastyczna czy nieelastyczna?",
             {"Elastyczna": ["Koszulki z nadrukiem w ciągu roku", "Usługi programistyczne online w długim okresie", "Ołówki w fabryce z wolnymi mocami"],
              "Nieelastyczna": ["Truskawki w środku sezonu w ciągu tygodnia", "Mieszkania w centrum w ciągu roku", "Bilety na mecz finałowy"]},
             why="Czas, moce produkcyjne i możliwość przechowywania decydują o elastyczności podaży."),
          LN("Ułóż, jak rynek mieszkań reaguje na wzrost popytu w czasie.",
             ["Popyt na mieszkania nagle rośnie", "W krótkim okresie podaż jest sztywna – ceny mocno rosną",
              "Wysokie ceny zachęcają deweloperów do nowych inwestycji", "Po kilku latach podaż rośnie", "Wzrost cen wyhamowuje"],
             why="Podaż staje się bardziej elastyczna w miarę upływu czasu."),
          W("Dlaczego ceny truskawek mogą się zmieniać nawet o kilkadziesiąt procent w ciągu tygodnia?",
            "Krótkookresowa podaż jest bardzo nieelastyczna (owoce szybko się psują)", "Popyt na truskawki jest doskonale elastyczny", "Truskawki są dobrem luksusowym",
            why="Nie da się szybko zwiększyć zbiorów ani długo przechowywać owoców."),
          PF("Im łatwiej przechowywać produkt, tym bardziej elastyczna jest jego podaż.", True,
             why="Zapasy pozwalają szybko reagować na zmianę ceny – sprzedać więcej lub wstrzymać sprzedaż."),
          M("Co zwiększa elastyczność podaży?",
            ["Wolne moce produkcyjne", "Łatwe wejście nowych firm", "Długi czas produkcji", "Możliwość przechowywania zapasów"],
            [0, 1, 3],
            why="Długi czas produkcji zmniejsza elastyczność."),
      ],
      calc=[
          LB("Cena wzrosła o 5%, a wielkość podaży o 15%. Ile wynosi Es?",
             3, "15/5", ["Es = 15% / 5% = 3 – podaż elastyczna"], unit=""),
          LB("Cena mieszkań wzrosła o 20%, a liczba oferowanych mieszkań w ciągu roku o 4%. Ile wynosi Es?",
             0.2, "4/20", ["Es = 4 / 20 = 0,2 – podaż bardzo nieelastyczna"], unit=""),
          LB("Podaż: Qs = −20 + 4P. Oblicz Es w punkcie P = 10 (Es = d · P / Q).",
             2, "4*10/(-20+4*10)", ["Q = −20 + 40 = 20", "Es = 4 · 10 / 20 = 2"], unit=""),
          LB("Cena wzrosła z 8 zł do 10 zł, a podaż z 400 do 600 sztuk. Oblicz Es metodą punktu środkowego.",
             1.8, "((600-400)/500)/((10-8)/9)", ["%ΔQ = 200 / 500 = 40%", "%ΔP = 2 / 9 ≈ 22,2%", "Es = 40 / 22,2 = 1,8"], unit="", tol=0.01),
          LB("Es = 0,5. O ile procent musi wzrosnąć cena, by producenci zaoferowali o 10% więcej?",
             20, "10/0.5", ["%ΔP = %ΔQ / Es = 10% / 0,5 = 20%"], unit="%"),
          LB("Podaż jednostkowo elastyczna (Es = 1). Cena rośnie o 7%. O ile procent wzrośnie wielkość podaży?",
             7, "1*7", ["1 · 7% = 7%"], unit="%"),
      ],
      case=[
          PR("Przed świętami popyt na karpie gwałtownie rośnie. Hodowcy odławiają ryby ze stawów przygotowywanych przez cały rok; liczby ryb nie da się zwiększyć w ciągu kilku tygodni.",
             W("Jaka jest podaż karpi w grudniu?",
               "Bardzo nieelastyczna", "Doskonale elastyczna", "Elastyczna",
               why="Hodowla trwa długo, więc w krótkim okresie ilości nie da się zwiększyć."),
             W("Co najlepiej wyjaśnia wysokie ceny karpi przed świętami?",
               "Wzrost popytu przy sztywnej podaży", "Spadek podaży w grudniu", "Spadek popytu",
               why="Przy nieelastycznej podaży wzrost popytu przekłada się głównie na cenę."),
             PF("Gdyby hodowcy mogli przechowywać żywe karpie od jesieni, grudniowy wzrost cen byłby mniejszy.", True,
                why="Możliwość przechowywania zwiększa elastyczność podaży w krótkim okresie."),
          ),
          PR("W ciągu roku popyt na maseczki ochronne wzrósł dziesięciokrotnie. W pierwszych tygodniach ceny wzrosły kilkukrotnie, ale po kilku miesiącach wiele firm przestawiło linie produkcyjne i ceny spadły prawie do poprzedniego poziomu.",
             W("Co zmieniło się po kilku miesiącach?",
               "Podaż stała się dużo bardziej elastyczna – wejście nowych producentów", "Popyt spadł do zera", "Rząd zakazał sprzedaży",
               why="W dłuższym okresie firmy mogą przestawić produkcję i wejść na rynek."),
             LB("Cena maseczki wzrosła z 1 zł do 5 zł. O ile procent (od wartości początkowej)?",
                400, "(5-1)/1*100", ["(5 − 1) / 1 · 100% = 400%"], unit="%"),
             W("Jak wyglądała krzywa podaży w pierwszych tygodniach?",
               "Prawie pionowa", "Prawie pozioma", "Opadająca",
               why="Bez nowych mocy produkcyjnych ilość mogła wzrosnąć tylko nieznacznie."),
          ),
      ]),

    L(5, "Nietypowe dobra: Giffen, Veblen, snobizm i owczy pęd",
      "Rozumieć wyjątki od prawa popytu i efekty społeczne w konsumpcji oraz odróżniać je od zwykłych przesunięć popytu.",
      ["Dobro Giffena", "Dobro Veblena (efekt Veblena)", "Efekt owczego pędu (efekt modny)", "Efekt snoba", "Dobra pozycyjne i wyścig pozycyjny", "Dobro niższego rzędu (podrzędne)"],
      [S62, S("OpenStax, Principles of Economics 3e, 6.3 Behavioral Economics", OS3 + "6-3-behavioral-economics-an-alternative-framework-for-consumer-choice", D),
       S("R. Jensen, N. Miller, Giffen Behavior and Subsistence Consumption, American Economic Review 98(4), 2008", "https://www.aeaweb.org/articles?id=10.1257/aer.98.4.1553", D)],
      explain=[
          K("Dobro Giffena – rzadki wyjątek",
            "Dobro Giffena to skrajny przypadek dobra niższego rzędu, które pochłania dużą część budżetu biednych gospodarstw. Gdy jego cena rośnie, ludzie stają się na tyle biedniejsi, że rezygnują z droższych produktów i kupują jeszcze WIĘCEJ tego taniego dobra. Krzywa popytu ma wtedy dodatnie nachylenie. W praktyce zdarza się bardzo rzadko."),
          K("Dobro Veblena – kupuję, bo drogie",
            "Thorstein Veblen opisał konsumpcję na pokaz: niektóre dobra (luksusowe zegarki, torebki) są pożądane właśnie dlatego, że są drogie – cena sygnalizuje status. Wzrost ceny może zwiększyć popyt w pewnym zakresie."),
          W("Czym różni się dobro Giffena od dobra Veblena?",
            "Giffen dotyczy biednych i taniego dobra (efekt dochodowy), Veblen – zamożnych i prestiżu (efekt statusu)",
            "Niczym, to synonimy",
            "Dobro Giffena jest luksusowe",
            why="Oba łamią prawo popytu, ale z zupełnie innych powodów."),
          K("Owczy pęd i snobizm",
            "Efekt owczego pędu: kupuję, bo inni kupują (moda, sieci społecznościowe) – popyt rynkowy jest bardziej elastyczny niż suma indywidualnych. Efekt snoba: tracę zainteresowanie, gdy produkt staje się powszechny – popyt rynkowy jest mniej elastyczny."),
          K("Dobra pozycyjne",
            "Wartość dóbr pozycyjnych zależy od pozycji względem innych (najlepsza szkoła, największy dom w okolicy). Gdy wszyscy wydają więcej, by „wyprzedzić” innych, nikt nie zyskuje pozycji – to wyścig pozycyjny, który może marnować zasoby."),
          PF("Jeśli po podwyżce ceny sprzedaż wzrosła, to na pewno jest to dobro Giffena.", False,
             why="Najczęściej po prostu jednocześnie wzrósł popyt (przesunięcie krzywej), np. przez modę lub dochody."),
      ],
      mech=[
          KT("Który efekt opisuje sytuacja?",
             {"Owczy pęd": ["Kupuję buty, bo noszą je wszyscy znajomi", "Gra staje się popularna, bo dużo osób już w nią gra"],
              "Efekt snoba": ["Przestaję nosić markę, gdy pojawia się w dyskontach", "Wybieram limitowaną edycję, bo mało kto ją ma"],
              "Efekt Veblena": ["Kupuję drogi zegarek, bo jego cena świadczy o statusie", "Restauracja podnosi ceny i ma więcej gości z „wyższych sfer”"]},
             why="Owczy pęd – naśladowanie; snob – wyróżnianie się rzadkością; Veblen – wyróżnianie się ceną."),
          LN("Ułóż mechanizm dobra Giffena.",
             ["Rośnie cena podstawowego, taniego produktu (np. ryżu)", "Biedne rodziny realnie biednieją",
              "Rezygnują z droższych produktów (mięso, warzywa)", "Brakujące kalorie uzupełniają tym samym tanim produktem", "Kupują go więcej mimo wyższej ceny"],
             why="Efekt dochodowy (silny przy dużym udziale w budżecie) przeważa nad efektem substytucyjnym."),
          W("Jak efekt owczego pędu wpływa na elastyczność popytu rynkowego?",
            "Zwiększa ją – spadek ceny przyciąga kupujących, co przyciąga kolejnych", "Zmniejsza ją", "Nie ma wpływu",
            why="Każdy nowy nabywca czyni produkt atrakcyjniejszym dla innych."),
          W("Rodzice w mieście wydają coraz więcej na korepetycje, by dzieci dostały się do najlepszego liceum, w którym liczba miejsc jest stała. Jakie zjawisko to ilustruje?",
            "Wyścig pozycyjny", "Dobro Giffena", "Efekt snoba",
            why="Liczy się pozycja względem innych, a liczba miejsc się nie zmienia – wydatki rosną, wynik ogólny nie."),
          PF("Dobro Veblena musi mieć bardzo wysoką cenę względem zwykłych substytutów.", True,
             why="Funkcja sygnalizacji statusu wymaga, by cena odróżniała produkt od zwykłych zamienników."),
          M("Które stwierdzenia o dobrach Giffena są prawdziwe?",
            ["Są dobrami niższego rzędu", "Stanowią dużą część budżetu biednych gospodarstw", "Są typowe dla dóbr luksusowych", "Ich krzywa popytu może być rosnąca"],
            [0, 1, 3],
            why="Dobra luksusowe to przeciwieństwo dóbr niższego rzędu."),
      ],
      calc=[
          LB("Rodzina ma 100 zł: kupuje 30 kg ryżu po 2 zł i 2 kg mięsa po 20 zł. Ryż drożeje do 2,5 zł. Ile pieniędzy zostanie jej na mięso, jeśli kupi 32 kg ryżu?",
             20, "100-32*2.5", ["Wydatek na ryż: 32 · 2,5 = 80 zł", "Na mięso: 100 − 80 = 20 zł (1 kg)"], unit="zł"),
          LB("W tym przykładzie: o ile procent wzrosła ilość kupowanego ryżu po podwyżce (30 → 32 kg)?",
             6.67, "(32-30)/30*100", ["2 / 30 · 100% ≈ 6,67% – mimo wzrostu ceny o 25%"], unit="%", tol=0.02),
          LB("Ile wynosi „elastyczność” popytu na ryż w tym przykładzie (ze znakiem; +6,67% ilości przy +25% ceny)?",
             0.27, "(2/30)/(0.5/2)", ["E = 6,67% / 25% ≈ +0,27 – dodatnia, jak dla dobra Giffena"], unit="", tol=0.01),
          LB("Torebka kosztowała 4000 zł, sprzedaż 500 szt. Po podwyżce do 5000 zł sprzedaż wzrosła do 550 szt. O ile zł wzrósł przychód?",
             750000, "5000*550-4000*500", ["Przed: 2 000 000 zł", "Po: 2 750 000 zł", "Wzrost: 750 000 zł"], unit="zł"),
          LB("Bez efektów społecznych przy obniżce ceny gry o 20% kupiłoby ją 1000 nowych osób. Owczy pęd dodaje 30% więcej nabywców. Ile osób kupi grę?",
             1300, "1000*1.3", ["1000 · 1,3 = 1300 osób"], unit="os."),
          LB("Dziesięcioro rodziców wydaje po 5000 zł na korepetycje, a miejsc w najlepszym liceum jest 5 – tyle samo jak bez korepetycji. Ile łącznie wydano „na wyścig”?",
             50000, "10*5000", ["10 · 5000 = 50 000 zł", "Liczba przyjętych się nie zmienia – to koszt wyścigu pozycyjnego"], unit="zł"),
      ],
      case=[
          PR("Badanie z prowincji Hunan w Chinach (Jensen i Miller, 2008): bardzo biednym rodzinom dopłacano do ryżu, czyli obniżano jego cenę. Część najuboższych rodzin kupowała wtedy MNIEJ ryżu, a więcej mięsa i warzyw.",
             W("Jak interpretować ten wynik?",
               "Ryż zachowywał się jak dobro Giffena: tańszy ryż „wzbogacał” rodziny, które przechodziły na lepszą żywność",
               "Ryż był dobrem luksusowym",
               "Rodziny nie lubiły ryżu",
               why="Spadek ceny zmniejszył popyt – odwrotnie niż prawo popytu – przez silny efekt dochodowy."),
             PF("Efekt dotyczył przede wszystkim rodzin bardzo biednych, dla których ryż stanowił dużą część wydatków.", True,
                why="Warunkiem efektu Giffena jest duży udział dobra w budżecie i niski dochód."),
             W("Dlaczego zamożniejsze rodziny nie wykazywały tego efektu?",
               "Ryż był dla nich małą częścią budżetu – efekt dochodowy był słaby", "Nie jadły ryżu", "Ryż był dla nich dobrem Veblena",
               why="Przy małym udziale w budżecie zmiana ceny słabo wpływa na dochód realny."),
          ),
          PR("Marka sneakersów wypuszcza limitowaną edycję po bardzo wysokiej cenie. Po roku robi tańszą, masową wersję tego samego modelu. Część dotychczasowych klientów przestaje kupować markę.",
             W("Jaki efekt tłumaczy odejście części klientów?",
               "Efekt snoba – produkt stał się zbyt powszechny", "Efekt Giffena", "Owczy pęd",
               why="Snob ceni rzadkość; masowa dostępność obniża dla niego wartość produktu."),
             W("Dlaczego limitowana edycja mogła się dobrze sprzedawać mimo wysokiej ceny?",
               "Efekt Veblena i rzadkość jako sygnał statusu", "Popyt był doskonale elastyczny", "Była dobrem niższego rzędu",
               why="Wysoka cena i ograniczona liczba sztuk zwiększały wartość sygnalizacyjną."),
             M("Jakie ryzyka ma strategia masowej wersji dla marki?",
               ["Utrata klientów dbających o wyjątkowość", "Osłabienie wizerunku luksusu", "Na pewno niższe łączne przychody", "Szybsze naśladowanie przez tańszych konkurentów"],
               [0, 1, 3],
               why="Przychody mogą wzrosnąć dzięki masowej sprzedaży – nie jest to pewne w żadną stronę."),
          ),
      ]),

    L(6, "Trzy zastosowania elastyczności: rolnictwo, OPEC i narkotyki",
      "Stosować elastyczność do wyjaśnienia paradoksu rolnictwa, nietrwałości wysokich cen ropy utrzymywanych przez kartel oraz skutków polityki antynarkotykowej.",
      ["Paradoks rolnictwa (dobra nowina dla rolnictwa – zła dla rolników)", "Elastyczność a polityka antynarkotykowa", "OPEC", "Elastyczność a utarg"],
      [EL53, EL51],
      explain=[
          K("Paradoks rolnictwa",
            "Nowa, wydajniejsza odmiana zboża przesuwa podaż w prawo. Popyt na żywność jest nieelastyczny, więc cena spada procentowo bardziej, niż rośnie ilość – łączne przychody rolników maleją. Postęp jest „dobrą nowiną dla rolnictwa” (i konsumentów), a „złą dla rolników”; tłumaczy to spadek zatrudnienia w rolnictwie.",
            g=G("sd", S=1)),
          K("Dlaczego OPEC nie utrzymał wysokich cen",
            "W latach 70. ograniczenie wydobycia gwałtownie podniosło ceny ropy, bo w krótkim okresie popyt i podaż są bardzo nieelastyczne. W długim okresie konsumenci kupowali oszczędniejsze auta i izolowali domy, a producenci spoza kartelu zwiększali wydobycie – elastyczności wzrosły i ceny spadły."),
          W("Rolnicy zbierają o 20% więcej zboża, a cena spada o 40%. Co z ich przychodem?",
            "Spada o ok. 28%", "Rośnie o 20%", "Nie zmienia się",
            why="1,2 · 0,6 = 0,72 → spadek o 28%."),
          K("Narkotyki: zakaz czy edukacja?",
            "Zakaz i ściganie przemytu przesuwają podaż w lewo. Przy nieelastycznym popycie cena rośnie bardziej, niż spada ilość – wydatki uzależnionych rosną, co może zwiększać przestępczość popełnianą w celu zdobycia pieniędzy. Edukacja i leczenie przesuwają popyt w lewo – spadają i cena, i ilość."),
          K("Ogólna lekcja",
            "Te same przesunięcia krzywych mają różne skutki w zależności od elastyczności i horyzontu czasu. W krótkim okresie popyt i podaż są zwykle mniej elastyczne niż w długim."),
          PF("Przy nieelastycznym popycie spadek podaży zwiększa łączne wydatki nabywców.", True,
             why="Cena rośnie procentowo bardziej, niż spada ilość."),
      ],
      mech=[
          WY("Nowa technologia nawadniania zwiększa plony pszenicy. Co z rynkiem pszenicy, jeśli popyt jest nieelastyczny?",
             G("sd", names={"D": "popyt na pszenicę", "S": "podaż pszenicy"}, S=1),
             "Ilość rośnie, cena spada silnie – przychody rolników maleją",
             "Cena rośnie, przychody rolników rosną",
             "Popyt rośnie, cena rośnie",
             why="Nieelastyczny popyt: duży spadek ceny przy małym wzroście ilości."),
          WY("Policja skutecznie ogranicza przemyt narkotyków. Co z rynkiem (popyt nieelastyczny)?",
             G("sd", names={"D": "popyt na narkotyki", "S": "podaż narkotyków"}, S=-1),
             "Cena rośnie silnie, ilość spada nieznacznie – wydatki uzależnionych rosną",
             "Cena i ilość spadają",
             "Popyt rośnie",
             why="Spadek podaży przy nieelastycznym popycie."),
          KT("Krótki czy długi okres na rynku ropy?",
             {"Krótki okres": ["Kierowcy nadal dojeżdżają do pracy tymi samymi autami", "Cena ropy gwałtownie skacze po ograniczeniu wydobycia"],
              "Długi okres": ["Konsumenci kupują oszczędniejsze samochody", "Producenci spoza kartelu zwiększają wydobycie", "Ceny wracają w dół"]},
             why="Elastyczność rośnie z czasem."),
          LN("Ułóż łańcuch skutków programu edukacji antynarkotykowej.",
             ["Kampanie edukacyjne i leczenie uzależnień", "Popyt na narkotyki maleje", "Cena i ilość spadają", "Mniej pieniędzy trafia do przestępców", "Spada przestępczość związana z narkotykami"],
             why="Polityka popytowa obniża i cenę, i ilość."),
          W("Dlaczego państwa wprowadzały programy ograniczania produkcji rolnej?",
            "Przy nieelastycznym popycie mniejsza podaż podnosi przychody rolników", "By obniżyć ceny żywności", "By zwiększyć eksport",
            why="Rolnicy jako grupa zyskują na mniejszej podaży."),
          M("Co sprawiło, że wysokie ceny ropy po działaniach OPEC nie utrzymały się?",
            ["Wzrost elastyczności popytu w długim okresie", "Zwiększenie wydobycia przez kraje spoza kartelu", "Oszczędzanie energii", "Spadek elastyczności popytu"], [0, 1, 2],
            why="Elastyczność wzrosła, a nie spadła."),
      ],
      calc=[
          LB("Zbiory rosną o 20%, cena spada o 40%. O ile procent zmienia się przychód rolników?",
             -28, "(1.2*0.6-1)*100", ["1,2 · 0,6 = 0,72 → −28%"], unit="%"),
          LB("Elastyczność popytu na ropę w krótkim okresie −0,1. O ile procent wzrośnie cena, jeśli podaż spadnie o 10%?",
             100, "10/0.1", ["%ΔP = 10% / 0,1 = 100%"], unit="%"),
          LB("W długim okresie elastyczność wynosi −0,5. O ile procent wzrośnie cena przy tym samym spadku podaży o 10%?",
             20, "10/0.5", ["10% / 0,5 = 20%"], unit="%"),
          LB("Zakaz podnosi cenę narkotyku o 50%, ilość spada o 20%. O ile procent zmieniają się wydatki?",
             20, "(1.5*0.8-1)*100", ["1,5 · 0,8 = 1,2 → +20%"], unit="%"),
          LB("Elastyczność popytu na zboże −0,3. O ile procent musi spaść cena, by sprzedać o 15% więcej?",
             50, "15/0.3", ["15% / 0,3 = 50%"], unit="%"),
          LB("Przychód rolników: 100 mln zł przed zmianą, ilość +10%, cena −25%. Ile wynosi po zmianie (mln zł)?",
             82.5, "100*1.1*0.75", ["100 · 1,1 · 0,75 = 82,5"], unit="mln zł", tol=0.001),
      ],
      case=[
          PR("W latach 1973–1974 kraje OPEC ograniczyły wydobycie, a cena ropy wzrosła kilkukrotnie. W latach 80. ceny spadły mimo prób utrzymania limitów.",
             W("Dlaczego w krótkim okresie cena wzrosła tak silnie?",
               "Popyt i podaż ropy były w krótkim okresie bardzo nieelastyczne", "Bo popyt był bardzo elastyczny", "Bo podaż wzrosła",
               why="Konsumenci nie mogli szybko zmienić zachowań."),
             W("Co przyczyniło się do spadku cen w latach 80.?",
               "Wzrost elastyczności popytu i podaży w długim okresie", "Wzrost liczby samochodów o dużym spalaniu", "Brak alternatyw",
               why="Oszczędzanie energii i wydobycie spoza OPEC."),
             PF("Kartelowi trudniej utrzymać wysokie ceny w długim okresie.", True,
                why="Rośnie elastyczność i pokusa łamania limitów."),
          ),
          PR("Rząd zastanawia się nad dwiema strategiami: zwiększyć budżet straży granicznej na walkę z przemytem narkotyków albo sfinansować programy profilaktyki i leczenia.",
             W("Jaki skutek może mieć pierwsza strategia przy nieelastycznym popycie?",
               "Wzrost cen i wydatków uzależnionych, potencjalnie więcej przestępstw", "Spadek cen", "Wzrost popytu",
               why="Podaż ↓ przy nieelastycznym popycie."),
             W("Jak działa druga strategia?",
               "Zmniejsza popyt – spadają cena i ilość", "Zwiększa podaż", "Podnosi ceny",
               why="Przesunięcie popytu w lewo."),
             PF("Obie strategie mogą się uzupełniać, a ich skutki zależą od elastyczności.", True,
                why="Analiza elastyczności pozwala przewidzieć efekty."),
          ),
      ]),

    L(7, "Metoda punktu środkowego i elastyczność wzdłuż prostej popytu",
      "Liczyć elastyczność metodą punktu środkowego, rozumieć, dlaczego elastyczność zmienia się wzdłuż liniowej krzywej popytu i jak wiąże się to z przychodem całkowitym.",
      ["Metoda punktu środkowego (elastyczność łukowa)", "Elastyczność wzdłuż liniowej krzywej popytu", "Elastyczność cenowa popytu"],
      [EL51, EL52],
      explain=[
          K("Problem zwykłego wzoru",
            "Liczone względem wartości początkowej zmiany procentowe dają inny wynik przy wzroście i spadku ceny: z 4 do 6 zł to +50%, a z 6 do 4 zł to −33%. Metoda punktu środkowego liczy zmiany względem średniej, więc wynik nie zależy od kierunku.",
            w="E = [ΔQ/((Q₁ + Q₂)/2)] / [ΔP/((P₁ + P₂)/2)]"),
          K("Przykład",
            "Cena rośnie z 4 do 6 zł, ilość spada ze 120 do 80. Zmiana ilości: −40 / 100 = −40%. Zmiana ceny: 2 / 5 = +40%. Elastyczność = −40% / 40% = −1 (jednostkowa) – przychód się nie zmienia (480 zł w obu przypadkach)."),
          W("Cena rośnie z 10 do 14 zł, ilość spada z 50 do 30. Ile wynosi elastyczność metodą punktu środkowego?",
            "−1,5", "−0,67", "−2,5",
            why="ΔQ% = −20/40 = −50%; ΔP% = 4/12 ≈ 33,3%; −50/33,3 = −1,5."),
          K("Elastyczność wzdłuż prostej",
            "Na liniowej krzywej popytu nachylenie jest stałe, ale elastyczność nie: |E| = (P/Q) · |ΔQ/ΔP|. Wysoko na krzywej (wysoka cena, mała ilość) popyt jest elastyczny, w połowie – jednostkowy, nisko – nieelastyczny. Przychód całkowity jest największy tam, gdzie |E| = 1.",
            w="|E| = (P / Q) · |ΔQ / ΔP|"),
          K("Wniosek praktyczny",
            "Ta sama firma może zarabiać więcej na obniżce ceny przy wysokich cenach (popyt elastyczny), a tracić przy niskich (nieelastyczny). Dlatego nie wystarczy znać nachylenie – trzeba znać miejsce na krzywej."),
          PF("Na liniowej krzywej popytu elastyczność jest w każdym punkcie taka sama.", False,
             why="Stałe jest nachylenie, a elastyczność zależy od P/Q."),
      ],
      mech=[
          KT("Popyt Q = 100 − P: elastyczny, jednostkowy czy nieelastyczny?",
             {"Elastyczny (|E| > 1)": ["P = 80, Q = 20", "P = 70, Q = 30"],
              "Jednostkowy (|E| = 1)": ["P = 50, Q = 50"],
              "Nieelastyczny (|E| < 1)": ["P = 20, Q = 80", "P = 10, Q = 90"]},
             why="|E| = P / Q przy nachyleniu 1."),
          LN("Ułóż obliczenie elastyczności metodą punktu środkowego.",
             ["Oblicz zmianę ilości i jej średnią", "Podziel zmianę ilości przez średnią – procentowa zmiana ilości", "Oblicz zmianę ceny i jej średnią", "Podziel zmianę ceny przez średnią – procentowa zmiana ceny", "Podziel procentową zmianę ilości przez procentową zmianę ceny"],
             why="Kolejne kroki metody łukowej."),
          W("Firma sprzedaje przy cenie, przy której popyt jest nieelastyczny. Co stanie się z przychodem po podwyżce ceny?",
            "Wzrośnie", "Spadnie", "Nie zmieni się",
            why="Ilość spada procentowo mniej, niż rośnie cena."),
          W("Dlaczego metoda punktu środkowego jest lepsza od liczenia względem wartości początkowej?",
            "Daje ten sam wynik przy wzroście i spadku ceny", "Zawsze daje wyższą elastyczność", "Nie wymaga danych o ilości",
            why="Średnia jest symetryczna względem kierunku zmiany."),
          M("Które twierdzenia o liniowej krzywej popytu są prawdziwe?",
            ["Nachylenie jest stałe", "Elastyczność maleje (co do wartości) przy spadku ceny", "Przychód jest maksymalny przy |E| = 1", "Elastyczność jest wszędzie równa 1"], [0, 1, 2],
            why="Elastyczność zmienia się wzdłuż prostej."),
          PF("Przy elastyczności jednostkowej zmiana ceny nie zmienia przychodu całkowitego.", True,
             why="Procentowe zmiany ceny i ilości się równoważą."),
      ],
      calc=[
          LB("Cena 4 → 6 zł, ilość 120 → 80. Ile wynosi elastyczność (wartość bezwzględna) metodą punktu środkowego?",
             1, "(40/100)/(2/5)", ["40% / 40% = 1"], unit="", tol=0.001),
          LB("Cena 10 → 14 zł, ilość 50 → 30. Ile wynosi |E| metodą punktu środkowego?",
             1.5, "(20/40)/(4/12)", ["50% / 33,3% = 1,5"], unit="", tol=0.001),
          LB("Popyt Q = 100 − P. Ile wynosi |E| przy P = 80?",
             4, "80/20", ["P / Q = 80 / 20 = 4"], unit="", tol=0.001),
          LB("Ile wynosi |E| przy P = 20?",
             0.25, "20/80", ["20 / 80 = 0,25"], unit="", tol=0.001),
          LB("Przy jakiej cenie przychód jest maksymalny dla Q = 100 − P?",
             50, "100/2", ["|E| = 1 przy P = Q = 50"], unit="zł"),
          LB("Ile wynosi wtedy maksymalny przychód?",
             2500, "50*50", ["50 · 50 = 2 500"], unit="zł"),
      ],
      case=[
          PR("Kino w małym mieście sprzedaje w tygodniu 300 biletów po 30 zł. Po obniżce ceny do 20 zł sprzedaje 500 biletów tygodniowo, a pozostałe warunki się nie zmieniły.",
             W("Ile wynosi elastyczność metodą punktu środkowego (co do wartości)?",
               "1,25", "0,8", "2",
               why="ΔQ% = 200/400 = 50%; ΔP% = 10/25 = 40%; 50/40 = 1,25."),
             W("Czy obniżka zwiększyła przychód?",
               "Tak – z 9 000 do 10 000 zł", "Nie – przychód spadł", "Przychód się nie zmienił",
               why="Popyt elastyczny: 300 · 30 = 9 000; 500 · 20 = 10 000."),
             PF("Popyt elastyczny oznacza, że obniżka ceny zwiększa przychód.", True,
                why="Ilość rośnie procentowo bardziej, niż spada cena."),
          ),
          PR("Zarząd metra rozważa podwyżkę biletu z 4 do 5 zł. Analityk ostrzega, że przy niskich cenach popyt jest nieelastyczny, ale przy 5 zł część pasażerów przesiądzie się na rowery.",
             W("Ile wynosi procentowa zmiana ceny metodą punktu środkowego?",
               "Ok. 22,2%", "25%", "20%",
               why="1 / 4,5 ≈ 22,2%."),
             W("Jeśli liczba pasażerów spadnie z 100 tys. do 95 tys., jaka jest elastyczność (co do wartości)?",
               "Ok. 0,23 – popyt nieelastyczny", "Ok. 2,3 – popyt elastyczny", "Dokładnie 1",
               why="ΔQ% = 5/97,5 ≈ 5,1%; 5,1 / 22,2 ≈ 0,23."),
             PF("Przy nieelastycznym popycie podwyżka zwiększy przychody metra.", True,
                why="100 000 · 4 = 400 000 < 95 000 · 5 = 475 000 zł."),
          ),
      ]),
]
