# -*- coding: utf-8 -*-
# Zrozumienie – Mikroekonomia / Podstawy ekonomii i wybór
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S11 = S("OpenStax, Principles of Economics 3e, 1.1 What Is Economics", OS3 + "1-1-what-is-economics-and-why-is-it-important", D)
S13 = S("OpenStax, Principles of Economics 3e, 1.3 Theories and Models", OS3 + "1-3-how-economists-use-theories-and-models-to-understand-economic-issues", D)
S14 = S("OpenStax, Principles of Economics 3e, 1.4 Economic Systems", OS3 + "1-4-how-to-organize-economies-an-overview-of-economic-systems", D)
S21 = S("OpenStax, Principles of Economics 3e, 2.1 Budget Constraint", OS3 + "2-1-how-individuals-make-choices-based-on-their-budget-constraint", D)
S22 = S("OpenStax, Principles of Economics 3e, 2.2 Production Possibilities Frontier", OS3 + "2-2-the-production-possibilities-frontier-and-social-choices", D)
S23 = S("OpenStax, Principles of Economics 3e, 2.3 Objections to the Economic Approach", OS3 + "2-3-confronting-objections-to-the-economic-approach", D)
S331 = S("OpenStax, Principles of Economics 3e, 33.1 Absolute and Comparative Advantage", OS3 + "33-1-absolute-and-comparative-advantage", D)

S12 = S("OpenStax, Principles of Economics 3e, 1.2 Microeconomics and Macroeconomics", OS3 + "1-2-microeconomics-and-macroeconomics", D)
S155 = S("OpenStax, Principles of Economics 3e, 15.5 Policies to Reduce Income Inequality", OS3 + "15-5-government-policies-to-reduce-income-inequality", D)

LESSONS = [
    L(1, "Rzadkość i koszt alternatywny – sedno każdego wyboru",
      "Rozumieć, dlaczego rzadkość wymusza wybór, i umieć liczyć koszt alternatywny – także czasu – zamiast patrzeć tylko na wydane pieniądze.",
      ["Rzadkość", "Koszt alternatywny (koszt utraconych możliwości)", "Dobro wolne", "Dobro ekonomiczne",
       "Pieniądz a czas wolny – koszt alternatywny czasu", "Problem ekonomiczny: co, jak i dla kogo produkować"],
      [S11, S21, S23],
      explain=[
          K("Rzadkość: potrzeb jest więcej niż zasobów",
            "Ludzkie potrzeby praktycznie nie mają granic, a zasoby (praca, ziemia, kapitał, czas) są ograniczone. Rzadkość nie oznacza, że czegoś jest „mało” w potocznym sensie – oznacza, że nie da się mieć wszystkiego naraz, więc trzeba wybierać. Dlatego każde społeczeństwo musi odpowiedzieć: co, jak i dla kogo produkować."),
          K("Dobro ekonomiczne i dobro wolne",
            "Dobro wolne (np. powietrze nad łąką) jest dostępne w ilościach większych niż potrzeby – nie trzeba z niczego rezygnować, by z niego korzystać, więc ma zerową cenę. Dobro ekonomiczne jest rzadkie: jego użycie oznacza rezygnację z czegoś innego. To, czy dobro jest wolne, zależy od warunków – czysta woda bywa wolna w górach, a ekonomiczna w mieście."),
          W("Które dobro jest najbliższe dobru wolnemu?",
            "Światło słoneczne w słoneczny dzień na otwartej plaży", "Woda butelkowana", "Miejsce parkingowe w centrum miasta", "Bilet na mecz",
            why="Dobro wolne nie wymaga rezygnacji z niczego – jest go więcej, niż potrzebują wszyscy chętni."),
          K("Koszt alternatywny = wartość najlepszej odrzuconej możliwości",
            "Koszt alternatywny wyboru to wartość NAJLEPSZEJ alternatywy, z której rezygnujemy – nie suma wszystkich alternatyw. Obejmuje pieniądze i rzeczy niepieniężne, zwłaszcza czas. Koszt studiów to czesne i książki, ale też dochód, którego nie zarobisz, ucząc się zamiast pracować.",
            p="Wieczór możesz spędzić na korepetycjach (120 zł) albo na treningu. Kosztem alternatywnym treningu jest 120 zł zarobku."),
          K("Czas też kosztuje",
            "Godzina stania w kolejce po tańszy produkt ma koszt: dla kogoś, kto mógłby w tym czasie zarobić 50 zł, „oszczędność” 20 zł jest pozorna. Dlatego osoby o wysokich zarobkach częściej płacą za usługi oszczędzające czas (dostawa, sprzątanie) – ich koszt alternatywny czasu jest wyższy."),
          PF("Koszt alternatywny wyboru to suma wartości wszystkich możliwości, z których zrezygnowaliśmy.", False,
             why="Liczy się tylko najlepsza odrzucona możliwość – i tak nie dałoby się skorzystać ze wszystkich naraz."),
          W("Rzadkość w ekonomii najlepiej opisuje stwierdzenie:",
            "Nie można jednocześnie zaspokoić wszystkich potrzeb, więc trzeba wybierać",
            "Pewnych dóbr w ogóle nie ma na rynku",
            "Biedne kraje mają mniej zasobów niż bogate",
            why="Rzadkość dotyczy wszystkich – także bogatych – bo zasoby i czas są ograniczone względem potrzeb."),
      ],
      mech=[
          LN("Ułóż rozumowanie: dlaczego darmowy koncert nie jest „bez kosztu”?",
             ["Bilet kosztuje 0 zł", "Koncert trwa 3 godziny", "W tym czasie można by pracować lub uczyć się",
              "Wartość tej najlepszej alternatywy to koszt alternatywny koncertu"],
             why="Koszt alternatywny obejmuje czas – nawet przy zerowej cenie."),
          W("Studentka może pracować w kawiarni za 30 zł/h albo udzielać korepetycji za 70 zł/h. Wybiera kawiarnię, bo jest bliżej. Jaki jest koszt alternatywny godziny w kawiarni?",
            "70 zł – utracony zarobek z korepetycji", "30 zł", "100 zł", "0 zł, bo dostaje wynagrodzenie",
            why="Najlepszą odrzuconą możliwością są korepetycje za 70 zł."),
          KT("Co jest częścią kosztu alternatywnego studiów stacjonarnych?",
             {"Wlicza się": ["Dochód z pracy, z której rezygnujesz", "Czesne", "Podręczniki potrzebne tylko na studia"],
              "Nie wlicza się (poniósłbyś i tak)": ["Jedzenie", "Ubrania codzienne", "Abonament telefoniczny"]},
             why="Koszt alternatywny to tylko to, co ponosisz z powodu wyboru; wydatki, które poniósłbyś i tak, do niego nie należą."),
          PF("Jeśli wzrosną płace w gospodarce, koszt alternatywny studiowania dla młodych ludzi wzrośnie.", True,
             why="Rośnie utracony zarobek, czyli wartość najlepszej alternatywy."),
          W("Dlaczego w czasie recesji często rośnie liczba osób rozpoczynających studia?",
            "Spada koszt alternatywny nauki – trudniej znaleźć dobrą pracę",
            "Uczelnie obniżają czesne do zera",
            "Rośnie dochód rodzin",
            why="Gdy alternatywą jest bezrobocie albo niska płaca, rezygnacja z pracy kosztuje mniej."),
          M("Które zdania o rzadkości i wyborze są prawdziwe?",
            ["Rzadkość dotyczy także bardzo bogatych osób", "Każdy wybór ma koszt alternatywny",
             "Dobra wolne mają wysoki koszt alternatywny", "Czas jest zasobem rzadkim"],
            [0, 1, 3],
            why="Dobra wolne nie wymagają rezygnacji z niczego, więc ich koszt alternatywny jest zerowy."),
      ],
      calc=[
          LB("Kurs językowy kosztuje 1500 zł i zajmuje 60 godzin, które mógłbyś przepracować za 35 zł/h. Ile wynosi pełny koszt alternatywny kursu?",
             3600, "1500+60*35", ["Utracony zarobek: 60 · 35 = 2100 zł", "Koszt pełny: 1500 + 2100 = 3600 zł"], unit="zł"),
          LB("Tańszy sklep jest dalej: oszczędzasz 24 zł, ale tracisz 1,5 h. Twój koszt czasu to 20 zł/h. O ile zł jesteś „do przodu” (wynik może być ujemny)?",
             -6, "24-1.5*20", ["Koszt czasu: 1,5 · 20 = 30 zł", "Bilans: 24 − 30 = −6 zł – wyprawa się nie opłaca"], unit="zł"),
          LB("Przy jakim koszcie godziny (zł/h) wyprawa z poprzedniego zadania (oszczędność 24 zł, 1,5 h) byłaby dokładnie „na zero”?",
             16, "24/1.5", ["24 zł / 1,5 h = 16 zł/h", "Przy niższej wartości czasu wyprawa się opłaca"], unit="zł/h"),
          LB("Możesz: pracować 5 h po 40 zł, iść na mecz (wartość dla ciebie 150 zł) albo spać (wartość 80 zł). Wybierasz mecz. Ile wynosi koszt alternatywny?",
             200, "max(5*40, 80)", ["Alternatywy: praca 200 zł, sen 80 zł", "Liczy się najlepsza: 200 zł"], unit="zł"),
          LB("Lot trwa 1,5 h i kosztuje 400 zł; pociąg trwa 6 h i kosztuje 150 zł. Przy jakiej wartości godziny (zł/h) oba wybory kosztują tyle samo?",
             55.56, "(400-150)/(6-1.5)", ["Różnica cen: 250 zł", "Różnica czasu: 4,5 h", "250 / 4,5 ≈ 55,56 zł/h – powyżej tej wartości opłaca się samolot"], unit="zł/h", tol=0.02),
          W("Gmina może za 2 mln zł zbudować boisko albo wyremontować drogę (korzyści 3 mln zł) lub park (2,5 mln zł). Wybiera boisko. Jaki jest koszt alternatywny?",
            "3 mln zł – korzyści z remontu drogi", "2 mln zł", "5,5 mln zł", "2,5 mln zł",
            why="Kosztem alternatywnym jest najlepsza odrzucona możliwość, czyli remont drogi."),
      ],
      case=[
          PR("Kasia (19 lat) ma ofertę pracy w magazynie za 4800 zł brutto miesięcznie albo może podjąć 3-letnie studia dzienne z czesnym 0 zł (uczelnia publiczna). Szacuje, że po studiach będzie zarabiać o 1500 zł miesięcznie więcej niż bez nich.",
             W("Co jest głównym kosztem studiów Kasi?",
               "Utracone zarobki z pracy przez 3 lata", "Czesne", "Brak kosztów – studia są bezpłatne",
               why="Studia „bezpłatne” mają wysoki koszt alternatywny – utraconą pensję."),
             LB("Ile zarobków (brutto) Kasia traci przez 3 lata studiów?",
                172800, "4800*12*3", ["4800 · 12 = 57 600 zł rocznie", "· 3 = 172 800 zł"], unit="zł"),
             LB("Po ilu latach pracy wyższe zarobki (+1500 zł/mies.) zrównają się z utraconym dochodem (bez dyskontowania)?",
                9.6, "172800/(1500*12)", ["Dodatkowo rocznie: 1500 · 12 = 18 000 zł", "172 800 / 18 000 = 9,6 roku"], unit="lat", tol=0.05),
          ),
          PR("Miasto ma działkę w centrum. Może sprzedać ją deweloperowi za 12 mln zł, wydzierżawić na parking (przychód 0,5 mln zł rocznie) albo urządzić park. Radni twierdzą, że park „nic nie kosztuje”, bo działka już należy do miasta.",
             W("Dlaczego stwierdzenie radnych jest błędne?",
               "Park ma koszt alternatywny – rezygnację ze sprzedaży lub dzierżawy",
               "Park kosztuje tylko utrzymanie zieleni",
               "Działki należącej do miasta nie da się sprzedać",
               why="Zasób, który już mamy, nadal ma alternatywne zastosowania – ich wartość to koszt."),
             PF("Decyzja o parku może być słuszna, jeśli korzyści mieszkańców z parku są większe niż wartość najlepszej alternatywy.", True,
                why="Koszt alternatywny nie wyklucza wyboru – pozwala porównać korzyści z tym, z czego rezygnujemy."),
             W("Która informacja jest najważniejsza do oceny decyzji?",
               "Wartość korzyści z parku w porównaniu z 12 mln zł ze sprzedaży",
               "Cena zakupu działki sprzed lat",
               "Liczba radnych głosujących za parkiem",
               why="Historyczna cena zakupu to koszt utopiony – liczą się obecne alternatywy."),
          ),
      ]),

    L(2, "Krzywa możliwości produkcyjnych",
      "Czytać krzywą możliwości produkcyjnych (KMP): punkty efektywne, nieefektywne i nieosiągalne, rosnący koszt alternatywny oraz przesunięcia krzywej przy wzroście gospodarczym.",
      ["Krzywa możliwości produkcyjnych (granica możliwości produkcyjnych)", "Koszt alternatywny (koszt utraconych możliwości)",
       "Czynniki wytwórcze (czynniki produkcji)", "Dobro konsumpcyjne, pośrednie i inwestycyjne"],
      [S22],
      explain=[
          K("Co pokazuje KMP",
            "Krzywa możliwości produkcyjnych pokazuje maksymalne kombinacje dwóch dóbr, które gospodarka może wytworzyć przy pełnym i efektywnym wykorzystaniu zasobów i danej technologii. Punkty NA krzywej są efektywne, punkty POD krzywą – nieefektywne (np. bezrobocie, marnotrawstwo), punkty NAD krzywą – nieosiągalne przy obecnych zasobach."),
          K("Ruch po krzywej = koszt alternatywny",
            "Przesuwając się po krzywej, zwiększamy produkcję jednego dobra kosztem drugiego. Ilość dobra B, z której trzeba zrezygnować, by uzyskać jednostkę więcej dobra A, to koszt alternatywny A. Na wykresie to nachylenie KMP."),
          K("Dlaczego KMP jest wygięta na zewnątrz",
            "Zasoby nie są jednakowo przydatne do wszystkiego. Gdy produkujemy więcej dobra A, najpierw przenosimy zasoby najlepiej do niego pasujące, potem coraz mniej przydatne – za każdą kolejną jednostkę A rezygnujemy z coraz większej ilości B. To prawo rosnących kosztów alternatywnych."),
          W("Gospodarka ma 15% bezrobocia. Gdzie leży jej punkt produkcji?",
            "Pod krzywą możliwości produkcyjnych", "Na krzywej", "Nad krzywą", "Na osi jednego z dóbr",
            why="Niewykorzystane zasoby oznaczają, że można by produkować więcej obu dóbr – punkt jest pod KMP."),
          K("Przesunięcie KMP = wzrost lub spadek możliwości",
            "Więcej zasobów (ludności, kapitału) albo lepsza technologia przesuwają KMP na zewnątrz. Klęska, wojna czy emigracja dużej części pracowników – do wewnątrz. Postęp w produkcji tylko jednego dobra „obraca” krzywą: rośnie maksimum tego dobra."),
          K("Inwestować dziś, mieć więcej jutro",
            "Społeczeństwo, które dziś produkuje więcej dóbr inwestycyjnych (maszyny, infrastruktura, edukacja) kosztem konsumpcji, w przyszłości ma KMP przesuniętą dalej na zewnątrz. Koszt alternatywny wzrostu to dzisiejsza konsumpcja."),
          PF("Punkt leżący nad krzywą możliwości produkcyjnych jest nieosiągalny niezależnie od tego, jak dobrze wykorzystamy zasoby.", True,
             why="Przy danych zasobach i technologii nie da się go osiągnąć; potrzebny byłby wzrost zasobów lub postęp techniczny."),
      ],
      mech=[
          KT("Gdzie leży punkt produkcji gospodarki?",
             {"Pod KMP": ["Fabryki pracują na pół gwizdka w recesji", "Część pól leży odłogiem bez powodu", "Wysokie bezrobocie"],
              "Na KMP": ["Wszystkie zasoby wykorzystane, technologia stosowana najlepiej", "Pełne zatrudnienie i brak marnotrawstwa"],
              "Nad KMP (nieosiągalne)": ["Więcej obu dóbr niż pozwalają obecne zasoby", "Produkcja przekraczająca możliwości przy danej technologii"]},
             why="Pod krzywą – nieefektywność; na krzywej – efektywność; nad krzywą – poza możliwościami."),
          W("Wynaleziono nową maszynę rolniczą, ale nie zmieniła się technologia produkcji samochodów. Jak zmienia się KMP (żywność – samochody)?",
            "Rośnie maksimum żywności – krzywa „obraca się” na osi żywności",
            "Cała krzywa przesuwa się równomiernie na zewnątrz",
            "Krzywa przesuwa się do wewnątrz",
            "Nic się nie zmienia",
            why="Postęp tylko w jednej branży zwiększa możliwości produkcji tego dobra."),
          LN("Ułóż, jak inwestycje dziś wpływają na KMP jutro.",
             ["Społeczeństwo przesuwa zasoby z konsumpcji do dóbr inwestycyjnych", "Dziś konsumuje mniej",
              "Rośnie zasób kapitału (maszyny, drogi, umiejętności)", "W przyszłości KMP przesuwa się na zewnątrz"],
             why="Koszt dzisiejszej konsumpcji jest ceną szybszego wzrostu możliwości produkcyjnych."),
          PF("Jeśli KMP jest linią prostą, koszt alternatywny jednego dobra jest stały.", True,
             why="Stałe nachylenie oznacza stałą ilość drugiego dobra, z której rezygnujemy za jednostkę pierwszego – zasoby są jednakowo przydatne do obu."),
          W("Duża emigracja młodych pracowników z kraju. Co dzieje się z KMP tego kraju?",
            "Przesuwa się do wewnątrz", "Przesuwa się na zewnątrz", "Punkt przesuwa się pod krzywą, ale krzywa się nie zmienia",
            why="Ubywa zasobu pracy, więc maksymalne możliwości produkcyjne maleją."),
          W("Przy przesuwaniu się wzdłuż wygiętej KMP w stronę większej produkcji broni koszt alternatywny kolejnych jednostek broni:",
            "Rośnie", "Maleje", "Jest stały", "Jest zerowy",
            why="Przenosimy coraz mniej przydatne zasoby, więc rezygnujemy z coraz większej ilości drugiego dobra."),
          M("Co przesuwa KMP na zewnątrz?",
            ["Postęp techniczny", "Wzrost liczby ludności w wieku produkcyjnym", "Spadek bezrobocia przy niezmienionych zasobach", "Wzrost zasobu kapitału"],
            [0, 1, 3],
            why="Spadek bezrobocia przesuwa punkt w stronę krzywej, ale nie zmienia samej krzywej."),
      ],
      calc=[
          LB("Gospodarka może wyprodukować 100 t żywności i 0 maszyn albo 0 t żywności i 50 maszyn; KMP jest prosta. Ile ton żywności kosztuje 1 maszyna?",
             2, "100/50", ["Rezygnując ze 100 t żywności, uzyskujemy 50 maszyn", "Koszt 1 maszyny: 100 / 50 = 2 t żywności"], unit="t"),
          LB("Dla tej samej KMP (100 t albo 50 maszyn) ile maszyn można wyprodukować, produkując jednocześnie 60 t żywności?",
             20, "(100-60)/2", ["Zostaje 40 t „do oddania”", "40 / 2 t za maszynę = 20 maszyn"], unit="szt."),
          LB("Punkty KMP: (żywność, maszyny) = (0, 30), (10, 28), (20, 22), (30, 12), (40, 0). Ile maszyn kosztuje przejście z 20 do 30 t żywności?",
             10, "22-12", ["Maszyny spadają z 22 do 12", "Koszt 10 t żywności = 10 maszyn"], unit="szt."),
          LB("Dla tych punktów: ile wynosi koszt alternatywny 1 tony żywności przy przejściu z 30 do 40 t?",
             1.2, "(12-0)/(40-30)", ["Maszyny: 12 → 0, czyli −12", "Na 10 t żywności: 12 / 10 = 1,2 maszyny za tonę", "Wcześniej (0→10 t) było 0,2 – koszt rośnie"], unit="maszyny", tol=0.01),
          LB("Gospodarka produkuje 15 t żywności i 20 maszyn, choć przy 15 t mogłaby wyprodukować 25 maszyn. Ile maszyn traci przez nieefektywność?",
             5, "25-20", ["Na KMP: 25 maszyn", "Faktycznie: 20", "Strata: 5 maszyn"], unit="szt."),
          LB("Po postępie technicznym maksymalna produkcja maszyn wzrosła z 50 do 60 (żywności bez zmian, 100 t). Ile teraz kosztuje 1 maszyna w tonach żywności (KMP prosta)?",
             1.67, "100/60", ["100 t / 60 maszyn ≈ 1,67 t", "Maszyny stały się „tańsze” w kategoriach żywności"], unit="t", tol=0.01),
      ],
      case=[
          PR("Kraj A przeznacza 30% produkcji na inwestycje (fabryki, drogi, szkolenia), kraj B – 10%; resztę konsumują. Dziś mają identyczne KMP.",
             W("Który kraj ma dziś wyższą konsumpcję?",
               "Kraj B", "Kraj A", "Oba tak samo",
               why="Przy tych samych możliwościach B przeznacza większą część produkcji na konsumpcję."),
             W("Który kraj za 20 lat ma prawdopodobnie KMP przesuniętą dalej na zewnątrz?",
               "Kraj A – szybciej rośnie zasób kapitału", "Kraj B", "Żaden – KMP się nie zmienia",
               why="Inwestycje zwiększają przyszłe zasoby i możliwości produkcyjne."),
             PF("Wybór kraju A nie ma kosztu – zyskuje tylko szybszy wzrost.", False,
                why="Kosztem jest niższa konsumpcja dziś – to klasyczny wybór między teraźniejszością a przyszłością."),
          ),
          PR("Pandemia: część fabryk zamknięto czasowo, wielu pracowników było na postojowym, ale maszyny i umiejętności się nie zmieniły. Po roku produkcja wróciła do poprzedniego poziomu.",
             W("Jak opisać sytuację w czasie zamknięcia na wykresie KMP?",
               "Punkt produkcji przesunął się pod krzywą, krzywa się nie zmieniła",
               "Krzywa przesunęła się trwale do wewnątrz",
               "Punkt znalazł się nad krzywą",
               why="Zasoby istniały, ale nie były wykorzystywane – to nieefektywność, nie utrata możliwości."),
             PF("Gdyby w czasie przestoju część maszyn trwale zniszczono, KMP przesunęłaby się do wewnątrz.", True,
                why="Utrata kapitału zmniejsza maksymalne możliwości produkcyjne."),
             W("Co pozwoliło szybko wrócić do poprzedniej produkcji?",
               "Zasoby i technologia pozostały – wystarczyło je znów wykorzystać",
               "Postęp techniczny w czasie pandemii",
               "Wzrost liczby ludności",
               why="Powrót z punktu pod krzywą na krzywą nie wymaga nowych zasobów."),
          ),
      ]),

    L(3, "Specjalizacja, podział pracy i przewaga komparatywna",
      "Rozumieć, dlaczego specjalizacja i wymiana zwiększają produkcję, oraz umieć wyznaczyć przewagę komparatywną z kosztów alternatywnych.",
      ["Podział pracy i specjalizacja", "Koszt alternatywny (koszt utraconych możliwości)", "Niewidzialna ręka rynku"],
      [S331, S22],
      explain=[
          K("Podział pracy według Adama Smitha",
            "Adam Smith opisał manufakturę szpilek: gdy każdy robotnik wykonuje jedną czynność, produkcja rośnie wielokrotnie. Powody: rosnąca wprawa, brak strat czasu na przechodzenie między czynnościami, łatwiejsze wprowadzanie maszyn do prostych, powtarzalnych zadań."),
          K("Przewaga absolutna a komparatywna",
            "Przewagę absolutną ma ten, kto produkuje więcej z tych samych zasobów. Przewagę komparatywną ma ten, kto produkuje dane dobro z NIŻSZYM KOSZTEM ALTERNATYWNYM. Do wymiany wystarczy przewaga komparatywna – nawet ktoś gorszy we wszystkim ma w czymś najniższy koszt alternatywny."),
          W("Ania w godzinę pisze 4 strony albo robi 8 grafik; Bartek – 2 strony albo 2 grafiki. Kto ma przewagę komparatywną w grafikach?",
            "Ania – grafika kosztuje ją 0,5 strony, Bartka 1 stronę", "Bartek", "Nikt, bo Ania jest lepsza we wszystkim",
            why="Liczy się koszt alternatywny: Ania rezygnuje z mniejszej liczby stron za grafikę."),
          K("Jak liczyć koszt alternatywny w tabeli",
            "Koszt 1 jednostki dobra X = ilość Y, z której rezygnujemy / ilość X, którą zyskujemy w tym samym czasie. Kto ma niższy koszt X, specjalizuje się w X; drugi – w Y. Obie strony mogą wtedy konsumować więcej, niż gdyby wszystko robiły same."),
          K("Granice specjalizacji",
            "Specjalizacja zwiększa produkcję, ale też współzależność: zakłócenie u jednego dostawcy (np. brak chipów) zatrzymuje wiele branż. Zbyt wąskie zadania mogą zniechęcać pracowników. Dlatego firmy i państwa łączą specjalizację z dywersyfikacją."),
          PF("Jeśli jedna osoba jest lepsza od drugiej we wszystkich czynnościach, wymiana między nimi nie przynosi korzyści.", False,
             why="Korzyść wynika z różnic kosztów alternatywnych, a nie z przewagi absolutnej."),
      ],
      mech=[
          LN("Ułóż, dlaczego podział pracy zwiększa produkcję.",
             ["Każdy wykonuje wąski zakres zadań", "Rośnie wprawa i szybkość", "Znika czas na zmianę czynności",
              "Łatwiej wprowadzić maszyny do prostych zadań", "Produkcja na pracownika rośnie"],
             why="To mechanizmy opisane przez Smitha w przykładzie manufaktury szpilek."),
          W("Polska ma przewagę komparatywną w meblach, a Niemcy w maszynach. Co powinno nastąpić według teorii?",
            "Polska eksportuje meble, Niemcy maszyny – oba kraje mogą zużywać więcej obu dóbr",
            "Oba kraje powinny produkować wszystko same",
            "Tylko Niemcy zyskują na handlu",
            why="Specjalizacja według przewagi komparatywnej zwiększa łączną produkcję, a wymiana dzieli korzyści."),
          KT("Przewaga absolutna czy komparatywna?",
             {"Absolutna": ["Kraj produkuje więcej pszenicy z hektara niż inny", "Pracownik składa więcej części na godzinę niż inny"],
              "Komparatywna": ["Kraj rezygnuje z mniejszej ilości stali, by wyprodukować tonę pszenicy", "Pracownik ma niższy koszt alternatywny złożenia części"]},
             why="Absolutna – więcej z tych samych zasobów; komparatywna – niższy koszt alternatywny."),
          PF("Przewagę komparatywną w danym dobrze może mieć tylko jedna z dwóch stron.", True,
             why="Jeśli A ma niższy koszt X, to automatycznie B ma niższy koszt Y – koszty są odwrotnościami."),
          W("Lekarka szybciej pisze na komputerze niż jej asystentka. Dlaczego i tak zatrudnia asystentkę do dokumentacji?",
            "Godzina lekarki ma wysoki koszt alternatywny – lepiej leczyć pacjentów",
            "Asystentka ma przewagę absolutną w pisaniu",
            "Lekarka nie potrafi pisać",
            why="Lekarka ma przewagę absolutną w pisaniu, ale komparatywną w leczeniu."),
          M("Które ryzyka wiążą się z silną specjalizacją gospodarki?",
            ["Wrażliwość na przerwanie łańcuchów dostaw", "Zależność od cen kilku towarów eksportowych",
             "Niższa produkcja niż przy samowystarczalności", "Trudności, gdy spada popyt na główną branżę"],
            [0, 1, 3],
            why="Specjalizacja zwykle zwiększa produkcję; ryzykiem jest współzależność i brak dywersyfikacji."),
      ],
      calc=[
          LB("Kraj A w miesiąc wytwarza 100 t sera albo 50 rowerów. Ile ton sera kosztuje go 1 rower?",
             2, "100/50", ["Koszt roweru = ser / rowery = 100 / 50 = 2 t"], unit="t"),
          LB("Kraj B wytwarza 60 t sera albo 60 rowerów. Ile ton sera kosztuje go 1 rower?",
             1, "60/60", ["60 / 60 = 1 t sera za rower – taniej niż w A (2 t)", "B ma przewagę komparatywną w rowerach"], unit="t"),
          LB("Jaki jest koszt 1 t sera w kraju A (100 t sera albo 50 rowerów) wyrażony w rowerach?",
             0.5, "50/100", ["50 / 100 = 0,5 roweru za tonę", "W B: 1 rower za tonę – A ma przewagę w serze"], unit="roweru"),
          LB("Bez handlu A dzieli czas po połowie (50 t sera, 25 rowerów), B też (30 t, 30 rowerów). Po pełnej specjalizacji A robi tylko ser, B tylko rowery. O ile wzrośnie łączna produkcja sera?",
             20, "100-(50+30)", ["Przed: 50 + 30 = 80 t", "Po: 100 t (tylko A)", "Wzrost: 20 t"], unit="t"),
          LB("W tym przykładzie: o ile zmieni się łączna produkcja rowerów po specjalizacji (przed: 25 + 30)?",
             5, "60-(25+30)", ["Przed: 55 rowerów", "Po: 60 (tylko B)", "Wzrost o 5 – więcej obu dóbr"], unit="szt."),
          LB("W manufakturze 10 robotników bez podziału pracy robi po 20 szpilek dziennie, a z podziałem pracy razem 48 000. Ile razy wzrosła wydajność?",
             240, "48000/(10*20)", ["Bez podziału: 10 · 20 = 200", "48 000 / 200 = 240 razy"], unit="razy"),
      ],
      case=[
          PR("Dwie wspólniczki prowadzą małą agencję. Ola w ciągu dnia napisze 10 tekstów albo pozyska 5 klientów. Ewa napisze 6 tekstów albo pozyska 1 klienta. Każda dzieli dziś czas po równo.",
             W("Kto ma przewagę komparatywną w pozyskiwaniu klientów?",
               "Ola – klient kosztuje ją 2 teksty, Ewę 6 tekstów", "Ewa", "Żadna",
               why="Koszt klienta: Ola 10/5 = 2 teksty, Ewa 6/1 = 6 tekstów."),
             W("Jak powinny się podzielić pracą?",
               "Ola pozyskuje klientów, Ewa pisze teksty", "Ola pisze teksty, Ewa pozyskuje klientów", "Obie robią wszystko po połowie",
               why="Każda specjalizuje się tam, gdzie ma niższy koszt alternatywny."),
             LB("Ile tekstów dziennie napiszą łącznie, jeśli Ewa tylko pisze, a Ola pół dnia pisze i pół pozyskuje klientów?",
                11, "6+10/2", ["Ewa: 6 tekstów", "Ola (pół dnia): 5 tekstów", "Razem: 11 (wcześniej 3 + 5 = 8)"], unit="szt."),
          ),
          PR("W 2021 r. niedobór półprzewodników zatrzymał linie montażowe wielu fabryk samochodów w Europie, choć same fabryki były sprawne. Produkcję chipów skupia niewielka liczba wyspecjalizowanych zakładów na świecie.",
             W("Jakie zjawisko pokazuje ten przypadek?",
               "Ryzyko współzależności wynikające ze specjalizacji",
               "Brak przewagi komparatywnej w chipach u producentów chipów",
               "Nieopłacalność handlu międzynarodowego",
               why="Specjalizacja zwiększa wydajność, ale uzależnia od kluczowych dostawców."),
             PF("Z tego przypadku wynika, że każda firma powinna sama produkować wszystkie części.", False,
                why="Samowystarczalność byłaby bardzo kosztowna; rozsądniejsze są dywersyfikacja dostawców i zapasy bezpieczeństwa."),
             W("Które działanie najlepiej ogranicza takie ryzyko bez rezygnacji ze specjalizacji?",
               "Dywersyfikacja dostawców i większe zapasy krytycznych części", "Zakaz importu części", "Rezygnacja z produkcji aut",
               why="Dywersyfikacja zmniejsza zależność od jednego źródła przy zachowaniu korzyści ze specjalizacji."),
          ),
      ]),

    L(4, "Systemy gospodarcze i ruch okrężny",
      "Porównywać gospodarkę rynkową, centralnie planowaną i mieszaną, rozumieć rolę cen jako sygnałów („niewidzialna ręka”) i czytać model ruchu okrężnego.",
      ["Gospodarka rynkowa, centralnie planowana i mieszana", "Niewidzialna ręka rynku", "Laissez-faire", "Model ruchu okrężnego", "Homo oeconomicus"],
      [S14, S("OpenStax, Principles of Economics 3e, 4.3 The Market System as an Efficient Mechanism for Information", OS3 + "4-3-the-market-system-as-an-efficient-mechanism-for-information", D)],
      explain=[
          K("Trzy sposoby odpowiedzi na pytania: co, jak, dla kogo",
            "W gospodarce rynkowej decydują rozproszone decyzje kupujących i sprzedających, koordynowane przez ceny. W centralnie planowanej – urząd planowania, który ustala produkcję i ceny. Dziś wszystkie kraje mają gospodarki mieszane: rynek dominuje, ale państwo dostarcza dóbr publicznych, reguluje i redystrybuuje dochody."),
          K("Niewidzialna ręka: ceny jako sygnał",
            "Adam Smith zauważył, że piekarz nie piecze chleba z dobroci serca, tylko dla zysku – a mimo to zaspokaja nasze potrzeby. Ceny przenoszą informację: rosnąca cena sygnalizuje niedobór i zachęca do produkcji, spadająca – nadmiar. Nikt nie musi znać całego systemu."),
          W("Dlaczego gospodarka centralnie planowana miała problemy z niedoborami?",
            "Planista nie miał informacji o milionach preferencji i kosztów, a ceny nie reagowały na niedobór",
            "Ludzie nie chcieli kupować towarów",
            "Za dużo było prywatnych firm",
            why="Bez elastycznych cen brakuje sygnału o niedoborach, a planista nie zbierze rozproszonej wiedzy."),
          K("Ruch okrężny",
            "Gospodarstwa domowe sprzedają firmom czynniki produkcji (pracę, kapitał, ziemię) na rynku czynników i dostają dochody. Za te dochody kupują dobra i usługi od firm na rynku dóbr. Strumień pieniądza płynie w jedną stronę, strumień dóbr i czynników – w przeciwną. W pełniejszym modelu dochodzą państwo (podatki, transfery, zakupy), banki (oszczędności, kredyty) i zagranica (eksport, import)."),
          K("Homo oeconomicus i jego granice",
            "Tradycyjne modele zakładają racjonalnego człowieka, który porównuje korzyści i koszty, by zmaksymalizować swoją użyteczność. To uproszczenie dobrze przewiduje reakcje na bodźce cenowe, ale ekonomia behawioralna pokazuje systematyczne odstępstwa (np. przywiązanie do tego, co już mamy)."),
          PF("W gospodarce mieszanej państwo nie ingeruje w rynek.", False,
             why="Gospodarka mieszana łączy rynek z działaniami państwa: regulacjami, podatkami, dobrami publicznymi."),
      ],
      mech=[
          LN("Ułóż, jak niewidzialna ręka reaguje na modę na rowery.",
             ["Rośnie popyt na rowery", "Ceny rowerów rosną", "Produkcja rowerów staje się bardziej opłacalna",
              "Firmy przenoszą zasoby do produkcji rowerów", "Podaż rośnie, ceny się stabilizują"],
             why="Ceny przekazują informację i tworzą bodźce – bez centralnego polecenia."),
          KT("Który system opisuje dana cecha?",
             {"Rynkowy": ["Ceny ustalane przez popyt i podaż", "Własność prywatna dominuje", "Decyzje rozproszone"],
              "Centralnie planowany": ["Urząd ustala plan produkcji", "Ceny urzędowe", "Dominacja własności państwowej"]},
             why="Gospodarka mieszana łączy elementy obu, z przewagą rynku."),
          W("W modelu ruchu okrężnym płaca, którą firma wypłaca pracownikowi, to:",
            "Przepływ pieniądza z firm do gospodarstw domowych na rynku czynników", "Przepływ na rynku dóbr", "Podatek",
            why="Płaca to zapłata za czynnik produkcji – pracę."),
          W("Gospodarstwa domowe zwiększają oszczędności. Jak to widać w rozszerzonym ruchu okrężnym?",
            "Część dochodu trafia do banków, które mogą udzielić kredytów firmom",
            "Pieniądz znika z gospodarki",
            "Firmy dostają więcej przychodów ze sprzedaży",
            why="Oszczędności to odpływ z bezpośrednich zakupów, ale wracają przez system finansowy jako inwestycje."),
          PF("Laissez-faire oznacza postulat jak najmniejszej ingerencji państwa w gospodarkę.", True,
             why="Hasło „pozwólcie działać” wyraża zaufanie do samoregulacji rynku."),
          M("Które zadania w gospodarce mieszanej zwykle pełni państwo?",
            ["Dostarczanie dóbr publicznych (np. obrona)", "Ochrona konkurencji", "Ustalanie cen wszystkich towarów", "Redystrybucja dochodów"],
            [0, 1, 3],
            why="Ustalanie wszystkich cen to cecha gospodarki centralnie planowanej."),
      ],
      calc=[
          LB("Gospodarstwa domowe zarabiają 500 mld zł, płacą 100 mld zł podatków, oszczędzają 50 mld zł, resztę wydają na konsumpcję. Ile wydają na konsumpcję?",
             350, "500-100-50", ["Dochód rozporządzalny: 500 − 100 = 400", "Konsumpcja: 400 − 50 = 350 mld zł"], unit="mld zł"),
          LB("Do firm wpływa: konsumpcja 350 mld zł, zakupy państwa 120 mld zł, eksport 80 mld zł, inwestycje 60 mld zł. Gospodarstwa wydają też 90 mld zł na import (który nie trafia do krajowych firm, ale jest już w konsumpcji). Ile wynoszą wydatki na krajowe produkty?",
             520, "350+120+80+60-90", ["Suma wydatków: 350 + 120 + 80 + 60 = 610", "Minus import: 610 − 90 = 520 mld zł"], unit="mld zł"),
          LB("Piekarnia sprzedaje 2000 bochenków po 6 zł; koszty to 9000 zł. Ile wynosi zysk – sygnał, czy warto piec?",
             3000, "2000*6-9000", ["Przychód: 12 000 zł", "Zysk: 12 000 − 9000 = 3000 zł"], unit="zł"),
          LB("Cena bochenka rośnie o 1 zł, a sprzedaż i koszty się nie zmieniają (2000 szt., 9000 zł). O ile procent rośnie zysk piekarni?",
             66.67, "(2000*7-9000-3000)/3000*100", ["Nowy zysk: 14 000 − 9000 = 5000 zł", "Wzrost: 2000 / 3000 ≈ 66,67%", "Silny sygnał do zwiększenia produkcji"], unit="%", tol=0.05),
          LB("Planista ustalił cenę chleba 3 zł, przy której ludzie chcą kupić 1200 bochenków, a piekarnie (przy tej cenie) pieką 800. Ile wynosi niedobór?",
             400, "1200-800", ["Niedobór = 1200 − 800 = 400 bochenków", "Cena nie może wzrosnąć, by go zlikwidować"], unit="szt."),
          W("W modelu ruchu okrężnym suma dochodów gospodarstw domowych (z płac, zysków, odsetek, czynszów) w prostym modelu bez państwa jest równa:",
            "Wartości wytworzonych dóbr i usług", "Tylko sumie płac", "Połowie produkcji",
            why="Każda złotówka wydana na produkcję jest czyimś dochodem – stąd równość produkcji i dochodu."),
      ],
      case=[
          PR("W latach 80. w Polsce ceny wielu towarów ustalało państwo. W sklepach brakowało mięsa, cukru czy pralek; obowiązywały kartki, a kolejki trwały godzinami. Po uwolnieniu cen w 1990 r. półki szybko się zapełniły, ale ceny gwałtownie wzrosły.",
             W("Co było główną przyczyną pustych półek przed 1990 r.?",
               "Ceny urzędowe utrzymywane poniżej poziomu równowagi", "Brak popytu", "Zbyt wysokie ceny",
               why="Ceny poniżej równowagi wywołują trwały niedobór."),
             W("Dlaczego po uwolnieniu cen półki się zapełniły?",
               "Ceny wzrosły do poziomu, przy którym wielkość popytu zrównała się z podażą", "Państwo zakazało kolejek", "Ludzie przestali kupować",
               why="Wyższa cena ograniczyła wielkość popytu i zwiększyła opłacalność dostaw."),
             PF("Kolejki i kartki to sposoby rozdzielania dóbr zastępujące mechanizm cenowy.", True,
                why="Przy niedoborze trzeba jakoś zdecydować, kto dostanie towar – czasem, przydziałem albo znajomościami."),
          ),
          PR("Rząd rozważa przejęcie wszystkich piekarni i ustalanie dziennej produkcji pieczywa w każdym mieście na podstawie statystyk z poprzedniego roku.",
             W("Jaki problem jest najpoważniejszy?",
               "Brak bieżącej informacji o zmianach gustów i kosztów, którą przenoszą ceny",
               "Za mało piekarzy",
               "Za duża konkurencja",
               why="Planista opiera się na danych historycznych, a rynek reaguje na bieżące sygnały."),
             M("Które sygnały rynku zniknęłyby przy takim systemie?",
               ["Wzrost ceny przy nagłym wzroście popytu", "Zysk jako zachęta do lepszej jakości", "Statystyki produkcji z poprzedniego roku", "Upadek nieefektywnych piekarni"],
               [0, 1, 3],
               why="Statystyki historyczne miałby planista; brakowałoby sygnałów cenowych i bodźców."),
             W("Jakiego skutku można się spodziewać w dni nietypowego popytu (np. święta)?",
               "Niedoboru lub marnowania pieczywa", "Idealnego dopasowania produkcji", "Spadku cen do zera",
               why="Plan oparty na średnich nie uwzględnia nagłych zmian."),
          ),
      ]),

    L(5, "Jak myślą ekonomiści: modele, ceteris paribus i liczby",
      "Rozumieć rolę modeli i założenia ceteris paribus, odróżniać zdania pozytywne od normatywnych, korelację od przyczynowości oraz procenty od punktów procentowych.",
      ["Ceteris paribus", "Model, teoria i prawo ekonomiczne", "Ekonomia pozytywna", "Ekonomia normatywna",
       "Punkt procentowy a procent", "Metoda naukowa w ekonomii: dedukcja, indukcja, falsyfikowalność", "Spory ekonomistów – źródła"],
      [S13, S("OpenStax, Principles of Economics 3e, Appendix A – The Use of Mathematics", OS3 + "a-the-use-of-mathematics-in-principles-of-economics", D)],
      explain=[
          K("Model to uproszczona mapa",
            "Model ekonomiczny celowo pomija wiele szczegółów, by pokazać najważniejsze zależności – jak mapa metra, która nie pokazuje budynków, ale świetnie służy do podróży. Dobry model ocenia się po tym, czy trafnie wyjaśnia i przewiduje, a nie po tym, czy jest „realistyczny” w każdym detalu."),
          K("Ceteris paribus – „przy pozostałych warunkach niezmienionych”",
            "Aby zbadać wpływ jednej zmiennej (np. ceny) na inną (ilość kupowaną), zakładamy, że reszta się nie zmienia. W rzeczywistości wiele rzeczy zmienia się naraz – dlatego ekonomiści używają metod statystycznych, by oddzielić wpływ poszczególnych czynników."),
          W("Które zdanie jest pozytywne (opisowe), a nie normatywne?",
            "Podwyżka akcyzy na papierosy zmniejszy ich sprzedaż",
            "Państwo powinno podnieść akcyzę na papierosy",
            "Palenie jest złym wyborem",
            why="Zdanie pozytywne da się sprawdzić danymi; normatywne zawiera ocenę „powinno”."),
          K("Korelacja to nie przyczynowość",
            "Dwie zmienne mogą rosnąć razem, bo obie zależą od trzeciej. Sprzedaż lodów i liczba utonięć rosną latem – przyczyną jest temperatura, a nie lody. Przy ocenie polityki gospodarczej łatwo pomylić współwystępowanie z wpływem."),
          K("Procent a punkt procentowy",
            "Gdy stopa bezrobocia spada z 6% do 5%, spada o 1 PUNKT PROCENTOWY, ale o ok. 16,7 PROCENT (1/6). Punkt procentowy to różnica dwóch wartości wyrażonych w procentach; procent to względna zmiana. W mediach często się to myli.",
            w="zmiana w p.p. = nowa − stara;  zmiana w % = (nowa − stara) / stara · 100%"),
          PF("Wzrost stopy procentowej z 2% do 3% to wzrost o 1%.", False,
             why="To wzrost o 1 punkt procentowy, czyli o 50% względem poziomu wyjściowego."),
      ],
      mech=[
          KT("Zdanie pozytywne czy normatywne?",
             {"Pozytywne": ["Wyższa płaca minimalna zwiększa koszty pracy firm", "W 2026 r. płaca minimalna wynosi 4806 zł", "Niższe stopy procentowe zwiększają popyt na kredyty"],
              "Normatywne": ["Płaca minimalna powinna wynosić połowę średniej", "Państwo powinno dopłacać do kredytów", "Nierówności dochodowe są niesprawiedliwe"]},
             why="Normatywne zdania zawierają ocenę i nie da się ich rozstrzygnąć samymi danymi."),
          W("Badanie pokazuje, że w miastach z większą liczbą policjantów jest więcej przestępstw. Jaki wniosek jest najbardziej uzasadniony?",
            "Nie wiadomo, co jest przyczyną – policję zwiększa się tam, gdzie jest więcej przestępstw",
            "Policjanci powodują przestępstwa",
            "Trzeba zmniejszyć liczbę policjantów",
            why="Przyczynowość może działać odwrotnie (odwrócona przyczynowość)."),
          LN("Ułóż etapy metody naukowej w ekonomii.",
             ["Obserwacja zjawiska", "Sformułowanie hipotezy (modelu)", "Wyprowadzenie przewidywań", "Sprawdzenie na danych", "Przyjęcie, poprawienie lub odrzucenie hipotezy"],
             why="Teoria musi być falsyfikowalna – dawać przewidywania, które dane mogą obalić."),
          W("Dlaczego ekonomiści często się spierają?",
            "Różnią się wartościami (normatywnie) i oceną, który model najlepiej opisuje rzeczywistość",
            "Ekonomia nie korzysta z danych",
            "Wszyscy mają te same poglądy, ale źle się komunikują",
            why="Spory wynikają z różnic w wartościach i w interpretacji niepełnych danych."),
          PF("Założenie ceteris paribus oznacza, że ekonomiści wierzą, iż w rzeczywistości nic poza badaną zmienną się nie zmienia.", False,
             why="To narzędzie myślowe do wyodrębnienia jednego wpływu, a nie opis świata."),
          M("Które zdania o modelach są prawdziwe?",
            ["Model upraszcza rzeczywistość celowo", "Dobry model trafnie przewiduje", "Model musi uwzględniać wszystkie szczegóły", "Ten sam model może być przydatny do jednych pytań, a nieprzydatny do innych"],
            [0, 1, 3],
            why="Uwzględnienie wszystkich szczegółów uczyniłoby model bezużytecznym – jak mapa w skali 1:1."),
      ],
      calc=[
          LB("Stopa bezrobocia spadła z 6% do 5%. O ile procent (względnie) spadła? Podaj liczbę dodatnią.",
             16.67, "(6-5)/6*100", ["Zmiana: 1 punkt procentowy", "Względnie: 1 / 6 · 100% ≈ 16,67%"], unit="%", tol=0.05),
          LB("Oprocentowanie kredytu wzrosło z 4% do 7%. O ile punktów procentowych?",
             3, "7-4", ["7 − 4 = 3 p.p."], unit="p.p."),
          LB("Oprocentowanie wzrosło z 4% do 7%. O ile procent wzrosło względnie?",
             75, "(7-4)/4*100", ["3 / 4 · 100% = 75%"], unit="%"),
          LB("Cena wzrosła o 20%, a potem spadła o 20%. O ile procent zmieniła się w sumie (podaj ze znakiem)?",
             -4, "(1.2*0.8-1)*100", ["1,2 · 0,8 = 0,96", "Zmiana: −4% – wzrost i spadek o ten sam procent się nie znoszą"], unit="%"),
          LB("Pensja wzrosła z 5000 zł do 5400 zł, a ceny w tym czasie o 5%. O ile procent wzrosła pensja realnie (dokładnie)?",
             2.86, "(5400/5000/1.05-1)*100", ["Wzrost nominalny: 8%", "Realnie: 1,08 / 1,05 − 1 ≈ 2,86%"], unit="%", tol=0.02),
          LB("Udział eksportu w PKB wzrósł z 50% do 55%. O ile punktów procentowych?",
             5, "55-50", ["55 − 50 = 5 p.p. (względnie: o 10%)"], unit="p.p."),
      ],
      case=[
          PR("Nagłówek portalu: „Inflacja spadła o 2 procent – z 6% do 4%”. Ekonomistka komentuje, że nagłówek jest nieprecyzyjny, a ceny wcale nie spadły.",
             W("Jak poprawnie opisać zmianę inflacji?",
               "Spadła o 2 punkty procentowe (o ok. 33% względnie)", "Spadła o 2%", "Spadła o 4 punkty procentowe",
               why="Różnica stóp to punkty procentowe; względnie 2/6 ≈ 33%."),
             PF("Spadek inflacji z 6% do 4% oznacza, że ceny przeciętnie spadły.", False,
                why="Ceny nadal rosną, tylko wolniej (4% rocznie zamiast 6%). Spadek cen to deflacja."),
             W("Które zdanie z dyskusji jest normatywne?",
               "Bank centralny powinien teraz obniżyć stopy", "Inflacja wynosi 4%", "Inflacja spadła o 2 p.p.",
               why="„Powinien” wprowadza ocenę – to zdanie normatywne."),
          ),
          PR("Analityk zauważa: w województwach, gdzie więcej osób ma wyższe wykształcenie, wyższe są też zarobki. Proponuje: „Dajmy każdemu dyplom, a zarobki wzrosną wszędzie”.",
             W("Jaki jest główny błąd rozumowania?",
               "Mylenie korelacji z przyczynowością – oba zjawiska mogą zależeć od innych czynników (np. struktury gospodarki dużych miast)",
               "Wykształcenie nie wpływa na zarobki",
               "Dane są zawsze fałszywe",
               why="Współwystępowanie nie mówi, ile jest skutkiem dyplomu, a ile np. lokalizacji i branż."),
             M("Jakie czynniki mogą tłumaczyć tę zależność oprócz samego dyplomu?",
               ["Koncentracja dobrze płatnych branż w dużych miastach", "Migracja wykształconych do bogatszych regionów", "Kolor tablic rejestracyjnych", "Różnice w kosztach życia i płacach regionalnych"],
               [0, 1, 3],
               why="To zmienne, które mogą jednocześnie wpływać na wykształcenie i zarobki."),
             PF("Aby ocenić wpływ wykształcenia na zarobki, warto porównywać osoby podobne pod innymi względami.", True,
                why="To próba zastosowania ceteris paribus na danych – oddzielenia wpływu jednej zmiennej."),
          ),
      ]),

    L(6, "Dziesięć zasad ekonomii: bodźce, myślenie krańcowe, efektywność i sprawiedliwość",
      "Znać dziesięć zasad ekonomii z podręcznika Mankiwa i Taylora, rozumieć myślenie krańcowe i reagowanie na bodźce oraz wymienność między efektywnością a sprawiedliwością.",
      ["Dziesięć zasad ekonomii (N.G. Mankiw)", "Bodźce (zachęty) w ekonomii", "Myślenie krańcowe (decyzje na marginesie)", "Efektywność a sprawiedliwość (wymienność celów)"],
      [S11, S23, S155],
      explain=[
          K("Jak ludzie podejmują decyzje (zasady 1–4)",
            "1) Ludzie muszą wybierać – zasoby są rzadkie. 2) Kosztem czegoś jest to, z czego rezygnujemy (koszt alternatywny). 3) Racjonalni ludzie myślą w kategoriach krańcowych – porównują dodatkowe korzyści i dodatkowe koszty niewielkiej zmiany. 4) Ludzie reagują na bodźce – zmiana kosztów lub korzyści zmienia zachowanie."),
          K("Współdziałanie i cała gospodarka (zasady 5–10)",
            "5) Handel może być korzystny dla wszystkich. 6) Rynki są zwykle dobrą formą organizacji gospodarki („niewidzialna ręka”). 7) Państwo może niekiedy poprawić wyniki rynku (efekty zewnętrzne, siła rynkowa, sprawiedliwość). 8) Poziom życia zależy od wydajności. 9) Ceny rosną, gdy państwo drukuje za dużo pieniędzy. 10) W krótkim okresie istnieje wymienność między inflacją a bezrobociem."),
          W("Linia lotnicza ma wolne miejsce tuż przed odlotem. Przeciętny koszt miejsca to 500 zł, koszt dodatkowego pasażera (catering, opłaty) – 30 zł. Klient oferuje 200 zł. Co zrobi racjonalna linia?",
            "Sprzeda bilet – korzyść krańcowa 200 zł > koszt krańcowy 30 zł", "Odmówi – cena poniżej przeciętnego kosztu", "Podniesie cenę do 500 zł",
            why="Decyzja zależy od wielkości krańcowych, nie przeciętnych."),
          K("Bodźce i skutki niezamierzone",
            "Polityka zmienia bodźce, a ludzie dostosowują zachowanie – czasem w nieoczekiwany sposób. Obowiązek zapinania pasów zmniejszył ryzyko kierowcy, więc część kierowców jeździła szybciej (efekt Peltzmana). Podatek od paliwa skłania do kupowania mniejszych aut i korzystania z transportu publicznego."),
          K("Efektywność a sprawiedliwość",
            "Efektywność – uzyskanie z rzadkich zasobów jak największej „wielkości tortu”; sprawiedliwość – słuszny podział tortu. Podatki i zasiłki wyrównują dochody, ale osłabiają bodźce do pracy i oszczędzania, przez co tort może się zmniejszyć. Ekonomia pokazuje koszty i korzyści wyborów; sam wybór jest normatywny."),
          PF("Racjonalny przedsiębiorca porównuje koszt krańcowy z korzyścią krańcową, a nie z kosztem przeciętnym.", True,
             why="Liczy się wpływ dodatkowej decyzji na wynik."),
      ],
      mech=[
          KT("Która zasada ekonomii?",
             {"Ludzie reagują na bodźce": ["Po wprowadzeniu kaucji za butelki ludzie oddają je do sklepów"],
              "Racjonalni ludzie myślą krańcowo": ["Student uczy się dodatkową godzinę, bo ocena wzrośnie bardziej, niż kosztuje go zmęczenie"],
              "Koszt to to, z czego rezygnujemy": ["Koszt studiów obejmuje utracone zarobki z pracy"],
              "Handel może być korzystny dla wszystkich": ["Polska kupuje banany i sprzedaje meble"],
              "Ceny rosną, gdy drukuje się dużo pieniędzy": ["Hiperinflacja w Zimbabwe po masowym druku pieniądza"]},
             why="Dziesięć zasad opisuje typowe mechanizmy gospodarki."),
          LN("Ułóż łańcuch skutków podwyżki akcyzy na paliwo.",
             ["Akcyza podnosi cenę paliwa", "Rośnie koszt jazdy samochodem", "Kierowcy jeżdżą mniej i kupują oszczędniejsze auta", "Rośnie popyt na transport publiczny", "Spada zużycie paliwa i emisja spalin"],
             why="Ludzie reagują na zmianę bodźców cenowych."),
          W("Rząd podnosi zasiłek dla bezrobotnych do poziomu płacy minimalnej. Jaki skutek uboczny przewiduje zasada „ludzie reagują na bodźce”?",
            "Osłabienie bodźców do szukania pracy", "Wzrost liczby ofert pracy", "Spadek bezrobocia do zera",
            why="Korzyść z podjęcia pracy maleje."),
          W("Co oznacza wymienność między efektywnością a sprawiedliwością?",
            "Większa redystrybucja zwiększa równość, ale może zmniejszyć łączny dochód przez słabsze bodźce", "Efektywność zawsze idzie w parze z równością", "Sprawiedliwość nie ma kosztów",
            why="Podatki i zasiłki zmieniają bodźce."),
          M("Które zasady dotyczą funkcjonowania całej gospodarki?",
            ["Poziom życia zależy od wydajności", "Ceny rosną, gdy państwo drukuje za dużo pieniędzy", "W krótkim okresie istnieje wymienność między inflacją a bezrobociem", "Ludzie reagują na bodźce"], [0, 1, 2],
            why="Zasada bodźców dotyczy decyzji jednostek."),
          PF("Skutki polityki mogą być niezamierzone, bo ludzie dostosowują zachowanie do nowych bodźców.", True,
             why="Przykładem jest efekt Peltzmana przy pasach bezpieczeństwa."),
      ],
      calc=[
          LB("Bilet sprzedany za 200 zł, koszt krańcowy pasażera 30 zł. O ile wzrośnie zysk linii?",
             170, "200-30", ["200 − 30 = 170 zł"], unit="zł"),
          LB("Dodatkowa godzina pracy daje 45 zł, a pracownik ceni godzinę wolnego czasu na 38 zł. Ile wynosi korzyść netto tej godziny (zł)?",
             7, "45-38", ["45 − 38 = 7 zł > 0 → warto pracować"], unit="zł"),
          LB("Tort (dochód) wynosi 100; uboższa grupa ma 20%. Po redystrybucji tort maleje do 90, a uboższa grupa ma 40%. Ile dostaje uboższa grupa?",
             36, "90*0.4", ["90 · 0,4 = 36 (wcześniej 20)"], unit="jedn."),
          LB("A ile dostaje po redystrybucji grupa zamożniejsza (wcześniej 80)?",
             54, "90*0.6", ["90 · 0,6 = 54 – spadek z 80"], unit="jedn."),
          LB("Kaucja 0,50 zł za butelkę; osoba oddaje 40 butelek miesięcznie. Ile odzyskuje rocznie (zł)?",
             240, "0.5*40*12", ["0,5 · 40 · 12 = 240 zł"], unit="zł"),
          LB("Ile jest zasad ekonomii dotyczących decyzji jednostek (zasady 1–4) w stosunku do wszystkich zasad (%)?",
             40, "4/10*100", ["4 / 10 = 40%"], unit="%"),
      ],
      case=[
          PR("Miasto wprowadza opłatę za wjazd do centrum w godzinach szczytu – 20 zł dziennie. Po miesiącu ruch spada o 25%, autobusy jeżdżą szybciej, ale część sklepów w centrum skarży się na mniej klientów.",
             W("Którą zasadę ilustruje spadek ruchu?",
               "Ludzie reagują na bodźce", "Ceny rosną, gdy drukuje się pieniądze", "Poziom życia zależy od wydajności",
               why="Opłata zmieniła koszt wjazdu."),
             W("Jak nazwać kłopoty sklepów?",
               "Niezamierzonym skutkiem zmiany bodźców", "Efektem drukowania pieniądza", "Wzrostem wydajności",
               why="Część klientów zmieniła miejsce zakupów."),
             PF("Ocena opłaty wymaga porównania wszystkich korzyści i kosztów, w tym niezamierzonych.", True,
                why="Myślenie ekonomiczne obejmuje całość skutków."),
          ),
          PR("Rząd rozważa podniesienie najwyższej stawki podatku dochodowego z 32% do 45% i przeznaczenie wpływów na zasiłki dla najuboższych. Jedni mówią o sprawiedliwości, inni o spadku aktywności zawodowej najlepiej zarabiających.",
             W("Jaki dylemat ilustruje spór?",
               "Wymienność między efektywnością a sprawiedliwością", "Paradoks wody i diamentu", "Prawo popytu",
               why="Redystrybucja a bodźce do pracy."),
             W("Które twierdzenie jest normatywne?",
               "„Najbogatsi powinni płacić więcej”", "„Wyższa stawka krańcowa obniża bodźce do pracy”", "„Wpływy z podatku wzrosną o 5 mld zł”",
               why="Zawiera ocenę „powinni”."),
             PF("Ekonomia może oszacować koszty redystrybucji, ale wybór poziomu redystrybucji jest normatywny.", True,
                why="Zależy od wartości społeczeństwa."),
          ),
      ]),

    L(7, "Wykresy, nachylenie i pułapki przyczynowości",
      "Czytać wykresy ekonomiczne, liczyć nachylenie, odróżniać ruch wzdłuż krzywej od jej przesunięcia oraz unikać błędów przyczynowości: zmiennej pominiętej i odwróconej przyczynowości. Rozumieć rolę ekonomisty jako naukowca i doradcy.",
      ["Wykresy w ekonomii: nachylenie i układ współrzędnych", "Korelacja a przyczynowość (zmienna pominięta, odwrócona przyczynowość)", "Ekonomista jako naukowiec i doradca polityki"],
      [S13, S12],
      explain=[
          K("Wykres i nachylenie",
            "Układ współrzędnych pokazuje zależność dwóch zmiennych. Nachylenie prostej = Δy / Δx. Krzywa popytu (cena na osi pionowej, ilość na poziomej) ma nachylenie ujemne – wyższa cena, mniejsza ilość. Nachylenie zależy od jednostek, dlatego ekonomiści wolą elastyczność (zmiany procentowe).",
            w="nachylenie = Δy / Δx"),
          K("Ruch wzdłuż a przesunięcie",
            "Zmiana zmiennej na osi (np. ceny) to ruch wzdłuż krzywej. Zmiana zmiennej spoza osi (np. dochodu, cen innych dóbr) przesuwa całą krzywą. Pomylenie tych dwóch zjawisk to jeden z najczęstszych błędów na olimpiadzie."),
          W("Cena rośnie z 6 do 8 zł, a ilość spada z 21 do 13 sztuk. Ile wynosi nachylenie krzywej popytu (cena na osi pionowej)?",
            "Ujemne, równe 0,25 co do wartości", "Ujemne, równe 4 co do wartości", "Dodatnie, równe 0,25",
            why="Δy/Δx = (8 − 6) / (13 − 21) = 2 / (−8) = −0,25."),
          K("Korelacja to nie przyczynowość",
            "Zmienna pominięta: obie zmienne zależą od trzeciej (np. sprzedaż lodów i liczba utonięć rosną latem – przyczyną jest pogoda). Odwrócona przyczynowość: to skutek wydaje się przyczyną (np. więcej policjantów w miastach o wysokiej przestępczości nie oznacza, że policja powoduje przestępczość)."),
          K("Naukowiec i doradca",
            "Jako naukowiec ekonomista buduje modele, przyjmuje założenia upraszczające i testuje teorie na danych (twierdzenia pozytywne). Jako doradca – rekomenduje politykę (twierdzenia normatywne). Ekonomiści różnią się poglądami z powodu różnych ocen naukowych (np. jak elastyczna jest podaż pracy) i różnych wartości."),
          PF("Jeśli dwie zmienne są silnie skorelowane, to zawsze jedna jest przyczyną drugiej.", False,
             why="Możliwa jest zmienna pominięta lub odwrócona przyczynowość."),
      ],
      mech=[
          KT("Jaki błąd przyczynowości?",
             {"Zmienna pominięta": ["Sprzedaż lodów i liczba utonięć rosną razem – obie zależą od pogody", "Posiadacze zapalniczek częściej chorują na raka płuc – przyczyną jest palenie"],
              "Odwrócona przyczynowość": ["Więcej strażaków przy większych pożarach – to pożar przyciąga strażaków", "Zakup minivana „powoduje” narodziny dziecka – w rzeczywistości oczekiwanie dziecka powoduje zakup"]},
             why="Korelacja nie dowodzi kierunku przyczyny."),
          LN("Ułóż poprawną analizę wpływu wzrostu dochodów na rynek mieszkań.",
             ["Dochody nabywców rosną", "Zmienna spoza osi – przesuwa się krzywa popytu", "Krzywa popytu przesuwa się w prawo", "Cena i ilość równowagi rosną", "Na osi widać ruch wzdłuż krzywej podaży"],
             why="Odróżniamy przesunięcie popytu od ruchu po podaży."),
          W("Spada cena pizzy. Co dzieje się na wykresie popytu na pizzę?",
            "Ruch wzdłuż krzywej popytu – wielkość popytu rośnie", "Przesunięcie krzywej popytu w prawo", "Przesunięcie krzywej popytu w lewo",
            why="Cena dobra jest na osi wykresu."),
          W("Ekonomistka mówi: „Podatek węglowy obniży emisję o 10%” i „Powinniśmy go wprowadzić”. Które zdanie jest pozytywne?",
            "Pierwsze – można je sprawdzić empirycznie", "Drugie", "Oba są normatywne",
            why="Drugie zawiera ocenę."),
          M("Dlaczego ekonomiści różnią się w zaleceniach?",
            ["Różne oceny naukowe (np. wartości elastyczności)", "Różne systemy wartości", "Niepewność danych i modeli", "Ekonomia nie stosuje danych"], [0, 1, 2],
            why="Ekonomia testuje teorie na danych."),
          PF("Ujemne nachylenie krzywej oznacza, że zmienne zmieniają się w przeciwnych kierunkach.", True,
             why="Wzrost jednej towarzyszy spadkowi drugiej."),
      ],
      calc=[
          LB("Cena rośnie z 6 do 8 zł, ilość spada z 21 do 13. Ile wynosi nachylenie (Δcena/Δilość)?",
             -0.25, "(8-6)/(13-21)", ["2 / (−8) = −0,25"], unit="", tol=0.0001),
          LB("Prosta przechodzi przez punkty (2; 10) i (6; 4). Ile wynosi nachylenie?",
             -1.5, "(4-10)/(6-2)", ["−6 / 4 = −1,5"], unit="", tol=0.0001),
          LB("Prosta podaży: przy cenie 2 zł ilość 10, przy cenie 5 zł ilość 40. Ile wynosi nachylenie (Δcena/Δilość)?",
             0.1, "(5-2)/(40-10)", ["3 / 30 = 0,1"], unit="", tol=0.0001),
          LB("Funkcja y = 12 − 0,5x. Ile wynosi y dla x = 8?",
             8, "12-0.5*8", ["12 − 4 = 8"], unit=""),
          LB("Przy jakim x funkcja y = 12 − 0,5x przecina oś poziomą?",
             24, "12/0.5", ["12 / 0,5 = 24"], unit=""),
          LB("Nachylenie popytu −0,25 (cena/ilość). O ile spadnie ilość, gdy cena wzrośnie o 1 zł?",
             4, "1/0.25", ["1 / 0,25 = 4 sztuki"], unit="szt."),
      ],
      case=[
          PR("Dziennikarz zauważa, że w gminach z większą liczbą lekarzy na 1 000 mieszkańców jest więcej zgonów, i pisze: „Lekarze szkodzą zdrowiu”.",
             W("Jaki błąd popełnia dziennikarz?",
               "Myli korelację z przyczynowością – lekarzy jest więcej tam, gdzie mieszka więcej starszych i chorych osób", "Nie ma błędu", "Myli nachylenie z elastycznością",
               why="Zmienna pominięta: struktura wieku i stan zdrowia."),
             W("Jak lepiej zbadać wpływ lekarzy na zdrowie?",
               "Porównać gminy o podobnej strukturze wieku i stanie zdrowia mieszkańców", "Policzyć tylko lekarzy", "Zignorować dane",
               why="Kontrola zmiennych pominiętych."),
             PF("W tym przykładzie może wystąpić także odwrócona przyczynowość.", True,
                why="Więcej chorych przyciąga więcej lekarzy."),
          ),
          PR("Uczeń analizuje rynek kawy. Najpierw cena kawy spada z powodu nieurodzaju w Brazylii, potem dochody konsumentów rosną. Uczeń rysuje dwa przesunięcia krzywej popytu.",
             W("Jak powinien przedstawić nieurodzaj w Brazylii?",
               "Jako przesunięcie krzywej podaży w lewo (i ruch wzdłuż popytu)", "Jako przesunięcie popytu w prawo", "Jako ruch wzdłuż krzywej podaży",
               why="Nieurodzaj zmniejsza podaż."),
             W("Co z cenami po nieurodzaju?",
               "Rosną, a nie spadają", "Spadają", "Nie zmieniają się",
               why="Mniejsza podaż przy danym popycie podnosi cenę."),
             PF("Wzrost dochodów (kawa – dobro normalne) przesuwa krzywą popytu w prawo.", True,
                why="Dochód to zmienna spoza osi wykresu."),
          ),
      ]),
]
