# -*- coding: utf-8 -*-
# Zrozumienie – Mikroekonomia / Daty i chronologia
D = "2026-10-07"
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
NP = "https://www.nobelprize.org/prizes/economic-sciences/"
S161 = S("OpenStax, Principles of Economics 3e, 16.1 Imperfect and Asymmetric Information", OS3 + "16-1-the-problem-of-imperfect-information-and-asymmetric-information", D)
N2001 = S("Nobelprize.org – Nagroda z ekonomii 2001 (Akerlof, Spence, Stiglitz) – informacja prasowa", NP + "2001/press-release/", D)
SAK = S("Nobelprize.org – Advanced information 2001: Markets with Asymmetric Information (omówienie artykułu Akerlofa z 1970 r.)", "https://www.nobelprize.org/prizes/economic-sciences/2001/advanced-information/", D)

LESSONS = [
    L(1, "1970: „The Market for Lemons” i rewolucja informacyjna",
      "Znać kontekst i treść artykułu Akerlofa z 1970 r. i rozumieć, jak zapoczątkował ekonomię informacji (sygnalizacja Spence’a, odsiewanie Stiglitza, Nobel 2001).",
      ["1970 – „The Market for Lemons” G. Akerlofa", "Akerlof George", "Asymetria informacji", "Negatywna (niekorzystna) selekcja", "Sygnalizacja i odsiewanie (screening)"],
      [SAK, N2001, S161],
      explain=[
          K("Artykuł, którego nie chciano wydać",
            "George Akerlof opublikował „The Market for ‘Lemons’” w 1970 r. w Quarterly Journal of Economics. Wcześniej kilka czasopism odrzuciło tekst jako zbyt banalny. Tymczasem pokazał on coś zasadniczego: przy asymetrii informacji rynek może się „zepsuć”, nawet gdy wszystkie strony chcą handlować."),
          K("„Cytryny” na rynku aut",
            "„Lemon” to w amerykańskim slangu wadliwy samochód. Kupujący nie odróżniają dobrych aut od wadliwych, więc płacą cenę przeciętną. Właściciele dobrych aut wycofują się z rynku, przeciętna jakość spada – i proces może się powtarzać aż do zaniku rynku dobrych aut."),
          W("W którym roku ukazał się artykuł „The Market for Lemons”?",
            "1970", "1960", "1979", "2001",
            why="1970 – Quarterly Journal of Economics; Nobel za te badania przyznano w 2001 r."),
          K("Spence i Stiglitz",
            "Michael Spence pokazał, jak strona lepiej poinformowana może zasygnalizować jakość (wykształcenie jako sygnał zdolności, 1973). Joseph Stiglitz (z Rothschildem) opisał, jak strona gorzej poinformowana może odsiewać klientów, oferując różne umowy (np. ubezpieczenia z różnym udziałem własnym)."),
          K("Nobel 2001",
            "W 2001 r. Akerlof, Spence i Stiglitz otrzymali wspólnie Nagrodę im. Nobla z ekonomii za analizę rynków z asymetryczną informacją. Ich idee wyjaśniają gwarancje, marki, wymogi kapitałowe banków, ubezpieczenia i oceny na platformach internetowych."),
          PF("Akerlof, Spence i Stiglitz otrzymali Nagrodę im. Nobla za analizę rynków z asymetryczną informacją.", True,
             why="Wspólna nagroda z 2001 r."),
      ],
      mech=[
          LN("Ułóż chronologicznie wydarzenia w ekonomii informacji.",
             ["1970 – artykuł Akerlofa o rynku cytryn", "1973 – Spence: sygnalizacja na rynku pracy", "1976 – Rothschild i Stiglitz: odsiewanie na rynku ubezpieczeń", "2001 – Nagroda im. Nobla dla Akerlofa, Spence’a i Stiglitza"],
             why="Idee rozwijały się w ciągu kilku lat po artykule Akerlofa."),
          KT("Sygnalizacja czy odsiewanie?",
             {"Sygnalizacja (działa strona lepiej poinformowana)": ["Dealer daje 2-letnią gwarancję na używane auto", "Kandydat zdobywa trudny certyfikat", "Firma inwestuje w znaną markę"],
              "Odsiewanie (działa strona gorzej poinformowana)": ["Ubezpieczyciel oferuje warianty z różnym udziałem własnym", "Bank wymaga zabezpieczenia kredytu", "Pracodawca stosuje okres próbny"]},
             why="Sygnał wysyła ten, kto wie więcej; odsiewa ten, kto wie mniej."),
          W("Dlaczego rynek cytryn może zaniknąć, choć są chętni kupujący i sprzedający dobrych aut?",
            "Kupujący nie odróżniają jakości, więc cena nie nagradza dobrych aut", "Państwo zakazuje sprzedaży", "Samochody są dobrem publicznym",
            why="Asymetria informacji wypycha dobrą jakość z rynku."),
          W("Która współczesna instytucja najbardziej ogranicza problem cytryn na rynku używanych aut?",
            "Raporty historii pojazdu i niezależne przeglądy", "Ceny maksymalne", "Cła",
            why="Zmniejszają przewagę informacyjną sprzedawcy."),
          PF("Teoria Akerlofa dotyczy tylko rynku samochodów.", False,
             why="Dotyczy wszystkich rynków z asymetrią informacji: ubezpieczeń, kredytów, pracy."),
          M("Które zjawiska wyjaśnia ekonomia informacji?",
            ["Dlaczego firmy dają gwarancje", "Dlaczego ubezpieczenia mają udział własny", "Dlaczego ceny truskawek spadają w czerwcu", "Dlaczego dyplom wpływa na płacę"],
            [0, 1, 3],
            why="Sezonowe ceny truskawek wyjaśnia zmiana podaży."),
      ],
      calc=[
          LB("Ile lat minęło od publikacji artykułu Akerlofa (1970) do Nagrody im. Nobla (2001)?",
             31, "2001-1970", ["2001 − 1970 = 31 lat"], unit="lat"),
          LB("70% aut dobrych (warte 25 tys. zł), 30% cytryn (10 tys. zł). Ile zapłaci kupujący bez informacji?",
             20.5, "0.7*25+0.3*10", ["17,5 + 3 = 20,5 tys. zł"], unit="tys. zł"),
          LB("Właściciel dobrego auta chce za nie co najmniej 23 tys. zł. O ile tys. zł oferta kupującego (20,5) jest za niska?",
             2.5, "23-20.5", ["23 − 20,5 = 2,5 tys. zł – dobre auta wycofują się"], unit="tys. zł"),
          LB("Gwarancja kosztuje sprzedawcę dobrego auta 500 zł, a sprzedawcę cytryny 4000 zł (częste naprawy). O ile więcej kosztuje ona sprzedawcę cytryny?",
             3500, "4000-500", ["4000 − 500 = 3500 zł – dlatego gwarancja jest wiarygodnym sygnałem"], unit="zł"),
          LB("Ile lat minęło od artykułu Akerlofa (1970) do roku 2026?",
             56, "2026-1970", ["2026 − 1970 = 56 lat"], unit="lat"),
          LB("Spence: dyplom kosztuje zdolną osobę 20 tys. zł, mniej zdolną 50 tys. zł; premia płacowa za dyplom wynosi 35 tys. zł. Ile zyskuje netto zdolna osoba, zdobywając dyplom?",
             15, "35-20", ["35 − 20 = 15 tys. zł (mniej zdolnej się nie opłaca: 35 − 50 = −15)"], unit="tys. zł"),
      ],
      case=[
          PR("Rynek używanych smartfonów w internecie: kupujący boją się ukrytych wad (np. wymienionej baterii, zablokowanego konta). Platforma wprowadza certyfikację przez serwis i roczną gwarancję za dopłatą.",
             W("Jaki problem rozwiązuje certyfikacja?",
               "Asymetrię informacji o jakości telefonów", "Efekt zewnętrzny", "Problem gapowicza",
               why="Kupujący zyskuje wiarygodną informację o stanie urządzenia."),
             W("Co powinno stać się z cenami certyfikowanych telefonów w porównaniu z niecertyfikowanymi?",
               "Wzrosnąć – kupujący zapłacą więcej za pewną jakość", "Spaść", "Nie zmienić się",
               why="Rozdzielenie jakości pozwala cenom odzwierciedlać wartość."),
             PF("Gwarancja za dopłatą może działać jak odsiewanie – kupują ją głównie ostrożni klienci.", True,
                why="Wybór umowy ujawnia informacje o kliencie."),
          ),
          PR("Ubezpieczyciel zdrowotny wprowadza jedną polisę z jednakową składką dla wszystkich, bez ankiety zdrowotnej. Po roku okazuje się, że koszty leczenia klientów są znacznie wyższe od średniej w populacji.",
             W("Jakie zjawisko z ekonomii informacji wystąpiło?",
               "Negatywna selekcja", "Pokusa nadużycia po zawarciu umowy", "Efekt Veblena",
               why="Polisę najchętniej kupiły osoby spodziewające się wysokich kosztów."),
             M("Jakie rozwiązania mogą ograniczyć problem?",
               ["Okres karencji", "Różne warianty polis (odsiewanie)", "Jeszcze niższa składka dla wszystkich", "Obowiązkowe ubezpieczenie całej grupy"],
               [0, 1, 3],
               why="Niższa składka nie zmienia struktury ryzyka klientów."),
             PF("Obowiązkowe ubezpieczenie wszystkich (np. pracowników firmy) usuwa negatywną selekcję, bo nikt nie wybiera.", True,
                why="Gdy wszyscy są objęci, struktura ryzyka odpowiada populacji."),
          ),
      ]),

    L(2, "Oś czasu mikroekonomii: od Smitha do teorii perspektywy",
      "Umieszczać na osi czasu przełomowe prace i idee mikroekonomii oraz rozumieć, jak kolejne teorie odpowiadały na ograniczenia poprzednich.",
      ["1970 – „The Market for Lemons” G. Akerlofa", "Smith Adam", "Marshall Alfred", "Coase Ronald", "Kahneman Daniel"],
      [N2001, S("OpenStax, Principles of Economics 3e, 1.1 What Is Economics", OS3 + "1-1-what-is-economics-and-why-is-it-important", D)],
      explain=[
          K("Klasycy i marginaliści",
            "1776 – „Bogactwo narodów” Smitha (rynek, podział pracy). 1854 – prawa Gossena. 1871–1874 – rewolucja marginalistyczna (Jevons, Menger, Walras). 1890 – „Zasady ekonomii” Marshalla (popyt i podaż, elastyczność)."),
          K("Ekonomia dobrobytu i instytucje",
            "1920 – „Ekonomia dobrobytu” Pigou (efekty zewnętrzne). 1937 – „The Nature of the Firm” Coase’a (koszty transakcyjne). 1960 – „The Problem of Social Cost” (twierdzenie Coase’a). 1968 – „Tragedia wspólnego pastwiska” Hardina."),
          W("Która praca jest najstarsza?",
            "„Bogactwo narodów” Smitha", "„Zasady ekonomii” Marshalla", "„The Nature of the Firm” Coase’a", "Artykuł Akerlofa",
            why="1776 – ponad sto lat przed Marshallem (1890)."),
          K("Informacja, gry i psychologia",
            "1950 – równowaga Nasha. 1970 – rynek cytryn Akerlofa. 1979 – teoria perspektywy Kahnemana i Tversky’ego. Od 1969 r. przyznawana jest Nagroda im. Nobla z ekonomii, która zwykle trafia do autorów wiele lat po ich odkryciach."),
          K("Dlaczego chronologia ma znaczenie",
            "Każda nowa teoria odpowiadała na luki poprzednich: marginaliści na problem wartości klasyków, Pigou i Coase na zawodności rynku, Akerlof na założenie pełnej informacji, Kahneman i Tversky na założenie pełnej racjonalności."),
          PF("Teoria perspektywy powstała przed rewolucją marginalistyczną.", False,
             why="Teoria perspektywy to 1979 r., marginaliści – lata 70. XIX wieku."),
      ],
      mech=[
          LN("Ułóż prace w kolejności chronologicznej.",
             ["„Bogactwo narodów” – Smith (1776)", "Prawa Gossena (1854)", "„Zasady ekonomii” – Marshall (1890)", "„Ekonomia dobrobytu” – Pigou (1920)", "„The Nature of the Firm” – Coase (1937)"],
             why="Od klasyków przez marginalistów do ekonomii dobrobytu i instytucjonalnej."),
          LN("Ułóż wydarzenia XX wieku.",
             ["Równowaga Nasha (1950)", "Twierdzenie Coase’a (1960)", "Tragedia wspólnego pastwiska (1968)", "Rynek cytryn (1970)", "Teoria perspektywy (1979)"],
             why="Druga połowa XX w. przyniosła teorię gier, instytucje i ekonomię behawioralną."),
          KT("Na jakie założenie odpowiadała teoria?",
             {"Pełna informacja": ["Rynek cytryn Akerlofa", "Sygnalizacja Spence’a"],
              "Pełna racjonalność": ["Teoria perspektywy", "Racjonalność ograniczona Simona"],
              "Brak efektów zewnętrznych": ["Podatek Pigou", "Twierdzenie Coase’a"]},
             why="Kolejne teorie „luzowały” założenia modelu konkurencji doskonałej."),
          W("Od którego roku przyznaje się Nagrodę im. Nobla z ekonomii?",
            "1969", "1901", "1945", "2001",
            why="Nagrodę ustanowił Bank Szwecji w 1968 r., pierwszy raz przyznano ją w 1969 r."),
          PF("Akerlof otrzymał Nagrodę im. Nobla w tym samym roku, w którym opublikował artykuł o rynku cytryn.", False,
             why="Artykuł – 1970, nagroda – 2001."),
          M("Które pary data – wydarzenie są poprawne?",
            ["1776 – „Bogactwo narodów”", "1890 – „Zasady ekonomii” Marshalla", "1970 – teoria perspektywy", "1968 – „Tragedia wspólnego pastwiska”"],
            [0, 1, 3],
            why="Teoria perspektywy pochodzi z 1979 r."),
      ],
      calc=[
          LB("Ile lat dzieli „Bogactwo narodów” (1776) od „Zasad ekonomii” Marshalla (1890)?",
             114, "1890-1776", ["1890 − 1776 = 114 lat"], unit="lat"),
          LB("Ile lat dzieli „The Nature of the Firm” (1937) od Nobla dla Coase’a (1991)?",
             54, "1991-1937", ["1991 − 1937 = 54 lata"], unit="lat"),
          LB("Ile lat dzieli teorię perspektywy (1979) od Nobla dla Kahnemana (2002)?",
             23, "2002-1979", ["2002 − 1979 = 23 lata"], unit="lat"),
          LB("Ile lat dzieli równowagę Nasha (1950) od jego Nobla (1994)?",
             44, "1994-1950", ["1994 − 1950 = 44 lata"], unit="lat"),
          LB("Średnio ile lat (zaokrąglij do całości) mija od odkrycia do Nobla w przykładach: Coase 54, Nash 44, Akerlof 31, Kahneman 23?",
             38, "round((54+44+31+23)/4)", ["(54 + 44 + 31 + 23) / 4 = 38"], unit="lat", tol=0.5),
          LB("Ile lat minęło od rewolucji marginalistycznej (1871) do pierwszej Nagrody im. Nobla z ekonomii (1969)?",
             98, "1969-1871", ["1969 − 1871 = 98 lat"], unit="lat"),
      ],
      case=[
          PR("Na olimpiadzie uczeń dostaje zestaw: (a) twierdzenie Coase’a, (b) teoria perspektywy, (c) prawo malejącej użyteczności krańcowej, (d) rynek cytryn, (e) niewidzialna ręka rynku. Ma je uporządkować od najstarszego.",
             LN("Ułóż od najstarszego.",
                ["Niewidzialna ręka rynku (1776)", "Prawo malejącej użyteczności krańcowej (Gossen, 1854)", "Twierdzenie Coase’a (1960)", "Rynek cytryn (1970)", "Teoria perspektywy (1979)"],
                why="Klasycy → marginaliści → ekonomia instytucjonalna → informacja → ekonomia behawioralna."),
             W("Która z tych idei jako jedyna pochodzi z XVIII wieku?",
               "Niewidzialna ręka rynku", "Twierdzenie Coase’a", "Rynek cytryn", "Teoria perspektywy",
               why="„Bogactwo narodów” – 1776."),
             PF("Trzy z tych idei pochodzą z XX wieku.", True,
                why="Coase (1960), Akerlof (1970), Kahneman i Tversky (1979)."),
          ),
          PR("Nauczycielka mówi: „Każda nowa teoria w mikroekonomii zdejmowała jedno z uproszczeń modelu konkurencji doskonałej”. Uczniowie mają przyporządkować przykłady.",
             W("Które uproszczenie „zdjął” Akerlof?",
               "Pełną informację wszystkich uczestników rynku", "Brak efektów zewnętrznych", "Pełną racjonalność",
               why="Rynek cytryn opiera się na asymetrii informacji."),
             W("Które uproszczenie zakwestionowali Kahneman i Tversky?",
               "Pełną racjonalność decyzji", "Pełną informację", "Jednorodność produktu",
               why="Teoria perspektywy opisuje systematyczne odstępstwa od racjonalności."),
             PF("Pigou i Coase zajmowali się sytuacjami, w których działania jednych wpływają na innych poza rynkiem.", True,
                why="To problem efektów zewnętrznych."),
          ),
      ]),
]
