# -*- coding: utf-8 -*-
# Zrozumienie – Mikroekonomia / Ekonomia behawioralna i nowe zjawiska
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S63 = S("OpenStax, Principles of Economics 3e, 6.3 Behavioral Economics", OS3 + "6-3-behavioral-economics-an-alternative-framework-for-consumer-choice", D)
S62 = S("OpenStax, Principles of Economics 3e, 6.2 Changes in Income and Prices", OS3 + "6-2-how-changes-in-income-and-prices-affect-consumption-choices", D)
SNOB = S("The Royal Swedish Academy of Sciences – Nagroda im. Nobla z ekonomii 2017 (R. Thaler), informacja prasowa", "https://www.nobelprize.org/prizes/economic-sciences/2017/press-release/", D)
SKAH = S("The Royal Swedish Academy of Sciences – Nagroda im. Nobla z ekonomii 2002 (D. Kahneman, V. Smith), informacja prasowa", "https://www.nobelprize.org/prizes/economic-sciences/2002/press-release/", D)
SPPK = S("PFR Portal PPK – Biuletyn PPK nr 06/2025 (dane z Ewidencji PPK na 31.05.2025)", "https://www.mojeppk.pl/pliki/repozytorium-plikow/materialy-do-pobrania/pdf/Biuletyn-PPK-06-2025.pdf", D)
SPAP = S("PAP – wygasające deklaracje rezygnacji z PPK i ponowny autozapis", "https://www.pap.pl/aktualnosci/news%2C1542149%2Cuwaga-jutro-wygasaja-deklaracje-o-rezygnacji-z-ppk-co-oznacza", D)

LESSONS = [
    L(1, "Racjonalność ograniczona i heurystyki",
      "Rozumieć, czym racjonalność ograniczona różni się od założenia homo oeconomicus, i rozpoznawać typowe heurystyki oraz błędy poznawcze, w tym efekt zakotwiczenia.",
      ["Racjonalność ograniczona", "Ekonomia behawioralna", "Efekt zakotwiczenia", "Homo oeconomicus"],
      [S63, SKAH],
      explain=[
          K("Racjonalność ograniczona",
            "Herbert Simon zauważył, że ludzie nie mają nieograniczonego czasu, informacji ani mocy obliczeniowej. Zamiast szukać rozwiązania optymalnego, często wybierają „wystarczająco dobre” (satysfakcjonujące). To nie głupota, tylko rozsądna oszczędność wysiłku."),
          K("Heurystyki – skróty myślowe",
            "Heurystyki to proste reguły podejmowania decyzji: „kupuję to, co zawsze”, „wybieram markę, którą znam”. Zwykle działają dobrze, ale prowadzą do systematycznych błędów. Daniel Kahneman i Amos Tversky opisali wiele z nich – za te badania Kahneman otrzymał Nagrodę im. Nobla z ekonomii w 2002 r."),
          K("Efekt zakotwiczenia",
            "Pierwsza liczba, którą widzimy (kotwica), wpływa na późniejsze oceny – nawet jeśli jest przypadkowa. Cena „przed promocją” 499 zł sprawia, że 299 zł wydaje się okazją; propozycja otwierająca negocjacje przesuwa ich wynik."),
          W("Sklep pokazuje przekreśloną cenę 1200 zł obok ceny 799 zł. Jaki efekt wykorzystuje?",
            "Zakotwiczenie", "Efekt Giffena", "Pokusę nadużycia", "Prawo Engla",
            why="Wyższa liczba staje się punktem odniesienia, przez co niższa cena wydaje się atrakcyjniejsza."),
          K("Ekonomia behawioralna nie odrzuca ekonomii",
            "Ekonomia behawioralna łączy ekonomię z psychologią: nadal zakłada, że ludzie reagują na bodźce, ale uwzględnia systematyczne odstępstwa od pełnej racjonalności. Pozwala to lepiej przewidywać zachowania i projektować polityki (np. domyślne opcje)."),
          PF("Racjonalność ograniczona oznacza, że ludzie podejmują decyzje zupełnie przypadkowo.", False,
             why="Oznacza, że kierują się rozsądnymi, uproszczonymi regułami przy ograniczonej informacji i czasie."),
      ],
      mech=[
          KT("Jaki błąd lub heurystyka?",
             {"Zakotwiczenie": ["Pierwsza oferta w negocjacjach mocno wpływa na cenę końcową", "Szacujemy wartość mieszkania, sugerując się ceną wywoławczą"],
              "Dostępność": ["Po głośnej katastrofie lotniczej ludzie przeceniają ryzyko latania", "Oceniamy częstość zjawiska po tym, jak łatwo przypomnieć sobie przykłady"],
              "Nadmierna pewność siebie": ["Większość kierowców uważa się za lepszych od przeciętnego", "Inwestor zbyt często handluje akcjami, wierząc w swoją przewagę"]},
             why="Różne heurystyki prowadzą do różnych, ale przewidywalnych błędów."),
          LN("Ułóż, jak zakotwiczenie działa w negocjacjach płacowych.",
             ["Pracodawca pierwszy podaje kwotę", "Kwota staje się punktem odniesienia", "Kandydat koryguje swoje oczekiwania w jej stronę", "Wynik negocjacji jest bliżej pierwszej oferty"],
             why="Korekta od kotwicy zwykle jest niewystarczająca."),
          W("Restauracja umieszcza w karcie bardzo drogie danie, którego prawie nikt nie zamawia. Po co?",
            "By inne dania wydawały się tańsze (kotwica)", "By zwiększyć koszty", "Z powodu prawa",
            why="Drogie danie zmienia punkt odniesienia klientów."),
          W("Co odróżnia „satysfakcjonowanie” (Simon) od optymalizacji?",
            "Wybór pierwszej opcji spełniającej kryteria zamiast szukania najlepszej", "Wybór zawsze najtańszej opcji", "Brak jakichkolwiek kryteriów",
            why="Przy kosztownym poszukiwaniu opłaca się zatrzymać na rozwiązaniu „wystarczająco dobrym”."),
          PF("Błędy poznawcze są systematyczne, więc można je przewidywać i uwzględniać w modelach.", True,
             why="Na tym opiera się ekonomia behawioralna."),
          M("Które zjawiska bada ekonomia behawioralna?",
            ["Zakotwiczenie", "Awersja do strat", "Prawo podaży w konkurencji doskonałej", "Zbyt duży wpływ teraźniejszości na decyzje"],
            [0, 1, 3],
            why="Prawo podaży to klasyczna teoria, nie odkrycie behawioralne."),
      ],
      calc=[
          LB("Klienci bez kotwicy oceniają wartość zegarka średnio na 400 zł, a po zobaczeniu „ceny katalogowej” 900 zł – na 560 zł. O ile procent kotwica podniosła ocenę?",
             40, "(560-400)/400*100", ["(560 − 400) / 400 = 40%"], unit="%"),
          LB("Szukanie lepszej oferty zajmuje godzinę i daje średnio 30 zł oszczędności. Twój czas jest wart 45 zł/h. O ile zł tracisz, szukając dalej (podaj liczbę dodatnią)?",
             15, "45-30", ["Koszt: 45 zł, korzyść: 30 zł", "Strata: 15 zł – racjonalne jest zatrzymać się na „wystarczająco dobrej” ofercie"], unit="zł"),
          LB("80% kierowców uważa, że jeździ lepiej niż mediana. Jaki maksymalnie procent może mieć rację?",
             50, "50", ["Powyżej mediany jest z definicji co najwyżej 50% osób"], unit="%"),
          LB("Inwestor przeprowadza 200 transakcji rocznie, koszt każdej to 15 zł. Ile płaci rocznie za nadmierną aktywność?",
             3000, "200*15", ["200 · 15 = 3000 zł"], unit="zł"),
          LB("Cena przed promocją 500 zł, w promocji 350 zł. O ile procent obniżono cenę?",
             30, "(500-350)/500*100", ["150 / 500 = 30%"], unit="%"),
          LB("Gdyby cena „przed promocją” była sztucznie zawyżona do 700 zł, jaki „rabat” (w %) zobaczyłby klient przy cenie 350 zł?",
             50, "(700-350)/700*100", ["350 / 700 = 50% – ta sama cena wydaje się większą okazją"], unit="%"),
      ],
      case=[
          PR("W UE sprzedawca ogłaszający obniżkę ceny musi obok podać najniższą cenę z 30 dni przed obniżką. Wcześniej zdarzało się, że sklepy podnosiły cenę na kilka dni przed promocją, by „obniżka” wyglądała na większą.",
             W("Jaki mechanizm wykorzystywało sztuczne podnoszenie cen przed promocją?",
               "Zakotwiczenie na zawyżonej cenie odniesienia", "Efekt Giffena", "Negatywną selekcję",
               why="Zawyżona cena referencyjna sprawia, że obniżka wydaje się atrakcyjniejsza."),
             PF("Obowiązek podawania najniższej ceny z 30 dni ogranicza możliwość manipulowania kotwicą.", True,
                why="Klient widzi rzeczywisty punkt odniesienia."),
             W("Jakie podejście do regulacji to ilustruje?",
               "Poprawa informacji dla konsumenta zamiast kontroli cen", "Cena maksymalna", "Nacjonalizacja handlu",
               why="Regulacja nie ustala cen, tylko wymaga rzetelnej informacji."),
          ),
          PR("W eksperymencie studenci losowali liczbę (od 10 do 65), a potem szacowali procent krajów afrykańskich w ONZ. Osoby, które wylosowały 65, podawały średnio dużo wyższe szacunki niż te, które wylosowały 10.",
             W("Co pokazuje ten eksperyment Tversky’ego i Kahnemana?",
               "Nawet przypadkowa liczba działa jak kotwica", "Studenci znali dokładną odpowiedź", "Liczby nie wpływają na oceny",
               why="Kotwica nie musi mieć żadnego związku z pytaniem."),
             PF("Wynik eksperymentu można wytłumaczyć brakiem wiedzy o geografii u wszystkich badanych.", False,
                why="Brak wiedzy nie tłumaczy, dlaczego oceny przesuwały się w stronę wylosowanej liczby."),
             M("Gdzie zakotwiczenie może mieć znaczenie gospodarcze?",
               ["Negocjacje cen nieruchomości", "Oczekiwania płacowe", "Prawo malejących przychodów", "Prognozy inflacji gospodarstw domowych"],
               [0, 1, 3],
               why="Prawo malejących przychodów to zależność techniczna, nie psychologiczna."),
          ),
      ]),

    L(2, "Teoria perspektywy: straty bolą bardziej",
      "Rozumieć awersję do strat, punkt odniesienia i efekt posiadania oraz ich skutki dla decyzji konsumentów i inwestorów.",
      ["Teoria perspektywy (prospect theory)", "Efekt posiadania (endowment effect)", "Ekonomia behawioralna"],
      [S63, SKAH],
      explain=[
          K("Punkt odniesienia",
            "Według teorii perspektywy (Kahneman i Tversky, 1979) ludzie oceniają wyniki jako zyski lub straty względem punktu odniesienia (np. tego, co już mają, lub tego, czego oczekują), a nie według końcowego poziomu bogactwa."),
          K("Awersja do strat",
            "Strata boli mniej więcej dwa razy bardziej, niż cieszy zysk tej samej wielkości. Dlatego wiele osób odrzuca rzut monetą „wygrywasz 120 zł, przegrywasz 100 zł”, choć ma on dodatnią wartość oczekiwaną."),
          W("Dlaczego wiele osób odrzuca grę: 50% na +110 zł, 50% na −100 zł?",
            "Awersja do strat – potencjalna strata waży więcej niż zysk", "Gra ma ujemną wartość oczekiwaną", "Efekt Veblena",
            why="Wartość oczekiwana to +5 zł, ale strata 100 zł „boli” bardziej, niż cieszy 110 zł."),
          K("Efekt posiadania",
            "Rzeczy, które posiadamy, cenimy wyżej niż takie same rzeczy, których nie mamy. W eksperymentach z kubkami właściciele chcieli za nie średnio około dwa razy więcej, niż kupujący byli gotowi zapłacić. To jeden ze skutków awersji do strat – oddanie rzeczy to strata."),
          K("Zachowania ryzykowne przy stratach",
            "W obszarze zysków ludzie zwykle unikają ryzyka (wolą pewne 500 zł niż 50% na 1000 zł), a w obszarze strat – podejmują je (wolą 50% szans na stratę 1000 zł niż pewną stratę 500 zł). Inwestorzy za długo trzymają tracące akcje, licząc na „odrobienie”."),
          PF("Według teorii perspektywy ludzie oceniają decyzje wyłącznie na podstawie końcowego poziomu majątku.", False,
             why="Kluczowy jest punkt odniesienia i to, czy wynik jest zyskiem, czy stratą."),
      ],
      mech=[
          LN("Ułóż, dlaczego inwestorzy trzymają akcje, które tracą.",
             ["Akcje spadły poniżej ceny zakupu", "Sprzedaż oznaczałaby „zrealizowanie” straty", "Awersja do strat sprawia, że jest to bolesne", "Inwestor czeka, licząc na odbicie", "Często traci jeszcze więcej"],
             why="To tzw. efekt dyspozycji – skutek awersji do strat."),
          KT("Jak większość ludzi wybiera?",
             {"Wybiera pewność": ["Pewne 500 zł zamiast 50% szans na 1000 zł", "Pewny zysk 2000 zł zamiast 25% szans na 9000 zł"],
              "Wybiera ryzyko": ["50% szans na stratę 1000 zł zamiast pewnej straty 500 zł", "25% szans na stratę 9000 zł zamiast pewnej straty 2000 zł"]},
             why="Awersja do ryzyka w zyskach, skłonność do ryzyka w stratach."),
          W("Siłownia oferuje „darmowy miesiąc”, a potem automatycznie pobiera opłaty, chyba że klient zrezygnuje. Jakie efekty wykorzystuje?",
            "Efekt posiadania i bezwładność domyślnej opcji", "Efekt Giffena", "Prawo Engla",
            why="Po miesiącu członkostwo staje się „nasze”, a rezygnacja wymaga wysiłku i odczuwa się ją jak stratę."),
          W("Rząd chce zachęcić do szczepień. Który komunikat będzie silniejszy według teorii perspektywy?",
            "„Nieszczepieni tracą ochronę wartą X zł leczenia”", "„Szczepienie daje korzyść X zł”", "Oba działają identycznie",
            why="Ujęcie w kategoriach straty zwykle działa silniej (efekt ujęcia)."),
          PF("Efekt posiadania sprawia, że sprzedający żądają więcej, niż kupujący są gotowi zapłacić za tę samą rzecz.", True,
             why="Oddanie posiadanej rzeczy odczuwa się jak stratę."),
          M("Gdzie widać awersję do strat?",
            ["Niechęć do sprzedaży mieszkania poniżej ceny zakupu", "Trzymanie tracących akcji", "Kupowanie tańszego dobra, gdy drogie podrożało", "Wysoka skuteczność „zwrotu pieniędzy” w promocjach"],
            [0, 1, 3],
            why="Substytucja przy wzroście ceny to zwykły efekt cenowy."),
      ],
      calc=[
          LB("Gra: 50% na +200 zł, 50% na −150 zł. Ile wynosi wartość oczekiwana?",
             25, "0.5*200-0.5*150", ["0,5 · 200 − 0,5 · 150 = 100 − 75 = 25 zł"], unit="zł"),
          LB("Jeśli strata „waży” 2 razy więcej niż zysk, jaka jest „subiektywna” wartość tej gry (0,5 · 200 − 0,5 · 2 · 150)?",
             -50, "0.5*200-0.5*2*150", ["100 − 150 = −50 – gra jest odrzucana mimo dodatniej wartości oczekiwanej"], unit=""),
          LB("Przy współczynniku awersji do strat 2: jaka minimalna wygrana W sprawi, że gra 50% na +W i 50% na −100 zł będzie akceptowana (0,5W = 0,5 · 2 · 100)?",
             200, "2*100", ["0,5W ≥ 100", "W ≥ 200 zł"], unit="zł"),
          LB("Właściciele kubków chcą za nie średnio 14 zł, a kupujący oferują 7 zł. Ile wynosi stosunek WTA do WTP?",
             2, "14/7", ["14 / 7 = 2"], unit=""),
          LB("Akcje kupiono po 100 zł, teraz kosztują 70 zł. O ile procent musiałyby wzrosnąć, by inwestor „wyszedł na zero”?",
             42.86, "(100-70)/70*100", ["30 / 70 ≈ 42,86% – spadek o 30% wymaga wzrostu o prawie 43%"], unit="%", tol=0.02),
          LB("Abonament za 49 zł/mies. Klient nie rezygnuje przez 8 miesięcy, choć korzysta raz. Ile wydał?",
             392, "8*49", ["8 · 49 = 392 zł"], unit="zł"),
      ],
      case=[
          PR("Ubezpieczyciel testuje dwa komunikaty. A: „Zniżka 200 zł, jeśli przedłużysz polisę online”. B: „Stracisz 200 zł, jeśli nie przedłużysz polisy online”. Kwota i warunki są identyczne.",
             W("Który komunikat według teorii perspektywy zwykle działa silniej?",
               "B – ujęcie jako strata", "A – ujęcie jako zysk", "Oba identycznie",
               why="Awersja do strat sprawia, że groźba straty mocniej motywuje."),
             PF("Racjonalny homo oeconomicus zareagowałby na oba komunikaty tak samo.", True,
                why="Ekonomicznie to ta sama oferta – różni się tylko sformułowanie (ujęcie)."),
             W("Jak nazywa się zjawisko, w którym sposób przedstawienia zmienia decyzję?",
               "Efekt ujęcia (framing)", "Efekt Veblena", "Negatywna selekcja",
               why="Ujęcie tej samej informacji jako zysk lub stratę zmienia wybory."),
          ),
          PR("Pani Anna kupiła mieszkanie za 600 tys. zł. Ceny w okolicy spadły i podobne mieszkania sprzedają się za 520 tys. zł. Mimo że chce się przeprowadzić, odrzuca oferty poniżej 600 tys. zł i od roku nie może sprzedać mieszkania.",
             W("Co jest dla pani Anny punktem odniesienia?",
               "Cena zakupu – 600 tys. zł", "Aktualna wartość rynkowa", "Średnia cena w kraju",
               why="Sprzedaż poniżej ceny zakupu odczuwa jako stratę."),
             LB("Ile wynosi „papierowa” strata, której pani Anna nie chce zrealizować?",
                80, "600-520", ["600 − 520 = 80 tys. zł"], unit="tys. zł"),
             PF("Cena zakupu sprzed lat jest kosztem utopionym i z ekonomicznego punktu widzenia nie powinna wpływać na decyzję o sprzedaży.", True,
                why="Liczy się dzisiejsza wartość i alternatywy, nie historyczna cena."),
          ),
      ]),

    L(3, "Księgowość mentalna i przecenianie teraźniejszości",
      "Rozumieć, jak ludzie dzielą pieniądze na „konta mentalne”, dlaczego przeceniają teraźniejszość i jak to wpływa na oszczędzanie oraz zadłużanie.",
      ["Księgowość mentalna", "Ekonomia behawioralna", "Racjonalność ograniczona"],
      [S63, SNOB],
      explain=[
          K("Konta mentalne",
            "Richard Thaler opisał, że ludzie przypisują pieniądze do różnych „kont” w głowie: wypłata na rachunki, premia na przyjemności, zwrot podatku na wakacje. Ekonomicznie złotówka to złotówka, ale wydajemy ją różnie w zależności od źródła i przeznaczenia. Thaler otrzymał Nagrodę im. Nobla z ekonomii w 2017 r."),
          K("Skutki księgowości mentalnej",
            "Ludzie potrafią jednocześnie trzymać oszczędności na nisko oprocentowanej lokacie „na czarną godzinę” i spłacać drogi kredyt na karcie. Wygrane z kasyna („pieniądze z nieba”) wydają łatwiej niż zarobione."),
          W("Ktoś ma 5000 zł na lokacie na 3% i 5000 zł zadłużenia na karcie na 20%. Co jest racjonalne finansowo?",
            "Spłacić kartę oszczędnościami", "Trzymać obie pozycje", "Zaciągnąć kolejny kredyt",
            why="Spłata długu na 20% daje „zwrot” znacznie wyższy niż lokata na 3%."),
          K("Przecenianie teraźniejszości",
            "Ludzie silniej cenią korzyści „teraz” niż nawet niedużo później: wolą 100 zł dziś niż 110 zł za tydzień, ale 110 zł za 53 tygodnie zamiast 100 zł za 52 tygodnie. Ta niespójność w czasie tłumaczy odkładanie oszczędzania, diety czy nauki „od poniedziałku”."),
          K("Mechanizmy samokontroli",
            "Ludzie świadomi swoich słabości tworzą zobowiązania: stałe zlecenia na oszczędzanie, programy „oszczędzaj więcej jutro” (podwyżki składek przy podwyżkach płac), blokady wypłat. To sposoby na przezwyciężenie przeceniania teraźniejszości."),
          PF("Według standardowej teorii pieniądze z premii i z pensji powinny być wydawane tak samo.", True,
             why="Pieniądz jest zamienny – źródło nie zmienia jego wartości."),
      ],
      mech=[
          KT("Księgowość mentalna czy przecenianie teraźniejszości?",
             {"Księgowość mentalna": ["Zwrot podatku traktowany jako „ekstra” na zakupy", "Odkładanie na lokatę przy jednoczesnym długu na karcie", "Wygrana w loterii wydana szybciej niż pensja"],
              "Przecenianie teraźniejszości": ["Odkładanie oszczędzania na emeryturę „na później”", "Wybór 100 zł dziś zamiast 120 zł za miesiąc", "Zakupy na raty mimo wysokiego oprocentowania"]},
             why="Pierwsze dotyczy podziału pieniędzy, drugie – wyboru w czasie."),
          LN("Ułóż, jak program „oszczędzaj więcej jutro” pokonuje przecenianie teraźniejszości.",
             ["Pracownik dziś zgadza się oszczędzać więcej w przyszłości", "Zobowiązanie nie zmniejsza bieżącej pensji", "Przy każdej podwyżce część trafia na oszczędności", "Pensja netto nie spada – brak poczucia straty", "Stopa oszczędzania stopniowo rośnie"],
             why="Program łączy przecenianie teraźniejszości z awersją do strat."),
          W("Turysta, który zgubił bilet do teatru za 100 zł, rzadziej kupi nowy niż ktoś, kto zgubił 100 zł gotówki. Dlaczego?",
            "Księgowość mentalna – koszt drugiego biletu trafia na to samo „konto teatru”", "Bo bilety są droższe niż gotówka", "Bo teatr jest dobrem niższego rzędu",
            why="W obu przypadkach strata wynosi 100 zł, ale bilet „obciąża konto” rozrywki."),
          W("Dlaczego karty kredytowe zwiększają wydatki w porównaniu z gotówką?",
            "Płacenie jest mniej odczuwalne „teraz”, a koszt przesuwa się w przyszłość", "Karty są dobrem Veblena", "Gotówka ma wyższe oprocentowanie",
            why="Mniejszy „ból płacenia” w chwili zakupu."),
          PF("Stałe zlecenie przelewu na oszczędności w dniu wypłaty jest narzędziem samokontroli.", True,
             why="Odcina pokusę wydania pieniędzy, zanim zostaną odłożone."),
          M("Które działania pomagają przezwyciężyć przecenianie teraźniejszości?",
            ["Automatyczne przelewy na oszczędności", "Domyślny zapis do programu emerytalnego", "Odkładanie decyzji o oszczędzaniu na kolejny rok", "Konto z ograniczeniem wypłat przed terminem"],
            [0, 1, 3],
            why="Odkładanie decyzji to właśnie objaw problemu."),
      ],
      calc=[
          LB("Lokata 5000 zł na 3% i dług 5000 zł na karcie na 20% rocznie. Ile zł rocznie zyska osoba, spłacając dług oszczędnościami?",
             850, "5000*(0.20-0.03)", ["Unikamy odsetek: 1000 zł", "Tracimy odsetki z lokaty: 150 zł", "Zysk: 850 zł"], unit="zł"),
          LB("Wybór: 100 zł dziś albo 110 zł za tydzień. Jaka jest tygodniowa stopa zwrotu z czekania (w %)?",
             10, "(110-100)/100*100", ["10 / 100 = 10% tygodniowo – ponad 140-krotnie więcej w skali roku przy kapitalizacji"], unit="%"),
          LB("Ile wynosi ta stopa w skali roku przy prostym liczeniu (10% · 52 tygodnie)?",
             520, "10*52", ["10% · 52 = 520% rocznie – wybór 100 zł dziś to bardzo „drogie” zniecierpliwienie"], unit="%"),
          LB("Pracownik oszczędza 3% pensji 6000 zł. W programie podnosi stopę o 1 p.p. przy każdej rocznej podwyżce. Ile procent pensji będzie oszczędzał po 4 podwyżkach?",
             7, "3+4*1", ["3% + 4 · 1 p.p. = 7%"], unit="%"),
          LB("Rata „0%” na telewizor 3000 zł w 10 ratach z opłatą przygotowawczą 300 zł. O ile procent faktycznie więcej się płaci?",
             10, "300/3000*100", ["300 / 3000 = 10%"], unit="%"),
          LB("Ktoś „na później” odkłada oszczędzanie 300 zł miesięcznie o 5 lat. Ile wpłat (bez odsetek) nie odłoży w tym czasie?",
             18000, "300*12*5", ["300 · 60 = 18 000 zł – plus utracone odsetki składane"], unit="zł"),
      ],
      case=[
          PR("Rodzina dostaje zwrot podatku 2400 zł i od razu kupuje nową konsolę, choć jednocześnie spłaca kredyt gotówkowy oprocentowany na 15%. Gdy pensja wzrosła o 200 zł miesięcznie, „dla odmiany” część podwyżki odkładają.",
             W("Jakie zjawisko widać w wydaniu zwrotu podatku?",
               "Księgowość mentalna – zwrot traktowany jako „ekstra pieniądze”", "Efekt Giffena", "Prawo Engla",
               why="Zwrot podatku to zwykły dochód, ale trafia na „konto przyjemności”."),
             LB("Ile odsetek rocznie zaoszczędziłaby rodzina, gdyby zwrot przeznaczyła na spłatę kredytu (15%)?",
                360, "2400*0.15", ["2400 · 0,15 = 360 zł"], unit="zł"),
             PF("Z punktu widzenia standardowej teorii pieniądze ze zwrotu podatku i z pensji są całkowicie zamienne.", True,
                why="Źródło dochodu nie zmienia wartości złotówki."),
          ),
          PR("Badania pokazują, że ludzie częściej wybierają dziś zdrową przekąskę na przyszły tydzień, ale gdy przyjdzie ten dzień – wybierają słodycze. Podobnie deklarują oszczędzanie „od przyszłego roku”.",
             W("Jak nazywa się ta niespójność preferencji w czasie?",
               "Przecenianie teraźniejszości (dyskontowanie hiperboliczne)", "Efekt snoba", "Pokusa nadużycia",
               why="Teraźniejszość ma nieproporcjonalnie dużą wagę."),
             M("Jakie narzędzia mogą pomóc takim osobom?",
               ["Zobowiązania podjęte z wyprzedzeniem", "Automatyczne oszczędzanie", "Wyższa dostępność słodyczy w pracy", "Ograniczenie łatwego dostępu do pokus"],
               [0, 1, 3],
               why="Większa dostępność pokus pogłębia problem."),
             PF("Osoba świadoma swojej niecierpliwości może racjonalnie ograniczać własny wybór w przyszłości.", True,
                why="Jak Odyseusz przywiązany do masztu – zobowiązanie chroni przed pokusą."),
          ),
      ]),

    L(4, "Szturchanie (nudge) i architektura wyboru – przykład PPK",
      "Rozumieć ideę „szturchania” i opcji domyślnych, oceniać ich zalety i granice na przykładzie Pracowniczych Planów Kapitałowych (autozapis z możliwością rezygnacji).",
      ["Teoria szturchania (nudge)", "Libertarianizm i libertariański paternalizm", "Racjonalność ograniczona"],
      [SNOB, SPPK, SPAP],
      explain=[
          K("Czym jest szturchanie",
            "Szturchanie (nudge) to taki sposób przedstawienia wyboru, który zmienia zachowanie w przewidywalny sposób, nie zakazując żadnej opcji i nie zmieniając istotnie bodźców finansowych. Przykłady: domyślne zapisanie do programu, kolejność produktów w stołówce, informacja o zużyciu prądu przez sąsiadów."),
          K("Siła opcji domyślnej",
            "Ludzie często zostają przy opcji domyślnej – z bezwładności, braku czasu albo traktując ją jako rekomendację. Dlatego w krajach z domniemaną zgodą na dawstwo narządów odsetek dawców jest dużo wyższy niż tam, gdzie trzeba się zapisać."),
          K("PPK – autozapis",
            "W Pracowniczych Planach Kapitałowych pracownik w wieku 18–54 lata jest zapisywany automatycznie, ale może złożyć deklarację rezygnacji. Co 4 lata pracodawca ponownie zapisuje osoby, które zrezygnowały (np. w 2023 i 2027 r.), chyba że znów złożą deklarację. Według Ewidencji PPK na 31 maja 2025 r. partycypacja wynosiła 53,18%."),
          W("Na czym polega „libertariański” element szturchania?",
            "Każdy może wybrać inaczej – nic nie jest zakazane", "Państwo zakazuje rezygnacji", "Firmy płacą za decyzje klientów",
            why="Szturchanie zachowuje wolność wyboru."),
          K("Granice i krytyka",
            "Krytycy wskazują, że szturchanie może być manipulacją, a decydent nie zawsze wie, co jest dla ludzi najlepsze. Firmy stosują też „ciemne wzorce” (dark patterns) – utrudnianie rezygnacji z subskrypcji. Ważna jest przejrzystość i łatwość wyboru innej opcji."),
          PF("Szturchanie polega na wprowadzaniu wysokich kar za niepożądane zachowania.", False,
             why="Szturchanie nie zmienia znacząco bodźców finansowych ani nie zakazuje opcji – zmienia sposób przedstawienia wyboru."),
      ],
      mech=[
          KT("Szturchanie czy klasyczne narzędzie?",
             {"Szturchanie": ["Owoce na wysokości oczu w szkolnym sklepiku", "Domyślne zapisanie do programu oszczędnościowego", "Rachunek za prąd z porównaniem do zużycia sąsiadów"],
              "Klasyczne narzędzie (zakaz, podatek, dotacja)": ["Zakaz sprzedaży napojów energetycznych nieletnim", "Akcyza na tytoń", "Dopłata do pompy ciepła"]},
             why="Szturchanie nie zakazuje i nie zmienia istotnie cen – zmienia kontekst wyboru."),
          LN("Ułóż, dlaczego autozapis zwiększa uczestnictwo w programie oszczędnościowym.",
             ["Pracownik jest zapisany automatycznie", "Rezygnacja wymaga wypełnienia deklaracji", "Część osób nie podejmuje działania z bezwładności lub braku czasu",
              "Część traktuje opcję domyślną jak rekomendację", "Uczestnictwo jest wyższe niż przy zapisie na wniosek"],
             why="Opcja domyślna działa przez bezwładność i sygnał rekomendacji."),
          W("Serwis ukrywa przycisk rezygnacji z subskrypcji w kilku podmenu. Jak to ocenić?",
            "To „ciemny wzorzec” wykorzystujący bezwładność wbrew interesowi klienta", "To klasyczna cena minimalna", "To dobre szturchanie",
            why="Szturchanie ma ułatwiać korzystne wybory, a nie utrudniać rezygnację."),
          W("Dlaczego co 4 lata w PPK następuje ponowny autozapis?",
            "By osoby, które zrezygnowały, ponownie znalazły się w opcji domyślnej i świadomie podjęły decyzję", "By ukarać pracowników", "Z powodu inflacji",
            why="Ponowny autozapis wykorzystuje siłę opcji domyślnej, zostawiając możliwość rezygnacji."),
          PF("Ten sam wybór może dać inne wyniki zależnie od tego, która opcja jest domyślna.", True,
             why="To główne odkrycie stojące za architekturą wyboru."),
          M("Jakie warunki powinno spełniać „etyczne” szturchanie?",
            ["Przejrzystość", "Łatwa rezygnacja", "Ukrycie informacji o opcjach", "Cel zgodny z interesem osoby szturchanej"],
            [0, 1, 3],
            why="Ukrywanie informacji to manipulacja, nie szturchanie."),
      ],
      calc=[
          LB("W firmie 400 osób kwalifikuje się do PPK. Przy partycypacji 53,18% ile osób (w przybliżeniu, zaokrąglij) oszczędza?",
             213, "round(400*0.5318)", ["400 · 0,5318 ≈ 212,7 ≈ 213 osób"], unit="os.", tol=0.5),
          LB("Przy zapisie „na wniosek” uczestniczy 20% pracowników, a przy autozapisie 53%. O ile punktów procentowych autozapis zwiększa uczestnictwo?",
             33, "53-20", ["53 − 20 = 33 p.p."], unit="p.p."),
          LB("Pensja 6000 zł brutto, podstawowa wpłata pracownika do PPK 2%, pracodawcy 1,5%. Ile łącznie trafia miesięcznie na rachunek (bez dopłat państwa)?",
             210, "6000*(0.02+0.015)", ["6000 · 3,5% = 210 zł"], unit="zł"),
          LB("Z tej kwoty ile wpłaca pracodawca (1,5% z 6000 zł)?",
             90, "6000*0.015", ["6000 · 0,015 = 90 zł – „darmowe” pieniądze tracone przy rezygnacji"], unit="zł"),
          LB("Ile rocznie wynosi wpłata pracodawcy (90 zł miesięcznie)?",
             1080, "90*12", ["90 · 12 = 1080 zł"], unit="zł"),
          LB("Rachunek za prąd z porównaniem do sąsiadów obniżył zużycie o 2%. Gospodarstwo zużywało 1800 kWh. O ile kWh mniej zużywa?",
             36, "1800*0.02", ["1800 · 0,02 = 36 kWh"], unit="kWh"),
      ],
      case=[
          PR("PPK wprowadzono z automatycznym zapisem pracowników w wieku 18–54 lat i możliwością rezygnacji. Według danych z Ewidencji PPK (31 maja 2025 r.) partycypacja wyniosła 53,18%. Co 4 lata osoby, które zrezygnowały, są ponownie zapisywane, chyba że złożą nową deklarację.",
             W("Dlaczego zastosowano autozapis zamiast dobrowolnego zapisu na wniosek?",
               "Opcja domyślna zwiększa uczestnictwo dzięki bezwładności", "Prawo zabrania dobrowolnych programów", "Autozapis jest tańszy dla pracodawców",
               why="To klasyczne zastosowanie architektury wyboru."),
             PF("Autozapis w PPK jest przykładem libertariańskiego paternalizmu – pracownik może zrezygnować.", True,
                why="Opcja jest domyślna, ale nie przymusowa."),
             M("Jakie czynniki mogą tłumaczyć, że mimo autozapisu prawie połowa osób rezygnuje?",
               ["Niski bieżący dochód i potrzeba pieniędzy teraz", "Brak zaufania do programów emerytalnych", "Brak możliwości rezygnacji", "Niewiedza o wpłatach pracodawcy"],
               [0, 1, 3],
               why="Rezygnacja jest możliwa – na tym polega szturchanie."),
          ),
          PR("Stołówka szkolna przestawia jedzenie: warzywa i owoce na początku lady na wysokości oczu, słodkie desery na końcu. Ceny i oferta się nie zmieniają. Po miesiącu sprzedaż owoców wzrosła o 25%.",
             W("Jakie narzędzie zastosowano?",
               "Szturchanie – zmiana architektury wyboru", "Podatek Pigou", "Zakaz sprzedaży deserów",
               why="Oferta i ceny są te same, zmienił się kontekst wyboru."),
             LB("Wcześniej sprzedawano 160 porcji owoców tygodniowo. Ile sprzedaje się teraz (+25%)?",
                200, "160*1.25", ["160 · 1,25 = 200 porcji"], unit="porcji"),
             PF("Uczniowie nadal mogą kupić deser – dlatego to nie jest zakaz.", True,
                why="Szturchanie zachowuje swobodę wyboru."),
          ),
      ]),

    L(5, "Efekt substytucyjny i dochodowy w praktyce oraz gospodarka współdzielenia",
      "Stosować rozróżnienie efektu substytucyjnego i dochodowego do realnych decyzji oraz rozumieć ekonomię platform i gospodarki współdzielenia: koszty transakcyjne, reputację i efekty sieciowe.",
      ["Efekt substytucyjny i efekt dochodowy", "Gospodarka współdzielenia (sharing economy) i peer economy"],
      [S62, S("OpenStax, Principles of Economics 3e, 16.1 Imperfect and Asymmetric Information (reputation)", OS3 + "16-1-the-problem-of-imperfect-information-and-asymmetric-information", D)],
      explain=[
          K("Dwa efekty w codziennych decyzjach",
            "Gdy drożeje benzyna: efekt substytucyjny – relatywnie tańsza staje się komunikacja i rower; efekt dochodowy – za tę samą pensję stać nas na mniej, więc ograniczamy różne wydatki. Rozdzielenie efektów pomaga zrozumieć, dlaczego rekompensaty dla gospodarstw nie znoszą zachęty do oszczędzania."),
          K("Gospodarka współdzielenia",
            "Platformy (najem krótkoterminowy, przewozy, wynajem narzędzi) pozwalają lepiej wykorzystać zasoby, które często stoją bezczynnie – samochód czy wolny pokój. Kluczowe jest obniżenie kosztów transakcyjnych: łatwe znalezienie kontrahenta, płatność, oceny."),
          W("Co jest główną innowacją ekonomiczną platform współdzielenia?",
            "Obniżenie kosztów transakcyjnych i asymetrii informacji (oceny, płatności)", "Wynalezienie samochodu", "Zakaz konkurencji",
            why="Platforma łączy obce osoby i buduje zaufanie przez reputację."),
          K("Efekty sieciowe",
            "Platforma jest tym cenniejsza, im więcej ma użytkowników po obu stronach (kierowców i pasażerów, gospodarzy i gości). To sprzyja koncentracji – rynek „przechyla się” w stronę jednej lub dwóch platform, co rodzi pytania o siłę rynkową."),
          K("Spory i regulacje",
            "Najem krótkoterminowy może podnosić czynsze w centrach miast (efekt zewnętrzny dla mieszkańców), a przewozy przez aplikacje – rodzić spory o status pracowników. Państwa wprowadzają rejestry najmu, limity dni czy obowiązki informacyjne platform."),
          PF("Efekty sieciowe sprawiają, że nowej platformie łatwo konkurować z dużą, ugruntowaną platformą.", False,
             why="Przeciwnie – użytkownicy wybierają platformę, na której już są inni, co tworzy barierę wejścia."),
      ],
      mech=[
          LN("Ułóż, jak efekty sieciowe wzmacniają platformę przewozową.",
             ["Więcej pasażerów korzysta z aplikacji", "Kierowcom opłaca się dołączyć – mniej czasu bez kursu", "Czas oczekiwania na przejazd się skraca", "Aplikacja staje się atrakcyjniejsza dla kolejnych pasażerów", "Platforma rośnie szybciej niż konkurenci"],
             why="To pętla dodatnich efektów sieciowych."),
          KT("Efekt substytucyjny czy dochodowy po wzroście cen biletów lotniczych?",
             {"Substytucyjny": ["Więcej osób wybiera pociąg zamiast samolotu", "Wakacje bliżej domu zamiast lotu za granicę"],
              "Dochodowy": ["Rodzina ogranicza także inne wydatki, bo jest realnie biedniejsza", "Mniej wyjść do restauracji, by zmieścić się w budżecie"]},
             why="Substytucja to zmiana proporcji dóbr; dochodowy – spadek realnej siły nabywczej."),
          W("Dlaczego oceny na platformach są tak ważne?",
            "Ograniczają asymetrię informacji między obcymi osobami", "Podnoszą koszty transakcyjne", "Są wymagane przez prawo podatkowe",
            why="Reputacja zastępuje osobistą znajomość i gwarancje."),
          W("Duża liczba mieszkań w centrum przeznaczona na najem krótkoterminowy podnosi czynsze dla mieszkańców. Jakie to zjawisko?",
            "Efekt zewnętrzny i zmiana podaży mieszkań na wynajem długoterminowy", "Efekt Giffena", "Pokusa nadużycia",
            why="Część mieszkań znika z rynku najmu długoterminowego, co podnosi jego ceny."),
          PF("Gospodarka współdzielenia zwiększa wykorzystanie zasobów, które wcześniej często stały bezczynnie.", True,
             why="Np. samochód prywatny stoi przez większość doby."),
          M("Jakie problemy regulacyjne wiążą się z platformami?",
            ["Status zatrudnienia osób pracujących przez aplikacje", "Wpływ najmu krótkoterminowego na czynsze", "Brak jakichkolwiek kosztów transakcyjnych", "Siła rynkowa dominujących platform"],
            [0, 1, 3],
            why="Koszty transakcyjne spadają, ale nie znikają."),
      ],
      calc=[
          LB("Samochód kosztuje właściciela 1200 zł miesięcznie (koszty stałe) i jest używany 40 h w miesiącu. Ile wynosi koszt stały na godzinę używania?",
             30, "1200/40", ["1200 / 40 = 30 zł/h"], unit="zł"),
          LB("Gdyby dzięki wynajmowi przez platformę auto było używane 120 h, ile wyniósłby koszt stały na godzinę?",
             10, "1200/120", ["1200 / 120 = 10 zł/h – lepsze wykorzystanie obniża koszt przeciętny"], unit="zł"),
          LB("Paliwo drożeje o 20%. Rodzina wydawała 600 zł miesięcznie na paliwo. Ile musiałaby wydać więcej, tankując tyle samo?",
             120, "600*0.2", ["600 · 0,2 = 120 zł – to miara efektu dochodowego (spadek realnej siły nabywczej)"], unit="zł"),
          LB("Platforma pobiera 20% prowizji od kursu za 50 zł. Ile dostaje kierowca?",
             40, "50*0.8", ["50 · 0,8 = 40 zł"], unit="zł"),
          LB("Na platformie jest n użytkowników; liczba możliwych połączeń między nimi to n(n − 1)/2. Ile połączeń przy 100 użytkownikach?",
             4950, "100*99/2", ["100 · 99 / 2 = 4950 – wartość sieci rośnie szybciej niż liczba użytkowników"], unit=""),
          LB("Gospodarz wynajmuje pokój 10 nocy w miesiącu po 180 zł, płacąc platformie 15%. Ile zarabia miesięcznie?",
             1530, "10*180*0.85", ["10 · 180 = 1800 zł", "Po prowizji: 1800 · 0,85 = 1530 zł"], unit="zł"),
      ],
      case=[
          PR("W dużym mieście turystycznym 8% mieszkań w ścisłym centrum wynajmuje się krótkoterminowo przez platformy. Mieszkańcy skarżą się na hałas i rosnące czynsze. Miasto rozważa limit 90 dni najmu krótkoterminowego rocznie dla jednego mieszkania.",
             W("Jaki efekt na rynku najmu długoterminowego wywołał rozwój najmu krótkoterminowego?",
               "Zmniejszył podaż mieszkań na wynajem długoterminowy, podnosząc czynsze", "Zwiększył podaż mieszkań", "Nie miał wpływu",
               why="Mieszkania przeniesione do najmu krótkoterminowego znikają z rynku długoterminowego."),
             W("Czym jest hałas w kamienicy w języku ekonomii?",
               "Negatywnym efektem zewnętrznym", "Dobrem publicznym", "Kosztem utopionym",
               why="Koszt ponoszą sąsiedzi, którzy nie biorą udziału w transakcji."),
             PF("Limit dni najmu może część mieszkań przywrócić na rynek najmu długoterminowego.", True,
                why="Przy limicie najem krótkoterminowy staje się mniej opłacalny dla części właścicieli."),
          ),
          PR("Nowa aplikacja przewozowa ma niższą prowizję niż lider rynku, ale w mieście ma tylko kilkuset kierowców. Pasażerowie czekają na nią średnio 12 minut, a w aplikacji lidera – 3 minuty.",
             W("Dlaczego niższa prowizja nie wystarcza, by szybko przejąć rynek?",
               "Efekty sieciowe – mało kierowców oznacza długie oczekiwanie i mało pasażerów", "Prowizja nie ma znaczenia", "Kierowcy zawsze wybierają wyższą prowizję",
               why="Wartość platformy zależy od liczby użytkowników po obu stronach."),
             M("Jakie strategie może zastosować nowa aplikacja?",
               ["Premie dla kierowców za dołączenie", "Skupienie na jednej dzielnicy lub lotnisku", "Podniesienie cen dla pasażerów od razu", "Rabaty dla pierwszych pasażerów"],
               [0, 1, 3],
               why="Podwyżka cen na starcie zniechęciłaby pasażerów i pogłębiła problem."),
             PF("Rynki z silnymi efektami sieciowymi często zmierzają do koncentracji.", True,
                why="Użytkownicy grupują się tam, gdzie są inni."),
          ),
      ]),
]
