# -*- coding: utf-8 -*-
# Zrozumienie – Mikroekonomia / Efektywność, zawodności rynku i państwa
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S35 = S("OpenStax, Principles of Economics 3e, 3.5 Demand, Supply, and Efficiency", OS3 + "3-5-demand-supply-and-efficiency", D)
S84 = S("OpenStax, Principles of Economics 3e, 8.4 Efficiency in Perfectly Competitive Markets", OS3 + "8-4-efficiency-in-perfectly-competitive-markets", D)
S121 = S("OpenStax, Principles of Economics 3e, 12.1 The Economics of Pollution", OS3 + "12-1-the-economics-of-pollution", D)
S122 = S("OpenStax, Principles of Economics 3e, 12.2 Command-and-Control Regulation", OS3 + "12-2-command-and-control-regulation", D)
S123 = S("OpenStax, Principles of Economics 3e, 12.3 Market-Oriented Environmental Tools", OS3 + "12-3-market-oriented-environmental-tools", D)
S133 = S("OpenStax, Principles of Economics 3e, 13.3 Public Goods", OS3 + "13-3-public-goods", D)
S161 = S("OpenStax, Principles of Economics 3e, 16.1 Imperfect and Asymmetric Information", OS3 + "16-1-the-problem-of-imperfect-information-and-asymmetric-information", D)
S162 = S("OpenStax, Principles of Economics 3e, 16.2 Insurance and Imperfect Information", OS3 + "16-2-insurance-and-imperfect-information", D)
S182 = S("OpenStax, Principles of Economics 3e, 18.2 Special Interest Politics", OS3 + "18-2-special-interest-politics", D)
S183 = S("OpenStax, Principles of Economics 3e, 18.3 Flaws in the Democratic System", OS3 + "18-3-flaws-in-the-democratic-system-of-government", D)
S114 = S("OpenStax, Principles of Economics 3e, 11.4 The Great Deregulation Experiment", OS3 + "11-4-the-great-deregulation-experiment", D)
S155 = S("OpenStax, Principles of Economics 3e, 15.5 Policies to Reduce Income Inequality", OS3 + "15-5-government-policies-to-reduce-income-inequality", D)

Z122 = S("OpenStax, Principles of Economics 3e, 12.2 Command-and-Control Regulation", OS3 + "12-2-command-and-control-regulation", D)
Z123 = S("OpenStax, Principles of Economics 3e, 12.3 Market-Oriented Environmental Tools", OS3 + "12-3-market-oriented-environmental-tools", D)
ZETS = S("Komisja Europejska – EU Emissions Trading System (EU ETS)", "https://climate.ec.europa.eu/eu-action/eu-emissions-trading-system-eu-ets_en", D)
Z133 = S("OpenStax, Principles of Economics 3e, 13.3 Public Goods", OS3 + "13-3-public-goods", D)

LESSONS = [
    L(1, "Efektywność: Pareto, alokacja i produkcja",
      "Rozumieć różne rodzaje efektywności (Pareto, alokacyjna, produkcyjna, X-efektywność), odróżniać efektywność od sprawiedliwości i wiedzieć, czym jest zawodność rynku.",
      ["Optimum Pareto (efektywność w sensie Pareto)", "Efektywność alokacyjna, produkcyjna i X-efektywność", "Zawodność rynku (market failure)",
       "Równowaga ogólna i cząstkowa"],
      [S35, S84],
      explain=[
          K("Optimum Pareto",
            "Sytuacja jest efektywna w sensie Pareto, jeśli nie da się nikomu poprawić położenia bez pogorszenia położenia kogoś innego. Zmiana, która komuś pomaga i nikomu nie szkodzi, to usprawnienie w sensie Pareto."),
          K("Efektywność alokacyjna i produkcyjna",
            "Efektywność produkcyjna: dobra wytwarzane są najniższym kosztem (na krzywej możliwości produkcyjnych, przy min ATC). Efektywność alokacyjna: produkuje się to, czego ludzie najbardziej chcą, w odpowiednich ilościach (P = MC – wartość ostatniej jednostki dla kupującego równa jej kosztowi). X-efektywność (Leibenstein): czy firma rzeczywiście wykorzystuje swoje możliwości, czy marnuje je przez brak presji konkurencji."),
          W("Rynek doskonale konkurencyjny w długim okresie spełnia warunek P = MC = min ATC. Co to oznacza?",
            "Efektywność alokacyjną i produkcyjną", "Tylko efektywność produkcyjną", "Brak efektywności",
            why="P = MC – alokacyjna, P = min ATC – produkcyjna."),
          K("Efektywność to nie sprawiedliwość",
            "Optimum Pareto może być bardzo nierówne: sytuacja, w której jedna osoba ma wszystko, też jest efektywna (każda zmiana komuś zaszkodzi). Ocena podziału dochodów wymaga sądów normatywnych – efektywność ich nie zastępuje."),
          K("Zawodności rynku",
            "Rynek nie zawsze prowadzi do efektywnego wyniku. Główne zawodności: siła rynkowa (monopol), efekty zewnętrzne, dobra publiczne, asymetria informacji. Wtedy interwencja państwa może poprawić wynik – ale państwo też bywa zawodne."),
          PF("Każda sytuacja efektywna w sensie Pareto jest sprawiedliwa.", False,
             why="Pareto mówi o braku marnotrawstwa, nie o sprawiedliwym podziale."),
      ],
      mech=[
          KT("Która zmiana jest usprawnieniem w sensie Pareto?",
             {"Usprawnienie Pareto": ["Dwie osoby dobrowolnie wymieniają się biletami, obie zadowolone", "Rozdanie niewykorzystanego jedzenia, które i tak by zmarnowano", "Nowy most finansowany z opłat użytkowników, z którego korzystają chętni"],
              "Nie jest usprawnieniem Pareto": ["Podatek od bogatych na rzecz biednych", "Zamknięcie fabryki, z której część pracowników traci pracę", "Wywłaszczenie działki pod drogę bez odszkodowania"]},
             why="Usprawnienie Pareto nikomu nie szkodzi."),
          LN("Ułóż, dlaczego brak konkurencji obniża X-efektywność.",
             ["Firma ma pozycję monopolu", "Nie grozi jej utrata klientów", "Menedżerowie i pracownicy mają słabszą presję na ograniczanie kosztów", "Koszty są wyższe niż technicznie możliwe", "Powstaje X-nieefektywność"],
             why="Konkurencja dyscyplinuje firmy do wykorzystywania możliwości."),
          W("Gospodarka produkuje dużo czołgów najtańszym sposobem, choć ludzie wolą więcej żywności. Jakiej efektywności brakuje?",
            "Alokacyjnej", "Produkcyjnej", "Żadnej",
            why="Produkcja jest tania, ale nie odpowiada preferencjom."),
          W("Analiza równowagi cząstkowej w porównaniu z ogólną:",
            "Bada jeden rynek, zakładając resztę gospodarki bez zmian", "Bada wszystkie rynki naraz", "Nie używa krzywych popytu",
            why="Równowaga ogólna (Walras) uwzględnia powiązania wszystkich rynków."),
          PF("Strata martwa monopolu oznacza brak efektywności alokacyjnej.", True,
             why="Przy P > MC część transakcji korzystnych dla obu stron nie dochodzi do skutku."),
          M("Które zjawiska są zawodnościami rynku?",
            ["Zanieczyszczenie powietrza przez fabrykę", "Brak prywatnego finansowania latarni morskich", "Wysoka cena wynikająca z rzadkości surowca", "Ukrywanie wad używanych aut przez sprzedawców"],
            [0, 1, 3],
            why="Wysoka cena rzadkiego dobra to poprawny sygnał rynku, nie zawodność."),
      ],
      calc=[
          LB("Kupujący ceni ostatnią sztukę na 50 zł, a jej koszt krańcowy wynosi 35 zł. O ile zł wzrosłaby nadwyżka całkowita, gdyby ją wyprodukować i sprzedać?",
             15, "50-35", ["Korzyść − koszt = 50 − 35 = 15 zł – produkcja jest za mała"], unit="zł"),
          LB("Ostatnia sztuka kosztuje 60 zł, a kupujący ceni ją na 40 zł. O ile zł jej produkcja obniża nadwyżkę?",
             20, "60-40", ["60 − 40 = 20 zł – produkcja jest za duża"], unit="zł"),
          LB("Firma X może wyprodukować 1000 szt. po 20 zł, a przez marnotrawstwo produkuje po 23 zł. Ile wynosi strata z X-nieefektywności?",
             3000, "1000*(23-20)", ["(23 − 20) · 1000 = 3000 zł"], unit="zł"),
          LB("Ania ma 10 jabłek i 0 gruszek, Bartek 0 jabłek i 10 gruszek. Ania wymienia 4 jabłka na 4 gruszki. Ile owoców ma po wymianie Ania (łącznie)?",
             10, "10-4+4", ["6 jabłek + 4 gruszki = 10 – liczba owoców bez zmian, ale oboje wolą zróżnicowany koszyk"], unit="szt."),
          LB("Popyt P = 100 − Q, koszt krańcowy stały 40 zł. Ile wynosi efektywna (alokacyjnie) ilość?",
             60, "100-40", ["P = MC ⇒ 100 − Q = 40 ⇒ Q = 60"], unit="szt."),
          LB("Przy tej samej ilości efektywnej (P = 100 − Q, MC = 40, Q = 60) ile wynosi nadwyżka całkowita?",
             1800, "0.5*(100-40)*60", ["½ · (100 − 40) · 60 = 1800 zł"], unit="zł"),
      ],
      case=[
          PR("Państwowa firma telekomunikacyjna przez lata była jedynym dostawcą usług. Po otwarciu rynku na konkurencję w ciągu kilku lat spadły ceny, skrócił się czas oczekiwania na instalację, a firma zwolniła część administracji, nie zmniejszając liczby obsługiwanych klientów.",
             W("Jaki rodzaj nieefektywności zmniejszyła konkurencja w samej firmie?",
               "X-nieefektywność", "Nieefektywność Pareto w handlu zagranicznym", "Nieefektywność dóbr publicznych",
               why="Firma obsługiwała tyle samo klientów niższym kosztem – wcześniej marnowała możliwości."),
             W("Co spadek cen oznacza dla efektywności alokacyjnej?",
               "Cena zbliżyła się do kosztu krańcowego – mniejsza strata martwa", "Jest bez znaczenia", "Efektywność spadła",
               why="Niższa cena zwiększa ilość do poziomu bliższego efektywnemu."),
             PF("Zwolnienia w administracji nie były usprawnieniem w sensie Pareto, bo część osób straciła pracę.", True,
                why="Pareto wymaga, by nikt nie stracił; tu zyski klientów przewyższyły straty, ale nie każdy zyskał."),
          ),
          PR("Gmina musi zdecydować, czy wybudować obwodnicę. Korzyści dla kierowców i mieszkańców centrum szacuje się na 80 mln zł, a koszty (budowa i straty mieszkańców przy nowej trasie) na 60 mln zł.",
             W("Czy budowa jest usprawnieniem w sensie Pareto?",
               "Nie – mieszkańcy przy nowej trasie tracą", "Tak – korzyści przewyższają koszty", "Nie da się ocenić",
               why="Kryterium Pareto wymaga, by nikt nie stracił."),
             W("Jak można by przekształcić projekt w usprawnienie Pareto?",
               "Wypłacić poszkodowanym odszkodowania z części korzyści", "Ukryć koszty", "Zrezygnować z analizy",
               why="Skoro korzyści (80) > koszty (60), można zrekompensować przegranych (kryterium Kaldora-Hicksa + faktyczna rekompensata)."),
             LB("Ile wynosi korzyść netto projektu dla społeczności?",
                20, "80-60", ["80 − 60 = 20 mln zł"], unit="mln zł"),
          ),
      ]),

    L(2, "Efekty zewnętrzne i jak je internalizować",
      "Rozpoznawać pozytywne i negatywne efekty zewnętrzne, rozumieć, dlaczego rynek produkuje wtedy niewłaściwą ilość, i porównywać narzędzia: podatek Pigou, dotacja, regulacja nakazowa, handel uprawnieniami.",
      ["Efekty zewnętrzne (externalities)", "Internalizacja efektów zewnętrznych", "Podatek Pigou", "Koszt społeczny"],
      [S121, S122, S123],
      explain=[
          K("Koszt prywatny a społeczny",
            "Efekt zewnętrzny pojawia się, gdy działanie wpływa na osoby trzecie, które za to nie płacą ani nie dostają zapłaty. Fabryka zanieczyszczająca rzekę nie płaci rybakom – jej koszt prywatny jest niższy od kosztu społecznego.",
            w="koszt społeczny = koszt prywatny + koszt zewnętrzny"),
          K("Negatywne – za dużo, pozytywne – za mało",
            "Przy negatywnych efektach (zanieczyszczenia, hałas) rynek produkuje za dużo, bo producenci nie płacą pełnego kosztu. Przy pozytywnych (szczepienia, edukacja, badania) – za mało, bo część korzyści trafia do innych, a nie do kupującego.",
            g=G("sd", names={"S": "koszt prywatny (podaż)"}, S=-1)),
          W("Szczepienie chroni nie tylko zaszczepionego, ale i otoczenie. Co zrobi rynek bez interwencji?",
            "Wytworzy za mało szczepień", "Wytworzy za dużo szczepień", "Wytworzy ilość efektywną",
            why="Kupujący nie uwzględnia korzyści innych – pozytywny efekt zewnętrzny."),
          K("Podatek Pigou",
            "Arthur Pigou zaproponował podatek równy kosztowi zewnętrznemu na jednostkę. Producent „widzi” wtedy pełny koszt i sam ogranicza produkcję do poziomu efektywnego. Przy pozytywnych efektach analogiczne narzędzie to dotacja."),
          K("Regulacje kontra narzędzia rynkowe",
            "Regulacja nakazowa (np. limit emisji dla każdej fabryki) jest prosta, ale nie uwzględnia różnic kosztów. Podatki i handel uprawnieniami (w UE – system EU ETS) sprawiają, że emisje ograniczają ci, którzy robią to najtaniej – ten sam efekt mniejszym kosztem."),
          PF("Celem podatku Pigou jest całkowite wyeliminowanie zanieczyszczeń.", False,
             why="Celem jest efektywny poziom, przy którym korzyść z dodatkowej produkcji równa się pełnemu kosztowi społecznemu."),
      ],
      mech=[
          WY("Na producentów cementu nałożono podatek równy kosztowi zanieczyszczeń. Co dzieje się na rynku?",
             G("sd", names={"S": "podaż cementu"}, S=-1), "Podaż maleje, cena rośnie, produkcja spada do efektywnego poziomu",
             "Popyt rośnie", "Podaż rośnie, cena spada", "Nic się nie zmienia",
             why="Podatek dodaje koszt zewnętrzny do kosztu prywatnego."),
          KT("Efekt zewnętrzny pozytywny czy negatywny?",
             {"Pozytywny": ["Pszczelarz, którego pszczoły zapylają sad sąsiada", "Odnowiona elewacja kamienicy podnosi wartość okolicy", "Badania naukowe wykorzystywane przez inne firmy"],
              "Negatywny": ["Głośna muzyka sąsiada w nocy", "Spaliny z samochodów", "Korki powodowane przez każdego dodatkowego kierowcę"]},
             why="Pozytywny – korzyści dla innych; negatywny – koszty dla innych."),
          LN("Ułóż, jak handel uprawnieniami do emisji obniża koszt redukcji.",
             ["Państwo ustala łączny limit emisji i rozdziela uprawnienia", "Firmy o niskim koszcie redukcji ograniczają emisje", "Sprzedają zbędne uprawnienia",
              "Firmy o wysokim koszcie redukcji kupują uprawnienia", "Łączny limit zostaje osiągnięty najmniejszym kosztem"],
             why="Redukcja odbywa się tam, gdzie jest najtańsza."),
          W("Dlaczego dotacja do zakupu książek przez szkoły może być uzasadniona ekonomicznie?",
            "Edukacja daje pozytywne efekty zewnętrzne dla społeczeństwa", "Książki są dobrem niższego rzędu", "Podaż książek jest pionowa",
            why="Dotacja zwiększa ilość do poziomu efektywnego przy pozytywnych efektach."),
          PF("Przy negatywnym efekcie zewnętrznym cena rynkowa jest niższa niż cena odzwierciedlająca pełny koszt społeczny.", True,
             why="Producent nie płaci kosztu zewnętrznego, więc oferuje taniej."),
          M("Które narzędzia mogą internalizować negatywny efekt zewnętrzny?",
            ["Podatek od jednostki zanieczyszczenia", "Handel uprawnieniami do emisji", "Dotacja do produkcji zanieczyszczającej", "Przypisanie praw własności i negocjacje (Coase)"],
            [0, 1, 3],
            why="Dotacja zwiększyłaby produkcję szkodliwego dobra."),
      ],
      calc=[
          LB("Koszt prywatny produkcji tony stali wynosi 1200 zł, koszt zanieczyszczeń dla otoczenia – 300 zł. Ile wynosi koszt społeczny tony?",
             1500, "1200+300", ["1200 + 300 = 1500 zł"], unit="zł"),
          LB("Popyt: P = 100 − Q, prywatny koszt krańcowy MC = 20 + Q, koszt zewnętrzny 20 zł na sztukę. Ile wyprodukuje rynek bez interwencji?",
             40, "(100-20)/2", ["100 − Q = 20 + Q", "Q = 40"], unit="szt."),
          LB("Ile wynosi ilość efektywna społecznie (MC społeczny = 40 + Q)?",
             30, "(100-40)/2", ["100 − Q = 40 + Q", "Q = 30"], unit="szt."),
          LB("Jaki podatek Pigou (zł/szt.) doprowadzi rynek do ilości efektywnej?",
             20, "20", ["Podatek = koszt zewnętrzny na jednostkę = 20 zł"], unit="zł"),
          LB("Ile wynosi strata martwa bez interwencji (trójkąt: ½ · koszt zewnętrzny · nadmiar produkcji)?",
             100, "0.5*20*(40-30)", ["½ · 20 · (40 − 30) = 100 zł"], unit="zł"),
          LB("Firma A może zmniejszyć emisję o tonę za 50 zł, firma B za 200 zł. Trzeba zredukować 10 t. Ile kosztuje redukcja, gdy całą wykona A (np. dzięki handlowi uprawnieniami)?",
             500, "10*50", ["10 · 50 = 500 zł (gdyby każda redukowała po 5 t: 5 · 50 + 5 · 200 = 1250 zł)"], unit="zł"),
      ],
      case=[
          PR("Miasto ma korki w godzinach szczytu. Każdy dodatkowy samochód wydłuża przejazd innym kierowcom. Rozważane są: opłata za wjazd do centrum w godzinach szczytu, zakaz wjazdu aut z parzystymi numerami w wybrane dni albo darmowa komunikacja.",
             W("Jaki problem ekonomiczny występuje?",
               "Negatywny efekt zewnętrzny – kierowca nie płaci za opóźnienia innych", "Dobro publiczne czyste", "Pokusa nadużycia",
               why="Koszt społeczny jazdy w szczycie przewyższa koszt prywatny."),
             W("Które rozwiązanie najbardziej przypomina podatek Pigou?",
               "Opłata za wjazd w godzinach szczytu", "Zakaz dla parzystych numerów", "Darmowa komunikacja",
               why="Opłata wycenia koszt zewnętrzny i zostawia wybór kierowcom."),
             PF("Opłata za wjazd sprawia, że z jazdy w szczycie rezygnują przede wszystkim ci, dla których jest ona najmniej wartościowa.", True,
                why="Na tym polega przewaga narzędzi cenowych nad zakazami."),
          ),
          PR("Gmina chce poprawić jakość powietrza. Może dopłacać do wymiany starych pieców węglowych albo wprowadzić zakaz ich używania od określonej daty z karami.",
             W("Czym jest dopłata do wymiany pieca w języku teorii?",
               "Zachętą finansową internalizującą korzyści czystego powietrza", "Podatkiem Pigou", "Regulacją nakazową",
               why="Dopłata nagradza zmniejszenie negatywnego efektu zewnętrznego."),
             W("Czym jest zakaz z karami?",
               "Regulacją nakazowo-kontrolną", "Handlem uprawnieniami", "Dobrem publicznym",
               why="Państwo wprost nakazuje określone zachowanie."),
             M("Jakie są zalety połączenia obu narzędzi?",
               ["Zakaz daje pewność efektu w określonym terminie", "Dopłata zmniejsza koszty dla uboższych gospodarstw", "Połączenie eliminuje wszystkie koszty", "Dopłata zwiększa akceptację społeczną"],
               [0, 1, 3],
               why="Koszty nie znikają – są rozłożone między budżet i mieszkańców."),
          ),
      ]),

    L(3, "Własność i dobra wspólne: Coase, pastwisko i gapowicz",
      "Rozumieć twierdzenie Coase’a, tragedię wspólnego pastwiska, klasyfikację dóbr (prywatne, publiczne, klubowe, wspólne) i problem gapowicza.",
      ["Twierdzenie Coase’a", "Tragedia wspólnego pastwiska (tragedia wspólnoty)", "Dobra publiczne", "Dobra mieszane: klubowe i wspólne",
       "Dobra prywatne", "Problem gapowicza (free rider)", "Przełowienie i dekapitalizacja zasobów"],
      [S133, S121],
      explain=[
          K("Twierdzenie Coase’a",
            "Jeśli prawa własności są jasno określone, a koszty negocjacji niskie, strony same dojdą do efektywnego rozwiązania problemu efektu zewnętrznego – niezależnie od tego, komu przyznano prawo. Od podziału praw zależy tylko, kto komu zapłaci. W praktyce koszty transakcyjne (wiele stron, trudność wyceny) często to uniemożliwiają."),
          K("Dwie cechy dóbr",
            "Wykluczalność: czy da się uniemożliwić korzystanie temu, kto nie płaci? Rywalizacyjność: czy korzystanie przez jedną osobę zmniejsza dostępność dla innych? Z tych cech powstają cztery typy dóbr."),
          K("Cztery typy dóbr",
            "Prywatne: wykluczalne i rywalizacyjne (kanapka). Publiczne: niewykluczalne i nierywalizacyjne (obrona narodowa, latarnia morska). Klubowe: wykluczalne, nierywalizacyjne do pewnego zatłoczenia (kino, platforma streamingowa). Wspólne: niewykluczalne, ale rywalizacyjne (ryby w morzu, pastwisko gminne)."),
          W("Ryby w otwartym morzu to dobro:",
            "Wspólne – niewykluczalne i rywalizacyjne", "Publiczne", "Klubowe", "Prywatne",
            why="Trudno zabronić połowu, ale złowiona ryba nie jest dostępna dla innych."),
          K("Gapowicz i tragedia wspólnoty",
            "Przy dobrach publicznych każdy liczy, że inni zapłacą – to problem gapowicza, przez który rynek dostarcza ich za mało; dlatego finansuje się je z podatków. Przy dobrach wspólnych każdy korzysta ponad miarę, bo koszt rozkłada się na wszystkich – zasób się wyczerpuje (Garrett Hardin, 1968). Rozwiązania: prawa własności, kwoty, opłaty albo wspólnotowe zasady (Elinor Ostrom)."),
          PF("Dobra publiczne zawsze muszą być produkowane przez państwo.", False,
             why="Państwo zwykle je finansuje, ale wytwarzać mogą firmy prywatne (np. budowa wałów przeciwpowodziowych na zlecenie)."),
      ],
      mech=[
          KT("Jaki to typ dobra?",
             {"Prywatne": ["Pizza", "Bilet lotniczy na konkretne miejsce"],
              "Publiczne": ["Obrona narodowa", "Ostrzeżenia pogodowe w radiu"],
              "Klubowe": ["Siłownia z karnetami", "Płatna telewizja"],
              "Wspólne": ["Łowisko ryb na otwartym morzu", "Darmowe miejsca parkingowe w centrum"]},
             why="Klasyfikacja zależy od wykluczalności i rywalizacyjności."),
          LN("Ułóż tragedię wspólnego pastwiska.",
             ["Pastwisko jest dostępne dla wszystkich", "Każdy rolnik dokłada krowę, bo korzyść jest jego, a koszt wspólny", "Liczba krów przekracza możliwości pastwiska", "Trawa nie odrasta", "Wszyscy tracą"],
             why="Racjonalne decyzje indywidualne prowadzą do zbiorowej straty."),
          W("Hodowca bydła i rolnik spierają się o szkody wyrządzane przez krowy. Według Coase’a, przy niskich kosztach negocjacji:",
            "Dojdą do efektywnego rozwiązania niezależnie od tego, kto ma prawo", "Zawsze potrzebny jest sąd", "Efektywny wynik zależy od tego, kto ma prawo",
            why="Prawo wpływa na podział korzyści, nie na efektywność."),
          W("Dlaczego Wikipedia działa mimo problemu gapowicza?",
            "Część osób wnosi wkład z motywacji niefinansowych, a koszty są niskie", "Bo jest dobrem prywatnym", "Bo państwo ją finansuje",
            why="Problem gapowicza nie zawsze całkowicie blokuje dostarczanie dóbr publicznych."),
          PF("Kwoty połowowe to sposób ograniczania tragedii wspólnoty na łowiskach.", True,
             why="Limitują korzystanie z zasobu wspólnego."),
          M("Kiedy twierdzenie Coase’a trudno zastosować?",
            ["Gdy poszkodowanych są tysiące osób", "Gdy trudno wycenić szkody", "Gdy są dwie strony i niskie koszty negocjacji", "Gdy prawa własności są niejasne"],
            [0, 1, 3],
            why="Dwie strony i niskie koszty to idealne warunki dla Coase’a."),
      ],
      calc=[
          LB("Fabryka zyskuje 50 000 zł rocznie z hałaśliwej nocnej zmiany, a sąsiedzi szacują szkody na 30 000 zł. Sąsiedzi mają prawo do ciszy. Jaką minimalną kwotę fabryka musi im zapłacić, by mogła pracować nocą?",
             30000, "30000", ["Sąsiedzi zgodzą się za co najmniej tyle, ile tracą: 30 000 zł", "Fabryce opłaca się płacić do 50 000 zł"], unit="zł"),
          LB("W tym samym przykładzie: ile wynosi korzyść netto dla społeczności z nocnej zmiany?",
             20000, "50000-30000", ["50 000 − 30 000 = 20 000 zł – dlatego efektywne jest, by fabryka pracowała"], unit="zł"),
          LB("Pastwisko: przy n krowach każda daje mleko warte 1000 − 20n zł rocznie. Ile wynosi łączna wartość przy 25 krowach?",
             12500, "25*(1000-20*25)", ["Na krowę: 1000 − 500 = 500 zł", "Razem: 25 · 500 = 12 500 zł"], unit="zł"),
          LB("Przy jakiej liczbie krów łączna wartość n·(1000 − 20n) jest największa?",
             25, "1000/40", ["Pochodna: 1000 − 40n = 0", "n = 25"], unit="szt."),
          LB("Przy swobodnym dostępie rolnicy dokładają krowy, dopóki krowa daje cokolwiek (1000 − 20n > 0). Do ilu krów dojdzie (graniczna liczba)?",
             50, "1000/20", ["1000 − 20n = 0 ⇒ n = 50 – wartość łączna spada do zera"], unit="szt."),
          LB("Latarnia morska kosztuje 600 000 zł, a każdy z 40 armatorów ceni ją na 20 000 zł. Ile wynosi łączna korzyść?",
             800000, "40*20000", ["40 · 20 000 = 800 000 zł > 600 000 zł – opłaca się społecznie", "Ale żaden armator sam jej nie zbuduje – problem gapowicza"], unit="zł"),
      ],
      case=[
          PR("Na Bałtyku przez lata nadmiernie poławiano dorsza, a jego zasoby dramatycznie się skurczyły. UE wprowadziła limity połowowe, a w ostatnich latach – bardzo ostre ograniczenia połowów dorsza bałtyckiego.",
             W("Jakie zjawisko doprowadziło do spadku zasobów?",
               "Tragedia wspólnoty – nadmierna eksploatacja zasobu wspólnego", "Problem gapowicza przy dobru publicznym", "Monopol naturalny",
               why="Każdy rybak korzystał z zasobu, a koszt wyczerpania rozkładał się na wszystkich."),
             W("Czym są limity połowowe?",
               "Ograniczeniem korzystania z zasobu wspólnego", "Podatkiem Pigou", "Dotacją",
               why="Limity wprowadzają reguły korzystania z dobra niewykluczalnego."),
             PF("Przekazanie rybakom zbywalnych kwot połowowych może skłaniać ich do dbania o odbudowę zasobów.", True,
                why="Kwoty działają jak prawa własności – rybak zyskuje na przyszłym wzroście zasobów."),
          ),
          PR("Mieszkańcy osiedla chcą monitoringu i oświetlenia ścieżki do przystanku. Koszt: 120 000 zł. Zarząd proponuje dobrowolne wpłaty. Po miesiącu zebrano 35 000 zł, choć w ankiecie większość mieszkańców deklarowała, że oświetlenie jest dla nich warte ponad 300 zł.",
             W("Dlaczego zebrano tak mało?",
               "Problem gapowicza – każdy liczy, że inni zapłacą, a i tak skorzysta", "Mieszkańcy nie chcą oświetlenia", "Oświetlenie jest dobrem prywatnym",
               why="Ścieżka oświetlona dla jednego jest oświetlona dla wszystkich – trudno wykluczyć niepłacących."),
             LB("Osiedle ma 500 mieszkań. Jaka składka obowiązkowa pokryłaby koszt?",
                240, "120000/500", ["120 000 / 500 = 240 zł na mieszkanie"], unit="zł"),
             PF("Obowiązkowa składka (jak podatek) jest typowym sposobem finansowania dobra publicznego.", True,
                why="Przymusowe finansowanie usuwa problem gapowicza."),
          ),
      ]),

    L(4, "Asymetria informacji: cytryny, pokusa nadużycia, agencja",
      "Rozumieć negatywną selekcję („rynek cytryn”), pokusę nadużycia, problem pryncypała i agenta oraz mechanizmy sygnalizacji i odsiewania.",
      ["Asymetria informacji", "Negatywna (niekorzystna) selekcja", "Pokusa nadużycia (moral hazard)", "Problem pryncypała i agenta (problem agencji)",
       "Sygnalizacja i odsiewanie (screening)", "Oportunizm (w nowej ekonomii instytucjonalnej)"],
      [S161, S162],
      explain=[
          K("Asymetria informacji",
            "Jedna strona transakcji wie więcej niż druga: sprzedawca używanego auta zna jego wady, kupujący – nie; ubezpieczony zna swoje zdrowie lepiej niż ubezpieczyciel. To może psuć rynki, nawet gdy obie strony chciałyby handlować."),
          K("Negatywna selekcja – rynek cytryn",
            "George Akerlof (1970) pokazał, że gdy kupujący nie odróżniają dobrych aut od wadliwych („cytryn”), płacą cenę przeciętną. Właściciele dobrych aut nie chcą sprzedawać za tę cenę i wycofują się, przeciętna jakość spada, cena spada dalej – rynek może zaniknąć. Dzieje się to PRZED zawarciem umowy."),
          W("Kto najchętniej kupuje ubezpieczenie zdrowotne o stałej składce bez badań?",
            "Osoby, które wiedzą, że są chore – negatywna selekcja", "Osoby najzdrowsze", "Nikt",
            why="Przy jednakowej cenie najbardziej opłaca się to tym, którzy spodziewają się wysokich kosztów."),
          K("Pokusa nadużycia",
            "Po zawarciu umowy jedna strona zmienia zachowanie, bo nie ponosi pełnych skutków: ubezpieczony mniej dba o mienie, bank „zbyt duży, by upaść” podejmuje ryzyko, licząc na ratunek. Sposoby: udział własny, franszyzy, kontrola, premie za brak szkód."),
          K("Pryncypał i agent; sygnały",
            "Pryncypał (właściciel) zleca zadanie agentowi (menedżerowi), który ma własne cele i więcej informacji. Pomagają: wynagrodzenie zależne od wyników, kontrola, reputacja. Sygnalizacja: strona lepiej poinformowana pokazuje swoją jakość (gwarancja, dyplom). Odsiewanie: strona gorzej poinformowana tak konstruuje oferty, by klienci sami się rozdzielili (np. ubezpieczenie z wyższym udziałem własnym i niższą składką)."),
          PF("Negatywna selekcja występuje po zawarciu umowy, a pokusa nadużycia – przed.", False,
             why="Odwrotnie: selekcja dotyczy tego, kto zawiera umowę (przed), pokusa – zachowania po jej zawarciu."),
      ],
      mech=[
          LN("Ułóż mechanizm rynku cytryn.",
             ["Kupujący nie odróżniają dobrych aut od wadliwych", "Oferują cenę przeciętną", "Właściciele dobrych aut wycofują je z rynku",
              "Przeciętna jakość oferowanych aut spada", "Cena spada dalej – rynek się kurczy"],
             why="Asymetria informacji wypycha dobrą jakość z rynku."),
          KT("Negatywna selekcja czy pokusa nadużycia?",
             {"Negatywna selekcja": ["Najbardziej ryzykowni kierowcy najchętniej kupują drogie AC", "Kredyt na wysoki procent przyciąga głównie ryzykownych pożyczkobiorców"],
              "Pokusa nadużycia": ["Po wykupieniu ubezpieczenia ktoś nie zamyka auta", "Menedżer z pensją niezależną od wyników nie przykłada się do pracy", "Bank ryzykuje, licząc na pomoc państwa"]},
             why="Selekcja – kto zawiera umowę; pokusa – jak zachowuje się po jej zawarciu."),
          W("Dlaczego dealerzy dają gwarancję na używane auta?",
            "Gwarancja jest wiarygodnym sygnałem jakości", "Prawo zabrania sprzedaży bez gwarancji", "Bo auta są nowe",
            why="Sprzedawca złych aut nie mógłby sobie pozwolić na kosztowną gwarancję."),
          W("Ubezpieczyciel oferuje dwa warianty: niska składka z wysokim udziałem własnym albo wysoka składka bez udziału. Jaki mechanizm to wykorzystuje?",
            "Odsiewanie – klienci sami ujawniają swoje ryzyko wyborem", "Sygnalizację przez ubezpieczyciela", "Pokusę nadużycia",
            why="Klienci o niskim ryzyku wybiorą wysoki udział własny, ryzykowni – pełną ochronę."),
          PF("Opcje na akcje dla menedżerów są próbą zmniejszenia problemu pryncypała i agenta.", True,
             why="Wiążą wynagrodzenie menedżera z wartością firmy dla właścicieli."),
          M("Co ogranicza pokusę nadużycia w ubezpieczeniach?",
            ["Udział własny w szkodzie", "Zniżki za bezszkodową jazdę", "Pełne pokrycie każdej szkody bez warunków", "Kontrole i wymagania zabezpieczeń"],
            [0, 1, 3],
            why="Pełne pokrycie bez warunków osłabia motywację do ostrożności."),
      ],
      calc=[
          LB("Połowa aut jest dobra (warta dla kupującego 40 000 zł), połowa wadliwa (20 000 zł). Ile kupujący zapłaci za auto, nie znając jakości?",
             30000, "0.5*40000+0.5*20000", ["Wartość oczekiwana: 0,5 · 40 000 + 0,5 · 20 000 = 30 000 zł"], unit="zł"),
          LB("Właściciel dobrego auta chce za nie co najmniej 36 000 zł. O ile zł za mało oferuje mu kupujący (cena 30 000 zł)?",
             6000, "36000-30000", ["36 000 − 30 000 = 6000 zł – dobre auta wycofują się z rynku"], unit="zł"),
          LB("Po wycofaniu dobrych aut zostają same wadliwe. Ile zapłaci teraz racjonalny kupujący?",
             20000, "20000", ["Wiedząc, że zostały tylko „cytryny”, płaci ich wartość: 20 000 zł"], unit="zł"),
          LB("10% klientów ma ryzyko szkody 50% (szkoda 10 000 zł), 90% – ryzyko 5%. Ile wynosi przeciętna oczekiwana szkoda na klienta?",
             950, "0.1*0.5*10000+0.9*0.05*10000", ["0,1 · 5000 + 0,9 · 500 = 500 + 450 = 950 zł"], unit="zł"),
          LB("Ubezpieczyciel ustala składkę 950 zł. Klienci niskiego ryzyka (oczekiwana szkoda 500 zł) rezygnują. Ile wyniesie oczekiwana szkoda pozostałych?",
             5000, "0.5*10000", ["Zostają ryzykowni: 0,5 · 10 000 = 5000 zł – składka 950 zł nie wystarczy"], unit="zł"),
          LB("Udział własny 20% przy szkodzie 4000 zł. Ile zapłaci sam ubezpieczony?",
             800, "0.2*4000", ["0,2 · 4000 = 800 zł – zachęta do ostrożności"], unit="zł"),
      ],
      case=[
          PR("Platforma sprzedaży używanych samochodów wprowadza: raporty historii pojazdu z bazy danych, niezależne przeglądy przed zakupem i oceny sprzedawców. Po roku średnie ceny dobrych aut na platformie wzrosły, a liczba transakcji też wzrosła.",
             W("Jaki problem rozwiązuje platforma?",
               "Asymetrię informacji i negatywną selekcję", "Efekt zewnętrzny", "Problem gapowicza",
               why="Raporty i przeglądy zmniejszają przewagę informacyjną sprzedawcy."),
             W("Dlaczego wzrosły ceny dobrych aut?",
               "Kupujący mogą odróżnić jakość i płacą więcej za dobre auta", "Spadła podaż aut", "Platforma ustaliła ceny minimalne",
               why="Przy lepszej informacji cena odzwierciedla jakość, a właściciele dobrych aut wracają na rynek."),
             PF("Oceny sprzedawców budują reputację, która jest formą sygnalizacji jakości.", True,
                why="Reputacja jest kosztowna do zbudowania i łatwa do zniszczenia oszustwem."),
          ),
          PR("Właściciele spółki płacą prezesowi stałą pensję. Prezes inwestuje w prestiżowe projekty i luksusową siedzibę, które mało zwiększają zyski. Rada nadzorcza proponuje nowy system: niższa pensja stała plus premia zależna od wzrostu wartości firmy w ciągu 5 lat.",
             W("Jaki problem opisuje sytuacja?",
               "Problem pryncypała i agenta", "Rynek cytryn", "Tragedia wspólnoty",
               why="Cele zarządzającego (prestiż) różnią się od celów właścicieli (zysk)."),
             W("Dlaczego premia za 5 lat, a nie za kwartał?",
               "By zniechęcić do krótkoterminowego „podkręcania” wyników kosztem przyszłości", "Bo kwartały są nielegalne", "By prezes zarabiał mniej",
               why="Długi horyzont zbliża interes agenta do długookresowego interesu właścicieli."),
             M("Jakie inne narzędzia mogą ograniczyć problem agencji?",
               ["Niezależny audyt", "Aktywna rada nadzorcza", "Brak jakiejkolwiek kontroli", "Rynek przejęć – groźba zmiany zarządu"],
               [0, 1, 3],
               why="Brak kontroli pogłębia problem."),
          ),
      ]),

    L(5, "Zawodność państwa i spory o sprawiedliwość",
      "Rozumieć źródła zawodności państwa (pogoń za rentą, przejęcie regulacyjne, interesy grupowe), argumenty za prywatyzacją i regulacją oraz główne teorie sprawiedliwego podziału.",
      ["Zawodność państwa (rządu)", "Pogoń za rentą (rent seeking)", "Regulacja, deregulacja i przejęcie regulacyjne", "Nacjonalizacja i prywatyzacja",
       "Kumoterstwo (kapitalizm kolesiów)", "Teorie sprawiedliwego podziału: utylitaryzm, liberalizm, libertarianizm", "Libertarianizm i libertariański paternalizm"],
      [S182, S183, S114, S155],
      explain=[
          K("Państwo też bywa zawodne",
            "Politycy i urzędnicy mają własne cele (reelekcja, budżet urzędu), brakuje im informacji, a koszty decyzji często ponoszą inni. Skutkiem mogą być marnotrawstwo, programy korzystne dla wąskich grup i decyzje krótkowzroczne (pod wybory). Zawodność rynku nie oznacza automatycznie, że interwencja poprawi sytuację."),
          K("Pogoń za rentą i interesy grupowe",
            "Pogoń za rentą to wydawanie zasobów na zdobycie przywilejów (cła, licencje, dotacje), a nie na tworzenie wartości. Mała, dobrze zorganizowana grupa, która dużo zyskuje, wygrywa z dużą, rozproszoną grupą, z której każdy traci niewiele (Mancur Olson). Przejęcie regulacyjne (Stigler): regulator zaczyna działać w interesie regulowanej branży."),
          W("Producenci cukru lobbują za cłem na import cukru. Kto traci i dlaczego mało protestuje?",
            "Konsumenci – każdy traci niewiele, a organizacja protestu jest kosztowna", "Producenci cukru", "Nikt nie traci",
            why="Rozproszone koszty i skoncentrowane korzyści sprzyjają lobbingowi."),
          K("Prywatyzacja, nacjonalizacja, regulacja",
            "Prywatyzacja może zwiększyć efektywność (presja zysku, konkurencja), ale w monopolach naturalnych bez regulacji grozi nadużywaniem pozycji. Nacjonalizacja bywa uzasadniana bezpieczeństwem lub dobrami strategicznymi, ale grozi X-nieefektywnością i upolitycznieniem."),
          K("Co to znaczy „sprawiedliwy podział”?",
            "Utylitaryzm (Bentham): maksymalizować sumę dobrobytu – przy malejącej użyteczności krańcowej dochodu przemawia za pewną redystrybucją. Liberalizm Rawlsa: oceniać zasady „za zasłoną niewiedzy” – nierówności są dopuszczalne, jeśli poprawiają los najsłabszych. Libertarianizm Nozicka: sprawiedliwy jest każdy podział wynikający z dobrowolnych transakcji, bez przymusowej redystrybucji."),
          PF("Teoria Rawlsa zakazuje wszelkich nierówności dochodów.", False,
             why="Dopuszcza nierówności, jeśli przynoszą korzyść najmniej uprzywilejowanym (zasada dyferencji)."),
      ],
      mech=[
          LN("Ułóż mechanizm przejęcia regulacyjnego.",
             ["Powstaje urząd regulujący branżę", "Branża ma silną motywację i wiedzę, by wpływać na urząd", "Urzędnicy korzystają z informacji i ekspertów branży (i przechodzą do niej do pracy)",
              "Regulacje coraz bardziej chronią firmy przed konkurencją", "Konsumenci tracą"],
             why="Stigler: regulator może zostać „przejęty” przez regulowanych."),
          KT("Która teoria sprawiedliwości?",
             {"Utylitaryzm": ["Największe szczęście największej liczby ludzi", "Przenieść złotówkę od bogatego do biednego, jeśli zwiększa to sumę użyteczności"],
              "Rawls": ["Wybór zasad za zasłoną niewiedzy", "Nierówności tylko gdy pomagają najsłabszym"],
              "Nozick (libertarianizm)": ["Sprawiedliwe jest to, co wynika z dobrowolnej wymiany", "Przymusowa redystrybucja narusza prawa jednostki"]},
             why="Każda teoria inaczej definiuje kryterium sprawiedliwości."),
          W("Rząd dopłaca do nierentownej kopalni, by utrzymać miejsca pracy przed wyborami. Jakie zjawisko może to ilustrować?",
            "Zawodność państwa – decyzja motywowana cyklem wyborczym", "Optimum Pareto", "Efekt Veblena",
            why="Koszty ponoszą podatnicy, a korzyści polityczne – decydenci."),
          W("Czym jest libertariański paternalizm (Thaler, Sunstein)?",
            "Kształtowanie wyboru (np. domyślne zapisanie do programu emerytalnego) bez odbierania swobody rezygnacji", "Zakaz wyborów konsumenckich", "Brak jakiejkolwiek polityki",
            why="To idea „szturchania” – zachowuje wolność wyboru, ale ułatwia dobre decyzje."),
          PF("Fakt, że rynek zawodzi, nie wystarcza do uzasadnienia interwencji – trzeba porównać ją z możliwą zawodnością państwa.", True,
             why="Interwencja ma swoje koszty i ryzyka; trzeba porównać realne alternatywy."),
          M("Co ogranicza pogoń za rentą?",
            ["Przejrzystość procesu legislacyjnego", "Konkurencja i otwarty handel", "Liczne ulgi dla wybranych branż", "Rejestr lobbystów i niezależna prasa"],
            [0, 1, 3],
            why="Liczne ulgi branżowe zachęcają do zabiegania o przywileje."),
      ],
      calc=[
          LB("Cło na import cukru podnosi cenę o 0,50 zł/kg. 38 mln konsumentów kupuje średnio 40 kg rocznie. Ile łącznie dopłacają konsumenci?",
             760, "38*40*0.5", ["38 mln · 40 kg · 0,50 zł = 760 mln zł"], unit="mln zł"),
          LB("Ile średnio traci jeden konsument rocznie (40 kg · 0,50 zł)?",
             20, "40*0.5", ["40 · 0,50 = 20 zł – za mało, by protestować"], unit="zł"),
          LB("Zysk 20 producentów z cła wynosi łącznie 300 mln zł. Ile średnio zyskuje jeden producent?",
             15, "300/20", ["300 / 20 = 15 mln zł – silna motywacja do lobbingu"], unit="mln zł"),
          LB("Firmy wydały łącznie 40 mln zł na lobbing o licencję, którą dostanie jedna z nich (zysk 50 mln zł). Ile netto zyskuje społeczeństwo (licencja nie tworzy wartości, tylko ją przenosi)?",
             -40, "-40", ["Wydatki na lobbing to marnotrawstwo zasobów: −40 mln zł", "Zysk zwycięzcy to transfer, nie nowa wartość"], unit="mln zł"),
          LB("Utylitaryzm: bogaty ma MU ostatniej złotówki 1, biedny – 4. O ile zmieni się suma użyteczności po przeniesieniu 100 zł (przy stałych MU)?",
             300, "100*(4-1)", ["Biedny zyskuje 400, bogaty traci 100", "Suma: +300"], unit=""),
          LB("Program kosztuje 2 mld zł, a korzyści dla odbiorców wynoszą 1,5 mld zł. Ile wynosi strata netto społeczeństwa?",
             0.5, "2-1.5", ["2 − 1,5 = 0,5 mld zł"], unit="mld zł"),
      ],
      case=[
          PR("Miasto ma jedną państwową firmę autobusową. Rozważa sprywatyzowanie jej albo ogłaszanie przetargów na obsługę poszczególnych linii, przy czym miasto ustala rozkład i ceny biletów.",
             W("Jakie ryzyko ma prosta prywatyzacja całej firmy bez regulacji?",
               "Prywatny monopolista mógłby podnieść ceny i ograniczyć nierentowne linie", "Spadek cen biletów", "Brak jakichkolwiek ryzyk",
               why="Prywatyzacja monopolu bez konkurencji ani regulacji przenosi siłę rynkową do firmy prywatnej."),
             W("Na czym polega zaleta przetargów na linie?",
               "Konkurencja o rynek – firmy rywalizują ceną za obsługę, a miasto kontroluje jakość", "Firmy rywalizują na tej samej ulicy", "Miasto nie ponosi żadnych kosztów",
               why="To „konkurencja o rynek” zamiast „konkurencji na rynku”."),
             PF("Przetargi mogą być podatne na zmowę oferentów albo kumoterstwo, więc wymagają przejrzystości.", True,
                why="Zawodność państwa i zmowy przetargowe to realne ryzyka."),
          ),
          PR("W debacie o podatkach jedna osoba mówi: „Każdy powinien zatrzymać to, co zarobił na rynku”. Druga: „Gdybyśmy nie wiedzieli, czy urodzimy się bogaci, czy biedni, wybralibyśmy system z siatką bezpieczeństwa”. Trzecia: „Przenieśmy pieniądze tam, gdzie dadzą najwięcej szczęścia”.",
             W("Którą teorię reprezentuje pierwsza osoba?",
               "Libertarianizm (Nozick)", "Rawls", "Utylitaryzm",
               why="Sprawiedliwość jako poszanowanie dobrowolnych transakcji."),
             W("Którą reprezentuje druga osoba?",
               "Liberalizm Rawlsa", "Utylitaryzm", "Libertarianizm",
               why="Zasłona niewiedzy to kluczowe narzędzie Rawlsa."),
             PF("Spór między tymi osobami da się rozstrzygnąć samymi danymi ekonomicznymi.", False,
                why="To spór normatywny – dotyczy wartości, nie tylko faktów."),
          ),
      ]),

    L(6, "Narzędzia polityki ekologicznej: regulacja, podatek i zbywalne zezwolenia",
      "Porównywać regulację nakazowo-rozdzielczą, podatek Pigou i zbywalne zezwolenia na zanieczyszczenia, liczyć koszty osiągnięcia celu redukcji emisji i rozumieć zastrzeżenia wobec ekonomicznego podejścia do środowiska.",
      ["Zbywalne zezwolenia na zanieczyszczenia (handel emisjami)", "Podatek Pigou", "Regulacja, deregulacja i przejęcie regulacyjne", "Efekty zewnętrzne (externalities)"],
      [Z122, Z123, ZETS],
      explain=[
          K("Regulacja nakazowo-rozdzielcza",
            "Państwo nakazuje określony limit emisji lub technologię (np. filtry) dla każdej firmy. Proste i pewne co do efektu, ale kosztowne: każda firma redukuje tyle samo, niezależnie od kosztów, i nie ma bodźca do redukcji ponad normę."),
          K("Podatek Pigou",
            "Podatek od jednostki zanieczyszczenia równy krańcowemu kosztowi zewnętrznemu. Każda firma redukuje emisję, dopóki koszt redukcji jest niższy od podatku – redukcję wykonują najtańsi. Państwo zna cenę zanieczyszczenia, ale nie wie dokładnie, jaka będzie łączna emisja."),
          W("Firma A redukuje emisję za 50 zł/t, firma B za 200 zł/t. Wprowadzono podatek 120 zł/t. Co zrobią firmy?",
            "A zredukuje emisję, B zapłaci podatek", "Obie zredukują emisję", "Obie zapłacą podatek",
            why="Każda wybiera tańszą opcję: redukcję lub podatek."),
          K("Zbywalne zezwolenia",
            "Państwo ustala łączny limit emisji i rozdziela lub sprzedaje uprawnienia; firmy mogą nimi handlować. Firmy o niskich kosztach redukują więcej i sprzedają uprawnienia firmom o wysokich kosztach – cel osiąga się najtaniej, a łączna emisja jest pewna (cenę ustala rynek). Przykład: EU ETS w UE od 2005 r."),
          K("Zastrzeżenia",
            "Krytycy uważają, że handel prawami do zanieczyszczania jest moralnie wątpliwy („licencja na truciznę”). Ekonomiści odpowiadają, że zerowe zanieczyszczenie jest niemożliwe lub skrajnie kosztowne; pytanie brzmi, jak osiągnąć dany poziom czystości najtaniej. Czyste środowisko to dobro normalne – popyt na nie rośnie z dochodem."),
          PF("Podatek Pigou i zbywalne zezwolenia mogą osiągnąć ten sam cel redukcji taniej niż jednolita regulacja.", True,
             why="Redukcję wykonują firmy o najniższych kosztach."),
      ],
      mech=[
          KT("Które narzędzie?",
             {"Regulacja nakazowo-rozdzielcza": ["Każda elektrownia musi zainstalować filtr określonego typu"],
              "Podatek Pigou": ["Opłata 120 zł za każdą tonę emisji"],
              "Zbywalne zezwolenia": ["Limit emisji i giełda uprawnień, na której firmy kupują i sprzedają prawa", "System EU ETS"],
              "Rozwiązanie prywatne (Coase)": ["Sąsiedzi negocjują z fabryką odszkodowanie za hałas"]},
             why="Różne sposoby internalizacji efektów zewnętrznych."),
          LN("Ułóż działanie systemu zbywalnych zezwoleń.",
             ["Państwo ustala łączny limit emisji", "Rozdziela lub sprzedaje uprawnienia", "Firmy o niskich kosztach redukcji ograniczają emisję", "Sprzedają nadwyżkowe uprawnienia firmom o wysokich kosztach", "Cel emisji zostaje osiągnięty najmniejszym kosztem"],
             why="Handel kieruje redukcję do najtańszych."),
          W("Czym różni się podatek Pigou od zbywalnych zezwoleń?",
            "Podatek ustala cenę emisji, a zezwolenia – ilość emisji", "Niczym", "Zezwolenia ustalają cenę, a podatek – ilość",
            why="Dwa narzędzia – stała cena albo stała ilość."),
          W("Dlaczego regulacja nakazowa nie daje bodźca do redukcji ponad normę?",
            "Firma nic nie zyskuje na dodatkowej redukcji", "Bo firmy płacą podatek za każdą tonę", "Bo normy rosną automatycznie",
            why="Brak nagrody za lepsze wyniki."),
          M("Jakie są zalety rynkowych narzędzi polityki ekologicznej?",
            ["Niższy koszt osiągnięcia celu", "Bodziec do innowacji ograniczających emisję", "Elastyczność dla firm", "Gwarancja zerowej emisji"], [0, 1, 2],
            why="Zerowa emisja nie jest celem efektywnym."),
          PF("Czyste środowisko jest dobrem normalnym – popyt na nie rośnie wraz z dochodem.", True,
             why="Bogatsze społeczeństwa wymagają czystszego środowiska."),
      ],
      calc=[
          LB("A redukuje za 50 zł/t, B za 200 zł/t. Regulacja nakazuje każdej zmniejszyć emisję o 50 t. Ile wynosi łączny koszt (zł)?",
             12500, "50*50+200*50", ["2 500 + 10 000 = 12 500 zł"], unit="zł"),
          LB("Przy handlu zezwoleniami A redukuje 100 t, B nic. Ile wynosi koszt (zł)?",
             5000, "50*100", ["50 · 100 = 5 000 zł"], unit="zł"),
          LB("Ile społeczeństwo oszczędza dzięki handlowi (zł)?",
             7500, "12500-5000", ["12 500 − 5 000 = 7 500 zł"], unit="zł"),
          LB("Uprawnienie kosztuje 120 zł/t. Ile zarobi A, sprzedając B 50 uprawnień (po odjęciu kosztu redukcji 50 zł/t) (zł)?",
             3500, "50*(120-50)", ["50 · 70 = 3 500 zł"], unit="zł"),
          LB("Ile oszczędza B, kupując 50 uprawnień zamiast redukować (zł)?",
             4000, "50*(200-120)", ["50 · 80 = 4 000 zł"], unit="zł"),
          LB("Podatek 120 zł/t; B emituje 50 t. Ile zapłaci podatku (zł)?",
             6000, "120*50", ["120 · 50 = 6 000 zł"], unit="zł"),
      ],
      case=[
          PR("Rząd chce zmniejszyć emisję SO₂ z elektrowni o połowę. Elektrownia nowa może to zrobić za 100 zł/t, a stara – za 600 zł/t. Związkowcy żądają jednakowych limitów dla wszystkich.",
             W("Które rozwiązanie osiągnie cel najtaniej?",
               "Zbywalne zezwolenia lub podatek – redukcję wykona głównie nowa elektrownia", "Jednakowy limit dla każdej", "Zakaz produkcji energii",
               why="Redukcję wykonują firmy o niższych kosztach."),
             W("Jaką wadę ma jednakowy limit?",
               "Wyższy łączny koszt osiągnięcia tego samego celu", "Niższy efekt ekologiczny", "Brak wpływu na emisję",
               why="Stara elektrownia redukuje drogo."),
             PF("Przy handlu zezwoleniami łączna emisja jest z góry znana.", True,
                why="Ustala ją limit uprawnień."),
          ),
          PR("Organizacja ekologiczna krytykuje EU ETS: „Firmy kupują prawo do trucia”. Ekonomista odpowiada, że limit emisji maleje co roku, a ceny uprawnień skłaniają do inwestycji w czystą energię.",
             W("Jaki argument ekonomisty jest najważniejszy?",
               "System osiąga malejący limit emisji najniższym kosztem i daje bodziec do innowacji", "Zanieczyszczenie nie ma kosztów", "Firmy nie emitują CO₂",
               why="Efektywność kosztowa i dynamiczny bodziec."),
             W("Co się stanie z ceną uprawnień, gdy limit spada szybciej niż popyt na emisję?",
               "Wzrośnie", "Spadnie", "Nie zmieni się",
               why="Mniejsza podaż uprawnień."),
             PF("Wyższa cena uprawnień zwiększa opłacalność odnawialnych źródeł energii.", True,
                why="Emisja staje się droższa."),
          ),
      ]),

    L(7, "Klasyfikacja dóbr: wykluczalność, rywalizacyjność i ważne dobra publiczne",
      "Klasyfikować dobra według wykluczalności i rywalizacyjności, rozumieć, dlaczego rynek niedostarcza dóbr publicznych i nadmiernie eksploatuje wspólne zasoby, oraz analizować przykłady: obronę narodową, badania podstawowe, walkę z ubóstwem, latarnie, łowiska.",
      ["Wykluczalność i rywalizacyjność (klasyfikacja dóbr)", "Dobra publiczne", "Dobra mieszane: klubowe i wspólne", "Tragedia wspólnego pastwiska (tragedia wspólnoty)"],
      [Z133],
      explain=[
          K("Dwie cechy dóbr",
            "Wykluczalność – czy można uniemożliwić korzystanie osobom, które nie płacą. Rywalizacyjność (konkurencyjność w konsumpcji) – czy korzystanie przez jedną osobę zmniejsza możliwość korzystania przez inne. Daje to cztery typy: prywatne (W, R), publiczne (nW, nR), wspólne zasoby (nW, R), klubowe (W, nR)."),
          K("Dobra publiczne",
            "Niewykluczalne i nierywalizacyjne – każdy korzysta, nawet bez płacenia, więc pojawia się problem gapowicza i rynek dostarcza ich za mało. Przykłady: obrona narodowa, badania podstawowe (wiedzy ogólnej nie da się opatentować), walka z ubóstwem (jeśli ludzie cenią życie w społeczeństwie bez biedy), pokazy sztucznych ogni, latarnie morskie (choć bywały finansowane prywatnie przez porty)."),
          W("Do jakiego typu należy zatłoczona, bezpłatna droga?",
            "Wspólny zasób – niewykluczalna, ale rywalizacyjna (korki)", "Dobro prywatne", "Dobro klubowe",
            why="Każdy może wjechać, ale kolejne auta spowalniają innych."),
          K("Wspólne zasoby",
            "Niewykluczalne, ale rywalizacyjne: łowiska, czyste powietrze, pastwiska, drogi w godzinach szczytu, dzikie zwierzęta. Każdy użytkownik nie bierze pod uwagę kosztu, jaki narzuca innym – zasób jest nadmiernie eksploatowany (tragedia wspólnego pastwiska). Rozwiązania: regulacja, opłaty (np. za wjazd), podział na prawa własności, kwoty połowowe."),
          K("Dobra klubowe",
            "Wykluczalne, ale nierywalizacyjne (do granicy zatłoczenia): telewizja kodowana, płatna autostrada przy małym ruchu, oprogramowanie. Często są monopolami naturalnymi – koszt obsługi dodatkowego użytkownika jest bliski zeru."),
          PF("Wiedza z badań podstawowych jest dobrem publicznym, dlatego państwo je finansuje.", True,
             why="Wiedzy ogólnej nie da się zawłaszczyć patentem."),
      ],
      mech=[
          KT("Jaki typ dobra?",
             {"Dobro prywatne": ["Bochenek chleba", "Para butów"],
              "Dobro publiczne": ["Obrona narodowa", "Pokaz sztucznych ogni nad miastem"],
              "Wspólny zasób": ["Ryby w Bałtyku", "Bezpłatna, zakorkowana droga"],
              "Dobro klubowe": ["Telewizja kodowana", "Płatna autostrada przy małym ruchu"]},
             why="Kryteria: wykluczalność i rywalizacyjność."),
          LN("Ułóż mechanizm przełowienia.",
             ["Łowisko jest dostępne dla wszystkich", "Każdy rybak łowi, ile może", "Nikt nie uwzględnia kosztu dla innych rybaków", "Zasoby ryb spadają poniżej poziomu odnawiania", "Połowy i dochody wszystkich rybaków maleją"],
             why="Tragedia wspólnego pastwiska."),
          W("Dlaczego prywatne firmy rzadko finansują obronę narodową?",
            "Nie mogą wykluczyć niepłacących – każdy korzystałby jak gapowicz", "Bo obrona jest rywalizacyjna", "Bo nikt jej nie potrzebuje",
            why="Niewykluczalność uniemożliwia pobieranie opłat."),
          W("Jak opłata za wjazd do centrum zmienia charakter drogi?",
            "Czyni ją wykluczalną – staje się bliższa dobru klubowemu lub prywatnemu", "Czyni ją dobrem publicznym", "Nie zmienia",
            why="Można wykluczyć niepłacących."),
          M("Jakie są sposoby ochrony wspólnych zasobów?",
            ["Kwoty połowowe", "Opłaty za korzystanie", "Przypisanie praw własności", "Zniesienie wszelkich ograniczeń"], [0, 1, 2],
            why="Brak ograniczeń prowadzi do nadmiernej eksploatacji."),
          PF("Dobro klubowe jest wykluczalne, ale nierywalizacyjne.", True,
             why="Np. telewizja kodowana."),
      ],
      calc=[
          LB("Latarnia kosztuje 1 mln zł, korzysta z niej 200 armatorów ceniących ją po 8 000 zł. Ile wynosi łączna wartość (mln zł)?",
             1.6, "200*8000/1e6", ["200 · 8 000 = 1,6 mln zł"], unit="mln zł", tol=0.001),
          LB("Czy budowa jest społecznie opłacalna? Podaj korzyść netto (mln zł).",
             0.6, "1.6-1", ["1,6 − 1 = 0,6 mln zł > 0 → tak"], unit="mln zł", tol=0.001),
          LB("Ilu armatorów (po 8 000 zł) musiałoby dobrowolnie zapłacić, by sfinansować latarnię?",
             125, "1000000/8000", ["1 000 000 / 8 000 = 125"], unit="armatorów"),
          LB("Łowisko odnawia się o 20% rocznie przy zasobie 50 000 t. Ile ton można łowić bez zmniejszania zasobu?",
             10000, "50000*0.2", ["50 000 · 0,2 = 10 000 t"], unit="t"),
          LB("Rybacy łowią 15 000 t rocznie. O ile zasób zmniejszy się w pierwszym roku (t)?",
             5000, "15000-10000", ["15 000 − 10 000 = 5 000 t"], unit="t"),
          LB("Opłata za wjazd 20 zł zmniejsza ruch z 40 000 do 30 000 aut dziennie. Ile wynoszą dzienne wpływy (zł)?",
             600000, "20*30000", ["20 · 30 000 = 600 000 zł"], unit="zł"),
      ],
      case=[
          PR("Gmina rozważa pokaz sztucznych ogni na Sylwestra za 300 tys. zł. 60 tys. mieszkańców ceni pokaz średnio na 10 zł, ale prywatna firma nie chce go zorganizować.",
             W("Dlaczego firma nie chce go zorganizować?",
               "Nie może pobierać opłat od oglądających – problem gapowicza", "Bo pokaz jest nieopłacalny społecznie", "Bo pokaz jest rywalizacyjny",
               why="Niewykluczalność uniemożliwia sprzedaż biletów."),
             W("Czy pokaz jest społecznie opłacalny?",
               "Tak – wartość 600 tys. zł przewyższa koszt 300 tys. zł", "Nie", "Nie da się ocenić",
               why="60 000 · 10 = 600 000 zł."),
             PF("Finansowanie pokazu z podatków może zwiększyć dobrobyt mieszkańców.", True,
                why="Korzyści przewyższają koszty."),
          ),
          PR("Na Bałtyku zasoby dorsza spadły tak bardzo, że UE wprowadziła zakaz połowów ukierunkowanych na dorsza we wschodniej części morza. Rybacy protestują, bo tracą dochody.",
             W("Jakie zjawisko doprowadziło do spadku zasobów?",
               "Tragedia wspólnego pastwiska – nadmierna eksploatacja wspólnego zasobu", "Problem gapowicza przy dobrach publicznych", "Monopol naturalny",
               why="Łowisko jest niewykluczalne i rywalizacyjne."),
             W("Jakie rozwiązanie może pogodzić ochronę zasobu z dochodami rybaków w przyszłości?",
               "Zbywalne kwoty połowowe ustalone na poziomie odnawiania zasobu", "Zniesienie limitów", "Dotacje do zwiększania połowów",
               why="Ogranicza połowy i daje rybakom prawa o wartości rynkowej."),
             PF("Krótkookresowa strata dochodów może być ceną za przyszłą odbudowę łowiska.", True,
                why="Zasób musi się odnowić."),
          ),
      ]),
]
