# -*- coding: utf-8 -*-
# Zrozumienie – Mikroekonomia / Struktury rynku i strategie firm
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S81 = S("OpenStax, Principles of Economics 3e, 8.1 Perfect Competition", OS3 + "8-1-perfect-competition-and-why-it-matters", D)
S82 = S("OpenStax, Principles of Economics 3e, 8.2 Output Decisions", OS3 + "8-2-how-perfectly-competitive-firms-make-output-decisions", D)
S83 = S("OpenStax, Principles of Economics 3e, 8.3 Entry and Exit Decisions in the Long Run", OS3 + "8-3-entry-and-exit-decisions-in-the-long-run", D)
S84 = S("OpenStax, Principles of Economics 3e, 8.4 Efficiency in Perfectly Competitive Markets", OS3 + "8-4-efficiency-in-perfectly-competitive-markets", D)
S91 = S("OpenStax, Principles of Economics 3e, 9.1 How Monopolies Form", OS3 + "9-1-how-monopolies-form-barriers-to-entry", D)
S92 = S("OpenStax, Principles of Economics 3e, 9.2 Monopoly Output and Price", OS3 + "9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price", D)
S101 = S("OpenStax, Principles of Economics 3e, 10.1 Monopolistic Competition", OS3 + "10-1-monopolistic-competition", D)
S102 = S("OpenStax, Principles of Economics 3e, 10.2 Oligopoly", OS3 + "10-2-oligopoly", D)
S111 = S("OpenStax, Principles of Economics 3e, 11.1 Corporate Mergers", OS3 + "11-1-corporate-mergers", D)
S112 = S("OpenStax, Principles of Economics 3e, 11.2 Regulating Anticompetitive Behavior", OS3 + "11-2-regulating-anticompetitive-behavior", D)
S113 = S("OpenStax, Principles of Economics 3e, 11.3 Regulating Natural Monopolies", OS3 + "11-3-regulating-natural-monopolies", D)
SEU = S("Wytyczne Komisji Europejskiej w sprawie oceny horyzontalnego połączenia przedsiębiorstw (2004/C 31/03), pkt 19–20", "https://eur-lex.europa.eu/legal-content/PL/TXT/?uri=CELEX:52004XC0205(02)", D)

LESSONS = [
    L(1, "Konkurencja doskonała: cenobiorca i zero zysku w długim okresie",
      "Rozumieć założenia konkurencji doskonałej, decyzje firmy-cenobiorcy i mechanizm prowadzący do zerowego zysku ekonomicznego w długim okresie.",
      ["Konkurencja doskonała", "Krzywa podaży firmy doskonale konkurencyjnej", "Struktura rynku", "Zysk normalny"],
      [S81, S82, S83, S84],
      explain=[
          K("Cztery założenia",
            "Wielu małych sprzedawców i kupujących, jednorodny produkt, swobodne wejście i wyjście z rynku, pełna informacja. Żadna firma nie ma wpływu na cenę – jest cenobiorcą. Najbliżej tego modelu są rynki rolne i giełdowe."),
          K("Popyt na produkt jednej firmy jest poziomy",
            "Rynek jako całość ma opadającą krzywą popytu, ale pojedynczy rolnik może sprzedać dowolną ilość po cenie rynkowej. Jeśli podniesie cenę choćby o grosz, nikt nie kupi – wszyscy kupią u sąsiada. Dlatego dla firmy P = MR = AR."),
          W("Rolnik podnosi cenę pszenicy o 5% powyżej ceny rynkowej. Co się stanie?",
            "Nie sprzeda nic – kupujący pójdą do innych", "Sprzeda trochę mniej", "Zarobi więcej",
            why="Przy jednorodnym produkcie i wielu sprzedawcach popyt na produkt pojedynczej firmy jest doskonale elastyczny."),
          K("Krótki okres: zysk albo strata",
            "Firma wybiera produkcję, przy której P = MC. Jeśli cena jest wyższa od ATC – zarabia; niższa – traci, ale produkuje, dopóki P ≥ AVC. Krzywa MC powyżej minimum AVC to krzywa podaży firmy."),
          K("Długi okres: wejście i wyjście",
            "Zysk ekonomiczny przyciąga nowe firmy – podaż rośnie, cena spada. Strata wypycha firmy – podaż maleje, cena rośnie. Proces trwa, aż P = min ATC: zysk ekonomiczny wynosi zero, a produkcja odbywa się po najniższym możliwym koszcie (efektywność produkcyjna) i przy P = MC (efektywność alokacyjna).",
            g=G("sd", S=1)),
          PF("W długookresowej równowadze konkurencji doskonałej firmy nie zarabiają nic.", False,
             why="Zarabiają zysk normalny (pokrywają koszty alternatywne właścicieli) – zerowy jest tylko zysk ekonomiczny."),
      ],
      mech=[
          LN("Ułóż dostosowanie rynku po wzroście popytu na borówki.",
             ["Popyt na borówki rośnie", "Cena rośnie, plantatorzy mają zysk ekonomiczny", "Nowi rolnicy zakładają plantacje",
              "Podaż rynkowa rośnie", "Cena spada, aż zysk ekonomiczny znów wynosi zero"],
             why="Swobodne wejście likwiduje zysk nadzwyczajny w długim okresie."),
          WY("Na rynku konkurencji doskonałej firmy mają zysk ekonomiczny. Co stanie się z podażą w długim okresie?",
             G("sd", names={"D": "popyt rynkowy", "S": "podaż rynkowa"}, S=1),
             "Rośnie – wchodzą nowe firmy, cena spada", "Maleje – firmy wychodzą", "Nie zmienia się",
             why="Zysk przyciąga nowe firmy, co przesuwa podaż rynkową w prawo."),
          KT("Który rynek jest najbliżej konkurencji doskonałej?",
             {"Blisko konkurencji doskonałej": ["Skup pszenicy", "Handel walutami na rynku międzybankowym", "Akcje dużej spółki na giełdzie"],
              "Daleko od niej": ["Sieć kolejowa", "Smartfony z markowym systemem", "Lokalny monopol wodociągowy"]},
             why="Kluczowe są: jednorodność produktu, wielu uczestników i swobodne wejście."),
          W("Dlaczego w konkurencji doskonałej firmy nie reklamują swoich produktów?",
            "Produkt jest jednorodny, a firma może sprzedać wszystko po cenie rynkowej", "Reklama jest zakazana", "Firmy są za duże",
            why="Reklama nie zwiększy popytu na produkt niczym nieróżniący się od innych."),
          PF("W długim okresie firmy doskonale konkurencyjne produkują przy minimum przeciętnego kosztu całkowitego.", True,
             why="Konkurencja i wejście sprowadzają cenę do min ATC."),
          M("Które warunki opisują długookresową równowagę konkurencji doskonałej?",
            ["P = MC", "P = min ATC", "Zysk ekonomiczny dodatni", "Brak bodźca do wejścia lub wyjścia"],
            [0, 1, 3],
            why="Zysk ekonomiczny wynosi zero."),
      ],
      calc=[
          LB("Cena rynkowa 40 zł. Firma produkuje 500 szt. przy ATC = 32 zł. Ile wynosi zysk ekonomiczny?",
             4000, "500*(40-32)", ["(P − ATC) · Q = 8 · 500 = 4000 zł"], unit="zł"),
          LB("TC = 50 + 2Q², MC = 4Q. Cena 40 zł. Ile wyprodukuje firma?",
             10, "40/4", ["P = MC ⇒ 40 = 4Q", "Q = 10"], unit="szt."),
          LB("Dla tej firmy (TC = 50 + 2Q², P = 40, Q = 10) ile wynosi zysk?",
             150, "40*10-(50+2*10**2)", ["TR = 400", "TC = 50 + 200 = 250", "Zysk = 150 zł"], unit="zł"),
          LB("TC = 50 + 2Q². Przy jakiej cenie w długim okresie zysk będzie zerowy (P = min ATC; ATC = 50/Q + 2Q, minimum przy Q = 5)?",
             20, "50/5+2*5", ["min ATC przy Q = √(50/2) = 5", "ATC(5) = 10 + 10 = 20 zł"], unit="zł"),
          LB("Rynek ma popyt Q = 10 000 − 100P. W długim okresie P = 20 zł, a każda firma produkuje 5 sztuk. Ile firm będzie na rynku?",
             1600, "(10000-100*20)/5", ["Q rynkowe = 10 000 − 2000 = 8000", "8000 / 5 = 1600 firm"], unit="firm"),
          LB("Cena spada do 15 zł, AVC firmy w optimum = 12 zł, ATC = 18 zł, Q = 100. Ile wynosi strata, jeśli firma produkuje?",
             300, "100*(18-15)", ["(ATC − P) · Q = 3 · 100 = 300 zł", "Bez produkcji straciłaby FC = (18 − 12) · 100 = 600 zł"], unit="zł"),
      ],
      case=[
          PR("Kilka lat temu bardzo opłacalna była uprawa borówki amerykańskiej. Wielu rolników założyło plantacje. Po kilku latach ceny skupu wyraźnie spadły, a część plantatorów narzekała na niską opłacalność.",
             W("Jak teoria wyjaśnia spadek opłacalności?",
               "Wysokie zyski przyciągnęły nowych producentów, podaż wzrosła, a cena spadła", "Spadek jakości borówek", "Zmowa skupujących",
               why="Mechanizm wejścia na rynek sprowadza zysk ekonomiczny w stronę zera."),
             W("Dlaczego ten proces trwał kilka lat, a nie kilka tygodni?",
               "Plantacja borówek daje pełne plony dopiero po kilku latach", "Rolnicy nie znali cen", "Rynek był regulowany",
               why="Szybkość dostosowania zależy od czasu potrzebnego na zwiększenie podaży."),
             PF("Plantatorzy, którzy weszli najwcześniej, mogli zarobić więcej niż ci, którzy weszli najpóźniej.", True,
                why="Zysk ekonomiczny jest najwyższy przed wejściem konkurentów."),
          ),
          PR("Na rynku jajek jest kilkaset dużych ferm. Wybuch ptasiej grypy zmusza część z nich do likwidacji stad. Pozostałe fermy działają normalnie.",
             W("Co stanie się z ceną jajek w krótkim okresie?",
               "Wzrośnie – podaż rynkowa maleje", "Spadnie", "Nie zmieni się, bo fermy są cenobiorcami",
               why="Firmy są cenobiorcami, ale cena rynkowa zależy od łącznej podaży."),
             W("Jak zareagują fermy, które nie ucierpiały?",
               "Zwiększą produkcję, bo przy wyższej cenie P = MC przy większym Q", "Zmniejszą produkcję", "Podniosą cenę ponad rynkową",
               why="Firma porusza się po swojej krzywej MC (podaży)."),
             PF("W długim okresie, po odbudowie stad i wejściu nowych ferm, cena może wrócić w okolice minimum ATC.", True,
                why="Wejście nowych producentów przywraca długookresową równowagę."),
          ),
      ]),

    L(2, "Monopol: bariery wejścia, cena i strata społeczna",
      "Rozumieć źródła monopolu, wyznaczać produkcję i cenę monopolisty (MR = MC), stratę martwą monopolu i problem monopolu naturalnego.",
      ["Monopol", "Monopol naturalny", "Bariery wejścia", "Siła rynkowa i wskaźnik Lernera", "Nadwyżka mocy produkcyjnych"],
      [S91, S92, S113],
      explain=[
          K("Skąd biorą się monopole",
            "Bariery wejścia chronią monopol przed konkurencją: prawne (patenty, koncesje, licencje), kontrola kluczowego zasobu, korzyści skali (monopol naturalny), efekty sieciowe, wysokie koszty utopione wejścia."),
          K("Monopolista musi obniżyć cenę, by sprzedać więcej",
            "Monopolista ma przed sobą całą opadającą krzywą popytu. Gdy chce sprzedać jedną sztukę więcej, musi obniżyć cenę WSZYSTKICH sztuk. Dlatego jego utarg krańcowy jest niższy od ceny (MR < P).",
            w="dla P = a − bQ:  MR = a − 2bQ"),
          K("Jak monopolista ustala cenę",
            "1) Wybiera ilość, przy której MR = MC. 2) Ustala najwyższą cenę, jaką zapłacą kupujący przy tej ilości (z krzywej popytu). W efekcie produkuje mniej i taniej niż… nie – drożej niż w konkurencji: P > MC."),
          W("Monopolista produkuje tam, gdzie MR = MC = 20 zł, a przy tej ilości popyt pozwala żądać 35 zł. Jaką cenę ustali?",
            "35 zł", "20 zł", "27,50 zł",
            why="Ilość wyznacza MR = MC, a cenę – krzywa popytu przy tej ilości."),
          K("Strata martwa monopolu i monopol naturalny",
            "Ponieważ P > MC, nie dochodzi do transakcji, za które kupujący zapłaciliby więcej, niż wynosi koszt – to strata martwa. Monopol naturalny (sieci wodociągowe, energetyczne) ma tak duże korzyści skali, że jedna firma produkuje najtaniej; państwo zwykle go reguluje (np. ceny taryfowe zatwierdzane przez regulatora)."),
          PF("Monopolista zawsze ustala najwyższą możliwą cenę.", False,
             why="Ustala cenę maksymalizującą ZYSK – zbyt wysoka cena drastycznie obniżyłaby sprzedaż."),
      ],
      mech=[
          KT("Jakie źródło bariery wejścia?",
             {"Prawne": ["Patent na lek", "Koncesja na wydobycie", "Wyłączne prawo do nadawania na częstotliwości"],
              "Ekonomiczne": ["Ogromne korzyści skali sieci przesyłowej", "Kontrola jedynego złoża surowca", "Efekty sieciowe portalu społecznościowego"]},
             why="Bariery prawne tworzy państwo, ekonomiczne – technologia i struktura rynku."),
          LN("Ułóż, jak monopolista wybiera cenę.",
             ["Szacuje krzywą popytu i MR", "Znajduje ilość, przy której MR = MC", "Odczytuje z popytu najwyższą cenę dla tej ilości", "Sprzedaje mniej i drożej niż rynek konkurencyjny"],
             why="Wybór ilości poprzedza ustalenie ceny."),
          W("Dlaczego monopolista nigdy nie produkuje na nieelastycznym odcinku krzywej popytu?",
            "Tam MR < 0 – zmniejszenie produkcji zwiększyłoby przychód i obniżyło koszty", "Bo tam cena jest najwyższa", "Bo zakazuje tego prawo",
            why="Przy |E| < 1 obniżka ilości (podwyżka ceny) zwiększa przychód."),
          W("Jak najczęściej państwo postępuje z monopolem naturalnym w sieci wodociągowej?",
            "Reguluje ceny i jakość (taryfy zatwierdzane przez regulatora)", "Zmusza do podziału na 10 konkurujących sieci", "Nic nie robi",
            why="Duplikowanie sieci byłoby marnotrawstwem; regulacja ogranicza nadużywanie pozycji."),
          PF("Wskaźnik Lernera (P − MC)/P równy 0 oznacza brak siły rynkowej.", True,
             why="W konkurencji doskonałej P = MC."),
          M("Jakie są skutki monopolu w porównaniu z konkurencją doskonałą?",
            ["Wyższa cena", "Mniejsza produkcja", "Wyższa nadwyżka konsumenta", "Strata martwa"],
            [0, 1, 3],
            why="Nadwyżka konsumenta jest mniejsza – część przejmuje monopolista, część znika."),
      ],
      calc=[
          LB("Popyt P = 100 − 2Q, więc MR = 100 − 4Q. MC = 20 zł (stały). Ile wyprodukuje monopolista?",
             20, "(100-20)/4", ["MR = MC ⇒ 100 − 4Q = 20", "Q = 20"], unit="szt."),
          LB("Jaką cenę ustali ten monopolista (P = 100 − 2Q, Q = 20)?",
             60, "100-2*20", ["P = 100 − 40 = 60 zł"], unit="zł"),
          LB("Ile wynosi zysk monopolisty (bez kosztów stałych, MC = AC = 20)?",
             800, "(60-20)*20", ["(P − AC) · Q = 40 · 20 = 800 zł"], unit="zł"),
          LB("Ile wyprodukowałby rynek konkurencyjny (P = MC = 20, popyt P = 100 − 2Q)?",
             40, "(100-20)/2", ["100 − 2Q = 20 ⇒ Q = 40"], unit="szt."),
          LB("Ile wynosi strata martwa monopolu (trójkąt między Q = 20 a Q = 40)?",
             400, "0.5*(60-20)*(40-20)", ["½ · (P_m − MC) · (Q_k − Q_m)", "= ½ · 40 · 20 = 400 zł"], unit="zł"),
          LB("Ile wynosi wskaźnik Lernera tego monopolisty ((P − MC)/P)?",
             0.67, "(60-20)/60", ["(60 − 20) / 60 ≈ 0,67"], unit="", tol=0.01),
      ],
      case=[
          PR("Firma farmaceutyczna ma patent na nowy lek. Koszt wyprodukowania tabletki to 2 zł, a cena – 80 zł. Firma argumentuje, że wydała miliardy na badania, w tym na wiele nieudanych projektów. Patent wygasa za 3 lata.",
             W("Co pozwala firmie utrzymać cenę wielokrotnie wyższą od kosztu krańcowego?",
               "Patent – prawna bariera wejścia", "Konkurencja doskonała", "Niski popyt",
               why="Patent wyklucza konkurentów na określony czas."),
             W("Co zwykle stanie się po wygaśnięciu patentu?",
               "Wejdą producenci leków generycznych, a cena spadnie", "Cena wzrośnie", "Lek zniknie z rynku",
               why="Zniknięcie bariery wejścia przyciąga konkurencję."),
             PF("Patenty tworzą kompromis: krótkookresowa strata martwa w zamian za zachęty do innowacji.", True,
                why="Bez ochrony patentowej trudno odzyskać ogromne koszty badań."),
          ),
          PR("W mieście działa jedna sieć ciepłownicza. Budowa drugiej sieci obok byłaby bardzo kosztowna. Cena ciepła dla mieszkańców wymaga zatwierdzenia taryfy przez regulatora (w Polsce – Prezesa URE).",
             W("Jakiego rodzaju monopol tu występuje?",
               "Monopol naturalny", "Monopol prawny wynikający z patentu", "Kartel",
               why="Ogromne koszty stałe sieci sprawiają, że jedna firma dostarcza najtaniej."),
             W("Po co regulator zatwierdza taryfy?",
               "By ograniczyć nadużywanie pozycji monopolisty przy cenach", "By zwiększyć konkurencję w sieci", "By zmniejszyć jakość usług",
               why="Bez regulacji monopolista mógłby ustalić cenę znacznie powyżej kosztów."),
             M("Jakie są trudności regulowania cen monopolu naturalnego?",
               ["Regulator nie zna dokładnie kosztów firmy", "Cena oparta na kosztach słabo motywuje do ich obniżania", "Regulacja zawsze tworzy konkurencję", "Ryzyko zbyt niskiej ceny ograniczającej inwestycje"],
               [0, 1, 3],
               why="Regulacja nie tworzy konkurencji – zastępuje ją."),
          ),
      ]),

    L(3, "Dyskryminacja cenowa i konkurencja monopolistyczna",
      "Rozumieć warunki i rodzaje dyskryminacji cenowej oraz model konkurencji monopolistycznej: różnicowanie produktu, reklama i nadwyżka mocy w długim okresie.",
      ["Dyskryminacja (różnicowanie) cenowa", "Konkurencja monopolistyczna", "Nadwyżka mocy produkcyjnych", "Struktura rynku"],
      [S101, S92],
      explain=[
          K("Dyskryminacja cenowa",
            "To sprzedaż tego samego produktu różnym klientom po różnych cenach, niewynikających z różnic w kosztach. Warunki: firma ma siłę rynkową, może rozdzielić klientów na grupy o różnej elastyczności popytu i zapobiec odsprzedaży."),
          K("Trzy stopnie",
            "1. stopień: każdy płaci swoją maksymalną cenę (aukcje, indywidualne negocjacje). 2. stopień: cena zależy od ilości (rabaty za większe opakowanie). 3. stopień: różne ceny dla grup (studenci, seniorzy, różne kraje). Wyższą cenę płaci grupa o mniej elastycznym popycie."),
          W("Zniżki studenckie na bilety do kina to przykład:",
            "Dyskryminacji cenowej 3. stopnia", "Dyskryminacji 1. stopnia", "Konkurencji doskonałej",
            why="Cena zależy od grupy klientów o innej elastyczności popytu."),
          K("Konkurencja monopolistyczna",
            "Wiele firm, swobodne wejście, ale produkty ZRÓŻNICOWANE (restauracje, fryzjerzy, marki odzieży). Każda firma ma „mały monopol” na swoją wersję produktu i opadającą krzywą popytu. Konkuruje ceną, jakością, lokalizacją i reklamą."),
          K("Długi okres: zero zysku i nadwyżka mocy",
            "Zyski przyciągają nowe firmy z podobnymi produktami, popyt na produkt każdej firmy maleje, aż zysk ekonomiczny = 0 (P = ATC). Ponieważ popyt jest opadający, styczność z ATC następuje na lewo od minimum ATC – firmy mają niewykorzystane moce (stoliki stoją puste). To cena za różnorodność."),
          PF("Dyskryminacja cenowa zawsze zmniejsza produkcję w porównaniu z jedną ceną.", False,
             why="Często zwiększa produkcję – firma sprzedaje też tym, którzy nie kupiliby po jednej, wyższej cenie."),
      ],
      mech=[
          KT("Który stopień dyskryminacji cenowej?",
             {"1. stopień": ["Sprzedawca samochodów negocjuje z każdym klientem osobno", "Aukcja internetowa"],
              "2. stopień": ["Rabat przy kupnie 3 sztuk", "Taniej za litr w opakowaniu 5-litrowym"],
              "3. stopień": ["Bilet ulgowy dla seniora", "Inna cena leku w różnych krajach", "Taniej rano w kinie"]},
             why="1. – indywidualnie, 2. – według ilości, 3. – według grup."),
          W("Dlaczego linie lotnicze sprzedają droższe bilety na ostatnią chwilę?",
            "Osoby kupujące w ostatniej chwili (często podróże służbowe) mają mniej elastyczny popyt", "Koszt lotu rośnie w ostatniej chwili", "Prawo tego wymaga",
            why="To dyskryminacja według elastyczności popytu."),
          LN("Ułóż dostosowanie rynku restauracji w długim okresie.",
             ["Nowa kuchnia staje się modna i restauracje zarabiają", "Otwierają się podobne lokale", "Popyt na każdą restaurację maleje",
              "Zysk ekonomiczny spada do zera", "Restauracje działają przy niepełnym wykorzystaniu sal"],
             why="To długookresowa równowaga konkurencji monopolistycznej."),
          W("Czym różni się konkurencja monopolistyczna od doskonałej?",
            "Produkty są zróżnicowane, a firmy mają pewien wpływ na cenę", "Na rynku jest jedna firma", "Wejście na rynek jest zablokowane",
            why="W obu modelach jest wiele firm i swobodne wejście; różni je zróżnicowanie produktów."),
          PF("Odsprzedaż między grupami klientów utrudnia dyskryminację cenową.", True,
             why="Ci, którzy kupili taniej, mogliby odsprzedać produkt grupie płacącej więcej."),
          M("Jakie są typowe cechy konkurencji monopolistycznej?",
            ["Reklama i budowanie marki", "Swobodne wejście", "Jednorodny produkt", "Opadająca krzywa popytu na produkt firmy"],
            [0, 1, 3],
            why="Produkt jest zróżnicowany, a nie jednorodny."),
      ],
      calc=[
          LB("Kino ma 2 grupy: dorośli (100 osób, płacą do 30 zł) i studenci (60 osób, płacą do 18 zł). Koszt widza ≈ 0. Ile wyniesie przychód przy jednej cenie 30 zł?",
             3000, "100*30", ["Kupują tylko dorośli: 100 · 30 = 3000 zł"], unit="zł"),
          LB("Ile wyniesie przychód przy jednej cenie 18 zł?",
             2880, "160*18", ["Kupują wszyscy: 160 · 18 = 2880 zł"], unit="zł"),
          LB("Ile wyniesie przychód przy cenach 30 zł (dorośli) i 18 zł (studenci)?",
             4080, "100*30+60*18", ["3000 + 1080 = 4080 zł – więcej niż przy każdej jednej cenie"], unit="zł"),
          LB("Grupa A: |E| = 1,5; grupa B: |E| = 3. MC = 20 zł. Reguła: P = MC · |E| / (|E| − 1). Jaką cenę ustali firma w grupie A?",
             60, "20*1.5/(1.5-1)", ["P = 20 · 1,5 / 0,5 = 60 zł"], unit="zł"),
          LB("Jaką cenę ustali w grupie B (|E| = 3, MC = 20)?",
             30, "20*3/(3-1)", ["P = 20 · 3 / 2 = 30 zł – niższa cena dla bardziej elastycznej grupy"], unit="zł"),
          LB("Restauracja ma 80 miejsc, a w długookresowej równowadze średnio zajętych jest 56. Ile procent mocy jest niewykorzystane?",
             30, "(80-56)/80*100", ["24 / 80 = 30%"], unit="%"),
      ],
      case=[
          PR("Producent oprogramowania sprzedaje program w wersji dla firm za 1200 zł, dla osób prywatnych za 400 zł i dla uczniów za 100 zł. Wszystkie wersje mają te same funkcje; koszt kolejnej licencji jest bliski zeru.",
             W("Dlaczego producent może utrzymać różne ceny?",
               "Rozdziela klientów (np. weryfikacja legitymacji, licencje firmowe) i ogranicza odsprzedaż", "Wersje kosztują różnie w produkcji", "Rynek jest doskonale konkurencyjny",
               why="Kluczem jest segmentacja i zapobieganie arbitrażowi."),
             W("Która grupa ma najmniej elastyczny popyt?",
               "Firmy", "Uczniowie", "Osoby prywatne",
               why="Najwyższą cenę płaci grupa najmniej wrażliwa na cenę."),
             PF("Tania wersja dla uczniów może zwiększyć przyszłe przychody, bo przyzwyczaja przyszłych pracowników do programu.", True,
                why="To strategia budowania lojalności i efektów sieciowych."),
          ),
          PR("Na jednej ulicy działa 12 kawiarni. Każda ma inny wystrój, menu i stałych klientów. Gdy otworzyła się trzynasta, kilka dotychczasowych straciło część gości. Właściciele narzekają, że rzadko mają komplet.",
             W("Jaka to struktura rynku?",
               "Konkurencja monopolistyczna", "Monopol", "Oligopol", "Konkurencja doskonała",
               why="Wiele firm, zróżnicowane produkty, swobodne wejście."),
             W("Co oznacza „rzadki komplet” w języku teorii?",
               "Nadwyżkę mocy produkcyjnych w długookresowej równowadze", "Monopol naturalny", "Stratę martwą podatku",
               why="Firmy produkują na lewo od minimum ATC."),
             M("Jak kawiarnie mogą bronić się przed spadkiem popytu?",
               ["Wyróżnić ofertę (np. specjalność, wystrój)", "Budować lojalność stałych klientów", "Zawrzeć zmowę cenową z pozostałymi", "Lepiej dopasować godziny otwarcia"],
               [0, 1, 3],
               why="Zmowa cenowa jest nielegalna i przy łatwym wejściu nietrwała."),
          ),
      ]),

    L(4, "Oligopol i teoria gier",
      "Rozumieć współzależność decyzji w oligopolu, rozwiązywać proste gry (strategia dominująca, równowaga Nasha, dylemat więźnia) i wyjaśniać, dlaczego kartele są niestabilne.",
      ["Oligopol", "Duopol", "Teoria gier", "Strategia dominująca", "Równowaga Nasha", "Dylemat więźnia", "Gry powtarzalne i kooperacja", "Kartel",
       "Model Cournota", "Model Bertranda", "Załamana krzywa popytu (model Sweezy’ego)", "Lider cenowy"],
      [S102],
      explain=[
          K("Kilka dużych firm, które się obserwują",
            "W oligopolu działa kilka firm, a decyzja każdej (cena, produkcja, reklama) wpływa na pozostałe. Firma musi przewidywać reakcje konkurentów – dlatego do analizy używa się teorii gier."),
          K("Strategia dominująca i równowaga Nasha",
            "Strategia dominująca jest najlepsza niezależnie od tego, co zrobi rywal. Równowaga Nasha to zestaw strategii, w którym żaden gracz nie chce zmienić swojej decyzji, znając decyzję drugiego."),
          K("Dylemat więźnia i kartel",
            "Dwie firmy zarobiłyby najwięcej, utrzymując wysoką cenę (zmowa). Ale każda z osobna zarabia jeszcze więcej, gdy obniży cenę, a druga nie. Obie więc obniżają ceny i zarabiają mniej. Dlatego kartele są niestabilne – każdemu członkowi opłaca się oszukiwać."),
          W("Obie firmy mają strategię dominującą „niska cena”. Jaka jest równowaga Nasha?",
            "Obie ustalają niską cenę", "Obie ustalają wysoką cenę", "Nie ma równowagi",
            why="Gdy obie grają swoje strategie dominujące, żadna nie chce zmienić decyzji."),
          K("Gry powtarzalne i modele oligopolu",
            "Gdy gra się powtarza, opłaca się współpraca: zdradę można ukarać w kolejnych rundach (strategia „wet za wet” z badań Axelroda). Model Cournota – firmy wybierają ilości; Bertranda – ceny (dwie firmy z identycznym produktem mogą zbić cenę do kosztu krańcowego). Model Sweezy’ego tłumaczy sztywność cen: konkurenci dopasują się do obniżki, ale nie do podwyżki."),
          PF("W jednorazowym dylemacie więźnia obu graczom opłaca się współpracować.", False,
             why="Każdemu z osobna opłaca się zdradzić – stąd wynik gorszy dla obu."),
      ],
      mech=[
          LN("Ułóż, dlaczego kartel się rozpada.",
             ["Firmy umawiają się na wysoką cenę i niskie ilości", "Każda zauważa, że potajemne zwiększenie sprzedaży da jej więcej", "Część członków zaczyna oszukiwać",
              "Podaż rośnie, cena spada", "Kartel traci sens"],
             why="Indywidualna pokusa zdrady przeważa nad wspólnym interesem."),
          W("Dlaczego w oligopolu ceny bywają sztywne (model załamanej krzywej popytu)?",
            "Konkurenci dopasują się do obniżki, ale nie do podwyżki – zmiana ceny w żadną stronę się nie opłaca", "Bo państwo ustala ceny", "Bo koszty są stałe",
            why="Podwyżka traci klientów, obniżka nie przynosi ich wielu – lepiej utrzymać cenę."),
          KT("Co ułatwia, a co utrudnia zmowę?",
             {"Ułatwia": ["Mała liczba firm", "Jednorodny produkt", "Przejrzyste ceny i częste kontakty"],
              "Utrudnia": ["Wiele firm", "Łatwe wejście nowych konkurentów", "Wysokie kary i program łagodzenia kar"]},
             why="Zmowa jest łatwiejsza, gdy łatwo ją uzgodnić i wykryć oszustwo."),
          W("Co to jest program łagodzenia kar (leniency)?",
            "Pierwszy uczestnik kartelu, który go ujawni, może uniknąć kary – to wzmacnia pokusę zdrady", "Obniżka podatków dla karteli", "Zwolnienie z prawa konkurencji",
            why="Program wykorzystuje logikę dylematu więźnia przeciw kartelom."),
          PF("W modelu Bertranda dwie firmy z identycznym produktem i takim samym kosztem mogą obniżyć cenę do poziomu kosztu krańcowego.", True,
             why="Każda podcina cenę drugiej, aż zysk zniknie."),
          M("Które zjawiska są typowe dla oligopolu?",
            ["Współzależność decyzji", "Bariery wejścia", "Cena ustalona przez rynek bez wpływu firm", "Pokusa zmowy"],
            [0, 1, 3],
            why="Firmy oligopolistyczne mają wpływ na cenę."),
      ],
      calc=[
          LB("Macierz zysków (mln zł), A/B: obie wysoka cena: (10, 10); A niska, B wysoka: (14, 4); A wysoka, B niska: (4, 14); obie niska: (6, 6). Ile zarobi A w równowadze Nasha?",
             6, "6", ["Dla A: niska daje 14 > 10 (gdy B wysoka) i 6 > 4 (gdy B niska) – strategia dominująca", "To samo dla B → obie niska: (6, 6)"], unit="mln zł"),
          LB("O ile mniej zarabiają razem obie firmy w równowadze Nasha niż przy zmowie (obie wysoka)?",
             8, "(10+10)-(6+6)", ["Zmowa: 20", "Nash: 12", "Różnica: 8 mln zł"], unit="mln zł"),
          LB("W tej grze: ile zyskuje A, zdradzając zmowę (A niska, B wysoka zamiast obie wysoka)?",
             4, "14-10", ["14 − 10 = 4 mln zł – pokusa zdrady"], unit="mln zł"),
          LB("Model Cournota: popyt P = 120 − Q, MC = 0, dwie identyczne firmy. W równowadze każda produkuje (120 − MC)/3. Ile produkuje jedna firma?",
             40, "120/3", ["q = 120 / 3 = 40"], unit="szt."),
          LB("Ile wynosi cena w tym duopolu Cournota (Q = 80)?",
             40, "120-80", ["P = 120 − 80 = 40"], unit="zł"),
          LB("Dla porównania: monopolista przy tym popycie (MR = 120 − 2Q = 0) ustala cenę… ile?",
             60, "120-60", ["Q = 60", "P = 60 – wyżej niż w duopolu (40), a w konkurencji P = MC = 0"], unit="zł"),
      ],
      case=[
          PR("Na rynku cementu działają 4 duże firmy. Urząd ochrony konkurencji ustalił, że przez kilka lat wymieniały informacje o cenach i dzieliły się rynkiem regionalnie. Jedna z firm sama zgłosiła zmowę i otrzymała znacznie obniżoną karę.",
             W("Dlaczego zmowa była możliwa na tym rynku?",
               "Mała liczba firm i jednorodny produkt", "Ogromna liczba drobnych producentów", "Produkt bardzo zróżnicowany",
               why="Oligopol z jednorodnym produktem sprzyja koordynacji."),
             W("Dlaczego firma sama zgłosiła zmowę?",
               "Program łagodzenia kar nagradza pierwszego, który ujawni kartel", "Bo kartel był bardzo zyskowny", "Bo musiała to zrobić co roku",
               why="To zastosowanie dylematu więźnia przeciw uczestnikom kartelu."),
             PF("Podział rynku regionami szkodzi odbiorcom, bo eliminuje konkurencję cenową.", True,
                why="Każda firma staje się „monopolistą” w swoim regionie."),
          ),
          PR("Dwie stacje paliw stoją naprzeciwko siebie przy drodze. Jeśli obie trzymają cenę 7,00 zł, każda zarabia 5000 zł dziennie. Jeśli jedna obniży do 6,80 zł, a druga nie, obniżająca zarabia 7000 zł, druga 2000 zł. Jeśli obie obniżą – po 3500 zł.",
             W("Jaka jest strategia dominująca każdej stacji?",
               "Obniżka ceny", "Utrzymanie ceny 7,00 zł", "Brak strategii dominującej",
               why="7000 > 5000 i 3500 > 2000 – obniżka jest lepsza niezależnie od rywala."),
             LB("Ile łącznie tracą stacje dziennie w równowadze Nasha w porównaniu z utrzymaniem cen?",
                3000, "(5000+5000)-(3500+3500)", ["10 000 − 7000 = 3000 zł"], unit="zł"),
             W("Co może sprawić, że stacje utrzymają wyższe ceny bez nielegalnej zmowy?",
               "Powtarzalność gry – każda wie, że obniżka spotka się z natychmiastową reakcją", "Brak klientów", "Zakaz obniżek",
               why="W grach powtarzalnych groźba odwetu może podtrzymywać współpracę (to zjawisko bywa jednak badane przez urzędy konkurencji)."),
          ),
      ]),

    L(5, "Koncentracja rynku i ochrona konkurencji",
      "Liczyć wskaźniki koncentracji (CR4, HHI), rozumieć progi oceny fuzji w UE, rynki kontestowalne oraz praktyki ograniczające konkurencję (ceny drapieżne, ceny zaporowe).",
      ["Wskaźniki koncentracji rynku (CR, HHI)", "Rynki kontestowalne", "Ceny zaporowe (limit pricing) i ceny drapieżne",
       "Formy monopolizacji (porozumienia i koncentracje)", "Siła rynkowa i wskaźnik Lernera", "Ekonomia przemysłowa (Industrial Organization)"],
      [S111, S112, SEU],
      explain=[
          K("CR4 – udział czterech największych",
            "Wskaźnik CR4 to suma udziałów w rynku czterech największych firm. Jest prosty, ale nie mówi, jak rozkłada się siła między nimi (25% + 25% + 25% + 25% i 97% + 1% + 1% + 1% dają ten sam CR4 = 100%)."),
          K("HHI – suma kwadratów udziałów",
            "Wskaźnik Herfindahla-Hirschmana to suma kwadratów udziałów wszystkich firm (w %). Maksimum 10 000 (monopol), bliski 0 przy bardzo wielu małych firmach. Kwadraty sprawiają, że duże firmy ważą znacznie więcej.",
            w="HHI = s₁² + s₂² + … + sₙ²;  Δ po fuzji firm A i B = 2·sA·sB"),
          W("Rynek ma 5 firm po 20% udziału. Ile wynosi HHI?",
            "2000", "100", "500", "10 000",
            why="5 · 20² = 5 · 400 = 2000."),
          K("Progi w UE",
            "Według wytycznych Komisji Europejskiej (2004) fuzje zwykle nie budzą zastrzeżeń, gdy HHI po połączeniu < 1000; gdy HHI wynosi 1000–2000, a przyrost (delta) < 250; albo gdy HHI > 2000, a delta < 150. Progi to wstępne sito – nie przesądzają decyzji."),
          K("Rynki kontestowalne i praktyki wykluczające",
            "Według teorii rynków kontestowalnych (Baumol) nawet jedna firma zachowuje się konkurencyjnie, jeśli wejście i wyjście są tanie i szybkie – groźba wejścia dyscyplinuje. Ceny zaporowe: tak niskie, by nowi nie weszli. Ceny drapieżne: poniżej kosztów, by wyeliminować rywala, a potem je podnieść – zakazane jako nadużycie pozycji dominującej."),
          PF("Wysoki HHI zawsze oznacza, że firmy zawarły zmowę.", False,
             why="HHI mierzy koncentrację, nie zachowanie – skoncentrowany rynek może być konkurencyjny (np. kontestowalny)."),
      ],
      mech=[
          LN("Ułóż strategię cen drapieżnych.",
             ["Dominująca firma obniża ceny poniżej kosztów", "Mniejszy rywal ponosi straty", "Rywal wycofuje się z rynku",
              "Dominująca firma podnosi ceny powyżej poziomu konkurencyjnego", "Odzyskuje straty kosztem klientów"],
             why="Dlatego takie praktyki są zakazane jako nadużycie pozycji dominującej."),
          KT("Co zwiększa kontestowalność rynku?",
             {"Zwiększa": ["Możliwość wynajęcia samolotów zamiast ich kupowania", "Niskie koszty utopione wejścia", "Brak barier prawnych"],
              "Zmniejsza": ["Konieczność budowy własnej sieci kolejowej", "Długoletnie umowy na wyłączność", "Wysokie koszty utopione reklamy marki"]},
             why="Kontestowalność zależy od kosztów wejścia i wyjścia, zwłaszcza utopionych."),
          W("Dwie firmy mają po 30% rynku i chcą się połączyć. Ile wynosi przyrost HHI (delta)?",
            "1800", "60", "900", "3600",
            why="Delta = 2 · 30 · 30 = 1800."),
          W("Dlaczego HHI lepiej niż CR4 opisuje siłę rynkową?",
            "Uwzględnia wszystkie firmy i większą wagę daje dużym", "Jest łatwiejszy do policzenia", "Zawsze daje niższe wartości",
            why="Kwadraty udziałów rosną szybko dla dużych firm, a wskaźnik obejmuje cały rynek."),
          PF("Rynek z jedną firmą może być konkurencyjny w zachowaniu, jeśli wejście jest łatwe i tanie.", True,
             why="To główna teza teorii rynków kontestowalnych."),
          M("Które działania mogą naruszać prawo konkurencji?",
            ["Porozumienie cenowe konkurentów", "Ceny drapieżne firmy dominującej", "Obniżka cen dzięki niższym kosztom", "Podział rynku między konkurentów"],
            [0, 1, 3],
            why="Obniżka cen wynikająca z efektywności to normalna konkurencja."),
      ],
      calc=[
          LB("Udziały: 40%, 25%, 15%, 10%, 5%, 5%. Ile wynosi CR4?",
             90, "40+25+15+10", ["40 + 25 + 15 + 10 = 90%"], unit="%"),
          LB("Ile wynosi HHI dla tych udziałów (40, 25, 15, 10, 5, 5)?",
             2600, "40**2+25**2+15**2+10**2+5**2+5**2", ["1600 + 625 + 225 + 100 + 25 + 25 = 2600"], unit=""),
          LB("Firmy z udziałami 10% i 5% łączą się. Ile wynosi delta HHI?",
             100, "2*10*5", ["Δ = 2 · 10 · 5 = 100"], unit=""),
          LB("HHI przed fuzją 2600, delta 100. Ile wynosi HHI po fuzji?",
             2700, "2600+100", ["2600 + 100 = 2700 (> 2000, delta < 150 – zwykle bez zastrzeżeń według wytycznych UE)"], unit=""),
          LB("Rynek 10 firm po 10% udziału. Ile wynosi HHI?",
             1000, "10*10**2", ["10 · 100 = 1000"], unit=""),
          LB("Na rynku 4 firmy: 50%, 30%, 10%, 10%. Łączą się dwie najmniejsze. Ile wynosi delta HHI?",
             200, "2*10*10", ["Δ = 2 · 10 · 10 = 200"], unit=""),
      ],
      case=[
          PR("Dwie sieci drogerii chcą się połączyć. Na krajowym rynku mają 22% i 18% udziału; pozostałe udziały to: 20%, 15%, 10%, 10% i 5%.",
             LB("Ile wynosi HHI przed fuzją?",
                1658, "22**2+18**2+20**2+15**2+10**2+10**2+5**2", ["Kwadraty: 484, 324, 400, 225, 100, 100, 25", "Suma: 1658 (po fuzji: 1658 + 792 = 2450)"], unit=""),
             LB("Ile wynosi delta HHI po fuzji?",
                792, "2*22*18", ["Δ = 2 · 22 · 18 = 792"], unit=""),
             W("Jak fuzja wypada w świetle progów z wytycznych UE?",
               "HHI po fuzji > 2000 i delta znacznie > 150 – wymaga dokładnej analizy", "Nie budzi żadnych wątpliwości", "Progi jej nie dotyczą",
               why="Wartości przekraczają „bezpieczne przystanie” z pkt 19–20 wytycznych."),
          ),
          PR("Tania linia lotnicza otwiera trasę, na której dotąd latał tylko jeden przewoźnik. Samoloty linia wynajmuje w leasingu i może je szybko przenieść na inne trasy. Dotychczasowy przewoźnik po ogłoszeniu wejścia rywala obniżył ceny o 40%, choć wcześniej twierdził, że niższe ceny są nieopłacalne.",
             W("Dlaczego wejście na tę trasę jest stosunkowo łatwe?",
               "Niskie koszty utopione – samoloty z leasingu można przenieść", "Brak pasażerów", "Państwowy zakaz konkurencji",
               why="To warunek kontestowalności rynku."),
             W("Jak może być oceniona obniżka cen o 40% przez dominującego przewoźnika?",
               "Może być badana jako potencjalna cena drapieżna, jeśli jest poniżej kosztów", "To zawsze legalne", "To zawsze kartel",
               why="Liczy się, czy cena jest poniżej odpowiedniej miary kosztów i czy celem jest wyeliminowanie rywala."),
             PF("Sama groźba wejścia nowych linii może utrzymywać niskie ceny nawet wtedy, gdy na trasie lata tylko jeden przewoźnik.", True,
                why="To teza teorii rynków kontestowalnych."),
          ),
      ]),
]
