# -*- coding: utf-8 -*-
# Zrozumienie – Mikroekonomia / Wzory (lekcje obliczeniowe)
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
SA = S("OpenStax, Principles of Economics 3e, Appendix A – The Use of Mathematics", OS3 + "a-the-use-of-mathematics-in-principles-of-economics", D)
S51 = S("OpenStax, Principles of Economics 3e, 5.1 Price Elasticity", OS3 + "5-1-price-elasticity-of-demand-and-price-elasticity-of-supply", D)
S54 = S("OpenStax, Principles of Economics 3e, 5.4 Elasticity in Areas Other Than Price", OS3 + "5-4-elasticity-in-areas-other-than-price", D)
S35 = S("OpenStax, Principles of Economics 3e, 3.5 Demand, Supply, and Efficiency", OS3 + "3-5-demand-supply-and-efficiency", D)
S73 = S("OpenStax, Principles of Economics 3e, 7.3 Costs in the Short Run", OS3 + "7-3-costs-in-the-short-run", D)
S82 = S("OpenStax, Principles of Economics 3e, 8.2 Output Decisions", OS3 + "8-2-how-perfectly-competitive-firms-make-output-decisions", D)
S92 = S("OpenStax, Principles of Economics 3e, 9.2 Monopoly Output and Price", OS3 + "9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price", D)
S111 = S("OpenStax, Principles of Economics 3e, 11.1 Corporate Mergers (HHI)", OS3 + "11-1-corporate-mergers", D)
S61 = S("OpenStax, Principles of Economics 3e, 6.1 Consumption Choices", OS3 + "6-1-consumption-choices", D)
S74 = S("OpenStax, Principles of Economics 3e, 7.4 Production in the Long Run", OS3 + "7-4-production-in-the-long-run", D)
S141 = S("OpenStax, Principles of Economics 3e, 14.1 The Theory of Labor Markets", OS3 + "14-1-the-theory-of-labor-markets", D)

LESSONS = [
    L(1, "Warsztat: elastyczności krok po kroku",
      "Sprawnie liczyć elastyczność cenową, dochodową, krzyżową i podaży (od wartości początkowych, łukowo i punktowo) oraz interpretować wyniki.",
      ["Elastyczność cenowa popytu – wzór", "Elastyczność dochodowa i mieszana – wzór", "Elastyczność cenowa podaży", "Funkcja o stałej elastyczności"],
      [S51, S54, SA],
      explain=[
          K("Jeden schemat dla wszystkich elastyczności",
            "Każda elastyczność to stosunek dwóch zmian procentowych: „skutku” do „przyczyny”. Cenowa popytu: ilość / cena tego dobra. Dochodowa: ilość / dochód. Krzyżowa: ilość X / cena Y. Podaży: ilość oferowana / cena.",
            w="E = (%Δ skutku) / (%Δ przyczyny)"),
          K("Trzy sposoby liczenia procentów",
            "Od wartości początkowej (prosto, ale wynik zależy od kierunku zmiany). Łukowo – metodą punktu środkowego (dzielimy przez średnią). Punktowo dla funkcji liniowej Q = a − bP: E = −b · P/Q.",
            w="łukowa: [ΔQ/((Q₁+Q₂)/2)] / [ΔP/((P₁+P₂)/2)];  punktowa: E = (dQ/dP)·(P/Q)"),
          W("Q = 300 − 5P, P = 20. Ile wynosi |E| punktowa?",
            "0,5", "2", "5", "0,25",
            why="Q = 300 − 100 = 200; |E| = 5 · 20 / 200 = 0,5."),
          K("Stała elastyczność",
            "Funkcja Q = A · P^(−e) ma stałą elastyczność równą e przy każdej cenie. To przydatne w szacunkach empirycznych (np. popyt na paliwo) – wzrost ceny o 1% zawsze zmienia ilość o e%.",
            w="Q = A · P^(−e)  ⇒  |E| = e"),
          K("Interpretacja znaków",
            "Cenowa popytu: zwykle ujemna (porównujemy |E| z 1). Dochodowa: > 1 luksusowe, 0–1 podstawowe, < 0 niższego rzędu. Krzyżowa: > 0 substytuty, < 0 komplementy. Podaży: zwykle dodatnia."),
          PF("Przy liniowej funkcji popytu elastyczność w punkcie P = a/(2b) wynosi 1.", True,
             why="Środek liniowej krzywej popytu to punkt elastyczności jednostkowej."),
      ],
      mech=[
          KT("Jaki wniosek z wyniku?",
             {"Popyt elastyczny": ["|E| = 1,8", "Ilość −15% przy cenie +5%"],
              "Popyt nieelastyczny": ["|E| = 0,3", "Ilość −2% przy cenie +10%"],
              "Dobro niższego rzędu": ["Ed = −0,4", "Dochód +10%, popyt −3%"],
              "Komplementy": ["Exy = −0,6", "Cena Y +10%, popyt na X −5%"]},
             why="Wartość i znak elastyczności mówią o rodzaju reakcji."),
          W("Na liniowej krzywej popytu cena rośnie. Co dzieje się z |E|?",
            "Rośnie", "Maleje", "Nie zmienia się",
            why="|E| = b·P/Q – P rośnie, Q maleje, więc iloraz rośnie."),
          LN("Ułóż kroki obliczania elastyczności łukowej.",
             ["Oblicz zmianę ilości i średnią ilość", "Podziel zmianę ilości przez średnią", "Oblicz zmianę ceny i średnią cenę", "Podziel zmianę ceny przez średnią", "Podziel pierwszy wynik przez drugi"],
             why="To metoda punktu środkowego."),
          W("Q = 1000 · P^(−1,5). O ile procent spadnie ilość po wzroście ceny o 2%?",
            "O ok. 3%", "O 1,5%", "O 2%", "O 6%",
            why="Stała elastyczność 1,5: 1,5 · 2% = 3%."),
          PF("Elastyczność krzyżowa równa zero oznacza dobra niezależne.", True,
             why="Zmiana ceny Y nie wpływa na popyt na X."),
          M("Które obliczenia są poprawne?",
            ["Q 100→90, P 10→11: |E| od wartości początkowych = 1", "Dochód +5%, popyt +10%: Ed = 2", "Cena Y +4%, popyt X +2%: Exy = 2", "Podaż +12% przy cenie +6%: Es = 2"],
            [0, 1, 3],
            why="Exy = 2% / 4% = 0,5, a nie 2."),
      ],
      calc=[
          LB("Cena biletu wzrosła z 40 do 50 zł, sprzedaż spadła z 600 do 450. Oblicz |E| metodą łukową.",
             1.29, "((600-450)/525)/((50-40)/45)", ["%ΔQ = 150 / 525 ≈ 28,57%", "%ΔP = 10 / 45 ≈ 22,22%", "|E| ≈ 1,29"], unit="", tol=0.01),
          LB("Q = 500 − 10P. Ile wynosi |E| przy P = 30?",
             1.5, "10*30/(500-10*30)", ["Q = 200", "|E| = 10 · 30 / 200 = 1,5"], unit=""),
          LB("Dochody wzrosły z 5000 do 5500 zł, a zakup książek z 20 do 23 sztuk rocznie. Ile wynosi Ed (od wartości początkowych)?",
             1.5, "(3/20)/(500/5000)", ["%ΔQ = 15%", "%ΔI = 10%", "Ed = 1,5 – dobro luksusowe"], unit=""),
          LB("Cena masła wzrosła o 25%, a sprzedaż margaryny o 10%. Ile wynosi Exy?",
             0.4, "10/25", ["Exy = 10 / 25 = 0,4 – substytuty"], unit=""),
          LB("Qs = −100 + 20P. Ile wynosi Es przy P = 15?",
             1.5, "20*15/(-100+20*15)", ["Q = 200", "Es = 20 · 15 / 200 = 1,5"], unit=""),
          LB("|E| = 2,5. O ile procent zmieni się utarg po obniżce ceny o 4% (dokładnie: (1 − 0,04)(1 + 0,10) − 1)?",
             5.6, "((1-0.04)*(1+2.5*0.04)-1)*100", ["Ilość +10%", "Utarg: 0,96 · 1,10 = 1,056 – wzrost o 5,6%"], unit="%", tol=0.05),
      ],
      case=[
          PR("Przewoźnik kolejowy analizuje trasę: przy cenie 60 zł sprzedaje 2000 biletów dziennie. Badanie wskazuje |E| = 1,6 (w okolicy obecnej ceny), elastyczność krzyżową względem cen paliwa +0,3 i elastyczność dochodową 0,8.",
             LB("O ile procent wzrośnie sprzedaż biletów, gdy cena spadnie o 5%?",
                8, "1.6*5", ["1,6 · 5% = 8%"], unit="%"),
             LB("O ile procent wzrośnie sprzedaż, gdy paliwo zdrożeje o 20% (cena biletu stała)?",
                6, "0.3*20", ["0,3 · 20% = 6%"], unit="%"),
             W("Czy obniżka ceny biletów zwiększy przychód?",
               "Tak – popyt jest elastyczny", "Nie – popyt jest nieelastyczny", "Przychód się nie zmieni",
               why="|E| = 1,6 > 1 – przy obniżce ilość rośnie procentowo bardziej, niż spada cena."),
          ),
          PR("Analityk szacuje popyt na kawę w sieci kawiarni jako Q = 800 − 40P (Q – filiżanki dziennie, P – cena w zł). Obecna cena: 12 zł.",
             LB("Ile filiżanek dziennie sprzedaje sieć?",
                320, "800-40*12", ["Q = 800 − 480 = 320"], unit="szt."),
             LB("Ile wynosi |E| przy obecnej cenie?",
                1.5, "40*12/(800-40*12)", ["|E| = 40 · 12 / 320 = 1,5"], unit=""),
             LB("Przy jakiej cenie utarg byłby największy?",
                10, "800/(2*40)", ["|E| = 1 w środku: P = 800 / 80 = 10 zł"], unit="zł"),
          ),
      ]),

    L(2, "Warsztat: równowaga, podatki i nadwyżki",
      "Rozwiązywać zadania z równowagi rynkowej z liniowymi funkcjami: wyznaczać równowagę, skutki podatku i dotacji, nadwyżki i stratę martwą.",
      ["Równowaga rynkowa – obliczanie", "Podatek na producentów – nowa równowaga", "Nadwyżka konsumenta i producenta – wzór"],
      [S35, SA],
      explain=[
          K("Równowaga – przyrównaj i rozwiąż",
            "Dla Qd = a − bP i Qs = c + dP przyrównujemy Qd = Qs i rozwiązujemy względem P, potem wstawiamy P do dowolnej funkcji, by dostać Q.",
            w="P* = (a − c) / (b + d);  Q* = a − b·P*"),
          K("Podatek od producenta",
            "Podatek t zł od sztuki płacony przez sprzedawcę: w funkcji podaży zamiast P wstawiamy (P − t), bo sprzedawca zatrzymuje cenę pomniejszoną o podatek. Wynik: cena płacona Pk, cena otrzymywana Pp = Pk − t, wpływy t · Q.",
            w="Qs = c + d(P − t)"),
          W("Qd = 100 − 2P, Qs = −20 + 4P. Ile wynosi P*?",
            "20", "30", "10", "15",
            why="100 − 2P = −20 + 4P ⇒ 120 = 6P ⇒ P = 20."),
          K("Nadwyżki jako trójkąty",
            "Nadwyżka konsumenta = ½ · (cena dławiąca − P*) · Q*, gdzie cena dławiąca to cena przy Qd = 0. Nadwyżka producenta = ½ · (P* − cena minimalna podaży) · Q* (dla liniowej podaży zaczynającej się na osi cen).",
            w="NK = ½ · (Pmax − P*) · Q*;  NP = ½ · (P* − Pmin) · Q*"),
          K("Strata martwa",
            "Podatek, dotacja, cena maksymalna lub minimalna zmieniają ilość. Strata martwa to trójkąt między popytem a podażą od nowej ilości do ilości równowagi.",
            w="SM = ½ · (różnica cen przy nowej ilości) · (Q* − Q₁)"),
          PF("Nie ma znaczenia, czy podatek płaci formalnie kupujący, czy sprzedawca – wynik rynkowy (ceny netto, ilość) jest ten sam.", True,
             why="Rozkład ciężaru zależy od elastyczności, a nie od formalnego podatnika."),
      ],
      mech=[
          LN("Ułóż kroki rozwiązania zadania z podatkiem.",
             ["Zapisz podaż po podatku: zamień P na (P − t)", "Przyrównaj popyt i nową podaż", "Wyznacz cenę płaconą przez kupujących", "Odejmij podatek – cena otrzymywana przez sprzedawców", "Policz ilość, wpływy i stratę martwą"],
             why="Standardowy schemat zadań olimpijskich."),
          KT("Co rośnie, a co maleje po nałożeniu podatku?",
             {"Rośnie": ["Cena płacona przez kupujących", "Wpływy budżetu (z zera)"],
              "Maleje": ["Ilość sprzedana", "Cena otrzymywana przez sprzedawców", "Nadwyżka konsumenta"]},
             why="Podatek tworzy klin między ceną płaconą a otrzymywaną."),
          W("Popyt doskonale nieelastyczny, podatek 5 zł od sztuki. O ile wzrośnie cena dla kupujących?",
            "O 5 zł – całość ponoszą kupujący", "O 0 zł", "O 2,50 zł",
            why="Kupujący nie zmieniają ilości, więc sprzedawcy mogą przerzucić cały podatek."),
          W("Dotacja 3 zł do sztuki dla producentów. Jak zmienia się funkcja podaży?",
            "Producent dostaje cenę powiększoną o dotację: w miejsce P wstawiamy P + 3", "Producent dostaje cenę pomniejszoną: w miejsce P wstawiamy P − 3", "Funkcja podaży się nie zmienia",
            why="Producent otrzymuje cenę rynkową plus dotację."),
          PF("Wpływy z podatku są zawsze równe stracie nadwyżki konsumenta i producenta.", False,
             why="Utrata nadwyżek = wpływy + strata martwa."),
          M("Które stwierdzenia o stracie martwej są prawdziwe?",
            ["Rośnie z wysokością podatku", "Jest większa przy bardziej elastycznych krzywych", "Jest równa wpływom z podatku", "Powstaje też przy wiążącej cenie maksymalnej"],
            [0, 1, 3],
            why="Strata martwa nie trafia do budżetu."),
      ],
      calc=[
          LB("Qd = 100 − 2P, Qs = −20 + 4P. Ile wynosi Q*?",
             60, "100-2*20", ["P* = 20", "Q* = 100 − 40 = 60"], unit="szt."),
          LB("Ile wynosi nadwyżka konsumenta (cena dławiąca: 50 zł)?",
             900, "0.5*(50-20)*60", ["½ · (50 − 20) · 60 = 900"], unit="zł"),
          LB("Ile wynosi nadwyżka producenta (Qs = 0 przy P = 5)?",
             450, "0.5*(20-5)*60", ["½ · (20 − 5) · 60 = 450"], unit="zł"),
          LB("Podatek t = 3 zł od sprzedawcy: Qs = −20 + 4(P − 3). Jaką cenę płacą kupujący?",
             22, "132/6", ["Qs = −32 + 4P", "100 − 2P = −32 + 4P ⇒ 6P = 132 ⇒ P = 22"], unit="zł"),
          LB("Ile wynoszą wpływy z tego podatku (Q = 100 − 2·22)?",
             168, "3*(100-2*22)", ["Q = 56", "Wpływy = 3 · 56 = 168 zł"], unit="zł"),
          LB("Ile wynosi strata martwa (t = 3, Q* = 60, Q₁ = 56)?",
             6, "0.5*3*(60-56)", ["½ · 3 · 4 = 6 zł"], unit="zł"),
      ],
      case=[
          PR("Rynek biletów na koncerty plenerowe: Qd = 12 000 − 100P, Qs = −3000 + 200P (P w zł). Gmina rozważa opłatę 15 zł od każdego biletu płaconą przez organizatorów.",
             LB("Ile wynosi cena równowagi przed opłatą?",
                50, "15000/300", ["12 000 − 100P = −3000 + 200P", "15 000 = 300P ⇒ P = 50 zł"], unit="zł"),
             LB("Jaką cenę zapłacą widzowie po wprowadzeniu opłaty (Qs = −3000 + 200(P − 15))?",
                60, "18000/300", ["Qs = −6000 + 200P", "12 000 − 100P = −6000 + 200P ⇒ 300P = 18 000 ⇒ P = 60 zł"], unit="zł"),
             LB("Ile wyniosą wpływy gminy (Q = 12 000 − 100·60)?",
                90000, "15*(12000-100*60)", ["Q = 6000 biletów", "Wpływy = 15 · 6000 = 90 000 zł"], unit="zł"),
          ),
          PR("W tym samym zadaniu (cena przed opłatą 50 zł, po opłacie widzowie płacą 60 zł, organizatorzy dostają 45 zł; ilość spada z 7000 do 6000 biletów).",
             LB("Jaką część opłaty (w %) ponoszą widzowie?",
                66.67, "(60-50)/15*100", ["Widzowie: 10 zł z 15 zł", "10 / 15 ≈ 66,67%"], unit="%", tol=0.05),
             LB("Ile wynosi strata martwa opłaty?",
                7500, "0.5*15*(7000-6000)", ["½ · 15 · (7000 − 6000) = 7500 zł"], unit="zł"),
             W("Dlaczego widzowie ponoszą większą część opłaty?",
               "Ich popyt jest mniej elastyczny niż podaż organizatorów (nachylenie 100 vs 200)", "Bo formalnie płacą organizatorzy", "Bo opłata jest stała",
               why="Ciężar ponosi w większym stopniu strona mniej elastyczna."),
          ),
      ]),

    L(3, "Warsztat: koszty i maksymalizacja zysku",
      "Liczyć koszty (TC, FC, VC, ATC, AVC, MC), wyznaczać produkcję maksymalizującą zysk, próg rentowności i próg zamknięcia na funkcjach.",
      ["Koszty – zależności", "Zysk ekonomiczny – wzór", "Utarg i jego maksimum", "Warunek maksymalizacji zysku", "Próg rentowności (BEP)"],
      [S73, S82],
      explain=[
          K("Mapa kosztów",
            "Z funkcji TC(Q) odczytujemy wszystko: FC = TC(0), VC = TC − FC, ATC = TC/Q, AVC = VC/Q, AFC = FC/Q, MC = pochodna TC (albo ΔTC/ΔQ).",
            w="TC = FC + VC;  ATC = AFC + AVC;  MC = dTC/dQ"),
          K("Utarg i zysk",
            "TR = P · Q, MR = dTR/dQ. Zysk π = TR − TC. Maksimum zysku: MR = MC (i MC rośnie). W konkurencji doskonałej MR = P.",
            w="π = TR − TC;  max π: MR = MC"),
          W("TC = 50 + 4Q + Q². Ile wynosi MC przy Q = 3?",
            "10", "7", "21", "4",
            why="MC = 4 + 2Q = 4 + 6 = 10."),
          K("Próg rentowności i zamknięcia",
            "BEP w sztukach: FC / (P − AVC) przy stałym AVC. Próg zamknięcia: cena równa minimum AVC – poniżej tej ceny firma w krótkim okresie wstrzymuje produkcję.",
            w="BEP = FC / (P − AVC);  zamknięcie: P < min AVC"),
          K("Minimum ATC i AVC",
            "Krzywa MC przecina AVC i ATC w ich minimach. W zadaniach: przyrównaj MC = ATC (albo MC = AVC) i rozwiąż – dostaniesz ilość minimalizującą koszt przeciętny."),
          PF("Koszt krańcowy zależy od kosztów stałych.", False,
             why="FC nie zmienia się z Q, więc pochodna TC nie zależy od FC."),
      ],
      mech=[
          KT("Którą wielkość opisuje dany wzór?",
             {"Koszt przeciętny (ATC)": ["TC podzielone przez Q", "AFC + AVC"],
              "Koszt krańcowy (MC)": ["ΔTC / ΔQ (zmiana kosztu na dodatkową sztukę)", "ΔVC / ΔQ"],
              "Zysk (π)": ["TR − TC", "(P − ATC) · Q"]},
             why="Warto pamiętać równoważne postaci wzorów."),
          LN("Ułóż kroki zadania „maksymalizacja zysku w konkurencji doskonałej”.",
             ["Zapisz MC z funkcji TC", "Przyrównaj P = MC i wyznacz Q", "Sprawdź, czy P ≥ min AVC", "Oblicz TR i TC przy tym Q", "Zysk = TR − TC"],
             why="Sprawdzenie progu zamknięcia chroni przed błędem przy niskiej cenie."),
          W("Cena 20 zł, ATC przy optymalnym Q = 25 zł, AVC = 17 zł. Co zrobi firma w krótkim okresie?",
            "Produkuje, ponosząc stratę mniejszą niż koszty stałe", "Wstrzymuje produkcję", "Ma zysk",
            why="AVC ≤ P < ATC – cena pokrywa koszty zmienne i część stałych, więc produkcja zmniejsza stratę."),
          W("Monopolista: TR = 100Q − 2Q². Ile wynosi MR?",
            "100 − 4Q", "100 − 2Q", "100", "−4Q",
            why="MR to pochodna TR po Q: 100 − 4Q (MR spada dwa razy szybciej niż cena)."),
          PF("Zysk jest maksymalny, gdy przeciętny koszt całkowity jest minimalny.", False,
             why="Maksimum zysku wyznacza MR = MC, a nie minimum ATC (choć w długim okresie konkurencji doskonałej te punkty się pokrywają)."),
          M("Które stwierdzenia są prawdziwe dla TC = 100 + 10Q?",
            ["FC = 100", "MC = 10 przy każdym Q", "ATC rośnie z Q", "AVC = 10"],
            [0, 1, 3],
            why="ATC = 100/Q + 10 maleje z Q."),
      ],
      calc=[
          LB("TC = 200 + 20Q + Q². Ile wynosi ATC przy Q = 10?",
             50, "(200+20*10+10**2)/10", ["TC = 200 + 200 + 100 = 500", "ATC = 50"], unit="zł"),
          LB("TC = 200 + 20Q + Q², cena 60 zł (konkurencja doskonała). Ile wynosi Q maksymalizujące zysk (MC = 20 + 2Q)?",
             20, "(60-20)/2", ["60 = 20 + 2Q ⇒ Q = 20"], unit="szt."),
          LB("Ile wynosi zysk przy Q = 20 (TC = 200 + 20Q + Q², P = 60)?",
             200, "60*20-(200+20*20+20**2)", ["TR = 1200", "TC = 200 + 400 + 400 = 1000", "π = 200"], unit="zł"),
          LB("Przy jakim Q ATC jest minimalne (TC = 200 + 20Q + Q²; 200/Q + 20 + Q = 20 + 2Q)?",
             14.14, "200**0.5", ["200/Q = Q ⇒ Q = √200 ≈ 14,14"], unit="szt.", tol=0.02),
          LB("Monopolista: P = 100 − 2Q, TC = 20Q + 100. Ile wynosi Q maksymalizujące zysk (MR = 100 − 4Q = 20)?",
             20, "(100-20)/4", ["Q = 80 / 4 = 20"], unit="szt."),
          LB("Ile wynosi zysk tego monopolisty (P = 100 − 2·20, TC = 20·20 + 100)?",
             700, "(100-2*20)*20-(20*20+100)", ["P = 60, TR = 1200", "TC = 500", "π = 700"], unit="zł"),
      ],
      case=[
          PR("Piekarnia rzemieślnicza: koszty stałe 9000 zł miesięcznie, koszt zmienny bochenka 4 zł (stały), cena 10 zł. Sprzedaje 1800 bochenków miesięcznie.",
             LB("Ile wynosi próg rentowności (bochenki)?",
                1500, "9000/(10-4)", ["Marża: 6 zł", "BEP = 9000 / 6 = 1500"], unit="szt."),
             LB("Ile wynosi miesięczny zysk?",
                1800, "1800*(10-4)-9000", ["1800 · 6 = 10 800", "π = 10 800 − 9000 = 1800 zł"], unit="zł"),
             LB("Ile wynosi ATC przy 1800 bochenkach?",
                9, "(9000+4*1800)/1800", ["TC = 9000 + 7200 = 16 200", "ATC = 9 zł"], unit="zł"),
          ),
          PR("Producent ma TC = 64 + Q² (MC = 2Q). Cena rynkowa (konkurencja doskonała) spada z 20 zł do 12 zł.",
             LB("Ile wynosi zysk przy cenie 20 zł (P = MC ⇒ Q = 10)?",
                36, "20*10-(64+10**2)", ["TR = 200, TC = 164", "π = 36"], unit="zł"),
             LB("Ile wynosi wynik przy cenie 12 zł (Q = 6), ze znakiem?",
                -28, "12*6-(64+6**2)", ["TR = 72, TC = 100", "π = −28"], unit="zł"),
             W("Czy przy cenie 12 zł firma powinna produkować w krótkim okresie?",
               "Tak – strata 28 zł jest mniejsza niż koszty stałe 64 zł (AVC = Q = 6 < 12)", "Nie – ma stratę", "Nie da się ocenić",
               why="Cena pokrywa przeciętny koszt zmienny."),
          ),
      ]),

    L(4, "Warsztat: siła rynkowa w liczbach",
      "Liczyć wynik monopolu, wskaźnik Lernera, regułę cenową z elastyczności oraz wskaźniki koncentracji CR i HHI.",
      ["Maksymalizacja zysku – monopol", "Monopol", "Siła rynkowa i wskaźnik Lernera", "Wskaźniki koncentracji rynku (CR, HHI)"],
      [S92, S111],
      explain=[
          K("Monopol w trzech krokach",
            "1) MR z funkcji popytu: dla P = a − bQ mamy MR = a − 2bQ. 2) MR = MC → Q. 3) P z funkcji popytu. Zysk = (P − ATC) · Q.",
            w="P = a − bQ  ⇒  MR = a − 2bQ"),
          K("Wskaźnik Lernera i reguła cenowa",
            "Lerner L = (P − MC)/P mierzy narzut ceny nad kosztem krańcowym (0 – konkurencja, bliżej 1 – duża siła rynkowa). Monopolista maksymalizujący zysk ustala L = 1/|E|.",
            w="L = (P − MC)/P = 1/|E|;  P = MC · |E|/(|E| − 1)"),
          W("|E| = 4, MC = 30 zł. Jaką cenę ustali monopolista?",
            "40 zł", "30 zł", "120 zł", "34 zł",
            why="P = 30 · 4 / 3 = 40 zł."),
          K("Wskaźniki koncentracji",
            "CRn – suma udziałów n największych firm (%). HHI – suma kwadratów udziałów wszystkich firm (od bliskiego 0 do 10 000). Przyrost HHI po fuzji firm o udziałach a i b: 2ab.",
            w="HHI = Σ sᵢ²;  ΔHHI = 2 · sA · sB"),
          K("Strata martwa monopolu",
            "Porównujemy z konkurencją (P = MC). Dla liniowego popytu i stałego MC strata martwa = ½ · (Pm − MC) · (Qk − Qm)."),
          PF("Monopolista maksymalizujący zysk zawsze działa na elastycznym odcinku popytu (|E| > 1).", True,
             why="Przy |E| ≤ 1 MR ≤ 0, a MC > 0 – warunek MR = MC nie może być spełniony."),
      ],
      mech=[
          LN("Ułóż kroki obliczania straty martwej monopolu.",
             ["Wyznacz Qm i Pm z MR = MC", "Wyznacz Qk z warunku P = MC", "Oblicz różnicę Pm − MC", "Oblicz różnicę Qk − Qm", "SM = ½ · (Pm − MC) · (Qk − Qm)"],
             why="Strata martwa to trójkąt między popytem a MC."),
          KT("Duża czy mała siła rynkowa?",
             {"Duża": ["Lerner = 0,6", "HHI = 7000", "|E| popytu na produkt firmy = 1,3"],
              "Mała": ["Lerner = 0,02", "HHI = 400", "|E| popytu na produkt firmy = 40"]},
             why="Wysoki Lerner i HHI oraz niska elastyczność wskazują na siłę rynkową."),
          W("Rynek ma 4 firmy po 25%. Ile wynosi HHI?",
            "2500", "100", "625", "10 000",
            why="4 · 625 = 2500."),
          W("Która fuzja zwiększy HHI bardziej?",
            "Dwóch firm po 20%", "Dwóch firm po 5%", "Obie tak samo",
            why="ΔHHI = 2 · 20 · 20 = 800 vs 2 · 5 · 5 = 50."),
          PF("Wskaźnik CR4 = 80% oznacza, że rynek na pewno jest monopolem.", False,
             why="Cztery firmy mogą konkurować; CR4 nie mówi o podziale między nimi."),
          M("Co prawda dla monopolisty z P = 120 − Q i MC = 0?",
            ["Q = 60", "P = 60", "Lerner = 0", "Utarg jest maksymalny"],
            [0, 1, 3],
            why="Przy MC = 0 Lerner = (60 − 0)/60 = 1."),
      ],
      calc=[
          LB("P = 150 − 3Q, MC = 30. Ile wynosi Qm?",
             20, "(150-30)/6", ["MR = 150 − 6Q = 30 ⇒ Q = 20"], unit="szt."),
          LB("Ile wynosi Pm (P = 150 − 3Q, Q = 20)?",
             90, "150-3*20", ["P = 150 − 60 = 90"], unit="zł"),
          LB("Ile wynosi strata martwa (Qk z P = MC: 150 − 3Q = 30 ⇒ Qk = 40)?",
             600, "0.5*(90-30)*(40-20)", ["½ · 60 · 20 = 600 zł"], unit="zł"),
          LB("Ile wynosi Lerner tego monopolisty ((90 − 30)/90)?",
             0.67, "(90-30)/90", ["60 / 90 ≈ 0,67"], unit="", tol=0.01),
          LB("Udziały: 35, 25, 20, 10, 10. Ile wynosi HHI?",
             2450, "35**2+25**2+20**2+10**2+10**2", ["1225 + 625 + 400 + 100 + 100 = 2450"], unit=""),
          LB("|E| = 3, MC = 40 zł. Jaką cenę ustali firma z siłą rynkową?",
             60, "40*3/2", ["P = 40 · 3 / (3 − 1) = 60 zł"], unit="zł"),
      ],
      case=[
          PR("Jedyny przewoźnik na lokalnej trasie ma popyt P = 80 − 0,5Q (Q – pasażerowie dziennie) i stały koszt krańcowy 20 zł.",
             LB("Ilu pasażerów obsłuży monopolista (MR = 80 − Q = 20)?",
                60, "80-20", ["Q = 60"], unit="os."),
             LB("Jaką cenę ustali?",
                50, "80-0.5*60", ["P = 80 − 30 = 50 zł"], unit="zł"),
             LB("O ilu pasażerów więcej przewiózłby rynek konkurencyjny (P = MC: 80 − 0,5Q = 20)?",
                60, "(80-20)/0.5-60", ["Qk = 120", "Różnica: 60 pasażerów"], unit="os."),
          ),
          PR("Na rynku 6 firm: 30%, 25%, 20%, 10%, 10%, 5%. Firmy z 20% i 10% chcą się połączyć.",
             LB("Ile wynosi HHI przed fuzją?",
                2150, "30**2+25**2+20**2+10**2+10**2+5**2", ["900 + 625 + 400 + 100 + 100 + 25 = 2150"], unit=""),
             LB("Ile wynosi ΔHHI?",
                400, "2*20*10", ["2 · 20 · 10 = 400"], unit=""),
             W("Jak fuzję oceniają progi z wytycznych KE?",
               "HHI po fuzji 2550 i Δ = 400 > 150 – potrzebna dokładniejsza analiza", "Fuzja jest na pewno zakazana", "Fuzja nie wymaga analizy",
               why="Przekroczenie progów nie oznacza zakazu, tylko brak „bezpiecznej przystani”."),
          ),
      ]),

    L(5, "Warsztat: konsument, producent i rynki czynników",
      "Rozwiązywać zadania z równowagi konsumenta (II prawo Gossena, MRS), optimum producenta (MRTS), zatrudnienia (VMPL), renty ekonomicznej i wartości oczekiwanej.",
      ["Równowaga konsumenta (II prawo Gossena)", "Krańcowa stopa substytucji (MRS)", "Linia ograniczenia budżetowego",
       "Produkt przeciętny i krańcowy, optimum czynników – wzory", "Optimum producenta (kombinacja najtańsza)",
       "Renta ekonomiczna i dochód transferowy – obliczanie", "Ryzyko, niepewność i wartość oczekiwana", "Płaca nominalna i realna"],
      [S61, S74, S141],
      explain=[
          K("Konsument",
            "Linia budżetowa: Px·X + Py·Y = I. Optimum: MUx/Px = MUy/Py, czyli MRS = Px/Py. Dla U = X·Y konsument wydaje połowę dochodu na każde dobro: X = I/(2Px), Y = I/(2Py).",
            w="MRS = MUx/MUy = Px/Py"),
          K("Producent",
            "Optimum (najtańsza kombinacja): MPL/w = MPK/r, czyli MRTS = w/r. Zatrudnienie na rynku konkurencyjnym: VMPL = MPL · P = w.",
            w="MPL/w = MPK/r;  VMPL = w"),
          W("U = X·Y, I = 120 zł, Px = 3 zł. Ile X kupi konsument?",
            "20", "40", "60", "10",
            why="X = 120 / (2 · 3) = 20."),
          K("Renta i dochód transferowy",
            "Przy liniowej podaży czynnika renta ekonomiczna to trójkąt nad krzywą podaży i pod ceną czynnika; dochód transferowy – pole pod krzywą podaży."),
          K("Wartość oczekiwana i płaca realna",
            "E(X) = Σ pᵢ · xᵢ. Płaca realna = płaca nominalna / indeks cen; zmiana w %: (1 + g)/(1 + π) − 1 ≈ g − π.",
            w="E = Σ pᵢxᵢ;  realna zmiana = (1+g)/(1+π) − 1"),
          PF("Jeśli MUx/Px > MUy/Py, konsument powinien kupić więcej Y.", False,
             why="Powinien kupić więcej X – złotówka wydana na X daje więcej użyteczności."),
      ],
      mech=[
          KT("Czego dotyczy warunek?",
             {"Konsument": ["MUx/Px = MUy/Py", "MRS = Px/Py"],
              "Producent": ["MPL/w = MPK/r", "MRTS = w/r", "VMPL = w"]},
             why="Analogia: konsument dzieli budżet między dobra, producent – między czynniki."),
          LN("Ułóż rozwiązanie zadania z optimum producenta.",
             ["Oblicz MPL/w i MPK/r", "Porównaj ilorazy", "Przesuń wydatki do czynnika z wyższym ilorazem", "Powtarzaj, aż ilorazy się zrównają", "Sprawdź, czy koszt mieści się w budżecie"],
             why="Ta sama logika co przy podziale budżetu konsumenta."),
          W("MPL = 10, w = 20 zł, MPK = 30, r = 50 zł. Co powinna zrobić firma?",
            "Użyć więcej kapitału (0,6 > 0,5)", "Użyć więcej pracy", "Nic nie zmieniać",
            why="Złotówka w kapitale daje 0,6 jednostki, w pracy 0,5."),
          W("Płace wzrosły o 10%, ceny o 6%. O ile (w przybliżeniu) wzrosła płaca realna?",
            "O ok. 4%", "O 16%", "O 10%",
            why="10% − 6% ≈ 4% (dokładnie 1,10/1,06 − 1 ≈ 3,8%)."),
          PF("Dla U = X·Y udział wydatków na X w budżecie nie zależy od ceny X.", True,
             why="Konsument zawsze wydaje połowę dochodu na każde dobro."),
          M("Które obliczenia są poprawne?",
            ["E(50% · 100 zł, 50% · 0 zł) = 50 zł", "MRS przy MUx = 6, MUy = 2 wynosi 3", "VMPL przy MPL = 5 i P = 10 wynosi 15", "Linia budżetowa: I = 100, Px = 10 ⇒ max X = 10"],
            [0, 1, 3],
            why="VMPL = 5 · 10 = 50."),
      ],
      calc=[
          LB("I = 200 zł, Px = 4 zł, Py = 10 zł, U = X·Y. Ile Y kupi konsument?",
             10, "200/(2*10)", ["Y = 200 / 20 = 10"], unit="szt."),
          LB("Q = L^0,5 · K^0,5, w = 16 zł, r = 4 zł. W optimum K/L = w/r. Ile kapitału przypada na jednostkę pracy?",
             4, "16/4", ["MRTS = K/L = w/r = 4"], unit=""),
          LB("MPL = 40 − 2L, cena produktu 5 zł, płaca 100 zł. Ilu pracowników zatrudni firma (VMPL = w)?",
             10, "(40-100/5)/2", ["5(40 − 2L) = 100", "40 − 2L = 20 ⇒ L = 10"], unit="os."),
          LB("Podaż czynnika: w = 10 + 2L, cena czynnika 50 zł. Ile wynosi renta ekonomiczna (L = 20)?",
             400, "0.5*(50-10)*20", ["L = (50 − 10) / 2 = 20", "Renta = ½ · 40 · 20 = 400"], unit="zł"),
          LB("Projekt: 30% szans na +500 tys. zł, 70% szans na −100 tys. zł. Ile wynosi wartość oczekiwana (tys. zł)?",
             80, "0.3*500-0.7*100", ["150 − 70 = 80 tys. zł"], unit="tys. zł"),
          LB("Płace +9%, inflacja +4%. O ile procent dokładnie wzrosła płaca realna?",
             4.81, "(1.09/1.04-1)*100", ["1,09 / 1,04 − 1 ≈ 4,81%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Studentka ma 600 zł miesięcznie na książki (40 zł) i kino (20 zł). Jej preferencje opisuje U = X·Y (X – książki, Y – bilety).",
             LB("Ile książek kupi?",
                7.5, "600/(2*40)", ["X = 600 / 80 = 7,5 (średnio miesięcznie)"], unit="szt."),
             LB("Ile biletów kupi?",
                15, "600/(2*20)", ["Y = 600 / 40 = 15"], unit="szt."),
             LB("Kino drożeje do 30 zł. Ile biletów kupi teraz?",
                10, "600/(2*30)", ["Y = 600 / 60 = 10"], unit="szt."),
          ),
          PR("Warsztat zatrudnia mechaników. Produkt krańcowy kolejnych mechaników (naprawy dziennie): 6, 5, 4, 3, 2. Cena naprawy: 150 zł. Dzienny koszt mechanika: 500 zł.",
             LB("Ile wynosi VMPL trzeciego mechanika?",
                600, "4*150", ["4 · 150 = 600 zł"], unit="zł"),
             LB("Ilu mechaników zatrudni warsztat?",
                3, "sum(1 for m in [6,5,4,3,2] if m*150 >= 500)", ["VMPL: 900, 750, 600, 450, 300", "VMPL ≥ 500 dla trzech pierwszych"], unit="os."),
             LB("Cena naprawy rośnie do 200 zł. Ilu mechaników zatrudni teraz warsztat?",
                4, "sum(1 for m in [6,5,4,3,2] if m*200 >= 500)", ["VMPL: 1200, 1000, 800, 600, 400", "Czterech spełnia warunek"], unit="os."),
          ),
      ]),
]
