# -*- coding: utf-8 -*-
# Zrozumienie – Polityka gospodarcza / Polityka społeczna, dochodowa i rynku pracy
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S43 = S("OpenStax, Principles of Economics 3e, 3.4 Price Ceilings and Price Floors", OS3 + "3-4-price-ceilings-and-price-floors", D)
S144 = S("OpenStax, Principles of Economics 3e, 14.2 Wages and Employment in an Imperfectly Competitive Labor Market", OS3 + "14-2-wages-and-employment-in-an-imperfectly-competitive-labor-market", D)
S143 = S("OpenStax, Principles of Economics 3e, 14.3 Market Power on the Supply Side of Labor Markets: Unions", OS3 + "14-3-market-power-on-the-supply-side-of-labor-markets-unions", D)
S152 = S("OpenStax, Principles of Economics 3e, 15.2 The Poverty Trap", OS3 + "15-2-the-poverty-trap", D)
S153 = S("OpenStax, Principles of Economics 3e, 15.3 The Safety Net", OS3 + "15-3-the-safety-net", D)
S155 = S("OpenStax, Principles of Economics 3e, 15.5 Government Policies to Reduce Income Inequality", OS3 + "15-5-government-policies-to-reduce-income-inequality", D)
S214 = S("OpenStax, Principles of Economics 3e, 21.4 What Causes Changes in Unemployment over the Long Run", OS3 + "21-4-what-causes-changes-in-unemployment-over-the-long-run", D)
DZU = S("Dz.U. 2025 poz. 1242 – rozporządzenie w sprawie minimalnego wynagrodzenia na 2026 r.", "https://dziennikustaw.gov.pl/D2025000124201.pdf", D)
ZL = S("gov.pl – Zielona Linia: wynagrodzenie minimalne w 2026 r.", "https://zielonalinia.gov.pl/wynagrodzenie-minimalne-w-2026-1/", D)
URE = S("URE – taryfy na 2026 r. (ceny energii dla gospodarstw domowych)", "https://www.ure.gov.pl/pl/urzad/informacje-ogolne/aktualnosci/13002,Prezes-Urzedu-Regulacji-Energetyki-zatwierdzil-taryfy-na-sprzedaz-i-dystrybucje-.html", D)
RDS = S("Rada Dialogu Społecznego – informacje o Radzie (gov.pl)", "https://www.gov.pl/web/rds", D)

LESSONS = [
    L(1, "Polityka rynku pracy: aktywna, pasywna i flexicurity",
      "Rozróżniać aktywną i pasywną politykę rynku pracy, rozumieć model flexicurity oraz dobierać instrumenty do rodzaju bezrobocia.",
      ["Aktywna i pasywna polityka rynku pracy", "Flexicurity (model duński)", "Układy zbiorowe pracy i regulacje rynku pracy"],
      [S214, S153],
      explain=[
          K("Pasywna polityka rynku pracy",
            "Łagodzi skutki bezrobocia: zasiłki dla bezrobotnych, świadczenia przedemerytalne. Chroni dochody, ale zbyt hojne i długie świadczenia mogą osłabiać bodźce do szukania pracy."),
          K("Aktywna polityka rynku pracy",
            "Zwiększa szanse na zatrudnienie: pośrednictwo i doradztwo zawodowe, szkolenia i przekwalifikowanie, staże, dotacje na założenie firmy, subsydiowane zatrudnienie, prace interwencyjne. Najlepiej działa na bezrobocie strukturalne i frykcyjne."),
          W("Który instrument należy do aktywnej polityki rynku pracy?",
            "Szkolenie zawodowe dla bezrobotnego", "Zasiłek dla bezrobotnych", "Świadczenie przedemerytalne",
            why="Aktywna polityka zwiększa zatrudnialność."),
          K("Flexicurity (Dania)",
            "„Złoty trójkąt”: (1) elastyczny rynek pracy – łatwe zatrudnianie i zwalnianie; (2) hojne, ale warunkowe zasiłki; (3) silna aktywna polityka rynku pracy. Zatrudnienie jest mało chronione, ale chronione są dochody i szanse na nową pracę („chronić pracownika, nie miejsce pracy”)."),
          K("Regulacje",
            "Kodeks pracy, płaca minimalna, ochrona przed zwolnieniem, układy zbiorowe pracy (porozumienia związków z pracodawcami) wpływają na elastyczność rynku. Zbyt sztywne regulacje utrudniają tworzenie miejsc pracy, zbyt słabe – zwiększają niepewność pracowników."),
          PF("W modelu flexicurity silna ochrona przed zwolnieniem jest głównym filarem.", False,
             why="Filarami są elastyczność zatrudnienia, zabezpieczenie dochodów i aktywna polityka."),
      ],
      mech=[
          KT("Polityka aktywna czy pasywna?",
             {"Aktywna": ["Dotacja na rozpoczęcie działalności", "Staż u pracodawcy", "Bon szkoleniowy"],
              "Pasywna": ["Zasiłek dla bezrobotnych", "Świadczenie przedemerytalne"]},
             why="Aktywna – powrót do pracy; pasywna – zastąpienie dochodu."),
          LN("Ułóż działanie flexicurity po zwolnieniu.",
             ["Firma szybko zwalnia pracownika przy spadku zamówień", "Pracownik dostaje wysoki zasiłek", "Musi uczestniczyć w szkoleniach i szukać pracy", "Szybko znajduje nowe zatrudnienie", "Bezrobocie długotrwałe pozostaje niskie"],
             why="Elastyczność + bezpieczeństwo dochodu + aktywizacja."),
          W("Na jakie bezrobocie najlepiej działa przekwalifikowanie?",
            "Strukturalne", "Cykliczne", "Sezonowe",
            why="Usuwa niedopasowanie kwalifikacji."),
          PF("Zbyt hojne i bezterminowe zasiłki mogą wydłużać okres bezrobocia.", True,
             why="Zmniejszają koszt alternatywny pozostawania bez pracy."),
          M("Co należy do „złotego trójkąta” flexicurity?",
            ["Elastyczne zasady zatrudniania i zwalniania", "Wysokie, warunkowe zasiłki", "Dożywotnia gwarancja jednego miejsca pracy", "Silna aktywna polityka rynku pracy"],
            [0, 1, 3],
            why="Model chroni pracownika, a nie konkretne miejsce pracy."),
          W("Dlaczego aktywizacja jest zwykle połączona z warunkami (np. obowiązek udziału w szkoleniach)?",
            "By zasiłek nie zniechęcał do szukania pracy", "By ukarać bezrobotnych", "Bo szkolenia są zbędne",
            why="Łączy bezpieczeństwo dochodu z bodźcem do powrotu na rynek."),
      ],
      calc=[
          LB("Wskaźnik zastąpienia: zasiłek 1800 zł, poprzednie wynagrodzenie netto 4500 zł. Ile wynosi (%)?",
             40, "1800/4500*100", ["1800 / 4500 = 40% (dane umowne)"], unit="%"),
          LB("Program szkoleń kosztuje 6000 zł na osobę, a uczestnik znajduje pracę 4 miesiące wcześniej, oszczędzając 1800 zł zasiłku miesięcznie. Ile wynosi oszczędność na zasiłkach (zł)?",
             7200, "1800*4", ["1800 · 4 = 7200 zł"], unit="zł"),
          LB("Ile wynosi korzyść netto dla budżetu na uczestnika (bez podatków od nowej pracy, zł)?",
             1200, "7200-6000", ["7200 − 6000 = 1200 zł"], unit="zł"),
          LB("Szkolenie dostało 200 osób, 90 znalazło pracę w ciągu pół roku; w grupie porównawczej (bez szkolenia) – 60 na 200. O ile p.p. szkolenie zwiększyło szansę zatrudnienia?",
             15, "(90-60)/200*100", ["45% − 30% = 15 p.p."], unit="p.p."),
          LB("Zasób bezrobotnych 900 tys., miesięcznie 10% znajduje pracę. Ile osób (tys.) wychodzi z bezrobocia w miesiącu?",
             90, "0.1*900", ["0,1 · 900 = 90 tys."], unit="tys."),
          LB("Ile miesięcy trwa średnio bezrobocie, jeśli co miesiąc pracę znajduje 10% bezrobotnych?",
             10, "1/0.1", ["Średni czas = 1 / 0,1 = 10 miesięcy"], unit="mies."),
      ],
      case=[
          PR("W Danii pracodawcy mogą stosunkowo łatwo zwalniać pracowników, a mimo to Duńczycy deklarują wysokie poczucie bezpieczeństwa zatrudnienia. Zasiłki są wysokie, ale wymagają aktywnego udziału w programach, a wydatki na aktywną politykę rynku pracy należą do najwyższych w UE.",
             W("Skąd poczucie bezpieczeństwa mimo łatwych zwolnień?",
               "Z ochrony dochodu i szybkiego znajdowania nowej pracy dzięki aktywizacji", "Z zakazu zwolnień", "Z niskich podatków",
               why="To istota flexicurity."),
             W("Jaki warunek musi być spełniony, by model działał?",
               "Wysokie wydatki publiczne i sprawne urzędy pracy", "Brak podatków", "Brak związków zawodowych",
               why="Model jest kosztowny i wymaga skutecznych instytucji."),
             PF("Przeniesienie modelu do innego kraju wymaga także odpowiednich instytucji i zaufania społecznego.", True,
                why="Flexicurity opiera się na współpracy partnerów społecznych."),
          ),
          PR("Powiatowy urząd pracy ma ograniczony budżet. Wśród bezrobotnych dominują osoby powyżej 50. roku życia z przestarzałymi kwalifikacjami oraz młodzi bez doświadczenia. Lokalne firmy zgłaszają brak spawaczy i operatorów maszyn CNC.",
             M("Które instrumenty wybrać?",
               ["Kursy spawania i obsługi maszyn CNC", "Staże dla młodych u lokalnych pracodawców", "Wydłużenie okresu pobierania zasiłku", "Subsydiowane zatrudnienie dla osób 50+"],
               [0, 1, 3],
               why="Wydłużenie zasiłku to instrument pasywny, nie zmniejsza niedopasowania."),
             W("Jaki rodzaj bezrobocia dominuje w powiecie?",
               "Strukturalne (niedopasowanie kwalifikacji)", "Cykliczne", "Sezonowe",
               why="Są wolne miejsca, ale bezrobotni nie mają wymaganych umiejętności."),
             PF("Badanie skuteczności programów z grupą porównawczą pozwala lepiej wydawać środki.", True,
                why="Pokazuje rzeczywisty efekt programu."),
          ),
      ]),

    L(2, "Płaca minimalna i klin podatkowy",
      "Rozumieć skutki płacy minimalnej w modelu konkurencyjnym i przy monopsonie, znać jej poziom w Polsce oraz liczyć klin podatkowy na pracy.",
      ["Płaca minimalna", "Klin podatkowy"],
      [S43, S144, DZU, ZL],
      explain=[
          K("Płaca minimalna w modelu konkurencyjnym",
            "Płaca minimalna to cena minimalna na rynku pracy. Jeśli jest ustalona powyżej płacy równowagi, podaż pracy przewyższa popyt – część osób (zwłaszcza o niskich kwalifikacjach) może nie znaleźć pracy lub przejść do szarej strefy.",
            g=G("praca")),
          K("Monopson i badania empiryczne",
            "Gdy pracodawca ma siłę rynkową (monopson, np. jedyny duży zakład w miasteczku), płaci mniej niż w konkurencji i zatrudnia mniej. Umiarkowana płaca minimalna może wtedy zwiększyć i płace, i zatrudnienie. Badania (np. Card i Krueger, 1994) pokazały, że umiarkowane podwyżki często nie zmniejszają zatrudnienia znacząco; skutki zależą od relacji płacy minimalnej do przeciętnej."),
          W("Kiedy podwyżka płacy minimalnej może zwiększyć zatrudnienie?",
            "Gdy pracodawca ma pozycję monopsonu", "Zawsze", "Nigdy",
            why="Płaca minimalna ogranicza siłę monopsonisty."),
          K("Płaca minimalna w Polsce",
            "Ustala ją rząd (rozporządzenie) po negocjacjach w Radzie Dialogu Społecznego. W 2026 r. minimalne wynagrodzenie wynosi 4806 zł brutto miesięcznie, a minimalna stawka godzinowa – 31,40 zł (w 2025 r.: 4666 zł i 30,50 zł)."),
          K("Klin podatkowy",
            "Różnica między całkowitym kosztem pracy dla pracodawcy a wynagrodzeniem netto pracownika, wyrażona jako % kosztu pracy. Obejmuje podatek dochodowy i składki pracownika oraz pracodawcy. Wysoki klin osłabia popyt na pracę i zachęca do szarej strefy, zwłaszcza przy niskich płacach.",
            w="klin = (koszt pracy − netto) / koszt pracy"),
          PF("Płaca minimalna w Polsce w 2026 r. wynosi 4806 zł brutto.", True,
             why="Rozporządzenie Dz.U. 2025 poz. 1242."),
      ],
      mech=[
          WY("Płaca minimalna zostaje ustalona wyraźnie powyżej płacy równowagi na konkurencyjnym rynku. Co pokazuje model?",
             G("praca", SL=1), "Nadwyżka podaży pracy – bezrobocie wśród mniej wykwalifikowanych", "Niedobór pracowników", "Brak zmian", "Wzrost popytu na pracę",
             why="Cena minimalna powyżej równowagi tworzy nadwyżkę podaży."),
          LN("Ułóż wpływ wysokiego klina podatkowego.",
             ["Rosną składki i podatki od pracy", "Rośnie koszt zatrudnienia dla firmy", "Firmy zatrudniają mniej lub proponują umowy poza etatem", "Część pracy przechodzi do szarej strefy", "Spadają wpływy ze składek i zatrudnienie legalne"],
             why="Klin działa jak podatek na rynku pracy."),
          KT("Zwiększa czy zmniejsza klin podatkowy?",
             {"Zwiększa": ["Wzrost składki rentowej pracodawcy", "Wyższa stawka PIT"],
              "Zmniejsza": ["Wyższa kwota wolna od podatku", "Ulga w składkach dla niskich płac", "Niższa składka zdrowotna"]},
             why="Klin obejmuje podatki i składki obu stron."),
          PF("Wysoka relacja płacy minimalnej do przeciętnej zwiększa ryzyko negatywnych skutków dla zatrudnienia.", True,
             why="Coraz więcej pracowników ma produktywność poniżej minimum."),
          M("Jakie są argumenty za płacą minimalną?",
            ["Ograniczenie ubóstwa pracujących", "Ograniczenie siły monopsonu", "Pewny wzrost zatrudnienia w każdej sytuacji", "Zachęta do legalnej pracy przy niskich kwalifikacjach"],
            [0, 1, 3],
            why="Wpływ na zatrudnienie bywa ujemny – nie jest pewnie dodatni."),
          W("Kto w Polsce ostatecznie ustala płacę minimalną, gdy partnerzy społeczni się nie porozumieją?",
            "Rada Ministrów w rozporządzeniu", "NBP", "Sąd Najwyższy",
            why="Najpierw negocjacje w RDS, potem decyzja rządu."),
      ],
      calc=[
          LB("Płaca minimalna wzrosła z 4666 zł (2025) do 4806 zł (2026). O ile procent?",
             3, "(4806/4666-1)*100", ["4806 / 4666 − 1 ≈ 3,0%"], unit="%", tol=0.03),
          LB("Inflacja średnioroczna 2025 r. wyniosła 3,6%. Czy płaca minimalna realnie wzrosła? Podaj realną zmianę (%) w przybliżeniu.",
             -0.6, "3.0-3.6", ["≈ 3,0 − 3,6 = −0,6% (porównanie przybliżone – inflacja z roku poprzedniego)"], unit="%", tol=0.1),
          LB("Ile wynosi stawka godzinowa przy 4806 zł i 153 godzinach pracy w miesiącu (zł)?",
             31.41, "4806/153", ["4806 / 153 ≈ 31,41 zł (oficjalnie 31,40 zł)"], unit="zł", tol=0.02),
          LB("Koszt pracy dla pracodawcy 5800 zł, pracownik dostaje netto 3600 zł. Ile wynosi klin podatkowy (%)?",
             37.93, "(5800-3600)/5800*100", ["2200 / 5800 ≈ 37,9% (dane umowne)"], unit="%", tol=0.02),
          LB("Rynek pracy: popyt L = 100 − 2w, podaż L = 3w − 20 (w – zł/godz.). Ile wynosi płaca równowagi?",
             24, "120/5", ["100 − 2w = 3w − 20", "w = 24"], unit="zł/godz."),
          LB("Płaca minimalna 28 zł/godz. Ile wynosi nadwyżka podaży pracy (tys. osób)?",
             20, "(3*28-20)-(100-2*28)", ["Podaż: 64, popyt: 44", "Nadwyżka: 20"], unit="tys."),
      ],
      case=[
          PR("Card i Krueger porównali w 1992 r. restauracje szybkiej obsługi w New Jersey, gdzie podniesiono płacę minimalną, i w sąsiedniej Pensylwanii, gdzie jej nie zmieniono. Nie stwierdzili spadku zatrudnienia w New Jersey.",
             W("Jaką metodę badawczą zastosowano?",
               "Porównanie z grupą kontrolną (eksperyment naturalny)", "Ankietę wśród konsumentów", "Model teoretyczny bez danych",
               why="Sąsiedni stan pełnił rolę grupy porównawczej."),
             W("Jak można wyjaśnić brak spadku zatrudnienia?",
               "Siła monopsonu pracodawców lub umiarkowana skala podwyżki", "Bo płaca minimalna była poniżej zera", "Bo firmy zbankrutowały",
               why="W modelu monopsonu płaca minimalna może nie zmniejszać zatrudnienia."),
             PF("David Card otrzymał w 2021 r. Nagrodę Nobla m.in. za empiryczne badania rynku pracy.", True,
                why="Nagroda za wkład do empirycznej ekonomii pracy."),
          ),
          PR("Rząd rozważa podniesienie płacy minimalnej tak, by wynosiła 60% przeciętnego wynagrodzenia. Pracodawcy z małych miejscowości obawiają się, że w ich regionie płaca minimalna będzie bliska lokalnej przeciętnej.",
             W("Dlaczego skutki tej samej płacy minimalnej różnią się między regionami?",
               "W regionach o niskich płacach relacja minimum do lokalnej przeciętnej jest wyższa", "Bo w regionach obowiązują różne waluty", "Nie różnią się",
               why="„Ugryzienie” płacy minimalnej (bite) zależy od lokalnych płac."),
             M("Jak firmy mogą zareagować na wysoką płacę minimalną?",
               ["Podnieść ceny", "Ograniczyć zatrudnienie lub godziny", "Zwiększyć zatrudnienie w każdej sytuacji", "Zautomatyzować część pracy"],
               [0, 1, 3],
               why="Zwiększenie zatrudnienia możliwe głównie przy monopsonie."),
             PF("Obniżenie klina podatkowego dla niskich płac może wspierać zatrudnienie przy rosnącej płacy minimalnej.", True,
                why="Zmniejsza koszt pracy dla pracodawcy przy tym samym netto."),
          ),
      ]),

    L(3, "Polityka dochodowa, społeczna i cenowa",
      "Rozumieć narzędzia polityki dochodowej i społecznej (podatki, transfery, pułapka ubóstwa), politykę cenową państwa i skutki cen administrowanych.",
      ["Polityka dochodowa i społeczna", "Polityka cenowa państwa i ceny administrowane"],
      [S152, S155, S43, URE],
      explain=[
          K("Polityka dochodowa i społeczna",
            "Polityka dochodowa wpływa na podział dochodów: progresywne podatki, transfery (zasiłki, świadczenia rodzinne), płaca minimalna. Polityka społeczna szerzej – zabezpieczenie społeczne (emerytury, renty), ochrona zdrowia, pomoc społeczna, przeciwdziałanie wykluczeniu."),
          K("Pułapka ubóstwa",
            "Gdy świadczenia są odbierane w miarę wzrostu dochodu, efektywna krańcowa stawka „podatku” może być bardzo wysoka – dodatkowa praca prawie nie zwiększa dochodu. Rozwiązania: stopniowe wygaszanie świadczeń („złotówka za złotówkę”), ulgi dla pracujących."),
          W("Na czym polega pułapka ubóstwa?",
            "Utrata świadczeń przy wzroście zarobków sprawia, że praca niewiele się opłaca", "Na zbyt niskich podatkach dla bogatych", "Na wysokiej inflacji",
            why="Wysoka efektywna krańcowa stawka zniechęca do pracy."),
          K("Polityka cenowa i ceny administrowane",
            "Państwo może ustalać ceny maksymalne (np. energia dla gospodarstw w czasie kryzysu), minimalne (skup interwencyjny w rolnictwie) lub zatwierdzać taryfy (energia, ciepło – Prezes URE). Ceny administrowane chronią odbiorców i stabilizują rynek, ale mogą tworzyć niedobory, koszty dla budżetu (rekompensaty) i zniekształcać bodźce do oszczędzania."),
          K("Przykład: ceny prądu",
            "W 2025 r. cena energii dla gospodarstw domowych była zamrożona na poziomie 500 zł/MWh netto (wcześniej obowiązywały inne odmiany mrożenia cen), a sprzedawcy otrzymywali rekompensaty z Funduszu Wypłaty Różnicy Ceny. Od 2026 r. obowiązują taryfy zatwierdzone przez URE ze średnią ceną energii 495,16 zł/MWh."),
          PF("Cena maksymalna ustalona poniżej ceny równowagi może prowadzić do niedoborów.", True,
             why="Popyt przewyższa podaż przy zbyt niskiej cenie."),
      ],
      mech=[
          LN("Ułóż skutki ceny maksymalnej na energię z rekompensatami.",
             ["Państwo ustala cenę maksymalną dla gospodarstw", "Odbiorcy płacą mniej niż koszt rynkowy", "Sprzedawcy dostają rekompensaty z budżetu", "Rosną wydatki publiczne", "Słabną bodźce do oszczędzania energii"],
             why="Ochrona odbiorców ma koszt fiskalny i efektywnościowy."),
          KT("Instrument polityki dochodowej czy cenowej?",
             {"Dochodowej": ["Progresywny PIT", "Zasiłek rodzinny", "Dodatek osłonowy dla ubogich"],
              "Cenowej": ["Cena maksymalna energii", "Taryfa zatwierdzana przez URE", "Skup interwencyjny zboża"]},
             why="Dochodowa zmienia dochody, cenowa – ceny."),
          W("Co jest zwykle bardziej celowanym wsparciem ubogich niż zamrożenie cen dla wszystkich?",
            "Dodatek pieniężny dla gospodarstw o niskich dochodach", "Zamrożenie cen dla wszystkich", "Obniżka podatku od zysków firm",
            why="Zamrożenie cen wspiera też zamożnych i osłabia bodźce do oszczędzania."),
          PF("Taryfy na energię dla gospodarstw domowych w Polsce zatwierdza Prezes URE.", True,
             why="Urząd Regulacji Energetyki."),
          M("Jakie są koszty cen administrowanych poniżej rynku?",
            ["Wydatki budżetu na rekompensaty", "Słabsze bodźce do oszczędzania", "Zawsze niższa inflacja w długim okresie", "Ryzyko niedoborów"],
            [0, 1, 3],
            why="Po wycofaniu mrożenia ceny często skokowo rosną."),
          W("Jak ograniczyć pułapkę ubóstwa?",
            "Stopniowo zmniejszać świadczenia przy wzroście dochodu", "Odbierać całe świadczenie po zarobieniu 1 zł więcej", "Podnieść podatki najuboższym",
            why="Łagodne wygaszanie zmniejsza efektywną krańcową stawkę."),
      ],
      calc=[
          LB("Gospodarstwo zużywa 1,8 MWh rocznie. Cena rynkowa energii 620 zł/MWh, cena zamrożona 500 zł/MWh. Ile wynosi rekompensata dla sprzedawcy (zł rocznie, netto)?",
             216, "1.8*(620-500)", ["1,8 · 120 = 216 zł (cena rynkowa – dane umowne)"], unit="zł"),
          LB("Przy 15 mln odbiorców ile kosztuje to budżet (mld zł)?",
             3.24, "216*15000000/1e9", ["216 · 15 mln ≈ 3,24 mld zł"], unit="mld zł", tol=0.02),
          LB("Pułapka ubóstwa: osoba zarabia dodatkowo 500 zł, ale traci 350 zł świadczenia i płaci 60 zł podatku. Ile wynosi efektywna krańcowa stawka (%)?",
             82, "(350+60)/500*100", ["(350 + 60) / 500 = 82%"], unit="%"),
          LB("Ile netto zostaje z dodatkowych 500 zł (zł)?",
             90, "500-350-60", ["500 − 350 − 60 = 90 zł"], unit="zł"),
          LB("Świadczenie wygasza się stopniowo: 30 gr za każdą dodatkową złotówkę. Ile wynosi utrata świadczenia przy dodatkowych 500 zł (zł)?",
             150, "0.3*500", ["0,3 · 500 = 150 zł"], unit="zł"),
          LB("Średnia cena energii w taryfach 2026 r. 495,16 zł/MWh wobec 572,64 zł/MWh w taryfie z IV kw. 2025 r. O ile procent spadła?",
             -13.53, "(495.16/572.64-1)*100", ["495,16 / 572,64 − 1 ≈ −13,5%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Od 1 stycznia 2026 r. gospodarstwa domowe płacą za energię według taryf zatwierdzonych przez Prezesa URE (średnio 495,16 zł/MWh, ok. 14% mniej niż w taryfach z IV kw. 2025 r.). Wcześniej cenę zamrażano na poziomie 500 zł/MWh, a różnicę pokrywał budżet.",
             W("Dlaczego zakończenie mrożenia nie spowodowało skoku cen?",
               "Taryfy URE na 2026 r. były już niższe od ceny zamrożonej", "Bo URE zakazał podwyżek na zawsze", "Bo energia stała się darmowa",
               why="Spadek kosztów hurtowych umożliwił niższe taryfy."),
             W("Kto ponosił koszt mrożenia cen?",
               "Budżet (podatnicy) przez rekompensaty dla sprzedawców", "Wyłącznie sprzedawcy energii", "Nikt",
               why="Rekompensaty wypłacał fundusz zasilany środkami publicznymi."),
             PF("Mrożenie cen dla wszystkich gospodarstw jest mniej celowane niż wsparcie dla najuboższych.", True,
                why="Korzystają z niego także zamożni."),
          ),
          PR("Samotna matka pracuje na pół etatu i otrzymuje świadczenia zależne od dochodu. Gdyby przeszła na pełny etat, straciłaby większość świadczeń, a jej dochód rozporządzalny wzrósłby tylko o kilkadziesiąt złotych miesięcznie.",
             W("Jakie zjawisko opisuje ten przypadek?",
               "Pułapkę ubóstwa (bezczynności)", "Krzywą Laffera dla firm", "Efekt wypychania",
               why="Praca prawie się nie opłaca przy utracie świadczeń."),
             W("Jakie rozwiązanie mogłoby pomóc?",
               "Stopniowe wygaszanie świadczeń i ulga dla pracujących", "Natychmiastowa utrata świadczeń", "Zakaz pracy na pełny etat",
               why="Zmniejsza efektywną krańcową stawkę."),
             PF("Zasada „złotówka za złotówkę” jest przykładem łagodniejszego wygaszania świadczeń.", True,
                why="Świadczenie maleje o kwotę przekroczenia progu, a nie znika w całości."),
          ),
      ]),

    L(4, "Polityka rodzinna, mieszkaniowa i wykluczenie społeczne",
      "Rozumieć cele i instrumenty polityki rodzinnej i mieszkaniowej, ich skutki ekonomiczne (dochody, podaż pracy, ceny mieszkań) oraz pojęcie wykluczenia społecznego.",
      ["Polityka rodzinna i mieszkaniowa; wykluczenie społeczne", "Polityka dochodowa i społeczna"],
      [S153, S155, S("Infor – Pieniądze na dziecko w 2026 r.: 800 plus i inne świadczenia", "https://www.infor.pl/twoje-pieniadze/swiadczenia/7527629,pieniadze-na-dziecko-w-2026-roku-kompletna-lista-swiadczen-800-plus-aktywny-rodzic-i-dobry-start-zobacz-o-jakie-dodatki-mozesz-wnioskowac.html", D)],
      explain=[
          K("Polityka rodzinna – cele",
            "Wsparcie dochodów rodzin z dziećmi, ograniczanie ubóstwa dzieci, ułatwianie godzenia pracy z rodzicielstwem i – często – zachęcanie do posiadania dzieci. Instrumenty: świadczenia pieniężne, ulgi podatkowe, urlopy rodzicielskie, żłobki i przedszkola."),
          K("Świadczenia pieniężne a usługi",
            "W Polsce od 1 stycznia 2024 r. świadczenie wychowawcze wynosi 800 zł miesięcznie na każde dziecko do 18. roku życia, bez kryterium dochodowego (w 2026 r. bez waloryzacji). Transfery pieniężne silnie ograniczają ubóstwo dzieci, ale ich wpływ na dzietność bywa niewielki; dostęp do opieki nad dziećmi wspiera też aktywność zawodową matek."),
          W("Jaki instrument polityki rodzinnej najbardziej wspiera pracę zawodową rodziców?",
            "Dostępne żłobki i przedszkola", "Wyłącznie zasiłki pieniężne", "Podwyżka VAT",
            why="Usługi opieki pozwalają godzić pracę z rodzicielstwem."),
          K("Polityka mieszkaniowa",
            "Instrumenty po stronie popytu (dopłaty do kredytów, ulgi) i podaży (budownictwo społeczne i komunalne, uwalnianie gruntów, plany zagospodarowania). Wsparcie popytu przy sztywnej podaży głównie podnosi ceny mieszkań; trwała poprawa dostępności wymaga zwiększenia podaży."),
          K("Wykluczenie społeczne",
            "Brak możliwości pełnego uczestnictwa w życiu społecznym i gospodarczym – nie tylko z powodu niskich dochodów, ale też braku pracy, edukacji, mieszkania, dostępu do usług czy niepełnosprawności. Polityka społeczna łączy wsparcie dochodowe z aktywizacją i usługami."),
          PF("Dopłaty do kredytów mieszkaniowych przy ograniczonej podaży mogą podnosić ceny mieszkań.", True,
             why="Popyt rośnie szybciej niż liczba dostępnych mieszkań."),
      ],
      mech=[
          WY("Rząd wprowadza dopłaty do kredytów hipotecznych, a liczba nowych mieszkań w krótkim okresie się nie zmienia. Co się dzieje na rynku mieszkań?",
             G("sd", D=1), "Popyt rośnie – ceny rosną, liczba transakcji niewiele się zmienia", "Podaż rośnie – ceny spadają", "Popyt spada", "Nic",
             why="Przy sztywnej podaży wzrost popytu przekłada się głównie na ceny."),
          KT("Instrument po stronie popytu czy podaży mieszkań?",
             {"Popytu": ["Dopłaty do rat kredytu", "Ulga podatkowa dla kupujących"],
              "Podaży": ["Budownictwo społeczne na wynajem", "Uchwalanie planów miejscowych", "Uwalnianie gruntów publicznych pod zabudowę"]},
             why="Trwała dostępność wymaga zwiększenia podaży."),
          LN("Ułóż możliwy wpływ powszechnego świadczenia na rynek pracy.",
             ["Rodzina otrzymuje stałe świadczenie niezależne od dochodu", "Rośnie dochód niezarobkowy", "Część rodziców ogranicza podaż pracy (efekt dochodowy)", "Ubóstwo dzieci spada", "Efekt na aktywność zależy od dostępności opieki i płac"],
             why="Świadczenie zmienia dochód, a więc i decyzje o pracy."),
          PF("Świadczenie 800+ w Polsce przysługuje bez kryterium dochodowego.", True,
             why="Jest powszechne dla dzieci do 18. roku życia."),
          M("Co obejmuje pojęcie wykluczenia społecznego?",
            ["Długotrwały brak pracy", "Brak dostępu do edukacji i usług", "Wysokie dochody z kapitału", "Bezdomność"],
            [0, 1, 3],
            why="Wysokie dochody nie są przejawem wykluczenia."),
          W("Dlaczego wpływ świadczeń pieniężnych na dzietność bywa niewielki?",
            "Decyzje o dzieciach zależą też od mieszkań, pracy, opieki i wartości", "Bo świadczenia są zbyt wysokie", "Bo dzieci nie mają kosztów",
            why="Pieniądz to tylko jeden z czynników."),
      ],
      calc=[
          LB("Rodzina z trojgiem dzieci otrzymuje 800 zł na każde dziecko. Ile wynosi roczna kwota świadczeń (zł)?",
             28800, "800*3*12", ["800 · 3 · 12 = 28 800 zł"], unit="zł"),
          LB("Świadczenie wzrosło z 500 do 800 zł. O ile procent?",
             60, "(800/500-1)*100", ["800 / 500 − 1 = 60%"], unit="%"),
          LB("Inflacja w latach 2024 i 2025 wyniosła odpowiednio 3,7% i 3,6% (przyjmijmy). Ile wynosi realna wartość 800 zł na koniec 2025 r. w cenach z początku 2024 r. (zł)?",
             744.65, "800/(1.037*1.036)", ["800 / (1,037 · 1,036) ≈ 744,65 zł"], unit="zł", tol=0.01),
          LB("Mieszkanie 60 m² kosztuje 12 000 zł/m². Dopłaty zwiększają popyt i ceny o 8%. O ile zł drożeje mieszkanie?",
             57600, "60*12000*0.08", ["720 000 · 0,08 = 57 600 zł (dane umowne)"], unit="zł"),
          LB("Rodzina zarabia 9000 zł netto miesięcznie, rata kredytu 3600 zł. Ile wynosi wskaźnik DSTI (%)?",
             40, "3600/9000*100", ["3600 / 9000 = 40%"], unit="%"),
          LB("Gmina buduje 200 mieszkań na wynajem po 300 000 zł. Ile wynosi koszt programu (mln zł)?",
             60, "200*300000/1e6", ["200 · 300 000 = 60 mln zł"], unit="mln zł"),
      ],
      case=[
          PR("W 2023 r. rząd uruchomił program dopłat do kredytów hipotecznych na pierwsze mieszkanie. W kolejnych miesiącach liczba udzielanych kredytów i ceny mieszkań w dużych miastach wyraźnie wzrosły, a podaż nowych mieszkań reagowała z opóźnieniem.",
             W("Jak ekonomia wyjaśnia wzrost cen?",
               "Wzrost popytu przy krótkookresowo sztywnej podaży", "Spadek popytu", "Wzrost podaży",
               why="Budowa mieszkań trwa kilka lat."),
             W("Która polityka trwale poprawiłaby dostępność mieszkań?",
               "Zwiększenie podaży (grunty, plany, budownictwo na wynajem)", "Kolejne dopłaty do kredytów", "Zakaz budowy",
               why="Problemem jest zbyt mała podaż względem popytu."),
             PF("Część korzyści z dopłat mogła trafić do sprzedających (wyższe ceny), a nie kupujących.", True,
                why="Przy sztywnej podaży dotacja jest „przerzucana” na cenę."),
          ),
          PR("W pewnym mieście mieszka grupa osób długotrwale bezrobotnych, z niskim wykształceniem, w zadłużonych mieszkaniach komunalnych. Część dzieci nie kończy szkoły. Gmina wypłaca zasiłki, ale sytuacja się nie poprawia.",
             W("Jakie zjawisko opisuje ten przypadek?",
               "Wykluczenie społeczne (wielowymiarowe)", "Bezrobocie frykcyjne", "Inflację kosztową",
               why="Problem dotyczy pracy, edukacji, mieszkania i uczestnictwa."),
             M("Jakie działania mogą pomóc?",
               ["Programy reintegracji zawodowej (np. centra integracji społecznej)", "Wsparcie edukacyjne dla dzieci", "Wyłącznie podwyżka zasiłków bez innych działań", "Pomoc w restrukturyzacji zadłużenia mieszkaniowego"],
               [0, 1, 3],
               why="Same zasiłki nie usuwają przyczyn wykluczenia."),
             PF("Przeciwdziałanie wykluczeniu wymaga zwykle połączenia wsparcia dochodowego z usługami i aktywizacją.", True,
                why="Wykluczenie ma wiele wymiarów."),
          ),
      ]),

    L(5, "Dialog społeczny i układy zbiorowe",
      "Rozumieć rolę dialogu społecznego, Rady Dialogu Społecznego, związków zawodowych i układów zbiorowych pracy oraz ich wpływ na płace i zatrudnienie.",
      ["Dialog społeczny i Rada Dialogu Społecznego", "Układy zbiorowe pracy i regulacje rynku pracy", "Płaca minimalna"],
      [S143, RDS, ZL],
      explain=[
          K("Dialog społeczny",
            "Współpraca rządu, organizacji pracodawców i związków zawodowych (partnerów społecznych) w sprawach pracy, płac i polityki społecznej. W Polsce głównym forum jest Rada Dialogu Społecznego (od 2015 r., zastąpiła Komisję Trójstronną). RDS opiniuje m.in. budżet, płacę minimalną i projekty ustaw."),
          K("Płaca minimalna w RDS",
            "Co roku rząd przedstawia propozycję płacy minimalnej, a partnerzy w RDS próbują uzgodnić jej wysokość. Jeśli nie dojdą do porozumienia, decyzję podejmuje Rada Ministrów w rozporządzeniu (nie niższą niż ustawowe minimum wynikające z formuły)."),
          W("Co się dzieje, gdy partnerzy w RDS nie uzgodnią płacy minimalnej?",
            "Rada Ministrów ustala ją rozporządzeniem", "Płaca minimalna przestaje obowiązywać", "Decyduje NBP",
            why="Ostateczna decyzja należy do rządu."),
          K("Związki zawodowe i układy zbiorowe",
            "Związki negocjują płace i warunki pracy w imieniu pracowników. Układ zbiorowy pracy to porozumienie między pracodawcą (lub organizacją pracodawców) a związkami – może dotyczyć jednego zakładu lub całej branży. W Polsce układy branżowe są rzadkie, a uzwiązkowienie niskie w porównaniu z krajami skandynawskimi."),
          K("Skutki ekonomiczne",
            "Związki mogą podnosić płace powyżej poziomu rynkowego (efekt monopolu po stronie podaży pracy), co sprzyja insiderom, a może ograniczać zatrudnienie outsiderów. Mogą też poprawiać komunikację, zmniejszać rotację i ograniczać siłę monopsonu. Skoordynowane negocjacje (np. w krajach nordyckich) pomagają uwzględniać konkurencyjność całej gospodarki."),
          PF("Rada Dialogu Społecznego zastąpiła w 2015 r. Komisję Trójstronną.", True,
             why="Na mocy ustawy z 2015 r."),
      ],
      mech=[
          LN("Ułóż przebieg ustalania płacy minimalnej w Polsce.",
             ["Rząd przedstawia propozycję płacy minimalnej", "Partnerzy w RDS negocjują", "Brak porozumienia lub uzgodnienie", "Rada Ministrów wydaje rozporządzenie", "Nowa płaca obowiązuje od 1 stycznia"],
             why="Dialog, potem decyzja rządu."),
          KT("Kto jest stroną dialogu społecznego?",
             {"Strona rządowa": ["Przedstawiciele Rady Ministrów"],
              "Pracodawcy": ["Organizacje pracodawców (np. Lewiatan, Pracodawcy RP)", "Związek Rzemiosła Polskiego"],
              "Pracownicy": ["Ogólnokrajowe związki zawodowe (np. NSZZ „Solidarność”, OPZZ)"]},
             why="RDS ma skład trójstronny."),
          WY("Związek zawodowy wywalcza płacę wyższą od rynkowej w branży konkurencyjnej. Co pokazuje model rynku pracy?",
             G("praca", SL=-1), "Płaca rośnie, ale firmy zatrudniają mniej – część chętnych nie znajduje pracy", "Zatrudnienie rośnie", "Nic się nie zmienia", "Płaca spada",
             why="Płaca powyżej równowagi zmniejsza popyt na pracę."),
          PF("W krajach nordyckich uzwiązkowienie jest znacznie wyższe niż w Polsce.", True,
             why="Tradycja silnych związków i systemu Ghent."),
          M("Jakie korzyści może przynieść dialog społeczny?",
            ["Mniej strajków i konfliktów", "Lepsze uwzględnienie interesów pracowników i firm", "Gwarancja braku zmian w prawie pracy", "Większa akceptacja reform"],
            [0, 1, 3],
            why="Dialog nie zamraża prawa."),
          W("Kogo w modelu insiderów–outsiderów chronią silne związki?",
            "Zatrudnionych (insiderów)", "Bezrobotnych", "Konsumentów",
            why="Negocjują płace i warunki dla obecnych pracowników."),
      ],
      calc=[
          LB("Popyt na pracę w branży: L = 500 − 10w, podaż L = 10w − 100. Ile wynosi płaca równowagi?",
             30, "600/20", ["500 − 10w = 10w − 100", "w = 30"], unit="zł/godz."),
          LB("Ile osób (tys.) jest zatrudnionych w równowadze?",
             200, "500-10*30", ["L = 500 − 300 = 200 tys."], unit="tys."),
          LB("Związek wywalcza płacę 33 zł/godz. Ile osób (tys.) zatrudniają firmy?",
             170, "500-10*33", ["L = 500 − 330 = 170 tys."], unit="tys."),
          LB("O ile procent wzrósł łączny dochód zatrudnionych z płac (w · L)?",
             -6.5, "(33*170/(30*200)-1)*100", ["30 · 200 = 6000", "33 · 170 = 5610", "Spadek o 6,5% – mniej osób pracuje"], unit="%"),
          LB("Płaca minimalna 2026: 4806 zł. Pracownik na układzie zbiorowym dostaje dodatek 15% ponad minimum. Ile zarabia brutto (zł)?",
             5526.9, "4806*1.15", ["4806 · 1,15 = 5526,90 zł"], unit="zł", tol=0.01),
          LB("Przyjmijmy, że uzwiązkowienie wynosi 13% w Polsce i 65% w Danii. Ile razy wyższe jest w Danii?",
             5, "65/13", ["65 / 13 = 5 razy (dane umowne)"], unit="razy"),
      ],
      case=[
          PR("Rząd przedstawił w RDS propozycję płacy minimalnej. Związki zawodowe żądały wyższej kwoty, pracodawcy – niższej, wskazując na koszty małych firm. Porozumienia nie osiągnięto i Rada Ministrów wydała rozporządzenie: na 2026 r. płaca minimalna wynosi 4806 zł, a stawka godzinowa 31,40 zł.",
             W("Jaką rolę pełniła RDS?",
               "Forum negocjacji partnerów społecznych", "Organu wydającego rozporządzenie", "Sądu pracy",
               why="Ostateczną decyzję podjął rząd."),
             W("Jaki argument pracodawców wobec wysokiej płacy minimalnej jest typowy?",
               "Wzrost kosztów pracy w małych firmach i regionach o niskich płacach", "Brak wpływu na koszty", "Zbyt niska inflacja",
               why="Płaca minimalna silniej „gryzie” tam, gdzie płace są niskie."),
             PF("Stawka godzinowa dotyczy m.in. umów zleceń.", True,
                why="Minimalna stawka godzinowa chroni zleceniobiorców i samozatrudnionych bez pracowników."),
          ),
          PR("W krajach nordyckich centralne negocjacje płacowe biorą pod uwagę konkurencyjność branż eksportowych: podwyżki w całej gospodarce są dopasowywane do tempa wzrostu płac w przemyśle eksportowym.",
             W("Jaką zaletę ma taka koordynacja?",
               "Płace rosną w tempie zgodnym z produktywnością i konkurencyjnością", "Płace przestają rosnąć", "Inflacja zawsze rośnie",
               why="Ogranicza spirale płacowo-cenowe."),
             W("Jaki warunek jest potrzebny, by taki model działał?",
               "Silne i reprezentatywne organizacje pracodawców i związków", "Brak związków zawodowych", "Brak dialogu z rządem",
               why="Koordynacja wymaga silnych partnerów."),
             PF("Koordynacja płac może ułatwiać bankowi centralnemu utrzymanie niskiej inflacji.", True,
                why="Ogranicza ryzyko efektów drugiej rundy."),
          ),
      ]),
]
