# -*- coding: utf-8 -*-
# Zrozumienie – Polityka gospodarcza / Polityka fiskalna i reguły budżetowe
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S301 = S("OpenStax, Principles of Economics 3e, 30.1 Government Spending", OS3 + "30-1-government-spending", D)
S302 = S("OpenStax, Principles of Economics 3e, 30.2 Taxation", OS3 + "30-2-taxation", D)
S303 = S("OpenStax, Principles of Economics 3e, 30.3 Federal Deficits and the National Debt", OS3 + "30-3-federal-deficits-and-the-national-debt", D)
S304 = S("OpenStax, Principles of Economics 3e, 30.4 Using Fiscal Policy to Fight Recession, Unemployment, and Inflation", OS3 + "30-4-using-fiscal-policy-to-fight-recession-unemployment-and-inflation", D)
S307 = S("OpenStax, Principles of Economics 3e, 30.7 The Question of a Balanced Budget", OS3 + "30-7-the-question-of-a-balanced-budget", D)
S313 = S("OpenStax, Principles of Economics 3e, 31.3 How Government Borrowing Affects Private Saving", OS3 + "31-3-how-government-borrowing-affects-private-saving", D)
S314 = S("OpenStax, Principles of Economics 3e, 31.4 Fiscal Policy, Investment, and Economic Growth", OS3 + "31-4-fiscal-policy-investment-and-economic-growth", D)
XYZD = S("XYZ – Deficyt sektora rządowego i samorządowego w 2025 r. wyniósł 7,3% PKB", "https://xyz.pl/dzieje-sie/deficyt-sektora-rzadowego-i-samorzadowego-w-2025-r-wyniosl-73-proc-pkb-1611", D)
PARK = S("Parkiet – Deficyt i dług publiczny w 2025 r. na rekordowych poziomach", "https://www.parkiet.com/gospodarka-krajowa/art44213641-deficyt-i-dlug-publiczny-w-2025-r-na-rekordowych-poziomach", D)
MFSZ = S("MF – Strategia zarządzania długiem sektora finansów publicznych 2025–2028", "https://www.gov.pl/web/finanse/rada-ministrow-przyjela-strategie-zarzadzania-dlugiem-sektora-finansow-publicznych-w-latach-20252028-przedlozona-przez-ministra-finansow", D)
XYZP = S("XYZ – Dług ma sięgnąć 75% PKB w 2029 r., zbliżamy się do krajowych progów", "https://xyz.pl/nanoanalizy/dlug-polski-ma-siegnac-75-proc-pkb-w-2029-r-zblizamy-sie-tez-do-krajowych-progow-ostroznosciowych-3127", D)
EDPA = S("Analizy.pl – Rada UE wszczęła procedurę nadmiernego deficytu wobec Polski", "https://www.analizy.pl/puls-rynku/35415/rada-ue-wszczela-procedure-nadmiernego-deficytu-wobec-polski", D)
EDPB = S("Bankier – Rada UE wszczęła procedurę nadmiernego deficytu wobec Polski", "https://www.bankier.pl/wiadomosc/Dziura-budzetowa-Rada-UE-wszczela-procedure-nadmiernego-deficytu-wobec-Polski-8788773.html", D)
KONST = S("Konstytucja RP (art. 216 ust. 5, art. 220) – tekst, Dz.U. 1997 nr 78 poz. 483 (Sejm, ELI)", "https://api.sejm.gov.pl/eli/acts/DU/1997/483/text.pdf", D)

LESSONS = [
    L(1, "Polityka fiskalna: deficyt, dług i mnożniki",
      "Rozumieć instrumenty polityki fiskalnej, różnicę między deficytem a długiem, deficyt strukturalny i cykliczny, dynamikę długu oraz możliwe niekeynesowskie efekty konsolidacji.",
      ["Polityka fiskalna (budżetowa)", "Niekeynesowskie efekty polityki fiskalnej", "Konsolidacja fiskalna"],
      [S303, S304, XYZD, PARK],
      explain=[
          K("Instrumenty i salda",
            "Polityka fiskalna to kształtowanie dochodów (podatki, składki) i wydatków publicznych. Deficyt – nadwyżka wydatków nad dochodami w danym roku (strumień). Dług – suma zaciągniętych i niespłaconych zobowiązań (zasób). Deficyt pierwotny – deficyt bez kosztów obsługi długu."),
          K("Deficyt cykliczny i strukturalny",
            "Deficyt cykliczny wynika z koniunktury (automatyczne stabilizatory), strukturalny – z trwałej relacji podatków i wydatków, jaka byłaby przy produkcji równej potencjałowi. Ocena polityki opiera się zwykle na saldzie strukturalnym."),
          W("Która wielkość jest „zasobem”, a nie „strumieniem”?",
            "Dług publiczny", "Deficyt budżetowy", "Wydatki w danym roku",
            why="Dług to suma deficytów z przeszłości (minus nadwyżki i spłaty)."),
          K("Dynamika długu",
            "Relacja długu do PKB rośnie, gdy deficyt pierwotny jest wysoki i gdy stopa procentowa od długu przewyższa tempo wzrostu nominalnego PKB (r > g). Przy g > r dług może maleć względem PKB nawet przy niewielkim deficycie pierwotnym.",
            w="Δd ≈ (r − g)·d + deficyt pierwotny"),
          K("Konsolidacja i efekty niekeynesowskie",
            "Konsolidacja fiskalna – trwałe ograniczanie deficytu (cięcia wydatków, wyższe podatki). Zwykle hamuje popyt w krótkim okresie, ale w kraju z bardzo wysokim długiem może poprawić zaufanie, obniżyć stopy procentowe i pobudzić inwestycje – to tzw. efekty niekeynesowskie (np. Irlandia i Dania w latach 80.). Ich skala jest przedmiotem sporu."),
          PF("Deficyt sektora instytucji rządowych i samorządowych w Polsce w 2025 r. wyniósł 7,3% PKB.", True,
             why="Według kwietniowej notyfikacji fiskalnej GUS (2026)."),
      ],
      mech=[
          LN("Ułóż wzrost długu w wyniku deficytów.",
             ["Wydatki przewyższają dochody", "Powstaje deficyt", "Rząd emituje obligacje", "Dług rośnie, a z nim koszty odsetek", "Wyższe odsetki zwiększają kolejne deficyty"],
             why="Kula śnieżna długu."),
          KT("Deficyt cykliczny czy strukturalny?",
             {"Cykliczny": ["Spadek wpływów z PIT w recesji", "Wzrost zasiłków dla bezrobotnych w recesji"],
              "Strukturalny": ["Trwała obniżka stawek podatku bez kompensaty", "Nowe stałe świadczenie socjalne", "Trwały wzrost wydatków na obronę"]},
             why="Cykliczny znika wraz z ożywieniem, strukturalny – nie."),
          W("Stopa od długu 5%, wzrost nominalnego PKB 8%. Co dzieje się z relacją długu do PKB przy zrównoważonym budżecie pierwotnym?",
            "Spada", "Rośnie", "Nie zmienia się",
            why="g > r – PKB rośnie szybciej niż dług."),
          PF("Konsolidacja fiskalna zawsze pobudza gospodarkę w krótkim okresie.", False,
             why="Zwykle ją hamuje; efekty niekeynesowskie zdarzają się w szczególnych warunkach."),
          M("Co zwiększa relację długu do PKB?",
            ["Wysoki deficyt pierwotny", "Wysokie stopy procentowe od długu", "Szybki wzrost nominalnego PKB", "Deprecjacja waluty przy długu w walutach obcych"],
            [0, 1, 3],
            why="Szybki wzrost PKB obniża relację."),
          W("Co to jest deficyt pierwotny?",
            "Deficyt bez kosztów obsługi długu (odsetek)", "Deficyt pierwszego roku kadencji", "Deficyt samorządów",
            why="Pokazuje, czy bieżące wydatki są pokryte dochodami."),
      ],
      calc=[
          LB("Deficyt 2025 r. wyniósł ok. 284 mld zł, czyli 7,3% PKB. Ile w przybliżeniu wynosił PKB (mld zł)?",
             3890.41, "284/0.073", ["284 / 0,073 ≈ 3890 mld zł"], unit="mld zł", tol=0.01),
          LB("Dług wzrósł z 54,8% do 59,7% PKB. O ile p.p.?",
             4.9, "59.7-54.8", ["59,7 − 54,8 = 4,9 p.p."], unit="p.p."),
          LB("Dług 60% PKB, r = 5%, g = 6%, deficyt pierwotny 3% PKB. O ile p.p. zmieni się relacja długu (przybliżenie)?",
             2.4, "(0.05-0.06)*60+3", ["(5% − 6%) · 60 = −0,6", "−0,6 + 3 = +2,4 p.p."], unit="p.p."),
          LB("Jaki deficyt pierwotny (% PKB) ustabilizuje dług na poziomie 60% przy r = 5% i g = 6%?",
             0.6, "-(0.05-0.06)*60", ["Δd = 0 ⇒ deficyt pierwotny = −(r − g) · d", "= −(−0,01) · 60 = 0,6% PKB – przy g > r niewielki deficyt pierwotny nie zwiększa relacji długu"], unit="%"),
          LB("Deficyt całkowity 7,3% PKB, koszty odsetek 2,5% PKB. Ile wynosi deficyt pierwotny (% PKB)?",
             4.8, "7.3-2.5", ["7,3 − 2,5 = 4,8% PKB (odsetki – dane umowne)"], unit="%"),
          LB("Deficyt 7% PKB, z czego cykliczny −0,5% (gospodarka powyżej potencjału zmniejsza deficyt o 0,5 p.p.). Ile wynosi deficyt strukturalny (% PKB)?",
             7.5, "7+0.5", ["Strukturalny = całkowity − cykliczny = 7 − (−0,5) = 7,5%"], unit="%"),
      ],
      case=[
          PR("Według kwietniowej notyfikacji fiskalnej GUS (2026) deficyt sektora instytucji rządowych i samorządowych w Polsce wyniósł w 2025 r. 7,3% PKB (ok. 284 mld zł), a dług – 59,7% PKB (2,335 bln zł) wobec 54,8% rok wcześniej. Rząd planował na 2026 r. deficyt ok. 6,8% PKB.",
             W("Jak ocenić tempo wzrostu długu?",
               "Szybkie – prawie 5 p.p. PKB w rok przy deficycie ok. 7% PKB", "Dług spadł", "Dług się nie zmienił",
               why="54,8% → 59,7% PKB."),
             W("Co, oprócz deficytu, decyduje o dynamice relacji długu do PKB?",
               "Relacja stóp procentowych od długu do tempa wzrostu nominalnego PKB", "Kurs akcji na giełdzie", "Liczba ministerstw",
               why="Efekt (r − g) · d."),
             PF("Utrzymywanie deficytu powyżej 3% PKB oznacza dalszy pobyt w procedurze nadmiernego deficytu UE.", True,
                why="Kryterium deficytu z traktatu: 3% PKB."),
          ),
          PR("Kraj o długu 120% PKB i wysokich rentownościach obligacji przeprowadza wiarygodną konsolidację, tnąc wydatki bieżące i przedstawiając wieloletni plan. Rentowności szybko spadają, inwestycje firm rosną, a recesja okazuje się płytsza niż przewidywano.",
             W("Jakie zjawisko mogło wystąpić?",
               "Niekeynesowskie efekty konsolidacji (poprawa zaufania)", "Paradoks zapobiegliwości", "Pułapka płynności",
               why="Spadek premii za ryzyko i lepsze oczekiwania częściowo zrównoważyły cięcia."),
             W("W jakich warunkach takie efekty są bardziej prawdopodobne?",
               "Przy bardzo wysokim długu i wiarygodnym planie opartym na wydatkach", "Przy niskim długu i stopach zerowych", "Zawsze",
               why="Wtedy poprawa zaufania jest największa."),
             PF("Wielu ekonomistów uważa, że w typowych warunkach konsolidacja jednak obniża PKB w krótkim okresie.", True,
                why="Mnożniki fiskalne są zwykle dodatnie, szczególnie w recesji."),
          ),
      ]),

    L(2, "Ekonomia podaży i krzywa Laffera",
      "Rozumieć ekonomię podaży, krzywą Laffera i politykę podażową: jak podatki wpływają na bodźce do pracy, oszczędzania i inwestowania oraz kiedy obniżka stawek może zwiększyć wpływy.",
      ["Ekonomia podaży (supply-side economics)", "Krzywa Laffera", "Polityka podażowa"],
      [S302, S314],
      explain=[
          K("Ekonomia podaży",
            "Nurt z lat 70.–80. (Laffer, Mundell, polityka Reagana i Thatcher): wzrost zależy przede wszystkim od podaży – bodźców do pracy, oszczędzania, inwestowania i przedsiębiorczości. Wysokie krańcowe stawki podatków je osłabiają. Postulaty: niższe stawki, deregulacja, elastyczny rynek pracy."),
          K("Krzywa Laffera",
            "Wpływy podatkowe w zależności od stawki: przy 0% – zero; przy 100% – też zero (nikt nie pracuje legalnie). Gdzieś pomiędzy jest stawka maksymalizująca wpływy. Na lewo od niej podwyżka stawki zwiększa wpływy, na prawo – zmniejsza (strefa „zakazana”). Kluczowe pytanie empiryczne: po której stronie maksimum jesteśmy.",
            w="T = t · B(t), B maleje wraz z t"),
          W("Kiedy obniżka stawki podatku może zwiększyć wpływy?",
            "Gdy stawka jest powyżej poziomu maksymalizującego wpływy", "Zawsze", "Nigdy",
            why="Tylko w „zakazanej” strefie krzywej Laffera."),
          K("Polityka podażowa",
            "Działania zwiększające potencjał gospodarki: niższe i prostsze podatki, deregulacja, edukacja i szkolenia, infrastruktura, sprzyjanie konkurencji i innowacjom. W modelu AD-AS przesuwa SRAS i LRAS w prawo – wzrost bez presji inflacyjnej, ale efekty pojawiają się wolno.",
            g=G("adas", SRAS=1)),
          K("Krytyka",
            "Obniżki podatków w USA w latach 80. zwiększyły deficyt – wpływy nie wzrosły tak, jak zapowiadano, bo stawki nie były w strefie zakazanej dla większości podatników. Efekt Laffera jest jednak realny przy bardzo wysokich stawkach i łatwym unikaniu podatków."),
          PF("Krzywa Laffera dowodzi, że każda obniżka podatków zwiększa wpływy budżetu.", False,
             why="Tylko jeśli stawka przekracza poziom maksymalizujący wpływy."),
      ],
      mech=[
          LN("Ułóż mechanizm efektu Laffera przy bardzo wysokiej stawce.",
             ["Krańcowa stawka podatku jest bardzo wysoka", "Opłaca się mniej pracować, unikać podatku lub przenieść dochód za granicę", "Podstawa opodatkowania się kurczy", "Obniżka stawki zachęca do legalnej aktywności", "Podstawa rośnie na tyle, że wpływy rosną"],
             why="Reakcja podstawy opodatkowania przeważa nad niższą stawką."),
          WY("Rząd upraszcza podatki i deregulację, co zwiększa produktywność. Co pokazuje model AD-AS?",
             G("adas", SRAS=1), "SRAS (i LRAS) w prawo – więcej produkcji przy niższych cenach", "AD w prawo – inflacja", "SRAS w lewo", "Nic",
             why="To polityka podażowa."),
          KT("Polityka podażowa czy popytowa?",
             {"Podażowa": ["Obniżka krańcowych stawek PIT", "Deregulacja zawodów", "Inwestycje w edukację zawodową"],
              "Popytowa": ["Jednorazowy bon dla gospodarstw domowych", "Obniżka stóp procentowych", "Zwiększenie zakupów rządowych"]},
             why="Podażowa zmienia bodźce i potencjał, popytowa – wydatki."),
          PF("Efekty polityki podażowej pojawiają się zwykle szybciej niż efekty polityki popytowej.", False,
             why="Zmiana bodźców i potencjału wymaga czasu."),
          M("Co według ekonomii podaży sprzyja wzrostowi?",
            ["Niższe krańcowe stawki podatków", "Deregulacja", "Wysokie cła importowe", "Elastyczny rynek pracy"],
            [0, 1, 3],
            why="Cła ograniczają konkurencję."),
          W("Od czego empirycznie zależy położenie maksimum krzywej Laffera?",
            "Od reakcji podstawy opodatkowania (elastyczności) na stawkę", "Od koloru formularza", "Od liczby urzędów skarbowych",
            why="Im silniejsza reakcja, tym niższa stawka maksymalizująca wpływy."),
      ],
      calc=[
          LB("Podstawa opodatkowania B = 1000 − 10t (t w %). Ile wynoszą wpływy przy t = 20% (T = t/100 · B)?",
             160, "0.2*(1000-10*20)", ["B = 800", "T = 0,2 · 800 = 160"], unit=""),
          LB("Ile wynoszą wpływy przy t = 50%?",
             250, "0.5*(1000-10*50)", ["B = 500", "T = 0,5 · 500 = 250"], unit=""),
          LB("Ile wynoszą wpływy przy t = 70%?",
             210, "0.7*(1000-10*70)", ["B = 300", "T = 0,7 · 300 = 210"], unit=""),
          LB("Przy jakiej stawce (%) wpływy są maksymalne? (T = t/100 · (1000 − 10t), pochodna: 10 − 0,2t = 0)",
             50, "10/0.2", ["T = 10t − 0,1t²", "T′ = 10 − 0,2t = 0 ⇒ t = 50%"], unit="%"),
          LB("Stawka spada z 70% do 60%. O ile rosną wpływy?",
             30, "0.6*(1000-10*60)-0.7*(1000-10*70)", ["Przy 60%: 0,6 · 400 = 240", "240 − 210 = 30 – efekt Laffera"], unit=""),
          LB("Stawka spada z 30% do 20%. O ile zmieniają się wpływy (ujemnie = spadek)?",
             -50, "0.2*(1000-10*20)-0.3*(1000-10*30)", ["Przy 30%: 0,3 · 700 = 210", "160 − 210 = −50"], unit=""),
      ],
      case=[
          PR("Na początku lat 80. XX w. w USA obniżono najwyższą krańcową stawkę podatku dochodowego z 70% do 50%, a później do 28%. Zwolennicy ekonomii podaży zapowiadali, że wpływy wzrosną. Deficyt budżetowy jednak wyraźnie się zwiększył.",
             W("Co sugeruje wzrost deficytu?",
               "Dla większości podatników stawki nie były w „zakazanej” strefie krzywej Laffera", "Krzywa Laffera nie istnieje", "Podatki wzrosły",
               why="Wpływy nie wzrosły na tyle, by pokryć obniżki."),
             W("U kogo efekt Laffera był najbardziej prawdopodobny?",
               "U najzamożniejszych podatników z bardzo wysoką stawką krańcową", "U osób o niskich dochodach", "U nikogo",
               why="Przy 70% reakcja podstawy jest najsilniejsza."),
             PF("Na deficyt USA w latach 80. wpływały też wyższe wydatki zbrojeniowe.", True,
                why="Deficyt zależy od obu stron budżetu."),
          ),
          PR("Kraj ma wysoki klin podatkowy na pracy i dużą szarą strefę. Rząd obniża składki dla najmniej zarabiających i upraszcza rozliczenia. Po dwóch latach liczba legalnie zatrudnionych rośnie, a wpływy ze składek spadają mniej, niż zakładano.",
             W("Jaki rodzaj polityki zastosowano?",
               "Podażową – zmiana bodźców do legalnej pracy", "Popytową – zwiększenie zakupów rządu", "Pieniężną",
               why="Niższe obciążenia zachęcają do legalnego zatrudnienia."),
             W("Dlaczego wpływy spadły mniej, niż zakładano?",
               "Poszerzyła się podstawa – część pracy wyszła z szarej strefy", "Bo stawki wzrosły", "Bo spadło zatrudnienie",
               why="Częściowy efekt Laffera."),
             PF("Takie obniżki zwykle w pełni się samofinansują.", False,
                why="Rzadko – najczęściej pokrywają tylko część kosztu."),
          ),
      ]),

    L(3, "Krajowe reguły fiskalne",
      "Rozumieć polskie reguły fiskalne: konstytucyjny limit długu, progi ostrożnościowe ustawy o finansach publicznych, stabilizującą regułę wydatkową i złotą zasadę finansów publicznych – oraz różnicę między krajową a unijną miarą długu.",
      ["Progi ostrożnościowe i konstytucyjny limit długu", "Stabilizująca reguła wydatkowa", "Reguła złotej zasady (finansów publicznych)"],
      [KONST, MFSZ, XYZP],
      explain=[
          K("Konstytucyjny limit długu",
            "Art. 216 ust. 5 Konstytucji RP: nie wolno zaciągać pożyczek ani udzielać gwarancji, w następstwie których państwowy dług publiczny przekroczy 3/5 wartości rocznego PKB. To jedna z niewielu na świecie reguł długu zapisanych w konstytucji."),
          K("Progi ostrożnościowe",
            "Ustawa o finansach publicznych przewiduje procedury, gdy relacja państwowego długu publicznego do PKB przekroczy 55% (dawniej także próg 50%): m.in. budżet bez deficytu lub z deficytem zapewniającym spadek relacji długu, zamrożenie płac w sferze budżetowej, waloryzacja świadczeń nie wyższa niż inflacja. Uwaga: państwowy dług publiczny (definicja krajowa) różni się od długu sektora instytucji rządowych i samorządowych (EDP) – ten drugi w 2025 r. wyniósł 59,7% PKB."),
          W("Która miara długu jest podstawą konstytucyjnego limitu 60% PKB?",
            "Państwowy dług publiczny (definicja krajowa)", "Dług EDP liczony przez Eurostat", "Dług gospodarstw domowych",
            why="Krajowa definicja różni się m.in. zakresem podmiotów (np. fundusze w BGK i PFR)."),
          K("Stabilizująca reguła wydatkowa",
            "Od 2014 r. ogranicza tempo wzrostu wydatków dużej części sektora finansów publicznych: limit rośnie w tempie średniookresowego wzrostu PKB i prognozowanej inflacji, z korektą, gdy deficyt lub dług są zbyt wysokie. Reguła działa antycyklicznie – nie pozwala wydawać nadzwyczajnych dochodów z boomu."),
          K("Złota zasada",
            "Dług wolno zaciągać tylko na inwestycje, a wydatki bieżące mają być pokryte dochodami bieżącymi. Uzasadnienie: inwestycje przynoszą korzyści przyszłym pokoleniom, które spłacają dług. Ryzyko: „księgowe” przesuwanie wydatków bieżących do inwestycyjnych."),
          PF("Dług poza budżetem (np. w funduszach przy BGK) może nie być w pełni widoczny w krajowej mierze długu.", True,
             why="Dlatego różnice między miarą krajową a unijną (EDP) bywają duże."),
      ],
      mech=[
          LN("Ułóż działanie progu ostrożnościowego 55%.",
             ["Relacja państwowego długu publicznego do PKB przekracza 55%", "Wynik jest ogłaszany w obwieszczeniu ministra finansów", "W kolejnym budżecie uruchamiają się procedury ostrożnościowe", "Ograniczane są deficyt, płace w sferze budżetowej i waloryzacja", "Relacja długu ma zacząć spadać"],
             why="Procedury mają zatrzymać wzrost długu, zanim osiągnie limit konstytucyjny."),
          KT("Reguła krajowa czy unijna?",
             {"Krajowa": ["Art. 216 ust. 5 Konstytucji (3/5 PKB)", "Próg 55% w ustawie o finansach publicznych", "Stabilizująca reguła wydatkowa"],
              "Unijna": ["Deficyt 3% PKB w traktacie", "Procedura nadmiernego deficytu", "Wartość referencyjna długu 60% PKB (EDP)"]},
             why="Polska podlega obu zestawom reguł."),
          W("Dlaczego reguła wydatkowa jest antycykliczna?",
            "Limit wydatków zależy od średniookresowego wzrostu, więc w boomie nadwyżki dochodów nie są wydawane", "Bo zakazuje wydatków", "Bo zależy od kursu złotego",
            why="Wydatki nie rosną szybciej w dobrej koniunkturze."),
          PF("Złota zasada pozwala finansować długiem wydatki bieżące, np. pensje.", False,
             why="Pozwala zadłużać się tylko na inwestycje."),
          M("Jakie są skutki przekroczenia progu 55% według ustawy o finansach publicznych?",
            ["Deficyt zapewniający spadek relacji długu do PKB", "Brak wzrostu wynagrodzeń w państwowej sferze budżetowej", "Automatyczna podwyżka wszystkich podatków o 10%", "Waloryzacja świadczeń nie wyższa niż inflacja"],
            [0, 1, 3],
            why="Ustawa nie przewiduje automatycznej podwyżki podatków."),
          W("Co jest ryzykiem złotej zasady?",
            "Klasyfikowanie wydatków bieżących jako inwestycyjnych, by móc je finansować długiem", "Zbyt niski dług", "Zakaz inwestycji",
            why="Granica między wydatkiem bieżącym a inwestycyjnym bywa płynna."),
      ],
      calc=[
          LB("PKB 3900 mld zł. Ile maksymalnie może wynieść państwowy dług publiczny zgodnie z konstytucją (mld zł)?",
             2340, "0.6*3900", ["3/5 · 3900 = 2340 mld zł"], unit="mld zł"),
          LB("Przy jakiej kwocie długu (mld zł) przekroczony zostanie próg ostrożnościowy 55%?",
             2145, "0.55*3900", ["0,55 · 3900 = 2145 mld zł"], unit="mld zł"),
          LB("Reguła wydatkowa (uproszczona): limit rośnie o średni wzrost realnego PKB 3% plus inflację 2,5%, minus korekta 1 p.p. Wydatki objęte regułą: 1200 mld zł. Jaki jest limit na kolejny rok (mld zł)?",
             1254, "1200*(1+0.03+0.025-0.01)", ["Wzrost: 3 + 2,5 − 1 = 4,5%", "1200 · 1,045 = 1254 mld zł (dane umowne)"], unit="mld zł"),
          LB("Bez korekty limit wyniósłby (mld zł):",
             1266, "1200*1.055", ["1200 · 1,055 = 1266 mld zł"], unit="mld zł"),
          LB("Złota zasada: dochody bieżące 900, wydatki bieżące 850, inwestycje 150 (mld zł). Ile trzeba pożyczyć (mld zł)?",
             100, "850+150-900", ["Nadwyżka bieżąca: 900 − 850 = 50", "Potrzeby pożyczkowe: 150 − 50 = 100 mld zł – mniej niż inwestycje, więc zasada spełniona"], unit="mld zł"),
          LB("Gdyby wydatki bieżące wynosiły 1000 mld zł, ile wyniósłby deficyt bieżący, łamiący złotą zasadę (mld zł)?",
             100, "1000-900", ["1000 − 900 = 100 mld zł finansowane długiem na cele bieżące"], unit="mld zł"),
      ],
      case=[
          PR("W 2025 r. dług sektora instytucji rządowych i samorządowych (definicja UE) wyniósł 59,7% PKB, natomiast państwowy dług publiczny według definicji krajowej był wyraźnie niższy. Część zobowiązań, m.in. funduszy w BGK i PFR, nie wchodzi do krajowej miary.",
             W("Dlaczego obie miary się różnią?",
               "Mają inny zakres podmiotów i zobowiązań", "Bo jedna jest w złotych, a druga w euro", "Nie różnią się",
               why="Krajowa definicja pomija część funduszy pozabudżetowych."),
             W("Do której miary odnosi się limit z art. 216 ust. 5 Konstytucji?",
               "Do państwowego długu publicznego", "Do długu EDP", "Do długu firm",
               why="Konstytucja dotyczy definicji krajowej."),
             PF("Przenoszenie wydatków do funduszy poza budżetem może osłabiać przejrzystość finansów publicznych.", True,
                why="Część długu jest „niewidoczna” dla krajowych reguł."),
          ),
          PR("Gospodarka przeżywa boom: dochody podatkowe rosną o 15%, a politycy chcą je przeznaczyć na nowe stałe świadczenia. Reguła wydatkowa pozwala na wzrost wydatków tylko o ok. 6%.",
             W("Jaką funkcję pełni reguła w tej sytuacji?",
               "Chroni przed procykliczną ekspansją i trwałym wzrostem wydatków z przejściowych dochodów", "Zmusza do zwiększenia wydatków", "Nie ma znaczenia",
               why="Nadwyżka dochodów z boomu poprawia saldo."),
             W("Co stanie się z deficytem w czasie boomu przy przestrzeganiu reguły?",
               "Zmniejszy się", "Wzrośnie", "Nie zmieni się",
               why="Dochody rosną szybciej niż wydatki."),
             PF("W recesji ta sama reguła pozwala wydatkom rosnąć mimo spadku dochodów.", True,
                why="Limit opiera się na średniookresowym wzroście, a nie bieżących dochodach."),
          ),
      ]),

    L(4, "Reguły UE: Pakt Stabilności, EDP i pakt fiskalny",
      "Rozumieć unijne reguły fiskalne: wartości referencyjne 3% i 60% PKB, procedurę nadmiernego deficytu, ogólną klauzulę wyjścia, pakt fiskalny z 2012 r. oraz reformę reguł z 2024 r.",
      ["Procedura nadmiernego deficytu (EDP)", "Klauzula wyjścia (Pakt Stabilności i Wzrostu)", "Pakt fiskalny (2012)"],
      [EDPA, EDPB, S307],
      explain=[
          K("Wartości referencyjne",
            "Traktat z Maastricht: deficyt sektora instytucji rządowych i samorządowych do 3% PKB, dług do 60% PKB. Pakt Stabilności i Wzrostu (1997) określa, jak egzekwować te wartości: część zapobiegawcza (średniookresowe cele, nadzór) i część naprawcza (procedura nadmiernego deficytu)."),
          K("Procedura nadmiernego deficytu",
            "Gdy deficyt przekracza 3% PKB (lub dług przekracza 60% i nie maleje w wymaganym tempie), Rada UE na wniosek Komisji stwierdza nadmierny deficyt i wydaje zalecenia z terminem korekty. W strefie euro możliwe są sankcje finansowe. Wobec Polski procedurę otwarto decyzją Rady z 26 lipca 2024 r. (wcześniej w latach 2004–2008 i 2009–2015)."),
          W("Kto formalnie stwierdza nadmierny deficyt w państwie UE?",
            "Rada UE na wniosek Komisji Europejskiej", "Europejski Bank Centralny", "Parlament krajowy",
            why="Decyzja należy do Rady."),
          K("Klauzula wyjścia",
            "Ogólna klauzula wyjścia pozwala czasowo odejść od wymogów w razie poważnego spowolnienia w całej UE. Aktywowano ją w 2020 r. (pandemia) i stosowano do końca 2023 r. Od 2024 r. obowiązują zreformowane reguły – z naciskiem na ścieżkę wydatków netto uzgadnianą na kilka lat."),
          K("Pakt fiskalny (2012)",
            "Traktat o stabilności, koordynacji i zarządzaniu w UGW: deficyt strukturalny nie większy niż 0,5% PKB (1% przy długu znacznie poniżej 60%), automatyczny mechanizm korekty w prawie krajowym, redukcja nadwyżki długu ponad 60% PKB o 1/20 rocznie. Powstał po kryzysie zadłużenia w strefie euro."),
          PF("Procedura nadmiernego deficytu wobec Polski otwarta w 2024 r. była pierwszą w historii Polski.", False,
             why="Polska była objęta EDP także w latach 2004–2008 i 2009–2015."),
      ],
      mech=[
          LN("Ułóż przebieg procedury nadmiernego deficytu.",
             ["Deficyt przekracza 3% PKB", "Komisja przygotowuje raport i wniosek", "Rada UE stwierdza nadmierny deficyt", "Rada wydaje zalecenia z terminem korekty", "Kraj raportuje postępy, a po trwałej korekcie procedura zostaje zamknięta"],
             why="Procedura ma doprowadzić do trwałego obniżenia deficytu."),
          KT("Która reguła lub dokument?",
             {"Traktat z Maastricht": ["Wartości referencyjne 3% i 60% PKB"],
              "Pakt fiskalny": ["Deficyt strukturalny do 0,5% PKB", "Redukcja nadwyżki długu o 1/20 rocznie"],
              "Klauzula wyjścia": ["Zawieszenie wymogów w czasie pandemii"],
              "EDP": ["Zalecenia Rady z terminem korekty deficytu"]},
             why="Różne elementy unijnych ram fiskalnych."),
          W("Dlaczego w 2020 r. aktywowano ogólną klauzulę wyjścia?",
            "Pandemia wywołała poważne spowolnienie w całej UE i wymagała dużego wsparcia fiskalnego", "Bo inflacja była za niska", "Bo zniesiono euro",
            why="Klauzula dotyczy poważnych kryzysów."),
          PF("Sankcje finansowe w procedurze nadmiernego deficytu mogą dotyczyć przede wszystkim państw strefy euro.", True,
             why="Wobec innych państw głównym narzędziem jest m.in. zawieszanie części środków."),
          M("Co obejmują ramy fiskalne UE?",
            ["Wartość referencyjną deficytu 3% PKB", "Wartość referencyjną długu 60% PKB", "Obowiązkowy cel inflacyjny dla rządów", "Procedurę nadmiernego deficytu"],
            [0, 1, 3],
            why="Cel inflacyjny dotyczy banków centralnych."),
          W("Co oznacza reguła 1/20 z paktu fiskalnego?",
            "Nadwyżka długu ponad 60% PKB ma maleć co roku o 1/20", "Deficyt ma wynosić 1/20 PKB", "Dług ma spaść do zera w 20 lat",
            why="Np. przy długu 80% nadwyżka 20 p.p. ma spadać o 1 p.p. rocznie."),
      ],
      calc=[
          LB("Deficyt wynosi 7,3% PKB. O ile p.p. przekracza wartość referencyjną?",
             4.3, "7.3-3", ["7,3 − 3 = 4,3 p.p."], unit="p.p."),
          LB("Reguła 1/20: dług 80% PKB. O ile p.p. rocznie powinna spadać jego relacja do PKB?",
             1, "(80-60)/20", ["(80 − 60) / 20 = 1 p.p."], unit="p.p."),
          LB("Deficyt ma spaść z 7,3% do 3% PKB w ciągu 4 lat równymi krokami. O ile p.p. rocznie?",
             1.08, "(7.3-3)/4", ["4,3 / 4 ≈ 1,08 p.p. rocznie (dane umowne)"], unit="p.p.", tol=0.02),
          LB("Deficyt całkowity 4% PKB, cykliczny 1% PKB, jednorazowe wydatki 0,5% PKB. Ile wynosi deficyt strukturalny (% PKB)?",
             2.5, "4-1-0.5", ["4 − 1 − 0,5 = 2,5%"], unit="%"),
          LB("O ile p.p. deficyt strukturalny przekracza limit paktu fiskalnego 0,5% PKB?",
             2, "2.5-0.5", ["2,5 − 0,5 = 2 p.p."], unit="p.p."),
          LB("PKB 3900 mld zł. Ile mld zł wynosi korekta deficytu o 1 p.p. PKB?",
             39, "0.01*3900", ["0,01 · 3900 = 39 mld zł"], unit="mld zł"),
      ],
      case=[
          PR("26 lipca 2024 r. Rada UE stwierdziła nadmierny deficyt w Polsce (decyzja 2024/2133), opierając się na kryterium deficytu za 2023 r. Polska ma co pół roku, od 30 kwietnia 2025 r., raportować postępy. Deficyt sektora GG w 2025 r. wyniósł 7,3% PKB.",
             W("Na jakim kryterium oparto decyzję?",
               "Kryterium deficytu (powyżej 3% PKB)", "Kryterium inflacji", "Kryterium kursu walutowego",
               why="Dług Polski był wtedy poniżej 60% PKB."),
             W("Jaki obowiązek wynika z procedury?",
               "Regularne raportowanie i korekta deficytu w wyznaczonym terminie", "Natychmiastowe przyjęcie euro", "Zakaz emisji obligacji",
               why="Procedura wymaga ścieżki korekty i sprawozdań."),
             PF("Wysoki deficyt w 2025 r. utrudnia szybkie zamknięcie procedury.", True,
                why="Deficyt nadal znacznie przekracza 3% PKB."),
          ),
          PR("Po kryzysie zadłużenia w strefie euro (2010–2012) kraje podpisały pakt fiskalny, zobowiązując się do zrównoważonych budżetów w ujęciu strukturalnym i wpisania reguł do prawa krajowego. Krytycy uważali, że wymusił on zbyt szybkie cięcia w czasie recesji.",
             W("Jaki był cel paktu?",
               "Wzmocnienie dyscypliny fiskalnej i wiarygodności strefy euro", "Zwiększenie deficytów", "Likwidacja euro",
               why="Odpowiedź na kryzys zaufania do długu."),
             W("Dlaczego reguły oparte na saldzie strukturalnym są trudne w praktyce?",
               "Saldo strukturalne zależy od niepewnie szacowanej luki PKB", "Bo saldo strukturalne jest zawsze zerowe", "Bo nie istnieje PKB",
               why="Szacunki potencjału bywają mocno rewidowane."),
             PF("Krytycy wskazywali, że zbyt szybka konsolidacja w recesji mogła pogłębić spadek PKB.", True,
                why="Dodatnie mnożniki fiskalne w recesji."),
          ),
      ]),

    L(5, "Jak konsolidować finanse publiczne",
      "Porównywać sposoby ograniczania deficytu (cięcia wydatków, podwyżki podatków, reformy), ich wpływ na wzrost i rozkład dochodów oraz projektować wiarygodny plan konsolidacji.",
      ["Konsolidacja fiskalna", "Polityka fiskalna (budżetowa)", "Niekeynesowskie efekty polityki fiskalnej", "Polityka podażowa"],
      [S304, S313, XYZD],
      explain=[
          K("Narzędzia konsolidacji",
            "Po stronie wydatków: ograniczenie wydatków bieżących, przegląd i celowanie transferów, reforma emerytalna (np. wiek emerytalny), efektywność administracji. Po stronie dochodów: szersza podstawa opodatkowania (likwidacja ulg), uszczelnienie podatków, podwyżki stawek. Inwestycje publiczne warto chronić, bo budują potencjał."),
          K("Tempo i moment",
            "Szybka konsolidacja w recesji może pogłębić spadek PKB (dodatnie mnożniki), co utrudnia obniżanie relacji długu do PKB. Stopniowa, wiarygodna ścieżka – rozpoczęta w okresie wzrostu – zwykle kosztuje mniej. Pomaga też łagodna polityka pieniężna."),
          W("Kiedy konsolidacja jest zwykle najmniej kosztowna dla wzrostu?",
            "Gdy gospodarka rośnie, a plan jest stopniowy i wiarygodny", "W głębokiej recesji", "Gdy jest prowadzona bez zapowiedzi",
            why="Mnożniki są wtedy mniejsze, a oczekiwania stabilne."),
          K("Wiarygodność",
            "Rynki i UE oceniają nie tylko jednoroczne cięcia, ale trwałość: czy zmiany są strukturalne (np. reforma), a nie jednorazowe (np. sprzedaż aktywów). Wiarygodny plan obniża rentowności obligacji i koszty obsługi długu."),
          K("Sprawiedliwość",
            "Konsolidacja zmienia rozkład obciążeń: cięcia transferów uderzają w uboższych, podwyżki VAT – w konsumpcję (regresywnie), podwyżki PIT – w lepiej zarabiających. Akceptacja społeczna zależy od postrzeganej sprawiedliwości."),
          PF("Jednorazowa sprzedaż majątku państwa trwale rozwiązuje problem deficytu strukturalnego.", False,
             why="Daje dochód tylko raz – deficyt strukturalny pozostaje."),
      ],
      mech=[
          KT("Działanie trwałe czy jednorazowe?",
             {"Trwałe (strukturalne)": ["Podniesienie efektywnego wieku emerytalnego", "Likwidacja nieefektywnej ulgi podatkowej", "Reforma zatrudnienia w administracji"],
              "Jednorazowe": ["Sprzedaż udziałów w spółce", "Przesunięcie płatności na kolejny rok", "Jednorazowy podatek od nadzwyczajnych zysków"]},
             why="Tylko działania trwałe poprawiają saldo strukturalne."),
          LN("Ułóż etapy wiarygodnej konsolidacji.",
             ["Diagnoza: deficyt strukturalny i przyczyny", "Wieloletni plan z celami liczbowymi", "Reformy strukturalne po stronie wydatków i dochodów", "Ochrona inwestycji i najuboższych", "Monitoring i raportowanie postępów"],
             why="Plan, reformy, ochrona wzrostu, kontrola."),
          W("Która zmiana jest najbardziej regresywna (obciąża relatywnie najmocniej uboższych)?",
            "Podwyżka podstawowej stawki VAT", "Podwyżka najwyższej stawki PIT", "Podatek od dużych majątków",
            why="Ubożsi wydają większą część dochodu na konsumpcję."),
          PF("Wiarygodny plan konsolidacji może obniżyć koszty obsługi długu.", True,
             why="Spada premia za ryzyko w rentownościach obligacji."),
          M("Co sprzyja powodzeniu konsolidacji?",
            ["Rozpoczęcie w okresie wzrostu", "Nacisk na trwałe zmiany", "Cięcie wyłącznie inwestycji publicznych", "Przejrzysta komunikacja"],
            [0, 1, 3],
            why="Cięcie inwestycji obniża przyszły potencjał."),
          W("Dlaczego cięcie inwestycji publicznych bywa krótkowzroczne?",
            "Obniża przyszły potencjał wzrostu, a więc i przyszłe dochody", "Bo inwestycje nie kosztują", "Bo zwiększa inflację",
            why="Inwestycje budują infrastrukturę i produktywność."),
      ],
      calc=[
          LB("Konsolidacja 2% PKB: 1,2% po stronie wydatków (mnożnik 0,8) i 0,8% po stronie podatków (mnożnik 0,4). O ile procent spada PKB w pierwszym roku?",
             1.28, "1.2*0.8+0.8*0.4", ["1,2 · 0,8 = 0,96", "0,8 · 0,4 = 0,32", "Razem 1,28%"], unit="%"),
          LB("Gdyby całą konsolidację przeprowadzić podatkami (mnożnik 0,4), o ile spadłby PKB (%)?",
             0.8, "2*0.4", ["2 · 0,4 = 0,8%"], unit="%"),
          LB("Dług 60% PKB, PKB spada o 1,28%, a dług pozostaje bez zmian. Ile wynosi nowa relacja długu do PKB (%)?",
             60.78, "60/(1-0.0128)", ["60 / 0,9872 ≈ 60,78% – krótkookresowo relacja może wzrosnąć"], unit="%", tol=0.02),
          LB("Likwidacja ulgi kosztującej 12 mld zł i podwyżka efektywnego wieku emerytalnego dająca 8 mld zł oszczędności. Ile wynosi trwała poprawa salda (mld zł)?",
             20, "12+8", ["12 + 8 = 20 mld zł"], unit="mld zł"),
          LB("Przy PKB 3900 mld zł ile to % PKB?",
             0.51, "20/3900*100", ["20 / 3900 ≈ 0,51% PKB"], unit="%", tol=0.02),
          LB("Spadek rentowności obligacji o 0,5 p.p. przy długu 2300 mld zł (pełne przeszacowanie po latach). O ile mld zł rocznie spadają odsetki?",
             11.5, "0.005*2300", ["0,005 · 2300 = 11,5 mld zł"], unit="mld zł"),
      ],
      case=[
          PR("Rząd kraju z deficytem 7% PKB rozważa dwa pakiety. A: jednorazowa sprzedaż udziałów w spółkach (1,5% PKB) i zamrożenie inwestycji publicznych. B: stopniowe podnoszenie efektywnego wieku emerytalnego, likwidacja części ulg podatkowych i przegląd wydatków, z ochroną inwestycji (łącznie 1,5% PKB rocznie przez 3 lata).",
             W("Który pakiet trwale poprawia saldo strukturalne?",
               "B", "A", "Żaden",
               why="A zawiera jednorazowy dochód i cięcia inwestycji obniżające potencjał."),
             W("Dlaczego pakiet B jest bardziej wiarygodny dla inwestorów?",
               "Opiera się na trwałych zmianach rozłożonych w czasie", "Bo daje więcej pieniędzy od razu", "Bo zwiększa deficyt",
               why="Trwałość i plan wieloletni zwiększają zaufanie."),
             PF("Pakiet A może poprawić deficyt w jednym roku, ale problem wróci w kolejnym.", True,
                why="Dochód ze sprzedaży aktywów jest jednorazowy."),
          ),
          PR("Grecja w latach 2010–2015 przeprowadziła bardzo silną konsolidację w czasie głębokiej recesji, przy braku własnej polityki pieniężnej i kursowej (strefa euro). Realny PKB był w połowie dekady o ok. jedną czwartą niższy niż na szczycie z 2008 r., a relacja długu do PKB mimo cięć wzrosła.",
             W("Dlaczego relacja długu do PKB rosła mimo cięć?",
               "PKB spadał szybciej, niż spadał dług", "Bo dług zniknął", "Bo PKB rósł",
               why="Mianownik relacji malał."),
             W("Którego narzędzia brakowało Grecji, by złagodzić skutki konsolidacji?",
               "Własnej polityki pieniężnej i kursu walutowego", "Podatków", "Wydatków publicznych",
               why="Jako członek strefy euro nie mogła zdewaluować waluty ani obniżyć stóp."),
             PF("Przykład Grecji pokazuje, że tempo i warunki konsolidacji mają duże znaczenie.", True,
                why="Zbyt szybkie cięcia w recesji mogą być samoniszczące."),
          ),
      ]),
]
