# -*- coding: utf-8 -*-
# Zrozumienie – Polityka gospodarcza / Cele i narzędzia polityki gospodarczej
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S304 = S("OpenStax, Principles of Economics 3e, 30.4 Using Fiscal Policy to Fight Recession, Unemployment, and Inflation", OS3 + "30-4-using-fiscal-policy-to-fight-recession-unemployment-and-inflation", D)
S305 = S("OpenStax, Principles of Economics 3e, 30.5 Automatic Stabilizers", OS3 + "30-5-automatic-stabilizers", D)
S306 = S("OpenStax, Principles of Economics 3e, 30.6 Practical Problems with Discretionary Fiscal Policy", OS3 + "30-6-practical-problems-with-discretionary-fiscal-policy", D)
S285 = S("OpenStax, Principles of Economics 3e, 28.5 Pitfalls for Monetary Policy", OS3 + "28-5-pitfalls-for-monetary-policy", D)
S263 = S("OpenStax, Principles of Economics 3e, 26.3 Balancing Keynesian and Neoclassical Models", OS3 + "26-3-balancing-keynesian-and-neoclassical-models", D)
S132 = S("OpenStax, Principles of Economics 3e, 13.3 Public Goods", OS3 + "13-3-public-goods", D)
S14 = S("OpenStax, Principles of Economics 3e, 1.4 How To Organize Economies: An Overview of Economic Systems", OS3 + "1-4-how-to-organize-economies-an-overview-of-economic-systems", D)
NOB86 = S("Nobel Prize – The Prize in Economic Sciences 1986 (James M. Buchanan Jr.)", "https://www.nobelprize.org/prizes/economic-sciences/1986/summary/", D)
NOB04 = S("Nobel Prize – The Prize in Economic Sciences 2004 (Kydland, Prescott)", "https://www.nobelprize.org/prizes/economic-sciences/2004/summary/", D)
SOR = S("Ministerstwo Funduszy i Polityki Regionalnej – Strategia na rzecz Odpowiedzialnego Rozwoju", "https://www.gov.pl/web/fundusze-regiony/informacje-o-strategii-na-rzecz-odpowiedzialnego-rozwoju", D)

S307 = S("OpenStax, Principles of Economics 3e, 30.7 The Question of a Balanced Budget", OS3 + "30-7-the-question-of-a-balanced-budget", D)
S314 = S("OpenStax, Principles of Economics 3e, 31.4 Fiscal Policy, Investment, and Economic Growth", OS3 + "31-4-fiscal-policy-investment-and-economic-growth", D)

LESSONS = [
    L(1, "Cele, podmioty i narzędzia polityki gospodarczej",
      "Rozumieć, czym jest polityka gospodarcza, jakie ma cele (magiczny czworokąt), kto ją prowadzi i jakimi narzędziami oraz dlaczego cele bywają sprzeczne.",
      ["Polityka gospodarcza (ekonomiczna)", "Cele, podmioty i instrumenty polityki gospodarczej", "Magiczny czworokąt polityki gospodarczej", "Policy mix"],
      [S304, S285, S263],
      explain=[
          K("Czym jest polityka gospodarcza",
            "To świadome oddziaływanie państwa (rządu, banku centralnego, samorządów) na gospodarkę w celu osiągnięcia określonych celów. Składa się z: celów (co chcemy osiągnąć), podmiotów (kto działa), instrumentów (czym działa) i mechanizmów oddziaływania (jak instrument wpływa na cel)."),
          K("Magiczny czworokąt",
            "Cztery główne cele makroekonomiczne: wzrost gospodarczy, wysokie zatrudnienie (niskie bezrobocie), stabilny poziom cen (niska inflacja) i równowaga zewnętrzna (bilans płatniczy). „Magiczny”, bo jednoczesne osiągnięcie wszystkich jest bardzo trudne – cele bywają sprzeczne (np. pobudzanie zatrudnienia może podnosić inflację)."),
          W("Który cel NIE należy do magicznego czworokąta?",
            "Maksymalizacja zysków przedsiębiorstw", "Stabilność cen", "Wysokie zatrudnienie", "Równowaga zewnętrzna",
            why="Czworokąt obejmuje wzrost, zatrudnienie, stabilność cen i równowagę zewnętrzną."),
          K("Podmioty i instrumenty",
            "Rząd i parlament – polityka fiskalna (podatki, wydatki, deficyt). Bank centralny (w Polsce NBP i RPP) – polityka pieniężna (stopy procentowe, operacje otwartego rynku, rezerwa obowiązkowa). Ponadto regulacje (prawo konkurencji, płaca minimalna), polityki sektorowe i regionalne. Instrumenty dzielą się na ekonomiczne (bodźce cenowe), administracyjne (nakazy i zakazy) i informacyjne."),
          K("Policy mix",
            "Połączenie polityki fiskalnej i pieniężnej. Mogą działać w tym samym kierunku (oba ekspansywne w recesji) albo w przeciwnych (np. ekspansywny budżet i restrykcyjne stopy – ryzyko wysokich stóp i aprecjacji waluty). Dobra koordynacja zmniejsza koszty osiągania celów."),
          PF("Cele polityki gospodarczej zawsze się wzajemnie wspierają.", False,
             why="Często są w konflikcie – np. stabilność cen i wysokie zatrudnienie w krótkim okresie."),
      ],
      mech=[
          KT("Cel, podmiot czy instrument?",
             {"Cel": ["Inflacja 2,5% ± 1 p.p.", "Niskie bezrobocie", "Zrównoważony bilans płatniczy"],
              "Podmiot": ["Rada Polityki Pieniężnej", "Rada Ministrów"],
              "Instrument": ["Stopa referencyjna", "Stawka VAT", "Wydatki inwestycyjne budżetu"]},
             why="Polityka to cele osiągane przez podmioty za pomocą instrumentów."),
          LN("Ułóż konflikt celów w przegrzanej gospodarce.",
             ["Bezrobocie spada poniżej naturalnego", "Rosną płace i ceny", "Bank centralny podnosi stopy, by chronić stabilność cen", "Wzrost gospodarczy zwalnia", "Bezrobocie nieco rośnie"],
             why="Stabilność cen kosztem krótkookresowego wzrostu i zatrudnienia."),
          W("Rząd zwiększa deficyt, a bank centralny podnosi stopy. Jaki to policy mix?",
            "Ekspansywna polityka fiskalna i restrykcyjna pieniężna", "Obie ekspansywne", "Obie restrykcyjne",
            why="Polityki działają w przeciwnych kierunkach."),
          PF("Płaca minimalna jest przykładem instrumentu administracyjnego (regulacji).", True,
             why="Państwo ustala nakaz – minimalny poziom wynagrodzenia."),
          M("Które instrumenty należą do polityki fiskalnej?",
            ["Stawki podatków", "Wydatki budżetu", "Stopa referencyjna", "Transfery socjalne"],
            [0, 1, 3],
            why="Stopa referencyjna to instrument polityki pieniężnej."),
          W("Dlaczego czworokąt nazywa się „magiczny”?",
            "Bo osiągnięcie wszystkich celów naraz wymagałoby niemal magii – cele są w konflikcie", "Bo nikt go nie stosuje", "Bo dotyczy tylko inflacji",
            why="Pokazuje trudność godzenia celów."),
      ],
      calc=[
          LB("Wskaźnik niedoli Okuna = inflacja + stopa bezrobocia. Inflacja 4,0%, bezrobocie 5,8%. Ile wynosi?",
             9.8, "4.0+5.8", ["4,0 + 5,8 = 9,8"], unit=""),
          LB("Cel: wzrost 3%, inflacja 2,5%, bezrobocie 5%, saldo CA 0% PKB. Wynik: wzrost 2%, inflacja 4%, bezrobocie 5,8%, CA −1%. Ile wynosi suma odchyleń bezwzględnych (p.p.)?",
             4.3, "abs(2-3)+abs(4-2.5)+abs(5.8-5)+abs(-1-0)", ["1 + 1,5 + 0,8 + 1 = 4,3 p.p."], unit="p.p."),
          LB("Wydatki publiczne 1900 mld zł, PKB 3900 mld zł. Jaki jest udział wydatków publicznych w PKB (%)?",
             48.72, "1900/3900*100", ["1900 / 3900 ≈ 48,7% (dane umowne)"], unit="%", tol=0.02),
          LB("Ekspansja fiskalna zwiększa PKB o 1,2%, a zacieśnienie monetarne obniża o 0,8%. Ile wynosi efekt netto policy mix (%)?",
             0.4, "1.2-0.8", ["1,2 − 0,8 = 0,4%"], unit="%"),
          LB("Inflacja 4,0%, cel 2,5%. O ile p.p. inflacja przekracza cel?",
             1.5, "4.0-2.5", ["4,0 − 2,5 = 1,5 p.p."], unit="p.p."),
          LB("Bezrobocie 5,8%, naturalne 5%. Ile wynosi luka PKB według Okuna (c = 2, %)?",
             -1.6, "-2*(5.8-5)", ["−2 · 0,8 = −1,6%"], unit="%"),
      ],
      case=[
          PR("We wrześniu 2026 r. inflacja CPI w Polsce wyniosła 4,0% r/r (szybki szacunek GUS), stopa bezrobocia rejestrowanego pod koniec sierpnia – 5,8%, a RPP na posiedzeniu 6–7 października pozostawiła stopę referencyjną na poziomie 3,75%. Deficyt sektora instytucji rządowych i samorządowych w 2025 r. wyniósł 7,3% PKB.",
             W("Który cel z magicznego czworokąta jest najbardziej zagrożony według tych danych?",
               "Stabilność cen (inflacja powyżej celu 2,5% ± 1 p.p.)", "Wysokie zatrudnienie – bezrobocie jest rekordowe", "Żaden",
               why="4,0% przekracza górną granicę pasma celu NBP."),
             W("Jak można opisać policy mix?",
               "Ekspansywna polityka fiskalna (wysoki deficyt) przy umiarkowanie restrykcyjnej polityce pieniężnej", "Obie polityki bardzo restrykcyjne", "Obie polityki neutralne",
               why="Wysoki deficyt pobudza popyt, a stopy realne są dodatnie."),
             PF("Wysoki deficyt budżetowy może utrudniać bankowi centralnemu sprowadzenie inflacji do celu.", True,
                why="Pobudza popyt, zwiększając presję cenową."),
          ),
          PR("Rząd chce jednocześnie szybko obniżyć bezrobocie w regionach, utrzymać niską inflację i ograniczyć deficyt. Doradca proponuje: szkolenia zawodowe, ulgi dla firm inwestujących w regionach o wysokim bezrobociu i stopniową konsolidację wydatków bieżących.",
             W("Dlaczego doradca proponuje narzędzia podażowe (szkolenia, inwestycje), a nie silne pobudzenie popytu?",
               "Mogą obniżyć bezrobocie bez dużej presji inflacyjnej i deficytu", "Bo są zawsze darmowe", "Bo popyt nie wpływa na zatrudnienie",
               why="Zmniejszają bezrobocie strukturalne przy mniejszym ryzyku inflacji."),
             M("Które cele próbuje pogodzić rząd?",
               ["Wysokie zatrudnienie", "Stabilność cen", "Maksymalizacja eksportu za wszelką cenę", "Zdrowe finanse publiczne"],
               [0, 1, 3],
               why="Eksport nie był celem w tym przypadku."),
             PF("Dobór instrumentów do celu (np. szkolenia na bezrobocie strukturalne) zwiększa skuteczność polityki.", True,
                why="Każdy instrument najlepiej działa na „swój” cel (reguła Tinbergena)."),
          ),
      ]),

    L(2, "Stabilizacja koniunktury: automaty i decyzje",
      "Rozumieć politykę stabilizacyjną, różnicę między automatycznymi stabilizatorami a polityką dyskrecjonalną, politykę ekspansywną i restrykcyjną oraz opóźnienia polityki.",
      ["Polityka stabilizacyjna", "Automatyczne stabilizatory", "Polityka dyskrecjonalna", "Polityka ekspansywna i restrykcyjna", "Opóźnienia polityki gospodarczej"],
      [S305, S306, S304],
      explain=[
          K("Polityka stabilizacyjna",
            "Ma łagodzić wahania koniunktury: w recesji pobudzać popyt (polityka ekspansywna – niższe podatki, wyższe wydatki, niższe stopy), w przegrzaniu go hamować (polityka restrykcyjna). Celem jest utrzymanie produkcji blisko potencjału i stabilnych cen.",
            g=G("adas", AD=1)),
          K("Automatyczne stabilizatory",
            "Elementy systemu, które same reagują na cykl bez nowych decyzji: podatek dochodowy (w recesji dochody spadają, więc podatki też – zwłaszcza przy progresji), zasiłki dla bezrobotnych (rosną w recesji), VAT i akcyza. Działają szybko i bez opóźnień decyzyjnych."),
          W("Który mechanizm jest automatycznym stabilizatorem?",
            "Zasiłki dla bezrobotnych, które rosną w recesji", "Ustawa o nowym programie budowy dróg", "Decyzja RPP o obniżce stóp",
            why="Działa bez nowej decyzji – sam reaguje na koniunkturę."),
          K("Polityka dyskrecjonalna",
            "Celowe, nowe decyzje: pakiety stymulacyjne, zmiana stawek podatków, programy inwestycyjne, zmiana stóp procentowych. Może być silniejsza niż stabilizatory, ale wymaga czasu i bywa źle wyczuta."),
          K("Opóźnienia",
            "Wewnętrzne: rozpoznania (dane spływają z opóźnieniem), decyzyjne (debata, ustawa), wdrożenia. Zewnętrzne: czas, zanim działanie wpłynie na gospodarkę (dla polityki pieniężnej zwykle kilka kwartałów). Opóźnienia grożą tym, że bodziec zadziała, gdy recesja już minie – polityka staje się procykliczna."),
          PF("Polityka fiskalna zwykle ma dłuższe opóźnienie decyzyjne niż polityka pieniężna.", True,
             why="Zmiany budżetu wymagają procesu ustawodawczego; RPP decyduje na posiedzeniu."),
      ],
      mech=[
          LN("Ułóż działanie stabilizatorów w recesji.",
             ["Gospodarka wchodzi w recesję", "Dochody i zatrudnienie spadają", "Wpływy z podatków maleją, a wydatki na zasiłki rosną", "Deficyt rośnie bez nowych decyzji", "Spadek dochodu rozporządzalnego jest mniejszy – recesja łagodnieje"],
             why="Stabilizatory amortyzują spadek popytu."),
          KT("Automatyczny stabilizator czy polityka dyskrecjonalna?",
             {"Automatyczny": ["Progresywny podatek dochodowy", "Zasiłek dla bezrobotnych", "Spadek wpływów z VAT w recesji"],
              "Dyskrecjonalna": ["Pakiet antykryzysowy uchwalony przez Sejm", "Obniżka stóp przez RPP", "Nowy program inwestycji publicznych"]},
             why="Automat działa sam, dyskrecja wymaga decyzji."),
          WY("W przegrzanej gospodarce rząd podnosi podatki i tnie wydatki. Co pokazuje model AD-AS?",
             G("adas", AD=-1), "AD w lewo – inflacja i produkcja spadają", "AD w prawo", "SRAS w prawo", "LRAS w lewo",
             why="Polityka restrykcyjna ogranicza popyt."),
          W("Co to jest opóźnienie rozpoznania?",
            "Czas, zanim decydenci zorientują się, że gospodarka zwalnia", "Czas uchwalania ustawy", "Czas działania stopy na kredyty",
            why="Dane o PKB są publikowane z opóźnieniem i rewidowane."),
          PF("Silniejsza progresja podatkowa wzmacnia działanie automatycznych stabilizatorów.", True,
             why="Podatki spadają (i rosną) bardziej niż proporcjonalnie do dochodów."),
          M("Jakie są ryzyka polityki dyskrecjonalnej?",
            ["Bodziec zadziała za późno", "Trudno go wycofać po ustaniu recesji", "Zawsze jest zbyt mały", "Może służyć celom wyborczym"],
            [0, 1, 3],
            why="Wielkość bodźca nie jest z góry za mała."),
      ],
      calc=[
          LB("Dochody spadają o 100 mld zł, efektywna stawka podatków i składek od dochodu wynosi 35%. O ile spadają wpływy (mld zł)?",
             35, "0.35*100", ["0,35 · 100 = 35 mld zł"], unit="mld zł"),
          LB("O ile w tej sytuacji spada dochód rozporządzalny (mld zł)?",
             65, "100-35", ["100 − 35 = 65 mld zł – podatki zamortyzowały 35"], unit="mld zł"),
          LB("Dodatkowo zasiłki rosną o 8 mld zł. Ile wynosi łączne automatyczne pogorszenie salda budżetu (mld zł)?",
             43, "35+8", ["35 + 8 = 43 mld zł"], unit="mld zł"),
          LB("Opóźnienia: rozpoznanie 2 kwartały, decyzja 3 kwartały, działanie 2 kwartały. Po ilu kwartałach od początku recesji bodziec zacznie działać w pełni?",
             7, "2+3+2", ["2 + 3 + 2 = 7 kwartałów"], unit="kw."),
          LB("Recesja trwa średnio 4 kwartały. Ile kwartałów bodziec działa już po jej zakończeniu?",
             3, "7-4", ["7 − 4 = 3 kwartały – ryzyko procykliczności"], unit="kw."),
          LB("Mnożnik wydatkowy 1,5, luka PKB −3% przy PKB 4000 mld zł. Jakie dodatkowe wydatki zamkną lukę (mld zł)?",
             80, "0.03*4000/1.5", ["Luka: 120 mld zł", "120 / 1,5 = 80 mld zł"], unit="mld zł"),
      ],
      case=[
          PR("W czasie kryzysu 2009 r. w wielu krajach europejskich deficyty budżetowe gwałtownie wzrosły, choć rządy uchwaliły stosunkowo niewielkie pakiety stymulacyjne. Duża część wzrostu deficytów wynikała ze spadku wpływów podatkowych i wzrostu wydatków socjalnych.",
             W("Co głównie zwiększyło deficyty?",
               "Automatyczne stabilizatory", "Wyłącznie decyzje o nowych programach", "Wzrost stóp procentowych",
               why="Spadek dochodów podatkowych i wzrost zasiłków działały bez nowych decyzji."),
             W("Czy rosnący deficyt w recesji jest zawsze błędem polityki?",
               "Nie – częściowo to pożądane działanie stabilizatorów", "Tak, zawsze", "Tak, bo zwiększa inflację w recesji",
               why="Stabilizatory łagodzą spadek popytu."),
             PF("Deficyt strukturalny (skorygowany o cykl) lepiej pokazuje intencje polityki fiskalnej niż deficyt nominalny.", True,
                why="Usuwa wpływ automatycznych stabilizatorów."),
          ),
          PR("Rząd w recesji uchwala pakiet inwestycji w drogi. Przygotowanie projektów i przetargów trwa dwa lata. Gdy budowy ruszają pełną parą, gospodarka jest już w fazie szybkiego wzrostu, a firmy budowlane zgłaszają brak pracowników.",
             W("Jaki problem polityki ilustruje ten przykład?",
               "Opóźnienia – bodziec zadziałał procyklicznie", "Pułapkę płynności", "Prawo Saya",
               why="Wydatki trafiły na okres ożywienia, a nie recesji."),
             W("Jakie narzędzie fiskalne działa szybciej w recesji?",
               "Automatyczne stabilizatory i transfery dla gospodarstw", "Wieloletnie inwestycje infrastrukturalne", "Reforma konstytucji",
               why="Transfery od razu zwiększają dochód rozporządzalny."),
             PF("Przygotowanie „gotowych do realizacji” projektów przed kryzysem może skrócić opóźnienia.", True,
                why="Skraca etap wdrożenia."),
          ),
      ]),

    L(3, "Reguły czy uznaniowość?",
      "Rozumieć problem niespójności czasowej, argumenty za regułami i za uznaniowością oraz główne debaty o polityce makroekonomicznej.",
      ["Reguły a uznaniowość (niespójność czasowa)", "Debaty o polityce makroekonomicznej (Mankiw)", "Polityka dyskrecjonalna"],
      [NOB04, S285, S263],
      explain=[
          K("Niespójność czasowa",
            "Kydland i Prescott (1977): polityka, która jest optymalna dziś, może przestać być optymalna jutro – i decydent ma pokusę zmienić zdanie. Przykład: bank centralny obiecuje niską inflację, ale gdy płace są już ustalone, kusi go „niespodzianka inflacyjna”, by obniżyć bezrobocie. Ludzie to przewidują, więc oczekują wyższej inflacji – efekt: wyższa inflacja bez korzyści w zatrudnieniu."),
          K("Rozwiązania",
            "Reguły (np. cel inflacyjny, reguła wydatkowa), niezależny bank centralny, delegowanie polityki „konserwatywnemu” prezesowi (Rogoff), reputacja budowana latami. Wiarygodność obniża koszty osiągania celów."),
          W("Na czym polega problem niespójności czasowej?",
            "Decydent ma pokusę odejść od wcześniejszej obietnicy, a ludzie to przewidują", "Polityka działa z opóźnieniem", "Dane są publikowane późno",
            why="Brak wiarygodności sprawia, że obietnice nie kształtują oczekiwań."),
          K("Debaty (za Mankiwem)",
            "Mankiw przedstawia spory: czy polityka powinna stabilizować gospodarkę; czy rząd ma walczyć z recesją wydatkami czy obniżkami podatków; czy polityka pieniężna ma opierać się na regułach czy uznaniowości; czy bank centralny ma dążyć do zerowej inflacji; czy budżet ma być zrównoważony; czy reformować podatki, by zachęcać do oszczędzania."),
          K("Argumenty uznaniowości",
            "Reguły są sztywne – nie przewidują wyjątkowych szoków (pandemia, wojna). Dlatego stosuje się reguły z klauzulami wyjścia: zasada jest jasna, ale w nadzwyczajnych sytuacjach dopuszcza się odstępstwa."),
          PF("Kydland i Prescott otrzymali Nagrodę Nobla m.in. za analizę spójności czasowej polityki gospodarczej.", True,
             why="Nagroda z 2004 r."),
      ],
      mech=[
          LN("Ułóż skutki braku wiarygodności banku centralnego.",
             ["Bank obiecuje niską inflację", "Ludzie wiedzą, że ma pokusę ją podnieść", "Oczekiwania inflacyjne rosną", "Płace i ceny rosną szybciej", "Inflacja jest wyższa bez spadku bezrobocia"],
             why="To pułapka niespójności czasowej."),
          KT("Reguła czy uznaniowość?",
             {"Reguła": ["Stabilizująca reguła wydatkowa", "Bezpośredni cel inflacyjny", "Konstytucyjny limit długu"],
              "Uznaniowość": ["Jednorazowy pakiet antykryzysowy", "Nadzwyczajne wsparcie dla branży dotkniętej powodzią"]},
             why="Reguły wiążą decydentów, uznaniowość daje swobodę."),
          W("Dlaczego wiele reguł fiskalnych ma klauzule wyjścia?",
            "By pozwolić na reakcję w nadzwyczajnych sytuacjach bez porzucania reguły", "By można je było ignorować zawsze", "Bo reguły są zakazane",
            why="Łączą wiarygodność z elastycznością."),
          PF("Niezależność banku centralnego jest jedną z odpowiedzi na problem niespójności czasowej.", True,
             why="Politycy nie mogą wymuszać „niespodzianek inflacyjnych”."),
          M("Które argumenty przemawiają za regułami?",
            ["Wiarygodność i przewidywalność", "Ograniczenie pokus politycznych", "Pełna swoboda reakcji na każdy szok", "Zakotwiczenie oczekiwań"],
            [0, 1, 3],
            why="Pełna swoboda to argument za uznaniowością."),
          W("Co jest przykładem „przywiązania się do masztu” (jak Odyseusz)?",
            "Wpisanie limitu długu do konstytucji", "Coroczna zmiana celu inflacyjnego", "Brak budżetu",
            why="Trudno zmienialna reguła chroni przed pokusą."),
      ],
      calc=[
          LB("Model Barro–Gordona (uproszczony): obiecana inflacja 2%, ludzie oczekują jednak 5%, bank „niespodziewanie” ustala 2%. Ile wynosi niespodzianka (π − πᵉ, p.p.)?",
             -3, "2-5", ["2 − 5 = −3 p.p. – ujemna niespodzianka obniża produkcję"], unit="p.p."),
          LB("Krzywa Phillipsa: u = 5 − 0,5(π − πᵉ). Przy π = 2, πᵉ = 5 ile wynosi bezrobocie?",
             6.5, "5-0.5*(2-5)", ["u = 5 + 1,5 = 6,5%"], unit="%"),
          LB("Wiarygodny bank: πᵉ = π = 2%. Ile wynosi bezrobocie w tym modelu?",
             5, "5-0.5*(2-2)", ["Brak niespodzianki: u = 5%"], unit="%"),
          LB("Niewiarygodny bank: równowaga przy π = πᵉ = 6%. O ile p.p. inflacja jest wyższa niż u wiarygodnego banku?",
             4, "6-2", ["6 − 2 = 4 p.p. – bez korzyści dla bezrobocia (u = 5% w obu przypadkach)"], unit="p.p."),
          LB("Reguła wydatkowa: wydatki rosną o średnie tempo PKB nominalnego 6% pomniejszone o korektę 1 p.p. Wydatki 1000 mld zł. Jaki jest limit wydatków na kolejny rok (mld zł)?",
             1050, "1000*1.05", ["1000 · (1 + 0,06 − 0,01) = 1050 mld zł (dane umowne)"], unit="mld zł"),
          LB("Rząd przekracza regułę o 15 mld zł. Jaki to procent limitu?",
             1.43, "15/1050*100", ["15 / 1050 ≈ 1,43%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Rząd zapowiada, że nie będzie ratował banków, które ryzykują zbyt mocno. Gdy jednak duży bank staje na krawędzi upadłości, rząd go ratuje, by uniknąć paniki. Inwestorzy zapamiętują tę decyzję.",
             W("Jaki problem ilustruje ten przypadek?",
               "Niespójność czasową i pokusę nadużycia", "Paradoks Leontiefa", "Krzywą J",
               why="Ex ante obietnica „nie pomożemy”, ex post opłaca się pomóc."),
             W("Jaki będzie długookresowy skutek?",
               "Banki będą ryzykować więcej, licząc na ratunek", "Banki staną się ostrożniejsze", "Brak skutków",
               why="Obietnica przestaje być wiarygodna."),
             PF("Reguły typu „bail-in” (straty najpierw ponoszą akcjonariusze i wierzyciele) mają zwiększyć wiarygodność takich obietnic.", True,
                why="Ograniczają ratowanie banków z pieniędzy podatników."),
          ),
          PR("W 2020 r. Unia Europejska uruchomiła ogólną klauzulę wyjścia z Paktu Stabilności i Wzrostu, pozwalając państwom na duże deficyty w czasie pandemii. Po kryzysie reguły przywrócono w zreformowanej formie.",
             W("Jaką zaletę reguł z klauzulą wyjścia pokazuje ten przypadek?",
               "Elastyczność w nadzwyczajnych sytuacjach bez porzucania reguł na stałe", "Całkowity brak reguł", "Zakaz deficytów w kryzysie",
               why="Reguły zawieszono czasowo, a potem przywrócono."),
             W("Jakie ryzyko wiąże się z klauzulą wyjścia?",
               "Zbyt częste lub zbyt długie korzystanie z niej osłabia wiarygodność reguły", "Brak ryzyka", "Natychmiastowa hiperinflacja",
               why="Reguła, którą łatwo zawiesić, przestaje dyscyplinować."),
             PF("Ogólna klauzula wyjścia dotyczy sytuacji poważnego spowolnienia w całej UE lub strefie euro.", True,
                why="Uruchomiono ją po raz pierwszy w 2020 r."),
          ),
      ]),

    L(4, "Rola państwa: od interwencjonizmu do strategii rozwoju",
      "Rozumieć argumenty za i przeciw interwencji państwa, dobra społecznie pożądane, politykę wybierania zwycięzców, planowanie w gospodarce rynkowej, strategie rozwoju i doświadczenie etatyzmu II RP.",
      ["Rola państwa w gospodarce", "Interwencjonizm państwowy", "Dobra społecznie pożądane (merit goods)", "Picking the winners", "Planowanie gospodarcze w gospodarce rynkowej", "Strategie rozwoju kraju", "Etatyzm i polityka gospodarcza II RP"],
      [S132, S14, SOR],
      explain=[
          K("Funkcje państwa (Musgrave)",
            "Alokacyjna – dostarczanie dóbr publicznych i korygowanie zawodności rynku (efekty zewnętrzne, monopol, asymetria informacji). Redystrybucyjna – zmiana podziału dochodów (podatki progresywne, transfery). Stabilizacyjna – łagodzenie wahań koniunktury."),
          K("Dobra społecznie pożądane",
            "Merit goods (Musgrave) to dobra, których – zdaniem państwa – ludzie konsumowaliby zbyt mało, gdyby decydowali sami: edukacja, szczepienia, opieka zdrowotna, kultura. Państwo je finansuje, dotuje lub nakazuje (obowiązek szkolny). Przeciwieństwo: demerit goods (alkohol, tytoń) – wysokie akcyzy."),
          W("Dlaczego państwo wprowadza obowiązek szkolny?",
            "Edukacja jest dobrem społecznie pożądanym – sama decyzja jednostek dałaby jej za mało", "Bo edukacja jest dobrem prywatnym bez korzyści dla innych", "Bo zwiększa inflację",
            why="Korzyści z edukacji wykraczają poza jednostkę, a ludzie mogą je niedoceniać."),
          K("Picking the winners i planowanie",
            "„Wybieranie zwycięzców” – państwo wskazuje i wspiera konkretne branże lub firmy (dotacje, ulgi, kredyty). Sukcesy (np. Korea Płd.) i porażki (przegrane inwestycje) – ryzyko, że urzędnicy gorzej niż rynek ocenią przyszłość, i lobbing. W gospodarce rynkowej planowanie ma charakter indykatywny (wskazujący), np. strategie rozwoju kraju (Strategia na rzecz Odpowiedzialnego Rozwoju) czy planowanie przestrzenne."),
          K("Etatyzm w II RP",
            "W latach 30. XX w. państwo polskie silnie zwiększyło udział w gospodarce: państwowe przedsiębiorstwa, banki (BGK, PKO), monopole (tytoń, spirytus, zapałki), a w latach 1936–1939 budowa Centralnego Okręgu Przemysłowego (COP) za ministra Eugeniusza Kwiatkowskiego."),
          PF("Planowanie indykatywne wskazuje kierunki rozwoju, ale nie nakazuje firmom, co mają produkować.", True,
             why="W odróżnieniu od planowania nakazowego w gospodarce centralnie planowanej."),
      ],
      mech=[
          KT("Która funkcja państwa (Musgrave)?",
             {"Alokacyjna": ["Finansowanie obrony narodowej", "Podatek od emisji CO₂"],
              "Redystrybucyjna": ["Progresywny podatek dochodowy", "Zasiłki dla najuboższych"],
              "Stabilizacyjna": ["Pakiet antykryzysowy w recesji", "Automatyczne stabilizatory"]},
             why="Trzy funkcje sektora publicznego."),
          LN("Ułóż ryzyka polityki „wybierania zwycięzców”.",
             ["Rząd wybiera branżę do wsparcia", "Firmy z branży otrzymują dotacje i ochronę", "Zaczynają zabiegać o dalsze wsparcie zamiast o efektywność", "Rynek zmienia się inaczej, niż przewidziano", "Wsparcie trwa mimo braku sukcesu"],
             why="Ryzyko pomyłki i lobbingu."),
          W("Które dobro jest przykładem demerit good?",
            "Papierosy", "Szczepionki", "Edukacja",
            why="Państwo zniechęca do ich konsumpcji akcyzą."),
          PF("Centralny Okręg Przemysłowy był przykładem polityki etatystycznej II RP.", True,
             why="Państwo inwestowało w przemysł ciężki i zbrojeniowy."),
          M("Jakie argumenty uzasadniają interwencję państwa?",
            ["Efekty zewnętrzne", "Dobra publiczne", "Chęć zastąpienia rynku we wszystkim", "Asymetria informacji"],
            [0, 1, 3],
            why="Zawodności rynku uzasadniają interwencję – ale nie całkowite zastąpienie rynku."),
          W("Czym różni się planowanie w gospodarce rynkowej od centralnego planowania?",
            "Ma charakter wskazujący i koordynujący, a nie nakazowy", "Niczym", "Obejmuje ceny wszystkich dóbr",
            why="Firmy zachowują swobodę decyzji."),
      ],
      calc=[
          LB("Państwo dopłaca do szczepionki 60 zł z ceny 100 zł. Ile płaci pacjent (zł)?",
             40, "100-60", ["100 − 60 = 40 zł"], unit="zł"),
          LB("Popyt na szczepienia: Q = 1000 − 8P (tys.). Ile osób szczepi się przy cenie 100 zł, a ile przy 40 zł (podaj różnicę, tys.)?",
             480, "(1000-8*40)-(1000-8*100)", ["Przy 100 zł: 200 tys.", "Przy 40 zł: 680 tys.", "Różnica: 480 tys."], unit="tys."),
          LB("Ile kosztuje dopłata (60 zł · 680 tys., mln zł)?",
             40.8, "60*680/1000", ["60 · 680 tys. = 40,8 mln zł"], unit="mln zł"),
          LB("Akcyza na papierosy: 15 zł za paczkę, popyt spada z 100 mln do 80 mln paczek. Ile wynoszą wpływy z akcyzy (mln zł)?",
             1200, "15*80", ["15 · 80 = 1200 mln zł"], unit="mln zł"),
          LB("Państwo dotuje 10 firm po 50 mln zł; 3 odnoszą sukces i każda przynosi 200 mln zł korzyści. Ile wynosi korzyść netto programu (mln zł)?",
             100, "3*200-10*50", ["600 − 500 = 100 mln zł"], unit="mln zł"),
          LB("COP: przyjmijmy nakłady 2,4 mld zł rozłożone równo na lata 1936–1939 (4 lata). Ile rocznie (mln zł)?",
             600, "2400/4", ["2400 / 4 = 600 mln zł (dane umowne)"], unit="mln zł"),
      ],
      case=[
          PR("Korea Południowa w latach 70. XX w. kierowała tani kredyt do wybranych branż: stoczniowej, stalowej, chemicznej i elektronicznej. Część z nich stała się światowymi liderami. W innych krajach podobne programy kończyły się nieefektywnymi firmami utrzymywanymi przez budżet.",
             W("Jak nazywa się taka polityka?",
               "Wybieranie zwycięzców (polityka przemysłowa sektorowa)", "Leseferyzm", "Konsensus waszyngtoński",
               why="Państwo wskazuje branże do wsparcia."),
             M("Co mogło sprzyjać sukcesowi Korei?",
               ["Nacisk na eksport i konkurencję na rynkach światowych", "Inwestycje w edukację", "Brak jakichkolwiek kryteriów sukcesu", "Wycofywanie wsparcia dla firm bez wyników eksportowych"],
               [0, 1, 3],
               why="Dyscyplina rynków eksportowych ograniczała marnotrawstwo."),
             PF("Ta sama polityka bez mechanizmów kontroli efektów może prowadzić do marnotrawstwa i lobbingu.", True,
                why="Firmy zabiegają o wsparcie zamiast o efektywność."),
          ),
          PR("Rząd przyjmuje strategię rozwoju na 10 lat: wskazuje priorytety (innowacje, transport, energetyka), ale nie nakazuje firmom produkcji. Fundusze publiczne i europejskie są kierowane zgodnie z tymi priorytetami.",
             W("Jaki to typ planowania?",
               "Indykatywne (wskazujące)", "Nakazowe", "Brak planowania",
               why="Strategia kieruje środki i sygnalizuje kierunki."),
             W("Czym są takie strategie w Polsce?",
               "Dokumentami wyznaczającymi kierunki polityki rozwoju i wydatkowania środków", "Ustawami nakazującymi ceny", "Planami pięcioletnimi PRL",
               why="Np. Strategia na rzecz Odpowiedzialnego Rozwoju."),
             PF("Fundusze UE są w dużej mierze programowane zgodnie z krajowymi i unijnymi strategiami rozwoju.", True,
                why="Programy operacyjne wynikają ze strategii."),
          ),
      ]),

    L(5, "Polityka oczami ekonomisty: wybór publiczny i demokracja",
      "Rozumieć teorię wyboru publicznego (Buchanan) i ekonomiczną teorię demokracji (Downs): zawodności państwa, grupy interesu, logrolling, racjonalną ignorancję wyborców i zachowanie partii.",
      ["Teoria wyboru publicznego (public choice)", "Ekonomiczna teoria demokracji", "Interwencjonizm państwowy", "Rola państwa w gospodarce"],
      [NOB86, S132],
      explain=[
          K("Wybór publiczny",
            "James Buchanan (Nobel 1986) i Gordon Tullock: politycy, urzędnicy i wyborcy kierują się – jak uczestnicy rynku – własnym interesem. Polityk chce być wybrany, urzędnik – zwiększyć budżet swojej agencji, grupy interesu – uzyskać przywileje. Stąd zawodność państwa: interwencja może pogorszyć sytuację, nawet gdy rynek zawodzi."),
          K("Grupy interesu i pogoń za rentą",
            "Korzyści z przywileju (cło, dotacja) są skoncentrowane w małej grupie, a koszty rozproszone na wielu podatników i konsumentów. Mała grupa łatwo się organizuje, więc lobbing jest skuteczny (Olson). Pogoń za rentą (rent seeking) – zużywanie zasobów na zdobywanie przywilejów zamiast na produkcję."),
          W("Dlaczego producenci cukru łatwiej uzyskują cło niż konsumenci jego zniesienie?",
            "Korzyści są skoncentrowane w małej grupie, a koszty rozproszone", "Bo konsumentów jest mniej", "Bo cła są zawsze korzystne",
            why="Każdy konsument traci niewiele, więc nie opłaca mu się walczyć."),
          K("Ekonomiczna teoria demokracji (Downs, 1957)",
            "Partie, jak firmy, maksymalizują głosy, a nie dobro wspólne. W systemie dwupartyjnym przesuwają się ku środkowi – ku wyborcy medianowemu. Wyborcy są racjonalnie nieświadomi: zdobywanie wiedzy o polityce kosztuje więcej, niż daje jeden głos (paradoks głosowania)."),
          K("Logrolling i krótkowzroczność",
            "Logrolling – handel głosami („poprzyj mój projekt, ja poprę twój”), który przepycha wydatki korzystne dla wąskich grup. Krótki horyzont kadencji zachęca do decyzji z szybkimi korzyściami i odroczonymi kosztami (deficyty, niedoinwestowanie)."),
          PF("Według teorii wyboru publicznego urzędnicy zawsze dążą wyłącznie do dobra wspólnego.", False,
             why="Zakłada się, że kierują się także interesem własnym."),
      ],
      mech=[
          LN("Ułóż mechanizm pogoni za rentą.",
             ["Branża chce ochrony przed importem", "Finansuje lobbing", "Politycy wprowadzają cło", "Branża zyskuje, konsumenci płacą więcej", "Zasoby zużyte na lobbing nie tworzą wartości"],
             why="Koszty przywileju i lobbingu ponosi społeczeństwo."),
          KT("Zawodność rynku czy zawodność państwa?",
             {"Zawodność rynku": ["Zanieczyszczenie powietrza przez fabrykę", "Monopol naturalny", "Brak prywatnej podaży latarni morskich"],
              "Zawodność państwa": ["Dotacje dla branży z silnym lobby", "Logrolling w parlamencie", "Rozrost biurokracji"]},
             why="Obie zawodności mogą występować jednocześnie."),
          W("Ku czemu według Downsa zmierzają programy dwóch partii?",
            "Ku preferencjom wyborcy medianowego", "Ku skrajnościom", "Ku programom zagranicznym",
            why="W centrum jest najwięcej głosów."),
          PF("Racjonalna ignorancja wyborców wynika z tego, że koszt zdobywania informacji przewyższa korzyść z jednego głosu.", True,
             why="Pojedynczy głos rzadko rozstrzyga wybory."),
          M("Co według teorii wyboru publicznego może ograniczać zawodność państwa?",
            ["Reguły konstytucyjne ograniczające deficyt", "Przejrzystość i konkurencja w przetargach", "Większe uprawnienia dla grup lobbingowych", "Niezależne instytucje (np. bank centralny)"],
            [0, 1, 3],
            why="Więcej władzy dla lobby zwiększa pogoń za rentą."),
          W("Czym jest logrolling?",
            "Wzajemnym popieraniem projektów przez polityków", "Prywatyzacją", "Rodzajem podatku",
            why="„Ty poprzesz mój projekt, ja twój”."),
      ],
      calc=[
          LB("Cło na cukier daje 10 producentom łącznie 200 mln zł zysku, a 20 mln konsumentów płaci łącznie 300 mln zł więcej. Ile zyskuje przeciętny producent (mln zł)?",
             20, "200/10", ["200 / 10 = 20 mln zł"], unit="mln zł"),
          LB("Ile traci przeciętny konsument (zł)?",
             15, "300000000/20000000", ["300 mln / 20 mln = 15 zł"], unit="zł"),
          LB("Ile wynosi strata netto dla społeczeństwa (mln zł)?",
             100, "300-200", ["300 − 200 = 100 mln zł"], unit="mln zł"),
          LB("Producenci wydają na lobbing 60 mln zł. Ile wynosi łączny koszt społeczny (strata netto + lobbing, mln zł)?",
             160, "100+60", ["100 + 60 = 160 mln zł"], unit="mln zł"),
          LB("Wyborcy: preferowane wydatki (mld zł) 10, 20, 30, 40, 50. Jaki poziom wybierze wyborca medianowy?",
             30, "(10+20+30+40+50)/5", ["Mediana z pięciu uporządkowanych wartości – trzecia: 30 (tu równa średniej)"], unit="mld zł"),
          LB("Szansa, że jeden głos rozstrzygnie wybory, wynosi 1 na 10 mln, a korzyść z wygranej preferowanej partii to 5000 zł. Ile wynosi oczekiwana korzyść z głosu (zł)?",
             0.0005, "5000/10000000", ["5000 / 10 000 000 = 0,0005 zł – paradoks głosowania"], unit="zł"),
      ],
      case=[
          PR("Parlament rozważa dopłaty do produkcji określonego surowca. Projekt popiera kilka firm z tej branży i związki zawodowe z regionu. Koszt dla budżetu to kilka złotych rocznie na każdego podatnika, więc mało kto się sprzeciwia.",
             W("Jak teoria wyboru publicznego wyjaśnia, że projekt może przejść mimo straty netto dla społeczeństwa?",
               "Korzyści skoncentrowane, koszty rozproszone – zwolennicy są lepiej zorganizowani", "Bo wszyscy zyskują", "Bo podatki nie istnieją",
               why="Logika działań zbiorowych (Olson)."),
             W("Jaki mechanizm parlamentarny mógłby pomóc przepchnąć projekt?",
               "Logrolling – poparcie w zamian za poparcie innego projektu", "Referendum", "Niezależny bank centralny",
               why="Handel głosami między posłami."),
             PF("Ocena skutków regulacji i jawność lobbingu mogą ograniczać takie zjawiska.", True,
                why="Ujawniają koszty i interesy."),
          ),
          PR("W dwupartyjnym systemie obie partie przed wyborami zbliżają swoje programy gospodarcze do siebie, obiecując podobne podatki i wydatki. Komentatorzy narzekają, że „nie ma wyboru”.",
             W("Którą teorię ilustruje ten przypadek?",
               "Twierdzenie o wyborcy medianowym (Downs)", "Krzywą Laffera", "Model Solowa",
               why="Partie zbliżają się do środka rozkładu preferencji."),
             W("Kiedy ten mechanizm słabnie?",
               "Gdy jest wiele partii lub wyborcy nie głosują (np. skrajni zostają w domu)", "Gdy wyborców jest więcej", "Nigdy",
               why="Założenia modelu Downsa nie zawsze są spełnione."),
             PF("Według Downsa partie traktują program jako narzędzie zdobywania głosów.", True,
                why="Jak firmy oferujące produkt klientom."),
          ),
      ]),
    L(6, "Debaty o polityce makroekonomicznej: stabilizacja, reguły, budżet i podatki",
      "Umieć przedstawić argumenty obu stron w głównych sporach opisanych przez Mankiwa: czy państwo powinno stabilizować koniunkturę, czy bank centralny powinien kierować się regułą, czy budżet powinien być zrównoważony i czy system podatkowy powinien sprzyjać oszczędzaniu (podatek konsumpcyjny).",
      ["Debaty o polityce makroekonomicznej (Mankiw)", "Podatek konsumpcyjny (reforma podatkowa sprzyjająca oszczędzaniu)", "Reguły a uznaniowość (niespójność czasowa)", "Opóźnienia polityki gospodarczej", "Automatyczne stabilizatory"],
      [S306, S307, S314, S285],
      explain=[
          K("Debata 1: stabilizować koniunkturę?",
            "Za: recesje marnują zasoby i krzywdzą ludzi; polityka pieniężna i fiskalna może łagodzić wahania popytu, a automatyczne stabilizatory działają bez decyzji. Przeciw: polityka działa z długimi i zmiennymi opóźnieniami (rozpoznanie, decyzja, efekt), prognozy są niepewne, więc „dociskanie gazu” może przyjść za późno i wzmacniać wahania."),
          K("Debata 2: reguła czy uznaniowość?",
            "Za regułą (np. cel inflacyjny, reguła Taylora): ogranicza niekompetencję i nadużycia władzy oraz problem niespójności czasowej – zapowiedzi są wiarygodne. Za uznaniowością: elastyczność wobec nietypowych szoków (2008, 2020), których reguła nie przewidzi."),
          W("Jaki argument za regułami w polityce pieniężnej wynika z niespójności czasowej?",
            "Reguła czyni zapowiedzi niskiej inflacji wiarygodnymi", "Reguła pozwala lepiej reagować na nietypowe szoki", "Reguła usuwa wszystkie opóźnienia",
            why="Bez zobowiązania polityk ma pokusę zaskoczyć inflacją."),
          K("Debata 3: zrównoważony budżet?",
            "Za: deficyty przerzucają ciężar na przyszłe pokolenia, wypierają inwestycje (niższe oszczędności narodowe) i grożą kryzysem zadłużenia. Przeciw: dług bywa uzasadniony w recesji (stabilizatory), w czasie wojny i przy inwestycjach publicznych, z których skorzystają przyszłe pokolenia; ważniejsza jest relacja długu do PKB niż roczne saldo."),
          K("Debata 4: podatki sprzyjające oszczędzaniu?",
            "Za: opodatkowanie dochodu z oszczędności (odsetek, dywidend, zysków) zniechęca do oszczędzania – podatek konsumpcyjny, IKE/IKZE czy PPK zwiększyłyby oszczędności, inwestycje i wzrost. Przeciw: korzyści trafiłyby głównie do zamożnych, którzy oszczędzają najwięcej, a oszczędności mogą słabo reagować na stopę zwrotu."),
          PF("Podatek konsumpcyjny opodatkowuje dochód w chwili jego wydania, a nie zarobienia.", True,
             why="Oszczędzany dochód nie jest opodatkowany, dopóki nie zostanie wydany."),
      ],
      mech=[
          KT("Argument za czy przeciw aktywnej stabilizacji?",
             {"Za stabilizacją": ["Recesja oznacza utracone dochody i bezrobocie", "Automatyczne stabilizatory działają szybko"],
              "Przeciw stabilizacji": ["Opóźnienia sprawiają, że bodziec działa, gdy już nie jest potrzebny", "Prognozy koniunktury są niepewne"]},
             why="Debata dotyczy skuteczności, a nie celu."),
          KT("Argument za czy przeciw zrównoważonemu budżetowi?",
             {"Za zrównoważonym budżetem": ["Deficyt wypiera prywatne inwestycje", "Dług przerzuca ciężar na przyszłe pokolenia"],
              "Przeciw sztywnej równowadze": ["W recesji deficyt łagodzi spadek popytu", "Inwestycje publiczne posłużą przyszłym pokoleniom"]},
             why="Dwie strony debaty Mankiwa o budżecie."),
          LN("Ułóż argument za podatkiem konsumpcyjnym.",
             ["Obecny system opodatkowuje dochód z oszczędności", "Oszczędzanie przynosi mniej po opodatkowaniu", "Ludzie mniej oszczędzają", "Mniej funduszy na inwestycje", "Wolniejszy wzrost kapitału i produkcji"],
             why="Tak argumentują zwolennicy reformy."),
          W("Który argument jest głównym zarzutem wobec podatku konsumpcyjnego?",
            "Przesuwa ciężar podatkowy na mniej zamożnych", "Zniechęca do oszczędzania", "Zwiększa deficyt handlowy",
            why="Ubodzy wydają większą część dochodu."),
          W("Polska konstytucja ogranicza państwowy dług publiczny do 3/5 PKB. Co to jest?",
            "Reguła fiskalna – argument za regułami w polityce", "Polityka uznaniowa", "Automatyczny stabilizator",
            why="Ustalone z góry ograniczenie, którego nie zmienia się co roku."),
          PF("Mankiw przedstawia debaty jako spory, w których dobrzy ekonomiści mogą się różnić.", True,
             why="Różnice wynikają z ocen empirycznych i wartości."),
      ],
      calc=[
          LB("Dochód 100 000 zł, z czego 20 000 zł oszczędzone. Podatek dochodowy 20%. Ile wynosi podatek (zł)?",
             20000, "0.2*100000", ["20% · 100 000 = 20 000 zł"], unit="zł"),
          LB("Podatek konsumpcyjny 25% od wydatków 80 000 zł. Ile wynosi podatek (zł)?",
             20000, "0.25*80000", ["25% · 80 000 = 20 000 zł"], unit="zł"),
          LB("Lokata 10 000 zł na 5%. Ile wynoszą odsetki netto po podatku 19% (zł)?",
             405, "10000*0.05*0.81", ["500 · 0,81 = 405 zł"], unit="zł"),
          LB("Ile wynoszą odsetki przy podatku konsumpcyjnym (bez podatku od odsetek) (zł)?",
             500, "10000*0.05", ["10 000 · 5% = 500 zł"], unit="zł"),
          LB("Dług 1 000 mld zł, PKB nominalny 2 000 mld zł. Ile wynosi relacja długu do PKB (%)?",
             50, "1000/2000*100", ["1 000 / 2 000 = 50%"], unit="%"),
          LB("PKB rośnie nominalnie o 6%, a deficyt wynosi 30 mld zł. Ile wynosi nowa relacja długu do PKB (zaokrąglij do 0,1)?",
             48.6, "1030/2120*100", ["1 030 / 2 120 ≈ 48,6% – relacja spada mimo deficytu"], unit="%"),
      ],
      case=[
          PR("W 2020 r. rząd Polski zwiększył deficyt sektora finansów publicznych, finansując tarcze antykryzysowe. Krytycy ostrzegali przed wzrostem długu, a zwolennicy argumentowali, że bez tego recesja i bezrobocie byłyby znacznie większe.",
             W("Który argument z debaty o budżecie popiera działanie rządu?",
               "W głębokiej recesji deficyt łagodzi spadek popytu", "Deficyt zawsze wypiera inwestycje", "Budżet musi być zawsze zrównoważony",
               why="Polityka antycykliczna w recesji."),
             W("Jakie ryzyko wskazywali krytycy?",
               "Wyższy dług i jego koszty dla przyszłych pokoleń", "Zbyt niską inflację na zawsze", "Brak wpływu na popyt",
               why="Argument przeciw trwałym deficytom."),
             PF("Ocena zależy też od tego, czy po kryzysie deficyt zostanie ograniczony.", True,
                why="Tymczasowy deficyt w recesji różni się od trwałego."),
          ),
          PR("Rząd rozważa zastąpienie podatku Belki (19% od zysków kapitałowych) wyższą stawką VAT, by zachęcić do oszczędzania. Organizacje pracodawców popierają pomysł, a związki zawodowe są przeciw.",
             W("Jaki główny argument mają zwolennicy?",
               "Wyższe oszczędności i inwestycje przyspieszą wzrost", "Zmniejszenie konsumpcji bogatych", "Wyższa progresja podatkowa",
               why="Zniesienie podatku od oszczędności zwiększa ich opłacalność."),
             W("Dlaczego związki zawodowe mogą być przeciw?",
               "Wyższy VAT obciąża bardziej osoby wydające całe dochody", "Bo VAT jest progresywny", "Bo podatek Belki płacą tylko pracownicy",
               why="Podatek konsumpcyjny jest regresywny względem dochodu."),
             PF("Spór łączy pytanie empiryczne (jak oszczędności reagują na podatki) z oceną sprawiedliwości.", True,
                why="Tak Mankiw opisuje debaty polityczne."),
          ),
      ]),
]
