# -*- coding: utf-8 -*-
# Zrozumienie – Polityka gospodarcza / Przepisy i stawki
D = "2026-10-07"
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
KONST = S("Konstytucja RP – tekst, Dz.U. 1997 nr 78 poz. 483 (Sejm, ELI)", "https://api.sejm.gov.pl/eli/acts/DU/1997/483/text.pdf", D)
UOK = S("UOKiK – Ograniczanie konkurencji: kary", "https://uokik.gov.pl/ograniczanie-konkurencji-kary", D)
DZU = S("Dz.U. 2025 poz. 1242 – rozporządzenie w sprawie minimalnego wynagrodzenia na 2026 r.", "https://dziennikustaw.gov.pl/D2025000124201.pdf", D)
ZL = S("gov.pl – Zielona Linia: wynagrodzenie minimalne w 2026 r.", "https://zielonalinia.gov.pl/wynagrodzenie-minimalne-w-2026-1/", D)
S112 = S("OpenStax, Principles of Economics 3e, 11.2 Regulating Anticompetitive Behavior", OS3 + "11-2-regulating-anticompetitive-behavior", D)

LESSONS = [
    L(1, "Konstytucja RP a gospodarka",
      "Znać i rozumieć gospodarcze przepisy Konstytucji RP: społeczną gospodarkę rynkową, wolność działalności gospodarczej, ustawową formę podatków, procedurę budżetową, limit długu i zakaz finansowania deficytu przez NBP.",
      ["Konstytucja RP – przepisy gospodarcze"],
      [KONST],
      explain=[
          K("Art. 20 i 22 – ustrój gospodarczy",
            "Art. 20: społeczna gospodarka rynkowa oparta na wolności działalności gospodarczej, własności prywatnej oraz solidarności, dialogu i współpracy partnerów społecznych stanowi podstawę ustroju gospodarczego RP. Art. 22: ograniczenie wolności działalności gospodarczej jest dopuszczalne tylko w drodze ustawy i tylko ze względu na ważny interes publiczny."),
          K("Art. 217 – podatki",
            "Nakładanie podatków, innych danin publicznych, określanie podmiotów, przedmiotów opodatkowania i stawek, zasad przyznawania ulg i umorzeń następuje w drodze ustawy. Rząd nie może więc wprowadzić nowego podatku rozporządzeniem."),
          W("W jakiej formie można w Polsce wprowadzić nowy podatek?",
            "Ustawy", "Rozporządzenia ministra", "Uchwały NBP",
            why="Art. 217 Konstytucji."),
          K("Budżet i dług (art. 216, 219–225)",
            "Budżet uchwala Sejm w formie ustawy budżetowej; projekt przedkłada Rada Ministrów do 30 września; Sejm nie może uchwalić deficytu wyższego niż w projekcie rządu (art. 220 ust. 1). Art. 216 ust. 5: państwowy dług publiczny nie może przekroczyć 3/5 PKB. Art. 220 ust. 2: zakaz finansowania deficytu przez zaciąganie zobowiązań w centralnym banku państwa."),
          K("Art. 227 – NBP i RPP",
            "NBP – centralny bank państwa, ma wyłączne prawo emisji pieniądza oraz ustalania i realizowania polityki pieniężnej; odpowiada za wartość polskiego pieniądza. Organami NBP są: Prezes NBP (powoływany przez Sejm na wniosek Prezydenta na 6 lat), Rada Polityki Pieniężnej i Zarząd NBP."),
          PF("Konstytucja RP pozwala finansować deficyt budżetowy kredytem z NBP.", False,
             why="Art. 220 ust. 2 tego zabrania."),
      ],
      mech=[
          KT("Który artykuł Konstytucji?",
             {"Art. 20": ["Społeczna gospodarka rynkowa"],
              "Art. 216 ust. 5": ["Dług publiczny nie większy niż 3/5 PKB"],
              "Art. 217": ["Podatki tylko w drodze ustawy"],
              "Art. 220": ["Zakaz finansowania deficytu kredytem w NBP", "Sejm nie zwiększy deficytu ponad projekt rządu"],
              "Art. 227": ["NBP odpowiada za wartość polskiego pieniądza"]},
             why="Najważniejsze przepisy gospodarcze."),
          LN("Ułóż hierarchię ochrony stabilności finansów w Konstytucji.",
             ["Podatki tylko ustawą (art. 217)", "Budżet uchwalany ustawą (art. 219)", "Sejm nie zwiększa deficytu ponad projekt (art. 220 ust. 1)", "Zakaz finansowania deficytu przez NBP (art. 220 ust. 2)", "Limit długu 3/5 PKB (art. 216 ust. 5)"],
             why="Wiele zabezpieczeń stabilności finansów publicznych."),
          W("Na jak długą kadencję Sejm powołuje Prezesa NBP?",
            "6 lat", "4 lata", "10 lat",
            why="Art. 227 ust. 3 Konstytucji."),
          PF("Ograniczenie wolności działalności gospodarczej jest dopuszczalne tylko w drodze ustawy i ze względu na ważny interes publiczny.", True,
             why="Art. 22 Konstytucji."),
          M("Które organy są organami NBP?",
            ["Prezes NBP", "Rada Polityki Pieniężnej", "Rada Ministrów", "Zarząd NBP"],
            [0, 1, 3],
            why="Rada Ministrów to rząd."),
          W("Kto przedkłada Sejmowi projekt ustawy budżetowej?",
            "Rada Ministrów", "Prezydent", "NBP",
            why="Art. 221–222 Konstytucji."),
      ],
      calc=[
          LB("PKB 3900 mld zł. Ile wynosi limit państwowego długu publicznego z art. 216 ust. 5 (mld zł)?",
             2340, "3900*3/5", ["3/5 · 3900 = 2340 mld zł"], unit="mld zł"),
          LB("Państwowy dług publiczny wynosi 1950 mld zł. Ile brakuje do limitu konstytucyjnego (mld zł)?",
             390, "2340-1950", ["2340 − 1950 = 390 mld zł (dane umowne)"], unit="mld zł"),
          LB("Rząd zaplanował deficyt 290 mld zł. Sejm zwiększa wydatki o 12 mld zł i dochody o 5 mld zł. Ile wyniósłby deficyt (mld zł)?",
             297, "290+12-5", ["290 + 12 − 5 = 297 mld zł – niedopuszczalne (wyższy niż w projekcie)"], unit="mld zł"),
          LB("O ile mld zł Sejm musi dodatkowo zwiększyć dochody lub zmniejszyć inne wydatki, by deficyt nie przekroczył projektu?",
             7, "12-5", ["297 − 290 = 7 mld zł"], unit="mld zł"),
          LB("Kadencja Prezesa NBP to 6 lat. Prezes powołany w 2022 r. – w którym roku kończy kadencję (przy pełnej kadencji)?",
             2028, "2022+6", ["2022 + 6 = 2028"], unit=""),
          LB("Konstytucję uchwalono w 1997 r. Ile lat minęło do 2026 r.?",
             29, "2026-1997", ["2026 − 1997 = 29 lat"], unit="lat"),
      ],
      case=[
          PR("Minister finansów proponuje, by nową opłatę od napojów słodzonych wprowadzić rozporządzeniem, „żeby było szybciej”. Prawnicy ostrzegają, że byłoby to niezgodne z Konstytucją.",
             W("Który przepis Konstytucji stoi na przeszkodzie?",
               "Art. 217 – daniny publiczne nakłada się w drodze ustawy", "Art. 227 – o NBP", "Art. 20 – o gospodarce rynkowej",
               why="Podatki i inne daniny wymagają ustawy."),
             W("Jaki jest cel tej zasady?",
               "Ochrona obywateli przed arbitralnym nakładaniem ciężarów – decyduje parlament", "Przyspieszenie wprowadzania podatków", "Wzmocnienie NBP",
               why="Zasada „nie ma podatku bez ustawy”."),
             PF("Opłata cukrowa w Polsce została wprowadzona ustawą.", True,
                why="Daniny publiczne wymagają ustawy."),
          ),
          PR("W czasie kryzysu politycy proponują, by NBP kupował obligacje bezpośrednio od Ministerstwa Finansów i w ten sposób sfinansował deficyt. Ekonomiści i prawnicy przypominają o przepisach Konstytucji i traktatów UE.",
             W("Który przepis Konstytucji zabrania takiego rozwiązania?",
               "Art. 220 ust. 2 – zakaz finansowania deficytu przez zaciąganie zobowiązań w NBP", "Art. 217", "Art. 22",
               why="Chroni przed monetyzacją długu."),
             W("Jakie ryzyko ekonomiczne wiąże się z monetyzacją długu?",
               "Wysoka inflacja i utrata wiarygodności banku centralnego", "Deflacja", "Spadek długu bez kosztów",
               why="Emisja pieniądza na finansowanie budżetu podnosi ceny."),
             PF("NBP może kupować obligacje skarbowe na rynku wtórnym w ramach polityki pieniężnej.", True,
                why="Tak działo się w 2020 r.; zakaz dotyczy bezpośredniego finansowania deficytu."),
          ),
      ]),

    L(2, "Ochrona konkurencji i konsumentów oraz płaca minimalna",
      "Znać podstawowe zasady ustawy o ochronie konkurencji i konsumentów (2007), ustawy o prawach konsumenta (2014) i przepisów o płacy minimalnej oraz rozumieć ich ekonomiczne uzasadnienie.",
      ["Ustawa o ochronie konkurencji i konsumentów (2007)", "Ustawa o prawach konsumenta (2014)", "Płaca minimalna w Polsce"],
      [UOK, DZU, ZL, S112],
      explain=[
          K("Ustawa o ochronie konkurencji i konsumentów (2007)",
            "Zakazuje porozumień ograniczających konkurencję (kartele: ustalanie cen, podział rynku, zmowy przetargowe) i nadużywania pozycji dominującej (domniemanie przy udziale w rynku powyżej 40%); wprowadza kontrolę koncentracji i ochronę zbiorowych interesów konsumentów. Prezes UOKiK może nałożyć karę do 10% obrotu, a na menedżerów – do 2 mln zł; program łagodzenia kar nagradza sygnalistów z kartelu."),
          K("Ustawa o prawach konsumenta (2014)",
            "Daje konsumentowi 14 dni na odstąpienie od umowy zawartej na odległość (np. przez internet) lub poza lokalem przedsiębiorstwa – bez podania przyczyny; nakłada obowiązki informacyjne na sprzedawcę; od 2023 r. obowiązują nowe zasady odpowiedzialności za zgodność towaru z umową."),
          W("Ile dni ma konsument na odstąpienie od umowy zawartej przez internet?",
            "14 dni", "7 dni", "30 dni",
            why="Ustawa o prawach konsumenta z 2014 r."),
          K("Płaca minimalna",
            "Ustalana co roku rozporządzeniem Rady Ministrów po negocjacjach w Radzie Dialogu Społecznego. 2025 r.: 4666 zł brutto miesięcznie i 30,50 zł za godzinę; 2026 r.: 4806 zł i 31,40 zł. Minimalna stawka godzinowa chroni m.in. zleceniobiorców."),
          K("Ekonomiczne uzasadnienie",
            "Ochrona konkurencji przeciwdziała zawodnościom rynku (monopol, kartele), prawa konsumenta – asymetrii informacji przy zakupach na odległość, płaca minimalna – ubóstwu pracujących i sile monopsonu. Każda regulacja ma też koszty (np. ryzyko dla zatrudnienia przy zbyt wysokiej płacy minimalnej)."),
          PF("Domniemanie pozycji dominującej w polskim prawie dotyczy udziału w rynku powyżej 40%.", True,
             why="Tak stanowi ustawa o ochronie konkurencji i konsumentów."),
      ],
      mech=[
          KT("Która ustawa lub przepis?",
             {"Ochrona konkurencji": ["Kara dla kartelu cementowego", "Zgoda na przejęcie konkurenta"],
              "Prawa konsumenta": ["Zwrot butów kupionych przez internet w 14 dni", "Obowiązek informacji o cenie przed zakupem online"],
              "Płaca minimalna": ["4806 zł brutto w 2026 r.", "Stawka godzinowa 31,40 zł dla zleceniobiorców"]},
             why="Różne obszary regulacji."),
          LN("Ułóż przebieg postępowania antymonopolowego.",
             ["Sygnał o możliwym kartelu (np. od uczestnika – leniency)", "Postępowanie wyjaśniające UOKiK", "Postępowanie antymonopolowe i przeszukania", "Decyzja i kara (do 10% obrotu)", "Możliwe odwołanie do sądu ochrony konkurencji i konsumentów"],
             why="Typowy przebieg sprawy."),
          W("Jaka zawodność rynku uzasadnia prawo odstąpienia od umowy zawartej na odległość?",
            "Asymetria informacji – konsument nie może obejrzeć towaru przed zakupem", "Efekt zewnętrzny produkcji", "Monopol naturalny",
            why="Prawo odstąpienia ogranicza ryzyko zakupu „w ciemno”."),
          PF("Prawo odstąpienia od umowy w 14 dni przysługuje także firmom kupującym towary dla celów działalności.", False,
             why="To uprawnienie konsumenta; przedsiębiorcy co do zasady nie mają go z mocy ustawy (z wyjątkami dla niektórych jednoosobowych firm)."),
          M("Jakie kary może nałożyć Prezes UOKiK?",
            ["Na przedsiębiorcę do 10% obrotu", "Na menedżera odpowiedzialnego za kartel do 2 mln zł", "Karę więzienia", "Kary za naruszenie zbiorowych interesów konsumentów"],
            [0, 1, 3],
            why="Kary pozbawienia wolności orzekają sądy karne, nie UOKiK."),
          W("Kto korzysta z minimalnej stawki godzinowej?",
            "Osoby pracujące na umowach zlecenia (i niektórzy samozatrudnieni)", "Wyłącznie urzędnicy", "Firmy",
            why="Chroni przed bardzo niskim wynagrodzeniem poza umową o pracę."),
      ],
      calc=[
          LB("Obrót firmy 300 mln zł. Ile wynosi maksymalna kara UOKiK za udział w kartelu (mln zł)?",
             30, "0.1*300", ["10% · 300 = 30 mln zł"], unit="mln zł"),
          LB("Zleceniobiorca przepracował 120 godzin po minimalnej stawce 31,40 zł. Ile powinien otrzymać brutto (zł)?",
             3768, "120*31.40", ["120 · 31,40 = 3768 zł"], unit="zł"),
          LB("Płaca minimalna wzrosła z 4666 do 4806 zł. O ile zł miesięcznie?",
             140, "4806-4666", ["4806 − 4666 = 140 zł"], unit="zł"),
          LB("Firma ma 40% udziału w rynku, kolejne trzy po 20%. Ile wynosi HHI?",
             2800, "40**2+3*20**2", ["1600 + 3 · 400 = 2800"], unit=""),
          LB("Konsument kupił 25 września towar online, odebrał go 27 września. Do którego dnia października może odstąpić od umowy (14 dni od odbioru)?",
             11, "27+14-30", ["27 września + 14 dni = 11 października"], unit=""),
          LB("Menedżer odpowiedzialny za kartel może zostać ukarany kwotą do 2 mln zł. Trzech menedżerów otrzymało kary maksymalne. Ile łącznie (mln zł)?",
             6, "3*2", ["3 · 2 = 6 mln zł"], unit="mln zł"),
      ],
      case=[
          PR("Kupujący zamówił przez internet ekspres do kawy. Po odbiorze stwierdził, że urządzenie mu nie odpowiada, choć jest sprawne. Sprzedawca odmawia przyjęcia zwrotu, twierdząc, że „towar nie ma wad”.",
             W("Czy sprzedawca ma rację?",
               "Nie – konsument może odstąpić od umowy zawartej na odległość w ciągu 14 dni bez podania przyczyny", "Tak – zwrot przysługuje tylko przy wadzie", "Tak – zwroty są zakazane",
               why="Ustawa o prawach konsumenta z 2014 r."),
             W("Jaką instytucję może zawiadomić konsument, jeśli sklep stosuje taką praktykę wobec wielu klientów?",
               "UOKiK lub rzecznika konsumentów", "NBP", "Eurostat",
               why="Ochrona zbiorowych interesów konsumentów."),
             PF("Prawo odstąpienia od umowy zawartej na odległość jest odpowiedzią na asymetrię informacji.", True,
                why="Konsument nie mógł obejrzeć towaru przed zakupem."),
          ),
          PR("Trzech największych producentów płyt gipsowych w Polsce przez kilka lat uzgadniało podwyżki cen. Jeden z nich zgłosił się do UOKiK w ramach programu łagodzenia kar i przedstawił dowody. Pozostali otrzymali wysokie kary.",
             W("Jakie naruszenie popełnili producenci?",
               "Porozumienie ograniczające konkurencję (kartel cenowy)", "Nadużycie prawa konsumenta do zwrotu", "Naruszenie płacy minimalnej",
               why="Ustalanie cen między konkurentami."),
             W("Dlaczego firma, która zgłosiła kartel, mogła uniknąć kary?",
               "Program łagodzenia kar (leniency) nagradza pierwszego sygnalistę", "Bo miała najmniejszy udział", "Bo kartele są dozwolone",
               why="Zachęca do ujawniania karteli."),
             PF("Maksymalna kara dla przedsiębiorcy za kartel wynosi 10% obrotu.", True,
                why="Zgodnie z ustawą z 2007 r."),
          ),
      ]),
]
