# -*- coding: utf-8 -*-
# Zrozumienie – Polityka gospodarcza / Wzory (nacisk na obliczenia)
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S284 = S("OpenStax, Principles of Economics 3e, 28.4 Monetary Policy and Economic Outcomes", OS3 + "28-4-monetary-policy-and-economic-outcomes", D)
S285 = S("OpenStax, Principles of Economics 3e, 28.5 Pitfalls for Monetary Policy", OS3 + "28-5-pitfalls-for-monetary-policy", D)
S231 = S("OpenStax, Principles of Economics 3e, 23.1 Measuring Trade Balances", OS3 + "23-1-measuring-trade-balances", D)
S293 = S("OpenStax, Principles of Economics 3e, 29.3 Macroeconomic Effects of Exchange Rates", OS3 + "29-3-macroeconomic-effects-of-exchange-rates", D)
S303 = S("OpenStax, Principles of Economics 3e, 30.3 Federal Deficits and the National Debt", OS3 + "30-3-federal-deficits-and-the-national-debt", D)
S304 = S("OpenStax, Principles of Economics 3e, 30.4 Using Fiscal Policy to Fight Recession, Unemployment, and Inflation", OS3 + "30-4-using-fiscal-policy-to-fight-recession-unemployment-and-inflation", D)
S302 = S("OpenStax, Principles of Economics 3e, 30.2 Taxation", OS3 + "30-2-taxation", D)
FINS = S("Finwire – stopy NBP październik 2026: 3,75%", "https://finwire.pl/artykuly/stopy-procentowe-nbp-pazdziernik-2026-375-decyzja-rpp-rata-kredytu", D)
XYZD = S("XYZ – Deficyt sektora rządowego i samorządowego w 2025 r. wyniósł 7,3% PKB", "https://xyz.pl/dzieje-sie/deficyt-sektora-rzadowego-i-samorzadowego-w-2025-r-wyniosl-73-proc-pkb-1611", D)

LESSONS = [
    L(1, "Reguła Taylora krok po kroku",
      "Liczyć stopę procentową według reguły Taylora, rozumieć znaczenie każdego składnika i zasadę Taylora (reakcja ponad 1 na inflację).",
      ["Reguła Taylora", "Reguła Taylora – wzór"],
      [S284, FINS],
      explain=[
          K("Wzór",
            "i = r* + π + a(π − π*) + b·luka. Oryginalnie (Taylor, 1993): r* = 2%, π* = 2%, a = b = 0,5. i – nominalna stopa banku centralnego, r* – naturalna (neutralna) realna stopa, π – bieżąca inflacja, π* – cel, luka – (Y − Y*)/Y* w %.",
            w="i = r* + π + 0,5(π − π*) + 0,5·luka"),
          K("Interpretacja składników",
            "r* + π – stopa neutralna nominalna (realna stopa równa naturalnej). Składnik inflacyjny – gdy inflacja przekracza cel, stopa rośnie. Składnik luki – gdy gospodarka jest powyżej potencjału, stopa rośnie. Łączna reakcja na inflację to 1 + a = 1,5 (zasada Taylora)."),
          W("Inflacja równa celowi, luka zero, r* = 1%, π* = 2,5%. Ile wynosi stopa według reguły?",
            "3,5%", "1%", "2,5%",
            why="i = 1 + 2,5 + 0 + 0 = 3,5%."),
          K("Przykład",
            "r* = 1%, π = 4%, π* = 2,5%, luka = −1%: i = 1 + 4 + 0,5·1,5 + 0,5·(−1) = 1 + 4 + 0,75 − 0,5 = 5,25%."),
          K("Ograniczenia",
            "r* i luka PKB są nieobserwowalne i szacowane z dużym błędem; dane są rewidowane; reguła nie uwzględnia szoków podażowych, kursu walutowego ani stabilności finansowej. Dlatego to punkt odniesienia, nie automat."),
          PF("Według zasady Taylora przy wzroście inflacji o 1 p.p. stopa powinna wzrosnąć o 1,5 p.p. (przy a = 0,5).", True,
             why="1 (składnik π) + 0,5 (składnik odchylenia od celu)."),
      ],
      mech=[
          LN("Ułóż kolejność liczenia stopy z reguły Taylora.",
             ["Ustal r*, π i π*", "Policz odchylenie inflacji od celu", "Policz lukę PKB", "Podstaw: r* + π + 0,5(π − π*) + 0,5·luka", "Porównaj z faktyczną stopą banku"],
             why="Systematyczne podejście zmniejsza błędy."),
          KT("Co podnosi, a co obniża wskazanie reguły?",
             {"Podnosi": ["Inflacja powyżej celu", "Dodatnia luka PKB", "Wyższa naturalna stopa realna"],
              "Obniża": ["Inflacja poniżej celu", "Ujemna luka PKB (recesja)"]},
             why="Każdy składnik działa w określonym kierunku."),
          W("Luka PKB rośnie o 2 p.p. (b = 0,5). Jak zmienia się wskazanie reguły?",
            "Rośnie o 1 p.p.", "Rośnie o 2 p.p.", "Spada o 1 p.p.",
            why="0,5 · 2 = 1 p.p."),
          PF("Reguła Taylora może dawać ujemne wartości stopy w głębokiej recesji.", True,
             why="Przy bardzo ujemnej luce i niskiej inflacji – stąd sens narzędzi niekonwencjonalnych."),
          M("Które wielkości w regule Taylora są trudne do zmierzenia?",
            ["Naturalna stopa realna r*", "Luka PKB", "Cel inflacyjny", "Potencjalny PKB"],
            [0, 1, 3],
            why="Cel inflacyjny jest ogłaszany przez bank."),
          W("Dlaczego współczynnik reakcji na inflację musi przekraczać 1?",
            "Aby realna stopa rosła przy wzroście inflacji", "Aby stopa nominalna spadała", "Bo tak stanowi konstytucja",
            why="Inaczej polityka luzowałaby się przy rosnącej inflacji."),
      ],
      calc=[
          LB("r* = 2%, π = 3%, π* = 2%, luka = 1%. Ile wynosi stopa według oryginalnej reguły Taylora (%)?",
             6, "2+3+0.5*(3-2)+0.5*1", ["2 + 3 + 0,5 + 0,5 = 6%"], unit="%"),
          LB("r* = 1%, π = 4%, π* = 2,5%, luka = −1%. Ile wynosi stopa (%)?",
             5.25, "1+4+0.5*(4-2.5)+0.5*(-1)", ["1 + 4 + 0,75 − 0,5 = 5,25%"], unit="%"),
          LB("r* = 1%, π = 1%, π* = 2,5%, luka = −4%. Ile wynosi stopa (%)?",
             -0.75, "1+1+0.5*(1-2.5)+0.5*(-4)", ["1 + 1 − 0,75 − 2 = −0,75% – reguła wskazuje stopę ujemną"], unit="%"),
          LB("Inflacja rośnie z 3% do 5% (pozostałe bez zmian). O ile p.p. rośnie wskazanie reguły?",
             3, "1.5*(5-3)", ["1,5 · 2 = 3 p.p."], unit="p.p."),
          LB("Ile wynosi realna stopa (i − π) wskazana przez regułę przy r* = 1%, π = 4%, π* = 2,5%, luka 0 (%)?",
             1.75, "(1+4+0.5*1.5)-4", ["i = 5,75%", "i − π = 1,75%"], unit="%"),
          LB("Faktyczna stopa NBP 3,75%, wskazanie reguły 5,25%. O ile p.p. polityka jest łagodniejsza niż wskazuje reguła?",
             1.5, "5.25-3.75", ["5,25 − 3,75 = 1,5 p.p."], unit="p.p."),
      ],
      case=[
          PR("Analityczka liczy wskazanie reguły Taylora dla Polski jesienią 2026 r. Przyjmuje: r* = 1%, inflacja 4,0% (wrzesień 2026), cel 2,5%, luka PKB −0,5%. Stopa referencyjna NBP wynosi 3,75%.",
             W("Ile wynosi wskazanie reguły?",
               "5,5%", "3,75%", "4,0%",
               why="1 + 4 + 0,75 − 0,25 = 5,5%."),
             W("Co sugeruje porównanie z faktyczną stopą?",
               "Polityka jest łagodniejsza niż wskazuje reguła o ok. 1,75 p.p.", "Polityka jest zbyt restrykcyjna", "Stopy są dokładnie zgodne z regułą",
               why="5,5 − 3,75 = 1,75 p.p."),
             PF("Bank centralny może świadomie odchodzić od reguły, np. gdy inflacja wynika z jednorazowej podwyżki podatku.", True,
                why="Reguła nie odróżnia źródeł inflacji."),
          ),
          PR("W 2009 r. w USA inflacja spadła do okolic zera, a luka PKB wynosiła ok. −6%. Fed obniżył stopy do przedziału 0–0,25%. Ekonomiści zauważyli, że reguła Taylora wskazywała wówczas stopy ujemne.",
             W("Ile wskazuje reguła przy r* = 2%, π = 0%, π* = 2%, luka −6%?",
               "Minus 2%", "Zero", "Plus 2%",
               why="2 + 0 − 1 − 3 = −2%."),
             W("Co zrobił Fed, nie mogąc obniżyć stóp poniżej zera?",
               "Sięgnął po luzowanie ilościowe i forward guidance", "Podniósł stopy", "Wprowadził standard złota",
               why="Narzędzia niekonwencjonalne przy dolnej granicy stóp."),
             PF("Wskazanie ujemnej stopy przez regułę uzasadniało niekonwencjonalne działania banku centralnego.", True,
                why="Stopa nominalna nie mogła zejść znacząco poniżej zera."),
          ),
      ]),

    L(2, "Warianty reguły Taylora i wygładzanie stóp",
      "Liczyć warianty reguły Taylora: z wygładzaniem (inercją) stóp, z inflacją bazową lub prognozowaną oraz z różnymi wagami, i rozumieć, dlaczego banki zmieniają stopy stopniowo.",
      ["Reguła Taylora", "Reguła Taylora – wzór"],
      [S284, S285],
      explain=[
          K("Wygładzanie stóp",
            "Banki centralne zmieniają stopy stopniowo (np. po 25 pb), by nie zaskakiwać rynków. Wariant z inercją: iₜ = ρ·iₜ₋₁ + (1 − ρ)·i^T, gdzie i^T – wskazanie reguły, ρ – stopień wygładzania (np. 0,8).",
            w="iₜ = ρ·iₜ₋₁ + (1 − ρ)·i^T"),
          K("Inflacja prognozowana i bazowa",
            "Ponieważ polityka działa z opóźnieniem, w regule stosuje się często prognozę inflacji za 1–2 lata zamiast bieżącej, albo inflację bazową (bez żywności i energii), by nie reagować na przejściowe szoki."),
          W("Ostatnia stopa 3,75%, wskazanie reguły 5,25%, ρ = 0,8. Ile wynosi stopa z wygładzaniem?",
            "4,05%", "5,25%", "3,75%",
            why="0,8 · 3,75 + 0,2 · 5,25 = 3 + 1,05 = 4,05%."),
          K("Różne wagi",
            "Bank silniej dbający o inflację („jastrzębi”) ma wyższe a, bank dbający bardziej o zatrudnienie („gołębi”) – wyższe b. Przy b = 1 (zamiast 0,5) reguła silniej reaguje na lukę PKB."),
          K("Reguła jako narzędzie komunikacji",
            "Porównanie faktycznej stopy z różnymi wariantami reguły pozwala ocenić, czy polityka jest restrykcyjna, czy łagodna, i ułatwia przewidywanie decyzji."),
          PF("Wygładzanie stóp oznacza, że bank od razu dostosowuje stopę do wskazania reguły.", False,
             why="Dostosowuje ją stopniowo, rozkładając zmianę na wiele posiedzeń."),
      ],
      mech=[
          LN("Ułóż stopniowe dochodzenie stopy do wskazania reguły (ρ = 0,5).",
             ["Stopa 2%, wskazanie reguły 6%", "Po pierwszym posiedzeniu: 4%", "Po drugim: 5%", "Po trzecim: 5,5%", "Stopa zbliża się do 6%"],
             why="Każdorazowo pokonuje się połowę dystansu."),
          KT("Wariant jastrzębi czy gołębi?",
             {"Jastrzębi": ["Wysoka waga odchylenia inflacji (a = 1)", "Reakcja na prognozę wzrostu inflacji"],
              "Gołębi": ["Wysoka waga luki PKB (b = 1)", "Reakcja wyłącznie na inflację bazową przy szoku energetycznym"]},
             why="Wagi odzwierciedlają preferencje banku."),
          W("Dlaczego w regule używa się często prognozy inflacji?",
            "Bo decyzje działają z opóźnieniem kilku kwartałów", "Bo bieżąca inflacja nie jest mierzona", "Bo prognozy są zawsze dokładne",
            why="Bank musi działać wyprzedzająco."),
          PF("Im wyższy parametr ρ, tym wolniej stopa dostosowuje się do wskazania reguły.", True,
             why="Większa waga poprzedniej stopy."),
          M("Jakie są zalety wygładzania stóp?",
            ["Mniejsza zmienność na rynkach", "Lepsza przewidywalność decyzji", "Natychmiastowa reakcja na każdy szok", "Możliwość korekty przy niepewnych danych"],
            [0, 1, 3],
            why="Wygładzanie oznacza wolniejszą reakcję."),
          W("Inflacja ogółem 4%, bazowa 2,8%. Które wskazanie reguły (r* = 1, π* = 2,5, luka 0) będzie niższe?",
            "Oparte na inflacji bazowej", "Oparte na inflacji ogółem", "Oba równe",
            why="Niższa inflacja w regule daje niższą stopę."),
      ],
      calc=[
          LB("iₜ₋₁ = 3,75%, i^T = 5,25%, ρ = 0,8. Ile wynosi iₜ (%)?",
             4.05, "0.8*3.75+0.2*5.25", ["3 + 1,05 = 4,05%"], unit="%"),
          LB("W kolejnym okresie (ρ = 0,8, i^T = 5,25%) ile wynosi stopa (%)?",
             4.29, "0.8*4.05+0.2*5.25", ["0,8 · 4,05 + 0,2 · 5,25 = 3,24 + 1,05 = 4,29%"], unit="%"),
          LB("Inflacja bazowa 2,8%, r* = 1%, π* = 2,5%, luka 0. Ile wskazuje reguła oparta na inflacji bazowej (%)?",
             3.95, "1+2.8+0.5*(2.8-2.5)", ["1 + 2,8 + 0,15 = 3,95%"], unit="%"),
          LB("Wariant z b = 1: r* = 1%, π = 3%, π* = 2,5%, luka −2%. Ile wynosi stopa (%)?",
             2.25, "1+3+0.5*0.5+1*(-2)", ["1 + 3 + 0,25 − 2 = 2,25%"], unit="%"),
          LB("Ten sam przypadek z b = 0,5. Ile wynosi stopa (%)?",
             3.25, "1+3+0.5*0.5+0.5*(-2)", ["1 + 3 + 0,25 − 1 = 3,25%"], unit="%"),
          LB("Prognoza inflacji za rok 3,2% (zamiast bieżącej 4%), r* = 1%, π* = 2,5%, luka 0. Ile wynosi stopa (%)?",
             4.55, "1+3.2+0.5*(3.2-2.5)", ["1 + 3,2 + 0,35 = 4,55%"], unit="%"),
      ],
      case=[
          PR("Rada banku centralnego ma do wyboru: od razu podnieść stopę o 150 pb do wskazania reguły albo podnosić ją stopniowo po 25–50 pb na kolejnych posiedzeniach. Rynek finansowy jest niestabilny, a dane o PKB podlegają częstym rewizjom.",
             W("Jaki argument przemawia za stopniowością?",
               "Niepewność danych i ryzyko wywołania nerwowości na rynkach", "Pewność co do r* i luki", "Brak opóźnień polityki",
               why="Stopniowość pozwala korygować kurs przy nowych danych."),
             W("Jakie ryzyko niesie zbyt wolne działanie?",
               "Utrwalenie oczekiwań inflacyjnych", "Natychmiastowa deflacja", "Brak ryzyka",
               why="Spóźniona reakcja może wymagać później silniejszych podwyżek."),
             PF("Wygładzanie stóp można opisać wzorem iₜ = ρ·iₜ₋₁ + (1 − ρ)·i^T.", True,
                why="To standardowy zapis reguły z inercją."),
          ),
          PR("Po szoku energetycznym inflacja ogółem wynosi 10%, a bazowa 5%. Cel 2,5%, r* = 1%, luka 0. Dwóch członków rady liczy regułę Taylora: jeden na inflacji ogółem, drugi na bazowej.",
             W("Ile wskazuje reguła z inflacją ogółem?",
               "14,75%", "7,25%", "10%",
               why="1 + 10 + 0,5 · 7,5 = 14,75%."),
             W("Ile wskazuje reguła z inflacją bazową?",
               "7,25%", "14,75%", "5%",
               why="1 + 5 + 0,5 · 2,5 = 7,25%."),
             PF("Wybór miary inflacji może zmienić wskazanie reguły o kilka punktów procentowych.", True,
                why="Szoki energetyczne silnie wpływają na inflację ogółem."),
          ),
      ]),

    L(3, "Terms of trade w liczbach",
      "Liczyć terms of trade (relacje wymiany) i ich zmiany, rozumieć wpływ zmian cen surowców i kursu na dochód kraju oraz odróżniać terms of trade od bilansu handlowego.",
      ["Terms of trade (relacje wymiany)"],
      [S231, S293],
      explain=[
          K("Definicja",
            "Terms of trade (ToT) = indeks cen eksportu / indeks cen importu · 100. Wzrost ToT oznacza, że za jednostkę eksportu kraj może kupić więcej importu – jego siła nabywcza na rynkach światowych rośnie.",
            w="ToT = Pₓ / Pₘ · 100"),
          K("Czynniki zmian",
            "ToT poprawiają się, gdy drożeje to, co kraj eksportuje (np. ropa dla Norwegii), lub tanieje to, co importuje (np. energia dla Polski). Pogorszenie ToT działa jak spadek dochodu: za ten sam eksport można kupić mniej."),
          W("Ceny eksportu rosną o 5%, a importu o 10%. Co dzieje się z terms of trade?",
            "Pogarszają się", "Poprawiają się", "Nie zmieniają się",
            why="ToT = 105 / 110 · 100 ≈ 95,5."),
          K("ToT a bilans handlowy",
            "Terms of trade dotyczą relacji CEN, bilans handlowy – WARTOŚCI eksportu i importu. Pogorszenie ToT może pogorszyć bilans (droższy import), ale ilości też się zmieniają. Kraj importujący energię po wzroście jej cen zwykle notuje pogorszenie ToT i bilansu."),
          K("Zysk lub strata z relacji wymiany",
            "Zmianę dochodu wynikającą ze zmiany ToT można przybliżyć: (zmiana ToT w %) · udział importu w PKB. Np. pogorszenie ToT o 5% przy imporcie 50% PKB to strata ok. 2,5% PKB siły nabywczej."),
          PF("Wzrost światowych cen ropy pogarsza terms of trade kraju importującego ropę.", True,
             why="Rośnie cena importu względem eksportu."),
      ],
      mech=[
          LN("Ułóż skutki pogorszenia terms of trade dla importera energii.",
             ["Ceny energii na świecie rosną", "Ceny importu rosną szybciej niż eksportu", "Terms of trade spadają", "Za ten sam eksport kraj kupuje mniej importu", "Realny dochód kraju maleje"],
             why="Pogorszenie ToT działa jak transfer dochodu za granicę."),
          KT("Poprawa czy pogorszenie ToT?",
             {"Poprawa": ["Drożeje miedź eksportowana przez kraj", "Tanieje importowana ropa", "Rosną ceny eksportowanych samochodów szybciej niż importu"],
              "Pogorszenie": ["Drożeje importowany gaz", "Tanieje eksportowana żywność"]},
             why="Liczy się relacja cen eksportu do importu."),
          W("Ceny eksportu −2%, importu −8%. Co z terms of trade?",
            "Poprawiają się", "Pogarszają się", "Bez zmian",
            why="98 / 92 · 100 ≈ 106,5."),
          PF("Terms of trade mierzą wartość eksportu minus importu.", False,
             why="To bilans handlowy; ToT to relacja cen."),
          M("Kto zyskuje na wzroście cen surowców na świecie?",
            ["Eksporterzy ropy (np. Norwegia)", "Eksporterzy miedzi (np. Chile)", "Importerzy energii (np. Polska)", "Kraje eksportujące gaz"],
            [0, 1, 3],
            why="Importerom energii ToT się pogarszają."),
          W("Jak deprecjacja waluty wpływa zwykle na terms of trade w krótkim okresie?",
            "Często je pogarsza – import drożeje w walucie krajowej szybciej niż ceny eksportu", "Zawsze je poprawia", "Nie wpływa",
            why="Ceny importu w walucie krajowej rosną od razu."),
      ],
      calc=[
          LB("Indeks cen eksportu 112, importu 105. Ile wynoszą terms of trade?",
             106.67, "112/105*100", ["112 / 105 · 100 ≈ 106,67"], unit="", tol=0.02),
          LB("Ceny eksportu rosną o 5%, importu o 10% (z bazy 100). Ile wynoszą terms of trade?",
             95.45, "105/110*100", ["105 / 110 · 100 ≈ 95,45"], unit="", tol=0.02),
          LB("O ile procent pogorszyły się terms of trade?",
             -4.55, "(105/110-1)*100", ["105 / 110 − 1 ≈ −4,55%"], unit="%", tol=0.02),
          LB("Import stanowi 50% PKB. Ile wynosi przybliżona strata siły nabywczej (% PKB) przy pogorszeniu ToT o 4,55%?",
             2.27, "0.5*4.545", ["0,5 · 4,55 ≈ 2,27% PKB"], unit="%", tol=0.02),
          LB("Kraj eksportuje 100 ton zboża, kupując za nie 50 ton nawozów. Po zmianie cen za 100 ton zboża kupuje 40 ton nawozów. O ile procent pogorszyły się relacje wymiany?",
             -20, "(40/50-1)*100", ["40 / 50 − 1 = −20%"], unit="%"),
          LB("Ceny eksportu spadają o 2%, importu o 8%. Ile wynoszą ToT (z bazy 100)?",
             106.52, "98/92*100", ["98 / 92 · 100 ≈ 106,52"], unit="", tol=0.02),
      ],
      case=[
          PR("W 2022 r. ceny gazu, ropy i węgla gwałtownie wzrosły po inwazji Rosji na Ukrainę. Polska importuje większość ropy i gazu. Ceny polskiego eksportu (maszyny, meble, żywność) rosły wolniej niż ceny importu energii.",
             W("Jak zmieniły się terms of trade Polski?",
               "Pogorszyły się", "Poprawiły się", "Nie zmieniły się",
               why="Ceny importu rosły szybciej niż eksportu."),
             W("Jaki był skutek dla gospodarki?",
               "Spadek realnego dochodu – więcej eksportu na opłacenie energii", "Wzrost realnego dochodu", "Brak skutków",
               why="Pogorszenie ToT to „transfer” dochodu do eksporterów energii."),
             PF("Kraje eksportujące gaz (np. Norwegia) odnotowały w tym czasie poprawę terms of trade.", True,
                why="Ceny ich eksportu wzrosły."),
          ),
          PR("Chile jest jednym z największych eksporterów miedzi. Gdy na świecie rośnie popyt na miedź (np. przez elektryfikację), jej cena rośnie, a dochody budżetu Chile i kurs peso często się umacniają.",
             W("Co dzieje się z terms of trade Chile, gdy drożeje miedź?",
               "Poprawiają się", "Pogarszają się", "Nie zmieniają się",
               why="Rośnie cena głównego towaru eksportowego."),
             W("Jakie ryzyko wiąże się z dużą zależnością od jednego surowca?",
               "Silne wahania dochodu i ryzyko choroby holenderskiej", "Brak wahań", "Stała inflacja",
               why="Zmiany cen surowca przenoszą się na całą gospodarkę."),
             PF("Fundusz stabilizacyjny oszczędzający nadwyżki z wysokich cen surowca łagodzi wahania budżetu.", True,
                why="Pozwala wydawać stabilniej w okresie niskich cen."),
          ),
      ]),

    L(4, "Arytmetyka deficytu i długu",
      "Liczyć deficyt pierwotny i całkowity, saldo strukturalne, dynamikę relacji długu do PKB oraz koszty obsługi długu.",
      ["Polityka fiskalna (budżetowa)", "Konsolidacja fiskalna", "Progi ostrożnościowe i konstytucyjny limit długu"],
      [S303, XYZD],
      explain=[
          K("Podstawowe salda",
            "Deficyt całkowity = wydatki − dochody. Deficyt pierwotny = deficyt całkowity − odsetki od długu. Saldo strukturalne = saldo całkowite − komponent cykliczny − działania jednorazowe.",
            w="DP = D − odsetki"),
          K("Dynamika relacji długu",
            "Relacja długu do PKB d zmienia się o: Δd ≈ (r − g)/(1 + g) · d + deficyt pierwotny (% PKB), gdzie r – średnie oprocentowanie długu, g – tempo wzrostu nominalnego PKB. Dla małych r i g: Δd ≈ (r − g)·d + dp.",
            w="Δd ≈ (r − g)·d + dp"),
          W("Deficyt całkowity 6% PKB, odsetki 2% PKB. Ile wynosi deficyt pierwotny?",
            "4% PKB", "8% PKB", "2% PKB",
            why="6 − 2 = 4% PKB."),
          K("Saldo stabilizujące dług",
            "Aby relacja długu się nie zmieniała (Δd = 0), saldo pierwotne musi wynosić (r − g)·d. Gdy g > r, można mieć niewielki deficyt pierwotny; gdy r > g, potrzebna jest nadwyżka pierwotna.",
            w="dp* = −(r − g)·d"),
          K("Przykład dla Polski",
            "W 2025 r. deficyt sektora GG wyniósł 7,3% PKB, a dług wzrósł z 54,8% do 59,7% PKB (notyfikacja GUS, kwiecień 2026). Wzrost relacji o 4,9 p.p. był mniejszy niż deficyt, bo nominalny PKB rósł i „rozcieńczał” dług."),
          PF("Przy g > r relacja długu do PKB może maleć nawet przy niewielkim deficycie pierwotnym.", True,
             why="PKB rośnie szybciej niż odsetki powiększają dług."),
      ],
      mech=[
          LN("Ułóż obliczanie zmiany relacji długu do PKB.",
             ["Ustal dług d (% PKB), r i g", "Policz efekt (r − g)·d", "Dodaj deficyt pierwotny (% PKB)", "Otrzymasz Δd", "Nowa relacja = d + Δd"],
             why="Dwa składniki: efekt kuli śnieżnej i saldo pierwotne."),
          KT("Zwiększa czy zmniejsza relację długu do PKB?",
             {"Zwiększa": ["Deficyt pierwotny", "Wzrost oprocentowania długu", "Recesja (spadek nominalnego PKB)"],
              "Zmniejsza": ["Nadwyżka pierwotna", "Szybki wzrost nominalnego PKB", "Wyższa inflacja (krótkookresowo)"]},
             why="Efekty licznika i mianownika."),
          W("Dlaczego inflacja może krótkookresowo obniżać relację długu do PKB?",
            "Zwiększa nominalny PKB, a stary dług o stałym oprocentowaniu nie rośnie tak szybko", "Bo zmniejsza dług nominalny", "Nie może",
            why="Mianownik rośnie szybciej niż licznik."),
          PF("Deficyt całkowity zawsze jest mniejszy od deficytu pierwotnego.", False,
             why="Całkowity = pierwotny + odsetki, więc jest większy (przy dodatnich odsetkach)."),
          M("Co obejmuje komponent cykliczny salda budżetu?",
            ["Spadek podatków w recesji", "Wzrost zasiłków w recesji", "Jednorazowa sprzedaż majątku", "Wyższe wpływy w boomie"],
            [0, 1, 3],
            why="Jednorazowe operacje to osobna kategoria."),
          W("Dług 60% PKB, r = 4%, g = 7%, deficyt pierwotny 0. Jak zmienia się relacja długu?",
            "Spada o ok. 1,8 p.p.", "Rośnie o 1,8 p.p.", "Bez zmian",
            why="(4 − 7)% · 60 = −1,8 p.p."),
      ],
      calc=[
          LB("Dług 54,8% PKB, r = 5%, g = 7%, deficyt pierwotny 5% PKB. O ile p.p. zmieni się relacja długu (przybliżenie)?",
             3.9, "(0.05-0.07)*54.8+5", ["(−0,02) · 54,8 = −1,096", "−1,1 + 5 ≈ 3,9 p.p."], unit="p.p.", tol=0.03),
          LB("Dług 60% PKB, r = 6%, g = 4%. Jakie saldo pierwotne (% PKB) stabilizuje dług? (Podaj nadwyżkę jako liczbę dodatnią.)",
             1.2, "(0.06-0.04)*60", ["(r − g) · d = 0,02 · 60 = 1,2% PKB nadwyżki pierwotnej"], unit="%"),
          LB("Deficyt 7,3% PKB, odsetki 2,4% PKB (dane umowne). Ile wynosi deficyt pierwotny (% PKB)?",
             4.9, "7.3-2.4", ["7,3 − 2,4 = 4,9% PKB"], unit="%"),
          LB("Dług 2335 mld zł, średnie oprocentowanie 5,5%. Ile wynoszą roczne odsetki (mld zł)?",
             128.43, "2335*0.055", ["2335 · 0,055 ≈ 128,4 mld zł (oprocentowanie – dane umowne)"], unit="mld zł", tol=0.01),
          LB("Deficyt całkowity 5% PKB, z czego 1% PKB wynika z recesji (część cykliczna), a 0,5% PKB to jednorazowe wydatki. Ile wynosi deficyt strukturalny (% PKB)?",
             3.5, "5-1-0.5", ["5 − 1 − 0,5 = 3,5% PKB"], unit="%"),
          LB("Dług nominalny rośnie o 10%, nominalny PKB o 7%. O ile procent rośnie relacja długu do PKB (względnie)?",
             2.8, "(1.10/1.07-1)*100", ["1,10 / 1,07 − 1 ≈ 2,8%"], unit="%", tol=0.03),
      ],
      case=[
          PR("W 2025 r. deficyt sektora GG w Polsce wyniósł 7,3% PKB, a dług wzrósł z 54,8% do 59,7% PKB. Rząd planował na 2026 r. deficyt ok. 6,8% PKB.",
             W("Dlaczego dług wzrósł o mniej niż wynosił deficyt (4,9 p.p. wobec 7,3% PKB)?",
               "Wzrost nominalnego PKB zmniejszał relację długu (efekt mianownika)", "Bo część deficytu nie była finansowana", "Bo dług spadł",
               why="Nominalny PKB rósł ok. kilka procent rocznie."),
             W("Co stanie się z relacją długu, jeśli deficyt utrzyma się na poziomie ok. 7% PKB, a nominalny PKB będzie rósł ok. 6%?",
               "Relacja dalej wyraźnie wzrośnie", "Spadnie", "Pozostanie stała",
               why="Deficyt przewyższa „rozcieńczenie” przez wzrost PKB."),
             PF("Stabilizacja relacji długu wymaga zmniejszenia deficytu pierwotnego.", True,
                why="Przy obecnym deficycie relacja rośnie."),
          ),
          PR("Kraj A ma dług 90% PKB, oprocentowanie 3%, wzrost nominalny 5%. Kraj B ma dług 40% PKB, oprocentowanie 8%, wzrost nominalny 4%. Oba mają zrównoważone budżety pierwotne.",
             W("W którym kraju relacja długu do PKB spada?",
               "W kraju A", "W kraju B", "W obu rośnie",
               why="A: (3 − 5) · 90 = −1,8 p.p.; B: (8 − 4) · 40 = +1,6 p.p."),
             W("Jaki wniosek płynie z porównania?",
               "O dynamice długu decyduje nie tylko jego poziom, ale też relacja r do g", "Niski dług zawsze maleje", "Wysoki dług zawsze rośnie",
               why="Efekt kuli śnieżnej zależy od r − g."),
             PF("Wzrost oprocentowania długu w kraju A mógłby odwrócić spadek relacji długu.", True,
                why="Gdy r przekroczy g, efekt staje się dodatni."),
          ),
      ]),

    L(5, "Mnożniki, policy mix i krzywa Laffera w liczbach",
      "Liczyć efekty polityki fiskalnej (mnożniki wydatkowy i podatkowy, z przeciekami), łączny wpływ policy mix oraz wpływy podatkowe na krzywej Laffera.",
      ["Policy mix", "Polityka stabilizacyjna", "Krzywa Laffera", "Mnożnik podatkowy"],
      [S304, S302],
      explain=[
          K("Mnożniki w gospodarce otwartej z podatkiem",
            "Mnożnik wydatkowy: k = 1 / (1 − c(1 − t) + m), gdzie c – krańcowa skłonność do konsumpcji, t – stawka podatku, m – krańcowa skłonność do importu. Mnożnik podatku kwotowego: −c·k.",
            w="k = 1 / (1 − c(1 − t) + m)"),
          K("Policy mix w liczbach",
            "Łączny efekt = efekt fiskalny + efekt pieniężny. Np. ekspansja fiskalna +1% PKB i podwyżka stóp −0,6% PKB dają +0,4% PKB. Przy wypychaniu część efektu fiskalnego znika przez wzrost stóp."),
          W("c = 0,8, t = 0,25, m = 0,2. Ile wynosi mnożnik wydatkowy?",
            "Ok. 1,67", "5", "2,5",
            why="c(1 − t) = 0,6; 1 − 0,6 + 0,2 = 0,6; k = 1 / 0,6 ≈ 1,67."),
          K("Krzywa Laffera w liczbach",
            "Jeśli podstawa opodatkowania maleje wraz ze stawką, np. B = B₀(1 − t/T), wpływy T(t) = t·B są paraboliczne i osiągają maksimum przy połowie stawki zerującej podstawę. W praktyce kształt krzywej zależy od elastyczności podstawy."),
          K("Dlaczego mnożniki w Polsce są umiarkowane",
            "Polska to otwarta gospodarka (wysoki import) z istotnym obciążeniem podatkowym – przecieki są duże, więc mnożniki wydatkowe są wyraźnie mniejsze niż w prostym modelu zamkniętym."),
          PF("Wyższa stawka podatku proporcjonalnego zmniejsza mnożnik wydatkowy.", True,
             why="Zwiększa przecieki z obiegu."),
      ],
      mech=[
          LN("Ułóż liczenie mnożnika w gospodarce otwartej z podatkiem.",
             ["Policz c(1 − t)", "Odejmij od 1", "Dodaj krańcową skłonność do importu m", "Weź odwrotność: k = 1 / (…)", "Pomnóż przez zmianę wydatków, by dostać ΔY"],
             why="Systematyczne liczenie mnożnika."),
          KT("Mnożnik wzrośnie czy spadnie?",
             {"Wzrośnie": ["Wyższa krańcowa skłonność do konsumpcji", "Niższa krańcowa skłonność do importu", "Niższa stawka podatku"],
              "Spadnie": ["Wyższa skłonność do importu", "Wyższa stawka podatku", "Wyższa skłonność do oszczędzania"]},
             why="Przecieki zmniejszają mnożnik."),
          W("Ekspansja fiskalna +1,5% PKB, wypychanie −0,5% PKB, zacieśnienie monetarne −0,6% PKB. Ile wynosi efekt netto?",
            "Wzrost o 0,4% PKB", "Wzrost o 1,5% PKB", "Spadek o 0,4% PKB",
            why="1,5 − 0,5 − 0,6 = 0,4."),
          PF("Mnożnik podatku kwotowego jest co do wartości bezwzględnej mniejszy od mnożnika wydatkowego.", True,
             why="Część obniżki podatku jest oszczędzana lub wydawana na import."),
          M("Co zmniejsza skuteczność ekspansji fiskalnej?",
            ["Wypychanie przez wyższe stopy", "Wysoka skłonność do importu", "Wysoka skłonność do konsumpcji", "Równoczesne zacieśnienie monetarne"],
            [0, 1, 3],
            why="Wysoka skłonność do konsumpcji zwiększa mnożnik."),
          W("Stawka 70%, podstawa B = 1000 − 10t. Czy obniżka stawki do 60% zwiększy wpływy?",
            "Tak – z 210 do 240", "Nie – spadną", "Nie zmienią się",
            why="0,7 · 300 = 210; 0,6 · 400 = 240."),
      ],
      calc=[
          LB("c = 0,8, t = 0,25, m = 0,2. Ile wynosi mnożnik wydatkowy?",
             1.67, "1/(1-0.8*0.75+0.2)", ["c(1 − t) = 0,6", "1 − 0,6 + 0,2 = 0,6", "k ≈ 1,67"], unit="", tol=0.02),
          LB("Wydatki publiczne rosną o 30 mld zł. O ile wzrośnie PKB przy tym mnożniku (mld zł)?",
             50, "30/(1-0.8*0.75+0.2)", ["30 · 1,667 = 50 mld zł"], unit="mld zł"),
          LB("Podatek kwotowy spada o 30 mld zł (mnożnik podatkowy = −c · k). O ile wzrośnie PKB (mld zł)?",
             40, "0.8*30/(1-0.8*0.75+0.2)", ["0,8 · 1,667 = 1,333", "1,333 · 30 = 40 mld zł"], unit="mld zł"),
          LB("W gospodarce zamkniętej bez podatków (c = 0,8) mnożnik wynosi 5. Ile razy jest większy od mnożnika 1,67?",
             3, "5/(1/(1-0.8*0.75+0.2))", ["5 / 1,667 = 3"], unit="razy"),
          LB("Podstawa B = 1000 − 10t. Ile wynoszą wpływy przy stawce 40% (T = t/100 · B)?",
             240, "0.4*(1000-10*40)", ["B = 600", "T = 0,4 · 600 = 240"], unit=""),
          LB("Ile wynoszą maksymalne wpływy (przy t = 50%)?",
             250, "0.5*(1000-10*50)", ["B = 500", "T = 0,5 · 500 = 250"], unit=""),
      ],
      case=[
          PR("Rząd chce pobudzić gospodarkę kwotą 40 mld zł. Rozważa: (A) zwiększenie inwestycji publicznych o 40 mld zł albo (B) obniżkę podatków o 40 mld zł. Przyjmuje c = 0,8, t = 0,25, m = 0,2.",
             W("Który wariant daje większy przyrost PKB w modelu?",
               "A – inwestycje (ok. 66,7 mld zł wobec ok. 53,3 mld zł)", "B – obniżka podatków", "Oba tyle samo",
               why="Mnożnik wydatkowy ≈ 1,67, podatkowy ≈ 1,33."),
             W("Jaka jest dodatkowa zaleta wariantu A w długim okresie?",
               "Inwestycje mogą zwiększyć potencjał gospodarki", "Brak zalet", "Zawsze niższa inflacja",
               why="Infrastruktura podnosi produktywność."),
             PF("Wariant B może jednak działać szybciej, bo nie wymaga przygotowania projektów.", True,
                why="Obniżka podatków szybko zwiększa dochód rozporządzalny."),
          ),
          PR("Rząd zwiększa deficyt o 1,5% PKB, a bank centralny – obawiając się inflacji – podnosi stopy, co według modeli obniża PKB o 0,6%. Dodatkowo wyższe stopy wypychają część inwestycji prywatnych (−0,5% PKB).",
             W("Ile wynosi łączny efekt na PKB?",
               "Ok. 0,4% PKB", "1,5% PKB", "Zero",
               why="1,5 − 0,6 − 0,5 = 0,4."),
             W("Jak można opisać ten policy mix?",
               "Ekspansywna polityka fiskalna i restrykcyjna pieniężna – działają w przeciwnych kierunkach", "Obie polityki ekspansywne", "Obie restrykcyjne",
               why="Rząd pobudza, bank hamuje."),
             PF("Lepsza koordynacja mogłaby osiągnąć ten sam efekt na PKB przy niższym deficycie i niższych stopach.", True,
                why="Polityki nie „zwalczałyby” się nawzajem."),
          ),
      ]),
]
