# -*- coding: utf-8 -*-
# Zrozumienie – Polityka gospodarcza / Osoby
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
D = "2026-10-07"
S294 = S("OpenStax, Principles of Economics 3e, 29.4 Exchange Rate Policies", OS3 + "29-4-exchange-rate-policies", D)
S284 = S("OpenStax, Principles of Economics 3e, 28.4 Monetary Policy and Economic Outcomes", OS3 + "28-4-monetary-policy-and-economic-outcomes", D)
S253 = S("OpenStax, Principles of Economics 3e, 25.3 The Phillips Curve", OS3 + "25-3-the-phillips-curve", D)
S302 = S("OpenStax, Principles of Economics 3e, 30.2 Taxation", OS3 + "30-2-taxation", D)
S285 = S("OpenStax, Principles of Economics 3e, 28.5 Pitfalls for Monetary Policy", OS3 + "28-5-pitfalls-for-monetary-policy", D)
NOBL = S("Nobel Prize – All prizes in economic sciences (lista laureatów)", "https://www.nobelprize.org/prizes/lists/all-prizes-in-economic-sciences/", D)
BEZP = S("Bezprawnik – plan Balcerowicza", "https://bezprawnik.pl/plan-balcerowicza/", D)

LESSONS = [
    L(1, "Pieniądz, kurs i wspólna waluta: Hume, Mundell, Fleming, McKinnon, Kenen",
      "Łączyć z ideami ekonomistów badających pieniądz w gospodarce otwartej: mechanizm przepływu kruszców Hume’a, model Mundella–Fleminga i trylemat oraz kryteria optymalnego obszaru walutowego.",
      ["Hume David", "Mundell Robert, Fleming Marcus", "McKinnon Ronald, Kenen Peter"],
      [S294, NOBL],
      explain=[
          K("Hume i przepływ kruszców",
            "David Hume (XVIII w.) pokazał, że bilans handlowy sam się równoważy przy standardzie kruszcowym: nadwyżka handlowa → napływ złota → wzrost podaży pieniądza i cen w kraju → droższy eksport, tańszy import → nadwyżka znika. To argument przeciw merkantylistycznemu gromadzeniu złota i wczesna wersja teorii ilościowej pieniądza."),
          K("Mundell i Fleming",
            "Robert Mundell i Marcus Fleming (lata 60.) rozszerzyli model IS-LM o gospodarkę otwartą: przy mobilnym kapitale i kursie płynnym skuteczna jest polityka pieniężna, przy stałym – fiskalna. Stąd trylemat: stały kurs, swobodny kapitał i niezależna polityka pieniężna – można mieć tylko dwa. Mundell (Nobel 1999) nazywany jest „ojcem euro”."),
          W("Według mechanizmu Hume’a nadwyżka handlowa przy standardzie złota prowadzi do:",
            "Napływu złota, wzrostu cen i zaniku nadwyżki", "Trwałego bogacenia się kraju", "Spadku cen w kraju",
            why="Samoregulacja bilansu przez ceny."),
          K("McKinnon i Kenen",
            "Uzupełnili teorię optymalnego obszaru walutowego Mundella (1961): Ronald McKinnon (1963) – im bardziej otwarta gospodarka, tym mniej przydatny własny kurs i tym większe korzyści ze wspólnej waluty; Peter Kenen (1969) – gospodarki o zróżnicowanej produkcji są mniej narażone na szoki asymetryczne."),
          K("Znaczenie dziś",
            "Te idee leżą u podstaw debat o euro, wyborze systemu kursowego i kontroli kapitału. Polska z kursem płynnym i swobodnym kapitałem wybrała w trylemacie niezależną politykę pieniężną."),
          PF("Mechanizm Hume’a był argumentem na rzecz merkantylizmu.", False,
             why="Był argumentem przeciw – gromadzenie złota podnosi ceny i niszczy nadwyżkę."),
      ],
      mech=[
          LN("Ułóż mechanizm przepływu kruszców Hume’a.",
             ["Kraj ma nadwyżkę handlową", "Napływa złoto", "Rośnie ilość pieniądza i ceny w kraju", "Eksport drożeje, import tanieje", "Nadwyżka handlowa zanika"],
             why="Samoregulacja przez ceny i pieniądz."),
          KT("Kto jest autorem idei?",
             {"Hume": ["Samoregulacja bilansu handlowego przez przepływ kruszców"],
              "Mundell": ["Teoria optymalnego obszaru walutowego (1961)", "Trylemat polityki w gospodarce otwartej"],
              "McKinnon": ["Otwartość gospodarki jako kryterium OOW"],
              "Kenen": ["Zróżnicowanie produkcji jako kryterium OOW"]},
             why="Łączenie idei z autorami."),
          W("Który ekonomista otrzymał Nagrodę Nobla w 1999 r. za analizę polityki w gospodarce otwartej i obszarów walutowych?",
            "Robert Mundell", "John Taylor", "Dani Rodrik",
            why="Mundell – Nobel 1999."),
          PF("Według Kenena gospodarka produkująca wiele różnych dóbr jest mniej narażona na szoki asymetryczne.", True,
             why="Szok w jednej branży ma mniejszy wpływ na całość."),
          M("Które kryteria OOW sformułowali Mundell, McKinnon i Kenen?",
            ["Mobilność czynników produkcji", "Otwartość gospodarki", "Wysoka inflacja", "Zróżnicowanie produkcji"],
            [0, 1, 3],
            why="Wysoka inflacja nie jest kryterium OOW."),
          W("Który wybór w trylemacie zrobiła Polska?",
            "Swobodny przepływ kapitału i niezależna polityka pieniężna przy kursie płynnym", "Stały kurs i kontrola kapitału", "Stały kurs i swobodny kapitał",
            why="Kurs złotego jest płynny od 2000 r."),
      ],
      calc=[
          LB("Hume: kraj ma 1000 jednostek złota, napływa 200. Przy teorii ilościowej (V i Y stałe) o ile procent rosną ceny?",
             20, "200/1000*100", ["%ΔP = %ΔM = 20%"], unit="%"),
          LB("Eksport kosztował 100, a po wzroście cen krajowych o 20% – 120 (ceny zagraniczne bez zmian). Przy elastyczności eksportu −1,5 o ile procent spada wolumen eksportu?",
             30, "1.5*20", ["1,5 · 20% = 30%"], unit="%"),
          LB("McKinnon: eksport + import = 160% PKB, PKB = 100. Ile wynosi suma obrotów handlowych?",
             160, "1.6*100", ["160% · 100 = 160"], unit=""),
          LB("Mundell–Fleming (kurs płynny): ekspansja fiskalna +2% PKB, aprecjacja obniża eksport netto o 1,8% PKB. Ile wynosi efekt netto (% PKB)?",
             0.2, "2-1.8", ["2 − 1,8 = 0,2% PKB – polityka fiskalna słaba"], unit="%"),
          LB("Przy stałym kursie ekspansja fiskalna +2% PKB nie powoduje aprecjacji, a bank centralny zwiększa podaż pieniądza, by utrzymać kurs. Mnożnik 1,2. O ile rośnie PKB (%)?",
             2.4, "2*1.2", ["2 · 1,2 = 2,4% – polityka fiskalna skuteczna"], unit="%"),
          LB("Kenen: kraj eksportuje 3 produkty o udziałach 50%, 30% i 20%. Spadek popytu na pierwszy o 20% zmniejsza eksport o ile procent?",
             10, "0.5*20", ["0,5 · 20% = 10% – im większa koncentracja, tym silniejszy szok"], unit="%"),
      ],
      case=[
          PR("W latach 90. Robert Mundell przekonywał do wspólnej waluty europejskiej, a jego teoria z 1961 r. stała się punktem odniesienia w debacie o euro. Krytycy wskazywali, że strefa euro nie spełnia w pełni kryteriów OOW: mobilność pracy jest ograniczona, a transfery fiskalne małe.",
             W("Które kryterium OOW strefa euro spełnia najsłabiej według krytyków?",
               "Mobilność pracy i transfery fiskalne", "Otwartość handlowa", "Wspólna waluta",
               why="Bariery językowe i brak dużego wspólnego budżetu."),
             W("Które kryterium przemawia za euro dla małych, otwartych gospodarek (McKinnon)?",
               "Wysoka otwartość handlowa", "Niska otwartość", "Zamknięte granice",
               why="Dla otwartych gospodarek własny kurs jest mniej użyteczny."),
             PF("Mundell jest nazywany „ojcem euro”.", True,
                why="Za wkład teoretyczny w ideę wspólnej waluty."),
          ),
          PR("W XVIII w. merkantyliści zalecali gromadzenie złota przez nadwyżki handlowe. David Hume odpowiadał, że to niemożliwe w dłuższym okresie.",
             W("Dlaczego według Hume’a nadwyżka nie może trwać wiecznie?",
               "Napływ złota podnosi ceny, eksport traci konkurencyjność", "Bo złoto się zużywa", "Bo państwo zakazuje eksportu",
               why="Mechanizm cenowo-pieniężny przywraca równowagę."),
             W("Na jakiej teorii opierał się argument Hume’a?",
               "Na ilościowej teorii pieniądza", "Na teorii Keynesa", "Na krzywej Laffera",
               why="Więcej pieniądza (złota) oznacza wyższe ceny."),
             PF("Hume był jednym z pierwszych krytyków merkantylizmu.", True,
                why="Jego esej o bilansie handlowym poprzedził „Bogactwo narodów”."),
          ),
      ]),

    L(2, "Reguły, oczekiwania i podatki: Taylor, Kydland, Prescott, Phelps, Laffer",
      "Łączyć z ideami ekonomistów, którzy zmienili podejście do polityki makroekonomicznej: reguła Taylora, niespójność czasowa, naturalna stopa bezrobocia i krzywa Laffera.",
      ["Taylor John B.", "Kydland Finn, Prescott Edward", "Phelps Edmund", "Laffer Arthur"],
      [S284, S253, S302, NOBL],
      explain=[
          K("John B. Taylor",
            "Ekonomista ze Stanford; w 1993 r. zaproponował prostą regułę opisującą politykę Fed: stopa zależy od inflacji i luki PKB. Reguła Taylora stała się punktem odniesienia dla banków centralnych i rynków."),
          K("Kydland i Prescott",
            "Finn Kydland i Edward Prescott (Nobel 2004): niespójność czasowa polityki (1977) – uzasadnienie dla reguł i niezależnych banków centralnych; teoria realnego cyklu koniunkturalnego – wahania jako reakcja na szoki technologiczne."),
          W("Za jaki wkład Kydland i Prescott otrzymali Nagrodę Nobla?",
            "Za spójność czasową polityki i źródła cykli koniunkturalnych", "Za krzywą Laffera", "Za teorię OOW",
            why="Nagroda z 2004 r. za dynamiczną makroekonomię."),
          K("Edmund Phelps",
            "Niezależnie od Friedmana (koniec lat 60.) pokazał, że długookresowa krzywa Phillipsa jest pionowa na poziomie naturalnej stopy bezrobocia, a oczekiwania inflacyjne przesuwają krzywą krótkookresową. Nobel 2006."),
          K("Arthur Laffer",
            "Ekonomista ekonomii podaży; spopularyzował w latach 70. krzywą pokazującą, że zbyt wysokie stawki mogą zmniejszać wpływy podatkowe. Idea wpłynęła na obniżki podatków w USA w latach 80."),
          PF("Phelps i Friedman niezależnie od siebie skrytykowali stabilną, długookresową krzywą Phillipsa.", True,
             why="Obaj wskazali na rolę oczekiwań i naturalnej stopy bezrobocia."),
      ],
      mech=[
          KT("Kto jest autorem?",
             {"Taylor": ["Reguła stopy procentowej (1993)"],
              "Kydland i Prescott": ["Niespójność czasowa polityki", "Realny cykl koniunkturalny"],
              "Phelps": ["Naturalna stopa bezrobocia i oczekiwania"],
              "Laffer": ["Zależność wpływów od stawki podatku"]},
             why="Łączenie idei z autorami."),
          LN("Ułóż laureatów Nobla chronologicznie.",
             ["Mundell (1999)", "Stiglitz (2001)", "Kydland i Prescott (2004)", "Phelps (2006)", "Nordhaus i Romer (2018)"],
             why="Kolejne nagrody za badania polityki i makroekonomii."),
          W("Która idea uzasadnia niezależność banku centralnego?",
            "Niespójność czasowa (Kydland i Prescott)", "Krzywa Laffera", "Mechanizm Hume’a",
            why="Bank niezależny może wiarygodnie zobowiązać się do niskiej inflacji."),
          PF("Krzywa Laffera wykazuje, że obniżka podatków zawsze zwiększa wpływy.", False,
             why="Tylko gdy stawka przekracza poziom maksymalizujący wpływy."),
          M("Które idee wpłynęły na politykę pieniężną banków centralnych?",
            ["Reguła Taylora", "Niespójność czasowa", "Krzywa Laffera", "Naturalna stopa bezrobocia"],
            [0, 1, 3],
            why="Krzywa Laffera dotyczy polityki podatkowej."),
          W("Co według Phelpsa się dzieje, gdy bank trwale utrzymuje bezrobocie poniżej naturalnego?",
            "Inflacja przyspiesza, bo oczekiwania rosną", "Inflacja spada", "Nic",
            why="Akcelerująca inflacja – logika NAIRU."),
      ],
      calc=[
          LB("Reguła Taylora: r* = 2%, π = 6%, π* = 2%, luka 2%. Ile wynosi stopa (%)?",
             11, "2+6+0.5*4+0.5*2", ["2 + 6 + 2 + 1 = 11%"], unit="%"),
          LB("Phelps: π = πᵉ − 0,5(u − u*). πᵉ = 3%, u* = 5%, u = 4%. Ile wynosi inflacja (%)?",
             3.5, "3-0.5*(4-5)", ["3 + 0,5 = 3,5%"], unit="%"),
          LB("W kolejnym roku oczekiwania rosną do 3,5%, u nadal 4%. Ile wynosi inflacja (%)?",
             4, "3.5-0.5*(4-5)", ["3,5 + 0,5 = 4%"], unit="%"),
          LB("Laffer: podstawa B = 2000 − 25t. Ile wynoszą wpływy przy t = 40% (T = t/100 · B)?",
             400, "0.4*(2000-25*40)", ["B = 1000", "T = 0,4 · 1000 = 400"], unit=""),
          LB("Przy jakiej stawce (%) wpływy są maksymalne? (T = 20t − 0,25t², T′ = 20 − 0,5t)",
             40, "20/0.5", ["T′ = 0 ⇒ t = 40%"], unit="%"),
          LB("Kydland–Prescott: obiecana inflacja 2%, ale ludzie oczekują 6%. Przy u = 5 − 0,5(π − πᵉ) i faktycznej inflacji 6% ile wynosi bezrobocie (%)?",
             5, "5-0.5*(6-6)", ["π = πᵉ – bezrobocie naturalne 5%, ale inflacja wyższa o 4 p.p."], unit="%"),
      ],
      case=[
          PR("W latach 60. XX w. politycy w USA wierzyli, że mogą trwale obniżyć bezrobocie, akceptując wyższą inflację. Edmund Phelps i Milton Friedman ostrzegali, że to złudzenie. W latach 70. inflacja i bezrobocie wzrosły jednocześnie.",
             W("Która idea Phelpsa wyjaśnia porażkę tej polityki?",
               "Naturalna stopa bezrobocia i dostosowanie oczekiwań inflacyjnych", "Krzywa Laffera", "Mechanizm Hume’a",
               why="Bezrobocie wraca do naturalnego, a inflacja zostaje wyższa."),
             W("Jak wygląda długookresowa krzywa Phillipsa według Phelpsa?",
               "Jest pionowa", "Jest opadająca", "Jest pozioma",
               why="Brak długookresowej wymiany."),
             PF("Phelps otrzymał Nagrodę Nobla w 2006 r.", True,
                why="Za analizę międzyokresowych kompromisów w polityce makroekonomicznej."),
          ),
          PR("Bank centralny wraz z publikacją decyzji pokazuje wykres porównujący stopę referencyjną z kilkoma wariantami reguły Taylora. Komentatorzy uznają, że ułatwia to przewidywanie przyszłych decyzji.",
             W("Jaką rolę pełni tu reguła Taylora?",
               "Punktu odniesienia i narzędzia komunikacji", "Prawnego obowiązku", "Narzędzia polityki fiskalnej",
               why="Pomaga zrozumieć logikę decyzji."),
             W("Jak to wiąże się z ideami Kydlanda i Prescotta?",
               "Przewidywalność wzmacnia wiarygodność i stabilizuje oczekiwania", "Nie ma związku", "Zwiększa niespójność czasową",
               why="Jasne reguły ograniczają pokusę zaskakiwania."),
             PF("Reguła Taylora pierwotnie opisywała politykę Rezerwy Federalnej.", True,
                why="Taylor dopasował ją do decyzji Fed z lat 1987–1992."),
          ),
      ]),

    L(3, "Państwo, rynki i ich krytycy: Buchanan, Downs, Stiglitz, Rodrik, Williamson, Minsky",
      "Łączyć z ideami ekonomistów badających granice skuteczności państwa i rynków: wybór publiczny, ekonomiczna teoria demokracji, zawodności rynku, konsensus waszyngtoński i jego krytyka oraz niestabilność finansowa.",
      ["Buchanan James", "Downs Anthony", "Stiglitz Joseph", "Rodrik Dani", "Williamson John", "Minsky Hyman"],
      [S285, NOBL],
      explain=[
          K("Buchanan i Downs",
            "James Buchanan (Nobel 1986) – teoria wyboru publicznego: politycy i urzędnicy kierują się własnym interesem, więc państwo też może zawodzić; postulował konstytucyjne ograniczenia polityki fiskalnej. Anthony Downs („Ekonomiczna teoria demokracji”, 1957) – partie maksymalizują głosy, programy zbiegają się do wyborcy medianowego, a wyborcy są racjonalnie nieświadomi."),
          K("Williamson i Rodrik",
            "John Williamson sformułował w 1989 r. konsensus waszyngtoński – 10 zaleceń dla krajów rozwijających się. Dani Rodrik krytykował jego uniwersalność („jedno lekarstwo dla wszystkich”) i sformułował trylemat globalizacji: nie da się jednocześnie mieć hiperglobalizacji, suwerenności narodowej i demokracji."),
          W("Kto sformułował trylemat globalizacji?",
            "Dani Rodrik", "John Williamson", "Anthony Downs",
            why="Hiperglobalizacja, suwerenność, demokracja – dwa z trzech."),
          K("Stiglitz",
            "Joseph Stiglitz (Nobel 2001) – ekonomia informacji (odsiewanie, płace efektywnościowe – model Shapiro–Stiglitza), krytyka MFW i sposobu prowadzenia globalizacji („Globalizacja”, 2002), argumenty za aktywną rolą państwa przy zawodnościach rynku."),
          K("Minsky",
            "Hyman Minsky – hipoteza niestabilności finansowej: okresy stabilności zachęcają do coraz ryzykowniejszego finansowania (zabezpieczone → spekulacyjne → Ponziego), co prowadzi do kryzysów. Postulował regulacje i rolę banku centralnego jako pożyczkodawcy ostatniej instancji. Po 2008 r. mówiono o „momencie Minsky’ego”."),
          PF("Buchanan uważał, że politycy zawsze działają wyłącznie dla dobra wspólnego.", False,
             why="Zakładał, że kierują się także własnym interesem."),
      ],
      mech=[
          KT("Kto jest autorem idei?",
             {"Buchanan": ["Teoria wyboru publicznego", "Konstytucyjne ograniczenia deficytu"],
              "Downs": ["Twierdzenie o wyborcy medianowym w polityce"],
              "Williamson": ["Konsensus waszyngtoński"],
              "Rodrik": ["Trylemat globalizacji"],
              "Minsky": ["Finansowanie Ponziego i niestabilność finansowa"],
              "Stiglitz": ["Krytyka MFW w kryzysie azjatyckim"]},
             why="Łączenie idei z autorami."),
          LN("Ułóż cykl Minsky’ego.",
             ["Okres stabilności i optymizmu", "Rośnie zadłużenie i lewarowanie", "Przewaga finansowania spekulacyjnego i Ponziego", "Spadek cen aktywów lub wzrost stóp", "Wymuszona sprzedaż i kryzys"],
             why="Stabilność rodzi niestabilność."),
          W("Czym, według Rodrika, trzeba zapłacić za hiperglobalizację przy zachowaniu demokracji?",
            "Ograniczeniem suwerenności narodowej (np. ponadnarodowe reguły)", "Niczym", "Wprowadzeniem standardu złota",
            why="Trylemat: można mieć tylko dwa z trzech."),
          PF("Stiglitz krytykował programy MFW w kryzysie azjatyckim jako zbyt restrykcyjne.", True,
             why="Uważał, że cięcia i wysokie stopy pogłębiły recesję."),
          M("Którzy ekonomiści otrzymali Nagrodę Nobla?",
            ["Buchanan", "Stiglitz", "Minsky", "Kydland"],
            [0, 1, 3],
            why="Minsky nie otrzymał Nobla (zmarł w 1996 r.)."),
          W("Jakie rozwiązanie proponował Buchanan wobec skłonności polityków do deficytów?",
            "Konstytucyjne reguły fiskalne", "Brak jakichkolwiek reguł", "Druk pieniądza",
            why="Ograniczenia na poziomie konstytucji wiążą przyszłych polityków."),
      ],
      calc=[
          LB("Downs: wyborcy na osi lewica–prawica mają preferencje 2, 3, 5, 7, 9. Jaką pozycję zajmie zwycięski program (mediana)?",
             5, "5", ["Uporządkowane: 2, 3, 5, 7, 9", "Mediana = 5"], unit=""),
          LB("Buchanan: subsydium daje 5 firmom po 40 mln zł, a 25 mln podatników płaci po 10 zł. Ile wynosi łączny koszt dla podatników (mln zł)?",
             250, "25*10", ["25 mln · 10 zł = 250 mln zł"], unit="mln zł"),
          LB("Ile wynosi strata netto (koszt − korzyści firm, mln zł)?",
             50, "250-5*40", ["250 − 200 = 50 mln zł"], unit="mln zł"),
          LB("Minsky: inwestor ma dochód z najmu 24 tys. zł, odsetki 30 tys. zł rocznie. O ile tys. zł dochód nie pokrywa odsetek (finansowanie Ponziego)?",
             6, "30-24", ["30 − 24 = 6 tys. zł"], unit="tys. zł"),
          LB("Stiglitz–Shapiro: płaca rynkowa 25 zł/godz., firma płaci 30 zł/godz., by zniechęcić do bumelowania. O ile procent wyższa jest płaca efektywnościowa?",
             20, "(30/25-1)*100", ["30 / 25 − 1 = 20%"], unit="%"),
          LB("Konsensus waszyngtoński: deficyt ma spaść z 8% do 2% PKB w 3 lata równymi krokami. O ile p.p. rocznie?",
             2, "(8-2)/3", ["6 / 3 = 2 p.p."], unit="p.p."),
      ],
      case=[
          PR("W 1997 r. MFW udzielił pomocy krajom Azji Wschodniej pod warunkiem zacieśnienia polityki fiskalnej i podwyżek stóp. Joseph Stiglitz, wówczas główny ekonomista Banku Światowego, krytykował te warunki, a Dani Rodrik podważał uniwersalność zaleceń konsensusu waszyngtońskiego.",
             W("Co łączyło krytykę Stiglitza i Rodrika?",
               "Sprzeciw wobec jednakowych recept niezależnie od warunków kraju", "Poparcie dla hiperinflacji", "Postulat zniesienia MFW",
               why="Reformy powinny uwzględniać instytucje i sytuację kraju."),
             W("Kto sformułował konsensus waszyngtoński?",
               "John Williamson", "Joseph Stiglitz", "Hyman Minsky",
               why="Sformułował go w 1989 r., zbierając 10 zaleceń."),
             PF("Stiglitz był głównym ekonomistą Banku Światowego pod koniec lat 90.", True,
                why="W latach 1997–2000."),
          ),
          PR("Jesienią 2008 r. upadek Lehman Brothers zapoczątkował panikę na rynkach finansowych. Wielu komentatorów nazwało ten moment „momentem Minsky’ego”, przypominając prace ekonomisty, który za życia był mało znany w głównym nurcie.",
             W("Co według Minsky’ego poprzedza taki kryzys?",
               "Długi okres stabilności, który zachęca do ryzykownego zadłużania się", "Okres recesji i niskiego zadłużenia", "Wysokie podatki",
               why="„Stabilność rodzi niestabilność”."),
             W("Jaką rolę przypisywał Minsky bankowi centralnemu?",
               "Pożyczkodawcy ostatniej instancji, zatrzymującego panikę", "Wyłącznie walki z inflacją", "Żadnej",
               why="Dostarczanie płynności w kryzysie."),
             PF("Polityka makroostrożnościowa (np. limity LTV) jest współczesną odpowiedzią na problemy opisane przez Minsky’ego.", True,
                why="Ogranicza narastanie ryzykownego finansowania."),
          ),
      ]),

    L(4, "Polska myśl ekonomiczna: Kalecki, Lange, Łaski, Osiatyński",
      "Łączyć z ideami polskich ekonomistów: teorię efektywnego popytu i cyklu Kaleckiego, polityczny cykl koniunkturalny, socjalizm rynkowy Langego oraz kontynuację myśli Kaleckiego przez Łaskiego i Osiatyńskiego.",
      ["Kalecki Michał", "Lange Oskar", "Łaski Kazimierz", "Osiatyński Jerzy"],
      [S("OpenStax, Principles of Economics 3e, 25.1 Aggregate Demand in Keynesian Analysis", OS3 + "25-1-aggregate-demand-in-keynesian-analysis", D), S285],
      explain=[
          K("Michał Kalecki",
            "Michał Kalecki (1899–1970) w 1933 r. – niezależnie od Keynesa i przed „Ogólną teorią” – sformułował teorię efektywnego popytu: produkcję i zatrudnienie wyznaczają wydatki, zwłaszcza inwestycje. Opracował teorię cyklu koniunkturalnego, a w 1943 r. – polityczny aspekt pełnego zatrudnienia: przedsiębiorcy mogą sprzeciwiać się trwałemu pełnemu zatrudnieniu, bo osłabia ono dyscyplinę pracy. Badał też wzrost gospodarki socjalistycznej."),
          K("Równanie zysków Kaleckiego",
            "W uproszczonej gospodarce (zamkniętej, bez państwa, robotnicy nie oszczędzają): zyski = inwestycje + konsumpcja kapitalistów – „robotnicy wydają to, co zarabiają, kapitaliści zarabiają to, co wydają”.",
            w="Π = I + Cₖ"),
          W("Co Kalecki sformułował niezależnie od Keynesa?",
            "Teorię efektywnego popytu", "Prawo Saya", "Teorię przewagi komparatywnej",
            why="Prace z początku lat 30. XX w."),
          K("Oskar Lange",
            "Oskar Lange (1904–1965) – w sporze o kalkulację ekonomiczną w socjalizmie zaproponował model „socjalizmu rynkowego”: planista ustala ceny metodą prób i błędów, reagując na nadwyżki i niedobory, jak gdyby był rynkiem. Rozwijał też ekonometrię i cybernetykę."),
          K("Łaski i Osiatyński",
            "Kazimierz Łaski (1921–2015) – uczeń Kaleckiego, postkeynesista, wykładał w Linzu i współpracował z wiedeńskim instytutem wiiw. Jerzy Osiatyński (1941–2022) – wydawca dzieł Kaleckiego, minister–kierownik Centralnego Urzędu Planowania (1989–1991), minister finansów (1992–1993), członek RPP (2013–2019)."),
          PF("Lange uważał, że planista może naśladować rynek, korygując ceny w reakcji na nadwyżki i niedobory.", True,
             why="To istota modelu socjalizmu rynkowego."),
      ],
      mech=[
          KT("Kto jest autorem lub głównym propagatorem idei?",
             {"Kalecki": ["Efektywny popyt przed Keynesem", "Polityczny aspekt pełnego zatrudnienia"],
              "Lange": ["Socjalizm rynkowy", "Ceny ustalane metodą prób i błędów przez planistę"],
              "Łaski": ["Postkeynesowska kontynuacja myśli Kaleckiego w Austrii"],
              "Osiatyński": ["Wydanie dzieł zebranych Kaleckiego", "Kierowanie Centralnym Urzędem Planowania 1989–1991"]},
             why="Łączenie idei z autorami."),
          LN("Ułóż mechanizm cenowy w modelu Langego.",
             ["Planista ustala ceny początkowe", "Obserwuje nadwyżki i niedobory", "Podnosi ceny dóbr deficytowych", "Obniża ceny dóbr nadwyżkowych", "Powtarza aż do zrównania podaży z popytem"],
             why="Metoda prób i błędów."),
          W("Dlaczego według Kaleckiego przedsiębiorcy mogą sprzeciwiać się trwałemu pełnemu zatrudnieniu?",
            "Trwałe pełne zatrudnienie osłabia dyscyplinę pracy i wzmacnia pozycję pracowników", "Bo zwiększa ich zyski", "Bo obniża płace",
            why="To polityczny aspekt pełnego zatrudnienia (1943)."),
          PF("Polityczny cykl koniunkturalny był analizowany przez Kaleckiego, a później przez Nordhausa.", True,
             why="Kalecki – 1943, Nordhaus – 1975."),
          M("Które idee wiążą się z Kaleckim?",
            ["Zyski zależą od inwestycji i konsumpcji kapitalistów", "Teoria cyklu koniunkturalnego", "Krzywa Laffera", "Wzrost gospodarki socjalistycznej"],
            [0, 1, 3],
            why="Krzywa Laffera to idea ekonomii podaży."),
          W("W jakim sporze uczestniczył Oskar Lange w latach 30.?",
            "O kalkulację ekonomiczną w socjalizmie (z Misesem i Hayekiem)", "O standard złota", "O euro",
            why="Lange bronił możliwości racjonalnego planowania."),
      ],
      calc=[
          LB("Kalecki: inwestycje 300, konsumpcja kapitalistów 120. Ile wynoszą zyski?",
             420, "300+120", ["Π = I + Cₖ = 420"], unit=""),
          LB("Inwestycje spadają o 60. O ile spadną zyski (przy stałej konsumpcji kapitalistów)?",
             60, "60", ["ΔΠ = ΔI = 60 – spadek inwestycji bezpośrednio obniża zyski"], unit=""),
          LB("Model Langego: przy cenie 10 popyt na dobro wynosi 120, a podaż 80. Planista podnosi cenę o 0,05 zł za każdą jednostkę niedoboru. Ile wyniesie nowa cena?",
             12, "10+0.05*(120-80)", ["Niedobór: 40", "10 + 0,05 · 40 = 12"], unit="zł"),
          LB("Popyt Q = 180 − 6P, podaż Q = 4P + 40. Ile wynosi cena równowagi, do której powinien dojść planista?",
             14, "140/10", ["180 − 6P = 4P + 40", "P = 14"], unit="zł"),
          LB("Ile lat minęło od pracy Kaleckiego o efektywnym popycie (1933) do „Ogólnej teorii” Keynesa (1936)?",
             3, "1936-1933", ["1936 − 1933 = 3 lata"], unit="lat"),
          LB("Osiatyński był członkiem RPP w latach 2013–2019. Ile lat trwała jego kadencja?",
             6, "2019-2013", ["2019 − 2013 = 6 lat – pełna kadencja członka RPP"], unit="lat"),
      ],
      case=[
          PR("W 1943 r. Michał Kalecki opublikował artykuł „Political Aspects of Full Employment”. Twierdził, że choć rząd potrafi utrzymać pełne zatrudnienie wydatkami, przedsiębiorcy mogą temu się sprzeciwiać, co prowadzi do cyklu: przed wyborami pobudzanie gospodarki, po wyborach cięcia.",
             W("Jakie zjawisko opisał Kalecki?",
               "Polityczny cykl koniunkturalny", "Pułapkę płynności", "Paradoks Leontiefa",
               why="Wahania wynikające z decyzji politycznych."),
             W("Kto rozwinął tę ideę w latach 70. w wersji z wyborami?",
               "William Nordhaus", "Arthur Laffer", "Robert Mundell",
               why="Model z 1975 r."),
             PF("Kalecki uważał, że problem pełnego zatrudnienia jest nie tylko ekonomiczny, ale i polityczny.", True,
                why="Interesy grup społecznych wpływają na politykę."),
          ),
          PR("W latach 30. Ludwig von Mises twierdził, że w socjalizmie bez rynkowych cen środków produkcji racjonalny rachunek jest niemożliwy. Oskar Lange odpowiedział modelem, w którym planista ustala ceny i koryguje je w zależności od nadwyżek i niedoborów.",
             W("Jaki był kluczowy argument Langego?",
               "Planista może naśladować mechanizm rynkowy metodą prób i błędów", "Ceny są niepotrzebne", "Rynek zawsze zawodzi",
               why="Socjalizm rynkowy."),
             W("Jaki zarzut stawiał temu modelowi Hayek?",
               "Planista nie ma dostępu do rozproszonej wiedzy i nie zmienia cen tak szybko jak rynek", "Że model jest zbyt rynkowy", "Że ceny są zbyt elastyczne",
               why="Problem wiedzy i bodźców."),
             PF("Spór o kalkulację ekonomiczną jest jednym z najważniejszych sporów w historii ekonomii XX w.", True,
                why="Dotyczył podstaw działania gospodarki planowej."),
          ),
      ]),

    L(5, "Polityka gospodarcza Polski w osobach: Kwiatkowski, Sadowski, Mazowiecki, Balcerowicz",
      "Łączyć postacie z kluczowymi etapami polskiej polityki gospodarczej: etatyzmem II RP (Gdynia, COP), reformami lat 80., rządem Mazowieckiego i planem Balcerowicza.",
      ["Kwiatkowski Eugeniusz (1888–1974)", "Sadowski Zdzisław", "Mazowiecki Tadeusz", "Balcerowicz Leszek"],
      [BEZP, S("OpenStax, Principles of Economics 3e, 1.4 How To Organize Economies", OS3 + "1-4-how-to-organize-economies-an-overview-of-economic-systems", D)],
      explain=[
          K("Eugeniusz Kwiatkowski",
            "Minister przemysłu i handlu w latach 20. – budowa portu w Gdyni i floty handlowej; wicepremier i minister skarbu (1935–1939) – Centralny Okręg Przemysłowy (od 1936 r.): inwestycje państwowe w przemysł ciężki i zbrojeniowy w widłach Wisły i Sanu, z dala od granic. Przykład etatyzmu i polityki inwestycyjnej państwa w II RP."),
          K("Zdzisław Sadowski",
            "Ekonomista, wicepremier ds. reformy gospodarczej (1987–1988) – drugi etap reformy w PRL (częściowe urynkowienie, porządkowanie cen). Wieloletni prezes Polskiego Towarzystwa Ekonomicznego (od 1985 r.). Reformy nie powstrzymały jednak narastającego kryzysu."),
          W("Z jaką inwestycją II RP wiąże się nazwisko Eugeniusza Kwiatkowskiego?",
            "Budową Gdyni i Centralnego Okręgu Przemysłowego", "Planem Balcerowicza", "Wprowadzeniem euro",
            why="Gdynia (lata 20.) i COP (1936–1939)."),
          K("Tadeusz Mazowiecki",
            "Pierwszy niekomunistyczny premier po 1989 r. (wrzesień 1989 – styczeń 1991). Jego rząd przyjął program stabilizacji i reform gospodarczych, stworzył podstawy prawne przemian (m.in. samorząd terytorialny w 1990 r.) i przeprowadził pierwsze miesiące terapii szokowej."),
          K("Leszek Balcerowicz",
            "Wicepremier i minister finansów (1989–1991 i 1997–2000), autor programu transformacji wprowadzonego od 1 stycznia 1990 r. (stabilizacja i liberalizacja), później prezes NBP (2001–2007). Zwolennik szybkich reform rynkowych i dyscypliny fiskalnej; krytycy wskazują na wysokie koszty społeczne pierwszych lat transformacji."),
          PF("Leszek Balcerowicz był prezesem NBP w latach 2001–2007.", True,
             why="Po pełnieniu funkcji wicepremiera i ministra finansów."),
      ],
      mech=[
          LN("Ułóż wydarzenia chronologicznie.",
             ["Budowa portu w Gdyni (lata 20.)", "Centralny Okręg Przemysłowy (od 1936 r.)", "Drugi etap reformy Sadowskiego (1987–1988)", "Rząd Mazowieckiego (od września 1989 r.)", "Plan Balcerowicza (od 1 stycznia 1990 r.)"],
             why="Od etatyzmu II RP do transformacji."),
          KT("Kto odpowiadał za politykę?",
             {"Kwiatkowski": ["COP", "Budowa Gdyni"],
              "Sadowski": ["Drugi etap reformy gospodarczej PRL"],
              "Mazowiecki": ["Pierwszy niekomunistyczny rząd po 1989 r."],
              "Balcerowicz": ["Program stabilizacji od 1 stycznia 1990 r.", "Prezes NBP 2001–2007"]},
             why="Łączenie postaci z polityką."),
          W("Dlaczego COP lokowano w widłach Wisły i Sanu?",
            "Z dala od granic, ze względów bezpieczeństwa, oraz w regionie z nadwyżką siły roboczej", "Bo tam był port morski", "Przypadkowo",
            why="Względy strategiczne i społeczne."),
          PF("Reformy Sadowskiego z lat 1987–1988 doprowadziły do pełnego urynkowienia gospodarki.", False,
             why="Były częściowe – pełne urynkowienie przyniósł dopiero 1990 r."),
          M("Jakie elementy zawierał program rządu Mazowieckiego i Balcerowicza?",
            ["Uwolnienie większości cen", "Ograniczenie deficytu budżetowego", "Zakaz prywatnej działalności", "Wewnętrzna wymienialność złotego"],
            [0, 1, 3],
            why="Prywatną działalność rozwijano, nie zakazywano."),
          W("Jaki model polityki gospodarczej reprezentował COP?",
            "Etatyzm – państwo jako główny inwestor w przemyśle", "Leseferyzm", "Monetaryzm",
            why="Inwestycje państwowe w przemysł ciężki."),
      ],
      calc=[
          LB("Ile lat minęło od rozpoczęcia budowy COP (1936) do planu Balcerowicza (1990)?",
             54, "1990-1936", ["1990 − 1936 = 54 lata"], unit="lat"),
          LB("Przyjmijmy, że COP miał kosztować 2,4 mld zł przedwojennych w ciągu 4 lat, a budżet państwa wynosił ok. 2,5 mld zł rocznie. Jaki procent rocznego budżetu stanowiła roczna rata (%)?",
             24, "(2.4/4)/2.5*100", ["2,4 / 4 = 0,6 mld rocznie", "0,6 / 2,5 = 24% (dane umowne)"], unit="%"),
          LB("Kurs ustalony w planie Balcerowicza: 9500 starych zł za dolara. Po denominacji (1995 r., 10 000 : 1) ile to nowych złotych?",
             0.95, "9500/10000", ["9500 / 10 000 = 0,95 zł"], unit="zł"),
          LB("Bezrobocie wzrosło z 6,5% (1990) do 16,4% (1993). O ile p.p.?",
             9.9, "16.4-6.5", ["16,4 − 6,5 = 9,9 p.p."], unit="p.p."),
          LB("Inflacja 1990 r.: 585,8%, 1991 r.: 70,3%. O ile p.p. spadła?",
             515.5, "585.8-70.3", ["585,8 − 70,3 = 515,5 p.p."], unit="p.p."),
          LB("Balcerowicz kierował NBP w latach 2001–2007. Ile lat trwała kadencja prezesa NBP?",
             6, "2007-2001", ["2007 − 2001 = 6 lat"], unit="lat"),
      ],
      case=[
          PR("W 1936 r. wicepremier Eugeniusz Kwiatkowski ogłosił czteroletni plan inwestycyjny, którego najważniejszą częścią był Centralny Okręg Przemysłowy. Powstały m.in. huta w Stalowej Woli i zakłady w Mielcu i Rzeszowie. Wybuch wojny przerwał realizację planu.",
             W("Jaki rodzaj polityki ilustruje COP?",
               "Etatyzm i planowanie inwestycji przez państwo w gospodarce rynkowej", "Leseferyzm", "Terapię szokową",
               why="Państwo jako główny inwestor."),
             W("Jakie cele miał COP?",
               "Obronność, uprzemysłowienie i zmniejszenie bezrobocia na przeludnionej wsi", "Wyłącznie eksport surowców", "Likwidację przemysłu",
               why="Cele strategiczne i społeczne."),
             PF("Część zakładów COP działa do dziś (np. w Stalowej Woli i Mielcu).", True,
                why="Ośrodki przemysłowe przetrwały i rozwinęły się po wojnie."),
          ),
          PR("We wrześniu 1989 r. Tadeusz Mazowiecki tworzy rząd, a Leszek Balcerowicz zostaje wicepremierem i ministrem finansów. W ciągu kilku miesięcy rząd przygotowuje pakiet ustaw, który wchodzi w życie 1 stycznia 1990 r. Wcześniej, w latach 1987–1988, wicepremier Zdzisław Sadowski próbował reform w ramach systemu socjalistycznego.",
             W("Czym różnił się plan Balcerowicza od reform Sadowskiego?",
               "Zmieniał system – szybka stabilizacja i pełna liberalizacja zamiast częściowych korekt", "Niczym", "Przywracał planowanie centralne",
               why="Reformy lat 80. były częściowe."),
             W("Dlaczego rząd działał tak szybko?",
               "Hiperinflacja i kryzys wymagały pilnej stabilizacji, a sytuacja polityczna dawała okno na reformy", "Bo nie było inflacji", "Bo wymagała tego UE",
               why="Okno możliwości politycznych i presja kryzysu."),
             PF("Rząd Mazowieckiego był pierwszym niekomunistycznym rządem po 1989 r.", True,
                why="Powołany we wrześniu 1989 r."),
          ),
      ]),
]
