# -*- coding: utf-8 -*-
# Zrozumienie – Polityka gospodarcza / Instytucje
D = "2026-10-07"
OS3 = "https://openstax.org/books/principles-economics-3e/pages/"
EUI = S("Unia Europejska – instytucje i organy UE (european-union.europa.eu)", "https://european-union.europa.eu/institutions-law-budget/institutions-and-bodies/search-all-eu-institutions-and-bodies_pl", D)
EUH = S("Unia Europejska – historia UE (european-union.europa.eu)", "https://european-union.europa.eu/principles-countries-history/history-eu_pl", D)
EDPA = S("Analizy.pl – Rada UE wszczęła procedurę nadmiernego deficytu wobec Polski", "https://www.analizy.pl/puls-rynku/35415/rada-ue-wszczela-procedure-nadmiernego-deficytu-wobec-polski", D)
KONST = S("Konstytucja RP (art. 219–225 – budżet) – tekst, Dz.U. 1997 nr 78 poz. 483 (Sejm, ELI)", "https://api.sejm.gov.pl/eli/acts/DU/1997/483/text.pdf", D)
S344 = S("OpenStax, Principles of Economics 3e, 34.4 How Governments Enact Trade Policy", OS3 + "34-4-how-governments-enact-trade-policy-globally-regionally-and-nationally", D)

LESSONS = [
    L(1, "Instytucje UE i nadzór nad finansami",
      "Rozumieć podział ról między Komisją Europejską, Radą UE, Radą Europejską i Parlamentem Europejskim w procesie stanowienia prawa i nadzoru fiskalnego oraz rolę Eurostatu i Europejskiego Mechanizmu Stabilności.",
      ["Instytucje UE", "Komisja Europejska", "Rada Unii Europejskiej i Rada Europejska", "Parlament Europejski", "Europejski Urząd Statystyczny (Eurostat)", "Europejski Mechanizm Stabilności (EMS)"],
      [EUI, EDPA],
      explain=[
          K("Trójkąt instytucjonalny",
            "Komisja Europejska – organ wykonawczy z (co do zasady wyłącznym) prawem inicjatywy ustawodawczej; „strażniczka traktatów”, prowadzi politykę konkurencji i handlową. Parlament Europejski – wybierany bezpośrednio co 5 lat, współprawodawca i władza budżetowa. Rada UE (ministrowie państw) – współprawodawca; w składzie ECOFIN decyduje m.in. o procedurze nadmiernego deficytu."),
          K("Rada Europejska",
            "Szefowie państw i rządów oraz przewodniczący Rady Europejskiej i Komisji – wyznacza ogólne kierunki polityczne UE, nie stanowi prawa. Nie mylić z Radą UE (ministrowie) ani z Radą Europy (organizacja spoza UE)."),
          W("Kto ma w UE prawo inicjatywy ustawodawczej?",
            "Komisja Europejska", "Rada Europejska", "Europejski Bank Centralny",
            why="Komisja przygotowuje projekty aktów prawnych."),
          K("Eurostat",
            "Urząd statystyczny UE: publikuje zharmonizowane dane – HICP, PKB (także wg PPS), deficyt i dług w ramach notyfikacji fiskalnej (EDP). Na danych Eurostatu opiera się ocena kryteriów konwergencji i procedury nadmiernego deficytu."),
          K("Europejski Mechanizm Stabilności",
            "Fundusz ratunkowy strefy euro (od 2012 r., zastąpił tymczasowy EFSF): udziela pożyczek państwom strefy euro w trudnościach finansowych, pod warunkiem programu dostosowawczego. Korzystały z niego m.in. Hiszpania (dokapitalizowanie banków), Cypr i Grecja."),
          PF("Rada Europejska jest współprawodawcą razem z Parlamentem Europejskim.", False,
             why="Współprawodawcą jest Rada UE (ministrowie); Rada Europejska wyznacza kierunki polityczne."),
      ],
      mech=[
          LN("Ułóż zwykłą procedurę ustawodawczą UE.",
             ["Komisja Europejska przedstawia projekt", "Parlament Europejski przyjmuje stanowisko", "Rada UE przyjmuje stanowisko", "Uzgodnienie wspólnego tekstu", "Publikacja aktu w Dzienniku Urzędowym UE"],
             why="Komisja inicjuje, Parlament i Rada stanowią."),
          KT("Która instytucja?",
             {"Komisja Europejska": ["Nakłada kary na kartele w UE", "Proponuje nowe rozporządzenie"],
              "Rada UE (ECOFIN)": ["Stwierdza nadmierny deficyt w państwie członkowskim"],
              "Parlament Europejski": ["Wybierany w wyborach bezpośrednich", "Zatwierdza budżet UE"],
              "Eurostat": ["Publikuje HICP i dane o deficycie"]},
             why="Każda instytucja ma inną rolę."),
          W("Na podstawie czyich danych ocenia się deficyt i dług w procedurze nadmiernego deficytu?",
            "Eurostatu (notyfikacja fiskalna)", "Banków komercyjnych", "Giełd",
            why="Eurostat weryfikuje dane przekazywane przez urzędy krajowe."),
          PF("Europejski Mechanizm Stabilności udziela pomocy pod warunkiem realizacji programu dostosowawczego.", True,
             why="Pomoc jest warunkowa."),
          M("Które instytucje są współprawodawcami w UE?",
            ["Parlament Europejski", "Rada UE", "Rada Europy", "Oba organy wspólnie w zwykłej procedurze"],
            [0, 1, 3],
            why="Rada Europy nie jest instytucją UE."),
          W("Kto nakłada w UE kary za kartele obejmujące wiele państw?",
            "Komisja Europejska", "Parlament Europejski", "Eurostat",
            why="Komisja prowadzi politykę konkurencji."),
      ],
      calc=[
          LB("Parlament Europejski wybierany jest co 5 lat; wybory odbyły się w 2024 r. W którym roku następne?",
             2029, "2024+5", ["2024 + 5 = 2029"], unit=""),
          LB("Kara Komisji za kartel: maksymalnie 10% światowego obrotu. Obrót firmy 4 mld euro. Ile wynosi maksymalna kara (mln euro)?",
             400, "0.1*4000", ["10% · 4000 mln = 400 mln euro"], unit="mln euro"),
          LB("Kraj otrzymuje pożyczkę z EMS 10 mld euro na 15 lat z równymi spłatami kapitału. Ile wynosi roczna rata kapitałowa (mln euro)?",
             666.67, "10000/15", ["10 000 / 15 ≈ 666,67 mln euro"], unit="mln euro", tol=0.01),
          LB("HICP: indeks 118,0 w zeszłym roku i 122,7 obecnie. Ile wynosi inflacja HICP (%)?",
             3.98, "(122.7/118-1)*100", ["122,7 / 118 − 1 ≈ 3,98%"], unit="%", tol=0.02),
          LB("Notyfikacja: deficyt 284 mld zł przy PKB 3890 mld zł. Ile wynosi deficyt (% PKB)?",
             7.3, "284/3890*100", ["284 / 3890 ≈ 7,3%"], unit="%", tol=0.02),
          LB("Komisja Europejska liczy po jednym komisarzu z każdego z 27 państw. Ilu komisarzy jest poza przewodniczącą (przewodniczącym) Komisji?",
             26, "27-1", ["27 − 1 = 26"], unit=""),
      ],
      case=[
          PR("W lipcu 2024 r. Komisja Europejska zarekomendowała, a Rada UE (ECOFIN) zdecydowała o otwarciu procedury nadmiernego deficytu wobec kilku państw, w tym Polski. Dane o deficytach pochodziły z notyfikacji fiskalnych weryfikowanych przez Eurostat.",
             W("Jaki był podział ról?",
               "Komisja – ocena i rekomendacja, Rada UE – decyzja, Eurostat – dane", "Parlament – decyzja, Eurostat – kary", "EBC – decyzja",
               why="Taki jest przebieg procedury."),
             W("Która instytucja wydaje państwu zalecenia z terminem korekty deficytu?",
               "Rada UE na wniosek Komisji", "Parlament Europejski", "Eurostat",
               why="Rada przyjmuje zalecenia w ramach EDP."),
             PF("Eurostat może zgłaszać zastrzeżenia do jakości danych fiskalnych przekazanych przez państwo.", True,
                why="Weryfikuje notyfikacje i metodologię."),
          ),
          PR("W 2012 r. Hiszpania otrzymała z europejskich funduszy ratunkowych pożyczkę na dokapitalizowanie banków dotkniętych pęknięciem bańki na rynku nieruchomości. Warunkiem była restrukturyzacja sektora bankowego.",
             W("Jaka instytucja strefy euro udziela takiej pomocy dziś?",
               "Europejski Mechanizm Stabilności", "Eurostat", "Parlament Europejski",
               why="EMS to stały fundusz ratunkowy strefy euro."),
             W("Dlaczego pomoc jest warunkowa?",
               "By ograniczyć pokusę nadużycia i przywrócić stabilność", "By ukarać obywateli", "Bez powodu",
               why="Warunki mają usunąć źródło problemu."),
             PF("EMS zastąpił tymczasowy fundusz EFSF.", True,
                why="EMS działa od 2012 r."),
          ),
      ]),

    L(2, "Rada Ministrów, budżet państwa oraz G7 i G20",
      "Rozumieć rolę Rady Ministrów w procesie budżetowym (terminy, rola Sejmu, Prezydenta i Trybunału Konstytucyjnego) oraz rolę nieformalnych forów G7 i G20.",
      ["Rada Ministrów", "Grupa G7 i G20"],
      [KONST, S344],
      explain=[
          K("Rada Ministrów i budżet",
            "Rząd opracowuje projekt ustawy budżetowej i przedkłada go Sejmowi najpóźniej do 30 września roku poprzedzającego rok budżetowy. Sejm uchwala budżet (Senat może zgłosić poprawki), Prezydent podpisuje lub kieruje ustawę do Trybunału Konstytucyjnego (TK orzeka w ciągu 2 miesięcy). Rząd wykonuje budżet i składa sprawozdanie z jego wykonania."),
          K("Ochrona budżetu",
            "Prezydent może skrócić kadencję Sejmu, jeśli w ciągu 4 miesięcy od przedłożenia projektu nie zostanie mu przedstawiona ustawa budżetowa do podpisu. Sejm nie może uchwalić wyższego deficytu niż przewidziany w projekcie rządowym."),
          W("Do kiedy Rada Ministrów musi przedłożyć Sejmowi projekt ustawy budżetowej?",
            "Do 30 września roku poprzedzającego", "Do 31 grudnia", "Do 1 maja",
            why="Termin z art. 222 Konstytucji."),
          K("G7 i G20",
            "G7 – nieformalne forum siedmiu dużych, rozwiniętych gospodarek (USA, Japonia, Niemcy, Wielka Brytania, Francja, Włochy, Kanada; UE uczestniczy w spotkaniach). G20 – 19 państw (w tym Chiny, Indie, Brazylia), UE i Unia Afrykańska; od kryzysu 2008 r. główne forum koordynacji polityki gospodarczej. Polska nie należy do żadnej z tych grup."),
          K("Znaczenie forów",
            "G7 i G20 nie stanowią prawa, ale uzgadniają wspólne stanowiska, np. pakiety antykryzysowe z 2009 r., minimalny globalny podatek od korporacji czy sankcje. Ich decyzje realizują potem państwa i organizacje (MFW, OECD)."),
          PF("Sejm może uchwalić deficyt wyższy niż przewidziany w rządowym projekcie budżetu.", False,
             why="Konstytucja (art. 220) tego zabrania."),
      ],
      mech=[
          LN("Ułóż etapy procedury budżetowej w Polsce.",
             ["Rada Ministrów przygotowuje projekt", "Projekt trafia do Sejmu do 30 września", "Sejm i Senat uchwalają ustawę budżetową", "Prezydent podpisuje lub kieruje ustawę do TK", "Rząd wykonuje budżet i składa sprawozdanie"],
             why="Procedura z rozdziału X Konstytucji."),
          KT("G7, G20 czy żadna?",
             {"G7 (i G20)": ["Japonia", "Kanada", "Włochy"],
              "Tylko G20": ["Chiny", "Indie", "Brazylia"],
              "Żadna": ["Polska"]},
             why="G7 to część G20."),
          W("Co może zrobić Prezydent, jeśli ustawa budżetowa nie zostanie mu przedstawiona w ciągu 4 miesięcy od przedłożenia projektu?",
            "Zarządzić skrócenie kadencji Sejmu", "Sam uchwalić budżet", "Nic",
            why="Art. 225 Konstytucji."),
          PF("G20 stało się głównym forum koordynacji gospodarczej po kryzysie 2008 r.", True,
             why="Spotkania na szczeblu przywódców od 2008 r."),
          M("Które działania koordynowano na forum G20?",
            ["Pakiety antykryzysowe w 2009 r.", "Globalny minimalny podatek od korporacji", "Ustalanie stóp procentowych NBP", "Wzmocnienie regulacji finansowych po 2008 r."],
            [0, 1, 3],
            why="Stopy NBP ustala RPP."),
          W("Kto wykonuje budżet państwa w Polsce?",
            "Rada Ministrów", "Narodowy Bank Polski", "Trybunał Konstytucyjny",
            why="Rząd wykonuje budżet, Sejm go kontroluje."),
      ],
      calc=[
          LB("Projekt budżetu przedłożono Sejmowi 30 września. Po ilu miesiącach Prezydent może skrócić kadencję Sejmu, jeśli nie otrzyma ustawy (podaj liczbę miesięcy)?",
             4, "4", ["Art. 225 Konstytucji: 4 miesiące"], unit="mies."),
          LB("Rząd planuje dochody 650 mld zł i wydatki 940 mld zł. Ile wynosi deficyt budżetu państwa (mld zł)?",
             290, "940-650", ["940 − 650 = 290 mld zł (dane umowne)"], unit="mld zł"),
          LB("Sejm chce zwiększyć wydatki o 10 mld zł. O ile musi zwiększyć dochody lub obniżyć inne wydatki, by nie podnieść deficytu (mld zł)?",
             10, "10", ["Deficyt nie może przekroczyć projektu rządowego – kompensata 10 mld zł"], unit="mld zł"),
          LB("Globalny minimalny podatek od korporacji uzgodniony na forum OECD/G20 wynosi 15%. Firma płaci efektywnie 9% od zysku 500 mln euro. Ile wynosi podatek wyrównawczy (mln euro)?",
             30, "(0.15-0.09)*500", ["6 p.p. · 500 = 30 mln euro"], unit="mln euro"),
          LB("G20 obejmuje 19 państw, UE i Unię Afrykańską. Ilu członków liczy łącznie?",
             21, "19+2", ["19 + 2 = 21"], unit=""),
          LB("TK ma 2 miesiące na orzeczenie w sprawie ustawy budżetowej. Ustawę skierowano 15 stycznia. Do jakiego dnia marca TK powinien orzec (podaj dzień)?",
             15, "15", ["15 stycznia + 2 miesiące = 15 marca"], unit=""),
      ],
      case=[
          PR("Rada Ministrów przyjęła projekt budżetu na kolejny rok i przekazała go Sejmowi 30 września. Posłowie opozycji proponują zwiększenie wydatków na ochronę zdrowia o 15 mld zł, bez wskazania nowych dochodów.",
             W("Czy Sejm może przyjąć taką poprawkę bez zmiany deficytu?",
               "Tylko jeśli wskaże źródło finansowania – deficyt nie może przekroczyć projektu rządu", "Tak, bez ograniczeń", "Nie, Sejm nie może zmieniać budżetu",
               why="Art. 220 Konstytucji."),
             W("Kto może skierować uchwaloną ustawę budżetową do Trybunału Konstytucyjnego przed podpisaniem?",
               "Prezydent", "Komisja Europejska", "NBP",
               why="TK ma wtedy 2 miesiące na orzeczenie."),
             PF("Konstytucja chroni stabilność budżetu, ograniczając możliwość zwiększania deficytu przez Sejm.", True,
                why="Decyzja o poziomie deficytu należy do rządu."),
          ),
          PR("W kwietniu 2009 r. na szczycie G20 w Londynie przywódcy uzgodnili m.in. zwiększenie zasobów MFW i wspólne działania na rzecz pobudzenia gospodarki światowej po kryzysie finansowym.",
             W("Dlaczego to G20, a nie G7, stało się głównym forum w 2009 r.?",
               "Gospodarki wschodzące (np. Chiny) miały już duże znaczenie dla światowej gospodarki", "Bo G7 przestało istnieć", "Bo Polska wstąpiła do G20",
               why="Bez dużych gospodarek wschodzących koordynacja byłaby niepełna."),
             W("Jak decyzje G20 są wprowadzane w życie?",
               "Przez państwa członkowskie i organizacje międzynarodowe (np. MFW)", "G20 uchwala wiążące ustawy", "Przez Eurostat",
               why="G20 to forum nieformalne."),
             PF("Polska nie jest członkiem G20.", True,
                why="Członkami są 19 państw, UE i Unia Afrykańska."),
          ),
      ]),
]
