# -*- coding: utf-8 -*-
# Zrozumienie – Zarządzanie / Motywacja, przywództwo i zespoły
OSM = "https://openstax.org/books/principles-management/pages/"
D = "2026-10-08"
M135 = S("OpenStax, Principles of Management, 13.5 Behavioral Approaches to Leadership", OSM + "13-5-behavioral-approaches-to-leadership", D)
M134 = S("OpenStax, Principles of Management, 13.4 The Trait Approach to Leadership", OSM + "13-4-the-trait-approach-to-leadership", D)
M136 = S("OpenStax, Principles of Management, 13.6 Situational (Contingency) Approaches to Leadership", OSM + "13-6-situational-contingency-approaches-to-leadership", D)
M138 = S("OpenStax, Principles of Management, 13.8 Transformational, Visionary, and Charismatic Leadership", OSM + "13-8-transformational-visionary-and-charismatic-leadership", D)
M142 = S("OpenStax, Principles of Management, 14.2 Content Theories of Motivation", OSM + "14-2-content-theories-of-motivation", D)
M143 = S("OpenStax, Principles of Management, 14.3 Process Theories of Motivation", OSM + "14-3-process-theories-of-motivation", D)
M152 = S("OpenStax, Principles of Management, 15.2 Team Development Over Time", OSM + "15-2-team-development-over-time", D)
M153 = S("OpenStax, Principles of Management, 15.3 Things to Consider When Managing Teams", OSM + "15-3-things-to-consider-when-managing-teams", D)
M162 = S("OpenStax, Principles of Management, 16.2 Types of Communications in Organizations", OSM + "16-2-types-of-communications-in-organizations", D)

KJ78 = S("S. Kerr, J. Jermier, Substitutes for leadership: Their meaning and measurement, OBHP 22(3), 1978 (DOI)", "https://doi.org/10.1016/0030-5073(78)90023-5", D)
LO68 = S("E. Locke, Toward a theory of task motivation and incentives, OBHP 3(2), 1968 (DOI)", "https://doi.org/10.1016/0030-5073(68)90004-4", D)
WOPC = S("Wikipedia – Operant conditioning", "https://en.wikipedia.org/wiki/Operant_conditioning", D)
WEMP = S("Wikipedia – Empowerment", "https://en.wikipedia.org/wiki/Empowerment", D)
WPSC = S("Wikipedia – Psychological contract", "https://en.wikipedia.org/wiki/Psychological_contract", D)
RO89 = S("D. Rousseau, Psychological and implied contracts in organizations, ERRJ 2(2), 1989 (DOI)", "https://doi.org/10.1007/bf01384942", D)
WOCB = S("Wikipedia – Organizational citizenship behavior", "https://en.wikipedia.org/wiki/Organizational_citizenship_behavior", D)
WCOH = S("Wikipedia – Group cohesiveness", "https://en.wikipedia.org/wiki/Group_cohesiveness", D)

OBO = "https://openstax.org/books/organizational-behavior/pages/"
OB24 = S("OpenStax, Organizational Behavior, 2.4 Personality and Work Behavior", OBO + "2-4-personality-and-work-behavior", D)
OB32 = S("OpenStax, Organizational Behavior, 3.2 Barriers to Accurate Social Perception", OBO + "3-2-barriers-to-accurate-social-perception", D)
OB182 = S("OpenStax, Organizational Behavior, 18.2 Organizational Influences on Stress", OBO + "18-2-organizational-influences-on-stress", D)
WB5 = S("Wikipedia – Big Five personality traits", "https://en.wikipedia.org/wiki/Big_Five_personality_traits", D)
WGAS = S("Wikipedia – General adaptation syndrome", "https://en.wikipedia.org/wiki/General_adaptation_syndrome", D)
WHALO = S("Wikipedia – Halo effect", "https://en.wikipedia.org/wiki/Halo_effect", D)
OB171 = S("OpenStax, Organizational Behavior, 17.1 An Introduction to Human Resource Management", OBO + "17-1-an-introduction-to-human-resource-management", D)
OB173 = S("OpenStax, Organizational Behavior, 17.3 Performance Management", OBO + "17-3-performance-management", D)
OB144 = S("OpenStax, Organizational Behavior, 14.4 Negotiation Behavior", OBO + "14-4-negotiation-behavior", D)
WGTY = S("Wikipedia – Getting to Yes (R. Fisher, W. Ury, 1981)", "https://en.wikipedia.org/wiki/Getting_to_Yes", D)
WBATNA = S("Wikipedia – Best alternative to a negotiated agreement", "https://en.wikipedia.org/wiki/Best_alternative_to_a_negotiated_agreement", D)
WAL = S("Wikipedia – Active listening", "https://en.wikipedia.org/wiki/Active_listening", D)
WAS = S("Wikipedia – Assertiveness", "https://en.wikipedia.org/wiki/Assertiveness", D)

LESSONS = [
    L(1, "Treściowe teorie motywacji",
      "Rozumieć, czym jest motywacja, i porównywać teorie potrzeb: hierarchię Maslowa, teorię ERG Alderfera, dwuczynnikową teorię Herzberga i teorię potrzeb McClellanda.",
      ["Motywacja", "Hierarchia potrzeb Maslowa", "Teoria ERG (C. Alderfer)", "Dwuczynnikowa teoria Herzberga", "Teoria potrzeb McClellanda"],
      [M142],
      explain=[
          K("Motywacja",
            "Motywacja to procesy, które nadają zachowaniu kierunek (na co się wysilamy), intensywność (jak bardzo) i trwałość (jak długo). Teorie treści pytają, CO motywuje (jakie potrzeby), teorie procesu – JAK powstaje motywacja (oczekiwania, porównania, cele). Wynik pracy zależy od motywacji, zdolności i warunków."),
          K("Maslow (1943) i Alderfer",
            "Maslow: potrzeby fizjologiczne → bezpieczeństwa → przynależności → uznania → samorealizacji; niezaspokojona potrzeba niższa dominuje, a zaspokojona przestaje motywować. Alderfer (ERG) upraszcza do trzech grup: egzystencji, relacji i rozwoju; kilka potrzeb może działać naraz, a frustracja potrzeby wyższej kieruje człowieka z powrotem ku niższej (frustracja–regresja)."),
          W("Pracownik, który nie ma szans na awans, zaczyna mocno zabiegać o podwyżki i dobre relacje. Którą zasadę to ilustruje?",
            "Frustracja–regresja w teorii ERG", "Hierarchię Maslowa w ścisłej kolejności", "Teorię X McGregora",
            why="Zablokowany rozwój kieruje uwagę ku potrzebom niższym."),
          K("Herzberg (1959)",
            "Czynniki higieny (płaca, warunki pracy, polityka firmy, nadzór, relacje) – ich brak wywołuje niezadowolenie, ale ich obecność nie motywuje, tylko usuwa niezadowolenie. Motywatory (osiągnięcia, uznanie, sama praca, odpowiedzialność, rozwój) – wywołują zadowolenie i motywację. Wniosek: wzbogacanie pracy."),
          K("McClelland",
            "Trzy wyuczone potrzeby: osiągnięć (nAch – ambitne, ale realne cele, informacja zwrotna), władzy (nPow – wpływ na innych; władza instytucjonalna sprzyja kierowaniu) i przynależności (nAff – relacje, akceptacja). Osoby o wysokiej nAch są dobrymi przedsiębiorcami, ale niekoniecznie menedżerami dużych firm."),
          PF("Według Herzberga podwyżka płacy sama w sobie trwale motywuje pracownika.", False,
             why="Płaca to czynnik higieny – usuwa niezadowolenie, nie motywuje."),
      ],
      mech=[
          KT("Czynnik higieny czy motywator (Herzberg)?",
             {"Czynnik higieny": ["Wysokość wynagrodzenia", "Warunki pracy w biurze", "Relacje z przełożonym"],
              "Motywator": ["Uznanie za osiągnięcia", "Odpowiedzialność za projekt", "Możliwość rozwoju"]},
             why="Higiena usuwa niezadowolenie, motywatory budują zadowolenie."),
          LN("Ułóż poziomy hierarchii Maslowa od najniższego.",
             ["Potrzeby fizjologiczne", "Potrzeby bezpieczeństwa", "Potrzeby przynależności", "Potrzeby uznania", "Potrzeba samorealizacji"],
             why="Kolejność od podstawowych do najwyższych."),
          W("Pracownik o wysokiej potrzebie osiągnięć (McClelland) najchętniej wybierze:",
            "Ambitne, ale realne zadanie z szybką informacją o wynikach", "Zadanie bardzo łatwe", "Zadanie praktycznie niewykonalne",
            why="nAch preferuje umiarkowane ryzyko i feedback."),
          W("Czym teoria ERG różni się od teorii Maslowa?",
            "Kilka potrzeb może działać jednocześnie i możliwa jest regresja", "Ma więcej poziomów", "Ignoruje potrzeby rozwoju",
            why="Alderfer odrzucił sztywną kolejność."),
          M("Które potrzeby wyróżnia McClelland?",
            ["Osiągnięć", "Władzy", "Przynależności", "Fizjologiczne"], [0, 1, 2],
            why="Potrzeby fizjologiczne to poziom Maslowa."),
          PF("Teorie treści pytają, jakie potrzeby motywują ludzi.", True,
             why="Teorie procesu pytają, jak powstaje motywacja."),
      ],
      calc=[
          LB("W badaniu 200 pracowników 70 wskazało rozwój jako najważniejszy czynnik. Jaki to procent?",
             35, "70/200*100", ["70 / 200 = 35%"], unit="%"),
          LB("Podwyżka 8% podnosi zadowolenie, ale po roku wskaźnik wraca z 72 do 65 pkt (przed podwyżką 64). Ile punktów trwałego wzrostu zostało?",
             1, "65-64", ["65 − 64 = 1 pkt"], unit="pkt"),
          LB("Maslow opublikował teorię w 1943 r., Herzberg w 1959 r. Ile lat różnicy?",
             16, "1959-1943", ["1959 − 1943 = 16"], unit="lat"),
          LB("Ile poziomów potrzeb mniej ma teoria ERG niż hierarchia Maslowa (5 poziomów)?",
             2, "5-3", ["5 − 3 = 2"], unit="poz."),
          LB("Program uznania kosztuje 50 000 zł rocznie i obniża odejścia o 5 osób; zastąpienie pracownika kosztuje 30 000 zł. Ile wynosi oszczędność netto (zł)?",
             100000, "5*30000-50000", ["5 · 30 000 − 50 000 = 100 000 zł"], unit="zł"),
          LB("Zespół 12 osób: 3 o dominującej potrzebie władzy, 5 – osiągnięć, reszta – przynależności. Jaki odsetek ma potrzebę przynależności (%)?",
             33.33, "(12-3-5)/12*100", ["4 / 12 ≈ 33,33%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Firma podniosła płace o 10%, ale ankieta pokazuje, że pracownicy nadal czują się niedocenieni i nie widzą możliwości rozwoju. Rotacja się nie zmniejszyła.",
             W("Jak teoria Herzberga wyjaśnia sytuację?",
               "Płaca to czynnik higieny – brakuje motywatorów: uznania i rozwoju", "Płace były wciąż za niskie", "Pracownicy mają za dużo odpowiedzialności",
               why="Usunięto niezadowolenie, ale nie zbudowano motywacji."),
             W("Co powinna wprowadzić firma?",
               "Ścieżki rozwoju, uznanie i więcej odpowiedzialności", "Kolejną podwyżkę", "Ścisłą kontrolę",
               why="To motywatory według Herzberga."),
             PF("Podwyżka mogła zapobiec jeszcze większemu niezadowoleniu.", True,
                why="Czynniki higieny ograniczają niezadowolenie."),
          ),
          PR("Kierowniczka zespołu sprzedaży zauważa: Anna lubi rywalizację i cele z wyraźnym wynikiem, Bartek chętnie wpływa na decyzje i prowadzi spotkania, a Celina najlepiej pracuje w zgranej grupie i źle znosi konflikty.",
             W("Jaką potrzebę dominującą ma Bartek?",
               "Władzy", "Osiągnięć", "Przynależności",
               why="Chce wpływać na innych i decyzje."),
             W("Jakie zadanie najlepiej zmotywuje Annę?",
               "Indywidualny, mierzalny cel sprzedażowy z szybkim feedbackiem", "Organizację imprezy firmowej", "Zadanie bez określonego wyniku",
               why="Wysoka potrzeba osiągnięć."),
             PF("Celinę najlepiej motywuje praca zespołowa i dobra atmosfera.", True,
                why="Ma wysoką potrzebę przynależności."),
          ),
      ]),

    L(2, "Procesowe teorie motywacji i wynagradzanie",
      "Rozumieć teorię oczekiwań Vrooma, teorię sprawiedliwości Adamsa i teorię wyznaczania celów oraz projektować system motywacyjny i wynagrodzeń.",
      ["Teoria oczekiwań (V. Vroom)", "Teoria sprawiedliwości (J.S. Adams)", "Systemy motywacyjne i wynagrodzeń", "Motywacja"],
      [M143, M142],
      explain=[
          K("Teoria oczekiwań (Vroom, 1964)",
            "Motywacja = oczekiwanie (E: czy wysiłek da wynik) × instrumentalność (I: czy wynik da nagrodę) × walencja (V: jak cenię nagrodę). Ponieważ to iloczyn, zero w którymkolwiek elemencie oznacza brak motywacji. Menedżer powinien: zapewnić zasoby i szkolenia (E), dotrzymywać obietnic nagród (I), dobierać nagrody cenione przez pracownika (V).",
            w="M = E · I · V"),
          K("Teoria sprawiedliwości (Adams, 1963)",
            "Pracownik porównuje stosunek swoich efektów (płaca, uznanie) do nakładów (wysiłek, kwalifikacje, czas) z takim stosunkiem innych osób. Przy poczuciu niedopłacenia obniża wysiłek, żąda podwyżki, zmienia punkt odniesienia lub odchodzi. Liczy się postrzegana, nie obiektywna sprawiedliwość.",
            w="efekty A / nakłady A  vs  efekty B / nakłady B"),
          W("E = 0,9, I = 0, V = 1. Ile wynosi motywacja według Vrooma?",
            "Zero – pracownik nie wierzy, że wynik da nagrodę", "0,9", "1,9",
            why="Iloczyn z czynnikiem zerowym wynosi zero."),
          K("Teoria wyznaczania celów (Locke)",
            "Cele konkretne i trudne (ale akceptowane) dają lepsze wyniki niż „rób, co możesz”. Warunki: zaangażowanie w cel, informacja zwrotna, odpowiednie zdolności. Praktyka: cele SMART i zarządzanie przez cele (MBO)."),
          K("System wynagrodzeń",
            "Składniki: płaca zasadnicza (wartościowanie stanowisk), premie i prowizje (za wyniki), świadczenia (opieka medyczna, PPK, karta sportowa), nagrody niefinansowe (uznanie, rozwój, elastyczność). Dobry system jest postrzegany jako sprawiedliwy (wewnętrznie i wobec rynku) i jasno łączy wynik z nagrodą. Uwaga: zbyt silne premie mogą zachęcać do „gry” wskaźnikami."),
          PF("W teorii sprawiedliwości Adamsa liczy się subiektywne poczucie sprawiedliwości.", True,
             why="Pracownik reaguje na to, jak postrzega porównanie."),
      ],
      mech=[
          KT("Który element teorii Vrooma?",
             {"Oczekiwanie (E)": ["„Jeśli się postaram, osiągnę cel sprzedaży”", "Szkolenie zwiększające umiejętności"],
              "Instrumentalność (I)": ["„Jeśli osiągnę cel, firma naprawdę wypłaci premię”", "Dotrzymywanie obietnic przez kierownika"],
              "Walencja (V)": ["„Bardzo zależy mi na dodatkowym dniu wolnym”", "Nagroda dobrana do preferencji pracownika"]},
             why="Każdy element wymaga innego działania menedżera."),
          LN("Ułóż reakcję na poczucie niedopłacenia według Adamsa.",
             ["Pracownik porównuje swoje efekty i nakłady z kolegą", "Stwierdza, że kolega dostaje więcej za ten sam wysiłek", "Odczuwa napięcie i niesprawiedliwość", "Obniża wysiłek lub domaga się podwyżki", "Gdy nic się nie zmienia, szuka innej pracy"],
             why="Niesprawiedliwość wywołuje działania korygujące."),
          W("Pracownik wie, że premie są przyznawane według uznania szefa, a nie wyników. Który element Vrooma jest niski?",
            "Instrumentalność", "Oczekiwanie", "Walencja",
            why="Wynik nie przekłada się wiarygodnie na nagrodę."),
          W("Który cel jest najlepszy według teorii Locke’a?",
            "Zwiększyć sprzedaż o 12% do końca kwartału", "Starać się sprzedawać więcej", "Robić, co się da",
            why="Cel konkretny, trudny i mierzalny."),
          M("Jak pracownik może zareagować na poczucie niedopłacenia?",
            ["Obniżyć wysiłek", "Zażądać podwyżki", "Zmienić osobę, z którą się porównuje", "Zawsze zwiększyć wysiłek"], [0, 1, 2],
            why="Zwiększenie wysiłku to typowa reakcja na nadpłacenie."),
          PF("Zbyt silne premie za jeden wskaźnik mogą prowadzić do manipulowania wynikami.", True,
             why="Pracownicy optymalizują mierzony wskaźnik kosztem innych celów."),
      ],
      calc=[
          LB("E = 0,8, I = 0,5, V = 0,9. Ile wynosi M według Vrooma?",
             0.36, "0.8*0.5*0.9", ["0,8 · 0,5 · 0,9 = 0,36"], unit="", tol=0.001),
          LB("Po wprowadzeniu jasnych zasad premii I rośnie do 0,9 (E = 0,8, V = 0,9). Ile wynosi M?",
             0.648, "0.8*0.9*0.9", ["0,8 · 0,9 · 0,9 = 0,648"], unit="", tol=0.001),
          LB("Anna zarabia 7 200 zł za 40 h, Bartek 6 000 zł za 40 h. Ile zł za godzinę dostaje Anna więcej?",
             30, "7200/40-6000/40", ["180 − 150 = 30 zł/h"], unit="zł/h"),
          LB("Płaca zasadnicza 6 000 zł, premia 15% płacy zasadniczej. Ile wynosi wynagrodzenie (zł)?",
             6900, "6000*1.15", ["6 000 · 1,15 = 6 900 zł"], unit="zł"),
          LB("Prowizja 3% od sprzedaży 180 000 zł i podstawa 4 500 zł. Ile wynosi wynagrodzenie (zł)?",
             9900, "4500+0.03*180000", ["4 500 + 5 400 = 9 900 zł"], unit="zł"),
          LB("Cel sprzedaży 500 000 zł, wykonanie 560 000 zł. Ile procent celu wykonano?",
             112, "560000/500000*100", ["560 / 500 = 112%"], unit="%"),
      ],
      case=[
          PR("Handlowcy mają premię za przekroczenie celu, ale cele są ustalane tak wysoko, że w ostatnich trzech latach osiągnęło je tylko 5% osób. Motywacja zespołu spada.",
             W("Który element teorii Vrooma jest najsłabszy?",
               "Oczekiwanie – ludzie nie wierzą, że osiągną cel", "Walencja – nikt nie chce pieniędzy", "Żaden",
               why="Cel postrzegany jako nieosiągalny."),
             W("Co zaleca teoria wyznaczania celów?",
               "Cele trudne, ale osiągalne i akceptowane", "Cele jak najwyższe", "Rezygnację z celów",
               why="Cel nieakceptowany nie motywuje."),
             PF("Obniżenie celu do realnego poziomu może zwiększyć łączną sprzedaż.", True,
                why="Więcej osób podejmie wysiłek."),
          ),
          PR("Nowo zatrudniony programista dostał wynagrodzenie o 20% wyższe niż doświadczeni koledzy na tym samym stanowisku. Informacja wyciekła. Dwóch seniorów zaczęło szukać pracy, a jeden ograniczył się do minimum.",
             W("Jaką teorię ilustruje reakcja seniorów?",
               "Teorię sprawiedliwości Adamsa", "Hierarchię Maslowa", "Teorię cech przywódczych",
               why="Porównują stosunek efektów do nakładów."),
             W("Jakie działanie firmy jest najbardziej sensowne?",
               "Przegląd i wyrównanie płac według przejrzystych zasad", "Zwolnienie nowego pracownika", "Ukrywanie płac",
               why="Przywraca poczucie sprawiedliwości wewnętrznej."),
             PF("Unijna dyrektywa o przejrzystości wynagrodzeń wzmacnia znaczenie sprawiedliwości płacowej.", True,
                why="Dyrektywa 2023/970 nakłada obowiązki jawności płac."),
          ),
      ]),

    L(3, "Przywództwo: cechy, style i siatka kierownicza",
      "Odróżniać przywództwo od kierowania, rozumieć teorie cech i podejście behawioralne: style Lewina, cztery systemy Likerta oraz siatkę kierowniczą Blake’a i Mouton.",
      ["Przywództwo", "Teorie cech przywódczych", "Style kierowania: autokratyczny, demokratyczny, liberalny", "Systemy zarządzania R. Likerta", "Siatka kierownicza (Blake i Mouton)"],
      [M134, M135],
      explain=[
          K("Przywództwo a kierowanie",
            "Przywództwo to zdolność wpływania na ludzi, by dobrowolnie dążyli do celów. Kierownik ma władzę formalną (z pozycji), przywódca może też mieć władzę osobistą. Źródła władzy (French i Raven): nagradzania, przymusu, prawomocna (formalna), ekspercka i odniesienia (charyzma, sympatia)."),
          K("Teorie cech",
            "Najstarsze podejście szukało wrodzonych cech „wielkich ludzi”. Badania wskazują związek z przywództwem m.in. inteligencji, pewności siebie, determinacji, uczciwości i ekstrawersji, ale same cechy słabo przewidują skuteczność – liczy się zachowanie i sytuacja."),
          W("Podwładni słuchają głównej księgowej, bo ma ogromną wiedzę o podatkach, choć nie jest ich szefową. To władza:",
            "Ekspercka", "Przymusu", "Prawomocna",
            why="Wpływ wynika z wiedzy, nie ze stanowiska."),
          K("Style kierowania (Lewin) i Likert",
            "Lewin: autokratyczny (szef decyduje sam), demokratyczny (konsultuje i angażuje), liberalny/laissez-faire (pozostawia swobodę). Likert opisał cztery systemy: 1 – autorytarny eksploatatorski, 2 – autorytarny życzliwy, 3 – konsultacyjny, 4 – partycypacyjny (grupowy); najlepsze wyniki dawał system 4."),
          K("Siatka kierownicza (Blake i Mouton, 1964)",
            "Dwa wymiary w skali 1–9: troska o produkcję (zadania) i troska o ludzi. Style: 1.1 zubożały, 1.9 „klub towarzyski”, 9.1 zadaniowy (władza–posłuszeństwo), 5.5 środka drogi, 9.9 zespołowy – za najlepszy uznany 9.9 (wysoka troska o oba wymiary). Badania Ohio i Michigan opisywały podobne wymiary: inicjowanie struktury i względy dla ludzi."),
          PF("W siatce Blake’a i Mouton styl 1.9 to wysoka troska o ludzi przy niskiej trosce o zadania.", True,
             why="To styl „klubu towarzyskiego”."),
      ],
      mech=[
          KT("Styl w siatce kierowniczej",
             {"9.1 zadaniowy": ["Liczą się tylko terminy i normy, ludzie mają wykonywać polecenia"],
              "1.9 klub towarzyski": ["Przede wszystkim miła atmosfera, wyniki są drugorzędne"],
              "1.1 zubożały": ["Kierownik robi minimum, by utrzymać stanowisko"],
              "9.9 zespołowy": ["Wysokie cele osiągane dzięki zaangażowaniu zespołu"],
              "5.5 środka drogi": ["Kompromis: przyzwoite wyniki i umiarkowane morale"]},
             why="Kombinacje troski o zadania i o ludzi."),
          LN("Ułóż systemy Likerta od najbardziej autorytarnego.",
             ["System 1 – autorytarny eksploatatorski", "System 2 – autorytarny życzliwy", "System 3 – konsultacyjny", "System 4 – partycypacyjny"],
             why="Rośnie udział pracowników w decyzjach."),
          W("Kierownik ogłasza decyzję bez pytania zespołu o zdanie. Jaki to styl według Lewina?",
            "Autokratyczny", "Demokratyczny", "Liberalny",
            why="Decyzja podjęta jednoosobowo."),
          W("Dlaczego teorie cech okazały się niewystarczające?",
            "Same cechy słabo przewidują skuteczność w różnych sytuacjach", "Nie ma żadnych cech osobowości", "Bo badały tylko kobiety",
            why="Skuteczność zależy też od zachowań i kontekstu."),
          M("Które źródła władzy wyróżnili French i Raven?",
            ["Władza nagradzania", "Władza ekspercka", "Władza odniesienia", "Władza losowa"], [0, 1, 2],
            why="Do tego władza przymusu i prawomocna."),
          PF("Styl liberalny może działać dobrze w zespole doświadczonych ekspertów.", True,
             why="Kompetentni i zmotywowani ludzie potrzebują swobody."),
      ],
      calc=[
          LB("Ile pól (kombinacji stylów) ma siatka 9 × 9?",
             81, "9*9", ["9 · 9 = 81"], unit="pól"),
          LB("Ocena kierownika: troska o zadania 7, o ludzi 3. O ile punktów brakuje mu do 9.9 łącznie w obu wymiarach?",
             8, "(9-7)+(9-3)", ["2 + 6 = 8"], unit="pkt"),
          LB("Systemy Likerta zostały opisane w 1967 r., siatka Blake’a i Mouton w 1964 r. Ile lat różnicy?",
             3, "1967-1964", ["1967 − 1964 = 3"], unit="lata"),
          LB("W ankiecie 60 z 80 pracowników chce stylu demokratycznego. Jaki to procent?",
             75, "60/80*100", ["60 / 80 = 75%"], unit="%"),
          LB("Premia za wyniki 1 200 zł miesięcznie dla 15 osób (władza nagradzania). Ile kosztuje rocznie (zł)?",
             216000, "1200*15*12", ["1 200 · 15 · 12 = 216 000 zł"], unit="zł"),
          LB("Po zmianie stylu na partycypacyjny absencja spadła z 5% do 3,5%. O ile procent?",
             30, "(1-3.5/5)*100", ["3,5 / 5 = 0,7 → spadek 30%"], unit="%"),
      ],
      case=[
          PR("Nowy kierownik zakładu wymaga ścisłego trzymania się norm, karze za każde spóźnienie i nie rozmawia z pracownikami. Wydajność na krótko wzrosła, ale po pół roku rośnie absencja i odchodzą najlepsi.",
             W("Jaki styl stosuje kierownik w siatce Blake’a i Mouton?",
               "9.1 zadaniowy", "1.9 klub towarzyski", "9.9 zespołowy",
               why="Wysoka troska o zadania, niska o ludzi."),
             W("Na którym źródle władzy opiera się głównie?",
               "Władzy przymusu", "Władzy odniesienia", "Władzy eksperckiej",
               why="Opiera wpływ na karach i strachu."),
             PF("Przejście ku stylowi 9.9 mogłoby poprawić zarówno morale, jak i wyniki.", True,
                why="Łączy wysokie wymagania z troską o ludzi."),
          ),
          PR("Kierowniczka laboratorium badawczego zatrudnia doświadczonych naukowców. Ustala z nimi cele roczne, a potem pozostawia im swobodę wyboru metod, wspierając zasobami. Wyniki zespołu są bardzo dobre.",
             W("Jaki styl Lewina jest jej najbliższy?",
               "Liberalny (z jasnymi celami)", "Autokratyczny", "Eksploatatorski",
               why="Pozostawia swobodę kompetentnym ludziom."),
             W("Dlaczego ten styl działa w tej sytuacji?",
               "Zespół jest kompetentny i wewnętrznie zmotywowany", "Bo naukowcy nie potrzebują celów", "Bo zespół jest nowy i niedoświadczony",
               why="Styl dopasowany do dojrzałości zespołu."),
             PF("Ten sam styl w zespole nowych, niedoświadczonych osób mógłby zawieść.", True,
                why="Potrzebowaliby instrukcji i wsparcia."),
          ),
      ]),

    L(4, "Sytuacyjne i nowoczesne teorie przywództwa",
      "Rozumieć, dlaczego skuteczny styl zależy od sytuacji: model Fiedlera, teorię ścieżki do celu, model Herseya–Blancharda, model Vrooma–Yettona–Jago, LMX oraz przywództwo transformacyjne.",
      ["Model LPC F. Fiedlera", "Teoria ścieżki do celu (R. House)", "Teoria cyklu życia (Hersey i Blanchard)", "Model Vrooma–Yettona–Jago", "Model LMX (wymiany przywódca–członek)", "Przywództwo transformacyjne i charyzmatyczne"],
      [M136, M138],
      explain=[
          K("Fiedler (model LPC)",
            "Styl lidera jest stały i mierzony skalą LPC (ocena „najmniej lubianego współpracownika”): niski LPC – lider zadaniowy, wysoki – nastawiony na relacje. Sprzyjanie sytuacji zależy od relacji lider–członkowie, struktury zadania i władzy formalnej (2 · 2 · 2 = 8 sytuacji). Lider zadaniowy jest skuteczny w sytuacjach bardzo korzystnych i bardzo niekorzystnych, relacyjny – w umiarkowanych. Skoro styl jest stały, trzeba dopasować lidera do sytuacji."),
          K("House i Hersey–Blanchard",
            "Ścieżka do celu (House, 1971): lider ma „oczyścić ścieżkę” do celu i nagrody, stosując styl dyrektywny, wspierający, partycypacyjny lub nastawiony na osiągnięcia – zależnie od podwładnych i zadania. Hersey–Blanchard: styl zależy od gotowości pracownika: instruowanie (S1, niskie umiejętności i chęci), przekonywanie (S2), uczestniczenie (S3), delegowanie (S4, wysokie umiejętności i chęci)."),
          W("Nowy pracownik bardzo chce się uczyć, ale nie ma jeszcze umiejętności. Jaki styl zaleca model Herseya–Blancharda?",
            "Przekonywanie (S2) – dużo instrukcji i wsparcia", "Delegowanie (S4)", "Brak jakiegokolwiek nadzoru",
            why="Chęci są, umiejętności brak – potrzeba kierowania i wsparcia."),
          K("Vroom–Yetton–Jago i LMX",
            "Model Vrooma–Yettona (1973), rozwinięty z Jago (1988), pomaga wybrać stopień udziału podwładnych w decyzji (od autokratycznej przez konsultacyjną po grupową) na podstawie pytań: jak ważna jest jakość decyzji, czy potrzebna jest akceptacja zespołu, czy lider ma informacje, ile jest czasu. LMX: lider tworzy z częścią podwładnych relacje wysokiej jakości („grupa wewnętrzna” – zaufanie, więcej zadań i wsparcia), z innymi – formalne („grupa zewnętrzna”)."),
          K("Przywództwo transformacyjne i charyzmatyczne",
            "Transakcyjne: wymiana nagród za wykonanie zadań. Transformacyjne (Burns, Bass): lider inspiruje wizją, stymuluje intelektualnie, indywidualnie traktuje ludzi i jest wzorem – pracownicy przekraczają własny interes. Charyzma budzi silne oddanie, ale grozi kultem lidera i nadużyciami."),
          PF("Według Fiedlera najlepiej zmienić styl lidera, gdy sytuacja się zmienia.", False,
             why="Fiedler uważał styl za stały – dopasowuje się lidera lub sytuację."),
      ],
      mech=[
          KT("Styl według Herseya–Blancharda",
             {"S1 instruowanie": ["Nowy pracownik bez umiejętności i niepewny siebie"],
              "S2 przekonywanie": ["Entuzjastyczny stażysta bez doświadczenia"],
              "S3 uczestniczenie": ["Doświadczony pracownik, który stracił pewność siebie"],
              "S4 delegowanie": ["Ekspert, który chce samodzielnie prowadzić projekt", "Doświadczony i zmotywowany kierownik zmiany"]},
             why="Styl dopasowany do gotowości pracownika."),
          LN("Ułóż rozumowanie w modelu Fiedlera.",
             ["Mierzymy styl lidera skalą LPC", "Oceniamy relacje lider–członkowie", "Oceniamy strukturę zadania i władzę formalną", "Ustalamy, jak korzystna jest sytuacja", "Dopasowujemy lidera do sytuacji lub zmieniamy sytuację"],
             why="Styl uznany za stały, więc dopasowuje się sytuację."),
          W("Zespół jest zdezorientowany, zadanie niejasne. Jaki styl zaleca teoria ścieżki do celu?",
            "Dyrektywny", "Wyłącznie wspierający", "Delegujący",
            why="Lider wyjaśnia zadanie i drogę do celu."),
          W("Co odróżnia przywództwo transformacyjne od transakcyjnego?",
            "Inspirowanie wizją i rozwój ludzi zamiast samej wymiany nagród za zadania", "Wyższe premie", "Brak celów",
            why="Transformacyjne zmienia wartości i zaangażowanie."),
          M("Od czego zależy sprzyjanie sytuacji w modelu Fiedlera?",
            ["Relacji lider–członkowie", "Struktury zadania", "Władzy formalnej lidera", "Wieku lidera"], [0, 1, 2],
            why="Trzy wymiary dają 8 sytuacji."),
          PF("W modelu LMX pracownicy z „grupy wewnętrznej” zwykle dostają więcej zaufania i wsparcia.", True,
             why="Relacja wysokiej jakości z liderem."),
      ],
      calc=[
          LB("Ile sytuacji wyróżnia Fiedler przy trzech wymiarach po dwa poziomy?",
             8, "2**3", ["2 · 2 · 2 = 8"], unit="sytuacji"),
          LB("Lider ma w grupie wewnętrznej 4 z 10 osób. Jaki odsetek zespołu jest w grupie zewnętrznej (%)?",
             60, "6/10*100", ["6 / 10 = 60%"], unit="%"),
          LB("Model Vrooma–Yettona powstał w 1973 r., rozszerzenie z Jago w 1988 r. Ile lat różnicy?",
             15, "1988-1973", ["1988 − 1973 = 15"], unit="lat"),
          LB("Zaangażowanie zespołu wzrosło z 55 do 77 pkt po wprowadzeniu lidera transformacyjnego. O ile procent?",
             40, "(77/55-1)*100", ["77 / 55 = 1,4 → +40%"], unit="%"),
          LB("Stażysta po 6 miesiącach przechodzi z S2 do S3; kierownik skraca czas instruowania z 10 h do 4 h tygodniowo. O ile procent?",
             60, "(1-4/10)*100", ["4 / 10 = 0,4 → spadek 60%"], unit="%"),
          LB("Decyzja autokratyczna zajmuje 1 h, grupowa – 6 h dla 6 osób każda. Ile osobogodzin więcej kosztuje decyzja grupowa?",
             35, "6*6-1", ["36 − 1 = 35"], unit="h"),
      ],
      case=[
          PR("Kierownik zmiany w magazynie ma bardzo dobre relacje z zespołem, jasno opisane procedury i pełną władzę formalną. Jest liderem silnie zadaniowym (niski LPC).",
             W("Jak korzystna jest sytuacja według Fiedlera?",
               "Bardzo korzystna", "Umiarkowana", "Bardzo niekorzystna",
               why="Dobre relacje, ustrukturyzowane zadanie, silna władza."),
             W("Czy lider zadaniowy będzie tu skuteczny według Fiedlera?",
               "Tak – lider zadaniowy sprawdza się w sytuacjach bardzo korzystnych", "Nie – potrzebny lider relacyjny", "Model tego nie przewiduje",
               why="Niski LPC skuteczny na krańcach skali."),
             PF("W sytuacji umiarkowanie korzystnej Fiedler przewidywał lepsze wyniki lidera relacyjnego.", True,
                why="Wysoki LPC w sytuacjach pośrednich."),
          ),
          PR("Dyrektorka musi zdecydować o reorganizacji grafików pracy pielęgniarek. Decyzja wymaga akceptacji zespołu, bo bez niej grafik nie zadziała, a pielęgniarki znają potrzeby oddziału lepiej niż ona. Ma na decyzję trzy tygodnie.",
             W("Jaki stopień udziału zespołu zaleca model Vrooma–Yettona–Jago?",
               "Wysoki – decyzja grupowa lub szeroka konsultacja", "Decyzja całkowicie autokratyczna", "Rzut monetą",
               why="Ważna akceptacja, informacje u zespołu, jest czas."),
             W("Co przemawiałoby za decyzją bardziej autokratyczną?",
               "Sytuacja kryzysowa i brak czasu", "Duża potrzeba akceptacji", "Wiedza u pracowników",
               why="Pośpiech zmniejsza możliwość konsultacji."),
             PF("Udział pracowników zwiększa szansę wdrożenia decyzji.", True,
                why="Rośnie zaangażowanie i akceptacja."),
          ),
      ]),

    L(5, "Zespoły, konflikt i komunikacja",
      "Rozumieć rozwój zespołu (Tuckman), role Belbina, myślenie grupowe, style rozwiązywania konfliktów i sieci komunikacyjne w małych grupach.",
      ["Grupy i zespoły", "Role zespołowe Belbina i team building", "Myślenie grupowe (groupthink)", "Konflikt w organizacji", "Sieci komunikacyjne w małych grupach", "Komunikacja w organizacji"],
      [M152, M153, M162],
      explain=[
          K("Grupa a zespół; fazy rozwoju",
            "Zespół to grupa o wspólnym celu, uzupełniających się umiejętnościach i wspólnej odpowiedzialności. Tuckman (1965): formowanie (niepewność, poznawanie), burzenie (konflikty o role i władzę), normowanie (ustalanie zasad), działanie (wysoka efektywność); w 1977 dodano fazę rozwiązania (zakończenia)."),
          K("Role Belbina",
            "M. Belbin wyróżnił dziewięć ról zespołowych, m.in. kreator (pomysły), koordynator, lokalizator zasobów, praktyczny organizator (wdrożenie), perfekcjonista (dopilnowanie szczegółów), ewaluator (krytyczna ocena), specjalista, dusza zespołu, lokomotywa (napęd). Skuteczny zespół potrzebuje równowagi ról, a nie samych gwiazd."),
          W("Zespół ma wiele pomysłów, ale nic nie zostaje dokończone. Jakiej roli Belbina najbardziej brakuje?",
            "Praktycznego organizatora lub perfekcjonisty", "Kreatora", "Lokalizatora zasobów",
            why="Brakuje osób wdrażających i domykających."),
          K("Myślenie grupowe (Janis, 1972)",
            "Spójna grupa pod presją dąży do jednomyślności kosztem krytycznej oceny: iluzja nieomylności, autocenzura, presja na dysydentów, „strażnicy umysłu”. Skutki: złe decyzje (np. Zatoka Świń 1961). Zapobieganie: „adwokat diabła”, zewnętrzni eksperci, lider wypowiada się na końcu, podgrupy."),
          K("Konflikt i komunikacja",
            "Konflikt zadaniowy w umiarkowanym stopniu poprawia decyzje, konflikt osobisty szkodzi. Style (Thomas–Kilmann): rywalizacja, współpraca, kompromis, unikanie, dostosowanie się. Sieci komunikacyjne: scentralizowane (koło, Y, łańcuch) są szybkie w prostych zadaniach, zdecentralizowane (okrąg, każdy z każdym) – lepsze w złożonych i dają większą satysfakcję. Liczba kanałów w sieci każdy z każdym: n(n − 1)/2.",
            w="kanały = n · (n − 1) / 2"),
          PF("Umiarkowany konflikt zadaniowy może poprawić jakość decyzji.", True,
             why="Ujawnia różne punkty widzenia."),
      ],
      mech=[
          KT("Faza rozwoju zespołu (Tuckman)",
             {"Formowanie": ["Członkowie poznają się i są ostrożni"],
              "Burzenie": ["Spory o role i sposób pracy"],
              "Normowanie": ["Zespół ustala wspólne zasady i role"],
              "Działanie": ["Zespół sprawnie realizuje cele"]},
             why="Kolejne etapy dojrzewania zespołu."),
          LN("Ułóż powstawanie myślenia grupowego.",
             ["Grupa jest bardzo spójna i izolowana od opinii z zewnątrz", "Lider wcześnie ujawnia preferowane rozwiązanie", "Członkowie autocenzurują wątpliwości", "Powstaje iluzja jednomyślności", "Grupa podejmuje ryzykowną, słabo przeanalizowaną decyzję"],
             why="Presja zgody wypiera krytyczne myślenie."),
          W("Który styl rozwiązywania konfliktu daje rozwiązanie korzystne dla obu stron?",
            "Współpraca", "Unikanie", "Rywalizacja",
            why="Wysoka troska o własne i cudze interesy."),
          W("Która sieć komunikacyjna jest najszybsza w prostych zadaniach?",
            "Koło (scentralizowana)", "Każdy z każdym", "Okrąg",
            why="Informacja płynie przez centralną osobę."),
          M("Jak zapobiegać myśleniu grupowemu?",
            ["Wyznaczyć adwokata diabła", "Zaprosić zewnętrznych ekspertów", "Lider wypowiada się na końcu", "Karać za odmienne zdanie"], [0, 1, 2],
            why="Karanie dysydentów nasila myślenie grupowe."),
          PF("Spory o role w nowym zespole są typowe dla fazy burzenia.", True,
             why="To naturalny etap rozwoju zespołu."),
      ],
      calc=[
          LB("Ile kanałów komunikacji ma 5-osobowa sieć „każdy z każdym”?",
             10, "5*4/2", ["5 · 4 / 2 = 10"], unit="kanałów"),
          LB("Ile kanałów ma 8-osobowa sieć „każdy z każdym”?",
             28, "8*7/2", ["8 · 7 / 2 = 28"], unit="kanałów"),
          LB("O ile kanałów więcej ma zespół 12-osobowy niż 6-osobowy (sieć „każdy z każdym”)?",
             51, "12*11/2-6*5/2", ["66 − 15 = 51"], unit="kanałów"),
          LB("W sieci „koło” z 6 osobami (1 centralna) ile jest kanałów?",
             5, "6-1", ["6 − 1 = 5"], unit="kanałów"),
          LB("Tuckman opisał 4 fazy w 1965 r., piątą dodał w 1977 r. Ile lat później?",
             12, "1977-1965", ["1977 − 1965 = 12"], unit="lat"),
          LB("Kierownik spędza 12 h z 40 h tygodniowo na rozwiązywaniu konfliktów. Jaki to procent czasu?",
             30, "12/40*100", ["12 / 40 = 30%"], unit="%"),
      ],
      case=[
          PR("Zarząd firmy, od lat w tym samym składzie, jednogłośnie zatwierdza przejęcie konkurenta. Prezes od początku mówi, że to „oczywista okazja”. Jeden członek ma wątpliwości co do wyceny, ale milczy. Analiz zewnętrznych nie zamówiono. Po roku trzeba odpisać połowę wartości przejęcia.",
             W("Jakie zjawisko wystąpiło?",
               "Myślenie grupowe", "Faza burzenia", "Konflikt osobisty",
               why="Autocenzura, presja lidera i iluzja jednomyślności."),
             W("Co mogło zapobiec błędowi?",
               "Niezależna wycena i adwokat diabła", "Szybsze głosowanie", "Mniejszy zarząd o tym samym składzie",
               why="Wprowadzają krytyczną ocenę."),
             PF("Prezes, ujawniając swoje zdanie na początku, zwiększył presję na zgodę.", True,
                why="To typowy czynnik myślenia grupowego."),
          ),
          PR("Nowy zespół projektowy po dwóch tygodniach ma ostre spory o to, kto prowadzi spotkania i jak dzielić zadania. Kierowniczka obawia się, że zespół się rozpadnie.",
             W("W jakiej fazie według Tuckmana jest zespół?",
               "Burzenia", "Działania", "Rozwiązania",
               why="Spory o role i władzę."),
             W("Co powinna zrobić kierowniczka?",
               "Pomóc ustalić zasady i role, moderować konflikt", "Rozwiązać zespół", "Ignorować problem",
               why="Pomaga przejść do fazy normowania."),
             PF("Konflikty w tej fazie są naturalne i nie oznaczają porażki.", True,
                why="Większość zespołów przechodzi tę fazę."),
          ),
      ]),
    L(6, "Władza i przywództwo w badaniach: Michigan, Ohio, substytuty, empowerment; cele i wzmocnienia",
      "Rozróżniać pięć źródeł władzy (French i Raven), wyniki badań przywództwa z Michigan i Ohio, koncepcję substytutów przywództwa i upełnomocnienie, a w motywacji – teorię wyznaczania celów Locke'a i teorię wzmocnienia Skinnera.",
      ["Badania przywództwa z Michigan i Ohio", "Substytuty przywództwa (Kerr i Jermier)", "Upełnomocnienie (empowerment)", "Teoria wyznaczania celów (E. Locke)", "Teoria wzmocnienia (B.F. Skinner)", "Przywództwo"],
      [M135, M136, KJ78, M143, LO68, WOPC, WEMP],
      explain=[
          K("Pięć źródeł władzy",
            "J. French i B. Raven (1959): władza nagradzania (możliwość przyznania nagrody), przymusu (kary), prawomocna (z zajmowanego stanowiska), ekspercka (z wiedzy) i odniesienia (charyzma – inni chcą się z kimś utożsamiać). Pierwsze trzy wynikają głównie ze stanowiska, dwie ostatnie – z cech osoby."),
          K("Michigan i Ohio",
            "Badania z Michigan wyróżniły przywództwo zorientowane na pracowników i na zadania – jako przeciwne końce jednej skali; skuteczniejsze okazało się zorientowane na pracowników. Badania z Ohio wskazały dwa niezależne wymiary: inicjowanie struktury (organizowanie pracy) i uwzględnianie (troska o ludzi) – przywódca może być wysoko na obu. Z tych prac wyrosła siatka kierownicza Blake'a i Mouton."),
          W("Czym różni się ujęcie z Ohio od ujęcia z Michigan?",
            "W Ohio orientacja na zadania i na ludzi to dwa niezależne wymiary", "W Ohio badano tylko cechy osobowości", "W Ohio uznano, że styl nie ma znaczenia",
            why="Można być wysoko na obu wymiarach naraz."),
          K("Substytuty przywództwa i empowerment",
            "S. Kerr i J. Jermier (1978): doświadczenie i profesjonalizm podwładnych, rutynowe zadania z wbudowaną informacją zwrotną czy sformalizowane reguły mogą zastąpić przywództwo lub zneutralizować jego wpływ. Upełnomocnienie (empowerment) to przekazanie pracownikom swobody wyznaczania celów i podejmowania decyzji w ich obszarze – np. zespoły samokierujące."),
          K("Locke i Skinner",
            "Teoria wyznaczania celów (E. Locke, 1968): konkretne i trudne, ale zaakceptowane cele dają lepsze wyniki niż cele łatwe lub ogólnikowe; pomaga informacja zwrotna i udział w ustalaniu celów. Teoria wzmocnienia (B.F. Skinner): zachowanie zależy od konsekwencji – wzmocnienie pozytywne, unikanie, wygaszanie i kara; harmonogramy ciągłe i przerywane (stałe lub zmienne odstępy i proporcje)."),
          PF("Według Locke'a cel „staraj się jak najlepiej” motywuje silniej niż konkretny trudny cel.", False,
             why="Konkretne, trudne cele dają wyższe wyniki."),
      ],
      mech=[
          KT("Źródło władzy?",
             {"Prawomocna": ["Dyrektor wydaje polecenie z racji stanowiska", "Sędzia ogłasza wyrok"],
              "Ekspercka": ["Informatyk, którego rad słuchają wszyscy, bo zna system", "Lekarz zalecający leczenie"],
              "Odniesienia": ["Charyzmatyczny lider, którego zespół chce naśladować", "Popularny sportowiec reklamujący produkt"]},
             why="Źródło władzy mówi, skąd bierze się wpływ."),
          KT("Wzmocnienie czy wygaszanie/kara?",
             {"Wzmocnienie pozytywne": ["Premia za przekroczenie normy", "Pochwała przy zespole"],
              "Wygaszanie": ["Ignorowanie żartów przerywających zebranie", "Brak reakcji na ciągłe skargi bez powodu"],
              "Kara": ["Upomnienie za spóźnienie", "Obniżenie premii za błąd"]},
             why="Wzmocnienia zwiększają częstość zachowań, wygaszanie i kara ją zmniejszają."),
          W("Który czynnik według Kerra i Jermiera może zastąpić przywództwo zorientowane na zadania?",
            "Duże doświadczenie i profesjonalizm podwładnych", "Brak jakichkolwiek reguł", "Niski poziom wykształcenia",
            why="Profesjonaliści wiedzą, jak wykonać pracę."),
          W("Na czym polega upełnomocnienie?",
            "Na przekazaniu pracownikom swobody decyzji i odpowiedzialności w ich obszarze", "Na zwiększeniu liczby szczebli", "Na zastąpieniu ludzi automatami",
            why="Pracownicy sami ustalają, jak osiągnąć cele."),
          M("Co zwiększa skuteczność celów według Locke'a?",
            ["Konkretność", "Trudność przy akceptacji", "Informacja zwrotna", "Brak terminów"], [0, 1, 2],
            why="Brak terminów osłabia cel."),
          PF("Premia wypłacana po losowej liczbie sprzedaży to harmonogram zmiennych proporcji.", True,
             why="Wzmocnienie zależy od liczby zachowań, która się zmienia."),
      ],
      calc=[
          LB("Cel: 120 umów miesięcznie; zawarto 108. Jaki procent celu osiągnięto?",
             90, "108/120*100", ["108 / 120 · 100 = 90%"], unit="%"),
          LB("Po ustaleniu konkretnych celów wydajność wzrosła ze 50 do 58 szt./dzień. O ile procent?",
             16, "(58-50)/50*100", ["8 / 50 · 100 = 16%"], unit="%"),
          LB("Premia co 10 sprzedanych polis (stałe proporcje). Ile premii za 75 polis?",
             7, "75//10", ["75 / 10 = 7,5 → 7 pełnych premii"], unit="premii"),
          LB("Kierownik ma 5 źródeł władzy według French i Ravena; z tego 3 wynikają głównie ze stanowiska. Ile z cech osobistych?",
             2, "5-3", ["5 − 3 = 2 (ekspercka i odniesienia)"], unit=""),
          LB("Badanie: 40 z 50 pracowników zespołów samokierujących jest zadowolonych. Jaki odsetek?",
             80, "40/50*100", ["40 / 50 · 100 = 80%"], unit="%"),
          LB("Od teorii Locke'a (1968) do pracy Kerra i Jermiera (1978) minęło ile lat?",
             10, "1978-1968", ["1978 − 1968 = 10 lat"], unit="lat"),
      ],
      case=[
          PR("W laboratorium badawczym pracują doświadczeni naukowcy. Nowa kierowniczka przez pierwsze tygodnie drobiazgowo rozdzielała zadania i kontrolowała każdy krok – efekty były słabe, a zespół był sfrustrowany. Gdy przestała, ustaliła z zespołem ambitne cele kwartalne i dała mu swobodę metod, wyniki wyraźnie się poprawiły.",
             W("Co według Kerra i Jermiera neutralizowało jej przywództwo zorientowane na zadania?",
               "Profesjonalizm i doświadczenie podwładnych", "Brak celów", "Niskie płace",
               why="Fachowcy nie potrzebują instrukcji krok po kroku."),
             W("Jak nazwać przekazanie zespołowi swobody metod?",
               "Upełnomocnienie (empowerment)", "Centralizacja", "Kontrola biurokratyczna",
               why="Zespół sam decyduje, jak osiągnąć cele."),
             W("Którą teorię motywacji wykorzystała, ustalając ambitne cele?",
               "Teorię wyznaczania celów Locke'a", "Teorię X McGregora", "Teorię ERG",
               why="Trudne, konkretne i akceptowane cele."),
          ),
          PR("Kierownik call center chwali pracowników za każdą rozmowę z oceną klienta 5/5, ignoruje narzekania na grafik zgłaszane bez propozycji zmian, a za trzecie spóźnienie w miesiącu odbiera część premii. Przełożeni oceniają go jako silnie skupionego zarówno na wynikach, jak i na ludziach.",
             W("Czym jest pochwała za ocenę 5/5 w teorii Skinnera?",
               "Wzmocnieniem pozytywnym", "Karą", "Wygaszaniem",
               why="Nagroda zwiększa częstość pożądanego zachowania."),
             W("Czym jest ignorowanie narzekań bez propozycji?",
               "Wygaszaniem", "Wzmocnieniem pozytywnym", "Unikaniem",
               why="Brak reakcji osłabia zachowanie."),
             W("Jak go opisać w ujęciu z Ohio?",
               "Wysokie inicjowanie struktury i wysokie uwzględnianie", "Niskie na obu wymiarach", "Wyłącznie zorientowany na pracowników jako przeciwieństwo zadań",
               why="W Ohio to dwa niezależne wymiary."),
          ),
      ]),
    L(7, "Jednostka i grupa w organizacji: kontrakt psychologiczny, zachowania w pracy, normy i spójność",
      "Rozumieć kontrakt psychologiczny i dopasowanie osoby do stanowiska, odróżniać zachowania efektywnościowe, wycofania, obywatelskie i dysfunkcjonalne oraz wyjaśniać, jak normy i spójność grupy wpływają na wyniki.",
      ["Kontrakt psychologiczny i dopasowanie osoby do stanowiska", "Zachowania w miejscu pracy", "Normy i spójność grupy", "Grupy i zespoły"],
      [WPSC, RO89, WOCB, WCOH, M153],
      explain=[
          K("Kontrakt psychologiczny",
            "To niepisane oczekiwania pracownika i organizacji wobec siebie. Pracownik wnosi wkład: wysiłek, umiejętności, czas, lojalność; organizacja daje zachęty: płacę, bezpieczeństwo, możliwości rozwoju, uznanie. Pojęcie rozwinęła D. Rousseau (1989). Naruszenie kontraktu (np. obietnica awansu bez pokrycia) obniża zaangażowanie i zaufanie."),
          K("Dopasowanie osoby do stanowiska",
            "Im lepiej potrzeby i umiejętności pracownika pasują do wymagań i zachęt stanowiska, tym większa satysfakcja i wydajność. Złe dopasowanie sprzyja frustracji, absencji i odejściom."),
          W("Pracownikowi obiecano szkolenia, ale firma ich nie organizuje, choć umowa o pracę o nich nie wspomina. Co zostało naruszone?",
            "Kontrakt psychologiczny", "Umowa o pracę", "Regulamin wynagradzania",
            why="Oczekiwanie było niepisane."),
          K("Zachowania w miejscu pracy",
            "Efektywnościowe – wykonywanie zadań stanowiska. Wycofania – absencja (nieobecności) i rotacja (odejścia z pracy). Obywatelskie (OCB) – dobrowolne działania ponad obowiązki, np. pomoc kolegom, dobre słowo o firmie. Dysfunkcjonalne – szkodliwe: kradzieże, sabotaż, agresja, mobbing."),
          K("Normy i spójność",
            "Normy to niepisane standardy zachowań w grupie (np. „nie wyrabiamy więcej niż norma”). Spójność to siła przywiązania członków do grupy; rośnie przy wspólnych celach, zagrożeniu z zewnątrz, sukcesach i małej liczebności. Spójna grupa o normach zgodnych z celami firmy jest bardzo wydajna, a o normach sprzecznych – najbardziej szkodliwa."),
          PF("Wysoka spójność grupy zawsze podnosi wydajność.", False,
             why="Zależy od tego, czy normy grupy są zgodne z celami organizacji."),
      ],
      mech=[
          KT("Rodzaj zachowania?",
             {"Obywatelskie (OCB)": ["Zostaje po godzinach, by wdrożyć nowego kolegę", "Z własnej inicjatywy proponuje usprawnienie"],
              "Wycofania": ["Częste nieobecności bez ważnej przyczyny", "Odejście do konkurencji"],
              "Dysfunkcjonalne": ["Wynoszenie materiałów biurowych do domu", "Celowe niszczenie sprzętu"]},
             why="Kategorie zachowań wpływających na skuteczność."),
          KT("Wkład czy zachęta w kontrakcie psychologicznym?",
             {"Wkład pracownika": ["Wysiłek", "Lojalność", "Umiejętności"],
              "Zachęty organizacji": ["Płaca", "Bezpieczeństwo zatrudnienia", "Możliwość awansu"]},
             why="Kontrakt to wymiana wkładu na zachęty."),
          M("Co zwiększa spójność grupy?",
            ["Wspólne zagrożenie z zewnątrz", "Sukcesy grupy", "Mała liczebność", "Silna rywalizacja wewnątrz grupy"], [0, 1, 2],
            why="Rywalizacja wewnątrz grupy osłabia spójność."),
          W("Jak zachowa się bardzo spójna grupa, której norma to „pracujemy powoli”?",
            "Będzie wyraźnie mniej wydajna niż grupa niespójna", "Będzie najbardziej wydajna", "Spójność nie ma znaczenia",
            why="Spójność wzmacnia egzekwowanie norm grupy."),
          W("Co jest przejawem złego dopasowania osoby do stanowiska?",
            "Ambitny specjalista na rutynowym stanowisku bez szans rozwoju, często szukający innej pracy", "Pracownik zadowolony z zakresu obowiązków", "Wysoka wydajność i niska absencja",
            why="Niezaspokojone potrzeby prowadzą do wycofania."),
          PF("Absencja i rotacja to zachowania wycofania.", True,
             why="Pracownik ogranicza lub kończy udział w organizacji."),
      ],
      calc=[
          LB("Firma zatrudnia średnio 200 osób; w roku odeszło 30. Wskaźnik rotacji (%)?",
             15, "30/200*100", ["30 / 200 · 100 = 15%"], unit="%"),
          LB("Zaplanowano 4400 dni roboczych, nieobecności wyniosły 220 dni. Wskaźnik absencji (%)?",
             5, "220/4400*100", ["220 / 4400 · 100 = 5%"], unit="%"),
          LB("Koszt zastąpienia pracownika to 30% rocznej płacy 80 tys. zł. Ile kosztuje jedno odejście (tys. zł)?",
             24, "0.3*80", ["0,3 · 80 = 24 tys. zł"], unit="tys. zł"),
          LB("Ile kosztuje 30 odejść (tys. zł)?",
             720, "30*24", ["30 · 24 = 720 tys. zł"], unit="tys. zł"),
          LB("Grupa 3-osobowa: ile jest relacji dwustronnych (n(n−1)/2)?",
             3, "3*2/2", ["3 · 2 / 2 = 3"], unit=""),
          LB("Grupa 10-osobowa: ile jest relacji dwustronnych?",
             45, "10*9/2", ["10 · 9 / 2 = 45 – dlatego spójność trudniej utrzymać w dużych grupach"], unit=""),
      ],
      case=[
          PR("Software house przez lata obiecywał pracownikom elastyczny czas pracy i pracę zdalną, choć nie zapisano tego w umowach. Nowy zarząd nakazał pięć dni w biurze. W ciągu pół roku rotacja wzrosła z 8% do 20%, a pracownicy przestali pomagać sobie nawzajem poza swoimi zadaniami.",
             W("Co naruszył nowy zarząd?",
               "Kontrakt psychologiczny", "Kodeks pracy", "Umowę zbiorową",
               why="Oczekiwania były niepisane, ale silnie utrwalone."),
             W("Którą kategorię zachowań ilustruje wzrost rotacji?",
               "Zachowania wycofania", "Zachowania obywatelskie", "Zachowania efektywnościowe",
               why="Pracownicy odchodzą z organizacji."),
             W("Co oznacza zanik wzajemnej pomocy poza zadaniami?",
               "Spadek zachowań obywatelskich (OCB)", "Wzrost zachowań obywatelskich", "Wzrost spójności",
               why="OCB to dobrowolne działania ponad obowiązki."),
          ),
          PR("W fabryce dwie brygady mają podobny sprzęt. Brygada A jest zżyta, a jej nieformalna norma brzmi: „nikt nie wyrabia ponad normę, żeby nie podnieśli normy”. Brygada B jest mało zżyta. Kierownik przenosi do A ambitnego nowego pracownika, który szybko zaczyna przekraczać normę.",
             W("Czego może doświadczyć nowy pracownik w brygadzie A?",
               "Presji grupy, by dostosował się do normy", "Nagrody od brygady za wyniki", "Braku jakiejkolwiek reakcji",
               why="Spójne grupy egzekwują swoje normy."),
             W("Która brygada ma prawdopodobnie niższą wydajność, mimo wyższej spójności?",
               "Brygada A", "Brygada B", "Obie tak samo",
               why="Spójność wzmacnia normę ograniczania wydajności."),
             PF("Kierownik powinien próbować zmienić normy brygady A, a nie tylko jej skład.", True,
                why="Normy, a nie sama spójność, decydują o kierunku wpływu."),
          ),
      ]),
    L(8, "Jednostka w organizacji: osobowość, percepcja i stres",
      "Znać model Wielkiej piątki i inne cechy osobowości ważne w pracy (umiejscowienie kontroli, typ A i B), rozpoznawać błędy percepcji (stereotyp, efekt aureoli, projekcja, atrybucja) i opisać przebieg stresu według Selyego.",
      ["Wielka piątka (cechy osobowości)", "Cechy osobowości w organizacji", "Percepcja i błędy percepcji", "Stres w pracy"],
      [WB5, OB24, OB32, WHALO, OB182, WGAS],
      explain=[
          K("Wielka piątka",
            "Pięć szerokich wymiarów osobowości: sumienność (rzetelność, zorganizowanie – najlepiej przewiduje wyniki pracy), ugodowość (życzliwość, współpraca), neurotyczność (skłonność do negatywnych emocji; jej przeciwieństwo to stabilność emocjonalna), ekstrawersja (towarzyskość, energia) i otwartość na doświadczenia (ciekawość, kreatywność)."),
          K("Inne cechy ważne w pracy",
            "Umiejscowienie poczucia kontroli: wewnętrzne (wyniki zależą ode mnie) lub zewnętrzne (od losu, innych). Poczucie własnej skuteczności – wiara, że podołam zadaniu. Makiawelizm – skłonność do manipulowania innymi. Osobowość typu A (pośpiech, rywalizacja, niecierpliwość – większa podatność na stres) i typu B (spokój) – M. Friedman i R. Rosenman."),
          W("Pracownik uważa, że jego awans zależy wyłącznie od szczęścia i znajomości. Jakie ma umiejscowienie kontroli?",
            "Zewnętrzne", "Wewnętrzne", "Sumienne",
            why="Przyczyn wyników szuka poza sobą."),
          K("Błędy percepcji",
            "Percepcja selektywna – dostrzegamy to, co pasuje do oczekiwań. Stereotyp – przypisywanie cech na podstawie przynależności do grupy. Efekt aureoli (halo) – jedna cecha rzutuje na ocenę całej osoby. Projekcja – przypisywanie innym własnych cech. Atrybucja (F. Heider) – wyjaśnianie przyczyn zachowań: wewnętrzne (osoba) lub zewnętrzne (sytuacja)."),
          K("Stres według Selyego",
            "Ogólny zespół adaptacyjny (H. Selye): faza alarmu (mobilizacja organizmu), odporności (opór i przystosowanie) i wyczerpania (gdy stres trwa zbyt długo). Długotrwały stres w pracy prowadzi do wypalenia zawodowego. Przyczyny w organizacji: przeciążenie, niejasność i konflikt ról, złe warunki, relacje; zaradzanie: wsparcie, programy zdrowotne, lepsza organizacja pracy."),
          PF("Faza wyczerpania w modelu Selyego następuje przed fazą alarmu.", False,
             why="Kolejność: alarm, odporność, wyczerpanie."),
      ],
      mech=[
          KT("Który wymiar Wielkiej piątki?",
             {"Sumienność": ["Zawsze dotrzymuje terminów i planuje pracę", "Starannie sprawdza dokumenty"],
              "Ekstrawersja": ["Chętnie zabiera głos i nawiązuje kontakty", "Czerpie energię z pracy z ludźmi"],
              "Otwartość na doświadczenia": ["Lubi nowe pomysły i eksperymenty", "Ciekawi go nieznana kultura"]},
             why="Każdy wymiar opisuje inny zakres zachowań."),
          KT("Jaki błąd percepcji?",
             {"Efekt aureoli": ["Elokwentny kandydat oceniony wysoko także za umiejętności techniczne", "Ładna prezentacja podnosi ocenę całego projektu"],
              "Stereotyp": ["Założenie, że starszy pracownik nie poradzi sobie z komputerem", "Przekonanie, że księgowi są nudni"],
              "Projekcja": ["Nieuczciwy kierownik zakłada, że wszyscy kradną", "Ambitna osoba myśli, że każdy marzy o awansie"]},
             why="Każdy błąd zniekształca ocenę inaczej."),
          LN("Ułóż fazy ogólnego zespołu adaptacyjnego.",
             ["Alarm", "Odporność", "Wyczerpanie"],
             why="Model H. Selyego."),
          W("Która cecha Wielkiej piątki najlepiej przewiduje wyniki w wielu zawodach?",
            "Sumienność", "Neurotyczność", "Ekstrawersja",
            why="Rzetelność i zorganizowanie sprzyjają wynikom niemal w każdej pracy."),
          M("Które czynniki organizacyjne wywołują stres?",
            ["Przeciążenie pracą", "Niejasność roli", "Konflikt ról", "Jasne cele i wsparcie przełożonego"], [0, 1, 2],
            why="Jasne cele i wsparcie łagodzą stres."),
          PF("Osoby typu A są bardziej podatne na stres niż typu B.", True,
             why="Pośpiech i rywalizacja sprzyjają przeciążeniu."),
      ],
      calc=[
          LB("Wynik testu sumienności: 32 pkt na 40 możliwych. Jaki procent maksimum?",
             80, "32/40*100", ["32 / 40 · 100 = 80%"], unit="%"),
          LB("W zespole 25 osób 10 zgłasza objawy wypalenia. Jaki odsetek?",
             40, "10/25*100", ["10 / 25 · 100 = 40%"], unit="%"),
          LB("Absencja z powodu stresu spadła z 600 do 450 dni rocznie po programie wsparcia. O ile procent?",
             25, "(600-450)/600*100", ["150 / 600 · 100 = 25%"], unit="%"),
          LB("Dzień nieobecności kosztuje firmę 400 zł. Ile zaoszczędzono na 150 dniach (tys. zł)?",
             60, "150*400/1000", ["150 · 400 = 60 000 zł = 60 tys. zł"], unit="tys. zł"),
          LB("Program wsparcia kosztował 45 tys. zł. Jaki jest zysk netto z oszczędności z poprzedniego zadania (tys. zł)?",
             15, "60-45", ["60 − 45 = 15 tys. zł"], unit="tys. zł"),
          LB("Model Wielkiej piątki ma 5 wymiarów; Griffin omawia dodatkowo 4 inne cechy (kontrola, skuteczność, autorytaryzm, makiawelizm). Ile łącznie cech?",
             9, "5+4", ["5 + 4 = 9"], unit=""),
      ],
      case=[
          PR("Kierowniczka działu sprzedaży ocenia nowego handlowca: jest bardzo sympatyczny i świetnie się prezentuje, więc wystawia mu najwyższe noty także za znajomość produktów i raporty – choć te są słabe. Gdy handlowiec nie wykonuje planu, sam tłumaczy to złą pogodą i trudnym rynkiem.",
             W("Jaki błąd popełnia kierowniczka?",
               "Efekt aureoli (halo)", "Projekcję", "Percepcję selektywną",
               why="Jedna pozytywna cecha rzutuje na całą ocenę."),
             W("Jak handlowiec wyjaśnia swoje niepowodzenia?",
               "Atrybucją zewnętrzną", "Atrybucją wewnętrzną", "Efektem aureoli",
               why="Przyczyn szuka w sytuacji, nie w sobie."),
             PF("Ocena 360° mogłaby ograniczyć wpływ błędu jednej osoby oceniającej.", True,
                why="Oceny z wielu źródeł się równoważą."),
          ),
          PR("Analityk od pół roku pracuje po 60 godzin tygodniowo. Najpierw działał z ogromną energią, potem przyzwyczaił się do tempa, ale od miesiąca jest wyczerpany, cyniczny wobec pracy i często choruje. Jest niecierpliwy, ciągle rywalizuje z kolegami i robi kilka rzeczy naraz.",
             W("W której fazie modelu Selyego jest teraz?",
               "Wyczerpania", "Alarmu", "Odporności",
               why="Długotrwały stres wyczerpał zasoby organizmu."),
             W("Jaki typ osobowości opisuje jego zachowanie?",
               "Typ A", "Typ B", "Wysoka ugodowość",
               why="Pośpiech, rywalizacja, niecierpliwość."),
             W("Jak nazwać jego stan wyczerpania i cynizmu wobec pracy?",
               "Wypalenie zawodowe", "Myślenie grupowe", "Eskalacja zaangażowania",
               why="Typowy skutek przewlekłego stresu w pracy."),
          ),
      ]),
    L(9, "Ludzie w firmie: HRM, negocjacje i komunikacja interpersonalna",
      "Znać etapy zarządzania zasobami ludzkimi (planowanie, rekrutacja, selekcja, szkolenie, ocena 360°, wynagradzanie, outplacement), zasady negocjacji rzeczowych Fishera i Ury'ego z BATNA oraz umiejętności komunikacji: aktywne słuchanie, asertywność, informacja zwrotna.",
      ["Zarządzanie zasobami ludzkimi (HRM)", "Negocjacje", "Komunikacja interpersonalna – umiejętności", "Komunikacja w organizacji"],
      [OB171, OB173, OB144, WGTY, WBATNA, WAL, WAS],
      explain=[
          K("Proces HRM",
            "Planowanie zatrudnienia (ile i jakich ludzi potrzeba), rekrutacja (wewnętrzna – awanse, przeniesienia; zewnętrzna – ogłoszenia, agencje, łowcy głów), selekcja (rozmowy, testy, assessment center – zestaw ćwiczeń ocenianych przez kilku obserwatorów), adaptacja i szkolenia, ocena okresowa (np. 360° – opinie przełożonego, współpracowników, podwładnych, klientów i samoocena), wynagradzanie, rozwój karier i zwolnienia z outplacementem (pomoc w znalezieniu nowej pracy)."),
          W("Co odróżnia ocenę 360° od tradycyjnej oceny?",
            "Pracownika oceniają osoby z wielu kierunków, nie tylko przełożony", "Ocenia tylko klient", "Ocena odbywa się co 360 dni",
            why="Wieloźródłowa informacja zwrotna."),
          K("Negocjacje rzeczowe",
            "R. Fisher i W. Ury („Dochodząc do TAK”, 1981, Harwardzki Projekt Negocjacyjny): oddziel ludzi od problemu, skup się na interesach, nie na stanowiskach, szukaj rozwiązań korzystnych dla obu stron, stosuj obiektywne kryteria. BATNA – najlepsza alternatywa dla negocjowanego porozumienia; nie przyjmuje się oferty gorszej niż BATNA. Style: twardy (wygrać za wszelką cenę), miękki (porozumienie za wszelką cenę), rzeczowy."),
          K("Komunikacja interpersonalna",
            "Aktywne słuchanie – pełna uwaga, parafraza, pytania doprecyzowujące. Komunikacja niewerbalna – mowa ciała, ton, dystans; często silniejsza niż słowa. Asertywność – wyrażanie swoich potrzeb i odmowa z szacunkiem dla innych, pomiędzy uległością a agresją. Konstruktywna informacja zwrotna – konkretna, dotycząca zachowania, nie osoby."),
          K("Taktyki negocjacyjne",
            "Salami – uzyskiwanie ustępstw kawałek po kawałku; dobry i zły policjant – jeden negocjator naciska, drugi „łagodzi”; wysoka piłka – zawyżona oferta otwarcia; fakty dokonane – postawienie drugiej strony przed gotową sytuacją. Rozpoznanie taktyki pozwala ją zneutralizować."),
          PF("Rozsądny negocjator przyjmuje ofertę gorszą od swojej BATNA, by zawrzeć porozumienie.", False,
             why="BATNA wyznacza minimum – gorszą ofertę się odrzuca."),
      ],
      mech=[
          LN("Ułóż etapy procesu HRM.",
             ["Planowanie zatrudnienia", "Rekrutacja", "Selekcja", "Adaptacja i szkolenie", "Ocena okresowa"],
             why="Od określenia potrzeb do oceny pracy."),
          KT("Rekrutacja wewnętrzna czy zewnętrzna?",
             {"Wewnętrzna": ["Awans specjalisty na kierownika zespołu", "Przeniesienie pracownika z innego działu"],
              "Zewnętrzna": ["Ogłoszenie w portalu z ofertami pracy", "Zlecenie łowcy głów (head hunting)"]},
             why="Źródło kandydatów: wewnątrz lub poza firmą."),
          KT("Jaka taktyka negocjacyjna?",
             {"Salami": ["Prośba o drobny rabat, potem o darmową dostawę, potem o dłuższy termin płatności", "Kolejne małe ustępstwa wymuszane osobno"],
              "Dobry i zły policjant": ["Jeden negocjator grozi zerwaniem rozmów, drugi proponuje kompromis", "Szef krzyczy, asystent „ratuje” sytuację"],
              "Wysoka piłka": ["Oferta otwarcia dwukrotnie wyższa od oczekiwanej ceny", "Żądanie podwyżki o 50%, by uzyskać 15%"]},
             why="Rozpoznanie taktyki ułatwia obronę."),
          W("Na czym polega skupienie się na interesach, a nie stanowiskach?",
            "Na szukaniu potrzeb stojących za żądaniami stron", "Na upieraniu się przy pierwszej ofercie", "Na ustępowaniu we wszystkim",
            why="Różne stanowiska mogą kryć zgodne interesy."),
          W("Która wypowiedź jest asertywna?",
            "„Nie mogę dziś zostać po godzinach, mogę jutro rano dokończyć raport”", "„Dobrze, zostanę, choć mam inne plany”", "„Nigdy więcej nie proś mnie o takie rzeczy!”",
            why="Asertywność to stanowczość z szacunkiem dla drugiej strony."),
          PF("Outplacement to pomoc zwalnianym pracownikom w znalezieniu nowej pracy.", True,
             why="Element odpowiedzialnego zwalniania."),
      ],
      calc=[
          LB("Na ogłoszenie odpowiedziało 120 osób, zatrudniono 3. Ile kandydatów przypada na jedno miejsce?",
             40, "120/3", ["120 / 3 = 40"], unit="kandydatów"),
          LB("Rekrutacja kosztowała 36 tys. zł i dała 3 zatrudnienia. Koszt jednego zatrudnienia (tys. zł)?",
             12, "36/3", ["36 / 3 = 12 tys. zł"], unit="tys. zł"),
          LB("Ocena 360°: przełożony 4, współpracownicy 3, podwładni 5, samoocena 4. Średnia ocena?",
             4, "(4+3+5+4)/4", ["(4 + 3 + 5 + 4) / 4 = 4"], unit="pkt"),
          LB("Kupujący ma BATNA: 100 tys. zł u innego dostawcy. Sprzedawca żąda 108 tys. zł. O ile tys. zł oferta jest gorsza od BATNA kupującego?",
             8, "108-100", ["108 − 100 = 8 tys. zł – kupujący powinien odmówić lub negocjować"], unit="tys. zł"),
          LB("Sprzedawca nie zejdzie poniżej 95 tys. zł, kupujący nie zapłaci więcej niż 100 tys. zł. Jak szeroka jest strefa możliwego porozumienia (tys. zł)?",
             5, "100-95", ["100 − 95 = 5 tys. zł"], unit="tys. zł"),
          LB("Szkolenie kosztowało 20 tys. zł i obniżyło koszty błędów o 50 tys. zł. Zwrot z inwestycji ROI (%)?",
             150, "(50-20)/20*100", ["(50 − 20) / 20 · 100 = 150%"], unit="%"),
      ],
      case=[
          PR("Producent mebli negocjuje z siecią sklepów. Sieć żąda ceny 400 zł za szafę, producent chce 500 zł. Okazuje się, że sieci najbardziej zależy na pewności terminów dostaw przed sezonem, a producentowi – na stałym, przewidywalnym zamówieniu. Producent ma też ofertę innej sieci po 440 zł.",
             W("Ile wynosi BATNA producenta?",
               "Oferta innej sieci – 440 zł", "500 zł – jego żądanie", "400 zł – żądanie sieci",
               why="BATNA to najlepsza alternatywa poza tymi negocjacjami."),
             W("Co zaleciliby Fisher i Ury?",
               "Skupić się na interesach: gwarancja terminów w zamian za stałe zamówienie", "Twardo żądać 500 zł bez względu na wszystko", "Od razu zaakceptować 400 zł",
               why="Interesy stron okazują się zgodne."),
             PF("Producent nie powinien przyjąć ceny 420 zł bez dodatkowych korzyści.", True,
                why="To mniej niż jego BATNA (440 zł)."),
          ),
          PR("Firma IT szuka kierownika projektu. Rozważa awans jednego z programistów albo zatrudnienie z rynku przez agencję. Kandydatów poddaje jednodniowym ćwiczeniom grupowym i symulacjom ocenianym przez trzech obserwatorów. Po roku nowy kierownik dostaje oceny od szefa, zespołu, klientów i własną samoocenę.",
             W("Jak nazywa się metoda selekcji z ćwiczeniami i obserwatorami?",
               "Assessment center", "Outplacement", "Benchmarking",
               why="Zestaw ćwiczeń ocenianych przez kilku obserwatorów."),
             W("Jaka metoda oceny została zastosowana po roku?",
               "Ocena 360°", "Fotografia dnia roboczego", "Metoda delficka",
               why="Opinie z wielu kierunków i samoocena."),
             W("Awans programisty to rekrutacja…",
               "Wewnętrzna", "Zewnętrzna", "Outsourcingowa",
               why="Kandydat pochodzi z firmy."),
          ),
      ]),
]
