# -*- coding: utf-8 -*-
# Zrozumienie – Zarządzanie / Motywacja, przywództwo i zespoły
OSM = "https://openstax.org/books/principles-management/pages/"
D = "2026-10-08"
M135 = S("OpenStax, Principles of Management, 13.5 Behavioral Approaches to Leadership", OSM + "13-5-behavioral-approaches-to-leadership", D)
M134 = S("OpenStax, Principles of Management, 13.4 The Trait Approach to Leadership", OSM + "13-4-the-trait-approach-to-leadership", D)
M136 = S("OpenStax, Principles of Management, 13.6 Situational (Contingency) Approaches to Leadership", OSM + "13-6-situational-contingency-approaches-to-leadership", D)
M138 = S("OpenStax, Principles of Management, 13.8 Transformational, Visionary, and Charismatic Leadership", OSM + "13-8-transformational-visionary-and-charismatic-leadership", D)
M142 = S("OpenStax, Principles of Management, 14.2 Content Theories of Motivation", OSM + "14-2-content-theories-of-motivation", D)
M143 = S("OpenStax, Principles of Management, 14.3 Process Theories of Motivation", OSM + "14-3-process-theories-of-motivation", D)
M152 = S("OpenStax, Principles of Management, 15.2 Team Development Over Time", OSM + "15-2-team-development-over-time", D)
M153 = S("OpenStax, Principles of Management, 15.3 Things to Consider When Managing Teams", OSM + "15-3-things-to-consider-when-managing-teams", D)
M162 = S("OpenStax, Principles of Management, 16.2 Types of Communications in Organizations", OSM + "16-2-types-of-communications-in-organizations", D)

LESSONS = [
    L(1, "Treściowe teorie motywacji",
      "Rozumieć, czym jest motywacja, i porównywać teorie potrzeb: hierarchię Maslowa, teorię ERG Alderfera, dwuczynnikową teorię Herzberga i teorię potrzeb McClellanda.",
      ["Motywacja", "Hierarchia potrzeb Maslowa", "Teoria ERG (C. Alderfer)", "Dwuczynnikowa teoria Herzberga", "Teoria potrzeb McClellanda"],
      [M142],
      explain=[
          K("Motywacja",
            "Motywacja to procesy, które nadają zachowaniu kierunek (na co się wysilamy), intensywność (jak bardzo) i trwałość (jak długo). Teorie treści pytają, CO motywuje (jakie potrzeby), teorie procesu – JAK powstaje motywacja (oczekiwania, porównania, cele). Wynik pracy zależy od motywacji, zdolności i warunków."),
          K("Maslow (1943) i Alderfer",
            "Maslow: potrzeby fizjologiczne → bezpieczeństwa → przynależności → uznania → samorealizacji; niezaspokojona potrzeba niższa dominuje, a zaspokojona przestaje motywować. Alderfer (ERG) upraszcza do trzech grup: egzystencji, relacji i rozwoju; kilka potrzeb może działać naraz, a frustracja potrzeby wyższej kieruje człowieka z powrotem ku niższej (frustracja–regresja)."),
          W("Pracownik, który nie ma szans na awans, zaczyna mocno zabiegać o podwyżki i dobre relacje. Którą zasadę to ilustruje?",
            "Frustracja–regresja w teorii ERG", "Hierarchię Maslowa w ścisłej kolejności", "Teorię X McGregora",
            why="Zablokowany rozwój kieruje uwagę ku potrzebom niższym."),
          K("Herzberg (1959)",
            "Czynniki higieny (płaca, warunki pracy, polityka firmy, nadzór, relacje) – ich brak wywołuje niezadowolenie, ale ich obecność nie motywuje, tylko usuwa niezadowolenie. Motywatory (osiągnięcia, uznanie, sama praca, odpowiedzialność, rozwój) – wywołują zadowolenie i motywację. Wniosek: wzbogacanie pracy."),
          K("McClelland",
            "Trzy wyuczone potrzeby: osiągnięć (nAch – ambitne, ale realne cele, informacja zwrotna), władzy (nPow – wpływ na innych; władza instytucjonalna sprzyja kierowaniu) i przynależności (nAff – relacje, akceptacja). Osoby o wysokiej nAch są dobrymi przedsiębiorcami, ale niekoniecznie menedżerami dużych firm."),
          PF("Według Herzberga podwyżka płacy sama w sobie trwale motywuje pracownika.", False,
             why="Płaca to czynnik higieny – usuwa niezadowolenie, nie motywuje."),
      ],
      mech=[
          KT("Czynnik higieny czy motywator (Herzberg)?",
             {"Czynnik higieny": ["Wysokość wynagrodzenia", "Warunki pracy w biurze", "Relacje z przełożonym"],
              "Motywator": ["Uznanie za osiągnięcia", "Odpowiedzialność za projekt", "Możliwość rozwoju"]},
             why="Higiena usuwa niezadowolenie, motywatory budują zadowolenie."),
          LN("Ułóż poziomy hierarchii Maslowa od najniższego.",
             ["Potrzeby fizjologiczne", "Potrzeby bezpieczeństwa", "Potrzeby przynależności", "Potrzeby uznania", "Potrzeba samorealizacji"],
             why="Kolejność od podstawowych do najwyższych."),
          W("Pracownik o wysokiej potrzebie osiągnięć (McClelland) najchętniej wybierze:",
            "Ambitne, ale realne zadanie z szybką informacją o wynikach", "Zadanie bardzo łatwe", "Zadanie praktycznie niewykonalne",
            why="nAch preferuje umiarkowane ryzyko i feedback."),
          W("Czym teoria ERG różni się od teorii Maslowa?",
            "Kilka potrzeb może działać jednocześnie i możliwa jest regresja", "Ma więcej poziomów", "Ignoruje potrzeby rozwoju",
            why="Alderfer odrzucił sztywną kolejność."),
          M("Które potrzeby wyróżnia McClelland?",
            ["Osiągnięć", "Władzy", "Przynależności", "Fizjologiczne"], [0, 1, 2],
            why="Potrzeby fizjologiczne to poziom Maslowa."),
          PF("Teorie treści pytają, jakie potrzeby motywują ludzi.", True,
             why="Teorie procesu pytają, jak powstaje motywacja."),
      ],
      calc=[
          LB("W badaniu 200 pracowników 70 wskazało rozwój jako najważniejszy czynnik. Jaki to procent?",
             35, "70/200*100", ["70 / 200 = 35%"], unit="%"),
          LB("Podwyżka 8% podnosi zadowolenie, ale po roku wskaźnik wraca z 72 do 65 pkt (przed podwyżką 64). Ile punktów trwałego wzrostu zostało?",
             1, "65-64", ["65 − 64 = 1 pkt"], unit="pkt"),
          LB("Maslow opublikował teorię w 1943 r., Herzberg w 1959 r. Ile lat różnicy?",
             16, "1959-1943", ["1959 − 1943 = 16"], unit="lat"),
          LB("Ile poziomów potrzeb mniej ma teoria ERG niż hierarchia Maslowa (5 poziomów)?",
             2, "5-3", ["5 − 3 = 2"], unit="poz."),
          LB("Program uznania kosztuje 50 000 zł rocznie i obniża odejścia o 5 osób; zastąpienie pracownika kosztuje 30 000 zł. Ile wynosi oszczędność netto (zł)?",
             100000, "5*30000-50000", ["5 · 30 000 − 50 000 = 100 000 zł"], unit="zł"),
          LB("Zespół 12 osób: 3 o dominującej potrzebie władzy, 5 – osiągnięć, reszta – przynależności. Jaki odsetek ma potrzebę przynależności (%)?",
             33.33, "(12-3-5)/12*100", ["4 / 12 ≈ 33,33%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Firma podniosła płace o 10%, ale ankieta pokazuje, że pracownicy nadal czują się niedocenieni i nie widzą możliwości rozwoju. Rotacja się nie zmniejszyła.",
             W("Jak teoria Herzberga wyjaśnia sytuację?",
               "Płaca to czynnik higieny – brakuje motywatorów: uznania i rozwoju", "Płace były wciąż za niskie", "Pracownicy mają za dużo odpowiedzialności",
               why="Usunięto niezadowolenie, ale nie zbudowano motywacji."),
             W("Co powinna wprowadzić firma?",
               "Ścieżki rozwoju, uznanie i więcej odpowiedzialności", "Kolejną podwyżkę", "Ścisłą kontrolę",
               why="To motywatory według Herzberga."),
             PF("Podwyżka mogła zapobiec jeszcze większemu niezadowoleniu.", True,
                why="Czynniki higieny ograniczają niezadowolenie."),
          ),
          PR("Kierowniczka zespołu sprzedaży zauważa: Anna lubi rywalizację i cele z wyraźnym wynikiem, Bartek chętnie wpływa na decyzje i prowadzi spotkania, a Celina najlepiej pracuje w zgranej grupie i źle znosi konflikty.",
             W("Jaką potrzebę dominującą ma Bartek?",
               "Władzy", "Osiągnięć", "Przynależności",
               why="Chce wpływać na innych i decyzje."),
             W("Jakie zadanie najlepiej zmotywuje Annę?",
               "Indywidualny, mierzalny cel sprzedażowy z szybkim feedbackiem", "Organizację imprezy firmowej", "Zadanie bez określonego wyniku",
               why="Wysoka potrzeba osiągnięć."),
             PF("Celinę najlepiej motywuje praca zespołowa i dobra atmosfera.", True,
                why="Ma wysoką potrzebę przynależności."),
          ),
      ]),

    L(2, "Procesowe teorie motywacji i wynagradzanie",
      "Rozumieć teorię oczekiwań Vrooma, teorię sprawiedliwości Adamsa i teorię wyznaczania celów oraz projektować system motywacyjny i wynagrodzeń.",
      ["Teoria oczekiwań (V. Vroom)", "Teoria sprawiedliwości (J.S. Adams)", "Systemy motywacyjne i wynagrodzeń", "Motywacja"],
      [M143, M142],
      explain=[
          K("Teoria oczekiwań (Vroom, 1964)",
            "Motywacja = oczekiwanie (E: czy wysiłek da wynik) × instrumentalność (I: czy wynik da nagrodę) × walencja (V: jak cenię nagrodę). Ponieważ to iloczyn, zero w którymkolwiek elemencie oznacza brak motywacji. Menedżer powinien: zapewnić zasoby i szkolenia (E), dotrzymywać obietnic nagród (I), dobierać nagrody cenione przez pracownika (V).",
            w="M = E · I · V"),
          K("Teoria sprawiedliwości (Adams, 1963)",
            "Pracownik porównuje stosunek swoich efektów (płaca, uznanie) do nakładów (wysiłek, kwalifikacje, czas) z takim stosunkiem innych osób. Przy poczuciu niedopłacenia obniża wysiłek, żąda podwyżki, zmienia punkt odniesienia lub odchodzi. Liczy się postrzegana, nie obiektywna sprawiedliwość.",
            w="efekty A / nakłady A  vs  efekty B / nakłady B"),
          W("E = 0,9, I = 0, V = 1. Ile wynosi motywacja według Vrooma?",
            "Zero – pracownik nie wierzy, że wynik da nagrodę", "0,9", "1,9",
            why="Iloczyn z czynnikiem zerowym wynosi zero."),
          K("Teoria wyznaczania celów (Locke)",
            "Cele konkretne i trudne (ale akceptowane) dają lepsze wyniki niż „rób, co możesz”. Warunki: zaangażowanie w cel, informacja zwrotna, odpowiednie zdolności. Praktyka: cele SMART i zarządzanie przez cele (MBO)."),
          K("System wynagrodzeń",
            "Składniki: płaca zasadnicza (wartościowanie stanowisk), premie i prowizje (za wyniki), świadczenia (opieka medyczna, PPK, karta sportowa), nagrody niefinansowe (uznanie, rozwój, elastyczność). Dobry system jest postrzegany jako sprawiedliwy (wewnętrznie i wobec rynku) i jasno łączy wynik z nagrodą. Uwaga: zbyt silne premie mogą zachęcać do „gry” wskaźnikami."),
          PF("W teorii sprawiedliwości Adamsa liczy się subiektywne poczucie sprawiedliwości.", True,
             why="Pracownik reaguje na to, jak postrzega porównanie."),
      ],
      mech=[
          KT("Który element teorii Vrooma?",
             {"Oczekiwanie (E)": ["„Jeśli się postaram, osiągnę cel sprzedaży”", "Szkolenie zwiększające umiejętności"],
              "Instrumentalność (I)": ["„Jeśli osiągnę cel, firma naprawdę wypłaci premię”", "Dotrzymywanie obietnic przez kierownika"],
              "Walencja (V)": ["„Bardzo zależy mi na dodatkowym dniu wolnym”", "Nagroda dobrana do preferencji pracownika"]},
             why="Każdy element wymaga innego działania menedżera."),
          LN("Ułóż reakcję na poczucie niedopłacenia według Adamsa.",
             ["Pracownik porównuje swoje efekty i nakłady z kolegą", "Stwierdza, że kolega dostaje więcej za ten sam wysiłek", "Odczuwa napięcie i niesprawiedliwość", "Obniża wysiłek lub domaga się podwyżki", "Gdy nic się nie zmienia, szuka innej pracy"],
             why="Niesprawiedliwość wywołuje działania korygujące."),
          W("Pracownik wie, że premie są przyznawane według uznania szefa, a nie wyników. Który element Vrooma jest niski?",
            "Instrumentalność", "Oczekiwanie", "Walencja",
            why="Wynik nie przekłada się wiarygodnie na nagrodę."),
          W("Który cel jest najlepszy według teorii Locke’a?",
            "Zwiększyć sprzedaż o 12% do końca kwartału", "Starać się sprzedawać więcej", "Robić, co się da",
            why="Cel konkretny, trudny i mierzalny."),
          M("Jak pracownik może zareagować na poczucie niedopłacenia?",
            ["Obniżyć wysiłek", "Zażądać podwyżki", "Zmienić osobę, z którą się porównuje", "Zawsze zwiększyć wysiłek"], [0, 1, 2],
            why="Zwiększenie wysiłku to typowa reakcja na nadpłacenie."),
          PF("Zbyt silne premie za jeden wskaźnik mogą prowadzić do manipulowania wynikami.", True,
             why="Pracownicy optymalizują mierzony wskaźnik kosztem innych celów."),
      ],
      calc=[
          LB("E = 0,8, I = 0,5, V = 0,9. Ile wynosi M według Vrooma?",
             0.36, "0.8*0.5*0.9", ["0,8 · 0,5 · 0,9 = 0,36"], unit="", tol=0.001),
          LB("Po wprowadzeniu jasnych zasad premii I rośnie do 0,9 (E = 0,8, V = 0,9). Ile wynosi M?",
             0.648, "0.8*0.9*0.9", ["0,8 · 0,9 · 0,9 = 0,648"], unit="", tol=0.001),
          LB("Anna zarabia 7 200 zł za 40 h, Bartek 6 000 zł za 40 h. Ile zł za godzinę dostaje Anna więcej?",
             30, "7200/40-6000/40", ["180 − 150 = 30 zł/h"], unit="zł/h"),
          LB("Płaca zasadnicza 6 000 zł, premia 15% płacy zasadniczej. Ile wynosi wynagrodzenie (zł)?",
             6900, "6000*1.15", ["6 000 · 1,15 = 6 900 zł"], unit="zł"),
          LB("Prowizja 3% od sprzedaży 180 000 zł i podstawa 4 500 zł. Ile wynosi wynagrodzenie (zł)?",
             9900, "4500+0.03*180000", ["4 500 + 5 400 = 9 900 zł"], unit="zł"),
          LB("Cel sprzedaży 500 000 zł, wykonanie 560 000 zł. Ile procent celu wykonano?",
             112, "560000/500000*100", ["560 / 500 = 112%"], unit="%"),
      ],
      case=[
          PR("Handlowcy mają premię za przekroczenie celu, ale cele są ustalane tak wysoko, że w ostatnich trzech latach osiągnęło je tylko 5% osób. Motywacja zespołu spada.",
             W("Który element teorii Vrooma jest najsłabszy?",
               "Oczekiwanie – ludzie nie wierzą, że osiągną cel", "Walencja – nikt nie chce pieniędzy", "Żaden",
               why="Cel postrzegany jako nieosiągalny."),
             W("Co zaleca teoria wyznaczania celów?",
               "Cele trudne, ale osiągalne i akceptowane", "Cele jak najwyższe", "Rezygnację z celów",
               why="Cel nieakceptowany nie motywuje."),
             PF("Obniżenie celu do realnego poziomu może zwiększyć łączną sprzedaż.", True,
                why="Więcej osób podejmie wysiłek."),
          ),
          PR("Nowo zatrudniony programista dostał wynagrodzenie o 20% wyższe niż doświadczeni koledzy na tym samym stanowisku. Informacja wyciekła. Dwóch seniorów zaczęło szukać pracy, a jeden ograniczył się do minimum.",
             W("Jaką teorię ilustruje reakcja seniorów?",
               "Teorię sprawiedliwości Adamsa", "Hierarchię Maslowa", "Teorię cech przywódczych",
               why="Porównują stosunek efektów do nakładów."),
             W("Jakie działanie firmy jest najbardziej sensowne?",
               "Przegląd i wyrównanie płac według przejrzystych zasad", "Zwolnienie nowego pracownika", "Ukrywanie płac",
               why="Przywraca poczucie sprawiedliwości wewnętrznej."),
             PF("Unijna dyrektywa o przejrzystości wynagrodzeń wzmacnia znaczenie sprawiedliwości płacowej.", True,
                why="Dyrektywa 2023/970 nakłada obowiązki jawności płac."),
          ),
      ]),

    L(3, "Przywództwo: cechy, style i siatka kierownicza",
      "Odróżniać przywództwo od kierowania, rozumieć teorie cech i podejście behawioralne: style Lewina, cztery systemy Likerta oraz siatkę kierowniczą Blake’a i Mouton.",
      ["Przywództwo", "Teorie cech przywódczych", "Style kierowania: autokratyczny, demokratyczny, liberalny", "Systemy zarządzania R. Likerta", "Siatka kierownicza (Blake i Mouton)"],
      [M134, M135],
      explain=[
          K("Przywództwo a kierowanie",
            "Przywództwo to zdolność wpływania na ludzi, by dobrowolnie dążyli do celów. Kierownik ma władzę formalną (z pozycji), przywódca może też mieć władzę osobistą. Źródła władzy (French i Raven): nagradzania, przymusu, prawomocna (formalna), ekspercka i odniesienia (charyzma, sympatia)."),
          K("Teorie cech",
            "Najstarsze podejście szukało wrodzonych cech „wielkich ludzi”. Badania wskazują związek z przywództwem m.in. inteligencji, pewności siebie, determinacji, uczciwości i ekstrawersji, ale same cechy słabo przewidują skuteczność – liczy się zachowanie i sytuacja."),
          W("Podwładni słuchają głównej księgowej, bo ma ogromną wiedzę o podatkach, choć nie jest ich szefową. To władza:",
            "Ekspercka", "Przymusu", "Prawomocna",
            why="Wpływ wynika z wiedzy, nie ze stanowiska."),
          K("Style kierowania (Lewin) i Likert",
            "Lewin: autokratyczny (szef decyduje sam), demokratyczny (konsultuje i angażuje), liberalny/laissez-faire (pozostawia swobodę). Likert opisał cztery systemy: 1 – autorytarny eksploatatorski, 2 – autorytarny życzliwy, 3 – konsultacyjny, 4 – partycypacyjny (grupowy); najlepsze wyniki dawał system 4."),
          K("Siatka kierownicza (Blake i Mouton, 1964)",
            "Dwa wymiary w skali 1–9: troska o produkcję (zadania) i troska o ludzi. Style: 1.1 zubożały, 1.9 „klub towarzyski”, 9.1 zadaniowy (władza–posłuszeństwo), 5.5 środka drogi, 9.9 zespołowy – za najlepszy uznany 9.9 (wysoka troska o oba wymiary). Badania Ohio i Michigan opisywały podobne wymiary: inicjowanie struktury i względy dla ludzi."),
          PF("W siatce Blake’a i Mouton styl 1.9 to wysoka troska o ludzi przy niskiej trosce o zadania.", True,
             why="To styl „klubu towarzyskiego”."),
      ],
      mech=[
          KT("Styl w siatce kierowniczej",
             {"9.1 zadaniowy": ["Liczą się tylko terminy i normy, ludzie mają wykonywać polecenia"],
              "1.9 klub towarzyski": ["Przede wszystkim miła atmosfera, wyniki są drugorzędne"],
              "1.1 zubożały": ["Kierownik robi minimum, by utrzymać stanowisko"],
              "9.9 zespołowy": ["Wysokie cele osiągane dzięki zaangażowaniu zespołu"],
              "5.5 środka drogi": ["Kompromis: przyzwoite wyniki i umiarkowane morale"]},
             why="Kombinacje troski o zadania i o ludzi."),
          LN("Ułóż systemy Likerta od najbardziej autorytarnego.",
             ["System 1 – autorytarny eksploatatorski", "System 2 – autorytarny życzliwy", "System 3 – konsultacyjny", "System 4 – partycypacyjny"],
             why="Rośnie udział pracowników w decyzjach."),
          W("Kierownik ogłasza decyzję bez pytania zespołu o zdanie. Jaki to styl według Lewina?",
            "Autokratyczny", "Demokratyczny", "Liberalny",
            why="Decyzja podjęta jednoosobowo."),
          W("Dlaczego teorie cech okazały się niewystarczające?",
            "Same cechy słabo przewidują skuteczność w różnych sytuacjach", "Nie ma żadnych cech osobowości", "Bo badały tylko kobiety",
            why="Skuteczność zależy też od zachowań i kontekstu."),
          M("Które źródła władzy wyróżnili French i Raven?",
            ["Władza nagradzania", "Władza ekspercka", "Władza odniesienia", "Władza losowa"], [0, 1, 2],
            why="Do tego władza przymusu i prawomocna."),
          PF("Styl liberalny może działać dobrze w zespole doświadczonych ekspertów.", True,
             why="Kompetentni i zmotywowani ludzie potrzebują swobody."),
      ],
      calc=[
          LB("Ile pól (kombinacji stylów) ma siatka 9 × 9?",
             81, "9*9", ["9 · 9 = 81"], unit="pól"),
          LB("Ocena kierownika: troska o zadania 7, o ludzi 3. O ile punktów brakuje mu do 9.9 łącznie w obu wymiarach?",
             8, "(9-7)+(9-3)", ["2 + 6 = 8"], unit="pkt"),
          LB("Systemy Likerta zostały opisane w 1967 r., siatka Blake’a i Mouton w 1964 r. Ile lat różnicy?",
             3, "1967-1964", ["1967 − 1964 = 3"], unit="lata"),
          LB("W ankiecie 60 z 80 pracowników chce stylu demokratycznego. Jaki to procent?",
             75, "60/80*100", ["60 / 80 = 75%"], unit="%"),
          LB("Premia za wyniki 1 200 zł miesięcznie dla 15 osób (władza nagradzania). Ile kosztuje rocznie (zł)?",
             216000, "1200*15*12", ["1 200 · 15 · 12 = 216 000 zł"], unit="zł"),
          LB("Po zmianie stylu na partycypacyjny absencja spadła z 5% do 3,5%. O ile procent?",
             30, "(1-3.5/5)*100", ["3,5 / 5 = 0,7 → spadek 30%"], unit="%"),
      ],
      case=[
          PR("Nowy kierownik zakładu wymaga ścisłego trzymania się norm, karze za każde spóźnienie i nie rozmawia z pracownikami. Wydajność na krótko wzrosła, ale po pół roku rośnie absencja i odchodzą najlepsi.",
             W("Jaki styl stosuje kierownik w siatce Blake’a i Mouton?",
               "9.1 zadaniowy", "1.9 klub towarzyski", "9.9 zespołowy",
               why="Wysoka troska o zadania, niska o ludzi."),
             W("Na którym źródle władzy opiera się głównie?",
               "Władzy przymusu", "Władzy odniesienia", "Władzy eksperckiej",
               why="Opiera wpływ na karach i strachu."),
             PF("Przejście ku stylowi 9.9 mogłoby poprawić zarówno morale, jak i wyniki.", True,
                why="Łączy wysokie wymagania z troską o ludzi."),
          ),
          PR("Kierowniczka laboratorium badawczego zatrudnia doświadczonych naukowców. Ustala z nimi cele roczne, a potem pozostawia im swobodę wyboru metod, wspierając zasobami. Wyniki zespołu są bardzo dobre.",
             W("Jaki styl Lewina jest jej najbliższy?",
               "Liberalny (z jasnymi celami)", "Autokratyczny", "Eksploatatorski",
               why="Pozostawia swobodę kompetentnym ludziom."),
             W("Dlaczego ten styl działa w tej sytuacji?",
               "Zespół jest kompetentny i wewnętrznie zmotywowany", "Bo naukowcy nie potrzebują celów", "Bo zespół jest nowy i niedoświadczony",
               why="Styl dopasowany do dojrzałości zespołu."),
             PF("Ten sam styl w zespole nowych, niedoświadczonych osób mógłby zawieść.", True,
                why="Potrzebowaliby instrukcji i wsparcia."),
          ),
      ]),

    L(4, "Sytuacyjne i nowoczesne teorie przywództwa",
      "Rozumieć, dlaczego skuteczny styl zależy od sytuacji: model Fiedlera, teorię ścieżki do celu, model Herseya–Blancharda, model Vrooma–Yettona–Jago, LMX oraz przywództwo transformacyjne.",
      ["Model LPC F. Fiedlera", "Teoria ścieżki do celu (R. House)", "Teoria cyklu życia (Hersey i Blanchard)", "Model Vrooma–Yettona–Jago", "Model LMX (wymiany przywódca–członek)", "Przywództwo transformacyjne i charyzmatyczne"],
      [M136, M138],
      explain=[
          K("Fiedler (model LPC)",
            "Styl lidera jest stały i mierzony skalą LPC (ocena „najmniej lubianego współpracownika”): niski LPC – lider zadaniowy, wysoki – nastawiony na relacje. Sprzyjanie sytuacji zależy od relacji lider–członkowie, struktury zadania i władzy formalnej (2 · 2 · 2 = 8 sytuacji). Lider zadaniowy jest skuteczny w sytuacjach bardzo korzystnych i bardzo niekorzystnych, relacyjny – w umiarkowanych. Skoro styl jest stały, trzeba dopasować lidera do sytuacji."),
          K("House i Hersey–Blanchard",
            "Ścieżka do celu (House, 1971): lider ma „oczyścić ścieżkę” do celu i nagrody, stosując styl dyrektywny, wspierający, partycypacyjny lub nastawiony na osiągnięcia – zależnie od podwładnych i zadania. Hersey–Blanchard: styl zależy od gotowości pracownika: instruowanie (S1, niskie umiejętności i chęci), przekonywanie (S2), uczestniczenie (S3), delegowanie (S4, wysokie umiejętności i chęci)."),
          W("Nowy pracownik bardzo chce się uczyć, ale nie ma jeszcze umiejętności. Jaki styl zaleca model Herseya–Blancharda?",
            "Przekonywanie (S2) – dużo instrukcji i wsparcia", "Delegowanie (S4)", "Brak jakiegokolwiek nadzoru",
            why="Chęci są, umiejętności brak – potrzeba kierowania i wsparcia."),
          K("Vroom–Yetton–Jago i LMX",
            "Model Vrooma–Yettona (1973), rozwinięty z Jago (1988), pomaga wybrać stopień udziału podwładnych w decyzji (od autokratycznej przez konsultacyjną po grupową) na podstawie pytań: jak ważna jest jakość decyzji, czy potrzebna jest akceptacja zespołu, czy lider ma informacje, ile jest czasu. LMX: lider tworzy z częścią podwładnych relacje wysokiej jakości („grupa wewnętrzna” – zaufanie, więcej zadań i wsparcia), z innymi – formalne („grupa zewnętrzna”)."),
          K("Przywództwo transformacyjne i charyzmatyczne",
            "Transakcyjne: wymiana nagród za wykonanie zadań. Transformacyjne (Burns, Bass): lider inspiruje wizją, stymuluje intelektualnie, indywidualnie traktuje ludzi i jest wzorem – pracownicy przekraczają własny interes. Charyzma budzi silne oddanie, ale grozi kultem lidera i nadużyciami."),
          PF("Według Fiedlera najlepiej zmienić styl lidera, gdy sytuacja się zmienia.", False,
             why="Fiedler uważał styl za stały – dopasowuje się lidera lub sytuację."),
      ],
      mech=[
          KT("Styl według Herseya–Blancharda",
             {"S1 instruowanie": ["Nowy pracownik bez umiejętności i niepewny siebie"],
              "S2 przekonywanie": ["Entuzjastyczny stażysta bez doświadczenia"],
              "S3 uczestniczenie": ["Doświadczony pracownik, który stracił pewność siebie"],
              "S4 delegowanie": ["Ekspert, który chce samodzielnie prowadzić projekt", "Doświadczony i zmotywowany kierownik zmiany"]},
             why="Styl dopasowany do gotowości pracownika."),
          LN("Ułóż rozumowanie w modelu Fiedlera.",
             ["Mierzymy styl lidera skalą LPC", "Oceniamy relacje lider–członkowie", "Oceniamy strukturę zadania i władzę formalną", "Ustalamy, jak korzystna jest sytuacja", "Dopasowujemy lidera do sytuacji lub zmieniamy sytuację"],
             why="Styl uznany za stały, więc dopasowuje się sytuację."),
          W("Zespół jest zdezorientowany, zadanie niejasne. Jaki styl zaleca teoria ścieżki do celu?",
            "Dyrektywny", "Wyłącznie wspierający", "Delegujący",
            why="Lider wyjaśnia zadanie i drogę do celu."),
          W("Co odróżnia przywództwo transformacyjne od transakcyjnego?",
            "Inspirowanie wizją i rozwój ludzi zamiast samej wymiany nagród za zadania", "Wyższe premie", "Brak celów",
            why="Transformacyjne zmienia wartości i zaangażowanie."),
          M("Od czego zależy sprzyjanie sytuacji w modelu Fiedlera?",
            ["Relacji lider–członkowie", "Struktury zadania", "Władzy formalnej lidera", "Wieku lidera"], [0, 1, 2],
            why="Trzy wymiary dają 8 sytuacji."),
          PF("W modelu LMX pracownicy z „grupy wewnętrznej” zwykle dostają więcej zaufania i wsparcia.", True,
             why="Relacja wysokiej jakości z liderem."),
      ],
      calc=[
          LB("Ile sytuacji wyróżnia Fiedler przy trzech wymiarach po dwa poziomy?",
             8, "2**3", ["2 · 2 · 2 = 8"], unit="sytuacji"),
          LB("Lider ma w grupie wewnętrznej 4 z 10 osób. Jaki odsetek zespołu jest w grupie zewnętrznej (%)?",
             60, "6/10*100", ["6 / 10 = 60%"], unit="%"),
          LB("Model Vrooma–Yettona powstał w 1973 r., rozszerzenie z Jago w 1988 r. Ile lat różnicy?",
             15, "1988-1973", ["1988 − 1973 = 15"], unit="lat"),
          LB("Zaangażowanie zespołu wzrosło z 55 do 77 pkt po wprowadzeniu lidera transformacyjnego. O ile procent?",
             40, "(77/55-1)*100", ["77 / 55 = 1,4 → +40%"], unit="%"),
          LB("Stażysta po 6 miesiącach przechodzi z S2 do S3; kierownik skraca czas instruowania z 10 h do 4 h tygodniowo. O ile procent?",
             60, "(1-4/10)*100", ["4 / 10 = 0,4 → spadek 60%"], unit="%"),
          LB("Decyzja autokratyczna zajmuje 1 h, grupowa – 6 h dla 6 osób każda. Ile osobogodzin więcej kosztuje decyzja grupowa?",
             35, "6*6-1", ["36 − 1 = 35"], unit="h"),
      ],
      case=[
          PR("Kierownik zmiany w magazynie ma bardzo dobre relacje z zespołem, jasno opisane procedury i pełną władzę formalną. Jest liderem silnie zadaniowym (niski LPC).",
             W("Jak korzystna jest sytuacja według Fiedlera?",
               "Bardzo korzystna", "Umiarkowana", "Bardzo niekorzystna",
               why="Dobre relacje, ustrukturyzowane zadanie, silna władza."),
             W("Czy lider zadaniowy będzie tu skuteczny według Fiedlera?",
               "Tak – lider zadaniowy sprawdza się w sytuacjach bardzo korzystnych", "Nie – potrzebny lider relacyjny", "Model tego nie przewiduje",
               why="Niski LPC skuteczny na krańcach skali."),
             PF("W sytuacji umiarkowanie korzystnej Fiedler przewidywał lepsze wyniki lidera relacyjnego.", True,
                why="Wysoki LPC w sytuacjach pośrednich."),
          ),
          PR("Dyrektorka musi zdecydować o reorganizacji grafików pracy pielęgniarek. Decyzja wymaga akceptacji zespołu, bo bez niej grafik nie zadziała, a pielęgniarki znają potrzeby oddziału lepiej niż ona. Ma na decyzję trzy tygodnie.",
             W("Jaki stopień udziału zespołu zaleca model Vrooma–Yettona–Jago?",
               "Wysoki – decyzja grupowa lub szeroka konsultacja", "Decyzja całkowicie autokratyczna", "Rzut monetą",
               why="Ważna akceptacja, informacje u zespołu, jest czas."),
             W("Co przemawiałoby za decyzją bardziej autokratyczną?",
               "Sytuacja kryzysowa i brak czasu", "Duża potrzeba akceptacji", "Wiedza u pracowników",
               why="Pośpiech zmniejsza możliwość konsultacji."),
             PF("Udział pracowników zwiększa szansę wdrożenia decyzji.", True,
                why="Rośnie zaangażowanie i akceptacja."),
          ),
      ]),

    L(5, "Zespoły, konflikt i komunikacja",
      "Rozumieć rozwój zespołu (Tuckman), role Belbina, myślenie grupowe, style rozwiązywania konfliktów i sieci komunikacyjne w małych grupach.",
      ["Grupy i zespoły", "Role zespołowe Belbina i team building", "Myślenie grupowe (groupthink)", "Konflikt w organizacji", "Sieci komunikacyjne w małych grupach", "Komunikacja w organizacji"],
      [M152, M153, M162],
      explain=[
          K("Grupa a zespół; fazy rozwoju",
            "Zespół to grupa o wspólnym celu, uzupełniających się umiejętnościach i wspólnej odpowiedzialności. Tuckman (1965): formowanie (niepewność, poznawanie), burzenie (konflikty o role i władzę), normowanie (ustalanie zasad), działanie (wysoka efektywność); w 1977 dodano fazę rozwiązania (zakończenia)."),
          K("Role Belbina",
            "M. Belbin wyróżnił dziewięć ról zespołowych, m.in. kreator (pomysły), koordynator, lokalizator zasobów, praktyczny organizator (wdrożenie), perfekcjonista (dopilnowanie szczegółów), ewaluator (krytyczna ocena), specjalista, dusza zespołu, lokomotywa (napęd). Skuteczny zespół potrzebuje równowagi ról, a nie samych gwiazd."),
          W("Zespół ma wiele pomysłów, ale nic nie zostaje dokończone. Jakiej roli Belbina najbardziej brakuje?",
            "Praktycznego organizatora lub perfekcjonisty", "Kreatora", "Lokalizatora zasobów",
            why="Brakuje osób wdrażających i domykających."),
          K("Myślenie grupowe (Janis, 1972)",
            "Spójna grupa pod presją dąży do jednomyślności kosztem krytycznej oceny: iluzja nieomylności, autocenzura, presja na dysydentów, „strażnicy umysłu”. Skutki: złe decyzje (np. Zatoka Świń 1961). Zapobieganie: „adwokat diabła”, zewnętrzni eksperci, lider wypowiada się na końcu, podgrupy."),
          K("Konflikt i komunikacja",
            "Konflikt zadaniowy w umiarkowanym stopniu poprawia decyzje, konflikt osobisty szkodzi. Style (Thomas–Kilmann): rywalizacja, współpraca, kompromis, unikanie, dostosowanie się. Sieci komunikacyjne: scentralizowane (koło, Y, łańcuch) są szybkie w prostych zadaniach, zdecentralizowane (okrąg, każdy z każdym) – lepsze w złożonych i dają większą satysfakcję. Liczba kanałów w sieci każdy z każdym: n(n − 1)/2.",
            w="kanały = n · (n − 1) / 2"),
          PF("Umiarkowany konflikt zadaniowy może poprawić jakość decyzji.", True,
             why="Ujawnia różne punkty widzenia."),
      ],
      mech=[
          KT("Faza rozwoju zespołu (Tuckman)",
             {"Formowanie": ["Członkowie poznają się i są ostrożni"],
              "Burzenie": ["Spory o role i sposób pracy"],
              "Normowanie": ["Zespół ustala wspólne zasady i role"],
              "Działanie": ["Zespół sprawnie realizuje cele"]},
             why="Kolejne etapy dojrzewania zespołu."),
          LN("Ułóż powstawanie myślenia grupowego.",
             ["Grupa jest bardzo spójna i izolowana od opinii z zewnątrz", "Lider wcześnie ujawnia preferowane rozwiązanie", "Członkowie autocenzurują wątpliwości", "Powstaje iluzja jednomyślności", "Grupa podejmuje ryzykowną, słabo przeanalizowaną decyzję"],
             why="Presja zgody wypiera krytyczne myślenie."),
          W("Który styl rozwiązywania konfliktu daje rozwiązanie korzystne dla obu stron?",
            "Współpraca", "Unikanie", "Rywalizacja",
            why="Wysoka troska o własne i cudze interesy."),
          W("Która sieć komunikacyjna jest najszybsza w prostych zadaniach?",
            "Koło (scentralizowana)", "Każdy z każdym", "Okrąg",
            why="Informacja płynie przez centralną osobę."),
          M("Jak zapobiegać myśleniu grupowemu?",
            ["Wyznaczyć adwokata diabła", "Zaprosić zewnętrznych ekspertów", "Lider wypowiada się na końcu", "Karać za odmienne zdanie"], [0, 1, 2],
            why="Karanie dysydentów nasila myślenie grupowe."),
          PF("Spory o role w nowym zespole są typowe dla fazy burzenia.", True,
             why="To naturalny etap rozwoju zespołu."),
      ],
      calc=[
          LB("Ile kanałów komunikacji ma 5-osobowa sieć „każdy z każdym”?",
             10, "5*4/2", ["5 · 4 / 2 = 10"], unit="kanałów"),
          LB("Ile kanałów ma 8-osobowa sieć „każdy z każdym”?",
             28, "8*7/2", ["8 · 7 / 2 = 28"], unit="kanałów"),
          LB("O ile kanałów więcej ma zespół 12-osobowy niż 6-osobowy (sieć „każdy z każdym”)?",
             51, "12*11/2-6*5/2", ["66 − 15 = 51"], unit="kanałów"),
          LB("W sieci „koło” z 6 osobami (1 centralna) ile jest kanałów?",
             5, "6-1", ["6 − 1 = 5"], unit="kanałów"),
          LB("Tuckman opisał 4 fazy w 1965 r., piątą dodał w 1977 r. Ile lat później?",
             12, "1977-1965", ["1977 − 1965 = 12"], unit="lat"),
          LB("Kierownik spędza 12 h z 40 h tygodniowo na rozwiązywaniu konfliktów. Jaki to procent czasu?",
             30, "12/40*100", ["12 / 40 = 30%"], unit="%"),
      ],
      case=[
          PR("Zarząd firmy, od lat w tym samym składzie, jednogłośnie zatwierdza przejęcie konkurenta. Prezes od początku mówi, że to „oczywista okazja”. Jeden członek ma wątpliwości co do wyceny, ale milczy. Analiz zewnętrznych nie zamówiono. Po roku trzeba odpisać połowę wartości przejęcia.",
             W("Jakie zjawisko wystąpiło?",
               "Myślenie grupowe", "Faza burzenia", "Konflikt osobisty",
               why="Autocenzura, presja lidera i iluzja jednomyślności."),
             W("Co mogło zapobiec błędowi?",
               "Niezależna wycena i adwokat diabła", "Szybsze głosowanie", "Mniejszy zarząd o tym samym składzie",
               why="Wprowadzają krytyczną ocenę."),
             PF("Prezes, ujawniając swoje zdanie na początku, zwiększył presję na zgodę.", True,
                why="To typowy czynnik myślenia grupowego."),
          ),
          PR("Nowy zespół projektowy po dwóch tygodniach ma ostre spory o to, kto prowadzi spotkania i jak dzielić zadania. Kierowniczka obawia się, że zespół się rozpadnie.",
             W("W jakiej fazie według Tuckmana jest zespół?",
               "Burzenia", "Działania", "Rozwiązania",
               why="Spory o role i władzę."),
             W("Co powinna zrobić kierowniczka?",
               "Pomóc ustalić zasady i role, moderować konflikt", "Rozwiązać zespół", "Ignorować problem",
               why="Pomaga przejść do fazy normowania."),
             PF("Konflikty w tej fazie są naturalne i nie oznaczają porażki.", True,
                why="Większość zespołów przechodzi tę fazę."),
          ),
      ]),
]
