# -*- coding: utf-8 -*-
# Zrozumienie – Zarządzanie / Daty i chronologia
OSM = "https://openstax.org/books/principles-management/pages/"
D = "2026-10-08"
M34 = S("OpenStax, Principles of Management, 3.4 Taylor-Made Management", OSM + "3-4-taylor-made-management", D)
M35 = S("OpenStax, Principles of Management, 3.5 Administrative and Bureaucratic Management", OSM + "3-5-administrative-and-bureaucratic-management", D)
M36 = S("OpenStax, Principles of Management, 3.6 Human Relations Movement", OSM + "3-6-human-relations-movement", D)
M142 = S("OpenStax, Principles of Management, 14.2 Content Theories of Motivation", OSM + "14-2-content-theories-of-motivation", D)
OPEC = S("OPEC – strona organizacji", "https://www.opec.org/", D)
FRH = S("Federal Reserve History – Oil Shock of 1973–74", "https://www.federalreservehistory.org/essays/oil-shock-of-1973-74", D)

LESSONS = [
    L(1, "Od naukowego zarządzania do Hawthorne (1911–1932)",
      "Umieścić w czasie narodziny nauki o zarządzaniu – Taylor (1911), Fayol (1916), eksperymenty w Hawthorne (1924–1932) – i rozumieć, jak kolejne idee odpowiadały na problemy poprzednich.",
      ["1911 – „Zasady naukowego zarządzania” F.W. Taylora", "1916 – „Administracja przemysłowa i ogólna” H. Fayola", "1924–1932 – eksperymenty w Hawthorne"],
      [M34, M35, M36],
      explain=[
          K("Tło: druga rewolucja przemysłowa",
            "Na przełomie XIX i XX w. powstawały wielkie fabryki z tysiącami robotników, często bez kwalifikacji. Brakowało metod organizacji pracy – wydajność zależała od zwyczajów i „żołnierkowania” (celowego zwalniania tempa). Odpowiedzią było szukanie naukowych zasad zarządzania."),
          K("1911 i 1916 – dwa nurty klasyczne",
            "1911: F.W. Taylor publikuje „Zasady naukowego zarządzania” – organizacja pracy na poziomie stanowiska (pomiar czasu, najlepsza metoda, płaca za wynik). 1916: H. Fayol publikuje „Administrację przemysłową i ogólną” – zasady kierowania całą organizacją (5 funkcji, 14 zasad). W tym okresie (1913) Ford uruchamia ruchomą linię montażową."),
          W("Która publikacja była wcześniejsza?",
            "Taylora (1911)", "Fayola (1916)", "Obie ukazały się w tym samym roku",
            why="Taylor wydał swoją książkę 5 lat przed Fayolem."),
          K("1924–1932 – Hawthorne",
            "W zakładach Western Electric pod Chicago badano wpływ oświetlenia, przerw i czasu pracy na wydajność. Od końca lat 20. w badaniach uczestniczył zespół z Harvardu (E. Mayo, F. Roethlisberger). Wnioski: na wydajność silnie wpływają czynniki społeczne – uwaga, relacje, normy grup nieformalnych. To początek szkoły stosunków międzyludzkich."),
          K("Logika zmian",
            "Szkoła klasyczna poprawiła wydajność, ale pomijała człowieka jako istotę społeczną – rodziło to konflikty i opór. Hawthorne pokazało, że ludzie reagują na relacje i uwagę. Kolejne idee nie unieważniały poprzednich, lecz je uzupełniały – współczesne zarządzanie łączy pomiar i standaryzację z dbałością o ludzi."),
          PF("Eksperymenty w Hawthorne zapoczątkowały szkołę stosunków międzyludzkich.", True,
             why="Pokazały znaczenie czynników społecznych w pracy."),
      ],
      mech=[
          KT("Okres",
             {"Przed 1920": ["„Zasady naukowego zarządzania” Taylora", "Książka Fayola o administracji", "Ruchoma linia montażowa Forda"],
              "1924–1932": ["Badania oświetlenia i przerw w Western Electric", "Odkrycie roli grup nieformalnych"]},
             why="Chronologia narodzin nauki o zarządzaniu."),
          LN("Ułóż wydarzenia chronologicznie.",
             ["Publikacja Taylora (1911)", "Linia montażowa Forda (1913)", "Publikacja Fayola (1916)", "Początek badań w Hawthorne (1924)", "Koniec badań w Hawthorne (1932)"],
             why="Kolejność wydarzeń w latach 1911–1932."),
          W("Na jaki problem szkoły klasycznej odpowiadały wnioski z Hawthorne?",
            "Pomijanie społecznych potrzeb pracowników", "Brak pomiarów czasu pracy", "Brak hierarchii w firmach",
            why="Klasycy traktowali pracownika głównie ekonomicznie."),
          W("Co było tłem powstania naukowego zarządzania?",
            "Wielkie fabryki i niska wydajność niewykwalifikowanej siły roboczej", "Rozwój internetu", "Kryzys naftowy",
            why="Potrzeba organizacji masowej pracy przemysłowej."),
          M("Które idee pochodzą z okresu 1911–1916?",
            ["Pomiar czasu pracy i jedna najlepsza metoda", "14 zasad zarządzania", "Pięć funkcji administracji", "Teoria X i Y"], [0, 1, 2],
            why="Teoria X i Y pochodzi z 1960 r."),
          PF("Badania w Hawthorne trwały krócej niż rok.", False,
             why="Trwały z przerwami od 1924 do 1932 r."),
      ],
      calc=[
          LB("Ile lat dzieli publikację Taylora (1911) od początku badań w Hawthorne (1924)?",
             13, "1924-1911", ["1924 − 1911 = 13"], unit="lat"),
          LB("Ile lat dzieli książkę Fayola (1916) od zakończenia badań w Hawthorne (1932)?",
             16, "1932-1916", ["1932 − 1916 = 16"], unit="lat"),
          LB("Ile lat minęło od publikacji Taylora do 2026 r.?",
             115, "2026-1911", ["2026 − 1911 = 115"], unit="lat"),
          LB("W eksperymencie oświetlenia wydajność grupy wzrosła z 100 do 112 szt. dziennie. O ile procent?",
             12, "(112/100-1)*100", ["112 / 100 = 1,12 → +12%"], unit="%"),
          LB("Grupa kontrolna (bez zmian oświetlenia) zwiększyła wydajność z 100 do 108 szt. Ile punktów procentowych wzrostu grupy badanej (12%) można przypisać samemu oświetleniu?",
             4, "12-8", ["12 − 8 = 4 pkt proc."], unit="pkt proc."),
          LB("Ile lat trwały badania w Hawthorne?",
             8, "1932-1924", ["1932 − 1924 = 8"], unit="lat"),
      ],
      case=[
          PR("W badaniu oświetlenia wydajność rosła zarówno po rozjaśnieniu, jak i po przyciemnieniu hali. Rosła też w grupie kontrolnej, w której nic nie zmieniano.",
             W("Jak wyjaśnić ten wynik?",
               "Wpływem samego udziału w badaniu i uwagi poświęcanej pracownikom", "Wyłącznie zmianą oświetlenia", "Błędem w liczeniu sztuk",
               why="To tzw. efekt Hawthorne."),
             W("Jaki był wniosek dla zarządzania?",
               "Czynniki społeczne i psychologiczne wpływają na wydajność", "Oświetlenie nie ma żadnego znaczenia dla zdrowia", "Należy zrezygnować z pomiarów",
               why="To przesłanie szkoły stosunków międzyludzkich."),
             PF("Grupa kontrolna pozwoliła stwierdzić, że oświetlenie nie było główną przyczyną wzrostu wydajności.", True,
                why="Wydajność rosła także bez zmian oświetlenia."),
          ),
          PR("Zakład produkcyjny w 1912 r. wprowadza pomiar czasu, normy i płacę akordową. Wydajność rośnie, ale w 1915 r. wybucha strajk przeciw „pędzeniu” robotników.",
             W("Z jakim nurtem wiąże się zmiana z 1912 r.?",
               "Z naukowym zarządzaniem Taylora", "Ze szkołą stosunków międzyludzkich", "Z zarządzaniem przez cele",
               why="Pomiar czasu, normy i akord."),
             W("Jakie późniejsze odkrycie pomogłoby uniknąć konfliktu?",
               "Znaczenie relacji i norm grupowych (Hawthorne)", "Wykres Gantta", "Biurokracja Webera",
               why="Uwzględnienie czynników społecznych zmniejsza opór."),
             PF("Opór pracowników był jedną z przyczyn krytyki naukowego zarządzania.", True,
                why="Robotnicy sprzeciwiali się intensyfikacji pracy."),
          ),
      ]),

    L(2, "Teorie motywacji i nowe otoczenie (1943–1960)",
      "Umieścić w czasie teorię potrzeb Maslowa (1943), teorię dwuczynnikową Herzberga (1959) oraz teorię X i Y McGregora i powstanie OPEC (1960) – i rozumieć, jak zmieniało się myślenie o człowieku w organizacji i o otoczeniu firm.",
      ["1943 – teoria potrzeb A. Maslowa", "1959 – teoria dwuczynnikowa F. Herzberga", "1960 – OPEC i teoria X/Y"],
      [M142, M36, OPEC, FRH],
      explain=[
          K("1943 – Maslow",
            "W artykule „A Theory of Human Motivation” (1943) A. Maslow przedstawił hierarchię potrzeb: fizjologiczne, bezpieczeństwa, przynależności, uznania, samorealizacji. Teoria ukazała się w czasie II wojny światowej, a do zarządzania na szeroką skalę weszła w latach 50. i 60."),
          K("1959 – Herzberg",
            "F. Herzberg (z B. Mausnerem i B. Snyderman, „The Motivation to Work”, 1959) na podstawie wywiadów z inżynierami i księgowymi rozdzielił czynniki higieny (płaca, warunki, nadzór) od motywatorów (osiągnięcia, uznanie, odpowiedzialność, rozwój). Wniosek praktyczny: wzbogacanie pracy."),
          W("Która teoria jest starsza?",
            "Hierarchia potrzeb Maslowa", "Teoria dwuczynnikowa Herzberga", "Teoria X i Y",
            why="Maslow – 1943, Herzberg – 1959, McGregor – 1960."),
          K("1960 – teoria X i Y oraz OPEC",
            "D. McGregor w „The Human Side of Enterprise” (1960) przeciwstawił pesymistyczną teorię X i optymistyczną teorię Y, opierając się m.in. na Maslowie. W tym samym roku (wrzesień 1960, Bagdad) Iran, Irak, Kuwejt, Arabia Saudyjska i Wenezuela założyły OPEC – organizację, która w latach 70. (szoki naftowe 1973 i 1979) gwałtownie zmieniła otoczenie firm i skłoniła do rozwoju planowania strategicznego i analizy otoczenia."),
          K("Logika zmian",
            "Od 1943 do 1960 r. obraz pracownika przesuwał się od istoty o potrzebach ekonomicznych ku osobie dążącej do rozwoju i odpowiedzialności. Równocześnie otoczenie stawało się mniej przewidywalne – co w kolejnych dekadach przyniosło podejście systemowe, sytuacyjne i strategiczne."),
          PF("OPEC powstał w tym samym roku, w którym McGregor opublikował teorię X i Y.", True,
             why="Oba wydarzenia przypadają na 1960 r."),
      ],
      mech=[
          KT("Rok",
             {"1943": ["Artykuł Maslowa o hierarchii potrzeb"],
              "1959": ["„The Motivation to Work” Herzberga i współpracowników"],
              "1960": ["„The Human Side of Enterprise” McGregora", "Założenie OPEC w Bagdadzie"]},
             why="Chronologia lat 1943–1960."),
          LN("Ułóż wydarzenia chronologicznie.",
             ["Hierarchia potrzeb Maslowa (1943)", "Teoria dwuczynnikowa Herzberga (1959)", "Teoria X i Y oraz założenie OPEC (1960)", "Pierwszy szok naftowy (1973)"],
             why="Od teorii motywacji do zmian w otoczeniu firm."),
          W("Na której teorii w dużej mierze opierał się McGregor?",
            "Na hierarchii potrzeb Maslowa", "Na biurokracji Webera", "Na akordzie Taylora",
            why="Teoria Y zakłada potrzeby wyższego rzędu."),
          W("Jak powstanie OPEC wpłynęło (w dłuższym okresie) na zarządzanie?",
            "Zwiększyło niepewność otoczenia i znaczenie planowania strategicznego", "Zlikwidowało konkurencję", "Nie miało żadnego wpływu",
            why="Szoki naftowe lat 70. zmusiły firmy do analizy otoczenia."),
          M("Którzy autorzy opublikowali swoje teorie przed 1961 r.?",
            ["A. Maslow", "F. Herzberg", "D. McGregor", "P. Senge"], [0, 1, 2],
            why="Senge wydał „Piątą dyscyplinę” w 1990 r."),
          PF("Teoria Herzberga powstała na podstawie wywiadów z inżynierami i księgowymi.", True,
             why="Badanie przeprowadzono w rejonie Pittsburgha."),
      ],
      calc=[
          LB("Ile lat dzieli teorię Maslowa (1943) od teorii Herzberga (1959)?",
             16, "1959-1943", ["1959 − 1943 = 16"], unit="lat"),
          LB("Ile lat dzieli założenie OPEC (1960) od pierwszego szoku naftowego (1973)?",
             13, "1973-1960", ["1973 − 1960 = 13"], unit="lat"),
          LB("Ilu członków założycielskich miał OPEC?",
             5, "1+1+1+1+1", ["Iran, Irak, Kuwejt, Arabia Saudyjska, Wenezuela = 5"], unit="państw"),
          LB("Ile lat dzieli teorię X i Y (1960) od eksperymentów w Hawthorne zakończonych w 1932 r.?",
             28, "1960-1932", ["1960 − 1932 = 28"], unit="lat"),
          LB("Ile lat minęło od założenia OPEC do 2026 r.?",
             66, "2026-1960", ["2026 − 1960 = 66"], unit="lat"),
          LB("Hierarchia Maslowa ma 5 poziomów; firma zaspokaja potrzeby pracowników do poziomu 3. Jaki odsetek poziomów to jest (%)?",
             60, "3/5*100", ["3 / 5 = 60%"], unit="%"),
      ],
      case=[
          PR("Firma w 1961 r. wprowadza program: pracownicy dostają więcej odpowiedzialności, uczestniczą w ustalaniu celów i są nagradzani uznaniem za osiągnięcia. Dyrektor powołuje się na najnowsze publikacje.",
             W("Na które publikacje mógł się powoływać?",
               "Herzberga (1959) i McGregora (1960)", "Senge (1990)", "Riesa (2011)",
               why="To najnowsze prace o motywacji w 1961 r."),
             W("Którą teorię realizuje zwiększanie odpowiedzialności?",
               "Teorię Y i wzbogacanie pracy Herzberga", "Teorię X", "Biurokrację Webera",
               why="Zakładają, że ludzie chcą odpowiedzialności."),
             PF("Program nie mógł opierać się na „Piątej dyscyplinie” Sengego.", True,
                why="Ta książka ukazała się dopiero w 1990 r."),
          ),
          PR("Europejski producent chemii planuje produkcję w latach 60., zakładając stałe i niskie ceny ropy. W 1973 r. ceny ropy gwałtownie rosną, a firma ponosi straty.",
             W("Jakie wydarzenie z 1960 r. stało się źródłem tej zmiany otoczenia?",
               "Założenie OPEC", "Publikacja teorii X i Y", "Założenie EWG",
               why="OPEC odegrał kluczową rolę w szokach naftowych."),
             W("Jakiej umiejętności zabrakło firmie?",
               "Analizy otoczenia i planowania scenariuszy", "Pomiaru czasu pracy", "Wzbogacania pracy",
               why="Zakładała niezmienne warunki zewnętrzne."),
             PF("Szoki naftowe przyczyniły się do rozwoju planowania scenariuszowego w firmach.", True,
                why="Firmy zaczęły przygotowywać się na różne warianty przyszłości."),
          ),
      ]),
]
