# -*- coding: utf-8 -*-
# Zrozumienie – Zarządzanie / Decyzje, kontrola i jakość
OSM = "https://openstax.org/books/principles-management/pages/"
D = "2026-10-08"
M21 = S("OpenStax, Principles of Management, 2.1 Overview of Managerial Decision-Making", OSM + "2-1-overview-of-managerial-decision-making", D)
M23 = S("OpenStax, Principles of Management, 2.3 Programmed and Nonprogrammed Decisions", OSM + "2-3-programmed-and-nonprogrammed-decisions", D)
M24 = S("OpenStax, Principles of Management, 2.4 Barriers to Effective Decision-Making", OSM + "2-4-barriers-to-effective-decision-making", D)
M26 = S("OpenStax, Principles of Management, 2.6 Group Decision-Making", OSM + "2-6-group-decision-making", D)
M103 = S("OpenStax, Principles of Management, 10.3 Managing Change", OSM + "10-3-managing-change", D)
M178 = S("OpenStax, Principles of Management, 17.8 The Control- and Involvement-Oriented Approaches to Planning and Controlling", OSM + "17-8-the-control-and-involvement-oriented-approaches-to-planning-and-controlling", D)
MA124 = S("OpenStax, Principles of Managerial Accounting, 12.4 Balanced Scorecard", "https://openstax.org/books/principles-managerial-accounting/pages/12-4-describe-the-balanced-scorecard-and-explain-how-it-is-used", D)
LJIT = S("Lean Enterprise Institute, Lean Lexicon: Just-in-Time", "https://www.lean.org/lexicon-terms/just-in-time/", D)
LKZ = S("Lean Enterprise Institute, Lean Lexicon: Kaizen", "https://www.lean.org/lexicon-terms/kaizen/", D)
LLP = S("Lean Enterprise Institute, Lean Lexicon: Lean Production", "https://www.lean.org/lexicon-terms/lean-production/", D)
GIS = S("Główny Inspektorat Sanitarny – HACCP", "https://www.gov.pl/web/gis/haccp", D)
DNV = S("DNV – The new edition of ISO 9001 is released (2026)", "https://www.dnv.com/news/2026/new-edition-of-the-quality-management-system-standard-iso-9001-released/", D)
SGS = S("SGS – ISO 9001:2026 published: what you need to know (09.2026)", "https://www.sgs.com/en-ke/news/2026/09/iso-9001-2026-published-what-you-need-to-know", D)

LESSONS = [
    L(1, "Podejmowanie decyzji: racjonalność i jej granice",
      "Rozumieć etapy podejmowania decyzji, różnicę między decyzjami zaprogramowanymi i niezaprogramowanymi, model ograniczonej racjonalności H. Simona, rolę intuicji i pułapkę eskalacji zaangażowania.",
      ["Podejmowanie decyzji", "Decyzje zaprogramowane i niezaprogramowane", "Model administracyjny decyzji (H. Simon)", "Intuicja w podejmowaniu decyzji", "Eskalacja zaangażowania (narastanie zaangażowania)"],
      [M21, M23, M24],
      explain=[
          K("Model racjonalny",
            "Etapy: rozpoznanie problemu → określenie kryteriów → zebranie informacji i opracowanie wariantów → ocena wariantów → wybór → wdrożenie → ocena skutków. Model zakłada pełną informację, jasne cele i wybór wariantu optymalnego. W warunkach ryzyka warianty porównuje się np. wartością oczekiwaną: suma (prawdopodobieństwo × wynik).",
            w="EV = Σ pᵢ · wynikᵢ"),
          K("Zaprogramowane i niezaprogramowane",
            "Decyzje zaprogramowane są powtarzalne i rozwiązywane według reguł i procedur (zamówienie towaru, gdy zapas spadnie poniżej progu). Niezaprogramowane są nowe, nietypowe, ważne i niejasne (wejście na nowy rynek, reakcja na kryzys) – wymagają twórczego podejścia i podejmują je głównie wyżsi menedżerowie."),
          W("Sklep automatycznie zamawia mleko, gdy zapas spadnie poniżej 200 litrów. To decyzja:",
            "Zaprogramowana", "Niezaprogramowana", "Strategiczna jednorazowa",
            why="Powtarzalna, oparta na regule."),
          K("Model administracyjny (H. Simon)",
            "Herbert Simon (Nobel 1978) zauważył, że ludzie mają ograniczoną racjonalność: brak pełnej informacji, ograniczony czas i zdolność przetwarzania. Dlatego zamiast optymalizować, „satysfakcjonują” – wybierają pierwszy wariant spełniający minimalne kryteria. Intuicja (szybkie rozpoznanie wzorca na podstawie doświadczenia) bywa trafna u ekspertów, ale podatna na błędy poznawcze."),
          K("Eskalacja zaangażowania",
            "Skłonność do dalszego inwestowania w przegrywający projekt, bo już dużo w niego włożono (koszty utopione), z obawy przed przyznaniem się do błędu lub z powodu presji społecznej (B. Staw, 1976). Przeciwdziałanie: z góry ustalone kryteria przerwania, ocena przez osoby niezaangażowane, patrzenie tylko na przyszłe koszty i korzyści."),
          PF("Według Simona menedżerowie zwykle wybierają wariant „wystarczająco dobry”, a nie optymalny.", True,
             why="To zasada satysfakcjonowania przy ograniczonej racjonalności."),
      ],
      mech=[
          KT("Zaprogramowana czy niezaprogramowana?",
             {"Zaprogramowana": ["Naliczenie premii według regulaminu", "Zamówienie materiałów przy minimalnym zapasie", "Zatwierdzenie urlopu według grafiku"],
              "Niezaprogramowana": ["Reakcja na pożar w głównym zakładzie", "Wejście na rynek azjatycki", "Przejęcie konkurenta"]},
             why="Kryterium: powtarzalność i istnienie reguły."),
          LN("Ułóż etapy modelu racjonalnego.",
             ["Rozpoznanie problemu", "Określenie kryteriów decyzji", "Opracowanie wariantów", "Ocena i wybór wariantu", "Wdrożenie i ocena skutków"],
             why="Klasyczna sekwencja procesu decyzyjnego."),
          W("Projekt przekroczył budżet o 200%, ale zarząd dokłada pieniędzy, „bo szkoda tego, co już wydano”. To przykład:",
            "Eskalacji zaangażowania", "Decyzji zaprogramowanej", "Satysfakcjonowania",
            why="Decyzja oparta na kosztach utopionych."),
          W("Jak powinny być traktowane koszty utopione przy decyzji o kontynuacji projektu?",
            "Pomijane – liczą się przyszłe koszty i korzyści", "Jako najważniejsze kryterium", "Dodawane do przychodów",
            why="Kosztów utopionych nie da się odzyskać żadną decyzją."),
          M("Co ogranicza racjonalność decydentów według Simona?",
            ["Niepełna informacja", "Ograniczony czas", "Ograniczona zdolność przetwarzania informacji", "Nadmiar wiedzy o przyszłości"], [0, 1, 2],
            why="Dlatego ludzie satysfakcjonują zamiast optymalizować."),
          PF("Intuicja doświadczonego eksperta w znanej dziedzinie bywa trafna.", True,
             why="Opiera się na rozpoznawaniu wzorców z doświadczenia."),
      ],
      calc=[
          LB("Wariant A: 60% szans na zysk 500 tys. zł, 40% na stratę 200 tys. zł. Ile wynosi wartość oczekiwana (tys. zł)?",
             220, "0.6*500+0.4*(-200)", ["300 − 80 = 220 tys. zł"], unit="tys. zł"),
          LB("Wariant B: 50% na zysk 400 tys. zł, 50% na zysk 100 tys. zł. Ile wynosi wartość oczekiwana (tys. zł)?",
             250, "0.5*400+0.5*100", ["200 + 50 = 250 tys. zł"], unit="tys. zł"),
          LB("O ile tys. zł wartość oczekiwana B przewyższa A?",
             30, "250-220", ["250 − 220 = 30"], unit="tys. zł"),
          LB("Wydano już 3 mln zł. Dokończenie kosztuje 2 mln zł, a projekt przyniesie 1,5 mln zł. Ile wynosi wynik decyzji o kontynuacji, licząc tylko przyszłe przepływy (mln zł)?",
             -0.5, "1.5-2", ["1,5 − 2 = −0,5 → lepiej przerwać"], unit="mln zł"),
          LB("Satysfakcjonowanie: kryterium minimalne – 4 z 5 pkt. Kandydaci oceniani kolejno: 3, 3,5, 4,2, 4,8. Którego z kolei kandydata wybierze decydent?",
             3, "3", ["Pierwszy spełniający próg to 3. kandydat (4,2)"], unit=""),
          LB("Herbert Simon otrzymał Nagrodę Nobla w 1978 r., a B. Staw opisał eskalację w 1976 r. Ile lat różnicy?",
             2, "1978-1976", ["1978 − 1976 = 2"], unit="lata"),
      ],
      case=[
          PR("Firma od 4 lat rozwija własny system informatyczny. Wydała 8 mln zł, a system nadal nie działa. Dostawca gotowego systemu oferuje wdrożenie za 3 mln zł, a dokończenie własnego wymaga według szacunków jeszcze 5 mln zł. Prezes, który był pomysłodawcą projektu, chce go kontynuować.",
             W("Jakie zjawisko grozi firmie?",
               "Eskalacja zaangażowania", "Myślenie zaprogramowane", "Brak intuicji",
               why="Kontynuacja z powodu poniesionych kosztów i osobistego zaangażowania."),
             W("Które liczby powinny decydować o wyborze?",
               "Przyszłe koszty: 5 mln zł vs 3 mln zł (i jakość obu rozwiązań)", "Wydane już 8 mln zł", "Liczba lat prac",
               why="8 mln zł to koszt utopiony."),
             PF("Ocena projektu przez niezależny zespół zmniejsza ryzyko eskalacji.", True,
                why="Osoby niezaangażowane nie bronią wcześniejszych decyzji."),
          ),
          PR("Kierownik sklepu szuka nowego dostawcy pieczywa. Zamiast porównać wszystkich 20 piekarni w regionie, sprawdza trzy najbliższe i wybiera pierwszą, która spełnia wymagania co do ceny i terminowości.",
             W("Jaki model decyzji stosuje kierownik?",
               "Administracyjny (satysfakcjonowanie)", "W pełni racjonalny", "Eskalację zaangażowania",
               why="Wybiera wariant wystarczająco dobry."),
             W("Dlaczego takie podejście może być rozsądne?",
               "Koszt i czas zbierania pełnej informacji przewyższyłyby korzyści", "Bo wszystkie piekarnie są identyczne", "Bo prawo tego wymaga",
               why="Szukanie informacji też kosztuje."),
             PF("Przy decyzji o dużej wartości warto przeanalizować więcej wariantów.", True,
                why="Rosną korzyści z lepszego wyboru."),
          ),
      ]),

    L(2, "Twórcze rozwiązywanie problemów i zarządzanie zmianą",
      "Znać metody twórczego rozwiązywania problemów (burza mózgów, metoda delficka, sześć kapeluszy, nominalna technika grupowa), model zmiany K. Lewina, reengineering i zarządzanie wiedzą.",
      ["Metody twórczego rozwiązywania problemów", "Zarządzanie zmianą (K. Lewin)", "Reengineering (BPR)", "Zarządzanie wiedzą"],
      [M26, M103],
      explain=[
          K("Metody twórcze",
            "Burza mózgów (A. Osborn): najpierw wiele pomysłów bez krytyki, ocena później. Technika grupy nominalnej: pomysły zapisywane indywidualnie, potem przedstawiane i głosowane – ogranicza dominację głośnych osób. Metoda delficka: anonimowi eksperci w kilku rundach zbliżają opinie. Sześć kapeluszy (E. de Bono): kolejno różne perspektywy – fakty, emocje, ryzyka, korzyści, pomysły, zarządzanie procesem."),
          K("Model zmiany Lewina",
            "Kurt Lewin: rozmrożenie (uświadomienie potrzeby zmiany, osłabienie oporu), zmiana (wprowadzenie nowych zachowań i struktur), zamrożenie (utrwalenie nowych praktyk). Analiza pola sił: siły napędowe vs siły hamujące – łatwiej osłabić opór niż tylko zwiększać nacisk. Rozwinięcie: 8 kroków J. Kottera (m.in. poczucie pilności, koalicja, wizja, szybkie sukcesy)."),
          W("Zarząd pokazuje pracownikom dane o utracie klientów, by przekonać ich, że zmiana jest konieczna. To etap:",
            "Rozmrożenia", "Zamrożenia", "Kontroli końcowej",
            why="Budowanie świadomości potrzeby zmiany."),
          K("Reengineering (BPR)",
            "M. Hammer i J. Champy (1993): fundamentalne przemyślenie i radykalne przeprojektowanie procesów, by osiągnąć dramatyczną poprawę kosztów, jakości, szybkości. W przeciwieństwie do kaizen (małe, ciągłe kroki) BPR to skok. Ryzyko: wiele projektów BPR zawodzi z powodu oporu i redukcji zatrudnienia."),
          K("Zarządzanie wiedzą",
            "Wiedza jawna (zapisana: procedury, bazy) i ukryta (doświadczenie w głowach). Nonaka i Takeuchi: model SECI – socjalizacja, eksternalizacja, kombinacja, internalizacja – zamienia wiedzę ukrytą w jawną i z powrotem. Narzędzia: bazy wiedzy, mentoring, społeczności praktyków."),
          PF("Burza mózgów zakłada wstrzymanie krytyki na etapie zgłaszania pomysłów.", True,
             why="Krytyka hamuje kreatywność."),
      ],
      mech=[
          KT("Etap zmiany według Lewina",
             {"Rozmrożenie": ["Spotkania pokazujące zagrożenia dla firmy", "Analiza przyczyn oporu"],
              "Zmiana": ["Wdrożenie nowego systemu i szkolenia"],
              "Zamrożenie": ["Nowe procedury w regulaminie i system nagród za nowe zachowania", "Ocena okresowa według nowych zasad"]},
             why="Trzy etapy zmiany organizacyjnej."),
          LN("Ułóż przebieg metody delfickiej.",
             ["Wybór grupy ekspertów", "Anonimowa pierwsza runda opinii", "Zestawienie i przekazanie wyników ekspertom", "Kolejne rundy z możliwością zmiany opinii", "Ustalenie zbliżonego stanowiska (konsensusu)"],
             why="Anonimowość i iteracje ograniczają presję autorytetu."),
          W("Która metoda najlepiej ograniczy dominację prezesa podczas zgłaszania pomysłów?",
            "Technika grupy nominalnej", "Otwarta dyskusja, w której prezes mówi pierwszy", "Głosowanie jawne przez podniesienie ręki",
            why="Pomysły zapisuje się indywidualnie przed dyskusją."),
          W("Czym reengineering różni się od kaizen?",
            "BPR to radykalne przeprojektowanie, kaizen – małe ciągłe usprawnienia", "Niczym", "Kaizen jest bardziej radykalny",
            why="Skok vs stopniowa poprawa."),
          M("Jak można osłabić siły hamujące zmianę?",
            ["Komunikacja i wyjaśnianie powodów", "Udział pracowników w planowaniu", "Szkolenia i wsparcie", "Ukrywanie planów do ostatniej chwili"], [0, 1, 2],
            why="Ukrywanie zwiększa niepewność i opór."),
          PF("Wiedza ukryta to doświadczenie i umiejętności trudne do zapisania.", True,
             why="Przekazuje się ją głównie przez współpracę i mentoring."),
      ],
      calc=[
          LB("Analiza pola sił: siły napędowe 4 + 5 + 3, hamujące 4 + 4 + 2 (skala 1–5). Ile wynosi przewaga sił napędowych?",
             2, "(4+5+3)-(4+4+2)", ["12 − 10 = 2"], unit="pkt"),
          LB("BPR skrócił obsługę wniosku kredytowego z 15 dni do 3 dni. O ile procent?",
             80, "(1-3/15)*100", ["3 / 15 = 0,2 → −80%"], unit="%"),
          LB("Burza mózgów: 8 osób, średnio 5 pomysłów; 10% nadaje się do wdrożenia. Ile pomysłów do wdrożenia?",
             4, "8*5*0.1", ["40 · 10% = 4"], unit="pomysłów"),
          LB("Delfi: opinie ekspertów w 1. rundzie mają rozstęp 40 pkt, w 3. rundzie 12 pkt. O ile procent zmniejszył się rozstęp?",
             70, "(1-12/40)*100", ["12 / 40 = 0,3 → −70%"], unit="%"),
          LB("Model Kottera ma 8 kroków, a Lewina 3 etapy. O ile kroków więcej ma model Kottera?",
             5, "8-3", ["8 − 3 = 5"], unit="kroków"),
          LB("Baza wiedzy skraca szukanie informacji o 2 h tygodniowo na osobę. Ile godzin rocznie zyska 50 osób (46 tygodni pracy)?",
             4600, "2*50*46", ["2 · 50 · 46 = 4 600 h"], unit="h"),
      ],
      case=[
          PR("Szpital wprowadza elektroniczną dokumentację medyczną. Część lekarzy uważa ją za stratę czasu. Dyrekcja nie wyjaśniła powodów zmiany, a szkolenie trwało godzinę. Po trzech miesiącach wielu lekarzy nadal prowadzi notatki papierowe.",
             W("Który etap modelu Lewina zaniedbano?",
               "Rozmrożenie – nie zbudowano przekonania o potrzebie zmiany", "Tylko zamrożenie", "Żaden",
               why="Brak wyjaśnienia powodów zwiększył opór."),
             W("Co pomoże utrwalić zmianę?",
               "Szkolenia, wsparcie i wycofanie dokumentacji papierowej", "Dalsze tolerowanie dwóch systemów bez końca", "Zwolnienie wszystkich lekarzy",
               why="To etap zamrożenia nowych praktyk."),
             PF("Udział lekarzy w dopracowaniu systemu mógłby ograniczyć opór.", True,
                why="Partycypacja zwiększa akceptację zmiany."),
          ),
          PR("Doświadczony technolog odchodzi na emeryturę za rok. Tylko on wie, jak ustawiać starą maszynę, by produkt miał właściwą jakość – nic nie jest zapisane.",
             W("Jaki rodzaj wiedzy firma może stracić?",
               "Wiedzę ukrytą", "Wiedzę jawną z bazy danych", "Żadną",
               why="Doświadczenie technologa nie zostało zapisane."),
             W("Jakie działanie jest najlepsze?",
               "Mentoring następcy i spisanie procedur (eksternalizacja)", "Poczekać na emeryturę", "Kupić nową maszynę bez szkoleń",
               why="Przenosi wiedzę ukrytą na innych i do dokumentów."),
             PF("Model SECI opisuje zamianę wiedzy ukrytej w jawną.", True,
                why="Eksternalizacja to jeden z jego etapów."),
          ),
      ]),

    L(3, "Kontrolowanie, zrównoważona karta wyników i projekty",
      "Rozumieć proces kontroli, rodzaje kontroli, zrównoważoną kartę wyników (BSC), fotografię dnia roboczego oraz podstawy zarządzania projektami (ścieżka krytyczna, PERT).",
      ["Kontrolowanie", "Zrównoważona karta wyników (BSC)", "Fotografia dnia roboczego", "Zarządzanie projektami"],
      [M178, MA124],
      explain=[
          K("Proces kontroli",
            "Kontrolowanie to porównywanie wyników z planem i korygowanie odchyleń: 1) ustalenie standardów, 2) pomiar wyników, 3) porównanie i analiza odchyleń, 4) działania korygujące. Rodzaje: wstępna (przed działaniem, np. kontrola surowców), bieżąca (w trakcie), końcowa (po fakcie). Podejście kontrolne (nadzór z góry) vs angażujące (samokontrola pracowników)."),
          K("Zrównoważona karta wyników",
            "R. Kaplan i D. Norton (1992): ocena firmy w czterech perspektywach – finansowej, klienta, procesów wewnętrznych oraz uczenia się i rozwoju. Każda ma cele, mierniki, wartości docelowe i inicjatywy. Idea: wskaźniki finansowe pokazują przeszłość, a pozostałe perspektywy – czynniki przyszłych wyników (relacje przyczynowo-skutkowe w mapie strategii)."),
          W("Odsetek pracowników, którzy ukończyli szkolenia, należy do perspektywy BSC:",
            "Uczenia się i rozwoju", "Finansowej", "Klienta",
            why="Dotyczy kompetencji ludzi – podstawy przyszłych wyników."),
          K("Fotografia dnia roboczego",
            "Ciągła obserwacja i rejestracja wszystkich czynności pracownika przez całą zmianę, z czasem trwania. Czas dzieli się na pracę podstawową, pomocniczą, przerwy uzasadnione i straty czasu. Służy do wykrycia strat, ustalenia norm i usprawnienia organizacji pracy."),
          K("Zarządzanie projektami",
            "Projekt: jednorazowe przedsięwzięcie z celem, budżetem i terminem (trójkąt ograniczeń: zakres–czas–koszt). Metoda ścieżki krytycznej (CPM): najdłuższa ścieżka w sieci zadań wyznacza czas projektu; opóźnienie zadania krytycznego opóźnia projekt, a zadania niekrytyczne mają zapas. PERT szacuje czas jako (o + 4m + p)/6 – czas optymistyczny, najbardziej prawdopodobny, pesymistyczny.",
            w="t = (o + 4m + p) / 6"),
          PF("Opóźnienie zadania na ścieżce krytycznej opóźnia cały projekt.", True,
             why="Zadania krytyczne nie mają zapasu czasu."),
      ],
      mech=[
          KT("Perspektywa BSC",
             {"Finansowa": ["Rentowność kapitału własnego", "Wzrost przychodów"],
              "Klienta": ["Wskaźnik zadowolenia klientów", "Udział w rynku"],
              "Procesów wewnętrznych": ["Czas realizacji zamówienia", "Odsetek wadliwych produktów"],
              "Uczenia się i rozwoju": ["Godziny szkoleń na pracownika"]},
             why="Cztery perspektywy Kaplana i Nortona."),
          LN("Ułóż etapy procesu kontroli.",
             ["Ustalenie standardów", "Pomiar rzeczywistych wyników", "Porównanie wyników ze standardami", "Analiza przyczyn odchyleń", "Działania korygujące"],
             why="Klasyczny cykl kontroli."),
          W("Kontrola jakości mąki przed przyjęciem jej do piekarni to kontrola:",
            "Wstępna", "Końcowa", "Bieżąca",
            why="Odbywa się przed rozpoczęciem produkcji."),
          W("Dlaczego BSC nie ogranicza się do wskaźników finansowych?",
            "Bo pokazują one przeszłość, a inne perspektywy – czynniki przyszłych wyników", "Bo finanse są nieważne", "Bo wymaga tego prawo",
            why="Równowaga wskaźników wyprzedzających i opóźnionych."),
          M("Co obejmuje trójkąt ograniczeń projektu?",
            ["Zakres", "Czas", "Koszt", "Liczbę spotkań"], [0, 1, 2],
            why="Zmiana jednego wymiaru wpływa na pozostałe."),
          PF("Fotografia dnia roboczego obejmuje obserwację całej zmiany pracownika.", True,
             why="Rejestruje się wszystkie czynności i przerwy."),
      ],
      calc=[
          LB("BSC: wagi 40/30/20/10% (finanse, klienci, procesy, rozwój), oceny 80, 90, 70, 60 pkt. Ile wynosi ocena łączna?",
             79, "0.4*80+0.3*90+0.2*70+0.1*60", ["32 + 27 + 14 + 6 = 79"], unit="pkt"),
          LB("Plan kosztów 500 tys. zł, wykonanie 540 tys. zł. Ile wynosi odchylenie (%)?",
             8, "(540/500-1)*100", ["540 / 500 = 1,08 → +8%"], unit="%"),
          LB("Fotografia: zmiana 480 min, straty czasu 90 min. Jaki to procent?",
             18.75, "90/480*100", ["90 / 480 = 18,75%"], unit="%"),
          LB("Praca podstawowa 300 min i pomocnicza 60 min na zmianie 480 min. Jaki procent czasu to praca produktywna?",
             75, "(300+60)/480*100", ["360 / 480 = 75%"], unit="%"),
          LB("Zadania: A (3 dni), potem równolegle B (5) i C (4), potem D (2) po B i C. Ile dni trwa projekt?",
             10, "3+5+2", ["Ścieżka krytyczna A–B–D: 3 + 5 + 2 = 10"], unit="dni"),
          LB("PERT: o = 2, m = 5, p = 14 dni. Ile wynosi oczekiwany czas zadania?",
             6, "(2+4*5+14)/6", ["(2 + 20 + 14) / 6 = 6"], unit="dni"),
      ],
      case=[
          PR("Projekt budowy magazynu: fundamenty (4 tyg.), potem równolegle konstrukcja (8 tyg.) i przyłącza (5 tyg.), na końcu wykończenie (3 tyg.) po obu. Przyłącza opóźniły się o 2 tygodnie.",
             W("Ile tygodni trwa projekt według planu?",
               "15 tygodni", "20 tygodni", "12 tygodni",
               why="4 + 8 + 3 = 15 – ścieżka krytyczna przez konstrukcję."),
             W("Czy opóźnienie przyłączy o 2 tygodnie opóźni projekt?",
               "Nie – przyłącza mają 3 tygodnie zapasu", "Tak, o 2 tygodnie", "Tak, o 5 tygodni",
               why="8 − 5 = 3 tygodnie zapasu."),
             PF("Opóźnienie konstrukcji o tydzień przesunęłoby koniec projektu.", True,
                why="Konstrukcja leży na ścieżce krytycznej."),
          ),
          PR("Sieć hoteli ocenia dyrektorów wyłącznie według zysku kwartalnego. Dyrektorzy ograniczają szkolenia i remonty. Zysk rośnie, ale spadają oceny gości i rośnie rotacja personelu.",
             W("Jaki problem ujawnia sytuacja?",
               "Jednostronny system kontroli oparty tylko na finansach", "Zbyt wiele wskaźników", "Brak planowania finansowego",
               why="Pomija czynniki przyszłych wyników."),
             W("Co zaproponuje zwolennik BSC?",
               "Dodać mierniki klienta, procesów i rozwoju pracowników", "Zlikwidować ocenę dyrektorów", "Oceniać tylko przychody",
               why="Równoważy krótko- i długoterminowe cele."),
             PF("Spadek ocen gości może w przyszłości obniżyć zysk.", True,
                why="Perspektywa klienta wyprzedza wyniki finansowe."),
          ),
      ]),

    L(4, "Zarządzanie operacyjne: lean, JIT, kaizen i zapasy",
      "Rozumieć zarządzanie operacyjne, filozofię lean i just in time, kaizen, ekonomiczną wielkość zamówienia, krzywą doświadczenia i łańcuch dostaw.",
      ["Zarządzanie operacyjne (produkcją)", "Just in time (JIT) i lean management", "Kaizen", "Zarządzanie zapasami", "Krzywa doświadczenia (uczenia się)", "Logistyka i łańcuch dostaw (SCM)"],
      [LLP, LJIT, LKZ],
      explain=[
          K("Lean i JIT",
            "Lean management wywodzi się z systemu produkcyjnego Toyoty (T. Ohno). Celem jest eliminacja marnotrawstwa (muda): nadprodukcji, zapasów, oczekiwania, zbędnego transportu i ruchów, nadmiernego przetwarzania i braków. Just in time: produkować i dostarczać dokładnie to, co potrzebne, wtedy, kiedy potrzebne, w potrzebnej ilości – produkcja „ciągniona” przez popyt (kanban)."),
          K("Kaizen",
            "Japońska filozofia ciągłego doskonalenia małymi krokami z udziałem wszystkich pracowników. Narzędzia: cykl PDCA Deminga (planuj–wykonaj–sprawdź–działaj), 5S (sortuj, systematyzuj, sprzątaj, standaryzuj, samodyscyplina), skrzynki pomysłów, warsztaty kaizen."),
          W("Fabryka produkuje części na zapas „na wszelki wypadek”, magazyny są pełne. Którą zasadę lean łamie?",
            "Unikanie nadprodukcji i zbędnych zapasów", "Pięć sił Portera", "Zasadę jedności rozkazodawstwa",
            why="Nadprodukcja i zapasy to rodzaje marnotrawstwa."),
          K("Zapasy i EOQ",
            "Zapasy chronią przed brakami, ale kosztują (kapitał, magazyn, starzenie). Ekonomiczna wielkość zamówienia równoważy koszty zamawiania i utrzymania: EOQ = √(2DS/H), gdzie D – roczny popyt, S – koszt jednego zamówienia, H – roczny koszt utrzymania jednostki. Analiza ABC: najwięcej uwagi pozycjom A (mała liczba, duża wartość). JIT zmniejsza zapasy, ale zwiększa wrażliwość na zakłócenia dostaw.",
            w="EOQ = √(2 · D · S / H)"),
          K("Krzywa doświadczenia i łańcuch dostaw",
            "Krzywa uczenia się: przy każdym podwojeniu skumulowanej produkcji czas (koszt) jednostki spada do stałego odsetka, np. 80% (T.P. Wright, 1936, przemysł lotniczy; BCG uogólnił na koszty). Łańcuch dostaw (SCM) obejmuje przepływ materiałów, informacji i pieniędzy od dostawców surowców do klienta końcowego; brak koordynacji wywołuje efekt byczego bicza (wzmacnianie wahań zamówień w górę łańcucha).",
            w="tₙ = t₁ · nᵇ, b = log(r) / log 2"),
          PF("JIT zwiększa wrażliwość firmy na przerwy w dostawach.", True,
             why="Brak zapasów buforowych."),
      ],
      mech=[
          KT("Rodzaj marnotrawstwa (muda)",
             {"Nadprodukcja": ["Produkcja 1 000 sztuk przy zamówieniach na 600"],
              "Oczekiwanie": ["Pracownicy czekają na dostawę części"],
              "Zbędny transport": ["Przewożenie półproduktów między odległymi halami"],
              "Braki": ["Poprawianie wadliwych spoin"]},
             why="Lean identyfikuje i eliminuje rodzaje strat."),
          LN("Ułóż cykl PDCA.",
             ["Planuj – zdefiniuj problem i usprawnienie", "Wykonaj – wprowadź zmianę na małą skalę", "Sprawdź – porównaj wyniki z oczekiwaniami", "Działaj – wystandaryzuj lub popraw rozwiązanie"],
             why="Cykl Deminga to podstawa kaizen."),
          W("Co dzieje się z EOQ, gdy rośnie koszt utrzymania zapasu (H)?",
            "Maleje – opłaca się zamawiać mniejsze partie", "Rośnie", "Nie zmienia się",
            why="H jest w mianowniku."),
          W("Co to jest efekt byczego bicza?",
            "Wzmacnianie wahań zamówień w górę łańcucha dostaw", "Spadek kosztów przy podwojeniu produkcji", "Metoda kontroli jakości",
            why="Małe zmiany popytu rosną u dostawców."),
          M("Które elementy należą do 5S?",
            ["Sortowanie", "Standaryzacja", "Samodyscyplina", "Sprzedaż"], [0, 1, 2],
            why="Do tego systematyka i sprzątanie."),
          PF("System kanban oznacza produkcję ciągnioną przez rzeczywiste zapotrzebowanie.", True,
             why="Karta kanban sygnalizuje potrzebę uzupełnienia."),
      ],
      calc=[
          LB("D = 12 000 szt., S = 150 zł, H = 4 zł. Ile wynosi EOQ (szt.)?",
             948.68, "(2*12000*150/4)**0.5", ["√(2 · 12 000 · 150 / 4) = √900 000 ≈ 948,68"], unit="szt.", tol=0.5),
          LB("Ile zamówień rocznie przy EOQ ≈ 948,68 szt. i popycie 12 000 szt.?",
             12.65, "12000/948.6833", ["12 000 / 948,68 ≈ 12,65"], unit="zamówień", tol=0.02),
          LB("Krzywa 80%: pierwsza jednostka 100 h. Ile godzin zajmie 8. jednostka?",
             51.2, "100*0.8**3", ["8 = 2³ → 100 · 0,8³ = 51,2 h"], unit="h", tol=0.01),
          LB("Koszt sprzedanych towarów 1,2 mln zł, przeciętny zapas 200 tys. zł. Ile wynosi rotacja zapasów (razy)?",
             6, "1200/200", ["1 200 / 200 = 6"], unit="razy"),
          LB("JIT obniża zapas z 200 tys. zł do 50 tys. zł; roczny koszt utrzymania to 10% wartości. Ile wynosi oszczędność (zł)?",
             15000, "(200000-50000)*0.1", ["150 000 · 10% = 15 000 zł"], unit="zł"),
          LB("Kaizen poprawia wydajność o 1% miesięcznie. O ile procent wzrośnie po 12 miesiącach (procent składany)?",
             12.68, "(1.01**12-1)*100", ["1,01¹² ≈ 1,1268 → +12,68%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Producent części samochodowych przeszedł na JIT – zapasy spadły o 70%. Po pożarze u jedynego dostawcy uszczelek fabryka stanęła na dwa tygodnie, a klient naliczył kary.",
             W("Jaką słabość JIT ujawniła sytuacja?",
               "Wrażliwość na zakłócenia dostaw przy braku zapasów buforowych", "Za duże zapasy", "Zbyt wiele dostawców",
               why="Brak bufora i jeden dostawca."),
             W("Jak ograniczyć ryzyko bez rezygnacji z JIT?",
               "Drugi dostawca i niewielki zapas bezpieczeństwa dla krytycznych części", "Powrót do pełnych magazynów wszystkich części", "Rezygnacja z kontraktu",
               why="Dywersyfikacja i bufor tylko tam, gdzie potrzebny."),
             PF("Obniżenie zapasów o 70% przyniosło oszczędności kosztów utrzymania.", True,
                why="Mniej kapitału zamrożonego w zapasach."),
          ),
          PR("Stocznia buduje serię 16 jednakowych statków. Pierwszy wymagał 200 000 roboczogodzin. Zespół szacuje, że działa krzywa uczenia się 90%.",
             W("Co się stanie z pracochłonnością 2. statku?",
               "Spadnie do 180 000 roboczogodzin", "Pozostanie bez zmian", "Wzrośnie",
               why="200 000 · 0,9 = 180 000."),
             W("Ile roboczogodzin zajmie 16. statek?",
               "Ok. 131 220", "Ok. 180 000", "Ok. 100 000",
               why="16 = 2⁴ → 200 000 · 0,9⁴ ≈ 131 220."),
             PF("Krzywa uczenia się pozwala lepiej wycenić kolejne zamówienia.", True,
                why="Kolejne jednostki są tańsze w wykonaniu."),
          ),
      ]),

    L(5, "Zarządzanie jakością: TQM, normy, Six Sigma i narzędzia",
      "Rozumieć TQM, normy ISO 9001 i HACCP, metodykę Six Sigma, siedem narzędzi jakości i rolę systemów informatycznych w zarządzaniu.",
      ["Zarządzanie jakością (TQM)", "Normy ISO 9001 i HACCP", "Six Sigma", "Narzędzia jakości", "Systemy informatyczne zarządzania", "Technologie informacyjne w zarządzaniu"],
      [DNV, SGS, GIS],
      explain=[
          K("TQM",
            "Kompleksowe zarządzanie jakością: jakość jest odpowiedzialnością wszystkich, orientacja na klienta (wewnętrznego i zewnętrznego), ciągłe doskonalenie, decyzje na podstawie faktów, współpraca z dostawcami. Prekursorzy: W.E. Deming (14 zasad, PDCA), J. Juran (trylogia jakości), P. Crosby („zero defektów”, „jakość jest za darmo”). Koszty jakości: zapobiegania, oceny, błędów wewnętrznych i zewnętrznych."),
          K("ISO 9001 i HACCP",
            "ISO 9001 określa wymagania dla systemu zarządzania jakością (podejście procesowe, orientacja na klienta, zarządzanie ryzykiem); certyfikat potwierdza spójne procesy, a nie samą jakość wyrobu. Stan na 10.2026: we wrześniu 2026 r. opublikowano nowe wydanie ISO 9001:2026, zastępujące wersję z 2015 r.; certyfikowane firmy mają okres przejściowy. HACCP – system analizy zagrożeń i krytycznych punktów kontroli w produkcji żywności, obowiązkowy w UE dla przedsiębiorstw spożywczych (rozporządzenie (WE) nr 852/2004)."),
          W("Restauracja wyznacza temperaturę pieczenia kurczaka jako punkt krytyczny i ją mierzy. Jaki system stosuje?",
            "HACCP", "Six Sigma w wersji DMAIC", "BSC",
            why="Krytyczny punkt kontroli bezpieczeństwa żywności."),
          K("Six Sigma",
            "Metodyka zapoczątkowana w Motoroli (1986): redukcja zmienności procesu, by liczba defektów nie przekraczała 3,4 na milion możliwości (DPMO). Projekty prowadzi się według cyklu DMAIC: definiuj, mierz, analizuj, udoskonalaj, kontroluj. Role: Champion, Black Belt, Green Belt.",
            w="DPMO = defekty / (jednostki · możliwości) · 1 000 000"),
          K("Siedem narzędzi jakości",
            "Arkusz kontrolny, histogram, diagram Pareto (ok. 20% przyczyn → 80% problemów), diagram Ishikawy (przyczynowo-skutkowy, „rybia ość”: człowiek, maszyna, metoda, materiał, pomiar, otoczenie), wykres rozrzutu, karta kontrolna (granice średnia ± 3σ), stratyfikacja lub schemat blokowy. Systemy informatyczne (ERP, CRM, BI) dostarczają danych do tych analiz."),
          PF("Certyfikat ISO 9001 sam w sobie gwarantuje najwyższą jakość produktu.", False,
             why="Potwierdza spójny system zarządzania, nie samą jakość wyrobu."),
      ],
      mech=[
          KT("Narzędzie jakości",
             {"Diagram Ishikawy": ["Szukanie przyczyn wad według kategorii: maszyna, metoda, materiał"],
              "Diagram Pareto": ["Uszeregowanie przyczyn reklamacji od najczęstszej"],
              "Karta kontrolna": ["Monitorowanie, czy średnica detalu mieści się w granicach ± 3σ"],
              "Histogram": ["Rozkład czasu obsługi klienta w przedziałach"]},
             why="Każde narzędzie ma inne zastosowanie."),
          LN("Ułóż etapy DMAIC.",
             ["Definiuj problem i cele", "Mierz obecny poziom procesu", "Analizuj przyczyny zmienności", "Udoskonalaj proces", "Kontroluj i utrzymuj poprawę"],
             why="Cykl projektu Six Sigma."),
          W("Która kategoria kosztów jakości jest zwykle najdroższa?",
            "Błędy zewnętrzne (reklamacje, utrata klientów)", "Zapobieganie", "Szkolenia",
            why="Wady wykryte przez klienta kosztują najwięcej."),
          W("Co wskazuje diagram Pareto?",
            "Kilka przyczyn odpowiedzialnych za większość problemów", "Granice kontrolne procesu", "Ścieżkę krytyczną projektu",
            why="Zasada 80/20 – kilka przyczyn, większość skutków."),
          M("Które zasady należą do TQM?",
            ["Orientacja na klienta", "Ciągłe doskonalenie", "Zaangażowanie wszystkich pracowników", "Kontrola jakości tylko na końcu produkcji"], [0, 1, 2],
            why="TQM wbudowuje jakość w cały proces."),
          PF("HACCP jest obowiązkowy dla przedsiębiorstw spożywczych w UE.", True,
             why="Wymaga tego rozporządzenie (WE) nr 852/2004."),
      ],
      calc=[
          LB("17 defektów w 5 000 jednostek, 3 możliwości defektu na jednostkę. Ile wynosi DPMO?",
             1133.33, "17/(5000*3)*1000000", ["17 / 15 000 · 10⁶ ≈ 1 133,33"], unit="DPMO", tol=0.05),
          LB("Ile razy DPMO 1 133 przekracza cel Six Sigma 3,4 (zaokrąglij do jedności)?",
             333, "1133/3.4", ["1 133 / 3,4 ≈ 333"], unit="razy", tol=1),
          LB("Reklamacje: 45, 25, 15, 10, 5 (5 przyczyn). Jaki odsetek reklamacji dają dwie najczęstsze przyczyny (%)?",
             70, "(45+25)/100*100", ["70 / 100 = 70%"], unit="%"),
          LB("Proces 3-etapowy z uzyskiem 98%, 95% i 99%. Ile wynosi uzysk całego procesu (%)?",
             92.17, "0.98*0.95*0.99*100", ["0,98 · 0,95 · 0,99 ≈ 92,17%"], unit="%", tol=0.02),
          LB("Karta kontrolna: średnia 50 mm, σ = 2 mm. Ile wynosi górna granica kontrolna (mm)?",
             56, "50+3*2", ["50 + 3 · 2 = 56 mm"], unit="mm"),
          LB("Ile lat minęło od wydania ISO 9001:2015 do wydania ISO 9001:2026?",
             11, "2026-2015", ["2026 − 2015 = 11"], unit="lat"),
      ],
      case=[
          PR("Producent mebli ma 8% reklamacji. Analiza Pareto: 50% to porysowane fronty, 30% – źle dopasowane zawiasy, reszta to drobne przyczyny. Diagram Ishikawy dla rys wskazuje sposób pakowania i transport.",
             W("Od czego zacząć poprawę?",
               "Od porysowanych frontów – największa przyczyna", "Od drobnych przyczyn", "Od zmiany logo",
               why="Pareto wskazuje priorytet."),
             W("Jakie działanie wynika z diagramu Ishikawy?",
               "Zmiana opakowań i sposobu transportu", "Zwolnienie stolarzy", "Podwyżka cen",
               why="To zidentyfikowane przyczyny rys."),
             PF("Usunięcie dwóch głównych przyczyn może zmniejszyć reklamacje o ok. 80%.", True,
                why="50% + 30% = 80% reklamacji."),
          ),
          PR("Firma ma certyfikat ISO 9001:2015. Audytor przypomina, że we wrześniu 2026 r. opublikowano nowe wydanie normy. Zarząd uważa, że certyfikat jest ważny bezterminowo i nic nie trzeba robić.",
             W("Co powinna zrobić firma?",
               "Zaplanować przejście na ISO 9001:2026 w okresie przejściowym", "Nic – certyfikat jest wieczny", "Natychmiast zrezygnować z certyfikacji",
               why="Certyfikaty według starego wydania wygasają po okresie przejściowym."),
             W("Co potwierdza certyfikat ISO 9001?",
               "Że firma ma działający system zarządzania jakością", "Że każdy produkt jest bez wad", "Że firma jest rentowna",
               why="Dotyczy systemu i procesów."),
             PF("Certyfikat ISO 9001 jest podstawą wymagań klientów w wielu przetargach i łańcuchach dostaw.", True,
                why="Wiele firm wymaga go od dostawców."),
          ),
      ]),
]
