# -*- coding: utf-8 -*-
# Zrozumienie – Zarządzanie / Osoby
OSM = "https://openstax.org/books/principles-management/pages/"
D = "2026-10-08"
M12 = S("OpenStax, Principles of Management, 1.2 The Roles Managers Play", OSM + "1-2-the-roles-managers-play", D)
M34 = S("OpenStax, Principles of Management, 3.4 Taylor-Made Management", OSM + "3-4-taylor-made-management", D)
M35 = S("OpenStax, Principles of Management, 3.5 Administrative and Bureaucratic Management", OSM + "3-5-administrative-and-bureaucratic-management", D)
M36 = S("OpenStax, Principles of Management, 3.6 Human Relations Movement", OSM + "3-6-human-relations-movement", D)
M37 = S("OpenStax, Principles of Management, 3.7 Contingency and System Management", OSM + "3-7-contingency-and-system-management", D)
M62 = S("OpenStax, Principles of Management, 6.2 Hofstede’s Cultural Framework", OSM + "6-2-hofstedes-cultural-framework", D)
M91 = S("OpenStax, Principles of Management, 9.1 Strategic Management", OSM + "9-1-strategic-management", D)
M135 = S("OpenStax, Principles of Management, 13.5 Behavioral Approaches to Leadership", OSM + "13-5-behavioral-approaches-to-leadership", D)
M136 = S("OpenStax, Principles of Management, 13.6 Situational (Contingency) Approaches to Leadership", OSM + "13-6-situational-contingency-approaches-to-leadership", D)
M142 = S("OpenStax, Principles of Management, 14.2 Content Theories of Motivation", OSM + "14-2-content-theories-of-motivation", D)
M143 = S("OpenStax, Principles of Management, 14.3 Process Theories of Motivation", OSM + "14-3-process-theories-of-motivation", D)
M152 = S("OpenStax, Principles of Management, 15.2 Team Development Over Time", OSM + "15-2-team-development-over-time", D)

LESSONS = [
    L(1, "Klasycy: naukowe zarządzanie i administracja",
      "Rozumieć dorobek twórców szkoły klasycznej – Taylora, Gilbrethów, Gantta, Emersona i Forda (organizacja pracy) oraz Fayola, Webera i Urwicka (administracja i struktura) – i oceniać jego mocne i słabe strony.",
      ["Taylor Frederick Winslow", "Gilbreth Frank i Lillian", "Gantt Henry", "Emerson Harrington", "Ford Henry", "Fayol Henri", "Weber Max", "Urwick Lyndall"],
      [M34, M35],
      explain=[
          K("Taylor i naukowa organizacja pracy",
            "F.W. Taylor („Zasady naukowego zarządzania”, 1911): badanie pracy pomiarami czasu, ustalenie jednej najlepszej metody, dobór i szkolenie pracowników, podział odpowiedzialności między kierownictwo (planowanie) a robotników (wykonanie), akordowy system różnicowy – wyższa stawka za wykonanie normy. Krytyka: traktowanie człowieka jak maszyny, monotonia."),
          K("Gilbrethowie, Gantt, Emerson, Ford",
            "Frank i Lillian Gilbreth – badanie ruchów (np. przy murowaniu cegieł), elementarne ruchy „therbligi”; Lillian wniosła psychologię pracy. H. Gantt – wykres harmonogramu (paski zadań na osi czasu) i system premiowy. H. Emerson – „Dwanaście zasad wydajności” (1912), wskaźnik sprawności = czas normatywny / czas rzeczywisty. H. Ford – ruchoma linia montażowa (1913) i płaca 5 dolarów dziennie (1914), standaryzacja i produkcja masowa."),
          W("Kierownik projektu przedstawia zadania jako paski na osi czasu. Czyje narzędzie stosuje?",
            "H. Gantta", "M. Webera", "H. Fayola",
            why="To wykres Gantta – harmonogram zadań."),
          K("Fayol i Urwick",
            "H. Fayol („Administracja przemysłowa i ogólna”, 1916) patrzył z perspektywy dyrektora: 5 funkcji administracji – przewidywanie, organizowanie, rozkazywanie, koordynowanie, kontrolowanie – oraz 14 zasad zarządzania (m.in. podział pracy, jedność rozkazodawstwa, hierarchia, ład, sprawiedliwość, inicjatywa). L. Urwick usystematyzował zasady administracji, m.in. ograniczoną rozpiętość kierowania."),
          K("Weber i biurokracja",
            "M. Weber opisał biurokrację jako idealny typ organizacji opartej na władzy legalnej: hierarchia stanowisk, formalne reguły, specjalizacja, bezosobowość, awans według kompetencji, dokumentacja. Zalety: przewidywalność i sprawiedliwość; wady (w praktyce): sztywność, formalizm, powolność."),
          PF("Jedność rozkazodawstwa jest jedną z 14 zasad H. Fayola.", True,
             why="Każdy pracownik powinien mieć jednego przełożonego."),
      ],
      mech=[
          KT("Kto to zaproponował?",
             {"F.W. Taylor": ["Akordowy system różnicowy i pomiar czasu pracy"],
              "Gilbrethowie": ["Analiza elementarnych ruchów (therbligi)"],
              "H. Fayol": ["Pięć funkcji administracji i 14 zasad"],
              "M. Weber": ["Idealny typ biurokracji opartej na władzy legalnej"],
              "H. Ford": ["Ruchoma linia montażowa w produkcji samochodów"]},
             why="Każdy klasyk wniósł inny element."),
          LN("Ułóż funkcje administracji według Fayola.",
             ["Przewidywanie (planowanie)", "Organizowanie", "Rozkazywanie", "Koordynowanie", "Kontrolowanie"],
             why="Fayol uważał je za uniwersalne funkcje kierownika."),
          W("Czym różnią się perspektywy Taylora i Fayola?",
            "Taylor patrzył od strony stanowiska robotnika, Fayol – od strony naczelnego kierownictwa", "Niczym", "Fayol badał ruchy robotników, a Taylor – całą firmę",
            why="Naukowe zarządzanie vs administracja."),
          W("Jaka jest główna krytyka naukowego zarządzania?",
            "Pomijanie potrzeb społecznych i psychologicznych pracowników", "Brak pomiarów", "Zbyt duża swoboda robotników",
            why="Taylor traktował pracownika głównie jako czynnik ekonomiczny."),
          M("Jakie cechy ma biurokracja według Webera?",
            ["Hierarchia stanowisk", "Formalne reguły", "Awans według kompetencji", "Decyzje według sympatii"], [0, 1, 2],
            why="Biurokracja zakłada bezosobowość reguł."),
          PF("Ford wprowadził płacę 5 dolarów dziennie m.in. by ograniczyć wysoką rotację pracowników.", True,
             why="Monotonna praca na linii powodowała masowe odejścia."),
      ],
      calc=[
          LB("Akord różnicowy: norma 50 szt., stawka 0,60 zł/szt. przy wykonaniu normy, 0,40 zł/szt. poniżej. Ile zarobi robotnik za 55 szt. (zł)?",
             33, "55*0.6", ["55 · 0,60 = 33 zł"], unit="zł"),
          LB("Ile zarobi robotnik za 45 szt. (poniżej normy) (zł)?",
             18, "45*0.4", ["45 · 0,40 = 18 zł"], unit="zł"),
          LB("Emerson: czas normatywny 6 h, czas rzeczywisty 8 h. Ile wynosi sprawność (%)?",
             75, "6/8*100", ["6 / 8 = 75%"], unit="%"),
          LB("Linia montażowa skróciła montaż podwozia z ok. 750 min (12,5 h) do ok. 93 min. O ile procent?",
             87.6, "(1-93/750)*100", ["93 / 750 = 0,124 → −87,6%"], unit="%", tol=0.02),
          LB("Płaca u Forda wzrosła z ok. 2,34 do 5 dolarów dziennie. O ile procent?",
             113.68, "(5/2.34-1)*100", ["5 / 2,34 ≈ 2,1368 → +113,68%"], unit="%", tol=0.05),
          LB("Ile lat dzieli „Zasady naukowego zarządzania” (1911) od książki Fayola (1916)?",
             5, "1916-1911", ["1916 − 1911 = 5"], unit="lat"),
      ],
      case=[
          PR("Centrum logistyczne mierzy czas każdej czynności magazynierów, ustala jedną standardową metodę kompletacji, a wynagrodzenie zależy od liczby skompletowanych zamówień. Wydajność wzrosła o 20%, ale rośnie liczba zwolnień lekarskich i odejść.",
             W("Którą szkołę przypomina ten system?",
               "Naukowe zarządzanie Taylora", "Szkołę stosunków międzyludzkich", "Teorię Y McGregora",
               why="Pomiar czasu, jedna metoda, płaca za wynik."),
             W("Jakiego ograniczenia szkoły klasycznej dowodzi rosnąca absencja?",
               "Pomijania potrzeb społecznych i zdrowia pracowników", "Braku pomiarów wydajności", "Zbyt wysokich płac",
               why="Presja normy i monotonia mają koszty ludzkie."),
             PF("Rotacja zadań i przerwy mogą łagodzić skutki wąskiej specjalizacji.", True,
                why="Zmniejszają monotonię i przeciążenia."),
          ),
          PR("Urząd wydaje pozwolenia według ścisłych procedur. Każdy wniosek przechodzi przez 6 szczebli akceptacji, a urzędnicy nie mogą odstąpić od formularza nawet w oczywistych sprawach. Obywatele skarżą się na powolność.",
             W("Jaki model organizacji opisuje sytuacja?",
               "Biurokrację Webera (z jej dysfunkcjami)", "Organizację sieciową", "Teorię Y",
               why="Hierarchia, reguły i formalizm."),
             W("Która cecha biurokracji jest tu zaletą?",
               "Równe traktowanie wszystkich wnioskodawców według tych samych reguł", "Powolność", "Nadmiar szczebli",
               why="Bezosobowość reguł chroni przed arbitralnością."),
             PF("Ograniczenie liczby szczebli akceptacji mogłoby przyspieszyć decyzje.", True,
                why="Mniej etapów to krótszy czas obsługi."),
          ),
      ]),

    L(2, "Szkoła stosunków międzyludzkich i badacze motywacji",
      "Rozumieć wkład Mayo, Follett, Barnarda, McGregora i Heidera oraz twórców teorii motywacji (Maslow, Herzberg, McClelland, Alderfer, Adams, Vroom) i umieć zastosować ich idee w praktyce kierowania.",
      ["Mayo Elton", "Follett Mary Parker", "Barnard Chester", "McGregor Douglas", "Heider Fritz", "Maslow Abraham", "Herzberg Frederick", "McClelland David", "Alderfer Clayton", "Adams J. Stacy", "Vroom Victor"],
      [M36, M142, M143],
      explain=[
          K("Mayo i eksperymenty w Hawthorne",
            "W zakładach Western Electric w Hawthorne (1924–1932) badano wpływ oświetlenia i warunków pracy na wydajność; zespół z udziałem E. Mayo odkrył, że ważniejsze od warunków fizycznych są czynniki społeczne: uwaga poświęcona pracownikom, normy grupy nieformalnej, relacje. „Efekt Hawthorne” – zmiana zachowania pod wpływem świadomości bycia obserwowanym."),
          K("Follett i Barnard",
            "M.P. Follett: konflikty rozwiązywać przez integrację (rozwiązanie zadowalające obie strony), władza „z” ludźmi zamiast „nad” ludźmi, „prawo sytuacji” – polecenia wynikają z wymagań sytuacji. Ch. Barnard („Funkcje kierownika”, 1938): organizacja to system współpracy; teoria akceptacji władzy – polecenie jest skuteczne, jeśli podwładny je akceptuje (strefa obojętności)."),
          W("Kierowniczka szuka rozwiązania sporu, które zaspokoi interesy obu działów, zamiast wybierać zwycięzcę. Czyje podejście stosuje?",
            "M.P. Follett (integracja)", "F.W. Taylora", "M. Webera",
            why="Follett proponowała integrację zamiast kompromisu lub dominacji."),
          K("McGregor i Heider",
            "D. McGregor („Ludzka strona przedsiębiorstwa”, 1960): teoria X – ludzie nie lubią pracy, trzeba ich kontrolować; teoria Y – ludzie mogą lubić pracę, szukać odpowiedzialności i samokontroli. Założenia kierownika działają jak samospełniające się proroctwo. F. Heider – teoria atrybucji (1958): przypisujemy przyczyny zachowań czynnikom wewnętrznym (cechy osoby) lub zewnętrznym (sytuacja); typowy błąd to przecenianie przyczyn wewnętrznych u innych."),
          K("Badacze motywacji",
            "A. Maslow (1943) – hierarchia potrzeb; F. Herzberg (1959) – czynniki higieny i motywatory; D. McClelland – potrzeby osiągnięć, władzy, przynależności; C. Alderfer (1969) – ERG; J.S. Adams (1963) – teoria sprawiedliwości; V. Vroom (1964) – teoria oczekiwań M = E · I · V."),
          PF("Teoria Y zakłada, że pracownicy mogą sami szukać odpowiedzialności.", True,
             why="McGregor przeciwstawił ją pesymistycznej teorii X."),
      ],
      mech=[
          KT("Kto jest autorem idei?",
             {"E. Mayo": ["Znaczenie grup nieformalnych odkryte w Hawthorne"],
              "Ch. Barnard": ["Teoria akceptacji władzy i strefa obojętności"],
              "D. McGregor": ["Teoria X i teoria Y"],
              "F. Heider": ["Przypisywanie przyczyn zachowań (atrybucja)"],
              "J.S. Adams": ["Porównywanie stosunku efektów do nakładów"]},
             why="Różne nurty szkoły behawioralnej."),
          LN("Ułóż chronologicznie publikacje.",
             ["Barnard – „Funkcje kierownika” (1938)", "Maslow – hierarchia potrzeb (1943)", "Herzberg – teoria dwuczynnikowa (1959)", "McGregor – teoria X i Y (1960)", "Vroom – teoria oczekiwań (1964)"],
             why="Kolejne etapy rozwoju nauki o zachowaniach w organizacji."),
          W("Kierownik uważa, że pracownicy są leniwi, więc wprowadza ścisłą kontrolę. Pracownicy tracą inicjatywę, co „potwierdza” jego przekonanie. Jakie zjawisko opisał tu McGregor?",
            "Samospełniające się proroctwo założeń teorii X", "Efekt Hawthorne", "Teorię ERG",
            why="Założenia kierownika kształtują zachowanie pracowników."),
          W("Szef uznaje spóźnienie pracownika za dowód lenistwa, ignorując awarię tramwaju. Jaki błąd opisuje teoria atrybucji?",
            "Przecenianie przyczyn wewnętrznych (podstawowy błąd atrybucji)", "Efekt aureoli", "Myślenie grupowe",
            why="Pominięto czynnik zewnętrzny."),
          M("Co odkryto w badaniach w Hawthorne?",
            ["Wpływ uwagi poświęcanej pracownikom", "Znaczenie norm grup nieformalnych", "Rolę relacji społecznych w pracy", "Że oświetlenie jest jedynym czynnikiem wydajności"], [0, 1, 2],
            why="Czynniki społeczne okazały się ważniejsze od fizycznych."),
          PF("Według Barnarda władza kierownika zależy także od akceptacji poleceń przez podwładnych.", True,
             why="To teoria akceptacji władzy."),
      ],
      calc=[
          LB("Ile lat trwały badania w Hawthorne (1924–1932)?",
             8, "1932-1924", ["1932 − 1924 = 8"], unit="lat"),
          LB("Ile lat dzieli teorię Maslowa (1943) od teorii X i Y (1960)?",
             17, "1960-1943", ["1960 − 1943 = 17"], unit="lat"),
          LB("Vroom: E = 0,5, I = 0,8, V = 1. Ile wynosi motywacja?",
             0.4, "0.5*0.8*1", ["0,5 · 0,8 · 1 = 0,4"], unit="", tol=0.001),
          LB("Adams: Ewa dostaje 6 300 zł za 180 h pracy w miesiącu, kolega 6 300 zł za 150 h. O ile zł na godzinę zarabia mniej Ewa?",
             7, "6300/150-6300/180", ["42 − 35 = 7 zł/h"], unit="zł/h"),
          LB("W grupie nieformalnej norma to 90 szt. dziennie, a pracownik mógłby robić 120. Jaki procent możliwości wykorzystuje?",
             75, "90/120*100", ["90 / 120 = 75%"], unit="%"),
          LB("Ile lat minęło od „Funkcji kierownika” Barnarda (1938) do 2026 r.?",
             88, "2026-1938", ["2026 − 1938 = 88"], unit="lat"),
      ],
      case=[
          PR("W zakładzie stworzono grupę roboczą, której członkowie mogą zgłaszać pomysły, a kierownik regularnie z nimi rozmawia. Wydajność wzrosła, choć warunki fizyczne się nie zmieniły. Pracownicy innych zmian ustalają jednak nieformalnie, że „nie przekraczamy 90 sztuk”.",
             W("Które odkrycie ze szkoły stosunków międzyludzkich ilustruje wzrost wydajności?",
               "Wpływ uwagi i relacji społecznych na wydajność", "Wpływ oświetlenia", "Teorię biurokracji",
               why="Zmieniły się relacje, nie warunki fizyczne."),
             W("Co ilustruje limit 90 sztuk?",
               "Normy grupy nieformalnej", "Teorię oczekiwań", "System akordowy Taylora",
               why="Grupa sama reguluje tempo pracy."),
             PF("Kierownik może wpływać na normy grupy, angażując jej liderów nieformalnych.", True,
                why="Liderzy nieformalni kształtują zachowania grupy."),
          ),
          PR("Nowy dyrektor zakłada, że pracownicy chcą się rozwijać. Wprowadza samodzielne zespoły, cele ustalane wspólnie i nagrody za osiągnięcia. Jeden z kierowników protestuje: „bez kontroli nikt nie będzie pracował”.",
             W("Jakie założenia ma dyrektor, a jakie kierownik?",
               "Dyrektor – teorii Y, kierownik – teorii X", "Obaj – teorii X", "Dyrektor – teorii X, kierownik – teorii Y",
               why="Optymistyczny vs pesymistyczny obraz pracownika."),
             W("Który teoretyk motywacji uzasadniłby nagrody za osiągnięcia jako motywatory?",
               "F. Herzberg", "M. Weber", "H. Gantt",
               why="Osiągnięcia i uznanie to motywatory według Herzberga."),
             PF("Wspólne ustalanie celów zwiększa akceptację celów przez pracowników.", True,
                why="Uczestnictwo buduje zaangażowanie."),
          ),
      ]),

    L(3, "Badacze przywództwa i zespołów",
      "Porównywać koncepcje przywództwa – Likerta, Blake’a i Mouton, Tannenbauma i Schmidta, Fiedlera, House’a, Herseya i Blancharda – oraz modele zespołów Tuckmana i Belbina.",
      ["Likert Rensis", "Blake Robert, Mouton Jane", "Tannenbaum Robert, Schmidt Warren H.", "Fiedler Fred", "House Robert", "Hersey Paul, Blanchard Kenneth", "Tuckman Bruce", "Belbin R. Meredith"],
      [M135, M136, M152],
      explain=[
          K("Podejście behawioralne",
            "R. Likert (Michigan) – cztery systemy zarządzania od autorytarnego eksploatatorskiego do partycypacyjnego; najlepsze wyniki dawał system 4. R. Blake i J. Mouton (1964) – siatka kierownicza: troska o produkcję × troska o ludzi (1–9), ideał 9.9. R. Tannenbaum i W. Schmidt (1958) – kontinuum zachowań: od decyzji kierownika ogłaszanej podwładnym po swobodę działania zespołu w wyznaczonych granicach."),
          K("Podejście sytuacyjne",
            "F. Fiedler (model LPC) – styl lidera jest stały; skuteczność zależy od sprzyjania sytuacji (relacje, struktura zadania, władza). R. House (1971) – teoria ścieżki do celu: lider dobiera styl (dyrektywny, wspierający, partycypacyjny, nastawiony na osiągnięcia), by ułatwić podwładnym osiągnięcie celów. P. Hersey i K. Blanchard – styl dopasowany do gotowości podwładnych (instruowanie, przekonywanie, uczestniczenie, delegowanie)."),
          W("Według którego autora lider powinien zmieniać styl wraz z rozwojem kompetencji pracownika?",
            "Herseya i Blancharda", "Fiedlera", "Webera",
            why="Model cyklu życia dopasowuje styl do gotowości."),
          K("Tuckman i Belbin",
            "B. Tuckman (1965) – fazy rozwoju zespołu: formowanie, burzenie, normowanie, działanie (w 1977 r. z M.A. Jensen dodał rozwiązanie). R.M. Belbin („Management Teams”, 1981) – role zespołowe; obecnie 9 ról (m.in. kreator, koordynator, perfekcjonista, specjalista). Zespół z samych „inteligentnych” osób (tzw. zespół Apollo) nie zawsze był najlepszy – liczy się równowaga ról."),
          K("Wspólny wniosek",
            "Badania przeszły od szukania jednego najlepszego stylu (Likert, Blake i Mouton) do podejścia sytuacyjnego (Fiedler, House, Hersey i Blanchard) – skuteczność zależy od ludzi, zadania i kontekstu. Podobnie w zespołach: liczy się dopasowanie ról i etap rozwoju grupy."),
          PF("Fiedler uważał, że lider łatwo zmienia swój styl.", False,
             why="Styl jest stały – zmienia się lidera lub sytuację."),
      ],
      mech=[
          KT("Autor koncepcji",
             {"R. Likert": ["Cztery systemy zarządzania"],
              "Blake i Mouton": ["Siatka kierownicza 9 × 9"],
              "Tannenbaum i Schmidt": ["Kontinuum zachowań przywódczych"],
              "R. House": ["Teoria ścieżki do celu"],
              "R.M. Belbin": ["Role zespołowe"]},
             why="Każdy autor zaproponował inny model."),
          LN("Ułóż koncepcje przywództwa chronologicznie.",
             ["Tannenbaum i Schmidt – kontinuum (1958)", "Blake i Mouton – siatka kierownicza (1964)", "Fiedler – model LPC (1967)", "House – ścieżka do celu (1971)", "Belbin – role zespołowe (1981)"],
             why="Od modeli zachowań do podejść sytuacyjnych i zespołowych."),
          W("Kierownik przedstawia problem, zbiera sugestie zespołu i dopiero wtedy decyduje. Gdzie leży to zachowanie na kontinuum Tannenbauma i Schmidta?",
            "Pośrodku – kierownik konsultuje przed decyzją", "Na skrajnym biegunie autokratycznym", "Na biegunie pełnej swobody zespołu",
            why="Udział zespołu jest, ale decyzja należy do kierownika."),
          W("Co pokazał eksperyment z zespołem złożonym z samych bardzo inteligentnych osób (Belbin)?",
            "Bez równowagi ról zespół często osiągał słabe wyniki", "Był zawsze najlepszy", "Nie mógł istnieć",
            why="Liczy się różnorodność ról, nie tylko inteligencja."),
          M("Którzy autorzy reprezentują podejście sytuacyjne?",
            ["F. Fiedler", "R. House", "Hersey i Blanchard", "M. Weber"], [0, 1, 2],
            why="Weber to klasyk teorii biurokracji."),
          PF("Tuckman dodał fazę rozwiązania zespołu w 1977 r.", True,
             why="Opisał ją wspólnie z M.A. Jensen."),
      ],
      calc=[
          LB("Ile lat dzieli kontinuum Tannenbauma i Schmidta (1958) od siatki Blake’a i Mouton (1964)?",
             6, "1964-1958", ["1964 − 1958 = 6"], unit="lat"),
          LB("Model Fiedlera: 3 wymiary po 2 poziomy. Ile sytuacji?",
             8, "2*2*2", ["2³ = 8"], unit="sytuacji"),
          LB("Belbin opisał w 1981 r. 8 ról, a później dodał rolę specjalisty. Ile ról liczy model obecnie?",
             9, "8+1", ["8 + 1 = 9"], unit="ról"),
          LB("Zespół 6 osób ma pokryć 9 ról Belbina. Ile ról średnio przypada na osobę?",
             1.5, "9/6", ["9 / 6 = 1,5"], unit="roli"),
          LB("Kierownik na siatce: zadania 9, ludzie 1. O ile punktów brakuje w trosce o ludzi do stylu 9.9?",
             8, "9-1", ["9 − 1 = 8"], unit="pkt"),
          LB("Ile lat dzieli fazy Tuckmana (1965) od ról Belbina (1981)?",
             16, "1981-1965", ["1981 − 1965 = 16"], unit="lat"),
      ],
      case=[
          PR("Nowo powołany zespół projektowy ma pięciu wybitnych analityków, ale nikogo, kto pilnuje terminów i doprowadza zadania do końca. Po miesiącu trwają spory o kierunek prac.",
             W("Jakie role Belbina są niedoreprezentowane?",
               "Role domykające i organizujące (perfekcjonista, praktyczny organizator, koordynator)", "Role kreatywne", "Żadne",
               why="Zespół ma analityków, brakuje wdrażania i koordynacji."),
             W("W jakiej fazie Tuckmana jest zespół?",
               "Burzenia", "Działania", "Rozwiązania",
               why="Spory o kierunek i role."),
             PF("Dobór ról jest równie ważny jak indywidualne kompetencje.", True,
                why="Wnioski Belbina z badań zespołów."),
          ),
          PR("Kierowniczka zespołu sprzedaży stosuje inny styl wobec każdego: nowym daje szczegółowe instrukcje, doświadczonym, ale zniechęconym – wsparcie i udział w decyzjach, ekspertom – pełną swobodę.",
             W("Który model najlepiej opisuje jej podejście?",
               "Hersey i Blanchard – przywództwo sytuacyjne", "Fiedler – stały styl lidera", "Weber – biurokracja",
               why="Styl dopasowany do gotowości pracownika."),
             W("Jaki styl stosuje wobec ekspertów?",
               "Delegowanie", "Instruowanie", "Przekonywanie",
               why="Wysokie kompetencje i motywacja."),
             PF("Teoria ścieżki do celu House’a również zaleca dobór stylu do podwładnych i zadania.", True,
                why="Obie teorie są sytuacyjne."),
          ),
      ]),

    L(4, "Twórcy koncepcji strategii, marketingu i internacjonalizacji",
      "Rozumieć koncepcje Ansoffa, Portera, Mintzberga, Milesa i Snowa, Kim i Mauborgne, Kotlera, Levitta, Kaplana i Nortona, Freemana oraz Johansona i Vahlnego – i stosować je do analizy decyzji firm.",
      ["Ansoff Igor", "Porter Michael E.", "Mintzberg Henry", "Miles Raymond, Snow Charles", "Kim W. Chan, Mauborgne Renée", "Kotler Philip", "Levitt Theodore", "Kaplan Robert, Norton David", "Freeman R. Edward", "Johanson Jan, Vahlne Jan-Erik"],
      [M12, M91],
      explain=[
          K("Ansoff i Porter",
            "I. Ansoff (1957) – macierz produkt–rynek: penetracja rynku, rozwój rynku, rozwój produktu, dywersyfikacja (najbardziej ryzykowna). M. Porter – pięć sił konkurencji (1979), strategie ogólne: przywództwo kosztowe, zróżnicowanie, koncentracja (1980), łańcuch wartości (1985), diament przewagi konkurencyjnej narodów (1990)."),
          K("Mintzberg oraz Miles i Snow",
            "H. Mintzberg (1973) obserwował pracę dyrektorów: 10 ról kierowniczych w 3 grupach – interpersonalne (reprezentant, przywódca, łącznik), informacyjne (monitorujący, propagator, rzecznik), decyzyjne (przedsiębiorca, przeciwdziałający zakłóceniom, dysponent zasobów, negocjator); strategia bywa zamierzona albo wyłaniająca się. R. Miles i C. Snow (1978) – typy strategii: obrońca, poszukiwacz, analizator, reaktor."),
          W("Firma szuka stale nowych produktów i rynków, akceptując ryzyko niepowodzeń. Jaki to typ według Milesa i Snowa?",
            "Poszukiwacz", "Obrońca", "Reaktor",
            why="Poszukiwacz nastawiony jest na innowacje i nowe rynki."),
          K("Kim i Mauborgne, Kotler, Levitt",
            "W.Ch. Kim i R. Mauborgne („Strategia błękitnego oceanu”, 2005) – zamiast walczyć z konkurentami na „czerwonym oceanie”, tworzyć nową przestrzeń rynkową (eliminować, redukować, podnosić, kreować). Ph. Kotler – systematyzacja zarządzania marketingiem (4P, STP, marketing społeczny). T. Levitt – „marketingowa krótkowzroczność” (1960) i globalizacja rynków (1983)."),
          K("Kaplan i Norton, Freeman, Uppsala",
            "R. Kaplan i D. Norton (1992) – zrównoważona karta wyników (4 perspektywy). R.E. Freeman (1984) – teoria interesariuszy: firma odpowiada wobec wszystkich grup, na które wpływa (pracownicy, klienci, dostawcy, społeczności), a nie tylko akcjonariuszy. J. Johanson i J.-E. Vahlne (1977) – model uppsalski: firmy internacjonalizują się stopniowo, zaczynając od rynków bliskich „psychicznie”, i zwiększają zaangażowanie wraz z nabywaniem wiedzy."),
          PF("Według macierzy Ansoffa dywersyfikacja to wejście z nowym produktem na nowy rynek.", True,
             why="To najbardziej ryzykowna z czterech strategii."),
      ],
      mech=[
          KT("Strategia w macierzy Ansoffa",
             {"Penetracja rynku": ["Promocje, by obecni klienci kupowali więcej tego samego produktu"],
              "Rozwój rynku": ["Sprzedaż tego samego produktu w nowym kraju"],
              "Rozwój produktu": ["Nowy produkt dla obecnych klientów"],
              "Dywersyfikacja": ["Producent mebli wchodzi w produkcję energii słonecznej"]},
             why="Kombinacje: produkt obecny/nowy × rynek obecny/nowy."),
          LN("Ułóż etapy internacjonalizacji według modelu uppsalskiego.",
             ["Sporadyczny eksport", "Eksport przez niezależnych przedstawicieli", "Własny oddział sprzedaży za granicą", "Produkcja za granicą"],
             why="Zaangażowanie rośnie wraz z wiedzą o rynku."),
          W("Dyrektor podpisuje dokumenty i przecina wstęgę na otwarciu zakładu. Jaką rolę według Mintzberga pełni?",
            "Reprezentanta (rola interpersonalna)", "Negocjatora", "Monitorującego",
            why="Symboliczne obowiązki wobec otoczenia."),
          W("Cyrk połączył elementy teatru i akrobatyki, rezygnując ze zwierząt i gwiazd areny – i stworzył nowy rynek. Jaką koncepcję ilustruje?",
            "Strategię błękitnego oceanu", "Strategię obrońcy", "Penetrację rynku",
            why="Tworzenie nowej przestrzeni rynkowej."),
          M("Które grupy interesariuszy uwzględnia teoria Freemana?",
            ["Pracowników", "Klientów", "Społeczności lokalne", "Wyłącznie akcjonariuszy"], [0, 1, 2],
            why="Teoria interesariuszy wykracza poza akcjonariuszy."),
          PF("Mintzberg opisał zarówno strategie zamierzone, jak i wyłaniające się.", True,
             why="Strategia może powstawać w trakcie działania."),
      ],
      calc=[
          LB("Ile ról kierowniczych wyróżnia Mintzberg, jeśli są 3 interpersonalne, 3 informacyjne i 4 decyzyjne?",
             10, "3+3+4", ["3 + 3 + 4 = 10"], unit="ról"),
          LB("Jaki odsetek ról Mintzberga to role decyzyjne (%)?",
             40, "4/10*100", ["4 / 10 = 40%"], unit="%"),
          LB("Penetracja rynku: udział rośnie z 10% do 14% na rynku 500 mln zł. O ile mln zł rośnie sprzedaż?",
             20, "500*(0.14-0.10)", ["500 · 0,04 = 20 mln zł"], unit="mln zł"),
          LB("Ile lat dzieli strategie ogólne Portera (1980) od strategii błękitnego oceanu (2005)?",
             25, "2005-1980", ["2005 − 1980 = 25"], unit="lat"),
          LB("Ile lat dzieli model uppsalski (1977) od pięciu sił Portera (1979)?",
             2, "1979-1977", ["1979 − 1977 = 2"], unit="lata"),
          LB("Macierz Ansoffa: 2 opcje produktu × 2 opcje rynku. Ile strategii?",
             4, "2*2", ["2 · 2 = 4"], unit="strategie"),
      ],
      case=[
          PR("Polska firma kosmetyczna sprzedaje w kraju. Najpierw zaczęła eksportować do Czech i na Słowację przez dystrybutorów, po pięciu latach otworzyła tam własne biuro, a dopiero potem weszła do Niemiec i Francji.",
             W("Który model opisuje tę ścieżkę?",
               "Model uppsalski Johansona i Vahlnego", "Strategia błękitnego oceanu", "Siatka kierownicza",
               why="Stopniowe zwiększanie zaangażowania, od rynków bliskich."),
             W("Którą strategię Ansoffa realizuje firma?",
               "Rozwój rynku – te same produkty na nowych rynkach", "Dywersyfikację", "Rozwój produktu",
               why="Produkty obecne, rynki nowe."),
             PF("Czechy i Słowacja są dla polskiej firmy rynkami bliskimi „psychicznie”.", True,
                why="Podobny język, kultura i warunki biznesowe."),
          ),
          PR("Spółka energetyczna planuje farmę wiatrową. Akcjonariusze oczekują zysku, mieszkańcy obawiają się hałasu, ekolodzy – wpływu na ptaki, a gmina liczy na podatki.",
             W("Którą teorię warto zastosować do analizy sytuacji?",
               "Teorię interesariuszy Freemana", "Teorię X McGregora", "Akord różnicowy Taylora",
               why="Wiele grup ma interes w decyzji firmy."),
             W("Jakie działanie wynika z tej teorii?",
               "Dialog z interesariuszami i uwzględnienie ich interesów w projekcie", "Pominięcie wszystkich poza akcjonariuszami", "Rezygnacja z inwestycji bez analizy",
               why="Interesariusze wpływają na powodzenie przedsięwzięcia."),
             PF("Konflikt z mieszkańcami może opóźnić lub zablokować inwestycję.", True,
                why="Interesariusze mają realny wpływ na projekt."),
          ),
      ]),

    L(5, "Organizacja, jakość, kultura i współczesne idee",
      "Rozumieć wkład Deminga, Druckera, Simona, Sengego, Thompsona, Woodward, Hofstedego, Riesa i Griffina – od jakości i zarządzania przez cele po kulturę narodową i lean startup.",
      ["Deming W. Edwards", "Drucker Peter", "Simon Herbert", "Senge Peter", "Thompson James D.", "Woodward Joan", "Hofstede Geert", "Ries Eric", "Griffin Ricky W."],
      [M37, M62],
      explain=[
          K("Deming i Drucker",
            "W.E. Deming – statystyczne sterowanie jakością, 14 zasad, cykl PDCA; jego wykłady w Japonii (od 1950 r.) wpłynęły na jakość japońskiego przemysłu (nagroda Deminga). P. Drucker („Praktyka zarządzania”, 1954) – zarządzanie przez cele (MBO), menedżer jako osoba odpowiedzialna za wyniki, pracownik wiedzy, pytania „jaki jest nasz biznes? kto jest klientem?”."),
          K("Simon i Senge",
            "H. Simon („Administrative Behavior”, 1947; Nobel 1978) – ograniczona racjonalność i satysfakcjonowanie zamiast optymalizacji. P. Senge („Piąta dyscyplina”, 1990) – organizacja ucząca się i myślenie systemowe."),
          W("Który autor wprowadził zarządzanie przez cele (MBO)?",
            "P. Drucker", "W.E. Deming", "J. Woodward",
            why="MBO opisał Drucker w „Praktyce zarządzania” (1954)."),
          K("Thompson i Woodward – podejście sytuacyjne",
            "J. Woodward (badania ok. 100 firm w Essex, „Industrial Organization”, 1965): skuteczna struktura zależy od technologii – produkcja jednostkowa i małoseryjna, masowa, procesowa. J.D. Thompson („Organizations in Action”, 1967): współzależność zadań – łączna (wspólne zasoby), sekwencyjna (wynik jednej jednostki to wkład drugiej), wzajemna (wymiana w obie strony) – wymaga coraz silniejszej koordynacji."),
          K("Hofstede, Ries, Griffin",
            "G. Hofstede – wymiary kultury narodowej: dystans władzy, indywidualizm–kolektywizm, męskość–kobiecość, unikanie niepewności (badania w IBM, 1980), potem orientacja długoterminowa i pobłażliwość (łącznie 6). E. Ries („Lean Startup”, 2011) – MVP i pętla zbuduj–zmierz–ucz się. R.W. Griffin – autor popularnego podręcznika: zarządzanie to planowanie, organizowanie, przewodzenie i kontrolowanie zasobów (ludzkich, finansowych, rzeczowych, informacyjnych) w celu sprawnego i skutecznego osiągania celów."),
          PF("Według Woodward najlepsza struktura zależy od rodzaju technologii produkcji.", True,
             why="To wniosek z jej badań firm w Essex."),
      ],
      mech=[
          KT("Typ współzależności według Thompsona",
             {"Łączna": ["Oddziały banku korzystające ze wspólnego systemu i kapitału"],
              "Sekwencyjna": ["Linia montażowa: lakiernia przekazuje karoserię do montażu"],
              "Wzajemna": ["Zespół chirurgów i anestezjologów stale wymieniający informacje podczas operacji", "Projektanci i inżynierowie na bieżąco uzgadniający zmiany w prototypie"]},
             why="Rośnie potrzeba koordynacji: łączna < sekwencyjna < wzajemna."),
          LN("Ułóż prace chronologicznie.",
             ["Simon – „Administrative Behavior” (1947)", "Drucker – „Praktyka zarządzania” (1954)", "Woodward – „Industrial Organization” (1965)", "Hofstede – wymiary kultur (1980)", "Senge – „Piąta dyscyplina” (1990)", "Ries – „Lean Startup” (2011)"],
             why="Rozwój myśli o zarządzaniu po II wojnie światowej."),
          W("W kraju o wysokim dystansie władzy pracownicy zwykle:",
            "Akceptują hierarchię i oczekują poleceń od przełożonych", "Kwestionują każdą decyzję szefa", "Nie uznają żadnych tytułów",
            why="Nierówności władzy są tam uznawane za naturalne."),
          W("Który wniosek Woodward jest najważniejszy?",
            "Nie ma jednej najlepszej struktury – zależy ona od technologii", "Biurokracja jest zawsze najlepsza", "Technologia nie ma znaczenia",
            why="To podstawa podejścia sytuacyjnego."),
          M("Które wymiary kultury opisał Hofstede?",
            ["Dystans władzy", "Unikanie niepewności", "Indywidualizm–kolektywizm", "Wysokość PKB"], [0, 1, 2],
            why="PKB nie jest wymiarem kultury."),
          PF("Deming był związany z rozwojem zarządzania jakością w powojennej Japonii.", True,
             why="Jego wykłady od 1950 r. wpłynęły na japoński przemysł."),
      ],
      calc=[
          LB("Hofstede: 4 wymiary w 1980 r., potem dodano 2. Ile wymiarów obecnie?",
             6, "4+2", ["4 + 2 = 6"], unit="wymiarów"),
          LB("Ile lat dzieli „Administrative Behavior” (1947) od Nagrody Nobla dla Simona (1978)?",
             31, "1978-1947", ["1978 − 1947 = 31"], unit="lat"),
          LB("MBO: cel kwartalny 1 200 umów, wykonanie 1 080. Ile procent celu wykonano?",
             90, "1080/1200*100", ["1 080 / 1 200 = 90%"], unit="%"),
          LB("Ile zasad Deminga pozostaje do wdrożenia, jeśli firma wprowadziła 9 z 14?",
             5, "14-9", ["14 − 9 = 5"], unit="zasad"),
          LB("Ile lat dzieli „Praktykę zarządzania” Druckera (1954) od „Piątej dyscypliny” Sengego (1990)?",
             36, "1990-1954", ["1990 − 1954 = 36"], unit="lat"),
          LB("Ile typów współzależności (Thompson) i typów technologii (Woodward) łącznie?",
             6, "3+3", ["3 + 3 = 6"], unit="typów"),
      ],
      case=[
          PR("Polska firma otwiera oddział w kraju o bardzo niskim dystansie władzy i wysokim indywidualizmie. Polscy menedżerowie przyzwyczajeni są do wydawania szczegółowych poleceń. Lokalni pracownicy skarżą się na brak samodzielności.",
             W("Którą koncepcję warto wykorzystać do zrozumienia problemu?",
               "Wymiary kultury Hofstedego", "Akord różnicowy Taylora", "Macierz Ansoffa",
               why="Różnice w dystansie władzy i indywidualizmie."),
             W("Jak dostosować styl kierowania?",
               "Więcej delegowania, konsultacji i samodzielności", "Jeszcze ściślejsza kontrola", "Brak jakichkolwiek celów",
               why="Pasuje do niskiego dystansu władzy."),
             PF("Ten sam styl kierowania może być skuteczny w jednej kulturze i nieskuteczny w innej.", True,
                why="Kultura narodowa wpływa na oczekiwania pracowników."),
          ),
          PR("Szpital tworzy zespół na oddziale ratunkowym, w którym lekarze, pielęgniarki i diagności stale wymieniają informacje i dostosowują działania do stanu pacjenta. Dyrekcja chce wprowadzić sztywną procedurę „krok po kroku” jak na linii produkcyjnej.",
             W("Jaka współzależność zadań występuje na oddziale ratunkowym według Thompsona?",
               "Wzajemna", "Łączna", "Sekwencyjna",
               why="Ciągła wymiana w obu kierunkach."),
             W("Dlaczego sztywna procedura może nie działać?",
               "Współzależność wzajemna wymaga koordynacji przez bieżące uzgadnianie, a nie tylko przez reguły", "Bo lekarze nie znają procedur", "Bo szpital nie ma budżetu",
               why="Thompson: im silniejsza współzależność, tym bardziej elastyczna koordynacja."),
             PF("Podejście sytuacyjne zaleca dopasowanie organizacji do charakteru zadań.", True,
                why="Nie ma jednej najlepszej metody organizowania."),
          ),
      ]),
]
