# -*- coding: utf-8 -*-
# Zrozumienie – Zarządzanie / Planowanie i strategia
OSM = "https://openstax.org/books/principles-management/pages/"
D = "2026-10-08"
M82 = S("OpenStax, Principles of Management, 8.2 Using SWOT for Strategic Analysis", OSM + "8-2-using-swot-for-strategic-analysis", D)
M84 = S("OpenStax, Principles of Management, 8.4 A Firm's Micro Environment: Porter's Five Forces", OSM + "8-4-a-firms-micro-environment-porters-five-forces", D)
M85 = S("OpenStax, Principles of Management, 8.5 The Internal Environment", OSM + "8-5-the-internal-environment", D)
M86 = S("OpenStax, Principles of Management, 8.6 Competition, Strategy, and Competitive Advantage", OSM + "8-6-competition-strategy-and-competitive-advantage", D)
M87 = S("OpenStax, Principles of Management, 8.7 Strategic Positioning", OSM + "8-7-strategic-positioning", D)
M91 = S("OpenStax, Principles of Management, 9.1 Strategic Management", OSM + "9-1-strategic-management", D)
M92 = S("OpenStax, Principles of Management, 9.2 Firm Vision and Mission", OSM + "9-2-firm-vision-and-mission", D)
M94 = S("OpenStax, Principles of Management, 9.4 Strategic Objectives and Levels of Strategy", OSM + "9-4-strategic-objectives-and-levels-of-strategy", D)
M66 = S("OpenStax, Principles of Management, 6.6 Strategies for Expanding Globally", OSM + "6-6-strategies-for-expanding-globally", D)
M172 = S("OpenStax, Principles of Management, 17.2 The Planning Process", OSM + "17-2-the-planning-process", D)
M174 = S("OpenStax, Principles of Management, 17.4 Goals or Outcome Statements", OSM + "17-4-goals-or-outcome-statements", D)
M177 = S("OpenStax, Principles of Management, 17.7 Management by Objectives", OSM + "17-7-management-by-objectives-a-planning-and-control-technique", D)

LESSONS = [
    L(1, "Planowanie: misja, wizja, cele i zarządzanie przez cele",
      "Rozumieć hierarchię planów od wizji i misji do celów operacyjnych, formułować cele SMART, stosować zarządzanie przez cele (MBO), wyjątki i partycypację oraz planowanie scenariuszowe.",
      ["Planowanie", "Misja i wizja", "Cele SMART", "Zarządzanie przez cele (MBO)", "Zarządzanie przez wyjątki i przez partycypację", "Planowanie scenariuszowe"],
      [M92, M172, M174, M177],
      explain=[
          K("Wizja i misja",
            "Wizja opisuje pożądany obraz organizacji w przyszłości („dokąd zmierzamy”), misja – sens istnienia i sposób działania („po co istniejemy, dla kogo, czym się wyróżniamy”). Z misji wynikają cele strategiczne (długoterminowe), taktyczne (średnioterminowe dla działów) i operacyjne (bieżące zadania)."),
          K("Cele SMART",
            "Dobry cel jest: Specific (konkretny), Measurable (mierzalny), Achievable/Ambitious (osiągalny, ale ambitny), Relevant (istotny) i Time-bound (określony w czasie). Np. „zwiększyć sprzedaż online o 15% do 31 grudnia 2027 r.” zamiast „poprawić sprzedaż”."),
          W("Który cel spełnia kryteria SMART?",
            "Obniżyć koszty logistyki o 8% do końca 2027 r.", "Być lepszym od konkurencji", "Poprawić jakość",
            why="Jest konkretny, mierzalny i określony w czasie."),
          K("MBO, wyjątki, partycypacja",
            "Zarządzanie przez cele (P. Drucker, 1954): przełożony i pracownik wspólnie ustalają cele, a ocena opiera się na ich realizacji. Zarządzanie przez wyjątki: kierownik zajmuje się tylko istotnymi odchyleniami od normy, resztę zostawia podwładnym. Zarządzanie przez partycypację: pracownicy uczestniczą w podejmowaniu decyzji, co zwiększa zaangażowanie."),
          K("Planowanie scenariuszowe",
            "W niepewnym otoczeniu zamiast jednej prognozy tworzy się kilka spójnych scenariuszy przyszłości (np. optymistyczny, bazowy, pesymistyczny) i plan działań dla każdego. Słynny przykład: Shell w latach 70. przygotował się w ten sposób na kryzys naftowy."),
          PF("Misja mówi, po co organizacja istnieje, a wizja – jaką chce się stać w przyszłości.", True,
             why="To podstawowe rozróżnienie tych pojęć."),
      ],
      mech=[
          LN("Ułóż hierarchię planowania od ogółu do szczegółu.",
             ["Wizja organizacji", "Misja", "Cele strategiczne", "Plany taktyczne działów", "Zadania operacyjne pracowników"],
             why="Każdy poziom wynika z wyższego."),
          KT("Która litera SMART jest naruszona?",
             {"Specific / Measurable": ["„Poprawić obsługę klienta”", "„Działać lepiej”"],
              "Achievable": ["Zwiększyć udział w rynku z 2% do 90% w rok"],
              "Time-bound": ["Zmniejszyć reklamacje o 20% – kiedyś", "Wejść na rynek niemiecki bez terminu"]},
             why="Każdy element SMART chroni przed innym błędem."),
          W("Kierownik dostaje raport tylko wtedy, gdy koszty przekroczą budżet o ponad 5%. Jaka to metoda?",
            "Zarządzanie przez wyjątki", "Zarządzanie przez cele", "Planowanie scenariuszowe",
            why="Reaguje tylko na istotne odchylenia."),
          W("W MBO cele pracownika są:",
            "Ustalane wspólnie z przełożonym i podstawą oceny", "Narzucane bez rozmowy", "Tajne",
            why="Wspólne ustalanie celów zwiększa zaangażowanie."),
          M("Kiedy planowanie scenariuszowe jest szczególnie przydatne?",
            ["Przy wysokiej niepewności otoczenia", "Przy długim horyzoncie inwestycji", "Gdy możliwe są skokowe zmiany (np. kryzys energetyczny)", "Gdy otoczenie jest całkowicie przewidywalne"], [0, 1, 2],
            why="W przewidywalnym otoczeniu wystarczy jedna prognoza."),
          PF("Zarządzanie przez partycypację zwykle zwiększa akceptację decyzji przez pracowników.", True,
             why="Ludzie chętniej realizują decyzje, które współtworzyli."),
      ],
      calc=[
          LB("Cel: sprzedaż 1 200 tys. zł, wykonanie 1 080 tys. zł. Ile wynosi stopień realizacji celu (%)?",
             90, "1080/1200*100", ["1 080 / 1 200 = 90%"], unit="%"),
          LB("Cel roczny 15% wzrostu sprzedaży z poziomu 4 mln zł. Jaka ma być sprzedaż docelowa (mln zł)?",
             4.6, "4*1.15", ["4 · 1,15 = 4,6 mln zł"], unit="mln zł", tol=0.01),
          LB("Zarządzanie przez wyjątki: próg 5% od budżetu 200 000 zł. Od jakiej kwoty kosztów kierownik dostaje alert (zł)?",
             210000, "200000*1.05", ["200 000 · 1,05 = 210 000 zł"], unit="zł"),
          LB("Scenariusze zysku: pesymistyczny 2 mln (p = 0,2), bazowy 5 mln (p = 0,6), optymistyczny 8 mln (p = 0,2). Ile wynosi wartość oczekiwana (mln zł)?",
             5, "0.2*2+0.6*5+0.2*8", ["0,4 + 3 + 1,6 = 5 mln zł"], unit="mln zł"),
          LB("Pracownik w MBO miał 4 cele o wagach 40/30/20/10% i zrealizował je w 100%, 80%, 50% i 100%. Ile wynosi wynik ważony (%)?",
             84, "0.4*100+0.3*80+0.2*50+0.1*100", ["40 + 24 + 10 + 10 = 84%"], unit="%"),
          LB("Wzrost 15% rocznie przez 3 lata. Ile razy wzrośnie sprzedaż (2 miejsca)?",
             1.52, "1.15**3", ["1,15³ ≈ 1,52"], unit="razy", tol=0.01),
      ],
      case=[
          PR("Sieć kawiarni ma misję „Dobra kawa i miejsce spotkań dla sąsiadów”. Zarząd stawia cele: „zwiększyć liczbę klientów” i „otworzyć dużo nowych lokali”.",
             W("Co jest nie tak z celami?",
               "Nie są SMART – brak liczb i terminów", "Są zbyt konkretne", "Są sprzeczne z misją",
               why="Nie da się ich zmierzyć ani rozliczyć w czasie."),
             W("Jak poprawić pierwszy cel?",
               "Zwiększyć średnią liczbę klientów dziennie o 12% do końca 2027 r.", "Mieć więcej klientów", "Być najlepszą kawiarnią",
               why="Cel ma liczbę i termin."),
             PF("Cele powinny wynikać z misji firmy.", True,
                why="Misja wyznacza kierunek dla celów."),
          ),
          PR("Producent nawozów planuje inwestycję na 10 lat. Cena gazu (głównego surowca) może się w tym czasie zmieniać bardzo silnie z powodów politycznych.",
             W("Jaką metodę planowania zastosować?",
               "Planowanie scenariuszowe", "Jedną prognozę bazową", "Brak planowania",
               why="Wysoka niepewność i długi horyzont."),
             W("Ile scenariuszy zwykle się tworzy?",
               "Kilka (np. 3–4) spójnych scenariuszy", "Jeden", "Kilkaset",
               why="Kilka wyraźnie różnych scenariuszy ułatwia analizę."),
             PF("Scenariusze nie są prognozami – mają przygotować firmę na różne możliwe przyszłości.", True,
                why="Ich celem jest elastyczność decyzji."),
          ),
      ]),

    L(2, "Analiza strategiczna: SWOT, pięć sił, łańcuch wartości",
      "Przeprowadzać analizę SWOT, oceniać atrakcyjność sektora modelem pięciu sił M. Portera, analizować łańcuch wartości i kompetencje kluczowe jako źródła przewagi konkurencyjnej.",
      ["Zarządzanie strategiczne i analiza strategiczna", "Strategia", "Analiza SWOT", "Pięć sił Portera", "Łańcuch wartości (M. Porter)", "Kompetencje wyróżniające (kluczowe)", "Przewaga konkurencyjna i konkurencyjność"],
      [M82, M84, M85, M91],
      explain=[
          K("Zarządzanie strategiczne",
            "Proces: analiza otoczenia i zasobów → sformułowanie strategii (jak osiągnąć przewagę) → wdrożenie → kontrola i korekta. Strategia to długookresowy plan wykorzystania zasobów i dopasowania do otoczenia, by osiągnąć cele i przewagę nad konkurentami."),
          K("SWOT",
            "Analiza mocnych (Strengths) i słabych stron (Weaknesses) – czynników wewnętrznych – oraz szans (Opportunities) i zagrożeń (Threats) – czynników zewnętrznych. Strategie: S–O (wykorzystaj mocne strony do szans), W–O (napraw słabości, by skorzystać z szans), S–T (mocnymi stronami ogranicz zagrożenia), W–T (defensywa)."),
          W("Rosnący popyt na samochody elektryczne to dla producenta baterii:",
            "Szansa (czynnik zewnętrzny)", "Mocna strona", "Słaba strona",
            why="To zjawisko w otoczeniu, nie cecha firmy."),
          K("Pięć sił Portera",
            "Atrakcyjność sektora zależy od: rywalizacji między obecnymi konkurentami, groźby wejścia nowych firm (bariery wejścia), siły przetargowej dostawców, siły przetargowej nabywców i groźby substytutów. Im silniejsze siły, tym niższa przeciętna rentowność sektora."),
          K("Łańcuch wartości i kompetencje kluczowe",
            "Porter dzieli działalność firmy na działania podstawowe (logistyka wewnętrzna, produkcja, logistyka zewnętrzna, marketing i sprzedaż, serwis) i pomocnicze (infrastruktura, zarządzanie zasobami ludzkimi, rozwój technologii, zaopatrzenie). Przewaga powstaje tam, gdzie firma tworzy więcej wartości lub ponosi niższe koszty. Kompetencje kluczowe (Prahalad i Hamel) to unikalne umiejętności, trudne do skopiowania, dające dostęp do wielu rynków."),
          PF("W analizie SWOT mocne i słabe strony dotyczą wnętrza firmy.", True,
             why="Szanse i zagrożenia pochodzą z otoczenia."),
      ],
      mech=[
          KT("Element SWOT",
             {"Mocna strona": ["Rozpoznawalna marka", "Własna technologia produkcji"],
              "Słaba strona": ["Przestarzały park maszynowy", "Wysokie zadłużenie"],
              "Szansa": ["Nowe dotacje UE na innowacje", "Otwarcie rynku eksportowego"],
              "Zagrożenie": ["Wejście taniej konkurencji z Azji", "Zaostrzenie regulacji"]},
             why="S i W – wnętrze, O i T – otoczenie."),
          KT("Która siła Portera?",
             {"Groźba nowych wejść": ["Niskie koszty otwarcia sklepu internetowego"],
              "Siła dostawców": ["Jeden dostawca kluczowego komponentu"],
              "Siła nabywców": ["Kilka dużych sieci handlowych kupuje większość produkcji"],
              "Groźba substytutów": ["Wideokonferencje zastępujące podróże służbowe"],
              "Rywalizacja w sektorze": ["Wojna cenowa między operatorami komórkowymi"]},
             why="Każda siła ogranicza rentowność sektora inaczej."),
          LN("Ułóż kroki zarządzania strategicznego.",
             ["Analiza otoczenia i zasobów firmy", "Określenie misji i celów", "Wybór strategii", "Wdrożenie strategii", "Kontrola wyników i korekta strategii"],
             why="To cykl, a nie jednorazowe zadanie."),
          W("Wysokie bariery wejścia (kosztowne licencje i infrastruktura) w sektorze oznaczają:",
            "Słabą groźbę nowych konkurentów i wyższą rentowność obecnych firm", "Silną groźbę wejścia", "Brak wpływu",
            why="Trudno wejść, więc konkurencja jest mniejsza."),
          M("Które działania w łańcuchu wartości Portera są podstawowe?",
            ["Produkcja", "Marketing i sprzedaż", "Serwis posprzedażowy", "Zarządzanie zasobami ludzkimi"], [0, 1, 2],
            why="Zarządzanie zasobami ludzkimi to działanie pomocnicze."),
          PF("Kompetencja kluczowa powinna być trudna do skopiowania przez konkurentów.", True,
             why="Inaczej nie daje trwałej przewagi."),
      ],
      calc=[
          LB("Ocena SWOT: mocne strony 3,8 pkt, słabe 2,4 pkt (wagi ważone). Ile wynosi przewaga mocnych stron?",
             1.4, "3.8-2.4", ["3,8 − 2,4 = 1,4"], unit="pkt", tol=0.01),
          LB("Pięć sił oceniono (1 = słaba, 5 = silna): 4, 2, 3, 5, 3. Ile wynosi średnia siła?",
             3.4, "(4+2+3+5+3)/5", ["17 / 5 = 3,4"], unit="pkt", tol=0.01),
          LB("Trzech największych nabywców kupuje 60% produkcji o wartości 50 mln zł. Ile kupują (mln zł)?",
             30, "50*0.6", ["50 · 60% = 30 mln zł"], unit="mln zł"),
          LB("Marża: cena 100 zł, koszty w łańcuchu wartości 82 zł. Ile wynosi marża (zł)?",
             18, "100-82", ["100 − 82 = 18 zł"], unit="zł"),
          LB("Firma obniża koszty logistyki z 15 zł do 11 zł na produkt przy sprzedaży 200 000 szt. Ile oszczędza (zł)?",
             800000, "(15-11)*200000", ["4 · 200 000 = 800 000 zł"], unit="zł"),
          LB("Rentowność sektora A 18%, sektora B 6%. Ile razy wyższa jest w A?",
             3, "18/6", ["18 / 6 = 3"], unit="razy"),
      ],
      case=[
          PR("Rodzinny producent ekologicznych soków: ma wierną bazę klientów i certyfikaty bio (mocne strony), ale małą skalę i wysokie koszty (słabości). Rośnie popyt na zdrową żywność, a sieci dyskontów wprowadzają tańsze soki pod własną marką.",
             W("Które działanie to strategia S–O?",
               "Wykorzystać markę bio, by wejść do sklepów ze zdrową żywnością", "Obniżyć ceny do poziomu dyskontów", "Wycofać się z rynku",
               why="Mocna strona + szansa rynkowa."),
             W("Którą siłę Portera reprezentują dyskonty z marką własną?",
               "Siłę nabywców i rywalizację", "Groźbę substytutów", "Siłę dostawców",
               why="Duże sieci negocjują ceny i same konkurują produktami."),
             PF("Konkurowanie ceną z dyskontami byłoby ryzykowne przy wysokich kosztach firmy.", True,
                why="Słabość kosztowa uniemożliwia wygranie wojny cenowej."),
          ),
          PR("Linie lotnicze mają niską rentowność: silna rywalizacja, nabywcy porównują ceny online, dostawców samolotów jest dwóch (Airbus, Boeing), a na krótkich trasach konkurują koleje dużych prędkości.",
             W("Która siła wynika z istnienia tylko dwóch producentów samolotów?",
               "Silna pozycja dostawców", "Groźba substytutów", "Siła nabywców",
               why="Mała liczba dostawców wzmacnia ich siłę."),
             W("Czym są koleje dużych prędkości dla linii lotniczych?",
               "Substytutem", "Dostawcą", "Nowym konkurentem w tym samym sektorze",
               why="Zaspokajają tę samą potrzebę inną technologią."),
             PF("Model pięciu sił wyjaśnia, dlaczego cały sektor może być mało rentowny mimo dobrego zarządzania firm.", True,
                why="Rentowność zależy od struktury sektora."),
          ),
      ]),

    L(3, "Strategie konkurencji i strategie cenowe",
      "Rozróżniać strategie konkurencji Portera, typologię Milesa i Snowa, strategie według pozycji rynkowej Kotlera i strategię błękitnego oceanu, a także dobierać strategię cenową do sytuacji rynkowej.",
      ["Strategie konkurencji Portera", "Typologia strategii Milesa i Snowa", "Strategie konkurencyjne według pozycji rynkowej (Ph. Kotler)", "Strategia błękitnego oceanu", "Strategie cenowe"],
      [M86, M87, M94],
      explain=[
          K("Trzy strategie Portera",
            "Przywództwo kosztowe – najniższe koszty w sektorze, dzięki skali, efektywności i standaryzacji (np. tanie linie lotnicze). Zróżnicowanie – unikalny produkt, za który klienci płacą więcej (marka, jakość, design). Koncentracja (niszy) – obsługa wąskiego segmentu kosztowo lub przez zróżnicowanie. Firma „utknięta pośrodku” bez wyraźnej strategii zwykle przegrywa."),
          K("Miles i Snow oraz Kotler",
            "Miles i Snow: poszukiwacz (prospector – innowacje, nowe rynki), obrońca (defender – efektywność w wąskiej domenie), analizator (łączy oba, szybko naśladuje sprawdzone innowacje), reaktor (brak spójnej strategii). Kotler według pozycji rynkowej: lider (rozwija rynek, broni udziału), pretendent (atakuje lidera), naśladowca (kopiuje i unika konfrontacji), specjalista niszowy (obsługuje niszę)."),
          W("Tania linia lotnicza z jednym typem samolotu, bez darmowych posiłków i z wysokim wykorzystaniem floty stosuje strategię:",
            "Przywództwa kosztowego", "Zróżnicowania", "Reaktora",
            why="Każdy element obniża koszty jednostkowe."),
          K("Błękitny ocean",
            "W. Chan Kim i Renée Mauborgne (2005): zamiast walczyć w „czerwonym oceanie” istniejących rynków, twórz nową przestrzeń rynkową, łącząc niższe koszty i nową wartość dla klienta (eliminuj, ograniczaj, podnoś, twórz). Przykład: Cirque du Soleil połączył cyrk z teatrem, rezygnując z drogich zwierząt i gwiazd areny."),
          K("Strategie cenowe",
            "Penetracji – niska cena na wejściu, by szybko zdobyć udział w rynku. Zbierania śmietanki – wysoka cena na start dla najmniej wrażliwych na cenę, potem obniżki (nowe smartfony). Prestiżowa – wysoka cena jako sygnał jakości. Psychologiczna – 9,99 zł zamiast 10 zł. Ceny dynamiczne – zmienne zależnie od popytu (bilety lotnicze)."),
          PF("Strategia zbierania śmietanki zakłada wysoką cenę na początku cyklu życia produktu.", True,
             why="Firma najpierw sprzedaje klientom gotowym zapłacić najwięcej."),
      ],
      mech=[
          KT("Strategia Portera",
             {"Przywództwo kosztowe": ["Dyskont spożywczy z ograniczonym asortymentem", "Masowa produkcja standardowych mebli"],
              "Zróżnicowanie": ["Luksusowa marka zegarków", "Producent samochodów premium"],
              "Koncentracja": ["Sklep z odzieżą dla wspinaczy", "Producent wózków dla osób niepełnosprawnych"]},
             why="Strategie różnią się źródłem przewagi i zakresem rynku."),
          KT("Pozycja rynkowa według Kotlera",
             {"Lider": ["Największy udział w rynku, rozwija cały rynek"],
              "Pretendent": ["Druga firma atakuje lidera agresywną promocją"],
              "Naśladowca": ["Kopiuje produkty lidera po niższej cenie, unikając konfrontacji"],
              "Specjalista niszowy": ["Obsługuje wąską grupę klientów o szczególnych potrzebach"]},
             why="Strategia zależy od pozycji firmy na rynku."),
          LN("Ułóż tworzenie błękitnego oceanu metodą czterech działań.",
             ["Eliminuj czynniki, które branża uznaje za oczywiste, a klienci nie cenią", "Ograniczaj czynniki rozbudowane ponad potrzeby", "Podnoś czynniki ważne dla klientów", "Twórz nowe czynniki, których branża nie oferowała", "Powstaje nowa krzywa wartości i nowa przestrzeń rynkowa"],
             why="Siatka ERRC (eliminate, reduce, raise, create)."),
          W("Nowy producent wchodzi na rynek napojów z ceną o 20% niższą od konkurencji, by szybko zdobyć klientów. Jaka to strategia cenowa?",
            "Penetracji rynku", "Zbierania śmietanki", "Prestiżowa",
            why="Niska cena wejścia służy zdobyciu udziału."),
          M("Jakie cechy ma poszukiwacz w typologii Milesa i Snowa?",
            ["Ciągłe szukanie nowych produktów i rynków", "Akceptacja ryzyka", "Elastyczna struktura", "Koncentracja wyłącznie na obniżaniu kosztów w wąskiej domenie"], [0, 1, 2],
            why="To cecha obrońcy."),
          PF("Firma „utknięta pośrodku” nie ma ani najniższych kosztów, ani wyraźnego wyróżnika.", True,
             why="Porter uważał to za pozycję o słabych wynikach."),
      ],
      calc=[
          LB("Cena konkurencji 50 zł, strategia penetracji – cena niższa o 20%. Ile wynosi cena (zł)?",
             40, "50*0.8", ["50 · 0,8 = 40 zł"], unit="zł"),
          LB("Smartfon na start 4 000 zł, po roku obniżka o 25%. Ile kosztuje (zł)?",
             3000, "4000*0.75", ["4 000 · 0,75 = 3 000 zł"], unit="zł"),
          LB("Przywództwo kosztowe: koszt jednostkowy 30 zł vs 36 zł u konkurenta. O ile procent niższy jest koszt?",
             16.67, "(1-30/36)*100", ["30 / 36 ≈ 0,833 → 16,67% niżej"], unit="%", tol=0.02),
          LB("Marka premium sprzedaje 10 000 szt. po 300 zł, koszt 180 zł. Ile wynosi zysk (zł)?",
             1200000, "10000*(300-180)", ["10 000 · 120 = 1 200 000 zł"], unit="zł"),
          LB("Cena psychologiczna 9,99 zł zamiast 10 zł przy 50 000 szt. O ile niższy jest przychód (zł)?",
             500, "50000*0.01", ["50 000 · 0,01 = 500 zł"], unit="zł"),
          LB("Udział lidera 40%, pretendenta 25%. O ile pkt proc. pretendent ustępuje liderowi?",
             15, "40-25", ["40 − 25 = 15 pkt proc."], unit="pkt proc."),
      ],
      case=[
          PR("Sieć siłowni działa na zatłoczonym rynku. Nowa firma otwiera kluby bez basenów i saun, z automatyczną obsługą i niskim abonamentem, czynne całą dobę, z nowoczesną aplikacją treningową.",
             W("Jaką strategię stosuje nowa firma według Kima i Mauborgne?",
               "Błękitnego oceanu – eliminuje i ogranicza jedne cechy, a tworzy nowe", "Klasyczne zróżnicowanie premium", "Naśladowcy",
               why="Łączy niższe koszty z nową wartością (24 h, aplikacja)."),
             W("Które działanie to „eliminowanie”?",
               "Rezygnacja z basenów i saun", "Dodanie aplikacji treningowej", "Całodobowe otwarcie",
               why="Usunięto elementy kosztowne i nie dla wszystkich ważne."),
             PF("Nowa firma może przyciągnąć osoby, które wcześniej w ogóle nie chodziły na siłownię.", True,
                why="Błękitny ocean tworzy nowych klientów, a nie tylko odbiera ich konkurentom."),
          ),
          PR("Producent konsol wprowadza nowy model po 3 000 zł. Po roku obniża cenę do 2 400 zł, a po dwóch latach do 1 800 zł. Konkurent wchodzi od razu z ceną 2 000 zł.",
             W("Jaką strategię cenową stosuje pierwszy producent?",
               "Zbierania śmietanki", "Penetracji", "Prestiżową stałą",
               why="Wysoka cena na start, potem obniżki."),
             W("Jaką strategię stosuje konkurent?",
               "Penetracji rynku", "Zbierania śmietanki", "Zróżnicowania premium",
               why="Niska cena wejścia, by zdobyć udział."),
             PF("Zbieranie śmietanki działa najlepiej, gdy produkt jest nowy i wyjątkowy, a część klientów mało wrażliwa na cenę.", True,
                why="Wtedy pierwsi nabywcy zapłacą wyższą cenę."),
          ),
      ]),

    L(4, "Portfel produktów i kierunki rozwoju: BCG, GE, ADL, Ansoff",
      "Analizować portfel produktów macierzami BCG, GE (McKinseya) i ADL, wybierać kierunek rozwoju z macierzy Ansoffa (w tym dywersyfikację i integrację) oraz rozumieć strategie wobec produktów w schyłku i dyfuzję innowacji.",
      ["Macierz BCG", "Macierz GE (McKinseya)", "Macierz ADL (Arthur D. Little)", "Macierz Ansoffa (strategie rozwoju)", "Dywersyfikacja", "Integracja pionowa i pozioma", "Strategie wobec produktu w schyłku", "Dyfuzja innowacji"],
      [M94, M87],
      explain=[
          K("Macierz BCG",
            "Osie: tempo wzrostu rynku i względny udział w rynku. Gwiazdy (duży udział, szybki wzrost) – inwestuj. Dojne krowy (duży udział, wolny wzrost) – generują gotówkę na inne produkty. Znaki zapytania (mały udział, szybki wzrost) – inwestuj selektywnie lub wycofaj. Psy (mały udział, wolny wzrost) – zwykle wycofuj.",
            w="względny udział = udział firmy / udział największego konkurenta"),
          K("GE i ADL",
            "Macierz GE (McKinseya, 3×3): atrakcyjność sektora × pozycja konkurencyjna, oceniane wieloma czynnikami – bogatsza niż BCG. Macierz ADL: faza cyklu życia sektora (zarodkowa, wzrostu, dojrzałości, starzenia) × pozycja konkurencyjna (od dominującej do słabej)."),
          W("Produkt ma duży udział na wolno rosnącym rynku. Jak go nazywa macierz BCG?",
            "Dojna krowa", "Gwiazda", "Pies",
            why="Generuje gotówkę przy małych potrzebach inwestycyjnych."),
          K("Macierz Ansoffa",
            "Penetracja rynku (obecne produkty, obecne rynki – np. promocje), rozwój rynku (obecne produkty, nowe rynki – eksport), rozwój produktu (nowe produkty, obecne rynki), dywersyfikacja (nowe produkty, nowe rynki – najbardziej ryzykowna). Dywersyfikacja może być pokrewna lub niepokrewna (konglomerat). Integracja pionowa obejmuje kolejne etapy łańcucha (w tył – dostawcy, w przód – dystrybucja); pozioma – przejmowanie firm z tego samego szczebla."),
          K("Schyłek i dyfuzja innowacji",
            "Wobec produktu w schyłku firma może: żniwować (ograniczać koszty i zbierać gotówkę), wycofać się, utrzymać pozycję lidera w kurczącym się rynku lub skupić się na niszy. E. Rogers opisał dyfuzję innowacji: innowatorzy (2,5%), wcześni użytkownicy (13,5%), wczesna większość (34%), późna większość (34%), maruderzy (16%)."),
          PF("Dywersyfikacja niepokrewna to najbardziej ryzykowny kierunek w macierzy Ansoffa.", True,
             why="Firma wchodzi z nowym produktem na nowy rynek bez powiązań."),
      ],
      mech=[
          KT("Pole macierzy BCG",
             {"Gwiazda": ["Lider na szybko rosnącym rynku hulajnóg elektrycznych"],
              "Dojna krowa": ["Lider rynku proszków do prania w dojrzałym segmencie"],
              "Znak zapytania": ["Nowy napój energetyczny z 2% udziału na rosnącym rynku"],
              "Pies": ["Mały producent odtwarzaczy DVD"]},
             why="Pozycja zależy od udziału i wzrostu rynku."),
          KT("Strategia z macierzy Ansoffa",
             {"Penetracja rynku": ["Program lojalnościowy dla obecnych klientów"],
              "Rozwój rynku": ["Sprzedaż tych samych mebli w Niemczech"],
              "Rozwój produktu": ["Nowa linia jogurtów bez laktozy dla obecnych klientów"],
              "Dywersyfikacja": ["Producent mebli otwiera hotele"]},
             why="Kryteria: produkt obecny/nowy × rynek obecny/nowy."),
          LN("Ułóż przepływ gotówki w zrównoważonym portfelu BCG.",
             ["Dojne krowy generują nadwyżki gotówki", "Gotówka trafia do wybranych znaków zapytania", "Udane znaki zapytania stają się gwiazdami", "Gdy rynek dojrzewa, gwiazdy stają się dojnymi krowami", "Psy są wycofywane, uwalniając zasoby"],
             why="Portfel ma zapewniać i finansowanie, i przyszły wzrost."),
          W("Producent samochodów kupuje fabrykę akumulatorów, która go zaopatruje. Jaka to integracja?",
            "Pionowa wstecz", "Pozioma", "Pionowa w przód",
            why="Przejęcie dostawcy to integracja w kierunku źródeł zaopatrzenia."),
          M("Jakie strategie wobec produktu w schyłku są możliwe?",
            ["Żniwowanie – ograniczenie inwestycji i zbieranie gotówki", "Szybkie wycofanie", "Koncentracja na opłacalnej niszy", "Zawsze podwojenie inwestycji"], [0, 1, 2],
            why="Inwestowanie w kurczący się rynek rzadko się opłaca."),
          PF("Według Rogersa późna większość to ok. 34% użytkowników innowacji.", True,
             why="Tyle samo co wczesna większość."),
      ],
      calc=[
          LB("Udział firmy w rynku 30%, największego konkurenta 20%. Ile wynosi względny udział w rynku?",
             1.5, "30/20", ["30 / 20 = 1,5 – firma jest liderem"], unit="", tol=0.01),
          LB("Rynek rośnie z 400 do 460 mln zł rocznie. Ile wynosi tempo wzrostu (%)?",
             15, "(460/400-1)*100", ["460 / 400 − 1 = 15%"], unit="%"),
          LB("Według Rogersa ile procent rynku stanowią łącznie innowatorzy i wcześni użytkownicy?",
             16, "2.5+13.5", ["2,5 + 13,5 = 16%"], unit="%"),
          LB("Rynek potencjalny 2 mln osób. Ilu stanowi wczesna większość (34%)?",
             680000, "2000000*0.34", ["2 000 000 · 34% = 680 000"], unit="osób"),
          LB("Ocena GE: atrakcyjność sektora – czynniki 4, 3, 5 o wagach 0,5; 0,3; 0,2. Ile wynosi wynik?",
             3.9, "0.5*4+0.3*3+0.2*5", ["2 + 0,9 + 1 = 3,9"], unit="pkt", tol=0.01),
          LB("Dojna krowa generuje 12 mln zł gotówki, a dwa znaki zapytania potrzebują po 4 mln zł. Ile zostaje na inne cele (mln zł)?",
             4, "12-2*4", ["12 − 8 = 4 mln zł"], unit="mln zł"),
      ],
      case=[
          PR("Producent słodyczy ma: czekolady – 35% udziału na rynku rosnącym 1% rocznie; batony proteinowe – 4% udziału na rynku rosnącym 18% rocznie; cukierki twarde – 3% udziału na rynku malejącym.",
             W("Jak sklasyfikować czekolady w BCG?",
               "Dojna krowa", "Gwiazda", "Znak zapytania",
               why="Duży udział, wolny wzrost."),
             W("Co zalecić dla batonów proteinowych?",
               "Selektywnie inwestować, by zdobyć udział – to znak zapytania", "Natychmiast wycofać", "Żniwować",
               why="Szybko rosnący rynek, ale mały udział."),
             PF("Cukierki twarde to „pies” – kandydat do wycofania lub żniwowania.", True,
                why="Mały udział na niekorzystnym rynku."),
          ),
          PR("Polska firma meblarska rozważa trzy opcje: (A) agresywną promocję w Polsce, (B) sprzedaż mebli w Skandynawii, (C) uruchomienie sieci hoteli.",
             W("Którą strategię Ansoffa reprezentuje B?",
               "Rozwój rynku", "Penetrację rynku", "Dywersyfikację",
               why="Obecny produkt, nowy rynek."),
             W("Która opcja jest najbardziej ryzykowna?",
               "C – dywersyfikacja", "A – penetracja", "B – rozwój rynku",
               why="Nowy produkt i nowy rynek bez doświadczenia firmy."),
             PF("Opcja A to penetracja rynku.", True,
                why="Obecne produkty na obecnym rynku."),
          ),
      ]),

    L(5, "Rozwój zewnętrzny i międzynarodowy",
      "Rozumieć fuzje i przejęcia, alianse i joint venture, outsourcing i benchmarking oraz motywy i formy internacjonalizacji przedsiębiorstw (paradygmat OLI J. Dunninga, model uppsalski), w tym ekspansję polskich firm i lukę konkurencyjną.",
      ["Fuzja i przejęcie (M&A)", "Alians strategiczny i joint venture", "Outsourcing", "Benchmarking", "Biznes międzynarodowy i paradygmat eklektyczny (OLI)", "Przedsiębiorczość międzynarodowa i modele internacjonalizacji", "Inwestycje zagraniczne wychodzące (ekspansja zagraniczna polskich firm)", "Konkurencyjność międzynarodowa przedsiębiorstwa i luka konkurencyjna"],
      [M66, M86],
      explain=[
          K("Rozwój zewnętrzny",
            "Fuzja łączy firmy w jedną; przejęcie to zakup kontroli nad inną firmą – szybki dostęp do rynków, technologii, klientów (synergie), ale ryzyko przepłacenia i zderzenia kultur. Alians strategiczny to współpraca niezależnych firm (np. wspólna dystrybucja), joint venture – wspólnie utworzona spółka. Outsourcing – przekazanie funkcji zewnętrznemu dostawcy (np. IT, księgowość), by skupić się na kompetencjach kluczowych."),
          K("Benchmarking",
            "Systematyczne porównywanie procesów, produktów i wyników z najlepszymi (konkurentami lub liderami z innych branż) i przenoszenie dobrych praktyk. Np. firma kurierska może uczyć się szybkiej obsługi od linii lotniczych."),
          W("Bank przekazuje obsługę infolinii zewnętrznej firmie. Co to jest?",
            "Outsourcing", "Joint venture", "Fuzja",
            why="Funkcję realizuje zewnętrzny dostawca."),
          K("Paradygmat OLI i internacjonalizacja",
            "J. Dunning: firma inwestuje za granicą (BIZ), gdy ma przewagi Ownership (własna technologia, marka), Location (korzyści lokalizacji – rynek, koszty, zasoby) i Internalization (opłaca się działać samemu zamiast sprzedawać licencję). Model uppsalski: firmy internacjonalizują się stopniowo – od eksportu przez przedstawicielstwo do własnej produkcji – i najpierw na rynkach bliskich kulturowo. Firmy „born global” wchodzą na rynki zagraniczne od początku."),
          K("Polskie firmy za granicą i luka konkurencyjna",
            "Polskie firmy coraz częściej inwestują za granicą (np. Orlen kupił czeski Unipetrol w 2005 r. i litewską rafinerię w Możejkach w 2006 r.; sieci odzieżowe i firmy IT otwierają oddziały w Europie). Luka konkurencyjna to różnica między pozycją firmy a pozycją wymaganą do skutecznej rywalizacji na rynku międzynarodowym – np. w zakresie skali, marki, technologii."),
          PF("Według modelu uppsalskiego firmy zwykle zaczynają ekspansję od rynków bliskich kulturowo.", True,
             why="Mniejszy „dystans psychiczny” zmniejsza ryzyko."),
      ],
      mech=[
          KT("Forma rozwoju zewnętrznego",
             {"Przejęcie": ["Kupno 100% akcji konkurenta"],
              "Joint venture": ["Dwie firmy zakładają wspólną spółkę produkującą baterie"],
              "Alians strategiczny": ["Linie lotnicze współdzielą połączenia w sojuszu"],
              "Outsourcing": ["Zlecenie księgowości biuru rachunkowemu", "Przeniesienie produkcji do podwykonawcy"]},
             why="Formy różnią się stopniem integracji i kontroli."),
          LN("Ułóż etapy internacjonalizacji według modelu uppsalskiego.",
             ["Sporadyczny eksport", "Regularny eksport przez pośredników", "Własne przedstawicielstwo handlowe", "Własna filia sprzedażowa", "Własna produkcja za granicą"],
             why="Zaangażowanie rośnie wraz z wiedzą o rynku."),
          W("Firma posiada unikalną technologię, rynek docelowy ma niskie koszty i dużych klientów, a licencjonowanie groziłoby utratą know-how. Co według OLI zrobi?",
            "Zainwestuje bezpośrednio za granicą", "Sprzeda licencję", "Zrezygnuje z ekspansji",
            why="Spełnione są przewagi O, L i I."),
          W("Jakie jest główne ryzyko przejęć?",
            "Przepłacenie i trudności integracji kultur", "Zbyt szybki wzrost synergii", "Brak ryzyka",
            why="Wiele przejęć nie przynosi oczekiwanych synergii."),
          M("Jakie korzyści daje outsourcing?",
            ["Skupienie na kompetencjach kluczowych", "Niższe koszty dzięki specjalizacji dostawcy", "Elastyczność kosztów", "Pełna kontrola nad każdym etapem procesu"], [0, 1, 2],
            why="Outsourcing oznacza częściową utratę kontroli."),
          PF("Benchmarking może dotyczyć firm z innych branż.", True,
             why="Dobre praktyki procesów są często uniwersalne."),
      ],
      calc=[
          LB("Firma A warta 400 mln zł przejmuje B wartą 150 mln zł; po połączeniu wartość 600 mln zł. Ile wynosi synergia (mln zł)?",
             50, "600-(400+150)", ["600 − 550 = 50 mln zł"], unit="mln zł"),
          LB("A zapłaciła za B 190 mln zł. Ile wynosi premia za kontrolę (mln zł)?",
             40, "190-150", ["190 − 150 = 40 mln zł"], unit="mln zł"),
          LB("Czy przejęcie stworzyło wartość dla akcjonariuszy A? Policz synergia − premia (mln zł).",
             10, "50-40", ["50 − 40 = 10 mln zł – tak, wartość wzrosła"], unit="mln zł"),
          LB("Koszt własnej księgowości 600 000 zł rocznie, outsourcing 420 000 zł. Ile wynosi oszczędność (%)?",
             30, "(600000-420000)/600000*100", ["180 000 / 600 000 = 30%"], unit="%"),
          LB("Benchmarking: czas obsługi zamówienia u nas 48 h, u lidera 18 h. O ile procent musimy skrócić czas, by dorównać?",
             62.5, "(48-18)/48*100", ["30 / 48 = 62,5%"], unit="%", tol=0.01),
          LB("Joint venture: kapitał 80 mln zł, partner polski wnosi 45%. Ile wnosi partner zagraniczny (mln zł)?",
             44, "80*0.55", ["80 · 55% = 44 mln zł"], unit="mln zł"),
      ],
      case=[
          PR("Polski producent okien sprzedaje w kraju i eksportuje do Niemiec przez dystrybutora. Rozważa otwarcie własnej fabryki w Niemczech albo udzielenie licencji niemieckiej firmie.",
             W("Który etap modelu uppsalskiego obecnie reprezentuje?",
               "Regularny eksport przez pośrednika", "Własna produkcja za granicą", "Brak eksportu",
               why="Sprzedaje przez dystrybutora."),
             W("Kiedy według OLI lepsza jest własna fabryka niż licencja?",
               "Gdy firma ma unikalną technologię, którą łatwo stracić przy licencji", "Gdy nie ma żadnej przewagi", "Gdy rynek jest bardzo mały",
               why="Przewaga internalizacji przemawia za własną inwestycją."),
             PF("Własna fabryka za granicą to bezpośrednia inwestycja zagraniczna (BIZ).", True,
                why="Firma obejmuje kontrolę nad aktywami za granicą."),
          ),
          PR("Dwie firmy farmaceutyczne – polska i koreańska – tworzą wspólną spółkę, by produkować leki biologiczne na rynek europejski. Polska wnosi dostęp do rynku i zakład, koreańska – technologię.",
             W("Jaka to forma współpracy?",
               "Joint venture", "Outsourcing", "Fuzja pozioma",
               why="Powstaje wspólna spółka z wkładami obu partnerów."),
             W("Jakie jest typowe ryzyko joint venture?",
               "Konflikty partnerów co do celów i podziału zysków", "Brak jakiejkolwiek współpracy", "Automatyczna utrata obu firm",
               why="Wspólne zarządzanie wymaga zgodności interesów."),
             PF("Joint venture pozwala podzielić ryzyko i połączyć komplementarne zasoby.", True,
                why="Każdy partner wnosi to, czego brakuje drugiemu."),
          ),
      ]),
]
