# -*- coding: utf-8 -*-
# Zrozumienie – Zarządzanie / Wzory
OSM = "https://openstax.org/books/principles-management/pages/"
OSK = "https://openstax.org/books/principles-marketing/pages/"
D = "2026-10-08"
M23 = S("OpenStax, Principles of Management, 2.3 Programmed and Nonprogrammed Decisions", OSM + "2-3-programmed-and-nonprogrammed-decisions", D)
M143 = S("OpenStax, Principles of Management, 14.3 Process Theories of Motivation", OSM + "14-3-process-theories-of-motivation", D)
M114 = S("OpenStax, Principles of Management, 11.4 Influencing Employee Performance and Motivation", OSM + "11-4-influencing-employee-performance-and-motivation", D)
M178 = S("OpenStax, Principles of Management, 17.8 The Control- and Involvement-Oriented Approaches to Planning and Controlling", OSM + "17-8-the-control-and-involvement-oriented-approaches-to-planning-and-controlling", D)
K16 = S("OpenStax, Principles of Marketing, 1.6 Customer Relationship Management (CRM)", OSK + "1-6-customer-relationship-management-crm", D)
K163 = S("OpenStax, Principles of Marketing, 16.3 Metrics Used to Evaluate the Success of Online Marketing", OSK + "16-3-metrics-used-to-evaluate-the-success-of-online-marketing", D)
LJIT = S("Lean Enterprise Institute, Lean Lexicon: Just-in-Time", "https://www.lean.org/lexicon-terms/just-in-time/", D)

LESSONS = [
    L(1, "Wzory zarządzania zapasami",
      "Obliczać ekonomiczną wielkość zamówienia, koszt całkowity zapasów, punkt ponownego zamówienia, zapas bezpieczeństwa i wskaźniki rotacji – i rozumieć, co oznaczają dla decyzji.",
      ["Zarządzanie zapasami"],
      [M23, LJIT],
      explain=[
          K("Koszty zapasów",
            "Koszt zamawiania (S) – stały za każde zamówienie: transport, obsługa, administracja. Koszt utrzymania (H) – za jednostkę na rok: kapitał zamrożony, magazyn, ubezpieczenie, starzenie. Większe partie = mniej zamówień, ale wyższy przeciętny zapas. Przeciętny zapas obrotowy = Q/2.",
            w="KC = (D/Q) · S + (Q/2) · H"),
          K("EOQ – model Wilsona",
            "Ekonomiczna wielkość zamówienia minimalizuje sumę kosztów zamawiania i utrzymania; w optimum oba koszty są równe. Założenia: stały i znany popyt, stały czas dostawy, brak rabatów ilościowych. EOQ rośnie z pierwiastkiem popytu – dwukrotny wzrost popytu zwiększa EOQ tylko ok. 1,41 raza.",
            w="EOQ = √(2DS / H)"),
          W("W optimum EOQ koszt zamawiania w skali roku jest:",
            "Równy kosztowi utrzymania zapasu", "Dwa razy wyższy niż koszt utrzymania", "Równy zeru",
            why="Suma kosztów jest najmniejsza, gdy oba składniki są równe."),
          K("Punkt ponownego zamówienia i zapas bezpieczeństwa",
            "ROP – poziom zapasu, przy którym składa się zamówienie: dzienny popyt × czas dostawy + zapas bezpieczeństwa. Zapas bezpieczeństwa chroni przed wahaniami popytu: ZB = z · σ · √L (z – współczynnik poziomu obsługi, np. 1,65 dla ok. 95%; σ – odchylenie dziennego popytu; L – czas dostawy w dniach).",
            w="ROP = d · L + ZB;  ZB = z · σ · √L"),
          K("Rotacja zapasów",
            "Rotacja (razy) = koszt sprzedanych towarów / przeciętny zapas; rotacja w dniach = 365 / rotacja w razach. Wyższa rotacja oznacza mniej kapitału zamrożonego, ale zbyt niski zapas grozi brakami. Analiza ABC: grupa A (ok. 20% pozycji, ok. 80% wartości) wymaga najściślejszej kontroli."),
          PF("Przy dwukrotnym wzroście popytu EOQ rośnie dwukrotnie.", False,
             why="Rośnie o √2 ≈ 1,41 raza."),
      ],
      mech=[
          KT("Co się stanie z EOQ?",
             {"EOQ rośnie": ["Rośnie roczny popyt", "Rośnie koszt jednego zamówienia"],
              "EOQ maleje": ["Rośnie koszt utrzymania jednostki", "Rosną stopy procentowe (droższy kapitał w zapasach)"]},
             why="D i S w liczniku, H w mianowniku."),
          LN("Ułóż obliczenie punktu ponownego zamówienia.",
             ["Ustal średni dzienny popyt", "Ustal czas dostawy w dniach", "Pomnóż popyt przez czas dostawy", "Oblicz zapas bezpieczeństwa", "Dodaj zapas bezpieczeństwa do popytu w czasie dostawy"],
             why="ROP = d · L + ZB."),
          W("Dostawca wydłuża czas dostawy z 4 do 9 dni. Co dzieje się z zapasem bezpieczeństwa przy tym samym z i σ?",
            "Rośnie o połowę (√9 / √4 = 1,5)", "Rośnie ponad dwa razy", "Nie zmienia się",
            why="ZB rośnie z pierwiastkiem czasu dostawy."),
          W("Rotacja zapasów spadła z 10 do 5 razy w roku. Co to oznacza?",
            "Towar leży w magazynie dwa razy dłużej", "Zapasy obracają się szybciej", "Koszty utrzymania zapasu spadły",
            why="Rotacja w dniach wzrosła z 36,5 do 73."),
          M("Jakie są założenia modelu EOQ?",
            ["Stały, znany popyt", "Stały czas dostawy", "Brak rabatów ilościowych", "Losowe ceny zakupu każdego dnia"], [0, 1, 2],
            why="Model zakłada przewidywalne warunki."),
          PF("Zwiększenie poziomu obsługi z 95% do 99% wymaga większego zapasu bezpieczeństwa.", True,
             why="Rośnie współczynnik z."),
      ],
      calc=[
          LB("D = 24 000 szt., S = 200 zł, H = 6 zł. Ile wynosi EOQ (szt.)?",
             1264.91, "(2*24000*200/6)**0.5", ["√(9 600 000 / 6) = √1 600 000 ≈ 1 264,91"], unit="szt.", tol=0.5),
          LB("Ile wynosi roczny koszt całkowity (zamawianie + utrzymanie) przy EOQ ≈ 1 264,91 szt. (zł)?",
             7589.47, "24000/1264.911*200+1264.911/2*6", ["3 794,73 + 3 794,73 ≈ 7 589,47 zł"], unit="zł", tol=1),
          LB("Dzienny popyt 80 szt., czas dostawy 5 dni, zapas bezpieczeństwa 100 szt. Ile wynosi ROP (szt.)?",
             500, "80*5+100", ["400 + 100 = 500"], unit="szt."),
          LB("z = 1,65, σ = 20 szt. dziennie, L = 4 dni. Ile wynosi zapas bezpieczeństwa (szt.)?",
             66, "1.65*20*4**0.5", ["1,65 · 20 · 2 = 66"], unit="szt."),
          LB("Rotacja zapasów 8 razy w roku. Ile wynosi rotacja w dniach?",
             45.63, "365/8", ["365 / 8 ≈ 45,63 dnia"], unit="dni", tol=0.01),
          LB("Q = 1 264,91 szt., zapas bezpieczeństwa 100 szt. Ile wynosi przeciętny zapas (szt.)?",
             732.46, "1264.911/2+100", ["632,46 + 100 ≈ 732,46"], unit="szt.", tol=0.5),
      ],
      case=[
          PR("Hurtownia zamawia proszek do prania raz w miesiącu po 2 000 opakowań. Roczny popyt 24 000 opakowań, koszt zamówienia 200 zł, koszt utrzymania 6 zł rocznie za opakowanie.",
             W("Ile wynosi roczny koszt całkowity przy obecnej polityce?",
               "8 400 zł (2 400 zł zamawiania + 6 000 zł utrzymania)", "7 589 zł", "12 000 zł",
               why="12 · 200 = 2 400 zł; 1 000 · 6 = 6 000 zł."),
             W("Ile hurtownia oszczędzi, przechodząc na EOQ?",
               "Ok. 811 zł rocznie", "Ok. 2 400 zł", "Nic",
               why="8 400 − 7 589 ≈ 811 zł."),
             PF("Przy obecnej polityce koszt utrzymania przewyższa koszt zamawiania, więc partie są za duże.", True,
                why="W optimum oba koszty są równe."),
          ),
          PR("Sklep sprzedaje średnio 50 sztuk produktu dziennie (σ = 12 szt.). Dostawa trwa 9 dni. Kierownik chce poziomu obsługi ok. 95% (z = 1,65).",
             W("Ile wynosi zapas bezpieczeństwa?",
               "Ok. 59 sztuk", "Ok. 20 sztuk", "Ok. 178 sztuk",
               why="1,65 · 12 · √9 = 1,65 · 36 = 59,4."),
             W("Przy jakim stanie zapasu należy złożyć zamówienie?",
               "Ok. 509 sztuk", "450 sztuk", "59 sztuk",
               why="50 · 9 + 59 ≈ 509."),
             PF("Skrócenie czasu dostawy zmniejszyłoby punkt ponownego zamówienia.", True,
                why="Maleje popyt w czasie dostawy i zapas bezpieczeństwa."),
          ),
      ]),

    L(2, "Wzory wartości klienta i lejka sprzedażowego",
      "Obliczać CLV, CAC, okres zwrotu kosztu pozyskania klienta, wskaźniki konwersji lejka, NPS i retencję – i wyciągać z nich wnioski dla marketingu.",
      ["Wartość klienta (CLV), lejek sprzedażowy i doświadczenie klienta", "Lojalność klienta i CRM"],
      [K16, K163],
      explain=[
          K("CLV",
            "Wartość klienta w czasie – zdyskontowana suma marż od klienta. Przy stałej rocznej marży m, wskaźniku utrzymania r i stopie dyskontowej d: CLV = m · r / (1 + d − r) (wersja, w której pierwsza marża pojawia się po roku, jeśli klient zostanie). Wzrost r silnie podnosi CLV, bo zmniejsza mianownik.",
            w="CLV = m · r / (1 + d − r)"),
          K("CAC i zwrot",
            "Koszt pozyskania klienta CAC = wydatki na pozyskanie / liczba nowych klientów. Okres zwrotu CAC = CAC / miesięczna marża z klienta. Relacja CLV/CAC – często przyjmuje się, że zdrowy biznes ma CLV co najmniej ok. 3 razy większe od CAC.",
            w="CAC = koszty pozyskania / nowi klienci"),
          W("CLV = 900 zł, CAC = 300 zł. Ile wynosi relacja CLV/CAC?",
            "3", "0,33", "600",
            why="900 / 300 = 3 – zdrowa relacja."),
          K("Lejek i konwersja",
            "Każdy etap lejka ma współczynnik konwersji = liczba osób na etapie następnym / liczba na etapie bieżącym. Łączna konwersja to iloczyn konwersji etapów. Poprawa najsłabszego etapu zwykle daje największy efekt.",
            w="konwersja łączna = k₁ · k₂ · … · kₙ"),
          K("Retencja i NPS",
            "Przy miesięcznym odpływie c roczna retencja = (1 − c)¹². Nawet niewielki miesięczny odpływ kumuluje się: 3% miesięcznie to ok. 31% klientów traconych w ciągu roku. NPS = % promotorów (9–10) − % krytyków (0–6).",
            w="retencja roczna = (1 − c)¹²"),
          PF("Miesięczny odpływ klientów 3% oznacza utratę dokładnie 36% klientów rocznie.", False,
             why="Odpływ się składa: 1 − 0,97¹² ≈ 30,6%."),
      ],
      mech=[
          KT("Wpływ na CLV",
             {"CLV rośnie": ["Wyższy wskaźnik utrzymania klientów", "Wyższa roczna marża na kliencie"],
              "CLV maleje": ["Wyższa stopa dyskontowa", "Większy odpływ klientów do konkurencji"]},
             why="Zależność od m, r i d."),
          LN("Ułóż obliczenie liczby klientów z kampanii.",
             ["Liczba wyświetleń reklamy", "Pomnóż przez CTR – liczba kliknięć", "Pomnóż przez konwersję na stronie – liczba zakupów", "Podziel koszt kampanii przez liczbę zakupów – CAC"],
             why="Kolejne etapy lejka i koszt pozyskania."),
          W("Lejek: CTR 2%, konwersja 5%. Który zabieg podwoi liczbę klientów?",
            "Podwojenie konwersji na stronie do 10% (lub CTR do 4%)", "Zwiększenie konwersji do 6%", "Obniżenie CTR do 1%",
            why="Łączna konwersja to iloczyn etapów."),
          W("Okres zwrotu CAC wynosi 30 miesięcy, a klienci zostają średnio 20 miesięcy. Co to oznacza?",
            "Firma traci na przeciętnym kliencie", "Firma ma bardzo zdrowy model", "Nic nie wynika",
            why="Klient odchodzi, zanim zwróci koszt pozyskania."),
          M("Jak można poprawić relację CLV/CAC?",
            ["Zwiększyć retencję klientów", "Obniżyć koszt pozyskania", "Podnieść marżę (np. cross-selling)", "Zwiększyć odpływ klientów"], [0, 1, 2],
            why="Odpływ obniża CLV."),
          PF("NPS może przyjmować wartości ujemne.", True,
             why="Gdy krytyków jest więcej niż promotorów."),
      ],
      calc=[
          LB("m = 500 zł, r = 0,7, d = 0,12. Ile wynosi CLV (zł)?",
             833.33, "500*0.7/(1+0.12-0.7)", ["350 / 0,42 ≈ 833,33 zł"], unit="zł", tol=0.02),
          LB("CAC = 300 zł, miesięczna marża z klienta 25 zł. Ile wynosi okres zwrotu CAC (miesiące)?",
             12, "300/25", ["300 / 25 = 12"], unit="mies."),
          LB("40 000 wyświetleń, CTR 2%, konwersja 5%. Ilu klientów?",
             40, "40000*0.02*0.05", ["40 000 · 0,02 · 0,05 = 40"], unit="osób"),
          LB("Kampania kosztowała 6 000 zł i dała 40 klientów. Ile wynosi CAC (zł)?",
             150, "6000/40", ["6 000 / 40 = 150 zł"], unit="zł"),
          LB("Miesięczny odpływ 3%. Ile wynosi roczna retencja (%)?",
             69.38, "0.97**12*100", ["0,97¹² ≈ 69,38%"], unit="%", tol=0.02),
          LB("48% promotorów, 30% pasywnych, 22% krytyków. Ile wynosi NPS?",
             26, "48-22", ["48 − 22 = 26"], unit="pkt"),
      ],
      case=[
          PR("Serwis subskrypcyjny: abonament 40 zł, marża 50% (20 zł miesięcznie), CAC 360 zł, miesięczny odpływ 5% (średni czas życia klienta ok. 1 / 0,05 = 20 miesięcy).",
             W("Ile wynosi okres zwrotu CAC?",
               "18 miesięcy", "9 miesięcy", "36 miesięcy",
               why="360 / 20 = 18 miesięcy."),
             W("Ile wynosi przybliżona (niezdyskontowana) wartość klienta?",
               "Ok. 400 zł – niewiele więcej niż CAC", "Ok. 4 000 zł", "Ok. 40 zł",
               why="20 zł · 20 miesięcy = 400 zł vs CAC 360 zł."),
             PF("Obniżenie odpływu do 2,5% podwoiłoby średni czas życia klienta.", True,
                why="1 / 0,025 = 40 miesięcy."),
          ),
          PR("Sklep internetowy: 100 000 wizyt miesięcznie, 8% dodaje produkt do koszyka, ale tylko 25% z nich finalizuje zakup. Analiza pokazuje, że wielu klientów rezygnuje przy wysokim koszcie dostawy.",
             W("Ile zakupów miesięcznie notuje sklep?",
               "2 000", "8 000", "25 000",
               why="100 000 · 0,08 · 0,25 = 2 000."),
             W("Ile zakupów byłoby, gdyby finalizację podnieść do 40%?",
               "3 200", "2 400", "4 000",
               why="100 000 · 0,08 · 0,4 = 3 200."),
             PF("Poprawa najsłabszego etapu lejka może dać duży przyrost sprzedaży bez wzrostu ruchu.", True,
                why="Konwersja łączna to iloczyn etapów."),
          ),
      ]),

    L(3, "Wzory jakości i wydajności",
      "Obliczać DPMO, uzysk procesu wieloetapowego, granice karty kontrolnej, krzywą uczenia się, wydajność pracy i OEE.",
      ["Six Sigma", "Narzędzia jakości", "Krzywa doświadczenia (uczenia się)", "Zarządzanie operacyjne (produkcją)"],
      [M178, LJIT],
      explain=[
          K("DPMO i poziom sigma",
            "DPMO = liczba defektów / (liczba jednostek · możliwości defektu na jednostkę) · 10⁶. Poziom 6σ odpowiada 3,4 DPMO (z umownym przesunięciem 1,5σ), 3σ – ok. 66 800 DPMO. Uzysk procesu wieloetapowego (rolled throughput yield) to iloczyn uzysków etapów.",
            w="DPMO = D / (N · O) · 10⁶"),
          K("Karta kontrolna",
            "Granice: górna GLK = średnia + 3σ, dolna DLK = średnia − 3σ. Punkt poza granicami lub nietypowy układ punktów (np. 7 kolejnych po jednej stronie średniej) sygnalizuje przyczynę specjalną, którą trzeba zbadać. Zmienność w granicach to przyczyny losowe – ingerowanie w nie („przeregulowanie”) zwiększa zmienność.",
            w="GLK/DLK = x̄ ± 3σ"),
          W("Średnia 200 g, σ = 4 g. Ile wynosi dolna granica kontrolna?",
            "188 g", "196 g", "176 g",
            why="200 − 3 · 4 = 188 g."),
          K("Krzywa uczenia się",
            "Przy współczynniku uczenia r czas n-tej jednostki: tₙ = t₁ · n^b, gdzie b = log r / log 2. Dla jednostek będących potęgami dwójki: t₂ₖ = tₖ · r. Przykład: r = 85%, t₁ = 40 h → t₂ = 34 h, t₄ = 28,9 h.",
            w="tₙ = t₁ · n^(log r / log 2)"),
          K("Wydajność i OEE",
            "Wydajność pracy = produkcja / nakład pracy (np. sztuki na roboczogodzinę). OEE (całkowita efektywność wyposażenia) = dostępność × wydajność (tempo) × jakość; wartość ok. 85% uchodzi za poziom światowy.",
            w="OEE = A · P · Q"),
          PF("Uzysk procesu wieloetapowego jest zawsze niższy lub równy najniższemu uzyskowi etapu.", True,
             why="Iloczyn liczb ≤ 1 nie przekracza najmniejszego czynnika."),
      ],
      mech=[
          KT("Przyczyna losowa czy specjalna?",
             {"Przyczyna losowa": ["Drobne wahania wagi w granicach kontrolnych"],
              "Przyczyna specjalna": ["Punkt powyżej górnej granicy kontrolnej", "Siedem kolejnych punktów powyżej średniej", "Nagły skok po zmianie dostawcy surowca"]},
             why="Tylko przyczyny specjalne wymagają interwencji."),
          LN("Ułóż obliczenie OEE.",
             ["Ustal planowany czas pracy maszyny", "Oblicz dostępność (czas pracy / czas planowany)", "Oblicz wydajność tempa (rzeczywiste / nominalne)", "Oblicz jakość (dobre sztuki / wszystkie)", "Pomnóż trzy wskaźniki"],
             why="OEE = A · P · Q."),
          W("Operator poprawia ustawienia maszyny po każdym wyniku w granicach kontrolnych. Skutek?",
            "Zmienność procesu rośnie (przeregulowanie)", "Zmienność maleje do zera", "Nic się nie zmienia",
            why="Reakcja na przyczyny losowe dodaje zmienności."),
          W("Krzywa uczenia 90% oznacza, że przy podwojeniu produkcji czas jednostki:",
            "Spada do 90% poprzedniej wartości", "Spada o 90%", "Rośnie o 10%",
            why="Każde podwojenie mnoży czas przez 0,9."),
          M("Co obniża OEE?",
            ["Przestoje maszyny", "Praca wolniejsza od nominalnej", "Wadliwe sztuki", "Planowana konserwacja poza czasem pracy"], [0, 1, 2],
            why="Czas poza planem pracy nie wchodzi do OEE."),
          PF("Im niższe DPMO, tym wyższy poziom sigma procesu.", True,
             why="Mniej defektów oznacza lepszy proces."),
      ],
      calc=[
          LB("45 defektów w 9 000 jednostek, 5 możliwości na jednostkę. Ile wynosi DPMO?",
             1000, "45/(9000*5)*1000000", ["45 / 45 000 · 10⁶ = 1 000"], unit="DPMO"),
          LB("Uzysk etapów: 99%, 97%, 98%, 96%. Ile wynosi uzysk całego procesu (%)?",
             90.35, "0.99*0.97*0.98*0.96*100", ["Iloczyn ≈ 0,9035 → 90,35%"], unit="%", tol=0.02),
          LB("Krzywa 85%, pierwsza jednostka 40 h. Ile godzin zajmie 4. jednostka?",
             28.9, "40*0.85**2", ["40 · 0,85² = 28,9 h"], unit="h", tol=0.01),
          LB("Produkcja wzrosła z 1 200 do 1 380 szt. przy tych samych 300 roboczogodzinach. O ile procent wzrosła wydajność?",
             15, "(1380/1200-1)*100", ["1 380 / 1 200 = 1,15 → +15%"], unit="%"),
          LB("Dostępność 90%, tempo 95%, jakość 98%. Ile wynosi OEE (%)?",
             83.79, "0.9*0.95*0.98*100", ["0,9 · 0,95 · 0,98 ≈ 83,79%"], unit="%", tol=0.02),
          LB("Średnia 200 g, σ = 4 g. Ile wynosi górna granica kontrolna (g)?",
             212, "200+3*4", ["200 + 12 = 212 g"], unit="g"),
      ],
      case=[
          PR("Linia pakująca: planowany czas 480 min, przestoje 48 min. Nominalne tempo 100 szt./min, w czasie pracy wyprodukowano 38 880 szt., z czego 38 102 dobrych.",
             W("Ile wynosi dostępność?",
               "90%", "95%", "98%",
               why="(480 − 48) / 480 = 432 / 480 = 0,9."),
             W("Ile wynosi wydajność tempa?",
               "90%", "100%", "85%",
               why="38 880 / (432 · 100) = 0,9."),
             PF("Jakość wynosi ok. 98%, więc OEE ≈ 0,9 · 0,9 · 0,98 ≈ 79%.", True,
                why="38 102 / 38 880 ≈ 0,98."),
          ),
          PR("Producent jachtów: pierwszy jacht nowej serii wymagał 2 000 h pracy, a krzywa uczenia się wynosi 80%. Klient zamawia jachty nr 5–8 i oczekuje ceny opartej na średnim czasie z jachtu nr 8.",
             W("Ile godzin zajmie jacht nr 8?",
               "1 024 h", "1 600 h", "1 280 h",
               why="2 000 · 0,8³ = 1 024 h."),
             W("Czy wycena wszystkich 4 jachtów według czasu z jachtu nr 8 jest dla stoczni korzystna?",
               "Nie – jachty 5–7 wymagają więcej godzin niż nr 8", "Tak, zawsze", "Nie ma to znaczenia",
               why="Czas spada stopniowo, więc nr 5–7 są droższe niż nr 8."),
             PF("Jacht nr 4 wymaga 1 280 h.", True,
                why="2 000 · 0,8² = 1 280 h."),
          ),
      ]),

    L(4, "Wzory zarządzania projektami i decyzji",
      "Obliczać czas oczekiwany i wariancję w metodzie PERT, ścieżkę krytyczną z zapasami, wartość oczekiwaną w drzewie decyzyjnym oraz wskaźniki wartości wypracowanej (CPI, SPI).",
      ["Zarządzanie projektami", "Podejmowanie decyzji"],
      [M23, M178],
      explain=[
          K("PERT",
            "Czas oczekiwany zadania: tₑ = (o + 4m + p) / 6; wariancja: σ² = ((p − o) / 6)². Wariancja ścieżki to suma wariancji zadań na ścieżce krytycznej, a odchylenie standardowe projektu to jej pierwiastek – pozwala oszacować prawdopodobieństwo dotrzymania terminu.",
            w="tₑ = (o + 4m + p) / 6;  σ² = ((p − o) / 6)²"),
          K("Ścieżka krytyczna i zapas",
            "Ścieżka krytyczna to najdłuższa ścieżka w sieci – wyznacza minimalny czas projektu. Zapas całkowity zadania = najpóźniejszy możliwy start − najwcześniejszy możliwy start; zadania krytyczne mają zapas 0. Skrócenie projektu wymaga skrócenia zadań krytycznych (może przy tym zmienić się ścieżka krytyczna)."),
          W("Zadanie ma najwcześniejszy start w 5. dniu, a najpóźniejszy w 9. Ile wynosi zapas?",
            "4 dni", "14 dni", "0 dni",
            why="9 − 5 = 4 dni zapasu całkowitego."),
          K("Drzewo decyzyjne",
            "Węzły decyzyjne (kwadraty) i losowe (koła). Wartość węzła losowego = suma prawdopodobieństw × wyników; w węźle decyzyjnym wybiera się gałąź o najwyższej wartości oczekiwanej (po odjęciu kosztu decyzji). Rozwiązuje się drzewo od końca („od prawej do lewej”).",
            w="EV = Σ pᵢ · xᵢ − koszt"),
          K("Wartość wypracowana (EVM)",
            "PV – wartość planowana (budżet prac zaplanowanych do dziś), EV – wartość wypracowana (budżet prac wykonanych), AC – koszt rzeczywisty. CPI = EV / AC (poniżej 1 – przekroczenie kosztów), SPI = EV / PV (poniżej 1 – opóźnienie). Prognoza kosztu całkowitego: EAC ≈ budżet / CPI.",
            w="CPI = EV / AC;  SPI = EV / PV"),
          PF("CPI = 0,8 oznacza, że za każdą wydaną złotówkę wykonano prace warte 80 groszy.", True,
             why="EV / AC = 0,8 – przekroczenie kosztów."),
      ],
      mech=[
          KT("Co oznacza wynik EVM?",
             {"Projekt przekracza budżet": ["CPI = 0,85"],
              "Projekt jest opóźniony": ["SPI = 0,9"],
              "Projekt jest tańszy od planu": ["CPI = 1,1"],
              "Projekt wyprzedza harmonogram": ["SPI = 1,05"]},
             why="Wskaźniki poniżej 1 sygnalizują problemy."),
          LN("Ułóż rozwiązywanie drzewa decyzyjnego.",
             ["Narysuj decyzje, zdarzenia losowe i wyniki", "Przypisz prawdopodobieństwa zdarzeniom", "Oblicz wartości oczekiwane w węzłach losowych od końca", "Odejmij koszty decyzji", "Wybierz gałąź o najwyższej wartości"],
             why="Drzewo rozwiązuje się od wyników do decyzji."),
          W("Jak zmienia się wariancja zadania PERT, gdy rozstęp p − o rośnie dwukrotnie?",
            "Rośnie czterokrotnie", "Rośnie dwukrotnie", "Nie zmienia się",
            why="Wariancja zależy od kwadratu rozstępu."),
          W("Skrócenie zadania niekrytycznego o 2 dni skróci projekt o:",
            "0 dni", "2 dni", "4 dni",
            why="Czas projektu wyznacza ścieżka krytyczna."),
          M("Które wielkości są potrzebne do policzenia CPI i SPI?",
            ["Wartość wypracowana (EV)", "Koszt rzeczywisty (AC)", "Wartość planowana (PV)", "Liczba spotkań zespołu"], [0, 1, 2],
            why="CPI = EV/AC, SPI = EV/PV."),
          PF("W węźle decyzyjnym wybiera się gałąź o najwyższej wartości oczekiwanej.", True,
             why="Przy neutralnym podejściu do ryzyka."),
      ],
      calc=[
          LB("PERT: o = 4, m = 7, p = 16 dni. Ile wynosi czas oczekiwany (dni)?",
             8, "(4+4*7+16)/6", ["(4 + 28 + 16) / 6 = 8"], unit="dni"),
          LB("Ile wynosi wariancja tego zadania?",
             4, "((16-4)/6)**2", ["(12 / 6)² = 4"], unit="dni²"),
          LB("Inwestycja 100 tys. zł: 30% szans na 400 tys. zł, 70% na 50 tys. zł. Ile wynosi wartość oczekiwana netto (tys. zł)?",
             55, "0.3*400+0.7*50-100", ["120 + 35 − 100 = 55"], unit="tys. zł"),
          LB("EV = 80 tys. zł, AC = 90 tys. zł. Ile wynosi CPI?",
             0.889, "80/90", ["80 / 90 ≈ 0,889"], unit="", tol=0.001),
          LB("EV = 80 tys. zł, PV = 100 tys. zł. Ile wynosi SPI?",
             0.8, "80/100", ["80 / 100 = 0,8"], unit=""),
          LB("Budżet projektu 400 tys. zł, CPI = 0,8. Ile wynosi prognoza kosztu całkowitego EAC (tys. zł)?",
             500, "400/0.8", ["400 / 0,8 = 500 tys. zł"], unit="tys. zł"),
      ],
      case=[
          PR("Firma rozważa wprowadzenie produktu. Badanie rynku kosztuje 20 tys. zł. Bez badania: wprowadzenie daje 50% szans na zysk 300 tys. zł i 50% na stratę 200 tys. zł. Rezygnacja daje 0.",
             W("Ile wynosi wartość oczekiwana wprowadzenia bez badania?",
               "50 tys. zł", "100 tys. zł", "250 tys. zł",
               why="0,5 · 300 − 0,5 · 200 = 50 tys. zł."),
             W("Którą opcję wybrać bez dodatkowych informacji, przy neutralności wobec ryzyka?",
               "Wprowadzić produkt (EV 50 > 0)", "Zrezygnować", "Obie są równie dobre",
               why="Wyższa wartość oczekiwana."),
             PF("Badanie rynku jest warte zakupu tylko wtedy, gdy zwiększa wartość oczekiwaną o więcej niż jego koszt.", True,
                why="To warunek opłacalności informacji."),
          ),
          PR("Po 6 miesiącach projektu IT: zaplanowano prace o wartości 600 tys. zł, wykonano prace o wartości budżetowej 480 tys. zł, a wydano 640 tys. zł. Budżet całego projektu to 1,2 mln zł.",
             W("Ile wynoszą CPI i SPI?",
               "CPI = 0,75, SPI = 0,8", "CPI = 1,33, SPI = 1,25", "CPI = 0,8, SPI = 0,75",
               why="480 / 640 = 0,75; 480 / 600 = 0,8."),
             W("Ile wyniesie prognozowany koszt całkowity przy obecnej efektywności?",
               "1,6 mln zł", "1,2 mln zł", "0,9 mln zł",
               why="1,2 / 0,75 = 1,6 mln zł."),
             PF("Projekt jest jednocześnie opóźniony i droższy od planu.", True,
                why="Oba wskaźniki są poniżej 1."),
          ),
      ]),

    L(5, "Wzory motywacji i organizacji pracy",
      "Obliczać motywację według Vrooma, wskaźnik potencjału motywacyjnego (MPS), liczbę szczebli i kierowników przy danej rozpiętości kierowania, liczbę kanałów komunikacji oraz wskaźniki fluktuacji i absencji.",
      ["Teoria oczekiwań (V. Vroom)", "Projektowanie stanowisk pracy", "Komunikacja w organizacji", "Zarządzanie zasobami ludzkimi (HRM)"],
      [M143, M114],
      explain=[
          K("Vroom i MPS",
            "Motywacja według Vrooma: M = E · I · V (oczekiwanie, instrumentalność, walencja). Wskaźnik potencjału motywacyjnego Hackmana i Oldhama: MPS = [(S + I + Sig) / 3] · A · F; autonomia i informacja zwrotna są mnożnikami, więc ich niski poziom drastycznie obniża wynik.",
            w="M = E · I · V;  MPS = (S + I + Sig)/3 · A · F"),
          K("Rozpiętość kierowania",
            "Przy jednakowej rozpiętości k i n szczeblach kierowniczych liczba pracowników na najniższym szczeblu to kⁿ, a liczba kierowników to 1 + k + k² + … + kⁿ⁻¹. Szersza rozpiętość = mniej szczebli i kierowników (struktura płaska)."),
          W("Rozpiętość 6, cztery szczeble kierownicze. Ilu pracowników wykonawczych?",
            "1 296", "24", "216",
            why="6⁴ = 6 · 6 · 6 · 6 = 1 296."),
          K("Kanały komunikacji",
            "W sieci „każdy z każdym” liczba kanałów = n(n − 1)/2 – rośnie w przybliżeniu z kwadratem liczby osób. Dlatego duże zespoły potrzebują struktury (podzespołów, liderów), a zespoły zadaniowe najlepiej działają przy kilku–kilkunastu osobach.",
            w="kanały = n(n − 1) / 2"),
          K("Fluktuacja i absencja",
            "Wskaźnik fluktuacji = liczba odejść / przeciętne zatrudnienie · 100%. Wskaźnik absencji = dni nieobecności / (zatrudnienie · dni robocze) · 100%. Koszt rotacji obejmuje rekrutację, szkolenie i utraconą wydajność – często szacowany na kilka miesięcznych pensji."),
          PF("Dodanie jednej osoby do 10-osobowego zespołu dodaje 10 kanałów komunikacji.", True,
             why="11 · 10 / 2 − 10 · 9 / 2 = 55 − 45 = 10."),
      ],
      mech=[
          KT("Co się stanie?",
             {"Rośnie liczba kanałów komunikacji": ["Zespół rośnie z 6 do 9 osób"],
              "Maleje liczba szczebli": ["Rozpiętość kierowania rośnie z 4 do 10"],
              "Maleje MPS": ["Pracownik traci możliwość decydowania o metodzie pracy"],
              "Motywacja (Vroom) spada do zera": ["Pracownik przestaje wierzyć, że firma wypłaci premię"]},
             why="Zastosowanie wzorów do zmian w organizacji."),
          LN("Ułóż obliczenie liczby kierowników przy rozpiętości 6 i 1 296 pracownikach.",
             ["Ustal liczbę szczebli: 6⁴ = 1 296, czyli 4 szczeble", "Najwyższy szczebel: 1 kierownik", "Kolejne szczeble: 6 i 36 kierowników", "Najniższy szczebel kierowniczy: 216 kierowników", "Suma: 1 + 6 + 36 + 216 = 259"],
             why="Suma ciągu geometrycznego."),
          W("E = 0,9, I = 0,9, V = 0,1. Jaka jest motywacja według Vrooma i dlaczego?",
            "Niska – nagroda jest mało ceniona", "Wysoka – E i I są wysokie", "Nieokreślona",
            why="0,9 · 0,9 · 0,1 = 0,081."),
          W("Jak zmienia się liczba kanałów komunikacji, gdy zespół się podwaja?",
            "Rośnie mniej więcej czterokrotnie", "Rośnie dwukrotnie", "Nie zmienia się",
            why="Zależność w przybliżeniu kwadratowa."),
          M("Co obejmuje koszt fluktuacji pracowników?",
            ["Rekrutację następcy", "Szkolenie i wdrożenie", "Utraconą wydajność", "Podatek VAT"], [0, 1, 2],
            why="VAT nie jest kosztem rotacji."),
          PF("MPS spada do minimum, gdy informacja zwrotna jest na najniższym poziomie.", True,
             why="F jest mnożnikiem we wzorze."),
      ],
      calc=[
          LB("E = 0,7, I = 0,6, V = 0,8. Ile wynosi motywacja M?",
             0.336, "0.7*0.6*0.8", ["0,7 · 0,6 · 0,8 = 0,336"], unit="", tol=0.001),
          LB("S = 6, I = 5, Sig = 4, A = 6, F = 5. Ile wynosi MPS?",
             150, "(6+5+4)/3*6*5", ["5 · 6 · 5 = 150"], unit="pkt"),
          LB("Rozpiętość 6, cztery szczeble kierownicze. Ilu jest kierowników łącznie?",
             259, "1+6+36+216", ["1 + 6 + 36 + 216 = 259"], unit="osób"),
          LB("Ile kanałów komunikacji ma 10-osobowy zespół „każdy z każdym”?",
             45, "10*9/2", ["10 · 9 / 2 = 45"], unit="kanałów"),
          LB("18 odejść przy przeciętnym zatrudnieniu 150 osób. Ile wynosi fluktuacja (%)?",
             12, "18/150*100", ["18 / 150 = 12%"], unit="%"),
          LB("1 200 dni nieobecności, 150 pracowników, 220 dni roboczych. Ile wynosi absencja (%)?",
             3.64, "1200/(150*220)*100", ["1 200 / 33 000 ≈ 3,64%"], unit="%", tol=0.02),
      ],
      case=[
          PR("Firma ma 1 296 pracowników wykonawczych i rozpiętość kierowania 6. Rozważa zwiększenie rozpiętości do 36 dzięki samodzielnym zespołom i systemom informatycznym.",
             W("Ile szczebli kierowniczych byłoby przy rozpiętości 36?",
               "2", "4", "6",
               why="36² = 1 296, więc wystarczą 2 szczeble."),
             W("Ilu kierowników byłoby wtedy potrzebnych?",
               "37", "259", "216",
               why="1 + 36 = 37 zamiast 259."),
             PF("Tak szeroka rozpiętość wymaga dużej samodzielności pracowników.", True,
                why="Kierownik nie może szczegółowo nadzorować 36 osób."),
          ),
          PR("Dział obsługi klienta: 80 osób, 20 odejść rocznie. Koszt zastąpienia jednej osoby to ok. 3 pensje po 6 000 zł. Program rozwoju i lepszych grafików kosztowałby 150 000 zł rocznie i zmniejszyłby odejścia o połowę.",
             W("Ile wynosi fluktuacja?",
               "25%", "20%", "4%",
               why="20 odejść / 80 osób = 25%."),
             W("Ile wynosi roczny koszt rotacji?",
               "360 000 zł", "120 000 zł", "18 000 zł",
               why="20 · 3 · 6 000 = 360 000 zł."),
             PF("Program się opłaca, bo oszczędność (180 000 zł) przewyższa jego koszt (150 000 zł).", True,
                why="10 odejść mniej · 18 000 zł = 180 000 zł."),
          ),
      ]),
]
