# -*- coding: utf-8 -*-
# Zrozumienie – Zarządzanie / Organizowanie i struktury
OSM = "https://openstax.org/books/principles-management/pages/"
D = "2026-10-08"
M43 = S("OpenStax, Principles of Management, 4.3 Organizational Designs and Structures", OSM + "4-3-organizational-designs-and-structures", D)
M44 = S("OpenStax, Principles of Management, 4.4 The Internal Organization and External Environments", OSM + "4-4-the-internal-organization-and-external-environments", D)
M46 = S("OpenStax, Principles of Management, 4.6 Organizing for Change in the 21st Century", OSM + "4-6-organizing-for-change-in-the-21st-century", D)
M101 = S("OpenStax, Principles of Management, 10.1 Organizational Structures and Design", OSM + "10-1-organizational-structures-and-design", D)
M102 = S("OpenStax, Principles of Management, 10.2 Organizational Change", OSM + "10-2-organizational-change", D)
M114 = S("OpenStax, Principles of Management, 11.4 Influencing Employee Performance and Motivation", OSM + "11-4-influencing-employee-performance-and-motivation", D)

WOLC = S("Wikipedia – Organizational life cycle", "https://en.wikipedia.org/wiki/Organizational_life_cycle", D)
WOD = S("Wikipedia – Organization development", "https://en.wikipedia.org/wiki/Organization_development", D)
M178 = S("OpenStax, Principles of Management, 17.8 The Control- and Involvement-Oriented Approaches to Planning and Controlling", OSM + "17-8-the-control-and-involvement-oriented-approaches-to-planning-and-controlling", D)
MA71 = S("OpenStax, Principles of Managerial Accounting, 7.1 Describe How and Why Managers Use Budgets", "https://openstax.org/books/principles-managerial-accounting/pages/7-1-describe-how-and-why-managers-use-budgets", D)

LESSONS = [
    L(1, "Struktura organizacyjna i grupowanie stanowisk",
      "Rozumieć, czym jest struktura organizacyjna, jakie elementy ją tworzą i jak grupuje się stanowiska według funkcji, produktów, regionów i klientów.",
      ["Organizowanie i struktura organizacyjna", "Grupowanie stanowisk (departamentalizacja)"],
      [M101, M43],
      explain=[
          K("Struktura organizacyjna",
            "To układ stanowisk, komórek i powiązań między nimi: kto komu podlega, kto podejmuje decyzje, jak płynie informacja. Elementy: specjalizacja (podział pracy), departamentalizacja (grupowanie), hierarchia i rozpiętość kierowania, centralizacja, formalizacja (zasady, procedury). Obraz struktury to schemat organizacyjny."),
          K("Sposoby grupowania",
            "Funkcjonalne – według funkcji (produkcja, finanse, marketing): korzyści specjalizacji, ale słaba koordynacja między działami. Produktowe – według produktów lub marek: odpowiedzialność za wynik produktu, ale dublowanie funkcji. Geograficzne – według regionów: dopasowanie do lokalnych rynków. Według klientów – np. klienci indywidualni, firmy, sektor publiczny."),
          W("Bank ma osobne piony dla klientów indywidualnych, małych firm i korporacji. Jakie to grupowanie?",
            "Według klientów", "Funkcjonalne", "Geograficzne",
            why="Kryterium jest typ obsługiwanego klienta."),
          K("Formalizacja i specjalizacja",
            "Wysoka formalizacja (dużo procedur) daje przewidywalność, ale ogranicza elastyczność. Specjalizacja zwiększa wydajność, ale nadmierna prowadzi do monotonii i utraty sensu pracy."),
          K("Dobór struktury",
            "Mała firma zwykle zaczyna od prostej struktury wokół właściciela; rosnąca – przechodzi do funkcjonalnej; zdywersyfikowana – do produktowej lub regionalnej (dywizjonalnej). Struktura powinna wspierać strategię („struktura podąża za strategią” – A. Chandler)."),
          PF("Według A. Chandlera struktura organizacyjna powinna podążać za strategią.", True,
             why="Zmiana strategii wymaga dopasowania struktury."),
      ],
      mech=[
          KT("Rodzaj departamentalizacji",
             {"Funkcjonalna": ["Działy: produkcja, finanse, marketing, HR"],
              "Produktowa": ["Piony: chemia gospodarcza, kosmetyki, żywność"],
              "Geograficzna": ["Oddziały: Europa, Azja, Ameryka"],
              "Według klientów": ["Dział klientów indywidualnych i dział korporacyjny"]},
             why="Każde kryterium ma inne zalety."),
          LN("Ułóż typową ewolucję struktury rosnącej firmy.",
             ["Właściciel sam podejmuje wszystkie decyzje", "Zatrudnia pierwszych specjalistów", "Tworzy działy funkcjonalne", "Wprowadza nowe produkty i wchodzi na nowe rynki", "Przechodzi na strukturę dywizjonalną (produktową lub regionalną)"],
             why="Struktura rozwija się wraz ze strategią i skalą."),
          W("Jaka jest główna wada grupowania funkcjonalnego w dużej, zróżnicowanej firmie?",
            "Słaba koordynacja między działami i wolne decyzje dotyczące produktów", "Dublowanie funkcji", "Brak specjalizacji",
            why="Każdy dział widzi tylko swój fragment."),
          W("Jaka jest główna wada grupowania produktowego?",
            "Dublowanie funkcji w każdym pionie", "Brak odpowiedzialności za wynik produktu", "Brak elastyczności",
            why="Każdy pion ma np. własny marketing i finanse."),
          M("Jakie są elementy struktury organizacyjnej?",
            ["Specjalizacja", "Hierarchia i rozpiętość kierowania", "Centralizacja decyzji", "Kurs akcji spółki"], [0, 1, 2],
            why="Kurs akcji nie jest elementem struktury."),
          PF("Wysoka formalizacja zwiększa przewidywalność działania.", True,
             why="Procedury ujednolicają zachowania."),
      ],
      calc=[
          LB("Firma ma 4 działy funkcjonalne po 25 osób i 4 kierowników. Ile osób liczy firma (bez zarządu)?",
             104, "4*25+4", ["100 + 4 = 104"], unit="osoby"),
          LB("Przejście na 3 piony produktowe, każdy z własnym działem marketingu (po 6 osób) zamiast wspólnego (10 osób). O ile więcej osób w marketingu?",
             8, "3*6-10", ["18 − 10 = 8"], unit="osób"),
          LB("Koszt jednej osoby w marketingu 120 000 zł rocznie. Ile kosztuje dublowanie funkcji (zł)?",
             960000, "8*120000", ["8 · 120 000 = 960 000 zł"], unit="zł"),
          LB("Czas decyzji o nowym produkcie spada z 90 do 30 dni po reorganizacji. O ile procent?",
             66.67, "(1-30/90)*100", ["30 / 90 ≈ 0,333 → spadek ≈ 66,67%"], unit="%", tol=0.02),
          LB("Procedury: 120 stron w regulaminie, uproszczone do 45 stron. O ile procent skrócono?",
             62.5, "(1-45/120)*100", ["45 / 120 = 0,375 → 62,5%"], unit="%", tol=0.01),
          LB("Region Azja odpowiada za 35% przychodów 2 mld zł. Ile to mld zł?",
             0.7, "2*0.35", ["2 · 35% = 0,7 mld zł"], unit="mld zł", tol=0.01),
      ],
      case=[
          PR("Producent kosmetyków z działami produkcji, marketingu, finansów i sprzedaży wprowadził 5 marek dla różnych grup klientów. Każda decyzja o marce wymaga uzgodnień 4 działów i trwa miesiącami.",
             W("Jaka struktura obecnie obowiązuje?",
               "Funkcjonalna", "Produktowa", "Macierzowa",
               why="Działy są pogrupowane według funkcji."),
             W("Jaka zmiana mogłaby przyspieszyć decyzje dla marek?",
               "Przejście na strukturę produktową (piony marek)", "Zwiększenie liczby procedur", "Likwidacja marketingu",
               why="Pion marki odpowiada za jej wynik i decyzje."),
             PF("Kosztem zmiany może być dublowanie niektórych funkcji w pionach.", True,
                why="Każdy pion może potrzebować własnych specjalistów."),
          ),
          PR("Firma logistyczna działa w Polsce, Czechach i Niemczech. Klienci w każdym kraju mają inne wymagania prawne i zwyczaje.",
             W("Jakie grupowanie najlepiej odpowiada tej sytuacji?",
               "Geograficzne", "Funkcjonalne", "Według produktów",
               why="Różnice między krajami są kluczowe."),
             W("Jakie ryzyko niesie silna autonomia oddziałów krajowych?",
               "Brak spójności standardów w całej firmie", "Brak dopasowania do lokalnych rynków", "Brak kierowników",
               why="Każdy kraj może działać inaczej."),
             PF("Wspólne standardy i systemy IT mogą ograniczyć to ryzyko.", True,
                why="Łączą lokalną elastyczność z jednolitością."),
          ),
      ]),

    L(2, "Rozpiętość kierowania, centralizacja i delegowanie",
      "Liczyć liczbę szczebli i kierowników przy różnej rozpiętości kierowania, porównywać struktury smukłe i płaskie, oceniać centralizację i decentralizację oraz zasady skutecznego delegowania.",
      ["Rozpiętość kierowania", "Centralizacja i decentralizacja", "Delegowanie uprawnień"],
      [M101, M44],
      explain=[
          K("Rozpiętość kierowania",
            "To liczba podwładnych bezpośrednio podległych jednemu kierownikowi. Wąska rozpiętość – struktura smukła (wysoka): wiele szczebli, ścisły nadzór, wolny przepływ informacji. Szeroka – struktura płaska: mało szczebli, większa samodzielność pracowników, szybsza komunikacja. Optymalna rozpiętość zależy od złożoności pracy, kompetencji podwładnych i podobieństwa zadań.",
            w="pracownicy = rozpiętość^liczba szczebli kierowniczych"),
          K("Centralizacja i decentralizacja",
            "Centralizacja – decyzje zapadają na szczycie: spójność, kontrola, ale wolniejsze reakcje i przeciążenie zarządu. Decentralizacja – decyzje przekazuje się niższym szczeblom: szybkość, wykorzystanie wiedzy lokalnej, motywacja, ale ryzyko niespójności. Firmy często łączą oba podejścia (np. centralne finanse, zdecentralizowana sprzedaż)."),
          W("Rozpiętość kierowania rośnie z 5 do 10 przy tej samej liczbie pracowników. Co dzieje się z liczbą szczebli?",
            "Maleje – struktura się spłaszcza", "Rośnie", "Nie zmienia się",
            why="Każdy kierownik nadzoruje więcej osób, więc potrzeba mniej poziomów."),
          K("Delegowanie",
            "Delegowanie to przekazanie podwładnemu zadania wraz z uprawnieniami (prawem decydowania) i odpowiedzialnością za wykonanie. Kierownik nadal odpowiada przed przełożonym za wynik. Zasady: jasny cel i termin, uprawnienia adekwatne do zadania, dobór osoby o odpowiednich kompetencjach, wsparcie i kontrola rezultatów, nie każdej czynności."),
          K("Bariery delegowania",
            "Kierownicy boją się utraty kontroli, uważają, że „sami zrobią szybciej”, nie ufają podwładnym; podwładni boją się błędów i krytyki. Brak delegowania przeciąża kierowników i hamuje rozwój pracowników."),
          PF("Delegując zadanie, kierownik przestaje ponosić odpowiedzialność za jego wynik.", False,
             why="Kierownik nadal odpowiada przed swoim przełożonym."),
      ],
      mech=[
          KT("Struktura smukła czy płaska?",
             {"Smukła (wąska rozpiętość)": ["Wiele szczebli zarządzania", "Ścisły nadzór nad pracownikami", "Dłuższa droga informacji"],
              "Płaska (szeroka rozpiętość)": ["Niewiele szczebli", "Duża samodzielność pracowników", "Szybka komunikacja"]},
             why="Rozpiętość kierowania decyduje o kształcie struktury."),
          LN("Ułóż kroki skutecznego delegowania.",
             ["Wybierz zadanie odpowiednie do delegowania", "Dobierz osobę o właściwych kompetencjach", "Określ cel, termin i zakres uprawnień", "Zapewnij wsparcie i zasoby", "Oceń rezultat i udziel informacji zwrotnej"],
             why="Delegowanie to proces, a nie tylko wydanie polecenia."),
          W("Sieć sklepów pozwala kierownikom placówek decydować o lokalnych promocjach. To przykład:",
            "Decentralizacji", "Centralizacji", "Zarządzania przez wyjątki wyłącznie",
            why="Decyzja zapada blisko klienta."),
          W("Kiedy szeroka rozpiętość kierowania jest odpowiednia?",
            "Gdy zadania są podobne, a pracownicy doświadczeni", "Gdy praca jest bardzo złożona i nowa", "Gdy pracownicy dopiero się uczą",
            why="Wtedy potrzeba mniej nadzoru."),
          M("Jakie są zalety decentralizacji?",
            ["Szybsze decyzje", "Wykorzystanie wiedzy lokalnej", "Większa motywacja kierowników niższego szczebla", "Pełna jednolitość decyzji w całej firmie"], [0, 1, 2],
            why="Jednolitość to raczej zaleta centralizacji."),
          PF("Spłaszczenie struktury zmniejsza liczbę kierowników średniego szczebla.", True,
             why="Mniej szczebli oznacza mniej stanowisk kierowniczych."),
      ],
      calc=[
          LB("Rozpiętość 8, na najniższym szczeblu 4 096 pracowników. Ile szczebli kierowniczych potrzeba (8^n = 4 096)?",
             4, "4", ["8⁴ = 4 096 → 4 szczeble"], unit="szczeble"),
          LB("Ilu kierowników jest w tej strukturze (512 + 64 + 8 + 1)?",
             585, "4096/8+4096/64+4096/512+4096/4096", ["512 + 64 + 8 + 1 = 585"], unit="osób"),
          LB("Ta sama liczba pracowników przy rozpiętości 4 (4^6 = 4 096). Ilu kierowników potrzeba (1 024 + 256 + 64 + 16 + 4 + 1)?",
             1365, "1024+256+64+16+4+1", ["Suma = 1 365"], unit="osób"),
          LB("O ilu kierowników więcej wymaga struktura o rozpiętości 4 niż 8?",
             780, "1365-585", ["1 365 − 585 = 780"], unit="osób"),
          LB("Koszt kierownika 150 000 zł rocznie. Ile kosztuje struktura smukła więcej (mln zł)?",
             117, "780*150000/1e6", ["780 · 150 000 = 117 mln zł"], unit="mln zł"),
          LB("Kierownik ma 12 podwładnych i 40 h tygodniowo; na rozmowy z każdym poświęca 2 h. Ile godzin zostaje na inne zadania?",
             16, "40-12*2", ["40 − 24 = 16 h"], unit="h"),
      ],
      case=[
          PR("Firma ubezpieczeniowa ma 7 szczebli zarządzania. Decyzja o wypłacie dużego odszkodowania przechodzi przez 5 poziomów akceptacji i trwa 6 tygodni. Klienci odchodzą do konkurencji, która wypłaca w 5 dni.",
             W("Jaki problem struktury ujawnia przypadek?",
               "Zbyt smukła, scentralizowana struktura spowalnia decyzje", "Zbyt płaska struktura", "Brak hierarchii",
               why="Wiele szczebli i akceptacji wydłuża proces."),
             W("Jakie rozwiązanie warto rozważyć?",
               "Spłaszczenie struktury i delegowanie uprawnień do decyzji o wypłatach", "Dodanie kolejnych szczebli", "Wymóg akceptacji prezesa",
               why="Decyzje bliżej klienta są szybsze."),
             PF("Delegowanie wymaga jasnych limitów kwot i kontroli, by ograniczyć ryzyko nadużyć.", True,
                why="Uprawnienia powinny być adekwatne do kompetencji."),
          ),
          PR("Kierowniczka działu (15 osób) sama sprawdza każde pismo, przygotowuje raporty i odpowiada na maile klientów. Pracuje 60 h tygodniowo, a zespół narzeka na brak rozwoju.",
             W("Czego brakuje w jej sposobie zarządzania?",
               "Delegowania zadań i uprawnień", "Kontroli", "Specjalizacji",
               why="Wykonuje pracę, którą mogliby przejąć podwładni."),
             W("Jaka korzyść płynie z delegowania dla zespołu?",
               "Rozwój kompetencji i większe zaangażowanie", "Mniej odpowiedzialności", "Brak korzyści",
               why="Pracownicy uczą się i czują zaufanie."),
             PF("Przekonanie „sama zrobię szybciej” jest typową barierą delegowania.", True,
                why="Krótkoterminowo bywa prawdą, długoterminowo przeciąża kierownika."),
          ),
      ]),

    L(3, "Typy struktur organizacyjnych",
      "Porównywać strukturę liniową, funkcjonalną, liniowo-sztabową, dywizjonalną, macierzową i sieciową oraz dobierać je do wielkości, strategii i otoczenia organizacji.",
      ["Typy struktur organizacyjnych", "Organizowanie i struktura organizacyjna"],
      [M43, M101],
      explain=[
          K("Liniowa i funkcjonalna",
            "Liniowa: każdy pracownik ma jednego przełożonego, prosta i przejrzysta, ale przeciąża kierowników i słabo wykorzystuje specjalistów – dobra dla małych firm. Funkcjonalna (Taylor): specjaliści wydają polecenia w swoich dziedzinach – wysoka fachowość, ale łamie jedność rozkazodawstwa."),
          K("Liniowo-sztabowa i dywizjonalna",
            "Liniowo-sztabowa: kierownicy liniowi decydują, a komórki sztabowe (prawnicy, analitycy, kontroling) doradzają – łączy jedność rozkazodawstwa z fachowością. Dywizjonalna: samodzielne dywizje (produktowe lub regionalne) z własnymi funkcjami i odpowiedzialnością za wynik; centrala ustala strategię i alokuje kapitał – typowa dla dużych zdywersyfikowanych firm."),
          W("Firma ma trzy samodzielne piony (AGD, elektronika, oświetlenie), każdy z własną produkcją i sprzedażą. Jaka to struktura?",
            "Dywizjonalna", "Liniowa", "Funkcjonalna",
            why="Piony są centrami zysku z własnymi funkcjami."),
          K("Macierzowa",
            "Łączy podział funkcjonalny z projektowym lub produktowym – pracownik ma dwóch przełożonych (kierownika działu i kierownika projektu). Zalety: elastyczność, dobre wykorzystanie specjalistów w wielu projektach. Wady: konflikty o zasoby i priorytety, niejasna odpowiedzialność. Typowa w firmach doradczych, inżynieryjnych, IT."),
          K("Sieciowa i wirtualna",
            "Organizacja sieciowa skupia się na kompetencjach kluczowych, a resztę zleca partnerom (produkcja, logistyka, marketing), koordynując sieć za pomocą umów i technologii. Elastyczna i tania w rozwoju, ale zależna od partnerów i trudniejsza do kontroli jakości."),
          PF("W strukturze macierzowej pracownik może podlegać dwóm przełożonym jednocześnie.", True,
             why="Kierownikowi działu i kierownikowi projektu."),
      ],
      mech=[
          KT("Jaka struktura?",
             {"Liniowa": ["Mała piekarnia: właściciel i sześciu pracowników"],
              "Liniowo-sztabowa": ["Dyrektor zakładu z działem prawnym i kontrolingu jako doradcami"],
              "Dywizjonalna": ["Koncern z dywizjami w Europie, Azji i Ameryce"],
              "Macierzowa": ["Firma inżynieryjna z działami branżowymi i zespołami projektowymi"],
              "Sieciowa": ["Marka odzieżowa zlecająca produkcję i logistykę partnerom"]},
             why="Każda struktura pasuje do innej sytuacji."),
          LN("Ułóż, jak działa struktura macierzowa w projekcie.",
             ["Firma uruchamia nowy projekt", "Kierownik projektu kompletuje zespół z różnych działów", "Specjaliści pracują w projekcie, pozostając w swoich działach", "Kierownik działu dba o kompetencje i obciążenie pracą", "Po zakończeniu projektu specjaliści wracają do innych zadań"],
             why="Zasoby są współdzielone między działami i projektami."),
          W("Jaka jest główna wada struktury macierzowej?",
            "Konflikty między przełożonymi o priorytety i zasoby", "Brak specjalistów", "Zbyt mała elastyczność",
            why="Dwóch przełożonych może mieć sprzeczne oczekiwania."),
          W("Dla jakiej firmy najlepsza jest struktura dywizjonalna?",
            "Dużej, zdywersyfikowanej, działającej na różnych rynkach", "Jednoosobowej działalności", "Małego warsztatu",
            why="Dywizje pozwalają dopasować się do różnych rynków."),
          M("Jakie są zalety struktury liniowo-sztabowej?",
            ["Zachowanie jedności rozkazodawstwa", "Wykorzystanie fachowej wiedzy sztabów", "Odciążenie kierowników liniowych", "Brak potrzeby jakichkolwiek kierowników"], [0, 1, 2],
            why="Kierownicy liniowi nadal podejmują decyzje."),
          PF("Organizacja sieciowa zleca partnerom działania spoza swoich kompetencji kluczowych.", True,
             why="Skupia się na tym, co robi najlepiej."),
      ],
      calc=[
          LB("Dywizja A: przychody 400 mln zł, zysk 48 mln zł. Ile wynosi rentowność (%)?",
             12, "48/400*100", ["48 / 400 = 12%"], unit="%"),
          LB("Dywizja B: przychody 250 mln zł, zysk 15 mln zł. Ile wynosi rentowność (%)?",
             6, "15/250*100", ["15 / 250 = 6%"], unit="%"),
          LB("Specjalista w macierzy dzieli 40 h tygodniowo: 60% projekt X, reszta – dział. Ile godzin na dział?",
             16, "40*0.4", ["40 · 40% = 16 h"], unit="h"),
          LB("Firma sieciowa zatrudnia 50 osób, a partnerzy – 2 000 osób pracujących dla niej. Jaki odsetek pracy wykonują partnerzy (%)?",
             97.56, "2000/2050*100", ["2 000 / 2 050 ≈ 97,56%"], unit="%", tol=0.02),
          LB("Koszty centrali koncernu 30 mln zł dzieli się na 3 dywizje proporcjonalnie do przychodów 400, 250 i 350 mln zł. Ile przypada na A (mln zł)?",
             12, "30*400/1000", ["30 · 400 / 1 000 = 12 mln zł"], unit="mln zł"),
          LB("Sztab kontrolingu: 6 osób obsługuje 120 kierowników liniowych. Ilu kierowników na jednego analityka?",
             20, "120/6", ["120 / 6 = 20"], unit="osób"),
      ],
      case=[
          PR("Agencja IT realizuje 15 projektów rocznie dla różnych klientów. Ma działy: programistów, testerów, projektantów UX. Każdy projekt potrzebuje osób z kilku działów na kilka miesięcy.",
             W("Jaka struktura najlepiej pasuje?",
               "Macierzowa", "Liniowa", "Dywizjonalna geograficzna",
               why="Łączy działy kompetencyjne z zespołami projektowymi."),
             W("Jak ograniczyć konflikty między kierownikami projektów a działów?",
               "Jasne zasady priorytetów i wspólne planowanie obciążenia", "Usunąć kierowników działów", "Zakazać projektów",
               why="Reguły rozstrzygania sporów zmniejszają napięcia."),
             PF("Struktura macierzowa pozwala jednemu specjaliście pracować w kilku projektach.", True,
                why="Zasoby są elastycznie współdzielone."),
          ),
          PR("Marka sportowa projektuje i promuje buty, ale produkcję zleca fabrykom w Azji, a logistykę – operatorom zewnętrznym. Afera z warunkami pracy u jednego z podwykonawców uderza w reputację marki.",
             W("Jaka to struktura?",
               "Sieciowa", "Liniowa", "Funkcjonalna",
               why="Firma koordynuje sieć partnerów zewnętrznych."),
             W("Jakie ryzyko ilustruje afera?",
               "Ograniczoną kontrolę nad partnerami i ryzyko reputacyjne", "Brak elastyczności", "Zbyt wysokie koszty stałe",
               why="Problemy partnerów obciążają markę."),
             PF("Audyty dostawców i kodeks postępowania dla partnerów mogą ograniczyć to ryzyko.", True,
                why="Wzmacniają kontrolę nad łańcuchem dostaw."),
          ),
      ]),

    L(4, "Organizacja mechanistyczna, organiczna i ucząca się",
      "Rozumieć różnicę między organizacją mechanistyczną i organiczną (Burns i Stalker), dopasowanie do otoczenia oraz cechy organizacji uczącej się według P. Senge.",
      ["Organizacja mechanistyczna i organiczna", "Organizacja ucząca się"],
      [M44, M46, M102],
      explain=[
          K("Burns i Stalker (1961)",
            "Badając szkockie i angielskie firmy elektroniczne, T. Burns i G.M. Stalker wyróżnili dwa typy. Mechanistyczny: wysoka specjalizacja i formalizacja, scentralizowane decyzje, komunikacja pionowa, ścisłe opisy stanowisk – skuteczny w stabilnym otoczeniu. Organiczny: elastyczne role, zdecentralizowane decyzje, komunikacja pozioma, praca zespołowa – skuteczny w zmiennym otoczeniu."),
          K("Dopasowanie do otoczenia",
            "Nie ma struktury najlepszej w każdych warunkach (podejście sytuacyjne). Firma energetyczna z regulowanymi taryfami może działać mechanistycznie; start-up technologiczny potrzebuje organiczności. Duże firmy łączą oba typy w różnych działach (np. mechanistyczna produkcja, organiczny dział badań)."),
          W("Dział badań i rozwoju w szybko zmieniającej się branży powinien być raczej:",
            "Organiczny", "Mechanistyczny", "Biurokratyczny w czystej postaci",
            why="Potrzebuje elastyczności i swobodnej komunikacji."),
          K("Organizacja ucząca się",
            "Peter Senge („Piąta dyscyplina”, 1990): organizacja, która stale rozwija zdolność do tworzenia przyszłości dzięki pięciu dyscyplinom: mistrzostwo osobiste, modele myślowe, wspólna wizja, uczenie się zespołowe i myślenie systemowe (piąta dyscyplina, spajająca pozostałe). Uczy się na błędach, dzieli wiedzą, eksperymentuje."),
          K("Mechanizmy uczenia się",
            "Analizy po działaniu (co poszło dobrze, co źle), dzielenie się wiedzą między zespołami, rotacja stanowisk, tolerancja dla eksperymentów, systemy zarządzania wiedzą. Uczenie się „podwójnej pętli” (Argyris) kwestionuje same założenia, a nie tylko poprawia działania."),
          PF("Myślenie systemowe jest według Senge „piątą dyscypliną”.", True,
             why="Spaja pozostałe cztery dyscypliny."),
      ],
      mech=[
          KT("Mechanistyczna czy organiczna?",
             {"Mechanistyczna": ["Szczegółowe procedury i opisy stanowisk", "Decyzje na szczycie hierarchii", "Komunikacja głównie z góry na dół"],
              "Organiczna": ["Zespoły międzydziałowe", "Decyzje podejmowane blisko problemu", "Elastyczne role i swobodna komunikacja"]},
             why="Dwa bieguny projektowania organizacji."),
          LN("Ułóż cykl uczenia się organizacji.",
             ["Organizacja działa i zbiera doświadczenia", "Analizuje wyniki i błędy (np. analiza po działaniu)", "Kwestionuje założenia, które doprowadziły do błędów", "Dzieli się wnioskami między zespołami", "Zmienia procedury i sposób działania"],
             why="Uczenie się wymaga refleksji i zmiany praktyk."),
          W("Szpital po każdym poważnym zdarzeniu przeprowadza analizę przyczyn bez szukania winnych i zmienia procedury. Jaką cechę wykazuje?",
            "Organizacji uczącej się", "Mechanistycznej biurokracji", "Teorii X",
            why="Uczy się na błędach i dzieli wnioskami."),
          W("Kiedy struktura mechanistyczna jest skuteczna?",
            "W stabilnym, przewidywalnym otoczeniu", "W bardzo zmiennym otoczeniu", "Nigdy",
            why="Procedury dobrze działają, gdy warunki się nie zmieniają."),
          M("Które dyscypliny wymienia P. Senge?",
            ["Mistrzostwo osobiste", "Modele myślowe", "Wspólna wizja", "Ścisła kontrola czasu pracy"], [0, 1, 2],
            why="Pozostałe to uczenie się zespołowe i myślenie systemowe."),
          PF("Jedna firma może mieć działy o różnym stopniu organiczności.", True,
             why="Np. mechanistyczną produkcję i organiczne badania."),
      ],
      calc=[
          LB("Firma przeprowadziła 40 analiz po projektach i wdrożyła 26 usprawnień. Jaki to procent?",
             65, "26/40*100", ["26 / 40 = 65%"], unit="%"),
          LB("Liczba powtarzających się błędów spadła z 50 do 20 rocznie. O ile procent?",
             60, "(1-20/50)*100", ["20 / 50 = 0,4 → spadek 60%"], unit="%"),
          LB("Czas wprowadzenia produktu: mechanistyczny dział 18 miesięcy, zespół organiczny 12. O ile procent szybciej?",
             33.33, "(1-12/18)*100", ["12 / 18 ≈ 0,667 → 33,33%"], unit="%", tol=0.02),
          LB("Burns i Stalker opublikowali badania w 1961 r., Senge w 1990 r. Ile lat różnicy?",
             29, "1990-1961", ["1990 − 1961 = 29"], unit="lat"),
          LB("Program dzielenia się wiedzą kosztuje 200 000 zł, a oszczędności z unikniętych błędów to 650 000 zł. Ile wynosi zwrot z inwestycji (%)?",
             225, "(650000-200000)/200000*100", ["450 000 / 200 000 = 225%"], unit="%"),
          LB("Pięć dyscyplin Senge; firma rozwija 3. Jaki to procent?",
             60, "3/5*100", ["3 / 5 = 60%"], unit="%"),
      ],
      case=[
          PR("Elektrownia działa według ścisłych procedur bezpieczeństwa i jasnej hierarchii. Ta sama grupa kapitałowa ma start-up rozwijający aplikacje dla klientów energii, który działa w małych zespołach i co tydzień zmienia priorytety.",
             W("Jaką strukturę ma elektrownia?",
               "Mechanistyczną", "Organiczną", "Sieciową",
               why="Procedury i hierarchia w stabilnym, regulowanym otoczeniu."),
             W("Dlaczego start-up powinien działać organicznie?",
               "Jego otoczenie jest zmienne i wymaga szybkiej adaptacji", "Bo nie ma pracowników", "Bo jest regulowany jak elektrownia",
               why="Organiczność sprzyja innowacjom i szybkości."),
             PF("Narzucenie start-upowi procedur elektrowni mogłoby zahamować innowacje.", True,
                why="Struktura nie byłaby dopasowana do otoczenia."),
          ),
          PR("Producent oprogramowania po nieudanym wdrożeniu u klienta zwołuje warsztat. Zespół odkrywa, że problem wynikał z założenia, że „klient sam wie, czego potrzebuje”. Firma zmienia proces: prototypy i testy z użytkownikami.",
             W("Jaki typ uczenia się nastąpił?",
               "Podwójnej pętli – zakwestionowano założenie", "Pojedynczej pętli – drobna poprawka", "Brak uczenia się",
               why="Zmieniono sposób myślenia, nie tylko działanie."),
             W("Którą dyscyplinę Senge wykorzystano najmocniej?",
               "Modele myślowe", "Mistrzostwo osobiste", "Wspólna wizja",
               why="Zakwestionowano utrwalone przekonanie."),
             PF("Warsztat bez szukania winnych sprzyja szczerości i uczeniu się.", True,
                why="Strach przed karą ukrywa przyczyny problemów."),
          ),
      ]),

    L(5, "Projektowanie stanowisk pracy",
      "Rozumieć metody projektowania stanowisk – specjalizację, rotację, rozszerzanie i wzbogacanie pracy – oraz model cech pracy Hackmana i Oldhama z wskaźnikiem potencjału motywacyjnego.",
      ["Projektowanie stanowisk pracy", "Organizowanie i struktura organizacyjna"],
      [M114],
      explain=[
          K("Specjalizacja i jej koszty",
            "Wąska specjalizacja (Taylor, Ford) zwiększa wydajność, ułatwia szkolenie i obniża koszty, ale prowadzi do monotonii, znużenia, absencji i braku poczucia sensu pracy."),
          K("Rotacja, rozszerzanie, wzbogacanie",
            "Rotacja – okresowe przenoszenie pracownika między stanowiskami (różnorodność, wszechstronność). Rozszerzanie pracy (job enlargement) – więcej zadań na tym samym poziomie (poziomo). Wzbogacanie pracy (job enrichment, Herzberg) – więcej odpowiedzialności, planowania i kontroli własnej pracy (pionowo) – najsilniej motywuje."),
          W("Pracownik linii montażowej zaczyna sam planować swoją pracę i kontrolować jakość. To przykład:",
            "Wzbogacania pracy", "Rozszerzania pracy", "Specjalizacji",
            why="Dochodzi odpowiedzialność i kontrola – wymiar pionowy."),
          K("Model cech pracy (Hackman i Oldham, 1976)",
            "Pięć cech: różnorodność umiejętności (S), tożsamość zadania (I – wykonanie całości), znaczenie zadania (Sig), autonomia (A) i informacja zwrotna (F). Wskaźnik potencjału motywacyjnego: MPS = [(S + I + Sig)/3] × A × F. Niska autonomia lub brak informacji zwrotnej drastycznie obniżają MPS.",
            w="MPS = [(S + I + Sig) / 3] · A · F"),
          K("Elastyczne formy pracy",
            "Ruchomy czas pracy, praca zdalna i hybrydowa, skrócony tydzień, dzielenie etatu. Zwiększają autonomię i równowagę praca–życie, ale wymagają zarządzania przez cele i dobrej komunikacji."),
          PF("Brak informacji zwrotnej (F = 1 na skali 1–7) obniża MPS niezależnie od innych cech.", True,
             why="F jest mnożnikiem we wzorze."),
      ],
      mech=[
          KT("Metoda projektowania stanowiska",
             {"Rotacja": ["Pracownik co miesiąc zmienia stanowisko na linii"],
              "Rozszerzanie": ["Kasjer dodatkowo układa towar na półkach"],
              "Wzbogacanie": ["Zespół sam ustala grafik i odpowiada za jakość", "Pracownik planuje i rozlicza swoje zadania"],
              "Specjalizacja": ["Pracownik wykonuje tylko jedną operację na linii"]},
             why="Metody różnią się kierunkiem zmiany (poziomo/pionowo)."),
          LN("Ułóż mechanizm modelu Hackmana i Oldhama.",
             ["Praca ma różnorodność, tożsamość i znaczenie", "Pracownik odczuwa sens swojej pracy", "Autonomia daje poczucie odpowiedzialności", "Informacja zwrotna daje wiedzę o wynikach", "Rośnie motywacja wewnętrzna, satysfakcja i jakość pracy"],
             why="Cechy pracy → stany psychiczne → wyniki."),
          W("Która cecha pracy najsilniej wpływa na poczucie odpowiedzialności za wyniki?",
            "Autonomia", "Różnorodność umiejętności", "Tożsamość zadania",
            why="Swoboda decyzji czyni pracownika odpowiedzialnym."),
          W("Jaka jest różnica między rozszerzaniem a wzbogacaniem pracy?",
            "Rozszerzanie dodaje zadań na tym samym poziomie, wzbogacanie – odpowiedzialność i kontrolę", "Nie ma różnicy", "Wzbogacanie oznacza wyższą pensję",
            why="Wymiar poziomy vs pionowy."),
          M("Jakie są skutki nadmiernej specjalizacji?",
            ["Monotonia i znużenie", "Wyższa absencja i rotacja", "Brak poczucia sensu pracy", "Zawsze wyższa satysfakcja"], [0, 1, 2],
            why="Nadmierna specjalizacja obniża satysfakcję."),
          PF("Wzbogacanie pracy wywodzi się z dwuczynnikowej teorii Herzberga.", True,
             why="Herzberg zalecał zwiększanie czynników motywujących w samej pracy."),
      ],
      calc=[
          LB("S = 5, I = 4, Sig = 6, A = 5, F = 4. Ile wynosi MPS?",
             100, "(5+4+6)/3*5*4", ["(15 / 3) · 5 · 4 = 5 · 20 = 100"], unit="pkt"),
          LB("Te same cechy, ale autonomia spada do 2. Ile wynosi MPS?",
             40, "(5+4+6)/3*2*4", ["5 · 2 · 4 = 40"], unit="pkt"),
          LB("Maksymalny MPS przy skali 1–7 (wszystkie cechy = 7)?",
             343, "(7+7+7)/3*7*7", ["7 · 7 · 7 = 343"], unit="pkt"),
          LB("Absencja spadła z 6% do 4,5% po wzbogaceniu pracy. O ile procent?",
             25, "(1-4.5/6)*100", ["4,5 / 6 = 0,75 → spadek 25%"], unit="%"),
          LB("Rotacja na 5 stanowiskach co 6 tygodni. Po ilu tygodniach pracownik wróci na pierwsze stanowisko?",
             30, "5*6", ["5 · 6 = 30 tygodni"], unit="tyg."),
          LB("Praca hybrydowa: 3 dni zdalnie z 5. Jaki procent czasu pracownik pracuje zdalnie?",
             60, "3/5*100", ["3 / 5 = 60%"], unit="%"),
      ],
      case=[
          PR("W centrum obsługi klienta pracownicy odpowiadają tylko na jeden typ pytań według skryptu, bez wpływu na rozwiązanie problemu i bez informacji, czy klient był zadowolony. Rotacja sięga 50% rocznie.",
             W("Które cechy pracy z modelu Hackmana i Oldhama są bardzo niskie?",
               "Autonomia i informacja zwrotna (oraz różnorodność)", "Tylko znaczenie zadania", "Żadne",
               why="Skrypt, brak wpływu i brak feedbacku."),
             W("Jakie zmiany mogą zwiększyć motywację?",
               "Uprawnienia do rozwiązywania spraw i informacja o ocenach klientów", "Więcej skryptów", "Krótsze przerwy",
               why="Zwiększają autonomię i informację zwrotną."),
             PF("Wzrost MPS może ograniczyć rotację pracowników.", True,
                why="Większa motywacja wewnętrzna i satysfakcja."),
          ),
          PR("Fabryka wprowadza zespoły autonomiczne: 8-osobowa grupa sama dzieli zadania, planuje pracę i odpowiada za jakość całego podzespołu, a co miesiąc dostaje raport o wynikach.",
             W("Jakie podejście do projektowania pracy zastosowano?",
               "Wzbogacanie pracy na poziomie zespołu", "Wąską specjalizację", "Tylko rotację",
               why="Zespół ma planowanie, kontrolę i odpowiedzialność."),
             W("Która cecha pracy rośnie dzięki odpowiedzialności za cały podzespół?",
               "Tożsamość zadania", "Monotonia", "Formalizacja",
               why="Zespół wykonuje całość zamiast fragmentu."),
             PF("Miesięczny raport o wynikach zapewnia informację zwrotną.", True,
                why="To jedna z pięciu cech modelu."),
          ),
      ]),
    L(6, "Rozwój organizacji i kontrola: cykl życia, OD, kontrola biurokratyczna i budżetowa",
      "Opisywać fazy cyklu życia organizacji i rolę doskonalenia organizacji (OD), porównywać kontrolę biurokratyczną z kontrolą z udziałem pracowników oraz rozumieć kontrolę budżetową i analizę odchyleń.",
      ["Cykl życia organizacji", "Doskonalenie organizacji (OD)", "Kontrola biurokratyczna i kontrola z udziałem pracowników", "Kontrola budżetowa", "Kontrolowanie"],
      [WOLC, M102, WOD, M178, MA71],
      explain=[
          K("Cykl życia organizacji",
            "Organizacja przechodzi fazy: narodzin (mała, nieformalna, wokół założyciela), młodości (szybki wzrost, pierwsze procedury), wieku średniego (stabilizacja, formalizacja, rozbudowana struktura) i dojrzałości (duża, sztywna, ryzyko stagnacji). Każda faza wymaga innej struktury – stąd potrzeba ciągłego dopasowywania i odnowy."),
          K("Doskonalenie organizacji (OD)",
            "OD to planowany, długofalowy wysiłek całej organizacji, wspierany przez kierownictwo, by zwiększyć jej skuteczność za pomocą wiedzy z nauk behawioralnych. Typowe techniki: diagnoza, budowanie zespołów, informacja zwrotna z badań ankietowych, doradztwo procesowe, szkolenia, planowanie kariery."),
          W("Co odróżnia OD od pojedynczej zmiany struktury?",
            "Planowany, długofalowy charakter obejmujący całą organizację i oparty na naukach behawioralnych", "Jednorazowe zwolnienie pracowników", "Wyłącznie zmiana systemu informatycznego",
            why="OD dotyczy ludzi, kultury i procesów w całej organizacji."),
          K("Dwa podejścia do kontroli",
            "Kontrola biurokratyczna opiera się na regułach, procedurach, hierarchii i nadzorze; nagradza zgodność, oczekuje posłuszeństwa. Kontrola z udziałem pracowników (zaangażowania, klanowa) opiera się na wspólnych wartościach, normach grupy i samokontroli; nagradza wyniki zespołu, oczekuje zaangażowania."),
          K("Kontrola budżetowa",
            "Budżet to plan wyrażony liczbami (np. przychody, koszty, przepływy pieniężne, nakłady inwestycyjne). Kontrola polega na porównaniu wykonania z budżetem i analizie odchyleń: korzystne (przychód wyższy lub koszt niższy niż plan) i niekorzystne. Budżet może być ustalany odgórnie lub oddolnie (partycypacyjnie)."),
          PF("Koszt niższy od budżetu to odchylenie korzystne.", True,
             why="Wydano mniej niż planowano."),
      ],
      mech=[
          LN("Ułóż fazy cyklu życia organizacji.",
             ["Narodziny", "Młodość", "Wiek średni", "Dojrzałość"],
             why="Wraz z wiekiem rośnie wielkość i formalizacja."),
          KT("Kontrola biurokratyczna czy z udziałem pracowników?",
             {"Biurokratyczna": ["Szczegółowe procedury i regulaminy", "Nadzór bezpośredniego przełożonego", "Nagroda za zgodność z normą"],
              "Z udziałem pracowników": ["Samokontrola i normy zespołu", "Wspólne wartości kultury organizacyjnej", "Premia za wynik całego zespołu"]},
             why="Pierwsza opiera się na regułach, druga na zaangażowaniu."),
          W("Która technika należy do OD?",
            "Informacja zwrotna z badań ankietowych pracowników", "Analiza progu rentowności", "Metoda kolejnych podstawień",
            why="OD posługuje się narzędziami nauk behawioralnych."),
          W("Kiedy budżet nazywamy partycypacyjnym?",
            "Gdy w jego ustalaniu uczestniczą kierownicy niższych szczebli", "Gdy ustala go wyłącznie zarząd", "Gdy nie zawiera liczb",
            why="Udział niższych szczebli zwiększa akceptację budżetu."),
          PF("Dojrzała organizacja zwykle jest bardziej sformalizowana niż młoda.", True,
             why="Formalizacja rośnie z wielkością i wiekiem."),
          PF("Kontrola z udziałem pracowników całkowicie znosi standardy wyników.", False,
             why="Standardy są, ale kontrolę sprawuje zespół i sam pracownik."),
      ],
      calc=[
          LB("Budżet kosztów materiałów: 200 tys. zł, wykonanie: 230 tys. zł. Ile wynosi odchylenie (tys. zł, niekorzystne)?",
             30, "230-200", ["230 − 200 = 30 tys. zł ponad budżet"], unit="tys. zł"),
          LB("To samo odchylenie w procentach budżetu?",
             15, "30/200*100", ["30 / 200 · 100 = 15%"], unit="%"),
          LB("Budżet przychodów: 1000 tys. zł, wykonanie: 1080 tys. zł. Odchylenie korzystne w tys. zł?",
             80, "1080-1000", ["1080 − 1000 = 80 tys. zł"], unit="tys. zł"),
          LB("Stopień wykonania budżetu przychodów (%)?",
             108, "1080/1000*100", ["1080 / 1000 · 100 = 108%"], unit="%"),
          LB("Budżet kosztów: 800 tys. zł; wykonanie: 760 tys. zł. Odchylenie korzystne w %?",
             5, "(800-760)/800*100", ["(800 − 760) / 800 · 100 = 5%"], unit="%"),
          LB("Firma toleruje odchylenia do 5% budżetu. Koszt budżetowany 400 tys. zł. Od jakiej kwoty (tys. zł) przekroczenie wymaga interwencji?",
             420, "400*1.05", ["400 · 1,05 = 420 tys. zł"], unit="tys. zł"),
      ],
      case=[
          PR("Start-up programistyczny założony przez trzech przyjaciół w ciągu pięciu lat urósł do 300 osób. Decyzje wciąż podejmują założyciele, nie ma opisów stanowisk, a zespoły skarżą się na chaos i opóźnienia. Zarząd zatrudnia doradców, którzy przeprowadzają ankietę wśród pracowników i warsztaty budowania zespołów.",
             W("W jakiej fazie cyklu życia znalazła się firma?",
               "Przechodzi z młodości do wieku średniego – potrzebuje formalizacji", "W fazie narodzin", "W fazie schyłku i likwidacji",
               why="Szybki wzrost wymaga procedur i struktury."),
             W("Jak nazwać działania doradców?",
               "Doskonalenie organizacji (OD)", "Reengineering procesów", "Kontrola budżetowa",
               why="Ankieta z informacją zwrotną i budowanie zespołów to techniki OD."),
             PF("Kultura nieformalna start-upu może utrudniać zmianę.", True,
                why="Pracownicy przyzwyczajeni do swobody stawiają opór formalizacji."),
          ),
          PR("Sieć sklepów wprowadziła miesięczne budżety kosztów dla każdego sklepu. Kierownicy uczestniczyli w ich ustalaniu. W czerwcu sklep A wydał na energię 52 tys. zł przy budżecie 40 tys. zł; sklep B – 38 tys. zł przy budżecie 40 tys. zł.",
             W("Jak ocenić odchylenie w sklepie A?",
               "Niekorzystne, 30% ponad budżet", "Korzystne, 30% poniżej budżetu", "Zgodne z budżetem",
               why="(52 − 40) / 40 = 30% ponad plan."),
             W("Jaki rodzaj budżetowania zastosowano?",
               "Partycypacyjne (oddolne)", "Wyłącznie odgórne", "Brak budżetowania",
               why="Kierownicy sklepów współtworzyli budżety."),
             PF("Kontrola budżetowa jest rodzajem kontroli finansowej.", True,
                why="Porównuje wykonanie z planem finansowym."),
          ),
      ]),
]
