# -*- coding: utf-8 -*-
TITLE = "Osoby – ekonomiści i teoretycy zarządzania"
INTRO = "Autorzy teorii, praw i modeli przywoływanych w pytaniach – kim byli i z czym ich kojarzyć. Hasła ułożone według nazwiska."
E = [
 ("Adams J. Stacy", "Amerykański psycholog; teoria sprawiedliwości (równości) w motywacji (1963).", {"k": ["adams"]}),
 ("Akerlof George", "Amerykański ekonomista, Nobel 2001; „The Market for Lemons” (1970) – asymetria informacji i negatywna selekcja; współtwórca nowej ekonomii keynesowskiej.", {"k": ["akerlof"]}),
 ("Alderfer Clayton", "Amerykański psycholog; teoria potrzeb ERG (egzystencja, więzi, wzrost), 1969.", {"k": ["alderfer"]}),
 ("Ansoff Igor", "Twórca planowania strategicznego; macierz produkt–rynek (strategie rozwoju), 1957.", {"k": ["ansoff"]}),
 ("Bagehot Walter", "Brytyjski ekonomista i dziennikarz („The Economist”); „Lombard Street” (1873) – zasady pożyczkodawcy ostatniej instancji.", {"k": ["bagehot"]}),
 ("Balcerowicz Leszek", "Polski ekonomista; wicepremier i minister finansów (1989–1991, 1997–2000), autor programu transformacji (od 1 stycznia 1990 r.); prezes NBP 2001–2007.", {"k": ["balcerowicz"]}),
 ("Barnard Chester", "Amerykański menedżer i teoretyk; „Funkcje kierownika” (1938): organizacja jako system współdziałania, teoria akceptacji autorytetu.", {"k": ["barnard"]}),
 ("Bernanke Ben", "Przewodniczący Fed 2006–2014 (kryzys 2008, QE); Nobel 2022 (z D. Diamondem i P. Dybvigiem) za badania banków i kryzysów finansowych.", {"k": ["bernanke"]}),
 ("Beveridge William", "Brytyjski ekonomista; raport z 1942 r. – podstawy państwa dobrobytu i NHS; krzywa Beveridge’a (wakaty–bezrobocie).", {"k": ["beveridge"]}),
 ("Black Fischer, Scholes Myron, Merton Robert", "Twórcy modelu wyceny opcji Blacka–Scholesa (1973); Scholes i Merton otrzymali Nobla w 1997 r. (Black zmarł w 1995 r.).", {"k": ["black", "scholes", "merton"]}),
 ("Blake Robert, Mouton Jane", "Twórcy siatki kierowniczej (1964).", {"k": ["blake", "mouton"]}),
 ("Coase Ronald", "Brytyjski ekonomista, Nobel 1991; koszty transakcyjne i istota firmy (1937), twierdzenie Coase’a (1960).", {"k": ["coase"]}),
 ("Cox John, Ross Stephen, Rubinstein Mark", "Twórcy dwumianowego modelu wyceny opcji (1979).", {"k": ["cox", "rubinstein"]}),
 ("Deming W. Edwards", "Amerykański statystyk, ojciec zarządzania jakością (TQM), cykl PDCA, 14 zasad; wpływ na powojenną Japonię.", {"k": ["deming"]}),
 ("Diamond Douglas", "Amerykański ekonomista, Nobel 2022; model runów bankowych Diamonda–Dybviga (1983).", {"k": ["diamond"]}),
 ("Drucker Peter", "Teoretyk zarządzania („ojciec nowoczesnego zarządzania”); zarządzanie przez cele (1954), przedsiębiorczość i innowacje.", {"k": ["drucker"]}),
 ("Duesenberry James", "Amerykański ekonomista; hipoteza dochodu względnego (1949), efekt demonstracji i efekt rygla.", {"k": ["duesenberry"]}),
 ("Eichengreen Barry", "Amerykański ekonomista; historia systemu walutowego, z R. Hausmannem pojęcie „grzechu pierworodnego”.", {"k": ["eichengreen"]}),
 ("Emerson Harrington", "Przedstawiciel naukowego zarządzania; „12 zasad wydajności” (1912).", {"k": ["emerson"]}),
 ("Fama Eugene", "Amerykański ekonomista, Nobel 2013; hipoteza rynku efektywnego (1970).", {"k": ["fama"]}),
 ("Fayol Henri", "Francuski inżynier i menedżer; twórca teorii administracji – funkcje kierownicze i 14 zasad zarządzania („Administracja przemysłowa i ogólna”, 1916).", {"k": ["fayol"]}),
 ("Fiedler Fred", "Amerykański psycholog; sytuacyjny model przywództwa LPC (1967).", {"k": ["fiedler"]}),
 ("Fisher Irving", "Amerykański ekonomista; równanie wymiany MV = PT, efekt Fishera (stopa nominalna a inflacja), teoria procentu.", {"k": ["fisher"]}),
 ("Follett Mary Parker", "Prekursorka podejścia behawioralnego; znaczenie współpracy, konfliktu konstruktywnego.", {"k": ["follett"]}),
 ("Friedman Milton", "Amerykański ekonomista, Nobel 1976; twórca monetaryzmu, hipotezy dochodu permanentnego (1957), naturalnej stopy bezrobocia; „inflacja jest zawsze i wszędzie zjawiskiem pieniężnym”; „Kapitalizm i wolność” (1962).", {"k": ["friedman"]}),
 ("Fukuyama Francis", "Amerykański politolog; „Koniec historii” (1992), „Zaufanie” (1995) – kapitał społeczny i zaufanie w gospodarce.", {"k": ["fukuyama"]}),
 ("Galbraith John Kenneth", "Amerykański ekonomista instytucjonalny; „Społeczeństwo dobrobytu” (1958), „Nowe państwo przemysłowe” (1967), koncepcja siły równoważącej.", {"k": ["galbraith"]}),
 ("Gantt Henry", "Współpracownik F.W. Taylora; wykres Gantta – harmonogram zadań w czasie.", {"k": ["gantt"]}),
 ("Gilbreth Frank i Lillian", "Przedstawiciele naukowego zarządzania; badania ruchów roboczych (mikroruchy – therbligi), psychologia pracy.", {"k": ["gilbreth"]}),
 ("Gossen Hermann Heinrich", "Niemiecki ekonomista; prawa Gossena (1854) – malejąca użyteczność krańcowa i równowaga konsumenta.", {"k": ["gossen"]}),
 ("Greenspan Alan", "Przewodniczący Fed 1987–2006; reguła Greenspana–Guidottiego (rezerwy a dług krótkoterminowy).", {"k": ["greenspan"]}),
 ("Gresham Thomas", "XVI-wieczny angielski kupiec i finansista; prawo Kopernika–Greshama (pieniądz gorszy wypiera lepszy).", {"k": ["gresham"]}),
 ("Griffin Ricky W.", "Autor podręcznika „Podstawy zarządzania organizacjami” – podstawowego źródła z zarządzania w OWE.", {"k": ["griffin"]}),
 ("Hardin Garrett", "Amerykański ekolog; „Tragedia wspólnego pastwiska” (1968).", {"k": ["hardin"]}),
 ("Hayek Friedrich von", "Austriacki ekonomista, Nobel 1974; szkoła austriacka, krytyka planowania („Droga do zniewolenia”, 1944), denacjonalizacja pieniądza, wiedza rozproszona i rola cen.", {"k": ["hayek", "denacjonalizacj"]}),
 ("Heider Fritz", "Austriacko-amerykański psycholog; teoria atrybucji (1958).", {"k": ["heider"]}),
 ("Hersey Paul, Blanchard Kenneth", "Twórcy sytuacyjnej teorii przywództwa (cyklu życia), 1969.", {"k": ["hersey", "blanchard"]}),
 ("Herzberg Frederick", "Amerykański psycholog; dwuczynnikowa teoria motywacji (1959).", {"k": ["herzberg"]}),
 ("Hicks John", "Brytyjski ekonomista, Nobel 1972; model IS-LM (1937), efekt substytucyjny i dochodowy.", {"k": ["hicks"]}),
 ("House Robert", "Amerykański teoretyk organizacji; teoria ścieżki do celu (1971).", {"k": ["house"]}),
 ("Kahneman Daniel", "Izraelsko-amerykański psycholog, Nobel z ekonomii 2002; z A. Tverskym teoria perspektywy (1979), heurystyki i błędy poznawcze („Pułapki myślenia”).", {"k": ["kahneman"]}),
 ("Kalecki Michał", "Polski ekonomista (1899–1970); niezależnie od Keynesa sformułował teorię efektywnego popytu (1933), teoria cyklu koniunkturalnego, polityczny cykl koniunkturalny, teoria wzrostu gospodarki socjalistycznej.", {"k": ["kalecki"]}),
 ("Kaplan Robert, Norton David", "Twórcy zrównoważonej karty wyników (Balanced Scorecard, 1992).", {"k": ["kaplan", "norton"]}),
 ("Keynes John Maynard", "Brytyjski ekonomista (1883–1946); „Ogólna teoria zatrudnienia, procentu i pieniądza” (1936) – popyt efektywny, mnożnik, preferencja płynności, pułapka płynności; współtwórca systemu z Bretton Woods.", {"k": ["keynes"]}),
 ("Kondratiew Nikołaj", "Rosyjski ekonomista; długie fale koniunktury (40–60 lat), lata 20. XX w.", {"k": ["kondratiew"]}),
 ("Kopernik Mikołaj", "Astronom i ekonomista; traktat „Monetae cudendae ratio” (1526) – sformułował prawo wypierania lepszego pieniądza przez gorszy.", {"k": ["kopernik"]}),
 ("Kornai János", "Węgierski ekonomista; „Niedobór w gospodarce” (1980), miękkie ograniczenie budżetowe.", {"k": ["kornai"]}),
 ("Kotler Philip", "Amerykański teoretyk marketingu; „Marketing” – podstawowy podręcznik, poziomy produktu, marketing społeczny.", {"k": ["kotler"]}),
 ("Krugman Paul", "Amerykański ekonomista, Nobel 2008; nowa teoria handlu (korzyści skali, handel wewnątrzgałęziowy), geografia ekonomiczna, model kryzysów walutowych I generacji (1979).", {"k": ["krugman"]}),
 ("Kuznets Simon", "Amerykański ekonomista, Nobel 1971; twórca rachunków narodowych (PKB), krzywa Kuznetsa, cykle Kuznetsa.", {"k": ["kuznets"]}),
 ("Kydland Finn, Prescott Edward", "Nobliści 2004; teoria realnego cyklu koniunkturalnego, problem niespójności czasowej polityki gospodarczej.", {"k": ["kydland", "prescott"]}),
 ("Laffer Arthur", "Amerykański ekonomista ekonomii podaży; krzywa Laffera (lata 70.).", {"k": ["laffer"]}),
 ("Lange Oskar", "Polski ekonomista (1904–1965); model socjalizmu rynkowego (rachunek ekonomiczny w socjalizmie), ekonometria.", {"k": ["lange"]}),
 ("Layard Richard, Nickell Stephen, Jackman Richard", "Brytyjscy ekonomiści; model rynku pracy i NAIRU („Unemployment”, 1991).", {"k": ["layard", "nickell", "jackman"]}),
 ("Leontief Wassily", "Amerykański ekonomista rosyjskiego pochodzenia, Nobel 1973; analiza przepływów międzygałęziowych (input–output), paradoks Leontiefa.", {"k": ["leontief"]}),
 ("Levitt Theodore", "Amerykański ekonomista (Harvard); „Marketing Myopia” (1960), „Exploit the Product Life Cycle” (1965), globalizacja rynków.", {"k": ["levitt"]}),
 ("Likert Rensis", "Amerykański psycholog; cztery systemy zarządzania, skala Likerta.", {"k": ["likert"]}),
 ("List Friedrich", "Niemiecki ekonomista (XIX w.); argument ochrony młodego (raczkującego) przemysłu, narodowy system ekonomii politycznej.", {"k": ["list f", "friedrich list", "f. list"]}),
 ("Lucas Robert E.", "Amerykański ekonomista, Nobel 1995; racjonalne oczekiwania, krytyka Lucasa, endogeniczna teoria wzrostu (kapitał ludzki).", {"k": ["lucas"]}),
 ("Malthus Thomas", "Angielski ekonomista; „Prawo ludności” (1798) – ludność rośnie w postępie geometrycznym, żywność arytmetycznym.", {"k": ["malthus"]}),
 ("Markowitz Harry", "Amerykański ekonomista, Nobel 1990; nowoczesna teoria portfela (1952).", {"k": ["markowitz"]}),
 ("Marshall Alfred", "Brytyjski ekonomista neoklasyczny; „Zasady ekonomii” (1890) – krzywe popytu i podaży, elastyczność, nadwyżka konsumenta, krótki i długi okres.", {"k": ["marshall"]}),
 ("Marks Karol", "Niemiecki filozof i ekonomista; „Kapitał” (1867) – teoria wartości dodatkowej, krytyka kapitalizmu.", {"k": ["marks", "marksa"]}),
 ("Maslow Abraham", "Amerykański psycholog humanistyczny; hierarchia potrzeb (1943).", {"k": ["maslow"]}),
 ("Mayo Elton", "Australijski psycholog; eksperymenty w Hawthorne (Western Electric), szkoła stosunków międzyludzkich.", {"k": ["mayo"]}),
 ("McClelland David", "Amerykański psycholog; teoria potrzeb nabytych (osiągnięć, władzy, przynależności).", {"k": ["mcclelland"]}),
 ("McGregor Douglas", "Amerykański psycholog zarządzania; teoria X i teoria Y („The Human Side of Enterprise”, 1960).", {"k": ["mcgregor"]}),
 ("McKinnon Ronald, Kenen Peter", "Współtwórcy (z R. Mundellem) teorii optymalnych obszarów walutowych (McKinnon 1963 – otwartość gospodarki; Kenen 1969 – zróżnicowanie produkcji).", {"k": ["mckinnon", "kenen"]}),
 ("Menger Carl", "Austriacki ekonomista, twórca szkoły austriackiej i jeden z ojców rewolucji marginalistycznej (1871).", {"k": ["menger"]}),
 ("Miles Raymond, Snow Charles", "Twórcy typologii strategii: poszukiwacz, obrońca, analityk, reaktor (1978).", {"k": ["miles", "snow"]}),
 ("Mill John Stuart", "Brytyjski filozof i ekonomista klasyczny; „Zasady ekonomii politycznej” (1848), utylitaryzm.", {"k": ["mill"]}),
 ("Minsky Hyman", "Amerykański ekonomista postkeynesowski; hipoteza niestabilności finansowej (finansowanie hedge, spekulacyjne, Ponziego).", {"k": ["minsk"]}),
 ("Mintzberg Henry", "Kanadyjski teoretyk zarządzania; role kierownicze (1973), konfiguracje struktur organizacyjnych, strategie emergentne.", {"k": ["mintzberg"]}),
 ("Mises Ludwig von", "Austriacki ekonomista; szkoła austriacka, problem kalkulacji w socjalizmie, prakseologia („Ludzkie działanie”, 1949).", {"k": ["mises"]}),
 ("Modigliani Franco, Miller Merton", "Modigliani (Nobel 1985) – hipoteza cyklu życia, twierdzenia Modiglianiego–Millera o strukturze kapitału (1958; Miller – Nobel 1990), współautor pojęcia NAIRU (z L. Papademosem, 1975).", {"k": ["modigliani", "miller"]}),
 ("Mundell Robert, Fleming Marcus", "Model Mundella–Fleminga (lata 60.), trylemat; Mundell – Nobel 1999, teoria optymalnych obszarów walutowych (1961), „ojciec euro”.", {"k": ["mundell", "fleming"]}),
 ("Musgrave Richard", "Amerykański ekonomista finansów publicznych; trzy funkcje finansów publicznych (alokacyjna, redystrybucyjna, stabilizacyjna).", {"k": ["musgrave"]}),
 ("Nash John", "Amerykański matematyk, Nobel z ekonomii 1994; równowaga Nasha w teorii gier.", {"k": ["nash"]}),
 ("Okun Arthur", "Amerykański ekonomista; prawo Okuna (1962), wskaźnik niedoli (inflacja + bezrobocie).", {"k": ["okun"]}),
 ("Pareto Vilfredo", "Włoski ekonomista i socjolog; optimum Pareto, zasada 80/20 (rozkład bogactwa).", {"k": ["pareto"]}),
 ("Phelps Edmund", "Amerykański ekonomista, Nobel 2006; naturalna stopa bezrobocia i krytyka krzywej Phillipsa (niezależnie od Friedmana).", {"k": ["phelps"]}),
 ("Phillips Alban William", "Ekonomista z Nowej Zelandii; krzywa Phillipsa (1958) – płace a bezrobocie w Wielkiej Brytanii 1861–1957.", {"k": ["phillips"]}),
 ("Pigou Arthur Cecil", "Brytyjski ekonomista; „Ekonomia dobrobytu” (1920), efekty zewnętrzne i podatek Pigou, efekt Pigou (realnych zasobów pieniężnych).", {"k": ["pigou"]}),
 ("Porter Michael E.", "Amerykański ekonomista (Harvard); pięć sił konkurencji, strategie ogólne, łańcuch wartości („Strategia konkurencji” 1980, „Przewaga konkurencyjna” 1985), diament przewagi narodów (1990), klastry.", {"k": ["porter"]}),
 ("Putnam Robert", "Amerykański politolog; kapitał społeczny wiążący i pomostowy („Samotna gra w kręgle”, 2000).", {"k": ["putnam"]}),
 ("Quesnay François", "Francuski lekarz i ekonomista, twórca fizjokratyzmu; „Tablica ekonomiczna” (1758).", {"k": ["quesnay"]}),
 ("Ricardo David", "Brytyjski ekonomista klasyczny; „Zasady ekonomii politycznej i opodatkowania” (1817) – przewaga komparatywna, renta gruntowa, ekwiwalencja ricardiańska.", {"k": ["ricardo"]}),
 ("Rodrik Dani", "Turecko-amerykański ekonomista; trylemat globalizacji, krytyka konsensusu waszyngtońskiego.", {"k": ["rodrik"]}),
 ("Samuelson Paul", "Amerykański ekonomista, Nobel 1970 (pierwszy amerykański laureat); synteza neoklasyczna, podręcznik „Ekonomia”, teoria dóbr publicznych.", {"k": ["samuelson"]}),
 ("Say Jean-Baptiste", "Francuski ekonomista klasyczny; prawo Saya („podaż tworzy własny popyt”), rola przedsiębiorcy.", {"k": ["say"]}),
 ("Schumpeter Joseph A.", "Austriacko-amerykański ekonomista; „Teoria rozwoju gospodarczego” (1911) – innowacje i przedsiębiorca, „Kapitalizm, socjalizm, demokracja” (1942) – twórcza destrukcja.", {"k": ["schumpeter"]}),
 ("Senge Peter", "Amerykański teoretyk zarządzania; organizacja ucząca się („Piąta dyscyplina”, 1990).", {"k": ["senge"]}),
 ("Sharpe William", "Amerykański ekonomista, Nobel 1990; model CAPM (1964), wskaźnik Sharpe’a.", {"k": ["sharpe"]}),
 ("Shiller Robert", "Amerykański ekonomista, Nobel 2013; finanse behawioralne, bańki spekulacyjne („Irracjonalny optymizm”), indeks cen nieruchomości Case–Shillera.", {"k": ["shiller"]}),
 ("Simon Herbert", "Amerykański ekonomista i psycholog, Nobel 1978; ograniczona racjonalność, model administracyjny decyzji.", {"k": ["simon"]}),
 ("Smith Adam", "Szkocki filozof i ekonomista (1723–1790), ojciec ekonomii klasycznej; „Badania nad naturą i przyczynami bogactwa narodów” (1776) – niewidzialna ręka rynku, podział pracy (przykład manufaktury szpilek), przewaga absolutna, zasady podatkowe.", {"k": ["smith"]}),
 ("Solow Robert", "Amerykański ekonomista, Nobel 1987; neoklasyczny model wzrostu (1956), paradoks produktywności.", {"k": ["solow"]}),
 ("Stiglitz Joseph", "Amerykański ekonomista, Nobel 2001; ekonomia informacji (odsiewanie), płace efektywnościowe (model Shapiro–Stiglitza), krytyka MFW i globalizacji.", {"k": ["stiglitz"]}),
 ("Tannenbaum Robert, Schmidt Warren H.", "Twórcy kontinuum zachowań przywódczych (1958).", {"k": ["tannenbaum", "schmidt"]}),
 ("Taylor Frederick Winslow", "Amerykański inżynier (1856–1915), ojciec naukowego zarządzania („Zasady naukowego zarządzania”, 1911); pomiar czasu, standaryzacja, akordowy system płac.", {"k": ["taylor f", "f.w. taylor", "frederick", "taylora"]}),
 ("Taylor John B.", "Amerykański ekonomista (Stanford); reguła Taylora (1993) dla polityki pieniężnej.", {"k": ["j. taylor", "john taylor", "reguł taylora", "reguła taylora"]}),
 ("Thaler Richard", "Amerykański ekonomista, Nobel 2017; ekonomia behawioralna – księgowość mentalna, efekt posiadania, teoria szturchania (z C. Sunsteinem, „Impuls”, 2008).", {"k": ["thaler"]}),
 ("Thompson James D.", "Amerykański socjolog organizacji; niepewność otoczenia (złożoność i dynamika), typy współzależności.", {"k": ["thompson"]}),
 ("Tobin James", "Amerykański ekonomista, Nobel 1981; q Tobina, podatek Tobina (1972), teoria portfela i popytu na pieniądz.", {"k": ["tobin"]}),
 ("Tuckman Bruce", "Amerykański psycholog; model faz rozwoju grupy (1965): formowanie, szturmowanie, normowanie, działanie (+ rozwiązanie, 1977).", {"k": ["tuckman"]}),
 ("Tversky Amos", "Izraelski psycholog (zm. 1996); z D. Kahnemanem teoria perspektywy i heurystyki.", {"k": ["tversky"]}),
 ("Urwick Lyndall", "Brytyjski teoretyk zarządzania administracyjnego; zasady organizacji (rozpiętość kierowania), z L. Gulickiem POSDCORB.", {"k": ["urwick"]}),
 ("Veblen Thorstein", "Amerykański ekonomista, twórca instytucjonalizmu; „Teoria klasy próżniaczej” (1899) – konsumpcja na pokaz, dobra Veblena.", {"k": ["veblen"]}),
 ("Vroom Victor", "Kanadyjsko-amerykański psycholog; teoria oczekiwań (1964), model decyzyjny Vrooma–Yettona(–Jago).", {"k": ["vroom"]}),
 ("Walras Léon", "Francuski ekonomista; teoria równowagi ogólnej (1874), współtwórca marginalizmu.", {"k": ["walras"]}),
 ("Weber Max", "Niemiecki socjolog (1864–1920); idealny typ biurokracji, „Etyka protestancka a duch kapitalizmu” (1905); zaliczany do twórców zarządzania administracyjnego.", {"k": ["weber"]}),
 ("Wicksell Knut", "Szwedzki ekonomista; naturalna stopa procentowa, proces kumulatywny (inflacja przy stopie rynkowej niższej od naturalnej).", {"k": ["wicksell"]}),
 ("Williamson John", "Brytyjski ekonomista; sformułował konsensus waszyngtoński (1989).", {"k": ["williamson"]}),
 ("Woodward Joan", "Brytyjska socjolog; badania wpływu technologii (jednostkowej, masowej, ciągłej) na strukturę organizacji – podejście sytuacyjne.", {"k": ["woodward"]}),
 ('Ford Henry', 'Amerykański przemysłowiec; w 1913 r. wprowadził ruchomą linię montażową (Model T) – symbol masowej produkcji i II rewolucji przemysłowej.', {'k': ['ford']}),
 ('Gesell Silvio', 'Niemiecko-argentyński ekonomista; koncepcja „pieniądza zanikającego” (opodatkowanego za przechowywanie) przyspieszającego obieg.', {'k': ['gesell']}),
 ('Hildebrand Bruno', 'Niemiecki ekonomista starszej szkoły historycznej (XIX w.) – periodyzacja gospodarki: naturalna, pieniężna, kredytowa.', {'k': ['hildebrand']}),
 ('Hume David', 'Szkocki filozof i ekonomista (XVIII w.); mechanizm przepływu kruszców i cen (samoregulacja bilansu handlowego), ilościowa teoria pieniądza.', {'k': ['hume']}),
 ('Maskin Eric', 'Amerykański ekonomista, Nobel 2007 (z L. Hurwiczem i R. Myersonem) za teorię projektowania mechanizmów.', {'k': ['maskin']}),
 ('Milgrom Paul', 'Amerykański ekonomista, Nobel 2020 (z R. Wilsonem) za teorię aukcji i nowe formaty aukcji.', {'k': ['milgrom']}),
 ('Owen Robert', 'Walijski przedsiębiorca i socjalista utopijny (XIX w.); reformy warunków pracy, spółdzielczość (New Lanark).', {'k': ['owen']}),
 ('Watt James', 'Szkocki wynalazca; ulepszona maszyna parowa (patent 1769) – symbol I rewolucji przemysłowej.', {'k': ['watt']}),
 ('Axelrod Robert', 'Amerykański politolog; badania nad ewolucją współpracy – turnieje dylematu więźnia i strategia „wet za wet” (1984).', {'k': ['axelrod']}),
 ('Bain Joe', 'Amerykański ekonomista, współtwórca ekonomii przemysłowej (Industrial Organization) i paradygmatu struktura–zachowanie–wyniki; badania barier wejścia.', {'k': ['bain']}),
 ('Belka Marek', 'Polski ekonomista; minister finansów (1997, 2001–2002), premier 2004–2005, prezes NBP 2010–2016.', {'k': ['belka', 'belki']}),
 ('Buchanan James', 'Amerykański ekonomista, Nobel 1986 – twórca teorii wyboru publicznego (z G. Tullockiem). W pracy z 1949 r. przeciwstawił organiczną (państwo jako odrębny organizm z własnymi celami) i indywidualistyczną (państwo jako wyraz woli jednostek) teorię finansów publicznych.', {'k': ['buchanan', 'organiczn', 'indywidualistyczn']}),
 ('Downs Anthony', 'Amerykański ekonomista; „Ekonomiczna teoria demokracji” (1957).', {'k': ['downs']}),
 ('Dunning John', 'Brytyjski ekonomista (Uniwersytet w Reading); paradygmat eklektyczny OLI bezpośrednich inwestycji zagranicznych.', {'k': ['dunning']}),
 ('Frank Robert', 'Amerykański ekonomista (Cornell); dobra pozycyjne i „wyścig zbrojeń” w konsumpcji, „Ekonomia Darwina”.', {'k': ['frank r', 'robert frank']}),
 ('Glapiński Adam', 'Polski ekonomista; członek RPP 2010–2016, prezes NBP od 2016 r.', {'k': ['glapiński']}),
 ('Gomułka Stanisław', 'Polski ekonomista (1940–2026); LSE, teoria wzrostu i innowacji, doradca ministrów finansów od 1989 r., negocjator z MFW i wierzycielami, wiceminister finansów w 2008 r.', {'k': ['gomułk']}),
 ('Gorynia Marian', 'Polski ekonomista; rektor Uniwersytetu Ekonomicznego w Poznaniu 2008–2016; konkurencyjność przedsiębiorstw, biznes międzynarodowy, mezoekonomia.', {'k': ['gorynia', 'goryni']}),
 ('Hofstede Geert', 'Holenderski psycholog społeczny; wymiary kultur narodowych (dystans władzy, indywidualizm–kolektywizm, męskość–kobiecość, unikanie niepewności, orientacja długoterminowa).', {'k': ['hofstede']}),
 ('Kuhn Thomas', 'Amerykański filozof nauki; „Struktura rewolucji naukowych” (1962) – paradygmat i rewolucje naukowe.', {'k': ['kuhn']}),
 ('Kwiatkowski Eugeniusz (1888–1974)', 'Wicepremier i minister skarbu II RP (1935–1939), wcześniej minister przemysłu i handlu; budowa Gdyni i Centralnego Okręgu Przemysłowego.', {'k': ['kwiatkowsk']}),
 ('Łaski Kazimierz', 'Polsko-austriacki ekonomista (1921–2015), uczeń M. Kaleckiego, postkeynesista; Linz, wiiw w Wiedniu.', {'k': ['łask']}),
 ('Nowak Leszek', 'Polski filozof (1943–2009), poznańska szkoła metodologiczna – idealizacyjna teoria nauki.', {'k': ['nowak']}),
 ('Osiatyński Jerzy', 'Polski ekonomista (1941–2022); minister–kierownik Centralnego Urzędu Planowania (1989–1991), minister finansów 1992–1993, członek RPP 2013–2019, wydawca dzieł M. Kaleckiego.', {'k': ['osiatyński']}),
 ('Popper Karl', 'Austriacko-brytyjski filozof nauki; kryterium falsyfikowalności („Logika odkrycia naukowego”, 1934), „Społeczeństwo otwarte i jego wrogowie”.', {'k': ['popper']}),
 ('Posner Michael', 'Brytyjski ekonomista; hipoteza luki technologicznej w handlu międzynarodowym (1961).', {'k': ['posner']}),
 ('Rosen Sherwin', 'Amerykański ekonomista; „Ekonomia supergwiazd” (1981).', {'k': ['rosen s', 'sherwin']}),
 ('Sadowski Zdzisław', 'Polski ekonomista (1925–2018); wicepremier ds. reformy gospodarczej 1987–1988, wieloletni prezes Polskiego Towarzystwa Ekonomicznego (od 1985 r.).', {'k': ['sadowsk']}),
 ('Williamson Oliver', 'Amerykański ekonomista, Nobel 2009 (z E. Ostrom); nowa ekonomia instytucjonalna – ekonomia kosztów transakcyjnych, granice firmy, oportunizm.', {'k': ['oliver williamson', 'o. williamson']}),
 ('Slutsky Eugen (Jewgienij Słucki)', 'Rosyjski ekonomista i statystyk; równanie Slutsky’ego (1915) – rozkład skutku zmiany ceny na efekt substytucyjny i dochodowy.', {'k': ['slutsk', 'słucki']}),
 ('Stackelberg Heinrich von', 'Niemiecki ekonomista; model duopolu z liderem i naśladowcą (1934).', {'k': ['stackelberg']}),
 ('Herfindahl Orris, Hirschman Albert O.', 'Twórcy wskaźnika koncentracji – sumy kwadratów udziałów rynkowych (Hirschman 1945, Herfindahl 1950); Hirschman znany też z koncepcji „exit, voice and loyalty” i niezrównoważonego wzrostu.', {'k': ['herfindahl', 'hirschman']}),
 ('Lerner Abba', 'Ekonomista urodzony w Besarabii, działał w Wielkiej Brytanii i USA; wskaźnik siły monopolowej (1934), warunek Marshalla–Lernera, koncepcja „finansów funkcjonalnych”.', {'k': ['lerner']}),
 ('Baumol William', 'Amerykański ekonomista; teoria rynków kontestowalnych (1982), model maksymalizacji utargu, choroba kosztów Baumola (usługi), model popytu na gotówkę Baumola–Tobina.', {'k': ['baumol']}),
 ('Stigler George', 'Amerykański ekonomista szkoły chicagowskiej, Nobel 1982; ekonomia informacji (poszukiwanie cen) i teoria przejęcia regulacyjnego (1971).', {'k': ['stigler']}),
 ('Cyert Richard, March James', 'Twórcy behawioralnej teorii przedsiębiorstwa (1963) – firma jako koalicja grup dążąca do celów satysfakcjonujących.', {'k': ['cyert']}),
 ('Leibenstein Harvey', 'Amerykański ekonomista; X-nieefektywność (1966), efekty owczego pędu (bandwagon) i snobizmu w popycie.', {'k': ['leibenstein']}),
 ('Knight Frank', 'Amerykański ekonomista, współtwórca szkoły chicagowskiej; „Risk, Uncertainty and Profit” (1921) – rozróżnienie ryzyka i niepewności, zysk jako nagroda za niepewność.', {'k': ['knight']}),
 ('Nordhaus William', 'Amerykański ekonomista, Nobel 2018 (ekonomia zmian klimatu); model politycznego cyklu koniunkturalnego (1975), współautor podręcznika „Ekonomia” z P. Samuelsonem.', {'k': ['nordhaus']}),
 ('Myers Stewart', 'Amerykański ekonomista finansowy; teoria hierarchii źródeł finansowania (pecking order, z N. Majlufem 1984).', {'k': ['myers', 'pecking']}),
 ('Gordon Myron J.', 'Amerykański ekonomista; model wyceny akcji o stałym wzroście dywidend (model Gordona, 1959/1962).', {'k': ['gordon']}),
 ('Altman Edward', 'Amerykański profesor finansów; model Z-score przewidywania upadłości przedsiębiorstw (1968).', {'k': ['altman']}),
 ('Kim W. Chan, Mauborgne Renée', 'Profesorowie INSEAD; „Strategia błękitnego oceanu” (2005).', {'k': ['mauborgne', 'błękitn']}),
 ('Belbin R. Meredith', 'Brytyjski badacz zespołów; 9 ról zespołowych („Management Teams”, 1981).', {'k': ['belbin']}),
 ('Ries Eric', 'Amerykański przedsiębiorca; „Lean Startup” (2011) – MVP, cykl zbuduj–zmierz–ucz się, pivot.', {'k': ['ries']}),
 ('Freeman R. Edward', 'Amerykański filozof biznesu; teoria interesariuszy („Strategic Management: A Stakeholder Approach”, 1984).', {'k': ['freeman', 'interesariusz']}),
 ('Johanson Jan, Vahlne Jan-Erik', 'Szwedzcy badacze z Uppsali; model stopniowej internacjonalizacji przedsiębiorstwa (1977).', {'k': ['uppsal', 'johanson']}),
 ('Mazowiecki Tadeusz', 'Pierwszy niekomunistyczny premier po 1989 r. (wrzesień 1989 – styczeń 1991); jego rząd wprowadził plan Balcerowicza.', {'k': ['mazowieck']}),
 ('Goodhart Charles', 'Brytyjski ekonomista (LSE), członek Komitetu Polityki Pieniężnej Banku Anglii 1997–2000; prawo Goodharta (wskaźnik, który staje się celem polityki, przestaje być dobrą miarą); współautor „Wielkiego zwrotu demograficznego” (2020, z M. Pradhanem).', {'k': ['goodhart']}),
 ('Pradhan Manoj', 'Ekonomista, były analityk Morgan Stanley, założyciel firmy badawczej Talking Heads Macro; współautor „Wielkiego zwrotu demograficznego” z C. Goodhartem.', {'k': ['pradhan']}),
 ('Barr Nicholas', 'Brytyjski ekonomista (LSE), specjalista od ekonomii państwa dobrobytu i systemów emerytalnych; z P. Diamondem „Reforming Pensions” (2008) i „Pension Reform: A Short Guide” (2010; wyd. pol. PTE 2014).', {'k': ['barr']}),
 ('Diamond Peter', 'Amerykański ekonomista (MIT), Nobel 2010 (z D. Mortensenem i C. Pissaridesem) za analizę rynków z tarciami (poszukiwania pracy); autorytet w dziedzinie systemów emerytalnych i podatków; model pokoleń nakładających się z długiem publicznym (1965). Nie mylić z Douglasem Diamondem.', {'k': ['peter diamond', 'p. diamond']}),
 ('Becker Gary', 'Amerykański ekonomista szkoły chicagowskiej, Nobel 1992; teoria kapitału ludzkiego, ekonomiczna analiza rodziny, płodności (ilość i jakość dzieci), dyskryminacji i przestępczości.', {'k': ['becker']}),
 ('Easterlin Richard', 'Amerykański ekonomista i demograf; hipoteza względnego dochodu w dzietności (fale wyżów i niżów) oraz paradoks Easterlina (1974) – szczęście a dochód.', {'k': ['easterlin']}),
 ('Notestein Frank', 'Amerykański demograf (Princeton); sformułował teorię przejścia demograficznego (1945).', {'k': ['notestein']}),
 ('van de Kaa Dirk, Lesthaeghe Ron', 'Demografowie holenderski i belgijski; koncepcja drugiego przejścia demograficznego (1986).', {'k': ['van de kaa', 'lesthaeghe']}),
 ('Lee Everett', 'Amerykański demograf; teoria migracji oparta na czynnikach wypychających i przyciągających (1966).', {'k': ['everett lee', 'e. lee']}),
 ('Ravenstein Ernst Georg', 'Geograf niemiecko-brytyjski; „prawa migracji” (1885–1889).', {'k': ['ravenstein']}),
 ('Stark Oded', 'Izraelski ekonomista; nowa ekonomia migracji zarobkowych (z D. Bloomem, 1985), deprywacja względna, „korzystny drenaż mózgów”.', {'k': ['stark']}),
 ('Piore Michael', 'Amerykański ekonomista (MIT); teoria dualnego (segmentowego) rynku pracy i „Birds of Passage” (1979) o migrantach zarobkowych.', {'k': ['piore']}),
 ('Todaro Michael', 'Amerykański ekonomista rozwoju; model Harrisa–Todaro (1970) – migracje ze wsi do miast zależą od oczekiwanego dochodu mimo bezrobocia w miastach.', {'k': ['todaro']}),
 ('Lewis W. Arthur', 'Ekonomista z Saint Lucia, Nobel 1979 (z T. Schultzem); model gospodarki dualnej z nieograniczoną podażą pracy (1954) i punkt zwrotny Lewisa.', {'k': ['lewis']}),
 ('Aaron Henry', 'Amerykański ekonomista (Brookings); warunek Aarona (1966) dotyczący efektywności systemu repartycyjnego.', {'k': ['aaron']}),
 ('Kotlikoff Laurence', 'Amerykański ekonomista; współtwórca rachunkowości pokoleniowej (z A. Auerbachem i J. Gokhale, 1991).', {'k': ['kotlikoff']}),
 ('Hansen Alvin', 'Amerykański ekonomista keynesowski („amerykański Keynes”); hipoteza sekularnej stagnacji (1938), model IS-LM Hicksa–Hansena.', {'k': ['hansen']}),
 ('Summers Lawrence', 'Amerykański ekonomista (Harvard), sekretarz skarbu USA 1999–2001; przywrócił pojęcie sekularnej stagnacji (2013).', {'k': ['summers']}),
 ('Okólski Marek', 'Polski demograf i ekonomista (UW), twórca Ośrodka Badań nad Migracjami UW; badacz migracji i przemian ludnościowych w Polsce (koncepcja niedokończonego przejścia migracyjnego); współautor podręcznika „Demografia” (z A. Fihel).', {'k': ['okólski']}),
 ('Fihel Agnieszka', 'Polska demografka (UW, Ośrodek Badań nad Migracjami); badaczka umieralności, migracji i starzenia się; współautorka „Demografii” (z M. Okólskim).', {'k': ['fihel']}),
 ('Robertson Dennis', 'Brytyjski ekonomista (Cambridge); teoria funduszy pożyczkowych (stopa procentowa kształtowana przez podaż i popyt na fundusze pożyczkowe); autor terminu „pułapka płynności” (1940), opisującego zjawisko analizowane przez Keynesa.', {'k': ['robertson']}),
 ('Clark John Bates', 'Amerykański ekonomista marginalista; teoria krańcowej produktywności jako teoria podziału („The Distribution of Wealth”, 1899).', {'k': ['clark']}),
 ('Rawls John', 'Amerykański filozof; „Teoria sprawiedliwości” (1971) – sprawiedliwość jako bezstronność, zasłona niewiedzy, zasada różnicy (maximin).', {'k': ['rawls']}),
 ('Nozick Robert', 'Amerykański filozof; „Anarchia, państwo, utopia” (1974) – libertarianizm, państwo minimalne, uprawnieniowa teoria sprawiedliwości.', {'k': ['nozick']}),
 ('Bentham Jeremy', 'Angielski filozof i prawnik; twórca utylitaryzmu – „największe szczęście największej liczby ludzi”.', {'k': ['bentham']}),
 ('Jevons William Stanley', 'Angielski ekonomista, współtwórca rewolucji marginalistycznej („Teoria ekonomii politycznej”, 1871); teoria plam słonecznych jako przyczyny cykli (przez wpływ na plony); paradoks Jevonsa (wzrost efektywności zużycia zasobu może zwiększać jego łączne zużycie).', {'k': ['jevons']}),
 ('Barro Robert', 'Amerykański ekonomista (Harvard), przedstawiciel nowej ekonomii klasycznej; ekwiwalencja ricardiańska (1974), badania wzrostu gospodarczego (konwergencja).', {'k': ['barro']}),
 ('Arrow Kenneth', 'Amerykański ekonomista, Nobel 1972 (z J. Hicksem); twierdzenie Arrowa o niemożliwości (brak idealnej reguły agregacji preferencji społecznych), twierdzenia ekonomii dobrobytu (model Arrowa–Debreu), ekonomia informacji i ryzyka.', {'k': ['arrow']}),
 ("Card David, Krueger Alan", "Ekonomiści pracy (Kanada/USA). Badanie z 1994 r. porównujące bary szybkiej obsługi w New Jersey (gdzie w 1992 r. podniesiono płacę minimalną) i sąsiedniej Pensylwanii nie wykazało spadku zatrudnienia – zapoczątkowało nową ekonomię płacy minimalnej; książka „Mit i pomiar” (1995, wyd. pol. PTE 2023 – literatura OWE). D. Card – Nobel 2021 za empiryczny wkład w ekonomię pracy.", {"k": ["card", "krueger"]}),
 ("Chamberlin Edward, Robinson Joan", "Twórcy teorii konkurencji niedoskonałej (1933): E. Chamberlin (USA) – „Teoria konkurencji monopolistycznej” (zróżnicowanie produktu, reklama, marka); J. Robinson (Wielka Brytania) – „Ekonomia konkurencji niedoskonałej”, wprowadziła pojęcie monopsonu; później czołowa postkeynesistka.", {"k": ["chamberlin", "robinson"]}),
 ("Neumann John von, Morgenstern Oskar", "Matematyk i ekonomista, autorzy „Teorii gier i zachowań ekonomicznych” (1944) – dzieła, od którego datuje się teoria gier; wprowadzili m.in. gry o sumie zerowej i teorię oczekiwanej użyteczności.", {"k": ["neumann", "morgenstern"]}),
 ("Ostrom Elinor", "Amerykańska politolożka i ekonomistka, Nobel 2009 (z O. Williamsonem) za analizę zarządzania gospodarczego, zwłaszcza dobrami wspólnymi – pierwsza kobieta z tą nagrodą; pokazała, że społeczności potrafią samodzielnie chronić zasoby wspólne przed „tragedią wspólnego pastwiska” („Governing the Commons”, 1990).", {"k": ["ostrom"]}),
 ("Spence Michael", "Amerykański ekonomista, Nobel 2001 (z G. Akerlofem i J. Stiglitzem) za analizę rynków z asymetrią informacji; model sygnalizacji na rynku pracy („Job Market Signaling”, 1973) – wykształcenie jako sygnał zdolności.", {"k": ["spence"]}),
 ("Romer Paul", "Amerykański ekonomista, Nobel 2018 (z W. Nordhausem) za włączenie innowacji technologicznych do długookresowej analizy makroekonomicznej; twórca endogenicznej teorii wzrostu (wiedza jako dobro nierywalizacyjne); były główny ekonomista Banku Światowego.", {"k": ["romer"]}),
 ("Acemoglu Daron, Johnson Simon, Robinson James", "Ekonomiści, Nobel 2024 za badania nad tym, jak powstają instytucje i jak wpływają na dobrobyt; instytucje włączające (inkluzywne) sprzyjają wzrostowi, a wyzyskujące (ekstrakcyjne) go hamują („Dlaczego narody przegrywają”, 2012).", {"k": ["acemoglu"]}),
 ("Mortensen Dale, Pissarides Christopher", "Ekonomiści pracy, Nobel 2010 (z P. Diamondem) za analizę rynków z frykcjami poszukiwań – model DMP wyjaśnia współistnienie bezrobocia i wolnych miejsc pracy oraz wpływ zasiłków na czas poszukiwania pracy.", {"k": ["mortensen", "pissarides"]}),
 ("Law John", "Szkocki finansista i ekonomista działający we Francji; założył bank emitujący banknoty (1716) i Kompanię Missisipi, której akcje wymieniano na dług państwa („system Lawa”); po pęknięciu bańki w 1720 r. uciekł z Francji. Wczesny teoretyk pieniądza papierowego.", {"k": ["law"]}),
]
TABLES = [
 ("Nagrody Nobla z ekonomii przywoływane w pytaniach", ["Rok", "Laureaci", "Za co (skrót)"], [
   ["1970", "P. Samuelson", "teoria ekonomii, synteza neoklasyczna"],
   ["1971", "S. Kuznets", "wzrost gospodarczy, rachunki narodowe"],
   ["1972", "J. Hicks, K. Arrow", "równowaga ogólna i dobrobyt"],
   ["1974", "F. von Hayek, G. Myrdal", "teoria pieniądza i wahań, współzależności"],
   ["1976", "M. Friedman", "konsumpcja, historia pieniądza, polityka stabilizacyjna"],
   ["1978", "H. Simon", "proces podejmowania decyzji w organizacjach"],
   ["1981", "J. Tobin", "rynki finansowe a decyzje wydatkowe"],
   ["1985", "F. Modigliani", "oszczędności i rynki finansowe"],
   ["1987", "R. Solow", "teoria wzrostu gospodarczego"],
   ["1990", "H. Markowitz, M. Miller, W. Sharpe", "teoria finansów"],
   ["1991", "R. Coase", "koszty transakcyjne i prawa własności"],
   ["1994", "J. Nash, J. Harsanyi, R. Selten", "teoria gier"],
   ["1995", "R. Lucas", "racjonalne oczekiwania"],
   ["1997", "R. Merton, M. Scholes", "wycena instrumentów pochodnych"],
   ["1999", "R. Mundell", "polityka w różnych systemach kursowych, optymalne obszary walutowe"],
   ["2001", "G. Akerlof, M. Spence, J. Stiglitz", "rynki z asymetrią informacji"],
   ["2002", "D. Kahneman, V. Smith", "psychologia i ekonomia eksperymentalna"],
   ["2004", "F. Kydland, E. Prescott", "realny cykl koniunkturalny, spójność czasowa"],
   ["2006", "E. Phelps", "inflacja a bezrobocie w czasie"],
   ["2008", "P. Krugman", "wzorce handlu i lokalizacja działalności"],
   ["2013", "E. Fama, L.P. Hansen, R. Shiller", "wycena aktywów"],
   ["2017", "R. Thaler", "ekonomia behawioralna"],
   ["2020", "P. Milgrom, R. Wilson", "teoria aukcji"],
   ["2022", "B. Bernanke, D. Diamond, P. Dybvig", "banki i kryzysy finansowe"],
   ["2023", "C. Goldin", "kobiety na rynku pracy"],
   ["2024", "D. Acemoglu, S. Johnson, J. Robinson", "instytucje a dobrobyt narodów"],
   ["2025", "J. Mokyr, P. Aghion, P. Howitt", "wzrost napędzany innowacjami"],
 ]),
]
