# -*- coding: utf-8 -*-
TITLE = "Instytucje"
INTRO = "Polskie, unijne i międzynarodowe instytucje występujące w pytaniach – czym się zajmują. Szerzej opisane instytucje mają także hasła w działach 3–6."
E = [
 ('Biura informacji gospodarczej (BIG)', 'Rejestry dłużników (np. KRD, ERIF, BIG InfoMonitor) gromadzące informacje o zaległych zobowiązaniach.', {'k': ['informacji gospodarczej', 'big infomonitor', 'krd']}),
 ('Główny Urząd Statystyczny (GUS)', 'Centralny organ statystyki publicznej: PKB, inflacja (CPI), bezrobocie (BAEL), spisy powszechne (ostatni – NSP 2021).', {'k': ['gus', 'główny urząd statystyczn', 'głównego urzędu statystyczn']}),
 ('Komisja Nadzoru Finansowego (KNF)', 'Organ nadzoru nad rynkiem finansowym (od 2006 r. kapitałowy i ubezpieczeniowy, od 2008 r. także bankowy): banki, SKOK-i, ubezpieczyciele, fundusze, rynek kapitałowy; zatwierdza prospekty emisyjne. Zastąpiła m.in. Komisję Papierów Wartościowych i Giełd oraz Komisję Nadzoru Bankowego.', {'k': ['knf', 'komisja nadzoru finansowego', 'komisji nadzoru finansowego', 'komisja papierów wartościowych']}),
 ('Komitet Stabilności Finansowej (KSF)', 'Organ makroostrożnościowy (od 2015 r.): przewodniczący – Prezes NBP; członkowie – Minister Finansów, Przewodniczący KNF, Prezes Zarządu BFG.', {'k': ['komitet stabilności finansowej', 'komitetu stabilności finansowej', 'ksf']}),
 ('Krajowa Izba Rozliczeniowa (KIR)', 'Operator systemów rozliczeń międzybankowych Elixir i Express Elixir.', {'k': ['kir', 'krajowa izba rozliczeniowa']}),
 ('Kasa Rolniczego Ubezpieczenia Społecznego (KRUS)', 'Ubezpieczenie społeczne rolników (emerytury, renty, świadczenia), finansowane głównie z dotacji budżetowych.', {'k': ['krus']}),
 ('Ministerstwo Finansów (MF)', 'Przygotowuje budżet, zarządza długiem publicznym (emisja obligacji skarbowych), polityka podatkowa; Minister Finansów nadzoruje KAS.', {'k': ['ministerstw finansów', 'ministerstwo finansów', 'minister finansów', 'ministra finansów']}),
 ('Polska Agencja Rozwoju Przedsiębiorczości (PARP)', 'Agencja wspierająca rozwój MŚP i innowacyjność, wdraża programy unijne.', {'k': ['parp']}),
 ('Polski Fundusz Rozwoju (PFR)', 'Grupa instytucji finansowych państwa wspierających inwestycje i rozwój; zarządza PPK (portal mojePPK), Tarcza Finansowa PFR (2020).', {'k': ['pfr', 'polski fundusz rozwoju']}),
 ('Rzecznik Małych i Średnich Przedsiębiorców', 'Organ (od 2018 r.) stojący na straży praw przedsiębiorców w relacjach z administracją.', {'k': ['rzecznik małych', 'rzecznik mśp']}),
 ('Urząd Patentowy RP', 'Udziela patentów, praw ochronnych na wzory użytkowe i znaki towarowe, praw z rejestracji wzorów przemysłowych.', {'k': ['urząd patentow', 'urzędu patentow']}),
 ('Związek Banków Polskich (ZBP)', 'Samorząd gospodarczy banków (od 1991 r.); założyciel BIK.', {'k': ['zbp', 'związek banków polskich']}),
 ('Rada Ministrów', 'Rząd RP; opracowuje projekt ustawy budżetowej (przedkłada Sejmowi do 30 września) i wykonuje budżet; Prezydent może skierować ustawę budżetową do Trybunału Konstytucyjnego, który orzeka w ciągu 2 miesięcy.', {'k': ['trybunał konstytucyjn', 'rada ministrów', 'rady ministrów']}),
 ('Europejski System Banków Centralnych (ESBC)', 'EBC i banki centralne wszystkich państw UE (w tym NBP); Eurosystem – EBC i banki centralne strefy euro.', {'k': ['esbc', 'europejski system banków']}),
 ('Komisja Europejska', 'Organ wykonawczy UE z prawem inicjatywy ustawodawczej; nadzoruje przestrzeganie traktatów i reguł fiskalnych, prowadzi politykę konkurencji i handlową UE.', {'k': ['komisj europejsk', 'komisja europejska']}),
 ('Rada Unii Europejskiej i Rada Europejska', 'Rada UE (Rada ministrów) – współprawodawca z Parlamentem, decyduje m.in. o procedurze nadmiernego deficytu (ECOFIN); Rada Europejska – szefowie państw i rządów, wytyczne polityczne.', {'k': ['rada ue', 'rady ue', 'rada unii', 'rada europejsk', 'ecofin']}),
 ('Parlament Europejski', 'Organ UE wybierany w wyborach bezpośrednich (co 5 lat); współprawodawca i władza budżetowa.', {'k': ['parlament europejsk', 'parlamentu europejsk', 'parlament ue']}),
 ('Europejski Urząd Statystyczny (Eurostat)', 'Urząd statystyczny UE: HICP, dane o deficycie i długu (EDP), PKB wg PPS.', {'k': ['eurostat']}),
 ('Europejskie urzędy nadzoru (EBA, ESMA, EIOPA)', 'EBA – bankowy, ESMA – giełd i papierów wartościowych, EIOPA – ubezpieczeń i pracowniczych programów emerytalnych; ESRB – Europejska Rada ds. Ryzyka Systemowego.', {'k': ['eba', 'esma', 'eiopa', 'esrb']}),
 ('Europejski Mechanizm Stabilności (EMS)', 'Fundusz ratunkowy strefy euro (od 2012 r.) udzielający pomocy państwom w trudnościach (zastąpił EFSF).', {'k': ['europejski mechanizm stabilności', 'efsf']}),
 ('System Rezerwy Federalnej (Fed)', 'Bank centralny USA (od 1913 r.), Federalny Komitet Otwartego Rynku (FOMC) ustala stopę federal funds.', {'k': ['fed', 'fomc']}),
 ('Bank Japonii i Bank Ludowy Chin', 'Banki centralne Japonii (QE od 2001 r., ujemne stopy 2016–2024) i Chin (cyfrowy juan e-CNY).', {'k': ['bank japonii', 'banku japonii', 'bank ludowy']}),
 ('Międzynarodowa Organizacja Pracy (MOP)', 'Agenda ONZ (od 1919 r.) ustalająca standardy pracy; definicja bezrobotnego stosowana w BAEL.', {'k': ['mop', 'międzynarodowa organizacja pracy']}),
 ('Światowe Forum Ekonomiczne (WEF)', 'Fundacja organizująca forum w Davos; raporty o konkurencyjności; K. Schwab spopularyzował pojęcie czwartej rewolucji przemysłowej.', {'k': ['davos', 'światowe forum ekonomiczne', 'schwab']}),
 ('Agencje ratingowe', 'Standard & Poor’s, Moody’s, Fitch – oceniają wiarygodność kredytową państw i firm.', {'k': ['agencj ratingow', 'agencje ratingowe', 'moody', 'fitch']}),
 ('Klub Paryski', 'Nieformalna grupa państw-wierzycieli; redukcja polskiego długu o 50% (1991).', {'k': ['klub paryski']}),
 ('Sądy gospodarcze', 'Wydziały gospodarcze sądów rejonowych i okręgowych; m.in. prowadzą Krajowy Rejestr Sądowy i postępowania upadłościowe.', {'k': ['sąd gospodarcz', 'sądy gospodarcz', 'sądu gospodarcz']}),
 ('Europejska Rada ds. Ryzyka Systemowego (ESRB)', 'Organ UE nadzoru makroostrożnościowego, działający od 16.12.2010 r. (rozporządzenie 1092/2010), z siedzibą we Frankfurcie; identyfikuje ryzyka systemowe, wydaje ostrzeżenia i zalecenia; wsparcie analityczne zapewnia EBC. Część Europejskiego Systemu Nadzoru Finansowego obok EBA, ESMA i EIOPA.', {'k': ['esrb', 'ryzyka systemowego']}),
 ('Rada Stabilności Finansowej (FSB)', 'Międzynarodowe ciało koordynujące regulacje finansowe (siedziba w Bazylei, przy BIS). Powstała w kwietniu 2009 r. (szczyt G20 w Londynie) z przekształcenia Forum Stabilności Finansowej (FSF), utworzonego w 1999 r. przez kraje G7 po kryzysie azjatyckim; członkowie – kraje G20, UE i instytucje międzynarodowe.', {'k': ['fsb', 'forum stabilności finansowej', 'rada stabilności finansowej']}),
]
TABLES = [('Instytucje opisane w działach tematycznych (bez powtarzania haseł)',
  ['Instytucja', 'Gdzie szukać'],
  [['Bank Anglii', 'dział 3. Pieniądz, banki i polityka pieniężna'],
   ['Bank Gospodarstwa Krajowego (BGK)', 'dział 3. Pieniądz, banki i polityka pieniężna'],
   ['Bank Rozrachunków Międzynarodowych (BIS)', 'dział 6. Gospodarka światowa, handel międzynarodowy i Unia Europejska'],
   ['Bank Światowy', 'dział 6. Gospodarka światowa, handel międzynarodowy i Unia Europejska'],
   ['Bankowy Fundusz Gwarancyjny (BFG)', 'dział 3. Pieniądz, banki i polityka pieniężna'],
   ['Biuro Informacji Kredytowej (BIK)', 'dział 3. Pieniądz, banki i polityka pieniężna'],
   ['Europejski Bank Centralny (EBC)', 'dział 3. Pieniądz, banki i polityka pieniężna'],
   ['Europejski Bank Inwestycyjny (EBI)', 'dział 6. Gospodarka światowa, handel międzynarodowy i Unia Europejska'],
   ['Europejski Bank Odbudowy i Rozwoju (EBOiR)', 'dział 6. Gospodarka światowa, handel międzynarodowy i Unia Europejska'],
   ['Giełda Papierów Wartościowych w Warszawie (GPW)', 'dział 4. Rynek finansowy, kapitałowy i ubezpieczenia'],
   ['Krajowa Administracja Skarbowa (KAS)', 'dział 5. Finanse publiczne, podatki i zabezpieczenie społeczne'],
   ['Krajowy Depozyt Papierów Wartościowych (KDPW)', 'dział 4. Rynek finansowy, kapitałowy i ubezpieczenia'],
   ['Międzynarodowy Fundusz Walutowy (MFW)', 'dział 6. Gospodarka światowa, handel międzynarodowy i Unia Europejska'],
   ['Najwyższa Izba Kontroli (NIK)', 'dział 5. Finanse publiczne, podatki i zabezpieczenie społeczne'],
   ['Narodowy Bank Polski (NBP)', 'dział 3. Pieniądz, banki i polityka pieniężna'],
   ['Narodowy Fundusz Zdrowia (NFZ)', 'dział 5. Finanse publiczne, podatki i zabezpieczenie społeczne'],
   ['OECD', 'dział 6. Gospodarka światowa, handel międzynarodowy i Unia Europejska'],
   ['OPEC', 'dział 6. Gospodarka światowa, handel międzynarodowy i Unia Europejska'],
   ['Rada Polityki Pieniężnej (RPP)', 'dział 3. Pieniądz, banki i polityka pieniężna'],
   ['Regionalne izby obrachunkowe (RIO)', 'dział 5. Finanse publiczne, podatki i zabezpieczenie społeczne'],
   ['Rzecznik Finansowy', 'dział 4. Rynek finansowy, kapitałowy i ubezpieczenia'],
   ['Ubezpieczeniowy Fundusz Gwarancyjny (UFG)', 'dział 4. Rynek finansowy, kapitałowy i ubezpieczenia'],
   ['Zakład Ubezpieczeń Społecznych (ZUS)', 'dział 5. Finanse publiczne, podatki i zabezpieczenie społeczne (hasło: Ubezpieczenia społeczne)'],
  ['Urząd Ochrony Konkurencji i Konsumentów (UOKiK)', 'dział 7. Rachunkowość, finanse przedsiębiorstwa i prawo gospodarcze'],
   ['Światowa Organizacja Handlu (WTO)', 'dział 6. Gospodarka światowa, handel międzynarodowy i Unia Europejska']])]
